### ISSUE TITLE
Use size_t for sizes

### ISSUE THREAD

**Issue by c0nk** [google/protobuf#1004]
Protobuf uses 'int' for size values. For example:
```bool ParsePartialFromArray(const void* data, int size)```
This is an issue for objects larger than 2GB. Can this be fixed for 3.x release?

**Comment by xfxyjwf** [comment]
We have no plan to make protobuf support objects larger than 2GB. All our existing implementations assume the size can be represented by an int. It's difficult to change and may have a negative performance impact. On the other hand, the general recommendation is to avoid having large protobuf messages. These messages can take a lot more memory than you think after parsed. It's not uncommon to see a 100MB message on the wire takes more than 4GB memory and causes OOM exceptions when parsing.

**Comment by c0nk** [comment]
Related to the use of int are a lot of warnings when compiling code that uses protobuf. For example, things like:
```
inline void CodedInputStream::GetDirectBufferPointerInline(const void** data,
                                                           int* size) {
  *data = buffer_;
  *size = buffer_end_ - buffer_;
}
```
Gives an implicit integer conversion warning. There are many cases of this in protobuf headers and C++ code generated by the protobuf compiler. What about adding some static_casts for these?

**Comment by xfxyjwf** [comment]
Yeah, implicit casting from size_t to int should use static_cast. These warning are disabled in our internal build system so most of them are introduced without anyone's notice. Feel free to send us pull requests to fix these warnings.
