### ISSUE TITLE
Ownership of Message instances created with DynamicMessageFactory using a Arena

### ISSUE THREAD

**Issue by TorstenWK** [google/protobuf#1009]
Hello,

i already posted the issue in the Protocol Buffers google group with the conclusion that it is maybe a bug.

i'am using a copy of the master branch of protobuf v 3.0.0-beta-1.

```
{
   DynamicMessageFactory dynamicMessageFactory;
   Arena myArena;

   const Descriptor *messageDesc = m_pProtoFileDescriptor->FindMessageTypeByName( "Foo" );
   Message *fooMessage = dynamicMessageFactory.GetPrototype( messageDesc )->New(&myArena); 
}
```

What i try to do is loading a .proto file at runtime and create various Message instances from it by name. I want to use a Arena cause of the massive amount of message creations out of this loaded .proto Descriptor.

Unfortunately both the DynamicMessageFactory and the Arena try to destroy the created message. The Message::New method description says that the ownership of the created message will be passed to the caller or in this case the arena. So why the DynamicMessageFactory is still holding a reference on that newly created messages instance?

With best regards, 

Torsten

**Comment by pherl** [comment]
DynamicMessageFactory should never try to free the message, even if no arena is used. Is the destruction order the culprint here? Can you define Arena before the factory so it out-live the factory? Closing it for now as it's probably solved.
