### ISSUE TITLE
BinaryToJsonString mishandling strings containing UTF8 multibyte characters

### ISSUE THREAD

**Issue by ronnnnnnnnnnnnn** [google/protobuf#1010]
With compilers that define char as signed by default (such as Microsoft's) - there's a problem handling strings containing multibyte characters.
It seems the place where things start to go wrong is in ReadCodePoint (in json_escaping.cc) when the first byte of the multibyte character is being read from the string (as char) and assigned into a variable of type uint32. This casting directly from a signed 1-byte value to an unsigned 4-byte value seems to produce values that are different than intended and different than expected a little later on by some if-else statements trying to look at that value to determine the correct length of the multibyte character. From there things go wrong and the string isn't serialized and just gets dropped.

Possible fixes could be either to modify StringPiece to use unsigned char instead of char (the default signedness of which is compiler-specific); or to at least to cast the value returned by its [ ] operator to a suitable intermediate type (like uint8 in the above case) wherever there's any such problematic assignment (like into uint32 in the above case)...

More details and an example in this forum thread:
https://groups.google.com/forum/#!topic/protobuf/LDeLkvGO5NQ

**Comment by xfxyjwf** [comment]
Should be fixed in v3.0.0-beta-2. I added a static_cast<uint8>() before assigning the value to uint32.
