### ISSUE TITLE
JsonFormat is not thread-safe

### ISSUE THREAD

**Issue by christian-lefty** [google/protobuf#1032]
The java util package TimeUtil.java uses a static instance of SimpleDateFormat
 private static final SimpleDateFormat timestampFormat =
      createTimestampFormat();

However it is specified that:  Date formats are not synchronized. It is recommended to create separate format instances for each thread. If multiple threads access a format concurrently, it must be synchronized externally.

This leads to actual bugs in our high throughput application where we need to serialize objects to json from multiple  threads.

**Comment by xfxyjwf** [comment]
Fixed in v3.0.0-beta-2. We changed to use ThreadLocal for the SimpleDateFormat.
