### ISSUE TITLE
code generated by protoc failed to compile in objective-c env for type error.

### ISSUE THREAD

**Issue by joyyoj** [google/protobuf#1040]
I try to use protobuf in object-c env, but it failed because the missing of the GPBTypeString, GPBTypeEnum. I think it is a bug since the definition of GPBDataTypeString rather than GPBTypeString  can be found in GPBRuntimeTypes.h. Anyone can fix it ?

**Comment by thomasvl** [comment]
Can you provide more information about what is failing?  Things are building fine for me, and we have travis.ci set up on the repository and it seems to be build fine also.

**Comment by thomasvl** [comment]
Re searching all the Objective C directories, there are no hits for GPBTypeString or GPBTypeEnum.  So I'm going to close this out since it doesn't seem to be coming from the library.  Please feel free to reopen or file a new issue if you can recreate it with the details of how you are doing that.
