### ISSUE TITLE
Make sure dotnet dependencies in Google.Protobuf.nuspec are always up to date.

### ISSUE THREAD

**Issue by jtattermusch** [google/protobuf#1054]
PR #1501 has added dependencies generated by Nuget package https://www.nuget.org/packages/NuSpec.ReferenceGenerator/. We could not check in the actual dependency on the referencegenerator nuget package (into packages.config file) because the package tries to update .nuspec file on every build and that step fails under mono. 

Action needed:
We should figure out an approach to make sure our .nuspec file stays up to date in terms of dependencies included.

**Comment by jtattermusch** [comment]
Detail of build error from Travis run:
 https://travis-ci.org/google/protobuf/jobs/97098686

It looks like the build step is trying to execute "RefGen.exe" directly, which has no chance of working on linux.
```
Target UpdateNuspecDependencies:
				Executing: "/home/travis/build/google/protobuf/csharp/src/packages/NuSpec.ReferenceGenerator.1.3.6/build/portable-net45+win+wpa81+wp80+MonoAndroid10+xamarinios10+MonoTouch10/../../tools/RefGen.exe" ";" dotnet "/home/travis/build/google/protobuf/csharp/src/Google.Protobuf/Google.Protobuf.nuspec;/home/travis/build/google/protobuf/csharp/src/Google.Protobuf/Google.Protobuf.nuspec" "/home/travis/build/google/protobuf/csharp/src/Google.Protobuf/" "/home/travis/build/google/protobuf/csharp/src/Google.Protobuf/bin/Release//Google.Protobuf.dll"
				/tmp/tmp49ee932f.tmp: 1: /tmp/tmp49ee932f.tmp: /home/travis/build/google/protobuf/csharp/src/packages/NuSpec.ReferenceGenerator.1.3.6/build/portable-net45+win+wpa81+wp80+MonoAndroid10+xamarinios10+MonoTouch10/../../tools/RefGen.exe: Permission denied
/home/travis/build/google/protobuf/csharp/src/packages/NuSpec.ReferenceGenerator.1.3.6/build/portable-net45+win+wpa81+wp80+MonoAndroid10+xamarinios10+MonoTouch10/NuSpec.ReferenceGenerator.targets: error : Command '"/home/travis/build/google/protobuf/csharp/src/packages/NuSpec.ReferenceGenerator.1.3.6/build/portable-net45+win+wpa81+wp80+MonoAndroid10+xamarinios10+MonoTouch10/../../tools/RefGen.exe" ";" dotnet "/home/travis/build/google/protobuf/csharp/src/Google.Protobuf/Google.Protobuf.nuspec;/home/travis/build/google/protobuf/csharp/src/Google.Protobuf/Google.Protobuf.nuspec" "/home/travis/build/google/protobuf/csharp/src/Google.Protobuf/" "/home/travis/build/google/protobuf/csharp/src/Google.Protobuf/bin/Release//Google.Protobuf.dll"' exited with code: 126.
			Task "Exec" execution -- FAILED
			Done building target "UpdateNuspecDependencies" in project "/home/travis/build/google/protobuf/csharp/src/Google.Protobuf/Google.Protobuf.csproj".-- FAILED
```

**Comment by onovotny** [comment]
Hi,

I've commented on the issue... on the thread

**Comment by jskeet** [comment]
@jtattermusch Do you believe PR #1059 fixed this issue, so we can close it?

**Comment by jtattermusch** [comment]
The solutions is still not 100% automatic. Right now, when you build with visual studio, and the .nuspec file gets updated by the reference generator upon build, you will see a change to the .nuspec file when invoking `git status`. But there is currently no test in place that would make sure that the checked-in version of that file is the same as the version generated by the reference generator.
In a way, this is a similar problem as checking that our generated code is up-to-date. 

In gRPC, we have a "sanity test" for this.It basically tries to regenerate the generated code and compares to the checked-in version. If they are different, the test fails.

**Comment by anandolee** [comment]
No .nuspec files any more.

PR #1727
