### ISSUE TITLE
Timestamp: Handle datetime aware and naives

### ISSUE THREAD

**Issue by dzen** [google/protobuf#1057]
Hello,
for what I can see (in python for instance) a Timestamp "type" can be used to store a date into a protobuf message.
But the problem is that we miss the timezone of the stored instance, and we can have date manipulation bugs …

Is it an implementation choice to not take in account the timezone ? and assume the date is in  UTC ?

**Comment by xfxyjwf** [comment]
Quote from the timestamp.proto
```proto
// A Timestamp represents a point in time independent of any time zone
// or calendar, represented as seconds and fractions of seconds at
// nanosecond resolution in UTC Epoch time
```

It's by design that timezone info is not stored in the Timestamp message. If you need the timezone info, you can store it in a separate field.
