### ISSUE TITLE
ios support issue

### ISSUE THREAD

**Issue by ustime** [google/protobuf#1066]

**Comment by ustime** [comment]
I try to build latest protobuf code for ios, but got failure. There is an arc error and a dependency failure. I wonder if ios is supported by protobuf 3, or is there any detailed dicment on ios build? Thanks

**Comment by ustime** [comment]
and I can not find SerializeToArray in IOS version, can anyone help me how to serialize to binary on ios?

**Comment by xfxyjwf** [comment]
Could you provide more details about how you build protobuf and what's the exact error? And are you using C++ or objective-c?

**Comment by anandolee** [comment]
Closing it as no response for a year. Feel free to reopen if it is still an issue
