### ISSUE TITLE
winxp_support

### ISSUE THREAD

**Issue by awayhome113** [google/protobuf#1067]
Is it possible for me to compile C# of protobuf in visual studio 2010 on windows XP?

**Comment by jtattermusch** [comment]
We recently started using C# 6 features in the code, so you actually need Visual Studio 2015 (freely available) to build protobuf C# assembly (Google.Protobuf). Note that this is only a requirement for active development - to use protobuf C#, just use Google.Protobuf nuget package that is a portable class library (works with .NET 4.5 and higher and many other targets - specifically we use PCL Profile259).

Closing this, feel free to reopen if appropriate.
