### ISSUE TITLE
Fix crashing conformance testee programs

### ISSUE THREAD

**Issue by xfxyjwf** [google/protobuf#1073]
We added many new conformance test cases in v3.0.0-beta-2 and the conformance testee program in some languages cannot handle these test cases gracefully and would crash on some input. They have been disabled temporarily because these failures cannot be ignore with the failure_list.txt configuration.

Disabled languages: python, csharp, ruby.

**Comment by acozzette** [comment]
Closing this because I believe this was fixed in e891c29f9bc6aec.
