### ISSUE TITLE
The semantics of #ifdef NDEBUG is apparently reversed

### ISSUE THREAD

**Issue by kkm000** [google/protobuf#1077]
https://github.com/google/protobuf/blob/v3.0.0-beta-1.1/src/google/protobuf/stubs/logging.h#L175

Looks like the polarity of `NDEBUG` is reversed (and higher up in the same file). Cf. the [definition of `assert()`](http://en.cppreference.com/w/c/error/assert)

**Comment by xfxyjwf** [comment]
It's not reversed. It's used the same way as the linked assert() definition.

**Comment by kkm000** [comment]
Sorry, a brain fart. I misread the `while (false)` trick. Is not the C preprocessor amazing.
