### ISSUE TITLE
[Ruby] Instance doesn't respond to `respond_to?`

### ISSUE THREAD

**Issue by zhuochun** [google/protobuf#1078]
Give a proto with a string field `name`.

I can access name with `instance.name`. But if I check `instance.respond_to?(:name)` it always return `false`, which should be `true`.

From the [source code](https://github.com/google/protobuf/blob/24fe6ba750bf8a247d41fc589460dce1bdd697a1/ruby/ext/google/protobuf_c/message.c#L462), `method_missing` is defined with no `respond_to_missing?` method. I think it is better to add `respond_to_missing?` method as well. Refer to https://robots.thoughtbot.com/always-define-respond-to-missing-when-overriding

Thanks.

**Comment by marcinwyszynski** [comment]
I just submitted a PR for that - https://github.com/google/protobuf/pull/2323

**Comment by gerben-s** [comment]
PR is assigned, closing this thread
