### ISSUE TITLE
ProtocolBuffers_iOS does not build

### ISSUE THREAD

**Issue by a-kao** [google/protobuf#1084]
(1) -Werror and -Wobjc-missing-property-synthesis are turned on, but the defaultValue property in Type.pbobjc.m does not explicitly synthesize the declared property.

```
../protobuf/objectivec/google/protobuf/Type.pbobjc.h:229:66: error: auto property synthesis is synthesizing property not explicitly synthesized [-Werror,-Wobjc-missing-property-synthesis]
@property(nonatomic, readwrite, copy, null_resettable) NSString *defaultValue;
                                                                 ^
```
(2) The null_resettable annotation is specified for the defaultValue property in Type.pbobjc.m but (currently) relies on the automatically synthesized setter.

```
../protobuf/objectivec/google/protobuf/Type.pbobjc.m:200:1: error: synthesized setter 'setDefaultValue:' for null_resettable property 'defaultValue' does not handle nil [-Werror,-Wnullability]
```

**Comment by thomasvl** [comment]
I believe this got fixed PR #1093 - commit fcce784
