### ISSUE TITLE
vs2015 build protobuf-cpp-3.0.0-alpha-3 error:release

### ISSUE THREAD

**Issue by yunlhowk** [google/protobuf#1103]
3>  libprotoc.vcxproj -> D:\SVN\iQuant\Quantrader V2.4\1.Engineering\13.Code Management\Trunk\slib\protobuf-3.0.0-alpha-3\vsprojects\Release\libprotoc.lib
4>------ 已启动全部重新生成: 项目: protoc, 配置: Release Win32 ------
4>  main.cc
4>LINK : warning LNK4075: 忽略“/INCREMENTAL”(由于“/OPT:ICF”规范)
4>libprotobuf.lib(generated_message_reflection.obj) : error LNK2019: 无法解析的外部符号 "public: static class google::protobuf::Message * __cdecl google::protobuf::internal::GenericTypeHandler<class google::protobuf::Message>::NewFromPrototype(class google::protobuf::Message const *,class google::protobuf::Arena *)" (?NewFromPrototype@?$GenericTypeHandler@VMessage@protobuf@google@@@internal@protobuf@google@@SAPAVMessage@34@PBV534@PAVArena@34@@Z)，该符号在函数 "private: void __thiscall google::protobuf::internal::RepeatedPtrFieldBase::MergeFromInnerLoop<class google::protobuf::internal::GenericTypeHandler<class google::protobuf::Message> >(void * *,void * *,int,int)" (??$MergeFromInnerLoop@V?$GenericTypeHandler@VMessage@protobuf@google@@@internal@protobuf@google@@@RepeatedPtrFieldBase@internal@protobuf@google@@AAEXPAPAX0HH@Z) 中被引用
4>Release\protoc.exe : fatal error LNK1120: 1 个无法解析的外部命令

**Comment by xfxyjwf** [comment]
This is a known issue and was fixed in recent releases. Please try the latest beta-2 version.

**Comment by yunlhowk** [comment]
thanks,but the latest beta-2 version no vsprojects!

**Comment by xfxyjwf** [comment]
See the instructions in https://github.com/google/protobuf/tree/master/cmake. We switched to use cmake for Visual Studio builds.
