### ISSUE TITLE
JsonFormat.TypeRegistry.add(Descriptor) warnings.

### ISSUE THREAD

**Issue by mikhailmikhaylov** [google/protobuf#1126]
We have encountered the situation, when TypeRegistry produces lots of warnings:

`Type <TYPENAME> is added multiple times.`

This situation appears because of adding same dependencies by different descriptors. As we only have adding descriptor in API, if we add two descriptors with same dependency, it will try adding this dependency twice. And this will produce warnings.

In our case we have to provide multiple dependencies to a single file, but we want to avoid these warnings. Is there a way to do so?

**Comment by xfxyjwf** [comment]
Can you check if the type is defined twice in different .proto files? The code only adds a .proto file once, so unless you have two different .proto files defining the same message, you won't get the warning message.

**Comment by mikhailmikhaylov** [comment]
I've managed to implement a simple sample.

So, we have four proto files, each one contains one message

```
message MessageA {
    string id = 1;
}

message MessageB {
    MessageA a = 1;
}

message MessageC {
    MessageA a = 1;
}

message MessageD {
    MessageB b = 1;
    MessageC c = 2;
}
```

And when you execute this code:
```
final MessageA a = MessageA.newBuilder().setId("0").build();
        final MessageB b = MessageB.newBuilder().setA(a).build();
        final MessageC c = MessageC.newBuilder().setA(a).build();
        final MessageD d = MessageD.newBuilder()
                .setB(b).setC(c).build();

        final Descriptors.Descriptor descriptorD = d.getDescriptorForType();
        final JsonFormat.TypeRegistry.Builder jsonFormatBuilder =
                JsonFormat.TypeRegistry.newBuilder();

        jsonFormatBuilder.add(descriptorD).build();
```

you'll get the warning:
`WARNING: Type MessageA is added multiple times.`

It's happening because both MessageB and MessageC have dependencies to MessageA. When TypeRegistry accepts the descriptor, it calls addFile() method for it, which recursively calls addFile() for each dependency. As we have MessageA dependencies added twice, we get the warning

Each type is defined only once.

**Comment by xfxyjwf** [comment]
I see. Thanks for the explanation. I think we should just remove the warning then.

**Comment by xfxyjwf** [comment]
The bug was fixed. It was a problem of the same .proto file being added multiple times to the registry.
