### ISSUE TITLE
extract_includes.bat.in has error parameter at copy path

### ISSUE THREAD

**Issue by yunlhowk** [google/protobuf#1130]
copy ${PROTOBUF_SOURCE_WIN32_PATH}..\src\google\protobuf\any.h include\google\protobuf\any.h

running extract_includes.bat. show not find the file any.h。

Proposed replacement：
copy ..\src\google\protobuf\any.h include\google\protobuf\any.h

**Comment by yunlhowk** [comment]
使用绝对路径出错（copy D:\SVN\slib\protobuf-3.0.0-beta-2\cmake..\src\google\protobuf\any.h include\google\protobuf\any.h）
所以建议还是直接使用相对路径就行

**Comment by xfxyjwf** [comment]
Do you mean the calculated path is incorrect? Can you attach the extract_includes.bat file generated after running cmake?

**Comment by yunlhowk** [comment]
我确认，也相当肯定，就是在所有编译成功之后，使用过程中，提示缺少头文件。后独立通过VS2015的MSbuild命令提示符运行extract_includes.bat过程中报错，文件找不到。所以才修订 extract_includes.bat。
这是我一步一步从操作的信息结果。
D:\SVN\iQuant\Quantrader V2.4\1.Engineering\13.Code Management\Trunk\slib\protob
uf-3.0.0-beta-2\cmake>copy D:\SVN\iQuant\Quantrader V2.4\1.Engineering\13.Code M
anagement\Trunk\slib\protobuf-3.0.0-beta-2\cmake\..\src\google\protobuf\any.h in
clude\google\protobuf\any.h
系统找不到指定的文件。

**Comment by yunlhowk** [comment]
beta-2\cmake中后面是"\..\",提交时被过滤了

**Comment by yunlhowk** [comment]
beta-2\cmake中后面是"\\..\",提交时被过滤了

**Comment by xfxyjwf** [comment]
ok, I believe the problem is the white-spaces in the file path. The extract_includes.bat file doesn't handle that case correctly. We should double-quote the file names.
