### ISSUE TITLE
csharp_out error

### ISSUE THREAD

**Issue by wulei** [google/protobuf#1132]
Hi gays:
i use protoc csharp_out error:

protoc-gen-csharp: program not found or is not executable
--csharp_out: protoc-gen-csharp: Plugin failed with status code 1.
protoc -I./protocol --csharp_out=./csharp ./protocol/serverInfo/team.proto

**Comment by wulei** [comment]
i'm in osx system

**Comment by xfxyjwf** [comment]
Which version of the protoc are you using? It seems you are using an older version protoc which doesn't come with csharp support. You can find the latest version in our releases page:
https://github.com/google/protobuf/releases

**Comment by wulei** [comment]
thks,I find protoc-3.0.0-beta-2-win32.zip, but not find protoc in osx

**Comment by xfxyjwf** [comment]
@wulei, I updated the downloads section and add protoc-3.0.0-beta-2-osx-x86_32.zip and protoc-3.0.0-beta-2-osx-x86_64.zip. Could you try it out?

If you are using old versions of the C# runtime, you can find more pre-built protocol compiler binaries here:
http://repo1.maven.org/maven2/com/google/protobuf/protoc/

**Comment by wulei** [comment]
@xfxyjwf tks.
successful create csharp file.
please release version don't forget osx user

**Comment by wulei** [comment]
proto: C# code generation only supports proto3 syntax

/maven2/com/google/protobuf/protoc/2.6.1/protoc-2.6.1-osx-x86_64.exe     

2.6.1 verision why is .exe file?

**Comment by xfxyjwf** [comment]
The file extension has no special meaning. It's actually an osx executable. It's named that way to be consistent and allow easier scripting.

**Comment by wulei** [comment]
@xfxyjwf 
2.6.1 not supper --csharp_out flag
3.0.0 not supper syntax=''proto3'

I want a csharp for syntax=''proto2' version?

**Comment by xfxyjwf** [comment]
We don't support proto2 csharp right now. For proto2 C# support, you can use:
https://github.com/jskeet/protobuf-csharp-port

I would recommend using proto3 unless you have old .proto files that can't be migrated.

**Comment by wulei** [comment]
@xfxyjwf 
but 3.0.0 won't work with Unity c#

**Comment by xfxyjwf** [comment]
@jskeet does proto3 C# work with Unity?

**Comment by jskeet** [comment]
No - we'd like it to eventually, but it definitely doesn't right now.

**Comment by layern9ne** [comment]
You can use https://github.com/mgravell/protobuf-net a community port for proto2 C#. 
(command line) protogen.exe -i:messagedef.proto -o:messagedef.cs
Take the generated C# into visual studio as a class library target NET 2.0 
Add a reference to protobuf-net\Full\unity\protobuf-net.dll
build the dll (you might have to download 2.0 to have it as a target)
With the new dll and protobuf-net.dll (in same directory) run
(command line) protobuf-net\Precompile\precompile.exe messagedef.dll -o:messagedefserializer.dll -t:messagedefserializer
Use the 3 dlls in Unity (messagedef.dll, messagedefserializer.dll, protobuf-net.dll)
