### ISSUE TITLE
Can parse json to Google.Protobuf.WellKnownTypes.Any in C#?

### ISSUE THREAD

**Issue by BennetWang** [google/protobuf#1134]
Can we parse json to Google.Protobuf.WellKnownTypes.Any in C#?When I parse,I get the error " Next() called after end of document"

**Comment by jskeet** [comment]
It should be okay - at least now, although that may be due to recent bug fixes. Could you post a complete example?

**Comment by jskeet** [comment]
@BennetWang: Have you tried this again? (If I don't hear anything more in the next week or so, I'll close this issue.)

**Comment by jskeet** [comment]
(Please feel free to add a comment and I can reopen it if there are still issues...)
