### ISSUE TITLE
ambiguous unqualified symbols from std namespace

### ISSUE THREAD

**Issue by ardatur** [google/protobuf#1136]
[3.0.0-beta-2, MSVC 2015]

Unqualified "string" usage in header files causes conflicts with string classes from other, unrelated, namespaces:

> ...\protobuf\src\google\protobuf\map_entry_lite.h(123): error C2872: 'string': ambiguous symbol
> ...\protobuf\src\google\protobuf\map_type_handler.h(625): error C2872: 'string': ambiguous symbol

Changing "string" to "::std::string" in relevant locations fixed that particular compilation issue, although there appear to be more similar "string" usage instances.

**Comment by ardatur** [comment]
Not global as such, but I do have it imported via "using namespace" in that
translation unit.

**Comment by johnco3** [comment]
I'm also having this problem - is the problem in the grpc source code?  I will have to change my protoc from using the map type to work around this, what a shame

**Comment by segrax** [comment]
If your making use of the grpc namespace via "using namespace grpc;", try removing it.

**Comment by anandolee** [comment]
Closing it for clean up. Feel free to reopen if it is still an issue

**Comment by ardatur** [comment]
It is still an issue. Protobuf 3.2.0, Visual Studio 2015 update 3.
