### ISSUE TITLE
Travis CI build is broken on master, has been for over 2 weeks

### ISSUE THREAD

**Issue by jhump** [google/protobuf#1141]
Master is red (as of 10:23am EST 1/14/16) and, according to history in Travis, has been red for 16 days.
https://travis-ci.org/google/protobuf/builds

I have some changes I'd like to land (#896). Do I just wait until master is green? Or should I rebase to a point before master was broken so that at least my branch build in Travis CI goes green?

**Comment by haberman** [comment]
For now, everything is passing except python_cpp -- any PR which maintains this should be ok.

I'm looking into the python_cpp failure. If I can resolve it today I'll add it to the allowable failures list.

**Comment by haberman** [comment]
Fixed finally -- sorry for the brokenness.
