### ISSUE TITLE
Python 3.0.0-beta2 Class Message almost entirely incomplete.

### ISSUE THREAD

**Issue by Lumiukko** [google/protobuf#1142]
The file is scattered with `NotImplementedError`s.

This causes one of the main functions `ParseFromString` not to work. Am I missing something or was this version released in a state that is just not functioning?

Is it possible to get an older, fully implemented version somewhere for the meantime?

This is the file in question: https://github.com/google/protobuf/blob/master/python/google/protobuf/message.py

**Comment by xfxyjwf** [comment]
NotImplementedError is not the problem. The message.py has been like that since always. These not-implemented functions are supposed to be implemented by its subclasses.

Could you describe what problem you are experience with ParseFromString()? How does your code look like?

**Comment by Lumiukko** [comment]
Oh... that's a little embarrassing.

Well, I have the python file generated by the protobuf compiler from the .proto file, which does indeed have a class that is a subclass of `Message` as well as a fitting descriptor. The file was not generated by me, but is also on GitHub:

https://github.com/Bakkes/demoinfo-csgo-python/blob/master/src/demoinfocsgo/proto/netmessages_pb2.py

To quickly summarize:
```
from google.protobuf import message as _message
# [...]
_CSVCMSG_SERVERINFO = _descriptor.Descriptor(
  # [...]
)

DESCRIPTOR.message_types_by_name['CSVCMsg_ServerInfo'] = _CSVCMSG_SERVERINFO

# [...]
class CSVCMsg_ServerInfo(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CSVCMSG_SERVERINFO

  # @@protoc_insertion_point(class_scope:CSVCMsg_ServerInfo)
```

This python file is imported properly and in the main program the subclass is instantiated and the parsing function called:
```
info = CSVCMsg_ServerInfo()
info.ParseFromString(data)
```

at which point it fails with an `NotImplementedError` , because apparently the subclass does not implement the `ParseFromString` function

I hope that helps, and thanks for your time.

**Comment by xfxyjwf** [comment]
What's the version of the protoc used to generate that netmessages_pb2.py file? And what's the version of the protobuf python runtime you are using? These two must match. Could you check?

**Comment by Lumiukko** [comment]
Unfortunately the original author did not keep the version number of the compiler around.
If that may be the problem, I can try to compile them again with the version I'm using (`'3.0.0b2'`) and report back.

**Comment by Lumiukko** [comment]
Yes, That was it! Thank you very much.
