### ISSUE TITLE
Python Protobuf package conflicts with AppEngine Python SDK

### ISSUE THREAD

**Issue by danielframe** [google/protobuf#1153]
Note that the Python protobuf package and the Google AppEngine both use the root module name 'google' so if one package is installed, the other package can't be located.

For instance protobuf on my mac is installed to (same problem on Linux as well):
/Library/Python/2.7/site-packages/google/protobuf

This will cause the AppEngine SDK imports to fail:
Traceback (most recent call last):
  File "/xxx/yyy.py", line 16, in <module>
    from google.appengine.api import users
ImportError: No module named appengine.api

Uninstalling the protobuf library fixes the issue.

For now, I am manually removing the protobuf library from my PYTHON_PATH.

It's not really a bug related to protobuf or appengine, they just have conflicting module names that don't play nicely together so I wanted to bring it to the teams attention.

**Comment by xfxyjwf** [comment]
@tbetbetbe, I remember you have looked into this issue before. Could you suggest a solution here?

**Comment by awan1** [comment]
*bump*

**Comment by xfxyjwf** [comment]
@haberman, Josh, do you know of any solutions to this problem?

**Comment by haberman** [comment]
Closing in favor of https://github.com/google/protobuf/issues/1296
