### ISSUE TITLE
Create a C++ NuGet (or vcpkg) package

### ISSUE THREAD

**Issue by eadordzhiev** [google/protobuf#1154]
An official C++ NuGet package would be really great. There already exists [one](https://www.nuget.org/packages/protobuf), but it's very outdated (2.5). Thanks in advance!

**Comment by goldenbull** [comment]
:+1:

**Comment by fsrfsr** [comment]
Absolutely...

**Comment by matthew798** [comment]
Just thought i'd +1 this as I've been pulling my hair out trying to match version with a c++ project and a c# project.

**Comment by rchom** [comment]
+1

**Comment by damian123** [comment]
+1

**Comment by Andrues** [comment]
+1

**Comment by perara** [comment]
+1

**Comment by Retik** [comment]
There desperately needs to be a protobuf3 package for c++ (grpc too). These libraries are so large, building them adds a ton of overhead to a project.

**Comment by jtattermusch** [comment]
Perhaps a vcpkg package for protobuf would be better and easier to build?  (see https://github.com/grpc/grpc/issues/10699)

**Comment by dmichaud** [comment]
Likewise - it would certainly be appreciated by the community if this existed.

Now off to try and figure out how to build this for use with VS 2017...

**Comment by riordanmr** [comment]
+1

**Comment by yelu** [comment]
+1

**Comment by xfxyjwf** [comment]
vcpkg was added in https://github.com/google/protobuf/pull/3825
