### ISSUE TITLE
Change in readme.md file

### ISSUE THREAD

**Issue by madminions** [google/protobuf#1168]
While issuing command `make` it gives **"permission denied"** error so it should be 
` sudo make `
` sudo make check `
instead of just `make` and `make check`

**Comment by jskeet** [comment]
I wouldn't expect that. Just `make` and `make check` shouldn't be doing anything that requires extra permission. (It's never been a problem for me, certainly.) At what point did you get "permission denied"? Did the log show what it was trying to do at the time?

**Comment by madminions** [comment]
It was showing **permission denied** at last step in **errors** earlier, in Ubuntu 14.04 (i failed to take snapshot) but now it is working fine.

**Comment by xfxyjwf** [comment]
It's likely to be caused by temporary files created with root permission (e.g., run "sudo make install" without "make" first will create many files under the root user). It should be working fine in a clean directory.
