### ISSUE TITLE
JSON casing code doesn't follow spec

### ISSUE THREAD

**Issue by jskeet** [google/protobuf#1171]
Background: the C# code follows the C++ code (src/google/protobuf/util/internal/utility.cc) for case handling.

The conformance tests show two issues with this:
- `_field_name3` is expected to map to `FieldName3`
- `FIELD_NAME11` is expected to map to `fIELDNAME11`

It's possible that there are equivalent issues when converting in the other direction, which would be shown up in field mask parsing, but I haven't looked into this.

The fact that the conformance tests use the C++ parsing (somewhat unavoidably!) makes it particularly hard to fix this sort of thing in just the C#,  so I'm intending to wait until the C++ is fixed before porting the fix over to C#.

**Comment by xfxyjwf** [comment]
Examining the conformance tests, I believe this is fixed already.
