### ISSUE TITLE
JSON parsing of number Value in Any is incorrect

### ISSUE THREAD

**Issue by jskeet** [google/protobuf#1172]
Discovered while trying to fix C# conformance tests.

It looks like JSON of:

```text
{ "optionalAny": { "@type": "type.googleapis.com/google.protobuf.Value", "value": 1 } }
```

is parsed as if `value` is an empty Struct, rather than a number value of 1.

This also occurs with a nested number value:

```text
{ "optionalAny": { "@type": "type.googleapis.com/google.protobuf.Value", "value": { "foo": 1 } } }
```

**Comment by xfxyjwf** [comment]
This has been fixed for a while. There is now a test for this nested Any value case:
https://github.com/google/protobuf/blob/master/src/google/protobuf/util/internal/protostream_objectwriter_test.cc#L1751
