### ISSUE TITLE
Python: Suport bytearray in FromString

### ISSUE THREAD

**Issue by hexum** [google/protobuf#1173]
Bytes decoding works fine.

``` python
s.FromString(b)
```

But if I convert bytes to bytearrat I get an error every time.

``` python
In [19]: s.FromString(bytearray(b))
---------------------------------------------------------------------------
DecodeError                               Traceback (most recent call last)
<ipython-input-19-a877d383a254> in <module>()
----> 1 s.FromString(bytearray(b))

/usr/local/lib/python3.4/dist-packages/google/protobuf/internal/python_message.py in FromString(s)
    768   def FromString(s):
    769     message = cls()
--> 770     message.MergeFromString(s)
    771     return message
    772   cls.FromString = staticmethod(FromString)

/usr/local/lib/python3.4/dist-packages/google/protobuf/internal/python_message.py in MergeFromString(self, serialized)
   1095     except (IndexError, TypeError):
   1096       # Now ord(buf[p:p+1]) == ord('') gets TypeError.
-> 1097       raise message_mod.DecodeError('Truncated message.')
   1098     except struct.error as e:
   1099       raise message_mod.DecodeError(e)

DecodeError: Truncated message.
```

VERSION
    3.0.0b2

**Comment by haberman** [comment]
The problem seems to be that `bytearray` returns an integer when you index `val[i]` whereas `bytes` in Python 2.x returns a one-character string.

We use `six.indexbytes(buffer, pos)` to index into a "bytes" object -- this does the right thing for bytes objects in both Python 2 and Python 3. However it doesn't work for `bytearray` objects in Python 2.

Not sure what the cleanest fix is here.

**Comment by holdenk** [comment]
I'm running into some related issues in text_encoding.py while migration Beam from Py2 to Py2/3 (not exactly 1:1).

**Comment by jleni** [comment]
Same issue here:
https://github.com/google/protobuf/issues/3734

I submitted a PR that I think is clean
https://github.com/google/protobuf/pull/3736

**Comment by jleni** [comment]
My PR #3736 was merged. Could you verify that also fix this issue. I believe they were same thing.
