### ISSUE TITLE
Ruby gem redefines slice

### ISSUE THREAD

**Issue by kallisti5** [google/protobuf#1174]
/home/travis/.rvm/gems/ruby-2.3.0/gems/google-protobuf-3.0.0.alpha.5.0/lib/google/protobuf/repeated_field.rb:108: warning: method redefined; discarding old slice
/home/travis/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/forwardable.rb:182: warning: previous definition of slice was here

Error seen under ruby 2.1.8, 2.2.4, 2.3.0

**Comment by kallisti5** [comment]
It looks like slice needs removed from def_delegators, or alias_method :slice, :[] needs removed... I don't know  the code well enough to determine which way it should go though.

**Comment by haberman** [comment]
How can I reproduce this? I tried:

```
$ gem list | grep google-protobuf
google-protobuf (3.0.0.alpha.5.0.3 x86_64-linux, 3.0.0.alpha.5.0.2 x86_64-linux)
$ ruby --version
ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-linux]
$ ruby -r google/protobuf -e ''
$
```

But I didn't see any warning.

**Comment by glennmatthews** [comment]
Use `-v` to enable verbose warnings:

```bash
$ ruby -v -r google/protobuf -e ''
ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-linux]
...lib/ruby/gems/2.2.0/gems/google-protobuf-3.0.0.alpha.5.0.3-x86_64-linux/lib/google/protobuf/repeated_field.rb:108: warning: method redefined; discarding old slice
.../lib/ruby/2.2.0/forwardable.rb:181: warning: previous definition of slice was here
```

**Comment by bluehallu** [comment]
Still today, any ruby code that imports protobuf with verbose warnings gets:

`/Users/x/.rvm/gems/ruby-2.3.0/gems/google-protobuf-3.0.2-universal-darwin/lib/google/protobuf/repeated_field.rb:108: warning: method redefined; discarding old slice
/Users/x/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/forwardable.rb:182: warning: previous definition of slice was here
`
