### ISSUE TITLE
Java compile nested_extension.proto has an error

### ISSUE THREAD

**Issue by qingchengzhi** [google/protobuf#1176]
protobuf version is 2.6.1
i use protoc to compile nested_extension.proto, it has an error as below:
>com/google/protobuf/non_nested_extension.proto: File not found.
src/test/java/com/google/protobuf/nested_extension.proto: Import "com/google/protobuf/non_nested_extension.proto" was not found or had errors.
src/test/java/com/google/protobuf/nested_extension.proto:43:10: "MessageToBeExtended" is not defined.

nested_extesion_lite.proto also has same problem 
>com/google/protobuf/non_nested_extension_lite.proto: File not found.
src/test/java/com/google/protobuf/nested_extension_lite.proto: Import "com/google/protobuf/non_nested_extension_lite.proto" was not found or had errors.
src/test/java/com/google/protobuf/nested_extension_lite.proto:45:10: "MessageLiteToBeExtended" is not defined.

how to fix it? thanks

**Comment by haberman** [comment]
If you are compiling `.proto` files by hand, you need to make sure that you have `-I` options for all of the directories where the included files live. These files (`com/google/protobuf/non_nested_extension.proto` and `com/google/protobuf/non_nested_extension_lite.proto`) live in `java/core/src/test/proto`, so you need to be sure that you either run `protoc` from this directory or that you have a `-I` option for it.
