### ISSUE TITLE
nmake check failing CommandLineInterfaceTest

### ISSUE THREAD

**Issue by elodg** [google/protobuf#1177]
I am trying to build 3.0.0-beta2 using cmake and nmake under Win7 x64 and VS2013. 14 tests fail:
[  FAILED  ] CommandLineInterfaceTest.BasicPlugin
[  FAILED  ] CommandLineInterfaceTest.GeneratorAndPlugin
[  FAILED  ] CommandLineInterfaceTest.MultipleInputs
[  FAILED  ] CommandLineInterfaceTest.MultipleInputsWithImport
[  FAILED  ] CommandLineInterfaceTest.CreateDirectoryA
[  FAILED  ] CommandLineInterfaceTest.GeneratorParameters
[  FAILED  ] CommandLineInterfaceTest.Insert
[  FAILED  ] CommandLineInterfaceTest.PluginOutputWriteError
[  FAILED  ] CommandLineInterfaceTest.PluginOutputDirectoryNotFoundError
[  FAILED  ] CommandLineInterfaceTest.GeneratorPluginError
[  FAILED  ] CommandLineInterfaceTest.GeneratorPluginFail
[  FAILED  ] CommandLineInterfaceTest.GeneratorPluginCrash
[  FAILED  ] CommandLineInterfaceTest.PluginReceivesSourceCodeInfo
[  FAILED  ] CommandLineInterfaceTest.PluginReceivesJsonName

All tests fail with:
error: Value of: error_text_
Actual: "--plug_out: prefix-gen-plug: The system cannot find the file specified.\r\n\n"
Expected: ""

A web search turned up a few cases with the same failing tests, but either there was no reply or they were in combination with other failures. I had other failures relating to core.autocrlf, but those got solved.

**Comment by elodg** [comment]
Nevermind. It seems that nmake check does not build everything. If however I run nmake first and only then nmake check, all tests pass.

**Comment by haberman** [comment]
Clarified that `nmake` must be run before `nmake check`: https://github.com/google/protobuf/pull/1225
