### ISSUE TITLE
Objective-C: At 3.0.0-beta-2, GPBField.defaultValue doesn't show in the .m

### ISSUE THREAD

**Issue by jcanizales** [google/protobuf#1188]
This is because https://github.com/google/protobuf/pull/1093 was merged right after the release tag.

It causes a warning in XCode 7, which prevents the gRPC podspec from being submitted.

**Comment by jcanizales** [comment]
CC: @TeBoring @thomasvl

**Comment by thomasvl** [comment]
Can you do a PR against that branch?

**Comment by jcanizales** [comment]
Not really: pods submitted to the Cocoapods repo point to git tags, which name specific commits. So we need to add a `3.0.0-beta-2.1` tag (or something) to any commit after the fix to #1189 is merged (and the version label in the podspec is updated). Then submit again to Cocoapods.

None of that needs to happen in master, though, if you're worried about that.

**Comment by jcanizales** [comment]
Update: Bo's suggestion on #1189 works now, and this doesn't block gRPC anymore.
