### ISSUE TITLE
Objective-C: The GPBArrays should mark its "values" init param as nullable.

### ISSUE THREAD

**Issue by jcanizales** [google/protobuf#1189]
Because they're [within `NS_ASSUME_NONNULL_BEGIN`](https://github.com/google/protobuf/blob/master/objectivec/GPBArray.h#L40), and the convenience class-level constructors pass `NULL` in the `.m` file.

This shows as warnings in XCode 7, which prevent the gRPC podspec from being submitted.

CC: @TeBoring

**Comment by TeBoring** [comment]
I think something is strange here. NS_ASSUME_NONNULL_BEGIN should be only applied to pointer type. However, in initWithValues:(const int32_t [])values, const int32_t is not a pointer type. At least, when I add nullable to it, compiler warns that it's not a pointer type.

**Comment by jcanizales** [comment]
Changing `[]` to `*` there fixed it for me, but I agree that either the compiler is mixing stuff up, or we're missing something.

**Comment by TeBoring** [comment]
Does that warning block you?

**Comment by TeBoring** [comment]
Perhaps you can still do pod trunk push --ignore-warnings

**Comment by jcanizales** [comment]
Unless they've changed the policy, not. `--ignore-warnings` used to only work for pushing to private pod repos. For the central repo they impose no-warnings. Still let me check and confirm in a minute.

**Comment by jcanizales** [comment]
Update: Bo's suggestion works now, and this doesn't block gRPC anymore.

**Comment by thomasvl** [comment]
Which specific Xcode version shows this?

**Comment by jcanizales** [comment]
7.2

**Comment by thomasvl** [comment]
This warning doesn't trip in the Xcode projects checked in, so it must be something in your project's settings.  Can you sort out what is triggering this so we can figure out if there really is something to be done here.

**Comment by jcanizales** [comment]
I had both projects, one that produced the warning (what Cocoapods creates), and one that didn't (the one checked in), side by side on my machine. So same clang version. I looked at the invocation command line, to compare the flags; and I removed those that were equal or that couldn't possible be related. I ended up with:

Produces spurious warning (Cocoapods): `clang -arch x86_64 -std=gnu99 -O0 ...`
Doesn't produce warning (yours): `clang -arch i386 -std=c99 -Os ...`

I thought: Surely it's the C standard used, then! GNU99 must say something like "arrays are pointers". So I changed your project to gnu99, and it still didn't produce the warning. I changed Cocoapods' project to c99, and it still produced the warning. As I was left with only the optimization level and the number of bits, and in my heart didn't want any of them to produce this effect, I cursed the gods and gave up. So any help is appreciated.

**Comment by dpassage** [comment]
Kibitzing here... Is there Swift code in one project and not the other? `NS_ASSUME_NONNULL_BEGIN` and company were created to help with importing Objective-C code into Swift projects.

**Comment by jcanizales** [comment]
Actually yes, the project checked in this repo includes `GPBSwiftTests.swift`, while the projects where I'm seeing the warning don't have Swift code. A clue!!

**Comment by thomasvl** [comment]
Swift source in the project shouldn't change the warnings generated when compiling ObjC code.

No other warning flag differences between the two projects?

**Comment by thomasvl** [comment]
According to `pod spec lint` -

```
objectivec/GPBArray.m:302:25: warning: null passed to a callee that requires a non-null argument [-Wnonnull]
  return [[[self alloc] initWithValues:NULL count:0] autorelease];
```

The warning is from -Wnonnull, but if I add that manually to the Xcode project, I don't seem to get the warning.
