### ISSUE TITLE
atomics issue compiling to uCLinux for arm microcontrollers

### ISSUE THREAD

**Issue by dldg** [google/protobuf#1192]
Hi,

atomicops implemented for arm gcc (atomicops_internals_arm_gcc.h) contains pointers to memory addresses where it is assumed kernel related methods are.

`typedef Atomic32 (_LinuxKernelCmpxchgFunc)(Atomic32 old_value,
                                           Atomic32 new_value,
                                           volatile Atomic32_ ptr);
LinuxKernelCmpxchgFunc pLinuxKernelCmpxchg **attribute**((weak)) =
    (LinuxKernelCmpxchgFunc) 0xffff0fc0;

typedef void (*LinuxKernelMemoryBarrierFunc)(void);
LinuxKernelMemoryBarrierFunc pLinuxKernelMemoryBarrier **attribute**((weak)) =
    (LinuxKernelMemoryBarrierFunc) 0xffff0fa0;
`
The thing is that uCLinux doesn't have those functions there (binary crashes).

please advice.

Daniel

**Comment by haberman** [comment]
Out of curiosity, does your platform support C++11 atomics?

Specifically, can you compile this program successfully?

```cpp
#include <atomic>

std::atomic_char x;
```

You may have to pass a compiler flag like `-std=c++11`, like:

```
g++ -std=c++11 -c -o test.o test.cc
```

**Comment by xfxyjwf** [comment]
Hi @dldg, we don't have the environment to test the code on arm and the current arm support is mostly contributed by protobuf users. If you find a solution to the problem, feel free to send us a patch. The C++11 atomics suggested by @haberman may be a viable option.
