### ISSUE TITLE
fixed64 is not fixed length

### ISSUE THREAD

**Issue by realcr** [google/protobuf#1200]
Hi,
I have problems with the size of fixed64 field when I assign it to be 0.
I am using protobuf-cpp-3.0.0-beta-2.tar.gz

Example:

	syntax = "proto3";
	package my_message;

	message MyMessage {
	  bytes field1 = 1;
	  fixed64 field2 = 2;
	}

The message is 9 bytes shorted when I set field2 to be 0.

        my_mess.field1 = b'A' * 16
        my_mess.field2 = 1

        len(my_mess.SerializeToString())  # 27
        my_mess.field2 = 0
        len(my_mess.SerializeToString()) # 18

I expected that the result for both len() invocations will be the same, because I used a fixed size field.
Thank you for your help.

**Comment by haberman** [comment]
When you use syntax=proto3, scalar fields are not serialized onto the wire if they are `0`, `false`, or `""`. So even though the field is fixed-size, it is not being serialized at all in the second case, so the serialized proto is shorter.

The goal of fixed-size fields is not to create a predictable serialization length, it is to speed up encoding and decoding compared to the varint-based types like `int32`, `int64`, etc.

**Comment by realcr** [comment]
Thank you for your quick reply :)
