### ISSUE TITLE
Unable to add nuget to Portable Library in mono

### ISSUE THREAD

**Issue by jake1164** [google/protobuf#1201]
I can create a .NET library but when trying to create a cross platform it states it is not compatible.

I have tried all combinations of the library (framework 4.0, 4.03, 3.5, no windows phone, no windows phone silverlight) without any luck.

Could not install package 'protobuf40 3.0.0'. You are trying to install this package into a project that targets 'portable-net45+win+wp80', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by jskeet** [comment]
It looks like you're installing a package other than the one this project is responsible for - you want the `Google.Protobuf` package, not `protobuf40`.

**Comment by jake1164** [comment]
Absolutely correct.. I didnt click pre-release to see google.protobuf.
