### ISSUE TITLE
JsonFormat Parser rejects messages with unknown fields

### ISSUE THREAD

**Issue by simonhorlick** [google/protobuf#1202]
This seems to go against the spirit of protocol buffers. I expect that the addition of new fields to JSON should be backwards-compatible. Is this by design?

The code in question is: https://github.com/google/protobuf/blob/master/java/util/src/main/java/com/google/protobuf/util/JsonFormat.java#L1126

**Comment by haberman** [comment]
Yes, this was an explicit choice. It was decided that JSON format would not have the same backward-compatibility guarantees as binary format. Some of the backward-compatibility guarantees are impossible to guarantee with JSON format (like compatibility in the face of field name changes).

In the case of unknown fields, they can't be properly converted to protobuf binary format or preserved, so it was decided to fail the parse.

We don't fail the parse for unknown fields in protobuf even though the same things are true. Maybe it is to try and protect against misspelled field names. @xfxyjwf might be able to offer more rationale about this choice.
