### ISSUE TITLE
Prune targets in C# nuspec file

### ISSUE THREAD

**Issue by jskeet** [google/protobuf#1203]
When installing `Google.Protobuf` in a regular .NET 4.5 desktop console app, a lot of extra NuGet packages are installed (System.IO etc). These make sense for .NET Core, but not when targeting the desktop framework. The dependencies should be conditional.

**Comment by jtattermusch** [comment]
I think the existing depdendencies are already supposed to be conditional.
The dependencies generated by ReferenceGenerator nuget package add a sections with target "dotnet" to our nuspec file.
https://github.com/google/protobuf/blob/master/csharp/src/Google.Protobuf/Google.Protobuf.nuspec#L18

I thought the idea in https://oren.codes/2015/07/29/targeting-net-core/ was that the "dotnet" target is an umbrella for "new unknown frameworks" (like dnxcore and aspnet), so for a traditional .NET project (targeting .NET 4.5 like in your scenario), these dependencies should not be picked up. If they are, that is a de facto bug in https://github.com/onovotny/ReferenceGenerator.

@onovotny, if you could take a quick look at our .nuspec file and share your opinions, that would be very helpful: https://github.com/google/protobuf/blob/master/csharp/src/Google.Protobuf/Google.Protobuf.nuspec#L18Thanks!

**Comment by jskeet** [comment]
Thinking about it more, it's possible that we should have a separate build for each target - as each one will end up with different dependencies, which should be reflected in the IL. @mmdriley has been looking at the same thing for the Google API Client library. I really like the simplicity of having a single project and a single configuration (modulo debug/release) but I can see how building each platform against the appropriate dependencies might make more sense.

Over time, I expect that moving over to DNX might make this simpler (I really hope so).

I may experiment with this in a separate branch - probably using a VS shared project as per Matt's client library work.

**Comment by jskeet** [comment]
It's definitely picking up those packages as dependencies for a .NET 4.5 console app. Here's my nuget log:

```
Attempting to gather dependencies information for package 'Google.Protobuf.3.0.0-beta2' with respect to project 'ProtoConsole45', targeting '.NETFramework,Version=v4.5'
Attempting to resolve dependencies for package 'Google.Protobuf.3.0.0-beta2' with DependencyBehavior 'Lowest'
Resolving actions to install package 'Google.Protobuf.3.0.0-beta2'
Resolved actions to install package 'Google.Protobuf.3.0.0-beta2'
Package 'System.Collections.4.0.0' already exists in folder 'C:\Users\Jon\Test\Projects\Sandbox\packages'
Added package 'System.Collections.4.0.0' to 'packages.config'
Successfully installed 'System.Collections 4.0.0' to ProtoConsole45
Package 'System.Diagnostics.Debug.4.0.0' already exists in folder 'C:\Users\Jon\Test\Projects\Sandbox\packages'
Added package 'System.Diagnostics.Debug.4.0.0' to 'packages.config'
Successfully installed 'System.Diagnostics.Debug 4.0.0' to ProtoConsole45
Package 'System.Globalization.4.0.0' already exists in folder 'C:\Users\Jon\Test\Projects\Sandbox\packages'
Added package 'System.Globalization.4.0.0' to 'packages.config'
Successfully installed 'System.Globalization 4.0.0' to ProtoConsole45
Package 'System.IO.4.0.0' already exists in folder 'C:\Users\Jon\Test\Projects\Sandbox\packages'
Added package 'System.IO.4.0.0' to 'packages.config'
Successfully installed 'System.IO 4.0.0' to ProtoConsole45
Package 'System.Linq.4.0.0' already exists in folder 'C:\Users\Jon\Test\Projects\Sandbox\packages'
Added package 'System.Linq.4.0.0' to 'packages.config'
Successfully installed 'System.Linq 4.0.0' to ProtoConsole45
Package 'System.Linq.Expressions.4.0.0' already exists in folder 'C:\Users\Jon\Test\Projects\Sandbox\packages'
Added package 'System.Linq.Expressions.4.0.0' to 'packages.config'
Successfully installed 'System.Linq.Expressions 4.0.0' to ProtoConsole45
Package 'System.ObjectModel.4.0.0' already exists in folder 'C:\Users\Jon\Test\Projects\Sandbox\packages'
Added package 'System.ObjectModel.4.0.0' to 'packages.config'
Successfully installed 'System.ObjectModel 4.0.0' to ProtoConsole45
Package 'System.Reflection.4.0.0' already exists in folder 'C:\Users\Jon\Test\Projects\Sandbox\packages'
Added package 'System.Reflection.4.0.0' to 'packages.config'
Successfully installed 'System.Reflection 4.0.0' to ProtoConsole45
Package 'System.Runtime.4.0.0' already exists in folder 'C:\Users\Jon\Test\Projects\Sandbox\packages'
Added package 'System.Runtime.4.0.0' to 'packages.config'
Successfully installed 'System.Runtime 4.0.0' to ProtoConsole45
Package 'System.Runtime.Extensions.4.0.0' already exists in folder 'C:\Users\Jon\Test\Projects\Sandbox\packages'
Added package 'System.Runtime.Extensions.4.0.0' to 'packages.config'
Successfully installed 'System.Runtime.Extensions 4.0.0' to ProtoConsole45
Package 'System.Text.Encoding.4.0.0' already exists in folder 'C:\Users\Jon\Test\Projects\Sandbox\packages'
Added package 'System.Text.Encoding.4.0.0' to 'packages.config'
Successfully installed 'System.Text.Encoding 4.0.0' to ProtoConsole45
Package 'System.Text.RegularExpressions.4.0.0' already exists in folder 'C:\Users\Jon\Test\Projects\Sandbox\packages'
Added package 'System.Text.RegularExpressions.4.0.0' to 'packages.config'
Successfully installed 'System.Text.RegularExpressions 4.0.0' to ProtoConsole45
Package 'Google.Protobuf.3.0.0-beta2' already exists in folder 'C:\Users\Jon\Test\Projects\Sandbox\packages'
Added package 'Google.Protobuf.3.0.0-beta2' to 'packages.config'
Successfully installed 'Google.Protobuf 3.0.0-beta2' to ProtoConsole45
========== Finished ==========
```

Will investigate this further.

**Comment by jskeet** [comment]
Aha - it looks like actually we just need to add

```xml
<group targetFramework="net45" />
<group targetFramework="wp8" />
<group targetFramework="win8" />
<group targetFramework="wpa81" />
<group targetFramework="xamarin.ios" />
<group targetFramework="monotouch" />
<group targetFramework="monoandroid" />
```

into our nuspec file, according to https://github.com/onovotny/ReferenceGenerator.

(We don't explicitly mention xamarion.iso/mono* in our nuspec file. It's possible that we should...)

**Comment by onovotny** [comment]
One gotcha to be aware of if you add these-- this works if the lib you're putting in `lib\dotnet` is a PCL 259 but you may run into issues down the line if you try to use a newer set of .net core libs to light-up additional functionality.

The core issue is that specific TFM > dotnet > portable-. So that if you want one that supports the newer profiles in .NET 4.6 version, .NET Core and Windows 10 UWP, you'll need to duplicate the dependency entries for two of them or the .NET 4.6 will hit resolve to the blank `net45` group and the UWP ver will hit the blank `win8` group.

Hopefully this will get more straightened out with the upcoming tooling support for `netstandard` where the compatibility bands are more well defined. In that case, you'd be able to say `netstandard1.0` for this lib and then later `netstandard1.4` to have a version with more functionality on later platforms.

**Comment by onovotny** [comment]
Getting to the root of this though is that these NuGet packages are essentially the same as the reference assemblies in the project system. 

Some of them are blank references but others do contain shims. For example, take `System.Reflection.Extensions`. It has a `ref\dotnet` assembly for referencing everywhere but then it's implementation is `_._` for most of the `lib` TFM's. However for .NET Core and UWP, it does provide a shim dll in there.

So overall, I think it's best to let things alone and leave the packages. There's really no harm in having them. I have a blog post coming later this morning that will help ease the pain of `packages.config` too, showing how any project type can switch to using `project.json` for its NuGet references. Then you won't even see these dependencies anymore.

**Comment by onovotny** [comment]
As promised, here's that post on how to use project.json with all project types: https://oren.codes/2016/02/08/project-json-all-the-things/

**Comment by jskeet** [comment]
@onovotny Thanks for that. Will strongly consider using the project.json file approach... although it does feel slightly risky making a change like that reasonably close to release. I need to reread your blog post at least a few times :)

Could you clarify a bit further what the risks are in adding the "empty dependency set" for specific runtimes into the nuspec file? Unless there's a really strongly compelling reason not to make the change, I'd really like to add those in so that a regular user doesn't see a bunch of dependencies which don't make sense to them. Even though we know they're harmless, it's still definite friction. I think it's very unlikely that we're going to want a newer set of .NET core libraries any time soon - and when we do, I think having some redundancy in the nuspec file is a reasonably small price to pay. If there are more worrying reasons which would actually limit what we could do in the future, I'd be very interested to hear about them.

**Comment by onovotny** [comment]
There is no real issue if you're sticking to the PCL 259 set right now. What's unknown is the role that dependencies will play with CLI but presumably they'll just read from the `dotnet` or `netstandard` section.

The risk comes later if you want to use a newer set of libraries and you very-well might. Sockets, File and a ton more stuff are in the later profiles. The surface area of .NET Core is way bigger than PCL 259. Once Xamarin & Mono support it, and support is coming, then you might find yourself constrained by the 259 profile.

So at that point, you have some current functionality and you then want more. You'll need an empty net45 group but then the dependencies in net46, uap10.0, Xamarin, etc. just to "unblock" that version from the dependencies. Because platform TFM > dotnet. I assume platform TFM > netstandard too for the same reasons of being able to override.

**Comment by jskeet** [comment]
Right, thanks for that. It sounds like that's a risk worth taking then (in terms of the pain not really being terribly large).
