### ISSUE TITLE
Introduction of GeneratedCodeInfo in descriptor.proto breaks C#

### ISSUE THREAD

**Issue by jskeet** [google/protobuf#1209]
We already have a public class called GeneratedCodeInfo in the Google.Protobuf namespace in C#.

In commit 5221dcbe, a message called GeneratedCodeInfo was introduced into `descriptor.proto` - which leads to another class being created with the same name.

I suspect that we'll need to rename the library class in order to fix this.

// cc @jtattermusch

**Comment by haberman** [comment]
This appears to be fixed in the attached merged change. Closing this issue.
