### ISSUE TITLE
Default value for repeated fields

### ISSUE THREAD

**Issue by xdmiodz** [google/protobuf#1211]
It's rather a feature request, that an issue. I think it will be useful to have an ability to set default values for primitive repeated fields, like this:

```
message Foo {
    repeated int32 bars = 1 [default = [1, 2, 3]];
}
```

**Comment by atvanguard** [comment]
Hey, any brainstorming on this yet?

**Comment by haberman** [comment]
Hi there,

I think this is unlikely to happen any time soon. This would be a substantial change we'd have to implement in every language (and would likely have practical challenges in some languages), and we haven't heard a lot of demand for it.

Do remember that you can attach custom options to fields. It would totally be possible for you to write:

```
syntax = "proto3";

import "google/protobuf/descriptor.proto";

message MyDefault {
  repeated int32 default = 1;
}

extend google.protobuf.FieldOptions {
  MyDefault my_default = 123456;
}

message M {
  repeated int32 x = 1 [(my_default) = {default: [1, 2, 3]}];
}
```
