### ISSUE TITLE
Ruby client should be able to be configured to emit default fields in JSON

### ISSUE THREAD

**Issue by kellydunn** [google/protobuf#1216]
Much like the Java client's recent ability to emit default fields in JSON (as of [v3.0.0-beta2](https://github.com/google/protobuf/releases/tag/v3.0.0-beta-2)), I would personally like to be able to do the same in ruby.  While decoding and encoding protobufs on their own can provide us with default values, sometimes its necessary for these default values to exist in JSON bodies.  

Perhaps the `encode_json` method could be altered such that it could accept an additional, optional, configuration hash that could indicate the desire to emit default values.  Maybe something like this?

``` ruby
MyWireObj.encode_json(msg, {include_default_values: true})
```

Thanks!

**Comment by vanvlack** [comment]
see the todo here: https://github.com/google/protobuf/blob/24fe6ba750bf8a247d41fc589460dce1bdd697a1/ruby/ext/google/protobuf_c/encode_decode.c#L836-L843

Would be good to have this

**Comment by haberman** [comment]
Agreed. PRs for this would be welcome -- unfortunately there are a lot of things higher on our priority list right now.

**Comment by vanvlack** [comment]
@haberman any news on this?

**Comment by acozzette** [comment]
No, there's nothing more to report for now; unfortunately we're still busy with other things but pull requests would be welcome.
