### ISSUE TITLE
Using protobuf as cmake Submodule

### ISSUE THREAD

**Issue by aspeteRakete** [google/protobuf#1219]
Following Use-Case:
I use protobuf as a submodule for a library:
I can't include it without using include_directory(), although the CMakeLists.txt file  specifies:
https://github.com/google/protobuf/blob/master/cmake/libprotobuf.cmake#L60
So in theory i would just have to call:
target_link_libraries(mylib libprotobuf) to get the includes into my library. This is not the case because of a line in install.cmake, where you rewrite the INTERFACE_INCLUDE_DIRECTORIES:
https://github.com/google/protobuf/blob/master/cmake/install.cmake#L8
Internally I commented out the include(install.cmake) to make this work for me. (Obviously I don't install anything, here). I don't want to use include_directories, because it would have to include it everywhere I use protobuf and in every target which links my library. I want the include dependencies pulled in transitively.

**Comment by xfxyjwf** [comment]
Hi @aspeteRakete, sorry but I don't know cmake well enough to fix this. Could you suggest a fix to the issue?

**Comment by anandolee** [comment]
Closing it as no response from users
