### ISSUE TITLE
Ruby library v3.0.0.alpha.5.0.1 broken

### ISSUE THREAD

**Issue by marcinwyszynski** [google/protobuf#1221]
```
/usr/local/bundle/gems/google-protobuf-3.0.0.alpha.5.0.1-x86_64-linux/lib/google/protobuf.rb:50:in `require': libruby.so.2.3: cannot open shared object file: No such file or directory - /usr/local/bundle/gems/google-protobuf-3.0.0.alpha.5.0.1-x86_64-linux/lib/google/protobuf_c.so (LoadError)
```

**Comment by nicolasnoble** [comment]
Yes, I've noticed that, and I've republished new gems almost immediately. I'm surprised you managed to get that in-between release I've done ? It should be 3.0.0.alpha.5.0.2: https://rubygems.org/gems/google-protobuf

**Comment by marcinwyszynski** [comment]
Maybe it would be a good idea to yank the borked version?

**Comment by nicolasnoble** [comment]
I thought I did. I'll do that now :-)

**Comment by marcinwyszynski** [comment]
![borat-dancing](https://cloud.githubusercontent.com/assets/571786/12961226/a0d4ff66-d03f-11e5-9dea-560e98fc5c3c.gif)

**Comment by haberman** [comment]
Thanks Nicolas. Closing this bug.
