### ISSUE TITLE
proposal: add MimeValue type

### ISSUE THREAD

**Issue by chai2010** [google/protobuf#1227]
```proto
message MimeValue {
    string content_type = 1;
    bytes content_data = 2;
    bool is_static = 3;
}
```

If the RPC method return a MimeValue type,
it can be transformed to http file.

**Comment by haberman** [comment]
Hi there -- what you are describing is outside the scope of protobufs. While protobufs do have well-known types for things like `Any` and `Struct`, these are basic data structures. MIME values and HTTP files are more domain-specific than anything protobufs have baked in.
