### ISSUE TITLE
Yanked gems

### ISSUE THREAD

**Issue by bobbytables** [google/protobuf#1228]
Are gems being automatically yanked now?

**Comment by haberman** [comment]
@nicolasnoble ?

**Comment by nicolasnoble** [comment]
No, it's mainly me doing a lot of fat fingering. Sorry.

**Comment by bobbytables** [comment]
Ok. We just noticed that we couldn't build our project a couple of times after updating the gem to the newest after the yanks.

**Comment by nicolasnoble** [comment]
I'm actually interested in knowing more what you ran into ? Is everything fine now ? And the yanked gems were basically non-working.

**Comment by bobbytables** [comment]
We just couldn't bundle. The yanked gems got ripped off of the RubyGems CDN, so when our project was bundling on CI it would fail harshly trying to install them.

**Comment by nicolasnoble** [comment]
I see, sorry about that. It seems a bit of a fragile system. Why didn't it pick up the next versions however ? Did you have a lock on the package ? Wasn't '~>' helping ?

**Comment by bobbytables** [comment]
We had strict locking due to the nature of it being in "alpha" state so we
didn't want it to update underneath us. We use `~>` now.

On Fri, Feb 12, 2016 at 1:45 PM, Nicolas Noble <notifications@github.com>
wrote:

> I see, sorry about that. It seems a bit of a fragile system. Why didn't it
> pick up the next versions however ? Did you have a lock on the package ?
> Wasn't '~>' helping ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/google/protobuf/issues/1228#issuecomment-183446017>.
>



-- 
- Robert Ross

**Comment by nicolasnoble** [comment]
Understood. Thanks for the detailed explanation.

**Comment by bobbytables** [comment]
My pleasure! Keep up the great work!

On Fri, Feb 12, 2016 at 1:51 PM, Nicolas Noble <notifications@github.com>
wrote:

> Understood. Thanks for the detailed explanation.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/google/protobuf/issues/1228#issuecomment-183447886>.
>



-- 
- Robert Ross
