### ISSUE TITLE
`json_format` should provide a way to load json into a Message

### ISSUE THREAD

**Issue by SimplicityGuy** [google/protobuf#1235]
Similar to the standard string to Message deserializer (`ParseFromString`), the either the generated class should provide a way to `ParseFromJSON` or the `json_format` class should provide a way to do so if JSON serialization is optionally supported.

**Comment by haberman** [comment]
I don't believe there are any plans right now to offer direct parsing/serialization from JSON to `Message` objects in C++. It is trickier than it sounds, and JSON<->protobuf transcoding can provide this functionality, though it is a two-step process.

We might possibly offer this someday so I'll leave the bug open.

**Comment by alfredkcp** [comment]
There exist `MessageToJsonString` and `JsonStringToMessage` since beta 3.0.
This issue should be closed now.

**Comment by xfxyjwf** [comment]
Yes, utility functions to convert between message and JSON already exists. Note that it's just a convenient wrapper on top of the JSON -- protobuf transcoding layer.
