### ISSUE TITLE
`ScalarMap` should provide a way to convert to native dictionaries

### ISSUE THREAD

**Issue by SimplicityGuy** [google/protobuf#1236]
The `ScalarMap` is a dictionary, however there is no built in mechanism to convert it to a language-native dictionary.

**Comment by haberman** [comment]
Is there a reason that `dict(mymsg.mymap)` won't work for you?

**Comment by haberman** [comment]
Since `dict(protobuf_scalar_map)` does what you are requesting, I'm closing this issue. Please re-open if there is something I've missed.

**Comment by SimplicityGuy** [comment]
Cool, that works perfectly. Thank you for pointing that out.
