### ISSUE TITLE
 Protobuf  with ZMQ (majordomo) floating point issue

### ISSUE THREAD

**Issue by GESTIFANOS** [google/protobuf#1238]
Not sure if this is protobuf or zmq  or my code  issue, but I have encountered an issue
I have striped it out to a simple message definition command.proto  with minimized code code  snippet 
  
``` 
  package command_message;
  message Command {
       optional double move = 1;
  }
```

# MajorDemo Client on Python + Django
    client = mdcliapi2.MajorDomoClient("tcp://localhost")
    commandProto = dict_to_protobuf(command_pb2.Command(), {'move': 1.1})
    client.send('COMMAND_HANDLER', commandProto.SerializeToString())
    reply = client.recv()

# MajorDemo Server C/C++
     command_message::Command command;   
     mdwrk_t *session = mdwrk_new ("tcp://localhost", "COMMAND_HANDLER");
     while (true) {
         zmsg_t *request = mdwrk_recv (session, &reply);
         if (request == NULL)
              break;
         command.ParseFromString(zmsg_popstr(request));
         std::cout<<command.parameter().slowjogspeed();
         reply = request;
     }

This will print out 1.0 which is as expected, but the moment I removed significant values, or provide int values e.g  {'move': 4} then it will be converted to 0 , not sure if it is a cast issue or null value.

Is it a know issue or am I introducing it ? thanks for the help or redirecting me to the appropriate parties.

FYI ..
I am compiling for an arm-linux-gnueabihf host on my PC (Ubuntu 14 ) and copy over libs to  Beagle Bone Black(BBB).

Let me know if you need more info

**Comment by haberman** [comment]
I don't quite follow, who is setting `slowjogspeed()` and what are they setting it to?

For the purposes of this report it would be best if you could remove ZeroMQ from the equation and just show protobuf parse/serialize calls.

**Comment by GESTIFANOS** [comment]
Sorry,  that was a carried over code, that line need to be replaced by 
std::cout<<command.parameter().move();

**Comment by haberman** [comment]
Again, please reduce this to a test case that doesn't involve ZeroMQ. Protobuf just deals in strings, so if this is a problem with protobuf, you should be able to reproduce the problem without the ZeroMQ step.
