### ISSUE TITLE
Many methods in CodedInputStream are missing const qualifier

### ISSUE THREAD

**Issue by vlovich** [google/protobuf#124]
Public methods missing const qualification, at least.  Could be others + other private functions that could/should be marked const.

ConsumedEntireMessage
GetDirectBufferPointerInline
BytesUntilLimit
LastTagWas
ExpectTagFromArray

**Comment by xfxyjwf** [comment]
As an IO stream class, it doesn't seem useful to have these methods marked as const even if they don't mutate the stream's state.
