### ISSUE TITLE
C++ JsonToBinaryStream losing large uint32 values

### ISSUE THREAD

**Issue by ronnnnnnnnnnnnn** [google/protobuf#1243]
I'm using the proto3 C++ library compiled in MSVC, and noticed some pretty strange behavior - using the JsonToBinaryString or JsonToBinaryStream functions, values in the upper half of the uint32 range get lost in the transition from JSON to binary.

After some investigation, it seems the issue's root cause is in the MathUtil::Sign function (called from NumberConvertAndCheck, which is called from DataPiece::GenericConvert, which gets called from DataPiece::ToUint32...)

When compiled in Release mode (with optimizations), the ternary condition operator in that function gets optimized incorrectly (the assembly code generated looks as if it's treated as int32 instead of uint32), causing the Sign function to return an incorrect result in the case of those larger uint32 values, which in turn causes a condition in some if statement in NumberConvertAndCheck to evaluate to false when it should be true, thus causing the value to be dropped.

Now obviously this is not really a protobuf issue, but a compiler bug ([opened an issue regarding this with Microsoft](https://connect.microsoft.com/VisualStudio/feedback/details/2332293/vc-ternary-conditional-operator-optimization-bug)), but  since protobuf does support MSVC compilers and since it's likely to be a while until the compiler issue is addressed if at all, I would suggest that until then the issue should probably be handled with a workaround in the protobuf code, for instance by changing that ternary condition operator to a simple if-else statement (seems to compile correctly, without this issue), or simply removing optimization flags when compiling with VS2010/VS2012/VS2013/VS2015, although this is probably a less desirable solution.

**Comment by haberman** [comment]
Thanks for tracking this down so thoroughly!

Just to repeat what you put in the other bug:

> The issue occurs in VS2010, VS2012, VS2013 and VS2015, but not in VS2008.

I looked at your bug report with Microsoft. I wonder if the Microsoft compiler is getting the usual arithmetic conversions slightly wrong. I know you said that changing the ternary operator to if/else solves the problem. I'm curious whether changing `0` to `0U` in your test function fixes the problem also?

**Comment by ronnnnnnnnnnnnn** [comment]
Changing the `0` to `0U` doesn't seem to fix the problem.
Interestingly, though, replacing it with a variable containing `0` does fix the problem.

**Comment by haberman** [comment]
Ok, it seems like the simplest fix then is to change `MathUtil::Sign()` to use explicit if/else instead of the ternary operator. And this fixes the problem on all of those compiler versions?

Also is this caught by the test suite we have in the protobuf repo?

**Comment by ronnnnnnnnnnnnn** [comment]
Tried it on VS2010, VS2012 and VS2015, and using explicit if-else fixed it on all of them. I imagine that should also be the case for VS2013, but I don't currently have access to check for sure.

No idea about the protobuf repo test suite, haven't used it.

**Comment by kientzle** [comment]
As I pointed out elsewhere, MathUtil::Sign is also broken because the return values are wrong:  It should return 1 or -1 instead of value or -value.  This breaks a number of conformance test cases.
