### ISSUE TITLE
What tool does this project use to generate ref manual from c++ headers?

### ISSUE THREAD

**Issue by tamaskenez** [google/protobuf#1246]
There is almost no markup noise.

**Comment by xfxyjwf** [comment]
We use doxygen plus some custom tools to generate the C++ reference. doxygen generates the initial output and it's then processed by some custom tools we build by ourselves to get the final html output.

**Comment by tamaskenez** [comment]
Thanks, but then how come there's no doxygen markup in the headers? Do you have another custom tool which decorates the raw headers with doxy-markup?

**Comment by xfxyjwf** [comment]
Yes, the cross-links in the documentation are added by one of the custom tools.

**Comment by tamaskenez** [comment]
And also replace `//` with `///`, I guess.
Okay, thank you, I'm closing this.
