### ISSUE TITLE
extract_includes.bat file path with spaces does not copy header files

### ISSUE THREAD

**Issue by ejsd1989** [google/protobuf#1264]
I wanted to post to the group page prior to posting anything on here, just in case my issue is created by my own setup. But i'm not sure if it posted there. So here we go posting it directly to the github.

This was during an attempt to just get the tutorial working. 

I'm running on a Windows 10 system, and using VS 2013.

I was attempting to run the extract_includes.bat in my release directory that was compiled using nmake, and nothing was copying over. Running tests.exe worked fine though.

In either case, I needed to modify the .bat file to include quotes ("") around the file paths that had spaces.

**Edit** Is this something related to the install.cmake file? Is there a need to parse the PROTOBUF_SOURCE_WIN32_PATH to check and adjust for spaces? Or am i just making things up?

I'm not sure if this is necessarily an issue or just due to my setup. I'd be interested in perhaps tracking down how the .bat is being created and see if it's related to the actual creation. But, i don't want to go searching down a rabbit hole if it's just a problem that i created myself.

Any tips or suggestions? 

Thanks.

**Comment by xfxyjwf** [comment]
This is a known issue. The current setup of extract_includes.bat doesn't allow spaces in file paths.

**Comment by ejsd1989** [comment]
@xfxyjwf i see. Given that it's a known issue, should my issue post remain?

Also, is anyone currently assigned/attempting to solve the issue?
