### ISSUE TITLE
vs version number doesn't match build requirement

### ISSUE THREAD

**Issue by ykwd** [google/protobuf#1265]
The newest version of c# code use c# 6 so that it can only be compiled use vs2015. 
So maybe there is a need to update the version number in csharp/src/Google.Protobuf.sln which currently is : 
```
# Visual Studio 2013
VisualStudioVersion = 12.0.31101.0
MinimumVisualStudioVersion = 10.0.40219.1
```

Otherwise if one his installed both vs2013 and vs2015, the vs version selector will automatically start vs2013 to open the project, which will cause the building failed due to c# 6.

**Comment by xfxyjwf** [comment]
Should be fixed by https://github.com/google/protobuf/pull/1267
