### ISSUE TITLE
inconsistency with repeated field in python generated code

### ISSUE THREAD

**Issue by srmerritt** [google/protobuf#1273]
Python generated code is inconsistent about which operations on a repeated field cause the containing message to exist.

Given a proto definition:

```
message Container {
    optional MaybeList maybeList = 1;
}

message MaybeList {
    repeated string items = 1;
}
```

The goal is creating a Container which has a MaybeList whose 'items' field is empty. This doesn't work as you would expect. The following code results in a Container with unset maybeList:

```
c = Container()
c.maybeList.items.extend([])
assert c.HasField('maybeList') # fails
```

However, the following code _does_ result in a Container with a set maybeList, with empty items:

```
c = Container()
c.maybeList.items.append('foo')
c.maybeList.items.remove('foo')
assert c.HasField('maybeList') # succeeds
```

I've tested this in 2.5 and 2.6.

**Comment by anandolee** [comment]
Fixed in internal code. The fix will be included in next release
