### ISSUE TITLE
Python 3.4+ support ...

### ISSUE THREAD

**Issue by CyanVladimirS** [google/protobuf#1276]
Hello everybody, 

I want to run Caffe with Python 3, which needs Protobuf, but I'm unable to run Protobuf with Python 3.

When I use protobuf from: sudo pip3 install protobuf

I got this error:

Traceback (most recent call last):
  File "/home/lada/diplomka/deep-learning/caffe/python/PyCaffeTest.py", line 10, in <module>
    import python.caffe
  File "/home/lada/diplomka/deep-learning/caffe/python/caffe/**init**.py", line 1, in <module>
    from .pycaffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, RMSPropSolver, AdaDeltaSolver, AdamSolver
  File "/home/lada/diplomka/deep-learning/caffe/python/caffe/pycaffe.py", line 15, in <module>
    import caffe.io
  File "/home/lada/diplomka/deep-learning/caffe/python/caffe/**init**.py", line 4, in <module>
    from .proto.caffe_pb2 import TRAIN, TEST
  File "/home/lada/diplomka/deep-learning/caffe/python/caffe/proto/caffe_pb2.py", line 7, in <module>
    from google.protobuf import reflection as _reflection
  File "/usr/local/lib/python3.4/dist-packages/google/protobuf/reflection.py", line 68, in <module>
    from google.protobuf.internal import python_message
  File "/usr/local/lib/python3.4/dist-packages/google/protobuf/internal/python_message.py", line 848
    except struct.error, e:
                       ^
SyntaxError: invalid syntax

I found somewhere, that I need to download Protobuf BETA, so I did: 
sudo pip3 install protobuf==3.0.0b2 (I tried also b1 version)

However this version still doesn't support Python 3 completlly, because when I run my Caffe script I got this error:

Failed to include caffe_pb2, things might go wrong!
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/google/protobuf/internal/python_message.py", line 1091, in MergeFromString
    if self._InternalParse(serialized, 0, length) != length:
  File "/usr/local/lib/python3.4/dist-packages/google/protobuf/internal/python_message.py", line 1113, in InternalParse
    (tag_bytes, new_pos) = local_ReadTag(buffer, pos)
  File "/usr/local/lib/python3.4/dist-packages/google/protobuf/internal/decoder.py", line 181, in ReadTag
    while six.indexbytes(buffer, pos) & 0x80:
TypeError: unsupported operand type(s) for &: 'str' and 'int'

During handling of the above exception, another exception occurred: ....

Any thoughts?  Any help appreciated, I'm kind of desperate now...

**Comment by xfxyjwf** [comment]
Can you check the version of six installed on your computer? Try "pip3 install --upgrade six"?

**Comment by CyanVladimirS** [comment]
Output from that command is: "Requirement already up-to-date: six in /usr/local/lib/python3.4/dist-packages" 

Thanks for reply.

**Comment by CaffeBin** [comment]
Hi there,
Some issue here. Did you manage to solve it?

**Comment by CyanVladimirS** [comment]
No I did not solve it, I had to use Python 2.7....

**Comment by CaffeBin** [comment]
Already have, six version is 1.10.0

**Comment by Coldmooon** [comment]
face the same problem...

**Comment by CaffeBin** [comment]
Reinstalling with python 3.3 worked for me

**Comment by Coldmooon** [comment]
@CaffeBin Thank you! I installed `python3.5` through `anaconda`. After downgrading to `python3.3`, all the packages including `jupyter` and `ipython notebook` didn't work because these packages are installed with python3.5 ...

**Comment by Coldmooon** [comment]
@CaffeBin After lots of attempts, finally I can let`caffe` work with `python3.5` in `Ubuntu 14.04`. These are what I did:
1) Download anaconda3 2.5 for python 3.5, then install it
2) Download `protobuf 3.0 beta2` , then compile and install it mannually.
3) Run `sudo apt-get install libboost1.55-all-dev`, then make a soft link
```
sudo ln -s /usr/lib/x86_64-linux-gnu/libboost_python-py33.so.1.55.0 /usr/local/lib/libboost_python3.so
```
4) Edit `Makefile.config`. Change `PYTHON_INCLUDE` to the following:
```
PYTHON_INCLUDE := $(ANACONDA_HOME)/include \
                       $(ANACONDA_HOME)/include/python3.5m \
                       $(ANACONDA_HOME)/lib/python3.5/site-packages/numpy/core/include 
```

5) `make all`, `make pycaffe`

**Comment by tpwrules** [comment]
I have fixed this issue with the very latest protobuf from Google's repository and building it as the c++ extension vs pure python.

**Comment by BKZero** [comment]
@Coldmooon 
hi~ i try to follow your hints. but when i install protobuf 3 beta2 mannually, make and make install seems good, but when i enter the python directory and run python setup.py build, i got this:
google/protobuf/any.proto:31:10: Unrecognized syntax identifier "proto3".  This parser only recognizes "proto2".
it seems wrong with something. but i don't know how to fix it. i am a newer to linux. could you give me some hint?
or should i reinstall the ubuntu cause i have installed protobuf2 before. although i uninstall it, but i am not sure if it has effects.

**Comment by andrey-iliyov** [comment]
@Coldmooon Thanks! I installed python3.5 with conda 4.0.5. Steps 2,3 help me! Thanks for your posts!

**Comment by Coldmooon** [comment]
@andrey-iliyov You are welcome~ I'm glad to have helped you.

**Comment by Coldmooon** [comment]
@BKZero To install protobuf, you need to install both `the protocol compiler` and `the protobuf runtime`. See  `overview` section: https://github.com/google/protobuf#overview.

It seems that you have installed `the protocol compiler protobuf2` before and you are trying to use `the protobuf2 compiler` to compile `the protobuf3 python runtime`.

If you follow my hints, the protobuf3 compiler will be installed. So both protobuf2 and protobuf3 exist in your system. If this is the case, you should set `$PATH` to point to `the protobuf3 compiler`
, or you may get that error.

**Comment by autosquid** [comment]
In py3,  `six.indexbytes = operator.getitem` while in py2 it is 
```
    def indexbytes(buf, i):
        return ord(buf[i])
```

I do not known why `operator.getitem(buf,i)` return a  `Str class` (which is beyond my knowledge), but for anyone for a quick (& dirty) hotfix: I redef `six.indexbytpes` in in beginning with that is from py2.

**Comment by autosquid** [comment]
can we just redef it as:

```
def indexbytes(buf, i):
        return ord(buf[i])
```

?

**Comment by autosquid** [comment]
Hi @Coldmooon , it seems you have solved your original problem (i.e. TypeError: unsupported operand type(s) for &: 'str' and 'int') -- is that true？

**Comment by autosquid** [comment]
Actually， I am wondering if this is right：
···six.indexbytes(buffer, pos) & 0x80···

`six.indexbytes` return a byte, and how could a byte & an int?

**Comment by autosquid** [comment]
ok, I figured it out in my case. 

Note the `ParseFromString` is  error prone for a pythoner -- it is in fact ParseFromBytes.

**Comment by arthur-tacca** [comment]
I had this problem but this fixed it for me: The problem for me is that the C++ version of protobuf on my system was too old; it was version 2.5. The solution was to download version 3.1 (the version matching the Python library installed in my virtual environment) and build and install that (as is standard: `./configure` then `make` then `sudo make install`). If you do that right it should end up in `/usr/local/`, and `protoc --version` should show 3.1. Don't forget to add `/usr/local/lib` to your `LD_LIBRARY_PATH` environment variable. You then need to rebuild caffe. (The native library is important because it affects the protocol buffer compiler `protoc`, as @Coldmooon said, and caffe uses that to generate the `caffe_pb2.py` file.)

I think this might actually be what others are talking about earlier in this thread, but I was confused by @tpwrules saying "building it as the c++ extension vs pure python" because there are two versions of the Python protobuf library, one is C++ and the other pure Python, and I thought that was the distinction being made. In fact what is important is the native code protobuf library, which is nothing to do with Python at all.

**Comment by momozizi** [comment]
hello
I have installed Anaconda, cafee and cuda on windows 7. then I want to start with caffe. So I run cmd on caffe root then I type python. But when I type import caffe I have this error:
`>>> import  caffe
Failed to include caffe_pb2, things might go wrong!
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\mohsen\Anaconda3\envs\firstEnvironment\caffe\__init__.py", line
 4, in <module>
    from .proto.caffe_pb2 import TRAIN, TEST
  File "C:\Users\mohsen\Anaconda3\envs\firstEnvironment\caffe\proto\caffe_pb2.py
", line 6, in <module>
    from google.protobuf.internal import enum_type_wrapper
ImportError: No module named 'google'`
 I am beginner to caffe. I do not know what is my problem?

**Comment by trungphan9x** [comment]
@momozizi you should install protobuf package also
