### ISSUE TITLE
c++ parseFromString fails when required int64 was set with 0 from Java client.

### ISSUE THREAD

**Issue by kmayfiel-ibm** [google/protobuf#1277]
Setting a required value to 0 works with Java parse, but fails parse on C++.  Non-zero results in no failure.

my.proto file:
> message Message {
  enum Type {
    A = 1;
    ...
    F = 2002;
  }
  // Identifies which field is filled in.
  required Type type = 1;
  **required int64 num = 2;**
   ...
  optional Type5 t5 = 7;
}

The following Java sender works with Java receiver, but fails with C++ receiver (without a message):
> My.Message.newBuilder().setType(My.Message.Type.A).**.setNum(0).**build();

The following Java sender works with both Java and C++ receivers:
>  My.Message.newBuilder().setType(My.Message.Type.A)**.setNum(1).**build();

**ENVIRONMENT**
* OS = RHEL 7.2
* protoc --version = **2.6.1**
* java -version =   java version "1.8.0_71"
* g++ --version = g++ (GCC) 4.8.5 20150623 (Red Hat 4.8.5-4)

**Comment by xfxyjwf** [comment]
How did you parse the data in C++? It smells like a bug in your C++ parsing code where you passed the data as a C string which terminates prematurely at the first '\0'. Can you verify if the data you are parsing has the same length as sent by the Java sender?

**Comment by kmayfiel-ibm** [comment]
I agree, but the C++ parsing code is the class generated by protoc.  I just hand it the buffer.
If I pass all strings and non-zero integers the C++ code works unchanged.  If I pass a required int == 0 then embedded message (or anything following the required int 0) is not parsed, and error returned.

I have the complete message sent from the Java builder, and in C++:
>   char buffer[BUFLEN];
    bzero(buffer, BUFLEN);
    ... // read length message, and the message from socket.  This works.
    my::Message msg;
    if (!msg.ParseFromString(stringbuffer))
         error("parse failure");

The bug seems to be in a nested message with the empty string or required int32/int64 value.

**Comment by kmayfiel-ibm** [comment]
Also fails with 3.0.0-beta-2

**Comment by kmayfiel-ibm** [comment]
Apparently if we pass the message length, the parse works.
msg.ParseFromString(buffer, nbytes);
