### ISSUE TITLE
Objective-C: why is "packed" the default for repeated int32?

### ISSUE THREAD

**Issue by waltsc** [google/protobuf#1279]
Given this protobuf definition:
```
syntax = "proto3";

message TestMesssage {
  repeated int32 scores = 1;
}
```

The compiler generates a packed array:

```
$ grep -C 7 Packed Test.pbobjc.m 
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "scoresArray",
        .number = TestMesssage_FieldNumber_ScoresArray,
        .hasIndex = GPBNoHasBit,
        .flags = GPBFieldRepeated | GPBFieldPacked,
        .dataType = GPBDataTypeInt32,
        .offset = offsetof(TestMesssage__storage_, scoresArray),
        .defaultValue.valueMessage = nil,
        .dataTypeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
    };
```

This seems wrong, why is this the default behavior? This is with libprotoc 3.0.0 (brew protobuf version 3.0.0-beta-2).

**Comment by xfxyjwf** [comment]
It has been decided that in proto3 repeated primitive fields are packed by default. Do you have any specific need to prefer non-packed repeated fields?

**Comment by waltsc** [comment]
oh, ok. i didn't see that documented anywhere on the web (i do see it now in a comment in descriptor.proto).

the reason is that i'm using https://github.com/dcodeIO/protobuf.js for my server, and that code tries to parse it as non-packed so it fails. i can file a bug or fix it there. it'd be nice if you guys could update the docs to say this somewhere? thanks!

**Comment by xfxyjwf** [comment]
I have created a separate issue for improving the documentation:
https://github.com/google/protobuf/issues/1280

For protobuf.js, sounds like it doesn't support packed fields? If it implements packed fields correctly, it should be able to parse the same repeated field in both packed and unpacked form.
