### ISSUE TITLE
Java: clear() won't really clear the member fields of oneof

### ISSUE THREAD

**Issue by dreamershl** [google/protobuf#1281]
```
   message Response {
          oneof reponse
         {
            ...
           QuotesList quotes = 3;
           ...
         }
    }
```

If call the Response.Builder.clear() function, it will just set the "reponseCase_ = 0;". Then the QuotesList will be left. If the second time, you use the member builder directly like this,

```
      Response.Builder.getQuotesBuilder()
```

 The second time to set the QuotesList value will include the first time values.

**Comment by BSBandme** [comment]
Would you please specific your protobuf version? 
In 3.5.0 the generated code of Builder.clear() does make the message field to be null after set the one case to be 0.

I think this should has been fix.
