### ISSUE TITLE
Check API design and documentation in terms of flushing

### ISSUE THREAD

**Issue by jskeet** [google/protobuf#1282]
Based on https://groups.google.com/forum/#!topic/protobuf/U_lr8TycsWM and the documentation, it's too easy to forget to flush a CodedOutputStream. Either the generated code should flush automatically in WriteTo, or we should make CodedOutputStream implement IDisposable and flush automatically on disposal (which would probably be more idiomatic).

// cc @jtattermusch for thoughts

**Comment by goldenbull** [comment]
The generated code should NOT flush automatically because it may hurt performance significantly. It is a little wired that `CodedOutputStream` is not a derived class of `Stream`. However, make `CodedOutputStream` implement `IDisposable` is a good idea :+1:

**Comment by jskeet** [comment]
CodedOutputStream certainly shouldn't derive from Stream - it isn't a general purpose stream. But yes, if we implement IDisposable in the same way that things like StreamWriter do, it would be simpler.
We already have an issue for that: #679.

**Comment by jskeet** [comment]
I've just looked at the docs again, and they're actually okay - they're calling the `Stream.WriteTo(message)` extension method, which creates a CodedOutputStream, writes to it, and flushes it. But still, implementing IDisposable feels like a good idea.
