### ISSUE TITLE
brew install failing for v3.0.0-beta-2

### ISSUE THREAD

**Issue by deeGraYve** [google/protobuf#1285]
failing to install using `brew` 

> ==> Installing google-protobuf from grpc/grpc
==> Downloading https://github.com/google/protobuf/archive/v3.0.0-beta-2.tar.gz
Already downloaded: /Library/Caches/Homebrew/google-protobuf-3.0.0-beta-2.tar.gz
==> Downloading https://raw.githubusercontent.com/grpc/homebrew-grpc/master/patches/google_protobuf_4472b4a_Fixed-assignment-syntax-error.patch
Already downloaded: /Library/Caches/Homebrew/google-protobuf--patch-47cbaaf7e782b09edb5dcf10ff6b7892af8f506df4d82f71877957de3552afa4.patch
==> Patching
==> Applying google_protobuf_4472b4a_Fixed-assignment-syntax-error.patch
patching file python/google/protobuf/pyext/message.cc
Hunk #1 FAILED at 340.
1 out of 1 hunk FAILED -- saving rejects to file python/google/protobuf/pyext/message.cc.rej
Error: Failure while executing: /usr/bin/patch -g 0 -f -p1 -i /private/tmp/google-protobuf--patch20160226-80317-4tw3x4/google_protobuf_4472b4a_Fixed-assignment-syntax-error.patch

**Comment by xfxyjwf** [comment]
@jtattermusch Could you help take a look? It seems the homebrew script in https://github.com/grpc/homebrew-grpc/blob/master/Formula/google-protobuf.rb is not working.

**Comment by jtattermusch** [comment]
Seems like this has already been fixed.

https://github.com/grpc/homebrew-grpc/pull/79

**Comment by xfxyjwf** [comment]
Thanks! @deeGraYve please try the updated homebrew script in the grpc repo.
