### ISSUE TITLE
msvc/c++ linker error when throw the object

### ISSUE THREAD

**Issue by NeuroProc** [google/protobuf#1288]
I'm using protobuf 3 C++ library compiled in MSVC2015.
I want to throw object generated from the proto message as c++ exception and get the linker error:
unresolved external symbol "private: __thiscall Message::Message(class Message const &)"
unresolved external symbol "private: __thiscall MessageLite::MessageLite(class MessageLite const &)"

I wrote prototype code for error reproducing:

``` c++
class A
{
public:
    A() { };
    ~A() {};
private:
    A(const A &);
};

class B : public A
{
public:
    B() {};
    ~B() {};
    B(const B &) { };
};

int main()
{
    try
    {
        B b;
        throw(b);
    }
    catch(B& e) { }

    return 0;
}
```

This code good compiles in gcc/MinGW/clang and only MSVC fails.

Protobuf have same copy constructor policy for the Message classes:
https://github.com/google/protobuf/blob/master/src/google/protobuf/message_lite.h#L271
https://github.com/google/protobuf/blob/master/src/google/protobuf/stubs/macros.h#L40

temporary fix, what I found: set to the copy constructors c++11 directive "delete" (A::A(const A&) = delete;) this works for MSVC2015, but may not in MSVC2013 or early.

Thanks.

**Comment by TeBoring** [comment]
Close this for clean up. Feel free to reopen if there is still problem.
