### ISSUE TITLE
Cannot easily build universal binary/library for iOS (v2.6.1)

### ISSUE THREAD

**Issue by yaakov-h** [google/protobuf#129]
There's no easy way to build static libraries for iOS.

Building protobuf for iOS generally requires a wrapper build script that:
- Compiles for OS X
- Compiles for `i386` iOS simulator with OS X `protoc`
- Compiles for `x86_64` iOS simulator with OS X `protoc`
- Cross-compiles for `armv7` device with OS X `protoc`
- Cross-compiles for `armv7s` device with OS X `protoc`
- Cross-compiles for `arm64` device with OS X `protoc`
- Uses `lipo` to combine into either one library, or one for `iphoneos` and one for `iphonesimulator` depending on how pedantic the wrapper script author is.

Is there no set of options I can pass to `configure` to support this automatically, and if not, can you please add some way to do this? I shouldn't have to rely on third-party scripts just to compile this project properly for a major target platform.

**Comment by TeBoring** [comment]
I believe we have provided protoc on Mac for all releases after 3.0.0

**Comment by kristian-kt** [comment]
how to build library from source code, the make command only make library for x86_64. how to make library for ARM64?
