### ISSUE TITLE
java generator: do not wrap comments in <pre> tags, do not escape html tags

### ISSUE THREAD

**Issue by estekhin** [google/protobuf#13]
Java generator wraps proto comments in &lt;pre&gt; tag and also html-escapes the comment value.

For example, this proto definition:

```
// <p>a comment</p>
message MyMessage {
}
```

is compiled into this Java source:

```
/**
 * Protobuf type {@code chronos.proto.MyMessage}
 *
 * <pre>
 * &lt;p&gt;a comment&lt;/p&gt;
 * </pre>
 */
public static final class MyMessage extends ...
```

Please change the generator behavior or add an option that will disable this behavior.
When it is enabled, proto comments should be converted into javadoc as is, without wrapping it in any additional tags or performing any escaping.

**Comment by acozzette** [comment]
I am going to go ahead and close this because we are cleaning up issues and I see that this one has not been updated in a long time. Feel free to reopen it if this is still a problem, though.
