### ISSUE TITLE
protoc.exe in protoc-3.0.0-beta-2win32 just generate single-instance java class:

### ISSUE THREAD

**Issue by azurelaker** [google/protobuf#1302]
this version protoc  only generate single-instance java class for a message , can not add different instance into list?

**Comment by xfxyjwf** [comment]
Can you explain the issue in more details? Do you mean the protoc only generates code for one message, but not for other messages in the same .proto file?

**Comment by azurelaker** [comment]
I use this proto file:

`// See README.txt for information and build instructions.
//
// Note: START and END tags are used in comments to define sections used in
// tutorials.  They are not part of the syntax for Protocol Buffers.
//
// To get an in-depth walkthrough of this file and the related examples, see:
// https://developers.google.com/protocol-buffers/docs/tutorials

// [START declaration]
syntax = "proto3";
package tutorial;
// [END declaration]

// [START java_declaration]
option java_package = "com.example.proto";
option java_outer_classname = "AddressBookProtos";
// [END java_declaration]

// [START csharp_declaration]
option csharp_namespace = "Google.Protobuf.Examples.AddressBook";
// [END csharp_declaration]
  
message Person {
    string name = 1;
    int32 id = 2;  // Unique ID number for this person.
    string email = 3;

  enum PhoneType {
    MOBILE = 0;
    HOME = 1;
    WORK = 2;
  }

  message PhoneNumber {
    string number = 1;
    PhoneType type = 2;
  }

  repeated PhoneNumber phones = 4;
}

// Our address book file is just one of these.
message AddressBook {
  repeated Person people = 1;
}
// [END messages]`

then generate the AddressBookProtos.java file, it's content is a little long, not post here.
but can not construct different class instance for class Person, because the constructor of class Person and it's Builder  are both private, and member function of Person:
 `public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }`
always return the same instance.

**Comment by azurelaker** [comment]
I compare the java code generated by protoc 2.6.1 and protoc-3.0.0-beta-2 using the same proto file. 
the member function newBuilder is different, here is the 2.6.1 version:
`public static Builder newBuilder() { return Builder.create(); }
private static Builder create() {
        return new Builder();
      }` 
so it can construct different class instance.

**Comment by xfxyjwf** [comment]
On Mon, Mar 7, 2016 at 7:00 PM, azurelaker <notifications@github.com> wrote:

> I use this proto file:
>
> `// See README.txt for information and build instructions.
> //
> // Note: START and END tags are used in comments to define sections used in
> // tutorials. They are not part of the syntax for Protocol Buffers.
> //
> // To get an in-depth walkthrough of this file and the related examples,
> see:
> // https://developers.google.com/protocol-buffers/docs/tutorials
>
> // [START declaration]
> syntax = "proto3";
> package tutorial;
> // [END declaration]
>
> // [START java_declaration]
> option java_package = "com.example.proto";
> option java_outer_classname = "AddressBookProtos";
> // [END java_declaration]
>
> // [START csharp_declaration]
> option csharp_namespace = "Google.Protobuf.Examples.AddressBook";
> // [END csharp_declaration]
>
> message Person {
> string name = 1;
> int32 id = 2; // Unique ID number for this person.
> string email = 3;
>
> enum PhoneType {
> MOBILE = 0;
> HOME = 1;
> WORK = 2;
> }
>
> message PhoneNumber {
> string number = 1;
> PhoneType type = 2;
> }
>
> repeated PhoneNumber phones = 4;
> }
>
> // Our address book file is just one of these.
> message AddressBook {
> repeated Person people = 1;
> }
> // [END messages]`
>
> then generate the AddressBookProtos.java file, it's content is a little
> long, not post here.
> but can not construct different class instance for class Person, because
> the constructor of class Person and it's Builder are both private, and
> member function of Person:
> public static Builder newBuilder() {
> return DEFAULT_INSTANCE.toBuilder();
> }
> always return the same instance.
>
I believe DEFAULT_INSTANCE.toBuilder() returns a different instance for
each call. Could you check?

**Comment by azurelaker** [comment]
yes,  DEFAULT_INSTANCE.toBuilder() returns a different instance for each call.
but, the code generated by version 2.6.1, i think, is much more reasonable.

**Comment by jinkingmanager** [comment]
just add an option like this:
option java_multiple_files = true;

then you can see what happens
