### ISSUE TITLE
Python: protobuf 3.0.0-alpha1 removed from PyPI

### ISSUE THREAD

**Issue by tseaver** [google/protobuf#1303]
Removing old releases is seriously bad practice:  it damages repeatability of builds, and in this case, breaks the [gcloud 0.7.1 release](https://github.com/GoogleCloudPlatform/gcloud-python/issues/1576), which pinned that version of protobuf.

**Comment by jgeewax** [comment]
@nathanielmanistaatgoogle What? We deleted a release from PyPI ? Why not just archive.... ?

**Comment by xfxyjwf** [comment]
Sorry for the breakage. I removed v3.0.0-alpha-1 because the version schema it uses is wrong and pip thinks v3.0.0-alpha-1 is newer than v3.0.0a3. See:
https://github.com/google/protobuf/issues/855

**Comment by jgeewax** [comment]
Wait... Can't we make it an archived package ? So it wouldn't be one "recommended"? @tseaver Any ideas on how we could fix this?

I would re-open this if I could... we're breaking stuff :(

**Comment by tseaver** [comment]
PyPI has a "hide this release" feature.  Unfortunately, I think we would need help from the PyPI admins to restore the release in order to hide it. @dstuft is the one person I can think of who would know.

**Comment by xfxyjwf** [comment]
I understand that we are breaking stuff, and that's mostly my fault for uploading a package with the wrong name. I'm sorry for that. I don't understand why we want to restore a broken package though. Is that because we had a promise to users that every gcloud release package will work for an indefinite amount of time, even when it has a broken dependency?

**Comment by Solyony** [comment]
@xfxyjwf Now we trying to update to later version of gcloud and if everything will go fine we can close this issue. But maybe there can be more users who use specific version of gcloud which suddenly stops work after next ```pip install -r requirements.txt```
