### ISSUE TITLE
Go Travis tests are broken

### ISSUE THREAD

**Issue by haberman** [google/protobuf#1305]
@tswast can you take a look?

Here is an example: https://travis-ci.org/google/protobuf/jobs/114293020

**Comment by haberman** [comment]
Actually why is this test in our Travis suite to begin with, since the Go source code isn't in this repo?

**Comment by haberman** [comment]
cc: @xfxyjwf

**Comment by xfxyjwf** [comment]
The test only runs the example Go code in the examples directory. It doesn't actually cover Go unittests I believe.

**Comment by haberman** [comment]
But it depends on the Go protobuf library and codegen plugin which do not live in this repo. Doesn't seem like it belongs here.

**Comment by xfxyjwf** [comment]
It also depends on the addressbook.proto file which only exists in this repo. I don't have a strong preference either way.

**Comment by tswast** [comment]
Sorry, I was OOO for a few days. The example error looks to me like the Go generator code now requires Go 1.6. The function `strings.LastIndexByte` was added in https://github.com/golang/go/commit/0fb5475bdf0e5352d7aac67d2ec97c0513ee0af3 which is after the 1.5.3 release and before 1.6 https://github.com/golang/go/releases

I'll update Travis to always use the latest stable version of Go.
