### ISSUE TITLE
Python:  3.0.0b2-post2 still breaks 'gcloud-python' lint tests

### ISSUE THREAD

**Issue by tseaver** [google/protobuf#1307]
See:  https://travis-ci.org/GoogleCloudPlatform/gcloud-python/builds/114377347#L434

Note that the non-lint tests are all passing.

**Comment by tseaver** [comment]
Pinning `protobuf == 3.0.0b2` makes everything happy again.

**Comment by haberman** [comment]
@silviulica 

Looks like post2 might be missing well-known types like timestamp_pb2 and duration_pb2?

**Comment by haberman** [comment]
@tseaver it looks like you're depending on internal-only interfaces like `google.protobuf.internal.type_checkers`. Why are you accessing these interfaces?

**Comment by silviulica** [comment]
@haberman What can cause this? Did I miss some step while building the package or is something that would show up anyway but was hidden by the previous much earlier errors in post1.

**Comment by silviulica** [comment]
I checked and the types are there. So there must be a more subtle reason.
$ pip freeze
...
protobuf==3.0.0b2.post2
...
>>> from google.protobuf import duration_pb2
>>> print duration_pb2
<module 'google.protobuf.duration_pb2' from '/usr/local/google/home/silviuc/miniconda2/envs/pb/lib/python2.7/site-packages/google/protobuf/duration_pb2.pyc'>

**Comment by tseaver** [comment]
> What can cause this? Did I miss some step while building the package or is something that would show up anyway but was hidden by the previous much earlier errors in post1.

As I said, the unit tests pass, which means that the imports actually succeed.  The test that is failing is pylint, which tries to introspect the imports without actually executing them, and fails (under `-post2`).

@haberman we are using the `Int64ValueChecker` to ensure that values assigned to a protobuf `int` field are in range.

**Comment by haberman** [comment]
@tseaver do you have any explanation for why your pylint would be failing when the actual import succeeds?

Also, why do you need to use `Int64ValueChecker` directly to check protobuf int fields? Just try assigning a value to an int field and it will fail if it's out of range.

**Comment by tseaver** [comment]
> Do you have any explanation for why your pylint would be failing when the actual import succeeds?

pylint's model for checking imports is [broken](https://bitbucket.org/logilab/pylint/issues/223) when the source module does "magic" to adjust import paths.

> Also, why do you need to use Int64ValueChecker directly to check protobuf int fields? Just try assigning a value to an int field and it will fail if it's out of range.

I don't recall why we are doing look-before-leap.  https://github.com/GoogleCloudPlatform/gcloud-python/pull/1626 drops it.
