### ISSUE TITLE
Protoc: Allow generation of non-public classes from proto files for C#

### ISSUE THREAD

**Issue by jhickson** [google/protobuf#1311]
In Jon Skeet's original proto2 support for C# you could specify via the command line for ProtoGen.exe that the generated classes should be marked as internal rather than public.  I found this very useful for keeping the public API of my libraries as clean as possible.  Would it be possible to add this functionality to protoc-3?

**Comment by xiangaodielian** [comment]
+1

**Comment by gvaish** [comment]
Created PR at #1346

**Comment by gvaish** [comment]
Created PR at #1347
