### ISSUE TITLE
py_proto_library gets confused when a filegroup is provided for srcs

### ISSUE THREAD

**Issue by davidzchen** [google/protobuf#1313]
Currently, it is not possible to do the following:
## Repository `foo`

`BUILD`:

``` python
filegroup(
    name = "foo_pb_srcs",
    srcs = ["foo.proto"],
)
```
## Repository `bar`

`WORKSPACE`:

``` python
git_repository(
    name = "foo"
    remote = "..."
   ...
)
```

`BUILD`:

``` python
load("@protobuf//:protobuf.bzl", "py_proto_library")

py_proto_library(
    name = "foo_pb",
    srcs = ["@foo//:foo_pb_srcs"],
)
```

I attempted to have this setup where I add a `filegroup` to `//src/main/protobuf` in the Bazel repository for `build.proto` and then have a `py_proto_library` target in a different repository that uses that filegroup (which is available in `@bazel_tools//`. This is the error that I get:

```
❯❯❯ bazel build //skydoc:build_pb
Extracting Bazel installation...
Sending SIGTERM to previous Bazel server (pid=10593)... done.
.......
ERROR: /Users/dzc/Sandbox/skydoc/skydoc/BUILD:5:1: //skydoc:build_pb_genproto: label '@bazel_tools//src/main/protobuf:build_p_pb2.py' is not in the current package.
ERROR: no such package 'skydoc': Package 'skydoc' contains errors.
INFO: Elapsed time: 1.493s
```

**Comment by davidzchen** [comment]
FYI: +@damienmg

**Comment by damienmg** [comment]
We probably have to figure out something on the Bazel side too. @cgrushko is working on internal protobuf and we should probably try to have some convergence between internal and external (especially since the syntax seems to converge). @cgrushko: do you think you can save some time in the following months to help with that?

**Comment by cgrushko** [comment]
Sure. There's one conceptual blocker for this (I sent a doc with 2 possible
solutions, you're CC'ed) and the question of how to maintain an internal
version alongside the external one. Anyway, both problems are surmountable
and I'll get to it soon enough.

**Comment by abergmeier** [comment]
Just got hit by this.
Personally the amount of shortcomings and bugs when using Python + Bazel gets to a point where I am seriously questioning whether there should be any support for Python in Bazel at all.

**Comment by promiseofcake** [comment]
This also happens when using a filegroup from a remote bazel workspace in the `cc_proto_library`

**Comment by xfxyjwf** [comment]
@promiseofcake For cc_proto_library, now you can use bazel's native cc_proto_library support. See an example here: https://github.com/google/protobuf/blob/master/examples/BUILD

**Comment by promiseofcake** [comment]
@xfxyjwf we also need to generate gRPC services and that isn't provided by the native rule.

**Comment by xfxyjwf** [comment]
@promiseofcake From what I can tell gRPC likely won't be supported by the native rule. gRPC team should provide their own build extensions to support gRPC.

**Comment by xfxyjwf** [comment]
@promiseofcake Yes, I think grpc team should provide their own bazel extension. The build extensions we added in protobuf.bzl are just workarounds that I would love to get rid of when bazel supports them natively.
