### ISSUE TITLE
py_proto_library gets confused when source file is in genfiles

### ISSUE THREAD

**Issue by davidzchen** [google/protobuf#1314]
This is a similar issue to #1313. The main difference is that the source file is generated in genfiles:

``` python
load("@protobuf//:protobuf.bzl", "py_proto_library")

genrule(
    name = "foo_pb_srcs",
    srcs = ["@foo//:foo_pb_srcs"],  # this target is a filegroup
    outs = ["foo.proto"],
    cmd = "cp -f $< $@",
)

py_proto_library(
    name = "foo_pb",
    srcs = ["foo.proto"],
)
```

**Comment by davidzchen** [comment]
FYI: +@damienmg

**Comment by fahhem** [comment]
Is there any movement on this issue? Maybe a workaround? I'm using the latest protobuf release (3.5) and the latest bazel release (0.8.0) and when I use a genrule's outs in the srcs of py_proto_library, I get ```output '...._pb2.py' was not created```
