### ISSUE TITLE
Windows Phone 8.1 issue

### ISSUE THREAD

**Issue by dobballa** [google/protobuf#132]
I use protobuf in winrt app for Windows and Windows phone.
I got this message when build for ARM: "Host architecture was not detected as supported by protobuf"
The device is Nokia Lumia 1020. My OS is Windows 8.1, Visual Studio 2013

When is build for x86(run on emulator) everything is fine.

Thank you!

**Comment by xfxyjwf** [comment]
@dobballa , could you try again with the latest versions on the release page? We don't have the test environment for Win Phone + ARM. Any help is appreciated to fix this issue.

**Comment by haberman** [comment]
Closing due to lack of information.
