### ISSUE TITLE
Go: idiomatic variable name

### ISSUE THREAD

**Issue by jtblin** [google/protobuf#1321]
It isn't a major issue but if I have a field name `id` in my definition, the Go code which will be generated will set the field as `Id` instead of `ID` like for idiomatic Go code. Is there a way to hint to the compiler what the variable should be in a specific language so that it stays idiomatic to this language?

Example definition

```
// Job represents a job definition
message Job {
    string id = 1;
}
```

Example generated code

```
// Job represents a job definition
type DeploymentJob struct {
    Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}
```

If we could do something like

```
// Job represents a job definition
message Job {
    string id = 1; `go:"ID"`
}
```

which would then generate

```
// Job represents a job definition
type DeploymentJob struct {
    ID string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}
```

**Comment by xfxyjwf** [comment]
Not familiar with Go, but this seems to be the intended behavior to me. If you name a field "foo", wouldn't the Go field be named "Foo"?

**Comment by jtblin** [comment]
Yes you're right for most of the terms but for others e.g. ID, URL, IP, API Go uses uppercase.

**Comment by haberman** [comment]
The decision from the Go guys in https://github.com/golang/protobuf/issues/156 is to keep the current behavior.
