### ISSUE TITLE
(NUSPEC) protoc.exe is not platform-independent, but is packaged as such

### ISSUE THREAD

**Issue by ananthonline** [google/protobuf#1324]
protoc is a native binary, but the [nuspec](https://github.com/google/protobuf/blob/master/csharp/src/Google.Protobuf/Google.Protobuf.nuspec) packs it [as if it's portable](https://github.com/google/protobuf/blob/master/csharp/src/Google.Protobuf/Google.Protobuf.nuspec). Could this nuspec instead package platform-specific binaries into subfolders like [Grpc.Tools.nuspec](https://github.com/grpc/grpc/blob/master/src/csharp/Grpc.Tools.nuspec) does?

This makes it possible for people to write nuget packages that can choose the protoc binary to execute in a build step based on the OS.

**Comment by haberman** [comment]
@jskeet can you take a look?

**Comment by jskeet** [comment]
Yes, it sounds like we should put it into `tools\windows_x86` - but I don't have any immediate thoughts on the build process to make sure we package multiple versions. @jtattermusch What do you do for grpc? Is it just manual?

**Comment by jskeet** [comment]
As a thought, if we wanted to include the Linux and Mac builds, it might be worth putting into a separate package (Google.Protobuf.Tools) so that anyone who only wanted to consume ready-generated protobufs didn't need to download tools they wouldn't need. (The Windows binary for protoc is about 4MB, compared with the Google.Protobuf assembly of about 300K.)

**Comment by dalebrubaker** [comment]
+1. I really like that idea. It's an executable, not a library. And imho one of the biggest barriers to broader use of protobuf is the need to write long inscrutable command lines just to generate the classes.

**Comment by jskeet** [comment]
@dalebrubaker: I'm afraid that shipping protoc in a separate package won't remove the need to use it - although I expect many clients who then publish protos will also publish the generated classes. (That's what my team is doing, e.g. in https://github.com/GoogleCloudPlatform/gcloud-dotnet)

**Comment by dalebrubaker** [comment]
Yes, true. I just think separation can make the whole process more discoverable. And your size argument is a good one.
And I wish there was a protoc option to find and generate all the proto files in the solution (i.e. in the directory tree under ..\(.

**Comment by ananthonline** [comment]
That's _exactly_ what I'm working on. The mechanism that I use to do so is very similar to the one I've implemented [here](https://github.com/ananthonline/Postal/blob/master/Postal.ProtoBuf/Postal.cs), except the new version I have uses simple built in tasks that seem to work on Visual Studio as well as Xamarin Studio at this time. While this approach doesn't generate cs for all proto files in a solution, it adds a new ItemType to item properties which this enables automatic code generation as part of the build.

+1 for a separate Tools package, this is exactly what I'm trying to create as well. If this project/package is added to this repository, I'll submit my code-generation task here.

**Comment by jtattermusch** [comment]
Hi, sorry for my late response.

Actually, as the dependency on protoc and protoc grpc plugin is a big issue
of gRPC as well, I've recently put some effort into pre-building protoc and
plugin  binaries for windows, linux and mac that should be pretty widely
binary compatible (most popular linux distros, mac os x 10.7+, and most
windows machines) and packaging them into Grpc.Tools nuget package.

The Grpc.Tools package contains both protoc and grpc_csharp_plugin, so
there shouldn't be any need to precompile or preinstall any native
dependecies if you want to use Protobuf C# (and gRPC C#).

There is still no VS integration for actually running protoc (and it is not
clear how exactly that would work or if we are going to do this at all) to
generate C# sources from .protos, so you'll still need to run the protoc
commands yourself.

The first version of Grpc.Tools package that has precompiled protoc for all
platforms is
https://www.nuget.org/packages/Grpc.Tools/0.13.1-pre1 , feel free to try it
out and provide feedback.

If there's a demand for it, we could possibly ship a Protobuf.Tools package
 with  precompiled protoc for various platforms as well.

**Comment by jskeet** [comment]
@jtattermusch: Yes, it feels like shipping precompiled protoc makes more sense as part of a Protobuf package than Grpc - if we ship it in Google.Protobuf.Tools, perhaps Grpc.Tools should just depend on that? I don't think we need them to be in two different places. Do you want to create a pull request with a nuspec file for such a package?

**Comment by jtattermusch** [comment]
@jskeet  I agree having two separate packages Google.Protobuf.Tools  and Grpc.Tools makes more sense in the long run, but the problematic part is the infrastructure setup to build protoc on different platforms and then package everything in a nuget package is not trivial at all and we currently only have that setup for the grpc project (and gRPC only includes a fixed version of protobuf  through third_party/protobuf  submodule). So at least until I find more time to revisit this, the Grpc.Tools package will need to do.

**Comment by jskeet** [comment]
Closing this as now the Google.Protobuf.Tools package exists.
