### ISSUE TITLE
Missing Conformance case

### ISSUE THREAD

**Issue by kientzle** [google/protobuf#1327]
In working through the JSON coding details, I've run across a case that isn't clear (to me) and doesn't seem to be covered by the current conformance suite:

The case is as follows:

JSON input:  "{\"optionalStruct\": null}")

When this is decoded and then recoded to JSON, what should the result be?  All three of the following seem reasonable to me:

  "{\"optionalStruct\”:null}"  -- Rationale:  output should match input, null should be preserved.  This also matches the behavior of Value.

 "{\"optionalStruct\":{}}"  -- In other places, null decodes to the "default value", which for Struct would seem to be "{}"

 "{}"  -- This would match the behavior of non-magical message fields, where a null input indicates the field is treated as not set.

Adding this case to the conformance test would be a great help.  Thanks!

**Comment by xfxyjwf** [comment]
The result should be "{}". Except for the special well-known type google.protobuf.Value/NullValue, "null" always indicates the field is not present.

**Comment by BSBandme** [comment]
The comformance test should have covered this case: 
https://github.com/google/protobuf/blob/master/conformance/conformance_test.cc#L1838
