### ISSUE TITLE
warning treated as error prevents VS2015 building  on 64-bit windows

### ISSUE THREAD

**Issue by topillar** [google/protobuf#1328]
inline void CodedOutputStream::WriteVarint32(uint32 value) {
  if (buffer_size_ >= 5) {
    // Fast path:  We have enough bytes left in the buffer to guarantee that
    // this write won't cross the end, so we can skip the checks.
    uint8* target = buffer_;
    uint8* end = WriteVarint32ToArray(value, target);
    int size = end - target;
    Advance(size);
  } else {
    WriteVarint32SlowPath(value);
  }
}

==>
inline void CodedOutputStream::WriteVarint32(uint32 value) {
  if (buffer_size_ >= 5) {
    // Fast path:  We have enough bytes left in the buffer to guarantee that
    // this write won't cross the end, so we can skip the checks.
    uint8* target = buffer_;
    uint8* end = WriteVarint32ToArray(value, target);
    int size = static_cast<int>(end - target);
    Advance(size);
  } else {
    WriteVarint32SlowPath(value);
  }
}

**Comment by xfxyjwf** [comment]
Could you send the patch as a PR?

**Comment by topillar** [comment]
Sorry for I don't know how make a PR,but the fix is really easy:
in source file:  protobuf/src/google/protobuf/io/coded_stream.h
 at line 1139 change the code : "int size = end - target;" to "static_cast<int>(end - target);"
only to add a cast.
best regards.

**Comment by topillar** [comment]
Add pull request #1344.
