### ISSUE TITLE
Cross module proto dependencies (Python)

### ISSUE THREAD

**Issue by richburdon** [google/protobuf#1336]
I have two python modules x, y, both of which define protos. 

Using --proto_path x.proto includes defs from y.proto (i.e., import "y.proto")

x/
  src/proto/x.proto
  src/python/x_pb2.py

y/
  src/proto/y.proto
  src/python/y_pb2.py

The generated file x_pb.y has:

    import y_pb2 as y__pb2

But y_pb2 is not in this directory.

Is it specified how cross module dependencies can be managed? It would be required that x specify the package where y is included (which is part of it's pip requirements, for example).

**Comment by zhongql** [comment]
I have a similar problem with you.I split the .proto files into different packages.
b.proto includes defs from a.proto
eg:
model/a.proto
view/b.proto    (import "model/a.proto";)

python/view/b_pb2.py

the generated file b_pb2.py has:

from model import a_pb2 as model_dot_a__pb2

but start up have this Error

ImportError: No module named model

**Comment by richburdon** [comment]
I think I understand the model now: the python package name is taken from the directory hierarchy where the proto files are saved.

@zhongql I think your solution is to either put the protos in the same file hierarchy, e.g.,

src/
  proto/
    model.proto
    view.proto
  python/
    view.py

OR define separate python packages:

model/
  src/
    proto/
      model/
        model.proto
    python/
      model.py
      setup.py

Here, you can create "model" as a separate package that can be installed by your "view" module.

For your use case I recommend the first approach since model and view seem to be quite directly related. In my case I have completely separate python modules, so I am using the second approach.
