### ISSUE TITLE
C++: JSON serialization of bytes not (yet) working?

### ISSUE THREAD

**Issue by KerstinKeller** [google/protobuf#1342]
I have the use case, where I would like to serialize a message to a JSON string that contains also a bytes field. The documentation (language guide) states that the `bytes` field shall be encoded as a `base64` encoded string.
However, on Windows, depending on the content of the bytes array, the serialized JSON contains an empty string for the bytes `""`.

I have made a  minimal example to reproduce the issue:
First the proto file: (message.proto)
```
syntax = "proto2";

package pb;

message Person
{
  optional string name   = 1;
  optional bytes  binary = 2;
}

```
 and then the code (main.cpp):

```
#include <iostream>
#include <memory>

// protobuf includes
#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable: 4100 4127 4244 4267 4512)
#endif
#include "messages.pb.h"
#include <google/protobuf/util/json_util.h>
#include <google/protobuf/util/type_resolver_util.h>
#ifdef _MSC_VER
#pragma warning(pop)
#endif

int main(int argc, char **argv)
{
  class pb::Person person;
  std::string binary_string;
  for (char i = 0; i < 10; i++)
  {
    binary_string.push_back(i);
  }
  person.set_name("Maria");
  person.set_binary(binary_string.c_str(), binary_string.length());
  std::string serialized = person.SerializeAsString();
  std::string json_string;

  google::protobuf::util::JsonOptions options;
  options.always_print_primitive_fields = true;
  std::shared_ptr<google::protobuf::util::TypeResolver> resolver_;
  resolver_.reset(google::protobuf::util::NewTypeResolverForDescriptorPool(
    "", google::protobuf::DescriptorPool::generated_pool()));


  auto status = google::protobuf::util::BinaryToJsonString(resolver_.get(), "/pb.Person", serialized, &json_string, options);
  std::cout << json_string << std::endl;

  std::string res;
  std::cin >> res;
  return(0);
}
```

This prints `{"name":"Maria","binary":""}` while I expect it to print `{"name":"Maria","binary":"AAECAwQFBgcICQ=="}`.

I have tried with beta2 and the current master (as of today), using either `syntax = "proto2";` and `syntax = "proto3";`  Else the JSON serialization works fine, except for the `bytes` field.

Can you please give me some hints if this is a bug, or not yet supported.

**Comment by haberman** [comment]
This should be supported -- the conformance tests include tests for bytes fields, and I believe these are currently passing.

It looks like this might be a bug. @xfxyjwf could you take a look?

**Comment by KerstinKeller** [comment]
Thanks, I also realized one additional thing: When I don't set the option   `options.always_print_primitive_fields = true;`, (e.g. change it to `options.always_print_primitive_fields = false;`) it works as intended. 
However, I also do need all values in the JSON string, including the defaults.

I realize, there is both `JsonObjectWriter` and a `DefaultValueObjectWriter`. When I debug, the above minimal sample, the code never steps inside `JsonObjectWriter::RenderBytes`, as it does without the default printing option.

**Comment by KerstinKeller** [comment]
Hi, are there any updates on this issue and is it going to be fixed for future releases?

**Comment by xfxyjwf** [comment]
Sorry, I haven't looked at it yet. It would be much appreciated if you can help provide a fix. It seems to me a platform-dependent bug for windows.

**Comment by KerstinKeller** [comment]
Hi, sorry for the late answer.
No, this bug is not related to windows only, it also occurs on Linux (tested on Ubuntu) and also with the beta3 release. You can reproduce it with the original example example on top.

Beware of these two lines
```
  google::protobuf::util::JsonOptions options;
  options.always_print_primitive_fields = true;
```
Then the test fails with output `{"name":"Maria","binary":""}`
```
  google::protobuf::util::JsonOptions options;
  options.always_print_primitive_fields = false; // This is the default
```
It works well, output is correctly `{"name":"Maria","binary":"AAECAwQFBgcICQ=="}`

So deserialization does not work for binary fields when `always_print_primitive_fields` option is set. I thought that this option just means that fields will be included in the JSON string even if they do have default values.

Are you able to reproduce the bug with the original example above?

**Comment by mike07026** [comment]
In Protocol Buffers v3.0.0, this bug still exists. (test on Ubuntu 16.04 64bit)

**Comment by xfxyjwf** [comment]
@mike07026 the original bug reported it's not working on windows. You mean it now fails on linux as well? Can you help add a test case to json_util_test.cc to demonstrate the issue? (sending us a pull request and it will trigger the tests automatically).

**Comment by mike07026** [comment]
@xfxyjwf I add a test case to json_util_test.cc and make a bug fix patch to default_value_objectwriter.cc #2045 .
This is the first time I make a PR, but it seems that somehow the patch can't pass CI test, could you please help to fix?
