### ISSUE TITLE
Where is the zero_out.so with TensorFlow source installation

### ISSUE THREAD

**Issue by MisayaZ** [google/protobuf#1348]
I use tensorflow r0.7 branch. I follow the instruction Building the Op library:With TensorFlow source installation, It tells me the following Bazel build rule would build zero_out.so, but I do not know where to put the build and where to find the generated zero_out.so.
cc_binary(
    name = "zero_out.so",
    srcs = ["zero_out.cc"],
    linkopts = [
        "-Wl,-Bsymbolic",
        "-lm",
    ],
    linkshared = 1,
    linkstatic = 1,
    deps = [
        "//third_party/tensorflow/core:framework",
    ],
)

**Comment by xfxyjwf** [comment]
This is bazel query rather than a protobuf or tensorflow one. Please refer to bazel's documentation:
http://bazel.io/
