### ISSUE TITLE
Can we make json_format._AnyMessageToJsonObject non-private?

### ISSUE THREAD

**Issue by jgeewax** [google/protobuf#1351]
https://github.com/google/protobuf/blob/9240acd179708c3a2ab79508af6fd68efa6f883a/python/google/protobuf/json_format.py#L207

It seems super useful - but keeping it private makes us sad :(

**Comment by tseaver** [comment]
While we're at it, the inverse `_ConvertAnyMessage` would be useful, too.

**Comment by xfxyjwf** [comment]
The python json_format API already provides MessageToJson() which converts a proto message to a JSON string. So what you need is a MessageToJsonObject() that converts the message to a JSON object instead of a string. Is this correct?

@haberman @anandolee

**Comment by tseaver** [comment]
@xfxyjwf Yes, that is correct:  our code right now works around the missing `MessageToJsonObject` API by [re-parsing the serialized string](https://github.com/GoogleCloudPlatform/gcloud-python/pull/1661/files#diff-88502f3725459cea6d653a4d5ef165f6R150).

**Comment by tseaver** [comment]
A putative `ConvertAnyMessage` API would work from the "object" form, rather than the serialized string.

**Comment by tseaver** [comment]
@xfxyjwf Any decision / motion on this issue?

**Comment by anandolee** [comment]
I believe it has been supported by

def MessageToDict():
  """Converts protobuf message to a JSON dictionary.
