### ISSUE TITLE
How can i get the EXACT type of an enum field or a repeated field?

### ISSUE THREAD

**Issue by YuanWenqing** [google/protobuf#1357]
In some cases, I want to make a mapping from field name to its value's exact type(Java Class), but i found no easy way to do this on a enum field or a repeated field.

For example, proto:

``` protobuf
enum Kind {
  A_KIND = 0;
  B_KIND = 1;
}
message A {
  int64 id = 1;
  string name = 2;
  Kind kind = 3;
  repeated int64 child_ids = 4;
  repeated A children = 5;
}
```

In Java, I build a ProtoHelper for convenience:

``` Java
public class ProtoHelper<T extends GeneratedMessage> {
...
  T defaultInstance;
  Map<String, FieldDescriptor> fieldMap;
  Map<String, Class<?>> valueTypes;

  public ProtoHelper(Class<T> clazz) {
    ...
  }

  public Class<?> getValueType(String field) {
    return valueTypes.get(field);
  }
...
}
```

`valueTypes` will be auto-initialized whenever `ProtoHelper<A> helper = new ProtoHelper(A.class)`. For fields `id`, `name` , it's easy to get `Long.class`, `String.class` via `defaultInstance.getField(fieldMap.get(field)).getClass()` or `fieldMap.get(field).getDefaultValue().getClass()`. However, for field `kind`, I got `class com.google.protobuf.Descriptors$EnumValueDescriptor`, and for fields `child_ids`, `children`, I even have no idea to get the exact type!

Is there any way or better way to do this? Please let me know, Thanks!

**Comment by xfxyjwf** [comment]
You can use protobuf descriptor API. See:
https://developers.google.com/protocol-buffers/docs/reference/java/com/google/protobuf/Descriptors.Descriptor.html

To get a descriptor, simply call: Foo.getDescriptor().
