### ISSUE TITLE
TR1 unordered hash map used with clang++/c++11?

### ISSUE THREAD

**Issue by jakirkham** [google/protobuf#1359]
Here is a gist ( https://gist.github.com/jakirkham/cdf271568669ca27be5b2d00d525be6d ). Information about system clang at the top of the gist. Using Mac OS 10.9 and XCode 5.0.2.

**Comment by haberman** [comment]
Sorry for the slow reply. Is this still an issue?

**Comment by xfxyjwf** [comment]
I was able to compile the latest code (v3.2.0) with -std=c++11 on Mac OS 10.12.3 and XCode 8.2.1. Assuming the issue is already fixed.

**Comment by jakirkham** [comment]
It was something unique to that compiler version. I now use XCode 6.1 or XCode 6.4 (on Mac OS 10.10). I know with 6.1 it did not experience this issue at the time or since. I don't experience this issue with XCode 6.4 currently, but don't know if that has always been true or not. In any event, I agree this should be closed.
