### ISSUE TITLE
Unit-test FAILED at TokenizerTest.ParseString

### ISSUE THREAD

**Issue by heonio** [google/protobuf#1363]
Environment
- Windows 7 K x64 (Korean) sp1
- Visual Studio 2015 community
- cmake 3.5.1
  and Google protobuf v3.0.0-beta-2

While going through the installation step of https://github.com/google/protobuf/tree/master/cmake/README.md, I encountered FAILED message at testing - "nmake check".

> [  FAILED  ] 1 test, listed below:
> [  FAILED  ] TokenizerTest.ParseString

It seems to be a matter of encoding UTF-8. 
I tried to solve it and got it. Here is my

failed solution
- Use "u8", prefix for UTF-8 encoded string literal. (https://msdn.microsoft.com/en-us/library/69ze775t.aspx)
- Use command "chcp 65001" at command line. 

solution
- Change encoding of "tokenizer_unittest.cc" from UTF-8 without BOM to UTF-8 BOM.
- Add line '#pragma execution_character_set("utf-8")' to the beginning of file "tokenizer_unittest.cc".

I don't know whether it is problem or not, but just want to save someone's time.

**Comment by xfxyjwf** [comment]
I'm not sure it's related to UTF-8. Can you post the log of the test failure message?

**Comment by heonio** [comment]
This is message of console in default code page (949)
>  [ RUN      ] TokenizerTest.ParseString
> E:\Work_Git\protobuf-master\src\google\protobuf\io\tokenizer_unittest.cc(827): error: Value of: output
>   Actual: "$\xC2\xA2\xE2\x82\xAC\xF0\xA4\xAD\xA2XX"
> Expected: "$짖?юㄽ줩X"
> Which is: "$\xC2\xA2?\xAC\xF0\xA4\xAD\xA2XX"
> E:\Work_Git\protobuf-master\src\google\protobuf\io\tokenizer_unittest.cc(830): error: Value of: output
>   Actual: "$\xC2\xA2\xE2\x82\xAC\xF0\xA4\xAD\xA2XX"
> Expected: "$짖?юㄽ줩X"
> Which is: "$\xC2\xA2?\xAC\xF0\xA4\xAD\xA2XX"
> [  FAILED  ] TokenizerTest.ParseString (0 ms)

This is message of console in UTF8 code page (65001)

> E:\Work_Git\protobuf-master\src\google\protobuf\io\tokenizer_unittest.cc(827): error: Value of: output
>   Actual: "$\xC2\xA2\xE2\x82\xAC\xF0\xA4\xAD\xA2XX"
> Expected: "$¢?�𤭢XX"
> Which is: "$\xC2\xA2?\xAC\xF0\xA4\xAD\xA2XX"
> E:\Work_Git\protobuf-master\src\google\protobuf\io\tokenizer_unittest.cc(830): error: Value of: output
>   Actual: "$\xC2\xA2\xE2\x82\xAC\xF0\xA4\xAD\xA2XX"
> Expected: "$¢?�𤭢XX"
> Which is: "$\xC2\xA2?\xAC\xF0\xA4\xAD\xA2XX"

After changing file encoding UTF8 BOM.
> E:\Work_Git\protobuf-master\src\google\protobuf\io\tokenizer_unittest.cc(827): error: Value of: output
>   Actual: "$\xC2\xA2\xE2\x82\xAC\xF0\xA4\xAD\xA2XX"
> Expected: "$¢?�𤭢XX"
> Which is: "$\xC2\xA2?\xAC\xF0\xA4\xAD\xA2XX"
> E:\Work_Git\protobuf-master\src\google\protobuf\io\tokenizer_unittest.cc(830): error: Value of: output
>   Actual: "$\xC2\xA2\xE2\x82\xAC\xF0\xA4\xAD\xA2XX"
> Expected: "$¢?�𤭢XX"
> Which is: "$\xC2\xA2?\xAC\xF0\xA4\xAD\xA2XX"

And after add line "#pragma ...".
> [ RUN      ] TokenizerTest.ParseString
> [       OK ] TokenizerTest.ParseString (0 ms)
