### ISSUE TITLE
Add support for generating closure extern file

### ISSUE THREAD

**Issue by wolfgangmeyers** [google/protobuf#1368]
I'm working on an java/angularjs app that compiles using closure. I've tested out the javascript support, and have been able to send messages back and forth between the server and client using a json format. It seems to work very well - the message objects do have closure-compatible jsdoc tags, but don't work well with the angular databindings. Since I'm just using json as a wire format, I'd like to just use protobuf for marshaling/unmarshaling on the server, and use `struct` declarations in closure extern files for the client-side javascript objects. How hard would it be to generate closure externs that match the json representation of the messages?

**Comment by jart** [comment]
The JS code protobuf generates has type annotations, e.g. `@param`. So it wouldn't make sense to generate externs files, which are meant for third party libraries that have no formal typing.

It seems like what you want are externs that describe the structure of the raw JSON that the generated proto API operates on. I'm not a proto expert, but I'm pretty sure that this data is an undocumented implementation detail and should not be accessed directly by the user. The protobuf authors might change its structure in the future, without breaking the API.

So I'm predicting that the protobuf authors wouldn't consider this sort of feature. Protobuf messages should be accessed through the generated API.

**Comment by wolfgangmeyers** [comment]
I believe it is documented here: https://developers.google.com/protocol-buffers/docs/proto3#json

**Comment by haberman** [comment]
Ah, I think I understand what you are asking. Your server is serializing as proto3 JSON (ie. using a protobuf library), but on the client you want to use this JSON raw -- ie. without a protobuf library.

I don't think this would be too hard. You would want to write your own protobuf compiler plugin. You can get the "json name" and the type for every field, which would let you generate the client-side structs you want.

**Comment by wolfgangmeyers** [comment]
Awesome. I looked at the javascript compiler plugin, and it seemed straightforward. Maybe if I can find time I'll contribute a plugin.

**Comment by anandolee** [comment]
Closing it as a compiler plugin can solve the problem.
