### ISSUE TITLE
[java] Add an ability to run protobuf server as a Servlet 4

### ISSUE THREAD

**Issue by vlsinitsyn** [google/protobuf#1370]
Pls add an ability to run a protobuf  v3 server as a Servlet 4 on any server with the Servlet 4 support.

**Comment by xfxyjwf** [comment]
What do we need to do to make that happen? (sorry, I have no idea what Servlet 4 is...)

**Comment by vlsinitsyn** [comment]
Oh, my fault. This request was actually for gRPC and probably has not much to do with the protobuf itself.

**Comment by vlsinitsyn** [comment]
Oh, my fault. This request was actually for gRPC and probably has not much to do with the protobuf itself.  Pls ignore it.
