### ISSUE TITLE
Java, generated code fails to compile with error-prone compiler

### ISSUE THREAD

**Issue by estekhin** [google/protobuf#138]
In particular, I have problems with ``repeated`` fields.

Generated code for ``repeated`` fields looks like this:

      public Builder addAllXXX(java.lang.Iterable<java.lang.String> values) {
        ensureXXXIsMutable();
        super.addAll(values, XXX_);
        onChanged();
        return this;
      }

Error-prone compiler rejects this code with

```
error: [StaticAccessedFromInstance] A static variable or method should not be accessed from an instance
        super.addAll(values, XXX_);  
             ^                             
    (see http://code.google.com/p/error-prone/wiki/StaticAccessedFromInstance)
  Did you mean 'Builder.addAll(values, XXX_);'?
```

**Comment by jmason** [comment]
(bump) -- any news on this?  https://groups.google.com/forum/#!msg/error-prone-discuss/scOsD6nFFeU/2KlkDzxGArEJ suggests that there's an internal protoc change that could be pushed to the external repo to avoid it.

**Comment by xfxyjwf** [comment]
This is fixed in the latest versions.
