### ISSUE TITLE
Support CLI option for ObjC filename infix

### ISSUE THREAD

**Issue by gvaish** [google/protobuf#1380]
Based on #1372

Ask:
    * Support CLI option for ObjC to customize filename infix.

Example:
    * `objc_opt=filename_infix=pb` will generate `a.pb.{h,m}` for `a.proto`
    * `objc_opt=filename_infix=pbx` will generate `a.pbx.{h,m}` for `a.proto`

**Comment by gvaish** [comment]
@xfxyjwf (tagged)

I can provide a patch for this as well.

**Comment by xfxyjwf** [comment]
Assigned to objective-c owners to take a look.

**Comment by thomasvl** [comment]
For anyone finding this, see the comments on #1372 for some of the thoughts/discussion.
