### ISSUE TITLE
[Java] Nested message with name 'Builder'

### ISSUE THREAD

**Issue by kshchepanovskyi** [google/protobuf#1383]
For given valid proto code, `protoc` generates non-compilabe java code:

``` proto
message Msg {

  int32 x = 1;  

  message Builder {
      int32 y = 1;
  }

}
```

Class `Msg` contains two static inner classes named `Builder`, which leads to a compilation error.

Tested with `protoc` version `3.0.0-beta-2`.

**Comment by gvaish** [comment]
IMHO, whatever `builder` class is generated can always conflict.

So, if the generated name is `MsgBuilder` or `Msg_Builder`, that can conflict too.
