### ISSUE TITLE
protobuf 3.0.0-beta2 cmake build does not install pkg-config files (which confuses grpc)

### ISSUE THREAD

**Issue by emmenlau** [google/protobuf#1384]
I'm using cmake to compile and install protobuf 3.0.0-beta2 on MinGW64 / MSYS2. Everything compiles, tests and works fine. However, the protobuf.pc file for pkg-config is not installed in <target>/lib/pkgconfig.

This confuses grpc compile into not finding protobuf, since grpc assumes that pkg-config must have protobuf.pc (if pkg-config is available).

**Comment by xfxyjwf** [comment]
The cmake support works with visual studio and other cmake projects better. If you are using pkgconfig, could you use autotools to build/install protobuf instead (following the linux install instructions)?

**Comment by emmenlau** [comment]
I see you point. But the autotools build currently fails for me on MinGW / MSYS2 (see issue #1355). So I'm a bit dependent on cmake. I'm not interested in pkgconfig myself, gRPC is. It seems gRPC is not playing nicely together with the cmake-build (for the lack of pkgconfig)?

Long story short, if you say cmake and pkgconfig don't go together, that's fine with me, and we can close this issue. But then we should either reopen #1355 to make sure people can build with pkgconfig on MinGW, or gRPC needs to be fixed. Whats the "correct" thing to do?

**Comment by xfxyjwf** [comment]
I think we should fix both issues:
1. make cmake installation work with pkgconfig.
2. make autoconf build under MingGW/MSYS2

I don't have time to work on these fixes though. Could you help investigate why they don't work? A pull request to fix them will be much appreciated.

**Comment by emmenlau** [comment]
I think this sounds good. I won't have time to work on this in the next weeks, though. If somebody else experiences this issue, I've found an (admittedly ugly) workaround: run configure to generate protobuf.pc with the correct settings, afterwards run cmake to get a compile and install, finally copy protobuf.pc to the install directory. Its ugly but sufficient to work, for the time being.

**Comment by emmenlau** [comment]
Dear @pherl is the issue now fixed? I think protobuf cmake should install `pkg-config` files. Many packages do this, and its really not too hard.

**Comment by xfxyjwf** [comment]
Sorry, the issue is not fixed, but we don't have the time nor expertise to fix the issue.

**Comment by ax3l** [comment]
@xfxyjwf Can we please re-open this issue so point 1

> make cmake installation work with pkgconfig.

can be addressed? :)

This would be the easiest solution and allows building with CMake which does not brake down-stream builds with autotools, such as [mosh](https://github.com/mobile-shell/mosh).

**Comment by xfxyjwf** [comment]
@ax3l Can you send us a pull request?

**Comment by ax3l** [comment]
@xfxyjwf sure, PR is open now in #3403 (sorry for my cross-post!)
