### ISSUE TITLE
deprecated hash_set in Vs15

### ISSUE THREAD

**Issue by roniburd** [google/protobuf#1388]
I've noticed that this issue was already brought up in https://github.com/google/protobuf/pull/797 and the issue is closed, but checking on the the pull request I couldn't really see the matching code change to fix the issue.

Is this issue indeed solved?

**Comment by xfxyjwf** [comment]
This will be fixed at the same time when we move to C++11 only. Doesn't need a dedicated fix. Feel free to send us a pull request though.
