### ISSUE TITLE
Why is JSON parser strict about missing fields

### ISSUE THREAD

**Issue by spf2** [google/protobuf#1389]
With google/protobuf/json_format.py, if you add new fields to the protobuf, it triggers errors like: `ParseError: Failed to parse message field: Message type "Foo" has no field named "fooId".`

This seems like an odd choice, b/c neither JSON nor pure protobufs are strict in this way (and for good reason). It kind of renders json_format.Parse useless.

I don't see a way to disable this strict field checking. What's going on here?

**Comment by xfxyjwf** [comment]
Some differences between JSON and protobuf binary format:
1. There is a way to preserve unknown fields when parsing protobuf binary format, but we can only discard unknown fields when parsing from JSON to protobuf message.
2. JSON input may be manually constructed. Ignoring unknown fields may hide real errors (like a mistyped field name).
For these reasons we think the default should be strict. There should be an option to ignore/discard unknown fields though. It's just not implemented yet. Feel free to send us a pull request if you would like to help implement this option.

**Comment by spf2** [comment]
I see.  1 & 2 are reasonable points, but I think if you're working with JSON, you've already decided to make this tradeoff in the favor of flexibility over strictness.

In any event, making this behavior an option seems like the right next step. I'll look into it...

**Comment by spf2** [comment]
I happened to start with a go pr instead of python and you can see @dsymonds [response](https://github.com/golang/protobuf/pull/165)...

Any chance of adding it to the spec?

**Comment by spf2** [comment]
BTW JSON Schema covers this here: http://tools.ietf.org/html/draft-fge-json-schema-validation-00#page-13, and the default behavior is to ignore unknown fields (additionalProperties defaults to empty schema, and if its value is a schema, validation always succeeds).

**Comment by xfxyjwf** [comment]
Developer guide updated:
https://developers.google.com/protocol-buffers/docs/proto3#json_options

**Comment by AlexeySalmin** [comment]
> Developer guide updated: https://developers.google.com/protocol-buffers/docs/proto3#json_options

For the reference, updated link: https://protobuf.dev/programming-guides/proto3/#json-options

Example for Python API: https://googleapis.dev/python/protobuf/latest/google/protobuf/json_format.html

```
google.protobuf.json_format.Parse(text, message, ignore_unknown_fields=False, descriptor_pool=None, max_recursion_depth=100)

    Parses a JSON representation of a protocol message into a message.

    Parameters:
            text – Message JSON representation.
            message – A protocol buffer message to merge into.
            ignore_unknown_fields – If True, do not raise errors for unknown fields.
            descriptor_pool – A Descriptor Pool for resolving types. If None use the default.
            max_recursion_depth – max recursion depth of JSON message to be deserialized. JSON messages over this depth will fail to be deserialized. Default value is 100.
```
