### ISSUE TITLE
Unable to install from npm

### ISSUE THREAD

**Issue by seishun** [google/protobuf#1396]
The [instructions](https://github.com/google/protobuf/blob/master/js/README.md) tell me to do `npm install google-protobuf`, but it's just a [dummy package](https://www.npmjs.com/package/google-protobuf).

Although I think you should take over [protobuf](https://www.npmjs.com/package/protobuf) instead, since it's unmaintained and doesn't work on any version of Node.js that's less than a year old.

**Comment by jaumard** [comment]
It could be nice to have a way to install/use protobuf/nanobuf on node 4+

**Comment by haberman** [comment]
Thanks for the report. I've messaged the npm maintainers about taking the `google-protobuf` package back. I'll also message the maintainer of `protobuf` to see if he's interested in giving us the name. Wouldn't that break lots of users who might depend on the package already though? Maybe if it doesn't work with recent node then they are broken already.

**Comment by seishun** [comment]
>Wouldn't that break lots of users who might depend on the package already though?

Only if they haven't specified the maximum version (e.g. `"protobuf": "*"`). If they have specified at least the major version (which people do if they don't want things to break), then they will be fine, since the current `protobuf` version is `0.11.0`, but Google's protobuf is `3.0.0-alpha.5`.

That's of course assuming Google is fine with keeping the old `protobuf` versions on npm after taking over the name.

**Comment by haberman** [comment]
I've gotten `google-protobuf` back and published the correct code there, so this bug should be fixed.
