### ISSUE TITLE
Spelling error in protocol buffer basic c++ documentation on google developers

### ISSUE THREAD

**Issue by mostevercxz** [google/protobuf#1399]
I've read the protocol buffer basic c++ documentation on [google developers protobuf basic c++ tutorial](https://developers.google.com/protocol-buffers/docs/cpptutorial#the-protocol-buffer-api).

  The first paragraph of "The Protocol Buffer API" chapter says "If you look in `tutorial.pb.h`, you can see that you have a class for each message you specified in `tutorial.proto`". In fact, the name should be `addressbook.pb.h` and `addressbook.proto`. I searched the page and did not get the way to modify the content. To make the people who's willing to read the documentation not be confused, I'm here creating a github issue.

**Comment by TeBoring** [comment]
Fixed
