### ISSUE TITLE
variable named TYPE_BOOL(c++ code) is conflicted with ios macro

### ISSUE THREAD

**Issue by mefilt** [google/protobuf#140]
Hello. How me fix ? I found solution on stackoverflow. Is it not hard code? i'm use cocoapods. 
Xcode last version, and 2.6.1 protobuf 

http://stackoverflow.com/questions/15759559/variable-named-type-boolc-code-is-conflicted-with-ios-macro

**Comment by tamird** [comment]
crosslinking https://code.google.com/p/protobuf/issues/detail?id=119

**Comment by xfxyjwf** [comment]
Should be fixed.
