### ISSUE TITLE
python quit unexpectedly while the using _message.so plug-in on OSX

### ISSUE THREAD

**Issue by ppLorins** [google/protobuf#1403]
After upgrade to the newest version 3.0-beta2 , I got this python code issue , but the same code 
work pretty good before the update.

environment: 

python  : 2.7.10
protobuf:  3.0.0-beta-2
mac OS Yosemite 10.10.5

info:
Process:               Python [53387]
Path:                  /System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python
Identifier:            Python
Version:               2.7.10 (2.7.10)
Code Type:             X86-64 (Native)
Parent Process:        zsh [1601]
Responsible:           iTerm [505]
User ID:               501

PlugIn Path:             /Users/USER/*/_message.so
PlugIn Identifier:       _message.so
PlugIn Version:          ??? (0)

Date/Time:             2016-04-11 10:39:18.784 +0800
OS Version:            Mac OS X 10.10.5 (14F1713)
Report Version:        11
Anonymous UUID:        F9CEE1C1-89F6-F573-3DBD-768F6D53BB27

Sleep/Wake UUID:       41E64B3E-7366-4C88-A91D-0AFA0EECE24A

Time Awake Since Boot: 23000 seconds
Time Since Wake:       1200 seconds

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000013600000000

VM Regions Near 0x13600000000:
    __LINKEDIT             000000010250a000-00000001026a5000 [ 1644K] r--/rwx SM=COW  /usr/local/lib/libprotobuf.10.dylib
--> 
    MALLOC_TINY            00007fd0d1c00000-00007fd0d2000000 [ 4096K] rw-/rwx SM=COW  

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   _message.so                     0x000000010222c492 std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > std::__1::operator+<char, std::__1::char_traits<char>, std::__1::allocator<char> >(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, char const_) + 46
1   _message.so                     0x000000010222b794 google::protobuf::python::cmessage::AddFieldNumberToClass(_object_, google::protobuf::FieldDescriptor const_) + 40
2   _message.so                     0x000000010222a8ea google::protobuf::python::cmessage::AddDescriptors(_object_, _object*) + 246
3   org.python.python               0x00000001017e32ea PyEval_EvalFrameEx + 15716
4   org.python.python               0x00000001017e5c82 0x10175b000 + 568450
5   org.python.python               0x00000001017e29a6 PyEval_EvalFrameEx + 13344
6   org.python.python               0x00000001017df352 PyEval_EvalCodeEx + 1409
7   org.python.python               0x00000001017835de 0x10175b000 + 165342
8   org.python.python               0x000000010176550a PyObject_Call + 99
9   org.python.python               0x00000001017702f7 0x10175b000 + 86775
10  org.python.python               0x000000010176550a PyObject_Call + 99
11  org.python.python               0x00000001017ac7b0 0x10175b000 + 333744
12  org.python.python               0x00000001017a7f87 0x10175b000 + 315271
13  org.python.python               0x000000010176550a PyObject_Call + 99
14  org.python.python               0x00000001017e2399 PyEval_EvalFrameEx + 11795
15  org.python.python               0x00000001017df352 PyEval_EvalCodeEx + 1409
16  org.python.python               0x00000001017dedcb PyEval_EvalCode + 54
17  org.python.python               0x00000001017f3ee3 PyImport_ExecCodeModuleEx + 241
18  org.python.python               0x000000010182369b 0x10175b000 + 820891
19  org.python.python               0x000000010176550a PyObject_Call + 99
20  org.python.python               0x000000010176569b 0x10175b000 + 42651
21  org.python.python               0x0000000101765897 PyObject_CallMethod + 231
22  org.python.python               0x00000001017f7663 0x10175b000 + 640611
23  org.python.python               0x00000001017f748f 0x10175b000 + 640143
24  org.python.python               0x00000001017f54f6 PyImport_ImportModuleLevel + 1327
25  org.python.python               0x00000001017da9b3 0x10175b000 + 522675
26  org.python.python               0x000000010176550a PyObject_Call + 99
27  org.python.python               0x00000001017e53df PyEval_CallObjectWithKeywords + 93
28  org.python.python               0x00000001017e1641 PyEval_EvalFrameEx + 8379
29  org.python.python               0x00000001017df352 PyEval_EvalCodeEx + 1409
30  org.python.python               0x00000001017dedcb PyEval_EvalCode + 54
31  org.python.python               0x00000001017f3ee3 PyImport_ExecCodeModuleEx + 241
32  org.python.python               0x00000001017f6bc2 0x10175b000 + 637890
33  org.python.python               0x00000001017f7663 0x10175b000 + 640611
34  org.python.python               0x00000001017f722d 0x10175b000 + 639533
35  org.python.python               0x00000001017f5436 PyImport_ImportModuleLevel + 1135
36  org.python.python               0x00000001017da9b3 0x10175b000 + 522675
37  org.python.python               0x000000010176550a PyObject_Call + 99
38  org.python.python               0x00000001017e53df PyEval_CallObjectWithKeywords + 93
39  org.python.python               0x00000001017e1641 PyEval_EvalFrameEx + 8379
40  org.python.python               0x00000001017df352 PyEval_EvalCodeEx + 1409
41  org.python.python               0x00000001017dedcb PyEval_EvalCode + 54
42  org.python.python               0x00000001017ff00e 0x10175b000 + 671758
43  org.python.python               0x00000001017ff0b1 PyRun_FileExFlags + 133
44  org.python.python               0x00000001017fec4e PyRun_SimpleFileExFlags + 769
45  org.python.python               0x0000000101810437 Py_Main + 3051
46  libdyld.dylib                   0x00007fff9682a5c9 start + 1

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000001  rbx: 0x0000000000000001  rcx: 0x0000000000000003  rdx: 0x0000000102236b89
  rdi: 0x00007fff5e4ace08  rsi: 0x0000013600000000  rbp: 0x00007fff5e4acdf0  rsp: 0x00007fff5e4acdc0
   r8: 0x0000000000000000   r9: 0x00000001021556c0  r10: 0x0000000000000000  r11: 0xffff8001a3ca88db
  r12: 0x0000013600000000  r13: 0x00007fd0d1e57d30  r14: 0x0000000102236b89  r15: 0x00007fff5e4ace08
  rip: 0x000000010222c492  rfl: 0x0000000000010206  cr2: 0x0000013600000000

Logical CPU:     4
Error Code:      0x00000004
Trap Number:     14

Binary Images:
       0x101751000 -        0x101751fff  org.python.python (2.7.10 - 2.7.10) <109A7A4A-99AF-338A-86CC-6D17F5EC88A6> /System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python
       0x10175b000 -        0x10184dfff  org.python.python (2.7.10 - 2.7.10) <E4356925-959C-36B1-9991-1D925E7B6C94> /System/Library/Frameworks/Python.framework/Versions/2.7/Python
       0x101a11000 -        0x101a12fff  _locale.so (89.40.1) <59549509-EE3A-300A-8C68-49F1FBEBE2DC> /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_locale.so
       0x101a96000 -        0x101a99ff7  strop.so (89.40.1) <3E094406-6B2D-3030-9B8C-F54A7998962F> /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/strop.so
       0x101a9e000 -        0x101aa4fff +constants.so (0) <681462F3-D2C8-3E52-AC7B-009F0272EF36> /Library/Python/2.7/site-packages/zmq/backend/cython/constants.so
       0x101aaf000 -        0x101afcff7 +libzmq.5.dylib (0) <FC875E25-FA93-3243-9371-B157F78098F4> /usr/local/lib/libzmq.5.dylib
       0x101b4c000 -        0x101b97fe7 +libsodium.13.dylib (0) <ED467208-EDDA-3487-BE99-90B526BB6F80> /usr/local/lib/libsodium.13.dylib
       0x101bbf000 -        0x101bc0fff +error.so (0) <24D8C6D6-C47C-3055-927B-BF59393E64EA> /Library/Python/2.7/site-packages/zmq/backend/cython/error.so
       0x101bc4000 -        0x101bccfff +message.so (0) <C85C6DC9-050F-3505-937C-CA3FE80AEEA1> /Library/Python/2.7/site-packages/zmq/backend/cython/message.so
       0x101bd7000 -        0x101bd8fff  time.so (89.40.1) <9E1F6DA2-9AF6-3881-945B-60E1960EEAE7> /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/time.so
       0x101c1e000 -        0x101c20fff  _collections.so (89.40.1) <AC77804C-F5F9-3EE7-B03B-8B2E373C5C79> /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_collections.so
       0x101c26000 -        0x101c29fff  operator.so (89.40.1) <557EF3D6-7532-3AA9-8F4F-F3637E714414> /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/operator.so
       0x101c2f000 -        0x101c33fff  itertools.so (89.40.1) <FC1B2B69-A09D-3DFC-8AFF-9DAA201EF29A> /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/itertools.so
       0x101c3c000 -        0x101c3dfff  _heapq.so (89.40.1) <BBBA9D12-5692-3BA2-A54D-ECCF618EEA91> /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_heapq.so
       0x101c82000 -        0x101c87fff +context.so (0) <735DE0F7-580B-3021-9DB9-4F1BC2B869BC> /Library/Python/2.7/site-packages/zmq/backend/cython/context.so
       0x101c8f000 -        0x101c9ffff +socket.so (0) <A345F7A8-C74F-3CFA-A580-FB2293A5E26A> /Library/Python/2.7/site-packages/zmq/backend/cython/socket.so
       0x101d2e000 -        0x101d31ff7  math.so (89.40.1) <3016B791-FC4B-3B04-82F2-7941EB5CC347> /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/math.so
       0x101d37000 -        0x101d39fff  binascii.so (89.40.1) <F21ADE6F-29F9-34EA-BCDD-EABA8FBD23DF> /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/binascii.so
       0x101d3d000 -        0x101d3efff  _hashlib.so (89.40.1) <FF03A044-74E2-3DF9-894D-1C322421D6EF> /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_hashlib.so
       0x101d43000 -        0x101d79ff7  libssl.0.9.8.dylib (52.40.1) <0121FFA1-8332-39FF-9542-3E80BBC323D7> /usr/lib/libssl.0.9.8.dylib
       0x101d8f000 -        0x101d92fff  _struct.so (89.40.1) <2443B9A8-9F7E-3620-A009-A545E8C16719> /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_struct.so
       0x101d98000 -        0x101d99ff7  _random.so (89.40.1) <6BEAED69-3F2E-377C-82C8-AC6D99A55F5E> /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_random.so
       0x101d9d000 -        0x101da1fff  _json.so (89.40.1) <15B203E1-4CBD-3615-AA88-B876DCF9081A> /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_json.so
       0x101da6000 -        0x101db1fff  cPickle.so (89.40.1) <8F420BF2-F4D7-3E7F-A458-5569C75D5602> /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/cPickle.so
       0x101db7000 -        0x101db8fff  cStringIO.so (89.40.1) <397642F6-410C-3229-8602-F81EB3DDCBFE> /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/cStringIO.so
       0x101dbd000 -        0x101dc0fff +utils.so (0) <1C5D0611-77DD-3B98-97DD-32831557C68F> /Library/Python/2.7/site-packages/zmq/backend/cython/utils.so
       0x101dc6000 -        0x101dcbfff +_poll.so (0) <F47DFE81-7533-3340-891F-2ED98A558FC4> /Library/Python/2.7/site-packages/zmq/backend/cython/_poll.so
       0x101dd2000 -        0x101dd3fff +_version.so (0) <9F6D47D9-0D96-397C-9A4D-913E6C66CCE2> /Library/Python/2.7/site-packages/zmq/backend/cython/_version.so
       0x101dd7000 -        0x101ddbfff +_device.so (0) <5252DF13-2846-3604-BA8F-626D02354954> /Library/Python/2.7/site-packages/zmq/backend/cython/_device.so
       0x101ea1000 -        0x101ea3fff  select.so (89.40.1) <B9C0E564-2854-3829-8107-AD47E3044C80> /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/select.so
       0x101ea9000 -        0x101eaafff  fcntl.so (89.40.1) <572598F0-FCF9-3821-AB50-CE6215E13C08> /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/fcntl.so
       0x101eae000 -        0x101eb0fff  _multiprocessing.so (89.40.1) <1CA43651-318F-3A0D-9BD6-B360D4376A06> /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_multiprocessing.so
       0x101eb5000 -        0x101ebafff +monitoredqueue.so (0) <70A29DA8-F92B-3AB9-84A3-BE8B91B9275B> /Library/Python/2.7/site-packages/zmq/devices/monitoredqueue.so
       0x101ec2000 -        0x101ec4fff  zlib.so (89.40.1) <FF477F41-897F-31C4-AB08-796BD942DCD5> /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/zlib.so
       0x101f09000 -        0x101f18fff  _io.so (89.40.1) <D1BE6B16-14FE-364F-BA9C-F53510B67E45> /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_io.so
       0x101f29000 -        0x101f29fff  grp.so (89.40.1) <7095913E-5385-3CC4-B877-4B07E5AD79C0> /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/grp.so
       0x101f6d000 -        0x101f6efff  _functools.so (89.40.1) <C3591409-0F95-32BE-ADE0-4B61CACE6260> /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_functools.so
       0x101f72000 -        0x101f7bfff  datetime.so (89.40.1) <DAAF704F-A84D-3028-92CD-5D5EB9A14635> /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/datetime.so
       0x101fc4000 -        0x101fcbff7  _socket.so (89.40.1) <942FC773-142B-364E-AC99-EB24A5D5D029> /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_socket.so
       0x101fd5000 -        0x101fdefff  _ssl.so (89.40.1) <62B0751A-A0D4-3B99-BCB3-54F88A921B11> /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_ssl.so
       0x102069000 -        0x102069fff  _scproxy.so (89.40.1) <42F89A22-64CE-3428-B207-2823F0665B7F> /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_scproxy.so
       0x1020ad000 -        0x1020b5fff  parser.so (89.40.1) <D80A515C-BF13-3CA8-B527-012CA5D7292B> /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/parser.so
       0x1020fa000 -        0x1020fffff  pyexpat.so (89.40.1) <076C80CF-7F8B-3D83-84FE-39E79C277B72> /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/pyexpat.so
       0x102206000 -        0x102214fff  _ctypes.so (89.40.1) <5F2457C3-2A10-3CA4-8E43-81AA60D43AE7> /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_ctypes.so
       0x102220000 -        0x102237ff7 +_message.so (0) <BF39E1CE-711F-32DF-8507-B9F0C991E426> /Users/USER/*/_message.so
       0x1023b1000 -        0x1024fffff +libprotobuf.10.dylib (0) <B1BA0E69-68B8-35D7-A925-76F61337141D> /usr/local/lib/libprotobuf.10.dylib
    0x7fff61d5b000 -     0x7fff61d91887  dyld (353.2.3) <D9967621-6378-381B-A47B-5085EE476B62> /usr/lib/dyld
    0x7fff877ec000 -     0x7fff87809fff  libsystem_kernel.dylib (2782.50.2) <FAA95C7E-5A59-35FD-9ED5-80BFB27BF3C7> /usr/lib/system/libsystem_kernel.dylib
    0x7fff88922000 -     0x7fff88933ff3  libsystem_coretls.dylib (35.40.1) <155DA0A9-2046-332E-BFA3-D7974A51F731> /usr/lib/system/libsystem_coretls.dylib
    0x7fff8956b000 -     0x7fff895bffff  libc++.1.dylib (120) <1B9530FD-989B-3174-BB1C-BDC159501710> /usr/lib/libc++.1.dylib
    0x7fff896c7000 -     0x7fff896d0fff  libsystem_pthread.dylib (105.40.1) <ACE90967-ECD0-3251-AEEB-461E3C6414F7> /usr/lib/system/libsystem_pthread.dylib
    0x7fff89acc000 -     0x7fff89b45fe7  libcorecrypto.dylib (233.30.1) <5779FFA0-4D9A-3AD4-B7F2-618227621DC8> /usr/lib/system/libcorecrypto.dylib
    0x7fff8a178000 -     0x7fff8a179fff  libffi.dylib (18.1) <0F6C6A4D-1210-3585-8DA1-B8A94B9924A5> /usr/lib/libffi.dylib
    0x7fff8a7e2000 -     0x7fff8a7e2ff7  liblaunch.dylib (559.40.1) <4F81CA3A-D2CE-3030-A89D-42F3DAD7BA8F> /usr/lib/system/liblaunch.dylib
    0x7fff8a7e3000 -     0x7fff8ab7bff7  com.apple.CoreFoundation (6.9 - 1153.18) <5C0892B8-9691-341F-9279-CA3A74D59AA0> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
    0x7fff8b773000 -     0x7fff8b775fff  libsystem_sandbox.dylib (358.20.5) <3F5E973F-C702-31AC-97BC-05F5C195683C> /usr/lib/system/libsystem_sandbox.dylib
    0x7fff8b995000 -     0x7fff8b9bdfff  libxpc.dylib (559.40.1) <5C829202-962E-3744-8B50-00D38CC88E84> /usr/lib/system/libxpc.dylib
    0x7fff8be0a000 -     0x7fff8be26ff7  libsystem_malloc.dylib (53.30.1) <DDA8928B-CC0D-3255-BD8A-3FEA0982B890> /usr/lib/system/libsystem_malloc.dylib
    0x7fff8be2c000 -     0x7fff8be56ff7  libdispatch.dylib (442.50.1) <A61E703C-784A-3698-B513-75DD12AAD6DC> /usr/lib/system/libdispatch.dylib
    0x7fff8d688000 -     0x7fff8d690fff  libsystem_platform.dylib (63) <64E34079-D712-3D66-9CE2-418624A5C040> /usr/lib/system/libsystem_platform.dylib
    0x7fff8d86c000 -     0x7fff8d884ff7  libexpat.1.dylib (12) <C5FE8836-E277-3162-9D15-6735321CB2C6> /usr/lib/libexpat.1.dylib
    0x7fff8d99a000 -     0x7fff8d99cfff  libsystem_configuration.dylib (699.40.2) <56F94DCE-DBDE-3615-8F07-DE6270D9F8BE> /usr/lib/system/libsystem_configuration.dylib
    0x7fff8dba8000 -     0x7fff8dbd8fff  libsystem_m.dylib (3086.1) <1E12AB45-6D96-36D0-A226-F24D9FB0D9D6> /usr/lib/system/libsystem_m.dylib
    0x7fff8dd57000 -     0x7fff8dd82fff  libc++abi.dylib (125) <88A22A0F-87C6-3002-BFBA-AC0F2808B8B9> /usr/lib/libc++abi.dylib
    0x7fff8e1ac000 -     0x7fff8e1adfff  com.apple.TrustEvaluationAgent (2.0 - 25) <2D61A2C3-C83E-3A3F-8EC1-736DBEC250AB> /System/Library/PrivateFrameworks/TrustEvaluationAgent.framework/Versions/A/TrustEvaluationAgent
    0x7fff8e78c000 -     0x7fff8e78cff7  libkeymgr.dylib (28) <77845842-DE70-3CC5-BD01-C3D14227CED5> /usr/lib/system/libkeymgr.dylib
    0x7fff8e790000 -     0x7fff8e798ffb  libcopyfile.dylib (118.1.2) <0C68D3A6-ACDD-3EF3-991A-CC82C32AB836> /usr/lib/system/libcopyfile.dylib
    0x7fff8ec7a000 -     0x7fff8ec80ff7  libsystem_networkextension.dylib (167.40.3) <BA58B30B-8377-3B0A-8AE3-4F84021D9D4E> /usr/lib/system/libsystem_networkextension.dylib
    0x7fff8ece5000 -     0x7fff8ece6fff  libDiagnosticMessagesClient.dylib (100) <2EE8E436-5CDC-34C5-9959-5BA218D507FB> /usr/lib/libDiagnosticMessagesClient.dylib
    0x7fff8ece7000 -     0x7fff8ed2dff7  libauto.dylib (186) <A260789B-D4D8-316A-9490-254767B8A5F1> /usr/lib/libauto.dylib
    0x7fff8edc6000 -     0x7fff8eeaafff  libcrypto.0.9.8.dylib (52.40.1) <D123FC57-E2EB-3E08-A51B-6C317EA83EB5> /usr/lib/libcrypto.0.9.8.dylib
    0x7fff8fc1b000 -     0x7fff8fca7fff  libsystem_c.dylib (1044.40.2) <69158EFA-8270-30A1-BA02-4F74A4498147> /usr/lib/system/libsystem_c.dylib
    0x7fff900f6000 -     0x7fff900f6ff7  libunc.dylib (29) <5676F7EA-C1DF-329F-B006-D2C3022B7D70> /usr/lib/system/libunc.dylib
    0x7fff9010f000 -     0x7fff90120ff7  libz.1.dylib (55) <88C7C7DE-04B8-316F-8B74-ACD9F3DE1AA1> /usr/lib/libz.1.dylib
    0x7fff903fa000 -     0x7fff90410ff7  libsystem_asl.dylib (267) <F153AC5B-0542-356E-88C8-20A62CA704E2> /usr/lib/system/libsystem_asl.dylib
    0x7fff904d1000 -     0x7fff904d2ff7  libsystem_blocks.dylib (65) <9615D10A-FCA7-3BE4-AA1A-1B195DACE1A1> /usr/lib/system/libsystem_blocks.dylib
    0x7fff9061d000 -     0x7fff90622fff  libsystem_stats.dylib (163.30.2) <A55632C9-CAFA-31DC-926C-B1FD07E445C1> /usr/lib/system/libsystem_stats.dylib
    0x7fff91d3f000 -     0x7fff91d41ff7  libsystem_coreservices.dylib (9) <41B7C578-5A53-31C8-A96F-C73E030B0938> /usr/lib/system/libsystem_coreservices.dylib
    0x7fff91ebb000 -     0x7fff91f33ff7  com.apple.SystemConfiguration (1.14.4 - 1.14) <3DFFD7F7-BD23-3F4C-A209-C4A0D99F6573> /System/Library/Frameworks/SystemConfiguration.framework/Versions/A/SystemConfiguration
    0x7fff92ad8000 -     0x7fff92adcfff  libcache.dylib (69) <45E9A2E7-99C4-36B2-BEE3-0C4E11614AD1> /usr/lib/system/libcache.dylib
    0x7fff92bb6000 -     0x7fff92bb7ffb  libremovefile.dylib (35) <3485B5F4-6CE8-3C62-8DFD-8736ED6E8531> /usr/lib/system/libremovefile.dylib
    0x7fff92bfb000 -     0x7fff92bfcff3  libSystem.B.dylib (1213) <538E391E-1BD1-3655-80DF-62609C9305CC> /usr/lib/libSystem.B.dylib
    0x7fff92cff000 -     0x7fff92d37fff  libsystem_network.dylib (412.20.3) <6105C134-6722-3C0A-A4CE-5E1261E2E1CC> /usr/lib/system/libsystem_network.dylib
    0x7fff92d9c000 -     0x7fff92da3ff7  libcompiler_rt.dylib (35) <BF8FC133-EE10-3DA6-9B90-92039E28678F> /usr/lib/system/libcompiler_rt.dylib
    0x7fff938ad000 -     0x7fff93a92ff7  libicucore.A.dylib (531.50) <CAA7ACE0-4012-3A13-864D-2B56B4B072FD> /usr/lib/libicucore.A.dylib
    0x7fff94285000 -     0x7fff94290fff  libcommonCrypto.dylib (60061.30.1) <E789748D-F9A7-3CFF-B317-90DF348B1E95> /usr/lib/system/libcommonCrypto.dylib
    0x7fff94a67000 -     0x7fff94a69fff  libquarantine.dylib (76.20.1) <7AF90041-2768-378A-925A-D83161863642> /usr/lib/system/libquarantine.dylib
    0x7fff94c57000 -     0x7fff94c58fff  libsystem_secinit.dylib (18) <581DAD0F-6B63-3A48-B63B-917AF799ABAA> /usr/lib/system/libsystem_secinit.dylib
    0x7fff94e13000 -     0x7fff94e3bfff  libsystem_info.dylib (459.40.1) <2E16C4B3-A327-3957-9C41-143911979A1E> /usr/lib/system/libsystem_info.dylib
    0x7fff94e7a000 -     0x7fff9507446f  libobjc.A.dylib (647) <759E155D-BC42-3D4E-869B-6F57D477177C> /usr/lib/libobjc.A.dylib
    0x7fff9531f000 -     0x7fff95328ff7  libsystem_notify.dylib (133.1.1) <61147800-F320-3DAA-850C-BADF33855F29> /usr/lib/system/libsystem_notify.dylib
    0x7fff96814000 -     0x7fff9681afff  libsystem_trace.dylib (72.20.1) <840F5301-B55A-3078-90B9-FEFFD6CD741A> /usr/lib/system/libsystem_trace.dylib
    0x7fff96827000 -     0x7fff9682aff7  libdyld.dylib (353.2.3) <CDB6EA0B-AAAE-3D81-A456-8D5C32D7E361> /usr/lib/system/libdyld.dylib
    0x7fff96949000 -     0x7fff96959ff7  libbsm.0.dylib (34) <A3A2E56C-2B65-37C7-B43A-A1F926E1A0BB> /usr/lib/libbsm.0.dylib
    0x7fff96993000 -     0x7fff96998ff7  libunwind.dylib (35.3) <BE7E51A0-B6EA-3A54-9CCA-9D88F683A6D6> /usr/lib/system/libunwind.dylib
    0x7fff96ecc000 -     0x7fff96ed1ff7  libmacho.dylib (862) <126CA2ED-DE91-308F-8881-B9DAEC3C63B6> /usr/lib/system/libmacho.dylib
    0x7fff97188000 -     0x7fff97190fff  libsystem_dnssd.dylib (576.50.2) <9EC5AF92-D0D2-3BDE-92B6-D3730D3865C8> /usr/lib/system/libsystem_dnssd.dylib

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 22196
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=90.7M resident=117.4M(129%) swapped_out_or_unallocated=16777216.0T(19398689554432%)
Writable regions: Total=51.6M written=9416K(18%) resident=12.5M(24%) swapped_out=0K(0%) unallocated=39.1M(76%)

REGION TYPE                      VIRTUAL
===========                      =======
Kernel Alloc Once                     4K
MALLOC                             42.9M
MALLOC (admin)                       16K
STACK GUARD                        56.0M
Stack                              8192K
VM_ALLOCATE                          16K
__DATA                             2168K
__LINKEDIT                         73.8M
__TEXT                             16.9M
__UNICODE                           552K
shared memory                         4K
===========                      =======
TOTAL                             200.3M

Model: MacBookPro11,2, BootROM MBP112.0138.B16, 4 processors, Intel Core i7, 2.2 GHz, 16 GB, SMC 2.18f15
Graphics: Intel Iris Pro, Intel Iris Pro, Built-In
Memory Module: BANK 0/DIMM0, 8 GB, DDR3, 1600 MHz, 0x80AD, 0x484D54343147533641465238412D50422020
Memory Module: BANK 1/DIMM0, 8 GB, DDR3, 1600 MHz, 0x80AD, 0x484D54343147533641465238412D50422020
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x134), Broadcom BCM43xx 1.0 (7.15.166.24.3)
Bluetooth: Version 4.3.6f3 16238, 3 services, 27 devices, 1 incoming serial ports
Network Service: USB Ethernet, Ethernet, en4
Network Service: Wi-Fi, AirPort, en0
Serial ATA Device: APPLE SSD SM0256F, 251 GB
USB Device: Internal Memory Card Reader
USB Device: Apple USB Ethernet Adapter
USB Device: iPhone
USB Device: BRCM20702 Hub
USB Device: Bluetooth USB Host Controller
USB Device: Apple Internal Keyboard / Trackpad
Thunderbolt Bus: MacBook Pro, Apple Inc., 17.1

**Comment by haberman** [comment]
Do you have a reproducible test case for this? A stack trace like this probably won't be enough to figure out what is going on.

**Comment by haberman** [comment]
Without a reproducible test case we can't make any progress on this.
