### ISSUE TITLE
mutable_string_field() should return an empty string rather than a string with the default value

### ISSUE THREAD

**Issue by xfxyjwf** [google/protobuf#141]
Given this definition:
message X {
  required string foo = 1 [default = "bar"];
}
The following code will output "bar" whereas it should be empty.
X x;
cout << *x.mutable_foo();

https://developers.google.com/protocol-buffers/docs/reference/cpp-generated#fields

**Comment by pherl** [comment]
I believe this will be a behavior change that we won't be able to fix.

**Comment by pherl** [comment]
Probably update the document to match the behavior then.

**Comment by pherl** [comment]
It seems like this already prints empty and the documentation was correct.
