### ISSUE TITLE
Expected encoding of .proto files

### ISSUE THREAD

**Issue by myitcv** [google/protobuf#1418]
Having looked at both:
- [Language guide (proto3)](https://developers.google.com/protocol-buffers/docs/proto3)
- [Protocol Buffers Version 3 Language Specification](https://developers.google.com/protocol-buffers/docs/reference/proto3-spec)

I couldn't find any mention of what encoding is expected of `.proto` files themselves, i.e. what encoding `protoc` considers valid.

I'm assuming Unicode text encoded in UTF-8?

**Comment by xfxyjwf** [comment]
Yes, protobuf only supports UTF-8 encoding.

**Comment by myitcv** [comment]
@xfxyjwf - thanks for confirming
