### ISSUE TITLE
Beta-3 Availability?

### ISSUE THREAD

**Issue by gvaish** [google/protobuf#1420]
When's Beta-3 (or Beta-2.2 / RC/GA) available?

Specifically, I'm interested in this change: https://github.com/google/protobuf/commit/bd41a39f693d8307d407e42b634b315e075b6c8f
(supercedes: https://github.com/google/protobuf/commit/4d663376e2023855e780459cdf612e0e33e3485a)

Reason:

`beta-2` has a memory leak - 80 bytes per object allocation (on call to `dispatch_semaphore_create`). Noting that the number of objects that may get created in app lifecycle can be large, it's a point of concern.

cc: @jskeet

**Comment by xfxyjwf** [comment]
We are working on a new release right now. It should be ready in ~2 weeks.

**Comment by gvaish** [comment]
Thanks @xfxyjwf 

Looking forward to it.
