### ISSUE TITLE
Wrong version number in Podspec file

### ISSUE THREAD

**Issue by gvaish** [google/protobuf#1421]
https://github.com/google/protobuf/blob/v3.0.0-beta-2/Protobuf.podspec#L8 

Is it a known issue?

**Comment by thomasvl** [comment]
It's not so much that it is wrong, I think there just hasn't been a push of the pod since then.

**Comment by gvaish** [comment]
`v3.0.0-beta-2` was pushed while this points to `alpha` (in the `beta` tag).

Anyway, we may not want to touch the tag now.
Let's keep that as a tracker time for future release.

**Comment by thomasvl** [comment]
Actually, the spec in the release shouldn't matter, right? When someone fetches things via pods, the podspec in the CocoaPods repository is all that matters; I don't think the file even has to exist in the branch that gets fetched.  Yes, it could be slightly confusing, but there's no real harm with it.

**Comment by thomasvl** [comment]
Closing this since there have been some release since then and I believe things are fixed up.
