### ISSUE TITLE
How to cmake protobuf 3.0 to .sln file in Win32(Or Arm)  not win64 （C++）

### ISSUE THREAD

**Issue by hyxppz** [google/protobuf#1423]
I need to use protobuf3.0 in win32 .I follow the readme.md file . At here create sln file

To create Visual Studio solution file:

 C:\Path\to\protobuf\cmake\build>mkdir solution & cd solution
 C:\Path\to\protobuf\cmake\build\solution>cmake -G "Visual Studio 12 2013 Win64" ^
 -DCMAKE_INSTALL_PREFIX=../../../../install ^
 ../..
It will generate Visual Studio solution file protobuf.sln in current directory.

I want Win32 not win 64 .

How to make it. THANKS!

**Comment by xfxyjwf** [comment]
To generate win32 solution files, you can use cmake generator flag: cmake -G "Visual Studio 12 2013" (i.e., omit Win64).

**Comment by 0lddriv3r** [comment]
When I use cmake to generate win32 solution, it shows follow:
```
CMake Error: File E:/protobuf-3.4.0/cmake/protobuf.pc.cmake does not exist.
CMake Error at install.cmake:3 (configure_file):
  configure_file Problem configuring file
Call Stack (most recent call first):
  CMakeLists.txt:175 (include)


CMake Error: File E:/protobuf-3.4.0/cmake/protobuf-lite.pc.cmake does not exist.
CMake Error at install.cmake:5 (configure_file):
  configure_file Problem configuring file
Call Stack (most recent call first):
  CMakeLists.txt:175 (include)
```
How to solve it? plz
