### ISSUE TITLE
compile fail...

### ISSUE THREAD

**Issue by kanddabbia** [google/protobuf#1425]
i try to build protobuf 3.0.0 beta-2.

building environment.
window 10 / msys2

i success to build make. but,
when i try to make check.. i face to this problem..

g++ -DHAVE_CONFIG_H -I. -I..  -I./../gmock/gtest/include -I./../gmock/include                                          -DHAVE_PTHREAD=1 -DHAVE_ZLIB=1 -Wall -Wwrite-strings -Woverloaded-virtual -Wno-s                                       ign-compare -g -DNDEBUG -MT google/protobuf/protobuf_test-any_test.o -MD -MP -MF                                        google/protobuf/.deps/protobuf_test-any_test.Tpo -c -o google/protobuf/protobuf                                       _test-any_test.o `test -f 'google/protobuf/any_test.cc' || echo './'`google/prot                                       obuf/any_test.cc
google/protobuf/any_test.cc:31:41: fatal error: google/protobuf/any_test.pb.h: N                                       o such file or directory
compilation terminated.

how to successfully build protobuf 3.0.0 beta-2 ??

**Comment by xfxyjwf** [comment]
I suggest try cmake build.
