### ISSUE TITLE
protobuf xcode 7 link error: building for iOS simulator, but linking against dylib built for OSX,...libprotobuf-lite.dylib' for architecture x86_64

### ISSUE THREAD

**Issue by tuantuannd** [google/protobuf#1427]
![screen shot 2016-04-20 at 3 08 07 am](https://cloud.githubusercontent.com/assets/13990884/14654157/7db675bc-06a6-11e6-8951-45b2b065bc25.png)

Help me please!

**Comment by nous-** [comment]
Damn wanted an answer for this.
