### ISSUE TITLE
Don't use null_resettable for field declarations in ObjC

### ISSUE THREAD

**Issue by BenchR267** [google/protobuf#1430]
In proto3 all fields are optional, so they should also be optional in the generated code. Currently all the fields are generated as null_resettable which means they are imported to Swift as implicitly unwrapped optionals, so they are not optional, but the code crashes if they are accessed and not set.
My proposal is to generate these fields as nullable, so they are really optional to set.

**Comment by thomasvl** [comment]
We're trying to keep proto2 and proto3 generated messages acting the same (they can be mixed, so developers don't always know which one they are getting).  You shouldn't crash as nil should never be returned from a fetch, the default value should be returned (a message with nothing set, or the empty string, etc.).  Do you have an example where that isn't happening?

**Comment by thomasvl** [comment]
If anyone else comes across this issue, please see some of the discussion on https://github.com/google/protobuf/pull/1431 (sorry, it happened there instead of on the issue itself)

**Comment by BenchR267** [comment]
Yeah, maybe it would have been better to discuss it just here and don't open the pull request :)

**Comment by thomasvl** [comment]
Closing this since the intent isn't to change the api.
