### ISSUE TITLE
Include Javadoc methods in distribution

### ISSUE THREAD

**Issue by nmittler** [google/protobuf#1435]
For now, grpc will have to copy & paste the javadoc code from the protobuf compiler. Ideally it should just be using the same methods to generate its service documentation.

I have a PR on the way ...

**Comment by haberman** [comment]
@nmittler what is the current status of this? I see a couple of open PRs, is one of them on a path to being merged?

**Comment by nmittler** [comment]
@haberman There was a PR but IIRC @xfxyjwf suggested a few reasonably significant changes.  I've wandered onto other things since ... should be easy enough to pick up if someone is interested :)

**Comment by nmittler** [comment]
@zhangkun83 I suspect that nobody is terribly interested in this.  Should we just abandon it for now?

**Comment by zhangkun83** [comment]
@nmittler Agreed.

**Comment by haberman** [comment]
Great, thanks guys.
