### ISSUE TITLE
How to make a sln file in win32 ( protpbuf 3.0.0 c++ vs)

### ISSUE THREAD

**Issue by hyxppz** [google/protobuf#1439]
First I say sorry,I have ask this question a few days ago,I got a replay that "To generate win32 solution files, you can use cmake generator flag: cmake -G "Visual Studio 12 2013" (i.e., omit Win64)."And the question has been closed.
I try this ,but it doesn't work."Cmake error Could not ctrate named generator Visual Studio 12 2013..... "
Is that something wrong with my Computer?
Thanks!

**Comment by xfxyjwf** [comment]
(You can still reply a closed issue.)

This is a cmake issue rather than a protobuf one. Please refer to cmake documentation about how to generate Win32 visual studio solution files.
