### ISSUE TITLE
Attempting to run the benchmark tests results in error:  Unable to get default message for benchmarks.Google{Size,Speed}

### ISSUE THREAD

**Issue by grooverdan** [google/protobuf#1440]
~/protobuf/java$ find . -name \*.jar -ls
20076149   60 -rw-rw-r--   1 danielgb danielgb    58322 Apr 21 13:32 ./util/target/protobuf-java-util-3.0.0-beta-2.jar
20076137 1116 -rw-rw-r--   1 danielgb danielgb  1141121 Apr 21 13:32 ./core/target/protobuf-java-3.0.0-beta-2.jar
20076139  220 -rw-rw-r--   1 danielgb danielgb   221752 Apr 21 13:32 ./lite/target/protobuf-lite-3.0.0-beta-2.jar

~/protobuf/benchmarks$ mkdir tmp
~/protobuf/benchmarks$  javac -d tmp -cp  ../java/core/target/protobuf-java-3.0.0-beta-2.jar  ProtoBench.java
danielgb@p84:~/protobuf/benchmarks$ ../src/protoc --java_out=tmp  google_size.proto google_speed.proto
danielgb@p84:~/protobuf/benchmarks$ cd tmp
danielgb@p84:~/protobuf/benchmarks/tmp$ javac -d . -cp  ../../java/core/target/protobuf-java-3.0.0-beta-2.jar   benchmarks/*.java
Note: benchmarks/GoogleSpeed.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
danielgb@p84:~/protobuf/benchmarks/tmp$  java -cp .:../../java/core/target/protobuf-java-3.0.0-beta-2.jar com.google.protocolbuffers.ProtoBench   benchmarks.GoogleSize$SizeMessage1 ../google_message1.dat  benchmarks.GoogleSpeed$SpeedMessage1 ../google_message1.dat   benchmarks.GoogleSize$SizeMessage2 ../google_message2.dat  benchmarks.GoogleSpeed$SpeedMessage2 ../google_message2.dat
Benchmarking benchmarks.GoogleSize with file ../google_message1.dat
Unable to get default message for benchmarks.GoogleSize
Benchmarking benchmarks.GoogleSpeed with file ../google_message1.dat
Unable to get default message for benchmarks.GoogleSpeed
Benchmarking benchmarks.GoogleSize with file ../google_message2.dat
Unable to get default message for benchmarks.GoogleSize
Benchmarking benchmarks.GoogleSpeed with file ../google_message2.dat
Unable to get default message for benchmarks.GoogleSpeed

**Comment by xfxyjwf** [comment]
@jskeet Is the benchmarks directory still maintained? It seems it hasn't received any real change after its initial commit.
https://github.com/google/protobuf/tree/master/benchmarks

**Comment by jskeet** [comment]
I certainly haven't done anything with it. @jtattermusch had some other benchmarks at one point.
I would suggest we either put some effort into a good benchmarking suite, or delete the benchmarks directory.

**Comment by jtattermusch** [comment]
When migrating the old protobuf-csharp-port project to google/protobuf, I've used these very simple benchmarks to compare Java with C#.

https://github.com/jtattermusch/protobuf-performance-test

**Comment by xfxyjwf** [comment]
Let's remove the benchmarks directory for now? For C++/Java, most of the benchmarks are not opensourced. We probably can only get to it at some later time.

**Comment by grooverdan** [comment]
Thanks for confirming the non-working status of this benchmark code.

I'm looking forward to seeing a open sourced C++ benchmark.

**Comment by grooverdan** [comment]
closed via #1445
