### ISSUE TITLE
Protobuf nano and java annotations

### ISSUE THREAD

**Issue by gchoza** [google/protobuf#1441]
I have a J2Objc project using protobuf nano. The issue I'm having is that the instance variables in the J2Objc-generated Objective C code are iVars and Swift cannot access them directly. I have to use the "valueForKey("mResponseData_")" syntax and cast the result to the correct type which is not ideal.

If I could annotate the generated protobuf Java classes, J2Ojbc could create properties but I have not found a way of annotating my .proto file to add annotations in the generated Java classes.

As a workaround I'm using " option 'optional_field_style=accessors'" to generate accessors for primitive data types. However, reference types do not have generated accessors so for those I'll have to use the "valueForKey" syntax.

Is there a better way of doing this?

Thanks,

Gabriel

**Comment by thomasvl** [comment]
I think you might need to open this over on j2objc, as I believe they have their own custom objc proto code that isn't what the objc generator here does.

**Comment by gchoza** [comment]
I'll open this request in j2objc, however they're using protobuf to generate the Java classes. Is there a way to annotate Java classes generated with Protobuf? J2Objc translates the Java classes into Objc and provides annotations to modify the resulting Objc class (e.g. @Property). It would be nice to be able to annotate the .proto file to have some control over the generated classes. The " option 'optional_field_style=accessors'" almost does what the @Property annotation does but does not generate accessors for reference variables.

**Comment by thomasvl** [comment]
I can't say I have any experience on the java generation, so you'll need someone more familiar with that to comment.

If you can drop j2objc from you question (i.e. - just spell out what you're asking for in the .proto and in the generated .java), there's a better chance other folks can provide the answer.  :)

**Comment by gchoza** [comment]
Thanks, I've updated my question.

**Comment by xfxyjwf** [comment]
Are these annotations Java standard ones or j2obj specific ones? (i.e., to add these annotations do we have to depend some libraries j2obj provides?) I'm fine with adding standard annotations to the generated code but definitely don't want to take a dependency on j2obj.

**Comment by gchoza** [comment]
They are j2objc specific: http://j2objc.org/docs/Property.html

If we cannot have annotations, could we pass comments to the generated Javanano classes? I could include the annotation as a comment and post-process the java class to strip the comment and leave the annotation. The annotation is only used by j2objc to generate properties for the java class variables.

**Comment by xfxyjwf** [comment]
Yes, we can preserve the comments in proto generated code. Can you create a separate issue for that? I'm closing this one as we will not add j2obj annotations.
