### ISSUE TITLE
Lite runtime is not supported in proto3

### ISSUE THREAD

**Issue by Dev-Tony** [google/protobuf#1443]
When I use "option optimize_for = LITE_RUNTIME;" in proto file, I get this error.

But I find a lot of document talks about it, even proto3 https://developers.google.com/protocol-buffers/docs/proto3#options

and release note for proto3 3.0.0-beta-2 talks about it.

I'm really confused... Does proto 3 support lite runtime or note

**Comment by xfxyjwf** [comment]
LITE_RUNTIME is only supported for proto2 syntax files in the 3.0.0-beta-2 release. We just added LITE_RUNTIME support for proto3 in the current github master branch though. Please try it out. It will be included in the next beta release.

**Comment by Dev-Tony** [comment]
ok, understand.
Thank you.
