### ISSUE TITLE
C# plugin generate internal types?

### ISSUE THREAD

**Issue by ananthonline** [google/protobuf#1449]
I need to have the C# code generation plugin for protoc generate internal classes. What I can't figure out for the life of me is now to use this option from within a proto file (not as a command line parameter to protoc), or if this is even possible.

It looks like this change made it in and was perhaps even generating internal types by default for a while before it was fixed in [this][2] PR. Is this change in the protoc compilers shipping with Google.Protobuf.3.0.0-beta2 and/or Grpc.Tools.0.13.1 ?

Can @jtattermusch or @jskeet help me with this? It looks like both were actively involved with this feature being merged in. A small proto snippet showing me how to do this would be much appreciated.

Thanks!

  [1]: https://github.com/google/protobuf/blob/master/src/google/protobuf/compiler/csharp/csharp_generator.cc#L85
  [2]: https://github.com/google/protobuf/pull/1400

**Comment by jskeet** [comment]
No, that pull request happened long after 3.0.0-beta2.

There's no intention to do implement this feature on a per-proto basis. I would suggest just running protoc twice, once for public messages and once for internal ones. You'll either have to build protoc yourself to use the feature, or wait for 3.0.0-beta3.

**Comment by jtattermusch** [comment]
The gRPC C# related part is here: https://github.com/grpc/grpc/pull/6284
(it will be included in Grpc 0.14.0 that will get released soon).

The way you specify the "internal_access" option in the command line (once
both protobuf and grpc are released):

--csharp_out=internal_access:your_outdir_of_choice
--grpc_out=internal_access:your_outdir_of_choice

Some more docs on protobuf code generator options:
https://developers.google.com/protocol-buffers/docs/reference/cpp-generated.

Jan

**Comment by ananthonline** [comment]
Perfect, thanks. I'll wait for 0.14.0 then.
