### ISSUE TITLE
Replace existing benchmarks with working C++/Java benchmarks

### ISSUE THREAD

**Issue by grooverdan** [google/protobuf#1456]
Current benchmark tests aren't open source.

Mentioned here https://github.com/google/protobuf/issues/1440#issuecomment-213564208

Fixes #1440

**Comment by haberman** [comment]
I'm working on this right now. The first step is generating a standard set of test data, which I'm addressing in this PR: https://github.com/google/protobuf/pull/1464

**Comment by grooverdan** [comment]
Thanks @haberman . Closing as addressed in #1464
