### ISSUE TITLE
C# Any.Unpack and Any.Pack seem to allow only a type_url prefixed with type.googleapis.com

### ISSUE THREAD

**Issue by jhickson** [google/protobuf#1459]
Hi,

Looking at the code for `Any.Unpack`, `Any.Pack` and `Any.GetTypeUrl` in AnyPartial.cs it would appear that there's no scope for using my own URL within the type URL rather than type.googleapis.com.  The C++ version would appear to allow more flexibility in this area and, indeed, the C# `TypeUrl` property would appear to allow flexibility as well as the only constraint is that the value it is set to is not null.

Is there a reason for this?

Jos

**Comment by xfxyjwf** [comment]
@jskeet Could you help update the C# implementation to allow custom type URLs? In C++ the unpack method accept any type URL prefix as long as the fully qualified type name matches and the pack method accepts an additional parameter to allow users specify a custom type URL.
