### ISSUE TITLE
Custom options with proto3

### ISSUE THREAD

**Issue by Globegitter** [google/protobuf#1460]
We are trying to use custom options in our application and running into issues under go (https://github.com/golang/protobuf/issues/178). Reading more into the docs I am also seeing that extenstions have been deprecated with proto3, on which custom option currently relies. So I am wondering what the plan is with custom options? Are they still going to be supported going forward (I assume so, as they are being mentioned in the docs)? And if they are supported how would they even work under proto3?

**Comment by xfxyjwf** [comment]
Custom options are still supported. It's the only place where you can use extensions in proto3. It works the same way as in proto2. Languages that don't support proto2 may provide a special API to access custom options as they don't support extensions.

**Comment by Globegitter** [comment]
Ok, thank you for adding some clarification on that. Then we can happily carry on using this feature.
