### ISSUE TITLE
Expose public headers for DocComment functionality.

### ISSUE THREAD

**Issue by jtattermusch** [google/protobuf#1466]
When generating docComments from comments in .proto files, sometimes there's a significant amount of formatting and escaping involved. In gRPC plugins, we need to replicate this code to achieve the same doccomment format when generating comments for gRPC service stubs.

Would it make sense to expose the headers with doc comment functionality as public headers?

https://github.com/google/protobuf/blob/master/src/google/protobuf/compiler/csharp/csharp_doc_comment.h
https://github.com/google/protobuf/blob/master/src/google/protobuf/compiler/java/java_doc_comment.h

**Comment by haberman** [comment]
Could you explain a bit more? The attached headers don't have any documentation about what those functions do. What is the docComment format?

**Comment by jtattermusch** [comment]
they basically take the {leading, trailing} comment from the .proto file and generate  a javadoc or .NET XML doc string that corresponds to the comment (wrapping in the comment accordingly in the <summary></summary> tag. 

See an example of comment taken from duration.proto
https://github.com/google/protobuf/blob/master/csharp/src/Google.Protobuf/WellKnownTypes/Duration.cs#L42

**Comment by xfxyjwf** [comment]
Nathan is working on exposing the Java one:
https://github.com/google/protobuf/issues/1435
https://github.com/google/protobuf/pull/1436

**Comment by anandolee** [comment]
gRPC members abandon the Java one and #1435 is closed. I assume we can abandon this one too
