### ISSUE TITLE
Unrecognized syntax identifier "proto3". This parser only recognizes "proto2". WHEN i try to install python setup.py build

### ISSUE THREAD

**Issue by BKZero** [google/protobuf#1469]
ubuntu 14.04
trying to install caffe interface to python 3.5.
but i got some problem with protobuf.
so when i seek the solution, i see this discuession:
https://github.com/google/protobuf/issues/1276
and i trying to install the protobuf-3.0.0-beta-2.
make and make install seems to be good. but when i try to install the python interface of protobuf, i got this message: 
google/protobuf/any.proto:31:10: Unrecognized syntax identifier "proto3". This parser only recognizes "proto2".
what i did is download the protobuf python package, enter the python directory and python setup.py build. did i make some mistakes?
because i installed the protobuf before by apt-get install libprotobuf-dev, i uninstall it and try 3.0beta install again, but it doesn't help.
is there any one can help me?

**Comment by BKZero** [comment]
i check the protoc --version, it stands 2.5.0. i try to reinstall 3.0 and add the path:
export PATH=$PATH:/usr/local/protobuf/bin
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/protobuf/lib
in /etc/profile. but it doesn't work.

**Comment by acozzette** [comment]
It looks like you added /usr/local/protobuf/bin to the end of your path; I think you need to add it to the beginning instead, since it will be searched in order:

`export PATH=/usr/local/protobuf/bin:$PATH`

**Comment by haberman** [comment]
This sounds like a path issue, not a bug in protobuf. Adam's suggesting of adding to the beginning of your path should do the trick.
