### ISSUE TITLE
 WhichOneof does not work after CopyFrom in Python

### ISSUE THREAD

**Issue by nadavsr** [google/protobuf#147]
Test case: compile this message

```
message FooOrBar {
  oneof test {
    int32 foo = 1;
    int32 bar = 2;
  }
}
```

Run this script:

```
from test_pb2 import FooOrBar

a = FooOrBar()
a.foo = 3
b = FooOrBar()
b.CopyFrom(a)

assert a.WhichOneof('test') == 'foo'
assert a.HasField('foo')
assert b.HasField('foo')
assert b.WhichOneof('test') == 'foo'   # fails in 2.6.1
```

The last assertion should pass. We are using Python 2.7.8, Protobuf 2.6.1 installed from PyPI on Linux.

This is similar to http://code.google.com/p/protobuf/issues/detail?id=671

**Comment by ninowalker** [comment]
It looks like there is a 2.6.1 git tag in the repo: https://github.com/google/protobuf/compare/v2.6.0...v2.6.1, which includes the fix: https://github.com/google/protobuf/compare/v2.6.0...v2.6.1#diff-ce002779e95ca597120c8b0bacc0f448

While it's tagged, it seems nobody has bothered to release it. A DIY cheat sheet for PIP users:

```
git clone https://github.com/google/protobuf.git
cd protobuf
./autogen.sh
./configure
make
sudo make install
cd python
python setup.py build
python setup.py google_test
python setup.py sdist
pip install .
```
