### ISSUE TITLE
Deprecated messages are not annotated in generate Java code

### ISSUE THREAD

**Issue by dimo414** [google/protobuf#1472]
This message:

```
message OldMessage {
  option deprecated = true;
  string old_field = 1 [deprecated = true];
}
```

Generates the following class:

```
public  static final class OldMessage extends
      com.google.protobuf.GeneratedMessage implements
      OldMessageOrBuilder {
  ...
  @java.lang.Deprecated public java.lang.String getOldField() { ... }
  ...
}
```

The `getOldField()` method is correctly annotated, but the class itself is not.

```
$ protoc --version
libprotoc 3.0.0
```

**Comment by pherl** [comment]
Could you elaborate?  What class did you expect to be annotated?

**Comment by pherl** [comment]
So the deprecated annotation only applies to the field, but not the containing class. I'm closing this now. Feel free to reopen it if this is not what you meant.

**Comment by dimo414** [comment]
`OldMessage` should be marked `@Deprecated`, because the message has the [`deprecated` option](https://github.com/google/protobuf/blob/master/src/google/protobuf/descriptor.proto#L418) set to `true`. In the example, *both* `OldMessage` and `getOldField()` should be `@Deprecated`, yet (as of April 2016) only the method is correctly annotated.

**Comment by pherl** [comment]
I see. Will fix it.

**Comment by vjkoskela** [comment]
I am using version 3.4.0 of the compiler (com.github.os72:protoc-jar-maven-plugin) and library (com.google.protobuf:protobuf-java) and while this correctly marks classes generated for messages when the `option deprecated = true;` exists on the message it does not do so when the option is added at the file level (e.g. outside the scope of any particular message) to the class generated for the file. For example:

MyProto.proto
```
option deprecated = true;

message Foo {
    option deprecated = true;
}
```

This generates a Myproto.java which contains a MyProto class which is not annotated with `@Deprecated`. However, the nested class Foo inside MyProto is correctly annotated. I can file a new issue for this if you prefer. Thanks!

**Comment by pherl** [comment]
Note that the file level deprecation might not be so useful as you could set java_multiple_files and the outer file becomes a wrapper for internal variables. Will be fixed in: https://github.com/google/protobuf/pull/3578
