### ISSUE TITLE
GeneratedMessage getAllFields doesn't return empty List

### ISSUE THREAD

**Issue by nykolaslima** [google/protobuf#1478]
The generated class for Java has a method `getAllFields` that calls `getAllFieldsMutable` to get all fields into the message but it doesn't return the field if it's value is a empty list.
There is any reason to do that?
This is causing me a problem with JSON serialization, because I want to serialize empty lists as a JSON empty array but the field isn't returned by `getAllFields`.

```
//getAllFieldsMutable method
if(field.isRepeated()) {
  List value = (List)this.getField(field);
  if(!value.isEmpty()) {
    result.put(field, value);
  }
  continue;
}
```

**Comment by haberman** [comment]
I believe `getAllFields()` is intended to return fields that are set. Repeated fields without any elements are not considered set.

If you want to iterate over all fields, including unset ones, it is probably better to use `Descriptor.getFields()` and iterate over that.

**Comment by nykolaslima** [comment]
Thank you @haberman
