### ISSUE TITLE
when the 3.0 will be release?

### ISSUE THREAD

**Issue by lwlzpn84** [google/protobuf#1479]
when the 3.0 will be release?

**Comment by onlyjob** [comment]
IMHO v3 release is long overdue as Golang ecosystem is already massively uses `proto3` syntax  files in production-ready releases...

**Comment by hsaliak** [comment]
@onlyjob I noticed that you asked a similar question with respect to debian packaging. 
I am interested in finding out more about your use cases there and whats blocking you from using protobuf there until this release happens. 

By the way, we are targeting to release this really soon -  currently targeting end of July.

**Comment by onlyjob** [comment]
> whats blocking you from using protobuf there until this release happens.

A bias towards stable releases. I would feel uncomfortable replacing latest stable release with beta...
Sometimes it may be OK but I can't make this assessment on my own. I'm talking about uploading protobuf to Debian.

> By the way, we are targeting to release this really soon - currently targeting end of July.

Awesome. That would be good news. Thanks. :)

**Comment by CDLuminate** [comment]
@xfxyjwf
So it comes the end of july. Any update on this?

**Comment by xfxyjwf** [comment]
3.0.0 is just released:
https://github.com/google/protobuf/releases/tag/v3.0.0

We are working on uploading language-specific binary packages to their corresponding package distribution sites (maven, PyPI, npm, etc.). @pherl

**Comment by podsvirov** [comment]
Hello all,

now you can try C++ implementation for MSVC2013 32/64bit from [DaD's House](http://dad.podsvirov.pro). It's available in 'testing' release:

[dad-0.3.1-windows-vc12x86-testing.exe](http://download.podsvirov.pro/installers/dad-0.3.1-windows-vc12x86-testing.exe)

and

[dad-0.3.1-windows-vc12x64-testing.exe](http://download.podsvirov.pro/installers/dad-0.3.1-windows-vc12x64-testing.exe).

You can also view other available builds of [Protobuf](http://dad.podsvirov.pro/build?module=protobuf) module.

Some can be interested [gRPC](http://dad.podsvirov.pro/build?module=grpc) module.

**Comment by Croydon** [comment]
@xfxyjwf Is there a place where I can find (official) v3.0 Ubuntu packages?

**Comment by CDLuminate** [comment]
@Croydon 

https://launchpad.net/ubuntu/+source/protobuf

**Comment by Croydon** [comment]
@CDLuminate Awesome, thanks! Last time I checked it out there was no 3.0 version :)
