### ISSUE TITLE
LoadError for "google/protobuf/descriptor" when using Ruby Gem

### ISSUE THREAD

**Issue by blowmage** [google/protobuf#1481]
The current versions of the ruby gem include well known protobuf files. However, not all well known protobuf files are available because the ruby code can't parse proto2 files yet. For example, [googleapi's `google/api/annotations.proto`](https://github.com/googleapis/googleapis/blob/master/google/api/annotations.proto) file has the following [import](https://github.com/googleapis/googleapis/blob/master/google/api/annotations.proto#L20):

``` proto
import "google/protobuf/descriptor.proto";
```

When we generate the ruby code for this proto file we get the following ruby code:

``` ruby
require 'google/protobuf/descriptor'
```

Unfortunately the google-protobuf ruby gem does not include this file, so the require raises LoadError. To work around this we have to place an empty file in our project so that the require no longer raises. Can the ruby gem include a dummy file at this path until the gem is able to provide the ruby version of the proto2 file?

**Comment by xfxyjwf** [comment]
Please reopen if the problem still persist in latest versions.
