### ISSUE TITLE
3.0.0.alpha.5.0.5.1 is only available for Darwin, breaks dependencies

### ISSUE THREAD

**Issue by timanovsky** [google/protobuf#1485]
https://rubygems.org/gems/google-protobuf/versions

https://github.com/grpc/grpc/issues/6427 and downstream to https://github.com/GoogleCloudPlatform/gcloud-ruby/releases/tag/v0.8.1

**Comment by jtattermusch** [comment]
@haberman   @xfxyjwf   this breaks gRPC continuous builds and is a P0 for us https://github.com/grpc/grpc/issues/6428.

**Comment by blowmage** [comment]
Related to #1480

**Comment by blowmage** [comment]
This looks to be fixed. I'm seeing version [3.0.0.alpha.5.0.5.1 available on all platforms](https://rubygems.org/gems/google-protobuf/versions). @timanovsky, @jtattermusch can you confirm?

**Comment by blowmage** [comment]
@timanovsky If this is resolved can you close the issue?

**Comment by timanovsky** [comment]
Works for me now

**Comment by jtattermusch** [comment]
Yes, works for us now.
