### ISSUE TITLE
Oneof should have its own options

### ISSUE THREAD

**Issue by ngthanhtrung** [google/protobuf#1488]
Currently oneof doesn't have options compared to file, message, etc. I think it would be more convenient to support that, because I often find myself wanting to extend oneof for my own need (like providing additional classes to mix into the generated super class of oneof, suppose that it's a custom code generator). What do you think?

**Comment by xfxyjwf** [comment]
It seems an oversight to not have options for oneof as all other types have options. @anandolee do you know why we haven't added options for oneof?

**Comment by anandolee** [comment]
I don't know why it is not in the original design. I think it is reasonable to add options to oneof, I got request from others too.

**Comment by anandolee** [comment]
Looked into other types, they all have their own options besides customer options. I guess this is why we do not have options in the original oneof design. However, it make sense to add it for customer options. Will add

**Comment by ngthanhtrung** [comment]
Do you guys need a PR? I can create one.

**Comment by anandolee** [comment]
Thanks for your willing to help. We already have a change in internal code. It will be included in next release.
