### ISSUE TITLE
What is the alternative of google::protobuf::internal::NewCallback?

### ISSUE THREAD

**Issue by mayah** [google/protobuf#1505]
Hi, I'm migrating an app from proto2 and proto3, and I found google::protobuf::NewCallback is moved to google::protobuf::internal::NewCallback (in 7c14dc837b2fcd61ed244ced90debeb4b42d1119). Since it's in `internal` namespace, I thought you don't want us to use NewCallback (and also NewPermantCallback).

Do we need to implement Closure* by ourselves?  Is there any alternative?

**Comment by xfxyjwf** [comment]
I don't think there is any protobuf public API requiring the use of NewCallback(). Could you consider using std::function/std::bind and lambdas in C++?

**Comment by mayah** [comment]
Thank you for the reply. I'll try another method.
