### ISSUE TITLE
Can't use google.protobuf.Any with javanano

### ISSUE THREAD

**Issue by blakearnold** [google/protobuf#1508]
When compiling a proto that contains an `Any` field with the javanano compiler I receive the following error: `Import "google/protobuf/struct.proto" was not found or had errors.`

**Comment by xfxyjwf** [comment]
Is the proto file in your proto import path when you invoke protoc?

**Comment by xfxyjwf** [comment]
also could you check the version of the protoc binary you are using?
```bash
$ protoc --version
```

**Comment by blakearnold** [comment]
I'm using the gradle plugin: https://github.com/google/protobuf-gradle-plugin/
I setup an example project here: https://github.com/blakearnold/failing_nano
The three branches I used for debugging:
- proto_nano_deps - does not generate the javanano code `google/protobuf/struct.proto: File not found.`
- deps_on_javaproto - I added `com.google.protobuf:protobuf-java:3.0.0-alpha-5` as a dependency. It will now generate the javanano code but doesn't compile. `error: cannot find symbol public com.google.protobuf.nano.Struct data;`
- non_nano - compiles fine (regular proto)

```
git checkout proto_nano_deps
./gradlew build

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':generateProto'.
> protoc: stdout: . stderr: /Users/blake/projects/failing_nano/build/extracted-protos/main: warning: directory does not exist.
  /Users/blake/projects/failing_nano/build/extracted-include-protos/main: warning: directory does not exist.
  google/protobuf/struct.proto: File not found.
  example.proto: Import "google/protobuf/struct.proto" was not found or had errors.
  example.proto:12:3: "google.protobuf.Struct" is not defined.
```

```
git checkout deps_on_javaproto
./gradlew build

:extractIncludeProto
:extractProto UP-TO-DATE
:generateProto UP-TO-DATE
:compileJava
/Users/blake/projects/failing_nano/generated/main/javanano/com/blakearnold/proto/nano/Example.java:24: error: cannot find symbol
  public com.google.protobuf.nano.Struct data;
                                 ^
  symbol:   class Struct
  location: package com.google.protobuf.nano
/Users/blake/projects/failing_nano/generated/main/javanano/com/blakearnold/proto/nano/Example.java:72: error: cannot find symbol
            this.data = new com.google.protobuf.nano.Struct();
                                                    ^
  symbol:   class Struct
  location: package com.google.protobuf.nano
2 errors
:compileJava FAILED
```

```
git checkout non_nano
./gradlew build
:extractIncludeProto
:extractProto UP-TO-DATE
:generateProto
:compileJava
:processResources
:classes
:jar
:assemble
:extractIncludeTestProto
:extractTestProto UP-TO-DATE
:generateTestProto UP-TO-DATE
:compileTestJava UP-TO-DATE
:processTestResources UP-TO-DATE
:testClasses UP-TO-DATE
:test UP-TO-DATE
:check UP-TO-DATE
:build

BUILD SUCCESSFUL
```

**Comment by xfxyjwf** [comment]
@zhangkun83 Kun, could you help take a look?

**Comment by zhangkun83** [comment]
The proto3 built-in types (empty.proto, timestamp.proto etc ) are not shipped with the protobuf-javanano jar. It seems to me that nano doesn't support these types.

**Comment by xfxyjwf** [comment]
@blakearnold could you obtain a copy of the .proto files for these built-in types (e.g., [struct.proto](https://github.com/google/protobuf/blob/master/src/google/protobuf/struct.proto) ) and build them together with your own .proto files?

**Comment by blakearnold** [comment]
@xfxyjwf Yes, I'll use that as a work around. Any chance we can get the built-in types that _do_ work with nano compiled into the jar?

**Comment by haberman** [comment]
We have no plans to make any further changes to nano, sorry.
