### ISSUE TITLE
"import" statements in Ruby DSL?

### ISSUE THREAD

**Issue by slnovak** [google/protobuf#1516]
Hi,

I'm trying to use the Ruby DSL for decoding a JSON message with a `Timestamp` datatype. However, I'm receiving `ArgumentError: Unknown field type.` when trying to define the field inside a `add_message` block. I've read that you need to include an `import` statement in `.proto` definitions -- is there a way to do this via that Ruby DSL?

Thanks!

**Comment by haberman** [comment]
Sorry for the slow reply to your question!

The DSL is not well-documented; it is mainly intended to be used by `protoc` generated code. The best way to see how to write the DSL correctly is to use `protoc` with a `.proto` file to see what the compiler spits out.

Feel free to re-open if this doesn't fix your problem.
