### ISSUE TITLE
macro `AM_PROG_AR' not found in library

### ISSUE THREAD

**Issue by louwersj** [google/protobuf#152]
When running autogen.sh I do get an issue arround AM_PROG_AR, more specifically I do get:

configure.ac:57: error: possibly undefined macro: AM_PROG_AR

The full trace is at:  http://pastebin.com/Hi2CESx4

Any thoughts on the root cause and/or how to resolve this? I an using Oracle Linux (Kernel: 3.8.13-16.2.2.el6uek.x86_64) 

Thanks already!
Regards,
Johan.

**Comment by louwersj** [comment]
I commented out line 57 in configure.ac and was able to compile and install protobuf.... it looks like AM_PROG_AR is not used really..... however for some reason is included.... 

Do I overlook something?

**Comment by xfxyjwf** [comment]
That macro AM_PROG_AR is defined by automake: http://www.gnu.org/software/automake/manual/html_node/Public-Macros.html

Maybe it's that the automake you were using is not newer enough to have that macro? I added that line because automake reports a warning and asks to add that macro in the configure.ac file.

**Comment by louwersj** [comment]
Might be the case.... I will be testing it on a newer version somewhere this weekend and let you know. However, might be good for people to know that commenting out the line when you hit the error will still compile the code and you will not find (up until now) any technical issues with the compiled code. :-)

**Comment by itfanr** [comment]
edit the file configure.ac as follows:

delete the line AM_PROG_AR and add m4_ifdef([AM_PROG_AR], [AM_PROG_AR])
