### ISSUE TITLE
Google.ProtoBuf Nuget package is pre-release

### ISSUE THREAD

**Issue by ananthonline** [google/protobuf#1526]
This means that due to [Nuget-1365](https://github.com/NuGet/Home/issues/1365), we cannot currently include this version of Google.ProtoBuf (and consequently use Grpc, which is not pre-release anymore) in a non pre-release package.

Are there any specific reasons to not remove the pre-release tag on the Nuget package? This is a blocker for me.

**Comment by xfxyjwf** [comment]
I think grpc is also still pre-release. The grpc version number on nuget is 0.14.0:
https://www.nuget.org/packages/Grpc/

**Comment by ananthonline** [comment]
For Nuget, having a [text-suffix to a version number](https://docs.nuget.org/create/versioning#prerelease-versions) means it's pre-release. I created an issue [here](https://github.com/grpc/grpc/issues/5796) for Grpc and got them to remove the *beta* part of the version. Could we do the same for Google.ProtoBuf?

**Comment by xfxyjwf** [comment]
Protobuf 3.0.0 hasn't reached GA status yet. It doesn't seem wise to remove the beta tag now. @jskeet Jon, what do you think?

**Comment by jskeet** [comment]
I completely agree. The Google.Protobuf package *is* still prerelease.

I'm surprised that NuGet views v0.* as non-pre-release - SemVer definitely states it's not expected to be stable:

> Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.

(That was in SemVer 1.0.0 and 2.0.0.)

You should treat both Google.Protobuf and Grpc as pre-release software at the moment.
