### ISSUE TITLE
Release 3.0.0-beta-3 doesn't have linux pre-built binaries 

### ISSUE THREAD

**Issue by pcorpet** [google/protobuf#1552]
Thanks for the new release, I'm excited to use the new CommonJS bindings on the protocompiler. I know I could buid the binaries myself but I would love to see the pre-built binaries released for linux x86-64 as well, so that I can follow your advice in the doc:

> For non-C++ users, the simplest way to install the protocol compiler is to download a pre-built binary from our release page:

**Comment by jtattermusch** [comment]
You might be able to use the grpc-tools package that contains pre-build version of protoc for mac, linux and windows.

https://www.npmjs.com/package/grpc-tools

**Comment by jtattermusch** [comment]
CC @murgatroid99

**Comment by pherl** [comment]
I have updated the release page to include protoc for multiple platforms. Let me know if that works for you.

**Comment by pcorpet** [comment]
Thanks @pherl , that's perfect!
