### ISSUE TITLE
Does V3 support FieldOptions with C#?

### ISSUE THREAD

**Issue by LazyPlanet** [google/protobuf#1553]
syntax = "proto3";

import "google/protobuf/descriptor.proto";

package ShareCommon;

extend google.protobuf.FieldOptions {
	int32 comm = 500001;
}

message Bar {
	int32 rate = 1 [(comm) = 1];
}

**while i cannot find "comm" in the .cs file.** Thank u.

**Comment by jskeet** [comment]
Am I right in saying this is a duplicate of #1603, effectively?

**Comment by LazyPlanet** [comment]
Right.
