### ISSUE TITLE
build status freezed when compiles google/protobuf/util/internal/protostream_objectwriter_test.cc

### ISSUE THREAD

**Issue by xueeinstein** [google/protobuf#1557]
I'm trying to build protobuf on arch linux with gcc 6.1.1. 
When compiles the file `google/protobuf/util/internal/protostream_objectwriter_test.cc`, it continually eats CPU but the build status doesn't update anymore, it already cost over 40 minutes.  I'm not sure whether it's the compatible issue of the newest gcc.

**Comment by xueeinstein** [comment]
In addition, it still has enough free memory.

**Comment by xfxyjwf** [comment]
If it takes that long to compile, I bet it must be an issue in the compiler rather than in the code.

**Comment by xueeinstein** [comment]
After downgrade to gcc 5.3.2, it builds successfully. Thanks a lot.
