### ISSUE TITLE
Regression: Missing platform-specific rubygems for 3.0.0.alpha.6.0.0

### ISSUE THREAD

**Issue by blowmage** [google/protobuf#1564]
There only seems to be one gem for 3.0.0.alpha.6.0.0, which was released today. Previous releases included precompiled gems for common platforms.

**Comment by blowmage** [comment]
@haberman Thoughts on this?

**Comment by blowmage** [comment]
This is an issue since this latest gem requires that the protobuf library is installed in order to use the gem. We are relying on the precompiled gems so users don't have to install the protobuf library.

**Comment by xfxyjwf** [comment]
Please file a separate issue if the problem still persist in the latest v3.2.0 release.
