### ISSUE TITLE
C# reflectionclass, why using String.Concat?

### ISSUE THREAD

**Issue by chrisdunelm** [google/protobuf#1567]
Why does the generated C# code for reflection classes use String.Concat("a", "b"), rather than using "a"+"b", which would allow concatenation at compile-time rather than runtime?
https://github.com/google/protobuf/blob/667f4a6282f9d7e7edb0acc8758e384b17a0359d/src/google/protobuf/compiler/csharp/csharp_reflection_class.cc#L154

**Comment by jskeet** [comment]
I believe at one point we *did* use compile-time concatenation, but that then caused issues. I can't remember *exactly* what the issues were - they could be any of:

- Execution-time limits (possibly on Mono?)
- Visual Studio issues
- Compiler issues

I'm sure it was deliberate though.
