### ISSUE TITLE
Js bindings don't generate any .fromObject function

### ISSUE THREAD

**Issue by pcorpet** [google/protobuf#1569]
It seems the code is ready for it (search for GenerateClassFromObject), but it's never called. Maybe the goal was to add an option for it, but as for now it doesn't seem possible to use it.

**Comment by hochhaus** [comment]
This is related to Issue #1591. I think the option name is jspb.generate_from_object.

**Comment by acozzette** [comment]
Let me go ahead and close this issue because most of the conversation about this has been happening on #1591.
