### ISSUE TITLE
Including both parent and child directory finds enum definition twice

### ISSUE THREAD

**Issue by wakjah** [google/protobuf#1570]
In a directory with the following structure:

```
root
-- src
---- subdir
------ SomeEnum.proto
------ SomeMessage.proto
```

If I try to compile with both src and src/subdir as include directories, protoc fails complaining that the enum values are already defined. If compiling with just src/subdir as an include directory, it works as expected.

SomeEnum.proto is:

```
option java_outer_classname = "SomeEnumProtos";

enum SomeEnum
{
    Value0 = 0;
    Value1 = 1;
}
```

SomeMessage.proto is:

```
import "SomeEnum.proto";

option java_outer_classname = "SomeMessageProtos";

message SomeMessage
{
    optional SomeEnum something = 1;
}
```

This succeeds as expected:
`protoc -Isrc/subdir --java_out=. src/subdir/SomeEnum.proto src/subdir/SomeMessage.proto`

Whereas this fails with a bit of a strange error:
```
protoc -Isrc -Isrc/subdir --java_out=. src/subdir/SomeEnum.proto src/subdir/SomeMessage.proto 
SomeEnum.proto:5:5: "Value0" is already defined in file "subdir/SomeEnum.proto".
SomeEnum.proto:5:5: Note that enum values use C++ scoping rules, meaning that enum values are siblings of their type, not children of it.  Therefore, "Value0" must be unique within the global scope, not just within "SomeEnum".
SomeEnum.proto:6:5: "Value1" is already defined in file "subdir/SomeEnum.proto".
SomeEnum.proto:6:5: Note that enum values use C++ scoping rules, meaning that enum values are siblings of their type, not children of it.  Therefore, "Value1" must be unique within the global scope, not just within "SomeEnum".
SomeEnum.proto:3:6: "SomeEnum" is already defined in file "subdir/SomeEnum.proto".
subdir/SomeMessage.proto: Import "SomeEnum.proto" was not found or had errors.
subdir/SomeMessage.proto:7:14: "SomeEnum" seems to be defined in "subdir/SomeEnum.proto", which is not imported by "subdir/SomeMessage.proto".  To use it here, please add the necessary import.


```

Some context: This situation has arisen in using the Gradle protobuf plugin, because the plugin always adds the default root proto source directory to the includes. When calling protoc from make / shell script, we have been able to avoid adding this directory to the includes, but it is more challenging to do so under the Gradle protobuf plugin, hence exposing this potential bug.

**Comment by xfxyjwf** [comment]
This is working as intended.

For every .proto file there is a canonical path and that's what you use in the "import" statement inside a .proto file. Protoc determines this canonical path of each .proto file by matching the specified file path to the "-I" flags. Given this invocation:
```bash
$ protoc -Isrc -Isrc/subdir --java_out=. src/subdir/SomeEnum.proto src/subdir/SomeMessage.proto 
```
protoc will determine the two files' canonical names are subdir/SomeEnum.proto and subdir/SomeMessage.proto respectively and that's what you should be using in the "import" statement.  If you instead use other names, protoc will treat them as different files and you will end up with these duplication errors.

The easiest fix is to change "import 'SomeEnum.proto'" to "import 'subdir/SomeEnum.proto'". If that's not desirable, the alternative is to ask gradle plugin to remove the default "-Isrc" flag.
