### ISSUE TITLE
The deployed protobuf-java 3.0.0-beta-3 pom contain an invalid  parent 

### ISSUE THREAD

**Issue by namtzigla** [google/protobuf#1571]
Hi,

this is more an FYI in case nobody notice it.
the deployed [pom](http://repo1.maven.org/maven2/com/google/protobuf/protobuf-java/3.0.0-beta-3/protobuf-java-3.0.0-beta-3.pom) for 3.0.0-beta-3 has an invalid parent.  
```
<parent>
<groupId>com.google.protobuf</groupId>
<artifactId>protobuf-parent</artifactId>
<version>3.0.0-beta-3</version>
</parent>
```

**Comment by craigday** [comment]
Its not invalid. It just hasn't been uploaded to central.

**Comment by LeanderK** [comment]
its on maven central now: http://search.maven.org/#artifactdetails%7Ccom.google.protobuf%7Cprotobuf-parent%7C3.0.0-beta-3%7Cpom

**Comment by namtzigla** [comment]
thanks !
