### ISSUE TITLE
Why no `java_proto_library` ?

### ISSUE THREAD

**Issue by darkcrawler01** [google/protobuf#1577]
i notice `cc_proto_library`and `py_proto_library` are added to BUILD file.
is there any plan for adding `java_proto_library`?

my real problem, is that I am trying to use `any.proto` from `well_known_protos` 
but i am finding it really hard to read the include `srcs` from that filegroup to a custom `skylark` rule.

**Comment by llhe** [comment]
+1

**Comment by xfxyjwf** [comment]
@cgrushko @lberki I remember java_proto_library was added to bazel a while ago and there was https://github.com/bazelbuild/bazel/issues/1817 on the bazel repo. Is there any documentation about how to use it?

**Comment by cgrushko** [comment]
I believe https://github.com/bazelbuild/rules_go/pull/121#issuecomment-251515362 sheds some light on this?

**Comment by pcj** [comment]
@darkcrawler01 @llhe I can attest it is actually not trivial to figure out how to use the well known protos in bazel.  Here's an example in go, but you can use the same recipe for `java_proto_library` in the same repo.

https://github.com/pubref/rules_protobuf/blob/master/examples/wkt/go/BUILD

**Comment by xfxyjwf** [comment]
@cgrushko 

What I'm asking for is more specific java_proto_library examples showing how it actually works from users' perspective. I understand that users would need to write rules like this in their BUILD file (as seen in: https://github.com/bazelbuild/bazel/issues/1817):
```
proto_library(
  name = "coord_proto",
  srcs = ["coord.proto"],
)

java_proto_library(
  name = "coord_proto_lib",
  deps = [":coord_proto"],
)
```
The questions:
1. What is the user supported to put in their WORKSPACE to make it actually work? Right now the above BUILD file simply fails (as mentioned in https://github.com/bazelbuild/bazel/issues/1817).
2. How is this going to work with well-known types? Are we supposed to add java_proto_library BUILD rules to protobuf's own BUILD file to make it work?

Ideally, the user should only need to put protobuf somewhere in his workspace, and then use the following BUILD file to build a proto using well-known types:
```
proto_library(
  name = "coord_proto",
  srcs = ["coord.proto"],
  deps = ["//google/protobuf:timestamp"],
)
java_proto_library(
  name = "coord_proto_java",
  deps = [":coord_proto"],
)
```
That's what we have inside Google. We should have something as simple as it to opensource users when using bazel.

**Comment by cgrushko** [comment]
For 1, see https://github.com/bazelbuild/bazel/issues/1817#issuecomment-257422673 . It's currently not particularly pretty, but I have a plan.

For 2, somebody will have to create those. Ideally the protobuf-team will put `proto_library` rules in place (your example doesn't require `java_proto_library`, only `proto_library`).

**Comment by xfxyjwf** [comment]
@cgrushko Thanks. I'll give it a try.  I can add proto_library rules to protobuf but only after I figure out how it actually works :)

**Comment by xfxyjwf** [comment]
An update on the java_proto_library rule.

So I was able to get the java_proto_library rule working by putting protobuf in the location desired by bazel and a WORKSPACE file specifying the correct path for protobuf Java runtime:
https://github.com/xfxyjwf/bazel_proto_examples

It however doesn't work well-known types. I poked around it a little bit and believe we are going to need some more attributes on the proto_library rule to support well-known types. Right now it's not possible with the bazel built-in proto_library/java_proto_library rule.

**Comment by psaville-google** [comment]
xfxyjwf,

Regarding your response, do you have an understanding of what might be needed for the bazel built-in java_proto_library rules to work with well-known types?

If you have a rough idea, could you share it and potentially I could give it a shot?

**Comment by cgrushko** [comment]
Is this covered by https://github.com/bazelbuild/bazel/issues/2039 ?

**Comment by xfxyjwf** [comment]
@psaville-google Thanks for offering help. The issue @cgrushko pointed to is one of the blocking issues for well-known types to work. It's not clear to me how to fix that though.
