### ISSUE TITLE
under_score to camel_case

### ISSUE THREAD

**Issue by mehrdadjahangirisc** [google/protobuf#1582]
I have some json with under_scored key names: myjsonTxt="{page_position: 1, data_size: 10}"
I've created a proto similarly: message MyData {int32 page_position = 1; int32 data_size=2; }
I do the following two lines to read/parse from json and create proto:
MyData.Builder d = MyData.newBuilder();
JsonFormat.parser().merge(myjsonTxt, d);

But it fails because of under_score. it requires pagePosition in the json, not page_position. is there any param I can set to convert under_score to camel_case? or any tools I can use to overcome?

I appreciate your help immensely.
Regards.

**Comment by haberman** [comment]
What language are you using? It appears to be Java?

**Comment by mehrdadjahangirisc** [comment]
Yes, java.

**Comment by xfxyjwf** [comment]
Which version are you using? The JSON parser should be able to accept snake_case names after beta-2 release.

**Comment by xfxyjwf** [comment]
There is also an option for the JSON printer to use snake_case names as declared in the .proto file:
https://github.com/google/protobuf/blob/master/java/util/src/main/java/com/google/protobuf/util/JsonFormat.java#L153

**Comment by mehrdadjahangirisc** [comment]
I was using 3.0.0-beta-1, upgraded to 3.0.0-beta-2 and no change.

@xfxyjwf yes, the option is for printer, but parser doesn't have such options.

**Comment by xfxyjwf** [comment]
The Parser is expected to accept both snake_case and lowerCamelCase names by default and we have tests to ensure this:
https://github.com/google/protobuf/blob/master/java/util/src/test/java/com/google/protobuf/util/JsonFormatTest.java#L1171

I don't know what's going wrong in your case.

**Comment by mehrdadjahangirisc** [comment]
My mistake. beta-2 wasn't enforced. I was still using beta-1, hence didn't work.
Once I upgraded to beta-2, it works like a charm. thank you for insisting and showing me the code.
I appreciate it very much.
