### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by worm2fed** [google/protobuf#1584]
last log i've seen is

`libtool: link: g++ -pthread -DHAVE_PTHREAD=1 -DHAVE_ZLIB=1 -Wall -Wwrite-strings -Woverloaded-virtual -Wno-sign-compare -march=native -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -pthread -Wl,-O1 -Wl,--sort-common -Wl,--as-needed -Wl,-z -Wl,relro -o .libs/zcgunzip google/protobuf/testing/zcgunzip.o  ./.libs/libprotobuf.so -lpthread -lz -pthread`

There are no errors in console. After 8 hours i broke up compilation. 

I don't think it's correct.

Can u help me?

I use archlinux:
`worm2fed@tarvos ~ $ uname -a
Linux tarvos 4.5.5-1-ck #1 SMP PREEMPT Thu May 19 03:37:02 EDT 2016 x86_64 GNU/Linux
`

**Comment by haberman** [comment]
This is a very unusual problem that I've never heard of before. If you can reproduce this problem please re-open and we'll see if we can help.
