### ISSUE TITLE
Protoc generated cpp and header files differ depending on the directory where the compiler call was invoked.

### ISSUE THREAD

**Issue by bratke** [google/protobuf#1592]
I compiled the same file 2 times but used different folder locations to invoke the compiler call:

```
$ protoc --version
libprotoc 2.6.1
$ protoc --proto_path=/usr/include -I. --cpp_out=. new/openrtb.proto
$ cd new/
$ protoc --proto_path=/usr/include -I. --cpp_out=../. openrtb.proto
$ cd ..
```

This will generate new/openrtb.pb.cc, new/openrtb.pb.h (1st call) and openrtb.pb.cc and openrtb.pb.h (2nd call).

I expected both files to be equal.
But that is not the case.
Some methods included the folders name 'new' into their names.
These methods become important when another .proto file tries to include openrtb.proto (example).

```
$ diff new/openrtb.pb.h openrtb.pb.h
2c2
< // source: new/openrtb.proto
---
> // source: openrtb.proto
4,5c4,5
< #ifndef PROTOBUF_new_2fopenrtb_2eproto__INCLUDED
< #define PROTOBUF_new_2fopenrtb_2eproto__INCLUDED
---
> #ifndef PROTOBUF_openrtb_2eproto__INCLUDED
> #define PROTOBUF_openrtb_2eproto__INCLUDED
35,37c35,37
< void  protobuf_AddDesc_new_2fopenrtb_2eproto();
< void protobuf_AssignDesc_new_2fopenrtb_2eproto();
< void protobuf_ShutdownFile_new_2fopenrtb_2eproto();
---
> void  protobuf_AddDesc_openrtb_2eproto();
> void protobuf_AssignDesc_openrtb_2eproto();
> void protobuf_ShutdownFile_openrtb_2eproto();
1300,1302c1300,1302
<   friend void  protobuf_AddDesc_new_2fopenrtb_2eproto();
<   friend void protobuf_AssignDesc_new_2fopenrtb_2eproto();
<   friend void protobuf_ShutdownFile_new_2fopenrtb_2eproto();
---
>   friend void  protobuf_AddDesc_openrtb_2eproto();
>   friend void protobuf_AssignDesc_openrtb_2eproto();
>   friend void protobuf_ShutdownFile_openrtb_2eproto();

(some more)

7530,7532c7530,7532
<   friend void  protobuf_AddDesc_new_2fopenrtb_2eproto();
<   friend void protobuf_AssignDesc_new_2fopenrtb_2eproto();
<   friend void protobuf_ShutdownFile_new_2fopenrtb_2eproto();
---
>   friend void  protobuf_AddDesc_openrtb_2eproto();
>   friend void protobuf_AssignDesc_openrtb_2eproto();
>   friend void protobuf_ShutdownFile_openrtb_2eproto();
20562c20562
< #endif  // PROTOBUF_new_2fopenrtb_2eproto__INCLUDED
---
> #endif  // PROTOBUF_openrtb_2eproto__INCLUDED
```

So the actual problem is the following:

If another .proto file includes openrtb.proto like this:
`import "new/openrtb.proto";` it will rely on new/openrtb.pb.cc and new/openrtb.pb.h.

And in case it does the following:
`import "openrtb.proto";` it will rely on openrtb.pb.cc and openrtb.pb.h.

If you would swap new/openrtb.pb.* with openrtb.pb.* any cpp compiler would stuck. Because it will not find the correct methods mentioned above.

If you have a directory structure like this:

```.
├── foo.proto // import "new/openrtb.proto"
└── new
    ├── bar.proto // import "openrtb.proto"
    └── openrtb.proto
```

You will not be able to share the library openrtb.proto when using generated cpp files.

This issue is related to the cmake limitation "The protobuf_generate_cpp and protobuf_generate_python functions and add_executable() or add_library() calls only work properly within the same directory." https://cmake.org/cmake/help/v3.5/module/FindProtobuf.html#command:protobuf_generate_cpp

Any help would be appreciated.

**Comment by xfxyjwf** [comment]
The behavior of protoc is working as intended. Basically the path you use in a "import" statement is the unique name of a .proto file as seen by the protocol compiler and it has to be identical everywhere if the file is imported by multiple other files. In your example, you either have to change "import new/openrtb.proto" to "import openrtb.proto" and compile the protos as such:
```bash
$ protoc --proto_path=new --proto_path=. foo.proto new/bar.proto new/openrtb.proto
```
or change "import openrtb.proto" to "import new/openrtb.proto" and compile the protos as such:
```bash
$ protoc foo.proto new/bar.proto new/openrtb.proto
```
Either will work but I guess you probably want the former because you probably also have "old/bar.proto" "old/oepnrtb.proto" in the same directory tree and want to replace them with the new one without changing the content of .proto files. 

The problem of the cmake "protobuf_generate_cpp" function is that it's missing the support for the --proto_path flag.

**Comment by bratke** [comment]
Thanks for your quick reply.

```.
├── foo.proto // import "new/openrtb.proto"
└── new
    ├── bar.proto // import "new/openrtb.proto"
    └── openrtb.proto
```

Seems to be the way to go if you want to build a shared lib out of foo.proto and bar.proto.
Since this is intended i wont complain any longer ;)
