### ISSUE TITLE
Protoc: How to generate multiple Objective-C source files?

### ISSUE THREAD

**Issue by xboy-im** [google/protobuf#1598]
Protoc: How to generate multiple Objective-C source files for one .proto file?
 Thank you.

**Comment by thomasvl** [comment]
All the enums and messages in a given .proto file will be defined in a single .pbobjc.m/.pbobjc.h pair.

Were you looking for a separate file pair for each enum/message?  Any specific reason?

**Comment by brilliance-boy** [comment]
@thomasvl  same as “option java_multiple_files = true;”

**Comment by thomasvl** [comment]
Yea, no other generators support anything like that.

Again, is there a reason you wanted multiple files?  Normally the single files approach is easier to integrate into build systems.

**Comment by raviswan** [comment]
Is this feature still not supported for objective-C?

**Comment by thomasvl** [comment]
> Is this feature still not supported for objective-C?

Nor by most of languages.
