### ISSUE TITLE
Java source and Javadoc missing for 3.0.0-beta-3 on Maven Central

### ISSUE THREAD

**Issue by ejona86** [google/protobuf#1605]
There doesn't seem to be a source jar nor javadoc:
http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.google.protobuf%22%20AND%20a%3A%22protobuf-java%22%20AND%20v%3A3.0.0-beta-3
https://repo1.maven.org/maven2/com/google/protobuf/protobuf-java/3.0.0-beta-3/

beta 2 had the source jar and javadoc:
http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.google.protobuf%22%20AND%20a%3A%22protobuf-java%22%20AND%20v%3A3.0.0-beta-2

When the packaging is jar (the default) Sonatype will also fail to release without the source jar. The packaging of 'bundle' may be why this was permitted.

CC @nmittler

**Comment by xfxyjwf** [comment]
The packaging is "bundle" in beta-2 as well, but in beta-3 two plugin configurations are missing: maven-source-plugin and maven-javadoc-plugin. They are originally in the beta-2 pom.xml file:
https://repo1.maven.org/maven2/com/google/protobuf/protobuf-java/3.0.0-beta-2/protobuf-java-3.0.0-beta-2.pom

**Comment by xfxyjwf** [comment]
Fixed in beta-4.
