### ISSUE TITLE
Podspec not working with Frameworks and CocoaPods 1.0.0

### ISSUE THREAD

**Issue by jafara** [google/protobuf#1607]
This might be a CocoaPods issue but the generated code fails to compile.

See screenshot:
![screen shot 2016-05-26 at 3 39 05 pm](https://cloud.githubusercontent.com/assets/7128658/15592360/ff3b55e4-2357-11e6-9638-cc8f08b5e09b.png)

Looks like the subpath `google/protobuf/Any.pbobjc.h` or any other header within `google/protobuf` cannot be found.

Actually removing `google/protobuf` fixes the problem but obviously this is not the right solution.

Podfile:

```ruby
source 'https://github.com/CocoaPods/Specs'

platform :ios, '8.0'

use_frameworks!

target 'SampleApp' do
  pod 'Protobuf', '3.0.0-alpha-4.1'
end
```

**Comment by thomasvl** [comment]
This is a dup of https://github.com/google/protobuf/issues/1457, we landed a fix on trunk recently for this, but it hasn't made it out into a release.  The next protobuf release should pick up the updated code/podspec.
