### ISSUE TITLE
GPBDictionary classes accidentally overriding NSObjects KVC category

### ISSUE THREAD

**Issue by thomasvl** [google/protobuf#1616]
In most of the custom _dictionary_ classes from the library, we used the natural names `-valueForKey:` and `-setValue:forKey:`, without anyone noticing we were using the same names as the NSObject KVC category.  Since the args and results don't match KVC, this means someone could try to keypath through the object and instead of it working, it will likely fail or blow up depending on the types and values actually used.

**Comment by thomasvl** [comment]
Possible Solutions

**Option 1 - Do Nothing**
Accept that the warning can be triggered, and document that developer shouldn’t do KVC into these objects.

- Pros
 - No changes needed.
 - Selectors remain what developers are likely to expect.
- Cons
 - Anyone that raises the warnings will hit it, and likely report the issue.
 - If a developer ends up doing KVC into the object (even by accident/error case), it can result in problems.

**Option 2 - “ProtoValue”**
Rename by swapping “Value” for “ProtoValue” in the selectors.  Change the selectors to the dictionary classes to be `-setProtoValue:forKey:` and `-protoValueForKey:`, to avoid the collisions.

- Pros:
 - Avoids the selector problems
- Cons:
 - Developers may still try to use the KVC selectors (they will show up in autocomplete).  Which could lead them to expect to work with boxed values, and things won’t work.
 - Rolling out the change can suck.  The KVC selectors hopefully will generate warnings/errors about the wrong types to flag things.
- Question:
 - GPBArrays use -valueAtIndex:, should those get renamed to match? 

**Option 3 - “[Type]” instead of “Value”**
Rename the selectors to include the basic type.  Change the selectors to the dictionary classes to be `-setInt32:forKey:`, `-setInt64:forKey:`, etc. and `-int32ForKey:`, `-int64ForKey:`, etc. to avoid the collisions.

- Pros:
 - Avoids the selector names.
- Cons:
 - Even though ObjC includes types in the naming, these could feel a little overkill.
 - Developers are forced to know and repeat the explicit type always every call into the dictionary.
 - Rolling out the change can suck.  The KVC selectors hopefully will generate warnings/errors about the wrong types to flag things.
- Question:
 - GPBArrays use -valueAtIndex:, should those get renamed to match?

**Comment by thomasvl** [comment]
I'm currently leaning toward Option 3, but welcome any other input on the topic.

**Comment by thomasvl** [comment]
Ok, starting in on this, this is one wrinkle.  The KVC methods need to change, but do we change all uses of `value` to match?  For example, they classes provide `-enumerateKeysAndValuesUsingBlock:`, should that stay as is, or should it also become `-enumerateKeysAndInt32sUsingBlock:`?  How about `-removeValueForKey:`?

**Comment by jcanizales** [comment]
Weird ; I thought commit 1383d53e67dac1d005fb3f8659e695b0be7e2718 had taken care of that.

**Comment by thomasvl** [comment]
That just dealt with some of the problem for the dictionaries that were object types values.  Not for all of them.

**Comment by thomasvl** [comment]
https://github.com/thomasvl/protobuf/tree/objc_dict_kvc_collisions has a current stab at the consistent naming.  You can see the diffs by looking at the one [commit](https://github.com/thomasvl/protobuf/commit/0057d542a3c56978e04729d0a62311db6bd780f9).

**Comment by jcanizales** [comment]
I think you've found a good solution there.

**Comment by thomasvl** [comment]
@sergiocampama had a good suggestion to tweak the signature for the value lookups; so I think we'll go with that; commit on my branch with just those changes is: https://github.com/thomasvl/protobuf/commit/76782eeb367b5a223b331e8f4a3796db32f862a2

I'll work turning this into a full CL to get a PR out.
