### ISSUE TITLE
Add the ObjC podspec integration test to the travis config

### ISSUE THREAD

**Issue by thomasvl** [google/protobuf#1619]
We could add this to the end of the current tests, but they already are sorta long, so it probably makes sense to just make this a new test (objectivec_cocoapods_integration).

The one things I'm a little fuzzy still is how the tag in the `Protobuf.podspec` is used when the `Podfile` uses a file reference to override where the repository is.  So far it seems like it gets ignored, but it would be nice to confirm that before making it an automated test.

**Comment by jcanizales** [comment]
> The one things I'm a little fuzzy still is how the tag in the `Protobuf.podspec` is used when the `Podfile` uses a file reference to override where the repository is. So far it seems like it gets ignored, but it would be nice to confirm that before making it an automated test.

It is ignored (if you use `:path` in the `Podfile`). That's how we test in gRPC.

You _can_ use `:podspec` instead of `:path`, and that'll use a local podspec but bring the sources from the repo+tag specified in that podspec.
