### ISSUE TITLE
Error in mergeFrom when the message has repeated data. Java

### ISSUE THREAD

**Issue by ccandy413** [google/protobuf#1634]
Hi everyone.
I spend a whole day to fix a protobuf bug but has no idea.
I wish someone could help me to resolve this probleam and thanks a lot.
The bug is: c++ server send a message to java server with RPC, the message has a repeated data as below:

> message A{
>   required string id = 1;
>   repeated B info = 2;
> }
> 
> message B{
>   required C type = 1;
>   required float data = 2;
>   required D status = 3;
> }
> 
> enum C{
>   TYPE_A = -1;
>   TYPE_B = 101;
> }
> 
> enum D{
>   UNDEFINED = -1;
>   NORMAL = 1;
> }

The java code is:
`service.getRequestPrototype(method).newBuilderForType().mergeFrom(message.getProtoBufData()).build();`

the error message is:

> com.google.protobuf.GeneratedMessage.getMethodOrDie(GeneratedMessage.java:1749)
> com.google.protobuf.GeneratedMessage.access$1100(GeneratedMessage.java:63)
> com.google.protobuf.GeneratedMessage$FieldAccessorTable$SingularFieldAccessor.<init>(GeneratedMessage.java:2036)
> com.google.protobuf.GeneratedMessage$FieldAccessorTable.ensureFieldAccessorsInitialized(GeneratedMessage.java:1890)
> com.google.protobuf.GeneratedMessage.getDescriptorForType(GeneratedMessage.java:109)
> com.google.protobuf.MessageReflection.findMissingFields(MessageReflection.java:187)
> com.google.protobuf.MessageReflection.findMissingFields(MessageReflection.java:224)
> com.google.protobuf.AbstractMessage$Builder.newUninitializedMessageException(AbstractMessage.java:440)
> com.google.protobuf.AbstractMessage.newUninitializedMessageException(AbstractMessage.java:280)
> com.google.protobuf.AbstractParser.newUninitializedMessageException(AbstractParser.java:57)
> com.google.protobuf.AbstractParser.checkMessageInitialized(AbstractParser.java:71)
> com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:124)
> com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:129)
> com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:49)
> com.launch.rpc.codec.RpcIoHandler.messageReceived(RpcIoHandler.java:167)
> org.apache.mina.core.filterchain.DefaultIoFilterChain$TailFilter.messageReceived(DefaultIoFilterChain.java:690)
> org.apache.mina.core.filterchain.DefaultIoFilterChain.callNextMessageReceived(DefaultIoFilterChain.java:417)
> org.apache.mina.core.filterchain.DefaultIoFilterChain.access$1200(DefaultIoFilterChain.java:47)
> org.apache.mina.core.filterchain.DefaultIoFilterChain$EntryImpl$1.messageReceived(DefaultIoFilterChain.java:765)
> org.apache.mina.core.filterchain.IoFilterEvent.fire(IoFilterEvent.java:74)
> org.apache.mina.core.session.IoEvent.run(IoEvent.java:63)
> java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> java.util.concurrent.FutureTask.run(FutureTask.java:266)
> java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
> java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
> java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
> java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
> java.lang.Thread.run(Thread.java:745)

**Comment by xfxyjwf** [comment]
What's the error thrown by Java runtime? It seems like a version-mismatch issue. Can you make sure the protobuf Java runtime and the protocol compiler you are using are of the same version number?
