### ISSUE TITLE
C++ compilation error for union

### ISSUE THREAD

**Issue by mauiarches** [google/protobuf#1637]
Hi,

I got a following proto file with below message:

message RequestUnion {
oneof request {
RangeRequest request_range = 1;
PutRequest request_put = 2;
DeleteRangeRequest request_delete_range = 3;
}

You can check rpc.proto from etcd github:
https://github.com/coreos/etcd/blob/master/etcdserver/etcdserverpb/rpc.proto

Generated header file contains the following:
class RequestUnion
{
    RequestUnion();
...
    union RequestUnion {
      RequestUnion() {}
      ::etcdserverpb::RangeRequest* request_range_;
      ::etcdserverpb::PutRequest* request_put_;
      ::etcdserverpb::DeleteRangeRequest* request_delete_range_;
    } request_;
...
}

When i tried compiling the following error was seen:
rpc.pb.h:1110:9: error: ‘etcdserverpb::RequestUnion::RequestUnion’ has the same name as the class in which it is declared

I'am using protoc 3.0

**Comment by xfxyjwf** [comment]
Protoc generated symbols conflict with the message name. Can you rename the oneof to something like "request_oneof"?

**Comment by mauiarches** [comment]
Hi,
Changed "oneof request" to "oneof request_oneof" and compilation is successful.

Thanks!

I also checked c++ generated code in protobuf site and it indeed has an example like this:
oneof oneof_name {
    int32 foo_int = 4;
    string foo_string = 9;
    ...
}

**Comment by xfxyjwf** [comment]
It's not required to have "oneof" in the name but having it generally improves clarity.
