### ISSUE TITLE
Conversion form json to proto breaks when the json has an undefied field in proto

### ISSUE THREAD

**Issue by mehrdadjahangirisc** [google/protobuf#1641]
Hi,
I'm not sure if this is an issue or an import feature request. But I definitely need this feature to proceed.
Let's say you've been parsing a json to your proto with no problems for days. anytime the json has a new field, the parsing (hence conversion to proto) fails.

Java code I use:
        MyProto.Builder r = MyProto.newBuilder();
        JsonFormat.parser().merge(jsonText, r);

I appreciate if someone can tell me a magic to skip those fields and not break the conversion.
Thanks a lot,
p.s. The ultimate feature could be adding those as repeated KeyValue in the proto as an extension. but let's not be dreamy here :)

**Comment by xfxyjwf** [comment]
This is a duplicate issue of https://github.com/google/protobuf/issues/1610

We will add an option to allow users to ignore unknown JSON fields when parsing.

**Comment by mehrdadjahangirisc** [comment]
is this added now?

**Comment by xfxyjwf** [comment]
I just merged https://github.com/google/protobuf/pull/2092 which adds an option to Java JsonFormat to ignore unknown fields.

**Comment by skebanga** [comment]
I have added a pull request ([#4145](https://github.com/google/protobuf/pull/4145)) at give C++ the same
