### ISSUE TITLE
Is there relation between the two  version number of  syntax *3* and protobuf *3*

### ISSUE THREAD

**Issue by codepython** [google/protobuf#1644]
can I use protobuf 3 to work with syntax 2 ?
will  the generated file be correct  ?

thanks

**Comment by xfxyjwf** [comment]
Yes, you can use protobuf-3.0.0-beta-3 with proto2 syntax. 3.0.0 supports both proto2 and proto3 syntax so you can upgrade from old 2.x versions without needing to update your .proto file.
