### ISSUE TITLE
Can't use protobuf-config.cmake

### ISSUE THREAD

**Issue by sipsorcery** [google/protobuf#1645]
I'm attempting to build a C++ source tree that depends on protobuf. I'm able to successfully build the protobuf from trunk (Windows x64 with VS 2012 toolchain). My issue is that when I try and use the protobuf cmake config files produced from the build I'm getting the error below:

`F:\gazebo-build\gazebo\build_cmake>cmake --debug-output -Wno-dev -G "NMake Makefiles"
Running with debug output on.
CMake Error at F:/gazebo-build/protobuf/build_debug/install/cmake/protobuf-config.cmake:21 (include):`

 ` include could not find load file:
    /protobuf-module.cmake
Call Stack (most recent call first):
  CMakeLists.txt:3 (find_package)
   Called from: [2]     F:/gazebo-build/protobuf/build_debug/install/cmake/protobuf-config.cmake
                [1]     F:/gazebo-build/gazebo/build_cmake/CMakeLists.txt
-- Configuring incomplete, errors occurred!
See also "F:/gazebo-build/gazebo/build_cmake/CMakeFiles/CMakeOutput.log".`

I'm using the simplest CMakeLists.txt file in order to test the dependency resolution of protobuf. 

`cmake_minimum_required(VERSION 2.8.6 FATAL_ERROR)
find_package(Protobuf REQUIRED PATHS "F:\\gazebo-build\\protobuf\\build_debug\\install")`

And the cmake command:

`cmake --debug-output -Wno-dev -G "NMake Makefiles"`

The command I used to generate the protobuf nmake makefiles:

`cmake -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=F:\gazebo-build\protobuf\build_debug\install -Dprotobuf_BUILD_TESTS=OFF ..\cmake`

**Comment by podsvirov** [comment]
It's will be fixed by #1642.
Now you can simple replace in ptotobuf-config script:

include("${_PROTOBUF_PACKAGE_PREFIX}/protobuf-module.cmake")

to

include("${CMAKE_CURRENT_LIST_DIR}/protobuf-module.cmake")

**Comment by sipsorcery** [comment]
Thanks.
