### ISSUE TITLE
Question about c++ generated code of Oneof fields

### ISSUE THREAD

**Issue by cirfe** [google/protobuf#1648]
I was following the user guide of protobuf,and did some test;
I wrote a _.proto_ file like this

```
syntax = "proto3"
package tutorial
message SubMessage{
        int count = 1;
}
message SampleMessage{
        oneof test_oneof{
                string name = 4;
                SubMessage sub_message = 9;
        }
}

```

after i generate c++ code,i found something.
the function of _has_name_ is private,while _has_sub_message_ is public.
I think this is different from the user guide.Is this a bug,or just a mistake that i made?

**Comment by xfxyjwf** [comment]
The has_name method is removed in proto3. We need to update the user guide to distinguish between proto2 and proto3.

**Comment by cirfe** [comment]
if functions like has_name are removed,then how should i know which field is set?

**Comment by xfxyjwf** [comment]
For oneof, you can use the generated getOneofCase() method to check which oneof is set.

**Comment by cirfe** [comment]
Got it,thanks
