### ISSUE TITLE
Framework for iOS

### ISSUE THREAD

**Issue by woigl** [google/protobuf#1649]
I am trying to create an iOS Framework that includes the Protocol Buffers sources.

After hours of trying, I am turning to you guys to hopefully give me some help.

Is there a tutorial to achieve this? Has someone done something like that already?

I would really like to prevent things like CocoaPods.

**Comment by jcanizales** [comment]
Hi @woigl, you _can_ create one with Cocoapods, then copy the built framework and forget about Cocoapods.

**Comment by woigl** [comment]
Hi @jcanizales, I finally got it done as a Objective-C Framework. Thanks for your suggestion.
