### ISSUE TITLE
Document building examples with CMake

### ISSUE THREAD

**Issue by podsvirov** [google/protobuf#1657]
Examples can now be building in two ways with CMake tool (thanks me and @yeswalrus), but do not know our users about this. (Also now there is a limit that we build only cpp version).
Previously, I've updated the documentation cmake/README.md, but I feel limited in English proficiency and time.
I have a suggestion for writing the documentation:
- Add the "Building Examples" section in the cmake/README.md file after the section of a "ZLib support" (mainly construction process);
- Transform examples/README.txt to examples/README.md (it is will be done in #1538)
  and add the optional section "CMake Configuration" before starting 'make ...' on the Windows (autonomous assembly, after installation, both for Unix now).

@yeswalrus you have the time and desire to do this work?

**Comment by yeswalrus** [comment]
I have the desire, we'll see about the time.

**Comment by gerben-s** [comment]
This seems to be a dead bug thread. Closing this for now
