### ISSUE TITLE
install protobuf-3.0.0-beta-3-pre-1.tar.gz failed

### ISSUE THREAD

**Issue by superluo** [google/protobuf#1659]
hi,help:
after perform './configure' successfully,
throw error when perform 'make' command, the error is below:

` -DNDEBUG -MT google/protobuf/map_field.lo -MD -MP -MF $depbase.Tpo -c -o google/protobuf/map_field.lo google/protobuf/map_field.cc &&\
	mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I.. -pthread -DHAVE_PTHREAD=1 -DHAVE_ZLIB=1 -Wall -Wwrite-strings -Woverloaded-virtual -Wno-sign-compare -O2 -g -DNDEBUG -MT google/protobuf/map_field.lo -MD -MP -MF google/protobuf/.deps/map_field.Tpo -c google/protobuf/map_field.cc  -fPIC -DPIC -o google/protobuf/.libs/map_field.o
In file included from ./google/protobuf/map_field_lite.h:34,
                 from ./google/protobuf/map_field.h:40,
                 from google/protobuf/map_field.cc:31:
./google/protobuf/map.h: In constructor ‘google::protobuf::Map<Key, T>::MapAllocator<U>::MapAllocator(const google::protobuf::Map<Key, T>::MapAllocator<X>&) [with X = google::protobuf::Map<google::protobuf::MapKey, google::protobuf::MapValueRef>::KeyValuePair, U = google::protobuf::Map<google::protobuf::MapKey, google::protobuf::MapValueRef>::InnerMap::Node, Key = google::protobuf::MapKey, T = google::protobuf::MapValueRef]’:
./google/protobuf/map.h:1291:   instantiated from ‘U* google::protobuf::Map<Key, T>::InnerMap::Alloc(size_t) [with U = google::protobuf::Map<google::protobuf::MapKey, google::protobuf::MapValueRef>::InnerMap::Node, Key = google::protobuf::MapKey, T = google::protobuf::MapValueRef]’
./google/protobuf/map.h:960:   instantiated from ‘std::pair<google::protobuf::Map<Key, T>::InnerMap::iterator_base<google::protobuf::Map<Key, T>::KeyValuePair>, bool> google::protobuf::Map<Key, T>::InnerMap::insert(const google::protobuf::Map<Key, T>::KeyValuePair&) [with Key = google::protobuf::MapKey, T = google::protobuf::MapValueRef]’
./google/protobuf/map.h:989:   instantiated from ‘google::protobuf::MapPair<Key, T>*& google::protobuf::Map<Key, T>::InnerMap::operator[](const Key&) [with Key = google::protobuf::MapKey, T = google::protobuf::MapValueRef]’
./google/protobuf/map.h:1505:   instantiated from ‘T& google::protobuf::Map<Key, T>::operator[](const Key&) [with Key = google::protobuf::MapKey, T = google::protobuf::MapValueRef]’
google/protobuf/map_field.cc:189:   instantiated from here
./google/protobuf/map.h:657: error: ‘google::protobuf::Arena* const google::protobuf::Map<google::protobuf::MapKey, google::protobuf::MapValueRef>::MapAllocator<google::protobuf::Map<google::protobuf::MapKey, google::protobuf::MapValueRef>::KeyValuePair>::arena_’ is private
./google/protobuf/map.h:592: error: within this context
make[2]: *** [google/protobuf/map_field.lo] Error 1
make[2]: Leaving directory `/home/luochao/proto/protobuf/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/luochao/proto/protobuf'
make: *** [all] Error 2
`

**Comment by xfxyjwf** [comment]
Fixed in https://github.com/google/protobuf/pull/1692

You should also be able to workaround it by upgrading the gcc version.
