### ISSUE TITLE
Unix tools for proto messages

### ISSUE THREAD

**Issue by krisskross** [google/protobuf#1661]
Hi

I'm playing around with logging proto messages in log files where each row is a base64 encoded message. Using this approach I can easily utilize tools like tail and cat on these files using the following script.

```bash
#!/bin/bash

if [ -z "$1" ]; then
  echo "usage: <command>"
  echo "ex: proto_cmd tail -f proto.log"
  echo "ex: proto_cmd cat proto.log"
  return 0
fi

$@ | while read line
do
    echo "$line" | base64 --decode | protoc --decode=org.ProtoLog --proto_path=. log.proto
done
```

I would like to understand how to do the same thing without the base64 encoding/decoding step? Any good advice?

Cheers,
-Kristoffer

**Comment by jcanizales** [comment]
I reckon `protoc` can be used to encode and decode messages in a text format instead of binary, if that's what you mean?

**Comment by krisskross** [comment]
Not quite. Each log is encoded as a String with a separating new line. I suppose that's how `tail` and `cat` knows how to redirect each log, line by line, to `base64` and `protoc`. 

But if there was no new line character in the file i'm not sure how to figure out (using unix tools) when a new message should be decoded.

In the script, this is done thanks to `$@ | while read line`.

**Comment by krisskross** [comment]
I could prepend the size of each binary proto message but that would make `tail -f` useless since I wouldn't know where to look for the size field.

New line '\n' delimiter doesn't work since proto string fields might contain new lines. I think the same is true for a NUL '\0' delimiter?

**Comment by jcanizales** [comment]
CC @pherl for ideas :)

**Comment by pherl** [comment]
Right, both '\n' and '\0' are valid protobuf payload. I don't see anyway to
use the protobuf wire directly with tail -f without any escaping.

**Comment by krisskross** [comment]
Ok, thanks!

**Comment by hcoona** [comment]
Why this thread was closed? We didn't come out anything yet?

**Comment by hcoona** [comment]
I think it's a good idea to prepend the frame size & provide a set of useful tools such as pbcat, pbtail, pbhead, etc.
