### ISSUE TITLE
csharp release is missing some files 

### ISSUE THREAD

**Issue by aeroson** [google/protobuf#1663]
Issue: Download [csharp release](https://github.com/google/protobuf/releases/download/v3.0.0-beta-3/protobuf-csharp-3.0.0-beta-3.zip), unpack, [ICustomDiagnosticMessage.cs](https://github.com/google/protobuf/blob/master/csharp/src/Google.Protobuf/ICustomDiagnosticMessage.cs) is missing despite being added to the project.

Result: unable to build

![image](https://cloud.githubusercontent.com/assets/3437520/15910265/5f061c58-2dca-11e6-87bb-569dbc30d2a5.png)

Fix: download git repo instead of release

**Comment by xfxyjwf** [comment]
Fixed now and I also added a test case for that kind of missing files.
