### ISSUE TITLE
javanano accessors for nested messages to reduce garbage

### ISSUE THREAD

**Issue by ennerf** [google/protobuf#167]
We've been using protobufs for a long time and have had a very good experience with it. However, we are now working on a soft real-time system, which requires some more deterministic (= less garbage) Java bindings.

I was hoping that javanano could be the solution. Unfortunately, in the current implementation (optional_field_style=accessors) doesn't create accessors for nested messages, and always sets them to null on clear(). 

Potential solution:
- generate accessors for nested messages
- change clear(): set hasNestedMessage=false and nestedMessage.clear() instead of nestedMessage=null

Since this is only seems like a minor change to what you already have, I was wondering if you could add another optional_field_style option for this.

**Comment by estekhin** [comment]
What if `nestedMessage` (this particular instance) is used somewhere else? Clearing a message just because it happened to be referenced by some other message will break a lot of code.

**Comment by ennerf** [comment]
The message is mutable anyways. How is that case different from editing a shared instance in any other way?

**Comment by xfxyjwf** [comment]
The current nano implementation supports quite a lot of flags and we wish to get rid of most of them in proto3. For your use case, instead of adding a new flag, maybe we can just make clearing the nested message the default behavior?

**Comment by ennerf** [comment]
Well, I'd obviously like that idea. I think it would give people a nice mutable alternative to the standard implementation, with little changes to the Syntax.

**Comment by ennerf** [comment]
If you end up deciding to add another flag, it would be nice to add a "type=gc_less" that supports allocation free environments, i.e.,

Repeated fields
- type[] getRepeatedFieldArray()
- int getRepeatedFieldLength()

Strings
- char[] getStringFieldArray()
- int getStringFieldLength()
- String getStringField()
- setStringField(CharSequence str)

CodedOutputByteBufferNano
- add a way to reuse instance, e.g., .rewind(int position)
