### ISSUE TITLE
autogen.sh downloads gmock even when it's installed on the system

### ISSUE THREAD

**Issue by penguin42** [google/protobuf#1676]
Hi,
  Host: fedora 24
  If I install the system packaged gmock 1.7.0-2 and gmock-devel packages, the protobuf build script still downlocks the gmock zip.

**Comment by mridulnagpal** [comment]
hey i would like to work on this issue

**Comment by anandolee** [comment]
@mridulnagpal are you still work on this issue? Can you send a PR for it?

**Comment by TeBoring** [comment]
This seems a little trivial to me. The gmock downloaded is only used when building protobuf. It should not be user visible.
Close this for now. Feel free to open it.
