### ISSUE TITLE
If I generate CommonJS code from a proto file that depends on a well known proto file, the generated code has incorrect imports

### ISSUE THREAD

**Issue by murgatroid99** [google/protobuf#1684]
I generated code from this proto file:

```proto
syntax = "proto3";

import "google/protobuf/wrappers.proto";

message Request {
  google.protobuf.BoolValue value = 1;
}

service Test {
  rpc Run(Request) returns (google.protobuf.Int32Value);
}
```

and got this output at the beginning of the file:

```js
var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var google_protobuf_wrappers_pb = require('./google/protobuf/wrappers_pb.js');
```

However, the file `./google/protobuf/wrappers_pb.js` does not exist.

**Comment by murgatroid99** [comment]
Note: two changes are probably required to make this work:

 1. The `google-protobuf` node module should include generated code for well known types.

 2. The code generator should generate code that refers to those files.

**Comment by murgatroid99** [comment]
CC @xfxyjwf @pherl

**Comment by murgatroid99** [comment]
Also CC @haberman

**Comment by xfxyjwf** [comment]
@haberman this bug is the blocking issue for a grpc JS release (planned this week). Could you take a look?

**Comment by haberman** [comment]
Looking at this now.

**Comment by haberman** [comment]
After talking this over with @murgatroid99, I think we may need a new file-level option for this. Unlike other languages, Node.js does not seem to have a way to generate `require(x)` statements that will work the same regardless of whether `x` is in the same package or a different package.

1. for files in the same package, we need to require them as `require('./google/protobuf/any_pb.js')`.
2. for files in a different package, we need to require them as `require('google-protobuf/google/protobuf/any_pb.js')`.

To support this, we propose adding a new file-level option: `npm_package`.

When we generate `require()` statements, we will see if the `npm_package` option between the includer and the includee match. If so, we will generate a require like (1). If not, we will generate a require like (2).

Does this sound good to you @pherl?

**Comment by pherl** [comment]
We should probably special well known types imports (we did this in C++ as well); and then revisit the issue if cross package imports is a common use case.

**Comment by haberman** [comment]
PR is out: https://github.com/google/protobuf/pull/1696

**Comment by haberman** [comment]
PR is merged, closing this issue.

**Comment by itavy** [comment]
i have 3 files, each one on a different directory:
./Base.proto
./User/User.proto 
./User/Web/Web.proto 

last one include the other 2;

in generated code for Web.proto (`protoc User/Web/Web.proto --js_out=import_style=commonjs,binary:protos -I=. -I=User -I=User/Web`) and the second require statement is wrong:

```javascript
$ head -13 protos/User/Web/Web_pb.js 
/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var Base_pb = require('../../Base_pb.js');
var User_pb = require('../../User_pb.js');
```

it should be:
```javascript
var User_pb = require('../User_pb.js');
```

below are the 3 proto files:

```javascript
$ cat Base.proto 
syntax = "proto3";

package itavy.Base;

enum AppVersion {
  V_0_0_1 = 0;
  V_0_0_2 = 1;
};
```

```javascript
$ cat User/User.proto 
syntax = "proto3";

package itavy.User;

enum Type {
  REGULAR = 0;
  ADMIN = 1;
};
```

```javascript
$ cat User/Web/Web.proto 
syntax = "proto3";

package itavy.User.Web;

import "Base.proto";
import "User.proto";

message User {
  itavy.Base.AppVersion version = 1;
  string name = 2;
  string email = 3;
  itavy.User.Type type = 4;
};
```
