### ISSUE TITLE
protoc 3.0.0 linux x86_64 issue Typo

### ISSUE THREAD

**Issue by ChaiBapchya** [google/protobuf#1685]
Readme.txt 
It says
 This binary is intended for ** Windows ** users who want to
use Protocol Buffers in Java or Python but do not want to compile protoc
themselves.

**Comment by xfxyjwf** [comment]
@TeBoring @pherl

**Comment by pherl** [comment]
We probably should checkin the readme.txt and make it platform independent.

**Comment by xfxyjwf** [comment]
Fixed in beta-4. I'll check-in a script to build these .zip files later.
