### ISSUE TITLE
[C#] Project file uses relative path to packages; cannot be added to other solutions

### ISSUE THREAD

**Issue by warrenfalk** [google/protobuf#1686]
The csproj file references the nuget packages directory using a relative path `..\packages` instead of a more precise `$(SolutionDir)\packages`.  This causes the project to be non-buildable if you add it to any solution outside the git tree.

The error you get is:

```
error : This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is ..\packages\NuSpec.ReferenceGenerator.1.4.1\build\portable-net45+win+wpa81+wp80+MonoAndroid10+xamarinios10+MonoTouch10\NuSpec.ReferenceGenerator.targets.
```

**Comment by warrenfalk** [comment]
Note: that this actually occurs due to a bug in NuGet (see https://github.com/NuGet/Home/issues/2368).  The final solution is to switch to package.json instead of package.config, but that feature isn't ready yet.  The temporary solution is to manually correct the paths from `..\packages` to `$(SolutionDir)\packages`.

**Comment by jskeet** [comment]
As it happens, PR #1721 already switches to use `project.json` instead of `packages.config`, but I'm trying to work out how we're going to build and test on Mono at the moment.

I'd rather not manually tinker with the project file at the moment.

**Comment by anandolee** [comment]
#1727 switches project.json already
