### ISSUE TITLE
About type of time

### ISSUE THREAD

**Issue by alanyangbo** [google/protobuf#169]
Addition of a small set of standard types for representation of time.Who can  do an example?

**Comment by xfxyjwf** [comment]
We'll include two standard protos in protobuf runtime:
// file: google/protobuf/timestamp.proto
syntax = "proto3";
package google.protobuf;
message Timestamp {
  int64 seconds = 1;
  int32 nanos = 2;
}

// file: google/protobuf/duration.proto
syntax = "proto3";
package google.protobuf;
message Duration {
  int64 seconds = 1;
  int32 nanos = 2;
}

So in your .proto file, you can use these types to define fields:
message MyMessage {
  optional Timestamp snapshot_time = 1;
}

Different programming languages will use their own native representation for these types in the generated code. For languages that haven't support these types yet, they can just generate these as normal message fields.
