### ISSUE TITLE
Serialize and Parse directly to and from JSON using google::protobuf::Message

### ISSUE THREAD

**Issue by cabeaulac** [google/protobuf#1690]
From this post: https://groups.google.com/d/msg/protobuf/SbuIW1FeFqg/VoQW_DvqAQAJ

Add util methods to Serialize from Message to Json and Parse from Json to Message.

_Example serializing to JSON string from Message_
**std::string json_string = google::protobuf::util::MessageToJsonString(startMovie); // startMovie is a google::protobuf::Message**

_Example parsing from JSON string to Message_
**Movie startMovie = google::protobuf::util::JsonToMessage("type.googleapis.com/movie.pbuf.Movie", json_string);**

**Comment by xfxyjwf** [comment]
Since the conversion may fail (and we don't use exceptions...), I think the API will need to be like this:
```cpp
bool MessageToJsonString(const Message& input, string* output);
bool JsonStringToMessage(const string& input, Message* output);
```

**Comment by cabeaulac** [comment]
That looks fine. Can you provide a link to the guidelines so I don't do a bunch of things that aren't allowed. ie. Can erI use c++11 or 14? unique_ptr, move semantics, etc. I'm searching for them but can't find them for some reason. 

So, could we do this? And would you want to?
```c++
// unique_ptr bool operator returns false when it doesn't point to anything
std::unique_ptr<string> MessageToJsonString(const Message& input);
std::unique_ptr<Message> JsonStringToMessage(const string& input);
// iostream param. Presume we'll want to take iostream input right?
std::unique_ptr<Message> JsonStringToMessage(iostream& input);
```
Then your code could look like:
```c++
unique_ptr<Message> new_msg = JsonStringToMessage(input);
if (new_msg)
{
    processNewMsg(std::move(new_msg));
}
```

**Comment by xfxyjwf** [comment]
We follow Google C++ style guide:
https://google.github.io/styleguide/cppguide.html

and with the additional restriction that the code needs to build without C++11 (that means no unique_ptr, move semantics, lambda, etc.).

**Comment by xfxyjwf** [comment]
@cabeaulac Have you started working on an implementation? If not I will probably add these convenient methods myself.

**Comment by cabeaulac** [comment]
I have not. Sorry about that. I look forward to seeing how you implement them.
Some Context: I'm making use of MongoDB and mongocxx for C++11. My use cases include storing and retrieving docs with MongoDB. Protobuf messages are serialized to JSON and and stored in mongo. Also convert BSON mongo docs to JSON and parse to protobuf message. Making those conversions quick and easy is my goal.

**Comment by xfxyjwf** [comment]
This is implemented now:
https://github.com/google/protobuf/blob/master/src/google/protobuf/util/json_util.h#L80
