### ISSUE TITLE
Wrong oneof index in Fielddescriptor if a oneof and a field is in a message

### ISSUE THREAD

**Issue by mreu** [google/protobuf#170]
When I run this protobuf
message CommandMessage
{
    oneof Action
  {
    string set = 1;
    int32 inc = 2;
    int64 return = 3;
    bytes quit = 4;
  }

  optional string text = 20;
}
with protoc --descriptor_set_out, all fields have a 0 in oneof_index in the FieldDescriptorInfo.

**Comment by xfxyjwf** [comment]
I think it's actually right. The oneof_index is the index of the oneof that this field belongs to. In your message there is only one oneof with index 0, so all fields in the oneof should have oneof_index 0. The field that's outside of the oneof should not have a oneof_index (i.e., field not set) but if you try to get its oneof_index value it would also be 0 as that's the default.

**Comment by mreu** [comment]
So, how can I see which fields belongs to the oneof which not?

**Comment by xiaofeng-gg** [comment]
Check has_oneof_index(). If and only if it's true, this field belongs to a
oneof.

**Comment by mreu** [comment]
Did not find a has_oneof_index() method in the descriptor.proto. I am writing a c# generator inside Visual Studio (see https://visualstudiogallery.msdn.microsoft.com/4bc0f38c-b058-4e05-ae38-155e053c19c5) and let protoc generate the descriptor.proto which I am interpreting to generate the c# code. So where should I call the has_oneof_index() method? That's why I think that there is a bug in the descriptor.proto. If a field is not inside a oneof, the index is set to 0 (I know, it is the default of an int32) and I cannot see if it is in an oneof or not. The oneof_index must be -1 or there nust be a boolean field like is_in_oneof or the oneof_index should start with 1 and not with 0.

**Comment by xfxyjwf** [comment]
Are you using C# to write the generator? In C++, with a FieldDescirptorProto, you should be able to call the has_oneof_index method directly:
FieldDescriptorProto field = ...;
if (field.has_oneof_index()) {...}

**Comment by mreu** [comment]
Yes, I use C# to generate the C# code. As I said I only have the descriptor.proto.

**Comment by mreu** [comment]
I wrote a small program to read the descriptor.proto and the protobuf-net assembly I use to deserialize the descriptor.proto is the one who causes my problems. Because of the defaults in the fields I see a zero as index in the oneof_index. In my small programm I see that there is no index set on the fields. So I will write my own implementation to interpret the descriptor.proto and I got all informations I need. Thanks for your support. I close this issue.

**Comment by eriktim** [comment]
I know this topic is old, but as I am building a plugin for Elm and can/should not know whether a field is set or not (i.e. takes the default value), I wonder how this relates to the following statements:

* The [`proto3` spec](https://developers.google.com/protocol-buffers/docs/proto3#default) describes
> Note that for scalar message fields, once a message is parsed there's no way of telling whether a field was explicitly set to the default value (...)

* The [`proto3` `descriptor.proto`-like `type.proto` file](https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/type.proto) (for which the use is unclear to me) contains
```proto
  // The index of the field type in `Type.oneofs`, for message or enumeration
  // types. The first type has index 1; zero means the type is not in the list.
  int32 oneof_index = 7;
```

Am I missing something here? Is this something that has changed for `proto3`?

**Comment by jimblackler** [comment]
I've encountered a similar issue.
