### ISSUE TITLE
javascript code generator emiting lists instead of maps

### ISSUE THREAD

**Issue by jhspaybar** [google/protobuf#1706]
I'm using grpc-tools 0.14.1 off of npm which has protoc 3 bundled.  It looks like it's emitting a list instead of a map for fields defined as maps with syntax="proto3" at the top of the file.  I also noticed the tests in js for proto3 don't actually have a map in the test either. ( https://github.com/google/protobuf/blob/3.0.0-beta-3/js/proto3_test.proto )

From my spelunking through the compiler, it appears the offending code is here https://github.com/google/protobuf/blob/3.0.0-beta-3/src/google/protobuf/compiler/js/js_generator.cc#L1938 where it checks for is_repeated, but isn't checking is_map first to call toMap instead of toObjectList.  The JSGetterName also needs some minor tweaks to emit a "Map" suffix instead of "List".  If this is the right approach, I'm happy to submit a pull request to get this patched up.

**Comment by xfxyjwf** [comment]
I remember maps support is added in our internal code base. It probably hasn't propagated to the opensource repo yet.

**Comment by jhspaybar** [comment]
Any idea when that will make it public?  Our team has been pretty actively contributing to grpc-java and working with the gRPC teams, and are expanding to NodeJS and other areas where the protobuf generation is a bit less mature than Java.  We'd like to be able to contribute here as well when needed, and know our efforts to track down the problems(like here) isn't a waste because it's already been patched somewhere we can't see.  I'm looking forward to hear how we can more effectively contribute.  Thanks!

**Comment by haberman** [comment]
Hi there and thanks for the report. This was indeed committed internally recently. I believe we are working right now on getting these changes to open-source. @acozzette can say more.

**Comment by acozzette** [comment]
Yes, I am working on merging and publishing our internal changes and will try to get that done as soon as possible, hopefully by tomorrow.

**Comment by acozzette** [comment]
Sorry for the delay but our internal changes have now been merged to the master branch and this includes the new maps support for JSPB.

**Comment by jhspaybar** [comment]
Thanks!  When should we expect a release to npm?

**Comment by acozzette** [comment]
We usually do a protobuf release once a quarter; the last one was around mid-May so a rough guess for the next one would be some time around mid-August. Does that sound reasonable or do you need this feature sooner?

**Comment by jhspaybar** [comment]
I also just looked at the changes on master to the files I had linked above.  They don't appear to have a test for map, nor do they use the toMap method anywhere in the compiler plugin.  The runtime library has support for maps, but it appears they aren't generating them still.  Am I looking in the wrong place?  I'm also happy to contribute a fix still if it turns out that the fix isn't made yet after all.

**Comment by acozzette** [comment]
I'll check with the rest of the team and see if there's a way we can do a release sooner or at least push the JS changes to npm without a full release for all languages.

About the map changes, I think you're right that something's missing--it looks to me like a file or two didn't make it to master. I'm working on fixing this right now.

**Comment by jhspaybar** [comment]
@acozzette I saw this in the most recent release notes, thanks for getting it out!

**Comment by jhspaybar** [comment]
@acozzette actually, I just went to use this, and on NPM the latest version is alpha6.2 and doesn't have support for maps, and it looks like the tagged 3.0.0-beta-4 branch also doesn't have map support.  Did this somehow get missed in the merge again?

**Comment by jhspaybar** [comment]
actually, looks like the fixe are there, they're just in the alpha-7 artifact which hasn't been pushed to NPM yet.  Do you know when that is planned to be published?

**Comment by xfxyjwf** [comment]
We are working on the next release and it will be out really soon. We will probably skip the npm package for alpha-7 and @haberman will push the npm package for the next release instead.

**Comment by vanthome** [comment]
Is there any update on this? We desperately need proper protobuf maps in NodeJS (in our case even node 7).

**Comment by acozzette** [comment]
@vanthome I believe this should be present in the 3.1.1 version on NPM, have you tried that version?

**Comment by vanthome** [comment]
@acozzette I don't think so, please look here: https://github.com/google/protobuf/issues/2369
