### ISSUE TITLE
Add ability to inspect javascript proto schema dynamically

### ISSUE THREAD

**Issue by omanamos** [google/protobuf#1711]
I might be missing something, but I can't figure out how to get all fields with types on a given message type using something like reflection in the C++ api - https://developers.google.com/protocol-buffers/docs/reference/cpp/google.protobuf.message#Reflection

**Comment by haberman** [comment]
I think this is unlikely to be added to JavaScript anytime soon. JavaScript is heavily optimized for code size, and reflection is not often needed for JavaScript, at least in our experience. If we did this, it would need to be implemented in a way that did not increase code size for people who aren't using it.
