### ISSUE TITLE
Default message value for proto3 Java is null?

### ISSUE THREAD

**Issue by biran0079** [google/protobuf#1718]
From [this doc](https://developers.google.com/protocol-buffers/docs/proto3#default) and  https://github.com/google/protobuf/issues/359, default value for message field is `null`, while from the generated code, it seems the DEFAULT_INSTANCE of the message is returned, which is not `null`.

It seems to me that proto3 for java is not implemented correctly?

**Comment by xfxyjwf** [comment]
The doc is wrong. The default value for message fields is implementation dependent and in most implementations it's the default instance.

**Comment by xfxyjwf** [comment]
The documentation has been updated.
