### ISSUE TITLE
Enum case changed in beta 3

### ISSUE THREAD

**Issue by dalebrubaker** [google/protobuf#1722]
I don't know if this is a protobuf issue or a grpc issue (i.e. I don't know who "owns" c# generation from a .proto file). But...

A proto like this
enum BarBreakType {
		BarBreakEOD = 0;
	}
would preserve the case as BarBreakEOD in beta 2.
In beta3 I get BarBreakEod.
public enum BarBreakType {
    [pbr::OriginalName("BarBreakEOD")] BarBreakEod = 0,
  }
Is this a bug? 
Is this documented somewhere?
Is there an option for going back to the previous behavior?
Thank you.

**Comment by jskeet** [comment]
Yes, this is deliberate, and documented in the [release notes](https://github.com/google/protobuf/releases). Conventional proto enums are usually in all-caps with underscores between words, which is fine for Java and C++ (for example) but unpleasant in C#.

*At the moment* you can go back to the previous behaviour with the C# option of `legacy_enum_values`, but that option will be *removed* for the final release - so I'd personally recommend just living with the new casing (and ideally updating your enum to be more conventional for other languages).

**Comment by dalebrubaker** [comment]
Okay, thank you.
