### ISSUE TITLE
Missing 3.0.0-beta-3.2 podspec?

### ISSUE THREAD

**Issue by dnkoutso** [google/protobuf#1724]
It seems a 3.2 release was made but there is no podspec for it.

https://github.com/CocoaPods/Specs/tree/master/Specs/Protobuf

We could publish it internally for us to use for now but I wonder if this was missed or it was intentional.

**Comment by pherl** [comment]
It is a minor release just for javascript. The runtime and codegen is the same for objc.

**Comment by dnkoutso** [comment]
Thanks!
