### ISSUE TITLE
Make StringPiece interface match std::string_view

### ISSUE THREAD

**Issue by acozzette** [google/protobuf#1726]
C++17 will include std::string_view, which is essentially just a standardized replacement for StringPiece. To plan ahead for this, we should consider updating the StringPiece API so that it exactly matches std::string_view. Then a few years from now when C++17 is widespread we can make StringPiece just a type alias for std::string_view. I believe StringPiece is just used within protobuf internals at the moment and so we can safely change its API without breaking any user code.

**Comment by haberman** [comment]
Do we know what (if any) differences there currently are?

**Comment by acozzette** [comment]
I don't remember offhand, but I believe they are almost all just relatively minor cosmetic differences. I know one thing is that `std::string_view` uses a `size_t` for length whereas our `StringPiece` uses a signed type.

**Comment by haberman** [comment]
Yes changing to `size_t` definitely makes sense.

**Comment by amitdo** [comment]
https://abseil.io/docs/cpp/guides/strings#string_view

**Comment by anandolee** [comment]
@acozzette Any updates?

**Comment by acozzette** [comment]
Let me just close this for now because I'm not actively working on it. Once we figure out how we will integrate with Abseil we can revisit this anyway.
