### ISSUE TITLE
readme.txt for os x release incorrectly says its for Win32

### ISSUE THREAD

**Issue by jaybuff** [google/protobuf#1728]
I grabbed the OS X release from here:

https://github.com/google/protobuf/releases/download/v3.0.0-beta-3.1/protoc-3.0.0-beta-3.1-osx-x86_64.zip

Opened readme.txt in the root and it says:

     This package contains a precompiled Win32 binary version of the protocol buffer
compiler (protoc).

This is incorrect.  It's the binary for os x.

**Comment by xfxyjwf** [comment]
Should be fixed now. The readme file no longer mentions a specific platform.
