### ISSUE TITLE
GetString() first argument error  in message.h 's comment line 101 for Example usage 

### ISSUE THREAD

**Issue by skyline09** [google/protobuf#173]
The GetString(), GetInt32(), GetDouble() function prototype is:

```
virtual Get* (const Message& message,  const FieldDescriptor* field) const = 0;
```

But, in the message.h comment, the usage of Message Foo, line 101

```
Message* foo = new Foo;
assert(reflection->GetString(foo, text_field) == "Hello World!");
```

absolutely，the first argument of GetString() is wrong
Make it correct，even though it is comments

**Comment by acozzette** [comment]
Closing this issue because it appears to have been fixed in 5db217305f37a.
