### ISSUE TITLE
node.js serialization doesn't handle oneof field properly

### ISSUE THREAD

**Issue by pmullaney** [google/protobuf#1741]
I am using protobufjs via grpc and I am having several issues with message types containing oneof fields. I have attached an example that is derived from the greeter example code. I have added a oneof field to the request that contains an A and a B message within the oneof. When I create the A message only(without enclosing it in a oneof of the HelloRequest) and send it, it works. However, I then send a B message in the same manner and it encounters an exception during serialization. The interesting thing to point out is that if I change the order of the elements of the oneof in the proto file to B and then A, the B request will be successful.

[greeter_client.js.txt](https://github.com/google/protobuf/files/344310/greeter_client.js.txt)
[greeter_server.js.txt](https://github.com/google/protobuf/files/344311/greeter_server.js.txt)
[helloworld.proto.txt](https://github.com/google/protobuf/files/344312/helloworld.proto.txt)

If I change the example such that I use the HelloRequest, I get another exception indicating the alt field is undefined. I am using grpc@0.14.1 and protobufjs@4.1.3 on ubuntu 14.04.

**Comment by pmullaney** [comment]
The crash I am seeing is in MessagePrototype.set. Here's the snippet causing it:

var field = T._fieldsByName[keyOrObj];
if (!noAssert) {
if (!field)
throw Error(this+"#"+keyOrObj+" is not a field: undefined");

The problem is either the oneof field should be mapped in the T._fieldsByName or there should be appropriate logic to avoid and skip the checks inside the !noAssert conditional. I hacked a version to avoid the checks and it works. Unfortunately, I can't seem to find a decent way to check that the field is a oneof.

**Comment by pmullaney** [comment]
This has be resolved as a usage issue with dynamic codegen grpc. See https://github.com/grpc/grpc/issues/7200

**Comment by mavrick** [comment]
Is there a more elegant solution to this? I've hit something similar with oneof using streams in nodejs. @pmullaney

**Comment by AkashBabu** [comment]
Sample protofile
```protobuf
message TryOneOf {
      oneof check {
                 string foo = 1;
                 string bar = 2;
      }
}
```
How to implement it elegantly ?
*Let's assume that grpc-client is sending {"foo": "test"} as request body
```js
function TryOneof(call, callback) {
        console.log("check:", call.request) // {check: "foo", foo: "test", bar: null}
        
        // So easier way of implementing it would be
        call.request[call.request.check] // test
}
```
