### ISSUE TITLE
--cpp_out => strange output directory configuration [Protobuf v3.0.0-beta-3]

### ISSUE THREAD

**Issue by chazix** [google/protobuf#1743]
My command usage looks like this:
protoc.exe --cpp_out=../src/ProtocolBuffers/ ../ProtocolBuffers/Subfolder/Subfolder1/Subfolder2/testMessage.proto

My original problem was not being able to get my cpp output to go to the right directory. I wanted : ../src/ProtocolBuffers/Subfolder/Subfolder1/Subfolder2/{outputHere}

It turned out that the .proto compile location is also being used for determining the output location, so to manipulate the location I had to set --cpp_out to be the root directory where the full output directory technically looks like this : ../src/ProtocolBuffers/../ProtocolBuffers/Subfolder/Subfolder1/Subfolder2/{outputHere} . As you can see it appears to be the --cpp_out + {to .proto file path}

I just tried this with --csharp_out and it does output to the desired location when I set the full desired path.

**Comment by chazix** [comment]
It also turns out that in the generation for the *.pb.cc it also is following the convention for the location of where the original .proto is located for it's various includes to the *.pb.h location.

Instead of getting : #include "../src/ProtocolBuffers/Subfolder/Subfolder1/Subfolder2/*.pb.h"
It generates as : #include "../ProtocolBuffers/Subfolder/Subfolder1/Subfolder2/testMessage.pb.h"

**Comment by TeBoring** [comment]
I think you should call:
protoc.exe --cpp_out=src/ProtocolBuffers -IProtocolBuffers ProtocolBuffers/Subfolder/Subfolder1/Subfolder2/testMessage.proto

**Comment by reavertm** [comment]
Could someone explain this:

```[mrozowsk@cnu420dqzs test_case]$ tree top/
top/
└── dir
    └── sub
        └── file.proto

2 directories, 1 file
[mrozowsk@cnu420dqzs test_case]$ protoc --cpp_out=out -Itop/dir/sub -Itop/dir top/dir/sub/file.proto
[mrozowsk@cnu420dqzs test_case]$ tree out/
out/
├── file.pb.cc
└── file.pb.h

0 directories, 2 files
[mrozowsk@cnu420dqzs test_case]$ rm -fr out/*
[mrozowsk@cnu420dqzs test_case]$ protoc --cpp_out=out -Itop/dir -Itop/dir/sub top/dir/sub/file.proto
[mrozowsk@cnu420dqzs test_case]$ tree out/
out/
└── sub
    ├── file.pb.cc
    └── file.pb.h

1 directory, 2 files```

The output directory layout depends on proto file lookup paths...

**Comment by haberman** [comment]
Yes, basically `protoc` tries to canonicalize every file path. If you use `-Ia/b` then `protoc` assumes that `a/b` is the root of a tree of .proto files. So then if it comes across `a/b/c/d.proto`, it assumes that `c/d.proto` is the canonical name for that proto. All of the output files will be generated to match the canonical path of the input .proto file.

I really do not recommend doing something like `-Itop/dir -Itop/dir/sub`.

**Comment by promi** [comment]
This behaviour is quite annoying, I'm trying to use `protoc` from `meson` (http://mesonbuild.com/) within a subproject.

I have integrated ( https://groups.google.com/forum/#!topic/mesonbuild/sOus_Wog5_E )  `protoc` like this:

```
gen = generator(protoc, \
  output    : ['@BASENAME@.pb.cc', '@BASENAME@.pb.h'],
  arguments : ['--proto_path=@SOURCE_DIR@', '--cpp_out=@BUILD_DIR@', '@INPUT@'])
```

The `@INPUT@` in my situation is filled with a relative path to the subproject. This leads to a `protoc` command like this:

 '/usr/bin/protoc' '--proto_path=..' '--cpp_out=subprojects/libyami-proto/yami-proto@sha' '../subprojects/libyami-proto/Mumble.proto'

What meson expects is that the generated protobuf files will be placed in 

```
subprojects/libyami-proto/yami-proto@sha/Mumble.pb.c
subprojects/libyami-proto/yami-proto@sha/Mumble.pb.h
```

What happens instead is that `protoc` generates these files:

```
subprojects/libyami-proto/yami-proto@sha/subprojects/libyami-proto/Mumble.pb.c
subprojects/libyami-proto/yami-proto@sha/subprojects/libyami-proto/Mumble.pb.h
```

I don't know how I can work around this.

**Comment by promi** [comment]
Using `--proto_path=@CURRENT_SOURCE_DIR@` works using current meson git :).

See also: https://github.com/mesonbuild/meson/issues/1622
