### ISSUE TITLE
require in commonjs does not respect folder structure

### ISSUE THREAD

**Issue by itavy** [google/protobuf#1746]
this one relates to [1684](https://github.com/google/protobuf/issues/1684) 

i have 3 files, each one on a different directory:
./Base.proto
./User/User.proto 
./User/Web/Web.proto 

last one include the other 2;

in generated code for Web.proto (`protoc User/Web/Web.proto --js_out=import_style=commonjs,binary:protos -I=. -I=User -I=User/Web`) and the second require statement is wrong:

``` javascript
$ head -13 protos/User/Web/Web_pb.js 
/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var Base_pb = require('../../Base_pb.js');
var User_pb = require('../../User_pb.js');
```

it should be:

``` javascript
var User_pb = require('../User_pb.js');
```

below are the 3 proto files:

``` javascript
$ cat Base.proto 
syntax = "proto3";

package itavy.Base;

enum AppVersion {
  V_0_0_1 = 0;
  V_0_0_2 = 1;
};
```

``` javascript
$ cat User/User.proto 
syntax = "proto3";

package itavy.User;

enum Type {
  REGULAR = 0;
  ADMIN = 1;
};
```

``` javascript
$ cat User/Web/Web.proto 
syntax = "proto3";

package itavy.User.Web;

import "Base.proto";
import "User.proto";

message User {
  itavy.Base.AppVersion version = 1;
  string name = 2;
  string email = 3;
  itavy.User.Type type = 4;
};
```

**Comment by graywolf336** [comment]
Any chance we can get an update on this? Ran into an issue related to this..

**Comment by anandolee** [comment]
@haberman any updates or should we close it?

**Comment by haberman** [comment]
Sorry for the (very) slow response. This isn't a bug in protoc. For include paths to work correctly, the import paths should be relative to the base.

Web.proto should start like this:

```
syntax = "proto3";

package itavy.User.Web;

import "Base.proto";
import "User/User.proto";
```

Then you shouldn't need any `-I` flags, and all of the import paths should work properly.
