### ISSUE TITLE
Release a new beta?

### ISSUE THREAD

**Issue by jafara** [google/protobuf#1748]
Hello,

It seems iOS support for frameworks was merged a while ago, is it possible to have a new official beta with the new features released?

Thank you

**Comment by myitcv** [comment]
Would also be appreciated on the JS side of things because of https://github.com/google/protobuf/pull/1589

**Comment by onlyjob** [comment]
Related to #1479.

**Comment by xfxyjwf** [comment]
We are working on a new beta release 3.0.0-beta-4:
https://github.com/google/protobuf/tree/3.0.0-beta-4

The final 3.0.0 release will come soon after this last beta release.

**Comment by SRyabinin** [comment]
But there are unresolved issues on "3.0.0-beta-3" (see https://github.com/google/protobuf/milestones) Do they need be moved to anothe milestone?

**Comment by jafara** [comment]
Looks like beta 3 milestone is marked as complete! Maybe are are close to a new release :)

**Comment by myitcv** [comment]
Thank you @xfxyjwf and team!

https://github.com/google/protobuf/releases/tag/v3.0.0-beta-4

**Comment by rchom** [comment]
Now we just need the NuGet package.....  :)
