### ISSUE TITLE
Some PB2/3 questions related to .net core

### ISSUE THREAD

**Issue by rykr** [google/protobuf#1749]
We are using PB 2.6 and want to include PB 3 in our upcoming .net core compatible project.  I have a couple of questions:

1.  Is PB3 wire compatible with PB 2.6?  One of our devs said that we would need to tweak our .proto files to have them compile. We are looking to create a set of proto files that are compatible with both PB 2 and 3.  Is this possible?

2.  Is RTM for PB3 still slated for this month?

3.  And is the csharp version of PB3 .net core compatible?

Thanks

**Comment by xfxyjwf** [comment]
On Wed, Jul 6, 2016 at 9:22 AM, rykr <notifications@github.com> wrote:

> We are using PB 2.6 and want to include PB 3 in our upcoming .net core
> compatible project. I have a couple of questions:
>
>    1.
>
>    Is PB3 wire compatible with PB 2.6?
>
> Yes, it's wire compatible.


>
>    1.
>
>    One of our devs said that we would need to tweak our .proto files to
>    have them compile. We are looking to create a set of proto files that are
>    compatible with both PB 2 and 3. Is this possible?
>
> protobuf-2.6 only supports proto2 syntax, while protobuf-3.0.0 supports
both proto2 and proto3 syntax. If you are using C++/Java/Python, you can
keep using proto2 syntax and that doesn't require any changes to your
existing .proto files. If you are using other proto3 only languages (like
csharp), you will have to upgrade your proto to proto3 syntax.


>
>    1.
>
>    Is RTM for PB3 still slated for this month?
>
> Different languages will have different schedules. The first release will
only include some of the languages but not all.


>
>    1.
>
>    And is the csharp version of PB3 .net core compatible?
>
> The csharp implementation of PB3 is a brand new implementation. It's not
compatible with other csharp implementations as far as I know.

**Comment by rykr** [comment]
Is there a roadmap that shows the expected RTM dates for the different languages?

**Comment by jskeet** [comment]
The C# version has now RTM'd - closing this issue.
