### ISSUE TITLE
javascript travis test is failing

### ISSUE THREAD

**Issue by xfxyjwf** [google/protobuf#1751]
See: https://travis-ci.org/google/protobuf/jobs/142773972

**Comment by xfxyjwf** [comment]
@haberman The javascript test is failing after down-integration. Could you help take a look?

**Comment by xfxyjwf** [comment]
@acozzette

**Comment by acozzette** [comment]
I think I know what is causing this, I'll send out a pull request shortly.

**Comment by acozzette** [comment]
This should be fixed with pull request #1752. I went ahead and merged it without waiting for the Travis build since it can be slow.
