### ISSUE TITLE
Linker flags in configure.sh

### ISSUE THREAD

**Issue by haleyyew** [google/protobuf#1754]
Hi,
I am trying to use protobuf on ARM TrustZone. The problem is that the libc that the ARM build environment uses does not have some of the functions that the standard libc has (e.g., malloc, memcpy, memmove). In my environment, these functions exist in a separate static library called libutil.a. How do I compile protobuf so that rather than looking for these functions dynamically in libc, it'll look for them statically in libutil?

Currently I'm adding the environment variables by `./configure --with-sysroot=MY_DIR` but without much success. Can you give me some tips on how to replace libc with libutil.a when installing protobuf? 

Thanks.

**Comment by TeBoring** [comment]
Perhaps you also need to tell the compiler which library to link against. e.g., -lutil
