### ISSUE TITLE
make error !!! (libprotobuf.la)

### ISSUE THREAD

**Issue by light-bo** [google/protobuf#1760]
When i  compile the source codes on the mac, i come across the error: **cannot find the library 'Buffers/protobuf-3.0.0-beta-3.1/src/libprotobuf.la' or unhandled argument 'Buffers/protobuf-3.0.0-beta-3.1/src/libprotobuf.la'** 

Does anyone comes across the same problem to?
How to solve it ?
^_^

**Comment by xfxyjwf** [comment]
Try to build protobuf in a directory whose path doesn't contain spaces? Seems you have a "Protocol Buffers" directory in the build tree and something goes wrong and the path is interpreted as "Protocol" and "Buffers/...".

**Comment by light-bo** [comment]
@xfxyjwf Thank you for your reply, I have try your method, but it still occurs the some error.

**Comment by TeBoring** [comment]
Close this issue for clean up. Feel free to reopen it if still have problem.

**Comment by chen0572054** [comment]
having the same error. no space in the path
