### ISSUE TITLE
FreeBSD build doesn't work

### ISSUE THREAD

**Issue by benlaurie** [google/protobuf#1766]
In order to build on FreeBSD, I have to set LD_LIBRARY_PATH=/usr/local/lib/gcc48. This is also required to run the built protoc.

Without that, I get the following error:

/usr/local/lib/compat/libstdc++.so.6: version GLIBCXX_3.4.10 required by /usr/local/lib/libprotobuf.so.10 not found

**Comment by xfxyjwf** [comment]
This seems to be a configuration problem of your build environment. There isn't much we can do in protobuf.

**Comment by benlaurie** [comment]
It seems more likely that it is caused by using gcc instead of cc (FreeBSD does not use gcc by default).
