### ISSUE TITLE
Bazel warning - workspace doesn't have a canonical name

### ISSUE THREAD

**Issue by cceckman** [google/protobuf#1767]
I've my own Bazel-build repository; in my WORKSPACE, I reference google/protobuf as a git_repository with name = "google_protobuf". Bazel gives a warning when I build a target that depends on it:

```
WARNING: /private/var/tmp/_bazel_cceckman/4fab4568001ac2509e1d1900e97dd42d/external/google_protobuf/WORKSPACE:1: Workspace name in /private/var/tmp/_bazel_cceckman/4fab4568001ac2509e1d1900e97dd42d/external/google_protobuf/WORKSPACE (@__main__) does not match the name given in the repository's definition (@google_protobuf); this will cause a build error in future versions.
```

It looks like Bazel is warning that google/protobuf doesn't use the [workspace](http://www.bazel.io/docs/be/functions.html#workspace) function to give name to the workspace. I don't get this warning by referencing the external repository [rules_go](https://github.com/bazelbuild/rules_go/blob/master/WORKSPACE) with the corresponding name.

It looks like this takes all of 5m to fix, so I'll take a stab at it.

**Comment by gerben-s** [comment]
Continue on the PR thread.
