### ISSUE TITLE
issue using a non-default calling convention 

### ISSUE THREAD

**Issue by breathe67** [google/protobuf#1769]
Hi, I'm having an issue compiling a protobuf header (arena.h) when using a non-default calling convention (__vectorcall) across the whole project. (This is used to accelerate SIMD-type parameter passing.) I think it's because of the default argument 'malloc' to block_alloc(...) below. When compiling it now assumes the new default  __vectorcall convention,  but is initialized with the  'cdecl' style malloc and so detects an incompatible function type. I might be able to modify the protobuf code directly to specify 'cdecl', but that's hard to maintain. Wondering if there's any way to fix the init to be calling convention agnostic ?

ArenaOptions()
      : start_block_size(kDefaultStartBlockSize),
        max_block_size(kDefaultMaxBlockSize),
        initial_block(NULL),
        initial_block_size(0),
        block_alloc(&malloc), **// << compile fails**
        block_dealloc(&internal::arena_free),
        on_arena_init(NULL),
        on_arena_reset(NULL),
        on_arena_destruction(NULL),
        on_arena_allocation(NULL) {}

**Comment by pherl** [comment]
Sorry we don't have the environment for this. Have you solved the issue already? I'm closing this issue now. Feel free to send PR if there's a fix.
