### ISSUE TITLE
help  : ad_block_key

### ISSUE THREAD

**Issue by alvis-huang** [google/protobuf#177]
hello,  ad_block_key is stable identifier for the combination of publisher, ad slot, and page. But I don't know how the information combination,  That is, how can I gain publisher, ad slot, and page information by ad_block_key. 
Because I am in China, I can open some website, you konw.

Thanks already!
Regards,
Alvis.huang

**Comment by xfxyjwf** [comment]
Hi, I think you posted the question to the wrong forum. I searched around and the closest I could find about ad_block_key is:
https://developers.google.com/ad-exchange/rtb/relnotes

You might want to check out that documentation and see if you can find relative information about ad_block_key there.
