### ISSUE TITLE
Performance downgrade in multi-thread JAVA implementation

### ISSUE THREAD

**Issue by fqsuncn** [google/protobuf#1770]
I tried to test protobuf in multi-thread case, and when I launch 1 thread, the cost of processing 1,000,000
 records is about 40s on my machine. But when I launched 2 threads, the cost of each raised to 80s. My server is not a PC, and it has 32 cores to process.

	public class parseThread implements Runnable {
		private String command;
		private TestMsg testMsgInput;
		byte[] buf = null;

		public parseThread(String s, TestMsg msg) {
			this.command = s;
			this.testMsgInput = msg;
		}

		@Override
		public void run() {

				buf = testMsgInput.toByteArray();

				for (int k = 0; k < 1000000; k++) {
					try {
						TestMsg parsedMsg = TestMsg.parseFrom(buf);
					} catch (Exception e) {
						e.printStackTrace();
					}
				}
                 }

**Comment by fqsuncn** [comment]
I run the test case for several time, the cost distributed from 40s to 80s. I don't understand why this happened.

**Comment by xfxyjwf** [comment]
What's the size of your test message? When happens if you try a smaller message and/or wth more concurrent threads?

**Comment by fqsuncn** [comment]
ExecutorService executorGet = Executors.newFixedThreadPool(numThread);

		for ( int i =1; i < numThread + 1; i ++) {
			Runnable worker = new parseThread("Parser" + i);
			executorGet.execute(worker);
		}
		executorGet.shutdown();

I run program with different number of concurrent threads, the result is below,

MsgOperator 1
Generate 500000 records Cost Parser1:10243 ms

MsgOperator 2
Generate 500000 records Cost Parser1:15590 ms
Generate 500000 records Cost Parser2:15644 ms

MsgOperator 3
Generate 500000 records Cost Parser3:41255 ms
Generate 500000 records Cost Parser1:41565 ms
Generate 500000 records Cost Parser2:42258 ms

MsgOperator 4
Generate 500000 records Cost Parser4:44766 ms
Generate 500000 records Cost Parser2:46213 ms
Generate 500000 records Cost Parser1:46284 ms
Generate 500000 records Cost Parser3:47003 ms

MsgOperator 5
Generate 500000 records Cost Parser4:49496 ms
Generate 500000 records Cost Parser2:49650 ms
Generate 500000 records Cost Parser5:49787 ms
Generate 500000 records Cost Parser1:49837 ms
Generate 500000 records Cost Parser3:49871 ms

**Comment by xfxyjwf** [comment]
Could you share the full source of your benchmarks?

**Comment by fqsuncn** [comment]
public class TestMsgOperator {

	public static void main(String[] args) {

		TestMsgOperator emo = new TestMsgOperator();
		emo.perfProtoBuf(Integer.valueOf(args[0]).intValue());

	}

	private void perfProtoBuf(int numThread) {
		ExecutorService executorGet = Executors.newFixedThreadPool(numThread);
		for ( int i =1; i < numThread + 1; i ++) {
			Runnable worker = new parseThread("Parser" + i, msg1);
			executorGet.execute(worker);
		}
		executorGet.shutdown();
	}

	public class parseThread implements Runnable {
		private String command;
		byte[] buf = null;

		public parseThread(String s) {
			this.command = s;
		}

		@Override
		public void run() {

			TestMsg.Builder testMsgBuilder = TestMsg.newBuilder();

			TestMsg testMsg = null;

			testMsgBuilder.setField1(100);
			.....
			About 200 fields to fill, I ignore them.
			.....



			testMsg = testMsgBuilder.build();
			long startTime = System.currentTimeMillis();
			buf = testMsg.toByteArray();

			for (int k = 0; k < 500000; k++) {
				try {
					TestMsg parsedMsg = TestMsg.parseFrom(buf);
				} catch (Exception e) {
					e.printStackTrace();
				}
			}

			long endTime = System.currentTimeMillis();
			System.out.println("Generate 500000 records Cost " + command
						+ ":" + String.valueOf(endTime - startTime) + " ms");

			}
		}

		@Override
		public String toString() {
			return this.command;
		}
	}
}

**Comment by fqsuncn** [comment]
issue resolved to update "optimize_for = SPEED"

**Comment by xfxyjwf** [comment]
@fqsuncn can you also post your benchmark results after setting optimize_for = SPEED? Were you using optimize_for = CODE_SIZE before?
