### ISSUE TITLE
Required lowerCamelCasing in Proto3 JSON standard

### ISSUE THREAD

**Issue by benjigoldberg** [google/protobuf#1774]
In the Proto3 reference it is [mentioned that JSON exported from Protobuf must be in `lowerCamelCase` format](https://developers.google.com/protocol-buffers/docs/proto3#json). Why is this part of the standard, and why can't casing of the key values be an option left to the user? 

At my company, and I imagine a handful of others, we prefer to `underscore_our_vars` since we're primarily developing Python where this is the standard. We also do this in the `.proto` definition files, as does Google in its sample `.proto` examples. While primarily a nuisance, this does cause extra work for us in maintaining proto-generated JSON alongside other types of JSON data in our infrastructure. 

If the maintainers are open to making this an option in the JSON formatting routines for the various languages, I would be happy to make those updates.

**Comment by xfxyjwf** [comment]
The option already exists in some implementations. For example, in Java:
https://github.com/google/protobuf/blob/master/java/util/src/main/java/com/google/protobuf/util/JsonFormat.java#L161

The option will allow you to use whatever field name you declare in the .proto file as the JSON field name.

What language are you particularly interested in?

**Comment by benjigoldberg** [comment]
@xfxyjwf Thanks for your response -- I'm happy to see that the option exists in Java. I'm most interested in the [Python `json_format.py` file](https://github.com/google/protobuf/blob/master/python/google/protobuf/json_format.py), which I don't believe offers this option.

If the Java version already supports this option, I assume it would be ok to submit a patch adding this functionality for Python?

**Comment by xfxyjwf** [comment]
Yes, feel free to send us a pull request.  :)

**Comment by xfxyjwf** [comment]
The same option is available in Python also so I'm closing this issue.

**Comment by xfxyjwf** [comment]
Forgot to post the link to the python option:
https://github.com/google/protobuf/blob/master/python/google/protobuf/json_format.py#L91
