### ISSUE TITLE
Option "(google.api.http)" unknown

### ISSUE THREAD

**Issue by aymanosman** [google/protobuf#1780]
`libprotoc 3.0.0`

Running command `protoc --js_out lib service.proto` on file:

```
syntax = "proto3";

message EchoMessage {
  string value = 1;
}

service EchoService {
   rpc Echo(EchoMessage) returns (EchoMessage) {
     option (google.api.http) = {
       post: "/v1/echo"
       body: "*"
     };
   }
}
```

**Comment by xfxyjwf** [comment]
(google.api.http) is a custom option defined in some other .proto file. You need to use the "import" statement to import that .proto file.

**Comment by aymanosman** [comment]
Sorry that was a rookie mistake. I did add the import statement but ran into problems testing on osx, but got it working in Ubuntu so all good. Thanks.

**Comment by lei314121077** [comment]
@aymanosman  How to fix this?

**Comment by aymanosman** [comment]
@lei314121077 It was so long ago I honestly don't remember.

**Comment by ihorbond** [comment]
apparently (at least in case of C#) the nuget package doesnt come with these so you have to get the files manually and add them to your project
https://github.com/googleapis/googleapis/blob/master/google/api/http.proto
https://github.com/googleapis/googleapis/blob/master/google/api/annotations.proto

**Comment by mvrhov** [comment]
> 
> 
> @lei314121077 you also need to import `import "google/api/annotations.proto";`
Am I the only one that thinks that this is beyond stupid. As I do not explicitly use the annotations in my proto file.
