### ISSUE TITLE
objectivec_cocoapods_integration is failing on traviscl.

### ISSUE THREAD

**Issue by xfxyjwf** [google/protobuf#1786]
Example: https://travis-ci.org/google/protobuf/jobs/144417083

Error message:
```
Cleaning up...
+shell_session_update
./tests.sh: line 333: shell_session_update: command not found
The command "./tests.sh $CONFIG" exited with 127.
Done. Your build exited with 1.
/Users/travis/build.sh: line 109: shell_session_update: command not found
```

@thomasvl

**Comment by thomasvl** [comment]
@sergiocampama is looking.  Looks it is coming from nvm for some reasons.  Trying to figure out what changed, to start triggering it.

**Comment by sergiocampama** [comment]
More information about the bug in https://github.com/direnv/direnv/issues/210
