### ISSUE TITLE
protobuf==3.0.0b3 loses message enum values from class

### ISSUE THREAD

**Issue by thanatos** [google/protobuf#1795]
`heka_py` defines the following [protocol buffer](https://github.com/kalail/heka-py/blob/d975dc7d0f285aee86f8e74037391856d1c46790/protobuf/message.proto#L16-L25):

``` proto
message Field {
  enum ValueType {
    STRING  = 0;
    BYTES   = 1;
    INTEGER = 2;
    DOUBLE  = 3;
    BOOL    = 4;
  }
  required string       name            = 1;
  optional ValueType    value_type      = 2 [default = STRING];
  optional string       representation  = 3;
  repeated string       value_string    = 4;
  repeated bytes        value_bytes     = 5;
  repeated int64        value_integer   = 6 [packed=true];
  repeated double       value_double    = 7 [packed=true];
  repeated bool         value_bool      = 8 [packed=true];
}
```

Notably, this defines an `enum`, "`ValueType`" (the message here carries a value, which is one of several types; `value_type` encodes which type the message encodes)

The code thus inspects `value_type`, and uses it to determine, through [a mapping](https://github.com/kalail/heka-py/blob/d975dc7d0f285aee86f8e74037391856d1c46790/heka/message.py#L81-L86), which attribute on the message to inspect, i.e.,

``` python
_FIELD_TYPE_TO_ATTRIBUTE = {
    Field.INTEGER: 'value_integer',
    Field.DOUBLE: 'value_double',
    Field.BOOL: 'value_bool',
    Field.STRING: 'value_string',
}
```

Here, it uses `Field.INTEGER`, which is the value of the `INTEGER` enum. (`Field` here is a subclass of `google.protobuf.message.Message`, as created by the protobuf compiler.) This attribute _exists_ in `protobuf>=2,<3`, but does not exist in `protobuf==3.0.0b3`, breaking `heka_py`.

(I, as a consumer of `heka_py`, am forced to use `protobuf==3.0.0b3` as `protobuf` v2 only supports Python 2.)

<s>I find it a bit odd to access the enum values on the _Message_ class; one would imagine that if the message defined two separate enum types with corresponding names but different values, this would result in a name collision on the `Message` subclass. There exists `Field.ValueType` (but only in protobuf 2), but that doesn't have the `INTEGER` etc. attributes. (This was causing me to wonder if `heka_py` is using something part of the API that wasn't intended to be as exposed.)</s> No, this is documented. I have no idea what two enums with conflicting values would do.

I can't find — anywhere — `INTEGER` as an attribute. There's `Field.DESCRIPTOR.enum_values_by_name['INTEGER']`, but that seems incredibly unwieldy.

**Comment by haberman** [comment]
> This attribute exists in protobuf>=2,<3, but does not exist in protobuf==3.0.0b3

Hmm, I can't reproduce this problem. For me `Field.INTEGER` exists in both 2.x and 3.x. Do you have a repro case for this?

**Comment by anandolee** [comment]
Closing it for unable to reproduce and no response
