### ISSUE TITLE
[feature] parseDelimitedFrom and writeDelimitedTo for C++

### ISSUE THREAD

**Issue by rubdos** [google/protobuf#1798]
Very useful for streaming sockets, and I'm not the only one requesting it:

http://stackoverflow.com/questions/8269452/google-protocol-buffers-parsedelimitedfrom-and-writedelimitedto-for-c

https://groups.google.com/forum/#%21topic/protobuf/xYeH5Wzy0N0

Apparently, it's in the Java version and not in the C++ version.

**Comment by pherl** [comment]
https://github.com/google/protobuf/pull/710 is an open PR, however no one has picked it up.
