### ISSUE TITLE
Protobuf 3.0 is slow

### ISSUE THREAD

**Issue by c0nk** [google/protobuf#1800]
I've done some testing with protobuf version 3.0.0-beta3.1 with our existing internal codebase and found its slower in all benchmarking i've done (10-20% regression compared to version 2.6.1). We're still using proto2 and only changed the .proto file by adding:

```
syntax = "proto2";
option cc_enable_arenas = true;
```

Using arenas explicitly in the code seemed to not affecting timings in any meaningful way. Is google also seeing this?

**Comment by c0nk** [comment]
To provide more information here. We are using the C++ interface on iOS. The regressions are on ARM. It is perhaps also worth noting that the code in question makes use of oneof. Some other unrelated code (that isn't using oneof) running on x86_64 seems to be a little faster on proto v3.0. So the regression is related to ARM or use of oneof. Does anyone have any insight here?

**Comment by gubbanoa** [comment]
I am trying to send float arrays over sockets between python and java and the other way around.
extending repeated field to 10000000 floats takes 6 seconds on a 4 core machine!

message BigMessage{
  required string property;
  repeated double data = 1;
}

#Here comes the python code:
import numpy as np
bigbuffer = np.empty(10000000)
bigbuffer[1] = 2.7
bigbuffer[9000000]=3.14

myMessage = messageDeclarations.BigMessage()

start = time.time()
myMessage.data.extend(bigbuffer)
end = time.time()

**Comment by xfxyjwf** [comment]
For C++, although 3.0.0 is a major version, but the actual code is from 2.6.1 with incremental changes (if you are using proto2 syntax only). I don't know where the major performance degradation can come from. We don't usually benchmark on Arm either so any insights from Arm users would be appreciated.

**Comment by veonua** [comment]
@jtattermusch what was the solution? it looks like the issue was not solved

**Comment by jtattermusch** [comment]
@veonua I think more insights are needed in terms of what exactly got slower and provide a snippet to run, including numbers before and after.
