### ISSUE TITLE
protobuf-java lite not in Maven Central

### ISSUE THREAD

**Issue by kaelad02** [google/protobuf#1804]
I was going to use the lite version of protobuf for Java. I'm going to use it for data storage and figured the lite version would work just fine for me. Also, being able to include a much smaller JAR file is appealing. Anyways, I went to add it as a dependency in my Maven pom.xml file when I realized that the lite version hasn't been published to Maven Central. I think there are some old versions, like 2.2 or 2.3, but not the latest release version, 2.6.1.

Did I miss anything, or is it not there?

**Comment by xfxyjwf** [comment]
Do you want to use it for mobile clients? We haven't published lite to maven before but we will do it starting from 3.0.

**Comment by kaelad02** [comment]
No, it's for a library that'll be consumed by server applications. The smaller JAR size is attractive because those apps that consume this library will only need one extra small JAR file.

**Comment by pherl** [comment]
protobuf-lite artifact is available now.

**Comment by mockturtl** [comment]
http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22com.google.protobuf%22%20AND%20a%3A%22protobuf-lite%22

> 3.0.1	28-Jul-2016 

Is this the latest release of javalite?

This repository, github.com/google/protobuf, is [currently](https://github.com/google/protobuf/releases/tag/v3.2.0) at 3.2 -- is it correct to infer that javalite is versioned separately?

**Comment by acozzette** [comment]
@mockturtl For the time being we are leaving the version of lite on Maven Central at 3.0.1, because we are in the process of making a number of changes that break compatibility between the generated code and the runtime library. See the discussion on #2935 for more details.
