### ISSUE TITLE
proto2 float getting truncated? 

### ISSUE THREAD

**Issue by sburke56** [google/protobuf#1806]
I'm using the service interface and successfully calling an RPC function between a Windows box to a Linux box.  My message contains a float and I'm using the following code & the float is not coming out the other end.  I'm using syntax proto2.  Any help would be appreciated.  Some floats are working but some are not. 

0.5 not working 
33.33 working 
anything < 1 doesn't seem to be working
anything > 2 after the decimal point seems to be working

```
TargetProto request;
RpcChannel rpc_channel(ENDPOINT_PORT);
MyService::Stub stub(&rpc_channel);
MyDataRequestProto response;
request.set_id(1);
request.set_size(0.25f);

cout << "request->size(): " << request.size() << endl; 
stub.MyCallRpc(NULL, &request, &response, NULL);
```

My message looks like this. 
```		
message TargetProto {
  required uint32 id = 1;
 required float size = 2;
}
```

My server looks like this. 
```
cout << this->descriptor()->full_name() << endl;
cout << "Received: " << request->id() << endl;
float tmp = request->size();
cout << "Received: " << tmp << endl;
```

**Comment by xfxyjwf** [comment]
What RPC implementation are you using?

**Comment by sburke56** [comment]
I'm using nanomsg.

**Comment by sburke56** [comment]
A little more info. I dump the buffers on both sides trying to send over a .25f value.  According to an IEEE 754 converter I should see .25 as 0x3e800000.  So the data looks ok as long as endianness is handled for me.  Thoughts? 

Windows buf. 
0d00 0080 3ecd cdcd cd

Linux buf. 
000d 8000 cd3e cdcd 00cd

**Comment by xfxyjwf** [comment]
Why is the linux buf dumped in a reverse order for every two bytes? And why are there padding "cd"s?

**Comment by sburke56** [comment]
I'm looking into this now with the transport layer (nanomsg). I assumed it
was just flipping the endianness after going over the network. I'm not sure
why that is happening and I read that protobufs would handle endianness for
me. What is odd to me is that floats like .2551 will work and < 1 will not.

**Comment by sburke56** [comment]
I was looking at the hex data with hexdump on linux which flips the byte order.  So no the data looks to be correct going across the wire. 

Figured it out.  Looks like I was using ParseFromString versus ParseFromArray.  I'm guessing the ParseFromString wasn't able to figure out where the end of the message was.
