### ISSUE TITLE
Unable to use compiled python protobuf in another system 

### ISSUE THREAD

**Issue by umarengasamy** [google/protobuf#181]
Getting the below error when we tried to use compile protobuf using protoc 2.6.1 
and issue doesn't appear if we use protoc 2.5.0
  from google.protobuf import symbol_database as _symbol_database
E   ImportError: cannot import name symbol_database

**Comment by xfxyjwf** [comment]
This is by design. Protobuf requires the version of the runtime to match with the version of the protocol compiler. If the version doesn't match, there will be such import or runtime errors.
