### ISSUE TITLE
When I build ProtoBuf On Windows ,Cmake Configuration Met a Problem and build failed , How to fix this problem?

### ISSUE THREAD

**Issue by hailong0715** [google/protobuf#1819]
When I build ProtoBuf with a Release package on windows, but when I run cmake configration script      C:\Path\to\protobuf\cmake\build>mkdir release & cd release
     C:\Path\to\protobuf\cmake\build\release>cmake -G "NMake Makefiles" ^
     -DCMAKE_BUILD_TYPE=Release ^
     -DCMAKE_INSTALL_PREFIX=../../../../install ^
Configration incomplete,errors occur.
The output is as follows:
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio
12.0/VC/bin/cl.exe -- broken
CMake Error at C:/cmake/share/cmake-3.6/Modules/CMakeTestCCompiler.cmake:61 (mes
sage):
  The C compiler "C:/Program Files (x86)/Microsoft Visual Studio
  12.0/VC/bin/cl.exe" is not able to compile a simple test program.

  It fails with the following output:

   Change Dir: E:/protobuf-cpp-3.0.0-beta-4/protobuf-3.0.0-beta-4/cmake/build/re
lease/CMakeFiles/CMakeTmp

  Run Build Command:"nmake" "/NOLOGO" "cmTC_f26cf\fast"

```
    "C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\nmake.exe" -
```

f
  CMakeFiles\cmTC_f26cf.dir\build.make /nologo -L
  CMakeFiles\cmTC_f26cf.dir\build

  Building C object CMakeFiles/cmTC_f26cf.dir/testCCompiler.c.obj

```
    "C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\cl.exe"
```

  @C:\Users\hzhan\AppData\Local\Temp\nm1F07.tmp

  testCCompiler.c

  Linking C executable cmTC_f26cf.exe

```
    C:\cmake\bin\cmake.exe -E vs_link_exe --intdir=CMakeFiles\cmTC_f26cf.dir
```

  --manifests -- "C:\Program Files (x86)\Microsoft Visual Studio
  12.0\VC\bin\link.exe" /nologo @CMakeFiles\cmTC_f26cf.dir\objects1.rsp
  @C:\Users\hzhan\AppData\Local\Temp\nm2011.tmp

  RC Pass 1 failed to run.

  NMAKE : fatal error U1077: 'C:\cmake\bin\cmake.exe' : return code
  '0xffffffff'

  Stop.

  NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio
  12.0\VC\bin\nmake.exe"' : return code '0x2'

  Stop.

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:12 (project)

-- Configuring incomplete, errors occurred!
See also "E:/protobuf-cpp-3.0.0-beta-4/protobuf-3.0.0-beta-4/cmake/build/release
/CMakeFiles/CMakeOutput.log".
See also "E:/protobuf-cpp-3.0.0-beta-4/protobuf-3.0.0-beta-4/cmake/build/release
/CMakeFiles/CMakeError.log".

The output in CMakeErrpr.log is:
The output was:
2
Microsoft (R) C/C++ Optimizing Compiler Version 18.00.31101 for x86
Copyright (C) Microsoft Corporation.  All rights reserved.

CMakeCCompilerId.c
Microsoft (R) Incremental Linker Version 12.00.31101.0
Copyright (C) Microsoft Corporation.  All rights reserved.

/out:CMakeCCompilerId.exe 
CMakeCCompilerId.obj 
LINK : fatal error LNK1104: cannot open file 'LIBCMT.lib'

I have already added the "C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\lib" to envionment variables, but it didn't work.
How to fix this Problem?
Great Thanks

**Comment by xfxyjwf** [comment]
The error message seems to suggest your VC installation has some problems. Can you reinstall VC or install a newer version of VC and try again?

**Comment by skatpgusskat** [comment]
I had same problem on VS2013, and I tried with VS2015, and it worked.

**Comment by podsvirov** [comment]
In my experience, pure VS2013 is broken allways. Try update to VS2013 SP1.
