### ISSUE TITLE
JsonFormat: why is Int64 being converted to a string ?

### ISSUE THREAD

**Issue by darkcrawler01** [google/protobuf#1823]
I am using the `JsonFormat.Printer` util class for converting Protos to JSON.
and I noticed that the Int64 is converted to `String` instead of keeping it a number/integer. 
https://github.com/google/protobuf/blob/master/java/util/src/main/java/com/google/protobuf/util/JsonFormat.java#L880-L883

I am sure there is a good reason but I am not able to figure it out.
can someone explain ?

**Comment by xfxyjwf** [comment]
See: https://groups.google.com/forum/#!topic/protobuf/4-BY-k-Lk-g

Quoted Jon's comment:
"It's due to the way that all numbers in JSON are basically IEEE-754 64-bit doubles... which means that any 64-bit integers can lose information. Using a string instead, all 64-bit integers can be round-tripped with no loss of information."

**Comment by mickeyreiss** [comment]
@xfxyjwf would you be open to a patch that makes it possible to override this behavior change? I'm having trouble upgrading to the latest protobuf library without making a breaking change for clients that consume JSON.

**Comment by xfxyjwf** [comment]
@mickeyreiss I don't remember we have made a behavior change on that. As far as I know, the JsonFormat class prints int64 as strings from the beginning. Are you migrating from some other JSON implementation?

**Comment by mickeyreiss** [comment]
Yes, we are migrating from [`JsonJacksonFormat`](https://github.com/bivas/protobuf-java-format/blob/master/src/main/java/com/googlecode/protobuf/format/JsonJacksonFormat.java#L217) from [com.googlecode.protobuf-java-format:protobuf-java-format:1.4](https://mvnrepository.com/artifact/com.googlecode.protobuf-java-format/protobuf-java-format/1.4).
