### ISSUE TITLE
MessageDifferencer in java

### ISSUE THREAD

**Issue by amkarthick** [google/protobuf#1838]
Is there any way to use MessageDifferencer in java? Or is that supported only for c++?

**Comment by xfxyjwf** [comment]
Right now MessageDifferencer is only available in C++. It may be added for Java later.

**Comment by lamuguo** [comment]
Any update about this?

**Comment by alexsapps** [comment]
There seems to be a Java version here: https://github.com/google/truth/blob/master/extensions/proto/src/main/java/com/google/common/truth/extensions/proto/MessageDifferencer.java
