### ISSUE TITLE
GPBUtilities_PackagePrivate.h should silence implicit conversion warnings

### ISSUE THREAD

**Issue by dfed** [google/protobuf#1844]
`GPBDecodeZigZag32`, `GPBDecodeZigZag64`, `GPBEncodeZigZag32`, and `GPBEncodeZigZag64` all have implicit conversions. Looks like they're doing this on purpose. We should surround these methods with
```
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wconversion"

#pragma clang diagnostic pop
```

**Comment by thomasvl** [comment]
Adding casts instead seems better as it helps make it explicit what we're after.
