### ISSUE TITLE
Failure complaining about protoc installing python (3.0.0b4)

### ISSUE THREAD

**Issue by asottile** [google/protobuf#1849]
From https://travis-ci.org/asottile/PokemonGo-Map/builds/147357964

```
Running setup.py bdist_wheel for protobuf

Destination directory: /home/travis/.cache/pip-faster/wheelhouse

Complete output from command /home/travis/build/asottile/PokemonGo-Map/venv/bin/python3.5 -c "import setuptools;__file__='/home/travis/build/asottile/PokemonGo-Map/venv/build/protobuf/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /home/travis/.cache/pip-faster/wheelhouse:

running bdist_wheel

running build

running build_py

protoc is not installed nor found in ../src.  Please compile it or install the binary package.

Generating google/protobuf/pyext/python_pb2.py...
```

From [what I gather](https://github.com/google/protobuf/blob/ba52f2b6780fa5e6bee86cf7e8ee6f6ba617862c/python/setup.py#L49), this seems to be trying to rebuild pb2 files, though they already exist in the source distribution:

```
$ wget https://pypi.python.org/packages/03/73/2e494c2d8aada472c82688ff4f692c975b3e8266bbe012a1a766e5c389ac/protobuf-3.0.0b4.tar.gz#md5=8b9ebb93024c19b24880a8acaf856f4c
...
$ tar -xf protobuf-3.0.0b4.tar.gz
...
$ tree protobuf-3.0.0b4 | grep python_pb2
│       │   ├── python_pb2.py
```

This strangely only seems to be happening on travis-ci (I cannot reproduce the same locally).

A workaround for now is to add:

```
addons:
    apt:
        packages:
        -   protobuf-compiler
```

Or to use 2.6.1

I'm not sure if it matters, but I'm using python3.5

I notice that all of the other .proto files are not included in the source distribution, should pyext/python.proto be excluded as well?

**Comment by BoBeR182** [comment]
https://travis-ci.org/BoBeR182/Pokemon-Go-Bot-Working-Hack-API

Has same issue, cannot replicate on my Arch linux machine nor fresh install of Ubuntu 16.04

**Comment by xfxyjwf** [comment]
@asottile @BoBeR182 Thanks for the bug report. I just uploaded a binary wheel package to pypi. That should resolve the problem for now. Can you try again?

**Comment by asottile** [comment]
Worked great for me! Thanks!

https://github.com/asottile/PokemonGo-Map/pull/29

**Comment by BoBeR182** [comment]
https://travis-ci.org/BoBeR182/Pokemon-Go-Bot-Working-Hack-API Issue fixed

**Comment by bogdan-ciobanu-hs** [comment]
Hi,
We're having the same problem while running `pip install protobuf==3.0.0b4`.
```  
Running setup.py install for protobuf
    protoc is not installed nor found in ../src.  Please compile it or install the binary package.
    Generating google/protobuf/pyext/python_pb2.py...
    Complete output from command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip_build_root/protobuf/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-BG7ugI-record/install-record.txt --single-version-externally-managed --compile:
    running install

running build

running build_py

protoc is not installed nor found in ../src.  Please compile it or install the binary package.

Generating google/protobuf/pyext/python_pb2.py...
```
Anyway, when running the command the second time, it works. Any idea on what might cause this?

**Comment by TeBoring** [comment]
Feel free to reopen the issue if there is still problems.

**Comment by mkundanjha** [comment]
Yes I am having the same issue again . Even the link for the repo above says "Couldn't find repo". Please Help
