### ISSUE TITLE
Java - Decouple protoc generated artifacts from runtime version

### ISSUE THREAD

**Issue by louiscryan** [google/protobuf#1852]
@xfxyjwf 

Currently a protoc 2.4 / 2.5 / 2.6 generated classes cannot be used with the proto3 runtime. Similarly a protoc 3.0 generated artifact cannot be used with non proto3 runtimes. This has created upgrade hell for users of libraries that themselves use protobuf (e.g. HBase, Hadoop, ...)

We need to find a way to:
- Migrate all existing protoc 2.4 / 2.5 / 2.6 generated artifacts onto the proto3 runtime
- For future runtime releases allow them to be drop in replacements for prior runtime versions without requiring code regeneration for:
  -  some number of trailing releases (e.g. 2)
  -  some reasonable upgrade window (12 - 24 months)

**Comment by xfxyjwf** [comment]
Current plan for Java:
* Starting from 3.0.0 release, minor version changes will be backwards compatible (e.g., protoc 3.0.0 generated code can be compiled/ran against protobuf runtime 3.1.0).
* 3.x runtime will not be compatible with 2.x generated code, but we are working on a Java 2.7 release that can be used as a bridge version between 2.x and 3.0:
  - 2.7 runtime will be compatible with 2.5/2.6 protoc generated code.
  - 3.0 runtime will be compatible with 2.7 protoc genreated code.
* 2.x users can migrate to 2.7 first and after there are no 2.5/2.6 dependencies, they can move to 3.x.
* 2.7 will be forked from 3.0.0-beta-4. It will include all new features in 3.x releases and we will keep updating it until most users are at 3.x.

**Comment by louiscryan** [comment]
Thanks for clarifying. Good to see commitment to compatibility within minor versions going forward.

**Comment by xfxyjwf** [comment]
I have created a 2.7 branch here as a step stone from 2.5/2.6 to 3.0:
https://github.com/google/protobuf/tree/2.7.0

And starting from 3.0.0 release we have compatibility tests to enforce binary backwards compatibility now.

**Comment by profic** [comment]
Hi @xfxyjwf, are there any plans to release 2.7.0? It has optimized version of `com.google.protobuf.CodedOutputStream#computeStringSizeNoTag` method, we wanna use it in our production
