### ISSUE TITLE
protobuf/js/README.md faulty API Documentation

### ISSUE THREAD

**Issue by sheffatguidance** [google/protobuf#1869]
_Migrated from [https://github.com/google/protobuf/commit/24c5424be5b220d8d4575e4262ee5d6ad9417959#comments](https://github.com/google/protobuf/commit/24c5424be5b220d8d4575e4262ee5d6ad9417959#comments), per @xfxyjwf's request._

The example code under the "API" heading of the JS README indicates that `deserializeBinary` can be called directly on a Message variable; this does not appear to be the case.  After some digging in the test code (which thankfully was indicated in the README), I discovered that `deserializeBinary` was called more like this:

> `var msg = new proto.jspb.test.TestProto3();`
>
> `// Set some fields on msg...`
>
> `var serialized = msg.serializeBinary();`
> **`msg = proto.jspb.test.TestProto3.deserializeBinary(serialized);`**

Updating the README to reflect this --or updating the messages to behave as indicated in the current README-- might save some other users some trouble in the short-term, before the JS protobuf feature is ready and fully documented.

Apart from that hiccup, the alpha javascript release seems to be working very well!  Thanks so much to everyone involved in this project :smiley:

**Comment by haberman** [comment]
Good catch, please feel free to add this fix to your PR!

**Comment by haberman** [comment]
Merged attached PR.
