### ISSUE TITLE
descriptor initialization failure

### ISSUE THREAD

**Issue by longoj** [google/protobuf#1870]
While checking the proto syntax version, has_syntax should be called to avoid descriptor loading failures.

Proposal:  please change the following line in descriptor.cc in function DescriptorBuilder::BuildFileImpl

  if (proto.syntax().empty() || proto.syntax() == "proto2") {

TO

  if (!proto.has_syntax() || proto.syntax().empty() || proto.syntax() == "proto2") {

**Comment by xfxyjwf** [comment]
What's the descriptor loading failure?

**Comment by longoj** [comment]
Sorry for the poor title and lack of description.  The descriptors for protos are maintained in the descriptor pool.  When functions that deal with dynamic lookups are used, the pool is referenced.  During the process of retrieving the descriptor, it sometimes fails because the syntax field is referenced but has not been initialized.

**Comment by xfxyjwf** [comment]
I don't think a missing syntax filed can cause retrieving descriptors from DescriptorPool to fail. can you provide more context? Any example code that can reproduce this problem?

**Comment by longoj** [comment]
The issue isn't that the syntax field is missing.  The issue is that `has_XXXX() `must be called to check if the field has been set.

The following code would produce similar unpredictable behavior (which is occurring in the line of code in the above post).

_example proto definition:_

```
message MyProto
{
	string field1 = 1;
	string field2 = 2;
}

```
_example unpredictable c++ code:_

```
MyProto p;

if (p.field1() == "TEST")
   // do something
else
   // do something else

```

The syntax field of FileDescriptorProto (specifically FileDescriptorProto::syntax) is a string and is created with an underlying uninitialized pointer.

This can be fixed in at least two ways:

1) use `has_XXXXX()` before accessing string fields (such as in DescriptorBuilder::BuildFileImpl)
2) change the implementation of string getters so they handle the uninitialized case

**Comment by longoj** [comment]
oops, closed it by accident.

**Comment by xfxyjwf** [comment]
In your example, p.field1() should always return a valid string reference. If it doesn't, that's a bug in protobuf implementation. The expected behavior is documented in our developer guide:
https://developers.google.com/protocol-buffers/docs/reference/cpp-generated#string
```
const string& foo() const: Returns the current value of the field. If the field is not set, returns the default value.
```

It will be great if you can give an example to reproduce the initialization error you saw.

**Comment by longoj** [comment]
Yes, then there may be a bug in the protobuf implementation.  This causes the issue I described and would cause other undesirable behavior.  If the resulting string is valid then there would be no issue with the initialization.

An example that reproduces the initialization issue is as follows (however, this will only occur intermittently due to the string issue.  In my case, there was a valid string in memory but it is technically garbage so it didn't fault, but it throws a FatalException because it doesn't match the proto version 2 or 3 string.  _And, in the face of a possible string bug, this can happen anytime the proto is specified without specifying the proto syntax version in the proto file_).

_proto definition_

```
enum Colors
{
  BLUE = 1;
  GREEN = 2;
  YELLOW = 3;
}

message MyProto
{
    string field1 = 1;
    string field2 = 2;
}
```

_test case:_

```
void print_color(Colors color)
{
   // _Colors_Name intermittently throws a FatalException
   std::string color_name = _Colors_Name(color);
   std::cout << color_name << std::endl;
}

```

**Comment by longoj** [comment]
After digging deeper, I found the source of my initialization problems.  String initialization is functioning fine (**not a bug**) except in cases involving static initialization attributed to protobuf library internals.

The first issue is with messages containing strings defined with default values.  For example:

_proto definition_
```
message Foo
{
   string field1 = 1 [default = "TEST"];
}
```

_example code_

```
Foo f;

int main()
{
  // field1 ??might?? be initialized with the default (this might could core dump)
  if (f.field1() == "something")
     ... do something ...
}
```
Depending on the order in which static initialization occurs, the default will be set only if protobuf_AddDesc_XXXXXXX has been invoked before f's constructor is invoked.

The second issue is similar (and, is the root cause of the issue in my first post); due to static initialization ordering, it is possible for a proto's constructor to be called before other "essential" library statics that effect strings (for protos defined with or without a default definition).  This occurred in my case when using proto's in shared libraries that are dynamically loaded.  I have yet to identified the exact sequence.  I will provide more information if inclined to continue researching it (since I now know how to avoid it, I may stop here).

I hope this is helpful to others.

**Comment by xfxyjwf** [comment]
I am not sure about the shared library case, but if protobuf library is static linked, your example should work regardless of the initialization order. Protobuf code has been tweaked carefully for that use case and a lot of code inside Google actually depends on that.

If you are using protobuf in dynamically loaded libraries, things will get more complicated and it's usually hard to get it working as far as I know.

**Comment by longoj** [comment]
In the example I provided, the protobuf library is statically linked into a simple app as written.  It fails under VC++.  I haven't tested it with gcc or clang yet.
