### ISSUE TITLE
[CSharp][3.0.0-beta4] CodedInputStream.ReadBytes throws when backed by IO.Stream

### ISSUE THREAD

**Issue by amineben89** [google/protobuf#1879]
Hi, 

I am using protocol buffer with a bytes field. on the C# side, my interfaces accept a System.IO.Stream as an argument. When trying to construct the message, I wrap the IO.Stream into a CodedInputStream then call ReadBytes() to set the bytes field. 
The problem is that ReadBytes throws when I do that (exception below)

**Repro steps:**

            using (var stream = File.OpenRead(@"PathToAttachedFile"))
            using(var protoStream = new CodedInputStream(stream))
            {
                var bytes = protoStream.ReadBytes();
                Console.WriteLine(bytes.Length);
            }

[File to use for the repro](https://github.com/google/protobuf/files/389674/data.txt)

**Exception:**
An unhandled exception of type 'Google.Protobuf.InvalidProtocolBufferException' occurred in Google.Protobuf.dll

Additional information: While parsing a protocol message, the input ended unexpectedly in the middle of a field.  This could mean either than the input has been truncated or that an embedded message misreported its own length.

**Suggestion:**
bytes is mapped to a ByteString in the c# generated message. Please add a method CopyFromStream that accepts System.IO.Stream to avoid copying the data twice (Stream to bytes[] then bytes[] to ByteString)

Regards,
Amine

**Comment by jskeet** [comment]
It's not clear why you're calling `ReadBytes` here. How did you write the file?

If you're just trying to read the whole of the file as a `byte[]`, that's not something protobuf would normally get involved in. `CodedInputStream.ReadBytes` expects the stream to be positioned at the start of a `bytes` value written out with a length prefix.

It's not clear how this relates to your suggestion, either. Please provide more detail about what you're actually trying to achieve, as it doesn't sound like your file actually contains a protobuf message...

**Comment by amineben89** [comment]
Hi jskeet, 

I have a protobuf message with a bytes field (and other fields). 

`message SomeMessage {
    bytes rawImg;
}`

The intent is to send raw bytes as part of this message. (a small image in my case) 

bytes gets translated to ByteString in C#, thus I need to go from System.IO.Stream to a ByteString in order to be able to construct the message. 
Wrapping my image stream in a CodedInputStream was a workaround I tried in order to create a ByteString from a System.IO.Stream without copying the data twice (Stream -> byte[] then byte[] -> ByteString). 

The exception is probably expected as the stream contains an arbitrary byte sequence. Should I create a new Issue for requesting the ability to create ByteString from a System.IO.Stream ? There is already a WriteTo(Stream outputStream), it would be nice to have ReadFrom(Stream inputStream).

Regards,
Amine.

**Comment by jskeet** [comment]
It's unlikely that a `ByteString.ReadBytes` would be able to read from a stream without multiple copies either - given that the length of the stream isn't generally known beforehand, we don't know how big to create the byte array. It would save one final copy, but that's all.

Personally I don't think this is a sufficiently common use-case (or significant benefit) to make it worth adding to the API, but maybe it would be worth filing the issue and seeing whether others think. (And then probably closing this issue, as the exception you're getting in the original code is expected.)
