### ISSUE TITLE
Missing binary suffix (.exe) on win32 build

### ISSUE THREAD

**Issue by ericzhill** [google/protobuf#1881]
The win32 build zip file includes the protoc executable, but is missing the .exe suffix on the filename so is not directly executable on Windows.

https://github.com/google/protobuf/releases/download/v3.0.0/protoc-3.0.0-win32.zip

protoc should be renamed to protoc.exe

**Comment by pherl** [comment]
Thanks for reporting. Updated the release page and fixed the related script.
