### ISSUE TITLE
Allow for an ordered variant of `map<K,V>`

### ISSUE THREAD

**Issue by jkbbwr** [google/protobuf#1883]
There is a use case for having an ordered map, as maps are expressed as repeated key value pairs, is there any pain in adding a flag or option to enforce ordering on the map structure.

**Comment by xfxyjwf** [comment]
From what I know, there isn't a plan to add support for ordered map types. We are adding a deterministic serialization API that will serialize map fields ordered by key though.

**Comment by xfxyjwf** [comment]
What's your use case of ordered maps?

**Comment by jkbbwr** [comment]
Cryptographic signatures and hashes of identical messages. Realistically I would want insertion order which shouldn't be hard to expose from what I understand. It could just be an extended kvp type with an order number. Then if an order number is there use say LinkedHashMap

**Comment by jkbbwr** [comment]
@xfxyjwf Any ideas?

**Comment by xfxyjwf** [comment]
We are discussing whether to support ordered maps internally inside Google. There isn't a consensus on it though. I believe it's unlikely to be supported in the near future. As to LinkedHashMap, it's language specific and we are actually trying to go the opposite side: randomize hash keys to ensure user are not relying on a specific map ordering.

**Comment by jkbbwr** [comment]
This seems counter intuitive considering `repeated` is ordered, along with fields. This means that nearly all of protobuf is easily hashable and signable except for map fields. Is there really no way that an ordering field could be added without disrupting the existing API?

**Comment by xfxyjwf** [comment]
We are adding a deterministic serialization API that will serialize map fields ordered. I think you can   hash the deterministic serialization output rather than iterating over map fields yourself. Does that sound like a workable solution to you?

**Comment by jkbbwr** [comment]
Yes, that is a perfect solution so long as there is some control over the ordering itself. Either by some key ordering, or by insertion order. (We prefer to have insertion order specifically), does this mean the serialised format is guaranteed on the wire and the format is good?

How long on the road map is this feature? This is critical for our product.

**Comment by xfxyjwf** [comment]
It's guaranteed to serialize map fields ordered.

The API is already available in C++:
https://github.com/google/protobuf/blob/master/src/google/protobuf/io/coded_stream.h#L840

and @pherl is working on adding it to Java.

**Comment by jkbbwr** [comment]
https://github.com/google/protobuf/blob/master/src/google/protobuf/io/coded_stream.h#L831

Does this mean numerical provides insertion order?

Our map looks as following 

```
"1JxgSknwdUvrZgASNi6197f6JpAtZcdHX8" : google.protobuf.Any
```

**Comment by pherl** [comment]
The deterministic serialization only guarantees that the order is stable in multiple instance of the same binary. If you need customized ordering, I'd suggest have a custom sorter instead.
