### ISSUE TITLE
`jspb.Map` not exported

### ISSUE THREAD

**Issue by Triztian** [google/protobuf#1885]
The `jspb.Map` object is not exported in the case of CommonJS modules. Should it be added: after here: https://github.com/google/protobuf/blob/master/js/commonjs/export.js#L13

**Comment by haberman** [comment]
Why does the Map symbol need to be available to clients? It's not intended to be constructed by generated code or user code. It's only constructed inside `jspb.Message.getMapField()`.

**Comment by Triztian** [comment]
It is called when trying to access map fields of any generated proto buf and even if `google-protobuf` package is added as a dependency of the npm project that hosts the generated protos the `getMapField` function is undefined.

**Comment by haberman** [comment]
Can you paste the error that you are getting?

**Comment by gegles** [comment]
I concur with @Triztian a 100%. I was having the same issue (when serializing/deserializing a message including a map<string, string>).

Here is the error I was getting (deserializing):

Cannot read property 'deserializeBinary' of undefined

The location of the error is this line:

jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readString);

After adding the following to export.js:

```javascript
goog.require('jspb.Map');
exports.Map = jspb.Map;
```

Everything works fine.

Thanks for fixing this.

PS: I could submit the patch, but I am not knowledgeable enough to know whether it is the best way to solve this problem.

**Comment by haberman** [comment]
Did the error have a stack trace? Or do you have a way to reproduce this?

I want to understand the error better so I can know the best way to fix it.

**Comment by gegles** [comment]
It did, but it is all from within the generated pb code which defines my messages. Here is the relevant block:

```javascript
	proto.aspera.art.ResponseMessage.deserializeBinaryFromReader = function(msg, reader) {
	  while (reader.nextField()) {
	    if (reader.isEndGroup()) {
	      break;
	    }
	    var field = reader.getFieldNumber();
	    switch (field) {
	    case 1:
	      var value = /** @type {number} */ (reader.readUint32());
	      msg.setStatusCode(value);
	      break;
	    case 2:
	      var value = msg.getHeadersMap();
	      reader.readMessage(value, function(message, reader) {
	        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readString);
	         });
	      break;
	    default:
	      reader.skipField();
	      break;
	    }
	  }
	  return msg;
	};
```

I am using commonjs imports (I code in es6 actually).

**Comment by haberman** [comment]
That's what I needed, thanks! I agree this is the right fix. Feel free to send a PR with this change.

I wonder if the tests don't exercise this code path. We should make sure the tests attempt to deserialize a message containing a map.
