### ISSUE TITLE
What is the meaning of std::pair::second returned in ReadTagWithCutoff?

### ISSUE THREAD

**Issue by KevinLucidyne** [google/protobuf#1897]
I am trying to debug an issue where data appears to be corrupted or interrupted while being passed through the message queue.  One possible area where this is occurring is in the generated function Datum::MergePartialFromCodedStream which calls ReadTagWithCutoff(127).

What is the meaning of std::pair::second returned in ReadTagWithCutoff?

**Comment by xfxyjwf** [comment]
```
  // This usually a faster alternative to ReadTag() when cutoff is a manifest
  // constant.  It does particularly well for cutoff >= 127.  The first part
  // of the return value is the tag that was read, though it can also be 0 in
  // the cases where ReadTag() would return 0.  If the second part is true
  // then the tag is known to be in [0, cutoff].  If not, the tag either is
  // above cutoff or is 0.  (There's intentional wiggle room when tag is 0,
  // because that can arise in several ways, and for best performance we want
  // to avoid an extra "is tag == 0?" check here.)
```
Is this comment clear enough?

**Comment by KevinLucidyne** [comment]
What does it mean logically when the tag is above cutoff or is 0?

**Comment by xfxyjwf** [comment]
ReadTagWithCutoff() is simply an optimized version of ReadTag(). It has an additional cutoff parameter to help predict the range of the tag value.
