### ISSUE TITLE
Building with cmake error. Not found 'repeated_field_reflection.h'

### ISSUE THREAD

**Issue by fregate** [google/protobuf#1899]
This file used in cmake/extract_includes.bat.in
https://github.com/google/protobuf/blob/master/cmake/extract_includes.bat.in#L72
If remove this line - no more errors.

**Comment by podsvirov** [comment]
Helllo @fregate,
good catch!

This bug since 16adea3ddc4e775aac230c4326aeb686c26620dc by @xfxyjwf.

Hello @xfxyjwf,
can we simple remove this file from list of exported headers?

**Comment by xfxyjwf** [comment]
Yes, feel free to send me a PR to remove that.

**Comment by podsvirov** [comment]
Hi @xfxyjwf,
please review PR #1902 to fix this issue.

**Comment by podsvirov** [comment]
Hello @xfxyjwf,
in my opinion, now we can close this issue.

**Comment by xfxyjwf** [comment]
Yes, thanks for fixing the issue!
