### ISSUE TITLE
Proposal: Divide ProtoBuf into a formal specification, and the separate language implementations

### ISSUE THREAD

**Issue by protobufel** [google/protobuf#19]
I think it is long overdue to have the separate 
1. the formal ProtoBuf specification, including the grammar, the serialization spec, the formal language independent API definitions, and the TCK;
2. the separate concrete language  implementations based on the above, with their own maintenance and release schedule.
3. (optional, and desired) language specific ProtoBuf generators, at least for Java, in addition to the existing protoc.

This would leverage the language specific tools, libraries, and domains, allowing for better, easier, and faster maintenance and evolution.

In addition, regarding Java, it is time to get rid of Java 5, and, maybe, Java 6 support, making a really portable Maven project, with modern tests, and the updated source.

It is very easy to do - the separation could be done within hours! The benefits, IMHO, are huge.

Cheers,
David

**Comment by xfxyjwf** [comment]
FYI. It has been decided protobuf implementations will live in this same repo. We don't have plans to separate the implementations for the time being.
