### ISSUE TITLE
protobuf-3.0.0-beta-4_install//include/google/protobuf/map.h:1285:32: error: enumeral and non-enumeral type in conditional expression [-Werror]        return n < kMinTableSize ? kMinTableSize : n;

### ISSUE THREAD

**Issue by ohaddahan** [google/protobuf#1900]
I'm getting the following error message.

> protobuf-3.0.0-beta-4_install//include/google/protobuf/map.h:1285:32: error: enumeral and non-enumeral type in conditional expression [-Werror]
       return n < kMinTableSize ? kMinTableSize : n;

Any known fix?

**Comment by ohaddahan** [comment]
Trying to use the suggested workaround from:
[http://stackoverflow.com/questions/1018208/how-to-suppress-the-enumeral-and-non-enumeral-type-in-conditional-expression-w](url)

`#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wno-enum-compare" 
// Code that causes warning goes here
#pragma GCC diagnostic pop`

This didn't help , I'm getting:

> protobuf-3.0.0-beta-4_install//include/google/protobuf/map.h:34:32: error: unknown option after \u2018#pragma GCC diagnostic\u2019 kind [-Werror=pragmas]
 #pragma GCC diagnostic ignored "-Wno-enum-compare"
                                ^
> cc1plus:  all warnings being treated as errors


I'm using GCC 4.8.3.

**Comment by ohaddahan** [comment]
Another update , I updated the code to:
`    size_type TableSize(size_type n) {
      #pragma GCC diagnostic push
      #pragma GCC diagnostic ignored "-Wenum-compare" 
      return n < kMinTableSize ? kMinTableSize : n;
      #pragma GCC diagnostic pop
    }`

Following the suggestion from [https://codeyarns.com/2014/03/11/how-to-selectively-ignore-a-gcc-warning/](url) .

I think this resolves the issue , I'm having other issues now that fail my compilation that seems unrelated.

**Comment by xfxyjwf** [comment]
I think static_cast the enums to ints should work?

**Comment by ohaddahan** [comment]
Sorry for the delay , had -fPIC related issues.
`return n < (int) kMinTableSize ? (int) kMinTableSize : n;`

Fixes it.
