### ISSUE TITLE
enum not preserved and unknown values are always 0 proto3 javanano enum

### ISSUE THREAD

**Issue by suau** [google/protobuf#1901]
I'm using proto3 with javanano.
deserialising an unknown enum is always interpreted as 0 and the unknown value is not retrievable.
Unknown enum values are also not preserved when deserialised and serialised again.

This behaviour seems out of line with the language guide
https://developers.google.com/protocol-buffers/docs/proto3#enum

**Comment by TeBoring** [comment]
Javanano is not supported.
