### ISSUE TITLE
When will the 3.0.0-GA Google.Protobuf NuGet package be published?

### ISSUE THREAD

**Issue by jhickson** [google/protobuf#1906]
Hi,

As the subject says, is there any indication of when we'll be able to access 3.0.0-GA from NuGet.org?  As far as I can tell the latest version there is still 3.0.0-beta4.

Regards,

Jos

**Comment by xfxyjwf** [comment]
@jskeet @jtattermusch

**Comment by jskeet** [comment]
I'm afraid I'm on vacation at the moment, and not in a position to do the release.

**Comment by jhickson** [comment]
Is anybody else able to do it?

**Comment by apolcyn** [comment]
I've released these today. They are on nuget.org at https://www.nuget.org/packages/Google.Protobuf/ and https://www.nuget.org/packages/Google.Protobuf.Tools/.

If there are any issues, please let me know
