### ISSUE TITLE
When will ChromeCast start using proto3?

### ISSUE THREAD

**Issue by wind-rider** [google/protobuf#1916]
Out of interest - with the first stable release of libraries for protobuf 3.0 out of the door - when will ChromeCast start using it?

Since ChromeCast is one of the well-known users of the protobuf v2 protocol and I assume there are plenty Google developers in this repo, I thought I might ask here.

**Comment by xfxyjwf** [comment]
We recommend new users to use proto3 syntax, but for existing proto2 users migrating to proto3 may not be worth-while (v3.0.0 release supports both proto2 syntax and proto3 syntax). I don't know much about ChromeCast but I guess it might stay with proto2 for quite a while.

**Comment by wind-rider** [comment]
Ok. I also asked because Google's Protobuf NuGet packages (for c#) do not support proto2..
