### ISSUE TITLE
Protocol Buffers v3.0.0 doesn't compile with -fPIC

### ISSUE THREAD

**Issue by brockgibson** [google/protobuf#1919]
I built and installed protobuf v3.0.0 release (static libraries, protoc, include) using cmake.

I then cloned the grpc c++ source from branch 0.15.0. When building, I get a linker error for libgrpc++_reflection.so against the 3.0.0 static protobuf libs indicating -fPIC must be specified for them.

I added the following line to the CMakeLists.txt for the protobuf v3.0.0 source and re-generated the makefile and rebuilt. 

set(CMAKE_POSITION_INDEPENDENT_CODE ON)

This resolves the grpc link issue.

Running Ubuntu 16.04.

**Comment by ohaddahan** [comment]
Did you try configuring with `./configure "CFLAGS=-fPIC" "CXXFLAGS=-fPIC"` ?

**Comment by brockgibson** [comment]
I may have been off the ranch a bit in using cmake on Ubuntu (rather than following src/README), but would the ./configure above help in that regard? It definitely works for the standard make approach.

Maybe just a note in the protobuf or grpc README noting something like the configure options you mentioned above?

**Comment by ohaddahan** [comment]
I didn't understand , did you try without `set(CMAKE_POSITION_INDEPENDENT_CODE ON)` and with `"CFLAGS=-fPIC" "CXXFLAGS=-fPIC"  ` and it worked for you?
I'm not a part of the protobuf team , just stumbled upon this issue very recently myself :)

**Comment by brockgibson** [comment]
Ah, I gotcha. :)

I ran the configure command you suggested and validated the resultant Makefile contained the -fPIC options (it previously didn't), though I didn't go all the way through rebuilding and validating the gRPC C++ plugin. Thanks for the tip...

Previously I had been working through the CMakeLists.txt file, which is where I used `set(CMAKE_POSITION_INDEPENDENT_CODE ON)`.

**Comment by xfxyjwf** [comment]
For cmake build, I think you can also pass it as a command line flag:
```bash
$ cmake -DCMAKE_POSITION_INDEPENDENT_CODE=ON ...
```

**Comment by anandolee** [comment]
Closing it for clean up. Feel free to reopen if it is still an issue
