### ISSUE TITLE
protobuf-3.0.0.jar include *.proto? 

### ISSUE THREAD

**Issue by wu-sheng** [google/protobuf#1921]
We use protobuf-3.0.0 in our project. We find some strange *.proto files in proto-java-3.0.0.jar。
such as:
* any.proto
* api.proto
* duration.proto
……

Are these files nessesary in jar? I have already find Any.class, Api.class, Duration.class in package "com.google.protobuf". I think it's enough for runtime when have these classes.

Is this a bug?

**Comment by xfxyjwf** [comment]
They are put there intentionally for convenience, especially for gradle and maven users who pull all dependencies from maven central and may not be able to obtain these .proto files from the git repo. If you are not using the gradle protoc plugin, you probably already have these .proto files when you build protoc or download the protoc binary from our release page. In that case, the included copy in the jar file is of no use to you. It doesn't cause any problems either I believe?

**Comment by xfxyjwf** [comment]
And these strange .proto files are the well-known types:
https://developers.google.com/protocol-buffers/docs/reference/google.protobuf

They are a set of common proto definitions that you can import and use in your own .proto files. For example, when you need a field to represent a timestamp, you can use the Timestamp type:
https://developers.google.com/protocol-buffers/docs/reference/google.protobuf#google.protobuf.Timestamp

**Comment by wu-sheng** [comment]
My project will run as javaagent. In order to avoid class conflict, I will change all class names. 
I must decide to delete or change these proto files, before my release.

**Comment by xfxyjwf** [comment]
These .proto files are not referenced by the runtime. You can safely delete them.

**Comment by wu-sheng** [comment]
Ok, thanks.

**Comment by zloyreznic** [comment]
jar {
    exclude("*.proto")
}
