### ISSUE TITLE
Need to increase kDefaultTotalBytesLimit to support 256MB protobuf message

### ISSUE THREAD

**Issue by SimonElfvingElekta** [google/protobuf#1927]
Change  file coded_stream.h 

Change line 
static const int kDefaultTotalBytesLimit = 64 << 20;  // 64MB
to 
static const int kDefaultTotalBytesLimit = 256 << 20;  //256MB

**Comment by xfxyjwf** [comment]
The limit has been removed (increased to INT32_MAX) from recent releases.
