### ISSUE TITLE
why string field with number 3 cannot ParseFromIstream

### ISSUE THREAD

**Issue by yaohairong** [google/protobuf#1932]
eg proto file
person.proto
syntax = "proto3";
message Person{
    string name = 3;
}

c++ code
    Person person;
    person.set_name("yaohairong");
    ofstream ofs("person.data");
    person.SerializeToOstream(&ofs);
    cout << person.name()<<endl;
    ofs.close();
    ifstream ifs("person.data");
    Person person2;
    person2.ParseFromIstream(&ifs);
    cout << person2.name() << endl;

above cannot cannot get ouput
but change "string name = 3;" can output "yaohairong"?

**Comment by xfxyjwf** [comment]
Can you try:
```cpp
string data = person.SerializeAsString();
person2.ParseFromString(data);
```
?

**Comment by Zhouxing-Su** [comment]
I have reproduced the bug and post a new issue with more details at https://github.com/google/protobuf/issues/3845
