### ISSUE TITLE
Build failure using VS2008 (v3.0.0)

### ISSUE THREAD

**Issue by jbfiot** [google/protobuf#1935]
Hi, 

I generated a VS2008 solution file using

```
cmake -G "Visual Studio 9 2008 Win64" ^
-DCMAKE_INSTALL_PREFIX=../../../../install ^
../.. -Dprotobuf_BUILD_TESTS=OFF
```

Then the build of the generated solution `protobuf.sln` fails with C3861 errors ([full build log](https://github.com/google/protobuf/files/409236/build.txt)). 

Log extract:

```
1>C:\Users\user\software\protobuf\src\google/protobuf/stubs/mathlimits.h(268) : error C3861: 'isinf': identifier not found
1>C:\Users\user\software\protobuf\src\google/protobuf/stubs/mathlimits.h(268) : error C3861: 'isnan': identifier not found
```

Additional info:
- MS VS2008: v9.0.30729.1 SP
- MS .NET Framework: v3.5 SP1
- The build was launched via VS2008 IDE (Build > Build solution)

Would you have any idea on how to solve this problem?

Thanks

**Comment by xfxyjwf** [comment]
Can you try to change WIN32 on line 224 to _WIN32?
https://github.com/google/protobuf/blob/master/src/google/protobuf/stubs/mathlimits.h#L224

**Comment by jbfiot** [comment]
Thanks for the answer. 

With the proposed modification
* `libprotobuf-lite` and `libprotoc` builds are now successful,
* `libprotobuf` build still fails though it goes from 109 errors to a single one,
* `protoc` build fails because it cannot link `libprotobuf`.

[Full build log](https://github.com/google/protobuf/files/410557/build.test._WIN32.txt).

**Comment by gerben-s** [comment]
seems like a link path error
