### ISSUE TITLE
Proto3 PHP support

### ISSUE THREAD

**Issue by xfxyjwf** [google/protobuf#1936]

**Comment by mcos** [comment]
Hi @TeBoring or @xfxyjwf - would either of you have an approximate timeframe for when we might see PHP support released in v3.1.0? 

My project is using `proto3` as well as `grpc`, using the https://github.com/stanley-cheung/Protobuf-PHP fork, but we're eager to be able to access support for the well-known types (specifically `timestamp.proto`) in `proto3`. Any guidance or workarounds here would be very much appreciated. Thanks.

**Comment by TeBoring** [comment]
Hi @mcos, well-known types will not be supported in our initial release. However, we still generate code for these well-known types messages. For now, you can access them just like normal messages.

**Comment by TeBoring** [comment]
3.3.0 released.
