### ISSUE TITLE
descriptor_database.cc:57] File already exists in database: EntityType.proto

### ISSUE THREAD

**Issue by chiisama** [google/protobuf#1941]
I'm using protobuf-3.0.0.-beta3 but on execute my executable I get descriptor_database.cc:57] File already exists in database: EntityType.proto

shared lib A used in executable B
both use protobuffer as shared lib

exe and shared lib A generate the same EntityType.proto object (from same file)

Seems here is discussed the same problem for linux (and an older version of proto) but i use vs2015.
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=721791

Maybe the patch from nobuhiro helps here. Not tested but seems to fix adding an already existing object.

https://bugs.debian.org/cgi-bin/bugreport.cgi?att=1;bug=721791;filename=protobuf-2.4.1-3.1.debdiff;msg=5

**Comment by xfxyjwf** [comment]
If A and B shares the same proto type, I believe you will need to make a separate shared lib C containing the shared proto and make it a dependency of A and B.

**Comment by clementruhm** [comment]
god bless nobuhiro. other suggestions about linkage are useless when it comes to pybind

**Comment by yurivict** [comment]
I am still getting the same failure from protobuf-24.4 used by PyTorch during the PyTorch initialization of onnx.
