### ISSUE TITLE
C# fails some of the proto3 oneof conformance tests (JSON and Binary)

### ISSUE THREAD

**Issue by thomasvl** [google/protobuf#1943]
https://github.com/google/protobuf/blob/master/conformance/failure_list_csharp.txt#L8-L27

JsonInput.OneofZeroBool.JsonOutput
JsonInput.OneofZeroBool.ProtobufOutput
JsonInput.OneofZeroDouble.JsonOutput
JsonInput.OneofZeroDouble.ProtobufOutput
JsonInput.OneofZeroEnum.JsonOutput
JsonInput.OneofZeroEnum.ProtobufOutput
JsonInput.OneofZeroFloat.JsonOutput
JsonInput.OneofZeroFloat.ProtobufOutput
JsonInput.OneofZeroUint64.JsonOutput
JsonInput.OneofZeroUint64.ProtobufOutput
ProtobufInput.OneofZeroBool.JsonOutput
ProtobufInput.OneofZeroBool.ProtobufOutput
ProtobufInput.OneofZeroDouble.JsonOutput
ProtobufInput.OneofZeroDouble.ProtobufOutput
ProtobufInput.OneofZeroEnum.JsonOutput
ProtobufInput.OneofZeroEnum.ProtobufOutput
ProtobufInput.OneofZeroFloat.JsonOutput
ProtobufInput.OneofZeroFloat.ProtobufOutput
ProtobufInput.OneofZeroUint64.JsonOutput
ProtobufInput.OneofZeroUint64.ProtobufOutput

**Comment by jskeet** [comment]
Will try to take a look at these this week - generally surprising though, as I thought our oneof behaviour was pretty thorough...

**Comment by jskeet** [comment]
Ah - the PR which changed the .proto file didn't regenerate the C# code, so those fields aren't present.
Will create a PR which just adds those to the generated code (which is checked into github, unusually I realise) and see if that makes the failures go away (as I expect it will).

**Comment by thomasvl** [comment]
So C# doesn't generate from the proto during the build like all the other languages do?

**Comment by jskeet** [comment]
Nope - it could do so before running the tests, but we'd want to flag up that what's in github is out of date.

We should really do this for the conformance tests, the descriptor protos and the AddressBook sample - I did investigate it a while ago, but didn't get terribly far. We have #1212 tracking this - I'll add conformance to that.

**Comment by thomasvl** [comment]
FYI - I updated objc a while ago to have a [`--check-only`](https://github.com/google/protobuf/blob/master/objectivec/generate_well_known_types.sh#L17) argument for this.  So the travis builds fail now for us (the check flag gets passed there).  You might be able to copy the logic/flow from there.  The conformance ones are just [generated](https://github.com/google/protobuf/blob/master/conformance/Makefile.am#L204) during the build.

**Comment by jskeet** [comment]
@thomasvl: Thanks - will have a look at that later in the week, with any luck.
