### ISSUE TITLE
Python fails some of the proto3 oneof conformance tests (JSON)

### ISSUE THREAD

**Issue by thomasvl** [google/protobuf#1944]
https://github.com/google/protobuf/blob/master/conformance/failure_list_python.txt#L38-L39

JsonInput.OneofZeroMessage.JsonOutput
JsonInput.OneofZeroMessage.ProtobufOutput

**Comment by haberman** [comment]
I just checked and these tests don't appear to be failing any more for Python (they aren't in the failure lists). Some other tests are failing, but we don't generally keep issues open for conformance test failures. If we wanted to start doing this, we should be more systematic about it.
