### ISSUE TITLE
Excess copies in CodedInputStream 

### ISSUE THREAD

**Issue by carl-mastrangelo** [google/protobuf#1956]
While running some benchmarks that involve deserializing large protobuf messages.  I noticed a large amount of garbage created by CodedInputStream as well as CPU time spent in it.  Specifically, when data is coming from a ByteBuffer that is known to be immutable,  CodedInputStream still makes a copy.  

For my benchmarks, I am using a simple proto with a single bytes field, set to a size of one megabyte, and sent over the network repeatedly.  The other endpoint reads the entire message off the wire before passing it to CIS.  The two available constructors are newInstance(ByteBuffer), and newInstance(InputStream)  Because I read the data off the network in chunks, I currently have a collection of ByteBuffers that need to be passed in to CIS, The only way currently to do this is to make an InputStream that composites these buffers together.   Sadly, this makes CIS use a code path called `readRawBytesSlowPath`, which makes a lot of defensive copies I don't need.  This is a major source of garbage and slowness.

An alternative approach is for myself to copy all the ByteBuffers into a single ByteBuffer, and pass that into CIS.newInstance.  This factory method _also_ makes a full copy of the buffer before parsing it.  

Going even further down the danger path is class called UnsafeByteOperations, which seems to be able to call the package-private constructors of CIS, but to use it, I have to collapse all my buffers into one before using it.  Even if there is only a single buffer, the buffers I get from the network are direct byte buffers, so to parse them it always incurs a copy.

What would be ideal is if there was a constructor that accepted a List / array of ByteBuffers.  My own benchmarking shows about 50% speed up (320MB/s to 480 MB/s)  in parsing using the Unsafe approach.  I believe it could be faster with even fewer copies.

Ideally, there needs to be a CodedInputStream that doesn't do its own buffering.  I believe it to be common case that Protos are used primarily across the network, which means that the networking libraries already have the data in a collection of ByteBuffers.

**Comment by jskeet** [comment]
Which implementation does this issue relate to? `CodedInputStream` exists in a number of different platforms.

**Comment by carl-mastrangelo** [comment]
@jskeet this happens with Java on x86_64.

**Comment by xfxyjwf** [comment]
@pherl

**Comment by carl-mastrangelo** [comment]
cc: @jayantkolhe

**Comment by BSBandme** [comment]
#3577
Should be done in v3.5.0
