### ISSUE TITLE
Unit test exe fail to link on MSVC VS2012 windows

### ISSUE THREAD

**Issue by koubaa** [google/protobuf#1962]
The static const definitions from 
https://github.com/google/protobuf/commit/a17367f44a3b592993d2ac5c074ed58fb0ce784c

in time_util.h & time_util.cc
const int64 TimeUtil::kTimestampMinSeconds;
const int64 TimeUtil::kTimestampMaxSeconds;
const int64 TimeUtil::kDurationMaxSeconds;
const int64 TimeUtil::kDurationMinSeconds;

are leading to this linker error:

libprotobuf.lib(time_util.cc.obj) : error LNK2005: "public: static __int64 const google::protobuf::util::TimeUtil::kTimestampMinSeconds" (?kTimestampMinSeconds@TimeUtil@util@protobuf@google@@2_JB) already defined in map_test.cc.obj
libprotobuf.lib(time_util.cc.obj) : error LNK2005: "public: static __int64 const google::protobuf::util::TimeUtil::kTimestampMaxSeconds" (?kTimestampMaxSeconds@TimeUtil@util@protobuf@google@@2_JB) already defined in map_test.cc.obj
libprotobuf.lib(time_util.cc.obj) : error LNK2005: "public: static __int64 const google::protobuf::util::TimeUtil::kDurationMinSeconds" (?kDurationMinSeconds@TimeUtil@util@protobuf@google@@2_JB) already defined in map_test.cc.obj
libprotobuf.lib(time_util.cc.obj) : error LNK2005: "public: static __int64 const google::protobuf::util::TimeUtil::kDurationMaxSeconds" (?kDurationMaxSeconds@TimeUtil@util@protobuf@google@@2_JB) already defined in map_test.cc.obj
tests.exe : fatal error LNK1169: one or more multiply defined symbols found
LINK failed. with 1169
NMAKE : fatal error U1077: '"F:\AnsysDev\NoBackup\Program Files\bin\cmake.exe"' : return code '0xffffffff'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 11.0\VC\BIN\amd64\nmake.exe"' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 11.0\VC\BIN\amd64\nmake.exe"' : return code '0x2'
Stop.

At first glance I thought it was a conflict with the constants that are in util/internal/constants.h

However, commenting out the above 4 lines in time_util.cc and the link succeeds.  It is probably a compiler bug with this specific version of MSVC

**Comment by xfxyjwf** [comment]
Surrounding the definitions in time_util.cc with "#ifdef _MSC_VER/#endif" should solve the problem, and yes it's a compiler bug in old MSVC versions. We are testing protobuf with Visual Studio 12.0 and it doesn't have the same issue.

**Comment by xfxyjwf** [comment]
This should be fixed in the recent releases.
