### ISSUE TITLE
Empty JSON Object lost when converted to protobuf message

### ISSUE THREAD

**Issue by robbarnes** [google/protobuf#1969]
Empty JSON objects are being treated the same as a null. Instead an empty JSON message should be turned into an empty but set message. i.e. { "messageValue" : {} } != {"messageValue":null}

Test:

```
assertTrue(json_format.Parse('{ "messageValue" : {} }',message).HasField('message_value'))

assertFalse(json_format.Parse('{ "messageValue" : null }',message).HasField('message_value'))

```

**Comment by xfxyjwf** [comment]
Which language are you using?

**Comment by robbarnes** [comment]
Python

**Comment by anandolee** [comment]
Fixed in internal and will be included in next release
