### ISSUE TITLE
Protobuf Javascript Increses the parsing time

### ISSUE THREAD

**Issue by xR3b0rn** [google/protobuf#1973]
Hey,
I am using the protbuf 3.0.0-alpha in conjunction with javascript. I compiled my protobuf-files with: protoc --js_out=library=name.js,binary:protos proto1.proto proto2.proto proto3.proto

After including the Javscriptfile name.js on my webpage, I figured out, that I have to include the clsoure library too, so I did.
But finally I am having the problem that the parsing times of the javascript files on my Webpage are enormous.
So are there some ways to minimize the javascript usage of protobuf?

Or am I doing something wrong? Cause it feels wrong to provide a 30mb js-library (closoure-library) in the file-tree of a webserver ^^ (I still haven't much experience)

The parsing times in my webbrowser are between 1 and 2 seconds, but my mobilephone still needs more than 5 seconds.

Regards

Julian

**Comment by hochhaus** [comment]
The recommended solution is to use closure-compiler to minify and dead-code-eliminate your source before running in prod.

**Comment by xR3b0rn** [comment]
Just wow, the output file has only 350kb.
Thank you.

**Comment by hochhaus** [comment]
If you didn't see it already, it might be worth checking out ADVANCED compilation mode to further reduce it.

**Comment by haberman** [comment]
It sounds like hochhaus's suggestion answered your question, thanks!
