### ISSUE TITLE
[feature request] Support options in the Objective C Descriptor API

### ISSUE THREAD

**Issue by thurn** [google/protobuf#1976]
Several of the protocol buffer Descriptor APIs expose options, e.g. in Java:

https://developers.google.com/protocol-buffers/docs/reference/java/com/google/protobuf/Descriptors.FieldDescriptor#getOptions()

It would be extremely useful if a similar method were present in the Objective C descriptor API in GPBDescriptor, GPBMessageDescriptor, etc.

**Comment by thomasvl** [comment]
This came up before in https://github.com/google/protobuf/issues/1779.  ObjC doesn't have the full descriptor, and most consumers don't need them, so capturing the data would end up just bloating the binary.  Given ObjC is mostly used for mobile, larger binaries is something we try to avoid.
