### ISSUE TITLE
how to use type Any in pb v3?

### ISSUE THREAD

**Issue by AlexStocks** [google/protobuf#198]
Changes.txt in pb v3 says ""Removal of extensions, which are instead replaced by a new standard type called Any.". However， I do not find any examples show how to use Any.  Can one of your members would be so kindy show me how to use it ?

**Comment by Gatherer** [comment]
Found this  ... posted by "Feng Xiao" in "Protobuf Buffers v3.0.0-alpha-1"

```
Sorry, but "Any" is not added in this alpha version. In proto3, "Any" will be a pre-defined message type. Its definition looks like this:
package google.protobuf;
message Any {
  string type_url = 1;
  bytes value = 2;
}
You could define such a message yourself and use it as a temporary solution. In the next alpha version we'll provide these types and utility functions to work with an Any message.
```

**Comment by AlexStocks** [comment]
thank you.
