### ISSUE TITLE
Support Deserializing Any in Go's jsonpb

### ISSUE THREAD

**Issue by gdbelvin** [google/protobuf#1980]
Conversion of Proto3's Any type between JSON and Proto is currently unimplemented.  When is implementation planned?
https://github.com/golang/protobuf/blob/master/jsonpb/jsonpb.go#L586

**Comment by xfxyjwf** [comment]
@gdbelvin Can you submit this issue to the golang/protobuf repo?

**Comment by gdbelvin** [comment]
https://github.com/golang/protobuf/issues/216
