### ISSUE TITLE
[feature request] Support setting values via field descriptors in the Objective C Descriptor API

### ISSUE THREAD

**Issue by thurn** [google/protobuf#1981]
The Java protocol buffers API allows clients to get and set field values using a Field Descriptor:

https://developers.google.com/protocol-buffers/docs/reference/java/com/google/protobuf/GeneratedMessage.Builder#setField(com.google.protobuf.Descriptors.FieldDescriptor,%20java.lang.Object)

https://developers.google.com/protocol-buffers/docs/reference/java/com/google/protobuf/GeneratedMessage#getField(com.google.protobuf.Descriptors.FieldDescriptor)

It would be extremely useful if this functionality were supported by the Objective C descriptor API. Here's a strawman API to demonstrate:

```objectivec
@interface GPBMessage : NSObject
- (nullable id)fieldValueForDescriptor:(GPBFieldDescriptor *)descriptor;
- (void)setFieldValue:(id)fieldValue forDescriptor:(GPBFieldDescriptor *)descriptor;
- (void)clearFieldForDescriptor:(GPBFieldDescriptor *)descriptor;
@end
```

**Comment by thomasvl** [comment]
See [GPBUtilities.h](https://github.com/google/protobuf/blob/master/objectivec/GPBUtilities.h)  These are all currently expose as C methods to keep the message surface a little smaller and to keep them some what out of the auto complete paths for the normal field access.
