### ISSUE TITLE
protobuf2.6.1 install on HP-UNIX fail

### ISSUE THREAD

**Issue by chen31450** [google/protobuf#1989]
i install protobuf2.6.1 on hp-unix, but fail. 
a lot of error, such as error : "GOOGLE_PROTOBUF_PLATFORM_ERROR not defined".

my machine is using aCC complier. Is't OK?

How install on hp-unix?

**Comment by xfxyjwf** [comment]
Can you try 3.0.0? We added more platform coverage after 2.6.1 and 3.0.0 might have a better chance to compile under hp-unix.
