### ISSUE TITLE
Java compile fails on Windows and MacOS but works on Linux

### ISSUE THREAD

**Issue by emmenlau** [google/protobuf#1990]
I can successfully compile protobuf C on Windows with MSYS2 (with gcc from MinGW64), on MacOS, and on Linux. I can also compile protobuf Java on Linux. But on Windows and MacOS, I fail to compile protobuf Java. The error is on both platforms:
```
main:
     [echo] Running protoc ...
    [mkdir] Created dir: /data/emmenlau/BioDataAnalysis/screeningBee-MacOS-x86_64-gcc4.2.1-tmp/LightBIS/thirdparty/protobuf-3.0.0/java/core/target/generated-sources
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Protocol Buffers [Parent] .......................... SUCCESS [  0.295 s]
[INFO] Protocol Buffers [Core] ............................ FAILURE [  2.073 s]
[INFO] Protocol Buffers [Util] ............................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 5.139 s
[INFO] Finished at: 2016-08-22T13:25:20+02:00
[INFO] Final Memory: 11M/156M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:1.8:run (generate-sources) on project protobuf-java: An Ant BuildException has occured: The following error occurred while executing this line:
[ERROR] /data/emmenlau/BioDataAnalysis/screeningBee-MacOS-x86_64-gcc4.2.1-tmp/LightBIS/thirdparty/protobuf-3.0.0/java/core/generate-sources-build.xml:4: Execute failed: java.io.IOException: Cannot run program "/data/emmenlau/BioDataAnalysis/screeningBee-MacOS-x86_64-gcc4.2.1-tmp/LightBIS/thirdparty/protobuf-3.0.0/java/core/../../src/protoc" (in directory "/data/emmenlau/BioDataAnalysis/screeningBee-MacOS-x86_64-gcc4.2.1-tmp/LightBIS/thirdparty/protobuf-3.0.0/java/core"): error=2, No such file or directory
[ERROR] around Ant part ...<ant antfile="generate-sources-build.xml"/>... @ 4:46 in /data/emmenlau/BioDataAnalysis/screeningBee-MacOS-x86_64-gcc4.2.1-tmp/LightBIS/thirdparty/protobuf-3.0.0/java/core/target/antrun/build-main.xml
```
I can make the compile work by copying the previously built `protoc` from the root of the build directory to the src/ directory. So it looks like ant/maven are searching the wrong directory for `protoc`? I'm not an ant user and don't know how to fix the path. Or am I doing something wrong?

**Comment by xfxyjwf** [comment]
How did you build the protoc? Usually protoc will be in src/ directory and that's also the directory maven build is looking at. If you build the protoc somewhere else, copying it to src/ is the right solution.

**Comment by emmenlau** [comment]
I build protobuf C with cmake, in the root directory of the archive with
```
cmake ./cmake ...some-cmake-options...
make && make install
```
Everything gets build and installed correctly. Now I'm copying it also to src/ but maybe the cmake could do that?

**Comment by xfxyjwf** [comment]
The current build scripts for Java assume the protoc binary is built by auto-tools (which puts the protoc binary in src). Instead of making cmake copy protoc to src/, I think it's better if we make the error message more clear on what the Java build expects the protoc binary to be. In any case, copying the protoc to src/ is the right solution when you are using cmake or bazel to build protoc.

**Comment by emmenlau** [comment]
Ok, if you think manual copy is the right solution, then in my eyes we can close the issue.
I would find it a bit cleaner if cmake and automake leave binaries in the same directory, so I would prefer if cmake builds (or moves) to src/ like automake does, but that's just me. In any case that solves the issue for me, so I know I'm not doing anything wrong. Thanks!
