### ISSUE TITLE
Is the Any networking behavior really needed?

### ISSUE THREAD

**Issue by thomasvl** [google/protobuf#1991]
https://github.com/google/protobuf/blob/master/src/google/protobuf/any.proto#L78-L82  mentions:

``` protobuf
// The pack methods provided by protobuf library will by default use
// 'type.googleapis.com/full.type.name' as the type URL and the unpack
// methods only use the fully qualified type name after the last '/'
// in the type URL, for example "foo.bar.com/x/y.z" will yield type
// name "y.z".
```

But then it also mentions: https://github.com/google/protobuf/blob/master/src/google/protobuf/any.proto#L125-L126

``` protobuf
  // * An HTTP GET on the URL must yield a [google.protobuf.Type][]
  //   value in binary format, or produce an error.
```

Is this second part really required, or should we just drop it from the file/spec (and like the next bullet about fetching/caching them.  Seems like most implementations only plan on supporting what is baked into a given binary.  Report fetching support seems like it would be opening a vector that could cause problems for a binary - what if the fetched descriptor tries to register something already registered?  Are all runtimes hardened against that?

**Comment by thomasvl** [comment]
PS - it is probably too late, but given the host isn't really needed, and likely shouldn't be fetched, it means we're burning bytes in any proto that uses any to include a host that isn't needed.  Is it worth updating helpers and making the host optional so it can be left off?

**Comment by xfxyjwf** [comment]
We probably should just remove that sentence. It's a requirement/recommendation for an Any type service, not for Any proto itself, and we don't currently have any type service setup or any runtime library support to build or use such type services.

@pherl

**Comment by thomasvl** [comment]
Thinking about this some more, with the global registry in some of the proto runtimes and/or the symbol collision it would cause; could we even support a package.Message duplicated from two different hosts?  Don't they really have to be global unique if they are built into a single binary?

Maybe we could trip this down to just "/[full_name]" and save those host on the wire?

**Comment by xfxyjwf** [comment]
You are right. "package.Message" must be globally unique, or otherwise protoc will complain about it at compile time or protobuf runtime will complain about it at runtime. The URL prefix  doesn't help identify a message uniquely. Instead it only points to a place where the type info is available. In existing use case where type info all comes from the local binary, the type URL prefix is useless, but if we build tools that will actually query remote type services to interpret an Any type, the prefix will be needed. I agree that "/[full_name]" as the default makes more sense, but it's not easy to change the behavior now because tons of existing code is already baked with hard-coded string comparison code against "type.googleapis.com".

For users who do want to avoid this additional type URL prefix cost, the generated Any API actually has a PackFrom(prefix, message) method where the user can simply pass an empty URL prefix. It is available in C++/Java and Python.

**Comment by kientzle** [comment]
If the user specifies an empty prefix, does that result in "/[full_name]" as the stored type?

**Comment by thomasvl** [comment]
For C++, it appears to: https://github.com/google/protobuf/blob/master/src/google/protobuf/any.cc#L63

Not sure if that is expected for all languages or not.

**Comment by skolodyazhnyy** [comment]
Is there any information about type repo or fetching type information by URL? It seems to be quite useful. Not just for Any type, but as well for code generation. May be even importing types by URL rather than fetching them manually and then placing in the proper folders and so on.

**Comment by jhump** [comment]
I found this issue after intending to file one, after an [exchange on the protobuf Google Group](https://groups.google.com/d/topic/protobuf/ekLpBKo2kPA/discussion).

*Please* update the docs if there is no intent to provide dynamic type resolution (like via the HTTP service described in the docs for the Any type). Also, I agree that we should just ditch the hostname and this field should simply be a fully-qualified message name and not a URL.

**Comment by xfxyjwf** [comment]
The Any documentation has been updated to call out the networking behavior as optional:
https://github.com/google/protobuf/blame/master/src/google/protobuf/any.proto#L129-L132

> In practice, teams usually precompile into the binary all types that they
> expect it to use in the context of Any. However, for URLs which use the
> scheme `http`, `https`, or no scheme, one can optionally set up a type
> server that maps type URLs to message definitions as follows:
