### ISSUE TITLE
2.5 release of protoc

### ISSUE THREAD

**Issue by pranasblk** [google/protobuf#1993]
Many thanks for resolving #969 for protoc 2.6.1. But my clients needs exactly 2.5.0 version ... Would it be possible to get protoc 2.5 release deployed to the maven repo?

Thanks again!

**Comment by xfxyjwf** [comment]
Any chance you can upgrade?

**Comment by pranasblk** [comment]
0 Chance to upgrade and Google official build would be accepted for production only. 
Sorry for the inconveniences and greatly appreciated your help!

**Comment by xfxyjwf** [comment]
Could you elaborate some more about why there is no chance to upgrade? Is it because the clients don't want to? or is there any technical difficulties making it impossible or risky?

**Comment by pranasblk** [comment]
My client (huge institution) can not upgrade 3rd party libs as system already in production, but need to modernise automate builds on Linux (currently using Windows). Thank you for the understanding.

Kind regards and thanks again
Pranas

**Comment by xfxyjwf** [comment]
Thanks to @TeBoring , protoc 2.5.0 binary is available on maven central repo now:
https://mvnrepository.com/artifact/com.google.protobuf/protoc/2.5.0
