### ISSUE TITLE
protobuf 3.0.0 check MapFieldStateTest.GetMap/1 fails on i686 but works on x86_64?

### ISSUE THREAD

**Issue by emmenlau** [google/protobuf#1996]
I'm compiling protobuf on MSYS2 with MinGW64 gcc-6.1.0 compiler for 32 and 64bit. The make check for 64bit works, but the check for 32bit crashes with segfault in MapFieldStateTest.GetMap/1. I'm unable to debug this because I don't understand how the tests work. I could find the source for MapFieldStateTest and the function GetMap(). What does the /0 and /1 mean?

```
[...]
[----------] 36 tests from MapFieldStateTestInstance/MapFieldStateTest
[ RUN      ] MapFieldStateTestInstance/MapFieldStateTest.GetMap/0
[       OK ] MapFieldStateTestInstance/MapFieldStateTest.GetMap/0 (0 ms)
[ RUN      ] MapFieldStateTestInstance/MapFieldStateTest.GetMap/1
make[3]: *** [CMakeFiles/check.dir/build.make:57: CMakeFiles/check] Segmentation fault
make[2]: *** [CMakeFiles/Makefile2:68: CMakeFiles/check.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:75: CMakeFiles/check.dir/rule] Error 2
make: *** [Makefile:162: check] Error 2
==> ERROR: A failure occurred in check().
    Aborting...
```

**Comment by TeBoring** [comment]
Close the issue for clean up. Feel free to re-open it if there is still problem.
