### ISSUE TITLE
Protobuf should not use folder names instead of namespace names

### ISSUE THREAD

**Issue by Zeks** [google/protobuf#2005]
This produces all kinda of problems for automatic generation and human readability.
Why does it even try to mangle folder structure into variable names? Shouldnt package structure be enough?

For example:
void protobuf_AddDesc_AirSpace_2fAltitude_2eproto();

here Altitude already knows it's a member of Airspace because it was declared as 
package "airspace"
but protoc on generation will not insert Airspace into the mix unless it's specifically invoked as:
protoc proto.... cpp_out... Airspace/filename.proto

this folder dependency is extremely strange when package spaces are already explicitly named in proto files.

**Comment by xfxyjwf** [comment]
The name protobuf_AddDesc_AirSpace_2fAltitude_2eproto is an implementation detail. Why do you care how it's named? Are you generating code based on the proto generated code?

**Comment by Zeks** [comment]
exactly, and name matching breaks.
I am generating stuff for google:grpc in this way
file 1.proto
Airspace/ file2.proto

file2 is a member of Airspace package as stated in its contents
protoc is invoked as:
abspath-to-protoc --proto-out-abspath-to-proto-file --cpp-out=abspath-to-out-folder abspath-to-file1 
abspath-to-protoc --proto-out-abspath-to-proto-file --cpp-out=abspath-to-out-folder abspath-to-file2 (including Airspace folder)

The Airspace package token isnt mangled into its name in File2 this way and name matching breaks between file1 and file2. I am forced to use relative names and this requires some quite non obvious project file fixes.

**Comment by Zeks** [comment]
This essentially forces my folder structure to copy package structure and also forces me into relative names, where it would have been much easier to feed protoc absolute ones

**Comment by xfxyjwf** [comment]
Assuming your project has such a dir layout:
```
/path/to/your/project/proto/file1.proto
/path/to/your/project/proto/airspace/file1.proto
```

You should be invoking protoc this way:
```bash
protoc --proto_path=/path/to/your/project/proto --cpp_out=/abspath/to/out /path/to/your/project/proto/file1.proto
protoc --proto_path=/path/to/your/project/proto --cpp_out=/abspath/to/out /path/to/your/project/proto/airspace/file2.proto
```

Note that the two commands share the same "--proto_path" flag.

**Comment by Zeks** [comment]
I am fairly sure I was doing it this exact way. I will recheck tomorrow when I am at work

**Comment by Zeks** [comment]
I must have been doing something wrong. When I did everything exactly as you stated in the example it worked, thx.
