### ISSUE TITLE
payment_libs.js:155 Uncaught TypeError: jspb.BinaryWriter is not a constructor

### ISSUE THREAD

**Issue by JoyCood** [google/protobuf#2010]
```
<script src="node_modules/google-closure-library/closure/goog/base.js"></script>
<script src="message.js"></script>
<script src="payment_libs.js"></script>
<script type="text/javascript">
```

var payment =  new proto.Wechat();
payment.setAppid('123');
appid = payment.getAppid();
payment.serializeBinary();
    </script>

**Comment by haberman** [comment]
Sorry for the slow reply! You should be including `google-protobuf.js` from the npm, not `message.js`.
