### ISSUE TITLE
tests.exe failed to build in Visual studio 2010. 

### ISSUE THREAD

**Issue by mhasan** [google/protobuf#2015]
Hi,
I am trying to build protobuf 3.0.0 in visual studio 2010, and I am getting linking error while trying to build tests.exe. The error is as follows:

2>libprotobufd.lib(time_util.obj) : error LNK2005: "public: static __int64 const google::protobuf::util::TimeUtil::kTimestampMinSeconds" (?kTimestampMinSeconds@TimeUtil@util@protobuf@google@@2_JB) already defined in map_test.obj
2>libprotobufd.lib(time_util.obj) : error LNK2005: "public: static __int64 const google::protobuf::util::TimeUtil::kTimestampMaxSeconds" (?kTimestampMaxSeconds@TimeUtil@util@protobuf@google@@2_JB) already defined in map_test.obj
2>libprotobufd.lib(time_util.obj) : error LNK2005: "public: static __int64 const google::protobuf::util::TimeUtil::kDurationMinSeconds" (?kDurationMinSeconds@TimeUtil@util@protobuf@google@@2_JB) already defined in map_test.obj
2>libprotobufd.lib(time_util.obj) : error LNK2005: "public: static __int64 const google::protobuf::util::TimeUtil::kDurationMaxSeconds" (?kDurationMaxSeconds@TimeUtil@util@protobuf@google@@2_JB) already defined in map_test.obj

Any idea how can I fix this issue?
Thanks.

**Comment by xfxyjwf** [comment]
This seems a bug in visual studio. I think you can fix it by commenting out line 147 to line 150 in this file:
https://github.com/google/protobuf/blob/master/src/google/protobuf/util/time_util.cc#L147

**Comment by haberman** [comment]
This was fixed in https://github.com/google/protobuf/commit/460e7dd7c47b5a3fc290008317c044fac741916a
