### ISSUE TITLE
Java wrappers.proto broken since 3.0.0 following GeneratedMessage versionning?

### ISSUE THREAD

**Issue by ltkn** [google/protobuf#2017]
Hi,

I can't use Int32Value on proto3 since 3.0.0 (was working fine on 3.0.0-beta-4).
possibly related to https://github.com/google/protobuf/commit/2e30301837ffcead1776a52999a6da1983a5686a and the versionning of GeneratedMessage.

broken code below

`Int32Value` extends `GeneratedMessageV3` but `SingleFieldBuilder` extends `GeneratedMessage`

```
 private com.google.protobuf.SingleFieldBuilder<
          com.google.protobuf.Int32Value, com.google.protobuf.Int32Value.Builder, com.google.protobuf.Int32ValueOrBuilder> 
          getDurationMinutesFieldBuilder() {
        if (durationMinutesBuilder_ == null) {
          durationMinutesBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.google.protobuf.Int32Value, com.google.protobuf.Int32Value.Builder, com.google.protobuf.Int32ValueOrBuilder>(
                  getDurationMinutes(),
                  getParentForChildren(),
                  isClean());
          durationMinutes_ = null;
        }
        return durationMinutesBuilder_;
      }
```

thanks

**Comment by xfxyjwf** [comment]
Old generated code won't work with protobuf 3.0.0 runtime. I think you just need to update your genreated code by running the latest protoc.

**Comment by landbit** [comment]
I did regenerate the code, but then the code doesn't compile anymore for the reasons mentionned earlier, we're using https://github.com/xolstice/protobuf-maven-plugin for code generation.

Let me know if you believe I'm not doing it correclty. thanks.

**Comment by ltkn** [comment]
Could you please label it as a bug? thanks.

**Comment by xfxyjwf** [comment]
Int32Value is part of protobuf library itself (included in protobuf-java.jar maven artifact), so if you have the correct dependency, you shouldn't need to compile it from source. This seems to me a problem in your build setup.

**Comment by Helcaraxan** [comment]
I am facing the same problem (although with other types than Int32Value).

Proto files following `syntax = "proto2"` (and not possible to upgrade to "proto3"). All code regenerated with "protoc" compiled from the v3.0.2 tag.

The SingleFieldBuilder class should extend GeneratedMessageV3 as stated in the initial issue report but it extends GeneratedMessage instead.

**Comment by xfxyjwf** [comment]
If you have regenerated the code using the latest protoc, it should not have "SingleFieldBuilder" in the generated code, but instead "SingleFieldBuilderV3". I still think the problem is the use of an out-dated protoc somewhere in your build config.

**Comment by ltkn** [comment]
It was a maven dependency issue in our case, problem fixed.

If someone has the same problem you might want to check that you're using all proto deps in the same versions (including those inherited from parent poms) 

Thanks for your help.
