### ISSUE TITLE
C#: Serialization/deserialization issue for first element of Enum

### ISSUE THREAD

**Issue by andrey-alekov** [google/protobuf#2020]
I have next proto file.
```
syntax = "proto3";
package API.Message;

message TestMessage {
	string StringField = 1;
	enum FieldEnum {
		FIRST = 0;
		SECOND = 1;
		THIRD = 2;
	}
	FieldEnum EnumField = 2;
}
```

Based on proto, I've compiled C# class and write next simple test
```
using System;
using API.Message;

namespace CheckForBug
{
    class Program
    {
        static void Main(string[] args)
        {
            var message = new TestMessage {StringField = "mystring", EnumField = TestMessage.Types.FieldEnum.First};
            Console.WriteLine(message.ToString());
            var message2 = new TestMessage { StringField = "mystring", EnumField = TestMessage.Types.FieldEnum.Second };
            Console.WriteLine(message2.ToString());
        }
    }
}
```
Finally I got this
```
{ "stringField": "mystring" }

{ "stringField": "mystring", "enumField": "SECOND" }
```

**Comment by xfxyjwf** [comment]
This is working as intended. For enum fields, its default value is the first enum value and in proto3 setting a primitive field to its default value is basically no-op (i.e., same as unset).

**Comment by andrey-alekov** [comment]
Ok, lets suppose that in proto is working as intended. Let assum that in proto3 for serialize/deserialize works great with default value. How about integration with other systems. In this case they don't know about proto and default values. This might lead to data contract violation. Keep this in mind.

**Comment by jskeet** [comment]
If you intend to interoperate with other systems, you need to be aware of the differences between protobuf and those other systems, basically. If you want all values to be serialized as JSON regardless of whether or not they're the default value, you can create a `JsonFormatter` with a `JsonFormatter.Settings` with `FormatDefaultValues` as `true`.

**Comment by andrey-alekov** [comment]
@jskeet thanks a lot. this will works great to intergation.
