### ISSUE TITLE
descriptor.h dependency in "using namespace std"

### ISSUE THREAD

**Issue by shooshx** [google/protobuf#2022]
src/google/protobuf/descriptor.h line 146 has:

```
  vector<string> leading_detached_comments;
```

unlike everywhere else in the code this line does not have the std:: qualifier 
this line compiles only due to 
include/google/protobuf/stubs/common.h line 220 which says

```
 using namespace std;  // Don't do this at home, kids.
```

I ran into this issue when I had this included from a file where another namespace (Ogre) added std into itself and also had a global "using namespace Ogre" . This caused an ambiguity of which vector to use google::protobuf::std::vector or Ogre::std::vector

**Comment by khingblue** [comment]
Can we remove `using namespace std;` and add `std::` to code?

**Comment by xfxyjwf** [comment]
Is adding std:: to vector<string> good enough to resolve the issue? If so feel free to send us a pull request to do the fix.

Replacing "using namespace std;" will be a more involving change and will likely require changes to our internal code base as well, so we'd better make that change in our internal code base instead.

**Comment by shooshx** [comment]
After browsing some more of the headers here, I am no longer convinced this is the right fix. I've fixed my own code to work around the issue I had. Please close this issue, sorry for the bother.
