### ISSUE TITLE
2.5.0 autogen.sh fails

### ISSUE THREAD

**Issue by mgummelt** [google/protobuf#2025]
https://github.com/google/protobuf/blob/v2.5.0/autogen.sh#L22

```
$ ./autogen.sh 
Google Test not present.  Fetching gtest-1.5.0 from the web...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1586  100  1586    0     0  16602      0 --:--:-- --:--:-- --:--:-- 16694
bzip2: (stdin) is not a bzip2 file.
tar: Child returned status 2
tar: Error is not recoverable: exiting now
```

It seems the gtest URL is no longer valid

**Comment by xfxyjwf** [comment]
Yes, the link is no longer available. We fixed this in master branch (see: https://github.com/google/protobuf/commit/bba446bbf2ac7b0b9923d4eb07d5acd0665a8cf0) , but we can't do anything for 2.5.0 autogen.sh though.

**Comment by Kentzo** [comment]
@mgummelt See my fork https://github.com/GreatFruitOmsk/protobuf-py3/tree/2.5.2

**Comment by KevinYuk** [comment]
HI @xfxyjwf,

It seems that the code diff conflict with the 2.5.0 autogen.sh file.

**Comment by tingxueronghua** [comment]
So, the solution is?
