### ISSUE TITLE
Please prived guidance how to produce single linux protoc binary (with static linking)

### ISSUE THREAD

**Issue by pranasblk** [google/protobuf#2027]
By default multiple linux binaries are created from sources of 2.5.0 release on Oracle Linux 6.6.
Motivation: I'd like putting protoc binary to maven repository to be used from gradle protobuf plugin.

**Comment by xfxyjwf** [comment]
We already pushed protoc binaries to maven and it doesn't cover old versions like 2.5.0. Can you try to upgrade to new versions first?
https://mvnrepository.com/artifact/com.google.protobuf/protoc

**Comment by pranasblk** [comment]
Is 2.5.0 no longer maintained? There some technical issues highlighted on #1993 regarding upgrade, but I'd like to hear your position about it. 

Thanks!

**Comment by xfxyjwf** [comment]
Thanks to @TeBoring , protoc 2.5.0 binary is available on maven central repo now:
https://mvnrepository.com/artifact/com.google.protobuf/protoc/2.5.0
