### ISSUE TITLE
gmock zip file not found 

### ISSUE THREAD

**Issue by ckeyer** [google/protobuf#2030]
At tag `v3.0.0`  autogen.sh

https://github.com/google/protobuf/blob/v3.0.0/autogen.sh#L34

`https://googlemock.googlecode.com/files/gmock-1.7.0.zip` return 404

**Comment by jlippuner** [comment]
I can confirm this issue. I used `http://pkgs.fedoraproject.org/repo/pkgs/gmock/gmock-1.7.0.zip/073b984d8798ea1594f5e44d85b20d66/gmock-1.7.0.zip` instead, but `autogen.sh` needs to be fixed.

**Comment by xfxyjwf** [comment]
It's already fixed:
https://github.com/google/protobuf/commit/bba446bbf2ac7b0b9923d4eb07d5acd0665a8cf0

The next patch version 3.0.2 will include the fix.
