### ISSUE TITLE
Unused parameter 'deterministic'

### ISSUE THREAD

**Issue by jlippuner** [google/protobuf#2032]
Every message generates an unused parameter warning for `bool deterministic` in `::google::protobuf::uint8* <message>::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const`.

This is on git tag `v3.0.0`.

**Comment by khingblue** [comment]
Looks like `deterministic` was added by commit d64a2d99.

Should we keep this variable and use some trick to remove compiler warning, or just remove this variable?
