### ISSUE TITLE
MergeFrom unexpected result in python cpp implementation

### ISSUE THREAD

**Issue by khigia** [google/protobuf#2038]
About python protobuf-3.0.0 (build from source).

I believe there is a difference in behaviour of `MergeFrom` between cpp_implementation and python implementation (joining simple code to demonstrate what I believe is an issue in cpp_implementation).
In short, **with cpp_implementation**, if a Message has sub-message, the `MergeFrom` method do different things depending if a sub-message is initialized or left to default in original message.

If the sub-message is left to default as construction time, after merge, accessing the sub-message field will always return the default (note that making of copy of the merged message give back a valid message returning correct values).

This is all easier to show with code, see below. The first test works as expected (see the sub-message is initialized). The second test fail on last line (note that the copied message behave correctly). By the way, both tests pass when using protobuf python (not cpp_impl).

(tested for both python 2.7 and 3.4, built with standard gcc compiler on fedora core 23)

```
# Using protobuf-v3.0.0
# Tested with python2.7.10 and python 3.4

import unittest

import mergetest_pb2 as mpb

# Content of mergetest.proto
"""
message MySubMsg {
    optional uint64 i = 1;
}

message MyMsg {
    optional uint64   singular = 1;
    optional MySubMsg sub = 2;
}
"""

class PbTest(unittest.TestCase):

    def test_merge_ok(self):
        m = mpb.MyMsg(
            singular=1,
            sub=mpb.MySubMsg(),  # Note: sub-message is defined
        )
        assert m.sub.i == 0

        m2 = mpb.MyMsg(
            singular=2,
            sub=mpb.MySubMsg(i=1),
        )
        assert m2.sub.i == 1

        m.MergeFrom(m2)
        assert m.singular == 2
        assert m.sub.i == 1

    def test_merge_bad(self):
        m = mpb.MyMsg(
            singular=1,
            # Note: sub-message is not defined (default)
        )
        assert m.sub.i == 0

        m2 = mpb.MyMsg(
            singular=2,
            sub=mpb.MySubMsg(i=1),
        )
        assert m2.sub.i == 1

        m.MergeFrom(m2)

        # The merge is ok, underlying data struct has correct value.
        # If we copy the message, we obtain a valid message back.
        mcopy = mpb.MyMsg()
        mcopy.CopyFrom(m)
        assert mcopy.singular == 2
        assert mcopy.sub.i == 1

        # However some of original message accessor return wrong result.
        # Singular field are ok
        assert m.singular == 2
        # Sub-message are NOT ok
        assert m.sub.i == 1  # <-- This raises! We expect this to works, right?
```

**Comment by khigia** [comment]
For info, just noted that calling `m.Clear()` before `m.mergeFrom(m2)` make the test pass (obviously it doesn't fix merging, but just for info).

**Comment by khigia** [comment]
Forcing `MergeFrom` on sub-message also wroks. Could be related to the recursive behaviour of `MergeFrom` wrt default value.

**Comment by anandolee** [comment]
There a known bug which may related, we are still working one but haven't get a good solution yet:
  // TODO(tibell): Message::MergeFrom might turn some child Messages
  // into mutable messages, invalidating the message field in the
  // corresponding CMessages.  We should run a FixupMessageReferences
  // pass here.
https://github.com/google/protobuf/blob/master/python/google/protobuf/pyext/message.cc

**Comment by anandolee** [comment]
It is fixed in internal code by adding a "struct FixupMessageAfterMerge : public FixupMessageReference". Expect to see the fix in next release
