### ISSUE TITLE
Error installing GoogleProtobuf

### ISSUE THREAD

**Issue by schillerGao** [google/protobuf#2040]
I use cocoapods to install  GoogleProtobuf 2.5.0 and it happened an error like followed:

[!] Error installing GoogleProtobuf
[!] /usr/bin/curl -f -L -o /var/folders/pv/vz70m94974l7f8x51zjq09qr0000gp/T/d20160831-2774-1qjplpv/file.tgz http://protobuf.googlecode.com/files/protobuf-2.5.0.tar.gz --create-dirs

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0curl: (22) The requested URL returned error: 404 Not Found

I am in Nanjing ,China where we have to visit google by VPN.
Even if I use VPN  I cannot visit  "http://protobuf.googlecode.com/files/protobuf-2.5.0.tar.gz".
Is the url not used now?  I  am waiting for a replying now . 
@willnorris @haberman

**Comment by thomasvl** [comment]
The pod maintained from this project is just _Protobuf_:

```shell
$ pod trunk info Protobuf

Protobuf
    - Versions:
      - 3.0.0 (2016-07-29 21:28:52 UTC)
      - 3.0.0-alpha-3 (2015-06-03 04:04:20 UTC)
      - 3.0.0-alpha-4.1 (2015-09-09 17:59:17 UTC)
      - 3.0.0-beta-2 (2016-01-05 19:00:56 UTC)
      - 3.0.0-beta-3 (2016-05-18 21:59:33 UTC)
      - 3.0.0-beta-3.1 (2016-06-14 18:47:57 UTC)
      - 3.0.0-beta-4 (2016-07-19 19:04:46 UTC)
    - Owners:
      - TeBoring <teboring@google.com>
      - Jorge Canizales <jcanizales@google.com>
      - Google <cocoapods@google.com>
```

The pod you referenced isn't maintained by anyone on this project:

```shell
$ pod trunk info GoogleProtobuf

GoogleProtobuf
    - Versions:
      - 2.4.1 (2014-05-19 21:56:32 UTC)
      - 2.5.0 (2014-05-19 21:57:07 UTC)
      - 2.5.0-NoMake (2014-05-19 22:08:32 UTC)
      - 2.6.1 (2014-12-11 14:52:55 UTC)
      - 3.0.0-beta-3.1 (2016-07-13 12:05:32 UTC)
    - Owners:
      - 阿凡树 <729397005@qq.com>
      - liuyufeng2014 <391868398@qq.com>
      - Graham Perks <graham@binocular.io>
```

If you really want the older 2.5 release, you'll need to contact those maintainers.
