### ISSUE TITLE
c++ std::min problem when use proto map

### ISSUE THREAD

**Issue by molixiaoge** [google/protobuf#2049]
When i use proto map type with c++ source code,the visual studio out put  show:
error C2589: “(”:“::”

So i check the code ,and use (std::min) instead of std::min,because windows.h have min macro conflict with std::min.

The filelist i found in 3.0ga show as the follow:

google/protobuf/map.h:1081
google/protobuf/wire_format_lite_inl.h:278
google/protobuf/wire_format_lite_inl.h:370

Look forward to your reply.

**Comment by xfxyjwf** [comment]
Can you point to which line of the code has this problem?

**Comment by asquithea** [comment]
Defining `NOMINMAX` may help avoid this one.

**Comment by molixiaoge** [comment]
because windef.h stdlib.h contains min or max macro define,so it is conflict

**Comment by dschepler** [comment]
In a quick search I also found std::max usage in google/protobuf/repeated_field.h lines 1262 and 1263 that might need the same (std::max)(...) treatment.

**Comment by david0u0** [comment]
Can we consider reopen this issue? I don't think this problem is perfectly solved if we had to modify the codegened files. It's against protobuf's workflow in my humble opinion.
