### ISSUE TITLE
Protobuf 2.6.0 windows compile error

### ISSUE THREAD

**Issue by toast12** [google/protobuf#205]
Hi,

I am trying to build protobuf 2.6.0 using visual studio 2008. But keep on getting this error:

command_line_interface.cc
..\src\google\protobuf\compiler\command_line_interface.cc(1562) : error C2440: 'initializing' : cannot convert from 'std::_Tree<_Traits>::const_iterator' to 'std::_Tree<_Traits>::iterator'
        with
        [
            _Traits=std::_Tset_traits<google::protobuf::compiler::`anonymous-namespace'::FieldRange,std::less<google::protobuf::compiler::`anonymous-namespace'::FieldRange>,std::allocator<google::protobuf::compiler::`anonymous-namespace'::FieldRange>,false>
        ]
        No constructor could take the source type, or constructor overload resolution was ambiguous
code_generator.cc
Generating Code...
libprotoc - 1 error(s), 2 warning(s)

How do I resolve it?

**Comment by xfxyjwf** [comment]
This is fixed in latest releases (after protobuf 2.6.1).
