### ISSUE TITLE
javascript: maps are converted to arrays of arrays

### ISSUE THREAD

**Issue by drobertduke** [google/protobuf#2056]
I'm using gRPC 1.0.0 with a google-protobuf.js build from master (to fix the valueWriterFn_ bug in the 3.0.0 release). Calling toObject() on a result that includes a map will express the map as an array of arrays. I would expect it to produce a javascript object.

proto definition: `map<string,string> definedscopes = 1;`

client code: `result.toObject();`

result: `{ definedscopesMap: [ [ "key1", "value1" ], [ "key2", "value2" ] ] }`

desired result: `{ definedscopesMap: { "key1": "value1", "key2", "value2" } }`

Using the same proto definition with the grpc.load() dynamic generation method produces a normal javascript object.

**Comment by xfxyjwf** [comment]
@haberman Is the plan to make toObject() produce valid proto3 JSON?

**Comment by hochhaus** [comment]
Per https://github.com/google/protobuf/issues/1591 I don't think proto3 JSON support is implemented for JavaScript (even internally at Google). My understanding is that `toObject()` does not / is not intended to return proto3 JSON.

**Comment by hochhaus** [comment]
https://github.com/google/protobuf/issues/1904 states it even more clearly:

"""
Yes, to be clear, toObject() is not proto3 JSON, it is a pre-existing JSON mapping that does not conform to proto3 JSON.
"""

**Comment by pherl** [comment]
I believe toObject() is not intended for public use. Closing this issue for now.
