### ISSUE TITLE
file_mask.proto is missing a go_package

### ISSUE THREAD

**Issue by tswast** [google/protobuf#2057]
https://github.com/google/protobuf/blob/master/src/google/protobuf/field_mask.proto

This file probably needs

```
option go_package = "github.com/golang/protobuf/ptypes/fieldmask";
```

I have filed https://github.com/golang/protobuf/issues/226 to track including it in the Go protobuf package.

**Comment by tswast** [comment]
I am working on writing conformance tests for Go and this is needed (mostly because Go doesn't do really relative imports and the Go protobuf compiler doesn't support compiling to multiple packages https://github.com/golang/protobuf/issues/39)

**Comment by anandolee** [comment]
Already fixed by
option go_package = "google.golang.org/genproto/protobuf/field_mask;field_mask";
