### ISSUE TITLE
autogen.sh failing

### ISSUE THREAD

**Issue by ypraveen** [google/protobuf#2063]
# ./autogen.sh 
Google Mock not present.  Fetching gmock-1.7.0 from the web...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1582  100  1582    0     0  11977      0 --:--:-- --:--:-- --:--:-- 12076
[gmock-1.7.0.zip]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of gmock-1.7.0.zip or
        gmock-1.7.0.zip.zip, and cannot find gmock-1.7.0.zip.ZIP, period.

**Comment by ypraveen** [comment]
Looks like gmock is not available at https://googlemock.googlecode.com/files/gmock-1.7.0.zip anymore

**Comment by ypraveen** [comment]
In v3.0.0; looks like it is fixed in master

**Comment by erikfrey** [comment]
Hi @ypraveen , do you guys hotfix existing releases?  We're getting bit by this - what's the right way to install a stable protobuf?

**Comment by xfxyjwf** [comment]
@erikfrey you can download one of the .tar.gz file in the downloads section:
https://github.com/google/protobuf/releases/tag/v3.0.0

for example: [protobuf-cpp-3.0.0.tar.gz](https://github.com/google/protobuf/releases/download/v3.0.0/protobuf-cpp-3.0.0.tar.gz). These .tar.gz files have gmock included already and you only need to run "./configure && make" to build the code.

**Comment by orian** [comment]
As far as I can see the bug is active.

**Comment by qkim0x01** [comment]
Updating autogen.sh works for me
https://github.com/google/protobuf/commit/bba446bbf2ac7b0b9923d4eb07d5acd0665a8cf0

**Comment by akgo** [comment]
@xfxyjwf  every good!  thank you!
