### ISSUE TITLE
Support proto2 syntax with both v2.x and v3.x

### ISSUE THREAD

**Issue by pstavirs** [google/protobuf#2064]
Without the `syntax = "proto2"` statement, v2.x builds fine, v3.x emits warnings
With the `syntax = "proto2"` statement, v2.x builds fail, v3.x has no warnings

As per the release note -
>If omitted, the protocol buffer compiler generates a warning and "proto2" is
used as the default. This warning will be turned into an error in a future
release.

Is there a way for .proto files using proto2 syntax to be compatible with both v2.x and v3.x without any warnings? Since v3.x non-beta just got released recently, as a proto2 user, I would like to support both proto v2.x and v3.x for some time before making pre-requisite as v3.x+

**Comment by xfxyjwf** [comment]
Since v2.x doesn't accept the "syntax" statement at all, I think your only option is to live with the warnings in v3.x.

**Comment by pstavirs** [comment]
@xfxyjwf In that case, can we make sure that the missing syntax warnings don't get converted to error any time soon? Is there a tentative date/release when this is likely to happen?

**Comment by xfxyjwf** [comment]
I think we should probably follow the same deprecation timeline in Java (see: [java compatibility notice](https://github.com/google/protobuf/blob/master/java/README.md#compatibility-notice) that a deprecated API will be removed two years after it's first marked as deprecated. So in this case, the warning should be turned into an error two years after it's first marked as a warning.

**Comment by pstavirs** [comment]
2 years sounds good to me.

I'm closing this issue now. Thanks!
