### ISSUE TITLE
如果我要把typ_url，当作一个变量，来手动赋值，可以算一种加密方式吗？

### ISSUE THREAD

**Issue by yinshiwu** [google/protobuf#2069]
FooUuid * ud = [[FooUuid alloc]init];
    ud.uuid=@"hello";
    
    FooMessage1 * mg1=[[FooMessage1 alloc]init];
    mg1.uuid =ud;
    mg1.username =@"xiaohong";
    mg1.password=@"8888888";
    mg1.sex =1;
    NSLog(@"ggggggg%@",mg1);
    
    
    NSData * da5=[mg1 data];
    
    GPBAny * any =[[GPBAny alloc]init];
    GPBAny * ang=  [any initWithData:da5 error:nil];
    
    ang.typeURL=@"type.googleapis.com/FooMessage1";
    ang.value =da5;
    
    
    [mod.payloadArray addObject:ang];

**Comment by xfxyjwf** [comment]
This seems the right use of Any type. Though I don't know what exactly you are asking... Packing data in Any does not provide any encryption.
