### ISSUE TITLE
generate_descriptor_proto.sh: Syntax error: "(" unexpected

### ISSUE THREAD

**Issue by khingblue** [google/protobuf#2071]
When using script to regenerate descriptors on Ubuntu, it fails with following error:
```
$ ./generate_descriptor_proto.sh
./generate_descriptor_proto.sh: 31: ./generate_descriptor_proto.sh: Syntax error: "(" unexpected
```

Because on Ubuntu, by default /bin/sh is dash, so if user executes this script directly, it will fail with this error.

There are 2 ways to fix it:

1. Change the first line of `generate_descriptor_proto.sh` to `#!/usr/bin/env bash`
1. Prompt user to use: `bash generate_descriptor_proto.sh`

If this is an issue that you'd like to get fixed, I'm happy to submit a PR with one of the solutions above which is preferable. Thanks.

**Comment by xfxyjwf** [comment]
Replacing /bin/sh with base seems the right fix. Feel free to send me a pull request.
