### ISSUE TITLE
Compile error on Debian Testing with GCC6

### ISSUE THREAD

**Issue by jeroenooms** [google/protobuf#2074]
Compiling master branch fails on Debian sid (stock gcc-6.1.1)

```
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I.. -pthread -DHAVE_PTHREAD=1 -DHAVE_ZLIB=1 -Wall -Wno-sign-compare -O2 -g -DNDEBUG -MT google/protobuf/compiler/objectivec/objectivec_file.lo -MD -MP -MF google/protobuf/compiler/objectivec/.deps/objectivec_file.Tpo -c google/protobuf/compiler/objectivec/objectivec_file.cc  -fPIC -DPIC -o google/protobuf/compiler/objectivec/.libs/objectivec_file.o
google/protobuf/compiler/objectivec/objectivec_file.cc: In function ‘void google::protobuf::compiler::objectivec::{anonymous}::PruneFileAndDepsMarkingAsVisited(const google::protobuf::FileDescriptor*, std::vector<const google::protobuf::FileDescriptor*>*, std::set<const google::protobuf::FileDescriptor*>*)’:
google/protobuf/compiler/objectivec/objectivec_file.cc:95:51: error: no matching function for call to ‘find(std::vector<const google::protobuf::FileDescriptor*>::iterator, std::vector<const google::protobuf::FileDescriptor*>::iterator, const google::protobuf::FileDescriptor*&)’
       std::find(files->begin(), files->end(), file);
                                                   ^
In file included from /usr/include/c++/6/bits/locale_facets.h:48:0,
                 from /usr/include/c++/6/bits/basic_ios.h:37,
                 from /usr/include/c++/6/ios:44,
                 from /usr/include/c++/6/ostream:38,
                 from /usr/include/c++/6/iterator:64,
                 from ./google/protobuf/repeated_field.h:55,
                 from ./google/protobuf/descriptor.pb.h:27,
                 from ./google/protobuf/compiler/objectivec/objectivec_helpers.h:38,
                 from ./google/protobuf/compiler/objectivec/objectivec_file.h:37,
                 from google/protobuf/compiler/objectivec/objectivec_file.cc:31:
/usr/include/c++/6/bits/streambuf_iterator.h:369:5: note: candidate: template<class _CharT2> typename __gnu_cxx::__enable_if<std::__is_char<_CharT2>::__value, std::istreambuf_iterator<_CharT> >::__type std::find(std::istreambuf_iterator<_CharT>, std::istreambuf_iterator<_CharT>, const _CharT2&)
     find(istreambuf_iterator<_CharT> __first,
     ^~~~
/usr/include/c++/6/bits/streambuf_iterator.h:369:5: note:   template argument deduction/substitution failed:
google/protobuf/compiler/objectivec/objectivec_file.cc:95:51: note:   ‘__gnu_cxx::__normal_iterator<const google::protobuf::FileDescriptor**, std::vector<const google::protobuf::FileDescriptor*> >’ is not derived from ‘std::istreambuf_iterator<_CharT>’
       std::find(files->begin(), files->end(), file);
                                                   ^
Makefile:3879: recipe for target 'google/protobuf/compiler/objectivec/objectivec_file.lo' failed
```

**Comment by xfxyjwf** [comment]
I don't see how can "std::find(files->begin(), files->end(), file);" trigger a compile error. Is it because of a missing inclusion of the <algorithm> header?

**Comment by RavenX8** [comment]
I am seeing the same error on Ubuntu using GNU 6.2.0.

`libtool: compile:  /usr/bin/g++-6 -DHAVE_CONFIG_H -I. -I.. -pthread -DHAVE_PTHREAD=1 -DHAVE_ZLIB=1 -Wall -Wno-sign-compare -O2 -g -DNDEBUG -MT google/protobuf/compiler/objectivec/objectivec_file.lo -MD -MP -MF google/protobuf/compiler/objectivec/.deps/objectivec_file.Tpo -c google/protobuf/compiler/objectivec/objectivec_file.cc  -fPIC -DPIC -o google/protobuf/compiler/objectivec/.libs/objectivec_file.o
google/protobuf/compiler/objectivec/objectivec_file.cc: In function ‘void google::protobuf::compiler::objectivec::{anonymous}::PruneFileAndDepsMarkingAsVisited(const google::protobuf::FileDescriptor*, std::vector<const google::protobuf::FileDescriptor*>*, std::set<const google::protobuf::FileDescriptor*>*)’:
google/protobuf/compiler/objectivec/objectivec_file.cc:95:51: error: no matching function for call to ‘find(std::vector<const google::protobuf::FileDescriptor*>::iterator, std::vector<const google::protobuf::FileDescriptor*>::iterator, const google::protobuf::FileDescriptor*&)’
       std::find(files->begin(), files->end(), file);
                                                   ^
In file included from /usr/include/c++/6/bits/locale_facets.h:48:0,
                 from /usr/include/c++/6/bits/basic_ios.h:37,
                 from /usr/include/c++/6/ios:44,
                 from /usr/include/c++/6/ostream:38,
                 from /usr/include/c++/6/iterator:64,
                 from ./google/protobuf/repeated_field.h:55,
                 from ./google/protobuf/descriptor.pb.h:27,
                 from ./google/protobuf/compiler/objectivec/objectivec_helpers.h:38,
                 from ./google/protobuf/compiler/objectivec/objectivec_file.h:37,
                 from google/protobuf/compiler/objectivec/objectivec_file.cc:31:
/usr/include/c++/6/bits/streambuf_iterator.h:369:5: note: candidate: template<class _CharT2> typename __gnu_cxx::__enable_if<std::__is_char<_CharT2>::__value, std::istreambuf_iterator<_CharT> >::__type std::find(std::istreambuf_iterator<_CharT>, std::istreambuf_iterator<_CharT>, const _CharT2&)
     find(istreambuf_iterator<_CharT> __first,
     ^~~~
/usr/include/c++/6/bits/streambuf_iterator.h:369:5: note:   template argument deduction/substitution failed:
google/protobuf/compiler/objectivec/objectivec_file.cc:95:51: note:   ‘__gnu_cxx::__normal_iterator<const google::protobuf::FileDescriptor**, std::vector<const google::protobuf::FileDescriptor*> >’ is not derived from ‘std::istreambuf_iterator<_CharT>’
       std::find(files->begin(), files->end(), file);
                                                   ^
make[1]: *** [google/protobuf/compiler/objectivec/objectivec_file.lo] Error 1`

**Comment by adrianludwin** [comment]
I'm seeing the same thing using gcc 4.8.4.

**Comment by adrianludwin** [comment]
This appears to be the issue: https://github.com/google/protobuf/commit/13a41246dd9aa6c6a84d436307b933fd4a6ec4a8. Without this change, I can compile fine; with it, compiler error.

Perhaps this change only works on more recent versions of GCC?

**Comment by adrianludwin** [comment]
Looks like there's a PR pending: https://github.com/google/protobuf/pull/2090 (h/t @thomasvl)

**Comment by xfxyjwf** [comment]
Should be fixed by https://github.com/google/protobuf/pull/2090
