### ISSUE TITLE
ZMQ_MORE vs ZMQ_SNDMORE

### ISSUE THREAD

**Issue by kentlinux** [google/protobuf#2075]
Hi!

I use C++ binding (zmq.hpp) to ZMQ version 4.1.4.

And as I understand there are 2 bugs:

1) There is no method to set property ZMQ_MORE to the **message_t** class.

2) Flag ZMQ_SNDMORE ignored in socket_t::send(**message_t &msg_**, int flags_ = 0).
Method socket_t::send(**const void *buf_, size_t len_**, int flags_ = 0) works fine!

**Comment by xfxyjwf** [comment]
I guess you meant to report the issue to zmq?

**Comment by kentlinux** [comment]
Ooops. :) 
Need more sleep! :)))
Sorry.
