### ISSUE TITLE
Python Installation Error

### ISSUE THREAD

**Issue by mirkara** [google/protobuf#2076]
I downloaded the source and am trying to compile it. However I get the following error:

```

python laura$ python setup.py build
running build
running build_py
Generating google/protobuf/descriptor_pb2.py...
google/protobuf/descriptor.proto:388:3: Expected "required", "optional", or "repeated".
google/protobuf/descriptor.proto:388:12: Expected field name.
```

Any ideas?

**Comment by xfxyjwf** [comment]
Can you check the output of "protoc --version"? If it's not 3.0.0, you probably have an older version of protoc installed already on your machine. In that case, uninstall the old protoc first, and then follow the instructions in the README.md file to install a newer version of protobuf:
https://github.com/google/protobuf/blob/master/README.md
