### ISSUE TITLE
3.0.2 releases do not include binary-only releases

### ISSUE THREAD

**Issue by lavalamp** [google/protobuf#2078]
Was quite confused by the documentation until I realized that 3.0.0 binaries are available as promised, just not 3.0.2--only source code is given for that release.

**Comment by hochhaus** [comment]
@pherl cut the release. Can the binaries be generated?

**Comment by pherl** [comment]
You mean the protoc binary? It's on the way.

**Comment by pherl** [comment]
Just put those binaries on the release page. Let me know if you meant something else.

**Comment by lavalamp** [comment]
Awesome, that's exactly what I meant, thanks!!
