### ISSUE TITLE
c# public static pb::MessageParser<T> Parser { get { return _parser; } }

### ISSUE THREAD

**Issue by plemanach** [google/protobuf#2082]
Hello,

Could you add  something like   MessageParser<T> Parser{ get;}   in the  IMessage<T>, like that we could parse a  protobuf message in a generic way.

Best Regards,
Patrice

**Comment by plemanach** [comment]
is the solution MergeFrom ?

**Comment by jskeet** [comment]
It's not clear to me what you're trying to do. If it were part of the interface, you'd only be able to get it from an existing instance. Can you give me more details of the use case you're trying to implement?

**Comment by plemanach** [comment]
Yes I try parse from an existing instance, it did not strike me that MergeFrom was doing the job on the instance, but it is fine now thanks.

**Comment by plemanach** [comment]
Actually I mean I miss static methods on an interface :) 
https://codeblog.jonskeet.uk/2008/08/29/lessons-learned-from-protocol-buffers-part-4-static-interfaces/
