### ISSUE TITLE
Should the conformance checks be checking for NaN float values?

### ISSUE THREAD

**Issue by tswast** [google/protobuf#2086]
Example: [ProtobufInput.FloatFieldNormalizeSignalingNan.JsonOutput](https://github.com/google/protobuf/blob/80f65d2df82cc23eb92ef5355d638b9102074190/conformance/conformance_test.cc#L1147)

I'm writing conformance tests for Go in https://github.com/google/protobuf/pull/2084, and I noticed that the Go encoder fails with an error for the following conformance tests:

```
ProtobufInput.FloatFieldNormalizeQuietNan.JsonOutput
ProtobufInput.FloatFieldNormalizeSignalingNan.JsonOutput
ProtobufInput.DoubleFieldNormalizeQuietNan.JsonOutput
ProtobufInput.DoubleFieldNormalizeSignalingNan.JsonOutput
JsonInput.ValueAcceptNull.JsonOutput
```

For all but the last one, these are conformance tests where there is a NaN value in JSON input or output. I believe this is caused by the underlying issue in the Go JSON encoding package: https://github.com/golang/go/issues/3480

The Go issue links to https://tools.ietf.org/html/rfc4627#section-2.4

>  Numeric values that cannot be represented as sequences of digits
   (such as Infinity and NaN) are not permitted.

If the spec doesn't allow such values, shouldn't we not be expecting them in JSON input/output? It would mean, unfortunately, that round trip between Protobuf and JSON could get lossy when dealing with floats, though.

**Comment by xfxyjwf** [comment]
Proto3 JSON requires the serializer to serialize NaN as a string value, such as:
```json
{
  "value": "NaN"
}
```
The following are not allowed as it's not valid JSON:
```json
{
  "value": NaN
}
```
These conformance tests are testing the former case.

**Comment by tswast** [comment]
Cool. The conformance tests are probably correct, then. I've filed https://github.com/golang/protobuf/issues/231 to track this encoding for the Go encoder.
