### ISSUE TITLE
[C#] Provide a way to construct a ByteString from a stream

### ISSUE THREAD

**Issue by amineben89** [google/protobuf#2088]
Hi, 

The C# implementation of ByteString does not provide a way to construct the object directly from a System.IO.Stream. 
In scenarios where the message contains bytes for binary data (such as images from the file system), we need to copy the data twice (Stream -> byte[] -> ByteString).

Although the Stream length is not always known, there are still many cases where it is known (such as files, request body in .net MVC applications, MemoryStream ...). 
A method like `ByteString.ReadFrom(System.IO.Stream input)` would solve this problem.

Please note that the Java implementation does have a `static readFrom(InputStream streamToDrain)` method to construct a ByteString. 

Regards,
Amine.

**Comment by jskeet** [comment]
Yes, aside from anything else this would be *convenient*.
(I thought I'd seen a similar request before, but I can't find it now.)
