### ISSUE TITLE
 [unittest_proto_middleman] Error 66

### ISSUE THREAD

**Issue by yushuiqiang** [google/protobuf#2089]
$ mingw32-make
C:/MinGW/bin/mingw32-make  all-recursive
mingw32-make[1]: Entering directory 'C:/MinGW/msys/1.0/home/Administrator/libarcus/protobuf-3.0.2'
Making all in .
mingw32-make[2]: Entering directory 'C:/MinGW/msys/1.0/home/Administrator/libarcus/protobuf-3.0.2'
mingw32-make[2]: Leaving directory 'C:/MinGW/msys/1.0/home/Administrator/libarcus/protobuf-3.0.2'
Making all in src
mingw32-make[2]: Entering directory 'C:/MinGW/msys/1.0/home/Administrator/libarcus/protobuf-3.0.2/src'
oldpwd=`pwd` && ( cd . && $oldpwd/protoc.exe -I. --cpp_out=$oldpwd google/protobuf/any_test.proto google/protobuf/compiler/cpp/cpp_test_bad_identifiers.proto google/protobuf/map_lite_unittest.proto google/protobuf/map_proto2_unittest.proto google/protobuf/map_unittest.proto google/protobuf/unittest_arena.proto google/protobuf/unittest_custom_options.proto google/protobuf/unittest_drop_unknown_fields.proto google/protobuf/unittest_embed_optimize_for.proto google/protobuf/unittest_empty.proto google/protobuf/unittest_enormous_descriptor.proto google/protobuf/unittest_import_lite.proto google/protobuf/unittest_import.proto google/protobuf/unittest_import_public_lite.proto google/protobuf/unittest_import_public.proto google/protobuf/unittest_lite_imports_nonlite.proto google/protobuf/unittest_lite.proto google/protobuf/unittest_mset.proto google/protobuf/unittest_mset_wire_format.proto google/protobuf/unittest_no_arena_lite.proto google/protobuf/unittest_no_arena_import.proto google/protobuf/unittest_no_arena.proto google/protobuf/unittest_no_field_presence.proto google/protobuf/unittest_no_generic_services.proto google/protobuf/unittest_optimize_for.proto google/protobuf/unittest_preserve_unknown_enum2.proto google/protobuf/unittest_preserve_unknown_enum.proto google/protobuf/unittest.proto google/protobuf/unittest_proto3_arena.proto google/protobuf/unittest_proto3_arena_lite.proto google/protobuf/unittest_proto3_lite.proto google/protobuf/unittest_well_known_types.proto google/protobuf/util/internal/testdata/anys.proto google/protobuf/util/internal/testdata/books.proto google/protobuf/util/internal/testdata/default_value.proto google/protobuf/util/internal/testdata/default_value_test.proto google/protobuf/util/internal/testdata/field_mask.proto google/protobuf/util/internal/testdata/maps.proto google/protobuf/util/internal/testdata/oneofs.proto google/protobuf/util/internal/testdata/struct.proto google/protobuf/util/internal/testdata/timestamp_duration.proto google/protobuf/util/json_format_proto3.proto google/protobuf/util/message_differencer_unittest.proto google/protobuf/compiler/cpp/cpp_test_large_enum_value.proto )
Makefile:7775: recipe for target 'unittest_proto_middleman' failed
mingw32-make[2]: **\* [unittest_proto_middleman] Error 66
mingw32-make[2]: Leaving directory 'C:/MinGW/msys/1.0/home/Administrator/libarcus/protobuf-3.0.2/src'
Makefile:1153: recipe for target 'all-recursive' failed
mingw32-make[1]: **\* [all-recursive] Error 1
mingw32-make[1]: Leaving directory 'C:/MinGW/msys/1.0/home/Administrator/libarcus/protobuf-3.0.2'
Makefile:1058: recipe for target 'all' failed
mingw32-make: **\* [all] Error 2

**Comment by yushuiqiang** [comment]
$ mingw32-make
C:/MinGW/bin/mingw32-make  all-recursive
mingw32-make[1]: Entering directory 'C:/MinGW/msys/1.0/home/Administrator/libarcus/protobuf-3.0.2'
Making all in .
mingw32-make[2]: Entering directory 'C:/MinGW/msys/1.0/home/Administrator/libarcus/protobuf-3.0.2'
mingw32-make[2]: Leaving directory 'C:/MinGW/msys/1.0/home/Administrator/libarcus/protobuf-3.0.2'
Making all in src
mingw32-make[2]: Entering directory 'C:/MinGW/msys/1.0/home/Administrator/libarcus/protobuf-3.0.2/src'
oldpwd=`pwd` && ( cd . && $oldpwd/protoc.exe -I. --cpp_out=$oldpwd google/protobuf/any_test.proto google/protobuf/compiler/cpp/cpp_test_bad_identifiers.proto google/protobuf/map_lite_unittest.proto google/protobuf/map_proto2_unittest.proto google/protobuf/map_unittest.proto google/protobuf/unittest_arena.proto google/protobuf/unittest_custom_options.proto google/protobuf/unittest_drop_unknown_fields.proto google/protobuf/unittest_embed_optimize_for.proto google/protobuf/unittest_empty.proto google/protobuf/unittest_enormous_descriptor.proto google/protobuf/unittest_import_lite.proto google/protobuf/unittest_import.proto google/protobuf/unittest_import_public_lite.proto google/protobuf/unittest_import_public.proto google/protobuf/unittest_lite_imports_nonlite.proto google/protobuf/unittest_lite.proto google/protobuf/unittest_mset.proto google/protobuf/unittest_mset_wire_format.proto google/protobuf/unittest_no_arena_lite.proto google/protobuf/unittest_no_arena_import.proto google/protobuf/unittest_no_arena.proto google/protobuf/unittest_no_field_presence.proto google/protobuf/unittest_no_generic_services.proto google/protobuf/unittest_optimize_for.proto google/protobuf/unittest_preserve_unknown_enum2.proto google/protobuf/unittest_preserve_unknown_enum.proto google/protobuf/unittest.proto google/protobuf/unittest_proto3_arena.proto google/protobuf/unittest_proto3_arena_lite.proto google/protobuf/unittest_proto3_lite.proto google/protobuf/unittest_well_known_types.proto google/protobuf/util/internal/testdata/anys.proto google/protobuf/util/internal/testdata/books.proto google/protobuf/util/internal/testdata/default_value.proto google/protobuf/util/internal/testdata/default_value_test.proto google/protobuf/util/internal/testdata/field_mask.proto google/protobuf/util/internal/testdata/maps.proto google/protobuf/util/internal/testdata/oneofs.proto google/protobuf/util/internal/testdata/struct.proto google/protobuf/util/internal/testdata/timestamp_duration.proto google/protobuf/util/json_format_proto3.proto google/protobuf/util/message_differencer_unittest.proto google/protobuf/compiler/cpp/cpp_test_large_enum_value.proto )
Makefile:7775: recipe for target 'unittest_proto_middleman' failed
mingw32-make[2]: *** [unittest_proto_middleman] Error 255
mingw32-make[2]: Leaving directory 'C:/MinGW/msys/1.0/home/Administrator/libarcus/protobuf-3.0.2/src'
Makefile:1153: recipe for target 'all-recursive' failed
mingw32-make[1]: *** [all-recursive] Error 1
mingw32-make[1]: Leaving directory 'C:/MinGW/msys/1.0/home/Administrator/libarcus/protobuf-3.0.2'
Makefile:1058: recipe for target 'all' failed
mingw32-make: *** [all] Error 2

**Comment by xfxyjwf** [comment]
Is this the full error log? I don't see any error message from building "unittest_proto_middleman".

**Comment by LegendaryD** [comment]
Hi, I have the same issue, please view the full log in the attachment:

[make.log.txt](https://github.com/google/protobuf/files/471247/make.log.txt)
[make.err.txt](https://github.com/google/protobuf/files/471248/make.err.txt)

Steps to reproduce:
- Tested 3.0.0 and 3.0.2 on Windows 7 and 10
- Install the latest MinGW, MSYS, autoconf 2.69, automake 1.14
- Open %MinGW_Home%/msys/1.0/msys.bat and: cd %MinGW_Home%/msys/1.0/home/user1/protobuf-3.0.0 (this is where I unzip the release package)
- Run: ./configure --prefix=`cd /mingw; pwd -W`
- Run: make

Actual result: please view the attachment.

**Comment by okomarov** [comment]
I also have the same issue with 3.1.0 on Win7 and latest MinGW. Same directory configuration.

More details are posted on [SO](http://stackoverflow.com/questions/40179693/build-protobuf-on-windows-with-mingw).

Basically `protoc.exe` crashes with memory access violation.

**Comment by pherl** [comment]
Hi, have you been able to solve this issue? We no long support mingw officially and rely on users to send  patches and fixes to make the library mingw compatible. Closing it for now and feel free to reopen if there's a PR.
