### ISSUE TITLE
How to print the extension fields correctly when calling DebugString()

### ISSUE THREAD

**Issue by yaomthu** [google/protobuf#2098]
I define a message A with extensions 100 to 200. Then extend A with field "optional int32 number = 100". 
When I use A->DubugString(), the extended field is shown as "100 : 1000", rather than "number: 1000". How can I solve this issue?

**Comment by xfxyjwf** [comment]
This is a symptom the extension definition is not linked in your binary. Try to access the extension somewhere to force it to be linked in.
