### ISSUE TITLE
isset function definition conflicts with other tools

### ISSUE THREAD

**Issue by jmhodges** [google/protobuf#2099]
In protobuf 3, there is a isset function defined that, unfortunately, conflicts with other tools (e.g. https://github.com/cruppstahl/upscaledb/issues/83 found in https://github.com/Homebrew/homebrew-core/pull/4145#issuecomment-245583380). That's kind of a general name for a library to take over, so maybe it could be renamed? Homebrew, etc., is having to patch at least one other tool right now to fix that up.

**Comment by xfxyjwf** [comment]
Where is the isset function defined in protobuf?

**Comment by jmhodges** [comment]
Oops, sorry, mis-read where the header was. Was in macOS, not protobuf. Closing!
