### ISSUE TITLE
protobuf generating lib for i386 architecture on linux 64 bit machine

### ISSUE THREAD

**Issue by rajnkamr** [google/protobuf#2101]
We need x86-64 bit libprotobuf but it generates by default i386

we are compiling on linux

with ./configure --build=i686-linux --host=x86_64-redhat-linux

objdump -f libprotobuf.so | grep ^architecture
architecture: i386, flags 0x00000150:

Please suggest how can it generate for 64 bit

**Comment by xfxyjwf** [comment]
Please check the compiler you are using. It produces correct x86-64 binary for me with different configurations.
