### ISSUE TITLE
Excessive copying leads to slow serialization

### ISSUE THREAD

**Issue by mazurkin** [google/protobuf#2108]
I'm working on a project which is consist of 1) producer 2) message broker 3) consumer. The project uses protobuf as a serialization protocol both for the producers and for the consumers. The project is settled a long ago and the beans are widely used along company so I'm not allowed to change anything easily.

I'm trying to get highest possible throughput with this bean library and it happens that it's protobuf that limits me - not the message broker nor anything else.

The problem is that some beans are quite huge and linear. Such a bean can contain ~300 fields in root object. Some fields are of primitive types and some fields are nested objects. I found out that due to nature of protobuf the only way to serialize object in producer is to make a immutable object from a builder. For huge bean this operation takes too long. It could be disputable question about immutable vs non-immutable - but I don't need both on producer side. All I need is to set some fields and serialize these to byte array.

I've wrote a simple test which describes the problem: https://github.com/mazurkin/protobuf-test
A monster bean: https://github.com/mazurkin/protobuf-test/blob/master/src/main/config/proto/Monster.proto
A test: https://github.com/mazurkin/protobuf-test/blob/master/src/test/java/org/test/MonsterTest.java

Test shows that build() for a simple object takes 20-30 microseconds that too much for a 'fast' protocol.

All I need is to serialize builder without excessive copying. I see that writeTo() could be implemented write in builder object. A builder has all the fields, all the mask and references child objects/builders.

**Comment by mazurkin** [comment]
Could someone explain why both protoc 2 and protoc 3 generate such a code for build() method:

`      if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.value001_ = value001_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.value002_ = value002_;`

instead of

`      if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
          result.value001_ = value001_;
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
          result.value002_ = value002_;
        }`

Why are non-initialized fields being copied from Bean.Builder to Bean?

**Comment by mazurkin** [comment]
I have manually fixed build() method and now performance is comparable to 'nano' mode of protoc v3 

As I see just some GenerateBuildingCode(io::Printer* printer) should be fixed in protoc compiler

**Comment by xfxyjwf** [comment]
Do you mind send us a pull request to fix that?

**Comment by gerben-s** [comment]
Let's continue on the PR
