### ISSUE TITLE
Lack of protobuf-java-util for protobuf 2

### ISSUE THREAD

**Issue by dbf256** [google/protobuf#2113]
https://github.com/google/protobuf/tree/master/java/util library has a nice JsonFormat class to convert protobuf <> json. The problem is that it requires protobuf 3 and it is not possible to use it in projects with protobuf 2.6.\* dependencies. Is it possible to create a backport or (if they are compatible) change versions range of protobuf lib to work with 2.\* also? 
Thanks.

**Comment by xfxyjwf** [comment]
We are unlikely to make any new 2.x releases unless it helps migration from 2.x to 3.x. How hard is it to upgrade your project to use 3.x?

**Comment by dbf256** [comment]
xfxyjwf, thanks for reply. We don't use protobuf directly in our app, but we have a couple of dependencies on another systems in our organization that are on 2.6 protobuf now, so it is out of our direct control. My task is to have a text representation that will allow to generate protobuf messages for testing, so json is not a mandatory option, but looks like it is convenient enough.

**Comment by anandolee** [comment]
I am closing it because xfxyjwf has already answered. Feel free to reopen it if you have more questions
