### ISSUE TITLE
Comparing protobuf Objects in java without considering order for "repeated" fields 

### ISSUE THREAD

**Issue by amkarthick** [google/protobuf#2116]
"repeated" in protobuf(java) internally maintains order. So while comparing two protobuf objects using .equals()  , We get false even if repeated fields have same values in different order.

Is there any simpler way to compare two protobuf objects without considering order for "repeated" fields?

**Comment by acozzette** [comment]
One thing you could try is to use a map field instead of a repeated field, since map fields are inherently unordered.
