### ISSUE TITLE
Add official Dart support

### ISSUE THREAD

**Issue by themacguffinman** [google/protobuf#2119]
The [dart team has no plans to support proto3](https://github.com/dart-lang/dart-protoc-plugin/issues/59) with their plugin.

I hope the protobuf team can offer support instead.

**Comment by xfxyjwf** [comment]
This might sound disappointing but right now protobuf-team has no plan to extend the support to cover languages other than what we already support.

**Comment by mit-mit** [comment]
cc @jakobr-google is working on this over in https://github.com/dart-lang/protobuf
