### ISSUE TITLE
Empty in PHP

### ISSUE THREAD

**Issue by tbillington** [google/protobuf#2124]
How does [empty](https://github.com/google/protobuf/blob/master/src/google/protobuf/empty.proto) work in PHP? It conflicts with the keyword http://php.net/manual/en/reserved.keywords.php.

**Comment by TeBoring** [comment]
This is mentioned in the README. We will rename it to EmptyMessage in
generated code.

**Comment by TeBoring** [comment]
google.protobuf.Empty is genereated as \Google\Protobuf\GPBEmpty. Fixed in both master and 3.1.x. For other messages named Empty, we don't do any special. So user have to change the name.
