### ISSUE TITLE
protoc-gen-php status code 255

### ISSUE THREAD

**Issue by tbillington** [google/protobuf#2126]
What does this output from `protoc --php_out=proto test.proto` mean, or where can I find info about these status codes?

`--php_out: protoc-gen-php: Plugin failed with status code 255.`

**Comment by TeBoring** [comment]
Have you installed other php proto plugin before? I don't think this error
message is created by our generator.

**Comment by tbillington** [comment]
I was using the latest release rather than the compiled head of this repo, my mistake. This can be closed.
