### ISSUE TITLE
protobuf 3, xcode 8, generated objc files has some compilation issues

### ISSUE THREAD

**Issue by nebiros** [google/protobuf#2127]
```proto
syntax = "proto3";

// import "Phone.proto";

option java_package = "com.batteries.pocs.binary.data.spring.boot.protobuf.domain";
option java_outer_classname = "ContactProto";

message Contact {
  string name = 1;
  string lastName = 2;
  Genre genre = 3;
  // repeated Phone phones = 4;

  enum Genre {
    M = 0;
    F = 1;
  };
}
```

```
Contact.pbobjc.m:53:13: ARC forbids Objective-C objects in struct

Contact.pbobjc.m:141:56: Cast of an indirect pointer to an Objective-C pointer to 'void *volatile *' is disallowed with ARC

Contact.pbobjc.m:142:15: ARC forbids explicit message send of 'release'

Contact.pbobjc.m:141:48: Implicit conversion of Objective-C pointer type 'GPBEnumDescriptor *' to C pointer type 'void *' requires a bridged cast

Contact.pbobjc.m:142:15: 'release' is unavailable: not available in automatic reference counting mode
```

```objc
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Contact.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

 #import "Contact.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - ContactRoot

@implementation ContactRoot

@end

#pragma mark - ContactRoot_FileDescriptor

static GPBFileDescriptor *ContactRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPBDebugCheckRuntimeVersion();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@""
                                                     syntax:GPBFileSyntaxProto3];
  }
  return descriptor;
}

#pragma mark - Contact

@implementation Contact

@dynamic name;
@dynamic lastName;
@dynamic genre;

typedef struct Contact__storage_ {
  uint32_t _has_storage_[1];
  Contact_Genre genre;
  NSString *name;
  NSString *lastName;
} Contact__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "name",
        .dataTypeSpecific.className = NULL,
        .number = Contact_FieldNumber_Name,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(Contact__storage_, name),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "lastName",
        .dataTypeSpecific.className = NULL,
        .number = Contact_FieldNumber_LastName,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(Contact__storage_, lastName),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "genre",
        .dataTypeSpecific.enumDescFunc = Contact_Genre_EnumDescriptor,
        .number = Contact_FieldNumber_Genre,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(Contact__storage_, genre),
        .flags = GPBFieldOptional | GPBFieldHasEnumDescriptor,
        .dataType = GPBDataTypeEnum,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[Contact class]
                                     rootClass:[ContactRoot class]
                                          file:ContactRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(Contact__storage_)
                                         flags:0];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\001\002\010\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

int32_t Contact_Genre_RawValue(Contact *message) {
  GPBDescriptor *descriptor = [Contact descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:Contact_FieldNumber_Genre];
  return GPBGetMessageInt32Field(message, field);
}

void SetContact_Genre_RawValue(Contact *message, int32_t value) {
  GPBDescriptor *descriptor = [Contact descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:Contact_FieldNumber_Genre];
  GPBSetInt32IvarWithFieldInternal(message, field, value, descriptor.file.syntax);
}

#pragma mark - Enum Contact_Genre

GPBEnumDescriptor *Contact_Genre_EnumDescriptor(void) {
  static GPBEnumDescriptor *descriptor = NULL;
  if (!descriptor) {
    static const char *valueNames =
        "M\000F\000";
    static const int32_t values[] = {
        Contact_Genre_M,
        Contact_Genre_F,
    };
    GPBEnumDescriptor *worker =
        [GPBEnumDescriptor allocDescriptorForName:GPBNSStringifySymbol(Contact_Genre)
                                       valueNames:valueNames
                                           values:values
                                            count:(uint32_t)(sizeof(values) / sizeof(int32_t))
                                     enumVerifier:Contact_Genre_IsValidValue];
    if (!OSAtomicCompareAndSwapPtrBarrier(nil, worker, (void * volatile *)&descriptor)) {
      [worker release];
    }
  }
  return descriptor;
}

BOOL Contact_Genre_IsValidValue(int32_t value__) {
  switch (value__) {
    case Contact_Genre_M:
    case Contact_Genre_F:
      return YES;
    default:
      return NO;
  }
}


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
```

**Comment by thomasvl** [comment]
See https://github.com/google/protobuf/tree/master/objectivec#building, you shouldn't be compile the generated source with ARC enabled.  You can use ARC in all your code, but compile the library and generated `.m` files without ARC.

**Comment by nebiros** [comment]
@thomasvl thank you!, didn't notice it, 😅, I create a custom build rule in xcode to run `protoc` for all `.proto` files, so, seems like I need to run this myself and then start adding `.m` files with no arc flag, :(

**Comment by thomasvl** [comment]
Or just add use a static library target with ARC turned off.  i.e. - your rule could still work, just add the .proto files to the target that doesn't have ARC enabled.

**Comment by Motti-Shneor** [comment]
Help please. I'm not using CocoaPods, or any other dependency injection system. The GitHub "last release" for MacOS/iOS contains only the `protoc` compiler binary, plus an "include" directory with some base `.protoc` files. When I use them (via Xcode 10 build-rules) my generated sources fail to build because they're looking for nonexistent  ` #import "GPBProtocolBuffers_RuntimeSupport.h"`. I understand from the above, that there must be some extra protobuf "library" or "framework" or some other "runtime support" that must be built/obtained for this. BUT I CANT FIND WHERE. Nor the instructions on building it, or what repo should I download, or how to go about it. I've been googling around for 2 days now, without any answer. Please help. This question seems to be related to my issue.

**Comment by thomasvl** [comment]
@Motti-Shneor did you look at the directions mentioned in the [previous comment](https://github.com/protocolbuffers/protobuf/issues/2127#issuecomment-247651294)?  That talks about how to build by directly adding the sources.

**Comment by Motti-Shneor** [comment]
Yes, I read it, and also finally worked this out, and it kind'a works - although I'm not happy with These non-arc sources. What bothers me, is that google's famous "protobuf" used in no less than 300000 projects - has such a poor support for ObjC - that actually no official documentation states HOW to build the needed components, the existing documentation and pre-built downloads fool you to believe you only need the protoc compiler + some accompanying .proto files to include in your own - and there is absolutely no description or even discussion of the limitations performance envelope or actually any technical aspect of the Obj-C support - let alone not being compatible with Apple's ARC which is here over a decade and is Xcode's default and standard for the last 5 years at least. This neglect is very frustrating  - an not really encouraging when selecting a technology to use.

**Comment by thomasvl** [comment]
There is a small section on the ObjC pages, but we've avoid duplicating the main pages documentation for building protoc since that has changed with time, and having two places vs. one for something can lead to confusion when one gets updated and the other doesn't.  I'm happy to take suggestions for improving the setup docs. Docs can be harder to write/validate the more familiar one is with something, so "fresh eyes" often are better at pointing out the stumbling blocks.

As far as ARC goes, ObjC code doesn't have to use ARC, and in the case of protocol buffers, a lot of developers want them to be as performant as possible, so by not using ARC and manually doing the retains/releases (MRR) within the generated code/runtime library we actually get better performance (and are still completely retain count safe) compared to the the compiler will insert with ARC.

**Comment by Jquery-draggableall-nigh** [comment]
> Yes, I read it, and also finally worked this out, and it kind'a works - although I'm not happy with These non-arc sources. What bothers me, is that google's famous "protobuf" used in no less than 300000 projects - has such a poor support for ObjC - that actually no official documentation states HOW to build the needed components, the existing documentation and pre-built downloads fool you to believe you only need the protoc compiler + some accompanying .proto files to include in your own - and there is absolutely no description or even discussion of the limitations performance envelope or actually any technical aspect of the Obj-C support - let alone not being compatible with Apple's ARC which is here over a decade and is Xcode's default and standard for the last 5 years at least. This neglect is very frustrating - an not really encouraging when selecting a technology to use.





https://lnkr.fun/fc2eee4
