### ISSUE TITLE
Bazel build is broken at HEAD

### ISSUE THREAD

**Issue by damienmg** [google/protobuf#2133]
git bisect says e0e54661f76183684dca66694967a60cbb10f04e is the culprit.

See http://ci.bazel.io/job/protobuf/BAZEL_VERSION=latest,PLATFORM_NAME=darwin-x86_64/376/console for a log

**Comment by damienmg** [comment]
Ping this breakage have been there for 2 weeks now...

**Comment by cgrushko** [comment]
+1

**Comment by xfxyjwf** [comment]
@damienmg Can you help send out a pull request?

**Comment by damienmg** [comment]
If I send one that would be a rollback...

**Comment by damienmg** [comment]
I spend some time investigating and the issue is worse now: there is missing js symbols.

**Comment by damienmg** [comment]
With git bisect run bazel build //:protoc the js culprit is 5a76e633ea9b5adb215e93fdc11e1c0c08b3fc74

**Comment by damienmg** [comment]
@pherl thanks for #2442, it fixes the issue. Can we hook the protobuf repository to our ci so this does not happen again (then you will get PR vetting the same way you have for gRPC)?

**Comment by pherl** [comment]
We will set up the bazel build test, probably Q1 next year.

**Comment by damienmg** [comment]
We already have the hook in place so it's probably a few click on Github for you to get the presubmit from ci.bazel.io if you wish to.

**Comment by pherl** [comment]
@xfxyjwf

**Comment by xfxyjwf** [comment]
@damienmg I can grant you temporary access to protobuf repo. Could you help set up the hook for bazel?

**Comment by damienmg** [comment]
Sure. I can do that next Monday (I am OOO for the rest of the week).

**Comment by xfxyjwf** [comment]
Thanks @damienmg . I have added you as an admin of protobuf repo and create a separate issue: https://github.com/google/protobuf/issues/2450 for setting up the bazel github hook.
