### ISSUE TITLE
PHP protobuf library not available on packagist

### ISSUE THREAD

**Issue by tbillington** [google/protobuf#2136]
The library mentioned in the [Readme](https://github.com/google/protobuf/tree/master/php#installation-from-composer) (google/protobuf) does not exist in packagist and can't be pulled by composer.

```
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package google/protobuf could not be found in any version, there may be a typo in the package name.
```

**Comment by xfxyjwf** [comment]
It hasn't been pushed yet because it's not in any of the releases. Should come soon.

**Comment by tbillington** [comment]
Awesome. Thanks!

**Comment by TeBoring** [comment]
https://packagist.org/packages/google/protobuf
