### ISSUE TITLE
Supported PHP versions are inconsistent

### ISSUE THREAD

**Issue by dhowden** [google/protobuf#2141]
The PHP version required for the pear package is 5.6 (https://github.com/google/protobuf/blob/master/php/ext/google/protobuf/package.xml#L48), but the README says PHP 5.5 or above.

**Comment by TeBoring** [comment]
Thanks for the catch.

**Comment by TeBoring** [comment]
Updated to 5.5.37 in 3.1.x branch.

**Comment by dhowden** [comment]
Awesome - looking forward to 3.1!
