### ISSUE TITLE
Protobuf :  C++ preprocessor "/lib/cpp" fails sanity check

### ISSUE THREAD

**Issue by sujithnss** [google/protobuf#2142]
Hi Team

I'm novice to Protobuf and I was trying installing the same towards as a dependency for my Collected . Where I tried the Protobuf-3.0.2 Tar Gz, I was getting the below error. 

 **C++ preprocessor "/lib/cpp" fails sanity check**

Any help please...I can share the config.log if require.

Best Regards
Sujith P V

**Comment by xfxyjwf** [comment]
You probably don't have the C++ compiler installed on your system:
http://askubuntu.com/questions/509663/c-preprocessor-lib-cpp-fails-sanity-check/509671

If you are using languages other than C++, you can just download the protoc binary from the release page (the protoc-xxx.zip files in the download section).
