### ISSUE TITLE
Support custom options in C#

### ISSUE THREAD

**Issue by jskeet** [google/protobuf#2143]
Currently there's no way of accessing options metadata in the C# API.

**Comment by gabm** [comment]
as some others, we'd also need this feature. Removing the support for custom default values left a little gap that custom extensions could solve.

@jskeet: We're thinking about providing a Pull Request for the custom extension feature in C#. To assess the situation, could you please outline a possible implementation?

**Comment by jskeet** [comment]
I'll see what I can do in the next few days, but it won't be much sooner than that - I'm very busy at the moment on other projects.

@pherl may be able to help out too...

**Comment by jskeet** [comment]
I've been looking at this today, and trying to work out how we can support it reasonably simply without adding too much to the API surface area. One issue is that options can be of any of the various types available - messages, strings, scalars etc.

If FieldDescriptor, MethodDescriptor, MessageDescriptor etc were to have a method such as:

```csharp
IList<ByteString> GetOptions(int fieldNumber)
```

would that be enough to start with? I'd need to also provide a `CodedInputStream` constructor accepting a `ByteString`, but basically the idea would be:

- For messages, you'd just call `YourMessage.Parser.Parse(value)`
- For strings, you'd call `value.ToStringUtf8`
- For byte strings, you'd already have the value
- For scalars, you'd create a `CodedInputStream` and read the value from that

You'd need to know the option's field number, which I wouldn't *initially* be generating any support for. In future, we could potentially generate a helper class for each option, which would know the right type, the field number etc - but that would take quite a bit more work. This "halfway house" would at least unblock users.

Thoughts?

**Comment by gabm** [comment]
@jskeet thanks for your fast reply. 

Actually your suggestion sounds great. I think it would solve the blocking issue. Is this solution a workaround or does it pave the road for the full support one day?

If you need testing, please let me know... we currently use protobuf in C++ and C#, so we could provide comparative testing and examples...

**Comment by jskeet** [comment]
Full support for what, exactly? Custom options, yes. Default values? No.

I'm putting together a pull request, which you could then look at and try for yourself.

**Comment by gabm** [comment]
I meant custom options... Default values won't be re-introduced as I understood.

Thanks, I'll give feedback...

**Comment by jskeet** [comment]
I've created #2317 for this - more testing is needed, but it's a start. In particular, it shows how crude and low-level the code is to retrieve the custom options.

I'd suggest encapsulating that in your own hand-written types to start with - and we can eventually autogenerate them.

I've currently allowed multiple values per option - I need to check whether that's actually reasonable, or whether I should just make the method return a single `ByteString` (or null if it's not found). Repeated options would be "interesting" at that point...

**Comment by gabm** [comment]
Thanks for your fast reply! Protobuf low-level code is :flushed:.

One of my colleagues is currently porting over our current custom message option solution from C++ to C#. I'll give you feedback, once we have a testcase running..

One thought to the multiple values per option solution: although I'm probably not deep enough into protobuf architecture, i see a problem when multiple options have different types. How do you distinguish them before parsing?

**Comment by jskeet** [comment]
@gabm: You'd need to know which option had which type. As I say, eventually we'd be able to generate a class which knows the names, field numbers, wire formats etc... this is a temporary measure which unblocks things for now, without causing problems down the line. Code using it before we make it cleaner should definitely isolate their usage into a single place, of course... keep all the ugliness away from everything else.

I still haven't checked what the deal is in terms of repeated fields etc. Will need to investigate that before going for proper PR review.

**Comment by gabm** [comment]
Aah misunderstood the "repeated options" thing. Somehow thought that `List<ByteString>` could actually contain multiple values of *different* types - nevermind... for sure, we'll encapsulate everything... But in our usecase thats not too limiting since we'd only use one single option for now...

**Comment by gabm** [comment]
We tested your code by retreiving a custom MessageOption from our messages. Everything works as expected, thank you!

For reference, how we retreive the message option on `ProtobufType`, ID field number `1000`:
```
ProtobufType.Descriptor.GetOptions(WireFormat.MakeTag(1000, WireFormat.WireType.Varint)).Single().CreateCodedInput().ReadInt64();
```

**Comment by jskeet** [comment]
Thanks so much for testing - I'm thrilled to hear it worked, even though the code is necessarily ugly.
I'm asking the team about what happens when an option is specified multiple times, to see if I can simplify that. We'll get there :)

**Comment by gabm** [comment]
@jskeet we are currently using the getOptiins feature internally in a custom build and we didn't experience any  problem so far... 

What is the progress on merging upstream? how can we contribute to this process. Would be useful to see this in an official release as at some point as we also need to ship code that's using the getOptions method at some point...

**Comment by jskeet** [comment]
@gabm: Glad to hear it's working for you. No more progress yet - I at least need to add a bunch of tests, which will be a little time consuming. I'd *like* to get codegen for it as well, but that will take longer yet. Early in 2017 I'll try to get what's currently in the PR into master, but then I'm afraid you'll need to wait for the next release. (I don't know the timing of that, I'm afraid.)

If you would like to clone my PR and add some tests, that would certainly help - but I understand if that ends up being somewhat annoying to pick up. Another alternative would be to write some hand-written versions of the code you think we should generate for the options, to help speed up the codegen effort.

**Comment by jskeet** [comment]
@gabm: I've pushed a new version which should make it much easier to use, and also easier to test.

It doesn't yet support repeated options - but I haven't found any examples of where that would occur, or what it would mean in terms of repeated message options. Could you have a look at the [latest commit](https://github.com/google/protobuf/pull/2317/commits/e0126db33da22a6cdf7576a328781b4258e5fc98) - particularly the CustomOptionsTest - and see what you think? If you're happy with that, I think I'm happy to get it reviewed at this point...

**Comment by gabm** [comment]
@jskeet cool, nice to see the commits ;)

Did you introduce a new inteface to retrieve these values? Actually this looks very handy and promising. Unfortunately I cannot give you too much feedback on the tests.

Do you want us to repeat our test using the updated version?

**Comment by jskeet** [comment]
@gabm: No new interface, but there's a new `CustomOptions` class which is used to retrieve the values - you no longer need to worry about creating the right tag and deserializing the value yourself.

**Comment by gabm** [comment]
that comes in very handy - and resolves the "hide your ugly code"-problem a little bit :+1:

**Comment by jskeet** [comment]
It's definitely simpler - you still need to know the field number and the type, but that's all. Eventually I'd like to autogenerate those, but that can come later, definitely.

And the lack of repeated options - would that be an issue for you, as far as you know?

(I need to tidy the PR up a little before getting it reviewed, to remove the previous attempt and to add the relevant files to Makefile.am. Will get on that tomorrow or Friday.)

**Comment by gabm** [comment]
No, no - for us the usecase is very simple. We transport IDs (large random numbers) through the proto file into our custom code and evaluate those externally. Repeated options are definitely not needed. Anyway: I read about some people on stackoverflow that have the same problem and - even though no repeated options are supported - that would be a relieve for those as well.

**Comment by jskeet** [comment]
Excellent - thanks for helping to validate that the fix will help you :)
