### ISSUE TITLE
visual studio c# compilation fails

### ISSUE THREAD

**Issue by jgrandyxignite** [google/protobuf#2148]
VS15 Community Edition

installed NuGet packages :

```
Google.Protobuf
Google.Protobuf.Tools
```

right-click `.proto` file ( known to compile via `protoc` on command-line ) and select "Run Custom Tool".

Error dialog : "The custom tool 'ProtoBufTool' failed."

Can't find any logs.

**Comment by jtattermusch** [comment]
I don't think we currently support any VS2015 integration for compilation for .proto files (Although we gave this some thought in the past). For now, you need to compile your .proto files by invoking `protoc` from commandline yourself.

**Comment by jskeet** [comment]
[ProtoBufTool](https://github.com/mdavid/protobuf-net/blob/master/ProtoBufGenerator/ProtoBufTool.cs) is part of protobuf-net, which is entirely separate from this project.
