### ISSUE TITLE
When will php7 be supported?

### ISSUE THREAD

**Issue by dinoxxx** [google/protobuf#2151]

**Comment by TeBoring** [comment]
ETA is next year.

**Comment by TeBoring** [comment]
For c extension impl, ETA is next year. But you can still use PHP impl for php 7.0.

**Comment by christophermancini** [comment]
@TeBoring has any progress been made towards PHP7 support? Would a PR for v7 support be welcomed?

**Comment by rennekon** [comment]
+1 Very much looking forward to the c extension

**Comment by TeBoring** [comment]
@christophermancini Yeah, that will be very appreciated. In the best, we hope the support for php7 could reuse the code for php5 as much as possible.
