### ISSUE TITLE
make error in php on macos

### ISSUE THREAD

**Issue by thinkerou** [google/protobuf#2155]
Infos:

    cc ${wl}-flat_namespace ${wl}-undefined ${wl}suppress -o .libs/protobuf.so -bundle  .libs/array.o .libs/def.o .libs/encode_decode.o .libs/map.o .libs/message.o .libs/protobuf.o .libs/storage.o .libs/type_check.o .libs/upb.o .libs/utf8.o
    duplicate symbol _protobuf_globals in:
        .libs/array.o
        .libs/def.o
    duplicate symbol _protobuf_globals in:
        .libs/array.o
        .libs/encode_decode.o
    duplicate symbol _protobuf_globals in:
        .libs/array.o
        .libs/map.o
    duplicate symbol _protobuf_globals in:
        .libs/array.o
        .libs/message.o
    duplicate symbol _protobuf_globals in:
        .libs/array.o
        .libs/protobuf.o
    duplicate symbol _protobuf_globals in:
        .libs/array.o
        .libs/storage.o
    duplicate symbol _protobuf_globals in:
        .libs/array.o
        .libs/type_check.o
    ld: 7 duplicate symbols for architecture x86_64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    make: *** [protobuf.la] Error 1

**Comment by TeBoring** [comment]
What's the command you do the make? against which commit? in which directory? What's your environment?

**Comment by thinkerou** [comment]
command:
  
    cd php/ext/google/protobuf
    phpize
    ./configure
    make

env:
   
	➜  protobuf git:(fix_compile_error) ✗ gcc -v
	Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
	Apple LLVM version 7.3.0 (clang-703.0.31)
	Target: x86_64-apple-darwin15.0.0
	Thread model: posix
	InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
	➜  protobuf git:(fix_compile_error) ✗

	➜  protobuf git:(fix_compile_error) ✗ php -v
	PHP 5.6.25 (cli) (built: Aug 21 2016 17:32:27)
	Copyright (c) 1997-2016 The PHP Group
	Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
	    with Xdebug v2.4.0, Copyright (c) 2002-2016, by Derick Rethans

**Comment by TeBoring** [comment]
Sorry, we haven't tested on Mac yet. It's likely the current version cannot compile on Mac. Just a double check, did you compile against the 3.1.x branch?

**Comment by thinkerou** [comment]
Oh, I will try 3.1.x branch firstly.

**Comment by TeBoring** [comment]
Fixed in 3.1.x branch.
