### ISSUE TITLE
The `protoc` embedded in the java artifacts is inconsistent with the protoc release.

### ISSUE THREAD

**Issue by aloiscochard** [google/protobuf#2160]
When compiling using `protoc` version 3.0.0, using the binary release I get deprecation on `valueOf` (asking to use `forNumber` instead).

But when I compile using the `protoc` embedded in the jar, this deprecation is generated, which is concerning as when looking at the code in `v3.0.0` it **must** make that method deprecated.

What is going on? was the java artifact with a badly compiled `protoc`?

(I did try with java release `v3.0.2` but I have the same issue).

Thanks

**Comment by xuwei-k** [comment]
https://github.com/google/protobuf/issues/2054 ?

**Comment by aloiscochard** [comment]
@xuwei-k thanks Kenji, it might be related indeed, unsure if they both have the same cause.

There is an inconsistency between the code here in this repo, and the executable deliverable in the maven artifact, I'm really don't get how that could happen though :-(

**Comment by aloiscochard** [comment]
My bad, I was confused with our scala (sbt) build and missed a dependency.

I still using alpha in some part of the app due to that... sorry for the noise!
