### ISSUE TITLE
Python implementation does not support json_name on descriptors

### ISSUE THREAD

**Issue by jmandel** [google/protobuf#2161]
The python implementation doesn't have awareness of a descriptor's `json_name`, which means that serialization (to JSON) and parsing (from JSON) behave incorrectly when a custom JSON field name has been defined.

It would be good to test the Python implementation against definitions that include custom JSON field names — e.g. `./src/google/protobuf/util/internal/testdata/books.proto`).

---

Example:

```protobuf
message Person {
  string id = 1 [json_name = "@id"];
}
```

An instance should serialize to `{"@id": "my-id"}`, but instead serializes to  `{"id": "my-id"}`:

```python
p = Person()
p.id = "my-id"
json_format.MessageToJson(p)
```

**Comment by acozzette** [comment]
This should be fixed as of 3.1.0, though the fix has not yet made it to the master branch yet. Let me close this for now but feel free to reopen it if you find any issues with 3.1.0.
