### ISSUE TITLE
JsonFormat includingDefaultValueFields doesn't work with oneof

### ISSUE THREAD

**Issue by mariano54** [google/protobuf#2166]
If I have a proto message with oneof, like 

`message SampleMessage {
  oneof test_oneof {
     string name = 1;
     string second_name = 2;
  }
}`

and I convert it to JSON with includingDefaultValueFields set,  the JSON will include both fields (name and second _name). I don't know if this is expected behavior. If is is, then parsing back to protobuf should ignore the default values. When I parse back to protobuf, I'm getting an error because both fields are set in the JSON. 

So protobuf -> JSON -> protobuf is not working.

**Comment by xfxyjwf** [comment]
This is a bug in the JsonFormat implementation. It shouldn't include oneof fields.

**Comment by shashwat** [comment]
Here is the patch and unit test for the same

[2166_patch.txt](https://github.com/google/protobuf/files/497726/2166_patch.txt)

**Comment by xfxyjwf** [comment]
@shashwat Could you send the patch as a pull request?

**Comment by shashwata** [comment]
Sure. I will.

**Comment by xfxyjwf** [comment]
Sorry, it appears the issue was already fixed by this commit:
https://github.com/google/protobuf/commit/1a56251a3582d8b060ca65db6ef1d178c744f81f

**Comment by shashwata** [comment]
Thanks
