### ISSUE TITLE
proto3 lacks TimestampValue

### ISSUE THREAD

**Issue by jgrandyxignite** [google/protobuf#2168]
proto3 adds google.protobuf.Timestamp but not TimestampValue

@jskeet what is recommended way to represent C# nullable DateTime? in proto3 ?

**Comment by jskeet** [comment]
Just use a `Timestamp` field and let it be null when you want it to be - `Timestamp` is just a regular message type. The conversion is simple. Suppose you have:

```text
message Proto {
    Timestamp update = 1;
}
```

and

```csharp
public class Poco {
    public DateTime? Update { get; set; }
}
```

Then converting between them, you'd use (in C# 6):

```csharp
poco.Update = proto.Update?.ToDateTime();
proto.Update = poco.Update == null ? null : Timestamp.FromDateTime(poco.Update);
```

The latter is obviously fairly ugly... you could introduce your own extension method if you need to do this often:

```csharp
public static Timestamp ToTimestamp(this DateTime? dateTime) =>
    dateTime == null ? null : Timestamp.FromDateTime(dateTime);

// And use it like this
proto.Update = poco.Update.ToTimestamp();
```
