### ISSUE TITLE
ByteSize/ByteSizeLong/GetCachedSize idempotent accesses present as data race in open-source TSAN

### ISSUE THREAD

**Issue by vjpai** [google/protobuf#2169]
The ByteSize function generated in C++ triggers a data race in open-source TSAN on `cached_size_` . This is marked as an idempotent and benign data race, but the annotation has no effect. That said, I don't think that C++ supports anything other than catch-fire semantics on any data race, including idempotent writes, so I'm not sure that an annotation is really effective as a matter of course.

**Comment by vjpai** [comment]
We have seen this issue in grpc/grpc#8174 and are working around it with grpc/grpc#8188

**Comment by xfxyjwf** [comment]
The annotation's sole purpose is to suppress TSAN warnings. If it doesn't have effect, we are either using the wrong annotation for opensource, or there is some problem in TSAN to recognize the annotations.

**Comment by haberman** [comment]
I agree with your assessment that the current situation is a data race per the standard. However I think it would be very difficult to change this to not have the idempotent write. I think annotations are the way to go for the foreseeable future.

**Comment by xfxyjwf** [comment]
We actually can use atomicops to avoid this race, but it's considered not worthwhile to change.

**Comment by vjpai** [comment]
This did not trigger a warning for us until very recently. I am not sure if it is because we have just improved our tests, or if it is because thread sanitizer is stricter than it was before.

**Comment by haberman** [comment]
@xfxyjwf That is a great point. If C++11 is available we could emit this as:

```c++

void FileDescriptorSet::SetCachedSize(int size) const {
  ANNOTATE_IGNORE_WRITES_BEGIN();
  _cached_size_.store(size, std::memory_order_relaxed);
  ANNOTATE_IGNORE_WRITES_END();
}
```

I verified that this produces exactly the same code as we get right now: a single store without any special synchronization emitted.

**Comment by vjpai** [comment]
Mind if I try sending that as a PR? I want to make sure that it won't hurt
our portability with gcc4.4+

**Comment by vjpai** [comment]
Or if you already have it as a PR, I can test it out on our portability
suite.

**Comment by xfxyjwf** [comment]
We can't use C++11 atomics, and the [atomicops support in protobuf](https://github.com/google/protobuf/blob/master/src/google/protobuf/stubs/atomicops.h) is far from a standard. For now I think I would prefer figuring out why the annotations is not working and fixing that.

And how does this hurt portability?

**Comment by vjpai** [comment]
It looks like there will be no portability issue. gcc4.4+ supports atomic and memory_order_relaxed; but it sounds like that's a moot issue if you can't use C++11 atomics for other reasons.

**Comment by haberman** [comment]
For the moment we are trying to support C++98 compiles.

**Comment by vjpai** [comment]
This now appears in ByteSizeLong . Changing title.

**Comment by anand2404** [comment]
Can you please describe the race condition ? I am hitting this issue on Windows where an assert is failing in proto_utils.h (/include/grpc++/impl/codegen) (line 185 in https://github.com/grpc/grpc/blob/master/include/grpc%2B%2B/impl/codegen/proto_utils.h as at the time of this comment) :

```
1 static Status Serialize(const grpc::protobuf::Message& msg,
 2                         grpc_byte_buffer** bp, bool* own_buffer) {
 3   *own_buffer = true;
 4   int byte_size = msg.ByteSize();
 5   if (byte_size <= internal::kGrpcBufferWriterMaxBufferLength) {
 6     grpc_slice slice = g_core_codegen_interface->grpc_slice_malloc(byte_size);
 7     GPR_CODEGEN_ASSERT(
 8         GRPC_SLICE_END_PTR(slice) ==
 9         msg.SerializeWithCachedSizesToArray(GRPC_SLICE_START_PTR(slice)));
10     *bp = g_core_codegen_interface->grpc_raw_byte_buffer_create(&slice, 1);
11     g_core_codegen_interface->grpc_slice_unref(slice);
12     return g_core_codegen_interface->ok();
13   } else {
14     internal::GrpcBufferWriter writer(
15         bp, internal::kGrpcBufferWriterMaxBufferLength);
16     return msg.SerializeToZeroCopyStream(&writer)
17                ? g_core_codegen_interface->ok()
18                : Status(StatusCode::INTERNAL, "Failed to serialize message");
19   }
20 }
```

The assert at Line 7 in the above code is failing. In the application dump, I see that :
`msg._cached_size_ = slice.data.refcounted.length`
So, going by that, when slice was allocated, the `msg.ByteSize()` call on line 4 gave the correct info. However, `msg.SerializeWithCachedSizesToArray()` which is based off the cached size is serializing a different data size (most probably more since the message here has, amongst a few other members, a 4K buffer (which is the major chunk) and I can match the beginning and end of the data in slice against the data in msg - so at least that 4K block was serialized)

**Comment by gerben-s** [comment]
Fixed in next down-integration
