### ISSUE TITLE
javanano codegen error when there's only one message in the proto file.

### ISSUE THREAD

**Issue by zsurocking** [google/protobuf#218]
Javanano codegen fails when there's only one message in the proto file:

syntax = "proto3";
message a {
}

The error complains about irrelevant stuff: 
Javanano generator has changed to align with java generator. An outer class will be created for this file and the single message in the file will become a nested class. Use java_multiple_files to skip generating the outer class, or set an explicit java_outer_classname to suppress this message.

Adding another message to the proto file fixes the issue.

Commadline:
protoc --javanano_out=. a.proto

**Comment by pherl** [comment]
This message is intended for warn legacy nano users that there will be an outer class generated. You can set the java_outer_classname to suppress the warning message. Also in your example, the message name is the same with the file name, which will lead to conflicted outer classname and nested message name. Setting the java_outer_classname option should make the code compile.
