### ISSUE TITLE
Proposal for a 128 bit type

### ISSUE THREAD

**Issue by awalterschulze** [google/protobuf#2180]
These days people communicating uuids and ipv6 addresses between processes is quite common.  These can both be addressed with a 128 bit type.

Just to give an idea of how many users already want this and hack around this.
I have protobuf code generator for go (gogoprotobuf) and I have added a feature called customtype.  This allows you to change a bytes type to a type of your choice, but still transfer it as bytes.  This allows for quite a large variety of applications, but what people use it for is very constraint.   Most users just want some 128bit type.

**Comment by acozzette** [comment]
Transferring this type as bytes (i.e. with the length-delimited wire type) sounds like a good idea. That way we would have the option of implementing it first just for one or two languages, and other languages without support for it could at least handle the data gracefully (e.g. by treating it as an unknown field or just a bytes field). I wonder what the API would look like since as far as I know most languages don't have a standard 128-bit type--maybe just the raw array of 16 bytes?

**Comment by awalterschulze** [comment]
perfect :)

**Comment by pascaldekloe** [comment]
For Go you can do this nicely with a [16]byte into the struct so no extra malloc. Same goes for C when you expose the length as a constant.
How would one do that for Java? Two (signed) long? :-( Just a byte array couses marshalling errors on size mismatch. A generated class with fields byte0 to byte15?

**Comment by awalterschulze** [comment]
Why is this closed?

**Comment by mbautin** [comment]
+1 to this feature request -- we could make a good use of it in [YugaByte DB](https://github.com/yugabyte/yugabyte-db) as well, for UUIDs, IPv6 addresses, MVCC timestamps, etc.

**Comment by loyd** [comment]
Any progress?

**Comment by pascaldekloe** [comment]
I'm trying to get this one right at pascaldekloe/colfer#36. Feedback wanted.

**Comment by dzmitry-lahoda** [comment]
u128 is pervasive in blockchains

**Comment by pascaldekloe** [comment]
The need is clear. No need for more use-cases here please. Same with the status requests. Unless you have something to contribute, this feature is pending on some serious work.

**Comment by dzmitry-lahoda** [comment]
@pascaldekloe 

> Unless you have something to contribute, this feature is pending on some serious work.

So you say this repo is open to accept PR with u128 support?

**Comment by pascaldekloe** [comment]
Certainly @dzmitry-lahoda. Please do a final byte array for Java.

In v2 branch you may find SPEC.md to help with inspiration. It has an opaque n-byte type which can be bound to intergers or bytes depending on compilation options.
