### ISSUE TITLE
[pecl] Please provide a LICENSE file.

### ISSUE THREAD

**Issue by remicollet** [google/protobuf#2185]
Missing with role="doc" in package.xml

**Comment by TeBoring** [comment]
The licence file is in the root directory.
What do you mean by missing with role="doc" in package.xml? Is this is separate problem?

**Comment by remicollet** [comment]
The LICENSE file is missing in the distributed archive (usually generated from a package.xml, where documentation file must be listed using the role="doc") 
=> https://pecl.php.net/get/protobuf-3.1.0a1.tgz

**Comment by TeBoring** [comment]
Since the package.xml already has <license> field. Is the LICENSE file still needed?

**Comment by remicollet** [comment]
> Since the package.xml already has field. Is the LICENSE file still needed?

Yes (field is only the License name, not the full text)

**Comment by TeBoring** [comment]
In all source files, we have included the text. Is it ok? BTW, is there any place explicitly say the LICENSE is a requirement? I see a lot of projects missing that file.

**Comment by remicollet** [comment]
From license term

```
//     * Redistributions of source code must retain the above copyright
// notice, this list of conditions and the following disclaimer.
```

> In all source files, we have included the text.

So this clause is satisfy.

```
//     * Redistributions in binary form must reproduce the above
// copyright notice, this list of conditions and the following disclaimer
// in the documentation and/or other materials provided with the
// distribution.
```

Only the LICENSE file can satisfy this clause.
Else, anyone using the pecl archive and distributing binary package (microsoft DLL, .rpm, .deb... will violate the License).

Ex see the content of http://windows.php.net/downloads/pecl/releases/zip/1.13.5/php_zip-1.13.5-7.1-nts-vc14-x86.zip
Ex, with an rpm
```
# rpm -ql php-pecl-zip
/etc/php.d/40-zip.ini
/usr/lib64/php/modules/zip.so
/usr/share/licenses/php-pecl-zip/LICENSE
...

```

**Comment by remicollet** [comment]
For more information about "license text", read https://fedoraproject.org/wiki/Packaging:LicensingGuidelines?rd=Packaging/LicensingGuidelines#License_Text

**Comment by TeBoring** [comment]
Because the LICENSE file is in our root dir (https://github.com/google/protobuf/blob/master/LICENSE), if we include it here, the pecl package dir structure will be weird. Nor do we want to have two LICENSE in our repository.
Since the package uploaded to pecl may not be exactly the same, can we include a LICENSE in the package we uploaded, but leave it missing in the github?

**Comment by remicollet** [comment]
A symlink should do the trick

**Comment by TeBoring** [comment]
Can symlink point to a http address? Note that in the pecl package https://github.com/google/protobuf/blob/master/LICENSE is not actually included, so a symlink will point to nothing in the pecl.

**Comment by TeBoring** [comment]
I prefer to just include the LICENSE in our released pecl package. Does that work for you?

**Comment by remicollet** [comment]
Symlink works
https://github.com/google/protobuf/pull/3029

**Comment by TeBoring** [comment]
https://pecl.php.net/package/protobuf
Added license file.

**Comment by remicollet** [comment]
In package.xml

   <file baseinstalldir="/" md5sum="35953c752efc9299b184f91bef540095" name="LICENSE" role="src" />

role should be "doc", not "src"

**Comment by remicollet** [comment]
```
$ tar xvf protobuf-3.3.0.tgz 
package.xml
protobuf-3.3.0/LICENSE
protobuf-3.3.0/config.m4
protobuf-3.3.0/array.c
protobuf-3.3.0/def.c
protobuf-3.3.0/encode_decode.c
protobuf-3.3.0/map.c
protobuf-3.3.0/message.c
protobuf-3.3.0/protobuf.c
protobuf-3.3.0/protobuf.h
protobuf-3.3.0/storage.c
protobuf-3.3.0/type_check.c
protobuf-3.3.0/upb.c
protobuf-3.3.0/upb.h
protobuf-3.3.0/utf8.c
protobuf-3.3.0/utf8.h
protobuf-3.3.0/LICENSE
```

And LICENSE is there twice, once as "src", one as "doc" ;)

**Comment by TeBoring** [comment]
Is it a must-fix bug? Can we fix it in next release?

**Comment by TeBoring** [comment]
@stanley-cheung to take a look

**Comment by remicollet** [comment]
> Is it a must-fix bug? Can we fix it in next release?

Yes, can wait next version

**Comment by stanley-cheung** [comment]
Ah I might have messed up while experimenting with stuff. Will fix next release.
