### ISSUE TITLE
[pecl] PHP 7 support

### ISSUE THREAD

**Issue by remicollet** [google/protobuf#2187]
PHP 7+ is not supported

**Comment by TeBoring** [comment]
This is a know issue. Will provide support in future release.

**Comment by isublimity** [comment]
+1 wait

**Comment by frankiefanstar** [comment]
Will you release the version support php7 in December?We are looking forward for it.

**Comment by lexa-uw** [comment]
+1 wait too

**Comment by jcchavezs** [comment]
+1

**Comment by GaryMarks** [comment]
+1

**Comment by hfyiyue** [comment]
+1
