### ISSUE TITLE
Visual Studio 2015 with update 3 can't open csharp/src/Google.Protobuf.sln

### ISSUE THREAD

**Issue by mohusheng** [google/protobuf#2194]
Visual Stuido's Version is 14.0.25431.01 Update3
Protobuf' Version is 3.1.0

**Comment by zelon** [comment]
Same environment and same version. And my visual studio shows below error:

P:\Download\protobuf-csharp-3.1.0\protobuf-3.1.0\csharp\src\AddressBook\AddressBook.xproj : error  : The imported project "C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.  P:\Download\protobuf-csharp-3.1.0\protobuf-3.1.0\csharp\src\AddressBook\AddressBook.xproj

P:\Download\protobuf-csharp-3.1.0\protobuf-3.1.0\csharp\src\Google.Protobuf\Google.Protobuf.xproj : error  : The imported project "C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.  P:\Download\protobuf-csharp-3.1.0\protobuf-3.1.0\csharp\src\Google.Protobuf\Google.Protobuf.xproj

P:\Download\protobuf-csharp-3.1.0\protobuf-3.1.0\csharp\src\Google.Protobuf.Test\Google.Protobuf.Test.xproj : error  : The imported project "C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.  P:\Download\protobuf-csharp-3.1.0\protobuf-3.1.0\csharp\src\Google.Protobuf.Test\Google.Protobuf.Test.xproj

P:\Download\protobuf-csharp-3.1.0\protobuf-3.1.0\csharp\src\Google.Protobuf.Conformance\Google.Protobuf.Conformance.xproj : error  : The imported project "C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.  P:\Download\protobuf-csharp-3.1.0\protobuf-3.1.0\csharp\src\Google.Protobuf.Conformance\Google.Protobuf.Conformance.xproj

P:\Download\protobuf-csharp-3.1.0\protobuf-3.1.0\csharp\src\Google.Protobuf.JsonDump\Google.Protobuf.JsonDump.xproj : error  : The imported project "C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.  P:\Download\protobuf-csharp-3.1.0\protobuf-3.1.0\csharp\src\Google.Protobuf.JsonDump\Google.Protobuf.JsonDump.xproj

It seems that visual studio cannot find "C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet" directory and the directory does not exist in my windows.

Should I install additional sdk like dotnet cli?

**Comment by jskeet** [comment]
Yes, the C# support library uses the .NET Core tooling, so you'll need to install that before you can open the project.

**Comment by mirsking** [comment]
Hi there, although I have installed this,  https://www.microsoft.com/net/core#windowscmd , I still met the same error. Anything more need to be done? Thank you.

**Comment by jskeet** [comment]
@mirsking: Unfortunately the situation with .NET Core is slightly fiddly. We're currently still on project.json - you need the 1.0.0-preview2-003131 SDK. On the page you were on, download "NET Core tools Preview 2 for Visual Studio 2015".

I'm hoping that some time this quarter we'll be moving to msbuild and the .NET Core 1.1 SDK, at which point you'll need Visual Studio 2017, but we'll no longer be on preview SDKs.
