### ISSUE TITLE
Failed to compile proto file with map<string, string>

### ISSUE THREAD

**Issue by yang-g** [google/protobuf#220]
Using installed open source version of 3.0.0 alpha1, when building my example, it failed with:

make pubsub_client
[PROTOC]  Generating protobuf CC file from examples/pubsub/empty.proto
[CXX]     Compiling gens/examples/pubsub/empty.pb.cc
[PROTOC]  Generating protobuf CC file from examples/pubsub/pubsub.proto
[CXX]     Compiling gens/examples/pubsub/pubsub.pb.cc
In file included from ./gens/examples/pubsub/pubsub.pb.h:29:0,
                 from gens/examples/pubsub/pubsub.pb.cc:5:
/usr/local/include/google/protobuf/map.h:35:40: fatal error: google/protobuf/stubs/hash.h: No such file or directory
 #include <google/protobuf/stubs/hash.h>
                                        ^
compilation terminated.
make: *** [objs/opt/./gens/examples/pubsub/pubsub.pb.o] Error 1

It seems to me /usr/local/include/google/protobuf/stubs does not have hash.h.

**Comment by pherl** [comment]
This has  been fixed in the reset alpha-2 release.
