### ISSUE TITLE
Ruby: require error when using well-known types

### ISSUE THREAD

**Issue by kmontag** [google/protobuf#2205]
Gem Version: 3.1.0

It looks like the WKT files packaged with the gem had their names changed in one of the recent releases, from e.g. `lib/google/protobuf/wrappers.rb` to `lib/google/protobuf/wrappers_pb.rb`. This breaks the generated require statement in a message like:

```protobuf
import "google/protobuf/wrappers.proto";
message Foo {
  google.protobuf.StringValue bar = 1;
}
```

**Comment by xfxyjwf** [comment]
We decided to rename the generated ruby file to xxx_pb.rb to be consistent with other languages before releasing 3.0.0. So the file name change was done in 3.0.0 release, not 3.1.0. If you are upgrading from the alpha/beta versions to 3.1.0, fixing the file names would be required.

**Comment by xfxyjwf** [comment]
@haberman I remember we kept the old generated file in 3.0.0. Is it removed in 3.1.0 release?

**Comment by kmontag** [comment]
@xfxyjwf sorry, looks like there was a mismatch between the gem version and the `protoc` binary I was testing with - no issues when both are at 3.1.0. Thanks for the quick response.

**Comment by haberman** [comment]
@xfxyjwf Yes I believe in the end we decided not to put old generated files in 3.0.0.
