### ISSUE TITLE
OSAtomicCompareAndSwap64Barrier is  deprecated in macOS 10.12

### ISSUE THREAD

**Issue by izouxv** [google/protobuf#2207]
In file included from no_warning_test.cc:2:
In file included from ./google/protobuf/stubs/atomic_sequence_num.h:33:
In file included from ./google/protobuf/stubs/atomicops.h:199:
./google/protobuf/stubs/atomicops_internals_macosx.h:173:9: error: 'OSAtomicCompareAndSwap64Barrier' is
      deprecated: first deprecated in macOS 10.12 - Use std::atomic_compare_exchange_strong() from
      <atomic> instead [-Werror,-Wdeprecated-declarations]
    if (OSAtomicCompareAndSwap64Barrier(

**Comment by acozzette** [comment]
Thanks for reporting this, @izouxv. This looks like a duplicate of issue #2182, though, so let me close this one and we can continue the discussion there.
