### ISSUE TITLE
Compile Time Error Objective-C in generated .m File , Xcode 8 , Proto3

### ISSUE THREAD

**Issue by AzAli71** [google/protobuf#2208]
hi , after that protoc Generate Objective C files the Xcode Shows Error in **defaultValue** and **fieldOptions** in .m generated file
Xcode 8 , Prorto Syntax 3 
Error message is : **field designator 'fieldOptions' does not refer to any field in type 'GPBMessageFieldDescription' (aka 'struct GPBMessageFieldDescription' )**
and 
**field designator 'defalutValue' does not refer to any field in type 'GPBMessageFieldDescription' (aka 'struct GPBMessageFieldDescription' )**

**Comment by AzAli71** [comment]
<img width="1003" alt="screen shot 2016-09-29 at 7 20 21 pm" src="https://cloud.githubusercontent.com/assets/16123809/18981057/861df010-86e7-11e6-8429-3c81ff5f612b.png">

**Comment by sergiocampama** [comment]
Can you try updating your protoc binary version? I believe that your generated sources are too old for the runtime library that you're linking with...

You can update protoc by running make and make install at the root of the protobuf directory...

**Comment by sergiocampama** [comment]
or you can also download it from here: https://github.com/google/protobuf/releases/download/v3.1.0/protoc-3.1.0-osx-x86_64.zip

**Comment by AzAli71** [comment]
yes sure , this is link of my Project , simple Project with Protocol Buffer in IOS with Objective C
https://1drv.ms/f/s!AkvXNAVlXB4lgZElGu3USUaXbDmplQ
you can See my GeneratedFile in 'PorotoFiles' Directory
the Content of .proto file is :  

**syntax = "proto3";
package kotancode;
message MySample {
    string name = 1;
    double longitude = 2;
    double latitude = 3;
    string description = 4;
}**

I find this sample ( Content of .proto file) from the Internet and protoc Compile it and Generate Test.pbobjc.h and Test.pbobjc.m Correctly but Xcode Shows Error in Test.pbobjc.m !

**Comment by sergiocampama** [comment]
yes, protoc is old, you need to download a new protoc

download https://github.com/google/protobuf/releases/download/v3.1.0/protoc-3.1.0-osx-x86_64.zip, unzip and use that protoc to generate Test.pbobjc.h and Test.pbobjc.m

also update Podfile to Protobuf 3.1.0

**Comment by sergiocampama** [comment]
I also see that your sample project commented out an #error statement, which should prevent you from using different versions between generated code and runtime library... please update your protoc as specified in my previous comment and also update your podfile to use the 3.1.0 version

**Comment by thomasvl** [comment]
The \#error you seem to have commented out in the generated header was trying to tell you about the mismatch.  Everything else that happens because of the mismatch doesn't really matter.

**Comment by AzAli71** [comment]
@sergiocampama yes Problem fixed , 
thank you **I used brew install protobuf** and then I have protoc 3.0.0 after I upgrade my protoc to 3.1.0 the Problem fixed ;)
