### ISSUE TITLE
Android Netty protobuf decode error

### ISSUE THREAD

**Issue by 925941723** [google/protobuf#2209]
I used python as server to send message,and Android phone received it.But it has something wrong in my Android code.It is:   
        Caused by: com.google.protobuf.InvalidProtocolBufferException: Protocol message contained an invalid tag (zero).
       I used the same .proto file to create different file by --python and --java orders.
       The following is my code:

python:
       entity = SubscribeRespProto_pb2.SubscribeRespProto()
       entity.subReqID = 1
       entity.userName = "H2901"
       entity.productName = "qao"
        entity.address = "guangzhou"
        content = entity.SerializeToString()
        print(str(entity))
        proto.transport.write(content)

Android(Netty 4.15):
         Bootstrap bootstrap = new Bootstrap();
         bootstrap.group(eventLoopGroup)
         .channel(NioSocketChannel.class)
         .option(ChannelOption.SO_KEEPALIVE, true)
         .handler(new ChannelInitializer() {
         @Override
         protected void initChannel(SocketChannel socketChannel) throws Exception {
                 socketChannel.pipeline().addLast(new ProtobufVarint32FrameDecoder())
                 .addLast(new ProtobufDecoder(SubscribeReqProto.SubscribeReq.getDefaultInstance()))
                 .addLast(new ProtobufVarint32LengthFieldPrepender())
                 .addLast(new ProtobufEncoder())
                 .addLast(new SubReqClientHandler());
                 }
         });
         channelFuture = bootstrap.connect(Constants.IP, Constants.PORT).sync();

.proto:
 message SubscribeRespProto{
         required int32 subReqID = 1;
         required string userName = 2;
         required string productName = 3;
         required string address = 4;
 }

**Comment by xfxyjwf** [comment]
You might want to check if the bytes serialized by the sender is identical with the bytes received by the parsing side first.

**Comment by 925941723** [comment]
Thanks for your help.I find the reason.Because in Android code I add:
.addLast(new ProtobufVarint32FrameDecoder())
.addLast(new ProtobufVarint32LengthFieldPrepender()).
It means insert 32 integer field in the begin,and decode it same.
But I haven't do it in Python code.So just delete this two lines code is ok.
