### ISSUE TITLE
jspb.Message.getFieldProto3  Undefined for google-protobuf 3.1.0 

### ISSUE THREAD

**Issue by MedGhassen** [google/protobuf#2210]
Hi , 
I'have just update my node modules , google-protobuf got update to 3.1.0 . Then the serializeBinary function from the generate js files does not Work any more and it says thatTypeError: jspb.Message.getFieldProto3 is not a function.
Any Idea ? 
With the Version 3.0.0 It works Fine.
Thanks

**Comment by acozzette** [comment]
@haberman has a fix for this here: https://github.com/google/protobuf/pull/2196 It's on the 3.1.x branch but I'm not sure if it has been published via npm yet.

**Comment by xfxyjwf** [comment]
@haberman what's the status of 3.1.1 release for JS? Is it blocked by something?

**Comment by haberman** [comment]
3.1.1 is released with the fix for this bug.
