### ISSUE TITLE
GCC 5.2: enumeral and non-enumeral type in conditional expression

### ISSUE THREAD

**Issue by drivehappy** [google/protobuf#2211]
When attempting to compile a generated *.cc file that includes a protobuf map<K,V>, the following warning is produced:

> .../src/google/protobuf/map.h:1285:32: warning: enumeral and non-enumeral type in conditional expression [-Wextra]
>       return n < kMinTableSize ? kMinTableSize : n;

We have warning to error conversion turned on ("-Werror"), and causes our build to fail. It looks like #1900 was also opened for this, but seems to be closed incorrectly - as the solution was posted, but not actually address in the protobuf sources.

Unfortunately, there doesn't seem to be an easy way in GCC to simply disable this particular warning.

**Comment by xfxyjwf** [comment]
Could you help send us a pull request to fix that?
