### ISSUE TITLE
Java: New Runtime Proposal

### ISSUE THREAD

**Issue by nmittler** [google/protobuf#2220]
Today's generated code does all the heavy lifting (serialization/deserialization, merging, etc.). Every field adds baggage to nearly every method. This leads to problems (many of which are described in #1852):
- Broad ABI between the generated code and the runtime
  - Refactoring the runtime is incredibly difficult
  - Generated code may require certain versions of the runtime
- Generates a ton of boilerplate code
  - This is a big problem on Android
  - Can’t fix bugs or improve performance without regenerating code

The attempt here is to begin discussion for a new runtime that will address (or eliminate) these issues.

For experimentation, I've created the [java_experimental](https://github.com/google/protobuf/tree/java_experimental) branch. PR #2216 is an initial attempt that moves functionality into the runtime. It makes use of "schemas", which are dynamically generated runtime components that implement various capabilities (e.g. serialization) on behalf of the message.
# Schema Creation

Before we can create a [Schema](https://github.com/google/protobuf/blob/java_experimental/java/core/src/main/java/com/google/protobuf/Schema.java), we need to reflect on a given protobuf message to generate a [MessageInfo](https://github.com/google/protobuf/blob/java_experimental/java/core/src/main/java/com/google/protobuf/MessageInfo.java).  This is currently done in one of two ways:
1. For standard proto, we just transform Descriptor -> MessageInfo
2. For android (proto lite), we use annotations on the fields of the message and manually parse the Dex. _The code for this is not currently in github._
# Schema Types

There are currently two types of schema implementations:
1. Table-based
   - Information for all fields of a given message is stored in a `ByteBuffer` (e.g. [Proto2Manifest](https://github.com/google/protobuf/blob/java_experimental/java/core/src/main/java/com/google/protobuf/Proto2Manifest.java#L70))
   - The same class will work for any message
   - Code size stays constant as # messages increases
   - Only schema supported on Android
2. Bytecode generation (via ASM)
   - Slower to create
   - Faster at runtime
   - Additional bytecode is generated for each message type
   - _The code for this is not currently on github_
# Runtime API

The new [runtime API](https://github.com/google/protobuf/blob/java_experimental/java/core/src/main/java/com/google/protobuf/Protobuf.java) will provide the capabilities to the application.  Ideally, this will lead to generated code becoming little more than POJOs where the application will interact with the runtime directly.  However, for existing code we can have an intermediate step where we still generate all of the methods, but they simply delegate to the runtime.
# Bechmarks

Initial Benchmarks (the code is not yet on github ... stay tuned!) show overall performance wins for the new code.
## Serialization

```
(schemaType)                  Score      Error  Units
PROTO2                        27193.351 ±  542.185  ops/s
PROTO3                        27910.265 ±  447.149  ops/s
GENERIC_PROTO2_TABLE          46455.018 ± 3189.952  ops/s
GENERIC_PROTO2_LOOKUP         48501.404 ±  572.482  ops/s
GENERIC_PROTO3_TABLE          48214.251 ±  677.677  ops/s
GENERIC_PROTO3_LOOKUP         44418.246 ± 4995.708  ops/s
ASM_PROTO3                    58715.064 ±  731.199  ops/s
```

To be fair, the new runtime uses a reverse-writing serializer which avoids the size calculation cost.
Adding reverse writing to current proto implementation has been determined infeasible due to the extra code bloat required.
## Deserialization

```
(schemaType)                   Score     Error  Units
PROTO2                         15099.911 ±  93.873  ops/s
PROTO3                         14573.616 ± 177.748  ops/s
GENERIC_PROTO2_TABLE           20058.241 ± 440.657  ops/s
GENERIC_PROTO2_LOOKUP          20092.639 ± 110.975  ops/s
GENERIC_PROTO3_TABLE           20402.281 ± 447.267  ops/s
GENERIC_PROTO3_LOOKUP          19582.969 ± 733.465  ops/s
ASM_PROTO3                     22213.371 ± 494.667  ops/s
```

Again to be fair, the new code is able to leverage some optimizations:
- Switches on field number (rather than tag). Higher chance of tableswitch (O(1)) rather than lookup switch (O(logn)).
- Lists are read all at once rather than field by field
  - Reduces overhead introduced by virtual method calls on the Reader

**Comment by nmittler** [comment]
FYI @louiscryan @xfxyjwf  @pherl @danielweis @normanmaurer @Scottmitch @jhump

**Comment by swankjesse** [comment]
Please borrow liberally from Wire, which has a Schema-like type called [ProtoAdapter](https://square.github.io/wire/2.x/wire-runtime/com/squareup/wire/ProtoAdapter.html). We have both reflection and codegen implantations.
