### ISSUE TITLE
iOS Cocoapod Errors

### ISSUE THREAD

**Issue by larromba** [google/protobuf#2222]
Using Cocoapods 1.0.1

**Podspec**
```
s.dependency 'Protobuf', '3.0.2'
s.pod_target_xcconfig = { 'GCC_PREPROCESSOR_DEFINITIONS' => '$(inherited) GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS=1' }
```

**Steps**
* Build .proto file
* Include .pbobjc.h / .m into xcode project (development pod folder) with ```-fno-arc-objc```
* ```pod install```

**Outcome**
* ```GPB_DEBUG_CHECK_RUNTIME_VERSIONS();``` implicit declaration invalid in C99
* ```GOOGLE_PROTOBUF_OBJC_VERSION``` is < 30002
* ```GPBDescriptorInitializationFlag_None``` not found. XCode's Suggested replacement ```GPBDescriptorInitializationFlag_WireFormat```

**Workaround**
* Comment out ```GPB_DEBUG_CHECK_RUNTIME_VERSIONS();```
* Comment out ```GOOGLE_PROTOBUF_OBJC_VERSION``` check
* Updated podspec to: ```s.pod_target_xcconfig = { 'GCC_PREPROCESSOR_DEFINITIONS' => '$(inherited) GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS=1 GOOGLE_PROTOBUF_OBJC_VERSION=30002'```
* Changed ```GPBDescriptorInitializationFlag_None``` to 0

**Question**
Is this a protobuf ios sdk bug when using protobuf 3.0.2 as a cocoapod dependancy?

**Comment by thomasvl** [comment]
Sounds like you aren't using the protoc that comes from 3.0.2 branch and instead using one from 3.1.  Are you mixing a different protoc from the version of the library you are using?

**Comment by larromba** [comment]
Thanks - yes, I updated my podspec to:

```s.dependency 'Protobuf', '3.1.0'```

and the problems went away

**Comment by mmdongxin** [comment]
s.pod_target_xcconfig = { 'GCC_PREPROCESSOR_DEFINITIONS' => '$(inherited) GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS=1}
