### ISSUE TITLE
How to get extension's filed without extension identifier?

### ISSUE THREAD

**Issue by zer0-x** [google/protobuf#2225]
How can I access all fields (including extension's field) from a message without getting the extension using extension identifier?
Refelection::ListFields does return a list of fields but I couldn't access fields of extension there.

**Comment by zer0-x** [comment]
Closed, actually there's no way, we need to use GetExtension, MutableExtension, etc,...

**Comment by xfxyjwf** [comment]
You access extension fields the same way as regular fields in reflection API. For example, if the extension type is a message, just use Reflection::GetMessage(message, field) to get the extension field.
