### ISSUE TITLE
Optional primitives in proto3 (feature idea)

### ISSUE THREAD

**Issue by ejball** [google/protobuf#223]
As regards the removal of presence logic for primitives in proto3, I wonder if you could consider supporting `nullable<T>`.

It would be like `map<K,V>`, but for primitives that need presence logic. For example, these messages could be effectively equivalent:

```
message A {
  nullable<string> name = 1;
}
message B {
  message NullableString {
    string value = 1;
  }
  NullableString name = 1;
}
```

I'd certainly be open to a better name. Perhaps `optional<string>`, if it isn't too confusing, since `optional` means something somewhat different in proto2.

**Comment by pherl** [comment]
There will be well know types added in the default protobuf runtime in the next release. See the wrappers.proto:
https://github.com/google/protobuf/blob/96e379ff8bc6907d044c62c1381b8e5a793b6a7a/src/google/protobuf/wrappers.proto
It provides field presence info for primitive fields without introducing new syntax. Runtime libraries that support well know types may choose to use a more efficient representation for the messages (or provide additional functions). Binary format will be compatible as if they are normal wrapper messages.
