### ISSUE TITLE
NodeJS Callback Functions.

### ISSUE THREAD

**Issue by vish74** [google/protobuf#2237]
I am creating RPC service with Empty response parameter.
`rpc Disconnect (getDisconnect) returns (Empty) {}`

Client code is in Javascript. Why do I need to write return callback function?

`client.disconnect({status:0});` 
throws 
`Error: parameter 'callback' waiting for Function argument but received Undefined`

As far I know, gRPC or protobuf documents don't mention anywhere that callback functions are mandatory. Is there any workaround?

**Comment by acozzette** [comment]
@vish74, this sounds like more of a gRPC question so you might have better luck opening an issue at https://github.com/grpc/grpc. My guess is that the right thing to do would be to just pass a do-nothing callback if you don't actually need to take any action in the callback.

**Comment by vish74** [comment]
@acozzette thanks for the reply. I am calling "do-nothing" callbacks only. As there is no way of calling unary RPC request with protobuf.
From my understanding, proto definition is part of grpc's module argue.js, which verifies all the parameters. I need to dive-in more into gRPC code.
