### ISSUE TITLE
32 bit windows ruby protobuf failing to load native library

### ISSUE THREAD

**Issue by apolcyn** [google/protobuf#2247]
I'm having trouble with the native ruby protobuf library failing to load on 32-bit windows ruby.

To reproduce:

on 32-bit windows ruby (using version 2.2.4 but I think any 32-bit version should do).

install google-protobuf:
`gem install google-protobuf`

output of `gem list google-protobuf` is now:
`google-protobuf (3.1.0 x86-mingw32)`

The ruby file containing:

```
puts "ruby version: #{RUBY_VERSION}"
puts "ruby platform: #{RUBY_PLATFORM}"

require 'google/protobuf'
```

when ran should output:

```
C:/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- google/protobuf_c (LoadError)
        from C:/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/google-protobuf-3.1.0-x86-mingw32/lib/google/protobuf.rb:50:in `rescue in <top (required)>'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/google-protobuf-3.1.0-x86-mingw32/lib/google/protobuf.rb:47:in `<top (required)>'
        from C:/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `require'
        from C:/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
        from C:/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:39:in `require'
        from trial.rb:4:in `<main>'
ruby version: 2.2.4
ruby platform: i386-mingw32
```

taking a look at this, it looks like it fails to load `google/2.2/protobuf_c` (google/2.2/protobuf_c.so is indeed there), but then also fails when falling back to try to load `google/protobuf_c`.

note I'm not seeing this issue with a 64-bit windows version of ruby.

**Comment by y-okubo** [comment]
Worked After you copy the file `libgcc_s_sjlj-1.dll` in the path `C:\DevKit\mingw\bin` to the path `C:\Ruby\bin`!

```
$ objdump -p ~/protobuf_c.so | grep 'DLL'
        DLL
 vma:            Hint    Time      Forward  DLL       First
        DLL Name: KERNEL32.dll
        DLL Name: msvcrt.dll
        DLL Name: libgcc_s_sjlj-1.dll
        DLL Name: msvcrt-ruby220.dll
```

Maybe, I think do not find the library `libgcc_s_sjlj-1.dll`.

**Comment by haberman** [comment]
Looks like we're pulling in a symbol from libgcc. The symbol appears to be `__ctzdi2`, referenced from `upb_vdecode_max8_massimino()` and `upb_vdecode_max8_wright()`. This is coming from the call to `__builtin_ctzll()`.

To fix this I should just always use `upb_vdecode_max8_branch32()` as the 8-byte varint decoder on 32-bit machines.
