### ISSUE TITLE
Provide message extension (proto2) querying facilities via the Python descriptor pool

### ISSUE THREAD

**Issue by soltanmm-google** [google/protobuf#2248]
C++ provides the methods [`FindExtensionByNumber`](https://github.com/google/protobuf/blob/master/src/google/protobuf/descriptor.h#L1432) and [`FindAllExtensions`](https://github.com/google/protobuf/blob/master/src/google/protobuf/descriptor.h#L1440). gRPC reflection needs these as part of its [protocol](https://github.com/grpc/grpc/blob/master/src/proto/grpc/reflection/v1alpha/reflection.proto#L60).

<sup>This issue is here mostly so that I have something to reference from `TODO`s in code.</sup>

**Comment by xfxyjwf** [comment]
What language is this issue about?

**Comment by soltanmm-google** [comment]
Yow - I missed that rather important tidbit!

For Python.

**Comment by soltanmm-google** [comment]
I see this is implemented on master but not on the `v3.1.0` tag. When can we expect the relevant change to make it into a release?

**Comment by soltanmm-google** [comment]
cc @hsaliak @markdroth w.r.t. blocked Python gRPC reflection

**Comment by xfxyjwf** [comment]
v3.2.0 release was out for a while. Please reopen if the needed support is still missing.
