### ISSUE TITLE
No way to get file level comments

### ISSUE THREAD

**Issue by thomasvl** [google/protobuf#2249]
FileDescriptor::GetSourceLocation() implementation says the empty path should provide the info, but that doesn't seem to work as a way to get the file's top level comments.

You can fake it by collecting for the `leading_detached_comments` for the `syntax` field (since that has to appear first); but if the file didn't have an explicit syntax, you then have to hack around trying to find the first thing that was in the file (package, option, enum, message), and look for detached comments off that).

What's the point of FileDescriptor::GetSourceLocation() if it doesn't expose the file level comments?  How does one get these comments to include them in the generated source?

**Comment by xfxyjwf** [comment]
I remember @pherl has added the support for file level comments. Not quite sure what's the public API for that.

**Comment by pherl** [comment]
The file level comments are stored into the `leading_detached_comments` of the top level elements. I think the best practice is to set up some proto file style guide.

**Comment by thomasvl** [comment]
@pherl every top level element has them as `leading_detached_comments` or just the _first_ one in the file as it?

Does anyone know the use of `FileDescriptor::GetSourceLocation()` since it doesn't include the comments?

**Comment by pherl** [comment]
Each top level element has it. So you could have comments for packages as well.

**Comment by thomasvl** [comment]
Doing a little poking around, I can't find any way at the info from `FileDescriptor`; looks like one has to use `FileDescriptor::CopySourceCodeInfoTo()` to get it on a `FileDescriptorProto`, and even then I still only see it on the first item (usually the syntax).  Which doesn't seem to match what you are saying?

**Comment by thomasvl** [comment]
From chatting outside the issue, it looks like they are just on the first top level item in the file.  @pherl was going to see about providing a C++ helper to get them, and also document how to get them for plugins/generators not written with the C++.

**Comment by anandolee** [comment]
@xfxyjwf  Do you know if the helper is added?

**Comment by xfxyjwf** [comment]
The comment is preserved, but you will need to get it from the 'leading_detached_comments' field.

For example:
```proto
// Top level comment

// Syntax comment
syntax = "proto2";
```

The generated descriptor data:
```
file {
  name: "a.proto"
  source_code_info {
    location {
      span: 3
      span: 0
      span: 18
    }
    location {
      path: 12
      span: 3
      span: 0
      span: 18
      leading_comments: " Syntax comment\n"
      leading_detached_comments: " Top level comment\n"
    }
  }
}
```

**Comment by thomasvl** [comment]
@xfxyjwf The catch is you have to know what the first item is, what is there isn't a `syntax` entry in the file?  Do they still end up there or do the end up on what ever was first in the file?  This is where documenting it in some way would be nice.
