### ISSUE TITLE
Serialization Deserialization bug?

### ISSUE THREAD

**Issue by tomoueda** [google/protobuf#2252]
I downloaded v3.1.0 for protoc and v3.1.1 for google-protobuf and recompiled my schema in.

Under the new version, my test for serializing and deserializing uuids in an object fail.

Was there a significant change in deserialization/serialization on major bump?

**Comment by xfxyjwf** [comment]
Serialization/deserialization should not fail if the message is valid. Do you happen to have required fields in your protos, or do you have string fields that have non-UTF8 data?

**Comment by tomoueda** [comment]
No I don't have required fields, and there are no string fields that have non-UTF8 data. Our uuid defined as bytes in the proto.

**Comment by tomoueda** [comment]
For example if I store uuid 871f609c-05a6-4fb9-9afd-a990fb9e774c, serialize the object and unserialize the uuid bytes field is returns as the following: 68783967-6e41-576d-5437-6d612f616d51

**Comment by tomoueda** [comment]
Figured out it wasn't due to serialization/deserialization,

**Comment by tomoueda** [comment]
For reference this was the change in _pb.js that broke my project:

getUuid() -> getUuid_asB64()

So at one point you're going to have to atob the output.
