### ISSUE TITLE
Php tutorial link does not work

### ISSUE THREAD

**Issue by TamalSaha** [google/protobuf#2255]
Hi, 
The PHP tutorial link in release docs does not work.

https://developers.google.com/protocol-buffers/docs/phptutorial

Thanks,
-Tamal

**Comment by TeBoring** [comment]
Sorry, we haven't published that doc. But this works:
https://developers.google.com/protocol-buffers/docs/reference/php-generated

**Comment by TeBoring** [comment]
#2566
