### ISSUE TITLE
Document protobuf for Dart

### ISSUE THREAD

**Issue by supermuka** [google/protobuf#2256]
Several languages implement protobuf.

Dart lang too with https://pub.dartlang.org/packages/protobuf

I suggest to include in readme  (https://github.com/google/protobuf#protobuf-runtime-installation) a referece to Dart Lang too.

**Comment by xfxyjwf** [comment]
The readme is intended to list implementations in this repo only. The dart implementation is a third-party one and should go into https://github.com/google/protobuf/blob/master/docs/third_party.md instead.
