### ISSUE TITLE
what's the requirement when install protobuf3.0

### ISSUE THREAD

**Issue by lwmonster** [google/protobuf#226]
I have the problems when install protobuf3.0:
1、 no macro AM_PROG_AR  (solved by add m4_pattern_allow([AM_PROG_AR]))
2、 g++ -V >&5  unrecognized command line option '-V' (solved by modify it to  g++ -v)
3、gcc -V >&5    same with 2
4、conftest.cpp:20:26: fatal error: minix/config.h: No such file or directory     [havn't solve]
5、conftest.cpp:62:10: error: '__SUNPRO_CC' was not declared in this scope   [havn't solve]
6、conftest.cpp:10:28: fatal error: ac_nonexistent.h: No such file or directory      [havn't solve]

I guess, that must be some version of dependency software isn't correct, but I don't know which. 
Can you give a detailed software dependency  and their version??????

**Comment by pherl** [comment]
Are you able to install the latest stable release? In 3.0 release we dropped the support for GCC 3.x and Java 1.5. Are you using Minix? It is a platform that we haven't tested. It may have other compatibility issues. If you managed to make it work, feel free to send a PR.

**Comment by lwmonster** [comment]
By ignoring problem 4,5,6 above,  I finally succeed to compile it and get libprotobuf.so;   and it seems work good. But I'm not sure if there are some problems in it.

BTW: My OS is Red Hat Enterprise Linux Server release 6.3 (Santiago)
          My gcc version: gcc version 4.9.2 (GCC)

          And what does that mean of PR?    Problem Report?

**Comment by pherl** [comment]
It only depends on autoconf, automake and libtool. It looks like the autoconf isn't working correctly. I don't know the exact minimum version requirement, but the following versions work:

autoconf: 2.69
automake: 1.14.1
libtool: 2.4.2

PR here is Pull Request.

**Comment by lwmonster** [comment]
Thank you very much!
I'll have a try. 

Mine: 
autoconf: 2.63
automake: 1.11
libtool: 2.2.6b
