### ISSUE TITLE
StackOverflowException in Java MapFieldLite.clear()

### ISSUE THREAD

**Issue by bobvawter** [google/protobuf#2263]
The `clear()` method calls itself rather than (presumable) `super.clear()`.

https://github.com/google/protobuf/blob/v3.1.0/java/core/src/main/java/com/google/protobuf/MapFieldLite.java#L86

```
  @Override public void clear() {
    ensureMutable();
    clear();
  }
```

**Comment by mdusina** [comment]
Are there test cases that call `.clear()` on each type of field?  The closest I could find is [this](https://github.com/google/protobuf/blob/v3.1.0/java/core/src/test/java/com/google/protobuf/MapForProto2LiteTest.java#L318), which calls `.clear()` on the builder for a message that contains a map field, but not the generated clear method for the map field itself.

**Comment by BSBandme** [comment]
This should have been fixed in the latest version.

**Comment by jbolinger** [comment]
Was this fix released? It seems the `.clear()` method is still unusable on the latest maven release (3.0.1). 

#2935 mentions some issues with updating, but it would be nice to have a usable `.clear()` method,
