### ISSUE TITLE
./autogen.sh in the v3.0.1-javalite repo doesn't work.

### ISSUE THREAD

**Issue by gillioa** [google/protobuf#2266]
When I try to compile protobuf in the v3.0.1-javalite repo I get this error.

`Google Mock not present.  Fetching gmock-1.7.0 from the web...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1582  100  1582    0     0   3547      0 --:--:-- --:--:-- --:--:--  3555
[gmock-1.7.0.zip]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of gmock-1.7.0.zip or
        gmock-1.7.0.zip.zip, and cannot find gmock-1.7.0.zip.ZIP, period.`

In the autogen.sh, if I change https://googlemock.googlecode.com/files/gmock-1.7.0.zip by https://github.com/google/googletest/archive/release-1.7.0.zip it works.

**Comment by pherl** [comment]
Should be fixed now.
