### ISSUE TITLE
[php] Allow individual files per class

### ISSUE THREAD

**Issue by mcos** [google/protobuf#2267]
It seems that the current `php` implementation generates multiple classes per file. Please allow an option similar to `option java_multiple_files = true;` to split each generated class out into its own file. 

This will comply with http://www.php-fig.org/psr/psr-0/ and http://www.php-fig.org/psr/psr-4/ autoloading directive that:

> The terminating class name corresponds to a file name ending in .php. The file name MUST match the case of the terminating class name.

The previous conventional protobuf implementation allowed an `option (php.multifile) = true;` directive, documented at https://drslump.github.io/Protobuf-PHP/protobuf-php.5.html which helped with this. Without this, users of this library who desire compliant conventional classloading will be forced to continue using `v3.0.0` with a different library, such as https://github.com/stanley-cheung/Protobuf-PHP.

**Comment by dstore-dbap** [comment]
When using PHP composer as the dependency manager there is a workaround for the non working PSR-autoloader:

Remove all require_once lines from generated *.pb.php files (sed/find is your friend) and you're able to use https://getcomposer.org/doc/04-schema.md#classmap

**Comment by NicklasWallgren** [comment]
Any progress on the psr-4 support?
