### ISSUE TITLE
Values getting doubled on using serializeBinary() for sint64 while working with arrays

### ISSUE THREAD

**Issue by tanmay-verma** [google/protobuf#2268]
using nodejs :-
**script :-**
```
var number = new buf.IntegerOperandList();
number.setOperandsList([1,2]);
var bytes = number.serializeBinary();
console.log(bytes)
```
**result:-**
`Uint8Array { '0': 10, '1': 2, '2': 2, '3': 4 }`

**In proto file**
`repeated sint64 operands = 1;`

**Comment by xfxyjwf** [comment]
That's by design. You can refer to the encoding documentation of sint32/sint64 fields:
https://developers.google.com/protocol-buffers/docs/encoding#types
