### ISSUE TITLE
Protobuf 3.1.0 on GAE

### ISSUE THREAD

**Issue by PhilippMundhenk** [google/protobuf#2269]
Protobuf in version 3.1.0 uses FileOutputStream in protobuf/java/core/src/main/java/com/google/protobuf/ByteBufferWriter.java
FileOutputStream is, however, not available on Google App Engine (GAE). Thus, Protobuf Java seems to be not working on GAE.

**Comment by xfxyjwf** [comment]
@nmittler I guess we need to remove the reference to FileOutputStream for GAE.

**Comment by nmittler** [comment]
PhilippMundhenk@ If I through together a PR, could you give it a shot?

**Comment by nmittler** [comment]
@PhilippMundhenk If I through together a PR, could you give it a shot?

**Comment by PhilippMundhenk** [comment]
Sure. I only have a very simple GAE playground setup running though. Nothing serious. And I can't seem to use the method were FileOutputStream is used.
For my own setup, to keep things running, I just took the concerning 3 lines (96-98) out. This runs on the local GAE environment.

**Comment by nmittler** [comment]
@PhilippMundhenk give #2274 a try.

**Comment by PhilippMundhenk** [comment]
@nmittler : This still uses FileOutputStream, thus resulting in the error: "java.io.FileOutputStream is not supported by Google App Engine's Java runtime environment"

**Comment by nmittler** [comment]
Ah I was under the impression that your problem was at runtime when it would attempt the cast. Just to be clear, you get this when you deploy your app?

**Comment by PhilippMundhenk** [comment]
Sorry, I should have clarified: I get this error already at compile time. The above line is copied out from Eclipse.

**Comment by nmittler** [comment]
@PhilippMundhenk PTAL ... just pushed an update to eliminate all direct references to FileOutputStream

**Comment by PhilippMundhenk** [comment]
@nmittler : This looks good! Compiles fine and my minimal examples are working fine. Thank you very much for the fast corrections!
