### ISSUE TITLE
Add "void" as a built-in type

### ISSUE THREAD

**Issue by Diggsey** [google/protobuf#227]
"oneof" is equivalent to algebraic data types in other languages, but it's currently impossible to have a variant without any associated data.

Example:

```protobuf
oneof pathSegment {
    bytes literal = 1;
    void wildcard = 2;
}
```

**Comment by pherl** [comment]
Is the struct well-known type what you are looking for? https://github.com/google/protobuf/blob/a779ae609c9ca6fa37ee4acec2d48eaa9c3afb91/src/google/protobuf/struct.proto

**Comment by xfxyjwf** [comment]
I think using an int32 field for such cases is good enough. There is not much a new field type can help here excepting for the large amount of the work required to introduce a new field type.
