### ISSUE TITLE
Discrepancy in interface keyword handling in generated Java code

### ISSUE THREAD

**Issue by ganesh-karthick** [google/protobuf#2270]
The key word interface when used in as field name in a proto message maps to generated code field as  as interface_  in a class, but when its part of proto package or option java_package , its mapped to the word interface in package name in java. This causes java compilation to fail.

``` proto
 syntax = "proto3"; 
 package com.interface;
 option java_package="com.interface";
 message A {
 string interface = 1;
 }
```

 protoc generated generated java code for the above proto would fail, because of generated package name 

 `package com.interface`

``` proto
 syntax = "proto3";
 package com.abc;
 option java_package="com.abc";
 message A {
 string interface = 1;
 }
```

 protoc generated generated java code for the above proto would pass,because field name generated is 

 `private java.lang.Object interface_ = ""`

**Comment by ganesh-karthick** [comment]
Taking a deeper look, I found protobuf appends all message field names with underscore for java generated code, which avoids keyword collisions in fields for classes, while package directives , are used as it is leading to compilation issue, hence the quirkiness, where language keywords ( such as interface) work fine in field names but not as package directives or message names.

**Comment by xfxyjwf** [comment]
Protobuf generates code in many different languages so there are a lot of places collision like this can happen. I recommend renaming the package if it doesn't require too much work. If that's not feasible, we can update the Java code generator to append "_" to package names when they are Java keywords.

**Comment by ganesh-karthick** [comment]
My intention is to do the same by adding option java_package , but if protoc handles it in the same way interface is handled in fields it would be align with each other.

**Comment by acozzette** [comment]
Let me go ahead and close this issue, since an easy workaround exists.
