### ISSUE TITLE
php generated class include file error

### ISSUE THREAD

**Issue by eclou** [google/protobuf#2271]
i generated php class use the proto file,the proto file package  first letter is upper case。when i include the php class,php report a class not found error.error message show that the namespace first letter is replaced by '#' or other number.it works on the package first letter is little case.

**Comment by TeBoring** [comment]
Could you patch your proto file here?

**Comment by eclou** [comment]
syntax = "proto3";
package tbVipUser;

message VipUserData{
    bytes paper_id         = 1;    
    int32 paper_type       = 2;    
    bytes real_name        = 3;   
    bytes user_name        = 4;    
    bytes password         = 5;    
    bytes password_pay     = 6;    
    bytes qq               = 7;   
    bytes email            = 8;   	
    bytes mobile           = 9;    
    int64 create_time      = 10;   
    int64 update_time      = 11;   
    bytes birthday         = 12;  
    bytes weixin           = 13;  
	int32 is_male          = 14;   

    bytes check_data       = 29;   
    int64 unique_id        = 30;                                                     
    int32 version          = 31; 
}

**Comment by TeBoring** [comment]
Could you try against master head again? I think this should have been fixed.
