### ISSUE TITLE
Incorrect documentation for "package" directive for python

### ISSUE THREAD

**Issue by holljen** [google/protobuf#2273]
The documentation states:
In Python, the package directive is ignored, since Python modules are organized according to their location in the file system.

This is not entirely true since you will get name errors if you try to import two protobuf files where one (or more) messages have the same name. This can only be resolved using the package directive. It would be helpful if this was mentioned in the docs.

See: https://github.com/google/protobuf/issues/53

**Comment by pherl** [comment]
Yep. I think the comments might be misleading that python users won't need to set packages. I guess it meant that the option you set on the proto file doesn't affect the output generated files (except for the encoded descriptor data). We need to change the doc to suggest that package shall still always be specified to avoid naming conflicts.

**Comment by pherl** [comment]
I sent out a change to fix the document. Will update the issue once it's live.

**Comment by haberman** [comment]
The current documentation (https://developers.google.com/protocol-buffers/docs/reference/python-generated#package) says:

> The Python code generated by the protocol buffer compiler is completely unaffected by the package name defined in the .proto file. Instead, Python packages are identified by directory structure.

This seems accurate, and it no longer says the package name is ignored. Closing this issue.

**Comment by holljen** [comment]
It is accurate only when you use the python backend. (See #53) I believe more and more people are going to use the c++ backend now that it is more stable and so I think the documentation is still misleading.
