### ISSUE TITLE
Type checking in Python when serializing

### ISSUE THREAD

**Issue by reprehensible** [google/protobuf#2276]
This issue arose from this thread in the gRPC mailing list: https://groups.google.com/d/msg/grpc-io/HGcDbxVK7Q4/bw6RAyTGBQAJ

When interacting with stubs or returning data from servicers in gRPC, it would be ideal if the types passed in / returned verified as being the types expected. The expectation from gRPC's side, as represented in that thread, is that the types should properly be verified by protobuf.

Specifically: when calling <message class>.SerializeToString(<message object>), the protobuf implementation should throw an error if the message object being serialized does not match the message class. See also https://github.com/grpc/grpc/issues/3410

Does this seem like the right approach, from the protobuf perspective?

**Comment by pherl** [comment]
@haberman

**Comment by reprehensible** [comment]
Is there anything I could / should be doing to get some feedback on this issue?

**Comment by acozzette** [comment]
I'm not that familiar with the Python implementation in particular but that sounds like a good approach to me. I wouldn't be too surprised if there's some code out there that's inadvertently relying on calling SerializeToString() with the wrong class but that seems like it should be relatively easy to fix.

**Comment by jtattermusch** [comment]
Closing as this is not actionable.
