### ISSUE TITLE
Preservation of unknown fields in JSON

### ISSUE THREAD

**Issue by pfhayes** [google/protobuf#2289]
Is there planned support for preserving unknown fields in JSON serialization/deserialization?

**Comment by pherl** [comment]
We will likely to bring unknowns back to proto3, however, it's still uncertain about JSON format. Do you mind elaborate your use case about unknowns in JSON?

**Comment by pfhayes** [comment]
We're serializing protobufs to postgres using their native JSON format. If unknown keys were serialized/deserialized to json as well then that would provide greater stability across nodes that might have older versions of the protobuf definitions

**Comment by pherl** [comment]
Thanks. So is the use case like: Binary A receives binary protobuf and forward the message to binary B using JSON. Binary B converts JSON message back into protobuf binary format and put it in storage?

**Comment by pfhayes** [comment]
More like

- Binary A serializes protobuf to JSON, stores in databse
- Binary B retrieves JSON from database, possibly modifies, then writes back

If binary B is outdated, then under the current flow unknown fields are lost

**Comment by pherl** [comment]
Binary B retrieves JSON from database and then parse it to message object and then serialize back to JSON? That would mean to preserve JSON payload within the message objects. I think that would probably not going to happen as
1) JSON support was built as a util library, the core protobuf doesn't know JSON payload. We don't have mechanism to preseve unknown Json payload. Adding such support will increase binary size and complicate semantics.
2) If the message is serialized to binary format, we are not able to preserve the unknowns in binary payload.

I would strongly recommend to use binary format in persistent storage. We were thinking that JSON payload may have some fields to carry unknown binary data, but probably not the other way around.
