### ISSUE TITLE
cpp_implementation or pure python

### ISSUE THREAD

**Issue by narsu1984** [google/protobuf#229]
how do i determine whether i'm running my own project under cpp_implementation or pure python environment?

**Comment by pherl** [comment]
@haberman

**Comment by llchan** [comment]
I think this is discouraged and there may be better ways, but I've done this in the past:

```python
import google.protobuf.internal.api_implementation
assert google.protobuf.internal.api_implementation.Type() == 'cpp'
assert google.protobuf.internal.api_implementation.Version() == 2
```

**Comment by xfxyjwf** [comment]
To use the cpp implementation, you need to specify some environment variables explicitly. If you don't know about it, you are probably using the pure python version.
