### ISSUE TITLE
Can't parse GraphDef from the given flat array that size is bigger than 64MB

### ISSUE THREAD

**Issue by apollo-time** [google/protobuf#2293]
If create a CodedInputStream that reads from the given flat array that size is bigger than 64MB, couldn't parse graph.
I think CodedInputStream(const uint8\* buffer, int size) function set total_bytes_limit_ with size when size is bigger 64MB(kDefaultTotalBytesLimit).

**Comment by xfxyjwf** [comment]
This seems reasonable. Can you send us a pull request?

**Comment by apollo-time** [comment]
How can I pull request?

**Comment by apollo-time** [comment]
I sent a pull request.
