### ISSUE TITLE
wrong package name when using --javanano_out and "Option java_package"

### ISSUE THREAD

**Issue by primiano** [google/protobuf#2300]
Hi from Chromium.
Currently we use two versions of protoc: 3.0 for C++ code and an ancient 2.2.0a from AOSP [1] for Java code.
I'm trying to switch everything to use 3.0 as that seems to have support for --javanano.
Unfortunately there seems to be a bug in the generation of the java stubs w.r.t. package names. I tried the latest release of protoc available (3.1.0) and this is what I get:

`$ cat proto/client.proto`

```
syntax = "proto2";

package com.google.protos.ipc.invalidation;
option optimize_for = LITE_RUNTIME;

option java_outer_classname = "NanoClient";
option java_package = "com.google.protos.ipc.invalidation.nano";

message PersistentTiclState {
  optional bytes client_token = 1;
  optional int64 last_message_send_time_ms = 2 [default = 0];
}
```

`$ protoc  --proto_path proto --javanano_out out proto/client.proto`

`$ find out -type f`

```
out/com/google/protos/ipc/invalidation/nano/nano/NanoClient.java
```

Note how the package name has `nano` twice.
This is not happening with [1] and seems a bug.
The generated java file should use the package specified in option java_package.
I don't see a reason for the second `nano`. 
(The generated `package` statement in the java file is consistently affected.)

[1] https://android.googlesource.com/platform/external/protobuf.git

**Comment by primiano** [comment]
Everything works fine if I use `--java_out` instead of `--javanano_out`

**Comment by xfxyjwf** [comment]
protoc now supports both --java_out and --javanano_out and they both use the java_package option to determine the java package for the generated code. To avoid conflict between the two, we made --javanano_out append a "nano" suffix to the package automatically. That's why you see a double "nano" when the java_package already has "nano" in it.

A simple fix is to change the java_package and remove "nano" from it.

**Comment by acozzette** [comment]
Let me go ahead and close this since it sounds like the problem has been resolved.
