### ISSUE TITLE
Segment fault on QNX 6.6

### ISSUE THREAD

**Issue by luchengchao** [google/protobuf#2308]
I succecced to compile the protobuf v2.5.0 in QNX 6.6 environment with the cnfigure: 
```
./configure --host=arm-unknown-nto-qnx6.6.0eabi --disable-protoc --with-protoc=protoc --prefix=`pwd`/build/arm-qnx
```
But when I run my test project with the result, I met segment fault:
```
terminated SIGSEGV code=1 fltno=11 ip=0106d2c4(/usr/lib/ldqnx.so.2@__generic_memcpy+0x1ec) mapaddr=0006d2c4. ref=00000000
```
Does anyone know why this issue happens? How can I configure google protobuf correctly?

**Comment by acozzette** [comment]
It's hard to know for sure what the problem is because we don't have any QNX systems for testing. Could you try running the test suite with `make check` and let us know if it's successful? It might also be worth upgrading to a newer protobuf version because 2.5.0 is a bit old at this point.

**Comment by haberman** [comment]
We don't have access to a QNX platform. If you have more information or a PR, please feel free to re-open.
