### ISSUE TITLE
autoreconf-2.69: libtoolize failed with exit status: 1

### ISSUE THREAD

**Issue by chenjianyyzz** [google/protobuf#2312]
I try to build protobuf under cygwin, and got the error as below: 
===============================================
'
+ printf '%s\n' 'libtoolize: copying file '\''build-aux/ltmain.sh'\'''
libtoolize: copying file 'build-aux/ltmain.sh'
+ IFS='
'
+ :
+ return
+ pkgaux_hdr='putting another copy of auxiliary files in '\''.'\'''
+ test -f configure.ac
+ test -z build-aux
+ test -f configure.ac
+ test subproject = ''
**autoreconf-2.69: libtoolize failed with exit status: 1**
===============================================
from the information I cannot find why libtoolize failed, will anyone help me? thanks.

James (chenjianyyzz@163.com)

**Comment by pherl** [comment]
Sorry as this has been opened for too long I guess you probably have already found a workaround. Closing this now. Note we no longer actively support cygwin in our release process, and we would rely on 3rd to contribute patches to make the release cygwin/mingw32 compatible.
