### ISSUE TITLE
Support for SystemJS module format

### ISSUE THREAD

**Issue by myitcv** [google/protobuf#2314]
https://github.com/systemjs/systemjs

Currently `protoc --js_out ...` has support for CommonJS and Closure-style imports. 

This issue is a request to add support for SystemJS

**Comment by acozzette** [comment]
I don't think we can commit to adding this feature, but if you'd like to give it a try we would be open to accepting pull requests for it. If you do decide to work on it then it would be good if you could send out a rough plan for discussion first.

**Comment by myitcv** [comment]
@acozzette quite understand. 

I'm currently looking at whether we can use [`jspm`](http://jspm.io/) to interface with the existing CommonJS support within protobuf. That would obviate the need for SystemJS support within protobuf from our perspective. But not the more general case (not sure how many people rely on SystemJS without `jspm`); however it would be a start.
