### ISSUE TITLE
OneofOptions cannot be extended in proto3

### ISSUE THREAD

**Issue by jskeet** [google/protobuf#2316]
This piece of unittest_custom_options.proto gives an error in proto3 syntax:

```text
extend google.protobuf.OneofOptions {
  int32 oneof_opt1 = 7740111;
}
```

I would expect OneofOptions to be supported in the same way as any other options.

**Comment by anandolee** [comment]
OneofOption support was added around Aug 2016 for other languages. Will add the support for C# too.

**Comment by jskeet** [comment]
Hmm... it was a protoc error that I got, so I wouldn't expect it to be C#-specific to be honest...
