### ISSUE TITLE
How to properly parse message in ObjectiveC world? 

### ISSUE THREAD

**Issue by lolgear** [google/protobuf#2319]
It appears to be no exception in Objective-C world/code.

Appealing to documentation:

[Dealing with Errors](https://developer.apple.com/library/content/documentation/Cocoa/Conceptual/ProgrammingWithObjectiveC/ErrorHandling/ErrorHandling.html)

> If you’re coming from other platforms and languages, you may be used to working with exceptions for the majority of error handling. When you’re writing code with Objective-C, exceptions are used solely for programmer errors, like out-of-bounds array access or invalid method arguments. These are the problems that you should find and fix during testing before you ship your app.

So, if I have some errors like 'InvalidBuffer', 'UninitializedMessage' etc. I should tell myself: Wow, you do something wrong.

But HOW could I check this? HOW could I ignore errors or handle them without crashing whole process? If a bit of message not passed, why whole process should failed?

For example, I would like to have methods like `parseData:(NSData *)data withError:(NSError **)error`. They are do what I want. They will return result or nil ( common in this world ) and fill error with appropriate value or nil.

Maybe I am wrong and protobuf has these methods inside magic place 'ErrorHandlerClass'.

**Comment by sergiocampama** [comment]
These methods already exist and can be found in the base class for all Objc messages:

https://github.com/google/protobuf/blob/master/objectivec/GPBMessage.h#L123

**Comment by lolgear** [comment]
@sergiocampama thanks! opening my eyes wider!
