### ISSUE TITLE
v3.0.0-alpha-2 make check has 4 test failures on Windows/mingw

### ISSUE THREAD

**Issue by matt1** [google/protobuf#233]
Couldn't find an existing issue for this.  Trying to build to get grpc-java up and running using a fresh mingw installation.

Followed these instructions from grpc-java.

$ git clone https://github.com/google/protobuf.git
$ cd protobuf
$ git checkout v3.0.0-alpha-2
$ ./autogen.sh
$ ./configure
$ make
$ make check

4 tests are failing.
[----------] Global test environment tear-down
[==========] 1221 tests from 133 test cases ran. (378102 ms total)
[  PASSED  ] 1217 tests.
[  FAILED  ] 4 tests, listed below:
[  FAILED  ] RubyGeneratorTest.GeneratorTest
[  FAILED  ] BootstrapTest.GeneratedDescriptorMatches
[  FAILED  ] TextFormatTest.Basic
[  FAILED  ] TextFormatExtensionsTest.Extensions

This is on windows 7, mingw-base version as reported by mingw-get "2013072200".

**Comment by pherl** [comment]
Could you print the detailed failure log, as well as the autoconf, automake, libtools and gcc version? I tested on the latest mingw before alpha-2 release and didn't find any failing tests.

**Comment by Harshasa** [comment]
Hi ,
Am also getting error during step
 make  check

Steps followed:
Installing "protobuf-cpp-3.0.0-alpha-2.tar.gz" on ubuntu. 3.16.0-23-generic #31

1. tar xzvf protobuf-cpp-3.0.0-alpha-2.tar.gz
2. cd  protobuf-3.0.0-alpha-2
3. ./configure
4. make
5. make  check


In test-suit.log file i can see this error first.
[libprotobuf FATAL google/protobuf/compiler/ruby/ruby_generator_unittest.cc:53] Could not find Ruby test directory. Please run tests from somewhere within the protobuf source package.
unknown file: Failure
C++ exception with description "Could not find Ruby test directory. Please run tests from somewhere within the protobuf source package." thrown in the test body.
[  FAILED  ] RubyGeneratorTest.GeneratorTest (388 ms)


can any one help to resolve this???

Thanks in advance.
Harsha

**Comment by pherl** [comment]
Add @cfallin to take a look at the failing ruby tests.

**Comment by cfallin** [comment]
All tests passed on Windows when we did the release testing, sorry. It's not possible to say any more about the cause without seeing your exact setup.

However, it seems that all four failing tests are ones that compare output to a golden file in the source tree. So perhaps there is something systematically wrong with the way your source tree is laid out, or with how your build is interacting with the filesystem?

**Comment by matt1** [comment]
Apologies for delay in response to this.  I would imagine my source tree layout is fairly default - I just checkout and go without any messing around, but please do let me know if there is anything specific in mingw that you'd like me to check (I am more of a Java guy so all this stuff is alien to me - apologies!)

Requested version details, steps to checkout used, and output from autogen, configure, make and make check are in this gist
https://gist.github.com/matt1/4e6257f3a8a418389b35

**Comment by cfallin** [comment]
Ah! I'm pretty sure I know what the issue is. Consider this failure from TextFormatTest:

    google/protobuf/text_format_unittest.cc:121: Failure
    Value of: proto_.DebugString()
      Actual: "optional_int32: 101\noptional_int64: 102\n..."
    Expected: proto_debug_string_
    Which is: "optional_int32: 101\r\noptional_int64: 102\r\n..."

Note the difference in line endings: \n vs. \r\n. As I suspected, this happens in every test that compares against a golden file, and your golden files have Windows-style line endings, so the contents do not match (the code generates only \n).

The answer is to change the text format that `git` uses to check out your tree. I believe the `core.autocrlf` git option controls this behavior. You'll probably want to change it globally then check out a fresh clone of protobuf.

**Comment by matt1** [comment]
Ah thanks - I learnt something about git today!

All tests passing.  If anyone else finds the same problem, check what your `core.autocrlf` is.  Mine was set to true and was converting the unix line endings in the tests to windows formats automatically when writing the files to the local workspace.

Set this to false with something like `git config --global core.autocrlf false`, clone again from scratch and build and the tests pass fine this time (since git is no longer fiddling with the line endings behind the scenes).
