### ISSUE TITLE
ProtoC C# Code Generator Eats Extra Underscores

### ISSUE THREAD

**Issue by biscuitWizard** [google/protobuf#2331]
Observation:
Naming a field in a message foo_1 creates a C# field by the name of Foo1.

Naming a field in a message foo__1 creates a C# field by the name of Foo1.

Expectation:
Adding a second underscore would allow one underscore to remain, producing Foo_1 from foo__1.

**Comment by pherl** [comment]
Any use case that you would need consecutive underscores as field names? I'd suggest name the fields without using double underscores. Otherwise it will create issues in json conversions and poor readability in other languages as well.
