### ISSUE TITLE
Compiler-generated PHP code is missing service definition

### ISSUE THREAD

**Issue by zorrocaesar** [google/protobuf#2334]
When compiling a simple helloworld.proto with a service definition a request and a response, the generated PHP code contains just two classes for the request and response respectively. There is no class for the service.

[helloworld.proto.txt](https://github.com/google/protobuf/files/572793/helloworld.proto.txt)
[helloworld.pb.php.txt](https://github.com/google/protobuf/files/572795/helloworld.pb.php.txt)

**Comment by TeBoring** [comment]
Working on it.

**Comment by TeBoring** [comment]
I think grpc will generate a service by its own. But we will still provide an option to generate a service stub.

**Comment by zorrocaesar** [comment]
But if there is no service stub, there is no class to instantiate in order to call the service.

**Comment by dParadiz** [comment]
Check this pull request https://github.com/google/protobuf/pull/2526/files. It implements interface generation for client stubs
