### ISSUE TITLE
Help required to setup protobuff 2.5 64 bit

### ISSUE THREAD

**Issue by alphonsetomjames** [google/protobuf#2338]
Hi 

I am new to protobuff. Currently we are using protobuff 2.5 version, in vs2013 windows c++ project.
I need to port the applicaion to 64 bit. 

Is source code of protobuff 2.5 for 32  bit and 64 bit same? Please help to build the 64 bit protobuffers in vs2013 c++

**Comment by xfxyjwf** [comment]
I recommend using the latest version of protobuf 3.1.0. It comes with cmake support which makes it a lot more easier to build for different visual studio versions (and 32bit or 64bit).
