### ISSUE TITLE
javanano `clone` method generation does not work for Oneof

### ISSUE THREAD

**Issue by jsievenpiper** [google/protobuf#2340]
Using proto3, if that helps: 3.1.0

I have this message:
```
message Value {
    oneof possible_values {
        string string_value = 1;
        bool boolean_value = 2;
        // etc for some other primitives
    }
}
```

I recently tried turning on `generate_clone` (this, I'm thinking isn't a fully-supported feature yet, since I haven't found a reference to it anywhere else) -- this worked for all of my messages save this one.

I noticed inside my generated `Value.java` file, that `possible_values` was written out as `possibleValues_`, and referenced accordingly, but in the clone method, it's just referred to as `possibleValues`, and the compiler yells, saying there is no such symbol.

**Comment by xfxyjwf** [comment]
javanano is in maintenance mode and we recommend users to use lite runtime instead. There is no planned change to javanano, nor are we going to apply bug fixes to it.
