### ISSUE TITLE
Tangled up in documentation for objective c compiler options.

### ISSUE THREAD

**Issue by lolgear** [google/protobuf#2343]
My set:

```
$ protoc --version
libprotoc 3.1.0
```

Directory:

```
$ ls ./
Mappers
Proto
```

```
$ cd ./Proto; ls
$ cd Proto/; ls
envelope.options	
envelope.proto 
header.proto
payload.options
payload.proto
```

What I want:
Generate protocol buffers files in `../Mappers` directory with names: `Prefix_SomeWords_FileName`.
For example: `envelope.proto -> PFXChannelContainersEnvelope.pbobjc`

What I try:
```
$ protoc --proto_path='./' --objc_out="../Mappers" --objc_opt='generate_for_named_framework=AmaterasuProtobuffed' envelope.proto
```

What I get:
```
$ ls ../Mappers
Envelope.pbobjc
```

Also I try to add option:

```
option objc_class_prefix="PFXChannelContainers";
```

But nothing changed.
File still does not have prefix, but classes inside it have correct prefixes. ( `PFXChannelContainers` ).

Could you show proper options setup for compiler with ( if not exists ) documentation update for `objectivec`.

**Comment by thomasvl** [comment]
https://github.com/google/protobuf/tree/master/objectivec#objective-c-generator-proto-file-options - documents that it effects the generate classes, enums, etc.  Sounds like that was working.

https://github.com/google/protobuf/tree/master/objectivec#objective-c-generator-protoc-options - documents that the information changes how `#import` directives are generated.  You don't seem to provide any info to say if that did/didn't work.

As far a your desire to prefix the generated file names with something, there is currently no support for that.  What most languages supported by ProtocolBuffers does is the take any directories on the input paths and recreate them in the output directories (i.e. - `protoc --cc_out=../Output foo/bar/baz.proto` would create `../Output/foo/bar/baz.pb.h` and `../Output/foo/bar/baz.pb.cc`); ObjC does this, but with the one change in that it uses underscores in the final filename to CamelCase the generate file name.

**Comment by thomasvl** [comment]
@lolgear Did that answer your question or was there more?

**Comment by lolgear** [comment]
@thomasvl Yes.
It would be better to list available options somewhere in one place, because I can't find `option objc_class_prefix` near compiler options.
