### ISSUE TITLE
Wrong protobuf build folder?

### ISSUE THREAD

**Issue by Baumfaust** [google/protobuf#2344]
Hello
I am using cmake 3.6.3 and Visual Studio 2015.
I have built protobuf using the x64 compiler and selected the folder protobuf-master/vsprojects to build the binarries.
CMake FindPackage uses vsprojects/x64/Debug and vsprojects/x64/Release to search for the Protobuf_SRC_ROOT_FOLDER.
https://cmake.org/cmake/help/v3.6/module/FindProtobuf.html
But protobuf creates its x64 binaries into the folder vsprojects/Debug and vsprojects/Release and because of this cmake cant find protobuf.
Is this a bug?

**Comment by podsvirov** [comment]
Now you can `install` protobuf to you development environment (`CMAKE_INSTALL_PREFIX`) and than find from your cmake project:
find_package(protobuf CONFIG).
See [examples/CMakeLists.txt](https://github.com/google/protobuf/blob/master/examples/CMakeLists.txt) for more info.
