### ISSUE TITLE
error at make java in examples folder

### ISSUE THREAD

**Issue by johnfercher** [google/protobuf#2346]
I'm trying to run use the protobuf in java, bun when I execute the **make java** in the examples folder I get the error bellow.

`make java
javac AddPerson.java ListPeople.java com/example/tutorial/AddressBookProtos.java -cp protobuf-java-2.4.1.jar
com/example/tutorial/AddressBookProtos.java:76: error: package com.google.protobuf does not exist
      com.google.protobuf.GeneratedMessage implements
                         ^
**. . .**  
            
100 errors
Makefile:54: recipe for target 'javac_middleman' failed
`

How resolve this error?

**Comment by acozzette** [comment]
Could you give it a try with a newer version of protobuf? Version 2.4.1 was released in 2011 so it's pretty old at this point.

**Comment by johnfercher** [comment]
Actually the original javac doesn't include the **-cp protobuf-java-2.4.1.jar**, I've saw in a forum to add this and forgot to remove.  The error is the same and the string is **javac AddPerson.java ListPeople.java com/example/tutorial/AddressBookProtos.java**. My protobuf is up-to-date, I install by the repository (**./configure, make, sudo make install, sudo ldconfig**).

**Comment by acozzette** [comment]
Ok, I think you just need to make sure the protobuf library is in your `$CLASS_PATH` then. You can build the jar with `mvn package` in the Java directory and just add the JAR path to your class path, and then `make java` should work.

**Comment by johnfercher** [comment]
In the terminal, I run **echo $CLASS_PATH** and doesn't return anything. How can I resolve this?

**Comment by acozzette** [comment]
Oops, I actually meant to say `$CLASSPATH` (no underscore). From inside the `examples/` directory you should be able to set your class path like this (assuming you have already built the jar):
`export CLASSPATH=$PWD/../java/core/target/protobuf-java-3.1.0.jar:$CLASSPATH`
