### ISSUE TITLE
[bug] [proto2] C++ ParseFromArray(...) fails to deserialize sub-messages containing repeated bytes fields

### ISSUE THREAD

**Issue by ASethi77** [google/protobuf#2351]
I am using protobuf version 2.6.1. I've defined a message which contains a sub-message that only has a `repeated bytes` field like so:

```
message A {
    repeated bytes payload = 1;
}

message B {
    repeated A payload_blocks = 1;
}
```

In my use case, I built the following instance of message B:
```
payload_block {
  payload: "\000\000\000\000\000\000\000\000\000\004Whee"
}
```

I have the serialized message in a char* buffer, then used the following C++ code to deserialize the message:
```
char* b_serialized_buf = new char[b_serialized_len];
// code to read the complete contents of the serialized instance of
// message B described above into the buf

mypackage::B b_deserialized;
bool parse_success = b_deserialized.ParseFromArray((void*) b_serialized_buf,
        b_serialized_len);
```

In this case `parse_success` is `true`, but when I inspect my message I find `b_deserialized.payload_blocks_size()` is 0 when it should be 1. Indeed, looking at `b_deserialized` in my debugger shows that there are no instances of message type A to be found.

I have tested deserializing this message in C++, Python, and Java, and am only able to observe this bug in C++. Editing message B's format to directly contain repeated bytes instead of repeated messages of type A fixes the parsing problem, but is not ideal for clarity in my particular application.

**Comment by xfxyjwf** [comment]
I bet that problem is in the code you omitted. I.e., "// code to read the complete contents of the serialized instance of message B described above into the buf".

**Comment by ASethi77** [comment]
Hi @xfxyjwf,

Thanks for looking into my issue!

For some context, my goal is effectively to read messages of type B (and only of type B) from a socket and deserialize them correctly, so my omitted code is essentially reading length-prefixed messages into a buffer first by reading and parsing the length (`b_serialized_len` in my comment above), followed by reading `b_serialized_len` bytes from the socket into a buffer of exactly `b_serialized_len` size.

I am reasonably confident that my omitted code is correct for three reasons:

1. I have run many trials of my code, each time confirming that the message length prefix I read and parse from the socket matches the serialized message length reported by the sender before it sends the message over the socket.
2.  I can inspect the buffer `b_serialized_buf` after reading my serialized message into the buffer, and when looking at the message within my debugger I see that the last element in the buffer is the last character of my payload (i.e the last 'e' in "Whee"). I would imagine that this is expected unless serialized protobufs end in some separate termination character, in which case my omitted code is incorrect.
3. I changed message B's format to simply store a `repeated bytes` field, and kept the same code for reading messages into `b_serialized_buf` before calling `ParseFromArray`. In this case my message is parsed correctly.

I can add my omitted code if you think there still might be an issue with my omitted code given the information above, but I will not be able to upload it for a few hours.

**Comment by xfxyjwf** [comment]
Can you post the content of b_serialized_buf before the parsing?

**Comment by ASethi77** [comment]
Sure, here are the contents of the buffer just before serializing as displayed in my Eclipse debugger:

```
  Address           0 - 3     4 - 7     8 - B     C - F               
  0000000000649A10  0A0E0002  00000000  00000004  57686565  
```

**Comment by xfxyjwf** [comment]
The input seems to be malformed:
0: 0A => 00001 010 => field number 1, wire type 2 => payload_blocks field
1: 0E => 14 => the length of the payload_blocks field is 14
2-F: the content of a payload_blocks field, i.e., a message A
2: 00 => 00000 000 => field number 0, wire type 0 => this is not a valid TAG. 0 is treated as end-of-stream.

The parsing stops at the 3rd byte.

Can you post the bytes data for the same message in other languages? There must be some differences there.

**Comment by ASethi77** [comment]
Sorry about that; I think I accidentally gave you the byte buffer contents for my new message format.

I re-ran my code after reverting back to the message format in my original post, and despite the fact that (to the best of my knowledge) I haven't changed my server-side serialization code or my client-side socket reading/message parsing code, I'm no longer seeing this issue. If you're still curious, this is my (hexadecimal) bytes data after re-running my C++ client:

```
  Address           0 - 3     4 - 7     8 - B     C - F               
  0000000000648A10  0A100A0E  00020000  00000000  00045768          
  0000000000648A20  6565 
```

And this is the (decimal) readout of my serialized message from my Java server:
```
[10, 16, 10, 14, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 87, 104, 101, 101]
```

These now match. My best guess as to what happened is that my server and client had out-of-sync field numbers, but unfortunately I don't have a clear answer about what caused the parsing failure at this point.

I'm going to close this issue for now and will see if I can root-cause what happened. Thanks so much for your help!
