### ISSUE TITLE
PHP package error

### ISSUE THREAD

**Issue by jasonhe88** [google/protobuf#2359]
php 7.0.12

the simple msg.proto file for testing:

```proto
syntax="proto3";

message Msg {
        uint32 mid  = 1;
        string body = 2;
}
```

then try to run following php code:

```php
<?php

require_once("./vendor/autoload.php");
require_once("./msg.pb.php");

$msg = new Msg();

?>
```

get following error:

PHP Notice:  Undefined index: Msg in /home/jasonhe/CS/vendor/google/protobuf/php/src/Google/Protobuf/Internal/DescriptorPool.php on line 109

Notice: Undefined index: Msg in /home/jasonhe/CS/vendor/google/protobuf/php/src/Google/Protobuf/Internal/DescriptorPool.php on line 109
PHP Fatal error:  Uncaught Error: Call to a member function getField() on null in /home/jasonhe/CS/vendor/google/protobuf/php/src/Google/Protobuf/Internal/Message.php:75
Stack trace:
#0 /home/jasonhe/CS/msg.pb.php(171): Google\Protobuf\Internal\Message->__construct()
#1 /home/jasonhe/CS/tt.php(4): require_once('/home/jasonhe/C...')
#2 {main}
  thrown in /home/jasonhe/CS/vendor/google/protobuf/php/src/Google/Protobuf/Internal/Message.php on line 75

Fatal error: Uncaught Error: Call to a member function getField() on null in /home/jasonhe/CS/vendor/google/protobuf/php/src/Google/Protobuf/Internal/Message.php:75
Stack trace:
#0 /home/jasonhe/CS/msg.pb.php(171): Google\Protobuf\Internal\Message->__construct()
#1 /home/jasonhe/CS/tt.php(4): require_once('/home/jasonhe/C...')
#2 {main}
  thrown in /home/jasonhe/CS/vendor/google/protobuf/php/src/Google/Protobuf/Internal/Message.php on line 75

**Comment by TeBoring** [comment]
I think this has been fixed in the master branch.
