### ISSUE TITLE
Add gtest as a git submodule.

### ISSUE THREAD

**Issue by jtattermusch** [google/protobuf#236]
from https://github.com/google/protobuf/blob/master/vsprojects/readme.txt:

"Check whether a gtest directory exists in the upper level directory. If
   you checkout the code from github via "git clone", this gtest directory
   won't exist and you won't be able to build the tests described below. To
   avoid this problem consider downloading one of the release tar balls which
   contains gtest already and copying the gest directory from there to your
   protobuf directory".

I would argue that adding gtest as a git submodule would be a much better practice here. 
Then user would be able to grab the desired version of gtest using just one git command.

See what gRPC is doing:
https://github.com/grpc/grpc/tree/master/third_party

**Comment by xfxyjwf** [comment]
The problem is that gtest is not available as a git repository so we cannot add it as a submodule (unless we make a copy of it ourselves).

**Comment by jtattermusch** [comment]
Oh, ok, understood.

**Comment by yairchu** [comment]
@xfxyjwf: isn't gtest available at https://github.com/google/googletest ?

**Comment by xfxyjwf** [comment]
@yairchu  thanks. When this issue was created, gtest wasn't migrated to github yet. We can change to use submodule for it now.

**Comment by aaronjheng** [comment]
@xfxyjwf, any plans?

**Comment by haberman** [comment]
This seems worth doing, though I'm not sure if anyone has the bandwidth right now.
