### ISSUE TITLE
Protoc is not generating Setter for Map fields for js 

### ISSUE THREAD

**Issue by MedGhassen** [google/protobuf#2360]
Hi , 
After compiling my protos files , they is no Setters for Map fields in the generated js code. 
Any Help ?

**Comment by acozzette** [comment]
This is to be expected actually; you can get the map by calling `getFooMap()` and then subsequently modify it however you like. The test code [here](https://github.com/google/protobuf/blob/master/js/maps_test.js) shows how to do this for example.
