### ISSUE TITLE
Polymorphism in a repeated (list) field

### ISSUE THREAD

**Issue by adamatan** [google/protobuf#2363]
Hi,

I've asked a Stackoverflow question yesterday - [Polymorphism in Protocol Buffers 3](http://stackoverflow.com/questions/40575493/polymorphism-in-protocol-buffers-3). There are no answers yet, so I wonder if I can get some attention to the problem here.

In essence, I am writing a microservice that services a Feed to an API call. I want to have a protobuf `Feed` class which contains a list of `FeedItem` classes. For example, a `Feed` may contain a list with a `Poke` object, a `Like` object, and an `Image` object. All `FeedItem` classes share a few properties (like `timestamp` and `title`), but each class have unique properties, like `imageURL` or `likeCount`. 

In OOP, the natural solution is Polymorphism - having each class inside the list inherit from the `FeedItem` class - but I don't know how to express this in Protobuf 3.

![Microservice architecture](https://i.stack.imgur.com/u2k3A.png)

**How do I express this notion of Polymorphism - a list of subclasses of `FeedItem` - in Protobuf 3?**

Feel free to answer on SO and put the link here, if you wish.

**Comment by gerben-s** [comment]
Protobufs do not support polymorphism. You could make a oneof field with the fields you want to accept.
