### ISSUE TITLE
provide c# support

### ISSUE THREAD

**Issue by hepin1989** [google/protobuf#237]
we could using it in unity

**Comment by pherl** [comment]
C# support is on our road map for the official 3.0 release.

**Comment by ngbrown** [comment]
There are currently two different ways to use Protocol Buffers in C#.  One is with plain ol' C# objects (POCO) with Marc Gravell's [protobuf-net](https://code.google.com/p/protobuf-net/).  The other is more idiomatic class generation with Marc Skeet's [protobuf-csharp-port](https://code.google.com/p/protobuf-csharp-port/).  Both are valid approaches and depend on your specific application.

**Comment by jtattermusch** [comment]
https://www.nuget.org/packages/Google.Protobuf/3.0.0-alpha4
