### ISSUE TITLE
[libprotobuf ERROR google/protobuf/io/printer.cc:135]  Unclosed variable name.

### ISSUE THREAD

**Issue by Rayman** [google/protobuf#2371]
I previously reported this error at grpc/grpc#8741, but it appears to be a protobuf issue.

When I compile the following protobuf file with gRPC, I get a compile warning. Why is this? It looks like the `$` sign is not allowed in comments?

```protobuf
syntax = "proto3";

message HelloRequest {
  string name = 1;
}

message HelloReply {
  string message = 1;
}

service Greeter {
  /**
   * $
   */
  rpc SayHello (HelloRequest) returns (HelloReply) {}
}
```
Command:
```
protoc --plugin=protoc-gen-grpc=grpc_cpp_plugin --grpc_out=protos_out/cpp --cpp_out=test.proto 
```

Output:
```
[libprotobuf ERROR google/protobuf/io/printer.cc:135]  Unclosed variable name.
[libprotobuf ERROR google/protobuf/io/printer.cc:135]  Unclosed variable name.
```

**Comment by xfxyjwf** [comment]
I can compile the following proto without problem:
```
syntax = "proto3";

message HelloRequest {
  string name = 1;
}

message HelloReply {
  /**
   * $
   */
  string message = 1;
}
```
Command:
```
protoc --cpp_out=. --java_out=. test.proto
```

I believe the problem lies in the grpc code generator where it's not using the correct protobuf API to format comments (which results in the error you see).

**Comment by MickStanciu** [comment]
I had the same issue, where it was a dollar sign in the comment
`// any currency sign, e.g. £ ¥ €`
vs
`// any currency sign, e.g. $ £ ¥ €
