### ISSUE TITLE
When building in VS2013, you need to upgrade project files to VS2013 format first

### ISSUE THREAD

**Issue by jtattermusch** [google/protobuf#238]
This is done automatically upon opening the solution, it generates some warnings, but it seems that things build fine and tests pass. Nevertheless, the user experience could be better (but perhaps it's just a nit).

**Comment by pherl** [comment]
Yes, we will move to a cmake based solution and distribute generated VS project files for each version. Please stay tuned.

**Comment by jtattermusch** [comment]
Superseded by #436
