### ISSUE TITLE
how to define map<string, list<Pojo>> in proto file? will it be map<string, repeated Pojo> ?

### ISSUE THREAD

**Issue by naman-singhal** [google/protobuf#2388]
My Java class has a class variable like below :
`Map<String, List<Pojo>> map;`
Writing a proto for the same, what is the correct syntax?
I read the specification but could not ascertain how to define "repeated" variables inside a map.

**Comment by xfxyjwf** [comment]
That's not supported. You will need to define a wrapper message instead. I.e.:
```proto
message Foo {
  message ListPojo {
    repeated Pojo pojo = 1;
  }
  map<string, ListPojo> map = 1;
}
```

**Comment by mavle** [comment]
Is there a reason why this isn't supported? When converting to JSON this makes redundant objects I would't want to expose to a user.

**Comment by milon-bs23** [comment]
I fall into the same issue here. I solve the problem this way. 

```
import "google/protobuf/struct.proto";
message RelationshipMap {
  map<string, google.protobuf.ListValue> driver2trip = 1;
}
```

**Comment by 631068264** [comment]
> I fall into the same issue here. I solve the problem this way.
> 
> ```
> import "google/protobuf/struct.proto";
> message RelationshipMap {
>   map<string, google.protobuf.ListValue> driver2trip = 1;
> }
> ```

How to define the struct of ListValue?

**Comment by hakusai22** [comment]
List<List<Integer>> How is this structure defined？@milon-bs23

**Comment by milon-bs23** [comment]
https://stackoverflow.com/questions/36715078/google-protobuffer-how-to-define-list-of-lists-in-proto-file

Maybe this can help you. @hakusai22

**Comment by panyogesh** [comment]
@milon-bs23 : ListValue seems to be working only or string/numbers. Do you have a sample code.

**Comment by milon-bs23** [comment]
@panyogesh I have used it a long time with Python. I am giving a simple code not sure if will it work or you or not.

`test.proto` file:
```proto
syntax = "proto3";
import "google/protobuf/timestamp.proto";
import "google/protobuf/struct.proto";

message Test {
  map<string, google.protobuf.ListValue> data = 1;
}
```

`test.py` file:
```python
import new_test_pb2
from google.protobuf.json_format import MessageToJson
from google.protobuf import struct_pb2

test = new_test_pb2.Test()
a = struct_pb2.ListValue()
a.extend([1, 2])
test.data['12'].CopyFrom(a)
json_obj = MessageToJson(test)
print(json_obj)
with open('schema.json', 'w') as json_file:
    json_file.write(json_obj)
```

output:
```json
{
  "data": {
    "12": [
      1.0,
      2.0
    ]
  }
}

```

**Comment by panyogesh** [comment]
Thanks @milon-bs23. It solved the issue.

**Comment by vine2024** [comment]
按照上面的方式我试了一下。
我下载了google官网的包，放到环境变量里。然后执行
protoc -I . --go_out=./proto --go-grpc_out=./proto  ./proto/source/test/slot.proto
报错：
The import path must contain at least one period ('.') or forward slash ('/') character.
排查后发现是官方包struct.proto文件内容option go_package = "types";
改为option go_package = "./types";后重新生成，可以正常生成了，
但是打开生成后的文件发现types 引用路径有问题：

import (
	types "/types"
...
)
手动改成引用google.golang.org/protobuf/types/known/structpb是可以正常运行的，但是生成为什么会异常？是因为我改了"./types"吗？如果不改又执行不了，请问这个怎么解决？
