### ISSUE TITLE
isValidUtf8Test is very slow on arm

### ISSUE THREAD

**Issue by opoplawski** [google/protobuf#2389]
The Fedora arm builds of protobuf take a very long time, primarily due to running com.google.protobuf.IsValidUtf8Test.  I'm wondering if there was any way to speed this up (multiple cores, java memory settings, ?) or limiting the size of it.  Thanks.

**Comment by xfxyjwf** [comment]
How long does it take on arm? Have you compared it with non-arm builds?

**Comment by opoplawski** [comment]
See http://koji.fedoraproject.org/koji/taskinfo?taskID=16512668

Entire x86_64 build took 21 minutes.  Steps in the isValidUtf8Test look like:
```
Nov 18, 2016 4:18:01 PM com.google.protobuf.IsValidUtf8TestUtil testBytes
INFO: Round tripped 18304 of 65536
Nov 18, 2016 4:18:01 PM com.google.protobuf.IsValidUtf8TestUtil testBytes
INFO: Round tripped 18304 of 65536
Nov 18, 2016 4:18:02 PM com.google.protobuf.IsValidUtf8TestUtil testBytes
```
It's been running for over 11.5 hours on arm, and test steps look like:
```
Nov 18, 2016 6:06:31 PM com.google.protobuf.IsValidUtf8TestUtil testBytes
INFO: Round tripped 18304 of 65536
Nov 18, 2016 6:07:50 PM com.google.protobuf.IsValidUtf8TestUtil testBytes
INFO: Round tripped 18304 of 65536
Nov 18, 2016 6:09:15 PM com.google.protobuf.IsValidUtf8TestUtil testBytes
```
and has increased in time to:
```
Nov 19, 2016 2:52:51 AM com.google.protobuf.IsValidUtf8TestUtil testBytes
INFO: Processed 15 million characters
Nov 19, 2016 3:15:25 AM com.google.protobuf.IsValidUtf8TestUtil testBytes
INFO: Processed 16 million characters
Nov 19, 2016 3:32:52 AM com.google.protobuf.IsValidUtf8TestUtil testBytes
INFO: Round tripped 2650112 of 16777216
```
I suspect this may be a pure java/arm/fedora platform issue than protobuf.  But just wondering if anyone else had any insights.

**Comment by opoplawski** [comment]
It appears that this may be down to the fact that it uses the interpreted Zero VM  on arm.
