### ISSUE TITLE
protoc-gen-php: program not found or is not executable  php_out: protoc-gen-php: Plugin failed with status code 1

### ISSUE THREAD

**Issue by lanffy** [google/protobuf#2393]
Hi

When I using protobuf, I have some problems.

I used **protoc-3.1.0-linux-x86_64.zip** command which download from [https://github.com/google/protobuf/releases](https://github.com/google/protobuf/releases)

My system is ``14.04.1-Ubuntu SMP Fri Mar 11 00:26:02 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux``

When I executed command ``/bin/protoc --proto_path=src --php_out=src/protobuf /path/to/Ctest.proto``, I got some error message like this:

> protoc-gen-php: program not found or is not executable
> --php_out: protoc-gen-php: Plugin failed with status code 1.

But When I use **protoc-3.1.0-osx-x86_64.zip** command on my friend's MAC. It worked and no error.

How should I fix this error? 

Thanks!

**Comment by haberman** [comment]
I just tried the latest release and `--php_out=<dir>` works great. This should not require an external plugin because it's built into `protoc`.

**Comment by lanffy** [comment]
Thanks.
