### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by Tinadim** [google/protobuf#2395]
I just installed the protocol buffer compiler on my mac (version 3.1.0) using brew and it seems to be installed correctly. However, I am experiencing a very weird behavior. When I navigate to the folder where my .proto files are located and run the command

`protoc --java_out=/absolute_path_to_folder file.proto`

in the terminal, it works perfectly fine. But if create a script, put the exact same command inside it and then run the script in the terminal, I see the following error message:

`No such file or directory`

Can anyone please point me what I am doing wrong?

**Comment by acozzette** [comment]
Could you verify that your script is calling the same `protoc` that you are calling when you run the command manually? If you run `which protoc` in your script that should tell you the path to the `protoc` binary it is using.

**Comment by Tinadim** [comment]
Both are using the `protoc` located in `/usr/local/bin/protoc`

**Comment by thomasvl** [comment]
What directory are you in when you run the script?  Is it the same one the proto file is in?  What is the exact content of the script?  How do you run the script.

**Comment by Tinadim** [comment]
@thomasvl exact same directory for both. 

Script name: protoCompiler.sh
Script content: `protoc file.proto --java_out=../../../../core/src`
How do I run the script: `./protoCompiler.sh`
Error message: `/: No such file or directory`

As I said, if I run the line `protoc file.proto --java_out=../../../../core/src` in the terminal itself, it works.

**Comment by acozzette** [comment]
Hmm, that's strange. Are you sure that error is coming from `protoc`? I wonder if perhaps something is failing in one of your dotfiles (like `~/.bashrc`) before it even gets to the protoc command. Another thing to consider is that if you have a shell script without a shebang line (e.g. `#!/bin/bash`), you might ending up with a subtly different environment than you would get at your terminal.

**Comment by vimiPonyai** [comment]
the same problem with you.  Any update? thanks!
