### ISSUE TITLE
While accessing Data.data() getting exception

### ISSUE THREAD

**Issue by avaan** [google/protobuf#2396]
I am trying to access Data.data()  in swift. but i am getting exception with below error,

Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[_TtGCs23_ContiguousArrayStorageCSo19DCTIdentityInternal_ isInitialized]: unrecognized selector sent to instance

please let me know what I am doing wrong.

my code is below,
var internalMsg:DCTTextMessageInternal?
internalMsg = DCTTextMessageInternal()
        internalMsg?.from = from.entityId()
        internalMsg?.toArray.add(recipientIdentieies)
        internalMsg?.id_p = TextMsgPacket.messageIdGenerator.generate()
        internalMsg?.text = msgText

let data:Data = (internalMsg?.data())! --------------> Crash here

**Comment by avaan** [comment]
I found the root cause of this issue. Which is internalMsg?.toArray.add(recipientIdentieies) is giving issue. which is array of DCTMessageInternal objects.  After commenting this the exception is gone.

**Comment by thomasvl** [comment]
Sounds like you have required fields but aren't setting the, all required fields must be set to use the data() method - https://github.com/google/protobuf/blob/master/objectivec/GPBMessage.h#L324-L325.

From the snippet you provided, I can't really tell what protos vs. other objects.  Can you include your proto definition and what type recipientIdentieies?  That might help figure out what is happening.

**Comment by thomasvl** [comment]
The toArray.add() is also a little odd.  Your comment seem to imply it is an array of message, in which case, it would be an NSArray<Message>, and that would bridge across with an append() method, not add().  So getting more info here of what the proto and types in that snippet really are is likely the only way anyone might be able to offer advise.
