### ISSUE TITLE
[php] Please release any stable version of google/protobuf 

### ISSUE THREAD

**Issue by lukaszwit** [google/protobuf#2401]
Hi,
currently only released version in packagist is v3.1.0-alpha-1
https://packagist.org/packages/google/protobuf
This makes it unusable with most projects because of "minimum-stability" i composer.json.
I would like to ask to release any stable version (if not 3.1 then maybe 3.0 with older code).

Regards

**Comment by xfxyjwf** [comment]
@TeBoring

**Comment by TeBoring** [comment]
Sorry, 3.1 is the first version that provide php support.
Currently, we are still making some API change. So, for now, we cannot release a stable version.
We may release a beta version next month.

**Comment by lukaszwit** [comment]
@TeBoring Oh I thougt that 3.0 was with php support too but just not added to packagist.
In this case I'm keeping my fingers crossed for stable release and thank you.
We can close it now.

**Comment by TeBoring** [comment]
3.3.0 is the first stable version for php.
