### ISSUE TITLE
unit test failures

### ISSUE THREAD

**Issue by damian123** [google/protobuf#2408]
I just build protobuf and get some unit test errors, can I safely ignore them?

[==========] 1904 tests from 183 test cases ran. (10465 ms total)
[  PASSED  ] 1899 tests.
[  FAILED  ] 5 tests, listed below:
[  FAILED  ] BootstrapTest.GeneratedDescriptorMatches
[  FAILED  ] RubyGeneratorTest.GeneratorTest
[  FAILED  ] TextFormatMapTest.Sorted
[  FAILED  ] TextFormatTest.Basic
[  FAILED  ] TextFormatExtensionsTest.Extensions

Using Windows 10, Visual Studio 2015, cmake

**Comment by xfxyjwf** [comment]
It seems to be a "\r\n" vs. "\n" problem and I believe you can safely ignore them.
