### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [google/protobuf#241]
I would like to point out that identifiers like "[`GOOGLE_PROTOBUF_ARENA_H__`](https://github.com/google/protobuf/blob/0a25cfe69d3c6f04d3d0a779549f126731aa4964/src/google/protobuf/arena.h#L34)" and "[`GOOGLE_PROTOBUF_SERVICE_H__`](https://github.com/google/protobuf/blob/e428862450679aaccd3675d1092f9f5253b7bd43/src/google/protobuf/service.h#L100)" [do not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL51-CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29) to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by xfxyjwf** [comment]
Thanks for pointing this out! It seems our internal code base uses both two trailing underscores and one trailing underscore in these macros inconsistently. This needs to be cleaned up.

**Comment by sahlberg** [comment]
This issue can be closed now ?
