### ISSUE TITLE
have php  tutorial?

### ISSUE THREAD

**Issue by liangjun0305** [google/protobuf#2410]
hi, https://developers.google.com/protocol-buffers/phptutorial/  can't open, have php  tutorial  and php api doc?
tks!

**Comment by mutantkeyboard** [comment]
@liangjun0305 There is no official protobuf for PHP. But you can use [this one](https://github.com/drslump/Protobuf-PHP). It's a very good implementation, with very good documentation.

**Comment by xfxyjwf** [comment]
@liangjun0305 where did you get that link? The tutorial is not available as far as I can tell.

**Comment by NicklasWallgren** [comment]
@xfxyjwf 

https://github.com/google/protobuf/tree/master/php
https://github.com/google/protobuf/pull/2052/files

**Comment by xfxyjwf** [comment]
@TeBoring The php/README.md file has a link to a non-exist php tutorial. Is the tutorial already available somewhere else, or is it work-in-progress?

**Comment by TeBoring** [comment]
You can reference https://developers.google.com/protocol-buffers/docs/reference/php-generated for now.
The broken link in README is an known issue. It needs to be updated and will be ok in next release.
