### ISSUE TITLE
PHP:  segfault error

### ISSUE THREAD

**Issue by liangjun0305** [google/protobuf#2412]
my pb file :
`syntax = "proto3";`

`message CVTitleRequest {`
`    bytes msgpack = 1;`
`}`

`message CVTitleResponse {`
`    bytes msgpack = 1;`
`}`

`service CVTitleService {`
`    rpc getTitleRank (CVTitleRequest) returns (CVTitleResponse);`
`}`

and use protoc generated php code 
`protoc --php_out=. cvtitle.proto`

but when i include the php file , I get error:
php[32553]: segfault at 8 ip b6d00b86 sp bfa086d4 error 4 in libc-2.19.so[b6c7d000+1a7000]

**Comment by liangjun0305** [comment]
php version: PHP 5.6.27-0+deb8u1
php protobuf version: 	protobuf-3.1.0a1

**Comment by TeBoring** [comment]
Could you help test against master head?

**Comment by TeBoring** [comment]
Does it work?

**Comment by liangjun0305** [comment]
@TeBoring the master work ! thanks
