### ISSUE TITLE
undefined: grpc.SupportPackageIsVersion3

### ISSUE THREAD

**Issue by erjoalgo** [google/protobuf#2420]
The following commit:

```
commit 727a60e4d135c53c4d62d708ac4528f7c077c0d0
Author: Mak Mukhi <mmukhi@google.com>
Date:   Fri Oct 21 18:06:55 2016 -0700

    update server reflection code to comply with the change to the grpc generator
```

Introduces the error:

```
# github.com/org/repo/vendor/some_grpc_lib
vendor/some_grpc_lib/some_lib.pb.go:173: undefined: grpc.SupportPackageIsVersion3`
```

The error message is not helpful. I have tried regenerating source files using the latest `protoc` 
```
$ protoc --version
libprotoc 3.1.0
```

1. How can this problem be fixed?
2. Can you provide a more helpful error message?

**Comment by xfxyjwf** [comment]
This seems a grpc issue. Can you create an issue against grpc instead?

**Comment by erjoalgo** [comment]
https://github.com/grpc/grpc-go/issues/1002
