### ISSUE TITLE
[python] Protobuf compiler proto not included with 3.1

### ISSUE THREAD

**Issue by david4096** [google/protobuf#2422]
Were the plugin proto removed from the 3.1 release? Wondering where to find `from google.protobuf.compiler import plugin_pb2 as plugin`.

https://github.com/ga4gh/schemas/blob/master/tools/sphinx/protobuf-json-docs.py#L16

**Comment by xfxyjwf** [comment]
I checked https://pypi.python.org/pypi/protobuf/3.1.0.post1 and it does have plugin_pb2.py.

**Comment by david4096** [comment]
Thanks I didn't know about the post1!
