### ISSUE TITLE
PHP extension build error

### ISSUE THREAD

**Issue by andryska** [google/protobuf#2423]
Any idea what's wrong here?

[root@www ~]# php -v
PHP 7.0.12 (cli) (built: Oct 17 2016 10:25:33) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.12, Copyright (c) 1999-2016, by Zend Technologies

[root@www ~]# pecl install channel://pecl.php.net/protobuf-3.1.0a1
downloading protobuf-3.1.0a1.tgz ...
Starting to download protobuf-3.1.0a1.tgz (193,749 bytes)
.........................................done: 193,749 bytes
14 source files, building
running: phpize
Configuring for:
PHP Api Version:         20151012
Zend Module Api No:      20151012
Zend Extension Api No:   320151012
building in /tmp/pear/temp/pear-build-rootHMQEym/protobuf-3.1.0a1
running: /tmp/pear/temp/protobuf/configure --with-php-config=/usr/local/bin/php-config
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for a sed that does not truncate output... /bin/sed
checking for cc... cc
checking for C compiler default output file name... a.out
checking whether the C compiler works... yes
checking whether we are cross compiling... no
checking for suffix of executables...
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether cc accepts -g... yes
checking for cc option to accept ISO C89... none needed
checking how to run the C preprocessor... cc -E
checking for icc... no
checking for suncc... no
checking whether cc understands -c and -o together... yes
checking for system library directory... lib
checking if compiler supports -R... no
checking if compiler supports -Wl,-rpath,... yes
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking target system type... x86_64-unknown-linux-gnu
checking for PHP prefix... /usr/local
checking for PHP includes... -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib
checking for PHP extension directory... /usr/local/lib/php/20151012
checking for PHP installed headers prefix... /usr/local/include/php
checking if debug is enabled... no
checking if zts is enabled... no
checking for re2c... re2c
checking for re2c version... 0.13.5 (ok)
checking for gawk... gawk
checking whether to enable Protobuf extension... yes, shared
checking for ld used by cc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for /usr/bin/ld option to reload object files... -r
checking for BSD-compatible nm... /usr/bin/nm -B
checking whether ln -s works... yes
checking how to recognize dependent libraries... pass_all
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking dlfcn.h usability... yes
checking dlfcn.h presence... yes
checking for dlfcn.h... yes
checking the maximum length of command line arguments... 1966080
checking command to parse /usr/bin/nm -B output from cc object... ok
checking for objdir... .libs
checking for ar... ar
checking for ranlib... ranlib
checking for strip... strip
checking if cc supports -fno-rtti -fno-exceptions... no
checking for cc option to produce PIC... -fPIC
checking if cc PIC flag -fPIC works... yes
checking if cc static flag -static works... no
checking if cc supports -c -o file.o... yes
checking whether the cc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no

creating libtool
appending configuration tag "CXX" to libtool
configure: creating ./config.status
config.status: creating config.h
running: make
/bin/sh /tmp/pear/temp/pear-build-rootHMQEym/protobuf-3.1.0a1/libtool --mode=compile cc  -I. -I/tmp/pear/temp/protobuf -DPHP_ATOM_INC -I/tmp/pear/temp/pear-build-rootHMQEym/protobuf-3.1.0a1/include -I/tmp/pear/temp/pear-build-rootHMQEym/protobuf-3.1.0a1/main -I/tmp/pear/temp/protobuf -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib  -DHAVE_CONFIG_H  -g -O2   -c /tmp/pear/temp/protobuf/array.c -o array.lo
mkdir .libs
 cc -I. -I/tmp/pear/temp/protobuf -DPHP_ATOM_INC -I/tmp/pear/temp/pear-build-rootHMQEym/protobuf-3.1.0a1/include -I/tmp/pear/temp/pear-build-rootHMQEym/protobuf-3.1.0a1/main -I/tmp/pear/temp/protobuf -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /tmp/pear/temp/protobuf/array.c  -fPIC -DPIC -o .libs/array.o
In file included from /tmp/pear/temp/protobuf/array.c:35:
/tmp/pear/temp/protobuf/protobuf.h:338: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘map_field_create’
In file included from /tmp/pear/temp/protobuf/array.c:35:
/tmp/pear/temp/protobuf/protobuf.h:449:1: warning: "Z_OBJ_P" redefined
In file included from /usr/local/include/php/Zend/zend.h:31,
In file included from /tmp/pear/temp/protobuf/array.c:35:
/tmp/pear/temp/protobuf/protobuf.h:449:1: warning: "Z_OBJ_P" redefined
In file included from /usr/local/include/php/Zend/zend.h:31,
                 from /usr/local/include/php/main/php.h:35,
                 from /usr/local/include/php/ext/spl/spl_iterators.h:24,
                 from /tmp/pear/temp/protobuf/array.c:31:
/usr/local/include/php/Zend/zend_types.h:531:1: warning: this is the location of the previous definition
/tmp/pear/temp/protobuf/array.c:62: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘repeated_field_create’
/tmp/pear/temp/protobuf/array.c: In function ‘repeated_field_init’:
/tmp/pear/temp/protobuf/array.c:87: error: ‘repeated_field_create’ undeclared (first use in this function)
/tmp/pear/temp/protobuf/array.c:87: error: (Each undeclared identifier is reported only once
/tmp/pear/temp/protobuf/array.c:87: error: for each function it appears in.)
/tmp/pear/temp/protobuf/array.c:95: warning: assignment from incompatible pointer type
/tmp/pear/temp/protobuf/array.c: At top level:
/tmp/pear/temp/protobuf/array.c:98: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘repeated_field_create’
/tmp/pear/temp/protobuf/array.c: In function ‘repeated_field_free’:
/tmp/pear/temp/protobuf/array.c:123: warning: passing argument 1 of ‘_zval_ptr_dtor’ from incompatible pointer type
/usr/local/include/php/Zend/zend_variables.h:112: note: expected ‘struct zval *’ but argument is of type ‘struct zval **’
/tmp/pear/temp/protobuf/array.c: In function ‘repeated_field_array_init’:
/tmp/pear/temp/protobuf/array.c:138: warning: passing argument 3 of ‘_zend_hash_init’ from incompatible pointer type
/usr/local/include/php/Zend/zend_hash.h:57: note: expected ‘dtor_func_t’ but argument is of type ‘void (*)(void *)’
/tmp/pear/temp/protobuf/array.c:141: error: lvalue required as left operand of assignment
/tmp/pear/temp/protobuf/array.c: In function ‘repeated_field_write_dimension’:
/tmp/pear/temp/protobuf/array.c:156: warning: initialization makes pointer from integer without a cast
/tmp/pear/temp/protobuf/array.c:180:55: error: macro "zend_hash_index_update" passed 5 arguments, but takes just 3
/tmp/pear/temp/protobuf/array.c:180: error: ‘zend_hash_index_update’ undeclared (first use in this function)
/tmp/pear/temp/protobuf/array.c: In function ‘repeated_field_get_gc’:
/tmp/pear/temp/protobuf/array.c:187: warning: initialization makes pointer from integer without a cast
/tmp/pear/temp/protobuf/array.c: In function ‘repeated_field_index_native’:
/tmp/pear/temp/protobuf/array.c:199: error: too many arguments to function ‘zend_hash_index_find’
/tmp/pear/temp/protobuf/array.c:199: warning: comparison between pointer and integer
/tmp/pear/temp/protobuf/array.c:210:61: error: macro "zend_hash_next_index_insert" passed 4 arguments, but takes just 2
/tmp/pear/temp/protobuf/array.c: In function ‘repeated_field_push_native’:
/tmp/pear/temp/protobuf/array.c:210: error: ‘zend_hash_next_index_insert’ undeclared (first use in this function)
/tmp/pear/temp/protobuf/array.c: In function ‘repeated_field_create_with_type’:
/tmp/pear/temp/protobuf/array.c:217: error: lvalue required as left operand of assignment
/tmp/pear/temp/protobuf/array.c:219: error: lvalue required as left operand of assignment
/tmp/pear/temp/protobuf/array.c:222: warning: initialization makes pointer from integer without a cast
/tmp/pear/temp/protobuf/array.c:225: warning: initialization discards qualifiers from pointer target type
/tmp/pear/temp/protobuf/array.c:227: warning: initialization makes pointer from integer without a cast
/tmp/pear/temp/protobuf/array.c: In function ‘zim_RepeatedField___construct’:
/tmp/pear/temp/protobuf/array.c:255: warning: initialization makes pointer from integer without a cast
/tmp/pear/temp/protobuf/array.c: In function ‘zim_RepeatedField_offsetExists’:
/tmp/pear/temp/protobuf/array.c:297: warning: initialization makes pointer from integer without a cast
/tmp/pear/temp/protobuf/array.c: In function ‘zim_RepeatedField_offsetGet’:
/tmp/pear/temp/protobuf/array.c:320: warning: initialization makes pointer from integer without a cast
/tmp/pear/temp/protobuf/array.c:323: error: too many arguments to function ‘zend_hash_index_find’
/tmp/pear/temp/protobuf/array.c:323: warning: comparison between pointer and integer
/tmp/pear/temp/protobuf/array.c:328: error: ‘return_value_ptr’ undeclared (first use in this function)
/tmp/pear/temp/protobuf/array.c: In function ‘zim_RepeatedField_offsetUnset’:
/tmp/pear/temp/protobuf/array.c:363: warning: initialization makes pointer from integer without a cast
/tmp/pear/temp/protobuf/array.c: In function ‘zim_RepeatedField_count’:
/tmp/pear/temp/protobuf/array.c:381: warning: initialization makes pointer from integer without a cast
make: *** [array.lo] Error 1
ERROR: `make' failed

**Comment by TeBoring** [comment]
Previously, c extension is not supported on php 7. It will be supported in 3.3 release.
