### ISSUE TITLE
Issues in the proto 3 spec

### ISSUE THREAD

**Issue by mwillema** [google/protobuf#2424]
Hi everyone,

I wrote an [ANTLR 4 grammar for Protobuf 3](https://github.com/mwillema/protobuf-parser/blob/master/src/main/antlr4/com/marcowillemart/protobuf/parser/Protobuf.g4). By doing so I found a couple of issues in the [Protobuf Language Specification](https://developers.google.com/protocol-buffers/docs/reference/proto3-spec). I explain them in [this issue on GitHub](https://github.com/mwillema/protobuf-parser/issues/1).

My 2 cents :-)

**Comment by anandolee** [comment]
Thanks for raise it up.

Have fixed issue 4 and 5 in description in our internal code which is not published yet. Will not fix 1-3
