### ISSUE TITLE
Features needed in Bazel

### ISSUE THREAD

**Issue by cgrushko** [google/protobuf#2426]
As discussed offline with @xfxyjwf, here's the list of features Bazel needs for its native proto-library rules:

- `--direct_dependencies`
- `--direct_dependencies_violation_msg `
- A yet-to-be-implemented flag to make direct-dep violations a warning instead of an error.

The motivation for the 3rd flag is similar to that of the strict-deps warning mode of Bazel's JavaBuilder. It allows developers to more quickly work on their code, without being interrupted by strict-deps errors.

**Comment by xfxyjwf** [comment]
I would prefer not adding any more flags. For (3) the argument of allowing developers to ignore errors for fast development is weak and actually against common practice as far as I can see.

**Comment by cgrushko** [comment]
1. I'm not proposing we ignore the errors (we don't need the flag for this). I'm proposing that we let developers keep testing their code in a loop (or whatever) without stopping everything because of something that's very easy to fix and is non-consequential in the short term.
2. Why is it against common practice?

**Comment by xfxyjwf** [comment]
The common practice is to treat warnings as errors, i.e., be strict when you build code. In Google we even report style issues as build errors and stop compiling. What you suggested is apparently the opposite and I'm not convinced that's beneficial.

**Comment by cgrushko** [comment]
That's the common practice when submitting code, but while developing there's no reason to make people's lives harder. 

1. Bazel's strict deps implementation takes this approach.
2. In Go, there are highly upvoted StackOverflow questions about turning off the unused import error ([1](http://stackoverflow.com/questions/19560334/how-to-disable-golang-unused-import-error), [2](http://stackoverflow.com/questions/21743841/how-to-avoid-annoying-error-declared-and-not-used-from-golang)) and an [FAQ on Go's site](https://golang.org/doc/faq#unused_variables_and_imports).

In these cases, the intention is to be forgiving when developing, and only making this an error before submitting. The rationale is that there are almost no short-term disadvantages to wrong imports, so there's no reason to disallow wrong imports in the short term.

**Comment by xfxyjwf** [comment]
There is no such difference between submitting code and developing code. We enforce build rules upon building the code, regardless whether you are trying to submitting the code or experimenting a dirty hack temporarily. Your argument is still "ignore errors for fast development", which I believe is the opposite of the common practice we are following, and I do not want to add a protoc flag for that. I don't know about bazel, but the Go team apparently decided to not provide compiler options to turn off unused import/variable errors as well.

**Comment by cgrushko** [comment]
Ok, fair enough.

Regarding the 2 other flags - any chance of getting them released in the near future?
The current Bazel canary already contains the direct-deps feature in `proto_library`.

**Comment by xfxyjwf** [comment]
The next protobuf release would be 3.2.0 with a stable php API. It's targeted the end of Dec. @Teboring for more status updates.

**Comment by cgrushko** [comment]
Any chance of doing another release before that? A month is a long time to block this feature in Bazel :)

**Comment by cgrushko** [comment]
@TeBoring - Bazel released 0.4.2, which contains all code necessary to launch `java_proto_library`, `java_lite_proto_library` and `proto_library`, with strict-proto-deps support.

However, we need the features listed in OP, which are already checked-in, and wait for a release.

Is there a chance to get an earlier release of proto-compiler?

**Comment by xfxyjwf** [comment]
@cgrushko An earlier release is not possible. The way protobuf release process is setup makes it very cumbersome to do one single release. No matter whether it's a patch release 3.1.1, or a minor release 3.2.0, at least two weeks are needed to finish the integration/testing/packaging process. The end of Dec. is likely the best we can do.

**Comment by cgrushko** [comment]
@xfxyjwf Is it possible to sync protobuf's github repo with the internal one? `--direct_dependencies_violation_msg` isn't in the repo yet, so the native Bazel rules can't be used even if one builds from HEAD.

**Comment by makdharma** [comment]
CC @nicolasnoble 
As grpc is moving to bazel based build system this bug has become important. @xfxyjwf is there a timeline for fixing this issue?

**Comment by xfxyjwf** [comment]
This feature is already available as of protobuf 3.2.0 release.
