### ISSUE TITLE
Java: unrelated return types in clone() methods

### ISSUE THREAD

**Issue by tehmoose** [google/protobuf#2428]
I'm trying to build libprotobuf-3.1.0 for Android (more specifically, android-x86 v.4.2.2, using java 1.6.0_45) and get this error:

```
external/protobuf-3.1.0/java/core/src/main/java/com/google/protobuf/AbstractMessage.java:327: types com.google.protobuf.Message.Builder and com.google.protobuf.AbstractMessageLite.Builder are incompatible; both define clone(), but with unrelated return types
  public static abstract class Builder<BuilderType extends Builder<BuilderType>>
```
I've noticed that [there is a comment](https://github.com/google/protobuf/blob/v3.1.0/java/core/src/main/java/com/google/protobuf/AbstractMessage.java#L516-L533) in the AbstractMessage.java about a (probably) similar error, but I'm not sure how to fix the one I've encountered.

**Comment by Kentzo** [comment]
This bug in Java is probably related: http://bugs.java.com/view_bug.do?bug_id=6908259

I hope there is a workaround.

**Comment by Kentzo** [comment]
Can anyone else confirm the issue?

**Comment by haberman** [comment]
Looks like this was fixed in: https://github.com/google/protobuf/pull/2602
