### ISSUE TITLE
MessageToJsonString: JsonPrintOptions should provide an option: do_not_force_SnakeCaseToCamelCase

### ISSUE THREAD

**Issue by timotheecour** [google/protobuf#2432]
I'd like to preserve the fields from a proto to it's json representation in MessageToJsonString (ie, without transforming foo_bar to fooBar); could we add an option do_not_force_SnakeCaseToCamelCase in JsonPrintOptions ?
what would be disadvantage of that if any?

## LINKS
* src/google/protobuf/util/field_mask_util.h 
* https://github.com/google/protobuf/blob/7f3e23707122f31ebfa58b7280bd56cbe77cb44e/src/google/protobuf/util/field_mask_util.cc#L84
* https://github.com/google/protobuf/blob/master/src/google/protobuf/util/json_util.h#L80
* https://github.com/google/protobuf/issues/1690

**Comment by xfxyjwf** [comment]
There is already such an option in Java:
https://github.com/google/protobuf/blob/master/java/util/src/main/java/com/google/protobuf/util/JsonFormat.java#L160

Though we haven't gotten time to port the feature to C++ yet. If you are willing to help, feel free to send me a pull request to add such an option.

**Comment by jecarter** [comment]
I have a port for this if there is still interest.

**Comment by xfxyjwf** [comment]
@jecarter Could you send me a pull request?

**Comment by timotheecour** [comment]
@jecarter  of course there is still interest; can't see it under https://github.com/jecarter

**Comment by timotheecour** [comment]
ping @jecarter ? (even if not in a pretty state)

**Comment by xfxyjwf** [comment]
Fixed by https://github.com/google/protobuf/pull/2867 thanks to @mojoBrendan 's contribution
