### ISSUE TITLE
Add proto_lang_toolchain() rules to root BUILD file

### ISSUE THREAD

**Issue by cgrushko** [google/protobuf#2434]
Bazel's upcoming proto support rules look for toolchains in the external repository `@com_google_protobuf_xxx//:xx_toolchain` for language/flavor `xxx`.

For example, in order to use `cc_proto_library`, one should place the following in their protobuf's distro's root `BUILD` file:

```
proto_lang_toolchain(
  name = "cc_toolchain",
  runtime = ":protobuf",
  command_line = "--cpp_out=$(OUT)",
  visibility = ["//visibility:public"],
)
```

And the following in their own project's `WORKSPACE` file:

```
local_repository(
  name = "com_google_protobuf_cc",
  path = "/path/to/protobuf-3.1.0/"
)
```

This feature-request is about adding these toolchains to protobuf's distributions.

**Comment by xfxyjwf** [comment]
Could you help send a pull request to add these rules?

**Comment by cgrushko** [comment]
Sent https://github.com/google/protobuf/pull/2436.

Questions -

1. Is changing `master` enough? does it cover all languages? does it cover the binary release you have? (e.g., protoc-3.1.0-osx-x86_64.zip)
2. Where would Java and JavaLite toolchains go?

**Comment by xfxyjwf** [comment]
Your change only adds cc_toolchain so that would only covers C++. The binary release is not related to bazel. For other languages, the toolchain rule should live where the runtime rule is defined. For Java/Python, they should live with the C++ rule. JavaLite toolchain will need to go into the javalite branch.

**Comment by cgrushko** [comment]
Blocked on #2762

**Comment by xfxyjwf** [comment]
Now we have toolchains rules for cc, java, and javalite.
