### ISSUE TITLE
PHP suggestions

### ISSUE THREAD

**Issue by troublete** [google/protobuf#2440]
Good afternoon,

I now have explored the PHP library of protobuf a good bit and even though I realize it is still in Beta state I would like to make two suggestions that could improve the library. 

* The code generator for PHP *IS ALREADY* created composer conform. So it doesn't really make sense that the classes generated defined with imports create `require_once` statements, and they even break the autoloading completely when the generated classes get included in the autoloading via composer. My suggestions here would be to use `use` statements instead which will then just include the full qualified namespace of the imported proto file.

* Secondly: even though the internal library has a nearly completlely covering error handling, it would be more appropriate to change the current behaviour of throwing errors to throwing exceptions (especially in the check functions). Since they can be handled way more proper in PHP applications.

Else it is pretty neat! Some inconssistencies with the API but overall nice to use. :)

**Comment by troublete** [comment]
One more thing packagist has the wrong (too old) commit registered for `dev-master` causing issues like #2359 when one just requires `google/protobuf` in composer.json.

**Comment by TeBoring** [comment]
#2435 change the generated code to conform PSR-4. You can use psr-4 autoload in composer to load generated files. Does that fix your first suggestion?

**Comment by TeBoring** [comment]
For the second suggestion, we will consider that in future release. But in the coming release, which is very soon, we will still keep the existing behavior.

**Comment by troublete** [comment]
1: By description of #2267 that it is supposed to fix, I assume yes it'll fix my problem. Will check when I get home though to confirm. 2: Great thank you so much! :)

**Comment by troublete** [comment]
I'll close this since I assume the bug is fixed, didn't have time to try yet. If the issue still occurs, I'll just reopen.

Thanks for the feedback. 👍
