### ISSUE TITLE
make error on Mac OS 10.12.1

### ISSUE THREAD

**Issue by loversInJapan** [google/protobuf#2448]
In file included from ./google/protobuf/stubs/atomic_sequence_num.h:33:
In file included from ./google/protobuf/stubs/atomicops.h:202:
./google/protobuf/stubs/atomicops_internals_macosx.h:85:9: error: 
      'OSAtomicCompareAndSwap32Barrier' is deprecated: first deprecated in macOS
      10.12 - Use std::atomic_compare_exchange_strong() from <atomic> instead
      [-Werror,-Wdeprecated-declarations]
    if (OSAtomicCompareAndSwap32Barrier(old_value, new_value,

**Comment by thomasvl** [comment]
Duplicate of #2182

**Comment by thomasvl** [comment]
And it looks like something removed the original fix…Reopening.

**Comment by thomasvl** [comment]
@sergiocampama fyi since #2337 fixed this last time.

**Comment by xfxyjwf** [comment]
@thomasvl I believe the fix is still there. Note that a C++11 compiler is required for that fix to work.

**Comment by sergiocampama** [comment]
so this depends on how you're compiling... can you try adding -std=c++11 to your compilation steps? that should trigger the <atomic> version of the header.

I sent a PR for compiling protobuf on a mac: https://github.com/google/protobuf/pull/2460, and when compiling protos with xcode it should get the correct header already.

**Comment by loversInJapan** [comment]
Hi, I try ./configure CPPFLAGS="-Wno-deprecated-declarations" but didn't work out. I also try set the CPPFLAG variable -std=c++11 and -Wno-deprecated-declarations in Makefile and it didn't work out either.  Is there another way to solve this problem? Thanks a lot.

**Comment by loversInJapan** [comment]
well, I removed the -Werror from the CPPFLAGS variable in the Makefile of gRPC and the errors gone， but there are still many warnings which make me feel not so good. Anyway it works.
