### ISSUE TITLE
Setup github hook to run bazel tests from ci.bazel.io

### ISSUE THREAD

**Issue by xfxyjwf** [google/protobuf#2450]
@damienmg

**Comment by damienmg** [comment]
Ok so PR vetting is working. To be admin you need to make the fact that you are in the "Google" organization public then you can use "Jenkins test this please" on PR to trigger the PR.

I am still figuring out if push are working too

**Comment by damienmg** [comment]
push should work too but I have to wait until you push to master to double check

**Comment by xfxyjwf** [comment]
Thanks. I just merged a PR. What is the link to the build status?

**Comment by damienmg** [comment]
http://ci.bazel.io/job/protobuf/ is the job URL. We can see that job 518 was after the push: http://ci.bazel.io/job/protobuf/518/ So it worked.

You can embed the build status of protobuf on ci.bazel.io, see http://ci.bazel.io/job/protobuf/badge/
