### ISSUE TITLE
DefaultValueObjectWriter print map as list instead object

### ISSUE THREAD

**Issue by podsvirov** [google/protobuf#2453]
Yesterday I tried Json export/import.

When we use:
```
JsonPrintOptions print_options;
print_options.always_print_primitive_fields = true;
```
We get broken maps printing via `DefaultValueObjectWriter`. He print `map` as `list` instead `object`.

I created a subtest `JsonUtilTest.ParsePrimitiveMapIn` (#2451) for showing this behavior.

**Comment by podsvirov** [comment]
New test #2451 now PASSED but why it's working now?

**Comment by xfxyjwf** [comment]
Let's assume this is fixed :)

**Comment by podsvirov** [comment]
Ok Google :+1:
