### ISSUE TITLE
keep unknown data after deserialization to from json

### ISSUE THREAD

**Issue by vach** [google/protobuf#2455]
Recently support to ignore unknown fields when deserializing json encoded proto message was added. But the other important feature is still missing which is retaining the unknown data.

So in binary protobuf, if you are on v1.0 of some proto message and you deserialize v1.1 not only you dont break the api but you also keep the unknown fields intact, so that if you serialize the same message from 1.0 version app and send it to different client who is on v1.1, this client will be able to use that data...

native protobuf 1.1 -> 1.0 -> 1.1 works
json protobuf 1.1 -> 1.0 -> 1.1 loses information on deserialization to 1.0

**Comment by xfxyjwf** [comment]
Keeping unknown fields in JSON convention isn't possible because the data structure used to store unknown fields is specifically designed for protobuf binary format and isn't capable of storing JSON data.

**Comment by vach** [comment]
oh i see, you cannot properly represent remaining unknown json in protobuf binary... 
ok then i'll get rid of json once and for all. Thanks

**Comment by xfxyjwf** [comment]
Note that right now in proto3 unknown fields are discarded when parsing binary just like JSON. To retain unknown data you need to stick with proto2 syntax.

The discussion about the drop of unknown fields in proto3 is tracked here: https://github.com/google/protobuf/issues/272

**Comment by vach** [comment]
Oh i didn't know that, didn't use proto3 though. Thanks
