### ISSUE TITLE
ByteInput-based CIS (Mirror of ByteOutput-based COS)

### ISSUE THREAD

**Issue by anoopsjohn** [google/protobuf#2456]
Just as it is possible to specify a ByteOutput-based COS, we'd like similar on the read-side.
Background: In Apache HBase, we are working on offheaping our write pipeline. Requests are read from the socket into N offheap ByteBuffers. The content is protobuf. We'd like to be able to read the protobuf content without pulling the data onheap first. Hence we'd like to implement a ByteInput that reads across N offheap ByteBuffers....

**Comment by anoopsjohn** [comment]
ByteInput we want it to be offset addressable like byte[]/BB. So it is not like an IS.

**Comment by BSBandme** [comment]
Maybe the new [IteraterDirectByteBufferDecoder](https://github.com/google/protobuf/blob/master/java/core/src/main/java/com/google/protobuf/CodedInputStream.java#L3092) is a solution for you
