### ISSUE TITLE
PHP generated code not compatible with grpc lib

### ISSUE THREAD

**Issue by zorrocaesar** [google/protobuf#2458]
In Grpc/UnaryCall::start(), at line 53, there is a call to $data->serialize(). If you generate the request/response classes with the protoc executable (v3.1.0), the request class extends \Google\Protobuf\Internal\Message which doesn't even define the serialize() method, so PHP throws a fatal error:

`PHP Fatal error:  Uncaught Error: Call to undefined method Helloworld\HelloRequest::serialize() in /home/user/workspace/grpc/php/vendor/grpc/grpc/src/php/lib/Grpc/UnaryCall.php:53` 

So it seems that the grpc PHP library is still relying on [drslump/Protobuf-PHP](https://github.com/drslump/Protobuf-PHP) and not on [google/protobuf](https://github.com/google/protobuf).

**Comment by TeBoring** [comment]
@stanley-cheung

**Comment by stanley-cheung** [comment]
The released version (1.0) is still using drslump/Protobuf-PHP - that's correct.

The `master` branch, currently under development, will be using google/protobuf in an upcoming 1.1 release, which is currently TBD.

**Comment by zorrocaesar** [comment]
Thanks.
