### ISSUE TITLE
no case in switch

### ISSUE THREAD

**Issue by liyujun** [google/protobuf#247]
file: protobuf/src/google/protobuf/compiler/cpp/cpp_message.cc

void MessageGenerator::GenerateClassDefinition(io::Printer* printer)
{
....
  uses_string_ = false;
  for (int i = 0; i < descriptors.size(); i++) {
    const FieldDescriptor* field = descriptors[i];
    if (field->cpp_type() == FieldDescriptor::CPPTYPE_STRING) {
      switch (field->options().ctype()) {
        default: uses_string_ = true; break;
      }
    }
  }
....
}

**Comment by pherl** [comment]
If this is from a warning, please safely ignore it. There are cases in the internal version of protobufs that deals with different ctypes. Unfortunately due to dependency issues, these ctype implementations haven't been opensourced yet, thus the code is currently stripped out.
