### ISSUE TITLE
can not compiled with php7.1.0

### ISSUE THREAD

**Issue by wuceyang** [google/protobuf#2481]
there are many warnings and errors while compiling source code to php extension
1.cd /root/protobuf-3.1.0/php/ext/google/protobuf
2.phpize
3../configure --with-php-config=/usr/local/php7.1.0/bin/php-config
4.make

or 

1.cd /root/protobuf-3.1.0/php/ext/google/protobuf
2.pear package
3.sudo pecl install protobuf-3.1.0a1.tgz

there are the same errors and warnings.
the operation system is CentOS-7-x86_64-Minimal-1511.
and the required extensions autoconf/automake/libtool/make/gcc/pear/pecl have been installed!
there is my screenshot
![pb_err1](https://cloud.githubusercontent.com/assets/1538757/21072547/873fc7fa-bf01-11e6-8bba-5797d21c77e4.png)

**Comment by TeBoring** [comment]
Sorry, the c extension is not supposed to be working with 7.x. We will support it in future.
