### ISSUE TITLE
Support for MonetaryAmount

### ISSUE THREAD

**Issue by luistrigueiros** [google/protobuf#2483]
Hi,

I would love to see support for MonetaryAmount in a similar way that exist with the JSR354 to solve the question of how to we serialize over the wire a monetary amount in a language neutral way and been able to have different languages working with the same concept of money. 
At the basics we I now that a monetary amount has a currency and an amount value, but how do we serialize the amount is it a double or a BigDecimal ? 
This seems to be such a common use case the that maybe would be support out of the box the same way that the is support for Timestamp.

Thank you, kindly
 Luis Oscar Trigueiros

**Comment by haberman** [comment]
I can see how this would be convenient. However I think it is (currently) outside the scope of protobuf.

Almost every language has a time type, so Timestamp lets us convert back and forth easily between protos and language-native types. Money is much more complicated, and there are far fewer language-native types for it.

I think it would make a lot of sense to create a `money.proto` file that could serialize the types defined in JSR354. You could put this in its own GitHub project and provide convenient conversion to/from the JSR354 types. If other languages also started creating money types, you could provide conversion to those types also.

If this `money.proto` became popular across many languages, we could consider putting it (or something like it) in the main protobuf repository. I think this would be the best approach towards getting money into protobuf.

**Comment by ahmetb** [comment]
For those visiting this issue, money.proto exists as part of googleapis: https://github.com/googleapis/googleapis/blob/master/google/type/money.proto

**Comment by Sigvaard** [comment]
But how to use money.proto? How to convert to decimals to nanos and nanos to decimals?
