### ISSUE TITLE
has_foo() for a nested message should be removed in proto3

### ISSUE THREAD

**Issue by alfredkcp** [google/protobuf#249]
Hello,

I found this within the generated Test1 class in both alpha 1 and 2 of V3.0.0:
```
inline bool has_submsg1() const;
```

I believe this should be removed following the response from issue#234. This is my example code:
```
message SubMsg1 {
   string Code = 1;
   int32 Num = 2;
}
message Test1 {
   SubMsg1 SubMsg1 = 1;
}
```

**Comment by cfallin** [comment]
Hi, actually, this is an explicit part of the field-presence design of proto3: message fields *do* have field presence. They are the only fields that have field presence (are nullable). If we remove this, there is no way to have any optional part of a message.
