### ISSUE TITLE
C#: import with different namespace

### ISSUE THREAD

**Issue by kwaclaw** [google/protobuf#2494]
Update: Seems I was using an older version of protoc, its working now. Please ignore.

I have a situation where the code generated from an import is put into a different namespace than the current .proto file. So my code does not compile.

Is there a way to have the import use an option, something like:
```
import "Base.proto" with option csharp_namespace = "My.Base";
```
so that the types declared in Base.proto would be referenced using the namespace My.Base?

Or more simply, should the import not respect the csharp_namespace  option used in Base.proto?

Or maybe I am missing something?

Karl

**Comment by jtattermusch** [comment]
Using an `import with option` is not possible and it wouldn't be a good feature.

If you have a situation like the one you're describing, it is a bug in the code generator, please provide a minimal example that reproduces the issue and the commandline you are using to generate.

**Comment by kwaclaw** [comment]
I have already corrected my initial posting - after an update everything works OK. 
I apologize for the inconvenience.
