### ISSUE TITLE
[QUESTION] 3.0.0-alpha-2 not on PyPi?

### ISSUE THREAD

**Issue by rstuart85** [google/protobuf#250]
It looks like version 3.0.0-alpha-2 was [released 21 days ago](https://github.com/google/protobuf/releases/tag/v3.0.0-alpha-2) but for some reason it isn't on PyPi. Is there any chance it is going to be put up there sometime soon?

**Comment by pherl** [comment]
@haberman

**Comment by dhermes** [comment]
By the same token, why is the `3.0.0` series still marked as alpha?

/cc @tseaver

**Comment by xfxyjwf** [comment]
@dhermes it's still alpha because there are more languages and features to be implemented/supported.

**Comment by dhermes** [comment]
Ahhh I see. That is good to know. We've been using it for Python 3 compatibility for Python generated libraries and it's been working like a charm.

**Comment by rstuart85** [comment]
@dhermes likewise.

**Comment by jleclanche** [comment]
Any update on getting this on pypi?

**Comment by rguldener** [comment]
@haberman or @pherl Any chance to push this soon? Would be great to have the new version on PyPi

**Comment by attilaolah** [comment]
As @underyx says in https://github.com/google/protobuf/issues/293#issuecomment-99396700, 3.0.0-alpha-2 [is on PyPI now][1].

[1]: //pypi.python.org/pypi/protobuf/3.0.0-alpha-2

**Comment by tseaver** [comment]
@attilaolah but it can't be installed (see #333).

**Comment by attilaolah** [comment]
@tseaver ah you're right — sorry I didn't actually try to install it yet. We have built a correct `sdist` and are hosting it ourselves to work around this.

The culprit seems to be in b55a20fa2c669b181f47ea9219b8e74d1263da19, specifically https://github.com/google/protobuf/commit/b55a20fa2c669b181f47ea9219b8e74d1263da19#commitcomment-11087217.

**Comment by nathanielmanistaatgoogle** [comment]
This issue should be closed, right? 3.0.0a2 has been on PyPI since 19 May 2015, right?

**Comment by xfxyjwf** [comment]
Yes, 3.0.0a2 is on PyPI. Closing this issue.
