### ISSUE TITLE
but how to see current version

### ISSUE THREAD

**Issue by houkx** [google/protobuf#2509]
the python module READEME:
"**3) Build the C++ code, or install a binary distribution of protoc. If you install a binary distribution, make sure that it is the same version as this package. If in doubt, run:

 $ protoc --version**"

**Comment by pherl** [comment]
I assume the version is included in the zip file name. If there isn't the easiest way is to look at configure.ac. It's defined at the top. If you only have python package, version is defined in __init__.py in google/protobuf
