### ISSUE TITLE
Creating 2.5.0 tag and make the tar ball downloadable

### ISSUE THREAD

**Issue by oza** [google/protobuf#251]
Apache Hadoop depends on protobuf 2.5.0. Is it possible for you to create 2.5.0 tag and make the tar ball downloadable?

**Comment by oza** [comment]
Is the comment here(https://github.com/google/protobuf/issues/11) still effective?

**Comment by xfxyjwf** [comment]
Old releases (before 2.6) are all made in svn branches which are not ported to github. As a result there isn't a single commit that corresponds to 2.5.0 release. Instead, you will see 2.5.0-pre in the commit history and then it just jumps to 2.6.0-pre. For this reason we are not going to tag old releases.

**Comment by xfxyjwf** [comment]
FYI. We decided to manually copy the commit history from svn branches to github in order to tag old releases. Now you should be able to find 2.5.0 and 2.4.1 in our releases page.

https://github.com/google/protobuf/releases/tag/v2.5.0

**Comment by oza** [comment]
@xfxyjwf Great, it helps us very much! Thank you!
