### ISSUE TITLE
python setup.py build: Expected "required", "optional", or "repeated"

### ISSUE THREAD

**Issue by houkx** [google/protobuf#2510]
$ python setup.py build
running build
running build_py
Generating google/protobuf/descriptor_pb2.py...
google/protobuf/descriptor.proto:381:3: Expected "required", "optional", or "repeated".
google/protobuf/descriptor.proto:381:12: Expected field name.
google/protobuf/descriptor.proto:439:3: Expected "required", "optional", or "repeated".
google/protobuf/descriptor.proto:439:12: Expected field name.
google/protobuf/descriptor.proto:537:3: Expected "required", "optional", or "repeated".
google/protobuf/descriptor.proto:537:12: Expected field name.

**Comment by vanpersie32** [comment]
@houkx I have the same problem.If you have the answer,please inform me

**Comment by SebastianJL** [comment]
I have exactly the same problem. Please help.

**Comment by anandolee** [comment]
I guess you are using an old protoc that "reserved" is not supported. Update the protoc should solve the problem.
