### ISSUE TITLE
com.google.protobuf.CodedInputStream.readStringRequireUtf8()

### ISSUE THREAD

**Issue by thinkhard-j-park** [google/protobuf#2514]
Hi,

I'm using protobuf(proto3) from my latest project with protobuf-java.jar version 3.1.0.
My message encoded from python and it delivered to scala via spark-streaming RDD.
I encounter below error when trying to decode it from scala. I also have tried to convert string "UTF-8" but not worked. The field indicated from error line is just typical string type field.  I'm not sure whether it is bug or not. Would you please check this?

**console message**

Elems: [Lscala.Tuple2;@75b0f8b8
key: null
value: 
U
$dff89b9c-5a91-4a70-8889-ad0777c240ae"kafka_producer.py*2016-12-18 17:33:54.150474*�
data�{"url": "some url 0", "title": "some title", "_id": "5815a37c43cfd44120e50538", "content": "some content", "tags": ["football"]}
value length: 227
Exception in thread "streaming-job-executor-0" java.lang.NoSuchMethodError: com.google.protobuf.CodedInputStream.readStringRequireUtf8()Ljava/lang/String;
	at org.libero.messages.Messages$Event.<init>(Messages.java:160)
	at org.libero.messages.Messages$Event.<init>(Messages.java:117)
	at org.libero.messages.Messages$Event$1.parsePartialFrom(Messages.java:1564)
	at org.libero.messages.Messages$Event$1.parsePartialFrom(Messages.java:1559)
	at com.google.protobuf.CodedInputStream.readMessage(CodedInputStream.java:309)
...

**scala code**

...

    nonEmptyMsgs.foreachRDD { msgsRDD =>
      println("Trying to print each RDD: " + msgsRDD)
      println("Count: " + msgsRDD.count())
      val elems = msgsRDD.collect()
      println("Elems: " + elems)
      for (v <- elems) {
        println("key: " + v._1)
        println("value: " + v._2)
        println("value length: " + v._2.length())
        val bytes = v._2.getBytes()
        val event = EventDataProduced.parseFrom(ByteString.copyFrom(bytes))
        println("event: " + event)
      }
    }

...

**Comment by acozzette** [comment]
My guess is that in your setup you are somehow mixing old (prior to 3.0) generated code with a new (3.1.0) runtime library. For Java we guarantee that you can upgrade the runtime library without having to upgrade your generated code, but that guarantee only starts from version 3.0. I'll close this issue for now but feel free to reopen it if this doesn't fix your problem.
