### ISSUE TITLE
[Bug] #ifdef scope error in src/google/protobuf/arena_nc.cc

### ISSUE THREAD

**Issue by sylens9** [google/protobuf#2515]
The left brace of "namespace google" is in the scope of "#ifdef TEST_ARENA_PRIVATE_CONSTRUCTOR", but the right brace is out of it. That makes a compiling error when TEST_ARENA_PRIVATE_CONSTRUCTOR is not defined.

**Comment by acozzette** [comment]
Thanks for reporting this, @sylens9. I don't think those files ever worked properly and so I just removed them.
