### ISSUE TITLE
Need feedback regarding a protobuf license change to Apache Licensee v2

### ISSUE THREAD

**Issue by xfxyjwf** [google/protobuf#2518]
We are considering changing the license of protobuf from BSD to Apache License and would like to hear from protobuf users whether this change will impact the use of protobuf library. More specifically we would like to know whether this license change will prevent the use of protobuf in certain conditions. Please comment on this issue if this change would affect your project. We will use feedback on this issue to decide whether we want to make the license change or not. Thanks.

**Comment by m-ric** [comment]
What is the rationale behing this license change? What is the problem with the BSD license?

**Comment by xfxyjwf** [comment]
@m-ric It's a requirement for an organization change. I don't know all the details though.

**Comment by xfxyjwf** [comment]
Closing the issue as we haven't heard any response for a while. The license change hasn't been decided yet, but we will assume it would not negatively impact most users' use of protobuf.
