### ISSUE TITLE
JS 'toObject' method generates inconsistent key names.

### ISSUE THREAD

**Issue by rosw12** [google/protobuf#2522]
The object keys used in generated 'toObject' methods are not consistent with field names. 

message ExampleMessage {
  repeated OtherMessage **identifier** = 1;
}

The generated js toObject function produces an object with this form:
{  **identifierList** : [...] }

JSON parsing utilities (for example JsonFormat.parser().merge) expect something of this form:
{  **identifier** : [...] }

Superficially, the existing behavior may seem correct because key name is consistent with the generated js accessor function.  I would argue that this behavior is wrong.   Proto accessor functions vary significantly from language to language.  JSON (like proto) is actually a language-independent format. It makes much more sense to have a single cannonical language-independent JSON representation for proto objects.

**Comment by acozzette** [comment]
Unfortunately the toObject methods were not designed to return proto3 JSON but confusingly, they return something that is sort of like proto3 JSON but not quite. We have been thinking about updating them to actually do proto3 JSON, but this would require a fair amount of work to figure out how to make this happen without breaking backward compatibility.

**Comment by schwiet** [comment]
Is there any way to get a JSON object that matches the field names in the .proto? I have been using decodeIO/protobufJS and have a code base that accesses all field names by their proper name (from .proto). If there is a way to create such a representation with google/protobuf, I am missing it. I second OPs request that field names not be created in this idiosyncratic way.

**Comment by haberman** [comment]
See #1904: there are currently no plans for true JSON serialization, but any updates would go to this bug.
