### ISSUE TITLE
Where I can find version 2.5

### ISSUE THREAD

**Issue by legatoo** [google/protobuf#253]
I am building Hadoop Yarn, and only 2.5 is compatible . I use to download 2.5 tar from google code, but with git, I could only build protobuf which is not 2.5. Does anyone know how to build to version 2.5 or where to download.

**Comment by yosukesan** [comment]
see this https://github.com/google/protobuf/releases and scroll down

**Comment by legatoo** [comment]
@yosukesan Thank you, got it.
