### ISSUE TITLE
[objectivec] provide NSArray/NSDictionary and GPBArray/GPBDictionary converting methods

### ISSUE THREAD

**Issue by aelam** [google/protobuf#2534]
I believe a lot of users need these

**Comment by thomasvl** [comment]
Can you provide more details on why you feel this is needed?  The only way to convert would be to in turn box all of the intergers/bools/floats, and the custom types are explicitly done to avoid this overhead.

**Comment by aelam** [comment]
## Array
We need to add NSArray to `GPBInt32Array`  by for-loop. so it's unconvenient based on current API 
then I extend serval methods like below. 
And I also add  IndexedSubscript methods to GPBArray makes it more convenient. we are using this a lot 

[GPBArray+NSArray.h](https://github.com/aelam/protobufEX/blob/master/ProtobufEX/Classes/GPBArray%2BNSArray.h)

```objc

#import <Protobuf/GPBArray.h>

@protocol PBArraySubscriptable <NSObject>
- (NSNumber *)objectAtIndexedSubscript:(NSUInteger)idx;
- (void)setObject:(NSNumber *)obj atIndexedSubscript:(NSUInteger)idx;
@end

@protocol PBArrayConvertable <NSObject>

- (void)addValuesFromNSArray:(NSArray<NSNumber *>*)numbers;
@optional
- (void)addNSArrayValues:(NSArray <NSNumber *>*)values __deprecated;

@end


@interface GPBInt32Array (NSArray) <PBArraySubscriptable, PBArrayConvertable>
@end

@interface GPBUInt32Array (NSArray) <PBArraySubscriptable, PBArrayConvertable>
@end
```

## Dictionary 
I also extend some method for GPBDictionary like below. Since there is a `_dictionary` wrapped inside, I can't operate it directly. I added subscriptable methods to GPBDictionary let it just works easily like NSDictionary. 

[GPBDictionary+NSDictionary.h](https://github.com/aelam/protobufEX/blob/master/ProtobufEX/Classes/GPBDictionary%2BNSDictionary.h)

@protocol PBDictionarySubscriptable <NSObject>

- (id)objectForKeyedSubscript:(NSNumber *)key;
- (void)setObject:(id)obj forKeyedSubscript:(NSNumber *)key;

@end


@protocol PBDictionaryConvertable <NSObject>

+ (instancetype)dictionaryWithNSDictionary:(NSDictionary *)dictionary;
- (void)addEntriesFromNSDictionary:(NSDictionary *)otherDictionary;

@end


#pragma mark - UInt32 -> UInt32
@interface GPBUInt32UInt32Dictionary (EX) <PBDictionarySubscriptable, PBDictionaryConvertable>


@end

## Discussion 
In my side I think they are necessary and if it's built inside that would be awesome and easy to use.
I really want to know what you think

**Comment by thomasvl** [comment]
Aside: Please don't mix the issues, subscripting is in the other issue.  It us easier if each issue is just for one discussion.

You didn't seem to actually answer the question - why do you need this such that you feel like it should be in the library?  Since ObjC doesn't really dead strip, adding every helper cause bloat the library and then the binaries of the apps using it.  So before we had any helpers like this we need a good handle on if they really would be commonly used.  What is it about your use where arrays and dictionaries of boxed values seems better?

**Comment by aelam** [comment]
Well. I know your concerns. 

When we create GPBArray or put elements in GPBArray. We prefer creating a NSArray rather than a cArray first. 
For the cArray way, we need care the size_of 
It seems no big differences. But when we need to write it hundreds of times. It's a tolerance . Though cArray has better performance. 

I believe JAVA or some other languages don't have this problem. They can get the count easily in runtime and works just like NSArray 

The extra subscript implementations is trying to get the same experience with NSArray/NSDictionary or array/dictionary implementations of other languages 

> �� 2016��12��30��������12:56��Thomas Van Lenten <notifications@github.com> ������
> 
>

**Comment by thomasvl** [comment]
Sorry, I'm not following where a cArray comes into this?  The issue you opened here was for providing conversions between the GPB*Dictionary and GPB*Array classes and the NSArray/NSDictionary ones.  I'm still trying to understand how this helps.  You mentioned adding hundreds of items; that would seem to be the exact types of cases where you want to directly use the correct type instead of creating an intermediary (that uses boxing) and then convert it to the final one.

**Comment by aelam** [comment]
Here, this one in GPBArray needs cArray to initialize 
```
- (instancetype)initWithValues:(const int32_t [])values
                         count:(NSUInteger)count;
```

What I am trying to do is  initialize it with a NSArray.
So are GPBDictionaries

**Comment by thomasvl** [comment]
That is just one way to initialize one.  You can also just alloc/init one and add values, the exact same as you would an NSArray but avoid all the boxing.

**Comment by thomasvl** [comment]
Expanding on my last comment, I'm not sure I follow the need to use the `NSArray`/`NSDictionary` first. You don't actually need to know the capacity of the GPB* up front, they can grow as you add items. For example it would be more efficient to use code like:

```objective-c
int32_t v1 = ...;
int32_t v2 = ...;
GPBInt32Array *array = [GPBInt32Array array];
[array addValue:v1];
[array addValue:v2];
...
```

Than constructing an intermediate NSArray:

```objective-c
int32_t v1 = ...;
int32_t v2 = ...;
GPBInt32Array *array = [GPBInt32Array array];
[array addValuesFromNSArray:@[ @(v1), @(v2) ]];
...
```

This avoids the overhead of alloc/init two `NSNumber`s, generating code to make an `NSArray` out of those, calling your helper to extract the numbers and add them to the `GPBInt32Array`, and finally release/dealloc'ing all of the intermediate `NSNumber`s and the `NSArray`.  So the overhead in code size, memory, and runtime is non trivial.

It may be that for your particular project you have other needs for the `NSArray`, but with the overhead of this approach it probably isn't something we would provide in the main library as it isn't a pattern we'd want to encourage.

Am I not following your needs and/or does that help clarify things for you?

**Comment by aelam** [comment]
I can understand what you said 

As I understand, the way we generally use would be like the below. 
```
int32_t cArray[5] = {1,2,3,4};
int32_t count = sizeof(cArray)/sizeof(cArray[0]);
GPBInt32Array *array = [GPBInt32Array initWithValues: cArray count: count];
```
It's hard to manage the array if we do like this
```
int32_t v1 = ...;
int32_t v2 = ...;
GPBInt32Array *array = [GPBInt32Array array];
[array addValue:v1];
[array addValue:v2];
```

I can do that. But I prefer the NSArray way in some extend. 

```
NSArray <NSNumber *>* numbers = @[@(1),@(2)];
GPBInt32Array *array = [GPBInt32Array array];
[array addValuesFromNSArray: numbers];
```

**Comment by thomasvl** [comment]
Sounds like you really want to take the hit for doing boxing/conversions.  If that's the style you want for your project that's fine, but it I don't think we'll be adding those helpers to the main library as it doesn't seem like something we'd want to encourage developers to generally do.

**Comment by richardtop** [comment]
@thomasvl what is the recommended way to convert `PBArray` to `NSArray`?

**Comment by thomasvl** [comment]
Do you mean a `GPB*Array`?  So you want to convert them to a boxed form?  The library currently doesn't provide something for this because it can be a non trivial cost in memory to use the boxed form and that's why the library doesn't provide them.

**Comment by richardtop** [comment]
@thomasvl yes, correct. The cost of rewriting current codebase to use `PBArray` is higher than any overhead of boxing/unboxing 3-5 `int` numbers. New Bionic chips should handle that easily.

I'm currently using this build of Protobuf: [minyushov/Protobuf-ObjC](https://github.com/minyushov/Protobuf-ObjC), as the changes in v3 are too significant to adopt, in that version the data type is still called `PBArray`.

I'm looking for an answer to one of these questions:

1. Quickly convert `PBArray` to `NSArray`
2. Iterate over / enumerate `PBArray` (knowing its type at compile time).

Would appreciate answering question 2, if 1 is impossible in the library.

**Comment by thomasvl** [comment]
Um, then you are asking about that other library and not the ObjC library here.  So we have no idea, you'd need to ask on that project and not this one as we can't speak for that project.

**Comment by richardtop** [comment]
@thomasvl OK, what is the recommended runtime library for working with protobuf 2.6.1? Thanks.

**Comment by thomasvl** [comment]
This library works with proto2 and proto3 syntax.  I'm not really sure what you are after in saying you want something that works with _2.6.1_, the spec hasn't change except to add features, and you don't have to use those.  Normally someone asking about a version number is worried about some form of api compatibility, and since you are already talking about using a different library, it would be a different api.  As to our objc api, we haven't made any changes since the initial release (just some additions).

The [Protobuf](http://go/gh/protocolbuffers/protobuf/blob/master/Protobuf.podspec) podspec is the one that gets updated here with releases.
