### ISSUE TITLE
PHP Reserved keywords in enum

### ISSUE THREAD

**Issue by NicklasWallgren** [google/protobuf#2546]
Reserved keywords in enums are not handled, and will result in parser error in PHP 5.5 and 5.6.

Maybe we could use a sufix, prefix or a pre-processor of some sort.

```
syntax = "proto3";
enum RequestType {
    ECHO = 1;        
}
```

**Comment by TeBoring** [comment]
The nearest release will be in two weeks. So we won't fix it this time. However, you are welcome to provide a PR.
