### ISSUE TITLE
Unit tests fail on windows

### ISSUE THREAD

**Issue by koubaa** [google/protobuf#2548]
See https://github.com/google/protobuf/issues/547

I reproduced these test failures on protobuf 3.1.0 using MSVC2012.  (the compiler actually does not matter)
[ FAILED ] 5 tests, listed below:
[ FAILED ] BootstrapTest.GeneratedDescriptorMatches
[ FAILED ] RubyGeneratorTest.GeneratorTest
[ FAILED ] TextFormatMapTest.Sorted
[ FAILED ] TextFormatTest.Basic
[ FAILED ] TextFormatExtensionsTest.Extensions

There are 9 files that need to be converted to linux line endings and the tests pass:
src/google/protobuf/testdata/map_test_data.txt
src/google/protobuf/testdata/text_format_unittest_data_oneof_implemented.txt
src/google/protobuf/testdata/text_format_unittest_extensions_data.txt
src/google/protobuf/descriptor.pb.h
src/google/protobuf/descriptor.pb.cc
src/google/protobuf/compiler/plugin.pb.h
src/google/protobuf/compiler/plugin.pb.cc
src/google/protobuf/compiler/ruby/ruby_generated_code_pb.rb
src/google/protobuf/compiler/ruby/ruby_generated_code.proto

I think the tests should not be sensitive to this since when checking out the git reposity on windows, the git default is to checkout windows-style.  A helper to do a line-by-line file diff could be used instead of comparing the entire file.

**Comment by koubaa** [comment]
Python tests reveal an additional two files:

src/google/protobuf/testdata/text_format_unittest_extensions_data_pointy.txt
src/google/protobuf/testdata/text_format_unittest_data_pointy_oneof.txt

**Comment by gerben-s** [comment]
This seems all related to CRLF

**Comment by koubaa** [comment]
I'm curious, was this fixed on master or is this not a priority?

**Comment by nehaljwani** [comment]
As a workaround, I just ended up doing: `git config --global  core.autocrlf false` while cloning on Windows and the tests passed.
