### ISSUE TITLE
Can any one please provide me the serialize and deserialize working example...(Help needed)

### ISSUE THREAD

**Issue by manthu522** [google/protobuf#2559]
// Serializes to a UInt8Array.
    var bytes = message.serializeBinary();
    console.log(bytes);

    var msg = messages.message1.deserializeBinary(bytes);
    console.log(msg);

this is giving me some object format instead of the deserialized value..

Please help me here... thanks

**Comment by petehouston** [comment]
Just two important methods: `serializeBinary()` and the static `deserializeBinary()`, your above code is invalid. Please read the documentation carefully, https://developers.google.com/protocol-buffers/docs/reference/javascript-generated

Also I've just created a demo for usage with Javascript here: https://github.com/petehouston/demo-protobuf-js

**Comment by haberman** [comment]
It looks like the examples provided by Pete answered the question, thanks!
