### ISSUE TITLE
Stuck in the building part with iOS project

### ISSUE THREAD

**Issue by ynot16** [google/protobuf#2561]
I was stuck in the building part while i build my iOS project.
The building part was said:
> There are two ways to include the Runtime sources in your project:
Add objectivec/\*.h & objectivec/GPBProtocolBuffers.m to your project......
> 
I did what it said, drag all the .h files and the GPBProtocolBuffers.m which is in the objectivec directory. However when i tried to build my project, it came an error located in the GPBProtocolBuffers.m that indicated missing all the m.files which was imported into the GPBProtocolBuffers.m.
I was wondering whether i has misunderstood the building part instruction or missed some steps, pls help fixed. thx a lot.

**Comment by thomasvl** [comment]
When you added the files to the project, did you tell Xcode to copy the files or use them from their original location?  If you copied them, they it likely only copied the files you drag and not the ones imported.

**Comment by ynot16** [comment]
This time i tried without copying them as you said, but it only worked by the second way which is 

> Add objectivec/\*.h & objectivec/\*.m except for objectivec/GPBProtocolBuffers.m to your project

anyway, it works finally, thanks a lot.
