### ISSUE TITLE
generated C++ code, GetTypeName() should be static

### ISSUE THREAD

**Issue by a4z** [google/protobuf#2573]
It should be possible to get the typename of a ProtoBuffer  class without instantiate it.
I think putting a simple static in front of the generated code should do the trick since the generated code looks like that.
```
::std::string Foo::GetTypeName() const {
   return "package.Foo";
 }
```
I guess this is even a const expression, but static would already be enough to work in a more generic way with ProtoBuffer derivative types.
Thanks in advance for fixing this! (and please do not destroy my optimism, thanks)

**Comment by anandolee** [comment]
You can get the type name and more info by descriptor.
See GetDescritpor() in message.h:
https://github.com/google/protobuf/blob/master/src/google/protobuf/message.h

I am closing it because we are not going to add GetTypeName(), feature is already supported. Feel free to reopen it if you have more questions.

**Comment by a4z** [comment]
Hej @anandolee ,  I am sorry for making the point not clear enough for you

consider this

A
```
template <typename T> auto  something() {
  return T::getTypeName() ;
}
```

vs

B
```
template <typename T> auto something() {
  return T().getTypeName() ;
}
```

T has to be of MessageLite


In case B, what is the current implementation, I have to create a instance of T for no reason.

why is this important? 

```
template <typename T> auto  ProtoFromChunck(BianryChungIncludeNameInfo info) {
  if (info.name !=  T().getTypeName() ){
     throw "Not the correct type of binary chunk"
     // Nothing useful happen but I had to instantiate a ProtoBuffer object, useless. 
 }
  
// Here it the earliest time I should pay for a ProtoBufferObject 
    T obj;
    obj.ParseFromArray (info.data (), inf.size ());
    return obj ;
}
```

You see, the current implementation requires in the wrong path unnececarry operations, this is bad, or do you think this is good?

and finally, GetDescriptor is not available in MessageLite, but only in Message, and requires the construction of an even more expensive object, what is not en improvement at all.

**Comment by peihe** [comment]
I found a static GetTypeName() is useful for building a static map keyed by protobuf type name.

**Comment by changhee1** [comment]
using the static instance,

```
template <class ProtoBuf>
inline std::string GetPBTypeName() { return ProtoBuf::default_instance().GetTypeName(); }

std::string foo_type_name = GetPBTypeName<Foo>();
```

**Comment by a4z** [comment]
> using the static instance,

* does not change my original issue, still creates an instance
* it's not the type name that is returned (. instead of ::)
* it's not a constexpr , thus, we can't have nice things

have worked around the problem, 
I mentioned and showed the base technique used [as a part of this talk](https://youtu.be/EGJAisKmUvU?si=mWP6ra9CK_FMREZZ&t=552)
