### ISSUE TITLE
C# JSON parser fails for well-known wrapper types

### ISSUE THREAD

**Issue by jskeet** [google/protobuf#2574]
(As reported on the mailing list)

I have simple proto definition like below and through the protoc compiler I am able to use the generated C# message class to covert object to byte array, de-serialize the object from byte array using the message parser etc.

When I try to use the JSON Formatter & parser, I am able to serialize the same to JSON string, but during deserialization the JSON parser throws an error about not able to convert System.UInt32 (.NET) to Google.

Will appreciate any help in resolving this. I am using Google.Protobuf.3.1.0 and Google.Protobuf.Tools.3.1.0 nuget packages

Proto:

```text
syntax = "proto3";
package testpack;
option csharp_namespace = "Test.v1";

// import proto definitions from google protobuf
import "wrappers.proto";
import "timestamp.proto";

message TestMessage {
 google.protobuf.UInt32Value testUintProperty = 1;
 google.protobuf.Int32Value testIntProperty = 2;
 google.protobuf.BoolValue testBoolProperty = 3;
 google.protobuf.Timestamp timestamp = 4;
}
```

Code:

```csharp
// this works
var testMessage = <some method to create TestMessage object using the generated TestMessage class>
var tmBytes = testMessage.ToByteArray();
var deserializedTestMessage = TestMessage.Parser.ParseFrom(tmBytes);

 // this works - json below
 JsonFormatter jsf = new JsonFormatter(new JsonFormatter.Settings(true));
 string jsonString = jsf.Format(testMessage);
  
 // this throws error - see exception details below
 var deserializedTestMessageFromJson = JsonParser.Default.Parse<TestMessage>(jsonString);
```

JSON:

```json
{ "testUintproperty": 1024, "testIntproperty": 300, "testBoolproperty": true, "timestamp": "2017-01-10T09:46:53.218325200Z" }
```

Exception:

> Unable to cast object of type 'System.UInt32' to type 'Google.Protobuf.WellKnownTypes.UInt32Value'.

Stack trace:
```text
 at lambda_method(Closure , IMessage , Object )
   at Google.Protobuf.Reflection.SingleFieldAccessor.SetValue(IMessage message, Object value)
   at Google.Protobuf.JsonParser.MergeField(IMessage message, FieldDescriptor field, JsonTokenizer tokenizer)
   at Google.Protobuf.JsonParser.Merge(IMessage message, JsonTokenizer tokenizer)
   at Google.Protobuf.JsonParser.Merge(IMessage message, TextReader jsonReader)
   at Google.Protobuf.JsonParser.Parse[T](TextReader jsonReader)
   at Google.Protobuf.JsonParser.Parse[T](String json)
   at DeviceSimulator.Program.<SendDeviceToCloudTestMessagesAsync>d__3.MoveNext() ...
```

**Comment by jskeet** [comment]
Hmm... I can't reproduce this at the moment.

One potentially-important point is that I had to change the proto file from this:

```
import "wrappers.proto";
import "timestamp.proto";
```

to this:

```
import "google/protobuf/wrappers.proto";
import "google/protobuf/timestamp.proto";
```

Perhaps that's related to the problem? Both protoc and the runtime "know" about the well-known types based on their packages... if you've created some sort of similar-but-not-quite-the-same environment for those types, that could well throw things off.

**Comment by ajaybha** [comment]
Hi,
Thanks for looking into this. I have the proto files being imported (wrappers & timestamp) under the same folder as my test proto file instead of trying to refer from the package root. I will try to refer the proto files as suggested by you and see if that makes a difference. 

What I also noted is that the generated file has the following property declaration while the [documentation ](https://developers.google.com/protocol-buffers/docs/reference/csharp-generated#wrapper_types) says that the well-known types should be generated as Nullable<T> types in C#. 

` private global::Google.Protobuf.WellKnownTypes.UInt32Value testUintProperty_;`



Would you mind sharing the class file that got generated for you? I am attaching mine 
[Test.cs.txt](https://github.com/google/protobuf/files/696330/Test.cs.txt)
[test.proto.txt](https://github.com/google/protobuf/files/696331/test.proto.txt)

**Comment by jskeet** [comment]
Right, this is definitely the problem then. Just use `-I path/to/Google.Protobuf.Tools/3.1.0/tools` and import `google/protobuf/wrappers.proto`. Basically, the way you're compiling isn't treating them as well-known types. I've attached my generated code.


[Test.cs.txt](https://github.com/google/protobuf/files/696357/Test.cs.txt)

**Comment by ajaybha** [comment]
Yes, that was the problem. Got it to working now. .
Though I am still curious about why having all the proto files & protoc compiler under one folder wasn't working as the protoc help definitely mentions that not specifying the proto-path mean the current folder is used. I hope this can be fixed some point of time in future.

Many thanks for helping solve this.

**Comment by jskeet** [comment]
Sorry, I don't fully understand how you compiled before - you've described bits of it, but not everything. 

protoc (for C#) definitely [checks for the file being `google/protobuf/wrappers.proto`](https://github.com/google/protobuf/blob/c44ca26fe89ed8a81d3ee475a2ccc1797141dbce/src/google/protobuf/compiler/csharp/csharp_helpers.h#L125).

Even if things are changed, I'd *strongly* discourage you from either mixing the "built-in" proto files with your own ones.

**Comment by jskeet** [comment]
We could potentially change that check to see whether the package name is `google.protobuf` instead, admittedly. I think we do this in a few places - I can check later on.

**Comment by jskeet** [comment]
I'm going to close this issue as it's not really a JSON parser issue, but I've opened #2575 to log the possibility of a related change.
