### ISSUE TITLE
Java classes generated by proto compiler fail to build

### ISSUE THREAD

**Issue by Safyia** [google/protobuf#2580]
I am using a simple proto file in my application. The java files are successfuly generated, but when I build the project I get the following error:

```
error: incompatible types: com.google.protobuf.GeneratedMessageV3.BuilderParent  
cannot be converted to com.google.protobuf.AbstractMessage.BuilderParent
              in  getParentForChildren(),
```

This only occurs when repeated message types like the `Address` below are used:

```
message Address {
    string city = 1;
    string country = 2;
}

message PersonalInfo {
    string name = 1;
    repeated Address adresses = 2;
}
```

**Comment by acozzette** [comment]
It sounds like you may be mixing generated code from an old `protoc` with a new runtime or vice versa. If you make sure to generate the code with a `protoc` from version 3.0 or up and use a runtime of the same version or newer then this problem should go away.
