### ISSUE TITLE
Representing date (without time) in proto3 using a well known time

### ISSUE THREAD

**Issue by achew22** [google/protobuf#2581]
Is it possible to represent a date without time in proto3 using a well known type? Timestamp is great, but if you're doing data entry often the precision provided by timestamps are more hassle than they are worth due to timezones.

**Comment by achew22** [comment]
@albertog Are you a maintainer of protobufs? If so what would the next step be here?

**Comment by albertog** [comment]
No I am using heavily

**Comment by haberman** [comment]
Sure, protobuf doesn't have a well-known type for "Date", but you are free to define your own. You can very easily define a message type with `year`, `month`, and `day` types.

**Comment by netdragonboberb** [comment]
https://github.com/googleapis/googleapis/blob/master/google/type/date.proto

**Comment by dvsingh9** [comment]
what about timestamp without using google
