### ISSUE TITLE
Add a :protoc-gen-javalite target to the BUILD file (presumably in the javalite branch?)

### ISSUE THREAD

**Issue by cgrushko** [google/protobuf#2583]

**Comment by cgrushko** [comment]
@xfxyjwf can you assign this to someone?

Also, I'm not sure whether `:protobuf_java` is the full runtime or just lite. The jar it produces contains `Message.class`, so I'm guessing the former. So this needs to be fixed too :)

**Comment by xfxyjwf** [comment]
protobuf_java is the full runtime. I will be on vacation for the next 3 weeks. Would it be OK for me to work on it after I come back?

**Comment by cgrushko** [comment]
I think at least one team wants to use java_lite_proto_library to open-source their code; they can use precompiled protobuf binaries for this, but that's hard to set up for different platforms.

I'll let them comment here on the priority of this.

**Comment by zvh** [comment]
It would be great if this could be done soon, we've been trying to get this working for months and I'd like to avoid delaying further if at all possible. Thanks!

**Comment by xfxyjwf** [comment]
@pherl to take a look.

**Comment by kamalmarhubi** [comment]
@pherl @xfxyjwf I believe this was closed by #2588.
