### ISSUE TITLE
cpp-implementation version of python library in pypi

### ISSUE THREAD

**Issue by unnonouno** [google/protobuf#2594]
`protobuf 3.2.0rc1` uploaded in pypi contains `.so` files and is built with `--cpp-implementation` option. I can't run it in my environment without `libprotobuf.so`. Previous version of protobuf does not contain `.so` files.
Please check if cpp-implementation is supported on run-time or upload pure python version of protobuf library.

**Comment by xfxyjwf** [comment]
This should already be taken care of as part of protobuf 3.2.0 release. Please file separate issues if the 3.2.0 package also doesn't work.
