### ISSUE TITLE
Does google protobuf supports any atomic update operation on fields

### ISSUE THREAD

**Issue by soumyajuit** [google/protobuf#2600]
Hi,

I am planning to use google protobuf for some development. In my use case the fields of the objects (defined using google protobuf) can get modified from multiple cores. Hence I sort of need atomic operation while calling get/set on those fields ( none of my fields are optional). So my question is does google protobuf supports atomic_fetch_add/sub (or __sync_fetch_and_add) semantics supported by GCC. 
I can see there are files name as "src/google/protobuf/stubs/atomicops_internals_generic_gcc.h", which kind of gives me faith.

Along with the same thread, is there a support for cacheline aligned. 

Thanks a lot in advance.

**Comment by gerben-s** [comment]
No protobuf does not support this. It's even unsupported to update different fields concurrently.
