### ISSUE TITLE
BSON <=> google::protobuf::Message

### ISSUE THREAD

**Issue by timotheecour** [google/protobuf#2601]
Is there any plan on extending https://github.com/google/protobuf/issues/1690 (Serialize and Parse directly to and from JSON using google::protobuf::Message) to support directly `BSON <=> google::protobuf::Message` ?

Benefits:
* speed (`proto <=> bson` instead of `proto <=> json <=> bson`) especially for binary data which would need to be encoded/decoded when passing through the json layer (eg base64)
* avoid loss of information when converting to/from json: quoting from http://stackoverflow.com/questions/6355497/performant-entity-serialization-bson-vs-messagepack-vs-json/6357042#6357042: 
> BSON has special types like "ObjectId", "Min key", "UUID" or "MD5" (I think these types are required by MongoDB). These types are not compatible with JSON. It means some type information are lost when you convert objects from BSON to JSON. It can be disadvantage to use both JSON and BSON in single service.

**Comment by asimpletune** [comment]
> speed (proto <=> json <=> bson instead of proto <=> json <=> bson)

Did you mean to say?

> speed (proto <=> bson instead of proto <=> json <=> bson)

**Comment by timotheecour** [comment]
yes, thanks; just corrected in the text above

**Comment by pherl** [comment]
We don't have such plans at the moment. Code size and complexity is one concern for us. We'd like to make the library lite-weight. If BSON was supported for one language then we have to extend the support for all the other languages as well.

However, you can always implement a proto <=> bson conversion yourself if performance is a concern.
