### ISSUE TITLE
error in autogen.sh?

### ISSUE THREAD

**Issue by nvarini** [google/protobuf#2604]
Hi, I would like to install protobuf-3.1.0 locally. Since there is no configure in the release tar.gz, I executed:
[nvarini@deneb2 protobuf-3.1.0]$ ./autogen.sh 
Google Mock not present.  Fetching gmock-1.7.0 from the web...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  362k  100  362k    0     0   247k      0  0:00:01  0:00:01 --:--:--  564k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  618k  100  618k    0     0   345k      0  0:00:01  0:00:01 --:--:--  618k
+ autoreconf -f -i -Wall,no-obsolete
configure.ac:30: error: possibly undefined macro: AC_PROG_LIBTOOL
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: /ssoft/spack/lafnetscha/opt/spack/x86_E5v2_IntelIB/gcc-5.3.0/autoconf-2.69-zmjaqc6liqgfuu7nk2y3uh5odvyqie5q/bin/autoconf failed with exit status: 1
[nvarini@deneb2 protobuf-3.1.0]$ module list

Currently Loaded Modules:
  1) gcc/5.3.0   2) autoconf/2.69   3) automake/1.15 3)libtool/2.4.6

Any idea?

**Comment by TeBoring** [comment]
Sounds like the libtool is not correctly installed.
Is this issue related?
https://github.com/tensorflow/tensorflow/issues/5237

**Comment by wjholden** [comment]
Thank you, `sudo apt-get install libtool` worked for me.

**Comment by wjholden** [comment]
I should note for others finding this page that I also had to `sudo apt-get install autoconf` to get `./autogen.sh` to work.
