### ISSUE TITLE
JS extensions binary serialization

### ISSUE THREAD

**Issue by pgn69** [google/protobuf#2605]
In JS, binary serialization of a proto object with an extension doesn't work if the value of extension evaluates to false, e.g. if it's an int32 with value zero.
In this case the extension is not serialized.

Problem seems to be in message.js function jspb.Message.serializeBinaryExtensions:

```
    var value = getExtensionFn.call(proto, fieldInfo);
    if (value) {
      .... serialize the extension value ....

```
The patch could be:

```
    var value = getExtensionFn.call(proto, fieldInfo);
    if (value !== undefined) {
      .... serialize the extension value ....

```

**Comment by acozzette** [comment]
Are you using proto3? If so then this is working as intended, because proto3 does not make a distinction between a value being empty and being set to its default value.

**Comment by pgn69** [comment]
I'm using protoc 3.1.0, but in my proto file I declared syntax = "proto2".

**Comment by acozzette** [comment]
I see, I think you're right. Do you want to send a pull request with the fix?

**Comment by pgn69** [comment]
No, I'm not so confident with this project and with proto3.
My fix seems to work with proto2 but I'm not sure it would work for proto3.

**Comment by acozzette** [comment]
This should now be fixed, thanks again for reporting this @pgn69.
