### ISSUE TITLE
Update url on pypi

### ISSUE THREAD

**Issue by jleclanche** [google/protobuf#261]
URL on pypi points to google code, should be updated to https://github.com/google/protobuf.

https://pypi.python.org/pypi/python3-protobuf

**Comment by xfxyjwf** [comment]
You are looking at the wrong package. Our official protobuf package on Pypi is:
https://pypi.python.org/pypi/protobuf

It currently points to https://developers.google.com/protocol-buffers/

**Comment by jleclanche** [comment]
That package should be deleted then? It's registered to @googlegroups.com, I'm not sure if that means that url updated it.

**Comment by xfxyjwf** [comment]
Unfortunately we don't own that package. Its owner is eudemonia (as shown by the package index owner).

**Comment by jleclanche** [comment]
Ah, right.
