### ISSUE TITLE
Missed LIBPROTOBUF_EXPORT attribute for the structure GzipOutputStream::Options 

### ISSUE THREAD

**Issue by degtiaan** [google/protobuf#2610]
**Issue:**
DLL **build failure** in the module **zero_copy_stream_unittest.cc**

**Fix:**
file: \io\gzip_stream.h
class: GzipOutputStream
Internal structure Options should be declared with attribute **LIBPROTOBUF_EXPORT** , i.e 
```
    struct LIBPROTOBUF_EXPORT Options { 
    ...
    }
```

**Comment by acozzette** [comment]
This should be fixed now; let me know if you still run into any DLL problems.
