### ISSUE TITLE
Lack of binary Python packages on PyPI

### ISSUE THREAD

**Issue by public** [google/protobuf#2623]
There is a protobuf wheel on PyPI, but it is an "any" wheel. This is great, but it does mean that if you want your protobufs to be fast you need to compile your own wheels using `--cpp-implementation`.

https://github.com/pypa/manylinux wheels are now a thing that works for shipping binary wheels on Linux. Should this project ship fast binary wheels for Linux and other supported platforms?

**Comment by TeBoring** [comment]
@anandolee Can we have separate wheel for python2 and python3 and upload binaries for them?

**Comment by public** [comment]
@TeBoring Anything I can do to help keep this ticket moving?

**Comment by ryan-lane** [comment]
Agreed with @public. We also need this. Any update here?

**Comment by TeBoring** [comment]
We are working on this.

**Comment by public** [comment]
@teboring I made a PR that will build the wheels for you. Is this unwanted?

**Comment by TeBoring** [comment]
Uploaded: https://pypi.python.org/pypi/protobuf/3.2.0
I also have a PR: https://github.com/google/protobuf/pull/2693 Feel free to leave comments there.

**Comment by ryan-lane** [comment]
Is there any way you can also upload a wheel for 3.0.0?

**Comment by TeBoring** [comment]
Will do that. Could you help check 3.2.0 works?

**Comment by public** [comment]
@TeBoring We are using the 3.2.0 wheels and they seem to work as expected. Thanks a lot. :+1:

**Comment by ewalker11** [comment]
@TeBoring Just checking on the 3.0.0 wheels, would it be possible to upload those this week? Thanks for your responsiveness on this issue!

**Comment by TeBoring** [comment]
I'll do that.

**Comment by TeBoring** [comment]
done

**Comment by tebriel** [comment]
@TeBoring this causes Protobuf to now have a different behavior for 3.0.0 than it did before. 

This new version changes the behavior of protobuf such that running SomeProtobuf.FromString(‘abc’) now results in a “TypeError: a bytes-like object is required, not 'str'” where before it was: “google.protobuf.message.DecodeError: Truncated message.”. I'm concerned about the behavior change here and what other potential issues may arise from this upload.

**Comment by tebriel** [comment]
We cannot help but download this version, as the bdist wheel takes precedence over the any wheel. So even requirements.txt requiring protobuf==3.0.0 still causes subsequent builds to take the new wheel.

**Comment by TeBoring** [comment]
If your code is not compatible with cpp implementation, you can avoid wheel when you do pip install.
I think in the end your code should be modified to be compatible with both python and cpp implementation. Currently, the python implementation may allow too many invalid cases.
@anandolee to take a look of this behavior change.

**Comment by crohling** [comment]
@TeBoring The issue is less with the changes that need to be made, but more about the shifting of dependencies. There has been a stable version of this code within PyPi for several months, and now it is different. IMO a package hard pinned at a specific version should be installable today, and 2 years from now, and the artifact received should not have changed at all. This is why version pinning is used, to guarantee idempotence.

**Comment by TeBoring** [comment]
I think the exact old version can still be installed by avoid wheel.

**Comment by tebriel** [comment]
@TeBoring Yes, it can, and does work in this one case. But my greater concern is releasing software and then re-releasing the same version later but with different code and potentially different behaviors. There is no way for me to guard against this in the future and this took more than a day to diagnose because the versions were marked as the same. Ideally these new wheels would've been released as 3.0.0-1 or 1-3.0.0 to indicate that they were new versions of 3.0.0.

**Comment by TeBoring** [comment]
Sorry for the trouble. Both python and cpp implementation came from the
same commit.

**Comment by tebriel** [comment]
Yeah I understand, I guess I'm more asking for a forward looking policy where re-released versions get different version tags to prevent this happening again. Is this something that would be in line with the google/protobuf polices? Thanks.

**Comment by TeBoring** [comment]
I agree that 3.0.0.post1 would have been a better solution. It's also our
usual way to release a new build if previous pypi release had problems.
For this case, I think it's a one-time case. For future release, we will
always release both at the same time. So user code has to conform to the
new change if they want upgrade. (Even though, there won't be broken API
change)
Besides, I think the broken code is to do using our undefined behavior.
(Coding based on defined API can avoid being broken by such case)In the
long way, it's better to fix them early than late.

**Comment by tebriel** [comment]
Okay, thanks, we'll update our tests and code and will check for any other issues. Appreciate the fast response.

**Comment by public** [comment]
I think the root cause here is not releasing a wheel but that the cpp and py versions have such divergent behaviour?

**Comment by tebriel** [comment]
@public I'm definitely concerned about that. My guess is that the cpp version has type checking before we actually get to the decode. So we get a different error because the type is expected to be bytes and I'm passing string.

**Comment by TeBoring** [comment]
These divergent behavior are undefined usage. We leave them there to give
us freedom of implementation. Some of them may be easily fixed. But some
are due to language differences, and are hard to change.

**Comment by public** [comment]
It might be too late to fix the wheel disruption but it sounds worth making a dedicated ticket for the cpp/py variance to help avoid this kind of issue for people in future?
