### ISSUE TITLE
String exception in update_failure_list.py

### ISSUE THREAD

**Issue by jwilk** [google/protobuf#2636]
`conformance/update_failure_list.py` contains the following statement:
```python
raise "Asked to both add and remove test: " + line
```
But [string exceptions have been removed in Python 2.6](https://docs.python.org/2/whatsnew/2.6.html#deprecations-and-removals), so instead of nice error message you will get:
```
TypeError: exceptions must be old-style classes or derived from BaseException, not str
```

Found using [pydiatra](https://github.com/jwilk/pydiatra).

**Comment by haberman** [comment]
Fix is here: https://github.com/google/protobuf/pull/2819

**Comment by haberman** [comment]
Fix is merged.
