### ISSUE TITLE
Lack of toByteArray method in Protobuf V3

### ISSUE THREAD

**Issue by kskk02** [google/protobuf#2643]
I am using protobuf with map-reduce and I just moved to Protbuf V3 but I now cant seem to transform my built protobuf message into a byte array. I.e. there is no method message.build().toByteArray()  where message is a Builder object. Can someone advice? I added a stackoverflow question on this as well.

http://stackoverflow.com/questions/41921737/cant-find-tobytearray-method-in-protobuf-v3

**Comment by xfxyjwf** [comment]
The toByteArray() method is certainly there as it's defined in the Message interface for all message types:
https://developers.google.com/protocol-buffers/docs/reference/java/com/google/protobuf/MessageLite.html
