### ISSUE TITLE
JSON to Protobuf deserialization fails when duplicate json_name tags exist (C++)

### ISSUE THREAD

**Issue by jacobowitz** [google/protobuf#2651]
The JSON to Protobuf deserialization fails when duplicated json_name tags exist in different parts of the JSON. Although that is technically a legal JSON structure.
I only noticed that happening with the C++ API. The Java Version works fine.

You can try this case with the following simple model & code:

```
message JsonExample {
  message NestedStructureA {
    int64 number_a = 1 [json_name = "number"];
  }

  message NestedStructureB {
    int64 number_b = 1 [json_name = "number"];
  }

  NestedStructureA message_a = 1;
  NestedStructureB message_b = 2;
}
```

```
const string jsonString = "{ \"messageA\": { \"number\": 1}, \"messageB\": { \"number\": 2} }";
JsonExample* jsonExample = new JsonExample();

Status parseStatus = google::protobuf::util::JsonStringToMessage(jsonString, jsonExample);
if (parseStatus.ok()) {
  cout << "Parse status is ok, number A is: '" << jsonExample->message_a().number_a() << "', number B is: '" << jsonExample->message_b().number_b() << "'" << endl;
}
else {
  cout << "Parsing failed, status is: " << parseStatus.ToString() << endl;
}

```
If you run this code, you will get the following output:

> [libprotobuf WARNING google/protobuf/util/internal/type_info.cc:145] Field 'number_b' and 'number_a' map to the same camel case name 'number'.
> Parsing failed, status is: INVALID_ARGUMENT:message_b: Cannot find field.

I've tested that with a very recent Protobuf version from Github (last commit is 9d3288e651700f3d52e6b4ead2a9f9ab02da53f4).

I tested the same model with this Java code and it worked as expected:

```
JsonExample.Builder jsonExample = JsonExample.newBuilder();
JsonFormat.Parser parser = JsonFormat.parser();
String jsonString = "{ \"messageA\": { \"number\": 1}, \"messageB\": { \"number\": 2} }";
parser.merge(jsonString, jsonExample);
System.out.println(jsonExample.getMessageA().getNumberA());
System.out.println(jsonExample.getMessageB().getNumberB());
```

**Comment by hadrielk** [comment]
The fix for this was merged back in https://github.com/google/protobuf/commit/92064a40ceb2ecdfed42f441b9c46c9c9fa00d34 so this should be closed, right?

**Comment by xfxyjwf** [comment]
Yeah, the bug was fixed by https://github.com/google/protobuf/pull/2824
