### ISSUE TITLE
Protobuf compilation issues in powerpc

### ISSUE THREAD

**Issue by M-Vivek** [google/protobuf#266]
While compiling protobuf for powerpc achitecture, there looks to be a compilation issue as below.

../../../../../src/external/bsd/protobuf/dist/src/google/protobuf/stubs/atomicops.h:188: error: stray '#' in program
../../../../../src/external/bsd/protobuf/dist/src/google/protobuf/stubs/atomicops.h:188: error: expected constructor, destructor, or type conversion before string constant

And this got fixed by adding GOOGLE_PROTOBUF_NO_THREAD_SAFETY flag. Wanted to know the implications of this flag in powerpc. Does it mean that we cant avail thread safety in power-pc?
+.if ${MACHINE_ARCH} == "powerpc"
+CXXFLAGS += -DGOOGLE_PROTOBUF_NO_THREAD_SAFETY
+.endif

**Comment by xfxyjwf** [comment]
With GOOGLE_PROTOBUF_NO_THREAD_SAFETY, the implementation of Mutex and other atomicops used in protobuf code for thread-safety will be turned into no-op. This means you cannot use it in a multi-threaded binary (even using different message types in different threads will be problematic).
