### ISSUE TITLE
C++ std::swap does not utilize built in Message.Swap

### ISSUE THREAD

**Issue by mascojames** [google/protobuf#2661]
Noticed this issue while utilizing "zero-copy" pipes. These pipes use std::swap to enqueue and dequeue items. However, it seems code generated by protoc does not supply move constructors/assignment ops so std::swap performs the naive triple-copy method, which is EXTREMELY costly for large messages.

Not sure what the correct fix would be, but protoc could possibly provide a template specialization of std::swap (legal, overloads are not) in the definition of a message to call the protobuf provided Swap function.

**Comment by xfxyjwf** [comment]
We do have a plan to add movable constructors/assignment to protobuf and it has been working in progress. As such there should be no need to add std::swap specialization for protobuf.
