### ISSUE TITLE
php run error through composer.json to install protobuf

### ISSUE THREAD

**Issue by jackyxie** [google/protobuf#2665]
I use protobuf by installing through composer.json 

`    "files": [
      "php/src/Google/Protobuf/descriptor.php"
    ]`
with this in composer.json , I run a php script, it'll show an error "PHP Fatal error:  Cannot redeclare class Google\Protobuf\Internal\Descriptor in /workspace/Projcet/vendor/google/protobuf/php/src/Google/Protobuf/descriptor.php on line 96"

And I need to comment the following two lines in vendor/composer/autoload_files.php

`return array(
//     '7c623dc93c03ddd466695ebe6517b393' => $vendorDir . '/google/protobuf/php/src/Google/Protobuf/descriptor.php',
//     '2ad3b26993ae76fb662af22f78d4da44' => $baseDir . '/php/src/Google/Protobuf/descriptor.php',
);`

**Comment by TeBoring** [comment]
Could you paste your composer.json and test code?

**Comment by jackyxie** [comment]
The composer.json I used is from this project. 

`{
  "name": "google/protobuf",
  "type": "library",
  "description": "proto library for PHP",
  "keywords": ["proto"],
  "homepage": "https://developers.google.com/protocol-buffers/",
  "license": "BSD-3-Clause",
  "require": {
    "php": ">=5.5.0"
  },
  "require-dev": {
    "phpunit/phpunit": ">=4.8.0"
  },
  "autoload": {
    "psr-4": {
      "Google\\Protobuf\\Internal\\": "php/src/Google/Protobuf/Internal",
      "GPBMetadata\\Google\\Protobuf\\Internal\\": "php/src/GPBMetadata/Google/Protobuf/Internal"
    },
    "files": [
      "php/src/Google/Protobuf/descriptor.php"
    ]
  }
}`


Here are the test code.

`<?php

require_once __DIR__ .'/vendor/autoload.php';
require_once __DIR__ .'/Lib/Test.php';
require_once __DIR__ .'/Lib/GPBMetadata/Test.php';

$from = new Test();
$from->setId(1000);
$data = $from->getId();
var_dump($data);`

**Comment by TeBoring** [comment]
I think you should create your own composer.json and add protobuf as a dependency for your project.

**Comment by TeBoring** [comment]
Here is an example using protobuf: https://github.com/grpc/grpc/blob/master/src/php/composer.json

**Comment by jackyxie** [comment]
Thanks, I'll have a try

**Comment by jackyxie** [comment]
I use the simple way to install protobuf php package. But error still exists.

![1](https://cloud.githubusercontent.com/assets/3347704/22777078/11ff401c-eeed-11e6-8492-3a8c475638f2.png)

![2](https://cloud.githubusercontent.com/assets/3347704/22777080/12004822-eeed-11e6-9658-0779b2307a46.png)

![3](https://cloud.githubusercontent.com/assets/3347704/22777077/11ff3fa4-eeed-11e6-9735-ceb7b3569de6.png)

![4](https://cloud.githubusercontent.com/assets/3347704/22777079/11ff56c4-eeed-11e6-87be-a0292a237299.png)

**Comment by cjardmore** [comment]
I'm not familiar w/ history of either google/protobuf or composer/composer, so maybe the following solution isn't ideal for one reason or another.

When I remove the separate declaration for "descriptor.php" in the composer.json files inside google/protobuf the problem goes away (for me) :)

But then I end up w/ another problem.  The loading of the 'GPBMetadata' classes fails.  So my workaround is as follows:

```
{
  "name": "blah",
  "require": {
    "php": ">=5.5.0"
  },
  "require-dev": {
    "phpunit/phpunit": ">=4.8.0",
    "google/protobuf": "@dev"
  },
  "autoload": {
    "psr-4":{
      "GPBMetadata\\": "build/gen/GPBMetadata/"
    }
  }
}

```

Note that build/gen/GPBMetadata directory in my project is a symlink to ../../vendor/google/protobuf/php/src/GPBMetadata, since this appears to be how google/protobuf defines the path to the GPBMetadata namespace.

**Comment by yangxgkem** [comment]
del php.ini -> protobuf.so

;extension="protobuf.so"

**Comment by TeBoring** [comment]
Feel free to reopen the issue if there is still problem.
