### ISSUE TITLE
v3.2.0 release details in Github

### ISSUE THREAD

**Issue by myitcv** [google/protobuf#2666]
_Apologies if this has been discussed elsewhere, I couldn't find an issue that covers the problem_

Am I right in thinking v3.2.0 has officially been released? 

If so, please can you update the [releases page](https://github.com/google/protobuf/releases)? It currently shows the following:

<img width="1009" alt="screen shot 2017-02-05 at 16 56 54" src="https://cloud.githubusercontent.com/assets/3374574/22628015/47265176-ebc4-11e6-940b-9b2e0ea2704f.png">

For example, the following zips/tars don't appear to be available (there may be other links that also don't work):

* https://github.com/google/protobuf/releases/download/v3.2.0/protobuf-js-3.2.0.tar.gz
* https://github.com/google/protobuf/releases/download/v3.2.0/protoc-3.2.0-linux-x86_64.zip

**Comment by xfxyjwf** [comment]
Sorry, we tagged the release but forgot to publish it. It should be available now:
https://github.com/google/protobuf/releases/tag/v3.2.0
