### ISSUE TITLE
toStringUtf8 got corrupted data

### ISSUE THREAD

**Issue by kaybinwong** [google/protobuf#2667]
when i test with the following code, it got error. it seems the original data was corrupted.
what had i done wrongly?
**code**
![image](https://cloud.githubusercontent.com/assets/5570216/22634135/0e7905aa-ec62-11e6-93cd-c9685d301310.png)
**error**
![image](https://cloud.githubusercontent.com/assets/5570216/22634144/25065642-ec62-11e6-849a-f2054a10afa8.png)

**Comment by xfxyjwf** [comment]
toByteString().toStringUtf8() in your code will corrupt the data because toByteString() produces binary data and is usually not valid UTF-8 encoded byte sequence.

Instead of using it as String, just use ByteString.
