### ISSUE TITLE
Null "submessage" after deserialization in C#

### ISSUE THREAD

**Issue by flabb17** [google/protobuf#2668]
I'm using c# with "Google Protocol Buffer" v3.2.0,  proto3 format

I have a .proto with "sub message" and according to https://github.com/google/protobuf/pull/1089 i'm expecting "default value" if the filed was not set on the "other side" .

but I have null "submessage"  It's look like c++ implementation return "default" message if not found, but not c#

==> in my example "Position" can be null, wen i set "Code" without set the position !

```
syntax = "proto3";

package google.protobuf;

message ResultMessage {

		message Code {	
			enum ReadStatus {	 
			UNKNOWN = 0;
			ERROR = 1;
			NOTFOUND = 2;
			TIMEOUT = 3;
			NOTREAD = 4;
			READ = 5;
			}

			message Position {
				message Point {
					int32 x_px = 1;
					int32 y_px = 2;
				}
				message Rectangle {
					bool HasValue =1;
					Point center = 2;
					int32 height_px = 3;
					int32 width_px = 4;
					float angle_deg = 5;
					float skew_deg = 6;
				}

				// represent the position of the data
				bool HasValue = 1;
				Rectangle boundingBox = 2;
				repeated Point pointList = 3;
			}
		
		//represent a single data
		ReadStatus readStatus = 1;
		string data = 2;
		Position position = 3;
	}
	
	int32 triggerNb = 1;
	int64 when = 2;
	repeated Code codeList = 3;
}

```

**Comment by haberman** [comment]
It's true that C++ returns an empty "default" message when a submessage is unset. But some languages, like C#, do not do this. For C# you will need to check for `null` submessages manually.

#1089 isn't the same because that only concerns map entries, not regular submessages.
