### ISSUE TITLE
[Java] Option to have mutable classes for message objects

### ISSUE THREAD

**Issue by cbornet** [google/protobuf#2671]
First, note that I recognize the value of immutable objects with builders.
The problem is that I want to use [mapstruct](http://mapstruct.org/) to map my service objects to my proto messages. And mapstruct doesn't work with builders but only with mutable objects.

**Comment by xfxyjwf** [comment]
There is no plan to support a mutable Java API in opensource protobuf. There was actually a Google internal implementation of a mutable protobuf Java API, but that's for legacy support and it has been explicitly decided to not opensource it.

**Comment by cbornet** [comment]
I am sad 😞 ...

**Comment by eschneider-quotient** [comment]
> @cbornet we can use `toBuilder()` (it may be not performant)
> 
> ```kotlin
> var headers = Headers
> 		.newBuilder()
> 		.setPriority(Priority.HIGH)
> 		.build()
> headers = headers.toBuilder().setPriority(Priority.MEDIUM).build()
> ```

The code becomes too complex, specially when you have a deep field to update in a nested structure.
