### ISSUE TITLE
Why uint64, int64 Protobuf-Type be serialize as String JSON-Type in MessageToJsonString()?

### ISSUE THREAD

**Issue by david9991** [google/protobuf#2679]
Why uint64, int64 Protobuf-Type be serialize as String JSON-Type in MessageToJsonString()?
I tried to use uint64 or int64 to save the Timestamp, and convert it to JSON by MessageToJsonString() 
Here is a sample output:
```
{"timestamp":"1486454809",
"nanosecond":549593000}
```
that timestamp is int64 or uint64 and nanosecond is int32 Protobuf-Type. Why a 64-bits integer be serialized as String type? Is there any JsonOptions was discussed to support 64-bits integer to JSON integer conversion?

**Comment by thomasvl** [comment]
That's the spec for the protobuf json format: https://developers.google.com/protocol-buffers/docs/proto3#json

**Comment by david9991** [comment]
@thomasvl Oh I see, this is a Javascript precision problem that mentioned in some article, thank you very much.
