### ISSUE TITLE
PHP: Repeated field setter should accept a regular PHP array

### ISSUE THREAD

**Issue by pauln** [google/protobuf#2686]
### The problem
Currently, in order to set a repeated field in a message, you seem to have two choices - neither of which is particularly nice, especially if the repeated field is itself a message.  It would be much cleaner if the generated PHP setter would accept a regular PHP array of objects of the relevant type (in this case, the applicable message type) and internally convert them to a `RepeatedField`.

The [docs for generated PHP code](https://developers.google.com/protocol-buffers/docs/reference/php-generated#repeated-fields) appear to suggest that it's possible to provide a regular array (`$m->setFoo($array);`), but this doesn't seem to be the case - at least with Protobuf v3.1.0-alpha-1 and a repeated message (perhaps other types of repeated field do indeed accept arrays - I haven't had cause to try).

### The current options:
As far as I can see, these are the only options at present - sorry if I've missed something.

- **Create a `RepeatedField` yourself**
```
$request = new \MyNS\MyMessage();
$customWidgets = new Google\Protobuf\Internal\RepeatedField(Google\Protobuf\Internal\GPBType::MESSAGE, \MyNS\MyMessage_Submessage::class);
$widget= new \MyNS\MyMessage_Submessage();
$widget->setMyProperty('foo');
$customWidgets[] = $widget;
$request->setCustomWidgets($customWidgets);
```
This is messy, requiring direct usage of "internal" GPB classes and providing the type and class (which are already known by the generated Message class - as evidenced by its setter's call to `GPBUtil::checkRepeatedField`, which uses these exact parameters); additionally, although the `RepeatedField` can be indexed like a regular array, its elements are immutable - which restricts you to fully composing your submessage and then appending it to the `RepeatedField` (which isn't necessarily a bad thing, but is definitely a trap to watch out for).
- **Use the getter to set your repeated fields**
```
$request = new \MyNS\MyMessage();
$customWidgets = $request->getCustomWidgets();
$widget= new \MyNS\MyMessage_Submessage();
$widget->setMyProperty('foo');
$customWidgets[] = $widget;
// No call to setter required!
```
This is just plain weird, as you're using a getter in order to retrieve a reference to an (initially, but not necessarily!) empty `RepeatedField`, then appending submessages to it - without even needing to call the setter (although you can if you really want to, it's not necessary due to the getter returning a reference to the **private** property, rather than a new `RepeatedField` object).

### Potential solutions
- Ideally, the setter should be able to accept a regular PHP array.  If a regular PHP array (rather than a `RepeatedField` object) is passed to the setter, it should internally convert it to a `RepeatedField`.
- Alternatively, the generated Message class could provide a method which returns an appropriate (but always empty - NOT a reference to the Message's property) `RepeatedField` instance which can be populated and then passed to the setter.  This would still be a bit clumsy, and would be afflicted with the same immutability of the elements as the "Create a `RepeatedField` yourself" option outlined above, but would at least provide a sensible create/set flow rather than get/append (without set).

If there's already a nicer/cleaner way of doing this that I've managed to miss, I'm more than happy to be pointed in the right direction; likewise, if anyone else has a more elegant solution (or a nice, clean, self-contained workaround), I'm all ears.

**Comment by TeBoring** [comment]
Thanks for your proposal. I will add the feature to setting standard array to php fields.
Currently, the recommended behavior is the second option you mentioned. I don't quite understand why you don't like it. Is it better than having a null there initially and let user create the repeated field by themselves?

**Comment by mkaminski1988** [comment]
Thank you @pauln, your explanation was helpful
