### ISSUE TITLE
Build fails on Cygwin - need to be using -std=gnu++11, not -std=c++11

### ISSUE THREAD

**Issue by CJxD** [google/protobuf#2690]
Not sure how autoconf chooses c++11 over gnu++11, but the latter needs to be used in order to compile successfully on Cygwin (64 bit).

For example, `src/google/protobuf/compiler/command_line_interface.cc` uses `readlink()` which is only available through the GNU extensions.

**Comment by TeBoring** [comment]
You can overried it in compiler flag: ./configure CXXFLAGS=-std=gnu+11

**Comment by CJxD** [comment]
The user should not have to be concerned with what compiler variant they have to use - not everyone knows that readlink() is only available under GNU extensions.

If you use GNU, the configure script should select the correct GNU compiler flags.
