### ISSUE TITLE
Setup.py not working

### ISSUE THREAD

**Issue by KrishnaMahi** [google/protobuf#2694]
setup.py is not working for me. I tried executing line by line commands too in Anaconda3. I get an error as //google/protobuf-python-3.1.0/__init__.py not found. What should I do now? How should I install protocol buffers? What are the setup tools to be installed? Can anyone please help me?

**Comment by TeBoring** [comment]
What did you do to get the error? What do you want to do?

**Comment by anandolee** [comment]
Closing for no response. Feel free to reopen if can provide more info
