### ISSUE TITLE
Unfreeze the Appveyor queue

### ISSUE THREAD

**Issue by podsvirov** [google/protobuf#2697]
As wrote there: http://help.appveyor.com/discussions/problems/3995-builds-are-queued

> Try cancelling this build https://ci.appveyor.com/project/protobuf/protobuf/build/1.0.3424 - that should unfreeze the queue.

We need `protobuf` account rights to cancel the build.

**Comment by FeodorFitsner** [comment]
We've cancelled that build from here. The queue is running again: https://ci.appveyor.com/project/protobuf/protobuf/build/1.0.3425

**Comment by podsvirov** [comment]
Wow @FeodorFitsner,
thanks for the quick answer and help!

**Comment by xfxyjwf** [comment]
@podsvirov @FeodorFitsner Thanks for reporting and resolving the issue!
