### ISSUE TITLE
failing to compile on Windows OS: "Missing output directives."

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [google/protobuf#270]
I've downloaded those files:
Protocol Buffers 2.6.1 full source:  https://github.com/google/protobuf/releases/download/v2.6.1/protobuf-2.6.1.tar.gz
Protocol Compiler 2.6.1 binary for windows: https://github.com/google/protobuf/releases/download/v2.6.1/protoc-2.6.1-win32.zip
from here:
https://developers.google.com/protocol-buffers/docs/downloads

Then, I've decompressed them to the same folder, and created a folder "protos" within, and I called this command to compile:

     protoc –javanano_out=src/ -I protos protos/backup.proto

(as this website said : https://plus.google.com/+fabiolobrutto/posts/KJeyKMBHVT7 ).

But I get this error:

    Missing output directives.

What should I do?
I just want to create a launcher, based on on the updated launcher3 app (lollipop).

**Comment by xfxyjwf** [comment]
javanano is only available from v3.0.0-alpha-2. You can download its sources here: https://github.com/google/protobuf/releases

**Comment by AndroidDeveloperLB** [comment]
@xfxyjwf I still fail to compile (getting the same message), using the same command. I've tried running the command on all possible files:
protobuf-java-3.0.0-alpha-2.zip
protobuf-javanano-3.0.0-alpha-2.zip
Source code (zip)

I've used the latest compiler:
protoc-3.0.0-alpha-2-win32.zip

Can you please provide a step by step explanation?
Will it create all needed files? for example the "BackupProtos.java" file?

**Comment by cfallin** [comment]
Is that a single dash in the option, i.e., `-javanano_out` ? Try it with two dashes: `--javanano_out`.

**Comment by AndroidDeveloperLB** [comment]
@cfallin Can you please point me to the correct file? so that we could continue in the right direction?

**Comment by cfallin** [comment]
As @xfxyjwf said above, you need 3.0.0-alpha-2. The windows compiler binary should be fine, unless I'm mistaken. Basically, I'm just pointing out a typo (two dashes instead of one).

**Comment by AndroidDeveloperLB** [comment]
@cfallin But which file? I've found 3 possible candidates...

**Comment by cfallin** [comment]
Use this to get `protoc`: protoc-3.0.0-alpha-2-win32.zip

Do *exactly* the same thing you did before, except for these changes we have suggested: (i) use 3.0.0-alpha-2 instead of the old version you had, and (ii) fix the dash typo.

**Comment by AndroidDeveloperLB** [comment]
@cfallin I meant, which file should I download and perform the compilation command on? What you've provided is the compiler. For Android, which of those should I work on:
- protobuf-java-3.0.0-alpha-2.zip
- protobuf-javanano-3.0.0-alpha-2.zip
- Source code (zip)

Anyway, I've tried doing it for each of those files, and now I get this error for all of them:

    protos/backup.proto: No such file or directory

So I created a folder ".../protos/backup.proto" , and then I got this error (again, for all of those files):

    protos/backup.proto: Permission denied

I used this command this time:

    protoc --javanano_out=src/ -I protos protos/backup.proto

**Comment by cfallin** [comment]
I'm afraid I don't understand what you're trying to do. It doesn't make sense to "perform the [protoc] compilation command" on the Protocol Buffers source code distribution. `protoc` is a compiler that takes *your* `.proto` source code (i.e., a `.proto` file that you have personally written) and generates code that implements the proto types.

If you had literally invoked `protoc` with a `.zip` file as input, you would have gotten parse errors. So you must be extracting the `.zip` and picking a `.proto` file from our source code. You shouldn't need to do this if your only goal is to use protocol buffers.

Other parts of your last message also don't make sense. Why do you create a folder with the name `backup.proto`? `.proto` files are supposed to be files, not folders. This might explain the "Permission denied" error you are getting (I don't know how Windows behaves when you try to open a folder as a plain file).

Could you explain from first principles what you are trying to do?

**Comment by cfallin** [comment]
OK, making progress. It seems you've been able to invoke `protoc` on a `.proto` file now.

Do you see the output files in the output directory you specified? If so, protoc is working correctly (and any further issues should go to this "Launcher3" project). If not, let us know and we'll diagnose further.

**Comment by AndroidDeveloperLB** [comment]
I assume the input is the "protos/backup.proto" file, and the output is inside the "src" folder, but all I can see there is a single file : "...src\com\android\launcher3\backup\BackupProtos.java" . 

Shouldn't there be more files? Or at least a jar file?
By importing the project, I see a lot of classes that are missing. I might be wrong, but I think all start with "com.google.protobuf.nano.*" . For example: 
com.google.protobuf.nano.MessageNano

**Comment by cfallin** [comment]
`protoc` is a code generator -- its output is Java. It is not a full build system, so it does not produce JAR files.

The `com.google.protobuf.*` classes are in the runtime. These are what you will find in those other files you mentioned earlier (you want protobuf-javanano-3.0.0-alpha-2.zip).

It sounds like everything is working as intended. Please let us know if there are any other issues.

**Comment by AndroidDeveloperLB** [comment]
After downloading "protobuf-java-3.0.0-alpha-2.zip" from here:
https://github.com/google/protobuf/releases

I got all source code errors figured out, so I think you've solved everything. Thank you.
Maybe I should post a tutorial about how to import the launcher, so that others would see how to do it. I could also put it into a repository.

**Comment by yuchuangu85** [comment]
How can i use this:
 protoc –javanano_out=src/ -I protos protos/backup.proto
to generate the "BackupProtos.java" file?
Is there a tutorial to introduce the step?

**Comment by xfxyjwf** [comment]
@yuchuangu85  see:
https://developers.google.com/protocol-buffers/docs/javatutorial

This tutorial talks about Java but it's mostly the same for javanano regarding how to compile proto files.

**Comment by yuchuangu85** [comment]
@xfxyjwf :
Thank you! I have generated the "BackupProtos.java" file.
