### ISSUE TITLE
Caffe Installation: 'atomic' file not found

### ISSUE THREAD

**Issue by brianscroggins24** [google/protobuf#2703]
I've been attempting to install caffe using the guide on the caffe installation website. They recommended altering the protobuf.rb file adding the environment variables:

def install
      # ADD THE FOLLOWING:
      ENV.append "CXXFLAGS", "-stdlib=libstdc++"
      ENV.append "CFLAGS", "-stdlib=libstdc++"
      ENV.append "LDFLAGS", "-stdlib=libstdc++ -lstdc++"
      # The following is necessary because libtool likes to strip LDFLAGS:
      ENV["CXX"] = "/usr/bin/clang++ -stdlib=libstdc++"
      ...
end

I've attempted to do this first on mac OSX El Capitan but I continually get the the errors listed below

In file included from ./google/protobuf/stubs/atomicops.h:200:
./google/protobuf/stubs/atomicops_internals_generic_c11_atomic.h:36:10: fatal error: 'atomic' file not found
#include <atomic>
         ^
In file included from google/protobuf/compiler/code_generator.cc:37:
In file included from ./google/protobuf/compiler/plugin.pb.h:23:
In file included from ./google/protobuf/arena.h:54:
In file included from ./google/protobuf/stubs/atomic_sequence_num.h:33:
In file included from ./google/protobuf/stubs/atomicops.h:200:
./google/protobuf/stubs/atomicops_internals_generic_c11_atomic.h:36:10: fatal error: 'atomic' file not found
#include <atomic>
         ^
In file included from google/protobuf/compiler/plugin.cc:53:
In file included from ./google/protobuf/compiler/plugin.pb.h:23:
In file included from ./google/protobuf/arena.h:54:
In file included from ./google/protobuf/stubs/atomic_sequence_num.h:33:
In file included from ./google/protobuf/stubs/atomicops.h:200:
./google/protobuf/stubs/atomicops_internals_generic_c11_atomic.h:36:10: fatal error: 'atomic' file not found
#include <atomic>
         ^
In file included from google/protobuf/compiler/command_line_interface.cc:57:
In file included from ./google/protobuf/stubs/shared_ptr.h:36:
In file included from ./google/protobuf/stubs/atomicops.h:200:
./google/protobuf/stubs/atomicops_internals_generic_c11_atomic.h:36:10: fatal error: 'atomic' file not found
#include <atomic>
         ^
1 error generated.
make[2]: *** [google/protobuf/compiler/plugin.lo] Error 1
make[2]: *** Waiting for unfinished jobs....
1 error generated.
make[2]: *** [google/protobuf/compiler/code_generator.lo] Error 1
1 error generated.
1 error generated.
make[2]: *** [google/protobuf/compiler/plugin.pb.lo] Error 1
make[2]: *** [google/protobuf/compiler/command_line_interface.lo] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
/usr/local/Homebrew/Library/Homebrew/debrew.rb:11:in `raise'
BuildError: Failed executing: make

After struggling with this for more than 3 days I'm not sure where to go from here so I thought i'd reach out for some help. Any advice on where to go would be great.

**Comment by TeBoring** [comment]
What's the version of the protobuf? Where do you get the source?

**Comment by xoxuewei** [comment]
I am also getting the same error when trying to install protobuf (for caffe) using

brew install --build-from-source --with-python -vd protobuf

I did not alter the  protobuf.rb file however. I am also using Mac OSX Sierra.

**Comment by xoxuewei** [comment]
After deleting those the env variables added to the protobuf.rb file, the installation worked

**Comment by ZhuFengdaaa** [comment]
@xoxuewei You mean you delete this variables ?

```
# ADD THE FOLLOWING:
ENV.append "CXXFLAGS", "-stdlib=libstdc++"
ENV.append "CFLAGS", "-stdlib=libstdc++"
ENV.append "LDFLAGS", "-stdlib=libstdc++ -lstdc++"
# The following is necessary because libtool likes to strip LDFLAGS:
ENV["CXX"] = "/usr/bin/clang++ -stdlib=libstdc++"
```

Wiil this deletion do harm to the installation of caffe ?

**Comment by xoxuewei** [comment]
I never ended up successfully completing the installation, but for me, not using those variables moved me further in the process I believe.
