### ISSUE TITLE
protoc installation not working

### ISSUE THREAD

**Issue by KrishnaMahi** [google/protobuf#2708]
I tried many times installing, "protoc-3.2.0-windows-x86_64.exe", but it doesn't get installed. When I double-click on it, there would be no screen displayed. I tried opening it through command line interface. I got a message as "Missing Input File". 
![protoc](https://cloud.githubusercontent.com/assets/19369107/22851605/a2971a62-f04d-11e6-8e62-beb6fd9e9aa8.jpg)
What is that missing input file? What should I do now? Please respond to my problem at the earliest!

**Comment by podsvirov** [comment]
Hello @KrishnaMahi, please more info.
For example:
- OS;
- language;
- IDE;
- What artifacts do you have and what you want to get?..

**Comment by TeBoring** [comment]
Looking from your image, I think you have successfully installed protoc.
You need to provide the proto file to protoc: protoc --cpp_out=. test.proto

**Comment by KrishnaMahi** [comment]
Should I run this command, in Command Prompt? I tried to run it, received error as, "'protoc' is not recognized as an internal or external command, operable program or batch file." 
![protocol](https://cloud.githubusercontent.com/assets/19369107/22862858/d30b5eaa-f15c-11e6-8cde-037c78512f3d.jpg)
I am running on Windows 10, with Anaconda3 4.3.0. I want Protocol Buffers for Python language. I downloaded the zip file from, " https://github.com/google/protobuf/tree/master/python ".

**Comment by TeBoring** [comment]
In your case, protoc-3.2.0-windows-x86_64.exe

**Comment by KrishnaMahi** [comment]
I have tried what you advised me, but it isn't working! Do I need to have any additional software for it to install? I have also been through the *.zip file of protocol compiler, but there is not file named "test.proto" in it. What should I do now? 
![protocol](https://cloud.githubusercontent.com/assets/19369107/22887110/ce5c2b4e-f226-11e6-968d-7e357b247542.jpg)

**Comment by kyawlinmyat** [comment]
Why this issue was closed without solving the problem.
 I am troubling the same issue.

**Comment by KrishnaMahi** [comment]
I will give you a link. Please visit that. I solved the issue on my own. So please visit that link, and you shall find a solution. [http://tech.knime.org/node/61902/view](url)

**Comment by 4saad** [comment]
the link is not working (for the solution by @KrishnaMahi )

**Comment by KrishnaMahi** [comment]
It is working @4saad. Copy and paste the link in web browser. Don't click on the link.

**Comment by roblee357** [comment]
Krishna, neither copying the link or clicking on it worked for me.

**Comment by KrishnaMahi** [comment]
@roblee357 The reason why link doesn't work is, Knime has undergone a overhaul recently. And, so all the links are changed. This is the latest link. 
https://www.knime.com/forum/knime-users/help-for-protocol-buffer-installation-with-anaconda3
Please select the link present above using mouse, copy the link, and paste in your browser.

**Comment by alisidaniel** [comment]
Hi  am having same problem but am not using conda please i need detail to solve this error

**Comment by pherl** [comment]
@alisidaniel you need to unzip the file, rename the protoc-3.x.x-windows-x86_64.exe as protoc.exe, and then put it in some directory in your system PATH.

**Comment by sumedhkumarprasad** [comment]
@KrishnaMahi @TeBoring @podsvirov 


![image](https://user-images.githubusercontent.com/29379271/47548973-3c5d7380-d918-11e8-8550-af7c21aef9e7.png)

Window 10 | Python 3.6 | Anaconda3|protoc 3.4.0 win32

How to resolve the issue. Please help.

**Comment by AR9Rizvi** [comment]
Hi Guys i have the Same issue and this issue do not seems to have been solved i have installed the protobuf separately but it is still not working.
I have windows 10 64bit and i have python 3.6.0 and every other tensor flow dependency installed 
i am new to python and stuck with this for a day and half now please some one who have solved this help...
![protobuf problem](https://user-images.githubusercontent.com/6542943/47766183-3fc57600-dcef-11e8-91da-f2d4fd791187.png)

**Comment by vinitbolla10** [comment]
same issue

**Comment by sajalsuhane** [comment]
Please enter 'conda install protobuf' in CMD in Admin mode. But install Anaconda of latest version if you haven't already.
![image](https://user-images.githubusercontent.com/44001883/53298184-2f15ae80-3850-11e9-8544-4997ad453711.png)

**Comment by SamratSen007** [comment]
Thanks a lot.

Regards
Samrat

**Comment by nirvaanGarg** [comment]
that conda install protobuf was the solution we needed

**Comment by MahmudaEva06** [comment]
hey i've tried it but still it gives th error "object_detection/protos/*.proto: No such file or directory" :(

**Comment by MahmudaEva06** [comment]
![image](https://user-images.githubusercontent.com/38761236/55498971-ab2cbe80-5666-11e9-89d4-fb77ad7dc050.png)

**Comment by stanleywym** [comment]
Wildcard option is not working from Windows Protobuf compiler version 3.5 onwards. Try this command instead
`for /f %G in ('dir /b object_detection\protos\*.proto') do protoc object_detection\protos\%G --python_out=.`

For details, see [https://github.com/protocolbuffers/protobuf/issues/3957](url)

**Comment by merts1** [comment]
conda install -c anaconda protobuf

**Comment by sparshd** [comment]
> Please enter 'conda install protobuf' in CMD in Admin mode. But install Anaconda of latest version if you haven't already.
> ![image](https://user-images.githubusercontent.com/44001883/53298184-2f15ae80-3850-11e9-8544-4997ad453711.png)
Thank you so much sajal, that was really helpful! God bless you! 💯

**Comment by sakshijain032** [comment]
Go to protoc you have installed and then go to bin and then change the path it should be like this
C:\Desktop\tensorflow\models\research\protoc-3.11.4-win64\bin
then run this command
protoc object_detection/protos/*.proto --python_out=.

**Comment by ct50394u** [comment]
@sajalsuhane 
thanks bro that worked

**Comment by isanjaysingh** [comment]
C:\tensorflow\models\research>C:\tensorflow\protoc-3.12.3-win64\bin\protoc object_detection/protos/*.proto --python_out=.

give full path of protoc

**Comment by atesibrahim** [comment]
could you please try as explained here > https://www.geeksforgeeks.org/how-to-install-protocol-buffers-on-windows/

**Comment by chirag858** [comment]
i also have done this @sakshijain032 but still in error
