### ISSUE TITLE
"Google.Protobuf.WellKnownTypes.Timestamp" is not defined

### ISSUE THREAD

**Issue by mayamoon** [google/protobuf#2709]
i use protobuf 3 from nuget for my .net core  csharp  project.
my protoc version is  3.2.0 windows_x64
i copy google/protobuf/*.proto to my project 
and my common.proto file like this:

syntax = "proto3";
option csharp_namespace = "ProtobufStudy.Protocols";
import "google/protobuf/timestamp.proto";
message Message 
{
      int32 request_number = 1;
      int32 id = 2;
    
}

message Packet {
      int64 id = 1;
      Message payload = 3;
	  Google.Protobuf.WellKnownTypes.Timestamp times = 4;
}

message PartnerToken {
    string partnerId = 1;
    string partnerUserId = 2;
    string sessionToken = 3;
}

i can find Timestamp in     "Google.Protobuf": "3.2.0"
but ,wen i compile the source code ,it come up with some error message:

common.proto:10:3: "Google.Protobuf.WellKnownTypes.Timestamp" is not defined.
common.proto: warning: Import google/protobuf/timestamp.proto but not used.

**Comment by jhump** [comment]
@mayamoon, in proto source, to refer to the timestamp, you have to use the package and type as defined in the proto file, not as you would use them in C Sharp source.

In the proto file, the "google/protobuf/timestamp.proto" file declares the package as "google.protobuf" *not* "Google.Protobuf.WellKnownTypes".

So replace your `Packet` message with this:

```proto
message Packet {
   int64 id = 1;
   Message payload = 3;
   google.protobuf.Timestamp times = 4;
}
```
