### ISSUE TITLE
Update/correct docs on FieldDescriptorProto's type_name and extendee

### ISSUE THREAD

**Issue by thomasvl** [google/protobuf#2711]
[FieldDescriptorProto type_name](https://github.com/google/protobuf/blob/7f3e23707122f31ebfa58b7280bd56cbe77cb44e/src/google/protobuf/descriptor.proto#L174-L179) says the name can be fully qualified or partial. [FieldDescriptorProto extendee](https://github.com/google/protobuf/blob/7f3e23707122f31ebfa58b7280bd56cbe77cb44e/src/google/protobuf/descriptor.proto#L181-L183) says the same thing.  But they actually seem to always be complete.  As this the the wire data between `protoc` and a plugin, it they will always be complete, it would seem to be better to document it as such otherwise, a plugin could be broken as they likely don't have a good way to test their support for the partial form.

**Comment by xfxyjwf** [comment]
Depending on where you get the FieldDescriptorProto, type_name is not always fully qualified. For example, a FileDescriptorProto produced by [the Parser class](https://github.com/google/protobuf/blob/master/src/google/protobuf/compiler/parser.h#L72) does not have fully qualified name in the type_name field. Such a FileDescriptorProto is still valid and should be accepted by a DescriptorPool.

Though in the specific protoc + plugin case, it's safe to assume FileDescriptorProto sent by protoc to the plugins always contain fully-qualified names. I guess we can add additional comments in descriptor.proto to make that a documented behavior.

**Comment by pherl** [comment]
I added some comments in the plugin.proto instead internally. Closing this for now.
