### ISSUE TITLE
Problem with protoc 3.2.0 --ruby_out import paths

### ISSUE THREAD

**Issue by CromonMS** [google/protobuf#2716]
Referencing this repo here: https://github.com/CromonMS/mscmgmt_protobuf_releases

When using imports in proto files in https://github.com/CromonMS/mscmgmt_protobuf_releases/blob/master/lib/protos/release.proto
I use the full path to the imported file, otherwise protoc fails to build the ruby file with 'artist.proto missing or broken'.

However when using the ruby files here: https://github.com/CromonMS/mscmgmt_protobuf_releases/blob/master/lib/protos/release_pb.rb
It generates the require statement with the full path, which fails, and I have to change it to require_relative before building the gem for it to work.

Sorry if it's a bit hard to understand I was trying to work out how to word it.

**Comment by TeBoring** [comment]
To add include path: protoc --ruby_out=. -Ilib/protos release.proto
