### ISSUE TITLE
errors show when do the command'make'

### ISSUE THREAD

**Issue by IvyGongoogle** [google/protobuf#2720]
Hello, when I do the command 'make', it shows error
`google/protobuf/compiler/command_line_interface.cc:1041:` error: 'class std::vector<google::protobuf::compiler::CommandLineInterface::OutputDirective, std::allocator<google::protobuf::compiler::CommandLineInterface::OutputDirective> >' has no member named 'cbegin'
google/protobuf/compiler/command_line_interface.cc:1042: error: 'class std::vector<google::protobuf::compiler::CommandLineInterface::OutputDirective, std::allocator<google::protobuf::compiler::CommandLineInterface::OutputDirective> >' has no member named 'cend'
make[2]: *** [google/protobuf/compiler/command_line_interface.lo] Error 1
make[2]: Leaving directory `/media/jfu/ztgong/protobuf/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/media/jfu/ztgong/protobuf'
make: *** [all] Error 2`

how to solve this problem?

**Comment by acozzette** [comment]
I think the issue here is that we ordinarily don't require C++11, but these `cbegin` and `cend` methods are new in C++11 and they managed to slip in to the codebase. I'll send out a change to remove these so that the code can still build without C++11.

**Comment by acozzette** [comment]
@IvyGongoogle Actually it looks like this was just fixed yesterday in ffde972ac705e. I'll close this issue then but feel free to reopen it if for any reason you still see errors.

**Comment by IvyGongoogle** [comment]
@acozzette Thankyou very much.  I used 2.5 version. I will  again trouble you when I have a problem later.
