### ISSUE TITLE
javascript feature request: generate exports.js for generated code

### ISSUE THREAD

**Issue by AndrewGuenther** [google/protobuf#2726]
Right now, if I were to compile the output of `protoc` with `ADVANCED` compilation all of my code is removed by dead-code-removal. That makes sense. But what I would really like to do is ensure all of the functions are exported so that I can distribute the compiled version as a NodeJS module. Right now, there doesn't seem to be a non-hacky way to do this.

What I have now is essentially a shell script that finds all type prototype declarations, and generates an `index.js` file as a pre-build step. This `index.js` puts all functions in the global namespace by using strings and ensures that none of it gets compiled out. While this *technically* works, it is fragile and much less than ideal. Does a better way exist? And if not, could one be implemented?

Sample of the script:
```bash
#!/bin/bash

grep -re "^goog\.provide" $proto_js | \
   sed -re "s/goog.provide\('([\.a-zA-Z]+)'\);/goog.require('\1'); module['exports']['\1'] = \1;/g"

grep -re "^$proto_namespace\.[a-zA-Z\.]\+\.prototype\.[a-zA-Z0-9_]\+" $proto_js | \
   sed -re "s/^($proto_namespace\.[a-zA-Z\.]+)\.prototype\.([a-zA-Z0-9_]+) =.*/module['exports']['\1'].prototype['\2'] = \1.prototype.\2;/g"
```

Sample output:
```javascript
goog.require('proto.my_proto.MyEvent'); module['exports']['MyEvent'] = proto.my_proto.MyEvent;
module['exports']['MyEvent'].prototype['serializeBinary'] = proto.my_proto.MyEvent.prototype.serializeBinary;
module['exports']['MyEvent'].prototype['serializeBinaryToWriter'] = proto.my_proto.MyEvent.prototype.serializeBinaryToWriter;
module['exports']['MyEvent'].prototype['getType'] = proto.my_proto.MyEvent.prototype.getType;
module['exports']['MyEvent'].prototype['setType'] = proto.my_proto.MyEvent.prototype.setType;
module['exports']['MyEvent'].prototype['hasType'] = proto.my_proto.MyEvent.prototype.hasType
```

**Comment by acozzette** [comment]
At the moment I'm not sure of a better way to do it than the way you're currently doing it. Perhaps we could eventually do something fancy where we could have a `protoc` plugin that would take in the `.proto` file and spit out a `.js` file with all the necessary exports. It might also be worth asking on the Closure compiler [mailing list](https://groups.google.com/forum/#!forum/closure-compiler-discuss) if anyone there has any ideas on the best way to do this.

**Comment by haberman** [comment]
This seems totally doable but probably not something that would be a priority for us. We might be able to accept a contribution for this. It could just be another code generator for generating `exports.js` that is kept in sync with the main code generator. We'd want a test that verifies that this works when compiling with Closure.

**Comment by AndrewGuenther** [comment]
Alright, I'll go ahead and leave this open, but we ended up switching to a different Javascript Protobuf implementation that works out of the box so we probably won't be pushing a contribution from our end.

**Comment by haberman** [comment]
In that case I might just close the bug. Out of curiosity, what implementation did you switch to and does it support generating an `exports.js`?

**Comment by AndrewGuenther** [comment]
We went with Protobuf.js: https://github.com/dcodeIO/protobuf.js

It doesn't create an exports.js, it just generates CommonJS code out of the box, so it is much easier to work with when using other tools. We also found that it was 4-5x faster and produced a 75% smaller JS file with only minor configuration.
