### ISSUE TITLE
Add option to watch files for changes and recompile

### ISSUE THREAD

**Issue by steelbrain** [google/protobuf#2731]
This should make the development easier. `protoc` should have an option (like `--watch`) where it initially compiles all the definitions and then watches them for changes and recompiles them as soon as any changes.

I've searched through open issues and could not find a similar one, my apologies if this is a duplicate

**Comment by acozzette** [comment]
I think this functionality might make more sense to implement outside of `protoc`. Actually it's fairly straightforward to get something working just using existing tools on the command-line; for example on Linux you can do something like this using inotify to watch for changes:

    while true; do
      # Wait for a .proto file to change
      inotifywait -e modify,move_self $(find . -type f -name '*.proto')
      # Run protoc...
    done

**Comment by steelbrain** [comment]
@acozzette while I appreciate the team trying to keep the project focused and minimal, the solution you posted is not the ideal way to go IMHO

The reason I don't like doing a inotifywait or anything similar is because it's heavily platform dependent and the code it requires cannot be reused for something else. For example, babel, typescript, coffee-script and all the other file transformers or compilers I've worked with (not project compilers, individual file compilers like protobuf) support file watching out of the box

**Comment by xfxyjwf** [comment]
This is more of a build system feature rather than protobuf one. Implementing it is out-of-scope of this project.
