### ISSUE TITLE
C++ Json - option to always print enums as ints

### ISSUE THREAD

**Issue by na-ka-na** [google/protobuf#2735]
We use a lot of enums. So we'd like an option to always print enums as ints. It will significantly reduce the size of our generated json. I already have changes to do so, will send out a PR.

**Comment by na-ka-na** [comment]
Here's the PR: https://github.com/google/protobuf/pull/2736

**Comment by na-ka-na** [comment]
Thank you for merging! Do I need to update the documentation too?

**Comment by xfxyjwf** [comment]
@na-ka-na No, there isn't a dedicated developer guide page for C++ JSON API at the moment.
