### ISSUE TITLE
[Python] TypeError: Couldn't build proto file into descriptor pool!

### ISSUE THREAD

**Issue by rossengeorgiev** [google/protobuf#2739]
I have two proto files `a.proto` and `b.proto`. They are identical, except their name. In reality, I have two files that happen to define a message with the same name.

`a.proto`
```proto
syntax = "proto2";

message Message1 {
}
```

`b.proto`
```proto
syntax = "proto2";

message Message1 {
}
```

When I try to import both files `python -c "import a_pb2, b_pb2"` I get:

```python
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/root/test/b_pb2.py", line 21, in <module>
    serialized_pb=_b('\n\x07\x62.proto\"\x18\n\x08Message1\x12\x0c\n\x04var2\x18\x01 \x01(\t')
  File "/root/test/env3/lib/python3.5/site-packages/google/protobuf/descriptor.py", line 824, in __new__
    return _message.default_pool.AddSerializedFile(serialized_pb)
TypeError: Couldn't build proto file into descriptor pool!
Invalid proto descriptor for file "b.proto":
  Message1: "Message1" is already defined in file "a.proto".
```

Only happens with `protobuf==3.2.0`.

**Comment by rossengeorgiev** [comment]
Looking at #53 this seems to be intended, and possibly a result of the refactoring in `3.2.0`

**Comment by TeBoring** [comment]
You should not define two messages with the same name. If you use pip to
install protobuf, you used sdist before. For 3.2.0, we have switched to
bdist, which uses cpp implementation. The python implementation didn't
report duplicated name, but the cpp implementation does.
You can add package to your proto files. Or avoid bdist when you do pip
install.

**Comment by rossengeorgiev** [comment]
Oh I see. Yes, the issue only appears when protobuf is installed from the new wheels.
