### ISSUE TITLE
Allow to pass protoc command line arguments via a file or stdin

### ISSUE THREAD

**Issue by sergei-ivanov** [google/protobuf#274]
This has been a recurring source of pain on Windows for ages: in large projects with lots of `.proto` definitions or lots of `.proto` imports it is pretty easy to reach the command line length limit on Windows, which is ridiculously small. We've developed a number of workarounds for this problem in the Maven plugin, but there are still reports that some projects are struggling.
A simple solution that would have allowed us to solve that issue once and forever would be to pass a file with the actual command line arguments on the command line, or alternatively pipe them in.

**Comment by xfxyjwf** [comment]
If you have a lot of .proto files, you don't have to invoke protoc on all of them in a single pass. Instead, you can invoke protoc once for each of them.

**Comment by sergei-ivanov** [comment]
I know, it is one of the workarounds that we either considered or already implemented. It may be less efficient, but it gets things done. I think the latest problem that one of the clients ran into was related to a large number of import paths (`-I=xxxxxx`), which busts the command line limit. Again, I think we can work around it in some creative way, but it would be much easier if we could run something like `protoc @args.tmp` where `args.tmp` would be a text file containing a newline-separated list of command line arguments.

**Comment by xfxyjwf** [comment]
We actually have this feature internally already.

**Comment by sergei-ivanov** [comment]
This is amazingly good news. I shall add support to the Maven plugin as soon as it is publicly available in protoc.

**Comment by pherl** [comment]
I believe this is already implemented.

**Comment by sergei-ivanov** [comment]
I've just tested it with protoc 3.5.0, and it appears to work beautifully. Is 3.5.0 the earliest version where this feature has become publicly available?
Many thanks for implementing this.

**Comment by xfxyjwf** [comment]
@sergei-ivanov Yes, 3.5.0 is the first version with this feature.
