### ISSUE TITLE
PHP Empty

### ISSUE THREAD

**Issue by tbillington** [google/protobuf#2740]
I don't know whether this is a grpc error or proto, I posted it initially in grpc but I'll cross post it here too.

Basically, `Empty` is generated to `GPBEmpty` properly in the metadata and for the service clients, but not for the actual class definition.

https://github.com/grpc/grpc/issues/9796

This is probably related to https://github.com/google/protobuf/commit/99564c3347223b92e49bd40f37b8c0d6fc6a3971 ?

**Comment by TeBoring** [comment]
Is it possible for you to rename Empty?

**Comment by tbillington** [comment]
Just seems weird to go through the effort of rewriting to `GPBEmpty` for the metadata but not doing it for the actual definition. It's like the use case has been thought of but the implementation only half works?

**Comment by TeBoring** [comment]
I want to add PB by default as prefix for reserved words. But I don't have time to do that. Could you help send a fix? Thanks!
