### ISSUE TITLE
CMake FindProtobuf finds protobuf but not protobuf_include_dir

### ISSUE THREAD

**Issue by mmende** [google/protobuf#2750]
Hi,

I am trying to compile a C/C++ project for windows that uses protobuf (grpc). The project works well with unix but I am struggling with the windows compilation. I added a third_party directory to the project where I've installed grpc together with protobuf. The protobuf installation directory (bin/lib/include) is in grpc/third_party/install. To add this custom protobuf build to the cmake file of the project I manually set the locations for all the protobuf stuff like this:

```cmake
set(PB_INSTALLATION "${CMAKE_SOURCE_DIR}/third_party/grpc/third_party/install")

set(PROTOBUF_LIBRARY "${PB_INSTALLATION}/lib/libprotobuf.lib")
set(PROTOBUF_PROTOC_LIBRARY "${PB_INSTALLATION}/lib/libprotoc.lib")
set(PROTOBUF_INCLUDE_DIR "${PB_INSTALLATION}/include")
set(PROTOBUF_PROTOC_EXECUTABLE "${PB_INSTALLATION}/bin/protoc.exe")
set(PROTOBUF_LITE_LIBRARY "${PB_INSTALLATION}/lib/libprotobuf-lite.lib") 
```

When trying to create the visual studio stuff with cmake generators it finds protobuf but seems to completely ignore the `PROTOBUF_INCLUDE_DIR`:

```
-- Found Protobuf: C:/Users/martinmende/Documents/development/tts-nativeclient/src/c_cpp/third_party/grpc/third_party/install/lib/libprotobuf.lib (found version "3.1.0")
CMake Error at C:/Program Files/CMake/share/cmake-3.7/Modules/FindPackageHandleStandardArgs.cmake:138 (message):
  Could NOT find Protobuf (missing: Protobuf_INCLUDE_DIR)
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.7/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  C:/Program Files/CMake/share/cmake-3.7/Modules/FindProtobuf.cmake:389 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  src/CMakeLists.txt:2 (find_package)
```

Is there something wrong with the FindProtobuf.cmake module or am I doing something completely stupid here?
Kind regards

**Comment by acozzette** [comment]
It might not hurt to ask the CMake developers about that module. As far as I know the protobuf team hasn't actually been involved in creating FindProtobuf.cmake and so I don't really know anything about how it works. It could be that you're using it right but that there's a bug in it somewhere.

**Comment by pherl** [comment]
We are closing open issues. Feel free to send PRs and reopen if you'd like to follow up on the issue.

**Comment by ZachClayburn** [comment]
I had this issue, and I was able to fix is by adding `include(FindProtobuf)` before `find_package(protobuf REQUIRED)`. I'm not sure if I just don't understand the find_package function, but it seems a little strange to me.
