### ISSUE TITLE
Pylint and installation from PyPi

### ISSUE THREAD

**Issue by pcorpet** [google/protobuf#2752]
I tried using the python module with pip `pip install protobuf`.

This works, however pylint is complaining that it cannot find a submodule:
```
E: 20, 0: No name 'json_format' in module 'google.protobuf' (no-name-in-module)
```

After poking around to see the differences with the manual install, it seems that there are no `__init__.py` in the `/usr/local/lib/python3.5/site-packages/google/` folder when installing with pip which makes the subfolders invisible to pylint.

Would it be possible to add this file please?

**Comment by xfxyjwf** [comment]
So you have installed other google python packages along with protobuf? I remember there were lots of discussions about how to solve this problem but I don't know if we have a good answer for it. @haberman

**Comment by pcorpet** [comment]
No I have not installed any other google python package. Is there a small google package that you would recommend adding there? (Note that the protobuf package works fine, only pylint complains about it).

**Comment by haberman** [comment]
I asked a local Python expert about this and this was the answer:

>I think they just have a really old version of pylint. :)
>
>setuptools and pip intentionally don't install __init__.py files for namespace packages, instead, it creates a magical nspth.pkg entry in site-packages that tells the interpreter where the search path is.

So it sounds like the current behavior is correct. I'm closing this for now, but please re-open if you have other information that contradicts this.

**Comment by pcorpet** [comment]
For closure (sorry for the latency), it indeed now works properly. I'm not sure what went wrong last year. Sorry about the noise.
