### ISSUE TITLE
protobuf 3.2.0 gcc build error under Solaris 11.2 SPARC and X86

### ISSUE THREAD

**Issue by onlyforwowgame** [google/protobuf#2756]
compiler:  gcc 4.8.2
   
   Followed the installation steps based on the document,  it threw error with std::isinf "was not declared in this scope". I tried to pass CXXFLAGS="-std=c++98", then it threw error "‘va_copy’ was not declared in this scope". 
    
   I had doubted bug of gcc for c++11 standard supporting. And I found similar issue on https://github.com/nodejs/node/issues/3179, that guys used "-D_GLIBCXX_USE_C99_MATH" to fix this issue.

   so after set to ./configure CXXFLAGS="-D_GLIBCXX_USE_C99_MATH", the building was successful without error.

**Comment by TeBoring** [comment]
Do you have a dockerfile to re-produce the error?

**Comment by pherl** [comment]
We are closing open issues. Feel free to send PRs and reopen if you'd like to follow up on the issue.
