### ISSUE TITLE
Protobuf fails to build on freebsd

### ISSUE THREAD

**Issue by cgrushko** [google/protobuf#2757]
We found out when I tried to upgrade Bazel's protobuf version, and CI broke [1]

It appears that a patch exists:
https://svnweb.freebsd.org/ports/head/devel/protobuf/files/

Can it be merged into protobuf?

[1] -http://ci.bazel.io/view/Bazel%20bootstrap%20and%20maintenance/job/Bazel/JAVA_VERSION=1.8,PLATFORM_NAME=freebsd-11/1312/console

**Comment by cgrushko** [comment]
@xfxyjwf

**Comment by cgrushko** [comment]
Looks like the root cause is that plugin.pb.h defines a new field, `major`, which conflicts with a macro that FreeBSD defines. 

Is it feasible to rename the field?

**Comment by xfxyjwf** [comment]
Let's just undef the macro. Could you help send a pull request?

**Comment by cgrushko** [comment]
I prefer not to :) My git-fu is weak, especially with GitHub.

There are also other changes in that diff which I didn't notice initially, such as using different includes.

**Comment by xfxyjwf** [comment]
@cgrushko  I don't have access to a FreeBSD machine. Do you know if anyone from bazel team can help here?

**Comment by cgrushko** [comment]
@damienmg how does one get a freebsd machine?

**Comment by damienmg** [comment]
We just created a VM on GCE.

**Comment by xfxyjwf** [comment]
I have a pull request out: https://github.com/google/protobuf/pull/2775

It fixes the major/minor macro issue for a different environment. Could someone help test it with bazel freebsd machine?

**Comment by damienmg** [comment]
jenkins test this please

**Comment by damienmg** [comment]
humm sorry

**Comment by damienmg** [comment]
Unfortunately this does not work yet, I think our CI needs a bit more work to be able to test FreeBSD. /cc @aehlig can probably help there.

**Comment by xfxyjwf** [comment]
Just sent out another PR: https://github.com/google/protobuf/pull/2848

Tested on a bazel freebsd machine :)
