### ISSUE TITLE
what does it mean that Installation from composer 

### ISSUE THREAD

**Issue by algorithmlover2016** [google/protobuf#2759]
Installation from composer

Simply add "google/protobuf" to the 'require' section of composer.json in your project.
php version is 7.1 and when installing with c extension, zend_object_value unknown.
but I don't know what's the meaning of add "google/protobuf" to the 'require' section. Please help

**Comment by lukaszwit** [comment]
In PHP composer is dependency management tool. This instructions ask you to add requirement in composer.json file of your project.
This should help you: [https://getcomposer.org/doc/01-basic-usage.md#the-require-key](https://getcomposer.org/doc/01-basic-usage.md#the-require-key).

Assuming that you already have composer.json file and composer installed globally you can use this command:
```
composer require google/protobuf
```
It should ad requirement info your json file and download with all dependencies.

**Comment by algorithmlover2016** [comment]
{                                                                                                   
    "require": {
        "protobuf-php/protobuf": "^0.1.3",
        "google/protobuf": "^3.2"
    }   
}

**Comment by algorithmlover2016** [comment]
yes, you are right. thank you very much.
I have a question about the protobuf installing in php. I execute the command that `composer require "google/protobuf`, but I still can not test the examples in the sub-folder. 
Have you ever make it true that php 7.1.* installing the extension of protobuf? I can't make it.
   Installation from composer
   Simply add "google/protobuf" to the 'require' section of composer.json in your project.
this means wherever I create a project, and I need composer require google/protobuf(which will download all the source files whose name is vendor in the project)?

**Comment by algorithmlover2016** [comment]
how to install protobuf in php, can you tell me in details (step by step)? @TeBoring . no matter, thank you very much! I have tried the c extension is not valid in php 7.*. Now I have to use the PHP package method, but I  doesn't understand what you mean

**Comment by TeBoring** [comment]
@algorithmlover2016 Could you show me the composer.json file you have now?
The c extension doesn't work on php 7. If you have to use php 7, you can only use the PHP package.

**Comment by algorithmlover2016** [comment]
first, I make a new dir and name it protobuf_example. Second, I run the command `composer require  google/protobuf`, and then I run the command `composer install`. After the second step, there will be a folder named vendor whose structure is 
![image](https://cloud.githubusercontent.com/assets/17782711/23385765/1202ebf0-fd8d-11e6-931f-1fa696c21b41.png) and the composer.json's content is 
![image](https://cloud.githubusercontent.com/assets/17782711/23385776/2691cad2-fd8d-11e6-8bad-5457372c717d.png).  
Third, I define the foo.proto file, and then run the command `protoc --php_out=./ ./foo.proto` which will create a php file. But When I run the test script, there is a error which is like this:
![image](https://cloud.githubusercontent.com/assets/17782711/23385841/8dbe1300-fd8d-11e6-8fc8-f1a5658613f9.png), I think it's caused by the sentence 
![image](https://cloud.githubusercontent.com/assets/17782711/23385853/a95ff60a-fd8d-11e6-8ed6-707cd85d1642.png).
I have tried a long time, but I can't make it. Please help, thank you vary  much @TeBoring

**Comment by TeBoring** [comment]
What's your test code? Do you also use phpunit?

**Comment by TeBoring** [comment]
Close this for cleanup. Feel free to reopen the issue if there is still problem.
