### ISSUE TITLE
Please merge the javalite and master branches

### ISSUE THREAD

**Issue by cgrushko** [google/protobuf#2760]
... it's duplicate work maintaining both BUILD files to work with Bazel.

**Comment by cgrushko** [comment]
@xfxyjwf

**Comment by xfxyjwf** [comment]
It can't be merged because the code is different. We can remove as much as possible from the javalite branch if needed.

**Comment by pherl** [comment]
Java lite branch should only be updated when we cut a release. Is there anything you'd like to include in that branch? Or are you trying to have a single project tree including both lite and full? The later probably doesn't work because they conflict with each other.

**Comment by cgrushko** [comment]
As I mentioned in the OP, the problem for me is BUILD files that need to be updated in both branches. I already ran into this.
I assume BUILD files can't be the only thing that needs to be kept in sync. (but I particularly care about BUILD and protobuf.bzl)

Also, I think having production code in a branch makes it hard to find and use. If it's completely different, perhaps move it a separate repo?
