### ISSUE TITLE
Add a proto_library rule for well-known types and update the proto_lang_toolchain rules

### ISSUE THREAD

**Issue by cgrushko** [google/protobuf#2763]
Bazel now has built-in rules for building Java and C++ protos (`proto_libarry`, `java_proto_library`, `java_lite_proto_library` and `cc_proto_library`).

For users to import well-known types (e.g., `descriptor.proto`) from their `.proto` files, they must depend on a `proto_library` that `srcs` the former.

This FR is about adding such a `proto_library`.

https://github.com/google/protobuf/issues/2598 is a blocker.

**Comment by kamalmarhubi** [comment]
@xfxyjwf do you know if you'll get to this in the near term?

**Comment by cgrushko** [comment]
https://github.com/bazelbuild/bazel/issues/2265 is a blocker.

**Comment by kamalmarhubi** [comment]
@cgrushko ah, I kept running into that error and didn't realize it was a bug in bazel.

**Comment by buchgr** [comment]
https://github.com/bazelbuild/bazel/issues/2265 has been fixed and should be part of the next bazel release.

**Comment by thaidn** [comment]
So is this issue fixed? If so, can I build bazel from HEAD and depend on well-known protos in my proto_library rules?

**Comment by buchgr** [comment]
hey @thaidn 

https://github.com/bazelbuild/bazel/issues/2265 has been fixed and reverted again, because it caused trouble inside of google's programming environment. See the bug for details.

It's really embarrassing and I apologize for the trouble's this causes. 

Inside bazel we also need well known types and thus made a simple hack that copies the well known types from `src/com/google/protobuf` to `com/google/protobuf` and then it works. Here is the patch that does that: https://bazel-review.googlesource.com/c/10690/

**Comment by xfxyjwf** [comment]
@buchgr Is a proper fix of this issue depending on b/37798101 (making both internal and external protoc accepts the same file path)?

**Comment by cgrushko** [comment]
Yes, it does. Adding proto_library requires compiling generated files
(because the request to move the well known types one level up the tree was
rejected).
In order to compile generated files we need to pass bazel-bin/ paths, which
require b/37798101.
We can workaround this in a number of ways, not all of which are easy.

**Comment by junghoahnsc** [comment]
Is there any workaround to import well-known protos for now?

**Comment by buchgr** [comment]
@junghoahnsc 
You can do what I described in my previous comment that bazel does.

**Comment by junghoahnsc** [comment]
@buchgr you mean using a patch https://bazel-review.googlesource.com/c/10690 ?

Would it be a workaround to have all well-known protos in local repo with BUILD?

**Comment by buchgr** [comment]
@junghoahnsc yes to both :-).

**Comment by kamalmarhubi** [comment]
I have an example repo defining an extra `com_google_protobuf_well_known_protos` repository: https://github.com/kamalmarhubi/bazel-well-known-protos-example

**Comment by buchgr** [comment]
@kamalmarhubi smart to use strip-prefix :-). Anyways, the fix is in bazel upstream again and will be part of the 0.5.4 release.

**Comment by perezd** [comment]
So, once 0.5.4 is available, what should we do to make use of this? Will it start to just work automatically?

**Comment by buchgr** [comment]
Someone needs to add proto_library rules to protobuf's BUILD file :-). I can do that next week.

**Comment by aj-michael** [comment]
Now that bazel 0.5.4 is released, can someone please fix this 😄

**Comment by buchgr** [comment]
I am working on a change.

**Comment by buchgr** [comment]
Thanks @xfxyjwf !
