### ISSUE TITLE
more info about original file in protoc plugin

### ISSUE THREAD

**Issue by konsumer** [google/protobuf#2764]
I am writing a little framework to make building protoc plugins in nodejs easier.

I've got the parsing complete (using `CodeGeneratorRequest` to read stdin and outputting `CodeGeneratorResponse` on stdout to tell protoc how files should be modified.

The first issue I ran into was that the grpc annotations were left out of all of the `CodeGeneratorRequest` object I received. If it were a string or object (maybe in the currently empty `options` field of the rpc) I could parse it directly. I double-checked with the python `CodeGeneratorRequest` to make sure it wasn't issue with protobuffjs's generated `CodeGeneratorRequest` and this info does appear to be missing there, too.

My first thought was "ok, I can use protobufjs to parse it, I just need the full path" since `file_to_generate` doesn't have this, and I can't seem to get the original `-I` path from `process.argv` (it gives me only path to node and the script I am running) I am not sure how to proceed.

Any of these things that would solve this issue for me, in order of my own preference:

1. If `options` in `CodeGeneratorRequest` included the options for the RPC, I wouldn't need to parse anything. Is it meant to be in there? I notice there is an empty object `options` in the rpc method definitions
2. If the string inside the rpc definition were available, I could parse it myself, and pull out the annotations
3. If the full disk path of `CodeGeneratorRequest.file_to_generate` were available, I could use another library to parse the proto file and extract the other info.
4. if the import paths (or just complete protoc CLI options) were available in `CodeGeneratorRequest` or `proccess.argv`, I could reassemble the virtual path resolution of `file_to_generate` and parse it with another library.

I'd be happy to work on any of these, if it's a PR this project is interested in accepting.

For reference, here is the proto I am using to test:

```proto
syntax = "proto3";
package helloworld;

import "google/api/annotations.proto";

// The greeting service definition.
service Greeter {
  // Sends a greeting
  rpc sayHello (GreeterRequest) returns (GreeterReply) {
    option (google.api.http) = {
      post: "/v1/hi"
      body: "*"
    };
  }

  // Sends a farewell
  rpc sayGoodbye (GreeterRequest) returns (GreeterReply) {
    option (google.api.http) = {
      post: "/v1/bye"
      body: "*"
    };
  }
}

// The request message containing the user's name.
message GreeterRequest {
  string name = 1;
}

// The response message containing the greetings
message GreeterReply {
  string message = 1;
}
```

I made a simple JSON logger protoc plugin:

```js
// this is just wrapped versions of protobuffjs CodeGeneratorRequest, CodeGeneratorResponse
const { CodeGeneratorRequest, CodeGeneratorResponse } = require('../src/index.js')

process.stdin.on('data', data => {
  process.stdout.write(CodeGeneratorResponse({
    file: [
      {
        name: 'parse_log.js',
        content: JSON.stringify(CodeGeneratorRequest(data), null, 2)
      }
    ]
  }))
})
```

This works great to figure out what protoc is giving me in `CodeGeneratorRequest`, which is 
[here](https://github.com/google/protobuf/files/804652/parse_log.js.zip).

**Comment by konsumer** [comment]
Just so you don;t have to read through the whole output of the log, here is the relevant rpc bit for `helloworld.Greeter.sayHello`:

```json
"service": [
        {
          "name": "Greeter",
          "method": [
            {
              "name": "sayHello",
              "input_type": ".helloworld.GreeterRequest",
              "output_type": ".helloworld.GreeterReply",
              "options": {}
            },
            {
              "name": "sayGoodbye",
              "input_type": ".helloworld.GreeterRequest",
              "output_type": ".helloworld.GreeterReply",
              "options": {}
            }
          ]
        }
      ]
```

**Comment by xfxyjwf** [comment]
@konsumer The CodeGeneratorRequest you get from protoc actually have the options. However, it may be unretrievable if you write your plugin using a language without proto2 support.

You can verify the options data following these steps:
  * First dump the original binary data you get from protoc. Don't parse it because parsing the data into a proto message will cause the options to be discarded right away and that's why your dumped JSON doesn't appear to have any options.
  * In a protobuf source tree, use the following command to convert the dumped data to a readable text format:
    ```bash
    cat [dumped data file] | protoc --decode google.protobuf.compiler.CodeGeneratorRequest -I. -Ipath/to/googleapis google/protobuf/compiler/plugin.proto [path to your own .proto file]
    ````

The resulted text output should have everything in the CodeGeneratorRequest. In your particular case, it should have a section like this:
```
  service {
    name: "Greeter"
    method {
      name: "sayHello"
      input_type: ".helloworld.GreeterRequest"
      output_type: ".helloworld.GreeterReply"
      options {
        [google.api.http] {
          post: "/v1/hi"
          body: "*"
        }
      }
    }
    method {
      name: "sayGoodbye"
      input_type: ".helloworld.GreeterRequest"
      output_type: ".helloworld.GreeterReply"
      options {
        [google.api.http] {
          post: "/v1/bye"
          body: "*"
        }
      }
    }
  }
```

The options data are represented using proto2 extensions, so if you are using a language without proto2 support, parsing the data into a proto message will render the options data unaccessible (they will be discarded as unknown fields). To preserve these options data, we will have to add additional APIs to keep and expose these options data. I remember there was some discussions around it but at the moment it hasn't be implemented in most proto3-only languages. @acozzette @haberman may know more about the current status of custom options support in Javascript.

There is also a planned proto3 change that introduces unknown fields back (i.e., unknown options data will no longer be discarded in proto3) and with that you should be able to access options data without adding other option specific APIs. It will take some time for this change to land though.

**Comment by konsumer** [comment]
That is a cool trick for debugging, but I'm not sure how to use it in crafting plugins for protoc. I have the annotation proto-files in my path when I parse it (google/ dir is at same level as helloworld.proto) so shouldn't it pass it along to stdin of my script? Is there a different `CodeGeneratorRequest` parser I should be using, other than the one generated by protoc (using `--js_out`) or the one generated by protobuffjs (via `pbjs`)?

This sheds some light on the possible reasons behind protobufjs making their own CLI tool (`pbjs`) , rather than a plugin for protoc. I was wondering about that.

**Comment by acozzette** [comment]
@xfxyjwf Actually we have support for proto2 and extensions for Javascript, so this should work.

@konsumer You should be able to access those custom options as extensions; here's an example of the extension syntax: https://github.com/google/protobuf/blob/40f3586412c2efa7a81ccb685e6f96e817996e36/js/binary/proto_test.js#L287
Note that those annotation options are just defined as an extension of `google.protobuf.MethodOptions`: https://github.com/googleapis/googleapis/blob/6ae2d424245deeb34cf73c4f7aba31f1079bcc40/google/api/annotations.proto#L28

**Comment by konsumer** [comment]
@acozzette thanks. I'm still not sure how to actually use the the generated lib for `CodeGeneratorRequest` to get the value of the incoming message. If I pipe an output from above trick (unparsed binary output from the helloworld.proto) I get this, which is even more limited:

```js
{
  "fileToGenerateList": 10,
  "parameter": 16,
  "protoFileList": [],
  "compilerVersion": {}
}
```

Do I need to do something other than ` (new pb.CodeGeneratorRequest(binaryMsg)).toObject()`?

`pb` is the output from `protoc -I proto/ proto/google/protobuf/compiler/plugin.proto --js_out=import_style=commonjs,binary:src/`

**Comment by acozzette** [comment]
@konsumer I think the problem is that the constructor takes a data array which is just the internal representation of the message and an implementation detail. To actually parse the raw binary you have to use `CodeGeneratorRequest.deserializeBinary()`. The other thing is that I wouldn't really recommend using `toObject()`; the `toObject` and `fromObject` methods are a sort of legacy feature that we wish we could remove; they are confusing because their output is pretty similar to proto3 JSON but not actually the same. It's better if you can just use the `CodeGeneratorRequest` directly.

**Comment by konsumer** [comment]
@acozzette I appreciate the help, but I think I'm still not getting it. The tests don't seem to clearly demonstrate "turn this binary buffer into a js object" and "turn this js object into binary buffer" and the README says "For more examples, see the tests.", but maybe I am misunderstanding or missed something.

For illustration, here is my current code (using highland and tou8 to make it go faster and be more readable)

```js
const _ = require('highland')
const tou8 = require('buffer-to-uint8array')
const pb = require('./google/protobuf/compiler/plugin_pb')

_(process.stdin)
  .reduce1((a, b) => Buffer.concat([a, b])) // mash all incoming together to avoid partial messages
  .map((req) => tou8(pb.CodeGeneratorRequest.deserializeBinary(req))
  // here I would do processing and conversion back into CodeGeneratorResponse
  // below is just for outputting
  .map((res) => JSON.stringify(res, null, 2))
  .pipe(process.stdout)
```

I added tou8, because I got this error: `AssertionError: Failure: Type not convertible to Uint8Array.` but I still get the error with it.

Here is the full error with tou8:

```
events.js:160
      throw er; // Unhandled 'error' event
      ^
AssertionError: Failure: Type not convertible to Uint8Array.
    at new goog.asserts.AssertionError (/Users/konsumer/Projects/node-protoc-plugin/node_modules/google-protobuf/google-protobuf.js:98:603)
    at Object.goog.asserts.fail (/Users/konsumer/Projects/node-protoc-plugin/node_modules/google-protobuf/google-protobuf.js:100:89)
    at Object.jspb.utils.byteSourceToUint8Array (/Users/konsumer/Projects/node-protoc-plugin/node_modules/google-protobuf/google-protobuf.js:247:257)
    at jspb.BinaryDecoder.setBlock (/Users/konsumer/Projects/node-protoc-plugin/node_modules/google-protobuf/google-protobuf.js:252:264)
    at new jspb.BinaryDecoder (/Users/konsumer/Projects/node-protoc-plugin/node_modules/google-protobuf/google-protobuf.js:250:486)
    at Function.jspb.BinaryDecoder.alloc (/Users/konsumer/Projects/node-protoc-plugin/node_modules/google-protobuf/google-protobuf.js:251:207)
    at new jspb.BinaryReader (/Users/konsumer/Projects/node-protoc-plugin/node_modules/google-protobuf/google-protobuf.js:270:433)
    at Function.proto.google.protobuf.compiler.CodeGeneratorRequest.deserializeBinary (/Users/konsumer/Projects/node-protoc-plugin/src/google/protobuf/compiler/plugin_pb.js:368:16)
    at _.reduce1.map (/Users/konsumer/Projects/node-protoc-plugin/src/index.js:291:46)
    at /Users/konsumer/Projects/node-protoc-plugin/node_modules/highland/lib/index.js:2008:25
```

**Comment by konsumer** [comment]
As a sidenote, I'd be happy to make a PR for the docs once I understand how to actually use the generated code. 😃

**Comment by konsumer** [comment]
Oh, duh, I had the `Uint8Array` conversion in the wrong place. So this totally works, but still doesn;t get the options:

```js
_(process.stdin)
  .reduce1((a, b) => Buffer.concat([a, b]))
  .map((req) => pb.CodeGeneratorRequest.deserializeBinary(tou8(req)))
  .map((res) => JSON.stringify(res, null, 2))
  .pipe(process.stdout)
```

[Attached](https://github.com/google/protobuf/files/812053/log.json.zip) is the json output.

**Comment by acozzette** [comment]
@konsumer Is there any particular reason you're trying to convert the request into a JSON form? I think the problem is probably that `toObject()` does not output data for extensions and the output of `JSON.stringify()` just shows you the internal representation, which isn't very useful. The easiest way would probably be to just work with the `CodeGeneratorRequest` directly, without trying to convert it to JSON.

**Comment by konsumer** [comment]
@acozzette In the above example, I am using `deserializeBinary()`, not `toObject()`. It's not that I want to convert it to JSON, I just want to hand something to the protoc plugin-writer that is useful, and I need to see the structure because I can't find any documentation on what the generated parser outputs. Since `stdout` only accepts strings (not JS objects) I am outputting what I can there. If I use `util.inspect(res, { showHidden: true, depth: null })` I see a bunch of wrapped objects that probably have methods that return the info I am looking for, but I'm not sure how to use them. If I hand an instance of a pre-populated `CodeGeneratorRequest` to the plugin-writer's function, I will probably need to make an example of grabbing the options, to help illustrate the solution to the issues I am having, since I think parsing those grpc options (or other field/rpc options) will be a fairly common use-case.

I think the problem I am hitting is that I need to know ahead of time the structure of the proto file being parsed by protoc, but maybe that is the part I am missing. Since this is intended for making plugins to turn any proto file into something else (eg source code or docs) it seems straightforward to turn the incoming plugin info into some sort of complete javascript object (JSON or otherwise) to make it easy to deal with, but maybe I am over-libraryizing, and should just leave it up to the plugin-writer to pull out the options they care about.

**Comment by acozzette** [comment]
@konsumer Ah ok, I see. If you just want to look at a human-readable form of the data, I would recommend  using `protoc --decode` like the command @xfxyjwf posted above. This should include the options (represented as extensions) which do not seem to be included in the output of `toObject()`.

To get at the options from within Javascript, you'll need to do something like `res.getExtension(annotations_pb.http)` where `annotations_pb` comes from compiling [this](https://github.com/googleapis/googleapis/blob/6ae2d424245deeb34cf73c4f7aba31f1079bcc40/google/api/annotations.proto) file that defines the options.

**Comment by konsumer** [comment]
@acozzette That totally makes sense. Thank you so much for your patience and explanations.

I started to try out your suggestions, but discovered that if you include all the types that are referenced, it actually does what I originally wanted with `toObject()`!


```js
const util = require('util')
const _ = require('highland')
const tou8 = require('buffer-to-uint8array')
const pluginPb = require('./google/protobuf/compiler/plugin_pb')
require('./google/api/annotations_pb') // not used, but probably monkey-patching a global

_(process.stdin)
  .reduce1((a, b) => Buffer.concat([a, b]))
  .map((req) => pluginPb.CodeGeneratorRequest.deserializeBinary(tou8(req)))
  .map((CodeGeneratorRequest) => CodeGeneratorRequest.toObject())
  // do stuff here instead of outputting to console
  .map((res) => util.inspect(res, { showHidden: true, depth: null }))
  .pipe(process.stdout)
```

Outputs all the grpc stuff:

```
[ { name: 'Greeter',
            methodList: 
             [ { name: 'sayHello',
                 inputType: '.helloworld.GreeterRequest',
                 outputType: '.helloworld.GreeterReply',
                 options: 
                  { deprecated: false,
                    idempotencyLevel: 0,
                    uninterpretedOptionList: [ [length]: 0 ],
                    http: 
                     { selector: '',
                       get: '',
                       put: '',
                       post: '/v1/hi',
                       pb_delete: '',
                       patch: '',
                       custom: undefined,
                       body: '*',
                       additionalBindingsList: [ [length]: 0 ] } },
                 clientStreaming: false,
                 serverStreaming: false },
               { name: 'sayGoodbye',
                 inputType: '.helloworld.GreeterRequest',
                 outputType: '.helloworld.GreeterReply',
                 options: 
                  { deprecated: false,
                    idempotencyLevel: 0,
                    uninterpretedOptionList: [ [length]: 0 ],
                    http: 
                     { selector: '',
                       get: '',
                       put: '',
                       post: '/v1/bye',
                       pb_delete: '',
                       patch: '',
                       custom: undefined,
                       body: '*',
                       additionalBindingsList: [ [length]: 0 ] } },
                 clientStreaming: false,
                 serverStreaming: false },
               [length]: 2 ],
            options: undefined },
          [length]: 1 ],
```

The confusing thing to me was that the helloworld.proto is doing an `import` for the annotations, so I would imagine that I wouldn't need to pre-parse the annotation proto, but I guess that's not really how it works. I can totally include instructions to pre-parse & `require` any extensions before using the plugin, with an example that illustrates the above. Thanks again @xfxyjwf and @acozzette!

**Comment by konsumer** [comment]
If anyone is interested, my project is over [here](https://github.com/konsumer/node-protoc-plugin). My issue is totally resolved. Thanks again!
