### ISSUE TITLE
Error in compiling C++ projects - repeated_field.h (libprotoc 3.2.0)

### ISSUE THREAD

**Issue by kkotyk** [google/protobuf#2765]
When I compile my project files that use my compiled protobufs I get the following error if I use libprotoc 3.2.0:
/usr/local/include/google/protobuf/repeated_field.h(1490): error: return value type does not match the function type

The compiler error gives no indication how this error is related to my code. This error does not appear if I install using libprotoc 3.1.0 instead.

make check shows all tests pass on both versions of libprotoc that I used.

Please list any other information you might need.

**Comment by TeBoring** [comment]
Where did you get the library?

**Comment by kkotyk** [comment]
Compiled from source following the C++ install instructions. I'm using the current master branch for my 3.2.0 install.

**Comment by TeBoring** [comment]
Could you try git checkout v3.2.0?
And what's the OS, compiler, c++ library you are using?

**Comment by kkotyk** [comment]
Just tried. It happens with that branch as well.

NAME="openSUSE Leap"
VERSION="42.2"
gcc (SUSE Linux) 4.8.5

which C++ lib are you refering to and how can I find the version?

**Comment by TeBoring** [comment]
For c++ lib, I meant the gcc.
We don't have openSUSE machines for test. Could you give us a docker image for debugging?
You are also welcome to provide a fix.

**Comment by kkotyk** [comment]
Sorry I made a mistake. The issue DOES NOT happen on the 3.2.x branch. Only the master branch.

**Comment by kkotyk** [comment]
I would like to be able to help, however I'm not familiar with the inner workings of the protobufs and I'm not sure how to debug the issue based off that single compiler error. Can you point me to some good documentation on how to create a Docker image? I can at least provide that for you.

**Comment by TeBoring** [comment]
Here is a tutorial about building an image: https://docs.docker.com/engine/getstarted/step_four/

**Comment by kkotyk** [comment]
@TeBoring Okay I've read a bit into these Docker images. What would you like contained within the image? I noticed that OpenSUSE has a base image.

**Comment by TeBoring** [comment]
You can just tell us the base image. If your error can be reproduced there.

**Comment by kkotyk** [comment]
I'm using the latest stable version, OpenSUSE 42.2. It might take me a few days, but I will attempt to recreate the issue from within a container. Please post back if you manage to recreate the error before I do.

https://hub.docker.com/_/opensuse/

**Comment by TeBoring** [comment]
Thanks. If your need to install other stuff in docker container, please
mention it in a Dockerfile.

**Comment by seed93** [comment]
Happened the same. Ubuntu 14.04, gcc 4.8.4

**Comment by TeBoring** [comment]
@seed93, master or 3.2.x branch?
I am surprised about this. I think we have tested this environment.

**Comment by seed93** [comment]
@TeBoring master branch. commit id is 008ff033ef3308512c1da2b7cdadf50a6296251a

**Comment by TeBoring** [comment]
@seed93, I used the ubuntu 14.04 images, which has the gcc 4.8.4.
The head of master is built without any error.
