### ISSUE TITLE
Add protoc --parse-only to facilitate building linters/auto-formatters

### ISSUE THREAD

**Issue by mwitkow** [google/protobuf#2767]
It would be *fantastic* if `protoc` command had a `--parse-only` flag which would output the 
"text-file equivalent", non-imports-dependent output of https://github.com/google/protobuf/blob/master/src/google/protobuf/compiler/parser.h#L72 
Right now

This would make it easy to build source-tree layout-independent tooling, basically an ability to get the `FileDescriptor` equivalent of the text of `.proto` files independently without relying on the appropriate imports path.  

This, combined with `--include_source_info` would allow developers to build auto-formatters and linters, which can be run on individual `.proto` files, either from editors or from the command line.

**Comment by pherl** [comment]
There's descriptor_set_out parameter which will generate a transitive closure on all the descriptors set.
