### ISSUE TITLE
Typos in the Basics: Python tutorial

### ISSUE THREAD

**Issue by obrien-j** [google/protobuf#2768]
https://developers.google.com/protocol-buffers/docs/pythontutorial

Pretty trivial typo in the declaration for the .proto at the link above. 

`message AddressBook {
  repeated Person people = 1;
}`

"people" is used in the proto declaration, but then referred to as "person" in the write&read from python code samples..

`PromptForAddress(address_book.person.add())`

and

`for person in address_book.person:`

Probably cleanest to just replace person in the two lines with people, as the plural makes a bit more sense with the repeating proto definition.

**Comment by TeBoring** [comment]
Fixed.
