### ISSUE TITLE
[python cpp_implementation] ImportError: dlopen(protobuf/python/google/protobuf/pyext/_message.so, 2): Symbol not found: __ZN6google8protobuf14FileDescriptor10SyntaxNameENS1_6SyntaxE

### ISSUE THREAD

**Issue by tamird** [google/protobuf#277]
Following the instructions at https://github.com/google/protobuf/blob/master/python/README.md, specifically:
>  If you want to build/test c++ implementation, run:
 $ python setup.py build --cpp_implementation
 $ python setup.py google_test --cpp_implementation

I get the error:
```
$ python setup.py build --cpp_implementation
...
$ python setup.py google_test --cpp_implementation
running google_test
running egg_info
writing requirements to protobuf.egg-info/requires.txt
writing protobuf.egg-info/PKG-INFO
writing namespace_packages to protobuf.egg-info/namespace_packages.txt
writing top-level names to protobuf.egg-info/top_level.txt
writing dependency_links to protobuf.egg-info/dependency_links.txt
reading manifest file 'protobuf.egg-info/SOURCES.txt'
writing manifest file 'protobuf.egg-info/SOURCES.txt'
running build_ext
copying build/lib.macosx-10.9-x86_64-2.7/google/protobuf/pyext/_message.so -> google/protobuf/pyext
Traceback (most recent call last):
  File "setup.py", line 210, in <module>
    "Protocol Buffers are Google's data interchange format.",
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python2.7/site-packages/setuptools/command/test.py", line 142, in run
    self.with_project_on_sys_path(self.run_tests)
  File "/usr/local/lib/python2.7/site-packages/setuptools/command/test.py", line 122, in with_project_on_sys_path
    func()
  File "/Users/tamird/src/protobuf/python/.eggs/google_apputils-0.4.2-py2.7.egg/google/apputils/setup_command.py", line 157, in run_tests
    ok &= self._RunTestModule(file_path)
  File "/Users/tamird/src/protobuf/python/.eggs/google_apputils-0.4.2-py2.7.egg/google/apputils/setup_command.py", line 123, in _RunTestModule
    module = imp.load_module(module_name, *import_tuple)
  File "google/protobuf/internal/descriptor_database_test.py", line 38, in <module>
    from google.protobuf import descriptor_pb2
  File "/Users/tamird/src/protobuf/python/google/protobuf/descriptor_pb2.py", line 6, in <module>
    from google.protobuf import descriptor as _descriptor
  File "/Users/tamird/src/protobuf/python/google/protobuf/descriptor.py", line 49, in <module>
    from google.protobuf.pyext import _message
ImportError: dlopen(/Users/tamird/src/protobuf/python/google/protobuf/pyext/_message.so, 2): Symbol not found: __ZN6google8protobuf14FileDescriptor10SyntaxNameENS1_6SyntaxE
  Referenced from: /Users/tamird/src/protobuf/python/google/protobuf/pyext/_message.so
  Expected in: flat namespace
 in /Users/tamird/src/protobuf/python/google/protobuf/pyext/_message.so
```

Inspecting `python/google/protobuf/pyext/_message.so`:
```
$ nm google/protobuf/pyext/_message.so | grep __ZN6google8protobuf14FileDescriptor10SyntaxNameENS1_6SyntaxE
                 U __ZN6google8protobuf14FileDescriptor10SyntaxNameENS1_6SyntaxE
```
So the symbol is undefined? Not sure what to make of this. cc @haberman

**Comment by haberman** [comment]
Ah, I think I may have neglected to put in the README that you have to `make install` on the main protobuf C++ library before you can run the C++ extension.

The problem is that the .so for the Python/C++ extension will look for the libprotobuf.so installed in the system, *not* the one in the source tree:

    $ ldd google/protobuf/pyext/_message.so
            linux-vdso.so.1 =>  (0x00007fff55bec000)
            libprotobuf.so.10 => /usr/local/lib/libprotobuf.so.10 (0x00007fb8e2376000)
            libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fb8e2072000)
            libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fb8e1d6b000)
            libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fb8e1b55000)
            libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fb8e1790000)
            libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fb8e1571000)
            libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fb8e1358000)
            /lib64/ld-linux-x86-64.so.2 (0x00007fb8e2904000)

So you need to `make install` in the base of the source tree, so that `/usr/local/lib/libprotobuf.so.10` is the library you just built, that has the latest and greatest.

**Comment by tamird** [comment]
Ah, that's a bummer.

**Comment by tamird** [comment]
Feel free to close this when the README is updated.

**Comment by parangsaraf** [comment]
I am facing the same issue. I have successfully installed the protobuf C++ library and my protoc --version command is working fine. 

However, I don't have any libprotobuf.so.* file present in /usr/local/lib/ folder. Here are all the libprotobuf files present in the folder: 

libprotobuf-lite.10.dylib libprotobuf-lite.dylib    libprotobuf.9.dylib       libprotobuf.la            libprotoc.a
libprotobuf-lite.9.dylib  libprotobuf-lite.la       libprotobuf.a             libprotoc.10.dylib        libprotoc.dylib
libprotobuf-lite.a        libprotobuf.10.dylib      libprotobuf.dylib         libprotoc.9.dylib         libprotoc.la

I tried installing both 3.0.0 and 2.6.1. While 3.0.0 works fine, the problem happens while installing 2.6.1

**Comment by haberman** [comment]
It looks like you are on MacOS X?

**Comment by parangsaraf** [comment]
Yes that's correct. Any idea how I can fix that?

**Comment by shenodaguirguis** [comment]
I faced the same issue and the fix for me was to add protobuf lib as a target link (in the CMakeLists.txt), to link protobuf in the produced executable. Something like: `target_link_libraries(<my project target> PRIVATE ${PROTOBUF_LIBRARY})`
