### ISSUE TITLE
java decode data failed. when php set int32 field value large than 128. 

### ISSUE THREAD

**Issue by jesus7** [google/protobuf#2773]
anyone has this issues? how can i  fix it?

**Comment by TeBoring** [comment]
Could you give us more detail about the issue?
What language are you using? And what version are you talking about? Where do you get the code?

**Comment by TeBoring** [comment]
Feel free to reopen the issue if you still have the problem.

**Comment by tomoat** [comment]
I have this problem too use php

**Comment by liqiang0508** [comment]
I have this problem too use nodejs

**Comment by 445052020** [comment]
I have this problem too use c++
