### ISSUE TITLE
_OBJC_CLASS_$_Person", referenced from: objc-class-ref in ViewController.o

### ISSUE THREAD

**Issue by shasanksakala** [google/protobuf#2777]
1. Initially I create a frameworking project using some classes
 2. Next I created a framework_name.framework 
 3. Place the above created framework in a project and imported some .h class and tried to run the project.
 4. While running the project I am getting the following issues please check the following image.

[![enter image description here][1]][1]

  [1]: https://i.stack.imgur.com/vPZDz.png

 1. I changed the architectures even still I am getting the same issue
 2. I checked various solution in the forum, such like add the .m file but we cannot have the .m file in framework
 3. I even tried to add some flags in build settings 

In this I used the Xcode 8.2.1

**Comment by thomasvl** [comment]
Assuming the framework is what has your sources generated from the protos, it sounds like you aren't linking the framework into your application.

**Comment by shasanksakala** [comment]
If I am not linking the framework I will get file not found, I am able to access the objects from thoses classes like person (it is one of the NSobject).

**Comment by thomasvl** [comment]
Linking the framework and including it in search paths are different things.  It all depends on how you have set up your project.  From the sounds of thing the header is being found, but the .m file isn't compiled in to the framework or the framework isn't linked in to the final app.

**Comment by shasanksakala** [comment]
How can confirm that .m files are compiled in to the framework?? Please help.

**Comment by thomasvl** [comment]
See what sources are in the framework target.

btw - you're sorta well out of the space of problems with protobufs, this is sounding like generic problems using/understanding Xcode.

**Comment by shasanksakala** [comment]
Hi @thomasvl 

I figured out my issue in my framework, it is not related to Protobufs, Thank you so much.

**Comment by KirillSemine** [comment]
Helle shasanksakala
How did you fix this problem?
