### ISSUE TITLE
Ruby gem 3.2.0 fails to load on Centos 6 and Debian 7 due to missing GLIBC_2.14

### ISSUE THREAD

**Issue by jacobvosmaer** [google/protobuf#2783]
https://gitlab.com/gitlab-org/omnibus-gitlab/issues/2042

We get this error when trying to load the google-protobuf 3.2.0 gem on Debian 7 and Centos 6:

```
LoadError: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.14' not found (required by /opt/gitlab/embedded/lib/ruby/gems/2.3.0/gems/google-protobuf-3.2.0-x86_64-linux/lib/google/protobuf_c.so) - /opt/gitlab/embedded/lib/ruby/gems/2.3.0/gems/google-protobuf-3.2.0-x86_64-linux/lib/google/protobuf_c.so
```

I wonder if this is a reincarnation of #354 #781 #969.

**Comment by jacobvosmaer** [comment]
As a workaround you can install the gem from source. I documented that process in https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/9665/diffs

**Comment by jacobvosmaer** [comment]
The gem for protobuf 3.1.0 also has the GLIBC_2.14 problem.

**Comment by jacobvosmaer** [comment]
We found a simpler workaround.

```
# get a .gem without platform-specific binaries
gem fetch google-protobuf -v 3.2.0 --platform=
gem install google-protobuf-3.2.0.gem --local
```

So a working release _is_ being pushed to rubygems, but `gem install google-protobuf` will grab the linux-amd64 one even if it does not work (due to GLIBC).

**Comment by acozzette** [comment]
@jacobvosmaer  It sounds like we might just need to build for an older glibc version; what version do you have?

**Comment by jacobvosmaer** [comment]
We (GitLab) ship to Debian 7 and Centos 6. Those seem to use gblic 2.13 and 2.12, respectively.

So 2.12 should do it.

```
[jacobvosmaer@centos6-test ~]$ ldd --version
ldd (GNU libc) 2.12
Copyright (C) 2010 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
```

```
jacobvosmaer@debian7-test:~$ ldd --version
ldd (Debian EGLIBC 2.13-38+deb7u10) 2.13
Copyright (C) 2011 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
```

**Comment by acozzette** [comment]
This should now be fixed with the 3.2.0.1 version of the gem. @jacobvosmaer Do you want to give it a try just to verify the fix?

**Comment by jacobvosmaer** [comment]
Centos 6 looks OK (Ruby 2.3.3 from RVM):

```
[jacobvosmaer@centos6-test ~]$ gem install google-protobuf
Fetching: google-protobuf-3.2.0.1-x86_64-linux.gem (100%)
Successfully installed google-protobuf-3.2.0.1-x86_64-linux
Parsing documentation for google-protobuf-3.2.0.1-x86_64-linux
Installing ri documentation for google-protobuf-3.2.0.1-x86_64-linux
Done installing documentation for google-protobuf after 0 seconds
1 gem installed
[jacobvosmaer@centos6-test ~]$ ruby -rgoogle/protobuf -e 'puts :ok'
ok
```

Trying Debian 7 next.

**Comment by jacobvosmaer** [comment]
Also looks OK on Debian 7.

```
jacobvosmaer@debian7-test:~$ gem install google-protobuf
Fetching: google-protobuf-3.2.0.1-x86_64-linux.gem (100%)
Successfully installed google-protobuf-3.2.0.1-x86_64-linux
Parsing documentation for google-protobuf-3.2.0.1-x86_64-linux
Installing ri documentation for google-protobuf-3.2.0.1-x86_64-linux
Done installing documentation for google-protobuf after 0 seconds
1 gem installed
jacobvosmaer@debian7-test:~$ ruby -rgoogle/protobuf -e 'puts :ok'
ok
```

Thanks @acozzette !

**Comment by acozzette** [comment]
Great, I'm glad to hear it works!

**Comment by jacobvosmaer** [comment]
Unfortunately 3.2.0.1 introduces a different LoadError. :( https://github.com/google/protobuf/issues/2853

**Comment by xiongchiamiov** [comment]
For people searching:  the same thing happened in grpc (at least - it seems like a general problem with how Google manages Ruby gems): grpc/grpc#11346

**Comment by GreenReaper** [comment]
This fix appears to have [broken protobuf in Debian Ports](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=931503) for the [x32 ABI](https://en.wikipedia.org/wiki/X32_ABI), because it requires the build to use symbols from a version of glibc a decade before glibc was compiled for x32.

It probably could do with being additionally qualified with `&& !defined(__ILP32__)` as described there.

**Comment by acozzette** [comment]
@GreenReaper Do you want to send a pull request with that fix?

**Comment by GreenReaper** [comment]
...not really? 😅 I'm unconcerned about credit, and I figured it's easy to determine what line I was talking about - maybe that's not right, in which case I could send a diff - or maybe I've misunderstood why you're asking?

I don't have a copy of your repository (or Debian's build infrastructure, for that matter) - I'm just trying to get more things compiling correctly on it, and I think the addition of that condition to the existing ones would do that.
________________________________

**Comment by acozzette** [comment]
No problem, I thought I would ask but if you don't want to volunteer to send the fix then that is totally fine.
