### ISSUE TITLE
Setter for map fields in javascript

### ISSUE THREAD

**Issue by ivan-sysoi** [google/protobuf#2789]
Hello. I am a newer in protobuf. It is not an issue, it is a question.
I use protoc to generate js messages. 
```
protoc -I=`dirname $file` --js_out=import_style=closure,binary:/opt/projects/... $file
```
I have noticed that there is no setter for map fields.

I have tried to use something like that to set map field in the message:
```
jspb.Message.setField(myMessage, 8, myMapData);
myMessage.geMyMapMap();
```

So how to set map field correctly? Will setter be added in future?

**Comment by acozzette** [comment]
The way it works is that you call `getMyMapMap()` to get the map, and then call `set()` on that to actually set key-value pairs on the map. Here's an example of from maps_test.js: https://github.com/google/protobuf/blob/2b7430d96aeff2bb624c8d52182ff5e4b9f7f18a/js/maps_test.js#L87

**Comment by stefanobaghino-da** [comment]
Hi there! :wave: 

I'm writing a small tool to convert `protoc` JS output to plain JS object (kinda what you can do with `toObject` but going both ways but with the possibility to map to make adjustments to the output schema).

Unfortunately this deviation from the _getters_/_setters_ approach make my code slightly more complex. This is not an issue of course, I was just curious regarding the different approach, since also lists can be put in place with a setter.

**Comment by tooolbox** [comment]
@acozzette is that documented somewhere that I missed?  I was only able to figure that out after Google brought up this issue--but I could certainly be guilty of skimming the docs.

**Comment by stefanobaghino-da** [comment]
@tooolbox https://developers.google.com/protocol-buffers/docs/reference/javascript-generated#map :sli

**Comment by tooolbox** [comment]
@stefanobaghino-da  thanks man :)

**Comment by pojka** [comment]
> Hi there! 👋
> 
> I'm writing a small tool to convert `protoc` JS output to plain JS object (kinda what you can do with `toObject` but going both ways and with the possibility to make adjustments to the output "schema").
> 
> Unfortunately this deviation from the _getters_/_setters_ approach make my code slightly more complex. This is not an issue of course, I was just curious regarding the different approach, since also lists can be put in place with a setter.

Did you ever write one? :)

**Comment by pojka** [comment]
> Hi there! 👋
> 
> I'm writing a small tool to convert `protoc` JS output to plain JS object (kinda what you can do with `toObject` but going both ways and with the possibility to make adjustments to the output "schema").
> 
> Unfortunately this deviation from the _getters_/_setters_ approach make my code slightly more complex. This is not an issue of course, I was just curious regarding the different approach, since also lists can be put in place with a setter.

@stefanobaghino-da Did you ever finish writing one? :)

**Comment by stefanobaghino-da** [comment]
> @stefanobaghino-da Did you ever finish writing one? :)

Kinda, but:

1. it's part of a now deprecated project
2. it's definitely not generic

So I'm not sure how helpful it would be. Anyway, you can see it [here](https://github.com/digital-asset/daml-js/tree/master/src/codec).

**Comment by pojka** [comment]
@stefanobaghino-da thank you, much appreciated!

**Comment by haroon-omer2000** [comment]
> 

Hi, this doesn't seem to be working for me. On the server side i'm getting an empty object. 
Here is what i did:
iceCreamRequest.getOrderMap().set(order_history); //order history is an object
