### ISSUE TITLE
Can't import _message

### ISSUE THREAD

**Issue by bergjo06** [google/protobuf#2797]
This recreates the error:
$ python
Python 2.7.5 (default, Aug  2 2016, 04:20:16)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-4)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from google.protobuf.pyext import _message
Traceback (most recent call last):
   File "<stdin>", line 1, in <module>
ImportError: dynamic module does not define init function (init_message)

I get the error when I try the following: 
$ export PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=cpp
$ python
Python 2.7.5 (default, Aug  2 2016, 04:20:16)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-4)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import addressbook_pb2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "addressbook_pb2.py", line 6, in <module>
    from google.protobuf import descriptor as _descriptor
  File "/home/jberg/venv/lib/python2.7/site-packages/google/protobuf/descriptor.py", line 46, in <module>
    from google.protobuf.pyext import _message
ImportError: dynamic module does not define init function (init_message)

This is for libprotoc 2.6.1

**Comment by haberman** [comment]
Did you compile from source? Did you set the `LD_LIBRARY_PATH` correctly?

I highly recommend using a more recent version of protocol buffers. There are many features that were added and bugs that were fixed since 2.6.1.
