### ISSUE TITLE
gcc "decimal constant is unsigned only in ISO C90" warning in c++ generated code with -m32

### ISSUE THREAD

**Issue by scotthunt** [google/protobuf#280]
"warning: this decimal constant is unsigned only in ISO C90" in c++ generated code (compiled with -m32)
Specific line of code is:
    if (_has_bits_[24 / 32] & 4278190080) {

Seems like changing it like this would be less warning-ful:
    if (_has_bits_[24 / 32] & 0xff000000) {

Potential patch:
--- a/src/protobuf-2.6.1/src/google/protobuf/compiler/cpp/cpp_message.cc
+++ b/src/protobuf-2.6.1/src/google/protobuf/compiler/cpp/cpp_message.cc
@@ -1620,10 +1620,11 @@ GenerateClear(io::Printer\* printer) {
           (count <= 4 && count == memset_field_count_for_chunk[i / 8])) {
         // No "if" here because the chunk is trivial.
       } else {
-        char buffer[kFastToBufferSize];
       printer->Print(
-          "if (_has_bits_[$index$ / 32] & $mask$) {\n",
-          "if (_has_bits_[$index$ / 32] & 0x$mask$) {\n",
         "index", SimpleItoa(i / 8 \* 8),
-          "mask", SimpleItoa(mask));
-          "mask", FastHex32ToBuffer(mask, buffer));
       printer->Indent();
       chunk_block_in_progress = true;
     }

**Comment by xfxyjwf** [comment]
Feel free to send the patch as a pull request to us.

**Comment by acozzette** [comment]
I am going to go ahead and close this because we are cleaning up issues and I see that this one has not been updated in a long time. Feel free to reopen it if this is still a problem, though.
