### ISSUE TITLE
"warning: type attributes ignored after type is already defined [-Wattributes]" caused by dllexport_decl

### ISSUE THREAD

**Issue by a-andre** [google/protobuf#2802]
Since the update to protobuf 3.2 I get a lot of __type attributes ignored after type is already defined [-Wattributes]__ warnings, using gcc 6.3.
These are caused by `$dllexport_decl$` in [`"friend struct $dllexport_decl$ $file_namespace$::TableStruct;\n"`](https://github.com/google/protobuf/blob/master/src/google/protobuf/compiler/cpp/cpp_message.cc#L1465). Removing the expression fixed the issue.

**Comment by acozzette** [comment]
Thanks for reporting this; do you have a pull request you could send out with a fix?

**Comment by acozzette** [comment]
It sounds like the fix would go here: https://github.com/google/protobuf/blob/a69bc9de75fe08f5fe7ad6e2339dfc5b0da5d8ef/src/google/protobuf/compiler/cpp/cpp_message.cc#L1465

**Comment by a-andre** [comment]
Thx hesmar
