### ISSUE TITLE
PHP API Design

### ISSUE THREAD

**Issue by TeBoring** [google/protobuf#2803]
Before PHP protobuf GA release, we want to share our design doc to get some feedback from opensource community. Feel free to leave some comments in the design doc.
https://docs.google.com/document/d/1fUi0lKpfR7gauaJdhjid1SStdLePREVeUnwfamrPRVk

**Comment by tuupola** [comment]
Currently generated files are mixture of the deprecated [PSR-0](http://www.php-fig.org/psr/psr-0/) and current [PSR-4](http://www.php-fig.org/psr/psr-4/) standards. If I have the following proto file.

```
syntax = "proto3";
package example;

message Foo {
    message Baz {
        int64 x = 1;
        int64 y = 2;
    }

    message Bar {
        string z = 1;
    }
}
```

Class names will be like `Example\Foo_Bar` with directory structure below.

```
├── Example
│   ├── Foo.php
│   ├── Foo_Bar.php
│   └── Foo_Baz.php
└── GPBMetadata
    └── Example.php

2 directories, 4 files
```

PSR-4 style class names should be `Example\Foo\Bar` style instead and directory structure like below.

```
test/
├── Example
│   ├── Foo
│   │   ├── Bar.php
│   │   └── Baz.php
│   └── Foo.php
└── GPBMetadata
    └── Example.php

3 directories, 4 files
```

Additionally. Maybe I am missing something. Is there a reason for current behaviour?

```
$ protoc --version
libprotoc 3.3.0
```

**Comment by TeBoring** [comment]
Thanks for the advice.
For embedded message, the generated class is Foo_Baz instead of Foo/Baz, so it still conform to PSR-4.
