### ISSUE TITLE
PHP Cannot get which oneof is actually set

### ISSUE THREAD

**Issue by TeBoring** [google/protobuf#2806]
This was fixed in #2631. But it seems not be included in 3.2.0 release.

**Comment by TeBoring** [comment]
Because this requires a new release of compiler, I'll fix this in 3.3.0 release.

**Comment by mcos** [comment]
@TeBoring what's the estimated release date for this? Could we get an intermediary 3.2.1 bugfix release?

**Comment by TeBoring** [comment]
3.3 will be released in these two weeks.
