### ISSUE TITLE
google was shielded in china

### ISSUE THREAD

**Issue by playaround88** [google/protobuf#282]
hi!
As you kown google was shielded in china, so I clone the source from github, but connot build!
when I run ./autogen.sh
error is: Failed to connect to googletest.googlecode.com port 443
so, can you help us, change some dependency to github or any other site that can reach

**Comment by xfxyjwf** [comment]
That script attempts to download gtest from googlecode if it's not present. You can download one of our release packages here: https://github.com/google/protobuf/releases. These release packages already have the gtest included and you can run ./configure && make check to build/compile the code. If for some reason you need to work with protobuf at head, you can copy the gtest directory from a release package to your cloned protobuf directory. That should work as well.
