### ISSUE TITLE
Adding of Properties in Protobuf - C#

### ISSUE THREAD

**Issue by adityaswami89** [google/protobuf#2828]
Hello,

The C# implementation is slightly different from the Python or other implementation. 
Case : 
I have an existing Proto file(Proto1.proto) with 5 properties and i wish to add 2 more properties in this. However the  proto1 with 5 properties will be used and also the proto with 7 properties. In C# can i use only the new Proto (with 7 properties) to work with both types of data that will be coming in ( data with 5 and 7). How can i implement this feature which is bydefault available in python implementation.

**Comment by pherl** [comment]
Do you still have this problem? We are closing open issues. Feel free to send PRs and reopen if you'd like to follow up on the issue.
