### ISSUE TITLE
JsonParser will not ignore unknown field when parsing - C#

### ISSUE THREAD

**Issue by Genmutant** [google/protobuf#2838]
Like the closed Issue #1610 for Java, the C# JsonParser doesn't ignore unknown fields during parsing.
If an unknown object is encountered, it throws an Exception: 

```
if (jsonFieldMap.TryGetValue(name, out field))
{
	[...]
}
else
{
	// TODO: Is this what we want to do? If not, we'll need to skip the value,
	// which may be an object or array. (We might want to put code in the tokenizer
	// to do that.)
	throw new InvalidProtocolBufferException("Unknown field: " + name);
}
```

It would be great if there would exists a similar option as got added to the Java Parser (`ignoringUnknownFields()`).

**Comment by joelpresence** [comment]
Thanks for all of your hard work on protobuf.

Hi, has this bug been looked at by Google?  This is a show stopping bug for us.  We are sending proto3 messages encoded as JSON via pubnub and then deserializing the JSON using the proto3 autogenerated json parsing.  Is it really the case that proto3 can encode a message as json with a new field but proto3 cannot successfully parse a message with that new field from json using an older definition of the containing message?  The new field was added with a higher flag and we followed all the rules, so why can't Google's own C# proto3 JSON demarshaller handle the field that was added by its json marshaller?  :-(

**Comment by jskeet** [comment]
I hadn't seen it before a few days ago. I'm no longer working on the Protobuf team beyond a 20% capacity, but I'll try to have a look this week.

**Comment by aaronhudon-ts** [comment]
I'm having a heck of a time making this work with version 3.8.0

`MessageParser<T>.WithDiscardUnknownFields(true).ParseJson` will always throw an exception about unknown fields

**Comment by aaronhudon-ts** [comment]
> I'm having a heck of a time making this work with version 3.8.0
> 
> `MessageParser<T>.WithDiscardUnknownFields(true).ParseJson` will always throw an exception about unknown fields

Seems to only work by instantiating a new `JsonParser`.  The static parser property available for each message doesn't appear to respect the json parsing settings.

So this works:
`new JsonParser(JsonParser.Settings.Default.WithIgnoreUnknownFields(true)).Parse<T>(json);`

**Comment by jskeet** [comment]
@aaronhudon-ts: Are you sure you weren't just confusing `WithDiscardUnknownFields` (used when serializing protos to binary) and `WithIgnoreUnknownFields` (used when parsing JSON)? I do appreciate that they're not the clearest names in the world.

The `MessageParser<T>` doesn't include JSON settings, so yes, constructing a new JSON parser is the right way to go here. It's fine to construct a single instance and keep it around though.

**Comment by aaronhudon-ts** [comment]
> @aaronhudon-ts: Are you sure you weren't just confusing `WithDiscardUnknownFields` (used when parsing and then serializing protos in binary form) and `WithIgnoreUnknownFields` (used when parsing JSON)? I do appreciate that they're not the clearest names in the world.
> 
> The `MessageParser<T>` doesn't include JSON settings, so yes, constructing a new JSON parser is the right way to go here. It's fine to construct a single instance and keep it around though.

Hey @jskeet I was originally using the `Parser` property that comes for free in the auto-generated message classes.
E.g. `MyMessage.Parser.WithDiscardUnknownFields(true).ParseJson(...)`

Too bad this doesn't work - as it seems relatively natural in the syntax (once you find the extension method).

**Comment by jskeet** [comment]
Looking back, I don't know whether we'd want to make that work or not, if we'd thought about it from the start. There's a subtle difference between the JSON and pb parsing here - if you preserve unknown fields in the pb parser, it retains them and then emits them later if you write out the proto. The JSON parser doesn't do that (and can't, really) - it just throws if you have any unknown fields.

That said, I can see how the parser retaining JSON settings could be useful.
