### ISSUE TITLE
Segmentation fault when using arena allocation with gcc 4.8

### ISSUE THREAD

**Issue by hfn92** [google/protobuf#2839]
Hello, 

The line
`ptr_ = new ::std::string(*initial_value);`
in `CreateInstance` (arenastring.h) causes a segmentation fault when compiled with gcc 4.8.4.
This method is called  eventually when calling `mutable_<string-field>`.

There the method `::google::protobuf::internal::GetEmptyStringAlreadyInited()` is called which uses a reinterpret_cast to cast a `char[sizeof(std::string)` to `std::string*` (btw isn’t  that undefined behavior?). This works fine on newer versions of gcc when the cxx11-abi version of std::string is used (sizeof(T) = 32).  gcc 4.8.4 however uses the pre cxx11-abi version std::string (sizeof(T) = 8) in which the cast fails and causes a segmentation fault when accessing the the reinterpret_cast result.

When stripped down to the the relevant parts you get this code (to try it on different compilers):
```
    char arr[sizeof(std::string)] = {0};
    const std::string* str = reinterpret_cast<const std::string*>(&arr);
    string* s = new std::string(*str);
```
This doesn’t work on gcc 4.8.4 but works fine on gcc 5.4 and newer (if not compiled if flags that disable the use of the newer abi)

**Comment by acozzette** [comment]
I believe that reinterpret_cast is OK and is defined behavior, because we do initialize the char array with placement-new [here](https://github.com/google/protobuf/blob/a69bc9de75fe08f5fe7ad6e2339dfc5b0da5d8ef/src/google/protobuf/generated_message_util.h#L90), like this: `new (&union_) T();`

It sounds to me like this must be some ABI issue then. This page seems to describe the GCC ABI change for std::string: https://gcc.gnu.org/onlinedocs/libstdc++/manual/using_dual_abi.html Based on that it sounds like all object files linked together must use the same ABI; would that possibly explain the problem? I have been using g++ 4.8.4 without any problems, but perhaps in your setup you are linking the protobuf library against code compiled against a newer ABI.

**Comment by gerben-s** [comment]
this is carefully designed to be c++14 conforming. It's basically a reimplementation of the c++14 http://en.cppreference.com/w/cpp/types/aligned_storage so it works with pre-c++14. It's based on an exception that a char/byte array is allowed as a backing buffer for other types.

Your segfault seems like an ABI linking incompatibility of libs compiled with different versions.

**Comment by hfn92** [comment]
Thank you for your answers!

Sorry I missed the `new (&union_) T();`

I don't think it's an abi issue because the installed libstdc++ doesn't even support cxx11 abi std::strings. (_GLIBCXX_USE_DUAL_ABI 0 and _GLIBCXX_USE_CXX11_ABI 0 are set).

After some investigation it looks like an initialization issue. `DefaultConstruct()` is never called or so it seems since `init_` is always false. If i add `fixed_address_empty_string.DefaultConstruct();` to `GetEmptyStringAlreadyInited()` it works fine - no segmentation fault. Is a special step necessary to make sure everything necessary is initialized? 

I will provide a minimal example project at a later time. Thank you!

**Comment by hfn92** [comment]
Here's my test project. Please try it out. What am I doing wrong?
I used a fresh install of ubuntu-14.04 with gcc 4.8.4 installed and protobuf 3.2.0
[Uploading ProtoTest.zip…]()

**Comment by hfn92** [comment]
Here's my test project. Please try it out. What am I doing wrong?
I used a fresh install of ubuntu-14.04 with gcc 4.8.4 installed and protobuf 3.2.0
[Uploading ProtoTest.zip…]()

**Comment by acozzette** [comment]
@hfn92 Thank you for the test case, I think you're right that this is a real protobuf bug, and is not an ABI issue after all. I agree that it looks like in this situation we are ending up calling `google::protobuf::internal::GetEmptyStringAlreadyInited()` without first initializing that string instance.

Here is slightly smaller version of the test case just for reference:

`test.proto`:
```
syntax = "proto2";
option optimize_for = LITE_RUNTIME;
option cc_enable_arenas = true;
message StringMessage {
  optional string s = 1;
}
```
`main.cc`:
```
#include <google/protobuf/arena.h>
#include "test.pb.h"

int main() {
  google::protobuf::Arena arena;
  StringMessage* m = google::protobuf::Arena::CreateMessage<StringMessage>(&arena);
  m->mutable_s();

  return 0;
}
```

**Comment by acozzette** [comment]
@gerben-s Do you happen to know what is going on here? It looks like the relevant generated code that would initialize the string instance is not being run because it is ifdef'd out:

Static initialization:
```
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
#endif  // GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
```
Arena constructor:
```
StringMessage::StringMessage(::google::protobuf::Arena* arena)
  : ::google::protobuf::MessageLite(),
  _internal_metadata_(arena) {
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  protobuf_test_2eproto::InitDefaults();
#endif  // GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:StringMessage)
}
```

**Comment by acozzette** [comment]
It seems to me like maybe the condition for the first one is inverted; we want to include that static initialization _unless_ the `_NO_STATIC_INITIALIZER` macro is defined, right?

**Comment by Abarrowman** [comment]
I'm running into the same problem. The test case @acozzette made segfaults when run after being compiled with g++ 4.9.4.

**Comment by acozzette** [comment]
Sorry about the delay on this, this slipped off my radar. I think the fix is just a simple matter of inverting that ifdef condition and so I'll try to test it and get that fix out soon.
