### ISSUE TITLE
not support for php7

### ISSUE THREAD

**Issue by yufeixuan** [google/protobuf#2840]
not support for php7

**Comment by 599259501** [comment]
I compiled the proto file into php file, then tried to run the php file, but always get following error:

PHP Fatal error: Class 'Google\Protobuf\Internal\Message' not found

**Comment by TeBoring** [comment]
Are you using c extension or php implementation?

**Comment by 599259501** [comment]
@TeBoring i have a protobuf.so in php extension

**Comment by TeBoring** [comment]
Currently, we don't support c extension for php7. Will support it in next
release.

**Comment by yufeixuan** [comment]
As soon as possible,thanks~

**Comment by 599259501** [comment]
thanks your answer
