### ISSUE TITLE
Cant generate swift proto 

### ISSUE THREAD

**Issue by Istiakmorsalin** [google/protobuf#2844]
I am not able to generate swift proto by trying this:
 
```
protoc --swift_out=. contact.proto

dyld: Library not loaded: @rpath/libswiftCore.dylib
  Referenced from: /usr/local/bin/protoc-gen-swift
  Reason: image not found
--swift_out: protoc-gen-swift: Plugin killed by signal 6.
```

But i have checked the directory and found protoc-gen-swift

**Comment by thomasvl** [comment]
This sounds like a problem with yoru install of `protoc-gen-swift`, it is unable to find the support library.  Did you copy the binary between machines so Xcode isn't installed/setup on this machine?

**Comment by Istiakmorsalin** [comment]
I tried to install protobuf-swift via   `brew install protobuf-swift` 
but it told me that it was already installed but not linked . 
So i did a complete uninstall of it via `brew uninstall protobuf-swift`  and after that reinstalling solved me the issue.

**Comment by mushtaque87** [comment]
I forced overwrite all file 

To force the link and overwrite all conflicting files:
  brew link --overwrite protobuf-swift 

and run the ./protoscript.sh again . It worked for me.
