### ISSUE TITLE
field naming issue for maps

### ISSUE THREAD

**Issue by bramthedev** [google/protobuf#2845]
Is it a convention that map names are in plural?
I have a map in my message that I want to call "input". But then there is a conflicting naming issue which is only a compile time error when the generated classes are compiled, not during building, because a variable "input" is already built by protobuf.
```
message Datapoint {

    map<string, string> context = 1;
    repeated Error errors = 2;
    map<string, string> endpoint = 3;
    map<string, string> meta = 4;
    repeated Detection detections = 5;
    map<string, string> input = 6;
}
```
Can someone maybe explain if there is anything I can do about this, keeping the map name?

If this is a wrong way to submit an issue, I would appreciate it if you'd tell me

**Comment by haberman** [comment]
What language are you compiling for?

Can you paste the compile error you are getting?

Also the version of protobuf you are using would be helpful to know.

**Comment by pherl** [comment]
We are closing open issues. Feel free to send PRs and reopen if you'd like to follow up on the issue.
