### ISSUE TITLE
Unable to build simple example in VS2015

### ISSUE THREAD

**Issue by aespielberg** [google/protobuf#2857]
(Crossposted to SO but I have reduced this to a very minimal example, so I'm not convinced this is not a bug.)

I built the protobuf library according to the instructions, using Visual Studio 2015 and cmake.  It passes all but 6 unit tests, so I figure the build itself should be fine.  Failed tests:

```
[  FAILED  ] 6 tests, listed below:
[  FAILED  ] BootstrapTest.GeneratedDescriptorMatches
[  FAILED  ] CsharpBootstrapTest.GeneratedCsharpDescriptorMatches
[  FAILED  ] RubyGeneratorTest.GeneratorTest
[  FAILED  ] TextFormatMapTest.Sorted
[  FAILED  ] TextFormatTest.Basic
[  FAILED  ] TextFormatExtensionsTest.Extensions
```
I'm using the latest version from master and running in VS2015.

I have created a .proto file as such:

```
syntax = "proto3";
package Networking; 

message Robot{

message KinematicLinkProto {
    string name = 1;
    float x_pos = 2;
    float y_pos = 3;
    float z_pos = 4;
    float roll = 5;
    float pitch = 6;
    float yaw = 7;
    float x_scale = 8;
    float y_scale = 9;
    float z_scale = 10;
}

repeated KinematicLinkProto links = 1;

}
```
I compile this, and try to add it to a project:

#include "Robot.pb.h"

```
int  main(int argc, char **argv)
{

    Networking::Robot robot_message;

    return 0;

}
```
My linker links the built libprotobuf.lib. I am building it as /MD and libprotobuf is built as /MD.  I am including the build Robot.pb.h file in the include directories.

For some reason, this simple program has the following two linker errors:

```
Error   LNK2019 unresolved external symbol "private: static bool google::protobuf::io::CodedOutputStream::default_serialization_deterministic_" (?default_serialization_deterministic_@CodedOutputStream@io@protobuf@google@@0_NA) referenced in function "public: virtual unsigned char * __cdecl Networking::Robot::SerializeWithCachedSizesToArray(unsigned char *)const " (?SerializeWithCachedSizesToArray@Robot@Networking@@UEBAPEAEPEAE@Z)   


Error   LNK2019 unresolved external symbol "class google::protobuf::internal::ExplicitlyConstructed<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > > google::protobuf::internal::fixed_address_empty_string" (?fixed_address_empty_string@internal@protobuf@google@@3V?$ExplicitlyConstructed@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@123@A) referenced in function "protected: void __cdecl google::protobuf::internal::RepeatedPtrFieldBase::Clear<class google::protobuf::RepeatedPtrField<class Networking::Robot_KinematicLinkProto>::TypeHandler>(void)" (??$Clear@VTypeHandler@?$RepeatedPtrField@VRobot_KinematicLinkProto@Networking@@@protobuf@google@@@RepeatedPtrFieldBase@internal@protobuf@google@@IEAAXXZ)   
```

Did I make an error somewhere, or is this a bug?

**Comment by aespielberg** [comment]
Note: A colleague compiled proto 3001000.  This version _does_ seem to work.  I'm curious as to what about 3002000 breaks everything.

**Comment by PhoebeHui** [comment]
Build Google_protobuf by Visual Studio 2015 update3 on Windows:
I see the following 5 test failed for a long time.
BootstrapTest.GeneratedDescriptorMatches
RubyGeneratorTest.GeneratorTest:RubyGeneratorTest.GeneratorTest
TextFormatTest.Basic
TextFormatExtensionsTest.Extensions
TextFormatMapTest.Sorted

Yesterday the below test passed on revision '43f2db7', but today it failed, might due to latest changes.
CsharpBootstrapTest.GeneratedCsharpDescriptorMatches

**Comment by aespielberg** [comment]
I should note that I'm not worried about a few tests failing - I assume that's normal.  My point was only 6 tests failed out of 1940 or something.  My point was more that I can't use the built protos.

**Comment by acozzette** [comment]
@aespielberg The problem might be that you are using a `Robot.pb.h` and `Robot.pb.cc` built from an older version of `protoc` and trying to link that against a newer version of the protobuf runtime library. Could you try rebuilding your generated code (`Robot.pb.*`) and see if that fixes the problem? For C++ we can't guarantee that the code will work properly unless the `protoc` version used to generate the code matches the version of the runtime library.

**Comment by weighzou** [comment]
the same problem

**Comment by myklory** [comment]
@weighzou Hi, I want know if you solved this problem?

**Comment by myklory** [comment]
@weighzou  just use micro PROTOBUF_USE_DLLS

**Comment by Vigerus** [comment]
@myklory Thank you so much! :)

**Comment by kidd9thu** [comment]
@myklory  Thank you！It did work.
