### ISSUE TITLE
protobuf\csharp\src\Google.Protobuf.JsonDump\Google.Protobuf.JsonDump.xproj : error  : Can't find imported proyect

### ISSUE THREAD

**Issue by Obsdark** [google/protobuf#2862]
That's the thing, the example doesn't come with the .xproj files so it cannot be loadead and worked on VS, is this intended and i'm doing it wrong or this is an issue?

Before you ask, yeah, i download it and try it.

If it is intended, please show me where i can download and try the example who actualy works, if is not...
Can you tell me if this protobuf will work with Xamarin Android?

And can you tell me what i'm doing wrong? (even if is really noobish i apreciate that)

This is the page of the code in the github who have the problem:
https://github.com/google/protobuf/tree/master/csharp/src/AddressBook

Thanks in advance

**Comment by pherl** [comment]
Do you still have the issue? We are closing open issues. Feel free to send PRs and reopen if you'd like to follow up on the issue.
