### ISSUE TITLE
JsonPrintOptions : option to always print optional fields that are set (regardless of value)

### ISSUE THREAD

**Issue by timotheecour** [google/protobuf#2871]
JsonPrintOptions has always_print_primitive_fields which, when false, will skip fields set to default value (even if these fields are optional and set to the default value).

Could we have another option in JsonPrintOptions:`print_optional_fields_when_set` which will only print optional fields when they're set (regarless what value they're set to)

This would be most useful to have a closer 1:1 relationship between what's in json and what's in the protobuf.

FYI @mojoBrendan  since you've implemented https://github.com/google/protobuf/pull/2867

implementation: I would imagine this would use proto reflection, eg: `HasField` in https://developers.google.com/protocol-buffers/docs/reference/cpp/google.protobuf.message

NOTE: always_print_primitive_fields is different from print_optional_fields_when_set, see:
http://stackoverflow.com/questions/9168052/how-do-has-field-methods-relate-to-default-values-in-protobuf

**Comment by xfxyjwf** [comment]
Are you using proto2 or proto3 syntax? If proto3, what you observed is the correct behavior because proto3 doesn't keep field presence and can't distinguish between unset fields and fields set to default value. However, if you are using proto2, the JSON conversion library should already do what you suggested, i.e., print fields that are set (even it's set to the default value). If that's not the case, I think we have a bug to fix in protobuf library.

**Comment by timotheecour** [comment]
I'm using proto2 here.

> However, if you are using proto2, the JSON conversion library should already do what you suggested, i.e., print fields that are set (even it's set to the default value)

Very confused because the docs for `always_print_primitive_fields` seems to say otherwise:

https://github.com/google/protobuf/blob/master/src/google/protobuf/util/json_util.h
```
  // Whether to always print primitive fields. By default primitive fields with
  // default values will be omitted in JSON joutput. For example, an int32 field
  // set to 0 will be omitted. Set this flag to true will override the default
  // behavior and print primitive fields regardless of their values.
  bool always_print_primitive_fields;
```

what I want is a field that controls whether or not to print a field depending on whether they're set or not (regardless of their value). 

* always_print_primitive_fields=true will print all optional fields even ones that are unset
* always_print_primitive_fields=false (the default) will not print an int32 field set to 0, according to doc above. In contrast, `print_optional_fields_when_set=true` should print that field if it's set (even to 0 or whatever the default value is for that field)

**Comment by xfxyjwf** [comment]
The doc about always_print_primitive_fields is for proto3 specifically (and it should be fixed/updated for proto2). Actually the whole JSON conversion library is designed for proto3, but it should also work reasonably for proto2 types. You should not need to set any option to get the behavior you want. Please give it a try and report back if it doesn't work as I suggested here.

**Comment by timotheecour** [comment]
indeed, works as you descibed; so the only thing to do is update the docs (before closing this bug)

**Comment by xfxyjwf** [comment]
@timotheecour Thanks for confirming. I created another issue to update the doc:
https://github.com/google/protobuf/issues/2880
