### ISSUE TITLE
Use *.proto as input file

### ISSUE THREAD

**Issue by coderwj** [google/protobuf#2872]
Why can I use *.proto as input file in protoc-3.2.0-win32.zip you providing, but when I clone the code to build, use *.proto, the error :Invalid argument?

**Comment by coderwj** [comment]
On window, use protoc.exe

**Comment by MartinDong** [comment]
I met the same problem, can you tell me you solved?

**Comment by pherl** [comment]
What errors are you seeing when using the protoc-3.2.0-win32.zip in windows?

**Comment by pherl** [comment]
We are closing open issues. Feel free to send PRs and reopen if you'd like to follow up on the issue.

**Comment by catalpeak** [comment]
We meet the same one, plz . Are there any Solutions?
