### ISSUE TITLE
protobuf 3.2 memory leak  with visual studio 2013

### ISSUE THREAD

**Issue by wjx0912** [google/protobuf#2874]
my compile parameter:
cmake -G "NMake Makefiles" -Dprotobuf_BUILD_TESTS=OFF -DCMAKE_BUILD_TYPE=Debug   -DCMAKE_INSTALL_PREFIX=../../../../install   -Dprotobuf_BUILD_SHARED_LIBS=ON   ../..
nmake

when use, i add define PROTOBUF_USE_DLLS, and add example addressbook .h/cpp generate from:
protoc.exe ./addressbook.proto --cpp_out=./

it's a bug or my usage problem?thanks

**Comment by pherl** [comment]
Can you attach the memory leak report and a simple instruction on how to reproduce them?
