### ISSUE TITLE
API/ABI changes review for protobuf

### ISSUE THREAD

**Issue by lvc** [google/protobuf#2875]
The review of API/ABI changes for protobuf since 2.2.0 version: https://abi-laboratory.pro/tracker/timeline/protobuf/

The report is updated 3 times a week. Hope it will be helpful for users and maintainers of the library.

Created with the help of abi-tracker tool: https://github.com/lvc/abi-tracker

Thank you.

![protobuf-1](https://cloud.githubusercontent.com/assets/1517837/24090144/2098458c-0d57-11e7-9cce-1df3134283e0.png)

![protobuf-2](https://cloud.githubusercontent.com/assets/1517837/24090164/37b324f8-0d57-11e7-82d4-d46f00795b99.png)

**Comment by acozzette** [comment]
Thanks for setting this up, that is pretty cool. We don't currently try to maintain ABI compatibility for C++, and instead rely on users to rebuild their code when upgrading, but it's still interesting to see this analysis.
