### ISSUE TITLE
Generated classes additional attributes.

### ISSUE THREAD

**Issue by alexpantyukhin** [google/protobuf#2876]
Hi.
Is there possibility to add some methods to generated class?
In C# implementation protoc makes partial classes and we can determinate addtitional methods, fields in separated file.
Is there some best practice way to do it with python?

The first approach was to inherit generated class, but there: https://developers.google.com/protocol-buffers/docs/reference/python-generated there is told that 'Generated classes are not designed for subclassing and may lead to "fragile base class" problems'

Best, Alex.

**Comment by alexpantyukhin** [comment]
Actually monkey patching in the `__init__` of the module would be suitable I believe. But I'm not sure that behavior of proto generated class will not be borken in this case.

**Comment by alexpantyukhin** [comment]
@anandolee @pherl Is there something new about this issue?

**Comment by pherl** [comment]
Any detailed ideas about what methods you would like to add? It would be great if you could put up a doc showing the use cases and potentially proposed APIs.

**Comment by alexpantyukhin** [comment]
@pherl Actually I would like to have somnething like this:
```
message Point {
  string address = 1;
  string id = 2;
}
```

after that in python I woud like to add the method (somehow) for example to_string(self).. and call it from python code:
```python
p = Point(address = "127.0.0.1", id=10)
print(p.to_string())
```
