### ISSUE TITLE
something wrong while I'm installing

### ISSUE THREAD

**Issue by zxc80932** [google/protobuf#2878]
![default](https://cloud.githubusercontent.com/assets/26457352/24099607/36561706-0dab-11e7-8b05-c7648b601283.PNG)
![make](https://cloud.githubusercontent.com/assets/26457352/24099609/365779c0-0dab-11e7-94fb-d7d087ec6793.PNG)
![make check](https://cloud.githubusercontent.com/assets/26457352/24099608/36571020-0dab-11e7-8820-7025387c7413.PNG)

I followed the instruction to install ,but every time when I do the "make check" instruction,it always went wrong.
I had change the path  for ./configue ,but still got the same wrong.And weirdly,the error line in that script was marked down.

**Comment by acozzette** [comment]
2.5.0 is a fairly old version at this point; could you try with a newer version just to see if that fixes it?

**Comment by zxc80932** [comment]
@acozzette but I need this version to install my R package.
![rhipe](https://cloud.githubusercontent.com/assets/26457352/24129774/c21e3cfe-0e1f-11e7-8303-2fb64c6fe4f2.PNG)

**Comment by acozzette** [comment]
Ah, ok. Have you verified that those two scripts are executable? Could you try running them directly from within the `src/` directory, e.g. `./google/protobuf/compiler/zip_output_unittest.sh`?

**Comment by zxc80932** [comment]
yes. Both files can run
so i can't figure out why is permission denied
