### ISSUE TITLE
cant find  sun.misc.unsafe 

### ISSUE THREAD

**Issue by iwantthink** [google/protobuf#2888]
developing the Android project by using java code 3.2.0
put the source code directly into my Android project  .not jar
in class UnsafeUtil , cannot resolve symbol 'unsafe'
sorry for my bad english....

**Comment by iwantthink** [comment]
java

**Comment by haberman** [comment]
Can you expand this bug report. What version of protobuf were you using, what command were you trying to run, what error message did you get?

**Comment by jrsen** [comment]
I have same problem. My protoc command version is 3.3.0 and  jre version is 1.8. Please help me.  Thanks!

**Comment by xfxyjwf** [comment]
If you are using Java on Android, you need to use the Java lite version. Try:
http://search.maven.org/#search%7Cga%7C1%7Ca%3A%22protobuf-lite%22

with this plugin:
http://search.maven.org/#search%7Cga%7C1%7Ca%3A%22protoc-gen-javalite%22

Instead of "--java_out", use "--java_lite_out".

**Comment by Dimon94** [comment]
Version:
com.google.protobuf:protobuf-lite:3.0.1
```
plugins {
        javalite {
            // The codegen for lite comes as a separate artifact
            artifact = 'com.google.protobuf:protoc-gen-javalite:3.0.0'
        }
    }
```
Log:
Could not find method sun.misc.Unsafe.copyMemory, referenced from method com.google.protobuf.UnsafeUtil.copyMemory
VFY: unable to resolve virtual method 65333: Lsun/misc/Unsafe;.copyMemory (JJJ)V
Could not find method sun.misc.Unsafe.getByte, referenced from method com.google.protobuf.UnsafeUtil.getByte
VFY: unable to resolve virtual method 65335: Lsun/misc/Unsafe;.getByte (J)B
