### ISSUE TITLE
Distribute well-known types protos in release packages.

### ISSUE THREAD

**Issue by xfxyjwf** [google/protobuf#289]
Well-known types (e.g., any.proto) is part of protobuf library and will be referenced in users' .proto files. We need to distribute them along with protobuf runtime and protoc.
1. The binary package for protoc will include well-known type protos (e.g., protoc-3.0.0-alpha-3-win32.zip).
2. "make install" will install these .proto files along with proto header files. protoc will find the right import path for them without requiring users to specify it.
3. The release package for each language may also have these protos included. For example, the .jar files we publish to Maven will include them.
4. Plugins we provide/support (Maven plugin, Gradle plugin, IDE plugin, etc.) should better support them as well (e.g., be able to recognize an import of "google/protobuf/any.proto" without requiring users to put the source in a certain location).

Besides well-known types, google/protobuf/descriptor.proto will also in included.

**Comment by xfxyjwf** [comment]
#2 is done. #3 is done for Java. Moving this issue out of alpha-3 milestone and file individual issues instead.

**Comment by peter-edge** [comment]
https://github.com/golang/protobuf/issues/50

**Comment by xfxyjwf** [comment]
This should be working now for most languages. There are separate tracking issues for a specific language. Closing this one.
