### ISSUE TITLE
Windows: long paths are not supported

### ISSUE THREAD

**Issue by laszlocsomor** [google/protobuf#2891]
See https://github.com/bazelbuild/bazel/issues/2634.

If the absolute path of an output file is longer than 259 characters, `open(2)` fails on Windows. I have a fix for this.

**Comment by laszlocsomor** [comment]
I accidentally closed this (by having a "Fixes" line in my commit message) but it's not fixed here (in upstream), only in Bazel's repo (https://github.com/bazelbuild/bazel/issues/2634).

**Comment by xfxyjwf** [comment]
@laszlocsomor Feel free to send us a pull request.
