### ISSUE TITLE
Who should own this nuget package - https://www.nuget.org/packages/protobuf-vc110/

### ISSUE THREAD

**Issue by karann-msft** [google/protobuf#2892]
We have a nuget package on nuget.org [Protocol Buffers v110 ](https://www.nuget.org/packages/protobuf-vc110/ )

We have received a request for transfer of ownership. Before, I act on the request, can one of the admins here confirm who should ideally own this package.

Thanks.
Karan
NuGet Team

**Comment by xfxyjwf** [comment]
Hi Karan,

Thanks for contacting us. Right now we are deploying protobuf nuget packages under the name "Google.Protobuf":
https://www.nuget.org/packages/Google.Protobuf/

For the Protocol Buffers v11 package you pointed to, I don't know what it's used for. At the moment we protobuf team probably don't have the time or interest in owning/maintaining that package. @jskeet @anandolee

**Comment by jskeet** [comment]
It looks like the package is a very old (2014) version of the native libraries. I don't know anything about its current owner. I doubt that it's a terribly useful package one way or the other, to be honest...

**Comment by karann-msft** [comment]
Cool. I just wanted to check if someone here would like to own the package since it has a very similar name to your official package and might cause confusion for your customers.  If not, please feel free to close the issue. Thanks.
