### ISSUE TITLE
Bad copy initialization in TF .so file

### ISSUE THREAD

**Issue by DavidNorman** [google/protobuf#2894]
I have an error that I don't understand, which is caused by a protobuf structure not copying correctly.

I have written a Tensorflow plugin.  It is compiled into a .so file, and is loaded into the process by python, after the main tensorflow wrapped .so file.

The error is:
```
2017-03-22 11:44:49.534664: F tensorflow/core/common_runtime/device.cc:31] Check failed: DeviceNameUtils::ParseFullName(name(), &parsed_name_) Invalid device name: N10tensorflow3VarE
```

```
Device::Device(Env* env, const DeviceAttributes& device_attributes,
               Allocator* device_allocator)
    : DeviceBase(env), device_attributes_(device_attributes) {
  LOG(INFO) << "incoming: " << device_attributes.name();
  LOG(INFO) << "copied: " << device_attributes_.name();
  CHECK(DeviceNameUtils::ParseFullName(name(), &parsed_name_))
    << "Invalid device name: " << name();
  rmgr_ = new ResourceMgr(parsed_name_.job);
}
```

DeviceAttributes is a protobuf structure.

I have added some trace, and can see that the value of the name field in the referenced DeviceAttributes is ok (it should be an empty string).  However, once the DeviceAttributes are copied into the device's member, the value is wrong.  N10tensorflow3VarE is part of one of the symbols in the symbol table, but it is neither first, nor the full name of the symbol. The referenced parameter is constructed on the stack in the parameters of the constructor chain a couple of children up.

The device is not constructed during static initialization.
Nevertheless, there is a fair bit of static initialization in the .so file.
It does not always fail.  Only when a Tensorflow Variable is added to the graph, and only within the unit test framework.
I am statically linking protobuf-lite into my .so file, although the same problem occurs if I use protobuf headers only and dynamically link to the protobuf symbols in the main tensorflow.so.
If I fiddle with the code so that the protobuf copy fail isn't important, then the problem appears elsewhere.  It is a general problem with copying protobufs.

I have read a few reports and issues about static initialization not playing well with multiple dynamic libraries.  Am I fighting a losing battle trying to get this to work?

```
2017-03-22 11:44:49.534641: I tensorflow/core/common_runtime/device.cc:29] incoming: 
2017-03-22 11:44:49.534656: I tensorflow/core/common_runtime/device.cc:30] copied: N10tensorflow3VarE
```

**Comment by haberman** [comment]
Can you isolate this issue to a series of calls to protobuf APIs only? It's a little hard to tease your problem report apart from the TensorFlow and application code.
