### ISSUE TITLE
php:  Class 'GPBMetadata\Google\Protobuf\Descriptor' not found

### ISSUE THREAD

**Issue by flisky** [google/protobuf#2901]
Please refer to grpc/grpc#10217.

Ｗhen generated `google/api/annotations.proto`, it calls `\GPBMetadata\Google\Protobuf\Descriptor::initOnce();`.
However, there is only class `GPBMetadata\Google\Protobuf\Internal\Descriptor`.

cc @stanley-cheung

**Comment by TeBoring** [comment]
Sorry, we don't support well known types yet. This is a known issue.

**Comment by flisky** [comment]
Then closed as a part of #1936

**Comment by TeBoring** [comment]
This still needs to be fixed in 3.3 release. If user just import well known type, it should be a valid case. @flisky could you help send a fix?

**Comment by flisky** [comment]
Yes, I'm glad to.

It seems we need a special case when importing `Descriptor` message.
Is that okay? Could you give me some hints on this?
