### ISSUE TITLE
JsonStringToMessage very slow 

### ISSUE THREAD

**Issue by hzhxxx** [google/protobuf#2902]
call 
success = JsonStringToMessage(json,message, options).ok();

std::string json = Json String,include 60000 AddressBook,
The Json length is 8209320~=8M,

JsonStringToMessage time:14848,14 sesonds

**Comment by hzhxxx** [comment]
g++ -g test.cpp proto.cpp addressbook.pb.cc -lprotobuf -lz -std=gnu++11 -o proto -Wl,-rpath,/usr/local/lib -I/usr/local/include/

centos 7.2 1511
gcc --version
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-11)

gettimeofday(&tv2,0);
if(flag_.test(PROTO_ZIP_INDXE))
 {
     success = unzip(json);		  
     times = ((tv2.tv_sec  - tv1.tv_sec) * 1000000 + (tv2.tv_usec - tv1.tv_usec))/1000;
    std::cout<<"3 CProtobufPacket::unzip time:"<<times<<endl;
 }
 success = JsonStringToMessage(json,message, options).ok();
gettimeofday(&tv1,0);  
times = ((tv1.tv_sec  - tv2.tv_sec) * 1000000 + (tv1.tv_usec - tv2.tv_usec))/1000;
 std::cout<<"4 CProtobufPacket::JsonStringToMessage time:"<<times<<endl;

**Comment by xfxyjwf** [comment]
What version of protobuf library are you using? Can you try the head version?

**Comment by hzhxxx** [comment]
protoc --version
libprotoc 3.2.0

**Comment by hzhxxx** [comment]
https://github.com/hzhxxx/protobufpacket/blob/master/test.cpp,test code

**Comment by na-ka-na** [comment]
I think this might be same as https://github.com/google/protobuf/issues/2305. @xfxyjwf any idea when the next version of protobuf library 3.3 will be released?

**Comment by xfxyjwf** [comment]
I believe this issue is fixed.
