### ISSUE TITLE
ambiguous unqualified symbols from std namespace

### ISSUE THREAD

**Issue by ardatur** [google/protobuf#2904]
Issue #1136 has been closed without resolution with the offer to reopen. Since I cannot reopen, here is the duplicate.

[Protobuf 3.2.0, MSVC 2015.3]

Unqualified "string" usage in header files causes conflicts with string classes from other, unrelated, namespaces (line numbers are from Protobuf 3.0.0-beta-2, they may be different now):

> ...\protobuf\src\google\protobuf\map_entry_lite.h(123): error C2872: 'string': ambiguous symbol
> ...\protobuf\src\google\protobuf\map_type_handler.h(625): error C2872: 'string': ambiguous symbol

Changing "string" to "::std::string" in relevant locations fixed that particular compilation issue, although there appear to be more similar "string" usage instances.

**Comment by xfxyjwf** [comment]
We can't change string to std::string because our google internal code base cannot use std::string. If you have the issue, it's likely you have some code somewhere importing a different string into the global namespace. Please fix that code instead (just don't import a string class into global namespace).

**Comment by ardatur** [comment]
@xfxyjwf Please clarify: does this mean that that "string" is supposed to refer to std::string for external users and to something very different when used in your internal code base? Shouldn't this be properly handled by an appropriate #if + typedef or something similar, then?

**Comment by xfxyjwf** [comment]
@ardatur Yes, you are right. "string" refers to some other type in our internal code base. There is ongoing effort to make it std::string though. I'm not sure what you mean by "#if + typedef" handling. Note that the string type is not defined by protobuf, but is part of the base library every Google code uses (e.g., #include <string> will include that special string). There is no way we can change it specifically for protobuf.

**Comment by ardatur** [comment]
@xfxyjwf The "#if+typedef" part was about explicitly assigning the correct type with
```
#if THIS_IS_THE_INTERNAL_CODEBASE
typedef ... proto_string;
#else
#include <string>
typedef std::string proto_string;
#endif
```
or its functional equivalent (and then using `proto_string` instead of `string`, of course).

As it is now, the open-ended/"uninitialized" type identifier used in those places leaves things to chance: with luck, it will point to the correct type, or otherwise it will start summoning typesystem-level nasal demons just like conventional uninitialized variables do (which is exactly what happened in this issue report). Surely this is an actual valid issue that deserves to be fixed.

I would also like to point out that "std::string" is used all over the place in protobuf, so the special treatment of the two lines in question sounds quite inconsistent from the outside point of view (it might make sense from the internal codebase' point of view, but we're talking about a project published specifically to be used be a wider audience).

**Comment by xfxyjwf** [comment]
What you are proposing has a cost: everyone who touches protobuf code must use proto_string rather than the standard string type. I don't see it as a worthwhile investment given how many people touches protobuf code everyday and how few people actually pulling another string type into global namespace.

If you think it's common for users to pull a certain non-standard string type into global namespace, let me know what project defines that string type so we can better understand the tradeoff here. For example, if the other string type is from grpc, we certainly want to fix it one way or another.

**Comment by ardatur** [comment]
> everyone who touches protobuf code must use proto_string rather than the standard string type

Not at all. I am introducing a type alias, not a new type. From the user code's point of view, the actual types will be exactly the same as they are / should be now: your internal strings for the internal codebase, std::string for everyone else. If you are worried about introducing type aliases, just wrap the types in a slightly different fashion:
```
#if THIS_IS_THE_INTERNAL_CODEBASE
#define INTERNAL_OR_EXTERNAL_STRING google::string
#else
#include <string>
#define INTERNAL_OR_EXTERNAL_STRING std::string
#endif
```
and use `INTERNAL_OR_EXTERNAL_STRING` precisely in those places within protobuf that require different types for different codebases.

The point of my proposal isn't the specific implementation, but rather the idea that if we want to employ different types in different usage contexts (internal/external), then we should do just that—explicitly!—instead of hoping that a compiler will be capable of resolving just the "string" the way we want.

> If you think it's common for users to pull a certain non-standard string type into global namespace

I can agree that such pulling is a contentious issue. According to protobuf itself (stubs/common.h):

3.2.0:
```
using namespace std;  // Don't do this at home, kids. 
```
3.5.0:
```
// TODO(acozzette): remove these using statements
...
using std::string; 
```
These snippets are not in the global namespace, but they are clearly considered an issue by protobuf developers. And they are directly related to the problem at hand, aren't they?

> if the other string type is from grpc, we certainly want to fix it one way or another

It is not a Google project, but thank you.
