### ISSUE TITLE
Packed repeated fields cannot be read as non-repeated fields in C++

### ISSUE THREAD

**Issue by grandseiken** [google/protobuf#2905]
I'm not 100% sure this is a bug, but the documentation isn't explicit about what is supposed to happen. According to the [encoding documentation](https://developers.google.com/protocol-buffers/docs/encoding#optional),

> Normally, an encoded message would never have more than one instance of a non-repeated field. However, parsers are expected to handle the case in which they do. For numeric types and strings, if the same field appears multiple times, the parser accepts the last value it sees.

An obvious consequence of this is that one can backwards-compatibly replace a `repeated` field with a non-`repeated` field, and still access old field data if e.g. the encoded data happens to just contain one element anyway.

However, this doesn't work for packed-encoded repeated fields (at least in C++) - the parser for the non-`repeated` field will ignore the length-delimited wire type entirely.

Again, I'm not sure if this is a bug; perhaps I'm misunderstanding and the intention was only to support merging of multiple messages rather than replacing `repeated` fields by non-`repeated` ones. But the documentation for packed repeated fields seems to suggest it's intended to affect encoding only rather than visible semantics, and the behaviour in the non-packed case is clearly useful.

Test case:

```
// test.proto
syntax = "proto3";
package test;

message Packed {
  repeated int32 a = 1;
}

message Optional {
  int32 a = 1;
}
```

```
// test.cc
#include "test.pb.h"
#include <gtest/gtest.h>
#include <string>

TEST(Test, PackedAsOptional) {
  test::Packed packed;
  packed.add_a(1);
  
  std::string buffer;
  packed.SerializeToString(&buffer);
  
  test::Optional optional;
  optional.ParseFromString(buffer);
  EXPECT_EQ(1, optional.a_size()); // Actual: 0
}
```

**Comment by xfxyjwf** [comment]
Singular field is compatible with non-packed repeated field and non-packed repeated field is compatible with packed repeated field, however, just as you have observed, singular field is not compatible with packed repeated field.

We are concerning that fixing this would have a significant impact on the parsing performance of singular fields and for this reason there is no plan to fix it at the moment.

**Comment by grandseiken** [comment]
OK, thank you for the clarification. It might be helpful if this was made clear in the docs.
