### ISSUE TITLE
JavaScript  -uint64 deserializeBinary bug

### ISSUE THREAD

**Issue by 15951836388** [google/protobuf#2908]
in the JavaScript
a uint64 number 136009802164731904  deserializeBinary  =》136009802164731900   
this is Unequal

**Comment by 15951836388** [comment]
message FeedAsk
{
	uint64 index= 1;
	int32 idItem = 2;
}

        const dd = 136009802164731904
        const message =new game_pb.FeedAsk()
        message.setIndex(dd)
        const bytes = message.serializeBinary()
        const ms = game_pb.FeedAsk.deserializeBinary(bytes)
        const dd2=ms.getIndex()
        cc.log("dd2=", dd2)

**Comment by updogliu** [comment]
Javascript's number is essentially double, which cannot represent an int larger than 2^53 precisely.

Try this
```
const dd = 136009802164731904;
const dd2 = dd;
console.log("dd2=", dd2);
```

**Comment by updogliu** [comment]
This issue is tracking the request of precision preserving representation of int64 fields.
https://github.com/google/protobuf/pull/2214
