### ISSUE TITLE
xcode 8.3 error

### ISSUE THREAD

**Issue by DylanDu123** [google/protobuf#2916]
array parameter ismissing a nullabillty type specifler (_Nonnul,_Nullable,or _null_unspecifled)

**Comment by saldous** [comment]
Same, I'm seeing 238 of these issues with Protobuf since upgrading to Xcode 8.3.

**Comment by awuu** [comment]
#2626

**Comment by awuu** [comment]
Non-portable path to file '<protobuf/Any.pbobjc.h>'; specified path differs in case from file name on disk

**Comment by mikestalker** [comment]
Yep. Same situation.

**Comment by terflogag** [comment]
Same situation 👍

**Comment by alexdd55** [comment]
same here 👍

**Comment by thomasvl** [comment]
This is a duplicate of #2625.  It's already fixed on `master` and the fix has been pulled to the 3.2.x branch.  @TeBoring is cutting a 3.2.1 release soon so folks can use that to pull it.

**Comment by saldous** [comment]
Thanks, I didn't add Protobuf to my podfile, another google pod I use must be pulling it automatically, so I don't know how to force it to pull from master (either Firebase or AdMod must be pulling it)

**Comment by mikestalker** [comment]
@thomasvl i have the same situation as @saldous . So how we can get rid of this warnings?

**Comment by iValkou** [comment]
@thomasvl The same issue

**Comment by SebastianKumor** [comment]
i had the same issue, the pod was pulled with firebase, add this to your podfile `pod 'Protobuf', :git => 'https://github.com/google/protobuf.git'` and run pod install, it solved my problem with the warnings.

**Comment by saldous** [comment]
@SebastianKumor thanks! 👍
