### ISSUE TITLE
C# code generator - no support for services

### ISSUE THREAD

**Issue by jlindrud** [google/protobuf#2917]
I noticed when running protoc to generate C# code, that service definitions are ignored. In fact this is mentioned in the [reference documentation](https://developers.google.com/protocol-buffers/docs/reference/csharp-generated):

_The C# code generator ignores services entirely._

Are there plans to implement service definitions in C#? The original protobuf-csharp-port project had support for this, and we have code that relies on it.

**Comment by pherl** [comment]
We rely on RPC libraries to implement services via plugins. For example, https://github.com/grpc/grpc/tree/master/src/csharp
