### ISSUE TITLE
Incorrect exception thrown from CodedOutputByteBufferNano

### ISSUE THREAD

**Issue by charlesmunger** [google/protobuf#292]
When a MessageNano containing a String is serialized into a buffer that is too small to contain it, and the buffer's boundary happens to be where the string field's length delimiting varint is serialized, and the string's length and 3*length have the same length when encoded as a varint, an IllegalArgumentException is thrown rather than an OutOfSpaceException. I have a patch and regression test ready to fix this. Do I submit them in AOSP or here?

**Comment by xfxyjwf** [comment]
Please submit the change here. In the future we'll make the nano code in AOSP a downstream and all changes should be made here and pushed to AOSP.

**Comment by brianduff** [comment]
Until the downstreaming happens, we'll continue to accept patches in AOSP and push them to google3. It doesn't seem reasonable to block fixes on the pushing being set up.

**Comment by brianduff** [comment]
AOSP fix in https://android-review.googlesource.com/#/c/145211/

**Comment by brianduff** [comment]
The fix is included in this pull request:
https://github.com/google/protobuf/pull/315
