### ISSUE TITLE
use_fast_cpp_protos breaks pythonic reload()

### ISSUE THREAD

**Issue by fischman** [google/protobuf#2920]
Python's [reload()](http://pydoc-zh.readthedocs.io/en/latest/library/functions.html#reload) is useful for reloading modules that are edited after already being imported into the runtime, to support iterative/experimental working styles.
protobuf's use_fast_cpp_protos breaks this use-case with an error like:
```
TypeError: Couldn't build proto file into descriptor pool! 
Invalid proto descriptor for file "<FILE>.proto": 
<FILE>.proto: A file with this name is already in the pool.
```

It would be great if DescriptorPool knew how to reload().

One twist is that extant messages of the type being reloaded will have a different type to that of new messages created after the reload, but that's something that's true of vanilla python's use of reload() as well.  Hopefully the perfect doesn't have to be the enemy of the good here.

**Comment by xfxyjwf** [comment]
There might be no way to solve this problem, i.e., there is no way to unload registered types in C++ descriptor pool. C++ runtime maintains several globals (descriptor pool, descriptor database, extension registry, etc.). These globals need to be kept in a consistent state (or you will get random crashes) and none of them supports unloading. Only addition is supported at the moment. Although theoretically it's possible to make every component support unloading, in practice it might be too hard to refactor the existing code base to do so.

**Comment by fischman** [comment]
@xfxyjwf: thanks for the answer and sorry for this slow reply (your answer went to a spam folder :/).
Can we take advantage of the indirection between the Python and C++ layers to lie to the C++ side about the identity of a reloaded type on the python side?  In other words pass it a generated, unique, name and maintain the mapping between python and C++ names in the python side.

**Comment by anandolee** [comment]
Have added warnings for duplicate register a few month ago. We can't reject duplicated register which will break a lot current projects. Thus we choose to raise warnings

**Comment by fischman** [comment]
@anandolee: the behavior that prompted me to file this bug has been the case for many years. Are you saying that a "few months ago" the behavior was changed to execute the reload and issue a warning?
(do you have pointers to CLs or bugs that might tell me more?)
Thanks for following up!

**Comment by fhho** [comment]
I don't think this has been changed yet. I just ran into this issue today, with the same original error @fischman reported.
