### ISSUE TITLE
DynamicMessageFactory for java

### ISSUE THREAD

**Issue by biran0079** [google/protobuf#2929]
I noticed that C++ proto has a `DynamicMessageFactory` class that can create proto message from descriptor.
Can we have similar class in java?

**Comment by acozzette** [comment]
Yes, Java has a DynamicMessage class as well: https://github.com/google/protobuf/blob/cc3fa2ec80d196e045ae05797799f079188106f3/java/core/src/main/java/com/google/protobuf/DynamicMessage.java#L50 You can use the various static methods on it to create a proto message for a given descriptor.
