### ISSUE TITLE
Upload 3.0.0-alpha-2 to PyPI

### ISSUE THREAD

**Issue by attilaolah** [google/protobuf#293]
Please upload 3.0.0-alpha-2 to PiPI. [3.0.0-alpha-1] doesn't work with the `_pb2.py` files generated by the latest `protoc` (missing `syntax` keyword arg to `google.protobuf.descriptor.Descriptor.__{new,init}__`).

[3.0.0-alpha-1]: //pypi.python.org/pypi/protobuf/3.0.0-alpha-1

**Comment by 0xC0FFEE** [comment]
I second that. Thanks in advance.

**Comment by underyx** [comment]
Seems like this can be closed: https://pypi.python.org/pypi/protobuf/3.0.0-alpha-2

**Comment by attilaolah** [comment]
Yep, closing, thanks for the ping @underyx.
