### ISSUE TITLE
Oneof creates syntacical incorrect java code for different camelcases of types.

### ISSUE THREAD

**Issue by oflebbe** [google/protobuf#2931]
The attached code creates incorrect java code:

`U.java:471: error: method clearTimeDelta() is already defined in class Builder
      public Builder clearTimeDelta() {
                     ^
1 error
`

[u.proto.txt](https://github.com/google/protobuf/files/889564/u.proto.txt)

Version protobuf-3.2.0

**Comment by oflebbe** [comment]
Even differentiation by underscore does not help (But this was unsurprising)
[u2.proto.txt](https://github.com/google/protobuf/files/889750/u2.proto.txt)

**Comment by acozzette** [comment]
@oflebbe Thank you for reporting this, but I believe this is actually working as intended. Our [style guide](https://developers.google.com/protocol-buffers/docs/style) recommends making field names all lowercase and separated by underscores (e.g. my_field_name), and going with this style ensures that you can't end up with different field names producing symbols that collide in the generated code.
