### ISSUE TITLE
Serialized Binary string generated using C++ can't be deserialized in Javascript

### ISSUE THREAD

**Issue by rodiers** [google/protobuf#2932]
I'm using google protobuf 3.2.0 and have a proto-file for which I generated C++ and Javascript code. 

A binary string is created using the generated C++ SerializeToString member function 
`bool SerializeToString(string* output) const; // serializes the message and stores the bytes in the given string. Note that the bytes are binary, not text; we only use the string class as a convenient container. `
and sent over HTTP in binary form as "application/octet-stream".
On Javascript side we receive the string and deserialized using the generated javascript function deserializeBinary. Here we get the error message:
"Unknown base64 encoding at char"

This is the complete callstack:
[2]</</goog.crypt.base64.decodeStringInternal_ http://localhost:34568/phoenix/configuration/RESTFulPhoenix_bundle.js:1208:312
	[2]</</goog.crypt.base64.decodeStringToUint8Array http://localhost:34568/phoenix/configuration/RESTFulPhoenix_bundle.js:1207:367
	[2]</</jspb.utils.byteSourceToUint8Array http://localhost:34568/phoenix/configuration/RESTFulPhoenix_bundle.js:1278:198
	[2]</</jspb.BinaryDecoder.prototype.setBlock http://localhost:34568/phoenix/configuration/RESTFulPhoenix_bundle.js:1283:253
	[2]</</jspb.BinaryDecoder http://localhost:34568/phoenix/configuration/RESTFulPhoenix_bundle.js:1281:481
	[2]</</jspb.BinaryDecoder.alloc http://localhost:34568/phoenix/configuration/RESTFulPhoenix_bundle.js:1282:207
	[2]</</jspb.BinaryReader http://localhost:34568/phoenix/configuration/RESTFulPhoenix_bundle.js:1301:414
	[1]</proto.RESTFulPhoenix.Socket.deserializeBinary http://localhost:34568/phoenix/configuration/RESTFulPhoenix_bundle.js:859:16

The jspb.utils.byteSourceToUint8Array function assumes that the binary stream is encoded as base64 which seems an erroneous assumption to me...

The complete generated js-code can be found here:
[RESTFulPhoenix_bundle.zip](https://github.com/google/protobuf/files/890132/RESTFulPhoenix_bundle.zip)

**Comment by acozzette** [comment]
@rodiers I'm not a Javascript expert, but I think this is working as intended since as I understand, Javascript strings are not intended for storing arbitrary binary data. Serialized protocol buffers are not safe to store in Javascript strings since in general they contain binary data that has no meaning as a Unicode string.

For your problem, I think the right solution is to either switch to using `ArrayBuffer`/`Uint8Array`, or else keep using a string but base-64 encode it.

**Comment by CheyenneForbes** [comment]
I was having the same issue, I've made a change to fix the issue [https://github.com/google/protobuf/commit/6596d2a19265dba0b1e0ccceb1d82c3844c10211](https://github.com/google/protobuf/commit/6596d2a19265dba0b1e0ccceb1d82c3844c10211) . Until my change is accepted you can use this function to convert your strings to Uint8Array

```
function StringToBytes(str){
	arr= new Uint8Array(str.length);
	str.split("").forEach(function(a,b){
		arr[b]=a.charCodeAt();
	});
	return arr;
}
```

example:

`var Message = new proto_messages.MyMessage.deserializeBinary(StringToBytes(data));`

**Comment by CheyenneForbes** [comment]
heres how to get it working [https://github.com/google/protobuf/issues/3079#issuecomment-300889976](https://github.com/google/protobuf/issues/3079#issuecomment-300889976)

**Comment by sivaraam** [comment]
@rodiers If possible, can you kindly share how you generated the JS file from the `.proto` file?

I'm trying to compile the `.proto` for use with the browser using the following `protoc` command:

`protoc --js_out=import_style=browser,binary:. input.proto`

For which I get a `input_pb.js`. When I use it in the browser, I get the following error,

```
ReferenceError: global is not defined
```

I think the generated file is not proper for standalone use with the browser. I'm not sure what I am missing.
