### ISSUE TITLE
Python MessageToJson converts uint64 to String

### ISSUE THREAD

**Issue by gauravgopi123** [google/protobuf#2934]
I have a protobuf defined with field as uint64. When I convert the object to json using MessageToJson it returns string for that field. I looked at the code and found this code ( https://github.com/google/protobuf/blob/master/python/google/protobuf/json_format.py#L246-L247). Is it expected behavior?

**Comment by thomasvl** [comment]
Spec for what is generated (and accepted) - https://developers.google.com/protocol-buffers/docs/proto3#json
