### ISSUE TITLE
Update Protobuf Lite on mavenCentral

### ISSUE THREAD

**Issue by LouisCAD** [google/protobuf#2935]
Hi, Protobuf 3.2.0 has been released, but I don't see the protobuf lite 3.2.0 version on Maven Central here : https://mvnrepository.com/artifact/com.google.protobuf/protobuf-lite

**Comment by acozzette** [comment]
@LouisCAD The reason we are not regularly updating protobuf-lite on Maven Central is that we have been making a number of major changes to the Java lite implementation that break compatibility with existing generated code. So if we published a new version and you updated your project to use it, it would break unless you simultaneously updated all your protobuf generated code, including generated code in dependencies. We are recommending that if you want to use lite with Maven, just stick with 3.0.1 for now.

(Let me close this issue for now, but feel free to reopen it if you have any other questions.)

**Comment by LouisCAD** [comment]
@acozzette My project is all new, so I'd like to get the latest Protobuf version ASAP instead of having to refactor it later when I rely more on the code generated by the version 3.0.1

Could you deploy it to mavenCentral/jCenter while documenting the breaking changes from v3.0.1 to 3.2.0, and the motivation behind them, please?

**Comment by xfxyjwf** [comment]
@LouisCAD The breaking changes we are making are mostly not public API changes, but "internal" changes to the interface between protobuf runtime and protobuf generated code. Although this interface is usually not visible to users, changes to the interface do break users who want to upgrade protobuf runtime from one version to another, and as such we don't want to deploy multiple versions that aren't compatible with each other to maven.

I would suggest you use 3.0.1 for now. Protobuf public API is fairly stable and we almost never remove public APIs. All public APIs documented in our developer guide can be relied on. There is no worry about the need to refactor your code for new versions.
