### ISSUE TITLE
Java: Maps with enum value type should allow putting unknown values

### ISSUE THREAD

**Issue by anuraaga** [google/protobuf#2936]
Currently, the singular ```put*Value``` method of a map with enum value type does not accept values that are not valid enums. This seems to literally be the only place in generated code that checks the validity of an enum value when using the ```*Value variants``` of the methods (e.g. singular, repeated fields). Even the ```putAll*Value``` variant that takes a ```Map<Key, Integer>``` parameter allows unknown values. I think the ```*Value``` variants were added to allow working with unknown values, for backwards compatibility situations, and in particular, just having the check in one location seems highly inconsistent.

**Comment by acozzette** [comment]
That does sound like a strange inconsistency. @xfxyjwf, what do you think?

**Comment by xfxyjwf** [comment]
Yes, I think this is a bug. put*Value should accept any integer value.

**Comment by thomasvl** [comment]
Should it depend on proto2 vs. proto3 syntax?  I when parsing binaries, I thought proto2 caused the map entries to go into unknown fields if the enum was unknown?

**Comment by anuraaga** [comment]
Yep it should, and the code was already trying to respect that difference. It just happened to insert the unknown value check into SupportsUnknownValues == (syntax = 'proto3') codepath as well, probably just a misunderstanding since putValue needs to behave the same as putAllValues

The branch for proto3 vs proto2 is here:

]https://github.com/anuraaga/protobuf/blob/bf483dfb99a5b7c57ee0a222bd041275cda9cf98/src/google/protobuf/compiler/java/java_map_field.cc#L402
