### ISSUE TITLE
java JsonFormat.printer().print(m) exception NoClassDefFoundError

### ISSUE THREAD

**Issue by Pro100AlexHell** [google/protobuf#2941]
java code:
com.google.protobuf.util.JsonFormat.printer().print(m); // m - my message, .getDefaultInstance() not work too

throws
java.lang.NoClassDefFoundError: com/google/protobuf/Any
	at com.google.protobuf.util.JsonFormat$PrinterImpl.buildWellKnownTypePrinters(JsonFormat.java:569)
	at com.google.protobuf.util.JsonFormat$PrinterImpl.<clinit>(JsonFormat.java:563)
	at com.google.protobuf.util.JsonFormat$Printer.appendTo(JsonFormat.java:196)

I have tried precompiled protobuf-java-util-3.2.0.jar
and can't test from sources - it's not compiles.

I have build protobuf.jar by myself from sources, cant' find a precompiled.

**Comment by xfxyjwf** [comment]
Is protobuf-java-3.2.0 jar in your class path?

**Comment by Pro100AlexHell** [comment]
it's in \lib folder, where other jars exist.
and I have tried 2nd case - run with "-classpath C:\...\lib".
also I have not found a class "com.google.protobuf.Any" in sources

**Comment by Pro100AlexHell** [comment]
I have tried http://mvnrepository.com/artifact/com.google.protobuf/protobuf-java/3.2.0 and now it compile "Any.pack(message)" and JsonFormat error is "java.lang.NoClassDefFoundError: com/google/gson/GsonBuilder"

**Comment by xfxyjwf** [comment]
Are you manually invoking javac to build the Java code? In that case you are going to need all transitive dependencies of protobuf-java-util, including guava and gson. You can see a list of them here:
http://mvnrepository.com/artifact/com.google.protobuf/protobuf-java-util/3.2.0

**Comment by Pro100AlexHell** [comment]
I use netbeans, and include jar files to libraries.
after import gson
the error "java.lang.NoClassDefFoundError: com/google/common/io/BaseEncoding" now..
I only import
protobuf-java-3.2.0.jar
protobuf-java-util-3.2.0.jar
then I need to include 10+ other jars ?))

**Comment by xfxyjwf** [comment]
I don't think you need 10+. The test dependencies can be ignored. Including gson and guava should be good enough.

**Comment by Pro100AlexHell** [comment]
thank you! now it work (after gson and guava)

**Comment by ricdong** [comment]
which version of gson and guava did you use ?

**Comment by Pro100AlexHell** [comment]
it works on
gson-2.8.0
guava-21.0
protobuf-java-3.2.0
protobuf-java-util-3.2.0
