### ISSUE TITLE
Cannot compile with "-stdlib=libstdc++" flag

### ISSUE THREAD

**Issue by rodyu** [google/protobuf#2945]
I've been attempting to compile protobuf v3.2.0 with "-stdlib=libstdc++"; however, I got following error messages after running 'make'.
***
./google/protobuf/stubs/atomicops_internals_generic_c11_atomic.h:36:10: fatal error: 'atomic' file not found
#include <atomic>
         ^
1 error generated.
make[2]: *** [google/protobuf/stubs/atomicops_internals_x86_gcc.lo] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
***
My OS is OS X 10.11 with Xcode 8.2.1. Here are my running steps:
1. ./configure CXXFLAGS="-stdlib=libstdc++"
2. make

Hope someone could kindly give me help. Thanks.

**Comment by xfxyjwf** [comment]
Can you try protobuf v3.1.0?

Compiling latest version of protobuf without C++11 on newer versions of Mac OS X is no longer possible. C++11 is required as OS X has deprecated non-C++11 atomic operations and using C++11 atomic header is the only option.

**Comment by rodyu** [comment]
Because my project is statically linked to other prerequisites, all prerequisites have to be built using the same standard c++ library. Therefore, the building consideration recommends using -stdlib=libstdc++. I want to ask whether there any older version is able to compile protobuf with stdlib=libstdc++?

**Comment by darbee** [comment]
why the question closed??
