### ISSUE TITLE
google.protobuf.json_format.MessageToJson skips serialization of zero index enums

### ISSUE THREAD

**Issue by eelkevdbos** [google/protobuf#2947]
JSON serialization of python message skips serialization of 'zero' indexed enums.

libprotoc: 3.2.0
python: 2.7.10

Steps to reproduce:

```protobuf
//ticketing.proto
message Person {

    int32 id = 1;
    string name = 2;
    string email = 3;
    Role role = 4;

    enum Role {
        DEVELOPER = 0;
        PRODUCT_OWNER = 1;
    }
}
```

```python
#example.py
from ticketing_pb2 import Person
from google.protobuf import json_format

creator = Person(
    name='Eelke van den Bos',
    role=Person.DEVELOPER
)

print(json_format.MessageToJson(creator))

#expected output: {"name":"Eelke van den Bos","role":"ROLE_DEVELOPER"}
#actual output: {"name":"Eelke van den Bos"}
```

When I select the `Person.PRODUCT_OWNER` enum, json output is as expected.

**UPDATE**:
It seems like it has something to do with the 'presence' of the field, defined by the `_IsPresent` method in [python_message.py#L765](https://github.com/google/protobuf/blob/master/python/google/protobuf/internal/python_message.py#L765)

**Comment by xfxyjwf** [comment]
This is working as intended. In proto3, a field set to default value  (0 for primitives) is indistinguishable from an unset field so the JSON formater will not print any field that's set to default unless you set the including_default_value_fields flag = true on MessageToJson:
https://github.com/google/protobuf/blob/master/python/google/protobuf/json_format.py#L90
