### ISSUE TITLE
Options for `oneof`s

### ISSUE THREAD

**Issue by cstrahan** [google/protobuf#2953]
This is a feature request to allow for setting options on `oneof` declarations:

1) Expand the definition of OneofDescriptorProto to look something like so:

```proto
message OneofDescriptorProto {
  optional string name = 1;
  optional OneofOptions options = 3;
}
```

2) Define `OneofOptions` as one would expect

3) Expand the parser to allow for something like so:

```proto
import "thrift.proto";

message Hello {
    required string first_field = 1;

    oneof something {
       string some_string = 2;
       int32 some_int = 3;
    } [(thrift.ord) = 2] // <-- add support for this construct
}
```

To explain that last snippet: I'm writing a Protobuf->Thrift IDL translator, and Thrift doesn't support anonymous unions in messages. So, I need to synthesize a top level union type in the generated schema file, and set what would be the `oneof` field to be of that new union type. The following problem then arises: Protobuf doesn't require (nor allow) that a field index be specified for a oneof, while thrift _will_ require an index be specified for the corresponding generated field. **TL;DR:** This will give me a way to specify field indexes for `oneof` when translating to Thrift (and I'm sure it'll be useful for other metadata / annotation type things).

Would this be a welcome addition?

**Comment by xfxyjwf** [comment]
We already have the OneofOptions:
https://github.com/google/protobuf/blob/master/src/google/protobuf/descriptor.proto#L208

Are you just using an older version of protobuf?

**Comment by cstrahan** [comment]
> Are you just using an older version of protobuf?

Oh noes! That's probably what's going on. Guess I deserve the embarassement, having not checked master / more recent versions. :blush:

Lemme check the latest release, and tentatively I'll appologize for not doing my due diligence.

**Comment by cstrahan** [comment]
$ protoc --version
    libprotoc 2.6.1

Yep, still on the 2.x series somehow. Thanks for the heads up, and sorry for the noise.

**Comment by cstrahan** [comment]
@xfxyjwf If I may quickly ask: is the syntax I described above implemented, or is the syntax different? The [developer docs](https://developers.google.com/protocol-buffers/docs/proto#options) don't give an example for `oneof`s.

**Comment by xfxyjwf** [comment]
Note that the syntax for this oneof option looks like this:
```proto
import "google/protobuf/descriptor.proto";
extend google.protobuf.OneofOptions {
  optional int32 my_option = 12345;
}

message Hello {
  oneof something {
    option (my_option) = 54321;
  }
}
```
(not like the trailing one you proposed)

**Comment by cstrahan** [comment]
Ha, ready my mind. Thanks a ton!
