### ISSUE TITLE
couldn't find field google.protobuf.FileOptions.javanano_use_deprecated_package

### ISSUE THREAD

**Issue by ChiaoHou** [google/protobuf#2959]
I use Ubuntu 16.04 LTS, Python3.5.2, I could`t use the tensorFlow module when I run the code.
there is my code:

```python
# -*-conding:utf-8 -*-

import tensorflow as tf

a = tf.constant(1)
b = tf.constant(2)
sum = tf.add(a, b)
sess = tf.Session()
sess.run(sum)

```

and there is issues:

```shell
KeyError: "Couldn't find field google.protobuf.FileOptions.javanano_use_deprecated_package"

```

**Comment by zyj008** [comment]
I have the same problem as yours.Have you solved it?

**Comment by ChiaoHou** [comment]
Uhh.Yes, I solved this issus
1.  install tensorflow based on Python3.x, there are a way: [click here](http://blog.csdn.net/zhaohe1995/article/details/53364502?utm_source=itdadao&utm_medium=referral)
2. tensorflow needs CAUD(GPU driver): [click here](https://developer.nvidia.com/cuda-downloads)
3. add cuda to _.profile_
```shell
export LD_LIBRARY_PATH="/usr/local/cuda-7.5/lib64"
export CUDA_HOME=/usr/local/cuda-7.5
```
4. if successful, when you run _ldd /usr/local/cuda-7.5/lib64/libcudart.so.7.5_,you will see:
```shell
linux-vdso.so.1 =>  (0x00007ffdac7ea000)
libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fc27a281000)
libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fc27a07d000)
libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fc279e5e000)
librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fc279c56000)
/lib64/ld-linux-x86-64.so.2 (0x00005604f5406000)
```

> the _PATH_ maybe not the same to me!
