### ISSUE TITLE
Varying Enums fields in .proto file

### ISSUE THREAD

**Issue by AjeyaGupta** [google/protobuf#2961]
I am a newbie in GPB. I have a situation and I am tying to find an optimized solution or some idea to solve the issue. Say, I have proto file like this:

syntax = "proto3";

message A{
       int32 var1 = 1;
       enum_type var2 = 2;

       Enum enum_type {
              TYPE1 = 0;
              TYPE2 = 1;
              TYPE3 = 2;
       }
}

Now, the thing is my enum_type Enum changes for different cases. Moreover, the number of defined variables inside the Enum enum_type also changes. For example, for one situation, I'll have TYPE1 = 0. But for some other situation, I can have something like this:
       Enum enum_type{
              TYPE25 = 0;
              TYPE26 = 1;
              TYPE27 = 2;
              TYPE28 = 3;
              TYPE29 = 4;
      }

I was wondering if I should nested messages or nested enums or something that addresses this issue. I appreciate your time and help to solve this problem.

Thank You.

**Comment by acozzette** [comment]
Are you saying that you just want to be able to store more than one kind of enum in the `var2` field? If so, a oneof field might be the right solution, something like this:

```
enum EnumType1 {
...
}

enum EnumType2 {
...
}

message MessageA {
  ...
  oneof oneof_enum {
    EnumType1 type1 = 1;
    EnumType2 type2 = 2;
  }
  ...
}
```

**Comment by AjeyaGupta** [comment]
Thanks Adam for your reply. I actually kind of figured out this solution. Creating a message within the main message and then assigning 'repeated' modifier to the parameter of innner message type should do the work for me.

**Comment by acozzette** [comment]
Ok, sounds good, I'll just mark this issue closed but feel free to reopen it if you have any more questions.
