### ISSUE TITLE
Convert .proto from "proto2" to "proto3"

### ISSUE THREAD

**Issue by Ch3ck** [google/protobuf#2964]
I just wish to know if there's any tool that converts proto files from "proto2" to proto3". At this point I don't really care about backward compatibility.

**Comment by acozzette** [comment]
I don't know of any tool for this, but in practice it is usually fairly easy to convert a .proto file if you don't care about backward compatibility. You can basically just update the syntax line to say `syntax = "proto3"` and remove all `optional` and `required` keywords. The other main things are that proto3 doesn't support extensions (so you would have to remove those), and it requires every enum definition to have a 0 value as its first element. I may be forgetting something but I think those are all the main changes to make to the .proto file.

**Comment by Ch3ck** [comment]
Yeah, that makes sense. It'll be great if we could have such a tool; will be ready to contribute code if necessary.

**Comment by acozzette** [comment]
If you want to write a tool for this we can add it to our list of third-party add-ons here: https://github.com/google/protobuf/blob/master/docs/third_party.md I'm not sure if we would want to accept it as a contribution to the main protobuf codebase, though, because I would worry that it would be hard to explain to users how it works. It might work well for simple cases or for when backward compatibility is not required, but in other cases an automatic conversion could cause problems and you would really have to think carefully about how to do the migration.

**Comment by xfxyjwf** [comment]
Yilun is working on something that can convert our proto2 benchmark dataset to proto3 so we can run the dataset against proto3 only languages. It might end up in the benchmarks directory since it will be used for benchmarking purpose but should be available for general use as well.

**Comment by BSBandme** [comment]
Just added one protoc plugin target for changing proto2 to proto3 in benchmark directory. To use that plugin:

```
$ cd benchmarks
$ make protoc-gen-proto2_to_proto3
$ protoc                                                        \
$    --plugin=protoc-gen-proto2_to_proto3                       \
$    -I$(your_input_proto_root_directory)                       \
$    --proto2_to_proto3_out=$(your_output_proto_root_directory) \
$    $(input_proto_files)
```

The output proto3 proto file name is the same as input proto2 file, So the output directory should be different with input one

**Comment by WithLin** [comment]
hi, i am excutting command:
```
$  cd  protobuf-3.6.1/
$   cd benchmarks/
$ make protoc-gen-proto2_to_proto3


[root@localhost benchmarks]# make protoc-gen-proto2_to_proto3
make: *** No rule to make target `protoc-gen-proto2_to_proto3'.  Stop.
```
so what should i do? @BSBandme

**Comment by rongguodong** [comment]
> hi, i am excutting command:
> 
> ```
> $  cd  protobuf-3.6.1/
> $   cd benchmarks/
> $ make protoc-gen-proto2_to_proto3
> 
> 
> [root@localhost benchmarks]# make protoc-gen-proto2_to_proto3
> make: *** No rule to make target `protoc-gen-proto2_to_proto3'.  Stop.
> ```
> so what should i do? @BSBandme

If you have followed instructions in "[C++ Installation Instructions](https://github.com/protocolbuffers/protobuf/blob/master/src/README.md)", you should have not problems to make it.

**Comment by ylhyh** [comment]
@BSBandme @rongguodong same issue here even I can make protobuf successfully:
`make: *** No rule to make target `protoc-gen-proto2_to_proto3'.  Stop.`

**Comment by bravekingzhang** [comment]
./autogen.sh
./configure
make

**Comment by LLoyou00** [comment]
@bravekingzhang Thanks

**Comment by B-Meg** [comment]
Hey!
I am getting the following Error:

`  CXX      util/protoc_gen_proto2_to_proto3-protoc-gen-proto2_to_proto3.o
util/protoc-gen-proto2_to_proto3.cc: In member function ‘virtual bool google::protobuf::compiler::Proto2ToProto3Generator::Generate(const google::protobuf::FileDescriptor*, const string&, google::protobuf::compiler::GeneratorContext*, std::__cxx11::string*) const’:
util/protoc-gen-proto2_to_proto3.cc:69:42: error: call of overloaded ‘StripProto(std::__cxx11::string&)’ is ambiguous
     string basename = StripProto(filename);
                                          ^
In file included from util/protoc-gen-proto2_to_proto3.cc:1:0:
../src/google/protobuf/compiler/code_generator.h:198:27: note: candidate: std::__cxx11::string google::protobuf::compiler::StripProto(const string&)
 PROTOC_EXPORT std::string StripProto(const std::string& filename);
                           ^~~~~~~~~~
util/protoc-gen-proto2_to_proto3.cc:25:8: note: candidate: std::__cxx11::string google::protobuf::compiler::{anonymous}::StripProto(std::__cxx11::string)
 string StripProto(string filename) {
        ^~~~~~~~~~
util/protoc-gen-proto2_to_proto3.cc: At global scope:
util/protoc-gen-proto2_to_proto3.cc:25:8: warning: ‘std::__cxx11::string google::protobuf::compiler::{anonymous}::StripProto(std::__cxx11::string)’ defined but not used [-Wunused-function]
Makefile:2594: recipe for target 'util/protoc_gen_proto2_to_proto3-protoc-gen-proto2_to_proto3.o' failed
make: *** [util/protoc_gen_proto2_to_proto3-protoc-gen-proto2_to_proto3.o] Error 1
`

**Comment by krishnamohanelluru** [comment]
it worked when I renamed StripProto function to another name. it is locally defined, but it seemed confused with the code-generator.h function as well.
