### ISSUE TITLE
Inconsistent dll linkage when compiling with PROTOBUF_USE_DLLS on Windows

### ISSUE THREAD

**Issue by ngg** [google/protobuf#2965]
Since https://github.com/google/protobuf/commit/b1295eeffbf2ae7da8a5c7d8601c3ace0663fa09 the [compiler/plugin.pb.h](https://github.com/google/protobuf/blob/master/src/google/protobuf/compiler/plugin.pb.h) file contains lines like this:
`LIBPROTOC_EXPORT extern DescriptorProtoDefaultTypeInternal _DescriptorProto_default_instance_;`
That file also includes [descriptor.pb.h](https://github.com/google/protobuf/blob/master/src/google/protobuf/descriptor.pb.h) which uses `LIBPROTOBUF_EXPORT` for the same instances.
(This latter seems to be the correct one as they reside in [descriptor.pb.cc](https://github.com/google/protobuf/blob/master/src/google/protobuf/descriptor.pb.cc))
This emits [inconsistent dll linkage warnings](https://msdn.microsoft.com/en-us/library/35bhkfb6.aspx).

I think the proper fix would be not to write these lines into plugin.pb.h at all as the included descriptor.pb.h contains them already correctly.

**Comment by xfxyjwf** [comment]
Thanks for reporting the issue. The fix you proposed seems the right solution to me. Could you help send us a pull request?

**Comment by ngg** [comment]
@xfxyjwf can you please take a look at the comments in the PR?

**Comment by ngg** [comment]
bump

**Comment by xfxyjwf** [comment]
Thanks for the fix!
