### ISSUE TITLE
Protobuf 3.2.1 protobuf.pc file contains wrong version.

### ISSUE THREAD

**Issue by kent-at-multiscale** [google/protobuf#2966]
I just built Protobuf 3.2.1 and then tested it using an autoconf/automake project. In my `configure.ac` I have the line `PKG_CHECK_MODULES([PROTOBUF], [protobuf = 3.2.1])`. The build fails because the `protobuf.pc` file that got generated has the version 3.2.0 instead of the version I built.

This was built from a clone of the repo at commit `b50c9ec1223895973d0e2fa6b6cb74ec3c8f3ce8`, which is tag `v3.2.1`.

**Comment by xfxyjwf** [comment]
3.2.1 is for objective-c only, and the version number for all other languages stay at 3.2.0.

**Comment by kent-at-multiscale** [comment]
The tag says v3.2.1 and it contains the C++ source code, so for any consumer cloning the repo to build they will expect version 3.2.1.

**Comment by xfxyjwf** [comment]
Yeah, sorry. We made a mistake there. I'll make sure all version numbers are updated next time.

**Comment by kent-at-multiscale** [comment]
I appreciate your response. Thank you.
