### ISSUE TITLE
GPBMetadata class for php generated without package namespace

### ISSUE THREAD

**Issue by devyk** [google/protobuf#2971]
I'm trying to generate protobuf classes for php. 
Message classes are generated correctly, but metadata class always has GPBMetadata namespace.

```
//test.proto
syntax = "proto3";

package test.name;

message Person {
  string name = 1;
  int32 id = 2; 
  string email = 3;
}
```

protoc --php_out=./ test.proto

After compilation I got two files:

`<?php
//Test/Name/Person.php
namespace Test\Name;`

`<?php
//GPBMetadata/Test.php
namespace GPBMetadata;`

But last one expected to be on the same namespace as Message class, but it's not.

I do something wrong or this feature for php not implemented yet?

**Comment by TeBoring** [comment]
The last one should not be on the same namespace as Message class.
Unlike generated message class, the metadata class's namespace is decided by proto file location.

**Comment by andydeng** [comment]
If I have several modules using different proto files in the same project, they have the file structure such as
a_pb/common.proto a.proto
b_pb/commob.proto b.proto

The message class are in the different namespace like a_pb and b_pb. But the metadata class's namespace are both in GPBMetadata, and they are called like \GPBMetadata\Common, what can I do in such situation?

**Comment by artemseleznev** [comment]
all that you need was added in https://github.com/protocolbuffers/protobuf/pull/4622
you can use php_metadata_namespace option
