### ISSUE TITLE
Dtor invocation in repeated_field.h can confuse VC++2015

### ISSUE THREAD

**Issue by mda000** [google/protobuf#2972]
Compiling C++ code which defines a class named Element with a non-public dtor before including repeated_field.h can cause a compile error at repeated_field.h:295, where the compiler confuses the template argument Element with class Element. I observed this when compiling with VC++2015.3. The dtor invocation can be simplified which removes the compiler error. After the change, make && make check passes on Ubuntu 16.10 and Windows with VC++2015.3 for me. Diff below:

```C++
diff --git a/src/google/protobuf/repeated_field.h b/src/google/protobuf/repeated_field.h
index db5893b..0f50253 100644
--- a/src/google/protobuf/repeated_field.h
+++ b/src/google/protobuf/repeated_field.h
@@ -291,7 +291,7 @@ class RepeatedField PROTOBUF_FINAL {
       Element* e = &rep->elements[0];
       Element* limit = &rep->elements[size];
       for (; e < limit; e++) {
-        e->Element::~Element();
+        e->~Element();
       }
       if (rep->arena == NULL) {
 #if defined(__GXX_DELETE_WITH_SIZE__) || defined(__cpp_sized_deallocation)
```

**Comment by acozzette** [comment]
@mda000 Thanks for reporting this; do you want to send us a pull request with that change?
