### ISSUE TITLE
Inferring '_Nonnull' for pointer type within array is deprecated

### ISSUE THREAD

**Issue by ungacy** [google/protobuf#2978]
`XXX/Pods/Protobuf/objectivec/GPBDictionary.h:1321:46: Inferring '_Nonnull' for pointer type within array is deprecated`

**Comment by thomasvl** [comment]
What version are you using?  You might need to just do a update on your pods to get the current versions which fixed all the new issues from Xcode 8.3

**Comment by ungacy** [comment]
fixed with version `3.2.1`.thx.
