### ISSUE TITLE
developers.google.com claims 3.0.0 is the latest release and links directly to it

### ISSUE THREAD

**Issue by gpshead** [google/protobuf#2986]
https://developers.google.com/protocol-buffers/docs/downloads claims that 3.0.0 is the latest protobuf release and links *directly* to it.  If you aren't going to keep that up to date, please remove the full version number and just link to https://github.com/google/protobuf/releases which _always_ shows the latest release.

**Comment by arthur-tacca** [comment]
Looks like this has been fixed.
