### ISSUE TITLE
Tests build failure under Windows

### ISSUE THREAD

**Issue by jskeet** [google/protobuf#299]
Environment:

- Windows 8.1
- Visual Studio 2015 CTP 6 (unsure if this is relevant)
- gtest copied from protobuf-java-3.0.0-alpha-2.zip

Opening protobuf.sln, projects are upgraded. There's one failure upgrading gtest, but that doesn't appear to affect the build as far as I can tell.

However, the build itself fails in the "tests" project with 15 identical errors:

> C2385 ambiguous access of 'arena_' in map_field_inl.h

I don't know enough C++ to understand what's going on here, but I wanted to report it...
(lite-test.exe builds and passes, just as one more data point.)

**Comment by ravi-bhoite** [comment]
I am getting similar error on Visual Studio Premium 2013. "Tests" project is failing to build with following sort of errors: 

1>E:\protobuf-master\protobuf-master\src\google/protobuf/map_field_inl.h(215): error C2385: ambiguous access of 'arena_'
1>          could be the 'arena_' in base 'google::protobuf::internal::MapFieldBase'
1>          or could be the 'arena_' in base 'google::protobuf::internal::MapFieldLite<int,enum protobuf_unittest::Proto2MapEnum,5,14,0>'

**Comment by TeBoring** [comment]
This was fixed in 3.0.0-alpha-3 release.
