### ISSUE TITLE
Is there any way to contribute a Chinese version of docs

### ISSUE THREAD

**Issue by jingsam** [google/protobuf#3005]
I found the [docs](https://developers.google.com/protocol-buffers/docs/overview) for protobuf is very helpful. I think I can contribute a Chinese version, whereas the docs is not hosted on GitHub. So is there any way to contribute a Chinese version of docs?

**Comment by xfxyjwf** [comment]
Unfortunately the developer guide site can only be modified by Google engineers using internal tools. There isn't a way for us to accept external contributions at the moment.

There are still a few ways you can contribute though:
1. Setup your own docs site and we put a link to your docs site in our developer guide.
2. Put the docs in a subdirectory of [protobuf/docs](https://github.com/google/protobuf/tree/master/docs).
