### ISSUE TITLE
improper comment

### ISSUE THREAD

**Issue by craynic** [google/protobuf#301]
src/google/protobuf/descriptor.proto:717~721
these comment marks may cause compiling error.
I compile criu on Arch. criu comments some lines with /* and */, lines 717~721 included, so I got a compiling error with lines after 721 not correctly commented.

**Comment by xfxyjwf** [comment]
I don't think this is a problem of the descriptor.proto. The code generator who generates code for descriptor.proto should be able to take care of such escaping.

**Comment by edmonds** [comment]
`criu` is a C project, it uses `protobuf-c`, not `protobuf`. The original reporter's problem is due to a bug introduced in `protobuf-c` 1.1.0, fixed in `protobuf-c` 1.1.1. @xfxyjwf you can close this.

**Comment by craynic** [comment]
Sorry for bothering. I've sent out-of-date notice of protobuf-c to Arch.
