### ISSUE TITLE
How to copy values from java bean to protobuf message object

### ISSUE THREAD

**Issue by Rephilo** [google/protobuf#3014]
Hi, i 'm trying to use protobuf in my java project,but there is a little question bother me for a while.
If i need to use a complex message object just like that

`message Item{
    string id = 1;
    string ai= 2;
    string bid = 3;
    int32 pr = 4;
    int32 pc = 5;
    string dr = 6;
    string dc = 7;
    int32 t = 8;
    int32 st = 9;
    string c = 10;
    string n= 11;
    int32 p= 12;
    string pct= 13;
    string pn= 14;
    string rn = 15;
    int32 rt = 16;
    string sn= 17;
}` 

I have to write so much builder code like that

` itemResp = itemResp.newBuilder()
                    .setMsgCode(
                            MsgCode.newBuilder()
                                    .setCode(OK)
                                    .setMsg("success")
                                    .build())
                    .setItem(
                            Item.newBuilder()
                                    .setAreaImgUrl(itemDto.getAreaImgUrl())
                                    .setA(item.getA())
                                    .setB(item.getB())
                                    .setC(item.getC())
                                    ......
                                    .build())
                    .build();`

Is there any easier way to copy values to the message object?

**Comment by BSBandme** [comment]
The builder should has an method a mergeFrom function that can merge from another builder or message. You may copy item first then overwrite new value of already merged item field
