### ISSUE TITLE
C++ generated XXX.pb.h question

### ISSUE THREAD

**Issue by lewis081** [google/protobuf#3017]
Dear Author:
I used protoc to compile google/protobuf/descriptor.proto.
0.make a new dir and copy descriptor.proto 
1.compile cmd: protoc --cpp_out=. descriptor.proto

However, i found diffs between generated  descriptor.pb.h from origin google/protobuf/descriptor.pb.h. 
line 36 in descriptor.pb.h :
`// Internal implementation detail -- do not call these.`
`void protobuf_AddDesc_descriptor_2eproto();`
`void protobuf_AssignDesc_descriptor_2eproto();`
`void protobuf_ShutdownFile_descriptor_2eproto();`

line 36 in google/protobuf/descriptor.pb.h :
`// Internal implementation detail -- do not call these.`
`void LIBPROTOBUF_EXPORT protobuf_AddDesc_google_2fprotobuf_2fdescriptor_2eproto();`
`void protobuf_AssignDesc_google_2fprotobuf_2fdescriptor_2eproto();`
`void protobuf_ShutdownFile_google_2fprotobuf_2fdescriptor_2eproto();`

How can I generate the same descriptor.pb.h with google/protobuf/descriptor.pb.h? 

Thank You!

**Comment by lewis081** [comment]
Acctually, i want to compile google/api/annotations.proto which imports http.proto inside.

What should i do if i want to generate like down:
`// Internal implementation detail -- do not call these.`
`void LIBPROTOBUF_EXPORT protobuf_AddDesc_google_2fapi_2fannotations_2eproto();`
`void protobuf_AssignDesc_google_2fapi_2fannotations_2eproto();`
`void protobuf_ShutdownFile_google_2fapi_2fannotations_2eproto();`

**Comment by TeBoring** [comment]
https://github.com/google/protobuf/blob/master/generate_descriptor_proto.sh

**Comment by zhaozhao** [comment]
@lewis081 went into the same issue here.
It turns out that the directory in which you run `protoc` command is encoded in the generated function name.
Try to run `protoc --cpp_out=. dirname/descriptor.proto` in the upper dir, you will find the difference.

**Comment by navono** [comment]
Just for notes, I use example to explain more details about what @zhaozhao says.
Say we have the file layouts like this:

|-- generated
|-- route_guide.proto
|-- third_party
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|-- google
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|-- api
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|-- annotations.proto
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|-- http.proto
|-- gen.sh

gen.sh
>protoc -I. -Ithird_party --grpc-cpp_out=./generated --cpp_out=./generated --plugin=protoc-gen-grpc-cpp="C:\\Program Files (x86)\\grpc\\bin\\grpc_cpp_plugin.exe" ./route_guide.proto.proto
>
>protoc -Ithird_party --plugin=protoc-gen-grpc-cpp="C:\\Program Files (x86)\\grpc\\bin\\grpc_cpp_plugin.exe" --cpp_out=./generated third_party/google/api/annotations.proto
>
>protoc -Ithird_party --plugin=protoc-gen-grpc-cpp="C:\\Program Files (x86)\\grpc\\bin\\grpc_cpp_plugin.exe" --cpp_out=./generated third_party/google/api/http.proto

After executint the `gen.sh` script, besides the `route_guide` files  we also get the `google/api/` path in `generated` folder. In `annotations.pb.h`, we can see namespace like this:
```cpp
namespace protobuf_google_2fapi_2fannotations_2eproto {
    ....
}
```
