### ISSUE TITLE
protobuf-python high cpu usage when uwsgi is exiting

### ISSUE THREAD

**Issue by gfreezy** [google/protobuf#3019]
When uwsgi worker exits, it consumes very high cpu. I can't reproduce the problem every time. But more frequent than 1 out of 10. When the problem occurs, `perf top` shows below.

![f8262d89-3e0f-419f-96fc-b66cd3bd7942](https://cloud.githubusercontent.com/assets/510012/25438143/1b9b8d14-2acb-11e7-8b02-62f619176060.png)

python dependencies:

* protobuf==3.2
* uwsgi==latest

detail code:
https://gist.github.com/gfreezy/9ee8fe584bb134c56f2a6e617b87caf0

**Comment by BSBandme** [comment]
Close for now as the protobuf version is old. Feel free to reopen if the bug still exists
