### ISSUE TITLE
gtest and downloading on-demand from Google Code

### ISSUE THREAD

**Issue by gtaylor** [google/protobuf#302]
I'm not sure if Google Code is running into issues or what, but for some reason we are seeing really spotty reliability between Google Compute Engine instances and the gtest download URL (http://googletest.googlecode.com/files/gtest-1.5.0.tar.bz2) today. From my home connection, I am able to reach and download the file.

While this will probably be fixed by someone else eventually, it does bring up the fact that protobuf has moved to Github, yet its build process depends on something sitting back over at Google Code (which is apparently having issues today, and is on death row).

This could be a gtest issue, but I'm going to drop it here since it's causing me pain with protobuf.

**Comment by ctiller** [comment]
FWIW I just sent out a pull request for grpc (grpc/grpc#3050) to use the google/googletest package on GitHub, now that there is one.

**Comment by xfxyjwf** [comment]
So they finally moved to github. Protobuf should be updated to use: https://github.com/google/googlemock as well.

**Comment by xfxyjwf** [comment]
We should move to use submodule as well. This is tracked by another issue:
https://github.com/google/protobuf/issues/236
