### ISSUE TITLE
protoc doesn't find include path

### ISSUE THREAD

**Issue by buchgr** [google/protobuf#3022]
protoc doesn't find a proto file, when it's full path is specified via `-I`.

```
$ cat foo/bar.proto
syntax = "proto2";

$ protoc -Ibar.proto=foo/bar.proto --descriptor_set_out=bar.proto.bin bar.proto
bar.proto: No such file or directory
```

This actually breaks bazel's `proto_library` rules.

**Comment by xfxyjwf** [comment]
The file parameter must be the actual physical path, i.e., regardless of other flags, you have to use foo/bar.proto when specifying the file to generate code for.

**Comment by xfxyjwf** [comment]
Note that that's actually contrary to the internal version of protocol compiler where you have to use the google3 relative path. It has been that way for reasons I don't know of...

**Comment by buchgr** [comment]
Thanks @xfxyjwf . Closing this for now.
