### ISSUE TITLE
how to get the data from protobuf message -php

### ISSUE THREAD

**Issue by dharmendart** [google/protobuf#3031]
Hi,
I am able to get/generate the protobuf php class files with .proto file using protoc plugin.
The REST API is rendering the protobuf message and i need to parse or serailze the message using php generated classes
when I print the protobuf message format in file it looks like this

)"*2eView:5/1/2017 10:46:28 AMB� !GienTT01*Gien1234Z	��ĵ�V !GienTT02*Gien5678Z	�����V "GienTT03*	Gien91011Z	�〶�V )BerlinDevice*BerlinDeviceZ	�����V 'BerlinTest1*BerlinTest1Z	�����V 'BerlinTest2*BerlinTest2Z	ڰ���V 'BerlinTest3*BerlinTest3Z	�����V 'BerlinTest4*BerlinTest4Z	�����V '	BerlinTest5*BerlinTest5Z	ƽ���V ' BerlinTest6*BerlinTest6Z	����V

and this message has the repeated fields

Please guide me how i can read the message in my php file .

**Comment by TeBoring** [comment]
$m = new YourMsg();
$m->mergeFromString($data);

**Comment by dharmendart** [comment]
I have used the above function but it is returning empty data .

**Comment by TeBoring** [comment]
https://docs.google.com/document/d/1fUi0lKpfR7gauaJdhjid1SStdLePREVeUnwfamrPRVk
This is the API doc

**Comment by TeBoring** [comment]
Please also check https://developers.google.com/protocol-buffers/docs/overview for basic idea of protobuf.

**Comment by TeBoring** [comment]
Please also make sure the data you provide is actually proto's wire format.

**Comment by dharmendart** [comment]
I am using the below proto file . Please check the below  proto  file for your reference is  it a proto wire format.


syntax = "proto3";
message DeviceDetail {
	int32 ID = 1;
	string DeviceUUID = 2;
	int32 DeviceStatus = 3;
	string ModelNumber = 4;
	string SerialNumber = 5;
	string FirmwareVersion = 6;
	int32 Location = 7;
	int32 ProductType = 8;
	string ProductVersion = 9;
	string CreatedBy = 10;
	int64 CreatedDate = 11;
	string ModifiedBy = 12;
	int64 ModifiedDate = 13;
	bool IsNew = 14;
	bool IsDirty = 15;
	bool IsDeleted = 16;
}

message DeviceDetails {
  repeated DeviceDetail results = 1;
}

**Comment by dharmendart** [comment]
The REST API returned data and parsing implementation as followed like this 
  
$options = array('http' => array(
    'method' => "GET",
    'header' => "Content-Type: application/x-protobuf" 
 ));

$context = stream_context_create($options);

$data = file_get_contents('REST API URL', false, $context);

$request = new DeviceDetail();

$result = $request->mergeFromString($data);

**Comment by TeBoring** [comment]
By wire format, I mean protobuf's binary format: https://developers.google.com/protocol-buffers/docs/encoding
It seems that you are directly using the $data for mergeFromString. Please double check what's in $data.

**Comment by dharmendart** [comment]
the $data having the below message.

)����"2�eView:�5/1/2017 10:46:28 AMB��� !����GienTT01�Gien1234Z	���ĵ�V�� !����GienTT02�Gien5678Z	������V�� "����GienTT03	Gien91011Z	��〶�V�� )���BerlinDevice*BerlinDeviceZ	������V�� '����BerlinTest1�BerlinTest1Z	������V�� '����BerlinTest2�BerlinTest2Z	�ڰ���V�� '����BerlinTest3�BerlinTest3Z	������V�� '����BerlinTest4�BerlinTest4Z	������V�� '�	��BerlinTest5�BerlinTest5Z	�ƽ���V�� '� ��BerlinTest6�BerlinTest6Z	�����V��

how to get the values from above message.

**Comment by TeBoring** [comment]
It's decided by the other Api you called, like file_get_content. It's out
of scope of protobuf. You need to check by yourself. Sorry I cannot help.

**Comment by dharmendart** [comment]
I have used this 
$request = new DeviceDetails();

$result = $request->mergeFromString($data);

Now able to deserialize the data with mergeFromString().  
After doing print_r($request)   I have got the below output .

 how to get the values from repeated field


Google\Protobuf\Internal\RepeatedField Object
(
    [container:Google\Protobuf\Internal\RepeatedField:private] => Array
        (
            [0] => DeviceDetail Object
                (
                    [ID:DeviceDetail:private] => 3
                    [DeviceUUID:DeviceDetail:private] => TestDevice
                    [DeviceStatus:DeviceDetail:private] => 1
                    [ModelNumber:DeviceDetail:private] => M_1.00
                    [SerialNumber:DeviceDetail:private] => S_1.01
                    [FirmwareVersion:DeviceDetail:private] => v1.0
                    [Location:DeviceDetail:private] => 1
                    [ProductType:DeviceDetail:private] => 1
                    [ProductVersion:DeviceDetail:private] => v1.0
                    [CreatedBy:DeviceDetail:private] => 
                    [CreatedDate:DeviceDetail:private] => 0
                    [ModifiedBy:DeviceDetail:private] => 
                    [ModifiedDate:DeviceDetail:private] => 0
                    [IsNew:DeviceDetail:private] => 
                    [IsDirty:DeviceDetail:private] => 
                    [IsDeleted:DeviceDetail:private] => 
 [desc:Google\Protobuf\Internal\Message:private] => Google\Protobuf\Internal\Descriptor Object
                        (

**Comment by TeBoring** [comment]
RepeatedField has the same API as array.
$element = $repeated_field[0]

**Comment by TeBoring** [comment]
Feel free to reopen the issue if there is still problem.
