### ISSUE TITLE
Parameters set to have certain value but, don't want to send that over wire (GPB: Proto 3)

### ISSUE THREAD

**Issue by AjeyaGupta** [google/protobuf#3032]
My comments/questions here are only for Google ProtoBufs, syntax=proto3 (and not proto2)

Upon doing some research online, it looks like unset fields are simply absent from the encoded message. If you have three fields, a, b, and c with tags 1, 2, and 3 respectively, and you encode a message with only "a"set to "100", then the encoded message will contain "field(1) = 42", and nothing else.

Now, I wanted to understand another aspect of GPB using proto3 syntax. Lets say, I have a parameter which has been set to a value (not hardcoded, but say by parsing another file in my source code). And if that parameter is set to certain value and I don't want to send that over wire, is there a way to accomplish this? Or do I need to have a separate flag for this parameter setting it to be true or false based on weather I want to send this particular parameter over wire?

I appreciate your help.

Thank You.

**Comment by xfxyjwf** [comment]
There isn't any option or feature to omit values other than the default.
