### ISSUE TITLE
NodeJS: String fields retain Int characteristics

### ISSUE THREAD

**Issue by relwell** [google/protobuf#3034]
Using `google-protobuf@3.2.0`:

Assume the following protobuf definition:

```
message Foo {
  string some_value = 1;
}
```

Using a console, you can note the following behavior:

```javascript
> var m = new Foo();
...
> m.setSomeValue(123);
undefined
> m.getSomeValue();  // '123' expected
123
```

It turns out that the protobuf message is storing something typed as a string as an integer when an integer is passed. This also results in incorrect serialization behavior. For instance:

```javascript
> var a = new Foo();
...
> var b = new Foo();
...
> a.setSomeValue(123);
undefined
> b.setSomeValue('123');
undefined
> a.serializeBinary() == b.serializeBinary()
false
```

**Comment by BSBandme** [comment]
Sorry but although this seems weird to you, it's the intended behavior. Currently we don't have type check for the string field in JS. 
We're working on making JS protobuf format standard, when the standard is ready to go, we'll make some announcement about that.
