### ISSUE TITLE
Internal compiler error with gcc (CentOs 6.8)

### ISSUE THREAD

**Issue by jamesawalker** [google/protobuf#3035]
Hi,

I'm trying to install from source on CentOs 6.8.

I used the download protobuff-cpp-3.3.0.tar.gz. I used gcc versions 4.9.0, 4.9.1, 5.3.0, and 6.1.0.

./configure appears to run fine, but when I make I get an error (same error for all gcc versions)

In file included from /data/apps/gcc/5.3.0/include/c++/5.3.0/tr1/hashtable.h:36:0,
                 from /data/apps/gcc/5.3.0/include/c++/5.3.0/tr1/unordered_map:41,
                 from ./google/protobuf/stubs/hash.h:145,
                 from ./google/protobuf/compiler/command_line_interface.h:42,
                 from google/protobuf/compiler/main.cc:33:
/data/apps/gcc/5.3.0/include/c++/5.3.0/tr1/hashtable_policy.h:383:5: internal compiler error: Illegal instruction
     _Prime_rehash_policy(float __z = 1.0)

I also tried using protobuf 3.2.0 and 3.1.0 with the same result.
Thanks for any help!

**Comment by Oppen** [comment]
If nobody opposes, I'll try to reproduce and fix this.
Please note I'm not in any way related to Google and/or protobuf, and have no authority.

**Comment by Oppen** [comment]
With the default compiler seems to build fine. How can I get the exact compiler builds you used?

**Comment by jamesawalker** [comment]
This is the compiler script used for our gcc 4.9.1 build, it should be equivalent for the others

#!/bin/sh -v
# J. Farran 
# 8/2014 Version 4.9.1

. /data/shell-syswide-setup/system-wide-bashrc

SOURCE=/data/apps/sources/gcc-4.9.1
  DEST=/data/apps/gcc/4.9.1
   LOG=`echo $DEST | tr "/" "-"`

module purge
module load gmp/6.0.0
module load mpfr/3.1.2
module load mpc/1.0.2
module load binutils/2.24
module list

cd $SOURCE

/bin/rm -f ,*

make clean  > /dev/null
find $SOURCE -name "*.o"  -exec echo Cleaning {} \; -exec rm {} \;

echo "Start compilation."

ARCH="-arch `arch`"

CFLAGS="-fPIC -O3" ./configure      \
    --with-gmp=/data/apps/gmp/6.0.0  --with-mpfr=/data/apps/mpfr/3.1.2  \
    --with-mpc=/data/apps/mpc/1.0.2  --enable-threads=posix             \
    --with-as=/data/apps/binutils/2.24/bin/as                           \
    --mandir=$DEST/man                                                  \
    --pdfdir=$DEST/pdf                                                  \
    --htmldir=$DEST/html                                                \
    --enable-languages=c,c++,fortran,go,java,lto,objc,obj-c++       \
    --prefix=$DEST  >& $SOURCE/,configure$LOG

**Comment by Oppen** [comment]
Is that from the stock repositories? Where can I fetch this?

2017-05-12 13:59 GMT-03:00 James Walker <notifications@github.com>:

**Comment by jamesawalker** [comment]
I wasn't the one who built this gcc, but the source files can be found here:
https://ftp.gnu.org/gnu/gcc/gcc-4.9.1/
