### ISSUE TITLE
v3.3.0 release has not been uploaded to https://pecl.php.net/

### ISSUE THREAD

**Issue by tpolich** [google/protobuf#3036]
The php c extension for the v3.3.0 release has not yet been uploaded to https://pecl.php.net/

https://pecl.php.net/package/protobuf

has "Release 3.2.0a1:" as the last release.

**Comment by TeBoring** [comment]
@stanley-cheung is working on that.

**Comment by TeBoring** [comment]
https://pecl.php.net/package/protobuf
