### ISSUE TITLE
Python "./setup.py sdist/bdist_egg/bdist_wheel" is hard to use correctly.

### ISSUE THREAD

**Issue by xfxyjwf** [google/protobuf#3045]
Several problems:
1. If "./setup.py build" is not ran before "./setup.py sdist", "./setup.py sdist" will create a broken package missing well-known types.
2. If "./setup.py test --cpp_implementation" is ran, "./setup.py bdist_egg/bdist_wheel" will include "google/protobuf/_message.so" in the resulted package and since the package doesn't contain protobuf C++ runtime, it will cause import errors. See an example in https://github.com/google/protobuf/issues/3042
3. "./setup.py sdist" includes files under python/compatibility_tests and *.h/*.cc files under python/google/protobuf/pyext, which shouldn't be included for pure python implementation.
4. "./setup.py bdist_egg/bdist_wheel" includes generated code of many unittest protos.

(1) and (2) make it very easy to deploy broken packages to PyPI. You must make sure a clean workspace is used and execute the commands in the right order.

**Comment by lukesneeringer** [comment]
Note: `python setup.py clean --all` is a thing, and might help with the second bullet.

I would recommend writing a script that does the right thing every time, so we do not run into this.

**Comment by xfxyjwf** [comment]
Yeah, we are working on a release script already.

**Comment by xfxyjwf** [comment]
We have a release script for pypi release now:
https://github.com/google/protobuf/blob/master/python/release.sh
