### ISSUE TITLE
CMake missing files

### ISSUE THREAD

**Issue by amerry** [google/protobuf#3047]
The CMake build is missing `generated_message_table_driven.cc` from its list of source files to compile, and both `generated_message_table_driven.h` and `metadata_lite.h` from `extract_includes.bat.in`. This causes problems when building gRPC against a CMake-built protobuf.

**Comment by sthelen** [comment]
`generated_message_table_driven.cc` is not included in the library sources in `src/Makefile.am` either, although it references both the headers you mention, which are absent in `extract_includes.bat.in`.

**Comment by sthelen** [comment]
These changes should do the trick: https://github.com/sthelen/protobuf/commit/fc45dfe5d7983cf67f2a5842dc2f79b921a87ea4

**Comment by sthelen** [comment]
Submitted a pull request (https://github.com/google/protobuf/pull/3051) for above change (https://github.com/sthelen/protobuf/commit/fc45dfe5d7983cf67f2a5842dc2f79b921a87ea4).
