### ISSUE TITLE
ParseGeneratorParameter is missing LIBPROTOC_EXPORT

### ISSUE THREAD

**Issue by amerry** [google/protobuf#3048]
ParseGeneratorParameter needs LIBPROTOC_EXPORT. Without it, gRPC (for example) cannot be built against a DLL version of protobuf.

**Comment by KindDragon** [comment]
Please reopen issue, they remove `LIBPROTOC_EXPORT` again https://github.com/google/protobuf/blob/13fd045dbb2b4dacea32be162a41d5a4b0d1802f/src/google/protobuf/compiler/code_generator.h#L169-L170
