### ISSUE TITLE
`make check` fails for source of C++-release on C#-test!?

### ISSUE THREAD

**Issue by Bagira80** [google/protobuf#3049]
Downloading the [3.3.0 release for C++](https://github.com/google/protobuf/releases/download/v3.3.0/protobuf-cpp-3.3.0.tar.gz) and building the libraries (with GCC 4.8 / 6) succeeds.
However, running its unit-tests (via `make check`) fails.

In particular, the *protobuf-test* fails with the following error (extracted from the `test_suite.log`):

```
[----------] 1 test from CsharpBootstrapTest
[ RUN      ] CsharpBootstrapTest.GeneratedCsharpDescriptorMatches
[libprotobuf FATAL ../../protobuf-3.3.0/src/google/protobuf/compiler/csharp/csharp_bootstrap_unittest.cc:94] CHECK failed: ::google::protobuf::internal::IsOk(File::GetContents(TestSourceDir() + "/" + physical_filename, &actual_contents, true)): Unable to get ../csharp/src/Google.Protobuf/Reflection/Descriptor.cs
unknown file: Failure
C++ exception with description "CHECK failed: ::google::protobuf::internal::IsOk(File::GetContents(TestSourceDir() + "/" + physical_filename, &actual_contents, true)): Unable to get ../csharp/src/Google.Protobuf/Reflection/Descriptor.cs" thrown in the test body.
[  FAILED  ] CsharpBootstrapTest.GeneratedCsharpDescriptorMatches (26 ms)
[----------] 1 test from CsharpBootstrapTest (26 ms total)
```

It seems as if this unit-tests requires some C# source files to be present which obviously are missing in a C++ release.

**Comment by Bagira80** [comment]
@xfxyjwf Was it on purpose that these fixes automatically went into another **3.3.0** release which replaced the original one? Shouldn't this have gone into another **3.3.1** release?

Or are the Github-scripts which generate compressed release-files buggy?

**Comment by xfxyjwf** [comment]
Apologize if this causes confusion, but I did replace the C++ tar.gz packages intentionally. I will make a separate 3.3.1 tag later.

**Comment by ACommonChinese** [comment]
============================================================================
See src/test-suite.log
Please report to protobuf@googlegroups.com
============================================================================
make[4]: *** [test-suite.log] Error 1
make[3]: *** [check-TESTS] Error 2
make[2]: *** [check-am] Error 2
make[1]: *** [check] Error 2
make: *** [check-recursive] Error 1
Error: 'make -j 8 check' exited with status 2

And i open the src/test-suite.log, it shows:
[  FAILED  ] 1 test, listed below:
[  FAILED  ] CsharpBootstrapTest.GeneratedCsharpDescriptorMatches
