### ISSUE TITLE
encode/decode using php protobuf

### ISSUE THREAD

**Issue by Aldibe** [google/protobuf#3053]
I'm having some trouble using protobuf for PHP. I've written my question here (http://stackoverflow.com/questions/43756986/php-protobuf-error-undefined-method-for-encode-decode), but no response yet. Can anyone help?

**Comment by abebars-nyt** [comment]
Encode & Decode not exist in the codebase as I traced down;

```
//to encode message 
$data = $message->serializeToString();

//to decode message
$messsage2 = new TestMessage();
$messsage2->mergeFromString($data);
```

**Comment by TeBoring** [comment]
Sorry, we haven't updated our doc.
@abebars-nyt is correct.
