### ISSUE TITLE
[php 7.1] broken build

### ISSUE THREAD

**Issue by remicollet** [google/protobuf#3058]
```
/dev/shm/BUILD/php71-php-pecl-protobuf-3.3.0/NTS/message.c: In function 'message_set_property':
/opt/remi/php71/root/usr/include/php/Zend/zend_globals_macros.h:46:33: error: 'zend_executor_globals {aka struct _zend_executor_globals}' has no member named 'scope'
 # define EG(v) (executor_globals.v)
                                 ^
/dev/shm/BUILD/php71-php-pecl-protobuf-3.3.0/NTS/message.c:119:28: note: in expansion of macro 'EG'
   if (Z_OBJCE_P(object) != EG(scope)) {
                            ^~
/dev/shm/BUILD/php71-php-pecl-protobuf-3.3.0/NTS/message.c: In function 'message_get_property':
/opt/remi/php71/root/usr/include/php/Zend/zend_globals_macros.h:46:33: error: 'zend_executor_globals {aka struct _zend_executor_globals}' has no member named 'scope'
 # define EG(v) (executor_globals.v)
                                 ^
/dev/shm/BUILD/php71-php-pecl-protobuf-3.3.0/NTS/message.c:149:28: note: in expansion of macro 'EG'
   if (Z_OBJCE_P(object) != EG(scope)) {
                            ^~

```

**Comment by remicollet** [comment]
Moving from EG(scope) to zend_get_executed_scope(); should do the trick

(I won't open a PR because of CLA)

**Comment by yufeixuan** [comment]
/usr/include/php/Zend/zend_globals_macros.h:46:33: error: 'zend_executor_globals' has no member named 'scope'
 # define EG(v) (executor_globals.v)
                                 ^
/tmp/pear/download/protobuf-3.3.0/message.c:119:28: note: in expansion of macro 'EG'
   if (Z_OBJCE_P(object) != EG(scope)) {
                            ^
/tmp/pear/download/protobuf-3.3.0/message.c: In function 'message_get_property':
/usr/include/php/Zend/zend_globals_macros.h:46:33: error: 'zend_executor_globals' has no member named 'scope'
 # define EG(v) (executor_globals.v)
                                 ^
/tmp/pear/download/protobuf-3.3.0/message.c:149:28: note: in expansion of macro 'EG'
   if (Z_OBJCE_P(object) != EG(scope)) {

[root@phoenix protobuf-3.3.0]# php -v
PHP 7.1.4 (cli) (built: Apr 27 2017 13:55:48) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.1.4, Copyright (c) 1999-2017, by Zend Technologies
    with Xdebug v2.5.1, Copyright (c) 2002-2017, by Derick Rethans
