### ISSUE TITLE
Unused parameter 'deterministic'

### ISSUE THREAD

**Issue by mger1** [google/protobuf#3059]
See issue #2032
Fix in #2072 

This was fixed in 3.2 but is back in 3.3.

This commit reintroduced it:
d36c0c538a545fac5d9db6ba65c525246d4efa95

**Comment by scpeters** [comment]
I just submitted #3085 that forward ports the fix from #2087 to 3.3.x

**Comment by kaimast** [comment]
Yikes. I wasted an hour trying to compile my code because of this :(

**Comment by scpeters** [comment]
I think this can be closed when 3.3.2 is tagged.

**Comment by mger1** [comment]
It should probably stay open until the fix lands in the master branch.
