### ISSUE TITLE
MessageToJson changes names of fields. How to avoid it?

### ISSUE THREAD

**Issue by kenenbek** [google/protobuf#3067]
I have some protobuf message object. So I want to serialize it in such way:

    import json
    from google.protobuf.json_format import MessageToJson

    with open("file.json", 'w') as fjs:
        fjs.write(MessageToJson(message_object))

But it changes the names of object fields.
For example, I have such object:

    [{
        "id": "333333",
        "creation_timestamp": 2011,
    }]

MessageToJson changed it fields to:

    [{
      "id": "333333",
      "creationTimestamp": "2011",
    }] 

i.e `creation_timestamp` changed to `creationTimestamp` and `2011` did to `"2011"`. 
How to avoid it?

**Comment by xfxyjwf** [comment]
You can use the JsonPrintOptions.preserve_proto_field_names flag to instruct the Json formatter to not convert field names to lowerCamelCase.

**Comment by xfxyjwf** [comment]
Sorry, my comment assumed you were using C++. For python, there is also such a flag but named a bit differently (as preserving_proto_field_names):
https://github.com/google/protobuf/blob/master/python/google/protobuf/json_format.py#L91

**Comment by kenenbek** [comment]
Thank you!
