### ISSUE TITLE
can't compile in centos 6.x  Part 2

### ISSUE THREAD

**Issue by nacho** [google/protobuf#3069]
I get this error when compiling on centos 6 either the master branch or 3.3.x

libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I.. -pthread -DHAVE_PTHREAD=1 -DHAVE_ZLIB=1 -Wall -Wno-sign-compare -O2 -g -DNDEBUG -MT google/protobuf/any.pb.lo -MD -MP -MF google/protobuf/.deps/any.pb.Tpo -c google/protobuf/any.pb.cc  -fPIC -DPIC -o google/protobuf/.libs/any.pb.o
In file included from ./google/protobuf/metadata.h:41,
                 from ./google/protobuf/any.pb.h:27,
                 from google/protobuf/any.pb.cc:5:
./google/protobuf/metadata_lite.h: In constructor 'google::protobuf::internal::InternalMetadataWithArenaLite::InternalMetadataWithArenaLite(google::protobuf::Arena*)':
./google/protobuf/metadata_lite.h:170: error: class 'google::protobuf::internal::InternalMetadataWithArenaLite' does not have any field named 'InternalMetadataWithArenaBase'
make[2]: *** [google/protobuf/any.pb.lo] Error 1
make[2]: Leaving directory `/builddir/DCV_JHBUILD/sources/protobuf/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/builddir/DCV_JHBUILD/sources/protobuf'
make: *** [all] Error 2

**Comment by xfxyjwf** [comment]
Can you check if this PR has fixed the issue?
https://github.com/google/protobuf/pull/3062

**Comment by nacho** [comment]
Yup that's the same patch I used downstream
