### ISSUE TITLE
Doubly-nested types generate invalid C# code

### ISSUE THREAD

**Issue by jskeet** [google/protobuf#307]
Consider a proto of:

```
syntax = "proto2";

package foo;

message Outer {
  message Middle {
    message Inner {
    }
  }
}
```

The generated C# code contains:

```
public override pbd::MessageDescriptor DescriptorForType {
  get { return global::foo.Outer.Types.Middle.Inner.Descriptor; }
}
```

This should be:

```
public override pbd::MessageDescriptor DescriptorForType {
  get { return global::foo.Outer.Types.Middle.Types.Inner.Descriptor; }
}
```

Note the extra `Types` between `Middle` and `Inner`.

(This currently makes the generated code from unittest.proto fail to compile, so once that *does* compile, that's enough of a test for the fix...)

**Comment by jtattermusch** [comment]
Is this still an issue in the new codegen?

**Comment by jskeet** [comment]
Yes, it is. (Probably because I haven't touched any of the code that works out type names.)

**Comment by jskeet** [comment]
Looks like the problem is in csharp_helpers.cc, in `ToCSharpName`:

    result += StringReplace(classname, ".", ".Types.", false);

It may be as simple as changing "false" to "true". Will need to investigate.
