### ISSUE TITLE
Python documentation error in Writing a Message tutorial

### ISSUE THREAD

**Issue by twhetzel** [google/protobuf#3070]
On this page:
https://developers.google.com/protocol-buffers/docs/pythontutorial

The example for "Writing a Message" includes:
 `PromptForAddress(address_book.person.add())`

However, it should be:
`PromptForAddress(address_book.people.add())`

Based on the sample `add_person.py` here:
https://github.com/google/protobuf/blob/master/examples/add_person.py and the error message with the original "Writing a Message" code stating that `AttributeError: 'AddressBook' object has no attribute 'person'`

Check-out the Python examples here for comparison of what works: https://github.com/google/protobuf/tree/master/examples

**Comment by anandolee** [comment]
Fixed. Thanks!
