### ISSUE TITLE
Python Documentation error in tutorial Reading a Message

### ISSUE THREAD

**Issue by twhetzel** [google/protobuf#3071]
In the sample here:
https://developers.google.com/protocol-buffers/docs/pythontutorial

It lists:
`for person in address_book.person:`

but it should be:
`for person in address_book.person:`

Check-out the Python examples here for comparison of what works: https://github.com/google/protobuf/tree/master/examples

**Comment by anandolee** [comment]
Changed to address_book.people

Thanks for raise it up
