### ISSUE TITLE
Q: php7.1.4 make: *** [message.lo] Error 1

### ISSUE THREAD

**Issue by searchpcc** [google/protobuf#3076]
When I built it with php7.1.4 pecl, some errors came :

/tmp/pear/temp/protobuf/message.c: In function ‘message_set_property’:
/tmp/pear/temp/protobuf/message.c:119: error: ‘zend_executor_globals’ has no member named ‘scope’
/tmp/pear/temp/protobuf/message.c: In function ‘message_get_property’:
/tmp/pear/temp/protobuf/message.c:149: error: ‘zend_executor_globals’ has no member named ‘scope’
make: *** [message.lo] Error 1
ERROR: `make' failed

**Comment by xfxyjwf** [comment]
Is this issue the same as https://github.com/google/protobuf/issues/3058 ?

**Comment by searchpcc** [comment]
Thanks.
