### ISSUE TITLE
Multiple methods named 'objectForkey:' found with mismatched result, paramter type or attributes

### ISSUE THREAD

**Issue by Insfgg99x** [google/protobuf#3081]
I get this error when i import protobuff, at 
```NSString *openid = [obj objectForKey:@"openid"];```
Multiple methods named 'objectForkey:' found with mismatched result, paramter type or attributes.

**Comment by thomasvl** [comment]
My guess is your `obj` doesn't have a specific type (maybe just `id`), so the compiler is telling you you there are multiple definitions and it doesn't know which is the correct one.  If you use an more explicit type, the warning will go away.

**Comment by shashidj** [comment]
Go to Protobuf files > select .m files > target membership > deselect/select target > compile

**Comment by MRZHL** [comment]
it is  ok ? @shadchin

**Comment by shadchin** [comment]
forward @shashidj :-)
