### ISSUE TITLE
protobuf-cpp version hash changed

### ISSUE THREAD

**Issue by Oppen** [google/protobuf#3087]
Did anyone reupload a different tarball of the same version?
This can break any attempt to having trusted tarballs, and probably shouldn't be done without notice.
I'm having an issue with the buildroot project because of this.

**Comment by xfxyjwf** [comment]
Yes, I re-uploaded protobuf-cpp-3.3.0.tar.gz/zip. Would it help if I just take it down?

**Comment by Oppen** [comment]
We fixed The checksum, don't worry.

**Comment by sebastienvas** [comment]
This happened for 3.2.0 as well.

**Comment by xfxyjwf** [comment]
@sebastienvas I think what you saw is a duplicate of https://github.com/google/protobuf/issues/3619

**Comment by sebastienvas** [comment]
Yes thanks!
