### ISSUE TITLE
C# identifier deduplification fails in corner case 

### ISSUE THREAD

**Issue by jskeet** [google/protobuf#309]
Sample proto:

```
syntax = "proto3";

package foo;

message A {
    int32 _A = 1;
}
```

Note that `A` and `_A` are the same after underscore stripping, so the deduplification code adds an underscore to the property name - which then collides with the field name:

```
private int A_;
public bool HasA_ {
  get { return hasA_; }
}
public int A_ {
  get { return A_; }
}
```

This was originally a problem in the previous C# code gen too:
https://github.com/jskeet/protobuf-csharp-port/issues/13

Looks like it was fixed by this change:
https://github.com/jskeet/protobuf-csharp-port/commit/c7b23c17979e93fb91be6e9a35ec0aef4a73704d

(That may not be directly applicable in the C++ codebase, but it's a good starting point.)

**Comment by anandolee** [comment]
@jskeet, we are cleaning up issues. Can you help to verify if this is fixed?

**Comment by jskeet** [comment]
No, this is still broken. I've updated the sample .proto file, but we still end up with:

```csharp
private int A_;
public int A_ {
    get { return A_; }
    set {
        A_ = value;
    }
}
```

It might be okay to close it as "won't fix" though...

**Comment by anandolee** [comment]
Will not fix it.
