### ISSUE TITLE
16 bit integer / unsigned integer support AND/OR FP16 support

### ISSUE THREAD

**Issue by DavidNorman** [google/protobuf#3091]
In tensorflow it would be useful to define an FP16 type.  Since many compilers don't support this natively, uint16 is used as an equivalent for storage and transmission.

Currently in TF, uint32 is used, which is both wasteful and prevents mapping constant arrays directly to the protobuf underlying buffer.

Could you please add uint16 and int16 to protobuf, and ideally also fp16.

**Comment by xfxyjwf** [comment]
It's unlikely that we will ever add a new field type to protobuf. The only viable solution is to use the length-delimited field type to mimic other field types but it also doesn't actually save anything compared to uint32.
