### ISSUE TITLE
Timestamp TZ offsets

### ISSUE THREAD

**Issue by dcarp** [google/protobuf#3093]
The [timestamp.proto](https://github.com/google/protobuf/blob/master/src/google/protobuf/timestamp.proto#L106) file documents that only UTC (Z suffix) is supported. The conformance tests [TimestampWithPositiveOffset](https://github.com/google/protobuf/blob/master/conformance/conformance_test.cc#L1996) and [TimestampWithNegativeOffset](https://github.com/google/protobuf/blob/master/conformance/conformance_test.cc#L2000) require other TZ offsets as well. Please correct one or the other.

**Comment by xfxyjwf** [comment]
The JSON serializer must only use Z suffix, but the parser should accept other timezones. The comment in timestamp.proto needs some more clarification.
