### ISSUE TITLE
protobuf-java 3 and protobuf-java 2 compatibility

### ISSUE THREAD

**Issue by jonefeewang** [google/protobuf#3097]
hi guys, would you please provide a shaded version protobuf-java 3, since it is  not compatible with protobuf-java 2. Using protobuf-java3 in legancy system with protobuf-2 bundled is impossible .

**Comment by xfxyjwf** [comment]
We decided not to provide an official shaded version because we don't want to allow users to mix two proto Java runtimes. You can always shade it yourself though.
