### ISSUE TITLE
[javascript] Failed to deserialize protobuf message which has other message types.

### ISSUE THREAD

**Issue by c-bata** [google/protobuf#3098]
## Summary

I use the protobuf in javascript. And I can properly deserialize the following message type:

```
message ProfileResponse {
    string uid = 1;
    string username = 2;
    string icon_url = 3;
    string website_url = 4;
    int64  created_at = 5;
    int64  updated_at = 6;
}
```

But the following message cannot:

```
message ConfirmProfileResponse {
    bool has_profile = 1;
    ProfileResponse profile = 2;
}
```

Error message is below:

```
goog.asserts.AssertionError {message: "Failure: Invalid wire type", reportErrorToServer: true, messagePattern: "Failure: Invalid wire type", stack: "AssertionError↵    at new goog.asserts.AssertionEr…bundle?platform=ios&dev=true&minify=false:7157:15"}
```

This error has occured when protobuf message has other message type (like `ProfileResponse profile = 2`).

#### Deserialize binary

We deserialize protobuf binary like:

```
import { ConfirmProfileResponse } from '../proto/profile_pb';

export const TimelineActionCreators = {
    fetchProfile(){
        fetch("http://our-end-point.com/").then((response) => {
            return response.arrayBuffer()
        }).then((b) => {
            const bytes = new Uint8Array(b);
            const message = ConfirmProfileResponse.deserializeBinary(bytes);  // Raised here :(
            console.log(message.getProfile());
        }).catch((error) => {
            console.log(error);
        });
    }
};
```

protoc command for generating `proto/profile_pb.js` 

```
protoc --proto_path=. --js_out=library=proto,binary:javascript *.proto
```

#### Environment

* libprotoc 3.2.0
* react-native 0.44.0
    * ES2015

**Comment by acozzette** [comment]
@c-bata Could you perhaps post the raw message bytes here (maybe formatted in hex)? That would make it easier to figure out what's going wrong. It sounds like somehow the message is getting corrupted or is not the right type.

**Comment by c-bata** [comment]
Sorry, I forgot to response and development of my react-native application is already finished.
So I close this. Thanks.
