### ISSUE TITLE
How can I install protobuf-3.3.1 on HP UX from source code?

### ISSUE THREAD

**Issue by sloagnidea** [google/protobuf#3099]
GCC 4.2.3

**Comment by xfxyjwf** [comment]
Did you run into problems when installing 3.3.1? If so what error did you see?

The install instructions are in this page:
https://github.com/google/protobuf/tree/master/src

**Comment by sloagnidea** [comment]
src/google/protobuf/stubs/atomicops.h:231: error: #error GOOGLE_PROTOBUF_ATOMICOPS_ERROR

**Comment by mascojames** [comment]
CMake is only used for the Windows build currently. Use the `./configure` script to build using GCC

**Comment by sloagnidea** [comment]
I used CMake to compile successfully in ubuntu 16.04.
