### ISSUE TITLE
proto3 with arena crashes with segfault in Clear() method in C++ 

### ISSUE THREAD

**Issue by romange** [google/protobuf#310]
Sample code:

    TEST_F(ProtoTest, Clear) {
      Arena arena;
      Person* person = Arena::CreateMessage<Person>(&arena);
      person->mutable_account()->set_bank_name("Foo");
      person->Clear();
    }

The code below is generated with proto3 mode and it fails at the marked line because account_ was not allocated with new but with arena.

    void Person::Clear() {
      name_.ClearToEmpty(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),     GetArenaNoVirtual());
      id_ = GOOGLE_LONGLONG(0);
      email_.ClearToEmpty(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),     GetArenaNoVirtual());
      if (account_ != NULL) delete account_;            // ************
      account_ = NULL;
      phone_.Clear();
      phone2_.Clear();
      tag_.Clear();
    }

**Comment by xfxyjwf** [comment]
@cfallin, could you take a look?

**Comment by cfallin** [comment]
@romange, thanks for the report! I've reproduced the bug and it's an unfortunate interaction of the removal of field presence with arena support.

@xfxyjwf, I've sent you a change internally. @romange, it should appear in our GitHub repo once reviewed internally and on our next GitHub sync. Alternately, I can cherry-pick if critical.

**Comment by romange** [comment]
Thanks, it's not urgent
