### ISSUE TITLE
Reccommendation for proto3

### ISSUE THREAD

**Issue by Phlip79** [google/protobuf#3105]
Why is it recommended to trying proto3 only: 
•If you want to try using protocol buffers in one of our newly-supported languages. 
•If you want to try our new open-source RPC implementation gRPC – we recommend using proto3 for all new gRPC servers and clients as it avoids compatibility issues. 

If I'm starting on a new project and neither of these conditions are valid, is there a reason I should not be using proto3?

**Comment by acozzette** [comment]
I think the documentation [here](https://developers.google.com/protocol-buffers/docs/overview#introducing-proto3) that you're referring to is out of date and is from when proto3 was still in beta. I'll see if I can update that documentation. Today we would recommend using proto3 for new projects.

**Comment by acozzette** [comment]
I've now updated the documentation. Thanks for reporting this @Phlip79.
