### ISSUE TITLE
Google Bazel support?

### ISSUE THREAD

**Issue by huahang** [google/protobuf#311]
The newly released bazel seems to be a very promising build tool. Can we add Google Bazel build for protobuf?

http://bazel.io/

Thanks,
Huahang

**Comment by xfxyjwf** [comment]
Seems it's the time to open-source the BUILD files we have been using internally for building protobufs :)

And just for the reference, an ex-googler has already written some BUILD files for protobuf here: https://github.com/mzhaom/trunk/tree/master/third_party/protobuf

**Comment by kjiwa** [comment]
The bazel-examples repository has rules for building protoc: https://github.com/google/bazel-examples/tree/master/protobuf-2.5.0.

**Comment by xfxyjwf** [comment]
There is a feature request for proto_library rule in bazel: https://github.com/google/bazel/issues/52

Before it's implemented in bazel, we can probably provide it as a wrapper script first.
