### ISSUE TITLE
Inconsistencies between protobuf.so and google/protobuf

### ISSUE THREAD

**Issue by bshaffer** [google/protobuf#3110]
There are classes and functions autoloaded in `google/protobuf` that are not part of the `protobuf.so` extension. The API surface should be identical.

Here are some commands to see which classes exist when `protobuf.so` is enabled:

```
$ php --re protobuf | head -1
Extension [ <persistent> extension #65 protobuf version 3.3.0 ] {
$ php -r "var_dump(class_exists('Google\Protobuf\Internal\Descriptor'));"
bool(true)
$ php -r "var_dump(class_exists('Google\Protobuf\Internal\FileDescriptor'));"
bool(false)
$ php -r "var_dump(function_exists('Google\Protobuf\Internal\getClassNamePrefix'));"
bool(false)
```

Then I disabled the extension and used the `google/protobuf:3.3.0` library:

```
$ php --re protobuf | head -1
Exception: Extension protobuf does not exist
$ composer require google/protobuf:3.3.0
$ php -r "require 'vendor/autoload.php'; var_dump(class_exists('Google\Protobuf\Internal\Descriptor'));"
bool(true)
$ php -r "require 'vendor/autoload.php'; var_dump(class_exists('Google\Protobuf\Internal\FileDescriptor'));"
bool(true)
$ php -r "require 'vendor/autoload.php'; var_dump(function_exists('Google\Protobuf\Internal\getClassNamePrefix'));"
bool(true)
```

These classes exist in the protobuf library but are missing in the extension:
- Google\Protobuf\Internal\FileDescriptor
- Google\Protobuf\Internal\OneofDescriptor
- Google\Protobuf\Internal\EnumValueDescriptor
- Google\Protobuf\Internal\FieldDescriptor
- Google\Protobuf\Internal\FieldDescriptor

These functions exist in the protobuf library but are missing in the extension:
- Google\Protobuf\Internal\getClassNamePrefix
- Google\Protobuf\Internal\getClassNameWithoutPackage
- Google\Protobuf\Internal\getFullClassName

**Comment by TeBoring** [comment]
These classes are implementation detail of php impl and is not part of
public API.

**Comment by bshaffer** [comment]
@TeBoring Can you elaborate on this? It seems like we should remove these classes if they are not part of the API.

**Comment by TeBoring** [comment]
The classes you mentioned are all from the Internal namespace, which should
not be used by users. All classes from the Internal space is not part of
public API. However, we cannot remove them.
