### ISSUE TITLE
Generated Java code not valid

### ISSUE THREAD

**Issue by lundefugl** [google/protobuf#3112]
We got a protobuf definition from an external supplier. We are not able to change the names in the file.
Unfortunately the generated code (Protobuf 3.3.0) in Java is not compileable. The Version 2.6.1 workes fine.

It's a problem with the basic Java class "Object". The generator should always generate the complete name (with package) for the Java class "java.lang.Object".

A stripped sample is attached.
[Object.proto.txt](https://github.com/google/protobuf/files/1009856/Object.proto.txt)

**Comment by xfxyjwf** [comment]
@lundefugl Thanks for the report. Could you also help provide a fix?

**Comment by lundefugl** [comment]
Sorry. At the moment I don't have time to create a build environment and to analyze the code.

**Comment by lundefugl** [comment]
Is it already known when someone looks at the pull request?

**Comment by xfxyjwf** [comment]
@lundefugl Sorry for the late response. I just merged the pull request. Thanks for fixing it!

**Comment by lundefugl** [comment]
Thank you. We tested the version 3.4.0 and it workes fine.
