### ISSUE TITLE
test.exe error

### ISSUE THREAD

**Issue by fpemdksk** [google/protobuf#3116]
hi my os window 7, im compiled and text.exe but i get error

![default](https://cloud.githubusercontent.com/assets/26478345/26281044/f09d0472-3e24-11e7-87d7-207e6976e0e9.png)

what is problem?

**Comment by xfxyjwf** [comment]
The error message contains incorrect file paths and that suggests an incorrect locale setting. That's likely also the cause of the test failure. You can safely ignore it though. Protobuf should still be able to function correctly despite the test failure.
