### ISSUE TITLE
Documentation of PHP generated classes

### ISSUE THREAD

**Issue by michaelbausor** [google/protobuf#3118]
Getter and setter methods on generated PHP classes should include phpdoc in the method documentation. E.g. `@return` for getters and `@param` for setters.

**Comment by mlosev** [comment]
+1 for phpdoc, it's very important for modern IDE and large codebases

**Comment by ev4ern** [comment]
+1 for phpdoc

**Comment by TeBoring** [comment]
Will add more detail in the phpdoc.

**Comment by Yakoot** [comment]
+1

**Comment by publiteer** [comment]
+1

**Comment by Grey2k** [comment]
+1 for phpdoc

**Comment by TeBoring** [comment]
FYI, currently, the phpdoc getter and setter only contains the field definition:
https://github.com/google/protobuf/blob/master/php/src/Google/Protobuf/Internal/DescriptorProto.php#L85
Would that be enough?

**Comment by michaelbausor** [comment]
I think that we want the `@return` and `@param` annotations. These are used by IDEs like PHPStorm to provide autocompletion, and by documentation generators
