### ISSUE TITLE
PHP: support proto option to specify namespace

### ISSUE THREAD

**Issue by michaelbausor** [google/protobuf#3122]
Similar to other languages, it would be useful to specify the namespace of the generated protobuf classes using an option in the proto file. See for example: https://github.com/googleapis/googleapis/blob/master/google/logging/v2/logging.proto#L28 which specifies namespace/package options for C#, Go and Java.

**Comment by TeBoring** [comment]
Fixed in #3162. Will be released in 3.4. ETA end of July.
