### ISSUE TITLE
cpp convert message to a simple json object

### ISSUE THREAD

**Issue by cipriancaba** [google/protobuf#3135]
I have the following message:
```
message JsonObject {
  google.protobuf.Struct obj = 1;
}
```

The following c++ code:
```
  JsonObject jsonObject;
  auto fields = jsonObject.mutable_obj()->mutable_fields();

  google::protobuf::Value v;
  v.set_null_value(google::protobuf::NULL_VALUE);

  (*fields)["FIELD1"] = v;
  (*fields)["FIELD2"] = v;

  google::protobuf::util::JsonPrintOptions options;
  string result;
  MessageToJsonString(jsonObject, &result, options);
```

And the following output:
```
{"obj":{"FIELD2":null,"FIELD1":null}}
```

I want instead to obtain something like:
```
{"obj":{"FIELD2","FIELD1"}}
```

**Comment by xfxyjwf** [comment]
What you want doesn't seem to be valid JSON. Do you want:
```json
{"obj":["FIELD2", "FIELD1"]}
```
instead?

**Comment by VTornoreanu** [comment]
So, after fiddling around with making that non valid JSON work, I realised that the server was actually expecting an Array like you pointed which is easily done with a repeated string..

Sorry for the confusion

**Comment by cipriancaba** [comment]
So, after fiddling around with making that non valid JSON work, I realised that the server was actually expecting an Array like you pointed which is easily done with a repeated string..

Sorry for the confusion
