### ISSUE TITLE
undefined reference to symbol '_ZN6google8protobuf9Timestamp9MergeFromERKS1_'

### ISSUE THREAD

**Issue by jopedroliveira** [google/protobuf#3143]
Hi everyone,

I'm on Ubuntu 14, developing in C++.
I just found this error while compiling a program.
protobuf compiles well but I'm not able to use it because every time I try to use it on my program, or even in the example program. 

The error looks pretty weird, and I could not figure out how to fix it. Anyone can help?

> 
> /usr/bin/ld: googleapis.ar(cloud_speech.pb.o): undefined reference to symbol '_ZN6google8protobuf9Timestamp9MergeFromERKS1_'
> //usr/local/lib/libprotobuf.so.12: error adding symbols: DSO missing from command line
>

**Comment by acozzette** [comment]
It sounds like you may mixing different protobuf versions; maybe linking generated code from one version with the libprotobuf from another version. Could you provide more details on what you are building and how?

**Comment by jopedroliveira** [comment]
I used another machine and was not able to reproduce the problem. Maybe It was related to different versions of protobuf. I think this issue is closed.
