### ISSUE TITLE
when I run makefile include pb.h , it tell me error, but I can compile it on other VM, I don.t why and how to solve it?

### ISSUE THREAD

**Issue by huacc** [google/protobuf#3146]
I paste the error info as follow, if I include EncOptvsCtl.pb.h it  shows:

EncOptvsCtl.pb.h:137:42: error: macro "des_set_key" requires 2 arguments, but only 1 given
   void set_key(const ::std::string& value);
                                          ^
EncOptvsCtl.pb.h:141:33: error: macro "des_set_key" requires 2 arguments, but only 1 given
   void set_key(const char* value);
                                 ^
EncOptvsCtl.pb.h:556:58: error: macro "des_set_key" requires 2 arguments, but only 1 given
 inline void MultiPart::set_key(const ::std::string& value) {
                                                          ^
EncOptvsCtl.pb.h:569:49: error: macro "des_set_key" requires 2 arguments, but only 1 given
 inline void MultiPart::set_key(const char* value) {
                                                 ^
httpAnalysis.cpp:42:24: error: macro "des_set_key" requires 2 arguments, but only 1 given
  mPart->set_key("ufile");
                        ^
httpAnalysis.cpp:47:23: error: macro "des_set_key" requires 2 arguments, but only 1 given
  mPart->set_key("text");
                       ^
In file included from /usr/include/openssl/des.h:101:0,
                 from DesFuns.h:5,
                 from MailParser.h:12,
                 from httpAnalysis.cpp:3:
EncOptvsCtl.pb.h:137:8: error: variable or field ‘des_set_key’ declared void
   void set_key(const ::std::string& value);
        ^
EncOptvsCtl.pb.h:141:8: error: variable or field ‘des_set_key’ declared void
   void set_key(const char* value);
        ^
EncOptvsCtl.pb.h:142:8: error: expected identifier before ‘(’ token
   void set_key(const char* value, size_t size);
        ^
EncOptvsCtl.pb.h:142:8: error: expected identifier before ‘&’ token
   void set_key(const char* value, size_t size);
        ^
EncOptvsCtl.pb.h:556:24: error: variable or field ‘des_set_key’ declared void
 inline void MultiPart::set_key(const ::std::string& value) {
                        ^
In file included from MailParser.h:15:0,
                 from httpAnalysis.cpp:3:
EncOptvsCtl.pb.h:558:3: error: ‘key_’ was not declared in this scope
   key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
   ^
EncOptvsCtl.pb.h:558:81: error: ‘value’ was not declared in this scope
   key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
                                                                                 ^
EncOptvsCtl.pb.h:558:87: error: expected ‘}’ before ‘;’ token
   key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
                                                                                       ^
EncOptvsCtl.pb.h:569:13: error: ‘MultiPart’ has not been declared
 inline void MultiPart::set_key(const char* value) {
             ^
In file included from /usr/include/openssl/des.h:101:0,
                 from DesFuns.h:5,
                 from MailParser.h:12,
                 from httpAnalysis.cpp:3:
EncOptvsCtl.pb.h:569:24: error: variable or field ‘des_set_key’ declared void
 inline void MultiPart::set_key(const char* value) {
                        ^
In file included from /usr/local/include/google/protobuf/stubs/common.h:50:0,
                 from EncOptvsCtl.pb.h:9,
                 from MailParser.h:15,
                 from httpAnalysis.cpp:3:
EncOptvsCtl.pb.h:570:17: error: ‘value’ was not declared in this scope
   GOOGLE_DCHECK(value != NULL);
                 ^
In file included from MailParser.h:15:0,
                 from httpAnalysis.cpp:3:
EncOptvsCtl.pb.h:570:31: error: expected ‘}’ before ‘;’ token
   GOOGLE_DCHECK(value != NULL);
                               ^
EncOptvsCtl.pb.h:572:3: error: ‘key_’ does not name a type
   key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
   ^
EncOptvsCtl.pb.h:575:13: error: ‘MultiPart’ has not been declared
 inline void MultiPart::set_key(const char* value, size_t size) {
             ^
In file included from /usr/include/openssl/des.h:101:0,
                 from DesFuns.h:5,
                 from MailParser.h:12,
                 from httpAnalysis.cpp:3:
EncOptvsCtl.pb.h:575:24: error: variable or field ‘DES_set_key’ declared void
 inline void MultiPart::set_key(const char* value, size_t size) {
                        ^
EncOptvsCtl.pb.h:575:32: error: expected primary-expression before ‘const’
 inline void MultiPart::set_key(const char* value, size_t size) {
                                ^
EncOptvsCtl.pb.h:575:32: error: expected ‘)’ before ‘const’
In file included from MailParser.h:15:0,
                 from httpAnalysis.cpp:3:
EncOptvsCtl.pb.h:1308:1: error: expected declaration before ‘}’ token
 }  // namespace cloudscreen

**Comment by huacc** [comment]
It is a very difficult bug to find,  if I declare a para named key, it have a conflict with protobuf file. 
So In version 3.3.0  the user can't use para'name  as key. I think it can;t compile when user compile proto file.

**Comment by pherl** [comment]
It looks like a macro conflcits with des_set_key. Unfortuantely we won't be able to help. Maybe you could try `#undef set_key` and see that would solve the problem.
