### ISSUE TITLE
protocol buffer php

### ISSUE THREAD

**Issue by maurofabiani** [google/protobuf#3148]
i`m currently using google protocol buffer for the first time, i need to read a serialized file in php generated in c#. i dont know if im doing well, this is an example of my proto file:

syntax = "proto3";

message Dax {

    message StrategyCalculatedProperties {
        double mainUnderlyingPrice = 1;
        PayoffData payoff = 2;
        bool isCalendar = 3;
        double delta = 4;
        double gamma = 5;
        double theta = 6;
        double vega = 7;
        double rho = 8;
    }

    message PayoffData {
        double xMinValue = 1;
        double xMaxValue = 2;
    }

    StrategyCalculatedProperties CalculatedProperties = 4;
    string analysisDate = 12;
    string name = 13;
    string notes = 14;
    sint32 Proto_m_color = 18;
}
here is my code:

require_once("./pb/build/GPBMetadata/Dax.php"); 
require_once("./pb/build/Dax.php"); 
require_once("./pb/build/Dax_PayoffData.php");
require_once("./pb/build/Dax_StrategyCalculatedProperties.php");

$data=file_get_contents("./pb/daxdata.proto");
$result = $mydax->mergeFromString($data);
the point is i'm able to read all fileds for the main message but i cannot read anything about the message "StrategyCalculatedProperties" (nested message). to do that i simply use $sp = $mydax->getCalculatedProperties(); and the all getter from the class generated by protoc command. i googled a lot but i couldnt fine anything for php. can somebody help me? tnx in advance.

**Comment by TeBoring** [comment]
"to do that i simply use $sp = $mydax->getCalculatedProperties(); and the
all getter from the class generated by protoc command"
This is the correct way to get sub-message fields. It doesn't work?

**Comment by maurofabiani** [comment]
well, i realized my problem was not in my code but in the way the serialized file has been generated, specifically about "tags". also because i generated a file by myself using the same structure  and i can easily read it. so now the c# programmer is working on this. thanks for your reply.

**Comment by TeBoring** [comment]
Close it for now. Feel free to reopen it if there is still problem.
