### ISSUE TITLE
javalite generated code fails errorprone checks

### ISSUE THREAD

**Issue by mdusina** [google/protobuf#3151]
Two categories of errorprone issues are flagged when the generated lite classes are checked with errorprone:  MissingOverride (a warning) and FallThrough (an error).  It's not clear that these are actually problems, but since errorprone doesn't support excluding packages and the generated proto classes aren't marked as generated, it makes it difficult to use at all.  While not comprehensive, these are the unique issues I see from protos that use enums, repeated, optional, maps, sub-messages, imported messages, and reserved.  Again, this is with `option optimize_for = LITE_RUNTIME;`

See also: issue #2718

MissingOverride
- enum -- EnumLite
  - int getNumber() {}
  - com.google.protobuf.Internal.EnumLiteMap<T>
    - T findValueByNumber(int number) {}
- message -- FooOrBuilder
  - boolean hasFoo() {}
  - Foo getFoo() {}
  - com.google.protobuf.ByteString getFooBytes() {}
  - java.util.List<com.foo.FooPb.Foo> getFooList() {}
  - int getFooCount() {}
  - com.foo.FooPb.Foo getFoo(int index) {}
  - java.util.Map<K, V> getFooMap() {}
  - V getFooOrDefault(K key, V defaultValue) {}
  - V getFooOrThrow(K key) {}
  - boolean containsFoo(K key) {}
- message -- MessageLite
  - void writeTo(com.google.protobuf.CodedOutputStream output) {}
  - int getSerializedSize() {}
- message -- GeneratedMessageLite
  - Object dynamicMethod(com.google.protobuf.GeneratedMessageLite.MethodToInvoke method, Object arg0, Object arg1) {}

FallThrough
- message -- GeneratedMessageLite
  - Object dynamicMethod(com.google.protobuf.GeneratedMessageLite.MethodToInvoke method, Object arg0, Object arg1) { /* MERGE_FROM_STREAM -> GET_DEFAULT_INSTANCE case */ }

**Comment by xfxyjwf** [comment]
This missing @Override are mostly because Java 1.5 errors out on @Override on an interface method. Though we no longer support Java 1.5 though so we should clean it up to add back the appropriate @Override annotations.

The fallthrough is intentionally. Note that we now only support using lite through the java-lite protoc plugin in the javalite branch.
