### ISSUE TITLE
PHP Fatal error:  Class 'Google\Protobuf\Internal\Message' not found 

### ISSUE THREAD

**Issue by fisnikhajredini** [google/protobuf#3155]
Im using php 5.5.9 for this project and i keep getting this error. I installed protobuf  from Source using these [instructions](https://github.com/google/protobuf/blob/master/php/README.md) and now after i compile the proto files, i cant seem to include them as i get this error `PHP Fatal error:  Class 'Google\Protobuf\Internal\Message' not found `. 

Added `extension=protobuf.so` in `/etc/php5/apach2/php.ini`
the file protobuf.so is located in `/usr/lib/php5/20121212/protobuf.so`

Do i need to link the library anywhere? Otherwise any suggestion is appreciated. 

**_EDIT_**
Tried to link the libraries: 
`export LD_LIBRARY_PATH=/usr/lib/php5/20121212`
`export LD_RUN_PATH=/usr/lib/php5/20121212/`
still the same.

**Comment by TeBoring** [comment]
Could you add -dextension=ABSOLUTE_PATH/protobuf.so when running php?

**Comment by TeBoring** [comment]
Close the issue for now. Feel free to reopen if there is still any problem.

**Comment by fisnikhajredini** [comment]
I have fixed that error by using composer and it worked! That was my solution.

**Comment by TeBoring** [comment]
I see. In that way, you are using the php implementation. If you want to use c extension, you need to let php find the protobuf.so.
