### ISSUE TITLE
A bug in GPBDictionary converting

### ISSUE THREAD

**Issue by KinderLi** [google/protobuf#3164]
I defined map<int32, int64> in the source proto file, but when the server put a value larger than 4294967296(2^32) and transfer to the iOS client, the value is incorrect. 
I found a bug from GPBDictionary.m in line 409:
valueToFill->valueInt64 = GPBCodedInputStreamReadInt32(&stream->state_);
I think it should be:
409 valueToFill->valueInt64 = GPBCodedInputStreamReadInt64(&stream->state_); 

                                                                        ^O^

**Comment by thomasvl** [comment]
Thanks!
