### ISSUE TITLE
Protoc for java generate the unexpected constructor for the Class with sub filed for itself

### ISSUE THREAD

**Issue by wxcsdb88** [google/protobuf#3192]
## The generate constructor in java should contains all fields defined in proto file
>In the linux go enviroment and use the protoc generate the `java`, `js`, `python` and `go` pb files through the `*.proto` files, the output `*.java` files is unexpected. The java class with the field and  type is the class itself may be lost the field.

## protobuf version
>protoc version 

**`libprotoc 3.2.0`** and **`libprotoc 3.3.0`**
>go version

**`go1.8.3 linux/amd64`**

## proto message
```
syntax = "proto3";
package protos;

option java_outer_classname = "TestMessage";

message Action{
    string id = 1;
    string desc = 2;
    Action action = 3;
}
```

## Generate Java file
```
public  static final class Action extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protos.Action)
      ActionOrBuilder {
    // Use Action.newBuilder() to construct.
    private Action(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Action() {
      id_ = "";
      desc_ = "";
    }
...
```
The constructor Action should be like
```
  private Action() {
      id_ = "";
      desc_ = "";
      action _=...;
    }
```
If like above, can convert to json with full fields(serialize the json and generate hash id) and keep the same with python, js and go.

**Comment by xfxyjwf** [comment]
All of id_, desc_, action_ are protobuf private fields. Why do you care about protobuf internal implementation? You should not rely on it for your code to work.

If you want to convert a proto message to JSON, please use com.google.protobuf.util.JsonFormat class instead.

**Comment by wxcsdb88** [comment]
Thks， I had solve it with the utils.
```
 /**
     * Convert protoByte to json string
     *
     * @param bt
     * @param message
     * @return
     */
    public static String protoByteToJson(byte[] bt, Message message) {
        Message obj = null;
        String jsonFormat = "";
        try {
            obj = message.getParserForType().parseFrom(bt);
            com.google.protobuf.util.JsonFormat.Printer printer = com.google.protobuf.util.JsonFormat.printer();
            jsonFormat = printer.omittingInsignificantWhitespace()
//                    .preservingProtoFieldNames()
                    .includingDefaultValueFields()
                    .print(obj);
            //todo
        } catch (Exception e) {
            e.printStackTrace();
        }
        return jsonFormat;
    }
```
