### ISSUE TITLE
Xcode analysis reports "Potential Leak" in generated pb.cc files

### ISSUE THREAD

**Issue by jcooper-korg** [google/protobuf#3195]
We're seeing this in all our generated pb.cc files (both in protobuf 3.1.0 and current release 3.3.0).

It's not clear to me whether it's simply a case that could never occur (heap allocation that is never freed when using arena).

Here's an example report, with the screen shots of Xcode's analysis:
```
core/API/Message/ClientMessages.pb.cc:2850:1: Potential leak of memory pointed to by 'temp'
core/API/Message/ClientMessages.pb.cc:2838:7: Assuming the condition is false
core/API/Message/ClientMessages.pb.cc:2842:31: Calling 'CheckpointRequest::New'
core/API/Message/ClientMessages.pb.cc:2731:1: Entered call from 'CheckpointRequest::Swap'
core/API/Message/ClientMessages.pb.cc:2732:10: Calling 'Arena::CreateMessage'
library/protobuf/src/google/protobuf/arena.h:254:25: Entered call from 'CheckpointRequest::New'
library/protobuf/src/google/protobuf/arena.h:256:9: Assuming 'arena' is equal to NULL
library/protobuf/src/google/protobuf/arena.h:257:14: Memory is allocated
core/API/Message/ClientMessages.pb.cc:2732:10: Returned allocated memory
core/API/Message/ClientMessages.pb.cc:2842:31: Returned allocated memory
core/API/Message/ClientMessages.pb.cc:2850:1: Potential leak of memory pointed to by 'temp'
```

Analysis Screenshots:
![screen shot 2017-06-07 at 10 07 54 am](https://user-images.githubusercontent.com/1987267/26891342-8b6e112a-4b69-11e7-8fb2-bdbf97688375.png)

![screen shot 2017-06-07 at 10 08 43 am](https://user-images.githubusercontent.com/1987267/26891343-8b76b514-4b69-11e7-86a8-fc7ec7b0cd41.png)

![screen shot 2017-06-07 at 10 08 52 am](https://user-images.githubusercontent.com/1987267/26891344-8b7723c8-4b69-11e7-8672-585e50449609.png)

And here are the proto, pb.cc and pb.h files, zipped:
[Archive.zip](https://github.com/google/protobuf/files/1058808/Archive.zip)

**Comment by xfxyjwf** [comment]
There is no memory leak as far as I can tell. When GetArenaNoVirtual() == NULL, the temp object will be allocated on heap and deleted appropriately. When GetArenaNoVirtual() != NULL, the object is allocated inside the arena and it doesn't need to be explicitly deleted because the arena owns the memory.

**Comment by gerben-s** [comment]
This is WAI

**Comment by ShibuRaja** [comment]
How to reproduce these leaks statically via xcode analyzer ?  , I am having xcode version 15.4

**Comment by ShibuRaja** [comment]
How to reproduce these leaks statically via xcode analyzer ? , I am having xcode version 15.4
