### ISSUE TITLE
json default value for string is an empty string instead of null

### ISSUE THREAD

**Issue by plemanach** [google/protobuf#3199]
Hello,

When serializing a protobuf object to json, default values for string are empty instead of null ?

```csharp
using (System.IO.StringWriter sw = new System.IO.StringWriter())
{
    var formater = new JsonFormatter(new JsonFormatter.Settings(true));
    formater.WriteValue(sw, this);
    return sw.ToString();
}
```

**Comment by jskeet** [comment]
Do you mean it *is* returning an empty string? If so, that's what I'd expect - after all, that's what you get if you create a new message and ask for its string value.

**Comment by plemanach** [comment]
you are right why the default value for a string is empty instead of null like a normal c# class when you create a message  ?

**Comment by jskeet** [comment]
That's the way protobuf is defined - string is deemed to be a scalar value type. See https://developers.google.com/protocol-buffers/docs/proto3

**Comment by plemanach** [comment]
Thank you it look like a odd choice knowing that most languages would have null as default for a string but I guess that is not a blocker.
