### ISSUE TITLE
C#: IDisposable.Dispose not being called

### ISSUE THREAD

**Issue by grant-d** [google/protobuf#3204]
Any reason why in `protobuf/csharp/src/Google.Protobuf/MessageExtensions.cs` (and possibly elsewhere) the `IDisposable` idiom (or explicit `.Dispose()`) is not being called? 

Was:
```
        public static void MergeFrom(this IMessage message, ByteString data)
        {
            ...
            CodedInputStream input = data.CreateCodedInput();
            message.MergeFrom(input);
            input.CheckReadEndOfStreamTag();
        }
```

Should probably be:
```
        public static void MergeFrom(this IMessage message, ByteString data)
        {
            ...
            using (var input = data.CreateCodedInput())
            {
                message.MergeFrom(input);
                input.CheckReadEndOfStreamTag();
            }
        }
```

I am happy to PR, but maybe there's a reason

**Comment by grant-d** [comment]
Note that `CodedInputStream.Dispose` also needs to be changed:

```
        public void Dispose()
        {
            if (!leaveOpen)
            {
                input?.Dispose(); // <-- Note conditional Dispose() since input may be null
            }
        }
```

**Comment by jskeet** [comment]
`ByteString.CreateCodedInput` creates a `CodedInputStream` that doesn't need to be disposed, basically. There'd never be a stream to dispose.

`Dispose` is fine as-is, but the constructors should be changed to adhere to the `leaveOpen` description of it always being `true` when there's no stream. (I'll do that in a separate PR.)

**Comment by jskeet** [comment]
Filed #3209 for the last part.

**Comment by grant-d** [comment]
Thanks Jon.

**Comment by grant-d** [comment]
Actually this is still an issue in a different circumstance.
The following code throws a `NullReferenceException` due to the stream being implicitly `null`;

     var foo = new byte[] { 1, 2 };
     using (var input = new CodedInputStream(foo))
     {
     } // Throws here (since `Dispose` sees that `leaveopen` is `false` so tries to free a `null` stream)

Arguably the caller should know that `using` is not necessary here, but I think that's a leaky abstraction. The `using` idiom should do the right thing regardless.

**Comment by grant-d** [comment]
Seems to be a duplicate of https://github.com/google/protobuf/pull/3215
