### ISSUE TITLE
Python including_default_value_fields does not work for singular message types

### ISSUE THREAD

**Issue by ewang** [google/protobuf#3210]
Looks like `google.protobuf.json_format._RegularMessageToJsonObject` intentionally skips over singular message types, which results singular message types and the Struct WKT being omitted in the JSON output even with `including_default_value_fields = True`.

The default values for Struct WKT should serialize to `{}` and singular message types to `null` respectively.

**Comment by anandolee** [comment]
It is documented "Singular message fields and oneof fields are not affected by this option."
https://github.com/google/protobuf/blob/39f9b43219bc5718b659ed72a2130a7b2ce66108/python/google/protobuf/json_format.py#L96

**Comment by ewang** [comment]
@anandolee I believe the Proto3 JSON spec does state that the default value for message type as well as the WKT wrapper types can be null. The Python json_format module currently does not seem to conform to the spec.

**Comment by anandolee** [comment]
Proto3 JSON spec states "When parsing, a null value is accepted for all field types."

@xfxyjwf who wrote Proto3 JSON spec. Do you think it is a bug of Go?

**Comment by ewang** [comment]
@anandolee If this helps clarify, at least for the WKT wrappers.proto types: "Wrappers use the same representation in JSON as the wrapped primitive type, except that null is allowed and preserved during data conversion and transfer.", specifically the part about preserving null values during data conversion/transfer.

In this case even w/ including_default_value_fields = True, we simply omit the fields corresponding to the unset WKT wrapper types (StringValue, DoubleValue, etc...).

**Comment by xfxyjwf** [comment]
@ewang The comment of "null is allowed and preserved during data conversion and transfer" is probably a bit misleading. It doesn't mean "null" will always be printed in proto3 JSON. Actually all implementations I know of by default don't print "null" value in JSON. The comment is supposed to mean "unlike regular primitive types, a null value for wrapper type can be distinguished from 0 (or false), and that state is maintained in proto-to-JSON and proto-to-binary conversion".

As to whether it should print a null value if including_default_value_fields = true, I don't have strong opinion either way. Both should be accepted and treated the same by proto3 JSON parser. What's your use case for a null value of absent singular message fields?

**Comment by ewang** [comment]
@xfxyjwf Here's a particular use case that we have ran into:

```
message Test {
    google.protobuf.StringValue name = 1;
}
```

A name value of '' is not treated the same way as a name value of null for our particular use case. In those cases, it was recommended that we use `google.protobuf.StringValue` instead of `string` to be able to differentiate between the null and 0 value cases. I think the JSON serialization output (when including_default_value_fields) is set should also be consistent in this case instead of omitting the field.

When including_default_value_fields is set to True, json_format currently emits the 0 values for the primitive types, so I think it's more consistent to emit the equivalent "default" values for the Wrapper types (and by extension singular message types) as null.

**Comment by xfxyjwf** [comment]
Singular message fields are different from primitive fields. This difference is a special-case in proto3 design in a sense. I don't feel like there is a need to make singular message fields behave more like primitive fields. Right now we don't print fields that support field presence but are unset. That includes singular message fields and oneof fields. The current behavior is actually consistent in that perspective.

In any case, I don't think not printing null values will cause any interoperability issues. If you actually need it to be printed as null for some reason, we can consider that and probably provide a different flag. But otherwise python json_format is working as intended.

**Comment by ewang** [comment]
@xfxyjwf Would you say the official stance on the default value for message types as well as WKT types such as IntValue, StringValue, DoubleValue, etc is undefined and thus not included in the output when including_default_value_fields is set to True?

**Comment by xfxyjwf** [comment]
@ewang Singular message fields support field presence, so it can be present or not present, and there are APIs to check their presence. If a singular message field is not present, it will not be included in JSON output.
