### ISSUE TITLE
when i use bazel to build tensorflow ，get error that no such package '@protobuf/

### ISSUE THREAD

**Issue by mmdlearn** [google/protobuf#3212]
ERROR: C:/windows/system32/tensorflow/tensorflow/tools/pip_package/BUILD:61:1: error loading package 'tensorflow/contrib
/session_bundle': Encountered error while reading extension file 'protobuf.bzl': no such package '@protobuf//': Tracebac
k (most recent call last):
        File "C:/windows/system32/tensorflow/tensorflow/workspace.bzl", line 117
                _apply_patch(repo_ctx, repo_ctx.attr.patch_file)
        File "C:/windows/system32/tensorflow/tensorflow/workspace.bzl", line 108, in _apply_patch
                _execute_and_check_ret_code(repo_ctx, cmd)
        File "C:/windows/system32/tensorflow/tensorflow/workspace.bzl", line 92, in _execute_and_check_ret_code
                fail("Non-zero return code({1}) when ..., <2 more arguments>))
Non-zero return code(127) when executing 'C:\tools\msys64\usr\bin\bash.exe -c patch -p1 -d C:/users/godw/appdata/local/t
emp/_bazel_godw/nseddbsr/external/protobuf -i C:/windows/system32/tensorflow/third_party/protobuf/add_noinlines.patch':
Stdout:
Stderr: /usr/bin/bash: patch: command not found
 and referenced by '//tensorflow/tools/pip_package:simple_console_for_windows'.
ERROR: Analysis of target '//tensorflow/tools/pip_package:build_pip_package' failed; build aborted.
INFO: Elapsed time: 15.712s

**Comment by Spenhouet** [comment]
I think i had a similar issue. Mysys is missing the patch command. You need to install it.
I think i did this with the command `pacman -Syuu patch` in the command line.

Maybe it also helps to follow some of these steps: [Bazel build with Windows](https://bazel.build/versions/master/docs/windows.html)

Sadly i can't build tensorflow on windows too... i just can't get it to work in anyway. :( I'm totally stuck but i really would need this to work.

**Comment by xfxyjwf** [comment]
This seems to be a problem of your WORKSPACE file. You need to import protobuf lib in your WORKSPACE file. For a working example using bazel with protobufs, you can take a look at our example here:
https://github.com/google/protobuf/blob/master/examples/BUILD#L13

Though since you are using bazel windows (which is at its very early stage of support), I suspect it's more likely to be a bazel issue here. You can probably try to ask it on a bazel forum instead.
