### ISSUE TITLE
Dose Objective-C target supports tvOS?

### ISSUE THREAD

**Issue by tang3w** [google/protobuf#3217]
If it supports, please specify the tvOS deployment target in Protobuf.podspec. Thanks.

**Comment by welshm** [comment]
Is there anything I need to do to force this to be picked up by Cocoapods? I'm running into an issue where it can't find the tvOS build.

**Comment by thomasvl** [comment]
I don't believe the pod has been updated yet.  I there is a full protobuf release coming that will take care of picking this up.
