### ISSUE TITLE
ubuntu14 protobuf-cpp-3.X command_line_interface_unittest.cc error

### ISSUE THREAD

**Issue by 331527583** [google/protobuf#3219]
when i run 'make check' on ubuntu14.04.01 platform.all of the protobuf-cpp-VERSION-3.X  have error at the same place.And my gcc is 'gcc (Ubuntu 5.4.1-2ubuntu1~14.04) 5.4.1 20160904'.

below this ,there will be details of 'src/test-suite.log ' about the command_line_interface_unittest.cc's output.
[----------] 68 tests from CommandLineInterfaceTest
[ RUN      ] CommandLineInterfaceTest.BasicOutput
[       OK ] CommandLineInterfaceTest.BasicOutput (1 ms)
[ RUN      ] CommandLineInterfaceTest.BasicPlugin
google/protobuf/compiler/command_line_interface_unittest.cc:399: Failure
Value of: error_text_
  Actual: "ls: \xE5\x88\x9D\xE5\xA7\x8B\xE5\x8C\x96\xE6\x9C\x88\xE4\xBB\xBD\xE5\xAD\x97\xE7\xAC\xA6\xE4\xB8\xB2\xE5\x87\xBA\xE9\x94\x99\n"
Expected: ""
[  FAILED  ] CommandLineInterfaceTest.BasicPlugin (302 ms)
[ RUN      ] CommandLineInterfaceTest.GeneratorAndPlugin
google/protobuf/compiler/command_line_interface_unittest.cc:399: Failure
Value of: error_text_
  Actual: "ls: \xE5\x88\x9D\xE5\xA7\x8B\xE5\x8C\x96\xE6\x9C\x88\xE4\xBB\xBD\xE5\xAD\x97\xE7\xAC\xA6\xE4\xB8\xB2\xE5\x87\xBA\xE9\x94\x99\n"
Expected: ""
[  FAILED  ] CommandLineInterfaceTest.GeneratorAndPlugin (36 ms)
[ RUN      ] CommandLineInterfaceTest.MultipleInputs
google/protobuf/compiler/command_line_interface_unittest.cc:399: Failure
Value of: error_text_
  Actual: "ls: \xE5\x88\x9D\xE5\xA7\x8B\xE5\x8C\x96\xE6\x9C\x88\xE4\xBB\xBD\xE5\xAD\x97\xE7\xAC\xA6\xE4\xB8\xB2\xE5\x87\xBA\xE9\x94\x99\n"
Expected: ""
[  FAILED  ] CommandLineInterfaceTest.MultipleInputs (18 ms)
[ RUN      ] CommandLineInterfaceTest.MultipleInputsWithImport
google/protobuf/compiler/command_line_interface_unittest.cc:399: Failure
Value of: error_text_
  Actual: "ls: \xE5\x88\x9D\xE5\xA7\x8B\xE5\x8C\x96\xE6\x9C\x88\xE4\xBB\xBD\xE5\xAD\x97\xE7\xAC\xA6\xE4\xB8\xB2\xE5\x87\xBA\xE9\x94\x99\n"
Expected: ""
[  FAILED  ] CommandLineInterfaceTest.MultipleInputsWithImport (19 ms)
[ RUN      ] CommandLineInterfaceTest.CreateDirectory
google/protobuf/compiler/command_line_interface_unittest.cc:399: Failure
Value of: error_text_
  Actual: "ls: \xE5\x88\x9D\xE5\xA7\x8B\xE5\x8C\x96\xE6\x9C\x88\xE4\xBB\xBD\xE5\xAD\x97\xE7\xAC\xA6\xE4\xB8\xB2\xE5\x87\xBA\xE9\x94\x99\n"
Expected: ""
[  FAILED  ] CommandLineInterfaceTest.CreateDirectory (18 ms)
[ RUN      ] CommandLineInterfaceTest.GeneratorParameters
google/protobuf/compiler/command_line_interface_unittest.cc:399: Failure
Value of: error_text_
  Actual: "ls: \xE5\x88\x9D\xE5\xA7\x8B\xE5\x8C\x96\xE6\x9C\x88\xE4\xBB\xBD\xE5\xAD\x97\xE7\xAC\xA6\xE4\xB8\xB2\xE5\x87\xBA\xE9\x94\x99\n"
Expected: ""
[  FAILED  ] CommandLineInterfaceTest.GeneratorParameters (17 ms)
[ RUN      ] CommandLineInterfaceTest.ExtraGeneratorParameters
[       OK ] CommandLineInterfaceTest.ExtraGeneratorParameters (1 ms)
[ RUN      ] CommandLineInterfaceTest.ExtraPluginParameters
google/protobuf/compiler/command_line_interface_unittest.cc:399: Failure
Value of: error_text_
  Actual: "ls: \xE5\x88\x9D\xE5\xA7\x8B\xE5\x8C\x96\xE6\x9C\x88\xE4\xBB\xBD\xE5\xAD\x97\xE7\xAC\xA6\xE4\xB8\xB2\xE5\x87\xBA\xE9\x94\x99\nls: \xE5\x88\x9D\xE5\xA7\x8B\xE5\x8C\x96\xE6\x9C\x88\xE4\xBB\xBD\xE5\xAD\x97\xE7\xAC\xA6\xE4\xB8\xB2\xE5\x87\xBA\xE9\x94\x99\n"
Expected: ""
[  FAILED  ] CommandLineInterfaceTest.ExtraPluginParameters (32 ms)
[ RUN      ] CommandLineInterfaceTest.UnrecognizedExtraParameters
[       OK ] CommandLineInterfaceTest.UnrecognizedExtraParameters (17 ms)
[ RUN      ] CommandLineInterfaceTest.Insert
google/protobuf/compiler/command_line_interface_unittest.cc:399: Failure
Value of: error_text_
  Actual: "ls: \xE5\x88\x9D\xE5\xA7\x8B\xE5\x8C\x96\xE6\x9C\x88\xE4\xBB\xBD\xE5\xAD\x97\xE7\xAC\xA6\xE4\xB8\xB2\xE5\x87\xBA\xE9\x94\x99\nls: \xE5\x88\x9D\xE5\xA7\x8B\xE5\x8C\x96\xE6\x9C\x88\xE4\xBB\xBD\xE5\xAD\x97\xE7\xAC\xA6\xE4\xB8\xB2\xE5\x87\xBA\xE9\x94\x99\n"
Expected: ""
[  FAILED  ] CommandLineInterfaceTest.Insert (34 ms)
[ RUN      ] CommandLineInterfaceTest.PathLookup
[       OK ] CommandLineInterfaceTest.PathLookup (1 ms)
[ RUN      ] CommandLineInterfaceTest.ColonDelimitedPath
[       OK ] CommandLineInterfaceTest.ColonDelimitedPath (0 ms)
[ RUN      ] CommandLineInterfaceTest.NonRootMapping
[       OK ] CommandLineInterfaceTest.NonRootMapping (0 ms)
[ RUN      ] CommandLineInterfaceTest.PathWithEqualsSign
[       OK ] CommandLineInterfaceTest.PathWithEqualsSign (0 ms)
[ RUN      ] CommandLineInterfaceTest.MultipleGenerators
[       OK ] CommandLineInterfaceTest.MultipleGenerators (1 ms)
[ RUN      ] CommandLineInterfaceTest.DisallowServicesNoServices
[       OK ] CommandLineInterfaceTest.DisallowServicesNoServices (0 ms)
[ RUN      ] CommandLineInterfaceTest.DisallowServicesHasService
[       OK ] CommandLineInterfaceTest.DisallowServicesHasService (0 ms)
[ RUN      ] CommandLineInterfaceTest.AllowServicesHasService
[       OK ] CommandLineInterfaceTest.AllowServicesHasService (1 ms)
[ RUN      ] CommandLineInterfaceTest.DirectDependencies_Missing_EmptyList
[       OK ] CommandLineInterfaceTest.DirectDependencies_Missing_EmptyList (0 ms)
[ RUN      ] CommandLineInterfaceTest.DirectDependencies_Missing
[       OK ] CommandLineInterfaceTest.DirectDependencies_Missing (0 ms)
[ RUN      ] CommandLineInterfaceTest.DirectDependencies_NoViolation
[       OK ] CommandLineInterfaceTest.DirectDependencies_NoViolation (1 ms)
[ RUN      ] CommandLineInterfaceTest.DirectDependencies_NoViolation_MultiImports
[       OK ] CommandLineInterfaceTest.DirectDependencies_NoViolation_MultiImports (0 ms)
[ RUN      ] CommandLineInterfaceTest.DirectDependencies_ProvidedMultipleTimes
[       OK ] CommandLineInterfaceTest.DirectDependencies_ProvidedMultipleTimes (1 ms)
[ RUN      ] CommandLineInterfaceTest.DirectDependencies_CustomErrorMessage
[       OK ] CommandLineInterfaceTest.DirectDependencies_CustomErrorMessage (0 ms)
[ RUN      ] CommandLineInterfaceTest.CwdRelativeInputs
[       OK ] CommandLineInterfaceTest.CwdRelativeInputs (0 ms)
[ RUN      ] CommandLineInterfaceTest.WriteDescriptorSet
[       OK ] CommandLineInterfaceTest.WriteDescriptorSet (1 ms)
[ RUN      ] CommandLineInterfaceTest.WriteDescriptorSetWithDuplicates
[       OK ] CommandLineInterfaceTest.WriteDescriptorSetWithDuplicates (0 ms)
[ RUN      ] CommandLineInterfaceTest.WriteDescriptorSetWithSourceInfo
[       OK ] CommandLineInterfaceTest.WriteDescriptorSetWithSourceInfo (1 ms)
[ RUN      ] CommandLineInterfaceTest.WriteTransitiveDescriptorSet
[       OK ] CommandLineInterfaceTest.WriteTransitiveDescriptorSet (0 ms)
[ RUN      ] CommandLineInterfaceTest.WriteTransitiveDescriptorSetWithSourceInfo
[       OK ] CommandLineInterfaceTest.WriteTransitiveDescriptorSetWithSourceInfo (0 ms)
[ RUN      ] CommandLineInterfaceTest.WriteDependencyManifestFileGivenTwoInputs
[       OK ] CommandLineInterfaceTest.WriteDependencyManifestFileGivenTwoInputs (1 ms)
[ RUN      ] CommandLineInterfaceTest.WriteDependencyManifestFileForAbsolutePath
[       OK ] CommandLineInterfaceTest.WriteDependencyManifestFileForAbsolutePath (0 ms)
[ RUN      ] CommandLineInterfaceTest.ParseErrors
[       OK ] CommandLineInterfaceTest.ParseErrors (0 ms)
[ RUN      ] CommandLineInterfaceTest.ParseErrorsMultipleFiles
[       OK ] CommandLineInterfaceTest.ParseErrorsMultipleFiles (1 ms)
[ RUN      ] CommandLineInterfaceTest.RecursiveImportFails
[       OK ] CommandLineInterfaceTest.RecursiveImportFails (0 ms)
[ RUN      ] CommandLineInterfaceTest.InputNotFoundError
[       OK ] CommandLineInterfaceTest.InputNotFoundError (0 ms)
[ RUN      ] CommandLineInterfaceTest.CwdRelativeInputNotFoundError
[       OK ] CommandLineInterfaceTest.CwdRelativeInputNotFoundError (1 ms)
[ RUN      ] CommandLineInterfaceTest.CwdRelativeInputNotMappedError
[       OK ] CommandLineInterfaceTest.CwdRelativeInputNotMappedError (0 ms)
[ RUN      ] CommandLineInterfaceTest.CwdRelativeInputNotFoundAndNotMappedError
[       OK ] CommandLineInterfaceTest.CwdRelativeInputNotFoundAndNotMappedError (0 ms)
[ RUN      ] CommandLineInterfaceTest.CwdRelativeInputShadowedError
[       OK ] CommandLineInterfaceTest.CwdRelativeInputShadowedError (0 ms)
[ RUN      ] CommandLineInterfaceTest.ProtoPathNotFoundError
[       OK ] CommandLineInterfaceTest.ProtoPathNotFoundError (1 ms)
[ RUN      ] CommandLineInterfaceTest.MissingInputError
[       OK ] CommandLineInterfaceTest.MissingInputError (0 ms)
[ RUN      ] CommandLineInterfaceTest.MissingOutputError
[       OK ] CommandLineInterfaceTest.MissingOutputError (0 ms)
[ RUN      ] CommandLineInterfaceTest.OutputWriteError
[       OK ] CommandLineInterfaceTest.OutputWriteError (0 ms)
[ RUN      ] CommandLineInterfaceTest.PluginOutputWriteError
[       OK ] CommandLineInterfaceTest.PluginOutputWriteError (16 ms)
[ RUN      ] CommandLineInterfaceTest.OutputDirectoryNotFoundError
[       OK ] CommandLineInterfaceTest.OutputDirectoryNotFoundError (1 ms)
[ RUN      ] CommandLineInterfaceTest.PluginOutputDirectoryNotFoundError
[       OK ] CommandLineInterfaceTest.PluginOutputDirectoryNotFoundError (16 ms)
[ RUN      ] CommandLineInterfaceTest.OutputDirectoryIsFileError
[       OK ] CommandLineInterfaceTest.OutputDirectoryIsFileError (1 ms)
[ RUN      ] CommandLineInterfaceTest.GeneratorError
[       OK ] CommandLineInterfaceTest.GeneratorError (0 ms)
[ RUN      ] CommandLineInterfaceTest.GeneratorPluginError
[       OK ] CommandLineInterfaceTest.GeneratorPluginError (17 ms)
[ RUN      ] CommandLineInterfaceTest.GeneratorPluginFail
[       OK ] CommandLineInterfaceTest.GeneratorPluginFail (18 ms)
[ RUN      ] CommandLineInterfaceTest.GeneratorPluginCrash
[       OK ] CommandLineInterfaceTest.GeneratorPluginCrash (3786 ms)
[ RUN      ] CommandLineInterfaceTest.PluginReceivesSourceCodeInfo
[       OK ] CommandLineInterfaceTest.PluginReceivesSourceCodeInfo (136 ms)
[ RUN      ] CommandLineInterfaceTest.PluginReceivesJsonName
[       OK ] CommandLineInterfaceTest.PluginReceivesJsonName (130 ms)
[ RUN      ] CommandLineInterfaceTest.PluginReceivesCompilerVersion
[       OK ] CommandLineInterfaceTest.PluginReceivesCompilerVersion (129 ms)
[ RUN      ] CommandLineInterfaceTest.GeneratorPluginNotFound
[       OK ] CommandLineInterfaceTest.GeneratorPluginNotFound (1 ms)
[ RUN      ] CommandLineInterfaceTest.GeneratorPluginNotAllowed
[       OK ] CommandLineInterfaceTest.GeneratorPluginNotAllowed (0 ms)
[ RUN      ] CommandLineInterfaceTest.HelpText
[       OK ] CommandLineInterfaceTest.HelpText (0 ms)
[ RUN      ] CommandLineInterfaceTest.GccFormatErrors
[       OK ] CommandLineInterfaceTest.GccFormatErrors (1 ms)
[ RUN      ] CommandLineInterfaceTest.MsvsFormatErrors
[       OK ] CommandLineInterfaceTest.MsvsFormatErrors (0 ms)
[ RUN      ] CommandLineInterfaceTest.InvalidErrorFormat
[       OK ] CommandLineInterfaceTest.InvalidErrorFormat (0 ms)
[ RUN      ] CommandLineInterfaceTest.ParseSingleCharacterFlag
[       OK ] CommandLineInterfaceTest.ParseSingleCharacterFlag (0 ms)
[ RUN      ] CommandLineInterfaceTest.ParseSpaceDelimitedValue
[       OK ] CommandLineInterfaceTest.ParseSpaceDelimitedValue (1 ms)
[ RUN      ] CommandLineInterfaceTest.ParseSingleCharacterSpaceDelimitedValue
[       OK ] CommandLineInterfaceTest.ParseSingleCharacterSpaceDelimitedValue (0 ms)
[ RUN      ] CommandLineInterfaceTest.MissingValueError
[       OK ] CommandLineInterfaceTest.MissingValueError (0 ms)
[ RUN      ] CommandLineInterfaceTest.MissingValueAtEndError
[       OK ] CommandLineInterfaceTest.MissingValueAtEndError (0 ms)
[ RUN      ] CommandLineInterfaceTest.PrintFreeFieldNumbers
[       OK ] CommandLineInterfaceTest.PrintFreeFieldNumbers (1 ms)
[----------] 68 tests from CommandLineInterfaceTest (4763 ms total)

who can give me some help?tks very much!

**Comment by pherl** [comment]
Looks like your terminal returned "初始化月份字符串出错" error message for those tests. I would suggest setting locale to en.US and try the test again. The failed tests are false positive anyways and I guess you can just ignore them and considered they pass.
