### ISSUE TITLE
./configure missing in latest 3.3 release?

### ISSUE THREAD

**Issue by tadeegan** [google/protobuf#3229]
I wget https://github.com/google/protobuf/archive/v3.3.0.tar.gz and unzip the tar but cannot run ./configure... I see configure.ac.  The installation instructions seem wrong.

**Comment by thomasvl** [comment]
What installation instructions are you trying to follow?

On the main README.md, [Protocol Compiler Installation](https://github.com/google/protobuf#protocol-compiler-installation), there is a link for the [C++ Installation Instructions](https://github.com/google/protobuf/blob/master/src/README.md) which should walk you though the whole process.

**Comment by tadeegan** [comment]
If you get the source from github, you need to generate the configure script first:

> $ ./autogen.sh
> This will download gmock source (which is used for C++ Protocol Buffer unit-tests) to the current directory and run automake, autoconf, etc. to generate the configure script and various template makefiles.
> 
> You can skip this step if you are using a release package (which already contains gmock and the configure script).
> 
> To build and install the C++ Protocol Buffer runtime and the Protocol Buffer compiler (protoc) execute the following:
> 
> $ ./configure
> $ make
> $ make check
> $ sudo make install
> $ sudo ldconfig # refresh shared library cache.

The instrucutions make it sound like the 'configure' executable should be there if you download a release version. I only see 'configure.ac' in the release.

```
$ wget https://github.com/google/protobuf/archive/v3.3.0.tar.gz
...
$ tar -tvf v3.3.0.tar.gz| grep configure
-rw-rw-r--  0 root   root     6851 Apr 26 16:32 protobuf-3.3.0/configure.ac
```
I don't know much about c++, sorry if I am reading the instructions improperly. Perhaps they need some clarification?

Also, ./autogen.sh also fails on both mac and ubuntu with:
```
configure.ac:30: error: possibly undefined macro: AC_PROG_LIBTOOL
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
```

**Comment by tadeegan** [comment]
Ah, I was now successful in running ./autogen.sh on my mac. It does indeed generate the 'configure' executable.

In "You can skip this step if you are using a release package (which already contains gmock and the configure script)." I think "this" can easily be confused with the ./autogen.sh.

**Comment by thomasvl** [comment]
`autogen.sh` is what makes the `configure` script, so the fact that it is failing is your real problem.

The comment in the docs about skipping that step has to do with download the zips from githup [Releases tab](https://github.com/google/protobuf/releases).  You'll notice those are different URLs, the url you are using appears to be github auto-creating a zip directly from the tag, so not a prepared release.

**Comment by tadeegan** [comment]
Okay. That does indeed seem like my error.  I'm having one more issue. After ./configure runs, I see:

$ make
make: *** No targets specified and no makefile found.  Stop.
$ make -f Makefile.in # Tried this too
Makefile.in:15: *** missing separator (did you mean TAB instead of 8 spaces?).  Stop.

Should I open a new bug?

**Comment by tadeegan** [comment]
Any plans to make an linux-arm release in the future?

**Comment by thomasvl** [comment]
Makefile.in isn't a Makefile, it has to be processed, so directly feeding it to make will fail.

What directory are you in when you did the make?  If you got through configure, there should be a Makefile generated.

**Comment by tadeegan** [comment]
Huh. Looks like running ./configure a second time help.  I can't repro when starting in a clean project though :/
