### ISSUE TITLE
Error when compile /usr/local/include/google/protobuf/descriptor.h

### ISSUE THREAD

**Issue by banv** [google/protobuf#3230]
I met an error when compile code using protobuf
Error messsage: 
`
/usr/local/include/google/protobuf/descriptor.h:1531:11: error: expected identifier
      TYPE,              // field type
`

Compiled environment: 
Mac OS X El Capitan
Version: 10.11.6

I think "TYPE" is special name, so could we change "TYPE" to another name (such as "ETYPE") ?

**Comment by xfxyjwf** [comment]
We can't change TYPE because it's part of public API. It seems you have a macro definition of TYPE somewhere in your code. To solve the issue, please `#undef TYPE` before including descriptor.h.
