### ISSUE TITLE
Ruby: InvalidByteSequenceError on instantiating messages with bytes

### ISSUE THREAD

**Issue by julienatshopify** [google/protobuf#3231]
Instantiating a message's bytes field with particular bytes fails:

```ruby
require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "AMessage" do
    optional :a_field, :bytes, 1
  end
end

AMessage = Google::Protobuf::DescriptorPool.generated_pool.lookup("AMessage").msgclass

AMessage.new(a_field: "\xF6") # Encoding::InvalidByteSequenceError: "\xF6" on UTF-8
```

Obviously, this makes the usage of `bytes` fields in Ruby impossible.

Thanks in advance!

**Comment by tenderlove** [comment]
@julienatshopify I don't think this is a problem with protobuf, but a problem with your script.  Later versions of Ruby default string literals to be UTF-8 encoded, but the string literal you have in your script contains bytes that are not valid UTF-8:

```
irb(main):001:0> x = "\xF6"
=> "\xF6"
irb(main):002:0> x.encoding
=> #<Encoding:UTF-8>
irb(main):003:0> x.valid_encoding?
=> false
irb(main):004:0>
```

If I change your sample program to this, it works:

```ruby
require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "AMessage" do
    optional :a_field, :bytes, 1
  end
end

AMessage = Google::Protobuf::DescriptorPool.generated_pool.lookup("AMessage").msgclass

p AMessage.new(a_field: "\xF6".b)
```

Note the `.b` at the end of the string literal.

Hope that helps!

**Comment by julienatshopify** [comment]
Many thanks, indeed, the default UTF-8 encoding was the issue.
