### ISSUE TITLE
getting value from Struct empty list_value and empty struct_value raises ValueError [python, bug]

### ISSUE THREAD

**Issue by sky-code** [google/protobuf#3238]
Python protobuf contains bug in `well_known_types.py` Struct implementation

When you add to struct empty list or empty dict (struct) and then trying to get it from that struct, it raise ValueError('Value not set')

I had written unit tests for this bug https://github.com/sky-code/protostruct/blob/master/test/test_struct.py (see test_empty_list_value_error and test_empty_dict_value_error)
and found a dirty hack that fixes a bug (see test_empty_list_hack and test_empty_dict_hack)

see also #3239

**Comment by anandolee** [comment]
Thanks for raise this bug. Empty list and struct errors have been fixed in internal code. Will be released in future
