### ISSUE TITLE
C++ - how to flush CodedOutputStreams without a Flush() function

### ISSUE THREAD

**Issue by colinfong** [google/protobuf#3254]
Is there another way to Flush the buffer (without using Dispose() because that doesn't exist either) without having to close and reopen the stream? There is no Flush() function for CodedOutputStreams. In my code, the CodedOutputStream writes to a GzipOutputStream. I can Flush the GzipOutputStream, but that yields errors when unzipping the file later on unless I delete and reinstantiating the CodedOutputStream which flushes the buffer properly. However, this has a memory/cpu overhead over many operations. Any suggestions?

**Comment by xfxyjwf** [comment]
I don't think performance is a concern here. Even in our micro-benchmark for small messages we are creating a new CodedOutputStream for each serialization and I never see anyone identifying that as a place to optimize. I would say constructing/destructing CodedOutputStream is cheap enough to not worry about its memory/cpu overhead.

**Comment by colinfong** [comment]
Thanks!

**Comment by Yuhta** [comment]
Is there a way to keep the `ByteCount` during the constructing/destructing?  How to set the byte count in the new instance?
