### ISSUE TITLE
is there a way to declare some conditions and validate in proto messages parameter

### ISSUE THREAD

**Issue by SeriousMa** [google/protobuf#3256]
```
syntax = "proto3";
package demo;

Simple {
    int32 id = 1;
    string email = 2;
}
```
i want to statement some conditions such as id SIZE(min = 2, max = 14) or email must contains ‘@’

**Comment by TeBoring** [comment]
You cannot do that in protobuf.

**Comment by SeriousMa** [comment]
I think if you can have a similar function, then you can save a lot of invalid rpc calls...
will you consider adding a similar function?
@TeBoring

**Comment by TeBoring** [comment]
I think this can be done as a side util library using protobuf's plugin. We
won't support it in the core library.

**Comment by htuch** [comment]
https://github.com/lyft/protoc-gen-validate is an OSS project to do this.

**Comment by SeriousMa** [comment]
@htuch https://github.com/SeriousMa/grpc-protobuf-validation i made my own 😁

**Comment by mwitkow** [comment]
#shamelessplug
https://github.com/mwitkow/go-proto-validators is another one for Golang with similar approach to lyft's
