### ISSUE TITLE
protobuf-mode broken w/ emacs 24.3.1

### ISSUE THREAD

**Issue by ArnJac** [google/protobuf#3257]
The latest protobuf-mode.el from melpa (20170526.950) seems to be broken with
emacs 24.3.1.

Even though the compilation process ends with two warnings emacs says that it cannot load protobuf-mode.

In order to get a working protobuf-mode I had to download the previous tagged version of protobuf-mode.el and place it somewhere emacs can find it, e.g. ~/.emacs.d/lisp.

**Comment by jgkamat** [comment]
I can't seem to reproduce. Here are the warnings you were talking about

```
Compiling file /root/.emacs.d/elpa/protobuf-mode-20170526.950/protobuf-mode-pkg.el at Thu Aug 10 02:15:23 2017
Entering directory `/root/.emacs.d/elpa/protobuf-mode-20170526.950/'
^L
Compiling file /root/.emacs.d/elpa/protobuf-mode-20170526.950/protobuf-mode.el at Thu Aug 10 02:15:23 2017

In protobuf-mode:
protobuf-mode.el:216:25:Warning: (lambda nil ...) quoted with ' rather than
    with #'

In end of data:
protobuf-mode.el:225:1:Warning: the function `c-populate-syntax-table' might
    not be defined at runtime.
```

and protobuf mode seems to work correctly at a first glance.

I'm testing in an ubuntu 14 docker image.
