### ISSUE TITLE
Javanano: Map fields are set to null by default when constructed

### ISSUE THREAD

**Issue by krause-michael** [google/protobuf#3260]
Using protoc version libprotoc 3.3.0

# Steps to reproduce

## Create a repro.proto file containing the following

```
syntax = "proto3";

package repro;

message Test {
    map<uint32,uint32> map_field = 1;
}
```

## Run protoc

`protoc --javanano_out=. repro.proto`

# Expected

When Test message is constructed, mapField is initialized to a non-null, empty map.

# Actual

When Test message is constructed, mapField is initialized to null.

# Discussion

Upon inspection of the protoc generated Repro.java file, it's evident that the generated constructor calls the clear() method and that the clear method sets the mapField to null:

    public Test() {
      clear();
    }

    public Test clear() {
      mapField = null;
      cachedSize = -1;
      return this;
    }

# Further Detail

Here is the link to the protoc compiler code that I think is responsible for generating the javanano output for the clear method for map fields:

https://github.com/google/protobuf/blob/c44ca26fe89ed8a81d3ee475a2ccc1797141dbce/src/google/protobuf/compiler/javanano/javanano_map_field.cc#L130

**Comment by xfxyjwf** [comment]
My understanding is that all non-primitive fields are initialized to null in javanano. Is that not the case?

**Comment by krause-michael** [comment]
A discussion about default value for a map field is conspicuously absent from the proto3 language guide: https://developers.google.com/protocol-buffers/docs/proto3#default

I would assume that maps would be handled in the same matter as repeated and give you an empty as opposed to a null object.

**Comment by pherl** [comment]
Nano is deprecated in favor of lite. Also this will be a behavior change that would be problematic for existing users. I'd suggest migrating over to use lite for android/mobile.
