### ISSUE TITLE
Java protobuf release 3.3.0 breaks normal protobuf promise

### ISSUE THREAD

**Issue by rosun82** [google/protobuf#3265]
If a field is not filled, why isn't it defaults to the zero value of that type, as in all other languages?!!!

What benefit does UNRECOGNIZED brings in?!!!

**Comment by rosun82** [comment]
Verified that in 3.2.0 the returned value is 0 if a field is not filled. In 3.3.0 it is UNRECOGNIZED.

**Comment by xfxyjwf** [comment]
Can you provide a code example (.proto and Java file) to reproduce the problem? If a field is not set, it should return the default value rather than UNRECOGNIZED.

**Comment by lenage** [comment]
Thanks for you response @xfxyjwf 

here is a .proto example (with proro3 and proto2):

```
syntax = "proto3";
message SessionKind {
  enum Enum {
    LISTENING = 0;    // Backward compatible with PBLessonKind.
    VOCABULARY = 1;
    //.... 
  }
}
message PBLesson {
  SessionKind.Enum kind = 6;
}
```
```
syntax = "proto2";
message SessionKind {
  enum Enum {
    LISTENING = 0;    // Backward compatible with PBLessonKind.
    VOCABULARY = 1;
    //.... 
  }
}
message PBLesson {
  optional SessionKind.Enum kind = 6;
  // ... other field
}
```

my protoc version is 3.2.0

```
$ protoc --version                                                                                                                                                                          
libprotoc 3.2.0
```

and generated java code as below:

proto3
```
// $protoc -I=./ --java_out=./example.proto
    /**
     * <code>.example.SessionKind.Enum kind = 6;</code>
     */
    public example.SessionKind.Enum getKind() {
      example.SessionKind.Enum result = core_course.SessionKind.Enum.valueOf(kind_);
      return result == null ? example.SessionKind.Enum.UNRECOGNIZED : result;
    }
```

proto2 
```
// $protoc -I=./ --java_out=./example_proto2.proto
    public example_proto2.SessionKind.Enum getKind() {
      example_proto2.SessionKind.Enum result = example_proto2.SessionKind.Enum.valueOf(kind_);
      return result == null ? example_proto2.SessionKind.Enum.LISTENING : result;
    }
```

it's return `UNRECOGNIZED` in `getKind` method.

In [java-generated guide](https://developers.google.com/protocol-buffers/docs/reference/java-generated)

> In addition, getFoo() will return UNRECOGNIZED if the enum value is unknown - this is a special additional value added by the proto3 compiler to the generated enum type.

it said ` getFoo() will return UNRECOGNIZED if the enum value is unknown`, 
so i can't using enum `0` as other value (for example, we using 0 as LISTENING in example) in proto3 ?

**Comment by xfxyjwf** [comment]
The generated code is as expected. In proto3, if an enum value is unknown, UNRECOGNIZED should be returned. This is different from proto2. For proto3, you should always has a switch case for UNRECOGNIZED and handle it explicitly.

**Comment by rosun82** [comment]
However, in our case, zero value is a *known* enum value, and still got
resolved to UNRECOGNIZED.

**Comment by xfxyjwf** [comment]
@rosun82 Can you provide a .proto file and the corresponding data that can reproduce what you said? You are basically saying Enum.valueOf(0) will return null and I don't see how that can happen.

I think a more plausible cause is that you actually have an unknown enum value (not zero) there, but when you use proto2, you get 0 because that's how proto2 behaves for unknown values and that makes you mistakenly think the value is 0, but it really isn't.
