### ISSUE TITLE
php extension documentation

### ISSUE THREAD

**Issue by dyeshurun** [google/protobuf#3271]
I am unable to find any documentation nor php-stubs for ide.
Any idea where I can find it?

**Comment by TeBoring** [comment]
What do you mean for ide?
The API doc is at: https://developers.google.com/protocol-buffers/docs/reference/php-generated

**Comment by dyeshurun** [comment]
Sorry, I was not clear enough.
When I said php-stubs for IDE I referred to something like this - https://github.com/JetBrains/phpstorm-stubs

I see the documentation now, missed it though it was in front of me :)
However, I don't see documentation about the underlying objects, e.g. MapField.
For example - I see from inspecting the variables I get back that there is a method "count()" to get the number of items. 
I am trying to figure out if there is a way to iterate over map fields when the map key is not a sequence but like an associative array.

Thanks,
Danny

**Comment by TeBoring** [comment]
Currently, we haven't set up a website to document the API of runtime library (we have the plan).
I think you can do foreach(map as key=>value)

**Comment by TeBoring** [comment]
I think you are right. We forgot to provide iterator for map in c extension. Will add it later.

**Comment by LinkedDestiny** [comment]
I checked my code whole day to solve this problem..... When can I get the right version?

**Comment by TeBoring** [comment]
ETA is end of July which is in 3.4 release.

**Comment by pjebs** [comment]
I couldn't find a way to iterate over MapField. There is no way for me to discover what all the keys are.

**Comment by pjebs** [comment]
Is version 3.4 available yet?

**Comment by pjebs** [comment]
@andizzle, in the meantime we need to use: `composer require "google/protobuf:^v3.3.0"` instead of `pecl install protobuf`

**Comment by pjebs** [comment]
@TeBoring Should this issue be closed now:
https://github.com/google/protobuf/releases/tag/v3.4.0
```
PHP

Support PHP generic services. Specify file option php_generic_service=true to enable generating service interface.
Message, repeated and map fields setters take value instead of reference.
**Added map iterator in c extension.**
Support json  encode/decode.
Added more type info in getter/setter phpdoc
Fixed the problem that c extension and php implementation cannot be used together.
Added file option php_namespace to use custom php namespace instead of package.
Added fluent setter.
Added descriptor API in runtime for custom encode/decode.
Various bug fixes.
```
