### ISSUE TITLE
can I ignore set the variable PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION_VERSION?

### ISSUE THREAD

**Issue by BreakTom** [google/protobuf#3273]
I have a question in protobuf2.6.1,In cpp_implement,can I only set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=cpp, not set the PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION_VERSION?thanks.(I have a poor English
)

**Comment by BreakTom** [comment]
or what's the different on the PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION_VERSION= 1 and PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION_VERSION = 2

**Comment by anandolee** [comment]
There used to have two cpp implementation versions. Version 1 is no longer supported

https://github.com/google/protobuf/blob/c44ca26fe89ed8a81d3ee475a2ccc1797141dbce/python/google/protobuf/internal/api_implementation.py#L87
