### ISSUE TITLE
iOS integration in app

### ISSUE THREAD

**Issue by ratnesh-iOSdev** [google/protobuf#3277]
Integrating this in iOS app is very messy, nothing is clear.

Steps are not clear, in  every step we need to search solution. 

Need lot of improvement. Better support on Cocoapods.

**Comment by DharmbirChoudhary** [comment]
@ratnesh-iOSdev Did you find clear way to implement it?

**Comment by dpassage** [comment]
As a kibitz, you may want to check out https://github.com/apple/swift-protobuf
