### ISSUE TITLE
Can I install protobuf 2 and protobuf 3 simultaneously?

### ISSUE THREAD

**Issue by my777777** [google/protobuf#3285]
Hi, there are two projects on my computer, and unfortunately, one uses protobuf 2, but another uses protobuf 3. How can the two projects work correctly? Can I install different version of protobuf simultaneously? or install different protobuf for different users?
thanks, ^_^

**Comment by xfxyjwf** [comment]
Assuming you are using C++, they can coexist but you will need to install them in different paths. For example:
```bash
$ ./configure --prefix=/home/xiaofeng/lib
$ make && sudo make install
```
The above will install protobuf in /home/xiaofeng/lib.
