### ISSUE TITLE
Add oneof support for proto C#

### ISSUE THREAD

**Issue by anandolee** [google/protobuf#329]
Will add oneof for proto C#

@jskeet anything you want to mention for the generated code? If no, I will follow the Java design.

**Comment by jskeet** [comment]
I think it's probably reasonable to start with the Java design, and then maybe tweak it. If you're happy to have tweak requests after an initial implementation, that's fine - otherwise I could draft something next week in terms of what I'd expect the generated code to look like, but it won't be before Tuesday or Wednesday.

**Comment by anandolee** [comment]
Next Tuesday or Wednesday sounds good to me

**Comment by jskeet** [comment]
Okay, now had a closer look at the generated Java code. Looks like it's broadly appropriate, yes.

The `*Case` enum can just be a simple enum in C#; each value corresponding to the field that's been set, with 0 having a name of `None`. (That will of course be a problem if there's a field called "none" but that's just like any other naming collisions.)

The field in the message class would be a field of that type. It's a pity that value types within a oneof end up boxing, but it's hard to see a way round that.

**Comment by anandolee** [comment]
C++ and Java use ONEOF_NAME_NOT_SET. Is there a reason that we use None instead of Oneof_Name_Not_Set?

**Comment by jskeet** [comment]
Yes - it's the convention for a C# enum:
https://msdn.microsoft.com/en-us/library/ms229058(v=vs.110).aspx

We definitely wouldn't want an underscore based version... NotSet or Unspecified would be okay if we don't want None.
