### ISSUE TITLE
version 3.3.0 -test failed 1-CommandLineInterfaceTest.W32ErrorMessage

### ISSUE THREAD

**Issue by taotanty** [google/protobuf#3293]
I downloaded source v3.3.0 to complie at windows(bit 64) ,use nmake release.run nmake check failed.
log like this:
NMAKE :fatal error U1077,xxxxx.tests.exe return code '0x01' STOP

**Comment by vibhoraggarwal** [comment]
In case somebody come across this issue. It is similar to #4773.
