### ISSUE TITLE
Make Any easier to use

### ISSUE THREAD

**Issue by jskeet** [google/protobuf#3294]
Currently it's easy to pack an Any value, and unconditionally Unpack a value, but we should offer a TryUnpack method or similar, which returns null if the type name is wrong. That will make it easier to unpack a value to one of multiple types.

**Comment by AlbinoGeek** [comment]
Shouldn't the signature be something using out variables like:

```csharp
   Byte[] data = new Byte[512]; // read from TCP
   AuthResponse response;
   if (LoginProto.Any.TryUnpack(data, out response)) {
```

This would mimic system types like `Dictionary,TryGetValue(T inVar, out outVar)`

However, it occurred to me in typing this -- wouldn't we want an offset and length way of unpacking for reading in a stream or large section of memory (such as a file) where it's cheaper to seek than it is to copy that data out.

**Comment by jskeet** [comment]
No, you don't unpack to a byte array - that would be packing. You unpack to another type. So for example (using C# 7 out variables):

```csharp
if (someProto.AnyProperty.Unpack(data, out Message 1 message1))
{
  Console.WriteLine(message1.PropertyFromMessage1
}
```
