### ISSUE TITLE
Protobuf versions Conflict (However correct version is installed)

### ISSUE THREAD

**Issue by AlexDzhusUA** [google/protobuf#3295]
Hello, I use Ubuntu 16.04, gcc 5.4.0 and CLion  (C++ environment).
I am trying to use [caffe](http://caffe.berkeleyvision.org/). And it needs protobuf for installation.
So, it works fine in Python, but C++ gives me a run-time exception:

**[libprotobuf FATAL google/protobuf/stubs/common.cc:78] This program was compiled against version 2.6.1 of the Protocol Buffer runtime library, which is not compatible with the installed version (3.3.0).  Contact the program author for an update.  If you compiled the program yourself, make sure that your headers are from the same version of Protocol Buffers as your link-time library.  (Version verification failed in "/build/mir-ui6vjS/mir-0.26.3+16.04.20170605/obj-x86_64-linux-gnu/src/protobuf/mir_protobuf.pb.cc".)
terminate called after throwing an instance of 'google::protobuf::FatalException'
  what():  This program was compiled against version 2.6.1 of the Protocol Buffer runtime library, which is not compatible with the installed version (3.3.0).  Contact the program author for an update.  If you compiled the program yourself, make sure that your headers are from the same version of Protocol Buffers as your link-time library.  (Version verification failed in "/build/mir-ui6vjS/mir-0.26.3+16.04.20170605/obj-x86_64-linux-gnu/src/protobuf/mir_protobuf.pb.cc".)**

As far as I understood, exception tells me that it needs protobuf 2.6.1, but 3.3.0 is installed. 
But command   **apt-get upgrade libprotobuf-dev** gives me  **libprotobuf-dev is already the newest version (2.6.1-1.3).** so i do have 2.6.1.
Could you, please, advice me how could i fix it ?

**Comment by mathben** [comment]
I have the same problem with another project.

**Comment by pherl** [comment]
You probably installed the v3.3 protobuf from source, into the /usr/local/include|lib directory which take precedence of the system distributed ones in /usr/include|lib. I'd suggest uninstall the local version, or use the docker file caffe provides for a clean setup.

**Comment by luongs3** [comment]
I get the same Issue with opencv. When try to import cv2, i got the same error.

**Comment by fybaft2012** [comment]
> I get the same Issue with opencv. When try to import cv2, i got the same error.

@luongs3  Hi, how did yo solve this problem? I met the same issue with you, I am considering whether I uninstall the existing one and reinstall new version or not?

**Comment by jinfagang** [comment]
DONOT uninstall system default 2.6.1 protobuf.

Install a new version which commonly install into `/usr/local/lib` can also works fine, just add a -L/usr/local/lib in your program.

**Comment by paherbst** [comment]
Why would this error happen when my application has statically linked protobuf libs ?? why is it even looking at the system's shared libs?

**Comment by beew** [comment]
Not sure if this is relevant. I encountered this problem when compiling something with qt5 as a dependency. This is how I fixed the problem

Depending on how qt5 is installed do one of the followings

if you compile qt5 from source, get the qtstyleplugins https://github.com/qt/qtstyleplugins, after compiling, it will create libqgtk2.so in plugins/platformthemes where it coexists with libqgtk3.so. Then
either  add this to .bashrc, or invoke in terminal before running your app
```
export QT_QPA_PLATFORMTHEME=gtk2

```
or  prepend the Exec=line in appliation's desktop file

```
env QT_QPA_PLATFORMTHEME=gtk2

```

if install qt from repo, install qt5-style-plugins, libqt5libqgtk2 or similar depending on your distro and set the QT_QPA_PLATFORMTHEME environmental variable as above.

See also https://gitlab.kitware.com/paraview/paraview/-/issues/17696 which has a different, a bit clumsier workaround.

**Comment by tanglebridge** [comment]
I am running into this now.  I have a custom shared lib and executable, with protobuf and grpc linked in statically. I carefully analyzed all dependencies and there is no dependency on protobuf. There are many other android libs that do have that dependency. 

My working hypothesis: a dependency loads the dynamic protobuf lib. The version is a global static or some such that gets picked up from the other library, and there it is. Don't have a good fix yet.
