### ISSUE TITLE
Is there some approach to generate pure c++ struct/class representing relevant proto file instead of protobuf object?

### ISSUE THREAD

**Issue by NetWilliam** [google/protobuf#3297]
Is there some approach to generate pure c++ struct/class representing relevant proto file instead of protobuf object?

eg: I have a proto file:
```
message Foo {
    int bar = 1;
    string blah = 2;
}
```
I can get a pb.cc by compile it by protoc. I can use it as follow:

```
f = Foo();
f.set_bar(128);
rpc_call(f);
```

It very useful in this rpc scenario. Now I have this rpc server/client work perfectly.
But my client would rather to use a local function call instead of rpc.
So I want him to pass the Foo struct in code. However I don't want to give the whole proto generated files and set him in a situation which is required for protobuf libs and proto files.

I wonder that if I can   use some struct by auto-compiling tool and generate some code like this:

`protoc -i foo.proto -o foo.cpp`

here foo.cpp is:
```

struct Foo {
    int bar;
    std::string blah;
    // it's ok without follow two lines
    void MergeFromPBMessage(Message *pb);
    Message* GetPBMessage();
}
```

**Comment by xfxyjwf** [comment]
There isn't official support for this but you can probably find some third_party implementations. If none available, you can also implement one yourself using protoc plugin. See third party extensions listed here:
https://github.com/google/protobuf/blob/master/docs/third_party.md
