### ISSUE TITLE
Is 3.3.2 a real release?

### ISSUE THREAD

**Issue by scpeters** [google/protobuf#3302]
Moved from a comment (https://github.com/google/protobuf/pull/3258#issuecomment-311737647) to an issue for increased visibility:

I see that the [v3.3.2 tag](https://github.com/google/protobuf/releases/tag/v3.3.2) was created after https://github.com/google/protobuf/pull/3258 that bumped the version number, but it is not classified as a release on github. So downstream packaging projects like [pypi](https://pypi.python.org/pypi/protobuf/3.3.0) and [homebrew](https://github.com/homebrew/homebrew-core/blob/master/Formula/protobuf.rb#L4) are still using 3.3.0 (see discussion in https://github.com/Homebrew/homebrew-core/pull/15074#issuecomment-311735007 ). Can you clarify whether the v3.3.2 tag is intended as a proper release or is just a tag?

**Comment by ilovezfs** [comment]
@xfxyjwf @TeBoring a gentle ping on this.

**Comment by xfxyjwf** [comment]
3.3.2 is intended to be an official release and since it only contains small bug fixes for particular languages, we didn't bother to publish the release package for all other languages. If 3.3.0 works for you, you don't need to upgrade to 3.3.2.

**Comment by ilovezfs** [comment]
@xfxyjwf thanks for clarifying! We'll upgrade protobuf to 3.3.2 in Homebrew in that case.
