### ISSUE TITLE
How to uninstall protobuf 3.3.0 (c++, ubuntu14.04)

### ISSUE THREAD

**Issue by my777777** [google/protobuf#3304]
I want to completely uninstall protobuf 3.3.0 from my computer, what should I do? thanks!

**Comment by 0bliterator** [comment]
Try running 'make uninstall' in the source folder.

**Comment by auroua** [comment]
If the source folder have deleted, how to uninstall?

**Comment by pherl** [comment]
You can download the 3.3.0 again and run `make uninstall`. It's just a few `rm` commands.

**Comment by mymultiverse** [comment]
I am getting 

    make: *** No rule to make target 'uninstall'.  Stop.

after running make uninstall

**Comment by AliRaza21918** [comment]
me too getting the same problem

make: *** No rule to make target 'uninstall'.  Stop.

after running make uninstall

**Comment by ruffsl** [comment]
Can we reopen this? Master branch is still has this issue:

```
protobuf$ make uninstall
make: *** No rule to make target 'uninstall'.  Stop.
```

**Comment by icolwell** [comment]
For those still stuck trying to uninstall via `make uninstall`. You may need to run `./configure` first.

**Comment by Tochemey** [comment]
it did not work. Any solutions
