### ISSUE TITLE
case insensitive problem

### ISSUE THREAD

**Issue by ccl0326** [google/protobuf#3308]
In a case insensitive file system, in some cases, some generated files with same name likes BodyRange.java, Bodyrange.java, and BodyRange.java depend on Bodyrange.java. So the back file can not be generated. I want to know is this a normal behavior?

**Comment by xfxyjwf** [comment]
This is the expected behavior and you'd better rename the types in the .proto file to avoid these kinds of conflicts.

**Comment by xfxyjwf** [comment]
What's the name of your .proto file and what's its content?

**Comment by ccl0326** [comment]
the file name is bodyrange.proto.
```
syntax = "proto3";

option java_multiple_files = true;
option java_package = "xxxxx.xxx.xx";

package xxxx;

message BodyRanges {
  repeated BodyRange bodyRange = 1;
}

message BodyRange {
  string name = 1;
  int32 min = 2;
  int32 max = 3;
}

message Metrics {
  repeated string metric = 1;
}
```

**Comment by xfxyjwf** [comment]
So one Java class "BodyRange.java" is generated for the "message BodyRange" and the other "Bodyrange.java" is generated for the bodyrange.proto file. You can use `option java_outer_classname = "SomeOtherName";` to customize the outer class name to avoid the conflict.

**Comment by ccl0326** [comment]
@xfxyjwf Thanks, it's major issue.
