### ISSUE TITLE
No protoc 3.3.1 found in maven central repository

### ISSUE THREAD

**Issue by beihaifeiwu** [google/protobuf#3313]
When I upgrade gRPC to 1.4.0, it requires protobuf 3.3.1, but I cannot get maven plugin working , beacuse there is no such version of protoc, Is this a mistake or something else ?

**Comment by xfxyjwf** [comment]
You can just use the 3.3.0 version of protoc. 3.3.1 is a patch release and is backwards compatible with protoc 3.3.0.

**Comment by beihaifeiwu** [comment]
OK, thanks for your reply
