### ISSUE TITLE
provide protoc for AARM64 on Maven

### ISSUE THREAD

**Issue by AdrienGuichard** [google/protobuf#3318]
When compiling my project using Gradle on ARM64 server, protoc could not be found from maven repository, and the compilation fails with the following output:
```
[ . . . ]
* What went wrong:
Could not resolve all files for configuration ':protobuf-source:protobufToolsLocator_protoc'.
> Could not find protoc-linux-aarch_64.exe (com.google.protobuf:protoc:3.3.0).
  Searched in the following locations:
      https://repo1.maven.org/maven2/com/google/protobuf/protoc/3.3.0/protoc-3.3.0-linux-aarch_64.exe
```
I will upload my build.gradle file from my system,

Thanks for your support!
Adrien

**Comment by AdrienGuichard** [comment]
the build.gradle file
[build.gradle.txt](https://github.com/google/protobuf/files/1127593/build.gradle.txt)

**Comment by xfxyjwf** [comment]
We don't have a process to release non-x86 protoc binaries. You may have to build the protoc from source.

**Comment by AdrienGuichard** [comment]
then I close this issue. Compiling protobuf was furether more trivial for AARCH64.

Thanks for your support!
Adrien
