### ISSUE TITLE
protobuf release-v3.3.0 test fails

### ISSUE THREAD

**Issue by gogomogolo** [google/protobuf#3319]
Setup Guide: https://github.com/google/protobuf/blob/master/cmake/README.md

OS: Windows 7
cmd: Developer Command Prompt for VS 2017

Testing Step at the Guide, protobuf is failed in 6 tests

![image](https://user-images.githubusercontent.com/29948637/27910194-c056ff78-625c-11e7-827a-5832d90444c7.png)

![image](https://user-images.githubusercontent.com/29948637/27910288-24daa512-625d-11e7-93ce-30d37923cb9f.png)

**Comment by xfxyjwf** [comment]
Pretty sure these are caused by line-ending conversions. You can ignore them, or you can configure your git client to not do line-ending conversions and try again.

**Comment by gogomogolo** [comment]
thanks for your reply.

**Comment by gogomogolo** [comment]
https://github.com/google/protobuf/issues/547 
https://github.com/google/protobuf/issues/2548

solution : 
As a workaround, I just ended up doing: 

``` git config --global core.autocrlf false ```

while cloning on Windows and the tests passed.
