### ISSUE TITLE
got errors saying conflicting declaration in except.h:15:32:

### ISSUE THREAD

**Issue by DaniPaulo** [google/protobuf#3323]
Hi everyone!
I'm trying to install several programs (bedtools, freebayes, trinity...) in my Ubuntu 16.04.4 x64 machine.
The thing is that, everytime I use the command "make" I'm getting the same error (bellow). I'm also getting a lot of warnnings before make stops...
My GNU gcc version is 5.4.0.
So, anyone have a clue of what this could be? 
Thanks!  
---------------------------------------------------------------------------------- Error when type "make"
In file included from /usr/local/include/assert.h:5:0,
                 from ./base/SVector.h:8,
                 from ./analysis/DNAVector.h:7,
                 from ./aligns/KmerAlignCore.h:8,
                 from ./aligns/KmerAlignCore.cc:6:
/usr/local/include/except.h:15:32: error: conflicting declaration ‘typedef struct Except_Frame_T* Except_Frame_T’
 typedef struct Except_Frame_T *Except_Frame_T;
                                ^
/usr/local/include/except.h:15:16: note: previous declaration as ‘struct Except_Frame_T’
 typedef struct Except_Frame_T *Except_Frame_T;
                ^
/usr/local/include/except.h:17:18: error: field ‘prev’ has incomplete type ‘Except_Frame_T’
   Except_Frame_T prev;
                  ^
/usr/local/include/except.h:16:8: note: definition of ‘struct Except_Frame_T’ is not complete until the closing brace
 struct Except_Frame_T {
        ^
Makefile:473: recipe for target 'aligns/KmerAlignCore.o' failed
make[1]: *** [aligns/KmerAlignCore.o] Error 1
make[1]: Leaving directory '/home/danielpaulo/programs/trinityrnaseq-Trinity-v2.4.0/Chrysalis'
Makefile:26: recipe for target 'chrysalis_target' failed
make: *** [chrysalis_target] Error 2

**Comment by nelumbolutea** [comment]
> Hi everyone! I'm trying to install several programs (bedtools, freebayes, trinity...) in my Ubuntu 16.04.4 x64 machine. The thing is that, everytime I use the command "make" I'm getting the same error (bellow). I'm also getting a lot of warnnings before make stops... My GNU gcc version is 5.4.0. So, anyone have a clue of what this could be? Thanks! ---------------------------------------------------------------------------------- Error when type "make" In file included from /usr/local/include/assert.h:5:0, from ./base/SVector.h:8, from ./analysis/DNAVector.h:7, from ./aligns/KmerAlignCore.h:8, from ./aligns/KmerAlignCore.cc:6: /usr/local/include/except.h:15:32: error: conflicting declaration ‘typedef struct Except_Frame_T* Except_Frame_T’ typedef struct Except_Frame_T *Except_Frame_T; ^ /usr/local/include/except.h:15:16: note: previous declaration as ‘struct Except_Frame_T’ typedef struct Except_Frame_T *Except_Frame_T; ^ /usr/local/include/except.h:17:18: error: field ‘prev’ has incomplete type ‘Except_Frame_T’ Except_Frame_T prev; ^ /usr/local/include/except.h:16:8: note: definition of ‘struct Except_Frame_T’ is not complete until the closing brace struct Except_Frame_T { ^ Makefile:473: recipe for target 'aligns/KmerAlignCore.o' failed make[1]: *** [aligns/KmerAlignCore.o] Error 1 make[1]: Leaving directory '/home/danielpaulo/programs/trinityrnaseq-Trinity-v2.4.0/Chrysalis' Makefile:26: recipe for target 'chrysalis_target' failed make: *** [chrysalis_target] Error 2

I have this error too
