### ISSUE TITLE
Invalid generated Javascript syntax

### ISSUE THREAD

**Issue by romeovs** [google/protobuf#3324]
This is a clone of https://github.com/grpc/grpc/issues/11687, where I was asked to post it here.

I generate Javascript code using the following `protoc` invocation:

```
protoc
    -I/usr/local/include \
    -I/Users/romeo/code/go \
    -I/Users/romeo/code/go/src/github.com/TheThingsNetwork \
    -I/Users/romeo/code/go/src/github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis \
    -I/Users/romeo/code/go/src \
    --grpc_out=./src/proto \
    --plugin=protoc-gen-grpc=/Users/romeo/code/go/src/github.com/TheThingsNetwork/node-app-sdk/node_modules/.bin/grpc_tools_node_protoc_plugin \
    --js_out=import_style=commonjs,binary:./src/proto/Users/romeo/code/go/src/github.com/TheThingsNetwork/ttn/api/discovery/discovery.proto
```

This all runs fine without errors but the generated files contain syntax errors.

For instance the generated file `src/proto/src/github.com/TheThingsNetwork/ttn/api/discovery/discovery_grpc_pb.js` has the following error:

```
var src_github.com_TheThingsNetwork_ttn_api_discovery_discovery_pb = require('../../../../../../src/github.com/TheThingsNetwork/ttn/api/discovery/discovery_pb.js');
              ^
              Invalid dot here
```

I don't know if what I'm doing is correct here. But this seems like a bug anyhow.

I'm running:

```
$ protoc --version
libprotoc 3.3.0
$ node -v
v8.1.3
```

**Comment by xfxyjwf** [comment]
You generally don't want to have too many '"-I" flags in one protoc invocation because protoc is pretty dumb and may get to an incorrect import path for your proto file. Especially you don't want to have both "-I/Users/remeo/code/go" and "-I/Users/remeo/code/go/..." at the same time because one will shadow the other.

Please try this command instead (assuming all protos on in TheThingsNetwork and googleapis):
```
protoc
    -I/Users/romeo/code/go/src/github.com/TheThingsNetwork \
    -I/Users/romeo/code/go/src/github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis \
    --grpc_out=./src/proto \
    --plugin=protoc-gen-grpc=/Users/romeo/code/go/src/github.com/TheThingsNetwork/node-app-sdk/node_modules/.bin/grpc_tools_node_protoc_plugin \
    --js_out=import_style=commonjs,binary:./src/proto /Users/romeo/code/go/src/github.com/TheThingsNetwork/ttn/api/discovery/discovery.proto
```

**Comment by romeovs** [comment]
The issue is then that it will not find `github.com/gogo/protobuf/gogoproto/gogo.proto`:
```
github.com/gogo/protobuf/gogoproto/gogo.proto: File not found.
```

I'm also a bit clueless here since even if I include my entire `GOPATH` (where all protos are located), it will not find them.

**Comment by xfxyjwf** [comment]
So you use `import "github.com/gogo/protobuf/gogoproto/gogo.proto"` in your .proto file? I'm not sure if that's the correct way to import that file and you probably want to ask the author of that .proto file what's the correct import path. In any case if you want that import to work, you can add another `-I` but after the other `-I` flags:
```bash
protoc
    -I/Users/romeo/code/go/src/github.com/TheThingsNetwork \
    -I/Users/romeo/code/go/src/github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis \
    -I/Users/romeo/code/go/src \
    --grpc_out=./src/proto \
    --plugin=protoc-gen-grpc=/Users/romeo/code/go/src/github.com/TheThingsNetwork/node-app-sdk/node_modules/.bin/grpc_tools_node_protoc_plugin \
    --js_out=import_style=commonjs,binary:./src/proto /Users/romeo/code/go/src/github.com/TheThingsNetwork/ttn/api/discovery/discovery.proto
```
