### ISSUE TITLE
「PHP」 Fatal error: Class 'ProtobufMessage' not found

### ISSUE THREAD

**Issue by searchpcc** [google/protobuf#3325]
INFO:
PHP 7.0.18 (cli) (built: May  9 2017 16:20:54) ( NTS )
protobuf Version => 3.3.0

ERROR:
Fatal error: Class 'ProtobufMessage' not found

When I used the protobuf extention, this error " Fatal error: Class 'ProtobufMessage' not found" came.

**Comment by TeBoring** [comment]
Could you provide more context? What's your source code, composer.json, command to run php?

**Comment by TeBoring** [comment]
Feel free to reopen the issue if there is still problem.

**Comment by searchpcc** [comment]
I am sorry. In the end, I used the php 5.6.30 extension to fix it. Thank you.

**Comment by visoeclipse** [comment]
PHP7.1.9 + protobuf 3.4.0 will  get Fatal error: Class 'ProtobufMessage' not found
