### ISSUE TITLE
Support for oneof setted field ?

### ISSUE THREAD

**Issue by amelhaoui** [google/protobuf#3328]
Hi,
```
message Bar {
  oneof data {
    Foo f = 1;
    Paa p = 2;
  }
}
```  
Since we can know which field is set using `data_case() ` why can't we use something similar to 'Any' message `data()` . Is it related to return value which is not known at compile time ?

**Comment by xfxyjwf** [comment]
Suppose you have:
```proto
message Bar {
  oneof data {
    int32 f = 1;
    int32 p = 2;
  }
}
```
After you get an int value from `data()`, how do you know whether its `f`, or `p`? When using oneof, I think checking `oneof_case()` is pretty much required. A `data()` method alone doesn't seem very useful. If you want, you can always create such a wrapper method yourself though.
