### ISSUE TITLE
bug ? strack is break with protobuf 3.0.0 ver

### ISSUE THREAD

**Issue by huangzuduan** [google/protobuf#3329]
syntax = "proto2";

package msg;

message SerivceInfo2
{
	optional uint32 ServerID = 1;			
	optional string ServerName= 2;		
	optional bool Recvsrvlist = 3;			
	optional bool Broadcastlist = 4;		
	optional uint32 SerivceID = 5; 			
	optional string SerivceName= 6;			
	optional string SerivceFun = 7;			
	optional string SerivceIP = 8;			
	optional uint32 SerivcePort = 9;		
	optional uint32 SerivceRemoteid = 10;	
	optional string SerivceUser = 11;	
	optional string SerivcePasswd = 12;
	optional string SerivceValue = 13;	
	
}
///------------------------------------------------------
	::msg::SerivceInfo2 proto;
	proto.set_servername("123");
	std::string name = proto.servername();
///--------------------------------------------------------
// if you set string field , Run-Time Check Failure #2 - Stack around the variable 'proto' was corrupted.

**Comment by xfxyjwf** [comment]
This sounds like a build issue. Your program is probably built with incorrect configurations (e.g., different compiler flags are used when compiling protobuf library and your own code).
