### ISSUE TITLE
PHP: Second argument to GPBUtil::checkEnum is not used

### ISSUE THREAD

**Issue by bshaffer** [google/protobuf#3330]
The GPBUtil class has a function called [`checkEnum`](https://github.com/google/protobuf/blob/master/php/src/Google/Protobuf/Internal/GPBUtil.php#L8), which is an alias for `checkInt32`.

The generated enum fields [call this function](https://github.com/google/protobuf/blob/12acbc2678073c3439b427be0b713b97e2074bfb/php/src/Google/Protobuf/Internal/MethodOptions.php#L101) and pass in a second argument which is the class name of the enum field, e.g. `MyEnum::class`. 

So either this second field should be used to determine if the enum integer is valid, or it should not be supplied as an argument to `checkEnum`.

**Comment by TeBoring** [comment]
This is implementation detail.

**Comment by sam0737** [comment]
The protoc (v3.6.1) generate setter codes that call GPBUtil::checkEnum($var, \CLASSNAME)
But GPBUtil::checkEnum in the PHP source code is just expecteding 1 input parameter.

Although it works, but it flags as error with static code checker.

I am afraid this is not just implementation detail.
