### ISSUE TITLE
Can the JS version be used client-side?

### ISSUE THREAD

**Issue by PeterMitrano** [google/protobuf#3336]
I have a simple html/js web page that does not communicate with a DB, and isn't served by a nodejs server. I would like to use the generated JS code within my js code (the old `<script src="custom.js">` style). However, I don't know how to "include" (forgive the C term) these files. The README seems to only talk about npm and other server-side stuff.

Also, the generated files (such as `MyMessage_pb.js`) seem to have `require()` statements in them, which of course doesn't exist on client-side.

**Comment by amelhaoui** [comment]
I haven't tried proto client side but to require modules on browser there is browserify.org
