### ISSUE TITLE
Trouble Installing the C Extension for PHP 5.5

### ISSUE THREAD

**Issue by ryanmats** [google/protobuf#3340]
I needed to [install gRPC for PHP](https://cloud.google.com/php/grpc) and part of the instructions included installing the Protobuf Runtime Library. I was unable to install the C extension, and got [this error message](https://paste.googleplex.com/6400195495460864). However, I was successfully able to install the PHP extension.

I have the following version of PHP installed: PHP 5.5.9-1ubuntu4.21

@TeBoring

**Comment by TeBoring** [comment]
I created an ubuntu14.04 instance on gce and installed php5.5.9. Our tests ran without error.

# Install build tools
 ``` sudo apt-get install autoconf automake libtool curl make g++ unzip git ```

# install php
```
wget http://php.net/get/php-5.5.9.tar.gz/from/this/mirror
mv mirror php-5.5.9.tar.gz
tar -xzvf php-5.5.9.tar.gz
sudo apt-get install libxml2-dev
cd php-5.5.9 && ./configure && make && sudo make install
cd ..
```

# build proto
```
git clone https://github.com/google/protobuf.git
cd protobuf && ./autogen.sh && ./configure && make
```

# generate test proto
```
pushd php/tests
mkdir generated
../../src/protoc --php_out=generated proto/test.proto proto/test_include.proto proto/test_no_namespace.proto proto/test_prefix.proto proto/test_php_namespace.proto proto/test_empty_php_namespace.proto
pushd ../../src
./protoc --php_out=../php/tests/generated google/protobuf/empty.proto
./protoc --php_out=../php/tests/generated -I../php/tests -I. ../php/tests/proto/test_import_descriptor_proto.proto
popd
```

# run test
```
./test.sh
```

**Comment by ghxter** [comment]
when run ./test.sh show errors:
