### ISSUE TITLE
64 bit integer serialization error - JS - How to make writeUint64String default ?

### ISSUE THREAD

**Issue by amelhaoui** [google/protobuf#3346]
Hi,
I used this sample
```
syntax = "proto3"; 

message foo {
	uint64 id = 1;
}
```

```
var Foo = require('./foo_pb.js');

var foo_pb = new Foo.foo();
foo_pb.setId(18446744073709551615); // is saved as number not as string which cast it
or
foo_pb.setId("18446744073709551615"); // saved as is

foo_pb.serializeBinary(); // fails here even it's less than 2^64
``` 

To my understanding, 64 bit integers can be serialized since protobuf put it in a (low, high) uint32.
This changes when I change the method in the generated foo_pb.js from writeUInt64 to writeUInt64String.. any way to make default-generated  the second one ?

Thanks

**Comment by amelhaoui** [comment]
The serialization fails because of:
https://github.com/google/protobuf/blob/master/js/binary/writer.js#L544
Because 18446744073709551616 > 18446744073709551615 would return false. Comparaison should be using strings or low1, high1 and low2, high2 ?

**Comment by acozzette** [comment]
I believe @updogliu is working on this problem as part of issue #2908.

**Comment by amelhaoui** [comment]
Thanks for the update @acozzette

**Comment by TeBoring** [comment]
I think now you can add the field option: js_type = string
