### ISSUE TITLE
Class 'Google\Protobuf\Internal\Message' not found

### ISSUE THREAD

**Issue by jprime1991** [google/protobuf#3347]
I'm using PHP version 5.6.31 with protobuf/protoc version 3.3.0

As I'm running protobuf, it shows `Class 'Google\Protobuf\Internal\Message' not found`.
I also added google/protobuf with version 3.3.0 to composer.json and removed composer.lock for clean and re-installed composer and then, it also shows could not find index 'Spprotocol\rtn_rep'.

@TeBoring Could you pls help me?

**Comment by jprime1991** [comment]
My Ubuntu version is 14.04

**Comment by TeBoring** [comment]
Do you have repository that I can fork?

**Comment by jprime1991** [comment]
I'm sorry I do not  :(

**Comment by jprime1991** [comment]
Or could we use teamviewer?

**Comment by TeBoring** [comment]
Could you paste the composer.json and the command line you run the test?

**Comment by TeBoring** [comment]
Also your proto file

**Comment by TeBoring** [comment]
Close this for now. Feel free to reopen if there is still problem.
