### ISSUE TITLE
php/js - map<string,string> can't decode value of ""

### ISSUE THREAD

**Issue by redaniel22** [google/protobuf#3351]
php 7.0
google/protobuf installed via composer and is version 3.3.2
protobuf code generation done with version 3.3

protobuf
```protobuf
message example {
    map<string,string> custom_fields = 1;
}
```

php
```php
    $example->getCustomFields()["my_key"] = "";
```

Encoding this via php and decoding (uint8) via javascript causes an assertion error in javascript. Making sure there are no empty strings as values in the map resolves the assertion error.

**Comment by TeBoring** [comment]
Could you try master? We had a lot of encoding fix recently.

**Comment by redaniel22** [comment]
Unfortunately, neither 3.3.x-dev or dev-master 9ab7c73 on the php side have resolved the issue.

Still getting assertion error:

```
protobuf.b3a75a6054c5aefb7719.js:1 Uncaught goog.asserts.AssertionError {message: "Assertion failed", reportErrorToServer: true, messagePattern: "Assertion failed", stack: "AssertionError↵    at new goog.asserts.AssertionEr…com:8443/dist/app.6b0000b3cbadadfd39a8.js:1:8348)"}
goog.asserts.DEFAULT_ERROR_HANDLER @ protobuf.b3a75a6054c5aefb7719.js:1
goog.asserts.doAssertFailure_ @ protobuf.b3a75a6054c5aefb7719.js:1
goog.asserts.assert @ protobuf.b3a75a6054c5aefb7719.js:1
jspb.Map.deserializeBinary @ protobuf.b3a75a6054c5aefb7719.js:1
(anonymous) @ protobuf.b3a75a6054c5aefb7719.js:1
jspb.BinaryReader.readMessage @ protobuf.b3a75a6054c5aefb7719.js:1
proto.Proto.Marketplace.EventView.deserializeBinaryFromReader @ protobuf.b3a75a6054c5aefb7719.js:1
proto.Proto.Marketplace.EventView.deserializeBinary @ protobuf.b3a75a6054c5aefb7719.js:1
convert @ app.6b0000b3cbadadfd39a8.js:1
handleReadyStateChange @ app.6b0000b3cbadadfd39a8.js:1
```

Additionally, on dev-master, if I set the value to a non-empty string, it decodes without any errors, but the map comes through empty. A separate int64 field did decode correctly when the map had a non-empty string. This may be due to a notice I had to suppress to get things working properly on dev-master which was:

```
Uncaught PHP Exception Symfony\Component\Debug\Exception\ContextErrorException: "Notice: Only variables should be passed by reference" at /var/www/marketplace/vendor/google/protobuf/php/src/Google/Protobuf/Internal/Message.php line 73
```

I tried setting the map in php via:

```php
$test = ["key" => "value"];
$example->setCustomFields($test);

//and

$key = "key";
$value = "value";
$example->getCustomFields()[$key] = $value
```

Both of these attempts did not solve the `Only variables should be passed by reference" error.

**Comment by TeBoring** [comment]
Could you paste the hex string for setting empty string?

**Comment by TeBoring** [comment]
I suspect js decoder is not general enough to take empty string.

**Comment by TeBoring** [comment]
@haberman to take a look.

**Comment by redaniel22** [comment]
protobuf
```protobuf
message Example {
    map<string,string> custom_fields = 1;
}
```

php
```php
$example->getCustomFields()["key"] = "";
```

This is received by javascript (in chrome) as:
```
// uint8Array
[10, 5, 10, 3, 107, 101, 121, 0, 0]
// hexstring
0a050a036b65790000
```

**Comment by TeBoring** [comment]
It should be a bug of php encoder. I'll fix that.

**Comment by TeBoring** [comment]
Are you using php implementation or c extension?

**Comment by redaniel22** [comment]
php implementation

**Comment by TeBoring** [comment]
I tested for master head.
For proto:
```
message TestMessage {
  map<string, string> map_string_string = 84;
}
```
And php:
```
$a = new TestMessage();
$map = $a->getMapStringString();
$map['key'] = '';
$data = $a->serializeToString();
var_dump(bin2hex($data));
```
I got:
```
a205050a036b6579
```
I think it's correct. Could you double check you have used master head?

**Comment by TeBoring** [comment]
Could you also check what is the output at php side?

**Comment by TeBoring** [comment]
Close this for now. Feel free to reopen if there is still problem.
