### ISSUE TITLE
program not found or is not executable with ~ on path

### ISSUE THREAD

**Issue by chemidy** [google/protobuf#3355]
I have on issue on mac when i use a path with ~, i receive an error : 

```
protoc --plugin=protoc-gen-javalite=/Users/chemidy/go/bin/protoc-gen-javalite \
--plugin=protoc-gen-grpc-java=~/go/bin/protoc-gen-grpc-java \
--grpc-java_out=lite:../api/android --javalite_out=../api/android -I. auth.proto
```

```
~/go/bin/protoc-gen-grpc-java: program not found or is not executable
--grpc-java_out: protoc-gen-grpc-java: Plugin failed with status code 1.
```

But if i use full path or $GOPATH instead of ~ it works

- Operating System : MacOS Sierra
- protoc --version : libprotoc 3.3.2

**Comment by acozzette** [comment]
That sounds to me like an issue with your shell and not an issue with protoc. Ordinarily your shell should expand ~ to the name of your home directory, and protoc shouldn't attempt to do that. Does your command work if you just use $HOME instead of ~?

**Comment by chemidy** [comment]
Hello,

Yes it works if i use $HOME.
I reproduce this issue with a colleague on 2 others computers 1 on Debian Linux with bash, and 1 on macOs with bash.

**Comment by acozzette** [comment]
Hmm, that's interesting. I'm not sure how bash decides to do the tilde expansion but at least on my machine it seems as if it avoids expanding the `~` when it appears as part of a flag beginning with `--`:
```
$ echo --abc=~
--abc=~
$ echo --abc=$HOME/go
--abc=/home/acozzette/go
$ echo ~/go
/home/acozzette/go
```

I'll go ahead and close this issue since it seems to be a surprising behavior of bash rather than a bug with protoc.
