### ISSUE TITLE
How can i solve the  @java.lang.Deprecated problem

### ISSUE THREAD

**Issue by liyf155** [google/protobuf#3358]
here is my generated code
` @java.lang.Deprecated public static final com.google.protobuf.Parser<SubscribeReq>
        PARSER = new com.google.protobuf.AbstractParser<SubscribeReq>() {
      public SubscribeReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new SubscribeReq(input, extensionRegistry);
      }
    };
`
the protoc version is 3.3
the command: `protoc -I=./netty --java_out=./ ./netty/SubscribeReq.proto`

**Comment by jtattermusch** [comment]
It is unclear what your problem actually is, therefore closing.
