### ISSUE TITLE
Support for Set

### ISSUE THREAD

**Issue by jkbbwr** [google/protobuf#3359]
It would be really useful to have a keyword (or if backwards compat not permitting a type) that allows me to perform set operations with protobuf messages e.g.

```
message Claim {
    set<string> permissions = 1;
    set<string> revokes = 2;
}

a = Claim(...)
b = Claim(...)
a.permissions.union(b.revokes)
b.permissions.union(a.revokes)
```

Without having to load this into language or fake it with `map<x, bool>` I want to avoid the bollerplate code

**Comment by jtattermusch** [comment]
@xfxyjwf  I think we can close this as "won't fix?"

**Comment by xfxyjwf** [comment]
Yes, there is no plan to add a set type in protobuf.
