### ISSUE TITLE
GetVersion failed in setup.py for python3.

### ISSUE THREAD

**Issue by gsmith-to** [google/protobuf#336]
GetVersion failed for me under python3, because it relies on the exec operation modifying the locals of GetVersion. According to python docs, code executed by exec(str) can read the function's locals but modifications to them may not work.
The fix is to create a namespace and to read the result from the namespace (which is a good idea whenever exec is used; but here we need to avoid python2's syntax 'exec expr in ns' in order to be python 3 compatible.)

As I understand it, python 2 normally 'compiles' functions so that the locals aren't in a dictionary, eliminating name lookups; supporting exec requires functions using exec to be compiled quite differently. I guess that was dropped in python3, and exec now fabricates a 'locals' dictionary, to support local access, but it can't propagate changes back (in particular, the exec function can't create locals which did not exist in the function at 'compile time').

-------------------

I did a PR but I'm not going to sign a CLA for 4 lines of code. So instead here it is.

In GetVersion() change everything below the 'with' to something along the lines of

--------------------

    inifile = version_file.read()
    if sys.version_info[0] >= 3:  # exec Can't reliably modify locals in python3
        nsp = {}
        exec(inifile, nsp, nsp)
        return nsp['__version__']
    else:
        exec(inifile)
        return __version__

**Comment by haberman** [comment]
I believe this was fixed in https://github.com/google/protobuf/commit/cd141089a120b6c15687e0653848d24682a07d32. Please re-open if you observe this issue with the latest code.
