### ISSUE TITLE
help! protoc.exe was crashed when generate cpp file

### ISSUE THREAD

**Issue by TheEarthIsFlat** [google/protobuf#3361]
Protoc.exe crash while I compile the proto file.

> protoc --proto_path=. --cpp_out=. Packet.proto

it is the command I entered.

how can i solve this problem?

**Comment by xfxyjwf** [comment]
What version of protoc.exe you are using? Can you try a different version?

**Comment by TheEarthIsFlat** [comment]
Based on your advice, I tried using a previous version of protoc.exe (3.2.0). and now it works well. Perhaps it's not a problem with the 3.3.0 version itself, just the file I owned seems to be corrupted. thank you :)
