### ISSUE TITLE
I'm getting errors in google/protobuf/descriptor.pb.cc

### ISSUE THREAD

**Issue by medhapotluri** [google/protobuf#3362]
`google/protobuf/descriptor.pb.cc:4568:31: error: expected '<' before '<:' token
                 4, static_cast<::google::protobuf::uint64>(value));
                               ^
google/protobuf/descriptor.pb.cc:4568:31: error: expected type-specifier before '<:' token
google/protobuf/descriptor.pb.cc:4568:31: error: expected '>' before '<:' token
google/protobuf/descriptor.pb.cc:4568:31: error: expected '(' before '<:' token
google/protobuf/descriptor.pb.cc:4568:33: error: expected identifier before ':' token
                 4, static_cast<::google::protobuf::uint64>(value));
                                 ^
google/protobuf/descriptor.pb.cc:4568:67: error: expected ']' before ';' token
                 4, static_cast<::google::protobuf::uint64>(value));
                                                                   ^
google/protobuf/descriptor.pb.cc: In lambda function:
google/protobuf/descriptor.pb.cc:4568:67: error: expected '{' before ';' token
google/protobuf/descriptor.pb.cc: In member function 'virtual bool google::protobuf::FieldDescriptorProto::MergePartialFromCodedStream(google::protobuf::io::CodedInputStream*)':
google/protobuf/descriptor.pb.cc:4568:67: warning: lambda expressions only available with -std=c++11 or -std=gnu++11 [enabled by default]
google/protobuf/descriptor.pb.cc:4568:67: error: expected ')' before ';' token`

I get the above errors wherever the line`static_cast<::google::protobuf::uint64>(value));` exists in the code.

**Comment by xfxyjwf** [comment]
This should be fixed by https://github.com/google/protobuf/pull/3353

**Comment by medhapotluri** [comment]
Thanks!!
