### ISSUE TITLE
Python 3 compatibility issue with Protobuf 2.6

### ISSUE THREAD

**Issue by ccope** [google/protobuf#3366]
I'm using Ubuntu 16.04. Some applications (like Rhythmbox) are linked to protobuf 2.6, but then use Python 3 to run plugins. This seems related to issue #7, but the resolution of that thread was to upgrade to protobuf 3 (and I don't want to end up recompiling large swathes of my OS to make this work). Is it feasible to make a bugfix release for protobuf 2.6 with py3 compatibility?

**Comment by xfxyjwf** [comment]
There is no plan to make further 2.6.x releases. If upgrading to newer protobuf versions is not possible, maybe you can make the application use Python 2.x instead of Python 3?

**Comment by ccope** [comment]
Well, I did some horrible hacks to get the 2.6 pip module installed, and then ran 2to3 on the python files. That seemed to mostly work. I considered trying to upstream the fixes, but the pip setup scripts seem to depend on a lot of code that is not python3 compatible and not resolvable by simply running 2to3.
