### ISSUE TITLE
Split into a sub-namespace instead of using underscores for sub-messages

### ISSUE THREAD

**Issue by bshaffer** [google/protobuf#3369]
For PHP, Instead of having class names such as `RedactContentRequest_ReplaceConfig`, it would be better if `RedactContentRequest` was a namespace, and the class was `ReplaceConfig`, i.e.:

```php
namespace Google\Privacy\Dlp\V2beta1\RedactContentRequest;

//...

/**
 * Generated from protobuf message <code>google.privacy.dlp.v2beta1.RedactContentRequest.ReplaceConfig</code>
 */
class ReplaceConfig extends \Google\Protobuf\Internal\Message
{
    //...
}
```

The namespaced version is much cleaner and more idiomatic with the language.

**Comment by jtattermusch** [comment]
@TeBoring, looks like we won't be fixing this as it would be a breaking change?

**Comment by bshaffer** [comment]
Is this really a breaking change? We've made changes to the namespaces before, and I believe these underscores are a recent change. Could we provide a flag to make this change opt-in?

**Comment by TeBoring** [comment]
How about an int file option php_submessage_namespace?

**Comment by bshaffer** [comment]
@TeBoring Sorry for the delay here. This solution definitely works for us!

**Comment by bshaffer** [comment]
@TeBoring is this something we should submit a PR for?

**Comment by TeBoring** [comment]
Added in #4536
