### ISSUE TITLE
Build fails on FreeBSD

### ISSUE THREAD

**Issue by yurivict** [google/protobuf#3373]
See the log here https://github.com/tensorflow/magenta/issues/779 - in the version bundled with
 the magenta project.

**Comment by cluon** [comment]
I traced this down to the following include chain causing problems:
`#include <google/protobuf/io/coded_stream.h>`
pulls in
`#include <sys/param.h>   // __BYTE_ORDER`
which in turn has the curious block:
`
#ifndef LOCORE
#include <sys/types.h>
#endif
`
Manually adding a `#define LOCORE` and `#undef LOCORE` around the include seems to fix the issue, but I haven't had a chance to dig into what LOCORE semantically means in the FreeBSD header ecosystem.

**Comment by cluon** [comment]
Looks like this was actually fixed in #2848.  Don't `#define LOCORE`; grepping the BSD source indicates that the define is used by the kernel to avoid "defining C stuff".

**Comment by BSBandme** [comment]
Close for now. If there's still issue feel free to reoepn
