### ISSUE TITLE
C++: Incorrect JSON output for NullValue

### ISSUE THREAD

**Issue by ewang** [google/protobuf#3376]
Given the following protobuf definition:
```
message Test {
    google.protobuf.NullValue value = 1;
}
```
According to the comment in `google/protobuf/struct.proto`, `google.protobuf.NullValue` should have a JSON representation of `null`. Currently it seems to print the enum string of `NULL_VALUE` instead.

Current:
```
{"value": "NULL_VALUE"}
```
Expected:
```
{"value": null}
```

**Comment by xfxyjwf** [comment]
Can you instead use google.protobuf.Value and set its null_value field if you need it to be "null"? Using NullValue directly out of the scope of google.protobuf.Value could be problematic.
