### ISSUE TITLE
Java type descriptor -> parser

### ISSUE THREAD

**Issue by rogeralsing** [google/protobuf#3379]
in the C# API, it's possible to get the message parser of a type from its type descriptor.
which is very handy when doing dynamic things/ self describing messages.

In Java there seems to be no such support.
Currently I've hacked something together which finds the `PARSER` field of the Java classes.
This works but fragile and ugly.

Is there some way I do not know about, if not, is there any chance of the C# feature being ported over to the Java API?

**Comment by xfxyjwf** [comment]
In Java, you will be using DynamicMessage. Something like:
```java
parser = DynamicMessage.getDefaultInstance(descriptor).getParserForType();
```

**Comment by rogeralsing** [comment]
That gives me an instance of a DynamicMessage, not an instance of the _actual_ message type.

**Comment by xfxyjwf** [comment]
Not sure how C# does that, but there isn't a mapping from descriptor to generated message type in Java. You either have to maintain such a mapping yourself, or use DynamicMessage.

**Comment by rogeralsing** [comment]
In C# we have this:
https://developers.google.com/protocol-buffers/docs/reference/csharp/class/google/protobuf/reflection/generated-clr-type-info

Is there any specific reason why the API's are different, why make something possible in one API and not in some other?

**Comment by jtattermusch** [comment]
Are we planning to fix this or can we close?

**Comment by xfxyjwf** [comment]
As I mentioned in https://github.com/google/protobuf/issues/3379#issuecomment-315848977, this cannot be implemented in Java. We would like to make languages on-par in features but different languages have their limitations.

**Comment by BSBandme** [comment]
I think this won't fix in the near future? 
@xfxyjwf
