### ISSUE TITLE
SerializeToString give incorrect string with empty string as key for Python implement

### ISSUE THREAD

**Issue by ariwaranosai** [google/protobuf#3381]
I found this error during work with tensorflow tf-learn [example.](https://www.tensorflow.org/get_started/tflearn)

```python
  feature_dict = {"": _float_feature(value=[6.4, 3.2, 4.5, 1.5])}
  label = 0

  example = tf.train.Example(features=tf.train.Features(feature=feature_dict))
  serialized = example.SerializeToString()

  request.inputs['inputs'].CopyFrom(
        tf.contrib.util.make_tensor_proto(serialized, shape=[1]))
```
this will give a Example with 

```
features {
     key: ""
     value { float_list {
       value: 6.4
       value: 4.2
       value: 4.5
       value: 1.5
     }}
   }
```

when set fields for Feature object

```python
new_value = type_checker.CheckValue(new_value) 
    if clear_when_set_to_default and not new_value:
      self._fields.pop(field, None)
    else:
      self._fields[field] = new_value
```
since new_value is ""， object won't set key="".

as a result, 

serialized_string = b'\n\x18\n\x16\x12\x14\x12\x12\n\x10\xcd\xcc\xcc@\xcd\xccL@\x00\x00\x90@\x00\x00\xc0?'

but CPP implement give 

b'\n\x1b\n\x19\n\x01f\x12\x14\x12\x12\n\x10\xcd\xcc\xcc@\xcd\xccL@\x00\x00\x90@\x00\x00\xc0?'

**Comment by anandolee** [comment]
Thanks for raising it up. Turns out not only empty string key, all default values do have the same issue. I have fixed it in internal code.
