### ISSUE TITLE
C#: Generated code is not adequately marked as auto-generated

### ISSUE THREAD

**Issue by yaakov-h** [google/protobuf#3388]
There are a few major things that static analysis tools look for, which are missing from the auto-generated C# code.

1. The presence of `<auto-generated />` or `<auto-generated/>` in the header comment block.

2. The presence of `System.CodeDom.Compiler.GeneratedCodeAttribute` on the generated members.

Would you be OK with a pull request to add this to protoc's csharp functionality? Currently the generated code is triggering a whole heap of warnings in various Roslyn Analyzers and FxCop Code Analysis.

(As an aside, would you be OK with fixing up the generated code to satisfy FxCop with the Microsoft Managed Recommended Rules ruleset?)

I don't mind making the change myself, as long as I can figure out the C++ unit testing and the PR doesn't get neglected like #1835.

Thanks.

**Comment by CFlatWouldbeMinor** [comment]
We face the issue as well. I would really like to have the mentioned autogenerated attributes in place

**Comment by lamLeX** [comment]
Hi @jtattermusch, is it possible to have the GeneratedCodeAttribute added to the generated code also? It seems to be asked again here https://github.com/protocolbuffers/protobuf/issues/6960

**Comment by lamLeX** [comment]
@jtattermusch  I found your change in here https://github.com/protocolbuffers/protobuf/commit/5ae7f692f38b12ca027aaebadc3e06f1ecdd1bb1
But it seems isn't built into Google.Protobuf 3.17.2 package yet

**Comment by jtattermusch** [comment]
> @jtattermusch I found your change in here [5ae7f69](https://github.com/protocolbuffers/protobuf/commit/5ae7f692f38b12ca027aaebadc3e06f1ecdd1bb1)
> But it seems isn't built into Google.Protobuf 3.17.2 and Grpc.Tools 2.38.0 package yet
> Here is my package reference
> 
> ```
>     <PackageReference Include="Google.Protobuf" Version="3.17.2" />
>     <PackageReference Include="Grpc.AspNetCore" Version="2.37.0" />
>     <PackageReference Include="Grpc.AspNetCore.Server.Reflection" Version="2.37.0" />
>     <PackageReference Include="Grpc.Tools" Version="2.38.0">
>       <PrivateAssets>all</PrivateAssets>
>       <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
>     </PackageReference>
> ```
> 
> I updated the `Google.Protobuf` and `Grpc.Tools` because the `Grpc.AspNetCore` still referencing the older version

The changes will be in the next release of Grpc.Tools and Google.Protobuf.
