### ISSUE TITLE
Is is safe to throw a C++ exception from a handler installed with SetLogHandler()?

### ISSUE THREAD

**Issue by dariomt** [google/protobuf#3389]
In my use case it is most convenient to be able to sometimes throw from a LogHandler.
Will something in protobuf break?
Does the library assume that a LogHandler never throws?
Or is it safe to throw a C++ exception fro a LogHandler?

Thank you!

**Comment by acozzette** [comment]
This will probably not work unfortunately. The Google C++ style guide [forbids](https://google.github.io/styleguide/cppguide.html#Exceptions) exceptions, and so the protobuf codebase generally assumes that nothing ever throws.

**Comment by dariomt** [comment]
Thanks for the info.
