### ISSUE TITLE
Potential SIGBUS with UnsafeUtil.getLong

### ISSUE THREAD

**Issue by alanbur** [google/protobuf#3394]
In earlier releases `com.google.protobuf.Utf8.unsafeEstimateConsecutiveAscii(byte[] bytes, long offset, final int maxChars)` would cause SIGBUS alignment coredumps on platforms that enforce alignment constraints. This was fixed, the code now does

`final int unaligned = 8 - ((int) offset & 7);`

However an equivalent calculation in `com.google.protobuf.Utf8.unsafeEstimateConsecutiveAsciil(ong address, final int maxChars)` was not fixed and still uses the following incorrect code:

` final int unaligned = (int) address & 7;`

That should be:

` final int unaligned = 8 - ((int) address &  7);`

**Comment by xfxyjwf** [comment]
Can you help send a pull request?

**Comment by alanbur** [comment]
I can but I'll have to take it through our legal process first

**Comment by AlanBurlison** [comment]
Pull request submitted as requested - https://github.com/google/protobuf/pull/3473

**Comment by jtattermusch** [comment]
fixed by #3473
