### ISSUE TITLE
php requirements missed

### ISSUE THREAD

**Issue by server-may-cry** [google/protobuf#3405]
That requirements must be at least in [composer.json](/google/protobuf/blob/master/composer.json) file "[suggest](https://getcomposer.org/doc/04-schema.md#suggest)" section
1. ext-bcmath for [bccomp](https://github.com/google/protobuf/search?l=PHP&q=bccomp&type=&utf8=%E2%9C%93) function
2. ext-json for [json_encode](https://github.com/google/protobuf/search?l=PHP&q=json_encode&type=&utf8=%E2%9C%93) function

Extension not always included in php
```
Error: Call to undefined function Google\Protobuf\Internal\bccomp()

/app/php/vendor/google/protobuf/php/src/Google/Protobuf/Internal/Message.php:776
/app/php/vendor/google/protobuf/php/src/Google/Protobuf/Internal/Message.php:880
/app/php/vendor/google/protobuf/php/src/Google/Protobuf/Internal/Message.php:908
/app/php/vendor/google/protobuf/php/src/Google/Protobuf/Internal/Message.php:666
/app/php/tests/ProtoTest.php:58
```

**Comment by TeBoring** [comment]
Could you help send a fix?

**Comment by TeBoring** [comment]
BTW, ext-json is not longer needed in our latest release.

**Comment by dianasong** [comment]
I am a fresh,please teach more in the future
