### ISSUE TITLE
MapField missing IteratorAggregate interface in PHP

### ISSUE THREAD

**Issue by meanevo** [google/protobuf#3408]
Env: macOS 10.12.6 / PHP 7.1.6 with Protobuf C-extension
as the picture shown, the [MapField](https://github.com/google/protobuf/blob/master/php/src/Google/Protobuf/Internal/MapField.php#L44) class can not be iterated.

![f2b8f72a-b5db-4bce-aa6c-1a6582c140d0](https://user-images.githubusercontent.com/1898273/28538094-a038a688-70df-11e7-9359-dafb8493074e.png)

It was really difficult to get all the data from map<uint32, uint32> aka array in php, I can only retrieve data by provide a key explicitly.

I'd like to know if I was misunderstanding something here.. thx

**Comment by meanevo** [comment]
missing the interface, foreach iterates nothing.
![qq20170725-022844](https://user-images.githubusercontent.com/1898273/28538495-025a5310-70e1-11e7-9acd-400249d75054.jpg)
![37cd336d-054f-4cad-bfbe-e5c1c6e37ce2](https://user-images.githubusercontent.com/1898273/28538496-03622274-70e1-11e7-9922-57a641ae2fc3.png)

**Comment by TeBoring** [comment]
I remember it has been added in MASTER HEAD. That feature will be available in 3.4 release.

**Comment by TeBoring** [comment]
Dup of #3341

**Comment by meanevo** [comment]
didn't notice there is a duplicate, my mistake
