### ISSUE TITLE
gzip_stream.h not installed

### ISSUE THREAD

**Issue by Bu11etmagnet** [google/protobuf#342]
The 'make install' step of version 2.6.1 did this:

 /usr/bin/mkdir -p '/usr/local/include/google/protobuf/io'
 /usr/bin/install -c -m 644  google/protobuf/io/coded_stream.h google/protobuf/io/printer.h google/protobuf/io/strtod.h google/protobuf/io/tokenizer.h google/protobuf/io/zero_copy_stream.h google/protobuf/io/zero_copy_stream_impl.h google/protobuf/io/zero_copy_stream_impl_lite.h '/usr/local/include/google/protobuf/io'

gzip_stream.h is conspicuously absent

**Comment by xfxyjwf** [comment]
That gzip header will only be installed if ./configure can find the zip lib. Could you check the log message of "./configure" and see if it has "checking zlib version... ok.."?

**Comment by haberman** [comment]
Closing due to lack of information.
