### ISSUE TITLE
Add node.js/Javascript support

### ISSUE THREAD

**Issue by xfxyjwf** [google/protobuf#343]

**Comment by cfallin** [comment]
FYI for anyone watching this: JS support is currently in-progress.

**Comment by xfxyjwf** [comment]
We decided to skip it in v3.0.0-alpha-3 release.

**Comment by seishun** [comment]
Sorry if this is the wrong place to ask.

1. Is the plan to make a pure JS module or one that requires compilation?
2. Are you planning to convert field names into camelCase like it's done in the Java implementation, or to keep them as-is? I'm passing decoded objects directly to users and I'd prefer to avoid breaking the API when I switch to the official implementation. (I'm currently using ProtoBuf.js which supports both, so I can change it in the upcoming major version)

**Comment by xfxyjwf** [comment]
JavaScript support is added to the js directory:
https://github.com/google/protobuf/tree/master/js
