### ISSUE TITLE
ImportError: No module named 'InternalMessage_pb2'

### ISSUE THREAD

**Issue by mrvn** [google/protobuf#3430]
In Message.proto I have a line `import "InternalMessage.proto";` and when I compile the proto file with

    protoc -Iqlunet --python_out=qlunet Message.proto

that results in a import statement

    import InternalMessage_pb2 as InternalMessage__pb2

When I try to import Message_pb2 I get the following error:

    ImportError: No module named 'InternalMessage_pb2'

The problem I think is that the import should use

    from . import InternalMessage_pb2 as InternalMessage__pb2

How do I make protoc output a relative import statement?

**Comment by anandolee** [comment]
Will not add relative import for protoc.
See #1491 for more info

**Comment by mrvn** [comment]
Thanks for the reference. This should really be better explained in the python language guide. People have been stumbling into this problem for years as the number of related issues shows.

**Comment by mojovski** [comment]
If your protobuf files are in the proto directory, add:
```
sys.path.append("./proto")
```
before importing
```
from proto.typename_pb2 as tn
```

**Comment by jahidhasanlinix** [comment]
I am getting this error when calling .proto file. any suggestion how to fix it. 


  File "server.py", line 3, in <module>
    import ipc_msg_pb2
ModuleNotFoundError: No module named 'ipc_msg_pb2'
