### ISSUE TITLE
Web UI fails for protobuf.js with chrome version 59.0.3071.86

### ISSUE THREAD

**Issue by renjithgg** [google/protobuf#3435]
Typescript application(UI) fails while making web socket communication through proto(protobuf.js). Issue is observed only with Chrome latest version(59.0.3071.86)

**Comment by haberman** [comment]
ProtoBuf.js is a separate implementation of protobuf developed in a separate repository (https://github.com/dcodeIO/ProtoBuf.js/). Issues against it should be filed there.
