### ISSUE TITLE
PHP c extension setter error

### ISSUE THREAD

**Issue by michaelbausor** [google/protobuf#3446]
I am seeing an error when using setters in the PHP c extension. It seems that the `binding` field is being set by the `setEtag` method in the example below. The following code uses the Policy class [available here](https://github.com/googleapis/gax-php/blob/master/src/generated/Google/Iam/V1/Policy.php).

```
$policy = new Policy();
$policy->setEtag("myetag");
var_dump($policy->getEtag());
var_dump($policy->getBindings());
```
produces this output:
```
/usr/local/google/home/michaelbausor/dev/veneer/testing/php-release-test/tests/system/Iam/IamTest.php:23:
string(6) "myetag"
/usr/local/google/home/michaelbausor/dev/veneer/testing/php-release-test/tests/system/Iam/IamTest.php:24:
string(6) "myetag"
```

When the c extension is disabled, the output is correct:
```
/usr/local/google/home/michaelbausor/dev/veneer/testing/php-release-test/tests/system/Iam/IamTest.php:23:
string(6) "myetag"
/usr/local/google/home/michaelbausor/dev/veneer/testing/php-release-test/tests/system/Iam/IamTest.php:24:
class Google\Protobuf\Internal\RepeatedField#244 (3) {
  private $container =>
  array(0) {
  }
  private $type =>
  int(11)
  private $klass =>
  string(21) "Google\Iam\V1\Binding"
}
```

**Comment by TeBoring** [comment]
In master?

**Comment by michaelbausor** [comment]
I am finding this issue with master, but also with 3.3.2 installed via pecl.

**Comment by TeBoring** [comment]
https://github.com/google/protobuf/commit/c78dbd7c895b8c80cd2f2401d73acf890edf82c6
Similar bug has been fixed in this PR.
Could you show me the definition of proto?

**Comment by michaelbausor** [comment]
The proto is defined here: https://github.com/googleapis/googleapis/blob/master/google/iam/v1/policy.proto#L60

Looks like the fields are "out of order", in that `bindings = 4` is before `etag = 3`

Should I try to regenerate using a protoc version with that fix?
