### ISSUE TITLE
README.md contains incorrect setup information.

### ISSUE THREAD

**Issue by dustinevan** [google/protobuf#3447]
**From the Reference Page**
https://developers.google.com/protocol-buffers/docs/gotutorial
1. If you haven't installed the compiler, download the package and follow the instructions in the README.

**From the Download Page**
https://developers.google.com/protocol-buffers/docs/downloads
Latest Version
The latest release of Protocol Buffers can be found on the release page.

**From the Release Page**
https://github.com/google/protobuf/releases/tag/v3.3.0
(Go users need to know to use the cpp zip or tar)

**From the README**
In the downloads section of each release, you can find pre-built binaries in
zip packages: protoc-$VERSION-$PLATFORM.zip. **_It contains the protoc binary_**
as well as a set of standard .proto files distributed along with protobuf.

The italicized part is not currently true
`find . | grep protoc` returns
`./cmake/libprotoc.cmake
./cmake/protoc.cmake
./src/libprotoc.map`

currently the instructions in src/README.md must be followed to build the binary. 

Mac + Go users could also be pointed to `brew install protobuf`

**Comment by xfxyjwf** [comment]
I think you downloaded the wrong package. The protoc binary is only available in `protoc-$VERSION-$PLATFORM.zip`, for example:
https://github.com/google/protobuf/releases/download/v3.3.0/protoc-3.3.0-linux-x86_64.zip

You probably downloaded the source tar ball rather than the protoc one.
