### ISSUE TITLE
PHP feature request: setters return $this

### ISSUE THREAD

**Issue by server-may-cry** [google/protobuf#3448]
Currently i have
```php
$msg = new MyMessage();
$msg->setType('myType');
$msg->setAmount(10);
```
if setters will `return $this;`, i can write
```php
$msg = new MyMessage();
$msg
    ->setType('myType')
    ->setAmount(10)
;
```
I'm not well know C++ to do that by myself and make pull request. https://github.com/google/protobuf/blob/master/src/google/protobuf/compiler/php/php_generator.cc

**Comment by TeBoring** [comment]
This has been implemented in master.
