### ISSUE TITLE
Fix spurious "warning: directory does not exist" messages in {cc,py}_proto_library

### ISSUE THREAD

**Issue by htuch** [google/protobuf#3449]
When building https://github.com/lyft/envoy-api, we see a lot of warning spew of the form:

```
INFO: From ProtoCompile api/filter/http_connection_manager.pb.cc:
bazel-out/local-fastbuild/genfiles/external/googleapis: warning: directory does not exist.
bazel-out/local-fastbuild/genfiles/external/protobuf_bzl/src: warning: directory does not exist.
bazel-out/local-fastbuild/genfiles/external/protobuf_bzl/src: warning: directory does not exist.
bazel-out/local-fastbuild/genfiles/external/googleapis: warning: directory does not exist.
bazel-out/local-fastbuild/genfiles/external/protobuf_bzl/src: warning: directory does not exist.
bazel-out/local-fastbuild/genfiles/external/protobuf_bzl/src: warning: directory does not exist.
bazel-out/local-fastbuild/genfiles/external/googleapis: warning: directory does not exist.
bazel-out/local-fastbuild/genfiles/external/protobuf_bzl/src: warning: directory does not exist.
bazel-out/local-fastbuild/genfiles/external/protobuf_bzl/src: warning: directory does not exist.
```

Digging into this, it appears the `protobuf_bzl/src` errors are a result of https://github.com/google/protobuf/blob/dd04ffb923d2048a9ba054f2099d450bea4fae68/protobuf.bzl#L74 adding a `genfiles` include for the Protobuf cc_wkt_protos, which don't have a generated component. 

I looked into removing `genfiles` for just the internal bootstrap proto hack (i.e. the WKTs), but this still left:

```
bazel-out/local-fastbuild/genfiles/external/googleapis: warning: directory does not exist.
```

This doesn't appear when I do `--spawn_strategy=standalone`, indicating that there is some missing dependency. I think the protogen rule https://github.com/google/protobuf/blob/dd04ffb923d2048a9ba054f2099d450bea4fae68/protobuf.bzl#L122 is not picking up on the genfiles directory correctly.

Creating this issue to track further investigation and a fix.

**Comment by htuch** [comment]
It doesn't look like the C++ build actually depends on anything in `bazel-out/local-fastbuild/genfiles/external/googleapis`, so this isn't a true dependency.

I'm wondering what the right fix is here. Some random ideas:

1. Provide an option to `cc_proto_library` to not add any `-I ..genfiles..` for a given target, where the target author know in advance this makes no sense. In general, it seems that this is fragile, and will have to default true for C++ at least.

2. Have Bazel always create and map into the sandbox a genfiles directory. Doesn't seem unreasonable, but requires some Bazel level changes.

3. Have `protoc` silently ignore these missing directories, conditioned on some flag.

**Comment by xfxyjwf** [comment]
Bazel has native support for cc_proto_library rule now and you probably should use that native rule instead. We do not indent to support the build extensions in protobuf.bzl longer term.

**Comment by bhamapillutla** [comment]
can anybody help me with this..
warning :   bazel-out/x64_windows-opt/genfiles/external/protobuf_archive/src: warning: directory does not exist.

**Comment by abe157** [comment]
What worked for me was creating the directory myself using `mkdir` and using the `--cxxopt=-std=c++11.` flag from #5728 when building with bazel.
