### ISSUE TITLE
DESCRIPTOR.services_by_name not populated when PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python

### ISSUE THREAD

**Issue by nathanielmanistaatgoogle** [google/protobuf#3452]
On my recent-enough-ish Debian (8.7) workstation with `virtualenv` 13.1.2:
```
$ virtualenv venv
$ venv/bin/pip install --upgrade pip  # installs pip 9.0.1
$ venv/bin/pip install --upgrade protobuf  # installs protobuf 3.3.0 setuptools-36.2.7 six-1.10.0
$ wget https://raw.githubusercontent.com/grpc/grpc/master/examples/python/helloworld/helloworld_pb2.py
$ venv/bin/python2.7
>>> import helloworld_pb2
>>> dict(helloworld_pb2.DESCRIPTOR.services_by_name)
{'Greeter': <google.protobuf.pyext._message.ServiceDescriptor object at 0x7fad70510550>}
```
but if I change
```
$ venv/bin/python2.7
```
to
```
$ PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python venv/bin/python2.7
```
the `services_by_name` [FileDescriptor](https://developers.google.com/protocol-buffers/docs/reference/python/google.protobuf.descriptor.FileDescriptor-class) attribute is not populated:
```
$ PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python venv/bin/python2.7
>>> import helloworld_pb2
>>> dict(helloworld_pb2.DESCRIPTOR.services_by_name)
{}
```
! What's up with that?

**Comment by mehrdada** [comment]
I think this is a duplicate of https://github.com/google/protobuf/issues/2882 and would be fixed via a change in protoc.

**Comment by nathanielmanistaatgoogle** [comment]
@mehrdada: go into more detail? I have my doubts. Notice in my report that I'm making use of already-generated code, so how would a change to the code generator have any effect? The difference arises between the return values of the two different implementations of `google.protobuf.descriptor.FileDescriptor`, right? And that's in static code in both implementations?

**Comment by mehrdada** [comment]
Yes, I meant there is a protoc change is needed, in addition to a slight change to the library itself. 

cl/160426863 and cl/160323171 together fix the issue, I think. They just need to be exported.

**Comment by nathanielmanistaatgoogle** [comment]
@mehrdada: you're right about the generated code needing to be regenerated. Closing.
