### ISSUE TITLE
are reserved available in ENUMS?

### ISSUE THREAD

**Issue by roidelapluie** [google/protobuf#3458]
Is it possible to use RESERVED in ENUMS? The proto3 language guide does not tell anything about this.

**Comment by xfxyjwf** [comment]
You can't use reserved in enums at the moment. The support was already added in our internal code base though. It missed the integration for 3.4.0 release but should be able to make its way into 3.5.0 release.

**Comment by haberman** [comment]
This has been released.

**Comment by Siddhant** [comment]
I think it would be best if it is explicitly documented in the guides that enum values can also be reserved.
(For both proto2 and proto3 guides.)

**Comment by Siddhant** [comment]
My bad. It has already been documented here:
https://developers.google.com/protocol-buffers/docs/proto3#enum_reserved
https://developers.google.com/protocol-buffers/docs/proto#enum_reserved

**Comment by BMomani** [comment]
Im unable to reserve the first item in the enum 

```
enum myChangingEnum {
  reserved 0;
  second = 1;
  third= 2;
}
```
Im getting this error

>First enum value must be 0 in proto3

but reserving not the first one is okay 
```
enum thisEnumOkay {
  thisMustNotChanged = 0;
  reserved 1;
  whatever= 2;
}
```
