### ISSUE TITLE
Decoding message php

### ISSUE THREAD

**Issue by fisnikhajredini** [google/protobuf#3462]
As im receiving an encoded string from another server, i want to be able to decode it and show the message as a human readable string. 

Now i got everything working but i cant seem to be finding any function to return any string. 

`$protoClass = new ModuleStatistics();`
`$protoClass -> mergeFromString($receivedString);`

mergeFromString() doesnt give me any error but it doesnt retrun anything neither. There is more details [here](https://stackoverflow.com/questions/45527187/decoding-message-in-protocol-buffers-php).

**Comment by adhesiveNOR** [comment]
If you're trying to serialize the full proto object to string, you can use
$protoClass->serializeToString();

**Comment by fisnikhajredini** [comment]
I have tried that. Here is what i get from this code:
```
echo "----------------------------------------";      
try{`    
   $protoClass -> mergeFromString($tcpData);
   $protoClass -> serializeToString();

   $protoClass -> serializeToString()
   $raw= $protoClass -> serializeToString();
    
   echo "serialized\n"; 
   $moduleStats=$protoClass -> getModuleStatistics();
   echo "got module stats\n";
   echo "echoing serializeToString():\n". $raw;
}catch (Exception $e){
   echo "error on one of them\n" . $e;
   echo "----------------------------------------";
}`
```

And this is what i get from that one:
```
-----------------------------------------
serialized
got module stats
echoing serializeToString():
----------------------------------------
Wrote data
-----------------------------------------
serialized
got module stats
echoing serializeToString():
----------------------------------------
Wrote data
-----------------------------------------
serialized
got module stats
echoing serializeToString():
----------------------------------------
```

If my understanding is correct, i already have the serialized object. I am only receiving 1 (ModuleStatistics) of the 4 messages of the proto file. Now the message ModuleStatistics uses other message types as field types. Do i need to receive all the other messages in order to decode it and make the data human readable string?

**Comment by TeBoring** [comment]
serializeToString is not human readable. Use serializeToJsonString

**Comment by fisnikhajredini** [comment]
Then it doesnt find it: `PHP Fatal error:  Call to undefined method ModuleStatistics::serializeToJsonString() in /app/index.php on line 41` 

Eventho serializeToString is not human readable, its supposed to return something right.. or at least give an error?

**Comment by TeBoring** [comment]
Ah, serializeToJsonString will be released in 3.4 release.
serializeToString do return something, you need to use bin2hex to transfer it first.

**Comment by fisnikhajredini** [comment]
As far as i can see serializeToString is to encode a message. In my case i already have the message encoded, i receive it encoded and i need to decode it. Im using mergeToString but the message `ModuleStatistics` has only one field type and its another message called `ModuleStatistic`. I am only receiving `ModuleStatistis` and in c++ i have `toString` which allows me to get readable string of the class ModuleStatistics. In php however i dont have anything like that and that is my goal. 

Do i need to receive the other 3 messages to decode the 'parent' message in php?

**Comment by TeBoring** [comment]
Could you explain what's the relation between ModuleStatistis and ModuleStatistics?
Could you also show your c++ code to let me understand what you are trying to do.

**Comment by TeBoring** [comment]
Feel free to reopen this issue if there is still any problem.
