### ISSUE TITLE
I cann't import Caffe and Apollocaffe with eachother.Protobuf error occures

### ISSUE THREAD

**Issue by Samaneh1994** [google/protobuf#3469]
I installed Caffe and Apollocaffe successfully. now I want to import them in python, an error occures :

 `[libprotobuf ERROR google/protobuf/descriptor_database.cc:57] File already exists in database: caffe.proto
[libprotobuf FATAL google/protobuf/descriptor.cc:1080]CHECK failed: generated_database_->Add(encoded_file_descriptor, size):
terminate called after throwing an instance of 'google::protobuf::FatalException'
  what(): CHECK failed: generated_database_->Add(encoded_file_descriptor, size)
:
Aborted (core dumped) `
I searched about this and I understand that the error is because of twice using of protobuf.so
What should I do ?
I appreciate any help.

**Comment by pherl** [comment]
I searched around and found: https://github.com/Russell91/ReInspect/issues/21 Hope that helps. Closing this issue for now.
