### ISSUE TITLE
No way to change generated Ruby module names

### ISSUE THREAD

**Issue by grantr** [google/protobuf#3471]
Many protoc generator implementations support options for the naming of generated classes, e.g. `java_package` and `go_package`. Ruby does not. This causes problems when a generated package conflicts with an existing class hierarchy:

```ruby
# Existing class
module Bigco
  class Embiggener
    # ...
  end
end

# Generated code for the bigco.embiggener.v1 package
module Bigco
  module Embiggener # <-- causes a syntax error because the class is already defined above
    module V1
      # ...
    end
  end
end
```

It'd be nice to have an option `ruby_namespace` to specify an alternate namespace hierarchy, similar to `java_package`.

**Comment by TeBoring** [comment]
https://github.com/google/protobuf/pull/4627
