### ISSUE TITLE
goog.require could not find: jspb.Message

### ISSUE THREAD

**Issue by StevenWash** [google/protobuf#3472]
Hi @willnorris ,
I am using the protobuf-js ,and I use 'npm install google-protobuf' to install it .Then I use 'goog.require('jspb.Message');' to get the 'Message',but it occured like this:
![image](https://user-images.githubusercontent.com/18731292/29064166-baec1678-7c5a-11e7-8687-bbb3fc398d3a.png)

And I use it in a Angular-cli project.I impot it in the .angular-cli.json like that:
![image](https://user-images.githubusercontent.com/18731292/29064224-eab13bae-7c5a-11e7-9aba-37768c6ca024.png)

Can anyone help me ?Thank you  very much!

**Comment by vividxuan** [comment]
I suggest that you include these files which  needed are located in js/binary  subdirectory; arith.js, constants.js, decoder.js, encoder.js, reader.js, utils.js, writer.js    and other two  in js  map.js, message.js,

**Comment by haberman** [comment]
@vividxuan is correct, you need to ensure that the core runtime is available. You can see all of the files we pass to the Closure builder in the repo's gulpfile: https://github.com/google/protobuf/blob/master/js/gulpfile.js#L116
