### ISSUE TITLE
Is this protobuf js lib suitable for angular project?

### ISSUE THREAD

**Issue by StevenWash** [google/protobuf#3477]
Hi @willnorris @haberman @bakineggs @nico ,
I want to use the protobuf js lib in my angular project.And I have generate the kurapayload.js according to the kurapayload.proto.But in my angular project the protobuf maybe can not be imported correctly.So anyone can help me ?
Thank you very much!

**Comment by haberman** [comment]
Are you having a specific problem, or are you asking about a hypothetical problem?

The protobuf generated code is regular JavaScript, so should be able to be used in an Angular project or any JavaScript project.
