### ISSUE TITLE
Illegal name in ENUM

### ISSUE THREAD

**Issue by kahwooi** [google/protobuf#3479]
I have this COMPLETED-KO = 2; in ENUM, but I get this error `illegal name: COMPLETED-KO`

**Comment by thomasvl** [comment]
A hyphen ("-") isn't valid in an enum value name (or enum, message, field, or extension name).  Use an underscore ("_").

**Comment by earonesty** [comment]
so sad, hyphens were already used in our enumerated system when switching to protobuf, so we have to shim in our own hyphen-to-underscore conversion every time we use it.
