### ISSUE TITLE
Having trouble with bytes field in Python3

### ISSUE THREAD

**Issue by asgoel** [google/protobuf#3489]
Hey all,

Am having trouble setting a `repeated bytes` field in python3 (not having the same error in python2).

Python version: 3.5.2. Protobuf 3.3 C++ implementation.

Sample proto:

```
syntax = "proto2";

message TestBytesMessage {
  repeated bytes key_id = 1;
```

Python result:
```
tb = TestBytesMessage()
decoded = base64.b16decode("EE876DD2127D862BF3C2856A81689E4B")
( b'\xee\x87m\xd2\x12}\x86+\xf3\xc2\x85j\x81h\x9eK' )

tb.key_id.extend(decoded)
TypeError: 238 has type int, but expected one of: bytes

(a simpler one)
tb.key_id.extend(b"ASDF")
TypeError: 65 has type int, but expected one of: bytes
```

Am I missing something here, or not doing something right?

**Comment by pherl** [comment]
I think the protobuf on python3.5 and 3.6 were broken. It should have been fixed on master already. @anandolee to confirm. We may push for a 3.4.1 release for python only.

**Comment by anandolee** [comment]
Jenkins tests fail on 3.5 and 3.6. We are still working on this

**Comment by asgoel** [comment]
Any update on this one? Python 3.3 is reaching [EOL next month](https://www.python.org/dev/peps/pep-0398/#x-end-of-life)

**Comment by asgoel** [comment]
Just kidding, this was actually my bad. I seem to have forgotten python syntax and was using `extend` with a singular element instead of an array. Feel free to close unless you see any other issues.
