### ISSUE TITLE
where is protoc in the downloaded zip?

### ISSUE THREAD

**Issue by suarezu** [google/protobuf#3490]
![image](https://user-images.githubusercontent.com/11764393/29299841-2674f2fe-81a4-11e7-9cf3-8b6e90966d10.png)

Hi there, two questions from the README.md:
1. where is the protoc binary in the downloaded protobuf-java-3.3.0.zip?

2. please update the readme, platform goes first in the name of the zip file.

**Comment by suarezu** [comment]
sorry for not clearly putting it, the platform is java

**Comment by xfxyjwf** [comment]
There isn't a protoc binary in protobuf-java-3.3.0.zip. The readme says "protoc-$VERSION-$PLATFORM.zip". You downloaded the wrong package.

**Comment by xfxyjwf** [comment]
You should download protoc-3.3.0-win32.zip (or the linux, osx version depending on your platform).
