### ISSUE TITLE
Code should compile with --std=c++03 before we switch to c++11 only.

### ISSUE THREAD

**Issue by pherl** [google/protobuf#3492]
I tried to compile a c++03 protoc on mac, but it seems to be broken:  following is an incomplete list of the failures. We should test the c++03 compatibility before making the C++11 only switch.

1) va_copy undefined - used in src/google/protobuf/stubs/stringprintf.cc
va_copy is only defined after C++11, however clang implicitly defines it when --std is not explicitly set. If --std=c++03 is passed, the function is not found. (need to use __va_copy)

2) isinf undefined - used in src/google/protobuf/stubs/mathlimits.h
there's a hack to workaround the including issue for gcc4.9 bug (see comments in the mathlimits.h). But plain isinf is not defined for clang for non C++11.

**Comment by xfxyjwf** [comment]
I don't think our code base ever compiles with --std=c++03. The va_copy code has been there since always.
