### ISSUE TITLE
Generated C++ code has compile warnings with -Wmissing-declarations compiler option set

### ISSUE THREAD

**Issue by robhancocksed** [google/protobuf#3497]
Using gcc 7.1.1 and protobuf 3.2.0, the C++ method AddDescriptorsImpl generated by protoc generates warnings when the -Wmissing-declarations flag is specified:

`
IpAudioRateProto.pb.cc: In function ‘void sedsystems::udsdm::proto::protobuf_sedsystems_2fuds_2fudsdm_2fIpAudioRateProto_2eproto::AddDescriptorsImpl()’:
IpAudioRateProto.pb.cc:71:6: warning: no previous declaration for ‘void sedsystems::udsdm::proto::protobuf_sedsystems_2fuds_2fudsdm_2fIpAudioRateProto_2eproto::AddDescriptorsImpl()’ [-Wmissing-declarations]
 void AddDescriptorsImpl() {
      ^~~~~~~~~~~~~~~~~~
`

The idea of this warning is that the method is globally visible but not previously declared in a header file, so presumably it can't be used outside that compilation unit. This is intended to catch cases where functions are only used in a given compilation unit and should be made static, or where the definition doesn't match the declaration that was intended for it. It's unfortunate that Protobuf-generated code now produces these warnings.

The easiest solution would seem to be to make the generated AddDescriptorsImpl method static.

**Comment by pherl** [comment]
I believe this should have been fixed now. Do you mind check if you still
get the issue on master?

**Comment by robhancocksed** [comment]
It looks like this commit should fix it, though I haven't tested: https://github.com/google/protobuf/commit/b6da2262e811d5c8d4b65d62756e9901a8dff48d

**Comment by pherl** [comment]
Let me know if you still see the issue.
