### ISSUE TITLE
Protobuf 3.3.0 name collision message Shutdown with TableStruct::Shutdown()

### ISSUE THREAD

**Issue by konstantin-psu** [google/protobuf#3498]
Compiling on ubuntu 16.04 x64, with gcc 7.1
If message Shutdown is defined, we get name clash with TableStruct::Shutdown()

For example:
test.proto
syntax = "proto2";

package com.test.pluginmessages;

message Shutdown {
  optional string testField = 1;
}

In file included from /usr/include/google/protobuf/message_lite.h:45:0,
                 from /usr/include/google/protobuf/generated_message_table_driven.h:34,
                 from test.pb.h:25,
                 from test.pb.cc:5:
test.pb.cc:50:50: error: ISO C++ forbids declaration of ‘type name’ with no type [-fpermissive]
   GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Shutdown, _has_bits_),
                                                  ^
/home/konstantin/twRepos/axon/cap-common/build/external/linux/x86/64/gcc/abi1011/include/google/protobuf/generated_message_util.h:105:35: note: in definition of macro ‘GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET’
           &reinterpret_cast<const TYPE*>(16)->FIELD) -               \
                                   ^~~~
test.pb.cc:50:50: error: expected ‘>’ before ‘Shutdown’
   GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Shutdown, _has_bits_),
                                                  ^
/home/konstantin/twRepos/axon/cap-common/build/external/linux/x86/64/gcc/abi1011/include/google/protobuf/generated_message_util.h:105:35: note: in definition of macro ‘GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET’
           &reinterpret_cast<const TYPE*>(16)->FIELD) -               \
                                   ^~~~
test.pb.cc:50:50: error: expected ‘(’ before ‘Shutdown’
   GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Shutdown, _has_bits_),
                                                  ^
/home/konstantin/twRepos/axon/cap-common/build/external/linux/x86/64/gcc/abi1011/include/google/protobuf/generated_message_util.h:105:35: note: in definition of macro ‘GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET’
           &reinterpret_cast<const TYPE*>(16)->FIELD) -               \
                                   ^~~~
/home/konstantin/twRepos/axon/cap-common/build/external/linux/x86/64/gcc/abi1011/include/google/protobuf/generated_message_util.h:105:40: error: expected primary-expression before ‘>’ token
           &reinterpret_cast<const TYPE*>(16)->FIELD) -               \
                                        ^
test.pb.cc:50:3: note: in expansion of macro ‘GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET’
   GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Shutdown, _has_bits_),
   ^
/home/konstantin/twRepos/axon/cap-common/build/external/linux/x86/64/gcc/abi1011/include/google/protobuf/generated_message_util.h:105:45: error: base operand of ‘->’ is not a pointer
           &reinterpret_cast<const TYPE*>(16)->FIELD) -               \
                                             ^
test.pb.cc:50:3: note: in expansion of macro ‘GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET’
   GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Shutdown, _has_bits_),
   ^
test.pb.cc:51:50: error: ISO C++ forbids declaration of ‘type name’ with no type [-fpermissive]
   GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Shutdown, _internal_metadata_),
                                                  ^
/home/konstantin/twRepos/axon/cap-common/build/external/linux/x86/64/gcc/abi1011/include/google/protobuf/generated_message_util.h:105:35: note: in definition of macro ‘GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET’
           &reinterpret_cast<const TYPE*>(16)->FIELD) -               \
                                   ^~~~
test.pb.cc:51:50: error: expected ‘>’ before ‘Shutdown’
   GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Shutdown, _internal_metadata_),
                                                  ^
/home/konstantin/twRepos/axon/cap-common/build/external/linux/x86/64/gcc/abi1011/include/google/protobuf/generated_message_util.h:105:35: note: in definition of macro ‘GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET’
           &reinterpret_cast<const TYPE*>(16)->FIELD) -               \
                                   ^~~~
test.pb.cc:51:50: error: expected ‘(’ before ‘Shutdown’
   GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Shutdown, _internal_metadata_),
                                                  ^
/home/konstantin/twRepos/axon/cap-common/build/external/linux/x86/64/gcc/abi1011/include/google/protobuf/generated_message_util.h:105:35: note: in definition of macro ‘GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET’
           &reinterpret_cast<const TYPE*>(16)->FIELD) -               \
                                   ^~~~
/home/konstantin/twRepos/axon/cap-common/build/external/linux/x86/64/gcc/abi1011/include/google/protobuf/generated_message_util.h:105:40: error: expected primary-expression before ‘>’ token
           &reinterpret_cast<const TYPE*>(16)->FIELD) -               \
                                        ^
test.pb.cc:51:3: note: in expansion of macro ‘GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET’
   GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Shutdown, _internal_metadata_),
   ^
/home/konstantin/twRepos/axon/cap-common/build/external/linux/x86/64/gcc/abi1011/include/google/protobuf/generated_message_util.h:105:45: error: base operand of ‘->’ is not a pointer
           &reinterpret_cast<const TYPE*>(16)->FIELD) -               \
                                             ^
test.pb.cc:51:3: note: in expansion of macro ‘GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET’
   GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Shutdown, _internal_metadata_),
   ^
test.pb.cc:55:50: error: ISO C++ forbids declaration of ‘type name’ with no type [-fpermissive]
   GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Shutdown, testfield_),
                                                  ^
/home/konstantin/twRepos/axon/cap-common/build/external/linux/x86/64/gcc/abi1011/include/google/protobuf/generated_message_util.h:105:35: note: in definition of macro ‘GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET’
           &reinterpret_cast<const TYPE*>(16)->FIELD) -               \
                                   ^~~~
test.pb.cc:55:50: error: expected ‘>’ before ‘Shutdown’
   GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Shutdown, testfield_),
                                                  ^
/home/konstantin/twRepos/axon/cap-common/build/external/linux/x86/64/gcc/abi1011/include/google/protobuf/generated_message_util.h:105:35: note: in definition of macro ‘GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET’
           &reinterpret_cast<const TYPE*>(16)->FIELD) -               \
                                   ^~~~
test.pb.cc:55:50: error: expected ‘(’ before ‘Shutdown’
   GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Shutdown, testfield_),
                                                  ^
/home/konstantin/twRepos/axon/cap-common/build/external/linux/x86/64/gcc/abi1011/include/google/protobuf/generated_message_util.h:105:35: note: in definition of macro ‘GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET’
           &reinterpret_cast<const TYPE*>(16)->FIELD) -               \
                                   ^~~~
/home/konstantin/twRepos/axon/cap-common/build/external/linux/x86/64/gcc/abi1011/include/google/protobuf/generated_message_util.h:105:40: error: expected primary-expression before ‘>’ token
           &reinterpret_cast<const TYPE*>(16)->FIELD) -               \
                                        ^
test.pb.cc:55:3: note: in expansion of macro ‘GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET’
   GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Shutdown, testfield_),
   ^
/home/konstantin/twRepos/axon/cap-common/build/external/linux/x86/64/gcc/abi1011/include/google/protobuf/generated_message_util.h:105:45: error: base operand of ‘->’ is not a pointer
           &reinterpret_cast<const TYPE*>(16)->FIELD) -               \
                                             ^
test.pb.cc:55:3: note: in expansion of macro ‘GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET’
   GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Shutdown, testfield_),
   ^
test.pb.cc:57:1: error: expected primary-expression before ‘}’ token
 };
 ^
test.pb.cc:57:1: error: expected ‘)’ before ‘}’ token
test.pb.cc:57:1: error: expected ‘)’ before ‘}’ token

**Comment by pherl** [comment]
This has been fixed internally. Unfortunately we would need for 3.5.0 to have it fixed.
