### ISSUE TITLE
json encoding in v3

### ISSUE THREAD

**Issue by ekg** [google/protobuf#350]
I see that [JSON encoding is in the works for protobuf v3](https://github.com/google/protobuf/releases). What is the timeline for this feature, and is there any simple way to help out? (I'm keen to help as I'm using and helping out with an independent json serializer for protobuf.)

**Comment by xfxyjwf** [comment]
(Assuming you are talking about C++) Currently we are doing the development in our internal code base so we can't accept external contributions. The plan is to have it open-sourced this quarter. Thanks for offering help though.

Java has a similar timeline to C++, whereas the initial release of objective-c and javanano will not have JSON support. For ruby, I think JSON is already supported.

**Comment by vanvlack** [comment]
@xfxyjwf wondering if your timelines on JSON encoding is still holding true?

**Comment by xfxyjwf** [comment]
@vanvlack, JSON support for C++ is added. See: https://github.com/google/protobuf/blob/master/src/google/protobuf/util/json_util.h
We may add some more convenient methods to make it easier to use.

For Java, I'm working on it right now and it should be ready soon.

**Comment by vanvlack** [comment]
> For Java, I'm working on it right now and it should be ready soon.

Great news @xfxyjwf. Is it possible to define `ready soon`? Like is that days, weeks, months?

**Comment by borud** [comment]
What solution do you recommend while we're waiting for JSON support in Java?   Preferably something that requires minimum of changes when the JSON support gets released.

**Comment by IceMan81** [comment]
@xfxyjwf Do you have a sense of when JSON support in Java might be available?

**Comment by xfxyjwf** [comment]
@IceMan81 check out this JsonFormat class:
https://github.com/google/protobuf/blob/beta-1/java/util/src/main/java/com/google/protobuf/util/JsonFormat.java

It's in the beta-1 branch. We will merge it back to master soon. A binary package "protobuf-java-util" is also available on maven now:
http://mvnrepository.com/artifact/com.google.protobuf/protobuf-java-util/3.0.0-beta-1

**Comment by borud** [comment]
Is this the solution that will be supported in the future or will protobuffer objects get something convenient like a .toJson() method? (And possibly a version of the method that takes a Writer or similar). 

I'd really like that convenience.

**Comment by xfxyjwf** [comment]
In C++ and Java, it will not be added to the message interface but will be kept as separate utility functions/classes. This is due to dependency restrictions in our internal code base (we cannot make the Message interface depend on the JSON util).

In other languages though, it might be possible to make it part of the message interface so you can call toJson on a proto object directly. It needs to be decided per language though.

**Comment by borud** [comment]
@xfxyjwf I'm going to ask a stupid question: what is the restriction?  License?  Not wanting to depend on some external library?

**Comment by xfxyjwf** [comment]
Re @borud , the restrictions are from how we manage the layout of our internal code bases. It's not related to license or external dependencies.
