### ISSUE TITLE
protobuf 3.4.0 gmock test failed

### ISSUE THREAD

**Issue by dawe2332** [google/protobuf#3501]
Hi, i've build a new release of libprotobuf (3.4.0) in visual studio 2013 as described in cmake/readme. I've build it as DLL (added cmake parameter and defined PROTOBUF_USE_DLL for compiler) 

But tests has failed.
Final out from tests: 

1>  [----------] Global test environment tear-down
1>  [==========] 1963 tests from 191 test cases ran. (58762 ms total)
1>  [  PASSED  ] 1957 tests.
1>  [  FAILED  ] 6 tests, listed below:
1>  [  FAILED  ] BootstrapTest.GeneratedDescriptorMatches
1>  [  FAILED  ] CsharpBootstrapTest.GeneratedCsharpDescriptorMatches
1>  [  FAILED  ] RubyGeneratorTest.GeneratorTest
1>  [  FAILED  ] TextFormatMapTest.Sorted
1>  [  FAILED  ] TextFormatTest.Basic
1>  [  FAILED  ] TextFormatExtensionsTest.Extensions
1>
1>   6 FAILED TESTS

Can you please check if everything is ok?  do i have bad configuration?

But i've told myself that it should be usable because i won't use those failed parts. But after compiling my project i've allways get same error:

error LNK2001: unresolved external symbol "class google::protobuf::internal::ExplicitlyConstructed<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > > google::protobuf::internal::fixed_address_empty_string" (?fixed_address_empty_string@internal@protobuf@google@@3V?$ExplicitlyConstructed@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@123@A)

error LNK2001: unresolved external symbol "bool google::protobuf::internal::proto3_preserve_unknown_" (?proto3_preserve_unknown_@internal@protobuf@google@@3_NA)

Any suggestions? Or it's really some bug?

**Comment by pherl** [comment]
It's probably due to the version mismatch. The libprotobuf, headers in the /include and protoc binary must all in v3.4.0. Can you double check that?

**Comment by dawe2332** [comment]
Actually, I can build it right now, the issue was that I've defined PROTOBUF_USE_DLL, not PROTOBUF_USE_DLLS (missing 's'). 

But what actually troubles me is that I can register libprotobuf with regsvr32.

**Comment by pherl** [comment]
what error messages did you get on regsvr32?
