### ISSUE TITLE
cross compile error: "internal compiler error: Segmentation fault" when excute make check

### ISSUE THREAD

**Issue by oucaijun** [google/protobuf#3505]
internal compiler error comes when cross compile probuf-3.3.0.

ocean@mhc:/home/ocean/armlibs$ git clone https://github.com/google/protobuf.git
ocean@mhc:/home/ocean/armlibs/protobuf# git checkout a6189ac
ocean@mhc:/home/ocean/armlibs/protobuf# git branch
	* (detached from a6189ac)
	
ocean@mhc:/home/ocean/armlibs/protobuf$ 	
	su
	. /opt/poky/1.7/environment-setup-cortexa9hf-vfp-neon-poky-linux-gnueabi 
	LC_ALL=C make clean
	LC_ALL=C ./autogen.sh 
	./configure --host=arm-poky-linux-gnueabi --with-protoc=/usr/local/bin/protoc  --prefix=/opt/poky/1.7/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/
	make -j8
	make check -j8 1> mkcklog 2>&1 
		
THEN we can see error in mkcklog:
mkcklog:
{
mv -f google/protobuf/stubs/.deps/protobuf_test-int128_unittest.Tpo google/protobuf/stubs/.deps/protobuf_test-int128_unittest.Po
arm-poky-linux-gnueabi-g++  -march=armv7-a -mthumb-interwork -mfloat-abi=hard -mfpu=neon -mtune=cortex-a9 --sysroot=/opt/poky/1.7/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi -std=c++11 -DHAVE_CONFIG_H -I. -I..  -I./../gmock/gtest/include -I./../gmock/include  -pthread -DHAVE_PTHREAD=1 -DHAVE_ZLIB=1 -Wall -Wno-sign-compare -O2 -pipe -g -feliminate-unused-debug-types -MT google/protobuf/protobuf_test-extension_set_unittest.o -MD -MP -MF google/protobuf/.deps/protobuf_test-extension_set_unittest.Tpo -c -o google/protobuf/protobuf_test-extension_set_unittest.o `test -f 'google/protobuf/extension_set_unittest.cc' || echo './'`google/protobuf/extension_set_unittest.cc
mv -f google/protobuf/stubs/.deps/protobuf_test-strutil_unittest.Tpo google/protobuf/stubs/.deps/protobuf_test-strutil_unittest.Po
arm-poky-linux-gnueabi-g++  -march=armv7-a -mthumb-interwork -mfloat-abi=hard -mfpu=neon -mtune=cortex-a9 --sysroot=/opt/poky/1.7/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi -std=c++11 -DHAVE_CONFIG_H -I. -I..  -I./../gmock/gtest/include -I./../gmock/include  -pthread -DHAVE_PTHREAD=1 -DHAVE_ZLIB=1 -Wall -Wno-sign-compare -O2 -pipe -g -feliminate-unused-debug-types -MT google/protobuf/protobuf_test-generated_message_reflection_unittest.o -MD -MP -MF google/protobuf/.deps/protobuf_test-generated_message_reflection_unittest.Tpo -c -o google/protobuf/protobuf_test-generated_message_reflection_unittest.o `test -f 'google/protobuf/generated_message_reflection_unittest.cc' || echo './'`google/protobuf/generated_message_reflection_unittest.cc
In file included from ./../gmock/gtest/include/gtest/gtest.h:1929:0,
                 from google/protobuf/dynamic_message_unittest.cc:58:
google/protobuf/dynamic_message_unittest.cc: In member function 'virtual void google::protobuf::DynamicMessageTest_Proto3_Test::TestBody()':
./../gmock/gtest/include/gtest/internal/gtest-internal.h:133:55: warning: converting 'false' to pointer type for argument 1 of 'char testing::internal::IsNullLiteralHelper(testing::internal::Secret*)' [-Wconversion-null]
     (sizeof(::testing::internal::IsNullLiteralHelper(x)) == 1)
                                                       ^
./../gmock/gtest/include/gtest/gtest_pred_impl.h:77:52: note: in definition of macro 'GTEST_ASSERT_'
   if (const ::testing::AssertionResult gtest_ar = (expression)) \
                                                    ^
./../gmock/gtest/include/gtest/gtest_pred_impl.h:162:3: note: in expansion of macro 'GTEST_PRED_FORMAT2_'
   GTEST_PRED_FORMAT2_(pred_format, v1, v2, GTEST_NONFATAL_FAILURE_)
   ^
./../gmock/gtest/include/gtest/gtest.h:1978:3: note: in expansion of macro 'EXPECT_PRED_FORMAT2'
   EXPECT_PRED_FORMAT2(::testing::internal:: \
   ^
./../gmock/gtest/include/gtest/gtest.h:1979:32: note: in expansion of macro 'GTEST_IS_NULL_LITERAL_'
                       EqHelper<GTEST_IS_NULL_LITERAL_(expected)>::Compare, \
                                ^
google/protobuf/dynamic_message_unittest.cc:271:3: note: in expansion of macro 'EXPECT_EQ'
   EXPECT_EQ(false, refl->HasField(*message, optional_int32));
   ^
./../gmock/gtest/include/gtest/internal/gtest-internal.h:133:55: warning: converting 'false' to pointer type for argument 1 of 'char testing::internal::IsNullLiteralHelper(testing::internal::Secret*)' [-Wconversion-null]
     (sizeof(::testing::internal::IsNullLiteralHelper(x)) == 1)
                                                       ^
./../gmock/gtest/include/gtest/gtest_pred_impl.h:77:52: note: in definition of macro 'GTEST_ASSERT_'
   if (const ::testing::AssertionResult gtest_ar = (expression)) \
                                                    ^
./../gmock/gtest/include/gtest/gtest_pred_impl.h:162:3: note: in expansion of macro 'GTEST_PRED_FORMAT2_'
   GTEST_PRED_FORMAT2_(pred_format, v1, v2, GTEST_NONFATAL_FAILURE_)
   ^
./../gmock/gtest/include/gtest/gtest.h:1978:3: note: in expansion of macro 'EXPECT_PRED_FORMAT2'
   EXPECT_PRED_FORMAT2(::testing::internal:: \
   ^
./../gmock/gtest/include/gtest/gtest.h:1979:32: note: in expansion of macro 'GTEST_IS_NULL_LITERAL_'
                       EqHelper<GTEST_IS_NULL_LITERAL_(expected)>::Compare, \
                                ^
google/protobuf/dynamic_message_unittest.cc:275:3: note: in expansion of macro 'EXPECT_EQ'
   EXPECT_EQ(false, refl->HasField(*message, optional_int32));
   ^
./../gmock/gtest/include/gtest/internal/gtest-internal.h:133:55: warning: converting 'false' to pointer type for argument 1 of 'char testing::internal::IsNullLiteralHelper(testing::internal::Secret*)' [-Wconversion-null]
     (sizeof(::testing::internal::IsNullLiteralHelper(x)) == 1)
                                                       ^
./../gmock/gtest/include/gtest/gtest_pred_impl.h:77:52: note: in definition of macro 'GTEST_ASSERT_'
   if (const ::testing::AssertionResult gtest_ar = (expression)) \
                                                    ^
./../gmock/gtest/include/gtest/gtest_pred_impl.h:162:3: note: in expansion of macro 'GTEST_PRED_FORMAT2_'
   GTEST_PRED_FORMAT2_(pred_format, v1, v2, GTEST_NONFATAL_FAILURE_)
   ^
./../gmock/gtest/include/gtest/gtest.h:1978:3: note: in expansion of macro 'EXPECT_PRED_FORMAT2'
   EXPECT_PRED_FORMAT2(::testing::internal:: \
   ^
./../gmock/gtest/include/gtest/gtest.h:1979:32: note: in expansion of macro 'GTEST_IS_NULL_LITERAL_'
                       EqHelper<GTEST_IS_NULL_LITERAL_(expected)>::Compare, \
                                ^
google/protobuf/dynamic_message_unittest.cc:277:3: note: in expansion of macro 'EXPECT_EQ'
   EXPECT_EQ(false, refl->HasField(*message, optional_msg));
   ^
./../gmock/gtest/include/gtest/internal/gtest-internal.h:133:55: warning: converting 'false' to pointer type for argument 1 of 'char testing::internal::IsNullLiteralHelper(testing::internal::Secret*)' [-Wconversion-null]
     (sizeof(::testing::internal::IsNullLiteralHelper(x)) == 1)
                                                       ^
./../gmock/gtest/include/gtest/gtest_pred_impl.h:77:52: note: in definition of macro 'GTEST_ASSERT_'
   if (const ::testing::AssertionResult gtest_ar = (expression)) \
                                                    ^
./../gmock/gtest/include/gtest/gtest_pred_impl.h:162:3: note: in expansion of macro 'GTEST_PRED_FORMAT2_'
   GTEST_PRED_FORMAT2_(pred_format, v1, v2, GTEST_NONFATAL_FAILURE_)
   ^
./../gmock/gtest/include/gtest/gtest.h:1978:3: note: in expansion of macro 'EXPECT_PRED_FORMAT2'
   EXPECT_PRED_FORMAT2(::testing::internal:: \
   ^
./../gmock/gtest/include/gtest/gtest.h:1979:32: note: in expansion of macro 'GTEST_IS_NULL_LITERAL_'
                       EqHelper<GTEST_IS_NULL_LITERAL_(expected)>::Compare, \
                                ^
google/protobuf/dynamic_message_unittest.cc:281:3: note: in expansion of macro 'EXPECT_EQ'
   EXPECT_EQ(false, refl->HasField(*message, optional_msg));
   ^
./../gmock/gtest/include/gtest/internal/gtest-internal.h:133:55: warning: converting 'false' to pointer type for argument 1 of 'char testing::internal::IsNullLiteralHelper(testing::internal::Secret*)' [-Wconversion-null]
     (sizeof(::testing::internal::IsNullLiteralHelper(x)) == 1)
                                                       ^
./../gmock/gtest/include/gtest/gtest_pred_impl.h:77:52: note: in definition of macro 'GTEST_ASSERT_'
   if (const ::testing::AssertionResult gtest_ar = (expression)) \
                                                    ^
./../gmock/gtest/include/gtest/gtest_pred_impl.h:162:3: note: in expansion of macro 'GTEST_PRED_FORMAT2_'
   GTEST_PRED_FORMAT2_(pred_format, v1, v2, GTEST_NONFATAL_FAILURE_)
   ^
./../gmock/gtest/include/gtest/gtest.h:1978:3: note: in expansion of macro 'EXPECT_PRED_FORMAT2'
   EXPECT_PRED_FORMAT2(::testing::internal:: \
   ^
./../gmock/gtest/include/gtest/gtest.h:1979:32: note: in expansion of macro 'GTEST_IS_NULL_LITERAL_'
                       EqHelper<GTEST_IS_NULL_LITERAL_(expected)>::Compare, \
                                ^
google/protobuf/dynamic_message_unittest.cc:284:3: note: in expansion of macro 'EXPECT_EQ'
   EXPECT_EQ(false, refl->HasField(*proto3_prototype_, optional_msg));
   ^
mv -f google/protobuf/.deps/protobuf_test-drop_unknown_fields_test.Tpo google/protobuf/.deps/protobuf_test-drop_unknown_fields_test.Po
arm-poky-linux-gnueabi-g++  -march=armv7-a -mthumb-interwork -mfloat-abi=hard -mfpu=neon -mtune=cortex-a9 --sysroot=/opt/poky/1.7/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi -std=c++11 -DHAVE_CONFIG_H -I. -I..  -I./../gmock/gtest/include -I./../gmock/include  -pthread -DHAVE_PTHREAD=1 -DHAVE_ZLIB=1 -Wall -Wno-sign-compare -O2 -pipe -g -feliminate-unused-debug-types -MT google/protobuf/protobuf_test-map_field_test.o -MD -MP -MF google/protobuf/.deps/protobuf_test-map_field_test.Tpo -c -o google/protobuf/protobuf_test-map_field_test.o `test -f 'google/protobuf/map_field_test.cc' || echo './'`google/protobuf/map_field_test.cc
In file included from ./../gmock/gtest/include/gtest/gtest.h:1929:0,
                 from google/protobuf/descriptor_unittest.cc:63:
google/protobuf/descriptor_unittest.cc: In member function 'virtual void google::protobuf::descriptor_unittest::CustomOptions_OptionTypes_Test::TestBody()':
./../gmock/gtest/include/gtest/internal/gtest-internal.h:133:55: warning: converting 'false' to pointer type for argument 1 of 'char testing::internal::IsNullLiteralHelper(testing::internal::Secret*)' [-Wconversion-null]
     (sizeof(::testing::internal::IsNullLiteralHelper(x)) == 1)
                                                       ^
./../gmock/gtest/include/gtest/gtest_pred_impl.h:77:52: note: in definition of macro 'GTEST_ASSERT_'
   if (const ::testing::AssertionResult gtest_ar = (expression)) \
                                                    ^
./../gmock/gtest/include/gtest/gtest_pred_impl.h:162:3: note: in expansion of macro 'GTEST_PRED_FORMAT2_'
   GTEST_PRED_FORMAT2_(pred_format, v1, v2, GTEST_NONFATAL_FAILURE_)
   ^
./../gmock/gtest/include/gtest/gtest.h:1978:3: note: in expansion of macro 'EXPECT_PRED_FORMAT2'
   EXPECT_PRED_FORMAT2(::testing::internal:: \
   ^
./../gmock/gtest/include/gtest/gtest.h:1979:32: note: in expansion of macro 'GTEST_IS_NULL_LITERAL_'
                       EqHelper<GTEST_IS_NULL_LITERAL_(expected)>::Compare, \
                                ^
google/protobuf/descriptor_unittest.cc:2817:3: note: in expansion of macro 'EXPECT_EQ'
   EXPECT_EQ(false    , options->GetExtension(protobuf_unittest::bool_opt));
   ^
mv -f google/protobuf/.deps/protobuf_test-dynamic_message_unittest.Tpo google/protobuf/.deps/protobuf_test-dynamic_message_unittest.Po
arm-poky-linux-gnueabi-g++  -march=armv7-a -mthumb-interwork -mfloat-abi=hard -mfpu=neon -mtune=cortex-a9 --sysroot=/opt/poky/1.7/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi -std=c++11 -DHAVE_CONFIG_H -I. -I..  -I./../gmock/gtest/include -I./../gmock/include  -pthread -DHAVE_PTHREAD=1 -DHAVE_ZLIB=1 -Wall -Wno-sign-compare -O2 -pipe -g -feliminate-unused-debug-types -MT google/protobuf/protobuf_test-map_test.o -MD -MP -MF google/protobuf/.deps/protobuf_test-map_test.Tpo -c -o google/protobuf/protobuf_test-map_test.o `test -f 'google/protobuf/map_test.cc' || echo './'`google/protobuf/map_test.cc
mv -f google/protobuf/.deps/protobuf_test-descriptor_database_unittest.Tpo google/protobuf/.deps/protobuf_test-descriptor_database_unittest.Po
arm-poky-linux-gnueabi-g++  -march=armv7-a -mthumb-interwork -mfloat-abi=hard -mfpu=neon -mtune=cortex-a9 --sysroot=/opt/poky/1.7/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi -std=c++11 -DHAVE_CONFIG_H -I. -I..  -I./../gmock/gtest/include -I./../gmock/include  -pthread -DHAVE_PTHREAD=1 -DHAVE_ZLIB=1 -Wall -Wno-sign-compare -O2 -pipe -g -feliminate-unused-debug-types -MT google/protobuf/protobuf_test-message_unittest.o -MD -MP -MF google/protobuf/.deps/protobuf_test-message_unittest.Tpo -c -o google/protobuf/protobuf_test-message_unittest.o `test -f 'google/protobuf/message_unittest.cc' || echo './'`google/protobuf/message_unittest.cc
google/protobuf/map_field_test.cc: In member function 'void google::protobuf::internal::MapField<Derived, Key, T, key_wire_type, value_wire_type, default_enum_value>::SyncRepeatedFieldWithMapNoLock() const [with Derived = protobuf_unittest::TestMap::TestMap_MapInt32Int32Entry; Key = int; T = int; google::protobuf::internal::WireFormatLite::FieldType kKeyFieldType = (google::protobuf::internal::WireFormatLite::FieldType)5u; google::protobuf::internal::WireFormatLite::FieldType kValueFieldType = (google::protobuf::internal::WireFormatLite::FieldType)5u; int default_enum_value = 0]':
google/protobuf/map_field_test.cc:485:1: internal compiler error: Segmentation fault
 }  // namespace google
 ^
Please submit a full bug report,
with preprocessed source if appropriate.
See <http://gcc.gnu.org/bugs.html> for instructions.
make[3]: *** [google/protobuf/protobuf_test-map_field_test.o] Error 1
make[3]: *** Waiting for unfinished jobs....
mv -f google/protobuf/.deps/protobuf_test-generated_message_reflection_unittest.Tpo google/protobuf/.deps/protobuf_test-generated_message_reflection_unittest.Po
mv -f google/protobuf/.deps/protobuf_test-arena_unittest.Tpo google/protobuf/.deps/protobuf_test-arena_unittest.Po
mv -f google/protobuf/.deps/protobuf_test-message_unittest.Tpo google/protobuf/.deps/protobuf_test-message_unittest.Po
mv -f google/protobuf/.deps/protobuf_test-extension_set_unittest.Tpo google/protobuf/.deps/protobuf_test-extension_set_unittest.Po
mv -f google/protobuf/stubs/.deps/protobuf_test-stringpiece_unittest.Tpo google/protobuf/stubs/.deps/protobuf_test-stringpiece_unittest.Po
mv -f google/protobuf/.deps/protobuf_test-map_test.Tpo google/protobuf/.deps/protobuf_test-map_test.Po
mv -f google/protobuf/.deps/protobuf_test-descriptor_unittest.Tpo google/protobuf/.deps/protobuf_test-descriptor_unittest.Po
make[3]: Leaving directory `/home/ocean/armlibs/protobuf/src'
make[2]: *** [check-am] Error 2
make[2]: Leaving directory `/home/ocean/armlibs/protobuf/src'
make[1]: *** [check] Error 2
make[1]: Leaving directory `/home/ocean/armlibs/protobuf/src'
make: *** [check-recursive] Error 1
}

BELOW are some information about the building environment .
THE environment after . /opt/poky/1.7/environment-setup-cortexa9hf-vfp-neon-poky-linux-gnueabi  
{
	declare -x AR="arm-poky-linux-gnueabi-ar"
	declare -x ARCH="arm"
	declare -x AS="arm-poky-linux-gnueabi-as "
	declare -x CC="arm-poky-linux-gnueabi-gcc  -march=armv7-a -mthumb-interwork -mfloat-abi=hard -mfpu=neon -mtune=cortex-a9 --sysroot=/opt/poky/1.7/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi"
	declare -x CFLAGS=" -O2 -pipe -g -feliminate-unused-debug-types"
	declare -x CONFIGURE_FLAGS="--target=arm-poky-linux-gnueabi --host=arm-poky-linux-gnueabi --build=x86_64-linux --with-libtool-sysroot=/opt/poky/1.7/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi"
	declare -x CONFIG_SITE="/opt/poky/1.7/site-config-cortexa9hf-vfp-neon-poky-linux-gnueabi"
	declare -x CPP="arm-poky-linux-gnueabi-gcc -E  -march=armv7-a -mthumb-interwork -mfloat-abi=hard -mfpu=neon -mtune=cortex-a9 --sysroot=/opt/poky/1.7/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi"
	declare -x CPPFLAGS=""
	declare -x CROSS_COMPILE="arm-poky-linux-gnueabi-"
	declare -x CXX="arm-poky-linux-gnueabi-g++  -march=armv7-a -mthumb-interwork -mfloat-abi=hard -mfpu=neon -mtune=cortex-a9 --sysroot=/opt/poky/1.7/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi"
	declare -x CXXFLAGS=" -O2 -pipe -g -feliminate-unused-debug-types"
	declare -x GDB="arm-poky-linux-gnueabi-gdb"
	declare -x HOME="/root"
	declare -x KCFLAGS="--sysroot=/opt/poky/1.7/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi"
	declare -x LANG="en_US.UTF-8"
	declare -x LC_ADDRESS="zh_CN.UTF-8"
	declare -x LC_IDENTIFICATION="zh_CN.UTF-8"
	declare -x LC_MEASUREMENT="zh_CN.UTF-8"
	declare -x LC_MONETARY="zh_CN.UTF-8"
	declare -x LC_NAME="zh_CN.UTF-8"
	declare -x LC_NUMERIC="zh_CN.UTF-8"
	declare -x LC_PAPER="zh_CN.UTF-8"
	declare -x LC_TELEPHONE="zh_CN.UTF-8"
	declare -x LC_TIME="zh_CN.UTF-8"
	declare -x LD="arm-poky-linux-gnueabi-ld  --sysroot=/opt/poky/1.7/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi"
	declare -x LDFLAGS="-Wl,-O1 -Wl,--hash-style=gnu -Wl,--as-needed"
	declare -x LESSCLOSE="/usr/bin/lesspipe %s %s"
	declare -x LESSOPEN="| /usr/bin/lesspipe %s"
	declare -x LOGNAME="root"
	declare -x M4="m4"
	declare -x NM="arm-poky-linux-gnueabi-nm"
	declare -x OBJCOPY="arm-poky-linux-gnueabi-objcopy"
	declare -x OBJDUMP="arm-poky-linux-gnueabi-objdump"
	declare -x OECORE_ACLOCAL_OPTS="-I /opt/poky/1.7/sysroots/x86_64-pokysdk-linux/usr/share/aclocal"
	declare -x OECORE_DISTRO_VERSION="1.7"
	declare -x OECORE_NATIVE_SYSROOT="/opt/poky/1.7/sysroots/x86_64-pokysdk-linux"
	declare -x OECORE_SDK_VERSION="1.7"
	declare -x OECORE_TARGET_SYSROOT="/opt/poky/1.7/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi"
	declare -x OE_QMAKE_AR="arm-poky-linux-gnueabi-ar"
	declare -x OE_QMAKE_CC="arm-poky-linux-gnueabi-gcc  -march=armv7-a -mthumb-interwork -mfloat-abi=hard -mfpu=neon -mtune=cortex-a9 --sysroot=/opt/poky/1.7/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi"
	declare -x OE_QMAKE_CFLAGS=" -O2 -pipe -g -feliminate-unused-debug-types"
	declare -x OE_QMAKE_CXX="arm-poky-linux-gnueabi-g++  -march=armv7-a -mthumb-interwork -mfloat-abi=hard -mfpu=neon -mtune=cortex-a9 --sysroot=/opt/poky/1.7/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi"
	declare -x OE_QMAKE_CXXFLAGS=" -O2 -pipe -g -feliminate-unused-debug-types"
	declare -x OE_QMAKE_INCDIR_QT="/opt/poky/1.7/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/include/qt5"
	declare -x OE_QMAKE_LDFLAGS="-Wl,-O1 -Wl,--hash-style=gnu -Wl,--as-needed"
	declare -x OE_QMAKE_LIBDIR_QT="/opt/poky/1.7/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib"
	declare -x OE_QMAKE_LINK="arm-poky-linux-gnueabi-g++  -march=armv7-a -mthumb-interwork -mfloat-abi=hard -mfpu=neon -mtune=cortex-a9 --sysroot=/opt/poky/1.7/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi"
	declare -x OE_QMAKE_MOC="/opt/poky/1.7/sysroots/x86_64-pokysdk-linux/usr/bin/qt5/moc"
	declare -x OE_QMAKE_PATH_HOST_BINS="/opt/poky/1.7/sysroots/x86_64-pokysdk-linux/usr/bin/qt5"
	declare -x OE_QMAKE_QDBUSCPP2XML="/opt/poky/1.7/sysroots/x86_64-pokysdk-linux/usr/bin/qt5/qdbuscpp2xml"
	declare -x OE_QMAKE_QDBUSXML2CPP="/opt/poky/1.7/sysroots/x86_64-pokysdk-linux/usr/bin/qt5/qdbusxml2cpp"
	declare -x OE_QMAKE_QT_CONFIG="/opt/poky/1.7/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/qconfig.pri"
	declare -x OE_QMAKE_RCC="/opt/poky/1.7/sysroots/x86_64-pokysdk-linux/usr/bin/qt5/rcc"
	declare -x OE_QMAKE_UIC="/opt/poky/1.7/sysroots/x86_64-pokysdk-linux/usr/bin/qt5/uic"
	declare -x OLDPWD="/home/ocean/armlibs/grpc-1.4.5/grpc/third_party/protobuf"
	declare -x PATH="/opt/poky/1.7/sysroots/x86_64-pokysdk-linux/usr/bin/qt5:/opt/poky/1.7/sysroots/x86_64-pokysdk-linux/usr/bin:/opt/poky/1.7/sysroots/x86_64-pokysdk-linux/usr/bin/arm-poky-linux-gnueabi:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games"
	declare -x PKG_CONFIG_PATH="/opt/poky/1.7/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/pkgconfig"
	declare -x PKG_CONFIG_SYSROOT_DIR="/opt/poky/1.7/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi"
	declare -x PWD="/home/ocean/armlibs/protobuf"
	declare -x PYTHONHOME="/opt/poky/1.7/sysroots/x86_64-pokysdk-linux/usr"
	declare -x QMAKESPEC="/opt/poky/1.7/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/linux-oe-g++"
	declare -x QT_CONF_PATH="/opt/poky/1.7/sysroots/x86_64-pokysdk-linux/usr/bin/qt5/qt.conf"
	declare -x QT_QPA_PLATFORMTHEME="appmenu-qt5"
	declare -x RANLIB="arm-poky-linux-gnueabi-ranlib"
	declare -x SDKTARGETSYSROOT="/opt/poky/1.7/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi"
	declare -x SHELL="/bin/bash"
	declare -x SHLVL="2"
	declare -x STRIP="arm-poky-linux-gnueabi-strip"
	declare -x TARGET_PREFIX="arm-poky-linux-gnueabi-"
	declare -x TERM="linux"
	declare -x USER="root"
	declare -x XDG_RUNTIME_DIR="/run/user/1000"
	declare -x XDG_SESSION_ID="3"

}	

root@mhc:/home/ocean/armlibs/protobuf# python --version
Python 2.7.3

root@mhc:/home/ocean/armlibs/protobuf# cat /etc/issue 
Ubuntu 14.04.5 LTS 

root@mhc:/home/ocean/armlibs/protobuf# arm-poky-linux-gnueabi-gcc -v
{
Using built-in specs.
COLLECT_GCC=arm-poky-linux-gnueabi-gcc
COLLECT_LTO_WRAPPER=/opt/poky/1.7/sysroots/x86_64-pokysdk-linux/usr/libexec/arm-poky-linux-gnueabi/gcc/arm-poky-linux-gnueabi/4.9.1/lto-wrapper
Target: arm-poky-linux-gnueabi
Configured with: /home/ocean/fsl-release-bsp/build-x11/tmp/work-shared/gcc-4.9.1-r0/gcc-4.9.1/configure --build=x86_64-linux --host=x86_64-pokysdk-linux --target=arm-poky-linux-gnueabi --prefix=/opt/poky/1.7/sysroots/x86_64-pokysdk-linux/usr --exec_prefix=/opt/poky/1.7/sysroots/x86_64-pokysdk-linux/usr --bindir=/opt/poky/1.7/sysroots/x86_64-pokysdk-linux/usr/bin/arm-poky-linux-gnueabi --sbindir=/opt/poky/1.7/sysroots/x86_64-pokysdk-linux/usr/bin/arm-poky-linux-gnueabi --libexecdir=/opt/poky/1.7/sysroots/x86_64-pokysdk-linux/usr/libexec/arm-poky-linux-gnueabi --datadir=/opt/poky/1.7/sysroots/x86_64-pokysdk-linux/usr/share --sysconfdir=/opt/poky/1.7/sysroots/x86_64-pokysdk-linux/etc --sharedstatedir=/opt/poky/1.7/sysroots/x86_64-pokysdk-linux/com --localstatedir=/opt/poky/1.7/sysroots/x86_64-pokysdk-linux/var --libdir=/opt/poky/1.7/sysroots/x86_64-pokysdk-linux/usr/lib/arm-poky-linux-gnueabi --includedir=/opt/poky/1.7/sysroots/x86_64-pokysdk-linux/usr/include --oldincludedir=/opt/poky/1.7/sysroots/x86_64-pokysdk-linux/usr/include --infodir=/opt/poky/1.7/sysroots/x86_64-pokysdk-linux/usr/share/info --mandir=/opt/poky/1.7/sysroots/x86_64-pokysdk-linux/usr/share/man --disable-silent-rules --disable-dependency-tracking --with-libtool-sysroot=/home/ocean/fsl-release-bsp/build-x11/tmp/sysroots/x86_64-nativesdk-pokysdk-linux --with-gnu-ld --enable-shared --enable-languages=c,c++ --enable-threads=posix --enable-multilib --enable-c99 --enable-long-long --enable-symvers=gnu --enable-libstdcxx-pch --program-prefix=arm-poky-linux-gnueabi- --without-local-prefix --enable-target-optspace --enable-lto --enable-libssp --disable-bootstrap --disable-libmudflap --with-system-zlib --with-linker-hash-style=gnu --enable-linker-build-id --with-ppl=no --with-cloog=no --enable-checking=release --enable-cheaders=c_global --with-gxx-include-dir=/opt/poky/1.7/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/include/c++/4.9.1 --with-build-time-tools=/home/ocean/fsl-release-bsp/build-x11/tmp/sysroots/x86_64-linux/usr/arm-poky-linux-gnueabi/bin --with-sysroot=/opt/poky/1.7/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi --with-build-sysroot=/home/ocean/fsl-release-bsp/build-x11/tmp/sysroots/imx6qsabresd --enable-poison-system-directories --with-mpfr=/home/ocean/fsl-release-bsp/build-x11/tmp/sysroots/x86_64-nativesdk-pokysdk-linux --with-mpc=/home/ocean/fsl-release-bsp/build-x11/tmp/sysroots/x86_64-nativesdk-pokysdk-linux --enable-nls --with-arch=armv7-a
Thread model: posix
gcc version 4.9.1 (GCC) 
}

WHERE the cross tools come from:
{
 cd $HOME/
~/bin/repo init -u git://git.freescale.com/imx/fsl-arm-yocto-bsp.git -b imx-3.14.28-1.0.0_ga
cd $HOME/fsl-release-bsp 
source setup-environment
MACHINE=imx6qsabresd source fsl-setup-release.sh -b build-x11 -e x11
bitbake meta-toolchain-qt5
sh  $HOME/fsl-release-bsp/build-x11/tmp/deploy/sdk/poky-glibc-x86_64-meta-toolchain-qt5-cortexa9hf-vfp-neon-toolchain-1.7.sh 

}

**Comment by pherl** [comment]
It looks like the compiler segfault and failed to compile the map test file. I would file a bug to gcc. Could you try if you can cross compile using other compilers?
