### ISSUE TITLE
Can only generate PHP code for proto3 .proto while importing proto2

### ISSUE THREAD

**Issue by yaronsumel** [google/protobuf#3513]
While compiling my .proto (proto3) that making use of protobuf/gogoproto/gogo.proto (proto2)
im getting - `-php_out: gogoproto/gogo.proto: Can only generate PHP code for proto3 .proto files.` any workaround solving this ?

**Comment by TeBoring** [comment]
Currently, we don't support proto2. proto2 support is a future plan.

**Comment by yaronsumel** [comment]
any simple way for skipping it ?

**Comment by awalterschulze** [comment]
Since the proto2 file is not actually being used for generation, can it be skipped?
For example, what do you do when someone imports the descriptor.proto which is proto2 as well.

**Comment by xfxyjwf** [comment]
@awalterschulze It's probably simpler if you just change gogo.proto to proto3 syntax?

**Comment by xfxyjwf** [comment]
descriptor.proto is special-cased in protocol compiler and such special-cases are not pretty...

**Comment by awalterschulze** [comment]
Gogo.proto uses extensions on descriptor.proto. I don't think I can make it
proto3, since it doesn't support extensions 🙁

**Comment by xfxyjwf** [comment]
Proto3 doesn't support regular extensions but extensions to the XXXOptions messages in descriptor.proto are explicitly allowed.

**Comment by awalterschulze** [comment]
Very interesting. That might help, but If I upgrade gogo.proto to proto3,
won't I loose backwards compatibility with people still using protoc 2.5?

**Comment by yaronsumel** [comment]
so the workaround in this case is just to stripe gogo from the proto
```bash
grep -vw 'import "github.com/gogo/protobuf/gogoproto/gogo.proto";' payment/paymentpb/payment.proto | sed -e 's/\[[^][]*\]//g' > payment/paymentpb/paymentpb.proto
```

**Comment by yufeixuan** [comment]
Hope PHP supports proto2

**Comment by awalterschulze** [comment]
Yes at least in a limited way that supports descriptor extensions.

**Comment by TeBoring** [comment]
Duplicates of #3623
