### ISSUE TITLE
Protobuf failed to build from master branch revision ba4e547

### ISSUE THREAD

**Issue by KarenHuang2016** [google/protobuf#3541]
We tried to build protobuf on Windows with VS2017 Update 2. It failed with many error. It starts failing from master branch revision ba4e547. Could you please take a look at this? Thanks in advance!

**Repro steps:**
1. git clone  https://github.com/google/protobuf.git D:\Google-Protobuf\src
2. Put the gmock source code under D:\Google-Protobuf\src\gmock
3. Open a VS 2017 x86 command prompt and browse to D:\Google-Protobuf
4. mkdir build_x86_ltcg && pushd build_x86_ltcg
5. cmake -G "Visual Studio 15" -DCMAKE_SYSTEM_VERSION=10.0.15063.0 -DCMAKE_EXE_LINKER_FLAGS="/LTCG" -DCMAKE_C_FLAGS="/GL" -DCMAKE_CXX_FLAGS="/GL" ..\src\cmake 
6. msbuild /p:Configuration=Release;Platform=Win32 \protobuf.sln /t:Rebuild 

**Actual result:**
Many errors are reported from objectivec_helpers_unittest.cc and message_unittest.cc. Please see details from attached log file.
[protobuf_x86_ltcg_build.txt](https://github.com/google/protobuf/files/1241610/protobuf_x86_ltcg_build.txt)

D:\Google-Protobuf\src\src\google\protobuf\compiler\objectivec\objectivec_helpers_unittest.cc(119): error C2039: 'KilledBySignal': is not a member of 'testing' [D:\Google-Protobuf\build_x86_ltcg\tests.vcxproj]
  D:\Google-Protobuf\src\src\google\protobuf\compiler\objectivec\objectivec_helpers_unittest.cc(119): error C2065: 'SIGABRT': undeclared identifier [D:\Google-Protobuf\build_x86_ltcg\tests.vcxproj]
  D:\Google-Protobuf\src\src\google\protobuf\compiler\objectivec\objectivec_helpers_unittest.cc(119): error C3861: 'KilledBySignal': identifier not found [D:\Google-Protobuf\build_x86_ltcg\tests.vcxproj]
  D:\Google-Protobuf\src\src\google\protobuf\compiler\objectivec\objectivec_helpers_unittest.cc(122): error C2039: 'KilledBySignal': is not a member of 'testing' [D:\Google-Protobuf\build_x86_ltcg\tests.vcxproj]
  D:\Google-Protobuf\src\src\google\protobuf\compiler\objectivec\objectivec_helpers_unittest.cc(122): error C2065: 'SIGABRT': undeclared identifier [D:\Google-Protobuf\build_x86_ltcg\tests.vcxproj]
  D:\Google-Protobuf\src\src\google\protobuf\compiler\objectivec\objectivec_helpers_unittest.cc(122): error C3861: 'KilledBySignal': identifier not found [D:\Google-Protobuf\build_x86_ltcg\tests.vcxproj]
 D:\Google-Protobuf\src\src\google\protobuf\message_unittest.cc(265): error C2065: 'Cord': undeclared identifier [D:\Google-Protobuf\build_x86_ltcg\tests.vcxproj]
  D:\Google-Protobuf\src\src\google\protobuf\message_unittest.cc(265): error C2146: syntax error: missing ';' before identifier 'one_megabyte' [D:\Google-Protobuf\build_x86_ltcg\tests.vcxproj]
  D:\Google-Protobuf\src\src\google\protobuf\message_unittest.cc(265): error C2065: 'one_megabyte': undeclared identifier [D:\Google-Protobuf\build_x86_ltcg\tests.vcxproj]
  D:\Google-Protobuf\src\src\google\protobuf\message_unittest.cc(267): error C2065: 'one_megabyte': undeclared identifier [D:\Google-Protobuf\build_x86_ltcg\tests.vcxproj]
  D:\Google-Protobuf\src\src\google\protobuf\message_unittest.cc(267): error C2228: left of '.Append' must have class/struct/union [D:\Google-Protobuf\build_x86_ltcg\tests.vcxproj]
  D:\Google-Protobuf\src\src\google\protobuf\message_unittest.cc(271): error C2248: 'protobuf_unittest::TestAllTypes::add_repeated_cord': cannot access private member declared in class 'protobuf_unittest::TestAllTypes' [D:\Google-Protobuf\build_x86_ltcg\tests.vcxproj]

**Comment by pherl** [comment]
Thanks for reporting. I will send out a fix soon.

**Comment by pherl** [comment]
#3546

**Comment by pherl** [comment]
Could you help verify if this has been fixed in the 3.4.x release branch?

**Comment by KarenHuang2016** [comment]
@pherl, thank you so much for fixing this issue! I've verified your fix works well. BTW, can I know when this fix will be merged to master branch?

**Comment by KarenHuang2016** [comment]
@pherl, It seems the fix has been merged to master branch. Thanks for your fix! Close this issue.
