### ISSUE TITLE
PHP protobuf generation and reserved keywords

### ISSUE THREAD

**Issue by michaelbausor** [google/protobuf#3545]
There are some keywords that are not correctly handled in protobuf generation:
- `DEFAULT` - see here: https://github.com/googleapis/gax-php/blob/master/src/generated/Google/Logging/Type/LogSeverity.php#L30
- `Namespace` - we have an upcoming API that has a protobuf message type called `Namespace`

In the first case, we have resolved the issue with a manual edit. In the second case, it is not possible to rename the class with a manual edit.

It would perhaps be appropriate to also attempt to determine all possible PHP keywords, and handle them correctly, rather than only addressing these cases. I can put together a test protobuf file that uses all of the keywords that require special case handling.

**Comment by TeBoring** [comment]
Do you have a list of reserved keywords. I want to add them all at once.

**Comment by michaelbausor** [comment]
I will create a list, and also an example proto file that uses them that we can put into tests

**Comment by michaelbausor** [comment]
Here is a proto file that contains keywords: https://gist.github.com/michaelbausor/d38e76da78a0c6206ec31b5a09689816

The keywords were compiled from here: http://php.net/manual/en/reserved.php

I would recommend adding a test which runs the proto compiler on this proto file, and then parses and instantiates all of the classes generated using a test like this one: https://github.com/googleapis/proto-client-php/blob/master/tests/Unit/InstantiateClassesTest.php
(Note that this test also needs to handle the generated grpc stub classes, so it can be simplified for the protobuf-only case)
