### ISSUE TITLE
Can I prevent the field from being automatically converted to lowercase?

### ISSUE THREAD

**Issue by Dec-F** [google/protobuf#3549]
I have a problem, using toObject () parsed into js object will lose the original hump writing, what method can be resolved?
- my `.proto`
![image](https://user-images.githubusercontent.com/20250430/29594915-d71a25c8-87e6-11e7-95a9-1a5e9e90f747.png)

- The object of analysis is
![image](https://user-images.githubusercontent.com/20250430/29594966-17346e02-87e7-11e7-8743-e6a4e6de2719.png)

- I expect the result is  `liveData`

what should I do？

thanks

**Comment by pherl** [comment]
Duplicated of https://github.com/google/protobuf/issues/2522

Unfortunately the toObject() API is not meant to be used to generate JSON format. For historical reasons it's used internally that it is hard to change now.

**Comment by pherl** [comment]
Unfortunately the toObject() API is not meant to be used to generate JSON format. For historical reasons it's used internally that it is hard to change now.
