### ISSUE TITLE
mvn package failed when building protobuf-java-3.4.0.zip

### ISSUE THREAD

**Issue by sagaxu** [google/protobuf#3552]
`main:
    [mkdir] Created dir: /home/saga/Downloads/protobuf-3.4.0/java/core/target/generated-test-sources
     [exec] /home/saga/Downloads/protobuf-3.4.0/java/core/../../src/google/protobuf/unittest_proto3.proto: No such file or directory
     [exec] Result: 1
`

After I manually downloaded unittest_proto3.proto from github, it works.

**Comment by pherl** [comment]
Confirmed. looks like csharp package is also broken. Working on a fix.

**Comment by pherl** [comment]
Will be fixed in the next release.
