### ISSUE TITLE
C++ TextFormat float rendering inconsistent with Python

### ISSUE THREAD

**Issue by ezyang** [google/protobuf#3553]
On c44c3af2bcbb59fd2b2fd60b247429a2c19ec02b:

```
MacBook-Pro-97:proto-float ezyang$ cat foo.proto
syntax = 'proto2';
message A {
  optional float f = 1;
}
MacBook-Pro-97:proto-float ezyang$ cat main.cc
#include "foo.pb.h"
#include <google/protobuf/text_format.h>
#include <iostream>
int main() {
  A a;
  a.set_f(0.9);
  std::string s;
  google::protobuf::TextFormat::PrintToString(a, &s);
  std::cout << s;
  return 0;
}
MacBook-Pro-97:proto-float ezyang$ DYLD_LIBRARY_PATH=/Users/ezyang/Dev/labs/protobuf/src/.libs /Users/ezyang/Dev/labs/protobuf/src/.libs/protoc foo.proto --cpp_out=. --python_out=.
MacBook-Pro-97:proto-float ezyang$ DYLD_LIBRARY_PATH=/Users/ezyang/Dev/labs/protobuf/src/.libs clang++ foo.pb.cc main.cc -o main -I/Users/ezyang/Dev/labs/protobuf/src -L/Users/ezyang/Dev/labs/protobuf/src/.libs  -lprotobuf
MacBook-Pro-97:proto-float ezyang$ DYLD_LIBRARY_PATH=/Users/ezyang/Dev/labs/protobuf/src/.libs ./main
f: 0.9
```

This is inconsistent with how the Python version of TextFormat prints floats:

```
(caffe2) MacBook-Pro-97:proto-float ezyang$ PYTHONPATH=/Users/ezyang/Dev/labs/protobuf/python/build/lib python
Python 3.6.1 | packaged by conda-forge | (default, May 23 2017, 14:31:56) 
[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import foo_pb2
>>> foo_pb2.A.FromString(open("foo", "rb").read())
f: 0.8999999761581421
```

I am not sure which one is right, but it would be good if they were the same...

**Comment by anandolee** [comment]
It is float precision difference between C++ and python languages themselves, not protobuf. (It has the same issue if it is not a protobuf message) So both behaviors are correct. 

Note: text-format is intended for communications with humans. For machine communications, use wire format instead.

**Comment by ezyang** [comment]
I am not sure what "precision" difference there could be: a float in protobufs is always four bytes, no matter what language you are in. Perhaps you are saying something like, the default rendering of float in C++ and Python is different, but that's strictly an implementation detail for the implementation of TextFormat.

I'm interested in the text-format being the same because we are using the text-format as "expect files" for various protobuf serialization tests we are doing, where it is important for a human to be able to visually inspect the diff of how a protobuf serialized. Some folks on the internet have claimed that textformat is deterministic.

**Comment by anandolee** [comment]
For now, unlike JSON format we do not have a standard for text-format yet. Different languages might have some difference besides float.

"Some folks on the internet have claimed that textformat is deterministic."  Yes textformat is deterministic, but it is talking about the field order especially the map field. The map was un-ordered  so the serialize result might be different every time. Text format sort the keys for textformat to make it 'deterministic'

**Comment by anandolee** [comment]
Closing the issue as no follow up messages. Free feel to reopen if needed

**Comment by twmht** [comment]
@anandolee 

Is it possible to output the text-format which is consistent with c++?

For example (https://github.com/BVLC/caffe/blob/master/src/caffe/proto/caffe.proto#L50),

I use `python-protobuf` to write a float point `0.1`, but the text-format is `0.00999999977648`. is it possible to output the text consistent with python?

**Comment by twmht** [comment]
I tried numpy with np.float32(0.1),  and serialized to text format, but it still outputs  0.00999999977648.
