### ISSUE TITLE
Documentation does not include release version information

### ISSUE THREAD

**Issue by rgeary1** [google/protobuf#356]
The .proto documentation is now confusing - new language features like "map" have been added to proto2 and proto3 docs, but this feature is not available in the latest stable release (2.6.1).  This is especially confusing given that it appears in "proto2" docs, which implies it's in the older version.

The documentation should include statements specifying the minimum version for each language feature, or at least add that information for "map".

**Comment by col6y** [comment]
I concur with this - I was very confused by proto2 not supporting maps when the documentation said that it should.

**Comment by pherl** [comment]
We had one discussion years ago and decide not to list version that the feature is added. Main rationale  is for readability that the doc won't have versioning tags all over the place. Users should use the newest version instead. I guess we could have snapshot of docs for each version instead.
