### ISSUE TITLE
CMake 3.4.0 builds broken on Linux due to missing files in release package

### ISSUE THREAD

**Issue by timou** [google/protobuf#3562]
For some reason, the "cpp" tar/zip releases for 3.4.0 are missing two key files:

* cmake/protobuf-lite.pc.cmake
* cmake/protobuf.pc.cmake

The absence of these files breaks the cmake build on Linux, as they are referred to from cmake/install.cmake.

These files are present in the full source code link, just not the cpp one. See for comparison:

* https://github.com/google/protobuf/releases/download/v3.4.0/protobuf-cpp-3.4.0.tar.gz
* https://github.com/google/protobuf/archive/v3.4.0.tar.gz

**Comment by pherl** [comment]
@xfxyjwf It seems the cmake files are explicitly excluded from the cpp-distcheck. Is there any reason for that?

**Comment by xfxyjwf** [comment]
It's done by mistake in https://github.com/google/protobuf/pull/3403

These files should be included in "make dist".

**Comment by timou** [comment]
Thanks!

**Comment by anuppari** [comment]
Can you update the zip/tar on the [release page](https://github.com/google/protobuf/releases/tag/v3.4.0) so new users can download a working source?

Thanks

**Comment by pherl** [comment]
I'm planning on a 3.4.1 release today. Should be able to fix the issue.
