### ISSUE TITLE
how to compile protobuf-compiler, libprotobuf-dev for Mosh 

### ISSUE THREAD

**Issue by blub4747** [google/protobuf#3569]
Hi guys,
How to I please compile the two above named packages so I can compile MOSH.
Thx

**Comment by faiz-akhtar** [comment]
Will need additional details in order to provide any solution. Which version of mosh are you trying to compile and on which distro? Which architecture? What steps you followed and what error did you encounter?

**Comment by blub4747** [comment]
Hi sorry here the missing bits of info coming up.
Version of MOSH mosh-1.3.2.tar.gz
Debian 8 and 9 possibly Ubuntu 16.04.3
architecture AMD64 and armhf
i will have provide the error msgs at a later point.

**Comment by faiz-akhtar** [comment]
I built mosh 1.3.2 on Ubuntu 16.04 (amd64} 
protobuf-compiler, libprotobuf-dev are present in repo. Do you need to build these dependencies specifically from source?

**Comment by blub4747** [comment]
Hi sorry for the delay.
I just retried to compile MOSH on all of servers.
On a cubietruck running armbian Ubu ntu 16.04.3 LTS
 I walked again into the issue of the missing Protocol Buffers

> configure: error: cannot find protoc, the Protocol Buffers compiler
Therefore which packages do I need to download and compile so I can compile MOSH ?

**Comment by faiz-akhtar** [comment]
Sorry I can verify only on amd64, don't have arm hardware. Maybe someone else will help you out. Till then, if protobuf is not present in repo for armbian ubuntu you can try building it from source by following these instructions https://github.com/google/protobuf/blob/master/src/README.md

**Comment by blub4747** [comment]
Hi again and once again sorry for the delay.
I just managed to clear all of my dependencies problems. MOSH is now finally compiling without problems on all of my serves.
THX

**Comment by flawless0714** [comment]
Hi @blub4747, I'm wondering how you succeed the installation of Mosh, I just compiled protobuf with [https://github.com/google/protobuf/blob/master/src/README.md](url), and when I **make** in mosh I got an error like this `from hostinput.pb.cc:4:
/usr/include/c++/5/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
 #error This file requires compiler and library support \` I'm not sure if it's a version problem or somehow, and my platform is Jetson TX2 (arrch64).
Thanks a lot.
