### ISSUE TITLE
warning C4800 

### ISSUE THREAD

**Issue by kimshnet** [google/protobuf#3572]
I use protobuf 3.4.0 in 64bit windows.  but i got 3 warning C4800.
warning C4800 'goole::protobuff::internal::AtomicWord' : forcing value to bool 'true' or 'false' (performance warning) \protobuf\google\protobuf\io\coded_stream.h
warning C4800 'goole::protobuff::internal::Atomic64' : forcing value to bool 'true' or 'false' (performance warning) \protobuf\google\protobuf\io\coded_stream.h
warning C4800 'goole::protobuf::uint32' : forcing value to bool 'true' or 'false' (performance warning) \protobuf\google\protobuf\generated_message_util.h

how can i fix this warning?
(now i use pragma warning disable)

**Comment by MrMoose** [comment]
Am I correct in understanding that this was closed as "customer issue"?

I would like to comment here that I have been dealing with those warnings for a long time too. Normally I resort to patching the code and try to fix them but it's getting to a point that I move to putting warning pragmas around including protobuf's headers.
Which is not much of a problem per se but I would like to ask: Does the protobuf project feel comfortable with users having to pragma warnings out when including generated headers? Wouldn't it be possible and in fact very much desirable to not be one of those libs?
