### ISSUE TITLE
The library is incompatible with python3-protobuf

### ISSUE THREAD

**Issue by omamchich** [google/protobuf#3573]
python3-protobuf is one of the dependencies for riak library.

Once I install protobuf. Then riak library stops working.

I always get the error like this:
File "/usr/local/lib/python3.5/dist-packages/google/protobuf/descriptor.py", line 824, in new
return _message.default_pool.AddSerializedFile(serialized_pb)
TypeError: expected bytes, str found

Seems like python3-protobuf and protobuf are incompatible.

**Comment by anandolee** [comment]
Which platform are you using?

Python3 is supported on linux at least 3.3 3.4 3.5 3.6 are tested:
https://github.com/google/protobuf/blob/c7457ef65a7a8584b1e3bd396c401ccf8e275ffa/tests.sh#L233

The error may related how you or riak library are using protobuf, platform, protobuf bug or others. It is possible to give more descriptions?

**Comment by omamchich** [comment]
Hello. Thanks for your response. 
I am using Ubuntu 15.10. Python is 3.5.1.
The problem is the following: riak library has python3-protobuf library as a dependency. I use google-cloud-bigquery that has a protobuf library as a dependency too. No problem when I use these libraries separately. But I found the interesting problem after protobuf installation after python3-protobuf. After protobuf installation python3-protobuf stops working correctly. Even after uninstall. Seems like protobuf rewrites something for python3-protobuf.
The same problem if I try to install python3-protobuf after protobuf. This time python3-protobuf works but protobuf raises the following error:

Traceback (most recent call last):
  File "{my_file}", line 6, in <module>
    from google.cloud import bigquery
  File "/usr/local/lib/python3.5/dist-packages/google/cloud/bigquery/__init__.py", line 29, in <module>
    from google.cloud.bigquery._helpers import ArrayQueryParameter
  File "/usr/local/lib/python3.5/dist-packages/google/cloud/bigquery/_helpers.py", line 21, in <module>
    from google.cloud._helpers import UTC
  File "/usr/local/lib/python3.5/dist-packages/google/cloud/_helpers.py", line 33, in <module>
    from google.protobuf import duration_pb2
  File "/usr/local/lib/python3.5/dist-packages/google/protobuf/duration_pb2.py", line 9, in <module>
    from google.protobuf import symbol_database as _symbol_database
  File "/usr/local/lib/python3.5/dist-packages/google/protobuf/symbol_database.py", line 184, in <module>
    _DEFAULT = SymbolDatabase(pool=descriptor_pool.Default())
AttributeError: module 'google.protobuf.descriptor_pool' has no attribute 'Default'

Thanks a lot for your help.

**Comment by arthur-tacca** [comment]
(Note: I'm not a Googler nor on the protobuf team.) It appears that [python3-protobuf](https://pypi.python.org/pypi/python3-protobuf) is an unofficial modification of a very old version of protobuf (version 2.5) to make it work with Python 3. It's not surprising that it can't be installed at the same time as protobuf: you are trying to install two different versions of the same library at the same time. The fact that `riak` doesn't work with recent versions of protobuf is a problem with that library, not this one.
