### ISSUE TITLE
build fails on macosx/i386

### ISSUE THREAD

**Issue by artiommorozov** [google/protobuf#3581]
Main fails to build on macosx sierra for i386 arch. It happens because Atomic32 and AtomicWord both typedef to intptr_t so atomicops_internals_x86_gcc.h and atomicops_internals_atomicword_compat.h redefine functions like NoBarrier_Load.

To reproduce issue
export CXX=clang++
export CXXFLAGS="-arch i386" 
./configure && make

To fix
--- src/google/protobuf/stubs/atomicops.h.prev	2017-09-01 11:17:30.000000000 +0300
+++ src/google/protobuf/stubs/atomicops.h	2017-09-01 11:20:07.000000000 +0300
@@ -231,7 +231,7 @@
 
 // On some platforms we need additional declarations to make AtomicWord
 // compatible with our other Atomic* types.
-#if defined(GOOGLE_PROTOBUF_OS_APPLE)
+#if defined(GOOGLE_PROTOBUF_OS_APPLE) && !defined(GOOGLE_PROTOBUF_ARCH_32_BIT)
 #include <google/protobuf/stubs/atomicops_internals_atomicword_compat.h>
 #endif

**Comment by acozzette** [comment]
Thank you for reporting this. Could you send us a pull request with your fix?

**Comment by pherl** [comment]
I believe should have been fixed.
