### ISSUE TITLE
Python - protobuf: AttributeError: 'SymbolDatabase' object has no attribute 'RegisterServiceDescriptor'

### ISSUE THREAD

**Issue by khenaidoo** [google/protobuf#3582]
Hello, we have been using python protobuf version 3.1.0.post1 for a while with no issues.  Starting this morning (September 1, 2017), after a clean install, we are getting the following error when importing any grpc module:

voltha_1 | Traceback (most recent call last):
voltha_1 | File "/voltha/voltha/main.py", line 37, in <module>
voltha_1 | from voltha.adapters.loader import AdapterLoader
voltha_1 | File "/voltha/voltha/adapters/loader.py", line 32, in <module>
voltha_1 | from voltha.core.adapter_agent import AdapterAgent
voltha_1 | File "/voltha/voltha/core/adapter_agent.py", line 39, in <module>
voltha_1 | from voltha.protos.voltha_pb2 import DeviceGroup, LogicalDevice, \
voltha_1 | File "/voltha/voltha/protos/voltha_pb2.py", line 22, in <module>
voltha_1 | import health_pb2 as health__pb2
voltha_1 | File "/voltha/voltha/protos/health_pb2.py", line 124, in <module>
voltha_1 | _sym_db.RegisterServiceDescriptor(_HEALTHSERVICE)
voltha_1 | AttributeError: 'SymbolDatabase' object has no attribute 'RegisterServiceDescriptor'

Looking at google/protobuf/symbol_database.py, I find that the RegisterServiceDescriptor() is missing.  It should have been there before for our build to succeed.   No new version of the protobuf module (version 3.1.0.post1) seem to have been uploaded on pypi.  Version 3.4.0 has the RegisterServiceDescriptor() method in symbol_database.py.   However, upgrading to version 3.4 brings about additional proto validation errors which were not occurring before.

Can you please provide any guidance on the missing service in version 3.1?  Was it an intentional change?

Thanks
Khen

**Comment by xfxyjwf** [comment]
I think the problem is that you accidentally upgraded to a newer version of protocol compiler.

**Comment by khenaidoo** [comment]
Thanks for the quick response Feng.   We did not provide an exact version for the grpc compiler , so this could be the issue (besides I saw an update to grpc-tools as of August 30).   I will make the change and let you know.

Thanks again.
Khen

**Comment by khenaidoo** [comment]
After testing with older versions of grpcio tools(1.3.5) the problem went away.   Feng was correct.   BY not locking down the grpcio version we picked up the latest version 1.6 (2 days ago) which was incompatible with the protobuf version we were using.

Thanks Feng.  I will close the issue.

**Comment by pcj** [comment]
Any idea when python will be compatible with 1.6?

**Comment by anandolee** [comment]
@pcj,  what is your issue?
khenaidoo is talking about the problem between protobuf  3.1 and grpcio 1.6 and it will not be fix. Protobuf 3.4 and grpcio1.6 is compatible.

**Comment by pcj** [comment]
Ugh, this was an issue on my side with darwin (dual python install, apple python and homebrew python) wherein pip was installing to apple python site-packages 3.4.0 and homebrew python had an older protobuf 3.1.0 (or something like that).  Sorry for the confusion.
