### ISSUE TITLE
jsonToMessage() fails depending on locale on Centos5

### ISSUE THREAD

**Issue by neundorf** [google/protobuf#3584]
Hi,

google::protobuf::util::JsonStringToMessage() fails to read a json string which contains doubles or floats if the locale doesn't use a "." as decimal point.
It fails for me on Centos5, the same code works for me on a current OpenSUSE.

Replacing safe_strtod() with NoLocaleStrtod() in JsonStreamParser::ParseNumberHelper() seems to fix the problem for me (but NoLocaleStrtod() looks quite slow).
I haven't tried using strtod_l() yet.

Alex

**Comment by neundorf** [comment]
This patch fixes it for me. The initial call is probably not thread-safe.

--- protobuf/src/google/protobuf/stubs/strutil.cc       (revision 33839)
+++ protobuf/src/google/protobuf/stubs/strutil.cc       (working copy)
@@ -1346,8 +1346,17 @@
 }
 
 bool safe_strtod(const char* str, double* value) {
+
+  static bool c_locale_initialized = false;
+  static locale_t c_locale;
+  if(!c_locale_initialized)
+  {
+    c_locale_initialized = true;
+    c_locale = newlocale(LC_ALL_MASK, "C", NULL);
+  }
+
   char* endptr;
-  *value = strtod(str, &endptr);
+  *value = strtod_l(str, &endptr, c_locale);
   if (endptr != str) {
     while (ascii_isspace(*endptr)) ++endptr;
   }

**Comment by acozzette** [comment]
Thanks for reporting this. Do you have an example of a particular locale where `strtod` gives the wrong result for the purpose of producing JSON? Are you saying that it's only a problem with Centos 5?

**Comment by neundorf** [comment]
"de_DE.UTF-8" in my case.
Regarding Centos5: that's a bit complicated. I'm using a quite special setup (Centos5 in a docker container, using the C++ compiler from Intel). There I have the problem. Building the same code using gcc on the OpenSUSE host doesn't show the problem. Building the same code using gcc (instead of Intel) in Centos5 didn't work because the gcc coming with Centos5 had problems building protobuf.

I wrote a small test case. The proto file:
<pre>
syntax = "proto3";

message Foo
{
  string name = 1;
  int32 index = 2;
  double value = 3;
}
</pre>

And the test. This gave an error and the double value was not set afterwards:
<pre>
int main()
{
  Foo foo;
  foo.set_name("hello");
  foo.set_index(3);
  foo.set_value(1234567.123);

  std::string jsonBuf;
  google::protobuf::util::MessageToJsonString(foo, &jsonBuf);

  Foo brokenFoo;
  google::protobuf::util::Status status = google::protobuf::util::JsonStringToMessage(jsonBuf, &brokenFoo);
  fprintf(stderr, "status=%d \"%s\"\n", status.error_code(), status.error_message().data());
  return 0;
}
</pre>

**Comment by acozzette** [comment]
I'm a little bit confused about this, because yesterday I tried with a French locale (`fr_FR.UTF-8`) and I couldn't get `strtod` to behave any differently with respect to decimal points (using gcc 4.8.4 on Ubuntu). Maybe the correct behavior is for `strtod` to always use `.` as the decimal point, but perhaps Intel's compiler has a bug? Or maybe Intel is doing it right and gcc has the bug.

It seems like it would be nice to be able to handle different behaviors of `strtod` but do so in a consistent way. Do you think it would be possible to just update `NoLocaleStrtod` but get it to perform better?

**Comment by pherl** [comment]
We are closing open issues. Feel free to send PRs and reopen if you'd like to follow up on the issue.
