### ISSUE TITLE
.NET package for 3.4.0 targets net451, not net45

### ISSUE THREAD

**Issue by jskeet** [google/protobuf#3595]
It looks like this was a failure on my part when converting from project.json to csproj... we should still target net45, rather than net451.

I can't check this instant, but I'd *expect* us to be able to just change

```xml
<TargetFrameworks>netstandard1.0;net451</TargetFrameworks>
```

to

```xml
<TargetFrameworks>netstandard1.0;net45</TargetFrameworks>
```

in Google.Protobuf.csproj.

If that works, could we patch it into the 3.4.x branch, bump the version number to 3.4.1, and rerelease?

**Comment by jtattermusch** [comment]
CC @jtattermusch

**Comment by pherl** [comment]
Is there any test that can catch/verify this? Also it looks like csharp/src/Google.Protobuf.Test/Google.Protobuf.Test.csproj sets the net451 as TargeFrameworks too.

**Comment by jskeet** [comment]
It would need a very specific test - given the lack of need to change the project file again, I'm not sure it's worth it... This was only missed as it was part of a bigger change.

**Comment by jtattermusch** [comment]
@jskeet  the PR was against 3.4.x, so no need to cherry-picked, it needs to be upmerged to master).
