### ISSUE TITLE
[C++]Use Reflection To SetValue , but value has not changed by normal visited 

### ISSUE THREAD

**Issue by P-Chao** [google/protobuf#3598]
It's strange that the `name` is diffirent that get from direct visit and reflection visit.
```
pMessage = &layer.imagepair_param().pair(0);
pDescriptor = pMessage->GetDescriptor();
pReflection = pMessage->GetReflection();
pFiled = pDescriptor->FindFieldByName("left");
pFiled = pDescriptor->FindFieldByNumber(1);

string name = pReflection->GetString(*pMessage, pFiled); // name = "F:/data"; (init value read from protofiles )
pReflection->SetString(const_cast<google::protobuf::Message*>(pMessage), pFiled, "123");
name = pReflection->GetString(*pMessage, pFiled); // name = "123";
name = layers[node->name].imagepair_param().pair(0).left(); // name = "F:/data"; (I cannot understand, why name not change)
```
And How Can I Modify the Origin Value By Reflection, thanks!

**Comment by acozzette** [comment]
Are you sure that `layer.imagepair_param()` is the same thing as `layers[node->name].imagepair_param()`? If those are different then that would explain why the problem.

**Comment by P-Chao** [comment]
Use `auto layer = layers[node->name]` will copy it, then I changed my code `auto& layer = layers[node->name]` , the result is right.
Thank you very much ~
