### ISSUE TITLE
Protobuf 3.3.2 missing on maven central

### ISSUE THREAD

**Issue by languitar** [google/protobuf#3602]
Version 3.3.2 is missing on maven central. Even if there is backwards compatibility this contradicts the usual recommendation that versions should match exactly. We have incorporated this into our build systems and these fail now with the missing version in maven.

**Comment by acozzette** [comment]
I believe 3.3.2 was a release we only needed for bug fixes for certain languages, and so we did not push new artifacts for every language with that release (see #3302). That's a fair point that ideally it should be possible to match versions exactly, though. Is your problem that you are using 3.3.2 for some languages but cannot using the matching version for Java?

**Comment by languitar** [comment]
Thr problem is that our build system defines the versions of the libraries to use from the version `protoc` prints out using the `--version` flag. And on archlinux, this is currently 3.3.2, so we try to find the matching maven artifact, which fails.

**Comment by pherl** [comment]
I'd suggest setting the version to the latest version in the same minor version. e.g. for 3.3.2, look for the latest one >=3.3.0 && < 3.4.0. This will make the dependency much stable. We typically have per-language fixes and releasing all other languages will slow down the release and development. Hopefully it would be better when we break down each languages to have their own release schedule.

**Comment by xfxyjwf** [comment]
Before we automate the binary release process, releasing binary artifacts for patch versions is just too much work and as Adam mentioned there are likely no changes made in many languages in a patch release. I would recommend updating your build setup to allow protoc version to be different from runtime version. Our release process will likely stay this way for a while until we get to build an automated release pipeline.

**Comment by languitar** [comment]
Sure I can do that. But an explicit statement somewhere in the documentation about these assumptions and rules would be very helpful. At the time we looked on how to automate things, there was just the general rule to "use the same version everywhere", which fails here.
