### ISSUE TITLE
make fails: Makefile:4086: recipe for target 'google/protobuf/descriptor.lo' failed

### ISSUE THREAD

**Issue by fargo47** [google/protobuf#3605]
Dear members,

I am getting this error when i want to build the C++ Protocol Buffer:

`libtool: compile:  g++ -std=c++11 -DHAVE_CONFIG_H -I. -I.. -pthread -DHAVE_PTHREAD=1 -Wall -Wno-sign-compare -O2 -g -DNDEBUG -MT google/protobuf/descriptor.lo -MD -MP -MF google/protobuf/.deps/descriptor.Tpo -c google/protobuf/descriptor.cc  -fPIC -DPIC -o google/protobuf/.libs/descriptor.o
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.9/README.Bugs> for instructions.
Makefile:4086: recipe for target 'google/protobuf/descriptor.lo' failed
make[2]: *** [google/protobuf/descriptor.lo] Error 1
make[2]: Leaving directory '/root/protobuf-master/src'
Makefile:1479: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/root/protobuf-master'
Makefile:1385: recipe for target 'all' failed
make: *** [all] Error 2
`

**Comment by hassan-alizadeh** [comment]
This error disappeared when I increased the RAM on my VirtualBox-Ubuntu.

**Comment by jainrahul1** [comment]
I am also facing the same issue on PINE A64+ board with bootable 32GB card. I am not sure how to increase virtual memory?
