### ISSUE TITLE
How to install or config php-protobuffer 3.3.0 on Windows.

### ISSUE THREAD

**Issue by linux2014linux** [google/protobuf#3610]

**Comment by TeBoring** [comment]
We only provide php implementation on windows. We haven't provide c extension on windows.

**Comment by linux2014linux** [comment]
So, I want to use my php code on windows and linux. Do I only use php implementation?

**Comment by TeBoring** [comment]
For now, you can only use php implementation. We probably will provide window c extension by end of year.

**Comment by linux2014linux** [comment]
Oh, I got it. Thank you!
