### ISSUE TITLE
UnmodifiableLazyStringList is not Serializable

### ISSUE THREAD

**Issue by JanecekPetr** [google/protobuf#3611]
Cont'd from https://groups.google.com/forum/#!msg/protobuf/7bFAlrtK_SU/lro6ajJJrXMJ, I basically got the same error, but 6 years later.

The idea is of course that I have a `repeated string` field that I get from a serialized protobuf and store in a POJO. That POJO is later elsewhere serialized and sent over the network. Imagine our surprise when a `List<String>` failed to serialize, it's just something that you do not expect to happen at all (even though it's completely valid).

Yes, the workaround, to copy the list out, is simple. But still, the list could simply be serializable itself...

**Comment by pherl** [comment]
This is something that we probably won't support. You would have to copy those lists somehow.

**Comment by JanecekPetr** [comment]
That's a shame, but I understand the decision. Is the rationale that you don't think the feature would pull its weight, or is it a more philosophical problem, e.g. that serializing a lazy list is not well defined?
