### ISSUE TITLE
No matching function for call to 'MessageToJsonString'

### ISSUE THREAD

**Issue by 2939699018** [google/protobuf#3616]
dear all,

   I download cpp source (protobuf-cpp-3.4.0.tar.gz) , and make them to libprotobuf-lite.a.

   I want to make pb object to json string like following  , but got error message like "No matching function for call to 'MessageToJsonString'" in Xcode.

    const std::string toJson(const google::protobuf::MessageLite &message, const google::protobuf::util::JsonPrintOptions& options) {
        std::string result;
        result.clear();
        const auto& google_status = google::protobuf::util::MessageToJsonString(message, &result, google::protobuf::util::JsonPrintOptions());
        return result;
    }
    
   it's seem that google::protobuf::util not in libprotobuf-lite.a.
   who can tell me how to solve it ?

**Comment by arthur-tacca** [comment]
Looks like you're using `MessageLite` rather than `Message`. The difference between these two classes is that `MessageLite` does not include reflection (i.e. a run time list of field names and types) whereas `Message` does. This information is necessary for the JSON functions to work.

**Comment by 2939699018** [comment]
const std::string toJson(const google::protobuf::Message &message, const JsonParseOptions& options) {
        std::string result;
        result.clear();
        
        int ret = google::protobuf::util::MessageToJsonString(message , &result, options);
        return result;
    }

I changed the class from MessageLite to Message,  but can't solve the error.

**Comment by hadrielk** [comment]
You're passing it `JsonParseOptions`, but `MessageToJsonString()` takes just `JsonOptions`.

**Comment by 2939699018** [comment]
@hadrielk 
the source code just copy from src/google/protobuf/util/json_util_test.cc.

  string ToJson(const Message& message, const JsonPrintOptions& options) {
    string result;
    GOOGLE_CHECK_OK(MessageToJsonString(message, &result, options));
    return result;
  }

**Comment by arthur-tacca** [comment]
@2939699018 as hadrielk said:
wrong: Json**Parse**Options
right: JsonOptions, also called Json**Print**Options
your code in your original comment: JsonPrintOptions (correct)
your second comment: JsonParseOptions (wrong)
json_util_test.cc: JsonPrintOptions (correct)

**Comment by 2939699018** [comment]
@arthur-tacca @hadrielk
thanks for all of you!

another question is : how can I use MessageToJsonString in protobuf-lite.a instead of  protobuf.a?

**Comment by xfxyjwf** [comment]
@2939699018 MessageToJsonString requires full runtime (i.e., libprotobuf.a is required). It's not possible to use it with libprotobuf-lite.a.
