### ISSUE TITLE
Use of undefined constant url_prifix_len

### ISSUE THREAD

**Issue by jackwakefield** [google/protobuf#3617]
After a change to the test script in #3563 the PHP implementation is failing with

```
1) WellKnownTest::testAny
Use of undefined constant url_prifix_len - assumed 'url_prifix_len'

php/src/Google/Protobuf/Any.php:212
php/tests/well_known_test.php:46

2) WellKnownTest::testAnyUnpackInvalidTypeUrl
Use of undefined constant url_prifix_len - assumed 'url_prifix_len'

php/src/Google/Protobuf/Any.php:212
php/tests/well_known_test.php:68

3) WellKnownTest::testAnyUnpackMessageNotAdded
Use of undefined constant url_prifix_len - assumed 'url_prifix_len'

php/src/Google/Protobuf/Any.php:212
php/tests/well_known_test.php:78

4) WellKnownTest::testAnyUnpackDecodeError
Use of undefined constant url_prifix_len - assumed 'url_prifix_len'

php/src/Google/Protobuf/Any.php:212
php/tests/well_known_test.php:89
```

**Comment by TeBoring** [comment]
It's strange that our test hasn't catched it.

**Comment by jackwakefield** [comment]
This wasn't thrown as an error until I changed the unit test script to run against the PHP implementation with https://github.com/google/protobuf/pull/3563/commits/c0d1ebfc1232c3e03895b3cef4768e1253a5c456#diff-8e2cebf79265b986aedee9ecaa76f2f6R21. Before it was only testing against the extension.

**Comment by TeBoring** [comment]
I figured out that is because the error is just notice instead of error. Besides, the code with problem can be deleted without any effect. That's why it failed silently.
