### ISSUE TITLE
Released tar ball hashes have changed

### ISSUE THREAD

**Issue by weili-jiang** [google/protobuf#3628]
We have a build that checksums source tar balls, and it appears that the v3.1.0.tar.gz checksum has changed from what we were previously expecting, failing our build.

**SHA256**
**Expected:** 0a0ae63cbffc274efb573bdde9a253e3f32e458c41261df51c5dbc5ad541e8f7
**Now:** fb2a314f4be897491bb2446697be693d489af645cb0e165a85e7e64e07eb134d

What has caused an existing released tar ball to have changed?

**Comment by xfxyjwf** [comment]
See: https://github.com/google/protobuf/issues/3619

Short summary: the tarball you downloaded is created by github and they changed the checksum of all such tarballs.
