### ISSUE TITLE
No documentation on how to run protoc with the Objective-C plugin

### ISSUE THREAD

**Issue by jcanizales** [google/protobuf#364]
I cloned the repo locally, now what? :)

**Comment by xfxyjwf** [comment]
Try "protoc --objc_out="? Objective-c code generators will be included in protocol compiler so you just use the protoc binary.

**Comment by jcanizales** [comment]
I understand I have first to follow the instructions of README.md under "C++ installation"?

**Comment by jcanizales** [comment]
(And would installing using homebrew include the Objective-C plugin?)

**Comment by xfxyjwf** [comment]
Homebrew is currently at v3.0.0-alpha-2 which does not have objective-c support. We are making a new alpha-3 release and it will include objective-c. After that the protoc installed by homebrew should have objective-c in it (of course only after someone update the homebrew script to alpha-3).
