### ISSUE TITLE
Compiling on a 32bit docker image

### ISSUE THREAD

**Issue by magick93** [google/protobuf#3644]
Hello

Im trying to compile Protobuf from source, during the build process of a docker image. 
The docker image is 32bit, but is intended to run on a 64bit host.

The build of the docker image was successful, but when I try to run protoc I cant. 
For example, I get:

```
file /usr/local/bin/protoc          
/usr/local/bin/protoc: ELF 64-bit LSB executable, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.18, BuildID[sha1]=e87bf6eb1c507bb7f65f3c7687df6a3b41b563be, stripped
```

And also
`bash: /usr/local/bin/protoc: No such file or directory`

So it seems, while the docker container is - in many ways 32 bit - the compilation was 64bit.

My question therefore is, how can I compile protobuffers to be 32 bit?

Thanks

**Comment by faiz-akhtar** [comment]
Not an expert in this area, but I think the docker container will behave as a 64 bit system, if the host is 64 bit. Whether the docker image is 32 bit specific will be inconsequential. The container uses the kernel of the host.

The obvious difference between a 32 bit image and a 64 bit image is that, a 32 bit image can be used to create containers on both 32 bit and 64 bit hosts, while a 64 bit image will work only on 64 bit host.

So, unless you have a 32 bit host, you cannot create 32 bit containers. On the other hand, if you want to build a 32 bit version of protobuf on a 64 bit system, that is possible by changing some configure parameters and compiler flags, but you will still not have a 32 bit environment. Is this what you are aiming for?

**Comment by TeBoring** [comment]
We have provided protoc on 32-bit in our release page: https://github.com/google/protobuf/releases/download/v3.4.0/protoc-3.4.0-linux-x86_32.zip
For more detail for compiling: https://github.com/google/protobuf/blob/master/protoc-artifacts/README.md

**Comment by Tim15** [comment]
One issue that I had when pulling `protoc` binaries from github on an `alpine` base image is that was referencing the wrong shared libraries, because it was dynamically linked on a builder that didn't use musl libc. You can check this by running `ldd $your_proto_binary`, and if it says that it is not found, you have an issue.

**Comment by davido** [comment]
Yeah, it seems that I have this issue.

I'm trying to build gerrit code review on Alpine linux docker image. gerrit Code Review is using Cosure compiler, that depends on protobuf and doing something like:

```
def com_google_protobuf_protoc_linux_x86_64():
  native.http_file(
      name = "com_google_protobuf_protoc_linux_x86_64",
      urls = [
          "http://bazel-mirror.storage.googleapis.com/github.com/google/protobuf/releases/download/v3.1.0/protoc-3.1.0-linux-x86_64.zip",
          "https://github.com/google/protobuf/releases/download/v3.1.0/protoc-3.1.0-linux-x86_64.zip",
      ],
      sha256 = "7c98f9e8a3d77e49a072861b7a9b18ffb22c98e37d2a80650264661bfaad5b3a",
  )
```

Now, this cannot work on Alpine docker image, as it doesn't have glibc:

```
ERROR: /home/davido/.cache/bazel/_bazel_davido/a6c7865269edc177ebab9d4cd9db0bb3/external/io_bazel_rules_closure/java/io/bazel/rules/closure/worker/BUILD:38:1: error executing shell command: 'JAR='external/local_jdk/bin/jar' OUTPUT='bazel-out/host/bin/external/io_bazel_rules_closure/java/io/bazel/rules/closure/worker/libworker_protocol_java_proto_srcjar.srcjar' PROTO_COMPILER='external/...' failed (Exit 1)
bazel-out/host/bin/external/io_bazel_rules_closure/closure/private/gensrcjar: line 1: external/com_google_protobuf_protoc/bin/protoc: not found
gensrcjar: proto_compiler failed
```

And trying to `ldd external/com_google_protobuf_protoc/bin/protoc`:

```
	/lib64/ld-linux-x86-64.so.2 (0x7f1327a3a000)
	libpthread.so.0 => /lib64/ld-linux-x86-64.so.2 (0x7f1327a3a000)
	libm.so.6 => /lib64/ld-linux-x86-64.so.2 (0x7f1327a3a000)
	libc.so.6 => /lib64/ld-linux-x86-64.so.2 (0x7f1327a3a000)
Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by external/com_google_protobuf_protoc/bin/protoc)
Error relocating external/com_google_protobuf_protoc/bin/protoc: __isnan: symbol not found
Error relocating external/com_google_protobuf_protoc/bin/protoc: __isnanf: symbol not found
86523ee72618:~/.cache/bazel/_bazel_davido/a6c7865269edc177ebab9d4cd9db0bb3/execroot/gerrit$ uname -a
Linux 86523ee72618 4.13.9-1-default #1 SMP PREEMPT Mon Oct 23 09:44:25 UTC 2017 (e7d7106) x86_64 Linux
```

**Comment by mduft** [comment]
Having the same issue when trying to build gerrit on alpine :) anybody got a workaround for that?

**Comment by davido** [comment]
@mduft sure, I always have a workaround how to build gerritm in any environment ;-)

Here is the right docker image: [1]. This image is based on my native Apline Linux Bazel package, that I maintain here: [2].

* [1] https://hub.docker.com/r/davido42/bazel-build-gerrit/
* [2] https://github.com/davido/bazel-alpine-package/releases/tag/0.8.0

**Comment by mduft** [comment]
@davido hah, great  :) I need to build my own gerrit, to include all the plugins we have in the release war, but this is a perfect starting point, thanks!

**Comment by davido** [comment]
This should be trivial thing to do. Just fork gerrit, and add your custom
plugins as submodules, and modify: tools/bzl/plugins.bzl

```
CUSTOM_PLUGINS = [
    # Add custom core plugins here
   "foo",
   "bar"
   "baz",
]
```

Done. Now building `bazel build release` should just work and do what you want.

**Comment by acozzette** [comment]
I'm going to close this issue just to tidy things up. It looks like there were a couple different problems here but they seem to be resolved now.
