### ISSUE TITLE
require 'google/protobuf'  fails on ruby gem version 3.4.1  x86_64-linux under nonroot user

### ISSUE THREAD

**Issue by Mamut3D** [google/protobuf#3646]
Latest version of the ruby gem cannot be required in code. Tested on docker container `ruby:2.4.1`
Gem works under root, however nonroot users requiring 'google/protobuf' get the following error:

```
> irb(main):001:0> require 'google/protobuf'
LoadError: cannot load such file -- google/protobuf
        from /usr/local/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:133:in `require'
        from /usr/local/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:133:in `rescue in require'
        from /usr/local/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:40:in `require'
        from (irb):1
        from /usr/local/bin/irb:11:in `<main>'
```

Issue seems similar to https://github.com/google/protobuf/issues/3509

**Comment by pherl** [comment]
I cannot reproduce locally. I can install and import google/protobuf not as root. Is this an installation issue?

**Comment by pherl** [comment]
I yanked the 3.4.1 gems and pushed 3.4.1.1 gems. Please let me know if you still see issues.
