### ISSUE TITLE
Cannot compile 3.0.0 - 3.4.0 

### ISSUE THREAD

**Issue by magick93** [google/protobuf#3647]
Hi

I've tried compiling every version of cpp Protobuf, from 3.0.0 to 3.4.0 but cannot.

I need to compile it, in a 32 docker container.

This is the out the output -https://gist.github.com/magick93/3a9c4894d8ee916d4bf68e764122ccc3

In each case I do the following

1. `wget https://github.com/google/protobuf/releases/download/v3.0.0/protobuf-cpp-3.0.0.zip`
2. Unzip
3.  run `./autogen.sh`
4. ` ./configure`
5.  `make`

Any help in solving this is greatly appreciated!

**Comment by pherl** [comment]
We would need to refine the preprocessor about snprintf to _snprintf for windows. See the comments in https://github.com/google/protobuf/blob/master/src/google/protobuf/stubs/strutil.cc#L46 for the hack for MSVC and MinGW. We need to exclude the macro for the wine compiler. Do you have know any defined preprocessors for your platform/compiler?

The code needs to be changed to
```c++
#if defined(_WIN32) && !defined(YOUR_COMPILER)
#define snprintf _snprintf
#endif
```

Could you test locally and see if that would work? Need to also change the macro in common.cc

**Comment by magick93** [comment]
Thanks.

I was mistakingly trying to compile using the incorrect compiler. 

I have it working now.

**Comment by VirtuallKingg** [comment]
I am using Windows. I can't compile protobuff. Please help.
