### ISSUE TITLE
Compiled static lib is huge

### ISSUE THREAD

**Issue by francislavoie** [google/protobuf#3652]
I compiled protobuf 3.4 myself to use in a C++ Qt project. The resulting `libprotobuf.a` is 66.1MB on Linux, but my coworker's `libprotobuf.a` for Mac is only 3.9MB. Is there a reason that happens for me? Was I supposed to pass certain flags to `./configure`?

We're trying to keep all our dependencies checked into our git repo to make it easier for future development, but I don't want to commit a large file if I don't need to.

Thanks

**Comment by TeBoring** [comment]
Have you tried protobuf-lite?

**Comment by francislavoie** [comment]
I haven't, because mac isn't using that version. Do you know why the size difference between the static lib I compiled for Linux and the one for mac is so large?

**Comment by xfxyjwf** [comment]
It seems by default the "-g" flag will be passed to the compiler and that makes the compiler keep all the debug info. The large binary you see is a result of this. Try override the CXXFLAGS and you should be able to get a much smaller binary:
```bash
$ ./configure CXXFLAGS="-O2"
```
