### ISSUE TITLE
protobuf-java 3.4.1 release on maven central

### ISSUE THREAD

**Issue by danburkert** [google/protobuf#3656]
Hi all,

Will there be a protobuf-java 3.4.1 release published to maven central?  I see in the release notes that there are no major changes for protobuf-java, so perhaps skipping this patch release is by design?

**Comment by danburkert** [comment]
Just found https://github.com/google/protobuf/issues/3602, so feel free to close if this is the same deal.

**Comment by pherl** [comment]
Yes. 3.4.1 didn't change Java and the protoc. There will be no mvn central upload for both protobuf-java or protoc.
