### ISSUE TITLE
configure: error: C preprocessor "/urs/bin/clang -E" fails sanity check

### ISSUE THREAD

**Issue by HJWAJ** [google/protobuf#3657]
Hi, Team

I downloaded the c++ release(3.4.1-tar-gz) and ran ./configure and got error as title shows. After checkin 'config.log' I  found info below:
`configure:5019: /urs/bin/clang -E  conftest.c
./configure: line 1676: /urs/bin/clang: No such file or directory
configure:5019: $? = 127
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "Protocol Buffers"
| #define PACKAGE_TARNAME "protobuf"
| #define PACKAGE_VERSION "3.4.1"
| #define PACKAGE_STRING "Protocol Buffers 3.4.1"
| #define PACKAGE_BUGREPORT "protobuf@googlegroups.com"
| #define PACKAGE_URL ""
| #define PACKAGE "protobuf"
| #define VERSION "3.4.1"
| /* end confdefs.h.  */
| #ifdef __STDC__
| # include <limits.h>
| #else
| # include <assert.h>
| #endif
| 		     Syntax error
configure:5049: error: in `/Users/huajiawei/Downloads/protobuf-3.4.1':
configure:5051: error: C preprocessor "/urs/bin/clang -E" fails sanity check
See `config.log' for more details
`

I noticed it's trying to get "/urs/bin/clang", see, "urs", not "usr". I wonder if there is a bug in the latest release?

**Comment by HJWAJ** [comment]
Yes, when I create a soft link "/urs/bin/clang" to "/usr/bin/clang" and run configure, it succeeds.

**Comment by pherl** [comment]
I believe autoconf reads the environment variable or the command line overwrite to loading which compiler to use.  Can you check the $CC variable?

**Comment by HJWAJ** [comment]
Ah yes, there's something wrong in my .bash_profile. How silly I am! Many thanks!
