### ISSUE TITLE
Add support for PHP "has" getters

### ISSUE THREAD

**Issue by jbq** [google/protobuf#3661]
Hi!  Thanks for the great Protobuf library.  I'm using the recent PHP support and I'm missing the famous `has` getter methods that I'm accustomed to use in the Java edition.  For example how to make a difference between an `int32` field set to zero and the same field that has not been set at all in the `Message`?

Looking for your feedback.  Thanks, and keep up the good work!

**Comment by TeBoring** [comment]
Only proto2 messages has ```has``` get methods.
Currently, we haven't support proto2 in php. My expectation is early next year.

**Comment by jbq** [comment]
OK I meant for proto3, so I read the language guide again and indeed there is no way to determine whether a field is set or not.  Thanks for your explanation.
