### ISSUE TITLE
PHP: error when calling RepeatedField setter with array value

### ISSUE THREAD

**Issue by jbq** [google/protobuf#3662]
Consider the following protobuf definition (cleaned-up for the sake of brevity):

```
message User {
    int32 id = 1;
}

message Tender {
    repeated User member = 12;
}
```

Now consider the following piece of PHP code:

```
$pbTender = new Tender();
$pbTender->setMember([]);
```

I get the following error:

```
Cannot pass parameter 1 by reference
```

I'm expecting to be able to pass an array directly.

**Comment by TeBoring** [comment]
Can you do:
$a = [];
$pbTender->setMember($a);

**Comment by jbq** [comment]
Yes of course I do this as a workaround

**Comment by TeBoring** [comment]
https://github.com/google/protobuf/commit/324b20a49170cb38d15ef243bc044026adb54ae1#diff-134ef5e20d9cb01892fd86eca5f67e34
We have this change in 3.4.0. You should be able to use array as param directly.
Feel free to reopen the bug if the problem is still there.

**Comment by jbq** [comment]
I'm already using the latest `3.4.0` release, I should've mentioned.  Can you please reopen the issue?  Thanks!

**Comment by jbq** [comment]
@TeBoring issue confirmed, but I can't reopen myself.  Shall I create a new issue?  Or maybe you can reopen?

**Comment by jbq** [comment]
Sorry it is my fault, I was properly using the right version of the PECL extension, the right version of the PHP library, but not the right version of the compiler.  Closing now.
