### ISSUE TITLE
Bug in proto3 C++ set_allocated_foo() for embedded message

### ISSUE THREAD

**Issue by alfredkcp** [google/protobuf#367]
We ran into a "double free" problem when using set_allocated_bar for embedded message.
This is the sample proto:
```
syntax = "proto3";

message Foo
{
   int32 Blah1 = 1;
   Bar Bar     = 2;
}

message Bar
{
   int32 Blah2 = 1;
}
```

We found if `set_allocated_bar()` is called (without first invoking a `mutable_bar()`) causes a double free crash when the `Foo` deconstructor is called. I identified the problem of a missing `!= NULL` check before `delete` is called in the generated .pb.h:
```
inline void Foo::set_allocated_bar(Bar* bar) {
  delete bar_; // **should have checked for NULL before deleting!!**
  bar_ = bar;
  if (bar) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:Foo.Bar)
}
```

Please confirm if this is a bug or not.

**Comment by haberman** [comment]
In C++ it is safe to delete the NULL pointer. An explicit check should not be required. See: https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null

What kind of error did you see from this?
