### ISSUE TITLE
No such target '//external:six': target 'six' not declared in package 'external'

### ISSUE THREAD

**Issue by jsonschema** [google/protobuf#3677]
https://github.com/google/protobuf/blob/c627530946e5d8783c1d9c2bbeb1704e4e868963/BUILD#L756

I'm using Bazel to build a Python project that uses protos. Bazel doesn't yet generate Python language bindings `.proto` files. See https://blog.bazel.build/2017/02/27/protocol-buffers.html. However, the Proto team have defined their own: https://github.com/google/protobuf/blob/c627530946e5d8783c1d9c2bbeb1704e4e868963/protobuf.bzl#L313

```
def py_proto_library(
        name,
        srcs=[],
        deps=[],
        py_libs=[],
        py_extra_srcs=[],
        include=None,
        default_runtime="//:protobuf_python",
        protoc="//:protoc",
        use_grpc_plugin=False,
        **kargs):
  """Bazel rule to create a Python protobuf library from proto source files
  NOTE: the rule is only an internal workaround to generate protos. The
  interface may change and the rule may be removed when bazel has introduced
  the native rule.
  Args:
    name: the name of the py_proto_library.
    srcs: the .proto files of the py_proto_library.
    deps: a list of dependency labels; must be py_proto_library.
    py_libs: a list of other py_library targets depended by the generated
        py_library.
    py_extra_srcs: extra source files that will be added to the output
        py_library. This attribute is used for internal bootstrapping.
    include: a string indicating the include path of the .proto files.
    default_runtime: the implicitly default runtime which will be depended on by
        the generated py_library target.
    protoc: the label of the protocol compiler to generate the sources.
    use_grpc_plugin: a flag to indicate whether to call the Python C++ plugin
        when processing the proto files.
    **kargs: other keyword arguments that are passed to cc_library.
  """
```

I thought I'd use this to generate Python language bindings by depending on the external repository in my WORKSPACE:

```
http_archive(
    name = "com_google_protobuf",
    urls = ["https://github.com/google/protobuf/archive/v3.4.1.zip"],
    strip_prefix = "protobuf-3.4.1",
)

```
Then in my BUILD file

```
load("@com_google_protobuf//:protobuf.bzl", "py_proto_library")

py_proto_library(
    name = "py",
    visibility = ["//visibility:public"],
    deps = [
        ":my_proto",
        "@com_google_protobuf//:protobuf_python",
    ],
)

# The proto_library rule implicitly depends on @com_google_protobuf//:protoc
proto_library(
    name = "my_proto",
    srcs = ["my.proto"],
)
```

However, the [protobuf_python](https://github.com/google/protobuf/blob/c627530946e5d8783c1d9c2bbeb1704e4e868963/BUILD#L756) library adds a list of other `py_library` targets (`"//external:six"` and `":python_srcs"`) depended by the generated code.
    
```
py_proto_library(
    name = "protobuf_python",
    srcs = COPIED_WELL_KNOWN_PROTOS,
    include = "python",
    data = select({
        "//conditions:default": [],
        ":use_fast_cpp_protos": [
            ":python/google/protobuf/internal/_api_implementation.so",
            ":python/google/protobuf/pyext/_message.so",
        ],
    }),
    default_runtime = "",
    protoc = ":protoc",
    py_libs = [
        ":python_srcs",
        "//external:six",
    ],
    srcs_version = "PY2AND3",
    visibility = ["//visibility:public"],
)
```

These dependencies cannot be resolved:

`No such target '//external:six': target 'six' not declared in package 'external'`

Is this working as intended? If so, how should [protobuf_python](https://github.com/google/protobuf/blob/c627530946e5d8783c1d9c2bbeb1704e4e868963/BUILD#L756) be used? Must these dependencies be added explicitly to my own project?

**Comment by pherl** [comment]
Please take a look at the WORKSPACE file in the protobuf directory for the external dependencies. You need to bind those targets to the same name, e.g. "six", for protobuf BUILD file to work.

**Comment by raliste** [comment]
Now giving `Caused by: java.lang.IllegalArgumentException: No such attribute testonly in new_http_archive rule //`. Any pointers?

**Comment by pherl** [comment]
How did you configure your WORKSPACE file? https://github.com/google/protobuf/blob/master/WORKSPACE#L10 there should be no "testonly" attribute.

**Comment by raliste** [comment]
There's no such `testonly` on our `WORKSPACE`

**Comment by pherl** [comment]
Is there any `testonly` in your `BUILD` files, including remote ones? I didn't find any on protobuf repo.

**Comment by pherl** [comment]
I'd suggest reproduce the error with a minimum BUILD and WORKSPACE. That will make the diagnose much easier.
