### ISSUE TITLE
Proto3 syntax not allowed in 2.6.1

### ISSUE THREAD

**Issue by dplasto** [google/protobuf#368]
When using protoc with syntax = "proto3" I'm getting the following error:

Unrecognized syntax identifier "proto3".  This parser only recognizes "proto2".

Here is the output of protoc --version:

> libprotoc 2.6.1

I've tried installing protobuf using brew, from the downloadable tarball, and also by downloading the 2.6.1 source from github. I've tried removing all other protobuf libraries on my system.

I notice the following lines of code in https://github.com/google/protobuf/blob/v2.6.1/src/google/protobuf/compiler/parser.cc

if (syntax != "proto2" && !stop_after_syntax_identifier_) {
    AddError(syntax_token.line, syntax_token.column,
      "Unrecognized syntax identifier \"" + syntax + "\".  This parser "
      "only recognizes \"proto2\".");
    return false;
  }

**Comment by cfallin** [comment]
That's an old version -- syntax "proto3" is only supported starting with 3.0.0-alpha-1.

See the release notes for more details: https://github.com/google/protobuf/releases

**Comment by yeurch** [comment]
The [C# tutorial](https://developers.google.com/protocol-buffers/docs/csharptutorial) links to the download page for 2.6.1, but the example is in proto3.  Perhaps the C# tutorial should direct users to a page where they can download the 3.0.0 prerelease version?

**Comment by Nalum** [comment]
The [Go tutorial](https://developers.google.com/protocol-buffers/docs/gotutorial#defining-your-protocol-format) also links to 2.6 download page but uses `proto3` in the examples.
