### ISSUE TITLE
Is python's google.protobuf.json_format using c++ extension?

### ISSUE THREAD

**Issue by okomarov** [google/protobuf#3680]
I have installed python protobuf with the c++ extensions:

```
>>> from google.protobuf.internal import api_implementation
>>> api_implementation._default_implementation_type
'cpp'

```

but it takes ages to process messages to json. To give an idea, the amount of data is saved as serialized string and read  in about **3 seconds**. Then, to process these messages to json takes about **2 minutes**.

**Comment by xfxyjwf** [comment]
JSON support is implemented using protobuf reflection API and it's known to be 10x to 100x slower than the generated parsing/serialization code. 2 minutes sounds slow but it may well be in the expected range of JSON parsing performance... If you have that much amount of data to process, you might want to stay with protobuf binary format.

**Comment by okomarov** [comment]
@xfxyjwf  Thanks for the reply.

In my workflow, I need to read the binary into a pandas dataframe to perform analysis. As far as I know, there is no direct way to create a dataframe without an intermediate step, and I have chose this to be a json conversion. Maybe you can suggest an alternative off the top of your mind?

Maybe you could give some pointers where to look in order to speed up the json methods?

**Comment by xfxyjwf** [comment]
The python implementation of JSON format is here:
https://github.com/google/protobuf/blob/master/python/google/protobuf/json_format.py

Feel free to send us pull requests if you have identified places to improve.

The corresponding C++ implementation is here:
https://github.com/google/protobuf/blob/master/src/google/protobuf/util/json_util.h#L83

Not sure if it's easy to hook up the C++ implementation to the python one. Also I suspect even after that it's still much slower than the proto binary parsing.
