### ISSUE TITLE
generate only client or server?

### ISSUE THREAD

**Issue by magick93** [google/protobuf#3681]
Hello

I saw that in c# its possible to use `no_server` or `no_client` as a cli arg, so that only the server or client code is generated.

Is there are similar setting for other languages?

Thanks

**Comment by anandolee** [comment]
Where did you see no_server/no_client? I can't find them in protobuf's code. 
+ Jan
Jan, do you know no_server/no_client? Are they in GPRC's plugin?

**Comment by jtattermusch** [comment]
@magick93   those options aren't part of the protobuf repository, but they are implemented in the gRPC C# plugin (gRPC provided the "service" layer over protobuf message definitions).

The `no_server` and `no_client` options are defined here:
https://github.com/grpc/grpc/blob/e759d2ad7abdb0702970eeccc5f033ff4b2a4c7f/src/compiler/csharp_plugin.cc#L43
They only seem to be available for C# (feel free to investigate the source code of other plugins in the same directory yourself).
