### ISSUE TITLE
Missing binaries for release 3.4.1

### ISSUE THREAD

**Issue by ChristianSchwarz** [google/protobuf#3683]
Seems like there are no binary zips are available for this version.

https://github.com/google/protobuf/releases/tag/v3.4.1

**Comment by pherl** [comment]
Usually we just tag micro releases without uploading tarbals. 3.4.1 was special because it fixed the missing files in the runtime tarballs.  Micro release also typically doesn't change protoc so you can just use the 3.4 compiler with 3.4.1 runtime.
