### ISSUE TITLE
Release v3.4.1 "make check" fails

### ISSUE THREAD

**Issue by ww9rivers** [google/protobuf#3685]
Got this on Rasbian (Debian 7):
`g++ -DHAVE_CONFIG_H -I. -I..  -I./../gmock/gtest/include -I./../gmock/include  -pthread -DHAVE_PTHREAD=1 -DHAVE_ZLIB=1 -Wall -Wno-sign-compare -g -DNDEBUG -MT google/protobuf/testing/protobuf_test-file.o -MD -MP -MF google/protobuf/testing/.deps/protobuf_test-file.Tpo -c -o google/protobuf/testing/protobuf_test-file.o `test -f 'google/protobuf/testing/file.cc' || echo './'`google/protobuf/testing/file.cc`
`google/protobuf/testing/file.cc: In static member function ?static bool google::protobuf::File::CreateDir(const string&, int)?:`
`google/protobuf/testing/file.cc:124:5: error: ?const string? has no member named ?back?`
`Makefile:7166: recipe for target 'google/protobuf/testing/protobuf_test-file.o' failed`

**Comment by pherl** [comment]
Should be fixed in #3691
