### ISSUE TITLE
GOOGLE_ATTRIBUTE_ALWAYS_INLINE is incorrectly implemented

### ISSUE THREAD

**Issue by abaldeva** [google/protobuf#3692]
Currently, in port.h
```
#if defined(__GNUC__) && (__GNUC__ > 3 ||(__GNUC__ == 3 && __GNUC_MINOR__ >= 1))
// For functions we want to force inline.
// Introduced in gcc 3.1.
#define GOOGLE_ATTRIBUTE_ALWAYS_INLINE __attribute__ ((always_inline))
```
which is then used in the wire_format_lite.h as

`#define INL GOOGLE_PROTOBUF_ATTRIBUTE_ALWAYS_INLINE`

Note that gcc specifies that just putting always_inline attribute is not enough. It should be preceded by the 'inline' keyword. Based on a combination of things (include order etc.), it showed up as an error on CentOS 6/ gcc 4.8

See the signature from this https://gcc.gnu.org/onlinedocs/gcc/Inline.html 
`inline void foo (const char) __attribute__((always_inline));`
Also, a similar bug in another project - https://github.com/rogerclarkmelbourne/Arduino_STM32/issues/54

**Comment by pherl** [comment]
The INL usages are for declaration, the definition will have the inline keyword (in wire_format_lite_inl.h). I think this falls into this category `when a function is first declared without using the inline keyword and then is defined with inline`

Even if the attribute is ignored, it shouldn't be an error. I suspect you miss the include on the wire_format_line_inl.h in which those functions are actually defined.

**Comment by abaldeva** [comment]
ah, I have not seen this usage pattern (declaring non-line and defining inline). After I changed my includes from wire_format_lite.h to wire_format_lite_inl.h, the problem went away. 

Thanks.
