### ISSUE TITLE
Build C++ gRPC helloworld client/server using protobuf-lite

### ISSUE THREAD

**Issue by nandansr** [google/protobuf#3694]
Hi,

Tried to build gRPC helloworld (grpc/examples/cpp/helloworld) using protobuf-lite.  I get the below error if I just try to use protobuf-lite during the linking time.

`In file included from /opt/grpc/include/grpc++/impl/codegen/async_stream.h:22:0,
                 from helloworld.grpc.pb.h:24,
                 from helloworld.grpc.pb.cc:6:
/opt/grpc/include/grpc++/impl/codegen/call.h: In instantiation of ‘grpc::Status grpc::CallOpSendMessage::SendMessage(const M&, grpc::WriteOptions) [with M = helloworld::HelloRequest]’:
/opt/grpc/include/grpc++/impl/codegen/call.h:299:45:   required from ‘grpc::Status grpc::CallOpSendMessage::SendMessage(const M&) [with M = helloworld::HelloRequest]’
/opt/grpc/include/grpc++/impl/codegen/client_unary_call.h:48:42:   required from ‘grpc::Status grpc::BlockingUnaryCall(grpc::ChannelInterface*, const grpc::RpcMethod&, grpc::ClientContext*, const InputMessage&, OutputMessage*) [with InputMessage = helloworld::HelloRequest; OutputMessage = helloworld::HelloReply]’
helloworld.grpc.pb.cc:32:99:   required from here
/opt/grpc/include/grpc++/impl/codegen/call.h:294:43: error: incomplete type ‘grpc::SerializationTraits<helloworld::HelloRequest, void>’ used in nested name specifier
   return SerializationTraits<M>::Serialize(message, &send_buf_, &own_buf_);`

From one of the issues, I saw that we should compile gRPC first to use protobuf-lite by adding the macro  "GRPC_USE_PROTO_LITE" in Makefile. Added this macro and built the gRPC successfully.

`CXXFLAGS += -DGRPC_USE_PROTO_LITE
CPPFLAGS += -DGRPC_USE_PROTO_LITE
CFLAGS += -DGRPC_USE_PROTO_LITE
`

Still getting error during build.

`
$/grpc/examples/cpp/helloworld# g++ -std=c++11 -I/usr/local/include helloworld.pb.cc helloworld.grpc.pb.cc greeter_server.cc -o greeter_server /opt/grpc/libs/opt/libgrpc++_unsecure.a  /usr/local/lib/libgrpc.a  /usr/local/lib/libprotobuf.a -lpthread  -fno-exceptions -flto -s
/usr/local/lib/libgrpc.a(message_compress.o):(.text+0x422): undefined reference to `deflateInit2_'
/usr/local/lib/libgrpc.a(message_compress.o):(.text+0x437): undefined reference to `deflate'
/usr/local/lib/libgrpc.a(message_compress.o):(.text+0x4b6): undefined reference to `deflateEnd'
/usr/local/lib/libgrpc.a(message_compress.o):(.text+0x5b1): undefined reference to `inflateInit2_'
/usr/local/lib/libgrpc.a(message_compress.o):(.text+0x5c0): undefined reference to `inflate'
/usr/local/lib/libgrpc.a(message_compress.o):(.text+0x636): undefined reference to `inflateEnd'
/usr/local/lib/libgrpc.a(stream_compression.o):(.text+0x68): undefined reference to `inflate'
/usr/local/lib/libgrpc.a(stream_compression.o):(.text+0x293): undefined reference to `inflate'
/usr/local/lib/libgrpc.a(stream_compression.o): In function `grpc_stream_compress':
(.text+0x647): undefined reference to `deflate'
/usr/local/lib/libgrpc.a(stream_compression.o): In function `grpc_stream_decompress':
(.text+0x6b7): undefined reference to `inflate'
/usr/local/lib/libgrpc.a(stream_compression.o): In function `grpc_stream_compression_context_create':
(.text+0x759): undefined reference to `deflateInit2_'
/usr/local/lib/libgrpc.a(stream_compression.o): In function `grpc_stream_compression_context_create':
(.text+0x760): undefined reference to `deflate'
/usr/local/lib/libgrpc.a(stream_compression.o): In function `grpc_stream_compression_context_create':
(.text+0x795): undefined reference to `inflateInit2_'
/usr/local/lib/libgrpc.a(stream_compression.o): In function `grpc_stream_compression_context_create':
(.text+0x79c): undefined reference to `inflate'
/usr/local/lib/libgrpc.a(stream_compression.o): In function `grpc_stream_compression_context_destroy':
(.text+0x7d4): undefined reference to `inflate'
/usr/local/lib/libgrpc.a(stream_compression.o): In function `grpc_stream_compression_context_destroy':
(.text+0x7e2): undefined reference to `deflateEnd'
/usr/local/lib/libgrpc.a(stream_compression.o): In function `grpc_stream_compression_context_destroy':
(.text+0x7f1): undefined reference to `inflateEnd'
collect2: error: ld returned 1 exit status
`

Please share if someone able to use protobuf-lite in C++

**Comment by pherl** [comment]
Could you file this in the grpc issue list instead? It's probably a problem of using the correct flags/commandlines.

**Comment by arajeeva** [comment]
@liujisi I am running into similar issue (https://github.com/grpc/grpc/issues/15604) when trying to use GRPC with protobuf-lite? I am currently using GRPC_USE_PROTO_LITE=true to build GRPC with protobuf-lite. Are there other options that needs to be enabled?
