### ISSUE TITLE
protobuf vs json

### ISSUE THREAD

**Issue by CoXier** [google/protobuf#3705]
From protocol buffer doc, I learn  `xml` vs `pb`. 

> refer : https://developers.google.com/protocol-buffers/docs/overview#whynotxml

But I have not leaned about `json` vs `pb` yet. Can you provide some material?

**Comment by pherl** [comment]
We don't have a doc about comparison with json. But the basic arguments between binary format and text format are the similar: the performance difference is still orders of magnitude; it's type safe to access in programming languges, etc.
