### ISSUE TITLE
NettyServerBuilder difference between executor() and workerEventLoopGroup()

### ISSUE THREAD

**Issue by noguespi** [google/protobuf#3713]
What is the difference between setting an executor(Threadpool) and setting a workerEventLoopGroup(EventLoopThreadPool) on NettyServerBuilder.

If I understand, all the IO operations (accept connexions, read/send packet...) are done by the boosEventLoopGroup thread. 

But what about the RPC call themself ? Are they done by executor threadpool or workerEventLoop ?

**Comment by xfxyjwf** [comment]
I think this issue is about a different project.

**Comment by noguespi** [comment]
indeed, it was about grpc-java https://github.com/grpc/grpc-java/issues/3536 . sorry about that :/
