### ISSUE TITLE
protoc-3.1.0 for linux-x86.64 is linked to GLIBC2.14

### ISSUE THREAD

**Issue by fhermeni** [google/protobuf#3718]
Hi

Having pre-compiled binaries for protoc inside the maven repository is awesome and simplified my daily life. However, some of the machines I am using to compile the proto files are using a GLIBC 2.12. so the compilation fails in that context and I have to go back to some maven gymnastic to make everything fine.

Would it be possible to have protoc statically linked to prevent that situation ?

**Comment by pherl** [comment]
Hmm, I thought we were already static linking those libraries. Would you mind take a look at the build script make changes if necessary? https://github.com/google/protobuf/blob/master/protoc-artifacts/build-protoc.sh

**Comment by madrob** [comment]
This was moderately educational for me: https://stackoverflow.com/questions/26304531/compiling-with-static-libgcc-static-libstdc-still-results-in-dynamic-depende and might provide hints to why static linking isn't working when we expect it to.

**Comment by acozzette** [comment]
This is now fixed in 3.6.0. (We haven't really announced that release yet because we're still working on publishing some artifacts, but at least the protoc binaries are ready to go.)
