### ISSUE TITLE
Grpc enum parse to json error when enum value = 0

### ISSUE THREAD

**Issue by santatic** [google/protobuf#3719]
I got a error when parse special gRPC enum value = 0 to json.

```java
public enum Status implements ProtocolMessageEnum {
  ACTIVE(0),
  SUSPENDED(1),
  UNRECOGNIZED(-1);
}
```
I parse to json with default options

```java
String json = JsonFormat.printer().print(message);
```

When enum status was `SUSPENDED`, I got json with status is `SUSPENDED` string
But when status was `ACTIVE`, I lost status field in json.

I think that problem is `ACTIVE` has value is `0` and parser was confuse this case.

**Comment by pherl** [comment]
In proto3, the default values are not serialized for primitive fields. However, you can set the option to always print default values, like:

```java
String json = JsonFormat.printer().includingDefaultValueFields().print(message);
```

**Comment by santatic** [comment]
Thank you, It works well in my case.
