### ISSUE TITLE
(JAVA) Send custom bytes with request

### ISSUE THREAD

**Issue by publicD3vRepository** [google/protobuf#3727]
hi all,
I need to modify my message request.

// Example
message Test {
  required int32 a = 1;
}
set a to 150 -> 08 96 01 (encoded)
size 3 bytes = 33(encoded)

i want to send request like this   33 08 96 01

service MyService {
rpc send (Test) returns (SomeReponse){}
}
 i tried ClientInterceptor, but i cant modify request from 08 96 01  -> 33 08 96 01

i tried send bytes
message Wrapper {
    bytes byte = 1;
}
This will encode again 0A 03  33 08 96 01

i need something like 
service MyService {
rpc send (ByteString) returns (SomeReponse){}
}

i want to send custom encoded structure.

Any ideas?

**Comment by xfxyjwf** [comment]
Note that protobuf doesn't support sending bytes over the network. You need to use a rpc library like grpc to send the data.
