### ISSUE TITLE
Unable to build protobuf on AIX with xlC 

### ISSUE THREAD

**Issue by varun85gupta** [google/protobuf#3730]
I am trying to build protobuf on AIX 7.1 using xlC and xlc compilers but configure fails to detect sched_yield on the system which is present. I checked it using man page for sched_yield

```
./configure CXX=xlC CC=xlc CPPFLAGS="-I/usr/vac/include"
checking whether to enable maintainer-specific portions of Makefiles... yes
checking build system type... powerpc-ibm-aix7.1.0.0
checking host system type... powerpc-ibm-aix7.1.0.0
checking target system type... powerpc-ibm-aix7.1.0.0
checking for a BSD-compatible install... ./install-sh -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... ./install-sh -c -d
checking for gawk... no
checking for mawk... no
checking for nawk... nawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether UID '9000' is supported by ustar format... yes
checking whether GID '100' is supported by ustar format... yes
checking how to create a ustar tar archive... plaintar
checking for gcc... xlc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... no
checking whether xlc accepts -g... yes
checking for xlc option to accept ISO C89... none needed
checking whether xlc understands -c and -o together... yes
checking for style of include used by make... GNU
checking dependency style of xlc... xlc
checking whether we are using the GNU C++ compiler... no
checking whether xlC accepts -g... yes
checking dependency style of xlC... xlc
checking how to run the C preprocessor... xlc -E
checking for gcc... gcc
checking whether we are using the GNU C compiler... (cached) no
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... (cached) none needed
checking whether gcc understands -c and -o together... (cached) yes
checking dependency style of gcc... (cached) xlc
checking how to run the C preprocessor... gcc -E
checking how to run the C++ preprocessor... xlC -E
checking for g++... g++
checking whether we are using the GNU C++ compiler... (cached) no
checking whether g++ accepts -g... yes
checking dependency style of g++... (cached) xlc
checking how to run the C++ preprocessor... g++ -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking minix/config.h usability... no
checking minix/config.h presence... no
checking for minix/config.h... no
checking whether it is safe to define __EXTENSIONS__... yes
checking for ar... ar
checking the archiver (ar) interface... ar
checking for gcc... gcc
checking whether we are using the GNU Objective C compiler... no
checking whether gcc accepts -g... no
checking dependency style of gcc... gcc3
checking C++ compiler flags...... use default:   -DNDEBUG
checking whether __SUNPRO_CC is declared... no
checking how to print strings... print -r
checking for a sed that does not truncate output... /usr/bin/sed
checking for fgrep... /usr/bin/grep -F
checking for non-GNU ld... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... no
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 786432
checking whether the shell understands some XSI constructs... yes
checking whether the shell understands "+="... no
checking how to convert powerpc-ibm-aix7.1.0.0 file names to powerpc-ibm-aix7.1.0.0 format... func_convert_file_noop
checking how to convert powerpc-ibm-aix7.1.0.0 file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... no
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... print -r --
checking for archiver @FILE support... no
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from xlc object... ok
checking for sysroot... no
checking for mt... mt
checking if mt is a manifest tool... no
checking for dlfcn.h... yes
checking for objdir... .libs
checking for xlc option to produce PIC...  -DPIC
checking if xlc PIC flag  -DPIC works... yes
checking if xlc static flag -bnso -bI:/lib/syscalls.exp works... no
checking if xlc supports -c -o file.o... yes
checking if xlc supports -c -o file.o... (cached) yes
checking whether the xlc linker (/usr/bin/ld) supports shared libraries... yes
checking dynamic linker characteristics... aix7.1.0.0 ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... no
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no
checking how to run the C++ preprocessor... xlC -E
checking whether the xlC linker (/usr/bin/ld) supports shared libraries... yes
checking for xlC option to produce PIC...  -DPIC
checking if xlC PIC flag  -DPIC works... yes
checking if xlC static flag -bnso -bI:/lib/syscalls.exp works... no
checking if xlC supports -c -o file.o... yes
checking if xlC supports -c -o file.o... (cached) yes
checking whether the xlC linker (/usr/bin/ld) supports shared libraries... yes
checking dynamic linker characteristics... aix7.1.0.0 ld.so
checking how to hardcode library paths into programs... immediate
checking whether the linker supports version scripts... no
checking for ANSI C header files... (cached) yes
checking fcntl.h usability... yes
checking fcntl.h presence... yes
checking for fcntl.h... yes
checking for inttypes.h... (cached) yes
checking limits.h usability... yes
checking limits.h presence... yes
checking for limits.h... yes
checking for stdlib.h... (cached) yes
checking for unistd.h... (cached) yes
checking for working memcmp... yes
checking for working strtod... yes
checking for ftruncate... yes
checking for memset... yes
checking for mkdir... yes
checking for strchr... yes
checking for strerror... yes
checking for strtol... yes
checking zlib version... headers missing or too old (requires 1.2.0.4)
checking for the pthreads library -lpthreads... yes
checking for joinable pthread attribute... PTHREAD_CREATE_JOINABLE
checking if more special flags are required for pthreads... -D_THREAD_SAFE
checking for xlc_r... xlc_r
checking whether to check for GCC pthread/shared inconsistencies... no
checking whether what we have so far is sufficient with -nostdlib... no
checking whether -lpthread saves the day... no
configure: WARNING: Impossible to determine how to use pthreads with shared libraries and -nostdlib
checking the location of hash_map...
configure: WARNING: could not find an STL hash_map
checking for library containing sched_yield... no
configure: error: in `/usr/u/qaunix/protobuf-3.4.1':
configure: error: sched_yield was not found on your system
See `config.log' for more details
```

In config.log 
```
configure:19229: checking for library containing sched_yield
configure:19260: xlC -o conftest  -DNDEBUG -I/usr/vac/include  conftest.cpp  >&5
"/usr/include/sys/atomic_op.h", line 123.9: 1540-1411 (W) "pragma mc_func" must be specified in global scope. The pragma is ignored.
"/usr/include/sys/atomic_op.h", line 126.9: 1540-1411 (W) "pragma mc_func" must be specified in global scope. The pragma is ignored.
"/usr/include/sys/atomic_op.h", line 129.9: 1540-1411 (W) "pragma mc_func" must be specified in global scope. The pragma is ignored.
"/usr/include/sys/atomic_op.h", line 132.9: 1540-1411 (W) "pragma mc_func" must be specified in global scope. The pragma is ignored.
"/usr/include/sys/types.h", line 43.12: 1540-0063 (S) The text "{" is unexpected.
"/usr/include/sys/sched.h", line 77.51: 1540-0064 (S) Syntax error:  "(" was expected but "*" was found.
"/usr/include/sys/sched.h", line 79.55: 1540-0064 (S) Syntax error:  "(" was expected but "*" was found.
"/usr/include/sys/sched.h", line 80.57: 1540-0064 (S) Syntax error:  "(" was expected but "*" was found.
"/usr/include/sys/sched.h", line 81.39: 1540-0064 (S) Syntax error:  "(" was expected but "," was found.
"/usr/include/time.h", line 137.25: 1540-0040 (S) The text "strftime" is unexpected.  "size_t" may be undeclared or ambiguous.
"/usr/include/time.h", line 138.25: 1540-0040 (S) The text "clock" is unexpected.  "clock_t" may be undeclared or ambiguous.
"/usr/include/time.h", line 140.25: 1540-0040 (S) The text "mktime" is unexpected.  "time_t" may be undeclared or ambiguous.
"/usr/include/time.h", line 142.25: 1540-0040 (S) The text "time" is unexpected.  "time_t" may be undeclared or ambiguous.
"/usr/include/time.h", line 145.45: 1540-0040 (S) The text "*" is unexpected.  "time_t" may be undeclared or ambiguous.
"/usr/include/time.h", line 146.43: 1540-0040 (S) The text "*" is unexpected.  "time_t" may be undeclared or ambiguous.
"/usr/include/time.h", line 147.46: 1540-0040 (S) The text "*" is unexpected.  "time_t" may be undeclared or ambiguous.
"/usr/include/time.h", line 158.47: 1540-0040 (S) The text "*" is unexpected.  "time_t" may be undeclared or ambiguous.
"/usr/include/time.h", line 159.48: 1540-0040 (S) The text "*" is unexpected.  "time_t" may be undeclared or ambiguous.
"/usr/include/time.h", line 160.51: 1540-0040 (S) The text "*" is unexpected.  "time_t" may be undeclared or ambiguous.
"/usr/include/time.h", line 230.22: 1540-1118 (S) The declaration of "it_interval" uses the undefined class "timespec" when the class must be complete.
"/usr/include/time.h", line 240.52: 1540-0064 (S) Syntax error:  "(" was expected but "*" was found.
"/usr/include/time.h", line 241.53: 1540-0064 (S) Syntax error:  "(" was expected but "*" was found.
"/usr/include/time.h", line 242.59: 1540-0064 (S) Syntax error:  "(" was expected but "*" was found.
"/usr/include/time.h", line 243.50: 1540-0063 (S) The text ")" is unexpected.
"/usr/include/time.h", line 248.41: 1540-0064 (S) Syntax error:  "(" was expected but "*" was found.
"/usr/include/time.h", line 251.53: 1540-0064 (S) Syntax error:  "(" was expected but "*" was found.
"/usr/include/time.h", line 253.38: 1540-0064 (S) Syntax error:  "(" was expected but "," was found.
"/usr/include/time.h", line 257.42: 1540-0064 (S) Syntax error:  "(" was expected but "," was found.
"/usr/include/time.h", line 275.36: 1540-0063 (S) The text "size_t" is unexpected.
"/usr/include/time.h", line 296.41: 1540-0040 (S) The text "*" is unexpected.  "time64_t" may be undeclared or ambiguous.
"/usr/include/time.h", line 297.50: 1540-0040 (S) The text "*" is unexpected.  "time64_t" may be undeclared or ambiguous.
"/usr/include/time.h", line 298.47: 1540-0040 (S) The text "*" is unexpected.  "time64_t" may be undeclared or ambiguous.
"/usr/include/time.h", line 300.21: 1540-0040 (S) The text "mktime64" is unexpected.  "time64_t" may be undeclared or ambiguous.
"/usr/include/time.h", line 302.21: 1540-0040 (S) The text "time64" is unexpected.  "time64_t" may be undeclared or ambiguous.
"/usr/include/time.h", line 304.43: 1540-0040 (S) The text "*" is unexpected.  "time64_t" may be undeclared or ambiguous.
"/usr/include/time.h", line 305.52: 1540-0040 (S) The text "*" is unexpected.  "time64_t" may be undeclared or ambiguous.
"/usr/include/time.h", line 307.49: 1540-0040 (S) The text "*" is unexpected.  "time64_t" may be undeclared or ambiguous.
"/usr/include/sys/sched.h", line 78.29: 1540-0274 (S) The name lookup for "pid_t" did not find a declaration.
"/usr/include/time.h", line 139.34: 1540-0274 (S) The name lookup for "time_t" did not find a declaration.
"/usr/include/time.h", line 250.25: 1540-0274 (S) The name lookup for "timer_t" did not find a declaration.
"/usr/include/time.h", line 252.29: 1540-0274 (S) The name lookup for "timer_t" did not find a declaration.
"/usr/include/time.h", line 301.30: 1540-0274 (S) The name lookup for "time64_t" did not find a declaration.
configure:19260: $? = 1

```

**Comment by pherl** [comment]
Sorry I don't have a machine to test those out. But would be happy to accept PRs

If there's no sched_yield on your system, you would probably have to:
- change SchedYeield() function in src/google/protobuf/stubs/once.cc by adding #ifdef on your platform and use some other equivalent syscalls.
- change configure.ac to skip the sched_yield library check for your platform.

**Comment by pherl** [comment]
sched_yield is part of POSIX and it seems AIX does support it on the standard c library: https://www.ibm.com/support/knowledgecenter/en/ssw_aix_71/com.ibm.aix.basetrf2/sched_yield.htm

**Comment by pherl** [comment]
Oops, sorry I misread your description.. In that case, simply whitelist your platform in the configure.ac should work. sched_yield seems to be part of libc in AIX.

**Comment by varun85gupta** [comment]
Can you specify how to do that ? I tried to find in configure.ac to whitelist, but couldn't .

**Comment by varun85gupta** [comment]
After some workarounds, I have been able to overcome the sched_yield problem. But Now I face more compilation issues. 

I removed the extern declaration from configure file and updated the check to this : 

#include <sys/sched.h>
int
main ()
{
return sched_yield ();
  ;
  return 0;
}

After that I was able to generate makefiles using :

`./configure CC=xlc_r CXX=xlC_r CXXFLAGS="-qtls"
`
Then I again faced some issues like this:

```
"./google/protobuf/wire_format_lite_inl.h", line 708.10: 1540-0290 (S) The function template parameter "T" has been found to have two values: "int" and "const google::protobuf::RepeatedField<int> &".
"./google/protobuf/wire_format_lite_inl.h", line 712.10: 1540-0290 (S) The function template parameter "T" has been found to have two values: "long long" and "const google::protobuf::RepeatedField<long long> &".
"./google/protobuf/wire_format_lite_inl.h", line 716.10: 1540-0290 (S) The function template parameter "T" has been found to have two values: "unsigned int" and "const google::protobuf::RepeatedField<unsigned int> &".
"./google/protobuf/wire_format_lite_inl.h", line 720.10: 1540-0290 (S) The function template parameter "T" has been found to have two values: "unsigned long long" and "const google::protobuf::RepeatedField<unsigned long long> &".
"./google/protobuf/wire_format_lite_inl.h", line 724.10: 1540-0290 (S) The function template parameter "T" has been found to have two values: "int" and "const google::protobuf::RepeatedField<int> &".
```

I solved it using explicit template parameters :

inline uint8* WireFormatLite::WriteEnumToArray(
    int field_number, const RepeatedField<   int>& value, uint8* target) {
  return WritePrimitiveToArray**<int>**(field_number, value, WriteEnumToArray, target);
}

Now I am facing more issues : 

```
"./google/protobuf/type.pb.h", line 340.3: 1540-1113 (S) The class template name "InternalHelper" must be followed by a < in this context.
"./google/protobuf/type.pb.h", line 651.25: 1540-1113 (S) The class template name "InternalHelper" must be followed by a < in this context.
"./google/protobuf/type.pb.h", line 829.25: 1540-1113 (S) The class template name "InternalHelper" must be followed by a < in this context.
"./google/protobuf/type.pb.h", line 974.25: 1540-1113 (S) The class template name "InternalHelper" must be followed by a < in this context.
"./google/protobuf/type.pb.h", line 1115.25: 1540-1113 (S) The class template name "InternalHelper" must be followed by a < in this context.
"google/protobuf/api.pb.cc", line 456.23: 1540-0256 (S) A parameter of type "const google::protobuf::MessageLite &" cannot be initialized with an expression of type "const google::protobuf::Option".
"google/protobuf/api.pb.cc", line 456.23: 1540-1205 (I) The error occurred while converting to parameter 2 of "google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(int, const MessageLite &, io::CodedOutputStream *)".
"google/protobuf/api.pb.cc", line 1268.23: 1540-0256 (S) A parameter of type "const google::protobuf::MessageLite &" cannot be initialized with an expression of type "const google::protobuf::Option".
"google/protobuf/api.pb.cc", line 1268.23: 1540-1205 (I) The error occurred while converting to parameter 2 of "google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(int, const MessageLite &, io::CodedOutputStream *)".
"./google/protobuf/generated_message_reflection.h", line 699.10: 1540-2411 (W) A dynamic cast is present, but the correct RTTI option is not specified.
"./google/protobuf/generated_message_reflection.h", line 682.4: 1540-0700 (I) The previous message was produced while processing "google::protobuf::internal::DynamicCastToGenerated<const google::protobuf::Api>(const Message *)".
"google/protobuf/api.pb.cc", line 649.7: 1540-0700 (I) The previous message was produced while processing "google::protobuf::Api::MergeFrom(const Message &)".
"./google/protobuf/type.pb.h", line 203.6: 1540-0251 (S) The "." operator cannot be applied to the undefined class "class Type".
"./google/protobuf/type.pb.h", line 399.6: 1540-0251 (S) The "." operator cannot be applied to the undefined class "class Field".
"./google/protobuf/type.pb.h", line 714.6: 1540-0251 (S) The "." operator cannot be applied to the undefined class "class Enum".
"./google/protobuf/type.pb.h", line 887.6: 1540-0251 (S) The "." operator cannot be applied to the undefined class "class EnumValue".
"./google/protobuf/type.pb.h", line 1030.6: 1540-0251 (S) The "." operator cannot be applied to the undefined class "class Option".
make: The error code from the last command is 1.
```

**Comment by alikhanafer** [comment]
Currently facing exact same issues on AIX 7.2. Applied same fix to the template error as suggested by @varun85gupta, and now getting similar errors:

source='google/protobuf/api.pb.cc' object='google/protobuf/api.pb.lo' libtool=yes \
DEPDIR=.deps depmode=xlc /bin/sh ../depcomp \
/bin/sh ../libtool  --tag=CXX   --mode=compile xlC -DHAVE_CONFIG_H -I. -I..    -D_THREAD_SAFE  -DHAVE_PTHREAD=1  -Wall -Wno-sign-compare -O2 -g -DNDEBUG -c -o google/protobuf/api.pb.lo google/protobuf/api.pb.cc
libtool: compile:  xlC -DHAVE_CONFIG_H -I. -I.. -D_THREAD_SAFE -DHAVE_PTHREAD=1 -Wall -Wno-sign-compare -O2 -g -DNDEBUG -c google/protobuf/api.pb.cc -Wp,-qmakedep=gcc,-MFgoogle/protobuf/.deps/api.pb.TPlo  -DPIC -o google/protobuf/.libs/api.pb.o
/opt/IBM/xlC/13.1.3/bin/.orig/xlC: 1501-289 (W) Option -Wall was incorrectly specified. The option will be ignored.
/opt/IBM/xlC/13.1.3/bin/.orig/xlC: 1501-289 (W) Option -Wno-sign-compare was incorrectly specified. The option will be ignored.
"./google/protobuf/type.pb.h", line 370.25: 1540-1113 (S) The class template name "InternalHelper" must be followed by a < in this context.
"./google/protobuf/type.pb.h", line 711.25: 1540-1113 (S) The class template name "InternalHelper" must be followed by a < in this context.
"./google/protobuf/type.pb.h", line 897.25: 1540-1113 (S) The class template name "InternalHelper" must be followed by a < in this context.
"./google/protobuf/type.pb.h", line 1054.25: 1540-1113 (S) The class template name "InternalHelper" must be followed by a < in this context.
"./google/protobuf/type.pb.h", line 1203.25: 1540-1113 (S) The class template name "InternalHelper" must be followed by a < in this context.
"google/protobuf/api.pb.cc", line 377.35: 1540-0256 (S) A parameter of type "google::protobuf::MessageLite *" cannot be initialized with an expression of type "google::protobuf::Option *".
"google/protobuf/api.pb.cc", line 377.35: 1540-1205 (I) The error occurred while converting to parameter 2 of "google::protobuf::internal::WireFormatLite::ReadMessage(io::CodedInputStream *, MessageLite *)".
"google/protobuf/api.pb.cc", line 489.20: 1540-0256 (S) A parameter of type "const google::protobuf::MessageLite &" cannot be initialized with an expression of type "const google::protobuf::Option".
"google/protobuf/api.pb.cc", line 489.20: 1540-1205 (I) The error occurred while converting to parameter 2 of "google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(int, const MessageLite &, io::CodedOutputStream *)".
"google/protobuf/api.pb.cc", line 562.25: 1540-0256 (S) A parameter of type "const google::protobuf::MessageLite &" cannot be initialized with an expression of type "const google::protobuf::Option".
"google/protobuf/api.pb.cc", line 562.25: 1540-1205 (I) The error occurred while converting to parameter 2 of "google::protobuf::internal::WireFormatLite::InternalWriteMessageToArray(int, const MessageLite &, bool, uint8 *)".
"google/protobuf/api.pb.cc", line 632.24: 1540-0256 (S) A parameter of type "const google::protobuf::MessageLite &" cannot be initialized with an expression of type "const google::protobuf::Option".
"google/protobuf/api.pb.cc", line 632.24: 1540-1205 (I) The error occurred while converting to parameter 1 of "google::protobuf::internal::WireFormatLite::MessageSize(const MessageLite &)".
"google/protobuf/api.pb.cc", line 956.35: 1540-0256 (S) A parameter of type "google::protobuf::MessageLite *" cannot be initialized with an expression of type "google::protobuf::Option *".
"google/protobuf/api.pb.cc", line 956.35: 1540-1205 (I) The error occurred while converting to parameter 2 of "google::protobuf::internal::WireFormatLite::ReadMessage(io::CodedInputStream *, MessageLite *)".
"google/protobuf/api.pb.cc", line 1049.20: 1540-0256 (S) A parameter of type "const google::protobuf::MessageLite &" cannot be initialized with an expression of type "const google::protobuf::Option".
"google/protobuf/api.pb.cc", line 1049.20: 1540-1205 (I) The error occurred while converting to parameter 2 of "google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(int, const MessageLite &, io::CodedOutputStream *)".
"google/protobuf/api.pb.cc", line 1121.25: 1540-0256 (S) A parameter of type "const google::protobuf::MessageLite &" cannot be initialized with an expression of type "const google::protobuf::Option".
"google/protobuf/api.pb.cc", line 1121.25: 1540-1205 (I) The error occurred while converting to parameter 2 of "google::protobuf::internal::WireFormatLite::InternalWriteMessageToArray(int, const MessageLite &, bool, uint8 *)".
"google/protobuf/api.pb.cc", line 1154.24: 1540-0256 (S) A parameter of type "const google::protobuf::MessageLite &" cannot be initialized with an expression of type "const google::protobuf::Option".
"google/protobuf/api.pb.cc", line 1154.24: 1540-1205 (I) The error occurred while converting to parameter 1 of "google::protobuf::internal::WireFormatLite::MessageSize(const MessageLite &)".
"./google/protobuf/generated_message_reflection.h", line 694.10: 1540-2411 (W) A dynamic cast is present, but the correct RTTI option is not specified.
"./google/protobuf/generated_message_reflection.h", line 678.4: 1540-0700 (I) The previous message was produced while processing "google::protobuf::internal::DynamicCastToGenerated<const google::protobuf::Api>(const Message *)".
"google/protobuf/api.pb.cc", line 685.7: 1540-0700 (I) The previous message was produced while processing "google::protobuf::Api::MergeFrom(const Message &)".
"./google/protobuf/type.pb.h", line 227.6: 1540-0251 (S) The "." operator cannot be applied to the undefined class "class Type".
"./google/protobuf/type.pb.h", line 431.6: 1540-0251 (S) The "." operator cannot be applied to the undefined class "class Field".
"./google/protobuf/type.pb.h", line 776.6: 1540-0251 (S) The "." operator cannot be applied to the undefined class "class Enum".
"./google/protobuf/type.pb.h", line 957.6: 1540-0251 (S) The "." operator cannot be applied to the undefined class "class EnumValue".
"./google/protobuf/type.pb.h", line 1112.6: 1540-0251 (S) The "." operator cannot be applied to the undefined class "class Option".

**Comment by acozzette** [comment]
It's hard to tell what exactly the problem is, but if you can figure it out and write a fix then feel free to send us a pull request.

**Comment by abula** [comment]
Below code doesn't work on AIX xlC, that's why we met the "InternalHelper" error.
class A{
template <typename T> class B{ void print(T i) {;} };
 };

class C{
template <typename T>  friend class A::B;
};

**Comment by abula** [comment]
Below code doesn't work on AIX xlC. That's why we met the "InternalHelper" issue.  Anyone has any progess?  Thanks.
class A{
template <typename T> class B{ void print(T i) {;} };
 };
class C{
template <typename T>  friend class A::B;
};

**Comment by abula** [comment]
Below code doesn't work on AIX xlC. That's why we met the "InternalHelper" issue. Anyone has any progess? Thanks.
`
class A{
template <typename T> class B{ void print(T i) {;} };
 };

class C{
template <typename T>  friend class A::B;
}; `

**Comment by abula** [comment]
Below code doesn't work on AIX xlC. That's why we met this InternalHelper issue.
```
class A{
template <typename T> class B{ void print(T i) {;} };
 };

class C{
template <typename T>  friend class A::B;
}; 
```

**Comment by abula** [comment]
To workaround this on AIX, change the code to:
```
class A{
template <typename T> class B{ void print(T i) {;} };
 };

class C{
template <> friend class A::B<int>;
}; 
```

**Comment by sbielasiak** [comment]
I am attempting to build protobuf v 3.5.0 on AIX 7 and seeing the same issues.  Has this ever been resolved?

**Comment by rahulsharma9595** [comment]
I am also trying to build v3.5.0 on AIX7.1 and getting the similar issue.
It would be very helpful if someone could share how to resolve it.

Below is the error I am getting.
"./google/protobuf/type.pb.h", line 362.25: 1540-1113 (S) The class template name "InternalHelper" must be followed by a < in this context.
"./google/protobuf/type.pb.h", line 699.25: 1540-1113 (S) The class template name "InternalHelper" must be followed by a < in this context.
"./google/protobuf/type.pb.h", line 884.25: 1540-1113 (S) The class template name "InternalHelper" must be followed by a < in this context.
"./google/protobuf/type.pb.h", line 1037.25: 1540-1113 (S) The class template name "InternalHelper" must be followed by a < in this context.
"./google/protobuf/type.pb.h", line 1185.25: 1540-1113 (S) The class template name "InternalHelper" must be followed by a < in this context.
"./google/protobuf/generated_message_reflection.h", line 698.10: 1540-2411 (W) A dynamic cast is present, but the correct RTTI option is not specified.
"./google/protobuf/generated_message_reflection.h", line 681.4: 1540-0700 (I) The previous message was produced while processing "google::protobuf::internal::DynamicCastToGenerated<const google::protobuf::Mixin>(const Message *)".
"google/protobuf/api.pb.cc", line 1540.7: 1540-0700 (I) The previous message was produced while processing "google::protobuf::Mixin::MergeFrom(const Message &)".
"./google/protobuf/type.pb.h", line 220.6: 1540-0251 (S) The "." operator cannot be applied to the undefined class "class Type".
"./google/protobuf/type.pb.h", line 423.6: 1540-0251 (S) The "." operator cannot be applied to the undefined class "class Field".
"./google/protobuf/type.pb.h", line 764.6: 1540-0251 (S) The "." operator cannot be applied to the undefined class "class Enum".
"./google/protobuf/type.pb.h", line 944.6: 1540-0251 (S) The "." operator cannot be applied to the undefined class "class EnumValue".
"./google/protobuf/type.pb.h", line 1095.6: 1540-0251 (S) The "." operator cannot be applied to the undefined class "class Option".
