### ISSUE TITLE
Investigate usage of generated protos

### ISSUE THREAD

**Issue by jskeet** [google/protobuf#374]
In PR #373 we deleted some files:

- UnittestPreserveUnknownEnum2.cs
- UnittestPreserveUnknownEnum.cs
- UnittestNoFieldPresence.cs

They weren't referenced in project files, but probably should have been. I'll investigate what's going on there.

**Comment by jskeet** [comment]
It looks like UnittestNoFieldPresence could be reinstated, deleting FieldPresenceTest.cs which is only in the csharp area.

The enum-preservation test protos are only used by C++ tests at the moment - we should probably port those tests into C# and reinstate the files.

**Comment by jskeet** [comment]
The two UnittestPreserveUnknownEnum files should use different namespaces, and are only useful when we have implemented proto3 enum behaviour. I have the start of a port of the C++ unit tests for that, but I'll put it in a branch on my fork.

For UnittestNoFieldPresence, I suspect we can use an existing proto in src/google/protobuf - will investigate that.

**Comment by jtattermusch** [comment]
@jskeet, should this be closed?

**Comment by jskeet** [comment]
Yup, it's obsolete now.
