### ISSUE TITLE
aix environment "an lvalue-to-rvalue transformation" error 

### ISSUE THREAD

**Issue by lanjinh520** [google/protobuf#3748]
compile version:IBM XL C/C++ for AIX, V11.1 (5724-X13) Version: 11.01.0000.0005
system version:6100-04-06-1034
protobuf version:protobuf-3.2.0
------------------------------------------error ------------------begin------------------
        source='google/protobuf/extension_set_heavy.cc' object='google/protobuf/extension_set_heavy.lo' libtool=yes  DEPDIR=.deps depmode=aix /bin/sh ../depcomp  /bin/sh ../libtool --tag=CXX    --mode=compile xlC_r -DHAVE_CONFIG_H -I. -I..     -D_THREAD_SAFE  -DHAVE_PTHREAD=1   -qrtti=dyna -qtls -c -o google/protobuf/extension_set_heavy.lo google/protobuf/extension_set_heavy.cc
 xlC_r -DHAVE_CONFIG_H -I. -I.. -D_THREAD_SAFE -DHAVE_PTHREAD=1 -qrtti=dyna -qtls -c -M google/protobuf/extension_set_heavy.cc  -DPIC -o google/protobuf/.libs/extension_set_heavy.o
"google/protobuf/extension_set_heavy.cc", line 400.25: 1540-0219 (S) The call to "down_cast<google::protobuf::Message *>" has no best match.
"google/protobuf/extension_set_heavy.cc", line 400.45: 1540-1228 (I) Argument number 1 is an lvalue of type "google::protobuf::MessageLite * const".
"./google/protobuf/stubs/casts.h", line 81.11: 1540-1202 (I) No candidate is better than "google::protobuf::internal::down_cast<google::protobuf::Message *,google::protobuf::MessageLite>(MessageLite *)".
"google/protobuf/extension_set_heavy.cc", line 400.45: 1540-1231 (I) The conversion from argument number 1 to"google::protobuf::MessageLite *" uses "an lvalue-to-rvalue transformation".
"./google/protobuf/stubs/casts.h", line 97.11: 1540-1202 (I) No candidate is better than "google::protobuf::internal::down_cast<google::protobuf::Message *,google::protobuf::MessageLite * const>(MessageLite * const &)".
"google/protobuf/extension_set_heavy.cc", line 400.45: 1540-1231 (I) The conversion from argument number 1 to"google::protobuf::MessageLite * const &" uses "the identity conversion".
make: The error code from the last command is 1.
----------------------------------------------end--------------------------------------------------
how can i  improve this error??

**Comment by pherl** [comment]
Could you try if changing down_cast<Message*> to down_cast<const Message*> solves the issue?

**Comment by pherl** [comment]
This actually looks like a compiler bug. When calling the function the original type of message_value -
 ```google::protobuf::MessageLite* const``` should be ```google::protobuf::MessageLite*``` due to the copy in function call. The compiler seems to still treat the parameter type as the original const type, which is a bug. I guess it only happens when the compiler is dealing with the implicit const added const function.

Could you please file a bug to the IBM compiler? Here's the simple code to reproduce the issue:

```c++
template<typename Arg>
void F(Arg* arg) {}

struct S {
  void ConstFunction() const {
    F(value_);
  }

  int* value_;
};
```
When passing the value_ into a function, the const qualifier (added implicitly due to in a const function) should be removed in template matching, as it's a value copy in function call. The compiler used the ```int* const``` to match types.

**Comment by lanjinh520** [comment]
OK thank you. but i rename function to solve problems in casts.h
inline To down_cast(From* f)------>remame>----inline To down_cast_point(From* f)
inline To down_cast(From& f)

**Comment by varun85gupta** [comment]
I have also encountered this error. Any ideas on how to solve it . I tried the renaming down_cast, but it gives problems later on.

**Comment by pherl** [comment]
@varun85gupta Are you also using the AIX compiler?

**Comment by varun85gupta** [comment]
Yes. I am using XLC compiler.

**Comment by pherl** [comment]
I'd suggest file a bug on the compile. I don't think there's much we can do. If you could figure a workround to make it pass for the compiler. Feel free to send a PR with `#ifdef` for the compiler/platform.
