### ISSUE TITLE
<Java> Java support primitive array serialization and deserialization

### ISSUE THREAD

**Issue by yanxinyuan** [google/protobuf#3749]
Guys,
 
     Version:  3.4.0
     Using lib: protobuf-java-3.4.0.jar, protobuf-java-util-3.4.0.jar
I'm working on a distribution framework, so we have hundreds services, but we don't use RPC, we actually use the asynchronous model of the queue.
here is the code :
Send Server: 
 
```
   com.google.protobuf.ListValue.Builder listBuilder = ListValue.newBuilder();
           for (Object subObj : list) {
            if (WRAPPER_TYPES.contains(subObj.getClass())) {
                Value value = parsePrimitiveType2Value(subObj);
                listBuilder.addValues(value);
                continue;
            }
        }
         return listBuilder.build();
```
Receive Server:
```
        List<Object> result = new ArrayList<>();
        List<Value> valueList = listValue.getValuesList();
        for (Value subValue : valueList) {
                Object subObj = parsePrimitiveValue2Obj(subValue);
                result.add(subObj);
        }
```
, So i can handle the return value of list with a inner wrapper of protobuf.  But if the return value is an array which means the receive server's interface is also an array, i didn't know how to handle by this method.
  Actually i don't know this is a issue or feature, so i post the question here first.

**Comment by pherl** [comment]
I don't quite understand how you are exchanging messages between different servers. But would you be able to send the serialized byte[] (message.toByteArray()), and parse the bytes on the other end?

**Comment by yanxinyuan** [comment]
yes pherl, we use byte[] to exchange messages between different servers. As above example:
A Server: 
    `List<String> method()`
B Server:
    `void method(List<String> params)`
Here is the workflow:
     When A Server method return a list<String>, the server will transform the list<String> to ListValue by protobuf, then send the serialized byte[] to rabbitmq by doing this.
`Any.pack(msg).toByteArray()`
     After the B Server receive this message, it will deserialize the byte to list and invoke it's method.

So my problem is blow scenario:
A Server:
    ` String[] method()`
B Server:
     ` void method(String[] params)`

As the above mention, i have already use the ListValue(com.google.protobuf.ListValue) to indicate the List(like List<String>, List<Double> and so on) in java, so i can not use the ListValue to indicate the array any more.

**Comment by yanxinyuan** [comment]
seems protobuf do not distinguish array and list. so close this issue.
