### ISSUE TITLE
cmake import target generation: cannot find protoc executable when using protobuf-modules

### ISSUE THREAD

**Issue by uykusuz** [google/protobuf#3750]
Platform: arch linux
cmake: 3.9.4

Error: when trying to include a compiled build of protobuf using `find_package()`'s config mode the search  won't succeed because protoc can't be found. It fails with "Protobuf_PROTOC_EXECUTABLE is not set."

Details: when building protobuf using cmake, the file templates in this project's subfolder `cmake` are used to generate import files for other projects. When I do this with no further arguments to cmake, it will generate, among others, a protobuf-targets-noconfig.cmake file, that contains the exact paths to all the targets. 
However, the protobuf-modules.cmake doesn't look for that "noconfig" variables when trying to initialize `Protobuf_PROTOC_EXECUTABLE`, only for "debug" and "release" variables.
Perhaps I'm doing something wrong, but I just can't figure out how to instruct cmake to generate something like `protobuf-targets-debug.cmake`. 

I will create a pull request that fixed this issue on my machine.

**Comment by acozzette** [comment]
I'm going to close this issue because it looks like it was fixed with pull request #3751.
