### ISSUE TITLE
ECCN for protobuf

### ISSUE THREAD

**Issue by beurer** [google/protobuf#376]
Hello,
We use protobuf in our commercial product and therefore need to know the ECCN for it.
The ECCN is an international Export control and compliance number that is necessary for EVERY Export. Most of the european countries specify their goods according to the european commerce control list (EG dual-use list : http://ec.europa.eu/trade/index_en.htm).
So for export of a commercial Software using protobuf  ( or any other open source or OEM Software), we need to document the libs, on one side to comply with license obligations and on the other side the ECCNs for Export restrictions. Please note, as the US regulations also care about re-export of US items ( any stuff that contains US Content above a certain Limit), we need to specify both; the EU-ECCN and the US-ECCN and hopefully the US license exception that applies (e.g. TSU for open source).

So please specify the ECCN for protobuf or answer the following questions:
- Country of origin ( where is  protobuf Software mainly developed)
- is there US Content in there? ( e.g. other open source libs)
- Is the SW designed or modified to use cryptography performing any cryptographic function other than authentication or digital signature? (y/n) 
–if yes,
-- key length symetric
-- Bit length asymmetric

Thanks and kind regards
Maria Beurer

**Comment by xfxyjwf** [comment]
I have never heard of that. I'm asking our internal teams to see if anyone knows.

**Comment by cfallin** [comment]
The ECCN for protobuf is 5D002.  It is eligible for treatment under License Exception TSU.
