### ISSUE TITLE
Bazel workspace name mismatch for @com_google_protobuf_cc causes build warnings

### ISSUE THREAD

**Issue by fis** [google/protobuf#3766]
Bazel's native `proto_library` rules have an implicit dependency on `@com_google_protobuf//:protoc`, while `cc_proto_library` rules have one on `@com_google_protobuf_cc//:cc_toolchain`. I believe the normal way of configuring a Bazel project to use these rules is to point both the plain and `_cc` remote repositories at the code in this GitHub repository.

With the recent addition of `workspace(name = "com_google_protobuf")` in the protobuf `WORKSPACE` file, any use of `cc_proto_library` (after pointing it at this code) is now causing the following warning:

`WARNING: /.../external/com_google_protobuf_cc/WORKSPACE:1: Workspace name in /.../external/com_google_protobuf_cc/WORKSPACE (@com_google_protobuf) does not match the name given in the repository's definition (@com_google_protobuf_cc); this will cause a build error in future versions`

There's an analogous issue for `java_proto_library`'s implicit dependency on `@com_google_protobuf_java`, which could also be pointed at the same codebase. (`java_lite_proto_library` manages to avoid this because the `javalite` branch doesn't have the workspace name definition.)

FWIW, I'm not really sure whether this counts as a protobuf issue or a Bazel issue.

I've managed to partially work around the issue by using `build --proto_toolchain_for_cc=@com_google_protobuf//:cc_toolchain` in my project's `bazel.rc`, but that does not work for example for "bazel query", which has no equivalent flag.

**Comment by fis** [comment]
Forgot to mention: this was using the latest Bazel release (0.6.1).

**Comment by xfxyjwf** [comment]
@cgrushko The options I can think of to address this warning:
1. Remove `workspace(name = "com_google_protobuf")` from protobuf's WORKSPACE file.
2. Remove the warning from bazel and be tolerant with the workspace name discrepancy. 
3. Make bazel point at com_google_protobuf by default for cc/java_proto_library rules.

Option (3) seems the only reasonable solution.

**Comment by xfxyjwf** [comment]
Seems this is fixed according to https://github.com/cgrushko/proto_library/issues/4
