### ISSUE TITLE
how to write .proto file?

### ISSUE THREAD

**Issue by dongjiang1989** [google/protobuf#3774]
My program is written in C language. Which uses the C Struct message data. Now I want to change C Struct to protobuf .proto file. Encountered some problems：

```
 typedef struct
 {
     unsigned int A;
     short unsigned int B[2]; 
     short unsigned int C; 
     unsigned char D;
     unsigned char E:2;
     unsigned char F:1;
     otherStruct G1;
     void *H;
 } ROOTSTRUCT;
```

**Comment by acozzette** [comment]
What problems did you encounter?

**Comment by dongjiang1989** [comment]
@acozzette  how to wirite bit field in proto file?

**Comment by acozzette** [comment]
@dongjiang1989 Protobuf doesn't directly support bitfields. To accomplish this sort of thing you would need to work with the regular integer types and then manually use bit operations to manipulate your data.
