### ISSUE TITLE
How can i reduce librarys size?

### ISSUE THREAD

**Issue by 0x7962** [google/protobuf#3776]
Hi,
I just want work with c++ and my device storage is too small(128M), so how can i reduce libs size?

Thanks.

**Comment by acozzette** [comment]
I would recommend setting `option optimize_for = LITE_RUNTIME;` in your .proto files and linking against `libprotobuf-lite`. This will save size by leaving out support for reflection.

**Comment by pherl** [comment]
There are also on-going efforts to further reduce the size. Probably will be available in 3.6+ releases.

**Comment by 0x7962** [comment]
Thanks for reply.
i used `CXXFLAGS="$(pkg-config --cflags protobuf-lite)" LIBS="$(pkg-config --libs protobuf-lite)" CFLAGS="$(pkg-config --cflags protobuf-lite)" --enable-static=no` for configure flags and the out libs size was reduced.

**Comment by 0x7962** [comment]
```
1047065 10月 20 20:21 libprotobuf-lite.so.14.0.0
8268713 10月 20 20:21 libprotobuf.so.14.0.0
4857013 10月 20 20:21 libprotoc.so.14.0.0
