### ISSUE TITLE
PHP crash / full test-case included

### ISSUE THREAD

**Issue by jbq** [google/protobuf#3779]
Hi, please find at https://github.com/jbq/protobuf-crash a full crash test with PHP 7.1.10.

Here is the GDB traceback of a similar crash: https://gist.github.com/jbq/9ebfc714f879cd81cce4ec0d3c4b0749

It's basically a `Segmentation fault` in `zend_hash_find_bucket()` when I try to pass Protobuf objects to a Twig template.

If you believe it's a PHP bug I can file the issue there, but this problem only arises with the protobuf extension loaded.

**Comment by TeBoring** [comment]
I can reproduce it locally. Investigating.

**Comment by TeBoring** [comment]
I found there is ```$twig->render('email_body.txt', $context)```
Do u know how render interact with protobuf message?

**Comment by TeBoring** [comment]
ok, I don't understand ```{tender.owner.first_name}```. Is it php syntax? If yes, user cannot access protobuf message directly.

**Comment by TeBoring** [comment]
change to ```tender.getOwner().getFirstName()```?

**Comment by jbq** [comment]
Indeed if I put `tender.getOwner().getFirstName()` it works.

Please find the Twig documentation here: https://twig.symfony.com/doc/2.x/templates.html#variables

I copy the implementation details documented

> For convenience's sake foo.bar does the following things on the PHP layer:
> 
> check if foo is an array and bar a valid element;
> if not, and if foo is an object, check that bar is a valid property;
> if not, and if foo is an object, check that bar is a valid method (even if bar is the constructor - use __construct() instead);
> if not, and if foo is an object, check that getBar is a valid method;
> if not, and if foo is an object, check that isBar is a valid method;
> if not, and if foo is an object, check that hasBar is a valid method;
> if not, return a null value.
> foo['bar'] on the other hand only works with PHP arrays:
> 
> check if foo is an array and bar a valid element;
> if not, return a null value.

So AFAICT the PHP implementation of Protobuf should be nice and is not supposed to crash if some code tries to access the properties directly.  Also please note that there is no crash if the `protobuf` PHP extension is disabled (pure PHP implementation).

**Comment by jbq** [comment]
@TeBoring if you believe it is a genuine PHP bug I can file the traceback upstream. WDYT?

**Comment by TeBoring** [comment]
Sorry for late reply. I don't think it's a bug. protobuf API doesn't allow access via field directly.

**Comment by jbq** [comment]
OK understood but is it possible to raise an exception or return null on
attribute access instead of the ugly PHP interpreter crash?
-- 
Jean-Baptiste Quenot
Tel maison: +33(0)5 62 57 17 28
Tel portable: +33(0)6 50 23 76 87

**Comment by TeBoring** [comment]
From my understanding, accessing through field directly is a behavior that we want to forbid. It's not like ```mergeFromString``` which we want user to be able to catch if data is not right. We don't want accessing through field appear in user's code. The current behavior helps user find it at develop time instead of leaving it to production.

**Comment by TeBoring** [comment]
Feel free to reopen if you still have question.
