### ISSUE TITLE
Where to find `protoc`?

### ISSUE THREAD

**Issue by kevinashaw** [google/protobuf#3780]
I'm attempting to use protobuf and, having carefully followed the docs, I now have a .proto file that is ready to compile.  But I cant find the protobuf compiler: `protoc` anywhere.  The `readme.md` says: 
> In the downloads section of each release, you can find pre-built binaries in zip packages: protoc-$VERSION-$PLATFORM.zip. It contains the protoc binary as well as a set of standard .proto files distributed along with protobuf.

I have downloaded the 3.4.1, 3.4.0 or 3.3.0 releases, but I cant find a "downloads" section in any of them.  Are we supposed to compile from source?  Or are binaries provided?  If so, where?

I've seen another discussion (https://github.com/google/protobuf/issues/3775) where we told to go to Maven for precompiled versions.  However those `protoc` files are all compiled for windows ("protoc-3.4.0-osx-x86_64.exe").  I bit of cruel irony, I guess.

So what is the preferred method of using `protoc`?  
And, once answered, will someone update the `readme.md` file to match?
Thanks!

**Comment by xfxyjwf** [comment]
Open this release page:
https://github.com/google/protobuf/releases/tag/v3.4.0

and in the downloads section you can find protoc-3.4.0-osx-x86_64.zip.

The protoc binaries we put up in maven are indeed compiled for multiple platforms. protoc-3.4.0-osx-x86_64.exe is a OSX binary. Don't be fooled by its file name... You can just change it to `protoc` after download (or at the time of download). You probably also need to `chmod +x` on it.

**Comment by kevinashaw** [comment]
@xfxyjwf Thank you for the help.  I spent several hours and just couldn't "see" the files.  Clearly they were right in front of me in the "Downloads" section at the bottom of the list.  Its so frustrating when one misses stuff like that!  My Bad!  Thanks for the help.

**Comment by amiracam** [comment]
funny , having the same issue
