### ISSUE TITLE
FieldMask backwards/forwards compatibility issues.

### ISSUE THREAD

**Issue by romeovs** [google/protobuf#3793]
One of the advantages of using protobuf is the fact that the message field names can evolve over time without breaking out-of-date clients:

For instance the `Foo` messages from these versions are binary compatible:
```
// v1
message Foo {
  string bar = 1;
  string baz = 2;
}
```
```
// v2
message Foo {
  string quu = 1;
  string qux = 2;
}
```

This means that clients that are still on `v1` can talk to `v2` servers without issues.

*If I'm not mistaken* (note the emphasis), I think adding `FieldMask` into the mix breaks this.

While the following API versions might be binary compatible:
```
// v1
message Foo {
  string bar = 1;
  string baz = 2;
  FieldMask mask = 3;
}
```
```
// v2
message Foo {
  string quu = 1;
  string qux = 2;
  FieldMask mask = 3;
}
```

Their messages lose meaning.

For instance, a `v1` client would send a message:
```
Foo {
  bar: "yes!",
  mask: "bar"
}
```
which updates the `Foo` field `bar` to `yes!` in `v1`.
This does nothing in `v2` however, since the server does not know the `bar` field anymore.

I know the server can work around this by having a list of field aliases from older versions, but that's a pain to maintain (why use protobuf if you're willing to do that?).

A more logical FieldMask implementation would be:
```
// v1
message Foo {
  string bar = 1;
  string baz = 2;
  FooMask mask = 3;
}

message FooMask {
  bool bar = 1;
  bool baz = 2;
}
```

So messages would look like:

```
Foo {
  bar: "yes!",
  mask: {
    bar: true
  }
}
```

This has a couple of advantages:
- The field mask values are part of the protobuf, so it's easier to create valid field masks (there is still some duplication of code, but it is more concentrated and part of the API).
- FieldMasks are binary compatible, as long as their field numbers are kept up to date.
- FieldMasks can be generated automatically for each message (to even further reduce duplicate code).

I understand this is probably not a change you would be willing to make, but I think this needs to be documented somewhere at least.

This is more of a question than an issue.

**Comment by acozzette** [comment]
You are right that if you use FieldMasks then you can't safely rename fields. But for that matter, if you use the JSON format or text format then you have the same issue that field names are significant and can't be changed easily. Changing field names really only works if you use the binary format only and avoid FieldMasks.
