### ISSUE TITLE
Cannot build javalite with bazel at HEAD

### ISSUE THREAD

**Issue by thaidn** [google/protobuf#3796]
ERROR: protobuf-javalite/BUILD:412:1: Traceback (most recent call last):
	File "protobuf-javalite/BUILD", line 412
		cc_proto_library(name = "cc_test_protos", srcs = (L...), <4 more arguments>)
	File "protobuf-javalite/protobuf.bzl", line 247, in cc_proto_library
		cc_libs += [default_runtime]
trying to mutate a frozen object
ERROR: protobuf-javalite/BUILD:793:1: Traceback (most recent call last):
	File "protobuf-javalite/BUILD", line 793
		py_proto_library(name = "python_specific_test_pro...", <6 more arguments>)
	File "protobuf-javalite/protobuf.bzl", line 373, in py_proto_library
		py_libs += [default_runtime]
trying to mutate a frozen object

@xfxyjwf could you please take a look? Thank you.

**Comment by xfxyjwf** [comment]
I just cherry-picked https://github.com/google/protobuf/commit/4fc93044a5de018527ec027dbee6a882012e0d9d to the javalite branch and it should fix this issue.
