### ISSUE TITLE
protobuf map core in  hash

### ISSUE THREAD

**Issue by LiuYang1206** [google/protobuf#3799]
```c++
 google::protobuf::Map<string, string>* headers = req.mutable_headers();
        for (size_t i = 0; i < request.headers.size(); i++) {
            (*headers)[request.headers[i].name] = request.headers[i].value;//core here 
        }
```
libprotobuf FATAL /usr/local/include/google/protobuf/stubs/hash.h:204] Should never be call

```

template <>
struct hash<const char*> {
  // Dummy, just to make derivative hash functions compile.
  int operator()(const char* key) {
    GOOGLE_LOG(FATAL) << "Should never be called.";
    return 0;
  }

  inline bool operator()(const char* a, const char* b) const {
    return strcmp(a, b) < 0;
  }
};

```
how to solve this issue???

**Comment by LiuYang1206** [comment]
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-11)
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by acozzette** [comment]
@LiuYang1206 What protobuf version are you using? That dummy hash function should only be used if the compiler is too old/unusual to have a better hash function available, so it's surprising that the dummy is being used given that your compiler is not that old.

**Comment by LiuYang1206** [comment]
@acozzette  protobuf release 3.4.1 ,  I find the bug is fixed in newest github code

**Comment by acozzette** [comment]
@LiuYang1206 Hmm, I wonder what the problem was, but in any case that is good to hear that is now fixed with the latest code.
