### ISSUE TITLE
fetch an error when using protoc to create php code 

### ISSUE THREAD

**Issue by karliehgf** [google/protobuf#3800]
[root@m soft]# protoc --proto_path=./ --php_out=./passport --grpc_out=./passport --plugin=protoc-gen-grpc=/root/soft/grpc/bins/opt/grpc_php_plugin ./passport.proto
[libprotobuf ERROR google/protobuf/io/printer.cc:151]  Undefined variable: GOPATH/src/ -I
[libprotobuf ERROR google/protobuf/io/printer.cc:151]  Undefined variable: GOPATH/src/ -I
[root@m soft]# echo $GOPATH
/usr/local/go
[root@m soft]# ll /usr/local/go/
总用量 136
drwxr-xr-x.  2 root root   205 10月  5 02:46 api
-rw-r--r--.  1 root root 33243 10月  5 02:46 AUTHORS
drwxr-xr-x.  2 root root    42 10月  5 02:53 bin
drwxr-xr-x.  4 root root    37 10月  5 02:53 blog
-rw-r--r--.  1 root root  1366 10月  5 02:46 CONTRIBUTING.md
-rw-r--r--.  1 root root 45710 10月  5 02:46 CONTRIBUTORS
drwxr-xr-x.  8 root root  4096 10月  5 02:46 doc
-rw-r--r--.  1 root root  5686 10月  5 02:46 favicon.ico
drwxr-xr-x.  3 root root    18 10月  5 02:46 lib
-rw-r--r--.  1 root root  1479 10月  5 02:46 LICENSE
drwxr-xr-x. 14 root root   190 10月  5 02:53 misc
-rw-r--r--.  1 root root  1303 10月  5 02:46 PATENTS
drwxr-xr-x.  8 root root   113 10月  5 02:53 pkg
-rw-r--r--.  1 root root  1399 10月  5 02:46 README.md
-rw-r--r--.  1 root root    26 10月  5 02:46 robots.txt
drwxr-xr-x. 46 root root  4096 10月  5 02:46 src
drwxr-xr-x. 17 root root  8192 10月  5 02:53 test
-rw-r--r--.  1 root root     7 10月  5 02:46 VERSION

**Comment by pherl** [comment]
Hmm, did you pass in GOPATH anywhere? Would it work without enabling the grpc plugin?
