### ISSUE TITLE
Documentation for adding comments only mentions line comments, not block comments

### ISSUE THREAD

**Issue by danbars** [google/protobuf#3801]
In proto [documentation](https://developers.google.com/protocol-buffers/docs/proto3#adding-comments), it is mentioned that only line comments are supported
However, in [descriptor.proto](https://github.com/google/protobuf/blob/master/src/google/protobuf/descriptor.proto#L834) block comments are specifically supported. 
I wanted to fix documentation in PR, but apparently it's not coming from a public git repo.
I think documentation should state that block comments are supported.

**Comment by acozzette** [comment]
Thanks for reporting this. I wrote a fix for the documentation and it should be published on the site soon.

**Comment by acozzette** [comment]
The update is now live on the documentation site.
