### ISSUE TITLE
Please allow the addition of stubs for the Python protobuf API to typeshed

### ISSUE THREAD

**Issue by gvanrossum** [google/protobuf#3803]
In https://github.com/python/typeshed we are collecting type-checking stubs for the Python standard library and for popular third party Python packages. These stubs are used by mypy, PyCharm and Google's own pytype.

We'd like to add stubs for protobuf. Our policy is to first request permission from the original package developers, to ensure that we don't do double work or cause additional problems for them. (See https://github.com/python/typeshed#third_party for the policy.)

To give permission, just say so in this issue and we'll do the rest (unless you want to be more involved, that would be great of course).

PS. I know of several projects that automatically generate stubs from protobuf specifications. Such stubs will be more useful if the protobuf base library APIs have stubs.

**Comment by acozzette** [comment]
Sounds great! Will this require some kind of support in protoc for generating stubs? It sounds like you already know of some projects that must be automatically generating stubs from .proto files.

**Comment by gvanrossum** [comment]
Glad to hear it! At Dropbox we already have *two* utilities that generate stubs from protobuf source code -- one in Go, one in Python! Of course it would be great if we could replace both of these with a new flag to protoc. But in the short term we are now in control of our own destiny.

**Comment by wkiser** [comment]
@gvanrossum are those protobuf stub generating utilities publicly available?

**Comment by gvanrossum** [comment]
Not yet; their respective authors want to open-source them but it takes time.

**Comment by wjh** [comment]
We could really do with using these utilities at work, sorry to bother you but is there any chance of a release sometime soon?

Wrote my own little util for it, but it's not particularly thorough.

**Comment by gvanrossum** [comment]
@wkiser, @wjh: The stub generating utilities are now available: https://github.com/dropbox/mypy-protobuf/

Also, since we've now got the permission to proceed with including the stubs in typeshed, closing this issue.
