### ISSUE TITLE
<Java> com.google.protobuf.Value support other protobuf type

### ISSUE THREAD

**Issue by yanxinyuan** [google/protobuf#3805]
Hi guys,
     Version:  3.4.0
     Using lib: protobuf-java-3.4.0.jar, protobuf-java-util-3.4.0.jar

I'm now working on a function, i need to parse a java list to protobuf ListValue.  As we know if the object in the list is java primitive type, i can use the Value to pack it. but if the object in the list is the protobuf type like the  below example, i have no idea how to handle it.

I have read the java doc and i realize the value is be designed only to support some limited type
> `Value` represents a dynamically typed value which can be either
>  null, a number, a string, a boolean, a recursive struct value, or a
>  list of values.
 
Note: CustomerProtobuf is a standard Java type generated by the protobuf compiler tool.
```
	public static ListValue parseList(List<?> list) {
		com.google.protobuf.ListValue.Builder listBuilder = ListValue.newBuilder();
		for (Object subObj : list) {
			if (subObj instanceof Double) {
	            Value value = Value.newBuilder()
	                    .setNumberValue(Double.valueOf(String.valueOf(subObj)))
	                    .build();
	            listBuilder.addValues(value);
                continue;
	        } 
			if (subObj instanceof String) {
	            Value value = Value.newBuilder()
	                    .setStringValue(String.valueOf(String.valueOf(subObj)))
	                    .build();
	            listBuilder.addValues(value);
                continue;
	        }
	        if (subObj instanceof Boolean) {
	            Value value = Value.newBuilder()
	                    .setBoolValue(Boolean.valueOf(String.valueOf(subObj)))
	                    .build();
	            listBuilder.addValues(value);
                continue;
	        } 
	        if (subObj instanceof CustomerProtobuf) {
	        	// how to handle ?
	        }
		}
        return listBuilder.build();
	}
```

Here is the proto file definition
```
syntax = "proto3";

package com.delta.meu.customer.protobuf;
option java_multiple_files = true;
option java_package = "com.delta.meu.customer.protobuf";

message CustomerProtobuf {
	string id = 1;
	string name = 2;
}
```

**Comment by yanxinyuan** [comment]
So far my solution is to use a use defined wrapper instead of using the ListValue, which means i should maintain a extra proto definition,  Any comments?

**Comment by acozzette** [comment]
@yanxinyuan Using a user-defined wrapper sounds to me like the right solution. As I understand, `Value` and `ListValue` and the other types in `struct.proto` are intended as a way to represent arbitrary JSON objects, so if you want to store your own proto message then those types in `struct.proto` are probably not the right choice.

**Comment by yanxinyuan** [comment]
@acozzette , thanks you for your explanation. In fact, this requirement is still hidden a big problem, and i don't know how to deal with it now.  
So far in our real solution, we have hundreds distributed services(event based), and we use protobuf to communicate between each service.  So we have to write hundreds proto files to define the service interface(Because we are non-invasive system, so we can not limit the user interface type), so it's a big work to maintain hundreds proto generated interface and object.
Actually I'm not sure if I have described the problem clearly enough, simply speaking the problem is how to handle the scenario with hundreds protobuf interface and hundreds protobuf generated objects? like version control, reduce develop complexity and so on.

**Comment by acozzette** [comment]
Have you thought about trying proto2 [extensions](https://developers.google.com/protocol-buffers/docs/proto#extensions) or the [Any](https://developers.google.com/protocol-buffers/docs/proto3#any) type if you're using proto3? This is one way of keeping your own protos simple while allowing other teams to extend them with their own message types. Would that help for your situation?

**Comment by yanxinyuan** [comment]
yes acozzette, we're now using proto3. And the data struct of my event(our framework is event based) is 
```
Message
---Event
------source
------destination
------Payload
---------Any
```
The Any type did help me a lot. But sadly, I still need to do a lot of thing. Like version control when i have hundreds service. Like primitive type wrap when the service use the java primitive type(String, Integer and so on) as its input parameter or output parameter.

**Comment by acozzette** [comment]
What problem are you having with version control? Is it some kind of problem with keeping .proto files in sync between separate Git repositories or something like that?
