### ISSUE TITLE
How does the first proto file import the message in the second file？

### ISSUE THREAD

**Issue by Zhouioi** [google/protobuf#3806]
syntax = "proto3";
package com.mobuz;
import “AddressInfo”；
option java_package = "com.proto.user";
option java_outer_classname = "UserInfo";
message User{
string uid=1;
string uname=2;
}

syntax = "proto3";
package com.mobuz;
option java_package = "com.proto.user";
option java_outer_classname = "AddressInfo";

message Address{
string state=1;
string city=2;
}

How do I import the AddressInfo into UserInfo by js？
O(∩_∩)O

**Comment by yanxinyuan** [comment]
If the two proto files are in the same directory, you can directly reference it, or you should use the full name.

**Comment by pherl** [comment]
See the https://developers.google.com/protocol-buffers/docs/proto#other for importing other messages.
