### ISSUE TITLE
Enum value with index 0 not shown

### ISSUE THREAD

**Issue by AKuzmanoski** [google/protobuf#3808]
I am not sure whether this is a bug or it is by design but when I try to return enum value which has index 0 in is not included in the end result.

For example, if I have the following structure:
```
enum RandomType {
      ONE = 0;
      TWO = 1;
      THREE = 2;
      ...
}

message RandomMsg {
       RandomType random_type = 1;
       ...
}
```

and I try to return RandomMsg with random_type = ONE then the result will be
`
{
    // Without random_type property
    ....
}
`

However, this behavior can be confusing if there is no default value or if every value has equal importance to any other value.

**Comment by acozzette** [comment]
This is by design actually: proto3 enums must start with a zero-valued entry, which is used as the default value. And with proto3 there is no distinction between a field that's empty and one that's set to its default. More here about proto3 enums: https://developers.google.com/protocol-buffers/docs/proto3#enum

**Comment by uldall** [comment]
Is it possible to get the JSON serializer to write the fields which are set to their default values?

**Comment by acozzette** [comment]
@uldall I think it might depend on which language you're using but at least for some languages there's an option to print primitive fields even if they're set to the default. Here is it for C++ for example: https://github.com/google/protobuf/blob/23adfeb00327fbdccacc99806acb1a9a073bd8e0/src/google/protobuf/util/json_util.h#L63
