### ISSUE TITLE
Error `./configure: line 1: syntax error near unexpected token `('` when running the script of `./full_mac_build.sh`

### ISSUE THREAD

**Issue by VictorZhang2014** [google/protobuf#3813]
It threw an error like this `./configure: line 1: syntax error near unexpected token `('` when running the script of `./full_mac_build.sh` in macOS Terminal.

I need a help from you. 
Thank you in advance.
![wechatimg4](https://user-images.githubusercontent.com/6853884/32142992-cbc2ca86-bc70-11e7-936f-817946a70c37.jpeg)

**Comment by thomasvl** [comment]
What versions of autoconf, automake, etc. do you have installed?  What macOS version are you on?  How did you get the source (git clone?  zip/tar download?  from where?)

If you haven't done them, see the _Note for Mac users_ in the [C++ Installation - Unix](https://github.com/google/protobuf/blob/master/src/README.md#c-installation---unix) of the docs.

**Comment by VictorZhang2014** [comment]
I found the issue, because I store the `full_mac_build.sh` file in a peripheral disk, instead of the system one. So I drag this whole unzipped directory into `Documents` directory in the system disk, and it worked well.

**Comment by thomasvl** [comment]
Do you happen to have spaces in some of the folder names?  I don't think the general configure process used by the core library can handle that.

**Comment by VictorZhang2014** [comment]
I'm afraid there is no any spaces in the path of the protobuf.  And finally ,I solved it and gave an answer and article in this ![link](http://www.googleplus.party/2017/10/18/Protocol-Buffer/#exampleOC).

Thank you. @thomasvl
