### ISSUE TITLE
Adding Sub Fields to a DescriptorProto.Builder.

### ISSUE THREAD

**Issue by RanadheerMusham** [google/protobuf#3816]
Hi,
I have recently started working protobufs, found the following tough. Could you please help me out?
Sample Code:
```
DescriptorProto.Builder builder;
FieldDescriptorProto.Builder fieldBuilder = FieldDescriptorProto.newBuilder()
					.setLabel(label)
					.setType(type)
					.setName("name")
					.setNumber(1)
					.setDefaultValue("value");
builder.addField(fieldBuilder.build());
```
Now let the **type** of the field is `FieldDescriptorProto.Type.TYPE_MESSAGE`. I have to add a sub field to the field built using **fieldBuilder **.
This should be possible because when I build a descriptor file for a proto file with a message having a nested message with fields. And when I debug what I found is "A field of type message with its inner fields is added to the root message ", i.e., for the following message it is represented as  rootMessage has a field subMessage(type = Message) with two subfields B, C.

Sample Proto:
```
message rootMessage{
      string A = 1;
      message subMessage{
         string B = 1;
         string C = 2;
      }
      subMessage sub = 2;
}
```

Typically I need something like
```
FieldDescriptorProto.Builder fieldBuilder = FieldDescriptorProto.newBuilder()
					.setLabel(label)
					.setType(type)
					.setName("name")
                                        .addField(...) // **This Part**
					.setNumber(1)
					.setDefaultValue("value");
```

**Comment by xfxyjwf** [comment]
FieldDescriptorProto/DescriptorProto is a regular proto type. We can't add special accessors for it.
