### ISSUE TITLE
protoc produces SourceCodeInfo that references uninterpreted options, which are not present

### ISSUE THREAD

**Issue by jhump** [google/protobuf#3819]
When protoc produces `SourceCodeInfo` for a file descriptor, all details related to options are attributed (according to the `path` field) to uninterpreted options. There is no way, however, for client code to actually map uninterpreted options to the actual options. During linking, protoc updates the options message and then *discards* the uninterpreted versions. So the path refers to absent elements of the descriptor.

This makes it effectively impossible to extract, for example, comments associated with options. Another task that *seems* like it should be possible is to reconstruct a proto source file from a descriptor that includes source code info (with the understanding that certain things, like trailing comments, cannot be preserved in the descriptor). But the way options are handled in source code info further reduces the fidelity that is possible.

Possible approaches to solve:

1. During linking, the source code info could be updated so that the info for options is actually attributed to the options (e.g. references proper option field numbers, or extension numbers for custom options). For options that define values nested deep inside of options that are messages, the path could contain additional elements that pinpoint exactly the field that is being set. This would lose fidelity since the current representation allows attribution of source code location and comments to option names (even name parts, when the option type is itself a message) whereas this could not be preserved with the suggested transformation.

2. During linking, preserve uninterpreted options in the descriptor when source code info is being included. Furthermore, add fields to the uninterpreted option (or maybe just the name part message) that provide the resolved field/extension numbers. This allows client code to discover the link between uninterpreted option source code info and the actual option values in the descriptor.

**Comment by jhump** [comment]
In an ideal world, the source code info for aggregate options (where the option is a message and its defined value is an aggregate, like `{ foo: 123, bar: "baz" }`, could also be preserved. It would allow, for example, a source code info that pinpoints the `foo` field in the example above, giving the exact source code location for that part of the option.

However, this seems much more complicated, due to how protoc internally stores the AST (which models the aggregate value as a text blob, instead of as a sub-AST for which sub-portions could be correctly attributed to locations in the source file).

**Comment by xfxyjwf** [comment]
I'm leaning towards (1). When we convert uninterpreted options to interpreted ones we are already losing some information. Doing the same transformation for the source code info accompanying the uninterpreted options seems reasonable and is consistent with what we are already doing.

(2) involves a larger interface change (1 can be considered a bug fix while 2 is adding new behavior and new public API) and I think it's also harder for users to use. I can see very little of its value (can't really think of an use case of the preserved source code info for option names...) and would say it's not a worthwhile change to make.

**Comment by jhump** [comment]
@jtattermusch was this resolved?

**Comment by xfxyjwf** [comment]
I guess this was closed by mistake. @jhump do you plan to make a pull request for this?

**Comment by jhump** [comment]
@xfxyjwf, I do hope to eventually. I started working on it, and have a pretty decent grasp of the changes I need to make. (To be honest, I lost a little momentum after I addressed it in my own proto parser that produces source code info, in a Go library named [protoreflect](https://godoc.org/github.com/jhump/protoreflect/desc/protoparse). But I do expect to return to it.)

**Comment by jhump** [comment]
@xfxyjwf I made a pull request to address this: #4342. When testing, I also discovered that protoc produces invalid source code info for extension range options, and that is also fixed in that same pull request.

Do you mind taking a look? It does not yet have tests. I was hoping to get a pointer or two on best approach and maybe to example similar tests. I was also hoping to go ahead and get some eyes on my C++ code: I have not professionally written C++ in 15 or so years, and it's a little slower to pick back up than riding a bike 😄.  It was a decent challenge just getting my head around the existing code and understanding where different responsibilities lie. And I wanted the change to be fairly surgical and low impact.
