### ISSUE TITLE
ParseFromIstream() exits unexpectedly when there are tags whose numbers are 3

### ISSUE THREAD

**Issue by Zhouxing-Su** [google/protobuf#3845]
I'm using the cpp port of proto3 v3.4.1 in Visual Studio 2015 Enterprise.

The library was compiled from source and part of the build configurations are
- x64
- Release
- static library
- /MD runtime

The code to reproduce the bug is
- .proto:
```protobuf
syntax = "proto3";

message Person{
  string name = 3;
}
```

- .cpp:
```cpp
#include <iostream>
#include <fstream>

#include "Person.pb.h"


using namespace std;


int main() {
    Person person;
    person.set_name("szx");
    ofstream ofs("person.data");
    person.SerializeToOstream(&ofs);
    cout << endl << "person.name()=" << person.name() << endl;
    person.PrintDebugString();
    ofs.close();

    ifstream ifs("person.data");
    Person person2;
    person2.ParseFromIstream(&ifs);
    cout << endl << "person2.name()=" << person2.name() << endl;
    person2.PrintDebugString();

    Person person3;
    string data = person.SerializeAsString();
    person3.ParseFromString(data);
    cout << endl << "person3.name()=" << person3.name() << endl;
    person3.PrintDebugString();

    return 0;
}
```

The output is 
```

person.name()=szx
name: "szx"

person2.name()=

person3.name()=szx
name: "szx"
```

Reference:
[1] https://github.com/google/protobuf/issues/1932

**Comment by Zhouxing-Su** [comment]
Besides, after replacing all "=3" to something else like "=77", the mysterious bug is still happening that there are some fields ignored during the deserialization.

**Comment by xfxyjwf** [comment]
Please do what I suggested in https://github.com/google/protobuf/issues/1932#issuecomment-238648920

If after that you can get the issue, please create another issue.

**Comment by Zhouxing-Su** [comment]
@xfxyjwf Do you mean the following code given in my post?

```
Person person3;
string data = person.SerializeAsString();
person3.ParseFromString(data);
cout << endl << "person3.name()=" << person3.name() << endl;
person3.PrintDebugString();
```

There could be some offline operations which require loading data from files.
I've also tried to read the whole file into an array and call the ParseFromArray() but there are still some missing fields compared to `person3.name()`.

The code above works fine, but if everything is kept in the memory then why do we need protobuf?

**Comment by Zhouxing-Su** [comment]
The code above is just an minimal working example.
However, there are a lot of fields in my original code and the ParseFromIstream() returns before the entire object is loaded, and the number of the last loaded field is 2.
So it can't be the case that the file is simply not created after SerializeToOstream().

**Comment by xfxyjwf** [comment]
With "person3" working it should be clear that the issue lies in file read/write operations rather than protobuf parsing/serialization. The real culprit is that the file is not opened in the correct mode. To store protobuf binary data the file needs to be opened in binary mode and the default mode is unfortunately text.

If you are still not sure how to fix the issue, take a look at our example code here:
https://github.com/google/protobuf/blob/master/examples/add_person.cc#L77

It's a perfect example showing how to read/write protos from/to file using ParseFromIstream/SerializeToOstream.

**Comment by Zhouxing-Su** [comment]
Got it. Thanks!

I thought there won't be any problems if the input and output stream was opened in the same mode, which turns out to be wrong (http://en.cppreference.com/w/cpp/io/c#Binary_and_text_modes)...
Sorry for the false report.
