### ISSUE TITLE
DynamicMessage.setField and compiled Message setter treat default values differently

### ISSUE THREAD

**Issue by andredasilvapinto** [google/protobuf#3849]
If I set a field in a DynamicMessage to its default value, the field gets cleared:

https://github.com/google/protobuf/blob/bcda919ceeae8bd854c07a8300d8996ef52315db/java/core/src/main/java/com/google/protobuf/DynamicMessage.java#L534-L535

This doesn't happen if I call the setter of that same field via its compiled Message class:
https://github.com/google/protobuf/blob/master/src/google/protobuf/compiler/java/java_enum_field.cc#L246-L254

thus producing inconsistent results between these two unserialized representations.

**Comment by xfxyjwf** [comment]
I think in both cases setting a field to its default value on a proto3 proto has the same semantics as clearing the field. Do you have a proto code example showing there is a difference?

**Comment by andredasilvapinto** [comment]
@xfxyjwf You are right. I was seeing different results because I was using Proto2 for the compiled version and Proto3 for the DynamicMessage version. The semantics between the two are different regarding setting fields to their default values, but I think that's to be expected. Sorry for the misreport. Closing the issue.
