### ISSUE TITLE
Windows binary of the compiler does not contain the fix for long paths (v3.4.0)

### ISSUE THREAD

**Issue by tri-bao** [google/protobuf#3856]
As per ticket #2891 the issue was fixed, the patch was merged to master. I can see it in source code of version 3.4.0 However, when I tried the precompiled binary downloaded from the release page (or downloaded from maven central repository https://repo1.maven.org/maven2/com/google/protobuf/protoc/3.4.0/), the problem still occurs.

Then I tried to build it by myself using Visual Studio (2017) as advised by the patch contributor @laszlocsomor (https://github.com/google/protobuf/pull/2969), it works! So apparently, the precompiled binary was not built with Visual Studio. Is it a mistake or there are caveats with Visual Studio that prevent the GA release from being built with Visual Studio? (but we need long path in Windows)

By the way, the Windows binary build is missing in release 3.4.1

**Comment by pherl** [comment]
Could you please check if this cross compiled binary supports long path?
[protoc.zip](https://github.com/google/protobuf/files/1462178/protoc.zip)

**Comment by tri-bao** [comment]
thanks @pherl when I ran that exe, I received errors like following (no error if I ran with the binary that I compiled from source 3.4.0)

```
google/protobuf/wrappers.proto: File not found.
xyz.proto: Import "google/protobuf/wrappers.proto" was not found or had errors.
xyz.proto:46:5: "google.protobuf.StringValue" is not defined.
xyz.proto: Import "google/protobuf/wrappers.proto" was not found or had errors.
xyz.proto:21:5: "google.protobuf.StringValue" is not defined.
```

**Comment by pherl** [comment]
The zip I packaged didn't contain the well known type protos. Would it work if you copy the rest google/protobuf/*.proto from the 3.4.0 package?

**Comment by tri-bao** [comment]
thanks for the hint. Now, that binary works with long path. Would you release that binary soon?

**Comment by pherl** [comment]
I uploaded them in the 3.5.0 release.

**Comment by pherl** [comment]
@laszlocsomor

There are couple of issues (#3957, #3951) reported regarding windows protoc paths.

I guess we will have to rollback the long path support change in 3.5.1 support.

**Comment by laszlocsomor** [comment]
Update: a PR is out for #3951.
I'm about to look at #3957.
