### ISSUE TITLE
Protoc not found

### ISSUE THREAD

**Issue by frenchqwerty** [google/protobuf#3864]
Hello everyone,

I'm a beginner for Protobuf and I want to use it.
I have a C# project and I make this file.proto : 

`syntax = "proto3";

message hello
{
  required string data = 1 [default="Hello World!"];
}`

I've installed download Protobuf, compile it with VS, import the .dll on my Project, import with Nuget Google Protobuf Tools, Google ProcotolBuffer and protobuf-net

After this, I have created a file make.bat with : 
`protoc --csharp_out=. hello.proto`

I have an error on my cmd, it doesn't found protoc...
Please help me, I'm blocked since 2 days 😢

**Comment by anandolee** [comment]
Protoc is implemented by C++, just download one protoc-version-win32.zip: https://github.com/google/protobuf/releases
