### ISSUE TITLE
sint32 with null value throws "Expect integer" exception in PHP

### ISSUE THREAD

**Issue by groganz** [google/protobuf#3865]
It seems that `null` is being converted to an empty value if defined as `sint32` in the .proto, while `null` is being converted to 0 if `int32` when doing `mergeFromJsonString()`. This causes an "Expect integer" exception for sint32 `null` values, but no exception - as expected - for int32 `null` values.

**Comment by TeBoring** [comment]
I think this has been fixed in master. Could you pull the latest change and make a try? (c extension may still have bug. Need more time to fix.)

**Comment by groganz** [comment]
I ran it on dev-master. Not using the c extension. I doubt it is causing the bug, but FYI: I'm using `import` in the related proto. Find it here (EnrichmentCombined.proto) as well as the imported protos: https://github.com/CampaignChain/channel-clearbit/tree/master/Resources/protobuf

**Comment by TeBoring** [comment]
Fixed in #3869
