### ISSUE TITLE
Repeated Enum Values generate segmentation fault

### ISSUE THREAD

**Issue by zamibaru** [google/protobuf#3866]
Hi

I am trying to generate a binary file and I have to use a repetead field with ENUM.
What I am doing:
Option one:

```
$weekDay = new WeekDay();
$setWeekday->setWeekday(array(\poi\common\Weekday::Monday,\poi\common\Weekday::Tuesday,\poi\common\Weekday::Wednesday,\poi\common\Weekday::Thursday,\poi\common\Weekday::Friday));
```

Option two:
```
$weekDay = new WeekDay();
$weekdayArr = $weekDay->getWeekday();   
$arrWeek = array(\poi\common\Weekday::Monday,\poi\common\Weekday::Tuesday,\poi\common\Weekday::Wednesday,\poi\common\Weekday::Thursday,\poi\common\Weekday::Friday) ; `
 foreach ($arrWeek as  $value) 
{
      $weekdayArr[] =  $value;
}
```

The problem:

This works well if I create a file with 400-500 messages but if i try to add more then 500 messages in the file I will get  
`segmentation fault` error

I am a little stuck here, don't know how to solve this. Any direction would be much appreciated.

**Later Edit:**
I managed to find a workaround. If I disable the garbage collector in my PHP script the problem goes away. 

In this case I presume that the problem is generated when the repeated field is collected by garbage collector.

Hope this helps. I am looking forward for a solution that does not imply totally disabling the garbage collector.

**Comment by TeBoring** [comment]
Are you using c exension or php implementation?
Could you also provide your proto file (which has > 500 messages?)

**Comment by pherl** [comment]
Closing this for now. Feel free to reopen.
