### ISSUE TITLE
always_print_primitive_fields is useless

### ISSUE THREAD

**Issue by piaoxu93** [google/protobuf#3872]
google::protobuf::util::JsonPrintOptions json_options;
json_options.always_print_enums_as_ints = true;
google::protobuf::util::MessageToJsonString(xxx, &jsonStr, json_options);

I find set always_print_enums_as_ints to true is useless. The field is still enum string.

protobuf version is 3.3.0, C++

**Comment by pherl** [comment]
We do have tests to ensure enums are printed as ints: https://github.com/google/protobuf/blob/master/src/google/protobuf/util/json_util_test.cc#L197 Do you have sample code to reproduce the issue?

**Comment by piaoxu93** [comment]
@pherl I find the problem, I've made a mistake. Thank you very much
