### ISSUE TITLE
"You don't have permission to use the application 'protoc-3.4.0-osx-x86_64.exe'" gradle

### ISSUE THREAD

**Issue by crilofer** [google/protobuf#3889]
Hi,

I am trying to build my application that uses protocol buffers. But I am getting the error shown in the screenshot attached.

![screen shot 2017-11-15 at 12 49 24](https://user-images.githubusercontent.com/6973711/32837579-01d10c94-ca06-11e7-8221-e04fe02a511f.png)

This file has 777 permissions.

Thanks.

**Comment by pherl** [comment]
I believe it's MacOS secruity setup. Could you please search around and see if there are some system settings that you can change?

**Comment by crilofer** [comment]
I solved specifying the protoc path.
But now I have different problem:

<img width="451" alt="screen shot 2017-11-20 at 10 34 53" src="https://user-images.githubusercontent.com/6973711/33014264-a5cc39d2-cdde-11e7-8222-16a2791514ae.png">

Thanks.

**Comment by pherl** [comment]
This is a grpc plugin. Could you please ask this in the grpc issues instead? I believe it's probably the same cause though.
