### ISSUE TITLE
Please upload non-language-specific tarballs for releases

### ISSUE THREAD

**Issue by jmillikin-stripe** [google/protobuf#3894]
Protobuf releases currently have language-specific tarballs such as "protobuf-cpp-3.5.0.tar.gz" or "protobuf-python-3.5.0.tar.gz", which include subsets of the repository. Tarballs of the full repository are only available via GitHub's automatic tarball endpoints.

This can be frustrating for users of Bazel, who expect tarball SHA checksums to be stable. GitHub does not guarantee that it always returns the exact same bytes for a tarball of a given commit/tag.

As a solution, when cutting a release, please upload a full source tarball. Then users can depend on it and expect a stable SHA.

Changing SHAs have broken Protobuf for Bazel users:

* https://github.com/google/protobuf/issues/3619
* https://github.com/google/protobuf/issues/3628
* https://github.com/google/protobuf/issues/3648

Other projects that have had builds broken by GitHub archive checksum changes include:
* Bazel: https://github.com/bazelbuild/bazel/issues/3722
* Kubernetes: https://github.com/kubernetes/kubernetes/issues/52307
* Homebrew: https://github.com/Homebrew/homebrew-core/issues/18044

**Comment by xfxyjwf** [comment]
@pherl is working on releasing a tar.gz with all languages.

**Comment by pherl** [comment]
Done.

**Comment by jmillikin-stripe** [comment]
Thanks!
