### ISSUE TITLE
Make fails for v3.5.0 on Ubuntu 17.10

### ISSUE THREAD

**Issue by NoahGleason** [google/protobuf#3897]
I checked out the repo, installed all the packages, and ran autogen and configure as instructed in the c++ installation. However, I got an error of `/bin/bash: line 1: $oldpwd/google/protobuf/compiler/js/well_known_types_embed.cc: ambiguous redirect` when I tried to run make. The full output is [here](https://pastebin.com/Tt7yHf8a).

**Comment by pherl** [comment]
Thanks for reporting. It will fixed in the next minor release. It seems your working directory contains whitespace. The workaround for now is to check out the repo in a directory without whitespace in its full path.

**Comment by hanalaydrus** [comment]
May I know which release this issue had fixed?

**Comment by pherl** [comment]
It will be fixed in the next minor release (probably sometime this week). Or you can try it in the 3.5.x branch

**Comment by liamfmoran** [comment]
I'm still getting the same issue with v3.5.1 with Windows Subsystem for Linux v16.04. The error occurs in the same location.
