### ISSUE TITLE
Allow extendable WellKnownTypeParser and  WellKnownTypePrinter for JsonFormat

### ISSUE THREAD

**Issue by cliveseldon** [google/protobuf#3906]
In Kubernetes' protos there is an [IntOrString](https://raw.githubusercontent.com/kubernetes/apimachinery/master/pkg/util/intstr/generated.proto) message which is able to be printed/parsed via Golang to an atomic type in JSON messages.

This is very similar to what is provided in [wrappers.proto](https://github.com/google/protobuf/blob/master/src/google/protobuf/wrappers.proto) and handled in JsonFormat. However, JSONFormat doesn't allow these Parsers/Printers to be extended by the user.

Can we extend JsonFormat to allow custom additions for formatting so examples such as IntOrString used in the Kubernetes project can be printed/parsed from atomic values?

**Comment by xfxyjwf** [comment]
JsonFormat implements proto3 JSON spec and for better interoperability between languages it is not intended to be customized.
