### ISSUE TITLE
py2.6 compatible?

### ISSUE THREAD

**Issue by wjo1212** [google/protobuf#3915]
I notice it's marked as py2.6 friendly. 
https://pypi.python.org/pypi/protobuf/3.5.0

But actually not, dict comprehension is used but actually not supported in Py2.6

```shell
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/google/protobuf/symbol_database.py", line 62, in <module>
    from google.protobuf import message_factory
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/google/protobuf/message_factory.py", line 142
    file_by_name = {file_proto.name: file_proto for file_proto in file_protos}
                                                  ^
SyntaxError: invalid syntax

```

**Comment by wjo1212** [comment]
I know, py2.6 is almost dead. but if we don't support this python version, we should remove it from setup.py and update the pypi

**Comment by pherl** [comment]
Yes, it's no longer supporting py2.6. I will update the setup.py

**Comment by wjo1212** [comment]
thanks for the confirmation, i'm curious why Travis-CI can pass run google protobuf on python 2.6 in past several weeks, but suddenly, it doesn't work last Sat as expected...

**Comment by anandolee** [comment]
New changes do not guarantee python 2.6.
We removed python 2.6 because Jenkins complains for it:
DEPRECATION: Python 2.6 is no longer supported by the Python core team

Not sure if it is related to your project.
