### ISSUE TITLE
How to get message level comments?

### ISSUE THREAD

**Issue by liuhan907** [google/protobuf#3920]
I write a plugin and I want to get message's comments, but I didn't find the interface to get the message comments. Can add this interface, or did I not find out?
ps: I use golang write plugin.

**Comment by xfxyjwf** [comment]
Comments are included in the SourceCodeInfo message as part of FileDescriptorProto:
https://github.com/google/protobuf/blob/master/src/google/protobuf/descriptor.proto#L842

If you use C++ to write the plugin, there are some helper APIs for you to retrieve the comments:
https://github.com/google/protobuf/blob/master/src/google/protobuf/descriptor.h#L416

It's built on top of the SourceCodeInfo message inside FileDescriptorProto and is more convenient to use than a raw FileDescriptorProto. Such support is available only in C++ and I would recommend using C++ to write the plugin instead.
