### ISSUE TITLE
%1 is not a valid Win32 application

### ISSUE THREAD

**Issue by fferri** [google/protobuf#3923]
I'm trying to get the Lua generator working on Windows (MSYS2/mingw64).
I installed 'protobuf' with luarocks.
It installed also the file /mingw64/lib/luarocks/rocks/protobuf/1.1.1-0/protoc-plugin/protoc-gen-lua, which I can run in a terminal without errors due to missing packages and such.
But if I run the protobuf compiler with this file as a plugin, I get:
```
$ protoc --plugin=protoc-gen-lua=/mingw64/lib/luarocks/rocks/protobuf/1.1.1-0/protoc-plugin/protoc-gen-lua --lua_out=. pubsub.proto
--lua_out: protoc-gen-lua: %1 is not a valid Win32 application.
```

Useful info:
```
$ pip3 show protobuf
Name: protobuf
Version: 3.4.0
Summary: Protocol Buffers
Home-page: https://developers.google.com/protocol-buffers/
Author: protobuf@googlegroups.com
Author-email: protobuf@googlegroups.com
License: 3-Clause BSD License
Location: /usr/lib/python3.6/site-packages
Requires: six, setuptools
```

**Comment by fferri** [comment]
is this article related? https://support.microsoft.com/en-us/help/812486/event-id-7000-and-1-is-not-a-valid-win32-application-error-message-whe

**Comment by xfxyjwf** [comment]
@fferri Could you attach the protoc-gen-lua binary you are using?

**Comment by fferri** [comment]
@xfxyjwf comes from https://github.com/urbanairship/protobuf-lua (inside protoc-plugin dir) it is a python script

**Comment by xfxyjwf** [comment]
@fferri Hmm, a python script? If I remember correctly, the plugin must be either a .exe or a .bat. Could you try to create a .bat wrapper about the python script and try again?

**Comment by xfxyjwf** [comment]
I have verified a .bat file will work. Just create a protoc-gen-lua.bat file with the following content:

```
@<path_to_python.exe> <path_to_protoc-gen-lua>
```

and invoke protoc with:

```
protoc --plugin=protoc-gen-lua=protoc-gen-lua.bat --lua_out=. <proto>
```
