### ISSUE TITLE
Is it normal to stuck for a long time while compiling?

### ISSUE THREAD

**Issue by PayneJoe** [google/protobuf#3930]
It begins to stuck when compiling 

> g++ -DHAVE_CONFIG_H -I. -I..  -I./../gmock/gtest/include -I./../gmock/include  -D_THREAD_SAFE  -DHAVE_PTHREAD=1 -DHAVE_ZLIB=1 -Wall -Wno-sign-compare -g -DNDEBUG -MT google/protobuf/util/internal/protobuf_test-protostream_objectsource_test.o -MD -MP -MF google/protobuf/util/internal/.deps/protobuf_test-protostream_objectsource_test.Tpo -c -o google/protobuf/util/internal/protobuf_test-protostream_objectsource_test.o `test -f 'google/protobuf/util/internal/protostream_objectsource_test.cc' || echo './'`google/protobuf/util/internal/protostream_objectsource_test.cc

and not going further any more one hour later. Is it normal? 

Much appreciated!

**Comment by xfxyjwf** [comment]
It's not normal. I think you should cancel the build if you can and try again.

Usually I get this same problem when I do "make -j" and it spawns too many concurrent build processes consuming all the memory leading to a computer freeze. When it happens, most of the time it won't recover and I have to force a reboot.

**Comment by PayneJoe** [comment]
@xfxyjwf , I am not sure it will be okay while using it if I skip the compiling step

> make check

**Comment by PayneJoe** [comment]
@xfxyjwf  by the way, is it just a resource problem? Can we get over with it if we have enough resource.

**Comment by xfxyjwf** [comment]
Does it get stuck every time? It should work if you just run "make check". If it doesn't, I would suspect a compiler bug and you can probably try upgrade your C++ compiler.

**Comment by alexthegreat63** [comment]
I'm having the same issue.

**Comment by PayneJoe** [comment]
@xfxyjwf  Yes, it does. By the way, I compile it with clang on my Mac Pro.
