### ISSUE TITLE
common js - "proto" and "COMPILED" are not defined in generated message_pb.js

### ISSUE THREAD

**Issue by jonathan-se** [google/protobuf#3931]
I'm designing a web app which communicates with a back-end server using protobuf messages and runs in the web browser.
I compiled the proto message to CommonJS and got the message_pb.js.
I also used npm install google-protobuf  to get the run-time library.
when I run the app I get the following multiple errors in the generated message_pb.js:
" **'proto' is not defined" and** " **'COMPILED' is not defined**"
The weird thing is that I can use serializeBinary(), deserializeBinary(), and the all the fields functions but afterwards it crashes immediately with the above errors.
whats wrong?

**Comment by deltaskelta** [comment]
@jonathan-se does this solution apply to you? https://github.com/improbable-eng/grpc-web/issues/96#issuecomment-347871452

**Comment by jonathan-se** [comment]
I'll try it, Thanks!

**Comment by dnuske** [comment]
@jonathan-se so how have you managed to solve this? I have the same situation and don't see any relation to the comment above

**Comment by xense** [comment]
@dnuske hope this helps
https://github.com/improbable-eng/grpc-web/issues/96#issuecomment-523448731
