### ISSUE TITLE
undefined reference to `google::protobuf::internal::Release_CompareAndSwap

### ISSUE THREAD

**Issue by Nayana-ibm** [google/protobuf#3937]
While compiling protobuf v3.5.0 on big endian, facing an issue 
`undefined reference to `google::protobuf::internal::Release_CompareAndSwap(long volatile*, long, long)'`

Need to add 64-bit version to `protobuf/src/google/protobuf/stubs/atomicops_internals_generic_gcc.h`

Similar issue was raised to add 64-bit versions: https://github.com/google/protobuf/pull/1044

**Comment by xfxyjwf** [comment]
Thanks for the report. Feel free to send us a pull request if you know of a working fix.

**Comment by Nayana-ibm** [comment]
Requires below patch in file protobuf/src/google/protobuf/stubs/atomicops_internals_generic_gcc.h 
```

--- a/src/google/protobuf/stubs/atomicops_internals_generic_gcc.h
+++ b/src/google/protobuf/stubs/atomicops_internals_generic_gcc.h
@@ -146,6 +146,15 @@ inline Atomic64 NoBarrier_Load(volatile const Atomic64* ptr) {
   return __atomic_load_n(ptr, __ATOMIC_RELAXED);
 }

+inline Atomic64 Release_CompareAndSwap(volatile Atomic64* ptr,
+                                       Atomic64 old_value,
+                                       Atomic64 new_value) {
+  __atomic_compare_exchange_n(ptr, &old_value, new_value, false,
+                              __ATOMIC_RELEASE, __ATOMIC_ACQUIRE);
+  return old_value;
+}
+
+
 #endif // defined(__LP64__)


 }  // namespace internal
```
