### ISSUE TITLE
install php protobuf c extension error 

### ISSUE THREAD

**Issue by jack15083** [google/protobuf#3943]
My os system is Ubuntu 16.04 and php version is 7.0.12,  all prerequirements tools are newest version. 

/data/git/protobuf-3.5.0/php/ext/google/protobuf/def.c: In function ‘zim_FieldDescriptor_getEnumType’:
/data/git/protobuf-3.5.0/php/ext/google/protobuf/def.c:485:5: warning: implicit declaration of function ‘zend_throw_exception’ [-Wimplicit-function-declaration]
     zend_throw_exception(NULL, error_msg, 0 TSRMLS_CC);
     ^
/bin/bash /data/git/protobuf-3.5.0/php/ext/google/protobuf/libtool --mode=compile cc  -I. -I/data/git/protobuf-3.5.0/php/ext/google/protobuf -DPHP_ATOM_INC -I/data/git/protobuf-3.5.0/php/ext/google/protobuf/include -I/data/git/protobuf-3.5.0/php/ext/google/protobuf/main -I/data/git/protobuf-3.5.0/php/ext/google/protobuf -I/usr/include/php/20151012 -I/usr/include/php/20151012/main -I/usr/include/php/20151012/TSRM -I/usr/include/php/20151012/Zend -I/usr/include/php/20151012/ext -I/usr/include/php/20151012/ext/date/lib  -DHAVE_CONFIG_H  -g -O2   -c /data/git/protobuf-3.5.0/php/ext/google/protobuf/encode_decode.c -o encode_decode.lo 
libtool: compile:  cc -I. -I/data/git/protobuf-3.5.0/php/ext/google/protobuf -DPHP_ATOM_INC -I/data/git/protobuf-3.5.0/php/ext/google/protobuf/include -I/data/git/protobuf-3.5.0/php/ext/google/protobuf/main -I/data/git/protobuf-3.5.0/php/ext/google/protobuf -I/usr/include/php/20151012 -I/usr/include/php/20151012/main -I/usr/include/php/20151012/TSRM -I/usr/include/php/20151012/Zend -I/usr/include/php/20151012/ext -I/usr/include/php/20151012/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /data/git/protobuf-3.5.0/php/ext/google/protobuf/encode_decode.c  -fPIC -DPIC -o .libs/encode_decode.o
/data/git/protobuf-3.5.0/php/ext/google/protobuf/encode_decode.c: In function ‘env_error_func’:
/data/git/protobuf-3.5.0/php/ext/google/protobuf/encode_decode.c:116:5: warning: implicit declaration of function ‘zend_throw_exception’ [-Wimplicit-function-declaration]
     zend_throw_exception(NULL, err_msg, 0 TSRMLS_CC);
     ^
/data/git/protobuf-3.5.0/php/ext/google/protobuf/encode_decode.c: In function ‘merge_from_string’:
/data/git/protobuf-3.5.0/php/ext/google/protobuf/encode_decode.c:1523:60: warning: passing argument 1 of ‘msgdef_decodermethod’ discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
   const upb_pbdecodermethod* method = msgdef_decodermethod(desc);
                                                            ^
/data/git/protobuf-3.5.0/php/ext/google/protobuf/encode_decode.c:1062:35: note: expected ‘Descriptor * {aka struct Descriptor *}’ but argument is of type ‘const Descriptor * {aka const struct Descriptor *}’
 static const upb_pbdecodermethod *msgdef_decodermethod(Descriptor* desc) {
                                   ^
/bin/bash /data/git/protobuf-3.5.0/php/ext/google/protobuf/libtool --mode=compile cc  -I. -I/data/git/protobuf-3.5.0/php/ext/google/protobuf -DPHP_ATOM_INC -I/data/git/protobuf-3.5.0/php/ext/google/protobuf/include -I/data/git/protobuf-3.5.0/php/ext/google/protobuf/main -I/data/git/protobuf-3.5.0/php/ext/google/protobuf -I/usr/include/php/20151012 -I/usr/include/php/20151012/main -I/usr/include/php/20151012/TSRM -I/usr/include/php/20151012/Zend -I/usr/include/php/20151012/ext -I/usr/include/php/20151012/ext/date/lib  -DHAVE_CONFIG_H  -g -O2   -c /data/git/protobuf-3.5.0/php/ext/google/protobuf/map.c -o map.lo 
libtool: compile:  cc -I. -I/data/git/protobuf-3.5.0/php/ext/google/protobuf -DPHP_ATOM_INC -I/data/git/protobuf-3.5.0/php/ext/google/protobuf/include -I/data/git/protobuf-3.5.0/php/ext/google/protobuf/main -I/data/git/protobuf-3.5.0/php/ext/google/protobuf -I/usr/include/php/20151012 -I/usr/include/php/20151012/main -I/usr/include/php/20151012/TSRM -I/usr/include/php/20151012/Zend -I/usr/include/php/20151012/ext -I/usr/include/php/20151012/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /data/git/protobuf-3.5.0/php/ext/google/protobuf/map.c  -fPIC -DPIC -o .libs/map.o
/bin/bash /data/git/protobuf-3.5.0/php/ext/google/protobuf/libtool --mode=compile cc  -I. -I/data/git/protobuf-3.5.0/php/ext/google/protobuf -DPHP_ATOM_INC -I/data/git/protobuf-3.5.0/php/ext/google/protobuf/include -I/data/git/protobuf-3.5.0/php/ext/google/protobuf/main -I/data/git/protobuf-3.5.0/php/ext/google/protobuf -I/usr/include/php/20151012 -I/usr/include/php/20151012/main -I/usr/include/php/20151012/TSRM -I/usr/include/php/20151012/Zend -I/usr/include/php/20151012/ext -I/usr/include/php/20151012/ext/date/lib  -DHAVE_CONFIG_H  -g -O2   -c /data/git/protobuf-3.5.0/php/ext/google/protobuf/message.c -o message.lo 
libtool: compile:  cc -I. -I/data/git/protobuf-3.5.0/php/ext/google/protobuf -DPHP_ATOM_INC -I/data/git/protobuf-3.5.0/php/ext/google/protobuf/include -I/data/git/protobuf-3.5.0/php/ext/google/protobuf/main -I/data/git/protobuf-3.5.0/php/ext/google/protobuf -I/usr/include/php/20151012 -I/usr/include/php/20151012/main -I/usr/include/php/20151012/TSRM -I/usr/include/php/20151012/Zend -I/usr/include/php/20151012/ext -I/usr/include/php/20151012/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /data/git/protobuf-3.5.0/php/ext/google/protobuf/message.c  -fPIC -DPIC -o .libs/message.o
/data/git/protobuf-3.5.0/php/ext/google/protobuf/message.c: In function ‘message_free’:
/data/git/protobuf-3.5.0/php/ext/google/protobuf/message.c:85:5: warning: implicit declaration of function ‘stringsink_uninit’ [-Wimplicit-function-declaration]
     stringsink_uninit(*(void**)intern->data);
     ^
/data/git/protobuf-3.5.0/php/ext/google/protobuf/message.c: In function ‘zim_Any_unpack’:
/data/git/protobuf-3.5.0/php/ext/google/protobuf/message.c:936:5: warning: implicit declaration of function ‘zend_throw_exception’ [-Wimplicit-function-declaration]

**Comment by TeBoring** [comment]
I see there is only warnings here. You are safe to ignore them.

**Comment by TeBoring** [comment]
Is there still problem?
