### ISSUE TITLE
Exception not caught in parseFromJsonStream function

### ISSUE THREAD

**Issue by hasu94** [google/protobuf#3944]
https://github.com/google/protobuf/blob/master/php/src/Google/Protobuf/Internal/Message.php#L1076

The `Message` class is under namespace `Google\Protobuf\Internal` but I see we are trying to catch the `\Exception` exception.
We need to add a backslash before the `Exception` to make it work properly.

**Comment by hasu94** [comment]
Here's the pull request
https://github.com/google/protobuf/pull/3945

**Comment by hasu94** [comment]
I've added backslashes in the phpdoc blocks in my pull request.

**Comment by TeBoring** [comment]
Fixed in 3.5.1
