### ISSUE TITLE
why ZigZagDecode32 is different between 3.5.0 and 3.3.0 version?

### ISSUE THREAD

**Issue by ookk** [google/protobuf#3947]
it's the code in 3.3.0 version:
inline int32 WireFormatLite::ZigZagDecode32(uint32 n) {
  return (n >> 1) ^ -static_cast<int32>(n & 1);
}

and the code in 3.5.0 version:
inline int32 WireFormatLite::ZigZagDecode32(uint32 n) {
  // Note:  Using unsigned types prevent undefined behavior
  return static_cast<int32>((n >> 1) ^ -(n & 1));
}

the code in 3.5.0 compile failed and the log is :
consoleapplication1\consoleapplication1\google\protobuf\wire_format_lite.h(863): error C4146: 一元负运算符应用于无符号类型，结果仍为无符号类型

**Comment by pherl** [comment]
I'd suggest turning off C4146 warning for now while we are looking for a fix.

**Comment by andschwa** [comment]
The unfortunate thing is that it appears that any file which includes a generated protobuf header also ends up including `wire_format_lite.h`, so this particular warning is regenerated _so many times_.

**Comment by acozzette** [comment]
I believe this was fixed in pull request #4000, though that was too late to make into the 3.5 release.

**Comment by andschwa** [comment]
@acozzette Thanks for the pointer, I'll add that as a patch to our build. Having trouble getting `/wd4146` to propogate everywhere... so we'll just kill the warning at the source :D
