### ISSUE TITLE
ObjectiveC plugin breaks windows build

### ISSUE THREAD

**Issue by jtattermusch** [google/protobuf#395]
-- libprotoc.vcproj doesn't contain objectivec generator files.
(fix for that one is here: https://github.com/jtattermusch/protobuf/tree/objectivec_partial_fix)

-- Use of posix headers:
Error	30	error C1083: Cannot open include file: 'arpa/inet.h': No such file or directory	c:\users\jtattermusch\github\protobuf\src\google\protobuf\compiler\objectivec\objectivec_helpers.cc	31	1	libprotoc
Error	45	error C1083: Cannot open include file: 'netinet/in.h': No such file or directory	c:\users\jtattermusch\github\protobuf\src\google\protobuf\compiler\objectivec\objectivec_field.cc	43	1	libprotoc

-- Use of int32_t
Error	47	error C2065: 'int32_t' : undeclared identifier	c:\users\jtattermusch\github\protobuf\src\google\protobuf\compiler\objectivec\objectivec_helpers.h	168	1	libprotoc

-- possibly other problems

**Comment by jtattermusch** [comment]
@jcanizales, this is a release blocker

**Comment by jcanizales** [comment]
Do we expect users to want to generate Objective-C code in a Windows machine? This is not a release blocker for the proto3 and gRPC Objective-C plugins, as the user is expected to use a Mac. So can we exclude both plugins from Windows builds so that C# isn't blocked by it?

@thomasvl @dmaclach

**Comment by jtattermusch** [comment]
protoc is supposed to compile on all supported platforms and it should be the same thing on all of them - so I don't think stripping away objective C generator from protoc on windows is an option at all. 

The only reasonable solution here seems to be fixing the objective C generator to compile properly on windows. I haven't checked the code much yet, but I don't see a reason why one would need to use headers like  arpa/inet.h in a code generator?

@pherl

**Comment by jcanizales** [comment]
I don't know what are those headers used for, but from taking a look at it the plugin does more than generate code, e.g. it reads an environment variable and writes stuff to a file.

In any case, the obvious engineering question to ask is why would we want to spend resources porting to Windows a piece of software whose users are all forced to use Macs (in order to run XCode). I.e. what is the use case we want to block the release for.

**Comment by thomasvl** [comment]
Nothing says they have to have a Mac and Xcode to use ObjC - http://appleinsider.com/articles/15/04/29/microsoft-hopes-to-court-ios-apps-to-windows-10-with-objective-c-support

I'd say it is no different they asking if people on windows really need python, etc. Just because it is common doesn't mean we shouldn't support it.

As far as arpa/inet.h and some others, left over from when it was first started to be ported to also run on linux.  They can/should be cleaned up.

**Comment by jcanizales** [comment]
That use case is exciting. My experience has been porting code to other platforms is a lot of effort, but if there's adequate C.I. support and it's just a matter of _removing_ stuff from the current code, maybe it's worth doing it now indeed.

**Comment by pherl** [comment]
At least it should not break the build on windows protoc. @thomasvl does the codegen really need the platform dependent libraries? How hard is it to make it portable?

**Comment by jtattermusch** [comment]
Things I noticed that need to be made portable:
-- use of getenv (should work fine once correct headers are used).
-- use of open, close, flock, htonl.
-- maybe something more

Why are you using open and close to write files instead of using the concept of printers that is supported by libprotoc (and used by all the other languages)?

**Comment by thomasvl** [comment]
On Mon, May 18, 2015 at 12:19 PM, Jan Tattermusch <notifications@github.com>
wrote:

> Things I noticed that need to be made portable:
> -- use of getenv (should work fine once correct headers are used).
> -- use of open, close, flock, htonl.
> -- maybe something more
>
> Why are you using open and close to write files instead of using the
> concept of printers that is supported by libprotoc (and used by all the
> other languages)?
>

They aren't for the generated sources, ObjC supports a whilelisting of
symbols because ObjC doesn't strip ObjC symbols, so it is needed to keep
the generated code down to what is directly needed.  It has been needed for
.protos that define too many Messages/Extensions in a single .proto file
(and clients tend not to need all of them).

**Comment by thomasvl** [comment]
On Mon, May 18, 2015 at 12:24 PM, Thomas Van Lenten <thomasvl@google.com>
wrote:

>
> On Mon, May 18, 2015 at 12:19 PM, Jan Tattermusch <
> notifications@github.com> wrote:
>
>> Things I noticed that need to be made portable:
>> -- use of getenv (should work fine once correct headers are used).
>> -- use of open, close, flock, htonl.
>> -- maybe something more
>>
>> Why are you using open and close to write files instead of using the
>> concept of printers that is supported by libprotoc (and used by all the
>> other languages)?
>>
> They aren't for the generated sources, ObjC supports a whilelisting of
> symbols because ObjC doesn't strip ObjC symbols, so it is needed to keep
> the generated code down to what is directly needed.  It has been needed for
> .protos that define too many Messages/Extensions in a single .proto file
> (and clients tend not to need all of them).
>

Oh, and the locks can be needed if you are running protoc in parallel
across inputs for faster builds.

**Comment by jtattermusch** [comment]
I got down to a point where I get these errors:
Error	9	error C2065: 'LOCK_EX' : undeclared identifier	c:\users\jtattermusch\github\protobuf\src\google\protobuf\compiler\objectivec\objectivec_helpers.cc	826	1	libprotoc
Error	2	error C2065: 'O_APPEND' : undeclared identifier	c:\users\jtattermusch\github\protobuf\src\google\protobuf\compiler\objectivec\objectivec_helpers.cc	810	1	libprotoc
Error	3	error C2065: 'O_CREAT' : undeclared identifier	c:\users\jtattermusch\github\protobuf\src\google\protobuf\compiler\objectivec\objectivec_helpers.cc	810	1	libprotoc
Error	1	error C2065: 'O_WRONLY' : undeclared identifier	c:\users\jtattermusch\github\protobuf\src\google\protobuf\compiler\objectivec\objectivec_helpers.cc	810	1	libprotoc
Error	6	error C2065: 'S_IRGRP' : undeclared identifier	c:\users\jtattermusch\github\protobuf\src\google\protobuf\compiler\objectivec\objectivec_helpers.cc	811	1	libprotoc
Error	7	error C2065: 'S_IROTH' : undeclared identifier	c:\users\jtattermusch\github\protobuf\src\google\protobuf\compiler\objectivec\objectivec_helpers.cc	811	1	libprotoc
Error	4	error C2065: 'S_IRUSR' : undeclared identifier	c:\users\jtattermusch\github\protobuf\src\google\protobuf\compiler\objectivec\objectivec_helpers.cc	811	1	libprotoc
Error	5	error C2065: 'S_IWUSR' : undeclared identifier	c:\users\jtattermusch\github\protobuf\src\google\protobuf\compiler\objectivec\objectivec_helpers.cc	811	1	libprotoc
Error	12	error C3861: 'close': identifier not found	c:\users\jtattermusch\github\protobuf\src\google\protobuf\compiler\objectivec\objectivec_helpers.cc	840	1	libprotoc
Error	10	error C3861: 'flock': identifier not found	c:\users\jtattermusch\github\protobuf\src\google\protobuf\compiler\objectivec\objectivec_helpers.cc	826	1	libprotoc
Error	8	error C3861: 'open': identifier not found	c:\users\jtattermusch\github\protobuf\src\google\protobuf\compiler\objectivec\objectivec_helpers.cc	810	1	libprotoc
Error	11	error C3861: 'write': identifier not found	c:\users\jtattermusch\github\protobuf\src\google\protobuf\compiler\objectivec\objectivec_helpers.cc	839	1	libprotoc
Warning	13	warning C4715: 'google::protobuf::compiler::objectivec::`anonymous namespace'::OrderGroupForFieldDescriptor' : not all control paths return a value	c:\users\jtattermusch\github\protobuf\src\google\protobuf\compiler\objectivec\objectivec_message.cc	122	1	libprotoc
Warning	14	warning C4715: 'google::protobuf::compiler::objectivec::`anonymous namespace'::PrimitiveArrayTypeName' : not all control paths return a value	c:\users\jtattermusch\github\protobuf\src\google\protobuf\compiler\objectivec\objectivec_primitive_field.cc	107	1	libprotoc
Warning	15	warning C4715: 'google::protobuf::compiler::objectivec::`anonymous namespace'::PrimitiveTypeName' : not all control paths return a value	c:\users\jtattermusch\github\protobuf\src\google\protobuf\compiler\objectivec\objectivec_primitive_field.cc	79	1	libprotoc


@thomasvl , do you think you will be able to take a look at them?  I can share the changes I have so far.

**Comment by thomasvl** [comment]
On Mon, May 18, 2015 at 12:45 PM, Jan Tattermusch <notifications@github.com>
wrote:

> I got down to a point where I get these errors:
> Error 9 error C2065: 'LOCK_EX' : undeclared identifier
> c:\users\jtattermusch\github\protobuf\src\google\protobuf\compiler\objectivec\objectivec_helpers.cc
> 826 1 libprotoc
> Error 2 error C2065: 'O_APPEND' : undeclared identifier
> c:\users\jtattermusch\github\protobuf\src\google\protobuf\compiler\objectivec\objectivec_helpers.cc
> 810 1 libprotoc
> Error 3 error C2065: 'O_CREAT' : undeclared identifier
> c:\users\jtattermusch\github\protobuf\src\google\protobuf\compiler\objectivec\objectivec_helpers.cc
> 810 1 libprotoc
> Error 1 error C2065: 'O_WRONLY' : undeclared identifier
> c:\users\jtattermusch\github\protobuf\src\google\protobuf\compiler\objectivec\objectivec_helpers.cc
> 810 1 libprotoc
> Error 6 error C2065: 'S_IRGRP' : undeclared identifier
> c:\users\jtattermusch\github\protobuf\src\google\protobuf\compiler\objectivec\objectivec_helpers.cc
> 811 1 libprotoc
> Error 7 error C2065: 'S_IROTH' : undeclared identifier
> c:\users\jtattermusch\github\protobuf\src\google\protobuf\compiler\objectivec\objectivec_helpers.cc
> 811 1 libprotoc
> Error 4 error C2065: 'S_IRUSR' : undeclared identifier
> c:\users\jtattermusch\github\protobuf\src\google\protobuf\compiler\objectivec\objectivec_helpers.cc
> 811 1 libprotoc
> Error 5 error C2065: 'S_IWUSR' : undeclared identifier
> c:\users\jtattermusch\github\protobuf\src\google\protobuf\compiler\objectivec\objectivec_helpers.cc
> 811 1 libprotoc
> Error 12 error C3861: 'close': identifier not found
> c:\users\jtattermusch\github\protobuf\src\google\protobuf\compiler\objectivec\objectivec_helpers.cc
> 840 1 libprotoc
> Error 10 error C3861: 'flock': identifier not found
> c:\users\jtattermusch\github\protobuf\src\google\protobuf\compiler\objectivec\objectivec_helpers.cc
> 826 1 libprotoc
> Error 8 error C3861: 'open': identifier not found
> c:\users\jtattermusch\github\protobuf\src\google\protobuf\compiler\objectivec\objectivec_helpers.cc
> 810 1 libprotoc
> Error 11 error C3861: 'write': identifier not found
> c:\users\jtattermusch\github\protobuf\src\google\protobuf\compiler\objectivec\objectivec_helpers.cc
> 839 1 libprotoc
> Warning 13 warning C4715: 'google::protobuf::compiler::objectivec::anonymous
> namespace'::OrderGroupForFieldDescriptor' : not all control paths return a
> value
> c:\users\jtattermusch\github\protobuf\src\google\protobuf\compiler\objectivec\objectivec_message.cc
> 122 1 libprotoc
> Warning 14 warning C4715: 'google::protobuf::compiler::objectivec::anonymous
> namespace'::PrimitiveArrayTypeName' : not all control paths return a value
> c:\users\jtattermusch\github\protobuf\src\google\protobuf\compiler\objectivec\objectivec_primitive_field.cc
> 107 1 libprotoc
> Warning 15 warning C4715:
> 'google::protobuf::compiler::objectivec::`anonymous
> namespace'::PrimitiveTypeName' : not all control paths return a value
> c:\users\jtattermusch\github\protobuf\src\google\protobuf\compiler\objectivec\objectivec_primitive_field.cc
> 79 1 libprotoc
>
> @thomasvl <https://github.com/thomasvl> , do you think you will be able
> to take a look at them? I can share the changes I have so far.
>
>
>
Sure, just started looking at things now.

**Comment by jtattermusch** [comment]
My code so far is here:
https://github.com/jtattermusch/protobuf/tree/objectivec_partial_fix

**Comment by thomasvl** [comment]
@jtattermusch can you give https://github.com/thomasvl/protobuf/tree/objc_on_win a try?  I trimmed out a bunch, so hopefully it will work on Window.

**Comment by jtattermusch** [comment]
@thomasvl  I tried and it looks pretty good.

You're missing  #include <stdint.h> in  objectivec_helpers.h (to declare the type int32_t).

Also, I see this warning:
2>c:\users\jtattermusch\github\protobuf\src\google\protobuf\compiler\objectivec\objectivec_message.cc(122): warning C4715: 'google::protobuf::compiler::objectivec::`anonymous namespace'::OrderGroupForFieldDescriptor' : not all control paths return a value


Besides that, I see an error when compiling tests project (but that seems to be unrelated)
Error	3	error C2385: ambiguous access of 'arena_'	c:\users\jtattermusch\github\protobuf\src\google\protobuf\map_field_inl.h	215	1	tests

**Comment by thomasvl** [comment]
New diffs up, I switched to using the int32 provided by the proto code instead.  Should resolve it.

**Comment by jtattermusch** [comment]
Error	44	error C2065: 'kAddUnderscore' : undeclared identifier	c:\users\jtattermusch\github\protobuf\src\google\protobuf\compiler\objectivec\objectivec_helpers.cc	923	1	libprotoc
Error	55	error C2065: 'kOpAllUpper' : undeclared identifier	c:\users\jtattermusch\github\protobuf\src\google\protobuf\compiler\objectivec\objectivec_helpers.cc	973	1	libprotoc
Error	57	error C2065: 'kOpAllUpper' : undeclared identifier	c:\users\jtattermusch\github\protobuf\src\google\protobuf\compiler\objectivec\objectivec_helpers.cc	986	1	libprotoc
Error	48	error C2065: 'kOpAsIs' : undeclared identifier	c:\users\jtattermusch\github\protobuf\src\google\protobuf\compiler\objectivec\objectivec_helpers.cc	932	1	libprotoc
Error	52	error C2065: 'kOpFirstLower' : undeclared identifier	c:\users\jtattermusch\github\protobuf\src\google\protobuf\compiler\objectivec\objectivec_helpers.cc	936	1	libprotoc
Error	50	error C2065: 'kOpFirstUpper' : undeclared identifier	c:\users\jtattermusch\github\protobuf\src\google\protobuf\compiler\objectivec\objectivec_helpers.cc	934	1	libprotoc
Error	11	error C2065: 'length' : undeclared identifier	c:\users\jtattermusch\github\protobuf\src\google\protobuf\compiler\objectivec\objectivec_helpers.cc	742	1	libprotoc
Error	12	error C2065: 'length' : undeclared identifier	c:\users\jtattermusch\github\protobuf\src\google\protobuf\compiler\objectivec\objectivec_helpers.cc	743	1	libprotoc
Error	60	error C2065: 'length' : undeclared identifier	c:\users\jtattermusch\github\protobuf\src\google\protobuf\compiler\objectivec\objectivec_field.cc	106	1	libprotoc
Error	61	error C2065: 'length' : undeclared identifier	c:\users\jtattermusch\github\protobuf\src\google\protobuf\compiler\objectivec\objectivec_field.cc	107	1	libprotoc
Error	62	error C2065: 'length' : undeclared identifier	c:\users\jtattermusch\github\protobuf\src\google\protobuf\compiler\objectivec\objectivec_field.cc	108	1	libprotoc
Error	41	error C2065: 'op' : undeclared identifier	c:\users\jtattermusch\github\protobuf\src\google\protobuf\compiler\objectivec\objectivec_helpers.cc	922	1	libprotoc
Error	43	error C2065: 'op' : undeclared identifier	c:\users\jtattermusch\github\protobuf\src\google\protobuf\compiler\objectivec\objectivec_helpers.cc	923	1	libprotoc
Error	45	error C2065: 'op' : undeclared identifier	c:\users\jtattermusch\github\protobuf\src\google\protobuf\compiler\objectivec\objectivec_helpers.cc	924	1	libprotoc
Error	46	error C2065: 'op' : undeclared identifier	c:\users\jtattermusch\github\protobuf\src\google\protobuf\compiler\objectivec\objectivec_helpers.cc	925	1	libprotoc
Error	42	error C2065: 'op_' : undeclared identifier	c:\users\jtattermusch\github\protobuf\src\google\protobuf\compiler\objectivec\objectivec_helpers.cc	922	1	libprotoc
Error	47	error C2065: 'op_' : undeclared identifier	c:\users\jtattermusch\github\protobuf\src\google\protobuf\compiler\objectivec\objectivec_helpers.cc	932	1	libprotoc
Error	49	error C2065: 'op_' : undeclared identifier	c:\users\jtattermusch\github\protobuf\src\google\protobuf\compiler\objectivec\objectivec_helpers.cc	934	1	libprotoc
Error	51	error C2065: 'op_' : undeclared identifier	c:\users\jtattermusch\github\protobuf\src\google\protobuf\compiler\objectivec\objectivec_helpers.cc	936	1	libprotoc
Error	53	error C2065: 'op_' : undeclared identifier	c:\users\jtattermusch\github\protobuf\src\google\protobuf\compiler\objectivec\objectivec_helpers.cc	947	1	libprotoc
Error	54	error C2065: 'op_' : undeclared identifier	c:\users\jtattermusch\github\protobuf\src\google\protobuf\compiler\objectivec\objectivec_helpers.cc	973	1	libprotoc
Error	56	error C2065: 'op_' : undeclared identifier	c:\users\jtattermusch\github\protobuf\src\google\protobuf\compiler\objectivec\objectivec_helpers.cc	986	1	libprotoc
Error	9	error C2065: 'uint32_t' : undeclared identifier	c:\users\jtattermusch\github\protobuf\src\google\protobuf\compiler\objectivec\objectivec_helpers.cc	742	1	libprotoc
Error	58	error C2065: 'uint32_t' : undeclared identifier	c:\users\jtattermusch\github\protobuf\src\google\protobuf\compiler\objectivec\objectivec_field.cc	106	1	libprotoc
Error	13	error C2070: 'unknown-type': illegal sizeof operand	c:\users\jtattermusch\github\protobuf\src\google\protobuf\compiler\objectivec\objectivec_helpers.cc	743	1	libprotoc
Error	63	error C2070: 'unknown-type': illegal sizeof operand	c:\users\jtattermusch\github\protobuf\src\google\protobuf\compiler\objectivec\objectivec_field.cc	108	1	libprotoc
Error	20	error C2086: 'const int google::protobuf::compiler::objectivec::`anonymous-namespace'::DecodeDataBuilder::uint8_t' : redefinition	c:\users\jtattermusch\github\protobuf\src\google\protobuf\compiler\objectivec\objectivec_helpers.cc	909	1	libprotoc
Error	25	error C2086: 'const int google::protobuf::compiler::objectivec::`anonymous-namespace'::DecodeDataBuilder::uint8_t' : redefinition	c:\users\jtattermusch\github\protobuf\src\google\protobuf\compiler\objectivec\objectivec_helpers.cc	910	1	libprotoc
Error	30	error C2086: 'const int google::protobuf::compiler::objectivec::`anonymous-namespace'::DecodeDataBuilder::uint8_t' : redefinition	c:\users\jtattermusch\github\protobuf\src\google\protobuf\compiler\objectivec\objectivec_helpers.cc	911	1	libprotoc
Error	35	error C2086: 'const int google::protobuf::compiler::objectivec::`anonymous-namespace'::DecodeDataBuilder::uint8_t' : redefinition	c:\users\jtattermusch\github\protobuf\src\google\protobuf\compiler\objectivec\objectivec_helpers.cc	912	1	libprotoc
Error	16	error C2143: syntax error : missing ';' before '='	c:\users\jtattermusch\github\protobuf\src\google\protobuf\compiler\objectivec\objectivec_helpers.cc	907	1	libprotoc
Error	21	error C2143: syntax error : missing ';' before '='	c:\users\jtattermusch\github\protobuf\src\google\protobuf\compiler\objectivec\objectivec_helpers.cc	909	1	libprotoc
Error	26	error C2143: syntax error : missing ';' before '='	c:\users\jtattermusch\github\protobuf\src\google\protobuf\compiler\objectivec\objectivec_helpers.cc	910	1	libprotoc
Error	31	error C2143: syntax error : missing ';' before '='	c:\users\jtattermusch\github\protobuf\src\google\protobuf\compiler\objectivec\objectivec_helpers.cc	911	1	libprotoc
Error	36	error C2143: syntax error : missing ';' before '='	c:\users\jtattermusch\github\protobuf\src\google\protobuf\compiler\objectivec\objectivec_helpers.cc	912	1	libprotoc
Error	15	error C2146: syntax error : missing ';' before identifier 'kAddUnderscore'	c:\users\jtattermusch\github\protobuf\src\google\protobuf\compiler\objectivec\objectivec_helpers.cc	907	1	libprotoc
Error	34	error C2146: syntax error : missing ';' before identifier 'kOpAllUpper'	c:\users\jtattermusch\github\protobuf\src\google\protobuf\compiler\objectivec\objectivec_helpers.cc	912	1	libprotoc
Error	19	error C2146: syntax error : missing ';' before identifier 'kOpAsIs'	c:\users\jtattermusch\github\protobuf\src\google\protobuf\compiler\objectivec\objectivec_helpers.cc	909	1	libprotoc
Error	29	error C2146: syntax error : missing ';' before identifier 'kOpFirstLower'	c:\users\jtattermusch\github\protobuf\src\google\protobuf\compiler\objectivec\objectivec_helpers.cc	911	1	libprotoc
Error	24	error C2146: syntax error : missing ';' before identifier 'kOpFirstUpper'	c:\users\jtattermusch\github\protobuf\src\google\protobuf\compiler\objectivec\objectivec_helpers.cc	910	1	libprotoc
Error	10	error C2146: syntax error : missing ';' before identifier 'length'	c:\users\jtattermusch\github\protobuf\src\google\protobuf\compiler\objectivec\objectivec_helpers.cc	742	1	libprotoc
Error	59	error C2146: syntax error : missing ';' before identifier 'length'	c:\users\jtattermusch\github\protobuf\src\google\protobuf\compiler\objectivec\objectivec_field.cc	106	1	libprotoc
Error	40	error C2146: syntax error : missing ';' before identifier 'op'	c:\users\jtattermusch\github\protobuf\src\google\protobuf\compiler\objectivec\objectivec_helpers.cc	922	1	libprotoc
Error	38	error C2146: syntax error : missing ';' before identifier 'op_'	c:\users\jtattermusch\github\protobuf\src\google\protobuf\compiler\objectivec\objectivec_helpers.cc	954	1	libprotoc
Error	17	error C2238: unexpected token(s) preceding ';'	c:\users\jtattermusch\github\protobuf\src\google\protobuf\compiler\objectivec\objectivec_helpers.cc	907	1	libprotoc
Error	22	error C2238: unexpected token(s) preceding ';'	c:\users\jtattermusch\github\protobuf\src\google\protobuf\compiler\objectivec\objectivec_helpers.cc	909	1	libprotoc
Error	27	error C2238: unexpected token(s) preceding ';'	c:\users\jtattermusch\github\protobuf\src\google\protobuf\compiler\objectivec\objectivec_helpers.cc	910	1	libprotoc
Error	32	error C2238: unexpected token(s) preceding ';'	c:\users\jtattermusch\github\protobuf\src\google\protobuf\compiler\objectivec\objectivec_helpers.cc	911	1	libprotoc
Error	37	error C2238: unexpected token(s) preceding ';'	c:\users\jtattermusch\github\protobuf\src\google\protobuf\compiler\objectivec\objectivec_helpers.cc	912	1	libprotoc
Error	14	error C4430: missing type specifier - int assumed. Note: C++ does not support default-int	c:\users\jtattermusch\github\protobuf\src\google\protobuf\compiler\objectivec\objectivec_helpers.cc	907	1	libprotoc
Error	18	error C4430: missing type specifier - int assumed. Note: C++ does not support default-int	c:\users\jtattermusch\github\protobuf\src\google\protobuf\compiler\objectivec\objectivec_helpers.cc	909	1	libprotoc
Error	23	error C4430: missing type specifier - int assumed. Note: C++ does not support default-int	c:\users\jtattermusch\github\protobuf\src\google\protobuf\compiler\objectivec\objectivec_helpers.cc	910	1	libprotoc
Error	28	error C4430: missing type specifier - int assumed. Note: C++ does not support default-int	c:\users\jtattermusch\github\protobuf\src\google\protobuf\compiler\objectivec\objectivec_helpers.cc	911	1	libprotoc
Error	33	error C4430: missing type specifier - int assumed. Note: C++ does not support default-int	c:\users\jtattermusch\github\protobuf\src\google\protobuf\compiler\objectivec\objectivec_helpers.cc	912	1	libprotoc
Error	39	error C4430: missing type specifier - int assumed. Note: C++ does not support default-int	c:\users\jtattermusch\github\protobuf\src\google\protobuf\compiler\objectivec\objectivec_helpers.cc	954	1	libprotoc

**Comment by jtattermusch** [comment]
Let me know if you need more info about those.

**Comment by thomasvl** [comment]
branch updated (got the rest of the [u]int(8,32)_t usage this time).
