### ISSUE TITLE
Code plagiarism

### ISSUE THREAD

**Issue by wenyangfu** [google/protobuf#3950]
Your code has been plagiarized without attribution by the xLearn project. Their [scoped_ptr implementation](https://github.com/aksnzhy/xlearn/blob/master/src/base/scoped_ptr.h)
is lifted from
https://github.com/google/protobuf/blob/master/src/google/protobuf/stubs/scoped_ptr.h

xLearn also seems to plagiarize other projects, so Protobuf is not the only project affected.

**Comment by pherl** [comment]
Thanks for reporting. I created an issue on xlearn project for this.

**Comment by wenyangfu** [comment]
No problem. There's also other copied code without correct copyright/attributions, including some open source Google code from other projects, for example:
https://github.com/aksnzhy/xlearn/blob/master/src/base/stringprintf.h#L29:20

I also don't know if the project's license choice of Apache 2.0 conflicts with Google's licensing, so I'll defer to you and other folks at Google.
