### ISSUE TITLE
`Swap` is a de-facto reserved keyword of protobuf

### ISSUE THREAD

**Issue by stefanofiorentino** [google/protobuf#3953]
The following code causes compilers to fail because of the de-facto reserved message name Swap (with S uppercase):
```
syntax = "proto3";
message Swap
{
    string name = 1;
}
```
and the error is 
```
Swap.pb.cc:347:28: error: return type specification for constructor invalid
 void Swap::Swap(Swap* other) { 
```
This is because Swap has already been defined as a member function for all protobuf objects (expected to act as std::swap). 

To reproduce this compile-time issue, type this:
```
protoc ./proto/swap.proto --cpp_out=./
g++ -c ./proto/swap.pb.cc -I.
```

**Comment by pherl** [comment]
I guess this applies to other function names too, but I don't think there's much we can do. Disallowing Swap or renaming Swap are both breaking changes.
