### ISSUE TITLE
Lots (and lots) or warnings building on Windows Visual C++ (2015)

### ISSUE THREAD

**Issue by gatkinso** [google/protobuf#3969]
Lot's of these warnings on Visual C++ 2015:

google/protobuf/generated_message_util.h(160): warning C4800: 'google::protobuf::uint32': forcing value to bool 'true' or 'false' (performance warning) 

google/protobuf/map_type_handler.h(732): warning C4800: 'int': forcing value to bool 'true' or 'false' (performance warning) 

google/protobuf/map_field_inl.h(236): warning C4800:'google::protobuf::Map<std::string,google::protobuf::int32>:: std::size_type': forcing value to bool 'true' or 'false' (performance warning)

google/protobuf/wire_format_lite.h(874): warning C4146: unary minus operator applied to unsigned type, result still unsigned

Fixing these 4 warnings would silence compiler chatter (on my builds) significantly.

**Comment by pherl** [comment]
This should have already been fixed. (warnings suppressed).

**Comment by ipechorin** [comment]
Some of the warnings are still there in 3.9.0 (Visual C++ 2015):

google/protobuf/parse_context.h(615): warning C4100: 'field_name': unreferenced formal parameter

google/protobuf/map_type_handler.h(493): warning C4800: 'google::protobuf::uint64': forcing value to bool 'true' or 'false' (performance warning)
