### ISSUE TITLE
php namespace support for GPBMetadata

### ISSUE THREAD

**Issue by cc5092** [google/protobuf#3970]
#3162 

> TeBoring commented on 2 Jun
I don't think we need to change the namespace of GPBMetadata files. These files are transparent to users.

As you said, these GPBMetadata files are transparent to users. But I think it still makes sense to add namespace for GPBMetadata file.

Suppose I have 2 grpc go services and are developed by different teams. They define the protobuf file by "user.proto". this "user.proto" will generate a GPBMetadata\User.php file.

My laravel project needs to use both two grpc services they provided and for the psr-4 autoload, the composer.json file needs to be defined as follows: 

```json
"autoload": {
    "psr-4": {
        "App\\": "app/"
    },
    "classmap": [
        "app/FirstService/GPBMetadata/",
        "app/SecondService/GPBMetadata/"
    ]
}
```

Executing "composer dumpautoload" in the root directory of project, and we will get notice like this:
> Warning: Ambiguous class resolution, "GPBMetadata\User" was found in both "$baseDir . 'app/FirstService/GPBMetadata/User.php" and "path_to_proj/app/SecondService/GPBMetadata/User.php", the first will be used.

So I think it makes sense to add GPBMetadata namespace support. 

Looking forward to your reply.

ping @TeBoring

**Comment by TeBoring** [comment]
I see this is a problem. The current namespace of GPBMetatdata file is related to the place of proto file, e.g., foo/bar.proto will become GPBMetadata/Foo/Bar.php
One way to solve this is the way you mentioned.
The other way is that user could put their proto files in a unique place, e.g., first_service/user.proto and second_service/user.proto will become GPBMetadata/FirstService/User.php and GPBMetadata/SecondService/User.php.
As far as I see, both ways needs action from the user side. However, the second option has fewer maintaining cost, because user only need to put all proto files there. The first option will need to add the file option in every proto file.

**Comment by cc5092** [comment]
Hi
I can't do like your second option to generate GPBMetadata/FirstService/User.php.
Here is my code tree path.
![image](https://user-images.githubusercontent.com/7655917/33361587-be7461f8-d513-11e7-9b1b-ce81883210b2.png)

current pwd is path_to_proj/proto/ and the compile command is
> protoc --proto_path=first/ --php_out=.  --grpc_out=. --plugin=protoc-gen-grpc=/usr/local/bin/grpc_php_plugin first/*.proto

The Pb class generate namespace successfully by option php_namespace in proto file. But the GPBMetadata still generate as GPBMetadata\User.php.

**Comment by TeBoring** [comment]
Is --proto_path=first/ required? If it is removed, you can get GPBMetadata\First\User.php

**Comment by TeBoring** [comment]
The import in your proto file may need to be changed accordingly.

**Comment by cc5092** [comment]
Ok, I tried second option, it works fine. thank you. @TeBoring 

The remain problem is the namespace of GPBMetadata is not the same with the stub class.

For example. stub class namespace is "FirstService\User.php", but GPBMetadata is "GPBMetadata\FirstService\User.php". It's better if is "FirstService\GPBMetadata\User.php".

**Comment by cc5092** [comment]
And for psr-4 autoload, namespace like "FirstService\GPBMetadata\User.php" makes sense for create standalone library for other developer to import.

**Comment by fiboknacky** [comment]
+1 for this.
It'd be great if the GPBMetadata is generated based on the proto option for specifying namespaces.

**Comment by andydeng** [comment]
+1. This issue affects our project too. It will be great if we can choose GPBMetadata's namespace.

**Comment by atrauzzi** [comment]
Looking forward to seeing this resolved, would hate to get collisions in any projects that rely on multiple PB-based implementations.

**Comment by atrauzzi** [comment]
Separate note: It would also be nice if while all this was being done, `GPBMetadata` was switched to `GpbMetadata` so as to follow PSR conventions.

**Comment by TeBoring** [comment]
I will add a file option to add GPBMetadata  namespace.

**Comment by atrauzzi** [comment]
Can you follow community+PSR conventions and make it `GpbMetadata`?  Or at least let it be configurable to be PSR compliant?

**Comment by TeBoring** [comment]
Added in #4622

**Comment by atrauzzi** [comment]
🎉
