### ISSUE TITLE
protobuf enum backward compatibility

### ISSUE THREAD

**Issue by patelprateek** [google/protobuf#3971]
there are two api to set enum in proto : 
1) setEnumValue(int value) 
2) setEnum(Enum enum) 
the first method is used by the  proto newBuilder.mergeFrom(...) method .
This works pretty seamlessly even when the proto definition changes remotely and someone adds a new enum type which the current deployed code doesn't know about, where as the second method internally call getNumber which throws exception. 
Is this intentional ? It kind of breaks forward compatibility when some one adds a new enum type , where as the deployed code doesn't know about this new enum value ? 
why is the behaviour not same ?

Another question on related note : the release notes for protobuf 3.3.0 mentions : 
"proto3 enum's getNumber() method now throws on UNRECOGNIZED values" : what is this supposed to mean , i looked back at generate code for proto3 using protoc version 3.2 and 3.1 and saw that has always been that way , so why is this mentioned in this release version ? what exactly changed ?

**Comment by xfxyjwf** [comment]
I guess the release note is misplaced. The current behavior is as intended though. You can't use setEnum() to set an UNRECOGNIZED value because it will lose the actual underlying enum value. If you want to copy over an enum value to another proto, use setEnumValue()/getEnumValue() instead.
