### ISSUE TITLE
generated c++  [-Werror,-Wnull-dereference] with clang-3.9

### ISSUE THREAD

**Issue by pranavk** [google/protobuf#3987]
A simple service when compiled using protoc generates C++ that doesn't compile with clang-3.9. Generated C++ contains null pointer dereferencing in the GetRequestPrototype and GetResponsePrototype functions.

    const ::google::protobuf::Message& SimpleService::GetRequestPrototype(
        const ::google::protobuf::MethodDescriptor* method) const {
     ...
     ... 
        default:
          GOOGLE_LOG(FATAL) << "Bad method index; this should never happen.";
          return *reinterpret_cast< ::google::protobuf::Message*>(NULL);
      }
    }

The generated C++ in the default case errors out (yeah, sure I can disable Werror but) with clang-3.9 as:

error: binding dereferenced null pointer to reference has undefined behavior [-Werror,-Wnull-dereference]

I don't think I can do anything with my .proto file which is pretty simple already.

**Comment by acozzette** [comment]
It looks like this was fixed a while ago in b60e615cba2131490c4b42d2b03de057407226d1. Are you using an old protobuf version?

**Comment by pranavk** [comment]
Ah, yes. Sorry for the noise. I misread my version number.
