### ISSUE TITLE
php-protobuf-3.5 new Request() Segmentation fault

### ISSUE THREAD

**Issue by Eilick** [google/protobuf#3995]
When I new Requet, Segmentation fault 
 i don't know what's going on, but it work fine with protobuf-3.4 about 20 days ago. 
I debugged, it broke at {{{{FileDescriptor::buildFromProto}}}
I generated php class file by useing protoc.exe [[version 3.4]], but my google/protobuf lib is 3.5
But they seems dont have too much difference

**Comment by TeBoring** [comment]
It looks like the buildFromProto is php implementation only method. Are you sure it's a segmentation fault?
Could you paste the full log?

**Comment by Eilick** [comment]
Thanks for replying.  i'm Sorry, I had found the error, there are so many artisan command in our lavavel project. The Segmentation fault happened in other command which isn't in the grpc , it just looks like happened in grpc
