### ISSUE TITLE
Gettin Exception  Google.Protobuf.InvalidProtocolBufferException

### ISSUE THREAD

**Issue by vikaschamp** [google/protobuf#3996]
I have installed this library in my visual studio. I have serialized object by this library in cpp and send on tcp to c# client and parsing it . So i am getting this exception

Google.Protobuf.InvalidProtocolBufferException: 'While parsing a protocol message, the input ended unexpectedly in the middle of a field.  This could mean either that the input has been truncated or that an embedded message misreported its own length.'

**Comment by acozzette** [comment]
I would guess that something is going wrong with the framing of the message. Can you verify that the serialized message is the same on both sides (i.e. the same length and the same serialized bytes)? Protocol buffers are not self-delimiting, and so to parse one you have to know its size, and this could be a problem if you're not taking this into account.

**Comment by ShanxiChenyi** [comment]
what the fuck?
