### ISSUE TITLE
Support for DLang

### ISSUE THREAD

**Issue by carun** [google/protobuf#4008]
Can you add support for D language?

At the moment, we use https://github.com/msoucy/dproto with proto2 for D. But it doesn't support proto3.

**Comment by acozzette** [comment]
Unfortunately I don't think we have the cycles to take on another language right now, but your best bet might be to contribute proto3 support to that existing D implementation if you need it.

**Comment by carun** [comment]
That's sad. dproto is heavily dependent on GC and hogs lot of memory and CPU. I was just hoping that it will be officially supported. :-|

**Comment by dcarp** [comment]
@carun You could give https://github.com/dcarp/protobuf-d a try.
Please report there any issues you may have.
