### ISSUE TITLE
Protoc artifacts are published without a means to consume them

### ISSUE THREAD

**Issue by george-hawkins-aa** [google/protobuf#401]
The fact that binary builds of the protoc compiler for all major platforms are now being released to Maven Central is great. Thanks for the work of @zhangkun83 on:

* https://github.com/google/protobuf/tree/master/protoc-artifacts

But now that you are doing this shouldn't you also be ensuring that the means to consume these artifacts is also available via Maven Central?

As far as I can see currently the only obvious way to use these artifacts from Maven is with the [maven-protoc-plugin](https://github.com/sergei-ivanov/maven-protoc-plugin) version being maintained by @sergei-ivanov 

For whatever reason this version of the plugin is not being released to Maven Central.

If you are producing these protoc compiler artifacts shouldn't you also take responsibility for ensuring that people can do something useful with them (without having to add in random secondary repositories, something which isn't necessarily trivial in corporate environments)?

In addition to the protoc artifiacts it would seem ideal if you also took ownership of the plugin and ensured its release to Maven Central.

**Comment by xfxyjwf** [comment]
@zhangkun83 Could you comment on the current status of how to use the protoc artifacts?

**Comment by zhangkun83** [comment]
These binary builds were originally intended for consumption by [protobuf-gradle-plugin](https://github.com/google/protobuf-gradle-plugin), which is actively maintained by Google and available on Maven Central. It's great that @sergei-ivanov added such functionality to maven-protoc-plugin. We know the situation is not ideal, but we don't have either the resource or expertise right now to maintain a Maven equivalent.

**Comment by sergei-ivanov** [comment]
I am working on it right now. It may take a while before I go through all OSSRH registration shenanigans, but I am getting close.

**Comment by zhangkun83** [comment]
@sergei-ivanov has put [protobuf-maven-plugin](http://repo1.maven.org/maven2/org/xolstice/maven/plugins/protobuf-maven-plugin/0.5.0/) on Maven Central too. @xfxyjwf I think you can close this issue.

**Comment by george-hawkins-aa** [comment]
I agree - you can see that the main issue maintained by @sergei-ivanov that has been tracking this - [sergei-ivanov/maven-protoc-plugin#11](https://github.com/sergei-ivanov/maven-protoc-plugin/issues/11) - has now been marked as closed, as have the related issues from the GRPC team.

So I'll close this issue now (as I opened it). It still seems a shame that the [Maven plugin](https://github.com/xolstice/protobuf-maven-plugin) is not being maintained by Google directly, while the corresponding [Gradle plugin](https://github.com/google/protobuf-gradle-plugin) is. But at least now everything is available via Maven Central.
