### ISSUE TITLE
[doc err]cpp reflection 

### ISSUE THREAD

**Issue by biolee** [google/protobuf#4019]
- A Get*() or Set*() method for singular fields is called on a repeated field.
- GetRepeated*(), SetRepeated*(), or Add*() is called on a non-repeated field.
->
- A Get*() or Set*() method for singular fields is called on a non-repeated field.
- GetRepeated*(), SetRepeated*(), or Add*() is called on a repeated field.

![screenshot](https://user-images.githubusercontent.com/7426917/33756563-06ebe220-dc31-11e7-9ba6-c2be788f1c64.png)
[doc err url](https://developers.google.com/protocol-buffers/docs/reference/cpp/google.protobuf.message#Reflection)

**Comment by acozzette** [comment]
@biolee  I believe that documentation is correct as it is actually. It's listing operations that are considered invalid, so it makes sense that those invalid operations sound contradictory. Let me know if I am misunderstanding what you are saying, though.
