### ISSUE TITLE
protobuf-lite is not on v3.5.0

### ISSUE THREAD

**Issue by rvijayraghavan** [google/protobuf#4022]
Any specific reason to not keep protobuf-lite and protoc-gen-javalite in line with other libraries? All but these 2 seem to be on older versions (3.0.1 and 3.0.0 respectively).

http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.google.protobuf%22

Use-case: Our server uses latest protobuf compiler version 3.5.0 whereas the Android client can only use 3.0.1 (latest protobuf-lite) causing some issues in code generation.

**Comment by xfxyjwf** [comment]
java-lite uses a separate protoc plugin and is pretty much isolated from other languages built into protoc. You should be able to use protoc 3.5.0 with java-lite 3.0.1 with no problem.
