### ISSUE TITLE
TypeError: jspb.Message.setProto3StringIntField is not a function

### ISSUE THREAD

**Issue by cmoad** [google/protobuf#4025]
```
homebrew 3.5.0.1
protoc --version
libprotoc 3.5.0
npm google-protobuf 3.5.0
```

I upgraded my project to 3.5.0 and use the `[jstype = JS_STRING]` field annotation on int64's extensively. I'm getting the following error in javascript:

```
TypeError: jspb.Message.setProto3StringIntField is not a function
```

**Comment by neurojab** [comment]
also having this issue.  Message.setProto3StringIntField is not a function
