### ISSUE TITLE
Abort in JsonToBinaryStream on mismatched type in json [C++]

### ISSUE THREAD

**Issue by wsw2016** [google/protobuf#4032]
If the json content mismatches with the "announced" type_url the function util::JsonToBinaryStream aborts instead of returning the issue in util::Status.

The problem occurs within the destructor of internal::ZeroCopyStreamByteSink sink(binary_output), which aborts, if no input was provided during the parsing.

Version 3.5.0.

**Comment by acozzette** [comment]
That looks like a bug that ZeroCopyByteSink's destructor calls `BackUp()` even if no data was written. It seems like we should only call `BackUp` there if `buffer_size_` is nonzero. @wsw2016 Do you want to try fixing this and send us a pull request?

**Comment by BSBandme** [comment]
Seems that this has been [fixed](https://github.com/google/protobuf/blob/bdf0d1d6f8539f6c7312eda57535396516ed7275/src/google/protobuf/util/json_util.cc#L53-L55). 
Close for now, if there's still issues, feel free to reopen
