### ISSUE TITLE
Android App is crashing due to no method found exception possibly due to progaurd obfuscate

### ISSUE THREAD

**Issue by ankit-ankuagrawal** [google/protobuf#4061]
Having a protobuff file, successfully able to generate java file.
Was able to create object using the java file, no problem till here.

But when trying to have toString on the created object, the app is crashing with no method found exception. After doing some work came to know the method was getting removed due to Obfuscation.

Had tried various entry in progaurd file so that the method's should not be removed when APK is formed using "-keep".

Can you guys suggest how to overcome this problem, what entry should be made in progaurd file, java file has many inner classes.

**Comment by xfxyjwf** [comment]
Don't use toString() on Android. It's not designed to survive proguard obfuscation.
