### ISSUE TITLE
type mismatch of default value for python

### ISSUE THREAD

**Issue by sumtiogo** [google/protobuf#407]
- proto version: test on both libprotoc 2.5.0 and 2.6.1
- python protobuf version: test on both 2.5.0 and 2.6.1

```
# file p.proto
message M {
    optional double d1 = 1 [default = 0.0];
    optional double d2 = 2 [default = 1.0];
    optional double d3 = 3 [default = 1.1];
}
```

``` python
>>> import p_pb2
>>> m = p_pb2.M()
>>> type(m.d1)
<type 'int'>
>>> type(m.d2)
<type 'int'>
>>> type(m.d3)
<type 'float'>
```

I thought the behavior is confusing. Is it possible to make the type of default value consistent with the type defined in proto file?

**Comment by anandolee** [comment]
It has been changed to always return a float value for the default
