### ISSUE TITLE
Protobuf 3.5.0/3.5.0.1 build issue

### ISSUE THREAD

**Issue by xRaznick** [google/protobuf#4093]
When using Windows (VS2017) protobuf-lite, and proto3, declaring this message:
```
message SomeMessage {
	message SomeInnerMessage {
		uint32 some_attribute = 1;
	}
	repeated SomeMessage multiple_some_messages = 1;
}
```
is generated correctly by protoc.exe, but when compiling, this message pops:
```
path\to\messages.pb.cc(3090): error C2243: 'type cast': conversion from 'google::protobuf::RepeatedPtrField<SomeMessage_SomeInnerMessage> *' to 'google::protobuf::internal::RepeatedPtrFieldBase *' exists, but is inaccessible
```
Can I get any help here?

**Comment by acozzette** [comment]
Could you paste here the the code that's producing the error from the `pb.cc` file, and a few lines above and below it?

**Comment by xRaznick** [comment]
Of course, these are the 2 methods:
```
void ListFilesResponseMessage::InternalSwap(ListFilesResponseMessage* other) {
  using std::swap;
  dir_find_results_.InternalSwap(&other->dir_find_results_); // Error here
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}
```
And:
```
void ProcessListResponseMessage::InternalSwap(ProcessListResponseMessage* other) {
  using std::swap;
  processes_.InternalSwap(&other->processes_); // Error here
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}
```
As you can see, both messages serve the same interest. The first is a file list, which contains files as messages, and the other is process list which contains processes as messages.

**Comment by acozzette** [comment]
@xRaznick I think you may be mixing a `protoc` version of 3.5.1 or older with a newer runtime. I recently made RepeatedPtrField inherit privately from RepeatedPtrFieldBase and simultaneously updated protoc to generate slightly different code to handle that. It looks like your protoc doesn't include that change but your runtime headers do.

**Comment by xRaznick** [comment]
Alright, as long as I'm updated to master, it should be fine right? Because protobuf is a submodule in my project, and I just `git pull`.

**Comment by acozzette** [comment]
The important thing is just to make sure your `protoc` is built from the same commit as the protobuf runtime code you build and link against. So keeping `protobuf` as a submodule and updating it to master is fine, as long as you also rebuild `protoc` when you update.

**Comment by Ding8222** [comment]
@xRaznick 
I have also encountered this problem.
At the time I just added libprotobuf to my solution and build protoc.exe in other solution.

Then I added js_embed, libprotoc and protoc to build protoc.exe.
Finally, I use this protoc to create pb, it can works.
