### ISSUE TITLE
nullptr used in 3.5.1

### ISSUE THREAD

**Issue by jakirkham** [google/protobuf#4094]
Appears that [`nullptr`]( http://en.cppreference.com/w/cpp/language/nullptr ) is used in 3.5.1 as evidenced by this [build failure]( https://ci.appveyor.com/project/conda-forge/protobuf-feedstock/build/1.0.115/job/c54b86hvqpv8pvix#L756 ). `nullptr` requires C++11 at least.

**Comment by jakirkham** [comment]
For reference, `nullptr` shows up on [this line]( https://github.com/google/protobuf/blob/v3.5.1/src/google/protobuf/stubs/io_win32.cc#L94 ). This was introduced by PR ( https://github.com/google/protobuf/pull/4013 ). So cc-ing @laszlocsomor.

**Comment by laszlocsomor** [comment]
Thanks for letting me know! That PR (https://github.com/google/protobuf/pull/4013) isn't yet merged to `master`, so the line doesn't exist on `master` yet.
@pherl , shall I send PR to merge it to `master`?

**Comment by pherl** [comment]
Master is now c++11 only. We only need to fix it in the 3.5.x branch.

**Comment by laszlocsomor** [comment]
@pherl : Thanks! So shall I create a PR to merge that commit to master, or will you (or someone else) merge all 3.5.x changes back to master?

**Comment by pherl** [comment]
I will merge it back.
