### ISSUE TITLE
using protobuf for ARMv7 on RPI3

### ISSUE THREAD

**Issue by NirelNemirovsky** [google/protobuf#4097]
Hey, I have a raspberry pi 3 using ARM processor and linux 16.04
Couldn't find any protobuf download suitable and didn't manage to compile the source code myself.
Does anyone have an idea of what should I do?
Thanks!

**Comment by EdjeElectronics** [comment]
I second this question if anyone can get to it!

**Comment by xfxyjwf** [comment]
Could you post the error message you got when trying to compile from source?

**Comment by EdjeElectronics** [comment]
Hi Feng, I was able to compile it from source on the Raspberry Pi, but it would be nice to just be able to install it using an "apt-get install protobuf-compiler" command, as is shown in the Object Detection installation guide. (https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/installation.md)

**Comment by xfxyjwf** [comment]
@EdjeElectronics You can "apt-get install protobuf-compiler" on ubuntu/debian already, but that's part of ubuntu/debian's package management system and is not supported directly by us. For Raspberry Pi, if you want to have an equivalent of "apt-get install protobuf-compiler", you will need to include protobuf as part of whatever package management system you are using on Raspberry Pi. That, unfortunately, is out of scope of this project.
