### ISSUE TITLE
ruby: Support Ruby 2.5.0 on MacOS

### ISSUE THREAD

**Issue by gaffneyc** [google/protobuf#4098]
Trying to install google-protobuf 3.5.0 with Ruby 2.5.0 on Mac OS returns the following error.

```
gem install google-protobuf
Fetching: google-protobuf-3.5.0-universal-darwin.gem (100%)
ERROR:  Error installing google-protobuf:
	The last version of google-protobuf (>= 0) to support your Ruby & RubyGems was 3.5.0. Try installing it with `gem install google-protobuf -v 3.5.0`
	google-protobuf requires Ruby version < 2.5, >= 2.0. The current ruby version is 2.5.0.
```

**Comment by gaffneyc** [comment]
It looks like 3.5.1 was released yesterday but has the same problem
```
$ gem install google-protobuf -v 3.5.1
Fetching: google-protobuf-3.5.1-universal-darwin.gem (100%)
ERROR:  Error installing google-protobuf:
        The last version of google-protobuf (= 3.5.1) to support your Ruby & RubyGems was 3.5.1. Try installing it with `gem install google-protobuf -v 3.5.1`
        google-protobuf requires Ruby version < 2.5, >= 2.0. The current ruby version is 2.5.0.
```

**Comment by noctivityinc** [comment]
+1 for support for 2.5.0

**Comment by gaffneyc** [comment]
Version 3.5.1.1 was released yesterday and installs cleanly on MacOS.

**Comment by taf2** [comment]
This is again an issue with ruby 2.6.0p-1 - is there a good reason to restrict the latest versions of ruby?

grpc-1.10.0-universal-darwin requires ruby version < 2.6, >= 2.0, which is incompatible with the current version, ruby 2.6.0p-1

**Comment by alfasin** [comment]
Now I'm getting:

`google-protobuf-3.5.1-universal-darwin requires ruby version < 2.5, which is incompatible with the current version, ruby 2.5.0p0`

**Comment by RKushnir** [comment]
@alfasin 3.5.1 doesn't support ruby 2.5, try a newer version.
