### ISSUE TITLE
File generated for python gives error

### ISSUE THREAD

**Issue by cw-pratik** [google/protobuf#4104]
gRPC Version: 1.7
 Language: Python 2.7
 OS: Windows 10
 
### What did you do?
I generated gRPC files for python and the run a client using the generated python file.
 
### What did you expect to see?
 It should run normally
 
### What did you see instead?
The generated python file gave an error even before the start of the execution
 
I tried to find the issue and the issue was with an enum that I used. Here is how this issue can be reproduced.

Here is the proto file

```
syntax = "proto3";
package Service;

service MmvGrpcService
{
    rpc Func1(Details) returns (Details) {} 
}

message Details
{
  StatusEnum Status=1;
}

enum StatusEnum
{
    None = 0;
    Futuristic = 1;
    New = 2;
}

```

Then I generated the python files using the following command

`python -m grpc_tools.protoc -I . --python_out=. --grpc_python_out=. mmv.proto`

Then when I try to use the mmv_pb2.py file in any code It gives this error:

```
  File "mmv_pb2.py", line 54
    None = 0
SyntaxError: cannot assign to None
```

I think the reason is `None` is a keyword in python used for `Null`

As soon as I replace None with something else like `NA`, It works!!

I raised an [Issue ](https://github.com/grpc/grpc/issues/13868)in the gRPC repo, where they redirected me here.

**Comment by xfxyjwf** [comment]
None is a python keyword. You would need to change your enum value to some other name.
