### ISSUE TITLE
Varint32 has an error for Java

### ISSUE THREAD

**Issue by xuehuashanshu** [google/protobuf#4105]
**The offset setting is wrong:**  
`int offset = 7;`

Version: 3.5.1
ClassName: com.google.protobuf.CodedInputStream
Line: 583

**The offset maybe:**
`int offset = 0;`

**Comment by Androbin** [comment]
What is the respective behavior with [CodedInputStream.java#L583](https://github.com/google/protobuf/blob/master/java/core/src/main/java/com/google/protobuf/CodedInputStream.java#L583) setting `offset` to either value?

**Comment by xuehuashanshu** [comment]
'Varint32' algorithm to deal with greater than or equal to 128 integer data, take the last seven digits in the first code execution.
`int result = firstByte & 0x7f;`

This is the first byte calculated,offset at this time is 7.Then
`final int b = input.read();`

At this time,  **b = firstByte** and **b & 0x7f = firstByte & 0x7f**,  Then
`result |= (b & 0x7f) << offset;`

When reading the first byte of input, the above code can be converted to
**result |= result << offset**

The first last 7 bits and second last 7 bits are all 'result'.

**Comment by Androbin** [comment]
> At this time, **`b = firstByte`** and `b & 0x7f = firstByte & 0x7f`.

Citing the documentation:
> expects that the caller has already read one byte.

Meaning, `firstByte` has already been read from `input`, thus `b = input.read()` won't be `firstByte`.

AFAICT, this is what `offset = 7` is accounting for.
