### ISSUE TITLE
proto file formatter

### ISSUE THREAD

**Issue by ashi009** [google/protobuf#4113]
Hi all,

Is there a proto file formatter somewhere?

If not, why there isn't one? It seems possible to create a working prototype from FileDescriptor.

**Comment by mikedanese** [comment]
clang-format supports formatting proto files. Google uses clang-format for this internally:

https://clang.llvm.org/docs/ClangFormat.html

**Comment by xuwei-k** [comment]
https://docs.buf.build/format/usage
