### ISSUE TITLE
C1061 error with many repeated fields in VS 2008

### ISSUE THREAD

**Issue by pim89** [google/protobuf#4125]
For reasons I am stuck with Visual Studio 2008.
When compiling a proto.pb.cc file with >250 repeated fields I get the error:
"fatal error C1061: compiler limit : blocks nested too deeply"
This is a known bug of visual studio (https://support.microsoft.com/en-us/help/315481/bug-too-many-unnested-loops-incorrectly-causes-a-c1061-compiler-error), and caused by having >250 unnested for loops in one scope.
It is fixable by putting the for loops in separate scopes. For backwards compatibility this might be worth implementing, at least in a c++98 branch.

In my particular case I put [this](https://github.com/google/protobuf/blob/master/src/google/protobuf/compiler/cpp/cpp_primitive_field.cc#L404) 'for' loop extra between { ... } to fix the problem.

**Comment by xfxyjwf** [comment]
This seems a compiler issue rather than a protobuf one. You probably want to limit the size of the proto as well.
