### ISSUE TITLE
An invalid file which is parsed successfully by protobuf

### ISSUE THREAD

**Issue by PengPengHub** [google/protobuf#4141]
Hi There

Baidu X-Lab found a suspicious issue of protobuf, please see the attachment for reproducing this issue. In addition, does google provide CVE for the confirmed bug?

Thanks
Peng

[protobuf_test.tar.gz](https://github.com/google/protobuf/files/1605558/protobuf_test.tar.gz)
+++++++
Protobuf bug report
1 download protobuf from:
https://github.com/google/protobuf

2 build and install protobuf
https://github.com/google/protobuf/blob/master/src/README.md

3 extra test sample

4 build test sample

5 test bug with command:
 ./test ./testfile/file

The testfile is a invalid protobuf file ,but it is parsed successful

**Comment by WangLiangChina** [comment]
very glad to see your feedback.but this is not a issue.please see protobuf source.

**Comment by xfxyjwf** [comment]
I believe this is fixed in the latest release (3.6.0).
