### ISSUE TITLE
3.5.1 failed in cross-compiling for OpenWrt in Ubunt

### ISSUE THREAD

**Issue by YaozongZhao** [google/protobuf#4162]
I used protobuf-3.5.1 in cross-compiling for OpenWrt on Ubuntu. the OpenWrt was ARM platform. the toolchain i chosen was  [https://downloads.lede-project.org/releases/17.01.4/targets/brcm2708/bcm2710/](url)

the steps as follows:
compiling on the native host firstly

**- ./configure**

**- make**

**- make check**

**- make install**

the steps above occurs no errors, then

**- make distclean**

**- ./configure --build=x86_64-unknown-linux-gnu --host=arm-openwrt-linux-muslgnueabi --with-protoc=protoc --prefix=xxx CC=arm-openwrt-linux-muslgnueabi-gcc CXX=arm-openwrt-linux-muslgnueabi-g++ LD=arm-openwrt-linux-muslgnueabi-ld**

outputs:

> checking whether to enable maintainer-specific portions of Makefiles... yes
> checking build system type... x86_64-unknown-linux-gnu
> checking host system type... arm-openwrt-linux-muslgnueabi
> checking target system type... arm-openwrt-linux-muslgnueabi
> checking for a BSD-compatible install... /usr/bin/install -c
> checking whether build environment is sane... yes
> checking for arm-openwrt-linux-muslgnueabi-strip... arm-openwrt-linux-muslgnueabi-strip
> checking for a thread-safe mkdir -p... /bin/mkdir -p
> checking for gawk... no
> checking for mawk... mawk
> checking whether make sets $(MAKE)... yes
> checking whether make supports nested variables... yes
> checking whether UID '1000' is supported by ustar format... yes
> checking whether GID '1000' is supported by ustar format... yes
> checking how to create a ustar tar archive... gnutar
> checking for arm-openwrt-linux-muslgnueabi-gcc... arm-openwrt-linux-muslgnueabi-gcc
> checking whether the C compiler works... yes
> checking for C compiler default output file name... a.out
> checking for suffix of executables... 
> **checking whether we are cross compiling... yes**
> checking for suffix of object files... o
> checking whether we are using the GNU C compiler... yes
> checking whether arm-openwrt-linux-muslgnueabi-gcc accepts -g... yes
> checking for arm-openwrt-linux-muslgnueabi-gcc option to accept ISO C89... none needed
> checking whether arm-openwrt-linux-muslgnueabi-gcc understands -c and -o together... yes
> checking for style of include used by make... GNU
> checking dependency style of arm-openwrt-linux-muslgnueabi-gcc... gcc3
> checking whether we are using the GNU C++ compiler... yes
> checking whether arm-openwrt-linux-muslgnueabi-g++ accepts -g... yes
> checking dependency style of arm-openwrt-linux-muslgnueabi-g++... gcc3
> checking how to run the C preprocessor... arm-openwrt-linux-muslgnueabi-gcc -E
> checking for gcc... gcc
> checking whether we are using the GNU C compiler... (cached) yes
> checking whether gcc accepts -g... yes
> checking for gcc option to accept ISO C89... (cached) none needed
> checking whether gcc understands -c and -o together... (cached) yes
> checking dependency style of gcc... (cached) gcc3
> checking how to run the C preprocessor... gcc -E
> checking how to run the C++ preprocessor... arm-openwrt-linux-muslgnueabi-g++ -E
> checking for g++... g++
> checking whether we are using the GNU C++ compiler... (cached) yes
> checking whether g++ accepts -g... yes
> checking dependency style of g++... (cached) gcc3
> checking how to run the C++ preprocessor... g++ -E
> checking for grep that handles long lines and -e... /bin/grep
> checking for egrep... /bin/grep -E
> checking for ANSI C header files... yes
> checking for sys/types.h... yes
> checking for sys/stat.h... yes
> checking for stdlib.h... yes
> checking for string.h... yes
> checking for memory.h... yes
> checking for strings.h... yes
> checking for inttypes.h... yes
> checking for stdint.h... yes
> checking for unistd.h... yes
> checking minix/config.h usability... no
> checking minix/config.h presence... no
> checking for minix/config.h... no
> checking whether it is safe to define __EXTENSIONS__... yes
> checking for arm-openwrt-linux-muslgnueabi-ar... arm-openwrt-linux-muslgnueabi-ar
> checking the archiver (arm-openwrt-linux-muslgnueabi-ar) interface... ar
> checking for arm-openwrt-linux-muslgnueabi-gcc... arm-openwrt-linux-muslgnueabi-gcc
> checking whether we are using the GNU Objective C compiler... no
> checking whether arm-openwrt-linux-muslgnueabi-gcc accepts -g... no
> checking dependency style of arm-openwrt-linux-muslgnueabi-gcc... gcc3
> checking C++ compiler flags...... use default: -O2  -g -DNDEBUG
> checking whether __SUNPRO_CC is declared... no
> checking how to print strings... printf
> checking for a sed that does not truncate output... /bin/sed
> checking for fgrep... /bin/grep -F
> checking for ld used by arm-openwrt-linux-muslgnueabi-gcc... arm-openwrt-linux-muslgnueabi-ld
> checking if the linker (arm-openwrt-linux-muslgnueabi-ld) is GNU ld... yes
> checking for BSD- or MS-compatible name lister (nm)... /home/zyz/Downloads/lede-sdk-17.01.4-brcm2708-bcm2708_gcc-5.4.0_musl-1.1.16_eabi.Linux-x86_64/staging_dir/toolchain-arm_arm1176jzf-s+vfp_gcc-5.4.0_musl-1.1.16_eabi/bin/arm-openwrt-linux-muslgnueabi-nm -B
> checking the name lister (/home/zyz/Downloads/lede-sdk-17.01.4-brcm2708-bcm2708_gcc-5.4.0_musl-1.1.16_eabi.Linux-x86_64/staging_dir/toolchain-arm_arm1176jzf-s+vfp_gcc-5.4.0_musl-1.1.16_eabi/bin/arm-openwrt-linux-muslgnueabi-nm -B) interface... BSD nm
> checking whether ln -s works... yes
> checking the maximum length of command line arguments... 1572864
> checking whether the shell understands some XSI constructs... yes
> checking whether the shell understands "+="... yes
> checking how to convert x86_64-unknown-linux-gnu file names to arm-openwrt-linux-muslgnueabi format... func_convert_file_noop
> checking how to convert x86_64-unknown-linux-gnu file names to toolchain format... func_convert_file_noop
> checking for arm-openwrt-linux-muslgnueabi-ld option to reload object files... -r
> checking for arm-openwrt-linux-muslgnueabi-objdump... arm-openwrt-linux-muslgnueabi-objdump
> checking how to recognize dependent libraries... pass_all
> checking for arm-openwrt-linux-muslgnueabi-dlltool... no
> checking for dlltool... no
> checking how to associate runtime and link libraries... printf %s\n
> checking for arm-openwrt-linux-muslgnueabi-ar... (cached) arm-openwrt-linux-muslgnueabi-ar
> checking for archiver @FILE support... @
> checking for arm-openwrt-linux-muslgnueabi-strip... (cached) arm-openwrt-linux-muslgnueabi-strip
> checking for arm-openwrt-linux-muslgnueabi-ranlib... arm-openwrt-linux-muslgnueabi-ranlib
> checking command to parse /home/zyz/Downloads/lede-sdk-17.01.4-brcm2708-bcm2708_gcc-5.4.0_musl-1.1.16_eabi.Linux-x86_64/staging_dir/toolchain-arm_arm1176jzf-s+vfp_gcc-5.4.0_musl-1.1.16_eabi/bin/arm-openwrt-linux-muslgnueabi-nm -B output from arm-openwrt-linux-muslgnueabi-gcc object... ok
> checking for sysroot... no
> checking for arm-openwrt-linux-muslgnueabi-mt... no
> checking for mt... mt
> configure: WARNING: using cross tools not prefixed with host triplet
> checking if mt is a manifest tool... no
> checking for dlfcn.h... yes
> checking for objdir... .libs
> checking if arm-openwrt-linux-muslgnueabi-gcc supports -fno-rtti -fno-exceptions... no
> checking for arm-openwrt-linux-muslgnueabi-gcc option to produce PIC... -fPIC -DPIC
> checking if arm-openwrt-linux-muslgnueabi-gcc PIC flag -fPIC -DPIC works... yes
> checking if arm-openwrt-linux-muslgnueabi-gcc static flag -static works... yes
> checking if arm-openwrt-linux-muslgnueabi-gcc supports -c -o file.o... yes
> checking if arm-openwrt-linux-muslgnueabi-gcc supports -c -o file.o... (cached) yes
> checking whether the arm-openwrt-linux-muslgnueabi-gcc linker (arm-openwrt-linux-muslgnueabi-ld) supports shared libraries... yes
> checking whether -lc should be explicitly linked in... no
> checking dynamic linker characteristics... GNU/Linux ld.so
> checking how to hardcode library paths into programs... immediate
> checking whether stripping libraries is possible... yes
> checking if libtool supports shared libraries... yes
> checking whether to build shared libraries... yes
> checking whether to build static libraries... yes
> checking how to run the C++ preprocessor... arm-openwrt-linux-muslgnueabi-g++ -E
> checking for ld used by arm-openwrt-linux-muslgnueabi-g++... arm-openwrt-linux-muslgnueabi-ld
> checking if the linker (arm-openwrt-linux-muslgnueabi-ld) is GNU ld... yes
> checking whether the arm-openwrt-linux-muslgnueabi-g++ linker (arm-openwrt-linux-muslgnueabi-ld) supports shared libraries... yes
> checking for arm-openwrt-linux-muslgnueabi-g++ option to produce PIC... -fPIC -DPIC
> checking if arm-openwrt-linux-muslgnueabi-g++ PIC flag -fPIC -DPIC works... yes
> checking if arm-openwrt-linux-muslgnueabi-g++ static flag -static works... yes
> checking if arm-openwrt-linux-muslgnueabi-g++ supports -c -o file.o... yes
> checking if arm-openwrt-linux-muslgnueabi-g++ supports -c -o file.o... (cached) yes
> checking whether the arm-openwrt-linux-muslgnueabi-g++ linker (arm-openwrt-linux-muslgnueabi-ld) supports shared libraries... yes
> checking dynamic linker characteristics... (cached) GNU/Linux ld.so
> checking how to hardcode library paths into programs... immediate
> checking whether the linker supports version scripts... yes
> checking for ANSI C header files... (cached) yes
> checking fcntl.h usability... yes
> checking fcntl.h presence... yes
> checking for fcntl.h... yes
> checking for inttypes.h... (cached) yes
> checking limits.h usability... yes
> checking limits.h presence... yes
> checking for limits.h... yes
> checking for stdlib.h... (cached) yes
> checking for unistd.h... (cached) yes
> checking for working memcmp... no
> checking for working strtod... no
> checking for pow... yes
> checking for ftruncate... yes
> checking for memset... yes
> checking for mkdir... yes
> checking for strchr... yes
> checking for strerror... yes
> checking for strtol... yes
> checking zlib version... headers missing or too old (requires 1.2.0.4)
> checking for the pthreads library -lpthreads... no
> checking whether pthreads work without any flags... yes
> checking for joinable pthread attribute... PTHREAD_CREATE_JOINABLE
> checking if more special flags are required for pthreads... no
> checking whether to check for GCC pthread/shared inconsistencies... yes
> checking whether -pthread is sufficient with -shared... yes
> checking whether what we have so far is sufficient with -nostdlib... yes
> checking the location of hash_map... <tr1/unordered_map>
> checking for library containing sched_yield... none required
> checking whether arm-openwrt-linux-muslgnueabi-g++ supports C++11 features by default... no
> checking whether arm-openwrt-linux-muslgnueabi-g++ supports C++11 features with -std=c++11... yes
> checking that generated files are newer than configure... done
> configure: creating ./config.status
> config.status: creating Makefile
> config.status: creating src/Makefile
> config.status: creating benchmarks/Makefile
> config.status: creating conformance/Makefile
> config.status: creating protobuf.pc
> config.status: creating protobuf-lite.pc
> config.status: creating config.h
> config.status: executing depfiles commands
> config.status: executing libtool commands

**the outputs show that "checking whether we are cross compiling... yes",but when i** 

**- sudo make**
outputs:

> make  all-recursive
> make[1]: Entering directory '/home/zyz/Downloads/protobuf-3.5.1'
> Making all in .
> make[2]: Entering directory '/home/zyz/Downloads/protobuf-3.5.1'
> make[2]: Leaving directory '/home/zyz/Downloads/protobuf-3.5.1'
> Making all in src
> make[2]: Entering directory '/home/zyz/Downloads/protobuf-3.5.1/src'
> depbase=`echo google/protobuf/stubs/atomicops_internals_x86_gcc.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
> /bin/bash ../libtool  --tag=CXX   --mode=compile arm-openwrt-linux-muslgnueabi-g++ -std=c++11 -DHAVE_CONFIG_H -I. -I..     -DHAVE_PTHREAD=1  -Wall -Wno-sign-compare -O2 -g -DNDEBUG -MT google/protobuf/stubs/atomicops_internals_x86_gcc.lo -MD -MP -MF $depbase.Tpo -c -o google/protobuf/stubs/atomicops_internals_x86_gcc.lo google/protobuf/stubs/atomicops_internals_x86_gcc.cc &&\
> mv -f $depbase.Tpo $depbase.Plo
> libtool: compile:  arm-openwrt-linux-muslgnueabi-g++ -std=c++11 -DHAVE_CONFIG_H -I. -I.. -DHAVE_PTHREAD=1 -Wall -Wno-sign-compare -O2 -g -DNDEBUG -MT google/protobuf/stubs/atomicops_internals_x86_gcc.lo -MD -MP -MF google/protobuf/stubs/.deps/atomicops_internals_x86_gcc.Tpo -c google/protobuf/stubs/atomicops_internals_x86_gcc.cc -o google/protobuf/stubs/atomicops_internals_x86_gcc.o
> ../libtool: line 1125: arm-openwrt-linux-muslgnueabi-g++: command not found
> **Makefile:4114: recipe for target 'google/protobuf/stubs/atomicops_internals_x86_gcc.lo' failed
> make[2]: *** [google/protobuf/stubs/atomicops_internals_x86_gcc.lo] Error 1**
> make[2]: Leaving directory '/home/zyz/Downloads/protobuf-3.5.1/src'
> Makefile:1558: recipe for target 'all-recursive' failed
> make[1]: *** [all-recursive] Error 1
> make[1]: Leaving directory '/home/zyz/Downloads/protobuf-3.5.1'
> Makefile:1465: recipe for target 'all' failed
> make: *** [all] Error 2

**the result show that when compile google/protobuf/stubs/atomicops_internals_x86_gcc.cc has a error likely.
i think it should not compile the files related x86 platform like atomicops_internals_x86_gcc.cc now that  running cross-compile.**

do you know why this has happened?

Thank you for the consideration and assistance.

**Comment by pherl** [comment]
You probably need to change the code in atomicops.h for the correct platforms macros in cross compiling, e.g. fallback to use Arm related implementations instead. We are trying to move to C++11 atomics and hopefully this will no longer be needed.

**Comment by YaozongZhao** [comment]
i am so sorry for that i had a incorrect description for the issue. the main reason for the error is "../libtool: line 1125: arm-openwrt-linux-muslgnueabi-g++: command not found".

that is when i executed "sudo make", the system environment had change to root, and the PATH i configured  in my own account will be invalid , so that the arm-openwrt-linux-muslgnueabi-g++ can not be found.

resolved methods are:
(1) execute "su" command to switch to root account, then configure the PATH again.
make && make install directly
or
(2)the parameters CC and CXX used absolute path when execute ./configure
