### ISSUE TITLE
(7 out of 2012) Failing Tests with Visual Studio 2017 v15.5.4/ Cmake 3.10.1

### ISSUE THREAD

**Issue by JackGrinningCat** [google/protobuf#4178]
Hi,

I followed following description
https://github.com/google/protobuf/tree/master/cmake

Used tools: 
- Visual Studio 2017 v15.5.4
  - x64 Native Tools Command Prompt for VS 2017
- Cmake 3.10.1
- git version 2.15.1.windows.2
- cloned protocbuf 
- cloned gmock/gtest 1.7.0 

- Windows 10 Version 1703 

`
set PATH=%PATH%;C:\Program Files\CMake\bin
git clone -b v3.5.1 https://github.com/google/protobuf.git
cd protobuf
mkdir install
git clone -b release-1.7.0 https://github.com/google/googlemock.git gmock
cd gmock
git clone -b release-1.7.0 https://github.com/google/googletest.git gtest
cd ../cmake
mkdir build
cd build
mkdir Release
cd Release
mkdir solution
cd solution
cmake -G "Visual Studio 15 2017 Win64" ^
-DCMAKE_BUILD_TYPE=Debug ^
-DCMAKE_INSTALL_PREFIX=../../../install ^
../..

msbuild protobuf.sln /p:Configuration=Debug
msbuild check.vcxproj /p:Configuration=Debug
`

When building the check project in the created visual studio solution, I meet following test failures.

>    [----------] Global test environment tear-down
>    [==========] 2012 tests from 194 test cases ran. (42205 ms total)
>    [  PASSED  ] 2005 tests.
>    [  FAILED  ] 7 tests, listed below:
>    [  FAILED  ] CommandLineInterfaceTest.Win32ErrorMessage
>    [  FAILED  ] BootstrapTest.GeneratedDescriptorMatches
>    [  FAILED  ] CsharpBootstrapTest.GeneratedCsharpDescriptorMatches
>    [  FAILED  ] RubyGeneratorTest.GeneratorTest
>    [  FAILED  ] TextFormatMapTest.Sorted
>    [  FAILED  ] TextFormatTest.Basic
>    [  FAILED  ] TextFormatExtensionsTest.Extensions

>    [  FAILED  ] CommandLineInterfaceTest.Win32ErrorMessage
  This one is due to false expectation about a translation of error messages from my German windows installation. 

Can anybody make a rhyme about those erros?

**Comment by xfxyjwf** [comment]
Those errors are most likely caused by auto "LF" => "CR LF" conversion when you git clone the project. It should be safe to ignore these test errors. If you want to fix them, try disable the autocrlf in your git settings and do it again.

**Comment by JackGrinningCat** [comment]
Thanks for the answer i'll repeat that Part tomorrow. Am 18.01.2018 7:43 nachm. schrieb Feng Xiao <notifications@github.com>:Those errors are most likely caused by auto "LF" => "CR LF" conversion when you git clone the project. It should be safe to ignore these test errors. If you want to fix them, try disable the autocrlf in your git settings and do it again.

**Comment by JackGrinningCat** [comment]
Well it worked. 

```
set PATH=%PATH%;C:\Program Files\CMake\bin

git clone -b v3.5.1 https://github.com/google/protobuf.git --config core.autocrlf=false
cd protobuf
mkdir install
git clone -b release-1.7.0 https://github.com/google/googlemock.git gmock --config core.autocrlf=false
cd gmock
git clone -b release-1.7.0 https://github.com/google/googletest.git gtest --config core.autocrlf=false
cd ../cmake
mkdir build
cd build
mkdir Release
cd Release
mkdir solution
cd solution
cmake -G "Visual Studio 15 2017 Win64" ^
-DCMAKE_BUILD_TYPE=Debug ^
-DCMAKE_INSTALL_PREFIX=../../../../install ^
../../..

msbuild protobuf.sln /p:Configuration=Debug
msbuild check.vcxproj /p:Configuration=Debug
```

Here are the results of the check run. As metioned beforehand the one failure is due to the german win32 translation

>   [----------] Global test environment tear-down
>   [==========] 2012 tests from 194 test cases ran. (44588 ms total)
>   [  PASSED  ] 2011 tests.
>   [  FAILED  ] 1 test, listed below:
>   [  FAILED  ] CommandLineInterfaceTest.Win32ErrorMessage
> 
>    1 FAILED TEST
