### ISSUE TITLE
use util::MessageToJsonString, alway error.

### ISSUE THREAD

**Issue by marshal-it** [google/protobuf#4187]
use like this:
	const google::protobuf::Message* msg = Message;
	std::string* jsonstr;
	google::protobuf::util::JsonOptions options;
	bool ok = google::protobuf::util::MessageToJsonString(msg, jsonstr, options).ok();
	google::protobuf::util::MessageToJsonString(msg, jsonstr);

but build error:
       error C2665: "google::protobuf::util::MessageToJsonString":none of the 2 overloads could convert all the argument types

in .h file have #include <google/protobuf/util/json_util.h>

so , i dont know why issue this error...

**Comment by arthur-tacca** [comment]
It takes a `const Message&` not a `Message&`. Change your argument to `*msg`.

**Comment by marshal-it** [comment]
thanks .
