### ISSUE TITLE
[Ruby] Crashes when calling `JSON.fast_generate` on a Protobuf object

### ISSUE THREAD

**Issue by janpaul123** [google/protobuf#4190]
```ruby
require 'json'
JSON.fast_generate(MyProtobuf.new)
```

Results in this error:
```
ArgumentError: wrong number of arguments (given 1, expected 0)
from ~/.gem/ruby/2.4.2/gems/google-protobuf-3.5.0-universal-darwin/lib/google/protobuf/message_exts.rb:43:in `to_json'
```

This affects serialisation in some libraries, like when logging errors using [Raven](https://github.com/getsentry/raven-ruby).

**Comment by TeBoring** [comment]
This was fixed in 3.6.0 release: https://github.com/google/protobuf/blob/3.6.x/ruby/lib/google/protobuf/message_exts.rb#L43
