### ISSUE TITLE
When marshaling to JSON, a timestamp should trim all fractional digits if possible

### ISSUE THREAD

**Issue by ochen** [google/protobuf#4193]
According to the proto3 to JSON specification, the JSON representation of a timestamp field

> Uses RFC 3339, where generated output will always be Z-normalized and uses **0**, 3, 6 or 9 fractional digits.

However, the jsonpb package will always use 3,6,9 fractional digits, leaving a timestamp with integer seconds ends with a suffix `.000Z`. I think this may be incomplete.

**Comment by xfxyjwf** [comment]
You mean the jsonpb package in golang/protobuf repository?
https://github.com/golang/protobuf/tree/master/jsonpb

Can you file the issue there?

**Comment by ochen** [comment]
Sorry, mistaken the repository.
