### ISSUE TITLE
Protobuf bytes[] to Json

### ISSUE THREAD

**Issue by Disturbing** [google/protobuf#4201]
Hello All,

I'm looking to change protobuf bytes[] to Json without the use of a protofile / class.

Otherwise, I'm looking to do this in a hot swapping way where the protobuf class definition can be either read in real time via proto file or be able to load a protobuf class as a script (via dotnet core AssemblyModule).

Are there any resources out there for this already?

**Comment by acozzette** [comment]
@jskeet Do you know the answer to this by any chance?

In C++ and Java we have a DynamicMessage that allows you to operate on a message type based on its descriptor, without needing it to be known at compile time, but I'm not sure if we have something like this for C# or not.

**Comment by jskeet** [comment]
We don't support DynamicMessage in C# yet, no. #658 is an existing issue requesting it.

We haven't previously had enough (and detailed) use cases for it, so we wanted to wait for those before designing what it would look like. It's a non-trivial but not enormous piece of work, I believe.

cc @anandolee
