### ISSUE TITLE
Redistribute CPython protobuf for mac and windows.

### ISSUE THREAD

**Issue by fengli79** [google/protobuf#4212]
Protobuf ships less redistributable packages than gRPC.
gRPC:
https://pypi.python.org/pypi/grpcio

It lacks for:
1. Windows 32, 64.
2. Mac
3. Linux 32.

Fulfill the gap helps to improve the gRPC performance on those platforms.

**Comment by xfxyjwf** [comment]
@nathanielmanistaatgoogle @fengli79 Any pointers on how the grpcio python wheels are built? We can probably reuse the same build script or pipeline to build protobuf python wheels.

**Comment by nathanielmanistaatgoogle** [comment]
@xfxyjwf: "it's all in the code" would be a true answer but not a very helpful one. I'd say check in with @matt-kwong and @jtattermusch about how the gRPC artifact-building process works in general and follow up with @kpayson64 and @mehrdada about the gRPC Python wheels in particular.

**Comment by TeBoring** [comment]
Done. https://pypi.org/project/protobuf/#files
