### ISSUE TITLE
Generated implementation for SpaceUsed in C++

### ISSUE THREAD

**Issue by toddlipcon** [google/protobuf#4218]
As noted in the C++ docs, SpaceUsed is quite slow:

> SpaceUsed() is noticeably slower than ByteSize(), as it is implemented using reflection (rather than the generated code implementation for ByteSize()). Like ByteSize(), its CPU time is linear in the number of fields defined for the proto.

In our application we have a lot of protobufs that end up in various memory-limited caches and assigned to various memory budgets. In some cases the difference between ByteSize and SpaceUsed can be significant enough (eg with many optional fields) and therefore we use SpaceUsed to track the memory consumption of these objects. This is becoming a fairly significant CPU consumer despite our best efforts to only compute it once per PB.

If I were to work on a change to optionally generate a SpaceUsed method rather than use reflection, would it be acceptable to the community?

**Comment by xfxyjwf** [comment]
We likely won't accept changes that add new generated methods in the existing .pb.cc file. However, you can easily implement it as a protoc plugin that generates a standalone static SpaceUsed() method for each proto type. That's the common way to add utility functions for protos (e.g., we have such protoc plugins to generate Equals() and HashCode() functions).

**Comment by toddlipcon** [comment]
Good idea. I had missed that the existing implementation was virtual and thus could be easily overridden.

**Comment by xfxyjwf** [comment]
To be clear, I'm not suggesting overriding the virtual method. Instead I'm advocating generating static SpaceUsed() method. For example:

```cpp
size_t SpacedUsed(const proto::Foo& foo) {
  ...
}
```

**Comment by JonKohler** [comment]
Hey! Did either of you figure out a SpaceUsed that could be generated such that it could give you a "pre calculated" SpaceUsed rather than the run time reflection based one?
