### ISSUE TITLE
[Java] Bug: Errors on 4-byte UTF-8 Unicode

### ISSUE THREAD

**Issue by jbfitbit** [google/protobuf#4219]
### Steps to reproduce:

1. Create a simple protobuf message object with just a string as a field
2. Generate the java code
3. Set the value of the string to `𤭢` or `😀` (**_any_** 4-byte unicode character)
4. Try to generate the binary

### Expected:
No errors

### Actual:
**String is not serialized!**
```
com.google.protobuf.CodedOutputStream inefficientWriteStringNoTag
WARNING: Converting ill-formed UTF-16. Your Protocol Buffer will not round trip correctly!
com.google.protobuf.Utf8$UnpairedSurrogateException: Unpaired surrogate at index 13 of 15"
```

### Issue:
~~Code incorrectly states that UTF-8 maxes out at 3 bytes per character~~
~~https://github.com/google/protobuf/blob/6de51caed52d798815954646b230c5aef3e4d2fc/java/core/src/main/java/com/google/protobuf/Utf8.java#L102~~
𤭢 and 😀, however, are unicode characters that are represented by four bytes: `\xF0\xA4\xAD\xA2`

Per [RFC 3629](https://tools.ietf.org/html/rfc3629), [utf-8 can be up to four bytes](https://stackoverflow.com/a/9533324).

This causes this code:

https://github.com/google/protobuf/blob/master/java/core/src/main/java/com/google/protobuf/CodedOutputStream.java#L1762

to incorrectly throw an `UnpairedSurrogateException`

**Comment by acozzette** [comment]
Could you link to an example test that shows the failure? I haven't worked on that particular code, but I think what it's saying is essentially that 2 bytes worth of UTF-16 can expand to at most 3 bytes of UTF-8. From what I can tell, this assumption is true and so I can't see how that would be a problem.

**Comment by xfxyjwf** [comment]
I can verify that protobuf Java supports 4-bytes UTF-8 characters correctly. See example code:
https://gist.github.com/xfxyjwf/98ae915d3a076c46586f4af7435e1f46

Adam's explanation is correct. For your given examples, it takes 2 chars to encode each character in UTF-16, and 4 bytes in UTF-8. So the ratio is `4 / 2 = 2` which is smaller than `MAX_BYTES_PER_CHAR = 3`.

My guess is that you do have unpaired surrogates in your string value just as the warning message indicates.

**Comment by jbfitbit** [comment]
It seems to work, but the warning message is incorrect. `😀` should be a valid string without unpaired surrogates
