### ISSUE TITLE
Make ability to compile protobuf statically with MD on Windows

### ISSUE THREAD

**Issue by mapron** [google/protobuf#4225]
At this moment, if I compile with protobuf_BUILD_SHARED_LIBS disabled, protobuf forced to use static msvc runtime (MT); I think we should have two different options for that.

My user scenario: I create dll (which use /MD as all my project). dll links libcaffe, which requires libprotobuf.
caffe have several issues with shared linkage on Windows, so I ought to use  static libraries.
But configuring protobuf with static linkage brings me "viral" /MT flag; so I could not use my wrapper dll anymore.

**Comment by xfxyjwf** [comment]
I think there is already a protobuf_MSVC_STATIC_RUNTIME flag for that purpose?

**Comment by mapron** [comment]
I'm such a dumb idiot; Sorry.
