### ISSUE TITLE
Reading .pb files.

### ISSUE THREAD

**Issue by ayush1999** [google/protobuf#4232]
I know that `.proto` files can be used to generate code. However, can someone tell me how are `.pb` (binary format ) files useful? And how can I generate data structures using `.pb` files?

**Comment by acozzette** [comment]
The binary format is just the stored representation of your data, based on the message schema you define in your .proto file. For any language we support, you can use `protoc` to generate code from your `.proto` file and use that code to read and write your messages in binary format.

**Comment by ayush1999** [comment]
@acozzette Suppose I don't have the .proto file, but only the .pb file. Is there a way of generating the data structure (with only the .pb file)?

**Comment by acozzette** [comment]
If you don't have access to the .proto file, you won't be able to determine the exact meaning of the data, but just as a debugging tool you can use `protoc --decode_raw` to print a human-readable view of the general structure of the data.

**Comment by ayush1999** [comment]
@acozzette Suppose I want to make a reader for onnx models. Since onnx models contain a model.pb file, how can we generate a data structure from this? Since no .proto file is present here, I'm confused.

**Comment by acozzette** [comment]
@ayush1999 I would talk to the onnx folks about that--I'm not familiar with onnx but if they're indeed storing protocol buffers then they must have a .proto file somewhere.

**Comment by charanpool** [comment]
@ayush1999 Did you find the answer to this question?
