### ISSUE TITLE
Ruby Gem 3.5.1.1 broken on Ruby 2.1

### ISSUE THREAD

**Issue by blowmage** [google/protobuf#4235]
The gem `google-protobuf-3.5.1.1-universal-darwin.gem` is missing the precompiled file for Ruby 2.1.

Compare the `universal-darwin` gem:

```
$ tree google-protobuf-3.5.1.1-universal-darwin/data/lib/google 
├── 2.0
│   └── protobuf_c.bundle
├── 2.2
│   └── protobuf_c.bundle
├── 2.3
│   └── protobuf_c.bundle
├── 2.4
│   └── protobuf_c.bundle
├── 2.5
│   └── protobuf_c.bundle
├── protobuf
│   ├── any_pb.rb
│   ├── api_pb.rb
│   ├── duration_pb.rb
│   ├── empty_pb.rb
│   ├── field_mask_pb.rb
│   ├── message_exts.rb
│   ├── repeated_field.rb
│   ├── source_context_pb.rb
│   ├── struct_pb.rb
│   ├── timestamp_pb.rb
│   ├── type_pb.rb
│   ├── well_known_types.rb
│   └── wrappers_pb.rb
└── protobuf.rb

6 directories, 19 files
```

To the `x86_64-linux` gem:

```
$ tree google-protobuf-3.5.1.1-x86_64-linux/data/lib/google 
├── 2.0
│   └── protobuf_c.so
├── 2.1
│   └── protobuf_c.so
├── 2.2
│   └── protobuf_c.so
├── 2.3
│   └── protobuf_c.so
├── 2.4
│   └── protobuf_c.so
├── 2.5
│   └── protobuf_c.so
├── protobuf
│   ├── any_pb.rb
│   ├── api_pb.rb
│   ├── duration_pb.rb
│   ├── empty_pb.rb
│   ├── field_mask_pb.rb
│   ├── message_exts.rb
│   ├── repeated_field.rb
│   ├── source_context_pb.rb
│   ├── struct_pb.rb
│   ├── timestamp_pb.rb
│   ├── type_pb.rb
│   ├── well_known_types.rb
│   └── wrappers_pb.rb
├── protobuf.rb
└── protobuf_c.so

7 directories, 21 files
```

The other platform gems have a precompiled file for all supportedlanguage versions, and don't appear to be affected. However, only the `x86_64-linux` gem has a non-language-versioned pre-compiled file (not nested under a `2.x` directory).

**Comment by geigerj** [comment]
Adding @pherl @TeBoring from Protobuf

**Comment by pherl** [comment]
Hmm, the mac one also misses 2.1 build. @apolcyn I will look into that.

**Comment by blowmage** [comment]
Oops, I meant Ruby 2.1, but I said 2.2. Apologies.

**Comment by pherl** [comment]
This is probably due to the Rakefile change in https://github.com/google/protobuf/commit/53d907f646a8e58e14511fba3e9d3e2abd5dd182

**Comment by blowmage** [comment]
Is there an ETA for the release of the 3.5.1.2 gems?

**Comment by pherl** [comment]
Probably will be ready by EOD.

**Comment by pherl** [comment]
Pushed the gems. Please let me know if you see any issues.

**Comment by blowmage** [comment]
Our CI builds for Mac and Ruby 2.1 can progress now. Thanks for being so responsive!
