### ISSUE TITLE
Error occured when I try to compile libprotobuf-lite.a using cross compile.

### ISSUE THREAD

**Issue by happyLiMing** [google/protobuf#4243]
As said in the title, There are some error when I want to compile libprotobuf-lite.a using special cross compile. 
1: cd to cmake folder, mkdir build ,cd build and run cmake as follow:
cmake -DCMAKE_C_COMPILER     = path to/mipsel-openwrt-linux-gcc  
           -DCMAKE_CXX_COMPILER = path to/mipsel-openwrt-linux-g++  ..

2: run make, then run into this error：
# #mipsel-openwrt-linux-uclibc-g++.bin: warning: environment variable 'STAGING_DIR' not defined
/tmp/cc8ssVBK.s: Assembler messages:
/tmp/cc8ssVBK.s:188: Error: opcode not supported on this processor: mips1 (mips1) `ll $6,0($3)'
/tmp/cc8ssVBK.s:190: Error: opcode not supported on this processor: mips1 (mips1) `sc $4,0($5)'
/tmp/cc8ssVBK.s:241: Error: opcode not supported on this processor: mips1 (mips1) `ll $4,0($3)'
/tmp/cc8ssVBK.s:243: Error: opcode not supported on this processor: mips1 (mips1) `sc $6,0($5)'
/tmp/cc8ssVBK.s:326: Error: opcode not supported on this processor: mips1 (mips1) `sync'

is there anyone do some relevant work? would you tell me how to fix this? 

Thanks.

**Comment by lucaswiechmann** [comment]
Hello,

I'm facing the same problem. Has anyone fix this issue?

Thanks.

**Comment by xfxyjwf** [comment]
Nobody is working on fixing this as far as I can tell. Feel free to send us a pull request if you know of a fix.

**Comment by lucaswiechmann** [comment]
It was a mistake on configure options.

Add CXXFLAGS="-D__MIPSEL__ -march=mips32" and you should be good

**Comment by happyLiMing** [comment]
Yes, lucaswiechmann, I have got it.

**Comment by vudinhlong4** [comment]
> I'm facing the same problem. 
Add CXXFLAGS="-D__MIPSEL__ -march=mips32"  in makefile but compiling don't be solved. 
Can you help me more clearly. Also, the toolchain i am using is "toolchain-mips_r2_gcc-4.6-linaro_uClibc-0.9.33.2"
