### ISSUE TITLE
Benchmark submodule fails to build on ppc64.

### ISSUE THREAD

**Issue by mandlebug** [google/protobuf#4244]
Building the Protobuf C++ benchmark on a PowerPC cpu fails because the submodule version of google/benchmark that protbuf uses is broken on powerpc. A Commit merged in #3822 was supposed to fix this but the submodule commit that the git link points to now is earlier then the commit needed to unbreak the PowerPC build.

```
git submodule status
-360e66c1c4777c99402cf8cd535aa510fee16573 third_party/benchmark

git show 360e66c1c4777c99402cf8cd535aa510fee16573
commit 360e66c1c4777c99402cf8cd535aa510fee16573
Merge: 336fd11 fa0e7ef
Author: Dominic Hamon <dominichamon@users.noreply.github.com>
Date:   Wed May 11 12:07:59 2016 -0700
```

The commit needed to fix the powerpc build is
```
commit fef203bd021bad019421abf5785a4ae89bd6ea15
Author: guray <guray.ozen@gmail.com>
Date:   Mon Jan 30 21:50:21 2017 +0100

    Fix typename for powerpc (#337)

```

**Comment by BSBandme** [comment]
Sorry for the accident rolling back

**Comment by mandlebug** [comment]
I've verified the fix by compiling natively on a Power8 machine. Thank you for the the fast turnaround, its appreciated!
