### ISSUE TITLE
protoc on linux64 to build csharp stubs allows you to specify an invalid plugin without complaining namely `--plugin=protoc-gen-grpc=`

### ISSUE THREAD

**Issue by nddipiazza** [google/protobuf#4245]
I give a C# protoc a bad plugin path, and it just proceeds like nothing happened.

`protoc -I/home/ndipiazza/lucidworks/googleapis -I/usr/local/include -I. --csharp_out=/home/ndipiazza/Projects/FusionConnectors/FusionConnectors --plugin=protoc-gen-grpc=tasdfasdfasdfasdfasdfasdf lucidworks/*.proto lucidworks/connector/`

returns no error.

What does that thing do anyway?

**Comment by xfxyjwf** [comment]
The plugin will only be invoked if you actually have the corresponding "--<xxx>_out" flag on the command line. For example, try adding "--grpc_out=." in your command line and then it should fail.

**Comment by nddipiazza** [comment]
yep that's my answer. thanks.

**Comment by nddipiazza** [comment]
might be worth adding a warning for this because clearly that means they just forgot to specify that param.
