### ISSUE TITLE
No way to determine unknown fields in C++-backed Python protocol buffers

### ISSUE THREAD

**Issue by 27359794** [google/protobuf#4281]
If I have a proto message object in C++, I can access its unknown fields using `Reflection::GetUnknownFields`. If I have a proto message object in Python backed by the pure Python message implementation, I can access its unknown fields using `msg._unknown_fields`. However, if I have a proto message object in Python backed by the C++ implementation of messages, there doesn't appear to be a way to access its unknown fields. There is no `_unknown_fields` attribute on such objects.

For completeness, shouldn't the C++-backed Python implementation also expose unknown fields? Probably via an `_unknown_fields` attribute, so it shares the same interface with the Pure Python implementation?

**Comment by arthur-tacca** [comment]
I'm not a protobuf developer but I would venture that `_unknown_fields` is not a supported API anyway: in Python a leading underscore usually indicates a private variable, and `_unknown_fields` is not mentioned in the [docs](https://developers.google.com/protocol-buffers/docs/reference/python/google.protobuf.message.Message-class). So maybe the issue should be "No way to determine unknown fields in ~~C++-backed~~ Python protocol buffers"

**Comment by xfxyjwf** [comment]
@arthur-tacca is correct. `_unknown_fields` is supposed to be private and should not be used by users. The problem here is that Python doesn't have a public API for unknown fields.

**Comment by 27359794** [comment]
I understand. Are there plans to introduce a public API for unknown fields in Python?

The scenario we have is that the versions of our proto definitions used by our client and server occasionally fall out of sync with each other, and we need a way for the server to recognise that the client is using a newer version of our proto definitions.  Is there a good way of doing this that doesn't depend on checking unknown fields server-side?

**Comment by xfxyjwf** [comment]
I think it's up to @anandolee to decide whether or not to add this new unknown field API in python.

**Comment by anandolee** [comment]
We do not have any plan for public unknown fields API. But to better support pure python users switch to C++ python, it make sense to implement _unknown_fields attribute in C++ python.

**Comment by 27359794** [comment]
Great, looking forward to it.

**Comment by anandolee** [comment]
Update: we are adding unknown fields APIs in internal code. Will not provide _unknown_fields attribute in C++ python. 
_unknown_fields in pure python will be removed sometime in future.

**Comment by anandolee** [comment]
Update: UnknownFields API has been submitted in internal code. Expect to see it in future release

**Comment by anandolee** [comment]
It is Down-integrate from google internal to master branch:
https://github.com/google/protobuf/blob/acd5b05e9f1ec2153574807463af0612267b6067/python/google/protobuf/internal/message_test.py#L1438

**Comment by anandolee** [comment]
You can see the tests for example:
https://github.com/protocolbuffers/protobuf/blob/ba8692fbade4ba329cc4531e286ab5a8e0821d97/python/google/protobuf/internal/unknown_fields_test.py#L190
