### ISSUE TITLE
Using my own protoc .pb.cc along with a library that has it's own protoc files

### ISSUE THREAD

**Issue by CraigglesO** [google/protobuf#4294]
I keep getting errors.
Using this library:
https://github.com/CanalTP/libosmpbfreader
Depends upon a library that uses it's own protoc files to read .osm.pbf files. But I want to store nodes in my own format. So I wrote a protoc file. When I build everything I get an error. 

I Can't using my own protoc along side the project maybe?

What's weird is I see errors when I open the pb.h file. I've independently tried 10 different version of protoc before asking this question, the other library I found out uses 3.0.0 but when I installed 3.0.0 It still didn't work.

UPDATE:
seems like I just can't create anything with protobuf/protoc even outside this project without the compiler getting angry... Dunno what to do.

**Comment by Jimbooti** [comment]
any progress with this ? i spent the last 3 days with this hell, i've gotten 3.0 and 3.5 to build with ue4, until i try to make a call into any of the classes generated i get unresolved linker errors.

**Comment by CraigglesO** [comment]
I switched to ubuntu and had much better success.

Make sure to download the packaged protofbuf:
```
sudo apt-get install libprotobuf-dev libprotobuf-java protobuf-compiler
```

Using other versions like recent releases will cause a headache.
As for os x, I really forgot my solution, but it was a hellish ride. Best of luck.

**Comment by acozzette** [comment]
I think the issue here is that for C++ we require the protoc version and library version to match exactly--you can't use one version of protoc to generate code but then build against a different library version. So if one of your library dependencies uses protobuf, you have to make sure you use the same version when you generate your own code.

**Comment by Jimbooti** [comment]
thank you for your response, i have tracked down the reasons for link time failure to cmake and my inability to use it correctly, i have built everything myself so the protoc i am using and the .proto files generated are using the same stuff.
