### ISSUE TITLE
Question: how to use UninterpretedOption in Proto3 ??

### ISSUE THREAD

**Issue by wawade** [google/protobuf#4308]
Hi,
does anyone know how to use class UninterpretedOption?

I have tried the following:

- extend google.protobuf.UninterpretedOption {
-   float my_option = 50002;
- }
- message MSG {
-   float data = 1 [(my_option) = 1.0];
- }

then protoc complains: "google.protobuf.UninterpretedOption" does not declare 50002 as an extension number.

or just

- message MSG {
-   float data = 1 [(my_option) = 1.0];
- }

protoc: Option "(my)" unknown.

Could someone gives me an advice? I didn't find any example from the tutorial or Internet. 
Thanks in advance.

PS: I cannot use FieldOption since I am in LITE.

Siqi

**Comment by xfxyjwf** [comment]
You can't extend UninterpretedOption. Instead, you can still use FieldOptions in the .proto file. It's just that you can't access the option value in LITE.

**Comment by wawade** [comment]
Thank you very much for your reply. So UninterpretedOption is not what I want. Is there any other possibilities to get the option value in LITE?

**Comment by xfxyjwf** [comment]
Custom options are not available in LITE.
