### ISSUE TITLE
C# copy ctor inconsistently writes to property rather than backing field for non-repeated messages

### ISSUE THREAD

**Issue by chrisdunelm** [google/protobuf#4316]
For example, in the [copy ctor for the Subscription type in Pubsub.cs](https://github.com/GoogleCloudPlatform/google-cloud-dotnet/blob/master/apis/Google.Cloud.PubSub.V1/Google.Cloud.PubSub.V1/Pubsub.cs#L1967); `PushConfig` and `MessageRetentionDuration` write to the property because they refer to non-repeated message types, whereas all other writes are to the backing field ([from pubsub.proto here](https://github.com/googleapis/googleapis/blob/master/google/pubsub/v1/pubsub.proto#L405)).

Is there a reason these writes are not always consistently to the backing field?

Thanks :)

**Comment by anandolee** [comment]
non-repeated message field is also write to backing field, please search pushConfig_. Correct me if I misunderstand your question.

I am closing it for clean up. Feel free to reopen if it is still an issue.

**Comment by ObsidianMinor** [comment]
This is writing to the property, not the backing field.
```cs
PushConfig = other.pushConfig_ != null ? other.PushConfig.Clone() : null;
```
To be consistent with other field types it should write to the backing field like this:
```cs
pushConfig_ = other.pushConfig_ != null ? other.pushConfig_.Clone() : null;
```
