### ISSUE TITLE
c++ upgrade from v3.5 to v3.5.1 has type cast conversion RepeatedPtrField exists but is inaccessible

### ISSUE THREAD

**Issue by jdmairs** [google/protobuf#4319]
VS2017 15.4
Our proto files did not change but numerous protoc generated files (*.pb.cc) have a function called InternalSwap that now error 
```
void Equipment::InternalSwap(Equipment* other) {
  using std::swap;
  code_.InternalSwap(&other->code_);
}


```

**Comment by jdmairs** [comment]
The generated stub from 3.5 creates the following source (this works):

code_.InternalSwap( CastToBase(&other->code_));

**Comment by jdmairs** [comment]
If it matters I built the protoc compiler from source.

**Comment by pherl** [comment]
Did you use the protoc to re-generate the sources with the new runtime? Could you link the errors in that case?

**Comment by jdmairs** [comment]
Definitely...that's my point.  The proto input to protoc did not change...only protoc itself (v3.5.1 vs v3.5).  The stubs that are generated between the 2 are different as shown above.

**Comment by acozzette** [comment]
@jdmairs For C++ the protoc version has to exactly match the runtime version. It looks like in this case you are mixing one version of protoc with a runtime library from a different version.

**Comment by acozzette** [comment]
Let me mark this closed because I believe the problem will go away as long as you use a matching protoc and runtime library. Feel free to reopen this if it still persists after that, though.
