### ISSUE TITLE
Add FieldMaskUtil support in C#

### ISSUE THREAD

**Issue by Falco20019** [google/protobuf#4325]
As of today, the C# implementation is missing support for working with `FieldMask`. The message itself exists in `Google.Protobuf.WellKnownTypes`, so it can be used for merging in other languages. But since the `FieldMaskUtil` is missing in C#, merging and working with `FieldMask`s in general has to be done manually.

If no one is working on it, I could also tackle it since I need it myself. Just wanted to make sure it's not done by anyone else right now or if there is a cause why it's not implemented.

**Comment by anandolee** [comment]
Runtime support for FieldMask is optional. There's no specification for FieldMask support. C# has a very limited FieldMask support in FieldMaskPartial.cs.

Merge is not implemented in ieldMaskPartial.cs. Are you happy to create a PR add merge?
You can take the c++ version as an example:
https://github.com/google/protobuf/blob/master/src/google/protobuf/util/field_mask_util.cc#L208

**Comment by anandolee** [comment]
@Falco20019, I am closing this issue for clean up. Once the PR is ready to review, feel free to assign to me for review.

**Comment by Falco20019** [comment]
@anandolee Do you prefer to have it in `FieldMaskPartial` or should I add a `Util` namespace and keep the `FieldMaskUtil` and `FieldMaskTree` in it's separate classes? Last one would be the cleaner option in my opinion, but would be a break with the helpers of other `Partial` classes like with `Duration`.
