### ISSUE TITLE
map support for c#

### ISSUE THREAD

**Issue by anandolee** [google/protobuf#433]
I am going to add map support for c#.

Should implement a dictionary which has a "bool readOnly" like what PopsicleList.cs does. MakeReadOnly() will be called when build. Copy(or Merge) will be called before modify.

@jskeet 
For Reflection API,  c++ and java use different data representations and convert data between the two depending on which API is called. Do you think we should follow this?

**Comment by jskeet** [comment]
I would prefer to just have a single version of the data structure, to me - as a user of the Java API it's never been entirely clear why there are two versions.

However, as I'm looking at an entirely-mutable version now, you *may* want to hold off on map support until we can decide one way or another on that. I guess it depends on how much of the work you think will be portable to the mutable version - all the serialization code will be portable, but I assume that's reasonably simple anyway.

**Comment by anandolee** [comment]
We need to decide the mutable version. However protobuf team want the proto3 support for csharp ASAP. How long do you think we could make the decision for mutable Version?
Can you draft a plan for the mutable version?

**Comment by jskeet** [comment]
Well I'm working on the mutable version as fast as I can bearing in mind that I'm on holiday :) I expect to be able to get a draft of the runtime working within the week, but I don't know how long the generator changes will take.

I think it will definitely be simpler to work with for those who haven't used the builder pattern before - at the cost of the benefits of immutability, of course. The current plan is to have *just* a mutable version of each message, but we could potentially add a "BuildImmutableClone" method later on.

**Comment by jtattermusch** [comment]
Implemented by https://github.com/google/protobuf/pull/543 (and some minor changes afterwards)
