### ISSUE TITLE
Update documentation to clarify that default values are omitted when serialized

### ISSUE THREAD

**Issue by JackGrinningCat** [google/protobuf#4330]
Hi, 

I wanted to use Protobuf. I did not used it before and saw it would good for my use. 

Basically I tried to update the header part of a file at the end of a session and realized that at the beginning had different sizes because the default values which are the same as starting values are ... well do not fit the size I reserved for it, because those values are 0 and got omitted.

So, i tried to find a way around it and it leaded me that i should wrap them to have a worst case size. Well I would not gone this way, using it as header description, if it would have been clearly stated in the documentation. 

Well, i know such documentation task are not very popular. If you point out where I should write this documentary note, I would do so.

Jack

**Comment by thomasvl** [comment]
You can use proto2 syntax instead, then if you explicitly set them to zero (the default) they will still be serialized.

**Comment by TeBoring** [comment]
You can also use wrappers in well know types: https://github.com/google/protobuf/blob/master/src/google/protobuf/wrappers.proto

**Comment by TeBoring** [comment]
Feel free to reopen the issue if there is still question.
