### ISSUE TITLE
(1/1) FatalErrorException Class 'ProtobufMessage' not found  in pb_proto_WhisperTextProtocol.php (line 12)

### ISSUE THREAD

**Issue by rakeshkj** [google/protobuf#4331]
I am trying to built whatsapp application with laravel and successfully installed protobuf but it is still saying   Class 'ProtobufMessage' not found. I have tried many thread over internet but no success. Please suggest how  to resolve this.

I am using php 5.6

**Comment by TeBoring** [comment]
Which version of protobuf php runtime are you using?

**Comment by rakeshkj** [comment]
Hello Paul,

here is protobuf version

[image: Inline image 1]

**Comment by TeBoring** [comment]
Sorry, I can't see the image.

**Comment by TeBoring** [comment]
Closed for now. Feel free to reopen if there is still problem.
