### ISSUE TITLE
scalar type `bytes` are slow when lots of message need to serialize.

### ISSUE THREAD

**Issue by vonnyfly** [google/protobuf#4337]
Hi expert,

In my project, I want to save bit map in disk, so choose type `bytes` to save these bits.
the length is mostly 8, but every time I need serialize 1k items.
The result shows that `bytes` are slow when lots of message need to serialize.

Question:
I found int64/fixed64 is more efficient.  However, I need continus memory's fixed64 to operator bit across int64.

The following proto shouldn't work for me.

```
repeated fixed64 bitmap;
```

**Comment by xfxyjwf** [comment]
How does your message definition look like? How slow is it compared to repeated fixed64? Are you comparing serialization performance or parsing or something else?

**Comment by xfxyjwf** [comment]
and what language are you using?

**Comment by TeBoring** [comment]
Close it for now. Feel free to reopen if there is still problem.
