### ISSUE TITLE
Error using TensorFlow and Google.protobuf

### ISSUE THREAD

**Issue by GoldenScarab569** [google/protobuf#4340]
Hi,

I am following the installation guide: https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/installation.md

as well as this tutorial: 
https://youtu.be/COlbP62-B-U

and when I get to the step where you run jupyter notebook from within the models/object_detection directory I get this error message:
ModuleNotFoundError: No module named 'google.protobuf'

Any thoughts on how to solve this?

**Comment by jo2y** [comment]
I haven't tested it, but I think the tensorflow document is missing a 'sudo pip install protobuf'. That should install the python compiled versions of the protos included in the [protobuf repository](https://github.com/google/protobuf/tree/master/src/google/protobuf). 

After running pip, you should be able to find them under one of these paths depending on your python vresion.
/usr/lib/python2.7/dist-packages/google/protobuf/\*_pb2.py
/usr/lib/python3/dist-packages/google/protobuf/\*_pb2.py

**Comment by TeBoring** [comment]
Close it for now. Feel free to reopen if there is still question.
