### ISSUE TITLE
Python protobuf overlinkage (zlib)

### ISSUE THREAD

**Issue by jakirkham** [google/protobuf#4344]
It appears that the Python C++ bindings end up getting linked to zlib. However there doesn't appear to be any direct linkage of zlib in the Python code. As such it appears this is overlinkage. Would it be possible to change the Python build to avoid linking to zlib?

**Comment by anandolee** [comment]
Python C++ extension is calling protobuf c++ code ( which is under protobuf/src/google/protobuf/ , not only  protobuf/python/google/protobuf/pyext/)

**Comment by jakirkham** [comment]
To the best of my knowledge, only `gzip_stream.h` and `gzip_stream.cc` use zlib directly, which AFAICT are not used in the Python bindings.

**Comment by anandolee** [comment]
Python cpp extension has put all c++ source into its' dependence:
https://github.com/google/protobuf/blob/master/python/setup.py#L208

Do you know if it is the cause?

**Comment by jakirkham** [comment]
Wouldn't think so. That just appears to be Python C++ binding code. It's not pointing to the C++ code outright.

Though noticed this was only happening on Linux and not on macOS, which made me wonder if the Linux loader's behavior was causing zlib to show up. Running `objdump` on the Python Protobuf binding library and looking at the `NEEDED` section shows zlib is not there.

IOW looks like the Python Protobuf binding library is not linked to zlib. Sorry for the noise.
