### ISSUE TITLE
Make C# code generation output a private setter

### ISSUE THREAD

**Issue by 5argon** [google/protobuf#4349]
I notice that the fields in `.proto` file becomes a `public {get; set;}`. Can we input some options for protobuf so that the field is `public {get; private set;}` instead? The generated class is `partial`, I want to make sure that all the protobuf variables can only be set at my side's `partial`.

The current solution I am using is name everything ends with `_pt` like `my_age_pt`, that would becomes `MyAgePt`. Now I create my own property `MyAge` that has `{get; private set;}` mapped to `MyAgePt`. Then I have to make sure by myself to never use anything that ends with `Pt` from the outside. But it is dirty and troublesome to make a new wrapper for every fields like this.

**Comment by anandolee** [comment]
Provide both mutable and immutable API will give us a lot additional work. We suffered for it in Java.

Add options in .proto are also very strict. We take very carefully especially options only for one languages (it is a cost for all languages to add an option).

Thus we do not have plane to add options and provide immutable APIs.
