### ISSUE TITLE
[PHP] pear package failed - "File "./LICENSE" in package.xml does not exist"

### ISSUE THREAD

**Issue by glueric** [google/protobuf#4353]
I followed the directions in the readme, but I can't install the package because there is no LICENSE file.

pear package
Error: File "./LICENSE" in package.xml does not exist

I pulled from the master branch which is I believe v3.5.11.

Would appreciate any help with this problem, thanks.

**Comment by TeBoring** [comment]
I download files from https://pecl.php.net/package/protobuf. I can found LICENSE

**Comment by glueric** [comment]
Oh thanks yeah the package there does have the LICENSE file. Got it installed now.
