### ISSUE TITLE
Generated node files have no set method for map types

### ISSUE THREAD

**Issue by jonahbron** [google/protobuf#4356]
My Proto file looks something like this:

```
message ProviderLoginUrlRequest {
  string name = 1;
  string redirect_uri = 2;
  map<string, string> state = 3;
}
```

The string properties have these methods:

 - `getName`
 - `setName`
 - `getRedirectUri`
 - `setRedirectUri`

But the map type has only these two methods:

 - `getStateMap`
 - `clearStateMap`

Is this an intentional decision, or a bug?  Is there not supposed to be a way to set map properties?

**Comment by jonahbron** [comment]
Never mind!  I figured out that the property always at least has an empty Map object.  To add properties to it, do...

    instance.getStateMap().set('key', 'val');

**Comment by zhushenhang** [comment]
same issue.
Finally found a solution !! 
thanks very much !!!
