### ISSUE TITLE
JS: Node Buffer support removed in 3.4.0

### ISSUE THREAD

**Issue by also** [google/protobuf#4359]
After updating to from 3.3.0 to 3.4.0 or 3.5.0, I started getting the error `AssertionError: Failure: Type not convertible to Uint8Array.` from `byteSourceToUint8Array`.

This happens when I set a value with type `optional bytes` to a Buffer, then call `serializeBinary()` on the object.

google-protobuf used to explicitly support Buffers, but this was removed in https://github.com/google/protobuf/pull/3043. This seems like a breaking change that should not happen in a minor version.

**Comment by acozzette** [comment]
@also Thanks for reporting this, I just merged a fix for it in #4378.
