### ISSUE TITLE
Drop suppport for VS2008

### ISSUE THREAD

**Issue by jtattermusch** [google/protobuf#436]
Currently, the Visual Studio solution and project files are in VS2008 format. As the format has changed with VS2010, everyone wanting to open the solution under VS2010 or VS2013 needs to perform conversion of the project before he can start using it.

My suggestion is to drop support for VS2008 with these benefits:
-- VS2010 and VS2013 users will be able to open the solution without need to convert anything (vast majority of users has VS2010 or VS2013 - and you can have a single solution that supports both)
-- VS2008 is so old that I'd argue nobody would seriously use it (I don't have any numbers though) and the fact that it uses different solution format makes maintenance a pain.
-- gRPC could more easily reference protobuf projects when building gRPC protoc plugins (gRPC supports VS2010+)

**Comment by isanych** [comment]
Unfortunately many corporate users still using vs2008. cmake build or separate 2008/2010 solutions will be much better options than dropping vs2008 support.

**Comment by pgrosu** [comment]
Based on the following site, the extended support for VS2008 ends on 4/10/2018:

https://support.microsoft.com/en-us/lifecycle/search?sort=PN&alpha=Microsoft%20Visual%20Studio%202008&Filter=FilterNO

~p

**Comment by xfxyjwf** [comment]
We have replaced vsproject files with cmake. vs2008 will continue to be supported. Note that this is just for C++ (runtime and protocol compiler). C# may have its own requirement and is not required to support what C++ supports.
