### ISSUE TITLE
enum reserved ranges allow overlap -- off by one error

### ISSUE THREAD

**Issue by jhump** [google/protobuf#4372]
I'm pretty sure that this is due to the fact that the ends of message reserved ranges are open (e.g. end+1), whereas enum reserved ranges are closed.

Here's the simplest repro case:

```proto
syntax = "proto3";

enum V {
  INV = 0;
  reserved 3 to 5;
  reserved 5 to 10;
}
```

It should complain that the two ranges overlap (which is how message reserved ranges work).

And it turns out that it is *trying* to validate overlaps but does so as if the range were open. Example:

```proto
syntax = "proto3";

enum V {
  INV = 0;
  reserved 3 to 5;
  reserved 4 to 10;
}
```

Error message:
```
test.proto: Reserved range 4 to 9 overlaps with already-defined range 3 to 4.
```

**Comment by jhump** [comment]
BTW, I verified that this off-by-one error does not extend to validating that actual values are not using reserved values. And that works fine. Even though the above message prints ranges `3 to 4` and `4 to 9` (instead of 3 to 5 and 5 to 10), it correctly fails if I try to create an enum value assigned to 10.

**Comment by pherl** [comment]
This is probably a bug in validation error printer. Note that the values used in reserved statement in the proto file are always inclusive. The protoc converts it to open end range in the descriptor. As enums allow higher value, we changed the descriptor internal to use inclusive ranges for enum reserve. Looks like the error printer logic isn't updated about this change.

**Comment by acozzette** [comment]
Marking this closed since it sounds like it was fixed.

**Comment by jhump** [comment]
Just tried it out with latest on master and can confirm that it is fixed. Thanks!
