### ISSUE TITLE
Compact varint

### ISSUE THREAD

**Issue by ivan386** [google/protobuf#4376]
advantages:
1. It generates a unique value for each byte sequence.
2. It allows you to encode larger values in a sequence of bytes of the same size.

### Encoding to compact varint:

https://github.com/ivan386/protobuf-1/blob/b76098a2adb7a080231cf14903ab7f3687667ce6/proto/encode.go#L95-L106
```
func EncodeVarint(x uint64) []byte {
	var buf [maxVarintBytes]byte
	var n int
	for n = 0; x > 127; n++ {
		buf[n] = 0x80 | uint8(x&0x7F)
		x >>= 7
		x -= 1
	}
	buf[n] = uint8(x)
	n++
	return buf[0:n]
}
```

#### Example
300 = `000 0010 010 1100`

1. split first 7 bit
 `010 1100`

2. add MSB to it
 `1 010 1100`

3. decrement next bits
 `(000 0010) - 1 = 000 0001`

5. add MSB to it
 `0 000 0001`

6. concat with first
 `1 010 1100 ++ 0 000 0001 =  1 010 1100 0 000 0001`

### Decoding compact varint:
https://github.com/ivan386/protobuf-1/blob/b76098a2adb7a080231cf14903ab7f3687667ce6/proto/decode.go#L63-L78
```
func DecodeVarint(buf []byte) (x uint64, n int) {
	for shift := uint(0); shift < 64; shift += 7 {
		if n >= len(buf) {
			return 0, 0
		}
		b := uint64(buf[n])
		n++
		x += (b & 0xFF) << shift
		if (b & 0x80) == 0 {
			return x, n
		}
	}

	// The number is too large to represent in a 64-bit value.
	return 0, 0
}
```

#### Example
300 in compact varint format = `1 010 1100 0000 000 1`

1. split
```
1 010 1100
0000 000 1
```

2. extend
 ```
1 010 1100 = 0000 000 1 010 1100
0000 000 1 = 0000 000 1 000 0000
```
3. sum
 ```
0000 000 1 010 1100
+
0000 000 1 000 0000
=
0000 001 0 010 1100 
→  256 + 32 + 8 + 4 = 300
```

#### 2 byte max value
```
a := []byte{255,127} //  1111 1111 0111 1111
```
***New 2 byte compact varint max is:*** 16511
encoded: `1 111 1111 0111 111 1` 

1. split
 ```
1 111 1111
0111 111 1
```
2. extend
 ```
1 111 1111 = 0000 000 1 111 1111
0111 111 1 = 0111 111 1 000 0000
```

2. sum
 ```
0000 000 1 111 1111
+
0111 111 1 000 0000
=
1000 000 0 111 1111 = 16511
```

***Old 2 byte varint max is:*** 16383
encoded: `1 111 1111 0 111 1111` 
1. split
 ```
1 111 1111
0 111 1111
```

2. drop MSB
 ```
111 1111
111 1111
```

3. concat
 ```
111 1111 ++ 111 1111
→ 111 1111 111 1111  = 16383
```

***difference:*** 16511 - 16383 = 128

#### 8 byte max value
```
a := []byte{255,255,255,255,255,255,255,127} // 1111 1111 1111 1111 1111 1111 1111 1111 1111 1111 1111 1111 1111 1111 0111 1111
```

```
8 byte compact varint max:  72624976668147839
                            -
old 8 byte varint max:      72057594037927935
                            =
difference:                   567382630219904
```

### difference test code:
```
func DecodeVarintDifference(buf []byte) (difference uint64, newVarint uint64, oldVarint uint64, n int) {
	for shift := uint(0); shift < 64; shift += 7 {
		if n >= len(buf) {
			return 0, 0, 0, 0
		}
		b := uint64(buf[n])
		n++
		newVarint += (b & 0xFF) << shift
		oldVarint |= (b & 0x7F) << shift
		if (b & 0x80) == 0 {
			return newVarint - oldVarint, newVarint, oldVarint, n
		}
	}

	// The number is too large to represent in a 64-bit value.
	return 0, 0, 0, 0
}
```

**Comment by pherl** [comment]
Thanks for the proposal. However, wireformat is fundamental to compatibility and serialization libraries. Internally we have proposed wireformats that are 50% faster than the current encoding format, but still decided not to proceed as the gain is still not justifiable for a wireformat breakage and its introduced complexity.

I guess the gain of the new wireformat in this proposal won't be able to out-weigh of the cost of introducing incomopatibility. I will keep this in the back log and we could revisit when there is a significant gain to create a new wireformat. We can combine the proposals then.
