### ISSUE TITLE
Examples in documentation are broken

### ISSUE THREAD

**Issue by gitcnd** [google/protobuf#4377]
Non-functional examples are the bane of my life.

`curl https://type.googleapis.com/google.profile.Person`
=>
`<title>Error 404 (Not Found)!!1</title>`

**Comment by acozzette** [comment]
Sorry for the confusion around this--the `type_url` field in `google.protobuf.Any` is intended to be a unique identifier for the type, but not necessarily a valid URL that you can look up with an HTTP get request. The comments in `any.proto` have some more details: https://github.com/google/protobuf/blob/5487d8ca0f5d76f930ea24ae62f67703592b2cdf/src/google/protobuf/any.proto#L123
