### ISSUE TITLE
 buffer overrun in ParseFromCodedStream

### ISSUE THREAD

**Issue by feng-y** [google/protobuf#4384]
==50235== Invalid read of size 8
==50235==    at 0x332200F558: ??? (in /lib64/libgcc_s-4.4.7-20120601.so.1)
==50235==    by 0x332201010D: _Unwind_Backtrace (in /lib64/libgcc_s-4.4.7-20120601.so.1)
==50235==    by 0x331FCFD165: backtrace (backtrace.c:109)
==50235==    by 0x3168811D7F: google::GetStackTrace(void**, int, int) (stacktrace_generic-inl.h:46)
==50235==    by 0x3168815DD0: google::(anonymous namespace)::FailureSignalHandler(int, siginfo*, void*) (signalhandler.cc:306)
==50235==    by 0x332040F66F: ??? (in /lib64/libpthread-2.17.so)
==50235==    by 0x707F97: std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(std::string const&) (basic_string.tcc:169)
==50235==    by 0x38003A9F: vgMemCheck___builtin_vec_delete (mc_malloc_wrappers.c:509)
**==50235==  Address 0x36e5a7f0 is 0 bytes after a block of size 384 alloc'd** 
==50235==    at 0x4A07BA7: operator new(unsigned long) (vg_replace_malloc.c:334)
==50235==    by 0x4CAB00: google::protobuf::Map<std::string, user_proto::UserStatInfo>::MapAllocator<std::tr1::__detail::_Hash_node<std::pair<std::string const, google::protobuf::MapPair<std::string, user_proto::UserStatInfo>*>, false>*>::allocate(unsigned long, std::tr1::__detail::_Hash_node<std::pair<std::string const, google::protobuf::MapPair<std::string, user_proto::UserStatInfo>*>, false>* const*) (map.h:599)
==50235==    by 0x4C878C: std::tr1::_Hashtable<std::string, std::pair<std::string const, google::protobuf::MapPair<std::string, user_proto::UserStatInfo>*>, google::protobuf::Map<std::string, user_proto::UserStatInfo>::MapAllocator<std::pair<std::string const, google::protobuf::MapPair<std::string, user_proto::UserStatInfo>*> >, std::_Select1st<std::pair<std::string const, google::protobuf::MapPair<std::string, user_proto::UserStatInfo>*> >, std::equal_to<std::string>, google::protobuf::hash<std::string>, std::tr1::__detail::_Mod_range_hashing, std::tr1::__detail::_Default_ranged_hash, std::tr1::__detail::_Prime_rehash_policy, false, false, true>::_M_allocate_buckets(unsigned long) (hashtable.h:493)
==50235==    by 0x4C56CB: std::tr1::_Hashtable<std::string, std::pair<std::string const, google::protobuf::MapPair<std::string, user_proto::UserStatInfo>*>, google::protobuf::Map<std::string, user_proto::UserStatInfo>::MapAllocator<std::pair<std::string const, google::protobuf::MapPair<std::string, user_proto::UserStatInfo>*> >, std::_Select1st<std::pair<std::string const, google::protobuf::MapPair<std::string, user_proto::UserStatInfo>*> >, std::equal_to<std::string>, google::protobuf::hash<std::string>, std::tr1::__detail::_Mod_range_hashing, std::tr1::__detail::_Default_ranged_hash, std::tr1::__detail::_Prime_rehash_policy, false, false, true>::_M_rehash(unsigned long) (hashtable.h:1148)
==50235==    by 0x4C2CCE: std::tr1::_Hashtable<std::string, std::pair<std::string const, google::protobuf::MapPair<std::string, user_proto::UserStatInfo>*>, google::protobuf::Map<std::string, user_proto::UserStatInfo>::MapAllocator<std::pair<std::string const, google::protobuf::MapPair<std::string, user_proto::UserStatInfo>*> >, std::_Select1st<std::pair<std::string const, google::protobuf::MapPair<std::string, user_proto::UserStatInfo>*> >, std::equal_to<std::string>, google::protobuf::hash<std::string>, std::tr1::__detail::_Mod_range_hashing, std::tr1::__detail::_Default_ranged_hash, std::tr1::__detail::_Prime_rehash_policy, false, false, true>::_M_insert_bucket(std::pair<std::string const, google::protobuf::MapPair<std::string, user_proto::UserStatInfo>*> const&, unsigned long, unsigned long) (hashtable.h:862)
==50235==    by 0x4BF8BE: std::tr1::__detail::_Map_base<std::string, std::pair<std::string const, google::protobuf::MapPair<std::string, user_proto::UserStatInfo>*>, std::_Select1st<std::pair<std::string const, google::protobuf::MapPair<std::string, user_proto::UserStatInfo>*> >, true, std::tr1::_Hashtable<std::string, std::pair<std::string const, google::protobuf::MapPair<std::string, user_proto::UserStatInfo>*>, google::protobuf::Map<std::string, user_proto::UserStatInfo>::MapAllocator<std::pair<std::string const, google::protobuf::MapPair<std::string, user_proto::UserStatInfo>*> >, std::_Select1st<std::pair<std::string const, google::protobuf::MapPair<std::string, user_proto::UserStatInfo>*> >, std::equal_to<std::string>, google::protobuf::hash<std::string>, std::tr1::__detail::_Mod_range_hashing, std::tr1::__detail::_Default_ranged_hash, std::tr1::__detail::_Prime_rehash_policy, false, false, true> >::operator[](std::string const&) (hashtable_policy.h:531)
==50235==    by 0x4BC020: google::protobuf::Map<std::string, user_proto::UserStatInfo>::operator[](std::string const&) (map.h:1513)
==50235==    by 0x4B925D: google::protobuf::internal::MapEntryLite<std::string, user_proto::UserStatInfo, (google::protobuf::internal::WireFormatLite::FieldType)9, (google::protobuf::internal::WireFormatLite::FieldType)11, 0>::Parser<google::protobuf::internal::MapField<std::string, user_proto::UserStatInfo, (google::protobuf::internal::WireFormatLite::FieldType)9, (google::protobuf::internal::WireFormatLite::FieldType)11, 0>, google::protobuf::Map<std::string, user_proto::UserStatInfo> >::MergePartialFromCodedStream(google::protobuf::io::CodedInputStream*) (map_entry_lite.h:339)
==50235==    by 0x4B6319: bool google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual<google::protobuf::internal::MapEntryLite<std::string, user_proto::UserStatInfo, (google::protobuf::internal::WireFormatLite::FieldType)9, (google::protobuf::internal::WireFormatLite::FieldType)11, 0>::Parser<google::protobuf::internal::MapField<std::string, user_proto::UserStatInfo, (google::protobuf::internal::WireFormatLite::FieldType)9, (google::protobuf::internal::WireFormatLite::FieldType)11, 0>, google::protobuf::Map<std::string, user_proto::UserStatInfo> > >(google::protobuf::io::CodedInputStream*, google::protobuf::internal::MapEntryLite<std::string, user_proto::UserStatInfo, (google::protobuf::internal::WireFormatLite::FieldType)9, (google::protobuf::internal::WireFormatLite::FieldType)11, 0>::Parser<google::protobuf::internal::MapField<std::string, user_proto::UserStatInfo, (google::protobuf::internal::WireFormatLite::FieldType)9, (google::protobuf::internal::WireFormatLite::FieldType)11, 0>, google::protobuf::Map<std::string, user_proto::UserStatInfo> >*) (wire_format_lite_inl.h:496)
==50235==    by 0x4AE044: user_proto::UserFeature::MergePartialFromCodedStream(google::protobuf::io::CodedInputStream*) (user_feature.pb.cc:1944)
==50235==    by 0x31678E8EEE: InlineMergeFromCodedStream (message_lite.cc:117)
==50235==    by 0x31678E8EEE: InlineParseFromCodedStream (message_lite.cc:128)

**Comment by xfxyjwf** [comment]
Can you provide a simple program that can reproduce this stack trace? We have seen many crashes with stack traces in protobuf code base but almost all of them are caused by bugs in users' own code.

**Comment by acozzette** [comment]
@feng-y I'm going to close this issue since we haven't heard a response back in a few days, but feel free to reopen it if you're still having a problem.
