### ISSUE TITLE
missing generic gcc 64-bit Release_CompareAndSwap atomicops in 3.5.2

### ISSUE THREAD

**Issue by salamaniibm** [google/protobuf#4386]
3.5.2 bumbed. On big endian still facing issue of `undefined reference togoogle::protobuf::internal::Release_CompareAndSwap(long volatile*, long, long)'` 

Issue fixed by #3937 

When this change will be tagged?

**Comment by acozzette** [comment]
We don't have a definitive date yet but we plan to do a 3.6 release soon, probably in the next week or two.
