### ISSUE TITLE
String value mutated into unreadable values after  json_format.MessageToJson

### ISSUE THREAD

**Issue by heng2j** [google/protobuf#4390]
Hi Team,

I am using json_format.MessageToJson to conver a message result from my tensorflow serving request.

When i just print the result out, it looks as expected. However, once I convert the result into json string. The string value mutated to be humanly unreadable. Can you advise? 

**Sample Code:**
print(result)
json_string = json_format.MessageToJson(result)
print("json_string: ", json_string)

**Sample output**
outputs {
  key: "classes"
  value {
    dtype: DT_STRING
    tensor_shape {
      dim {
        size: 4
      }
    }
    string_val: "reserve"
    string_val: "want"
  }
}
outputs {
  key: "prediction"
  value {
    dtype: DT_FLOAT
    tensor_shape {
      dim {
        size: 1
      }
      dim {
        size: 4
      }
    }
    float_val: 0.0154006108642
    float_val: 0.0376211367548
    float_val: 0.860316336155
    float_val: 0.086661927402
  }
}

json_string:  {
  "outputs": {
    "classes": {
      "dtype": "DT_STRING", 
      "tensorShape": {
        "dim": [
          {
            "size": "4"
          }
        ]
      }, 
      "stringVal": [
        "cmVzZXJ2ZQ==", 
        "d2FudA=="
      ]
    }, 
    "prediction": {
      "dtype": "DT_FLOAT", 
      "floatVal": [
        0.015400610864162445, 
        0.037621136754751205, 
        0.8603163361549377, 
        0.0866619274020195
      ], 
      "tensorShape": {
        "dim": [
          {
            "size": "1"
          }, 
          {
            "size": "4"
          }
        ]
      }
    }
  }
}

**Comment by xfxyjwf** [comment]
It seems your string value is actually "bytes" fields. Bytes fields are encoding using base64.

**Comment by swateek** [comment]
Is there a way to convert it back? Or disallow conversion into base64?

**Comment by xfxyjwf** [comment]
You can avoid the conversion by changing the field type from "bytes" to "string".

**Comment by swateek** [comment]
Thanks, that I could figure out but unfortunately in my case I cannot do this.
