### ISSUE TITLE
How to compile libmirprotobuf ?

### ISSUE THREAD

**Issue by ZeroCool11000** [google/protobuf#4392]
How to get and compile libmirprotobuf ?

Best regards.

**Comment by ZeroCool11000** [comment]
Because i need a new version for Nvidia TX2, based on protobuf 3.5.x to get used of a newer version of gstreamer 1.13.x.

Best regards

**Comment by acozzette** [comment]
@ZeroCool11000 We don't maintain libmirprotobuf. I hadn't heard of that until now but it looks to me like that is part of the Mir codebase here: https://github.com/MirServer/mir/tree/master/src/protobuf

**Comment by ZeroCool11000** [comment]
Ok thx i will try it to recompile it.
