### ISSUE TITLE
Using "DescriptorPool:: generated_pool () ->FindMessageTypeByName" can only find a part of the type

### ISSUE THREAD

**Issue by weike20** [google/protobuf#4394]
```
This is my code:
-------------------------------------------------------------------------------------------------
using namespace google::protobuf;
std::string type_length_str(data,data+sizeof(int));
int type_length = (*(int*)type_length_str.data());
std::string type_name(data+sizeof(int),type_length);
int total_length = sizeof(int)+type_length;
const Descriptor* descriptor =DescriptorPool::generated_pool()->FindMessageTypeByName(type_name);
assert(descriptor != std::nullptr_t());

auto factory = google::protobuf::MessageFactory::generated_factory();
const Message* msg_type = factory->GetPrototype(descriptor);
boost::shared_ptr<Message>  msg_ptr(msg_type ->New()) ;
if(msg_ptr ->ParseFromArray(data+total_length,length-total_length))
    return msg_ptr;
return std::nullptr_t();
```
-------------------------------------------------------------------------------------------------

**Comment by acozzette** [comment]
@weike20 What do you mean when you say that FindMessageTypeByName() can only find part of the type?

**Comment by weike20** [comment]
In my project,Some of the messages in proto files can be found by that function, others do not.There are two proto files，The message in "world_message.proto" can be found, but "gate_message.proto" does not work. I debugged with GDB, and found that the "FindMessageTypeWithName" function could not find the message in the gate_message.proto file, but The function parameters I have passed are correct(ProtoBuf.CMD_GET_LOGIC_SERVER_STATUS in the gate_message.proto).I don't know why,thank you for your attention.

`------------------------------------------------world_message.proto------------------------------------------------
syntax = "proto2";
import "msg_id.proto";
import "return_code.proto";

package ProtoBuf;

message CMD_INIT_REMOTE
{
	optional MSG_ID id= 1 [default=ID_INIT_REMOTE];
	optional int32 session_type = 2;
}

message CMD_INIT_REMOTE_R
{
	optional MSG_ID id = 1 [default=ID_INIT_REMOTE_R];
	optional RETURN_CODE return_code = 2[default=CODE_NORMAL];
}

message CMD_NOTIFY_KICKOUT_USER
{
	optional MSG_ID id = 1[default=ID_NOTIFY_KICKOUT_USER];
	optional uint32 user_id = 2;
}
message CMD_NOTIFY_GATESERVER_STATUS
{
	optional MSG_ID id = 1[default=ID_NOTIFY_GATESERVER_STATUS];
	optional uint32 session_count =2;
}`
`------------------------------------------------gate_message.proto------------------------------------------------
syntax = "proto2";
import "msg_id.proto";
import "return_code.proto";

package ProtoBuf;

message CMD_LOGIN_GATESERVER
{
	optional MSG_ID id = 1[default=ID_LOGIN_GATESERVER];
	optional uint32 user_id = 2;
	optional string token = 3;	
}

message CMD_LOGIN_GATESERVER_R
{
	optional MSG_ID id = 1[default=ID_LOGIN_GATESERVER_R];
	optional RETURN_CODE return_code =2 [default=CODE_NORMAL];
}

message CMD_CREATE_USER
{
	optional MSG_ID id = 1[default=ID_CREATE_USER];
	optional uint32 user_id = 2;
}

message CMD_CREATE_USER_R
{
	optional MSG_ID id = 1[default=ID_CREATE_USER_R];
	optional RETURN_CODE return_code =2 [default=CODE_NORMAL];
	optional uint32 user_id = 3;
}

message CMD_NOTIFY_REMOVE_USER
{
	optional MSG_ID id = 1[default=ID_NOTIFY_REMOVE_USER];
	optional uint32 user_id = 2;
}
message CMD_GET_LOGIC_SERVER_STATUS
{
	optional MSG_ID id = 1[default=ID_GET_LOGIC_SERVER_STATUS];
}
message CMD_GET_LOGIC_SERVER_STATUS_R
{
	optional MSG_ID id = 1[default=ID_GET_LOGIC_SERVER_STATUS_R];
	optional uint32 user_count = 2;
}`

**Comment by weike20** [comment]
What is even more surprising is that if I can't find "ProtoBuf:: GET_THE_LOGIC_SERVER_STATUS", then i call "ProtoBuf:: GET_THE_LOGIC_SERVER_STATUS:: descriptor ()" function before "FindMessageTypeByName",it works.

**Comment by acozzette** [comment]
@weike20 I think what's probably happening is that the linker is dropping the object file associated with one of your pb.cc files, because your code doesn't have any references to that object file. That is probably why `FindMessageTypeByName()` suddenly works if you explicitly reference the message first.

To fix that problem, you could either just make sure to reference all the messages you need, or tweak your build setup so that the linker always includes the object files even if they are not referenced.

**Comment by weike20** [comment]
That's true.It's a compilation error. I compiled two static libraries, but  didn't add any header files in "CMakeLists.txt". I thought g++ would automatically contain them, finally I added corresponding statements in "CMakeLists.txt",it works.Thank you very much.

**Comment by acozzette** [comment]
Great, I'm glad it's working now!

**Comment by mkckr0** [comment]
No! I think it's not a linking problem. The problem occurs in runtime. Look at the follow code:
```cpp
// pkg::MessageA is in example.proto

//  case A
pkg::MessageA::descriptor();
auto x = protobuf::DescriptorPool::generated_pool()->FindFileByName("example.proto");

// case B
auto x = protobuf::DescriptorPool::generated_pool()->FindFileByName("example.proto");
pkg::MessageA::descriptor();
```
The result is: case A'`x` is not NULL, but case B'`x` is NULL.
So I guess the object is loaded dynamically gradually.
But I can't find a good method to construct all objects in google's docs.

**Comment by acozzette** [comment]
@mkckr0 Is your example code executing pre-main? Once `main` begins, all the protos should have been loaded into the descriptor pool, but pre-main they might not be present yet.

**Comment by weike20** [comment]
> No! I think it's not a linking problem. The problem occurs in runtime. Look at the follow code:
> 
> ```c++
> // pkg::MessageA is in example.proto
> 
> //  case A
> pkg::MessageA::descriptor();
> auto x = protobuf::DescriptorPool::generated_pool()->FindFileByName("example.proto");
> 
> // case B
> auto x = protobuf::DescriptorPool::generated_pool()->FindFileByName("example.proto");
> pkg::MessageA::descriptor();
> ```
> 
> The result is: case A'`x` is not NULL, but case B'`x` is NULL.
> So I guess the object is loaded dynamically gradually.
> But I can't find a good method to construct all objects in google's docs.

I see your point and i agree with you

> No! I think it's not a linking problem. The problem occurs in runtime. Look at the follow code:
> 
> ```c++
> // pkg::MessageA is in example.proto
> 
> //  case A
> pkg::MessageA::descriptor();
> auto x = protobuf::DescriptorPool::generated_pool()->FindFileByName("example.proto");
> 
> // case B
> auto x = protobuf::DescriptorPool::generated_pool()->FindFileByName("example.proto");
> pkg::MessageA::descriptor();
> ```
> 
> The result is: case A'`x` is not NULL, but case B'`x` is NULL.
> So I guess the object is loaded dynamically gradually.
> But I can't find a good method to construct all objects in google's docs.

I see your point and i agree with you
