### ISSUE TITLE
When the field is the default, the field disappears after json

### ISSUE THREAD

**Issue by helpceo** [google/protobuf#4400]
example:The value is 0 false, empty string.After json, they all disappear.

**Comment by thomasvl** [comment]
https://developers.google.com/protocol-buffers/docs/proto3#json

> If a field has the default value in the protocol buffer, it will be omitted in the JSON-encoded data by default to save space.

**Comment by xfxyjwf** [comment]
Omitting default value fields is the default behavior. Depending on what language you are using, there may be an option to print all default value fields, e.g., in Java:
https://github.com/google/protobuf/blob/master/java/util/src/main/java/com/google/protobuf/util/JsonFormat.java#L170
