### ISSUE TITLE
Support for Protobuf on Power(ppc64le)

### ISSUE THREAD

**Issue by pravin-dsilva** [google/protobuf#4401]
This issue is with regards to adding support on Power ppc64le arch. There have been efforts made to add support in the past (https://github.com/google/protobuf/pull/3506) . I would like to carry this forward so that it can be tested and have a distribution for ppc64le

So far, upon building and running tests on the latest code have been successful on PPC Ubuntu by using the patch from https://github.com/google/protobuf/pull/3506 with minor modifications. Further testing is  underway.

Please let me know your thoughts or suggestions.

**Comment by xfxyjwf** [comment]
We are generally happy to accept pull requests that make protobuf compile on more platforms. Except for those that are covered by our testing environment (windows, macosx, ubuntu), support for other platforms is best-effort only though.

**Comment by pravin-dsilva** [comment]
Thanks! Sure, there is effort being put at our end to test and contribute to the changes required for PPC.  I will open up a PR in the next few days so that it can be reviewed when tests are successful.
