### ISSUE TITLE
Protobuf CocoaPod depends upon umbrella header ordering

### ISSUE THREAD

**Issue by paulb777** [google/protobuf#4403]
CocoaPods will fail to build the Protobuf CocoaPod if the explicitly pathed headers are ordered before the wild carded headers in the generated umbrella header file.

This is exposed in the unreleased CocoaPods master branch. CocoaPods may change back to the old behavior, but it would probably be good to make the Protobuf CocoaPod less fragile.

Details and example at https://github.com/CocoaPods/CocoaPods/issues/7518.

**Comment by paulb777** [comment]
Part of the problem seems to be a circular dependency chain between Any.pbobjc.h and GPBWellKnownTypes.h. Other strange things are GPBProtocolBuffers.h being kind of a duplicate umbrella header and header sequencing to test the protoc versioning.

**Comment by thomasvl** [comment]
This sounds a little like #4301, is it the same thing?

From a quick look at the linked issue, that seems to say it is an ordering problem, but it isn't clear that protos has and ordering problem vs. something causing the imports to be found via different paths, so the `#import` doesn't collapse into a single definition?

**Comment by thomasvl** [comment]
> Other strange things are GPBProtocolBuffers.h being kind of a duplicate umbrella header

I'm not sure how to resolve this one.  Cocoapods isn't the only packaging system, we need to provide an umbrella for others (Carthage, direct source usage, etc).

> header sequencing to test the protoc versioning

Not sure I follow this one, this should just mean the defines have to exist before we import other headers, no?

**Comment by paulb777** [comment]
If you create your own module_map with your own umbrella header - https://guides.cocoapods.org/syntax/podspec.html#module_map, then CocoaPods shouldn't generate one.
