### ISSUE TITLE
integers being returned as string in MessageToJson

### ISSUE THREAD

**Issue by skgbanga** [google/protobuf#4408]
https://github.com/google/protobuf/blob/ed4321d1cb33199984118d801956822842771e7e/python/google/protobuf/json_format.py#L284

Is there any reason why integers being returned as a string in the code above?

**Comment by acozzette** [comment]
@skgbanga The JSON format represents int64 fields as a string because otherwise the value might not have an exact representation in JSON. JSON's number type is a double, which can't represent all int64 values.
