### ISSUE TITLE
Make check fail in Mac OS

### ISSUE THREAD

**Issue by plzdaye** [google/protobuf#4414]
when I am run make check, the output is repeating samething, can anybody help me?

following is the message of terminal:

Making check in .
/Library/Developer/CommandLineTools/usr/bin/make  check-local
Making lib/libgmock.a lib/libgmock_main.a in gmock
make[3]: `lib/libgmock.la' is up to date.
make[3]: `lib/libgmock_main.la' is up to date.
make[3]: `lib/libgtest.la' is up to date.
make[3]: `lib/libgtest_main.la' is up to date.
Making check in src
depbase=`echo google/protobuf/arenastring.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
	/bin/sh ../libtool  --tag=CXX   --mode=compile g++ -std=c++11 -DHAVE_CONFIG_H -I. -I..    -D_THREAD_SAFE  -DHAVE_PTHREAD=1 -DHAVE_ZLIB=1 -Wall -Wno-sign-compare -O2 -g -DNDEBUG -MT google/protobuf/arenastring.lo -MD -MP -MF $depbase.Tpo -c -o google/protobuf/arenastring.lo google/protobuf/arenastring.cc &&\
	mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  g++ -std=c++11 -DHAVE_CONFIG_H -I. -I.. -D_THREAD_SAFE -DHAVE_PTHREAD=1 -DHAVE_ZLIB=1 -Wall -Wno-sign-compare -O2 -g -DNDEBUG -MT google/protobuf/arenastring.lo -MD -MP -MF google/protobuf/.deps/arenastring.Tpo -c google/protobuf/arenastring.cc  -fno-common -DPIC -o google/protobuf/.libs/arenastring.o
libtool: compile:  g++ -std=c++11 -DHAVE_CONFIG_H -I. -I.. -D_THREAD_SAFE -DHAVE_PTHREAD=1 -DHAVE_ZLIB=1 -Wall -Wno-sign-compare -O2 -g -DNDEBUG -MT google/protobuf/arenastring.lo -MD -MP -MF google/protobuf/.deps/arenastring.Tpo -c google/protobuf/arenastring.cc -o google/protobuf/arenastring.o >/dev/null 2>&1
depbase=`echo google/protobuf/extension_set.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
	/bin/sh ../libtool  --tag=CXX   --mode=compile g++ -std=c++11 -DHAVE_CONFIG_H -I. -I..    -D_THREAD_SAFE  -DHAVE_PTHREAD=1 -DHAVE_ZLIB=1 -Wall -Wno-sign-compare -O2 -g -DNDEBUG -MT google/protobuf/extension_set.lo -MD -MP -MF $depbase.Tpo -c -o google/protobuf/extension_set.lo google/protobuf/extension_set.cc &&\
	mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  g++ -std=c++11 -DHAVE_CONFIG_H -I. -I.. -D_THREAD_SAFE -DHAVE_PTHREAD=1 -DHAVE_ZLIB=1 -Wall -Wno-sign-compare -O2 -g -DNDEBUG -MT google/protobuf/extension_set.lo -MD -MP -MF google/protobuf/.deps/extension_set.Tpo -c google/protobuf/extension_set.cc  -fno-common -DPIC -o google/protobuf/.libs/extension_set.o
libtool: compile:  g++ -std=c++11 -DHAVE_CONFIG_H -I. -I.. -D_THREAD_SAFE -DHAVE_PTHREAD=1 -DHAVE_ZLIB=1 -Wall -Wno-sign-compare -O2 -g -DNDEBUG -MT google/protobuf/extension_set.lo -MD -MP -MF google/protobuf/.deps/extension_set.Tpo -c google/protobuf/extension_set.cc -o google/protobuf/extension_set.o >/dev/null 2>&1
depbase=`echo google/protobuf/generated_message_util.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
	/bin/sh ../libtool  --tag=CXX   --mode=compile g++ -std=c++11 -DHAVE_CONFIG_H -I. -I..    -D_THREAD_SAFE  -DHAVE_PTHREAD=1 -DHAVE_ZLIB=1 -Wall -Wno-sign-compare -O2 -g -DNDEBUG -MT google/protobuf/generated_message_util.lo -MD -MP -MF $depbase.Tpo -c -o google/protobuf/generated_message_util.lo google/protobuf/generated_message_util.cc &&\
	mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  g++ -std=c++11 -DHAVE_CONFIG_H -I. -I.. -D_THREAD_SAFE -DHAVE_PTHREAD=1 -DHAVE_ZLIB=1 -Wall -Wno-sign-compare -O2 -g -DNDEBUG -MT google/protobuf/generated_message_util.lo -MD -MP -MF google/protobuf/.deps/generated_message_util.Tpo -c google/protobuf/generated_message_util.cc  -fno-common -DPIC -o google/protobuf/.libs/generated_message_util.o
libtool: compile:  g++ -std=c++11 -DHAVE_CONFIG_H -I. -I.. -D_THREAD_SAFE -DHAVE_PTHREAD=1 -DHAVE_ZLIB=1 -Wall -Wno-sign-compare -O2 -g -DNDEBUG -MT google/protobuf/generated_message_util.lo -MD -MP -MF google/protobuf/.deps/generated_message_util.Tpo -c google/protobuf/generated_message_util.cc -o google/protobuf/generated_message_util.o >/dev/null 2>&1
depbase=`echo google/protobuf/generated_message_table_driven_lite.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
	/bin/sh ../libtool  --tag=CXX   --mode=compile g++ -std=c++11 -DHAVE_CONFIG_H -I. -I..    -D_THREAD_SAFE  -DHAVE_PTHREAD=1 -DHAVE_ZLIB=1 -Wall -Wno-sign-compare -O2 -g -DNDEBUG -MT google/protobuf/generated_message_table_driven_lite.lo -MD -MP -MF $depbase.Tpo -c -o google/protobuf/generated_message_table_driven_lite.lo google/protobuf/generated_message_table_driven_lite.cc &&\
	mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  g++ -std=c++11 -DHAVE_CONFIG_H -I. -I.. -D_THREAD_SAFE -DHAVE_PTHREAD=1 -DHAVE_ZLIB=1 -Wall -Wno-sign-compare -O2 -g -DNDEBUG -MT google/protobuf/generated_message_table_driven_lite.lo -MD -MP -MF google/protobuf/.deps/generated_message_table_driven_lite.Tpo -c google/protobuf/generated_message_table_driven_lite.cc  -fno-common -DPIC -o google/protobuf/.libs/generated_message_table_driven_lite.o
libtool: compile:  g++ -std=c++11 -DHAVE_CONFIG_H -I. -I.. -D_THREAD_SAFE -DHAVE_PTHREAD=1 -DHAVE_ZLIB=1 -Wall -Wno-sign-compare -O2 -g -DNDEBUG -MT google/protobuf/generated_message_table_driven_lite.lo -MD -MP -MF google/protobuf/.deps/generated_message_table_driven_lite.Tpo -c google/protobuf/generated_message_table_driven_lite.cc -o google/protobuf/generated_message_table_driven_lite.o >/dev/null 2>&1
depbase=`echo google/protobuf/message_lite.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
	/bin/sh ../libtool  --tag=CXX   --mode=compile g++ -std=c++11 -DHAVE_CONFIG_H -I. -I..    -D_THREAD_SAFE  -DHAVE_PTHREAD=1 -DHAVE_ZLIB=1 -Wall -Wno-sign-compare -O2 -g -DNDEBUG -MT google/protobuf/message_lite.lo -MD -MP -MF $depbase.Tpo -c -o google/protobuf/message_lite.lo google/protobuf/message_lite.cc &&\
	mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  g++ -std=c++11 -DHAVE_CONFIG_H -I. -I.. -D_THREAD_SAFE -DHAVE_PTHREAD=1 -DHAVE_ZLIB=1 -Wall -Wno-sign-compare -O2 -g -DNDEBUG -MT google/protobuf/message_lite.lo -MD -MP -MF google/protobuf/.deps/message_lite.Tpo -c google/protobuf/message_lite.cc  -fno-common -DPIC -o google/protobuf/.libs/message_lite.o
^Cmake[1]: *** [google/protobuf/message_lite.lo] Error 1
make: *** [check-recursive] Interrupt: 2

**Comment by acozzette** [comment]
@plzdaye I don't quite understand what the problem is--it looks from your error message like you hit Ctrl-C before the build finished. Could you elaborate on what's going wrong?
