### ISSUE TITLE
How to convert a protobuf message to a human-readable format?

### ISSUE THREAD

**Issue by dingrui37** [google/protobuf#4416]
For example, 
message S {
   string name = 1;
   bytes test = 2;
}
for a S object, I want to print like 
   "name" : "xxx"
    "test" : "10 11 12"

**Comment by acozzette** [comment]
@dingrui37 What language are you using?

**Comment by dingrui37** [comment]
@acozzette sorry for late, the language I use is java.

**Comment by acozzette** [comment]
@dingrui37 In Java you should be able to just call `toString()` on a message to get a human-readable format.
