### ISSUE TITLE
protoc-artifacts Dockerfile: `git clone` fails

### ISSUE THREAD

**Issue by ericgribkoff** [google/protobuf#4419]
The `git clone --depth 1 https://github.com/google/protobuf.git` command in `protoc-artifacts/Dockerfile` fails with a pretty generic error message and error code 128. Entering the docker container and running `GIT_CURL_VERBOSE=1 GIT_TRACE=1 git clone ...` shows that the error is caused by a failure in the TLS negotiation. 

I believe this was caused when Github dropped support for TLS1.0 and TLS1.1: https://githubengineering.com/crypto-removal-notice/

The Dockerfile uses CentOS 6.6. It appears that this version of CentOS does not include support for TLS1.2, at least not in the libcurl library used by git: out-of-the-box, `curl` cannot fetch a Github web page. I used yum in update libcurl, and then curl recognized the `--tlsv1.2` flag and was able to get a web page from Github, but doesn't change the failure with git clone.

(FWIW, I tried changing the dockerfile to use CentOS 7, which does support TLS1.2, and encountered an unrelated error with the command in the dockerfile's last line. Using CentOS 6.9 instead, everything built fine, but I'm not sure what reasons went into choosing 6.6 and if 6.9 may have other unwanted side-effects)

**Comment by ericgribkoff** [comment]
cc @ejona86

**Comment by ejona86** [comment]
We don't actually need git to do a release build. `wget https://github.com/grpc/grpc-java/archive/v1.10.1.zip`  worked fine for me within the container.

I was already wanting the git clone in the Dockerfile to be removed, and I did this for grpc in grpc/grpc-java#4087 (but we've not yet swapped to it for our release process).

**Comment by ejona86** [comment]
CC @zhangkun83 @zpencer

**Comment by xfxyjwf** [comment]
Not sure what's the right fix here. Can you folks propose a PR?

**Comment by ejona86** [comment]
I'm working on a PR. There will need to be changes release documentation elsewhere, but I'm not sure where to change that.

**Comment by xfxyjwf** [comment]
@ejona86 Thanks! I think updating the README.md in protoc-artifacts should be good enough:
https://github.com/google/protobuf/tree/master/protoc-artifacts#tips-for-deploying-on-linux
