### ISSUE TITLE
How to .Unpack( an Any Message in Python

### ISSUE THREAD

**Issue by TimmKayserHere** [google/protobuf#4420]
Hi there,

I have some trouble, unpacking an Any message from a protobuf message. Here is a description of what I did:

1. While building my Protobuf message, I generate a message based on my proprietary protocol file as follow:
```
# we generate our proprietary message based on our proprietary proto-file
myMessageExtension = extension_pb2.GeneralContent_Extension()
myMessageExtension.fancyID = 345
myMessageExtension.fancyProjectDescription = "All awesome!"
```

2. I hand-over the proprietary message to my general message, that contains the "extension" defined as Any:
```
# We generate a carrier message to push our proprietary message into the Any-extension of the official spec
some_any = any_pb2.Any()
some_any.Pack(myMessageExtension)
```

3. I attach the extension to my general message:
```
# Fourth, we push our proprietary message to the extension of the official standard
myMessage.extension.CopyFrom(some_any)
```

So far, so good.

But now I want to read the same extension:

4. I generate a local any, copy the content of the already de-serialized protobuf message in there and unpack it:
```
# we now get the extension out of the protobuf
some_any2 = any_pb2.Any()
some_any2.CopyFrom(myMessage_rewrite.extension)
some_any2.Unpack(extension_pb2.GeneralContent_Extension())
```

5. I double-check, if the some_any2 message now reflects the extension definition (very simple message with just the two attributes):
```
print some_any2
print "---"
print myMessage_rewrite.extension
```

6. ISSUE: Both prints are reflecting just the same message (see below). My web-search unveiled, that the "Unpack(" will just return a "TRUE", if it is possible to convert. **But: WHERE DO I FIND THE UNPACKED message itself?**

```
[type.googleapis.com/project.protobuf.extension.data.GeneralContent_Extension] {
  fancyID: 345
  fancyProjectDescription: "All awesome!"
}
---
[type.googleapis.com/project.protobuf.extension.data.GeneralContent_Extension] {
  fancyID: 345
  fancyProjectDescription: "All awesome!"
}
```

**Comment by anandolee** [comment]
In for 4th step, you need to create your message before unpack. Please try:

some_any2 = any_pb2.Any()
some_any2.CopyFrom(myMessage_rewrite.extension)
unpacked_msg = extension_pb2.GeneralContent_Extension())
some_any2.Unpack(unpacked_msg)

**Comment by lukemaxwell** [comment]
I am experiencing the same difficulty in obtaining the unpacked message. I believe I have replicated the steps above from @anandolee, but I still can only obtain a boolean rather than the unpacked message.

I've declared some simple protobufs:
```
# A message envelope for carrying any message
message MessageEnvelope {
  google.protobuf.Any any_message = 2;
}

# A simple greeting message
message Greeting {
  string name = 1;
}
```

Then attempted to pack and unpack a message using the message envelope:
```
# Create the greeting message
greeting = Greeting(name='bob')

# Pack the greeting message into an Any message
any = Any()
any.Pack(greeting)

# Copy the any message to the message envelope  
message_envelope = MessageEnvelope()
message_envelope.any_message.CopyFrom(any)

# Now unpack the message at the other side...
any2 = Any()
# Copy the value from the message envelope
any2.CopyFrom(message_envelope.any_message)

unpacked_message = Greeting()
any2.Unpack(unpacked_message)
>>>True
>>> any2
type_url: "type.googleapis.com/Greeting"
value: "\n\003bob"
```
Where is the unpacked message?

Can anyone help put me on the right track?
