### ISSUE TITLE
throw java.lang.NoSuchMethodError when run mockito or powermockito

### ISSUE THREAD

**Issue by sunhang** [google/protobuf#4423]
I has written some unit code using powermockito in android app. The unit code call some object of my class defined by me, and there are protobuf's code inside my class.

Then the console report "java.lang.NoSuchMethodError empty Protobuf List()". After spend a lot of time to rearch it,  I still don't know how to resolve it. I have try to use mockito to replace powermockito ,but the isssue still be there. And if I remove the script code of powermockito and mockito from gradle, the unit code run completely.

**Comment by xfxyjwf** [comment]
The error message suggests you have different versions of proto generated code vs. proto runtime in your dependencies. Please makes sure the protoc you used to generate your proto code is the same as the proto Java runtime version you are depending on (you probably have multiple versions in your dependencies).
