### ISSUE TITLE
Proto files impact c++ library in python code

### ISSUE THREAD

**Issue by PeterUherek** [google/protobuf#4427]
I have python code which load my python proto files and also my own c++ so/dll library. Everything works fine until my so/dll library tries to cast string to int with boost::lexical::cast. Then my code failed with generic error:  **"conversion of data to type "i" failed"**

I thought something was wrong with my local variables. But when I set local variables (  std::setlocale(LC_ALL, "C") ) in my c++ library, it didn't help. I got same error. I tried to not use proto files in my python code and boost::lexical::cast works fine. Also it works fine when I first load my so library and after that proto files. I think proto files somehow impact my c++ library. 

It goes wrong after import: **from google.protobuf.pyext import _message**  in **api_implementation.py** file. If I load c++ library before this call everything goes fine. If I load library after this call I got error. 

I generated proto files with grpcio-tools package (Version: 1.10.) My c++ library was generated with gcc version: 6.4.0. This happens only in linux. It works fine on windows. 

Any advice what can be wrong? I will appreciate any help.

**Comment by acozzette** [comment]
@PeterUherek Sorry for the delay getting back to you, but do you have an example of the lexical cast that's failing?
