### ISSUE TITLE
No such file or directory     protoc object_detection/protos/*.proto --python_out=. 

### ISSUE THREAD

**Issue by 975150313** [google/protobuf#4428]
protoc object_detection/protos/*.proto --python_out=.  
in protoc3.5 have  problem：No such file or directory

**Comment by acozzette** [comment]
I would guess that `object_detection/protos/*.proto` doesn't match any files--are you sure there are any files there? What OS are you using? I believe there may also be some issues with shell globbing on Windows.

**Comment by 975150313** [comment]
I'm using the Windows operating system，When I use the protobuf 3.51+ Python3.63 + tensorflow1.6 +object_detection API build project has the  problem，the problem was not found for protobuf 3.4

**Comment by acozzette** [comment]
I think this is the same issue as in #3957, so let's move the discussion over to that issue.

**Comment by 975150313** [comment]
I know how to do it，now. Thanks  for your reply. @acozzette

**Comment by jeancarlos2020** [comment]
1.- SE INSTALA EL PROTOC EN MI CASO USE LA VERSION 3.5.1 WIN 
2.- CREE UN ARCHIVO DE TEXTO Y LO GUARDE CON .BAT 
 NOTA se debe ejecutar el bat desde  models-master\research dado que protoc depende de otros archivos  

"C:\Users\jroldan\Desktop\protoc-3.5.1-win32\bin\protoc" object_detection\protos\anchor_generator.proto --python_out=.
"C:\Users\jroldan\Desktop\protoc-3.5.1-win32\bin\protoc" object_detection\protos\argmax_matcher.proto --python_out=.
"C:\Users\jroldan\Desktop\protoc-3.5.1-win32\bin\protoc" object_detection\protos\bipartite_matcher.proto --python_out=.
"C:\Users\jroldan\Desktop\protoc-3.5.1-win32\bin\protoc" object_detection\protos\box_coder.proto --python_out=.
"C:\Users\jroldan\Desktop\protoc-3.5.1-win32\bin\protoc" object_detection\protos\box_predictor.proto --python_out=.
"C:\Users\jroldan\Desktop\protoc-3.5.1-win32\bin\protoc" object_detection\protos\aeval.proto --python_out=.
"C:\Users\jroldan\Desktop\protoc-3.5.1-win32\bin\protoc" object_detection\protos\faster_rcnn.proto --python_out=.
"C:\Users\jroldan\Desktop\protoc-3.5.1-win32\bin\protoc" object_detection\protos\faster_rcnn_box_coder.proto --python_out=.
"C:\Users\jroldan\Desktop\protoc-3.5.1-win32\bin\protoc" object_detection\protos\graph_rewriter.proto --python_out=.
"C:\Users\jroldan\Desktop\protoc-3.5.1-win32\bin\protoc" object_detection\protos\grid_anchor_generator.proto --python_out=.
"C:\Users\jroldan\Desktop\protoc-3.5.1-win32\bin\protoc" object_detection\protos\hyperparams.proto --python_out=.
"C:\Users\jroldan\Desktop\protoc-3.5.1-win32\bin\protoc" object_detection\protos\image_resizer.proto --python_out=.
"C:\Users\jroldan\Desktop\protoc-3.5.1-win32\bin\protoc" object_detection\protos\input_reader.proto --python_out=.
"C:\Users\jroldan\Desktop\protoc-3.5.1-win32\bin\protoc" object_detection\protos\keypoint_box_coder.proto --python_out=.
"C:\Users\jroldan\Desktop\protoc-3.5.1-win32\bin\protoc" object_detection\protos\losses.proto --python_out=.
"C:\Users\jroldan\Desktop\protoc-3.5.1-win32\bin\protoc" object_detection\protos\matcher.proto --python_out=.
"C:\Users\jroldan\Desktop\protoc-3.5.1-win32\bin\protoc" object_detection\protos\mean_stddev_box_coder.proto --python_out=.
"C:\Users\jroldan\Desktop\protoc-3.5.1-win32\bin\protoc" object_detection\protos\model.proto --python_out=.
"C:\Users\jroldan\Desktop\protoc-3.5.1-win32\bin\protoc" object_detection\protos\multiscale_anchor_generator.proto --python_out=.
"C:\Users\jroldan\Desktop\protoc-3.5.1-win32\bin\protoc" object_detection\protos\optimizer.proto --python_out=.
"C:\Users\jroldan\Desktop\protoc-3.5.1-win32\bin\protoc" object_detection\protos\pipeline.proto --python_out=.
"C:\Users\jroldan\Desktop\protoc-3.5.1-win32\bin\protoc" object_detection\protos\post_processing.proto --python_out=.
"C:\Users\jroldan\Desktop\protoc-3.5.1-win32\bin\protoc" object_detection\protos\preprocessor.proto --python_out=.
"C:\Users\jroldan\Desktop\protoc-3.5.1-win32\bin\protoc" object_detection\protos\region_similarity_calculator.proto --python_out=.
"C:\Users\jroldan\Desktop\protoc-3.5.1-win32\bin\protoc" object_detection\protos\square_box_coder.proto --python_out=.
"C:\Users\jroldan\Desktop\protoc-3.5.1-win32\bin\protoc" object_detection\protos\ssd.proto --python_out=.
"C:\Users\jroldan\Desktop\protoc-3.5.1-win32\bin\protoc" object_detection\protos\ssd_anchor_generator.proto --python_out=.
"C:\Users\jroldan\Desktop\protoc-3.5.1-win32\bin\protoc" object_detection\protos\string_int_label_map.proto --python_out=.
"C:\Users\jroldan\Desktop\protoc-3.5.1-win32\bin\protoc" object_detection\protos\train.proto --python_out=.
pause

**Comment by flyingsquirrel10** [comment]
How did you fix this issue?
