### ISSUE TITLE
Why do we need protobuf-all.zip library, while i can use the compiler(protoc)?

### ISSUE THREAD

**Issue by Zedonboy** [google/protobuf#4430]
Hey i have gone through google developer guide, all i see is
1. write a .proto
2. compile it with protoc
3. use the generated file in your source.
4. no way to generate service/server/ .grpc file
5. All these are already done in the helloWorld examples
6. All what the guide taught me is how to compile helloWorld example

So why do i need protobuf-all.zip,
and most times tutorials emphasize on an already made helloworld example, with their already made makefiles, and already built plugin(thats not properly documented how you came about getting the plugin)

**Comment by xfxyjwf** [comment]
protobuf-all.zip is for those who need to compile everything (including multiple languages) from source. If you don't need to build protobuf library from source, you probably don't need it.

**Comment by Zedonboy** [comment]
how do i go about with the plugins
am using windows

**Comment by xfxyjwf** [comment]
@Zedonboy Please ask plugin providers. For example, if you want to use grpc with protobuf, check out https://grpc.io/
