### ISSUE TITLE
Export cc_library `protobuf` as a .bzl function

### ISSUE THREAD

**Issue by lannadorai** [google/protobuf#4435]
Hello Folks,
As mentioned here https://github.com/google/protobuf/issues/2365, GzipOutputStream and GzipInputStream needs zlib to build.

This could be achieved by adding the C++ compilation flag -DHAVE_ZLIB to `copts` and a dependency on the external zlib library in the cc_library rule `protobuf`.

Until protobuf natively supports zlib, is it possible to export the cc_library rule `protobuf` as a .bzl function with options to append custom C++ compilation flags to `copts` and dependencies to `deps`.

**Comment by xfxyjwf** [comment]
Could you help resolve https://github.com/google/protobuf/issues/2365 instead?

**Comment by xfxyjwf** [comment]
Closing as I don't think it's a good idea to expose protobuf library as a .bzl function. We should aim to provide one single cc_library target.
