### ISSUE TITLE
Code generation issue in C#

### ISSUE THREAD

**Issue by svetlioMihaylov** [google/protobuf#4436]
Hi, 
I am using protoc-3.5.1 оn a windows machine with а gRPC.Tools 1.10.0 version to compile my proto files which have gRPC services defined in them.  The issue is that when we have a method 'request' 
 declared in the service with name the generated C# code does not compile.
Example:

service SomeService {
      rpc request (SomeRequest) returns (SomeResponse){}
}

The generated code looks like this:

public virtual global::SomeResponse request(global SomeRequest request, grpc::Methadata headers = null, ...){
return request(request, new grpc::CallOptions(headers, ..));
}

The compilation error is in the line starting with the return statement. The error is "Method name expected". From what I understand the protoc does not make difference between the argument and the method it needs to invoke. This is working correctly when I am compiling java code.

Regards,
Svetlozar.

**Comment by xfxyjwf** [comment]
Thsi seems to be a name conflict between "request" the method name and "request" the parameter name. I think you can just change your method name to something else.

**Comment by svetlioMihaylov** [comment]
Yes we are doing this as a workaround. But is it possible that this is fixed in the C# code generator, since as I said it is working as expected in Java?

**Comment by xfxyjwf** [comment]
@svetlioMihaylov It's possible but we prefer not to do it because giving the method a different name is a better solution all around.
