### ISSUE TITLE
(c++) Does json_util.h MessageToJsonString and JsonStringToMessage work with proto 2 messages?

### ISSUE THREAD

**Issue by sbailey476** [google/protobuf#4437]
Can messages which have been defined in a proto 2 file but compiled with the latest proto 3 compiler to c++ code be encoded and decoded to/from JSON using the json utils?

**Comment by xfxyjwf** [comment]
It can, as long as you don't rely on proto2 only features (like extensions, groups). If you have, e.g., extensions in your proto2 message, json util will discard them away when converting it to json.
