### ISSUE TITLE
set a protocol buffer field to None in python

### ISSUE THREAD

**Issue by lukekingbru** [google/protobuf#4444]
in proto 3

I have this object 

message act {
    bytes                                      act_cmd          = 1;
}

In python code:
hope to do this 

act_inst = act()
act_inst.act_cmd = None <<<<<<<<<<<<<<<<<<< throw error

/google/protobuf/internal/type_checkers.py", line 109, in CheckValue\n    raise TypeError(message)\nTypeError: None has type <type \'NoneType\'>, but expected one of: ((<type \'str\'>,),)

Is anyway to get rid of this error? Or there is some data type I can use in protocol buffer, which can accept string or None value ?

in python give None value to a string variable is allowed.

>>> s = str()
>>> type(s)
<type 'str'>
>>> 
>>> s = None
>>> type(s)
<type 'NoneType'>

Thanks

**Comment by anandolee** [comment]
The Struct and ListValue of Well Know Types can accept None:
https://github.com/google/protobuf/blob/master/src/google/protobuf/struct.proto

But Struct is a map and ListValue is using repeated field, I am not sure if it what you want. Sample usage:
https://github.com/google/protobuf/blob/master/python/google/protobuf/internal/well_known_types_test.py

Why do you nee None for bytes field?

**Comment by lukekingbru** [comment]
Hi,

my work is encode some json format into protocol buffer.
Let's say, we have a json request like this:
{
     "foo":"bar"
}

but sometimes the value of field "fool" is null like
{
   "foo": null
}
Can protocol buffer handle this ?

Thanks,

**Comment by anandolee** [comment]
Are you using protobuf/python/google/protobuf/json_format.py?

According to our JSON Mapping document, null is accepted:
https://developers.google.com/protocol-buffers/docs/proto3#json

**Comment by anandolee** [comment]
You can find examples for ListValue() which has null value in json_format_test.py
https://github.com/google/protobuf/blob/master/python/google/protobuf/internal/json_format_test.py#L551

**Comment by anandolee** [comment]
Closing it for clean up, feel free to reopen it still an issue for you

**Comment by asimonov** [comment]
thank you for the example!

**Comment by wangjunbao2018** [comment]
Hi, there
I also met this problem.  How did you solve it? 

Here is my code:

```
message Transaction { 
  repeated TxIn vin = 2; 
  repeated TxOut vout = 3; 
} 

message TxIn { 
  OutPoint prev_out_point = 1; 
  bytes script_sig = 2; 
  uint32 sequence = 3; 
}
```

```
for i in range(len(tx.vin)):
  if i != index:
    tx.vin[index].script_sig = None
  else:
    tx.vin[index].script_sig = script_pub_key
```

And I'm developing a SDK, so I can't change the proto file.  Is there anything I can do to solve the problem?
