### ISSUE TITLE
How to read a size-delimited Google protocol buffer messages?

### ISSUE THREAD

**Issue by RuojunLi** [google/protobuf#4446]
Hi, I have a size-delimited Google protocol buffer messages(.pbs). Also I have the .proto file of the messages. How can make the pbs file readable?  I have read the tutorial on the [https://developers.google.com/protocol-buffers/docs/proto](url)
But it doesn't mention any details about the .pbs file. 
Thank you for anyone's potential help.

**Comment by RuojunLi** [comment]
I am not a programmer and only know few about the protocol. I just want to use the data in this .pbs file and do my future research. If there are any simple and quick method to read such file, plz let me know.

**Comment by xfxyjwf** [comment]
Maybe ask whoever created that size-delimited .pbs file? There are many ways to create size-delimited file formats and the creator of the file should know better.

**Comment by RuojunLi** [comment]
@xfxyjwf Thank you for the prompt reply. The pbs file is generated by an Android App. Now I can hardly contact the programmer who wrote it. But he has sent me his java project. Will that's be helpful to figure out how to decode this .pbs file?

**Comment by xfxyjwf** [comment]
Then I guess you need to find someone who can understand that Java project to help you. That's not the kind of support we offer here though.
