### ISSUE TITLE
Please Release 3.5.2 on GitHub

### ISSUE THREAD

**Issue by pcorpet** [google/protobuf#4454]
Apparently the v3.5.2 is out: there's a tag and also a [PyPi release](https://pypi.python.org/pypi/protobuf/3.5.2) but no GitHub release as such.

Can you publish such a release please?

I'm asking because our systems rely on downloading the compiler from GitHub and we pick the compiler version based on the PyPi version installed.

**Comment by TeBoring** [comment]
3.5.2 is only for updating python runtime on pypi. Could you make your system more general to accept custom compiler version.

**Comment by pcorpet** [comment]
I see. Ideally we'd love to have a reliable and easily automated way (we use Docker) of installing the latest version of protoc. It seems that for now we need to resolve where https://github.com/google/protobuf/releases/latest is redirecting, then deduce the version number, then download the protoc binary for us.

If you know of a simpler solution, please share it, otherwise you can close this issue.

**Comment by TeBoring** [comment]
You may want to direct you protoc version to: https://mvnrepository.com/artifact/com.google.protobuf/protoc
