### ISSUE TITLE
[PHP] Missing GPBUtil Methods in Extension

### ISSUE THREAD

**Issue by bshaffer** [google/protobuf#4457]
Methods `GPBUtil::hasSpecialJsonMapping` and `GPBUtil::hasJsonValue` don't exist in the Protobf C Extension for PHP.

I am using PHP 5.6 on Mac OSX and I've downloaded the latest protobuf extension using `pecl install protobuf`. 

```
Fatal error: Call to undefined method Google\Protobuf\Internal\GPBUtil::hasSpecialJsonMapping() in vendor/google/gax/src/ApiCore/RequestBuilder.php on line 279
```

**Comment by TeBoring** [comment]
You are not supposed to use that by yourself.
