### ISSUE TITLE
Allow skipping path segments during output when mapping package to PHP namespaces

### ISSUE THREAD

**Issue by atrauzzi** [google/protobuf#4459]
The best example to explain this is with the default Laravel framework project.  The skeleton tells composer to map the `app` dir to the root namespace level `App`.  If I have a `.proto` file that defines the package `app.myDomain`, and I'm `.gitignore`ing the directories created by `protoc` I'll end up with the following directory structure:

```
    app/
        App/
            MyDomain/
```

Whereas I'd rather see:

```
    app/
        MyDomain/
```

Note however that within the file itself, I would still want the namespace to be `App\MyDomain`.  Tricky stuff 😄 

cc. https://github.com/google/protobuf/issues/3970

**Comment by TeBoring** [comment]
Does this still work with autoload? AFAIK, autoload require namespace to be consistent with file name. You need to change your own composer configuration to do that.

**Comment by atrauzzi** [comment]
I'm not really asking to change the filename.  Just how much of the path protobuf chooses to take responsibility for creating.

So, instead of protobuf creating the file `App/MyDomain/MyType.php`, I'd like to to make `MyDomain/MyType.php` and then I'll point it to the directory `app` as the root for output.

In the case of my example `MyType.php` is unchanged, and the namespace in `MyType.php` still reads as 

```php
<?php

namespace App\MyDomain\MyType;

// ...
```

**Comment by TeBoring** [comment]
You can call protoc in ```app``` folder instead of the parent folder of ```app```.
Besides, you need to add ```php_namespace = "App\MyDomain"``` file option to your proto file.

**Comment by atrauzzi** [comment]
Making me call the tool from a different directory seems like a bit of an inconvenience.  I'm not sure you understand what I'm asking for here.

**Comment by archy-bold** [comment]
The use case @atrauzzi is definitely a valid one. At the minute I have to move the files manually.
