### ISSUE TITLE
protoc-gen-lua: program not found or is not executable

### ISSUE THREAD

**Issue by Aaron-Chan** [google/protobuf#4471]
I run  the command "protoc --lua_out=./ person.proto " in Mac Os Ternimal.
It was failed.Who can Help me figure out the problem
protoc-gen-lua: program not found or is not executable
--lua_out: protoc-gen-lua: Plugin failed with status code 1.

**Comment by xfxyjwf** [comment]
--lua_out is not supported by this repo. Please consult the developer who told you to run "protoc --lua_out" instead.
