### ISSUE TITLE
Protobuf-tool generates code that breaks serialization symethry with proto2

### ISSUE THREAD

**Issue by mstavrev** [google/protobuf#4472]
To my understanding, one of the major goals between proto2 and proto3 is to keep the on-the-wire message content compatibility. This is largely achieved, however there is a problem related to interoperability between systems that are using implementation derived from proto2 definition communicating with such using proto3.

It is related to how the Protobuf.Tools (at least for c#) generate the serialization code for scalar fields that are currently holding the default value for their respective scalar type.
For example, imagine a .proto2 definition for a message like:

message Property {
	required	uint32		id	 = 1;
	optional	string		name= 2;
	required	float			val 	 = 3;
}

and its equivalent proto3 definition:

message Property {
		uint32		id	 = 1;
		string		name = 2;
		float			val	  = 3;
}

When a proto3 implementation is generating a message of type "Property" that has a value of 0 (float) for the field "val", the on-the-wire message is generated such that it is lacking the field completely. This breaks proto2 implementations, which expect to always find a field carrying the value for the "val" field.

To overcome such problems, I need to manually edit the Protobuf.Tool generated implementation and make it serialize the field, even when it currently contains its default value of 0.

I would suggest to add a field option for the .proto3 file - for example:

message Property {
		uint32		id		= 1;
		string		name	= 2;
		float			val		= 3  **[always_serialize=true];**
}

The always_serialize field option would make the Protobuf.Tool generate the serialization, size computation, hashing, comparison and cloning implementation ignoring if the value is the default one - always generating the field on protocol level.

**Comment by acozzette** [comment]
@mstavrev If you really need to maintain wire compatibility and need to rely on field presence as you upgrade from proto2 to proto3, I would recommend putting the scalar field inside a `oneof` as a workaround. In issue #1606 we thought about adding a new option for this but decided against it.

**Comment by xfxyjwf** [comment]
Note that proto3 is wire-compatible with proto2 in that a proto2 message can be parsed in proto3 (and vice versa). There are semantic differences between them though. Right now we have no plan to change proto3 (or add proto3 features) to mimic proto2 behaviors.
