### ISSUE TITLE
[docs] Language specification for Syntax is too broad

### ISSUE THREAD

**Issue by dsnet** [google/protobuf#4479]
The documented BNF for syntax is as follows:
```
syntax = "syntax" "=" quote "proto2" quote ";"
quote = "'" | '"'
```

As written, this implies that the following is valid: `syntax = 'proto2"`, where the single and double quote are mismatching.

**Comment by anandolee** [comment]
The spec is not strong enough for automatic tools, and does not cover everything. The goal is only a guide for users.
