### ISSUE TITLE
Migrate C# generator from writer to io::Printer

### ISSUE THREAD

**Issue by anandolee** [google/protobuf#448]
Current C# generator is using writer. I will change to use io::Printer like other languages, it will have better readability.

@jskeet 
Have you begin the "simplify generate members" task? Is the conflict accept for you?
I guess you are not working on mutable for the generator part?

Protobuf like to have the proto3 support for C# ASAP. It will be good if we could make the things faster that blocks proto3.

**Comment by jskeet** [comment]
Assuming it's simple to apply the changes to use io::Printer, I'm sure it won't be a problem - the work I'm prototyping is for more than just "simplify generate members", it's for the whole codegen and runtime, but it's worth you doing the io::Printer stuff first, while we work out exactly what the plan is for the rest.
