### ISSUE TITLE
Is Python 3.5.x supported?

### ISSUE THREAD

**Issue by PhilippSelenium** [google/protobuf#4483]
```
from google.protobuf import descriptor as D
```
throws
```
AttributeError: '_NamespacePath' object has no attribute 'sort'
```

Python 3.5.2
py3-protobuffers==3.0.0a4

**Comment by PhilippSelenium** [comment]
I created a new virtual environment in the meantime.
Now i get the error when installing via pip
```
pip install py3-protobuffers
```
```
AttributeError: '_NamespacePath' object has no attribute 'sort'
```

Is this maybe an error with setuptools or with my Ubuntu 16.04 distro?
setuptools (39.0.1)
  INSTALLED: 39.0.1 (latest)

**Comment by anandolee** [comment]
Python 3.5.x is supported and we have test to cover python 3.5:

https://github.com/google/protobuf/blob/3c5442a95d9608519a76a5db27d21d71dd1137a1/tests.sh#L285

**Comment by alexforever86** [comment]
After running `build`, `pip` is giving the same error.
