### ISSUE TITLE
Conflicting redefinition of GPBType

### ISSUE THREAD

**Issue by jcanizales** [google/protobuf#449]
The class generated for the well-known-type type.proto, [GPBType](https://github.com/google/protobuf/blob/master/objectivec%2Fgoogle%2Fprotobuf%2FType.pbobjc.h#L127) can't be compiled because its name conflicts with the [GPBType enum](https://github.com/google/protobuf/blob/master/objectivec%2FGPBTypes.h#L89).

**Comment by jcanizales** [comment]
@thomasvl @TeBoring @dmaclach

**Comment by jcanizales** [comment]
Similarly, [GPBField](https://github.com/google/protobuf/blob/master/objectivec%2Fgoogle%2Fprotobuf%2FType.pbobjc.h#L165), generated in the same file, conflicts with the [GPBField of the runtime](https://github.com/google/protobuf/blob/master/objectivec%2FGPBField.h#L38).

Maybe well-known-types shouldn't use the same prefix as the library's runtime?

**Comment by jcanizales** [comment]
@murgatroid99 FYI

**Comment by jcanizales** [comment]
Same with `GPBValue` (defined in `struct.proto`) too.

**Comment by thomasvl** [comment]
C++ needed to know about Any to build out support for it, so if ObjC ever does something like that they should probably get the same prefix.

I'll rename the internal types.

**Comment by jcanizales** [comment]
Fixed by #480.
