### ISSUE TITLE
Build label wrong for tag 3.5.2

### ISSUE THREAD

**Issue by oxoocoffee** [google/protobuf#4491]
I just build and installed from v3.5.2 tag and after installation I see version 3.5.1
Not sure if this is real issue or lib and exec versions might be different? Sounds wrong....

((v3.5.2)) $ protoc --version
libprotoc 3.5.1

**Comment by xfxyjwf** [comment]
I believe protoc hasn't changed from 3.5.1 to 3.5.2 and the version mismatch shouldn't be a problem (i.e., it's safe to use protoc 3.5.1 with a language runtime tagged 3.5.2).

**Comment by xfxyjwf** [comment]
@TeBoring Bo, it seems you forgot to update C++ version number in this commit https://github.com/google/protobuf/commit/b5fbb742af122b565925987e65c08957739976a7

**Comment by xfxyjwf** [comment]
I created an issue to add a test to check the version number for future releases. Closing this one as there isn't anything we can do to the existing tag. Feel free to ask questions if you still have confusion about the compatibility between protoc and the proto runtime you are using.
