### ISSUE TITLE
v2.5.0 autogen.sh中的googletest连接失效

### ISSUE THREAD

**Issue by uilzzw** [google/protobuf#4492]
v2.5.0版本中autogen.sh的googletest连接已经失效了.需要脚本中下载googletest的连接需要改为:
curl -O release-1.5.0.tar.gz https://codeload.github.com/google/googletest/tar.gz/release-1.5.0 | tar zx
mv googletest-release-1.5.0 gtest

**Comment by xfxyjwf** [comment]
This is a known issue but there is nothing we can do about already released versions.
