### ISSUE TITLE
protobuf for Windows Phone ARM in C++

### ISSUE THREAD

**Issue by langyanduan** [google/protobuf#450]
I use protobuf in winrt app for Windows and Windows phone.

I create project as Visual C++ --- Windows Phone Application ---- Static Library (Windows Phone)

I got this message when build for ARM: "Host architecture was not detected as supported by protobuf"
The device is Nokia Lumia 1020. My OS is Windows 8.1, Visual Studio 2013

When is build for x86(run on emulator) everything is fine.

Thank you!

**Comment by johanlindfors** [comment]
Any news on this issue? I'm having the same problem!

**Comment by xfxyjwf** [comment]
Hi, we (protobuf-team) don't have the resource to test the code on Windows Phones, and would appreciate if any one can help provide a patch to make the code compilable on that platform.

For the "Host architecture was not supported" problem, it can be fixed by defining the appropriate macros and probably also some atomic functions. See:
https://github.com/google/protobuf/blob/master/src/google/protobuf/stubs/platform_macros.h#L46

A possible fix for win phone arm:
```cpp
#elif defined(_M_ARM)
#define GOOGLE_PROTOBUF_ARCH_ARM 1
#define GOOGLE_PROTOBUF_ARCH_32_BIT 1
```

**Comment by zabulus** [comment]
Do you accept PRs for WP?

**Comment by xfxyjwf** [comment]
Yes, we accept PRs for WP.

**Comment by m-deckel** [comment]
@xfxyjwf I develop for Windows 10 which runs on x86 and ARM. Your suggestion to add _M_ARM helped a bit but I eventually get stuck with GOOGLE_PROTOBUF_ATOMICOPS_ERROR. Do you know if there will be a support for Microsoft ARM for atomicops? If not, I will have a look if I can do something else here.

**Comment by haberman** [comment]
We are happy to accept pull requests to make protobuf work on more platforms. I'm closing this for now since the team doesn't have the resources to add this support ourselves.

**Comment by xueyangx** [comment]
@xfxyjwf @haberman Do you know if there will be a  support for Windows 10 + ARM64 ? or there is a Microsoft ARM64 version atomicops_internals_xxx header file? @m-deckel  wondering if you have make a Microsoft ARM atomicops?

**Comment by xfxyjwf** [comment]
There will be support for windows 10 + ARM64 if someone can help contribute one ;)

**Comment by xueyangx** [comment]
@xfxyjwf  wondering if windows 10 + ARM64 is supported ?
