### ISSUE TITLE
JsonParser will not ignore unknown types - C#

### ISSUE THREAD

**Issue by charlie430** [google/protobuf#4506]
This feature request is similar to https://github.com/google/protobuf/issues/2838

Except instead of ignoring fields, we should be able to ignore an unknown type when packing or unpacking an Any message.

I created https://github.com/google/protobuf/pull/4505 to solve this issue.

**Comment by xfxyjwf** [comment]
As I mentioned in the https://github.com/google/protobuf/pull/4505, it's intentional that we don't want to accept payload with unknown Any types. Also note that it's actually both ways: if an Any type cannot be resolved at serialization, printing to JSON will also fail.
