### ISSUE TITLE
where is the protobuf 2.4

### ISSUE THREAD

**Issue by bichao1986** [google/protobuf#4507]
Because it needs to connect with Baidu, so it needs to use the same version as Baidu. Baidu uses protobuf 2.4 and how to get the 2.4 version. Thank you.

**Comment by xfxyjwf** [comment]
I don't know what you mean by 'connect tiwh Baidu' but you generally don't need the same version to connect to a service that serves protobufs but all protobuf versions are wire compatible.

For the specific question you are asking: no, we no longer have any public 2.4.x. release packages.
