### ISSUE TITLE
svn checkout https://github.com/google/protobuf.git failed

### ISSUE THREAD

**Issue by tnie** [google/protobuf#4512]
Error Message

![err](https://user-images.githubusercontent.com/5952845/38762924-7d2b6860-3fc4-11e8-80db-049d6003a855.png)

About TortoiseSVN

![about](https://user-images.githubusercontent.com/5952845/38762926-81d1ff64-3fc4-11e8-85ff-b91ee3cb220a.png)

**Comment by xfxyjwf** [comment]
I don't think this has anything to do with protobuf. If svn doesn't work with github, please file a bug against github instead.
