### ISSUE TITLE
Unit test for string_as_array?

### ISSUE THREAD

**Issue by piquan** [google/protobuf#4516]
I came across a comment for a utility function, `string_as_array(string*)` (taken from `google3/util/gtl/stl_util.h`) that has an implementation note that only references the unit test:
https://github.com/google/protobuf/blob/da3ce6717156c8b4f8890207895069ce6b102f65/src/google/protobuf/stubs/stl_util.h#L84

I can't find anywhere that the unit test was open-sourced. Could we copy the relevant info into the open-sourced `stl_util.h` (possibly also copying it into the corresponding comment in google3)? Or, failing that, could we copy it to this issue thread?

Some updates to the matter have come along since the function's comment was written:
- `std::string::data()` returns a non-`const` pointer starting in C++17; see http://www.open-std.org/JTC1/SC22/WG21/docs/lwg-defects.html#2391.
- WG21 issue 530 referenced in the comment has moved from "active issue" to "defect report", and so the URL in the comment is no longer valid. The new URL is http://www.open-std.org/JTC1/SC22/WG21/docs/lwg-defects.html#530
- While 2391 is relevant, 530 still should remain referenced. Matt notes vendor conversations and current implementation practice in 530, while 2391 focuses more on the user need for a non-`const` return value.

**Comment by xfxyjwf** [comment]
Found the test here:
https://github.com/flutter/base/blob/master/stl_util_unittest.cc#L256

Apparently we opensource the same piece of code again and again in different projects...

**Comment by piquan** [comment]
That's terrific, thanks!  I'll leave this issue open so you can decide if you want to update the comment in stl_util.h, but that gives me the information I needed: `string_as_array` was written that way because the author was worried about COW strings prior to C++11.

**Comment by xfxyjwf** [comment]
I'll leave it as-is as I prefer keeping the file as close as possible to its original.
