### ISSUE TITLE
Message.toObject() does not respect chosen field name

### ISSUE THREAD

**Issue by majelbstoat** [google/protobuf#4518]
(Relocated from https://github.com/grpc/grpc-node/issues/279)

When generating JS code, given a definition with a repeated field:

```protobuf
message History {
  repeated string paths = 1;
}
```

and the following code:

```js
const history = new History()
history.setPathsList(['/', '/var'])
console.log(history.toObject())
```

I expect the output to be:

```js
{ paths: ["/", "/var"] }
```

Instead, it is:

```js
{ pathsList: ["/", "/var"] }
```

The `(s|g)et*List()` function naming convention is clear and helpful, but failure to honour the specified name when turning it back into JSON creates a lot of work mapping the fields back to what they are intended to be. 

Plus, if `setFromJson` or similar is ever added (https://github.com/google/protobuf/issues/4006), that would make roundtripping data through protobufs much more straightforward.

**Comment by acozzette** [comment]
@majelbstoat We don't yet support the JSON format in JS. The `toObject()` method is a bit confusing because it produces output that looks similar to the official JSON format but it is not actually the same.

**Comment by majelbstoat** [comment]
That makes sense. By 'yet', does that mean it is planned for the future? (Without setting expectations of when it might happen.)

**Comment by acozzette** [comment]
@majelbstoat We do want to eventually support proto3 JSON in JS, but at the moment I think we all have our hands full with other things and so we haven't been able to prioritize it yet.

**Comment by majelbstoat** [comment]
Curious why this was closed if it's something that's acknowledged as a current deficiency, and future support is planned?

**Comment by acozzette** [comment]
Sorry about the confusion--I agree that proto3 JSON support has not been resolved yet, but I wanted to tidy things up by closing this issue, since most of the discussion around JSON support has already been happening in #1591.
