### ISSUE TITLE
Is there a way to check if all the fields in one Message exist in another Message in Java?

### ISSUE THREAD

**Issue by kaybinwang** [google/protobuf#4519]
I have two protobuf messages of the same class. I want to be able to check if all the fields in one are contained in the other.

Example
```
message Person {
  string name = 1;
  int32 age = 2;
}

// java
Person person1 = Person.newBuilder()
    .setName("Jon")
    .setAge(23)
    .build()
Person person2 = Person.newBuilder()
    .setAge(23)
    .build()
containsFields(person1, person2); // returns true
```

**Comment by acozzette** [comment]
@kaybinwang I don't know of any pre-existing code that does exactly this, but you can probably implement it using protobuf reflection without too much trouble. See for example the [getAllFields](https://developers.google.com/protocol-buffers/docs/reference/java/com/google/protobuf/MessageOrBuilder#getAllFields--) method that will return all the fields that are set on a given message.
