### ISSUE TITLE
Converting Python protobuf object to dict base64 encoding not optional

### ISSUE THREAD

**Issue by samredway** [google/protobuf#4525]
When I convert a protobuf object to dictionary using the protobuf.json_format module it encodes the byte strings as a base64. Whilst I see there is a rational for this - in my own particularly use case I find this difficult. In my case the bytes object is a representation of a string. Of course I can decode from base64 and then encode to utf-8, but how do I know that this particular field is a byte object that has been encoded to base64?

The obvious thing would be to parse the protobuf definition in the .proto file and find all byte objects and use that as a guide to which fields need to be thus decoded. However this adds a whole level of unnecessary complexity to my program.

What I would like is an optional argument for the `MessageToDict` function that allows me to set `base64encoding=False`, which would save me a whole load of work.

This would be very easy to implement and I could do the PR myself but would like to ask:

  - is there a reason why this should not be done?
  - Am I in fact misusing the method?

**Comment by xfxyjwf** [comment]
We do not accept options that break inter-op between different implementations.

I would suggest you change the field type to string instead if it's used for string only. Also, you shouldn't process the JSON output without the proto type info (that just won't work).

**Comment by pavan530** [comment]
Hi @samredway , I am also got into similar issue. In our case, we have 100's of columns in bytes type. Decoding and encoding to utf-8 is going to be costly operation for us. Did you find some work-around to deal with this? It would be helpful if you can share/extend your ideas here on how did you solve this.

**Comment by samredway** [comment]
This was a while ago. But from memory I think that for this I ultimately did some redesign of the service to make it work as intended (as stated above) rather than find a workaround. Sorry if not super helpful.
