### ISSUE TITLE
Version 3.5.2 CocoaPod?

### ISSUE THREAD

**Issue by ddralves** [google/protobuf#4529]
When is the Version 3.5.2 cocoa pod going to be pushed onto the trunk?

**Comment by TeBoring** [comment]
There is no change to objc for 3.5.2. You can keep using 3.5.1

**Comment by ddralves** [comment]
Hi @TeBoring 

Please see here: https://cocoapods.org/pods/Protobuf

As you can see, as per my original issue comment, Google has not updated the CocoaPod trunk to have 3.5.1 so one cannot consume this version.  When will this update happen?
