### ISSUE TITLE
Missing official package for \GPBMetadata\Google\Api (PHP)

### ISSUE THREAD

**Issue by idcmp** [google/protobuf#4545]
Generated PHP references classes in \GPBMetadata\Google\Api namespace. As best I can tell there's no official composer package which provides classes in the namespace.   Example:

```
<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: foo.proto

namespace GPBMetadata;

class Foo
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Api\Annotations::initOnce();
        \GPBMetadata\Google\Protobuf\GPBEmpty::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(....
```

I _think_ there should be a composer package somewhere that offers this namespace but I can't seem to find one?

**Comment by TeBoring** [comment]
I think we provide it at https://github.com/google/protobuf/tree/master/php/src/GPBMetadata/Google/Protobuf

**Comment by idcmp** [comment]
Hey @TeBoring, maybe I've misunderstood, but wouldn't ` \GPBMetadata\Google\Api\Annotations::initOnce();` be in a in `/Google/Api` directory, not `/Google/Protobuf`?

**Comment by TeBoring** [comment]
@michaelbausor, do you know which library should expose Google\Api\Annotations?

**Comment by michaelbausor** [comment]
They are available from the `google/gax` package from the gax-php repo, e.g. https://github.com/googleapis/gax-php/blob/master/metadata/Api/Annotations.php

However, I think that we should break them out into their own package - I have filed https://github.com/googleapis/gax-php/issues/172 to track this.

**Comment by flc1125** [comment]
As a supplement, he has moved here: https://github.com/googleapis/common-protos-php
