### ISSUE TITLE
The generated import code in Python have error in xxx_pb2_grpc.py

### ISSUE THREAD

**Issue by shengyang998** [google/protobuf#4546]
The protoc generate `xxx_pb2_grpc.py` code like this for example: 
```python
# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc
import shadowfax_pb2 as shadowfax__pb2
```

However, in some case, `line 3` will fail with an Error: 
```shell 
ModuleNotFoundError: No module named 'shadowfax_pb2'
```

How about changing this line to: 
```python
from . import shadowfax_pb2 as shadowfax__pb2
```

**Comment by anandolee** [comment]
@nathanielmanistaatgoogle, can you help to take a look?

**Comment by nathanielmanistaatgoogle** [comment]
I suspect that this is the same problem that we're tracking in [gRPC Python issue 11041](https://github.com/grpc/grpc/issues/11041) and [gRPC Python issue 9450](https://github.com/grpc/grpc/issues/9450).

**Comment by anandolee** [comment]
I am closing this issue as duplicated with some issues under gRPC

**Comment by tvalentyn** [comment]
See https://github.com/protocolbuffers/protobuf/issues/1491 for a discussion of this issue.
