### ISSUE TITLE
Documentation for binary protocol doesn't have a description for how to read/write oneof fields

### ISSUE THREAD

**Issue by wvxvw** [google/protobuf#4548]
From looking into source code I could, sort of, see that it must generate an enumerator for it, and then encode the actual choice made by using this enumerator... but the exact layout of this field is still unclear to me.  Is the value of the enumerator concatenated with the chosen value and both encoded as a lenght-delimited field, or are enumerator's value and the value of the field encoded separately (so that each has its own key)?

**Comment by xfxyjwf** [comment]
oneof fields are encoded in exactly the same way as optional fields for backwards compatibility.

**Comment by wvxvw** [comment]
OK, this helps, thank you.  While not exactly on the subject, is there any way to represent `oneof` field in text format? I.e. suppose:

`test.proto`
``` proto
message Test {
    oneof x {
        int32 y = 1;
        string z = 2;
    }
}
```

I've tried:

    $ echo "x: { y: 42 }" | protoc --encode ...

and

     $ echo "y: 42" | protoc --encode ...

as well as few other things I could think about, but couldn't get it to work.  It would in general help to have text format documented somewhere too.
