### ISSUE TITLE
undefined field

### ISSUE THREAD

**Issue by Soypete** [google/protobuf#4582]
I just generated some new protobuf .pb.go files. WhenI go to build I get this error "undefined: proto.InternalMessageInfo".

I know this is because of the new branch that was merged in today https://groups.google.com/forum/#!topic/protobuf/N-elvFu4dFM. I just want my code to compile.
 Any suggestions?

**Comment by jgoodall** [comment]
We are having the same issue.

**Comment by xfxyjwf** [comment]
Can you report this to https://github.com/golang/protobuf ? The protobuf go generator and runtime is hosted in a different repository.

**Comment by ramnique** [comment]
I had the same issue today. There are two solutions:

1. **Either use an older version of the plugin** i.e. manually download and install `protoc-gen-go` release v1.1.0 (https://github.com/golang/protobuf/releases/tag/v1.0.0) to generate proto code in the old style.
1. **Use the right dependency version**: You should have `github.com/golang/protobuf` somewhere in your project dependencies, you need to bump its version to `v1.1.0` and run `dep ensure` (or appropriate glide command). Then, compilation succeeds with the new types above.

**Comment by ramnique** [comment]
Here is some more information on this issue; with a heads-up dating back to Jan: https://groups.google.com/forum/#!topic/golang-nuts/F5xFHTfwRnY

**Comment by thanhnl** [comment]
It's fixed after update vendor.
