### ISSUE TITLE
Compile error when extending FieldOptions on macOS

### ISSUE THREAD

**Issue by yijiem** [google/protobuf#4584]
I faced with a similar compilation error as #549 on macOS High Sierra.

    ../protobuf/src/google/protobuf/descriptor.pb.h:1605:21: error: expected member name or ';' after declaration specifiers
    static const Type TYPE_BOOL =
      ~~~~~~~~~~~~~~~~~ ^

    In file included from
    ....
    /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include/ConditionalMacros.h:147:39: note: expanded from 
    macro 'TYPE_BOOL'
    #define TYPE_BOOL                1
                  ^

While #549 is fixed, this time is an another scenario -- I extended `FieldOptions` in `my.proto`. I imported [descriptor.proto](https://github.com/google/protobuf/blob/master/src/google/protobuf/descriptor.proto) in `my.proto` file. Then, after protoc compile, `my.pb.h` includes the pre-compiled [descriptor.pb.h](https://github.com/google/protobuf/blob/master/src/google/protobuf/descriptor.pb.h) which does not have the fix in [descriptor.h](https://github.com/google/protobuf/blob/master/src/google/protobuf/descriptor.h#L65).

**Comment by xfxyjwf** [comment]
Do you know why there is no such error when compiling descriptor.pb.cc?

**Comment by xfxyjwf** [comment]
Given that you can compile protobuf library itself, I think you should be able to fix the issue by include "#undef TYPE_BOOL" in your code before including protobuf headers.

**Comment by yijiem** [comment]
I found in macOS sdk 10.13, apple removed TYPE_BOOL from ConditionalMacros.h. So this only conflicts with macOS sdk 10.12 and potential earlier version.

**Comment by xfxyjwf** [comment]
@yijiem Thanks for the updates. That's even better.
