### ISSUE TITLE
MinGW build failed

### ISSUE THREAD

**Issue by chronoxor** [google/protobuf#4585]
C:/projects/cppserialization/modules/protobuf/src/google/protobuf/stubs/mathlimits.h:248:47: error: '_finite' was not declared in this scope
   static bool IsFinite(const Type x) { return _finite(x); } \
                                               ^

**Comment by chronoxor** [comment]
Latest MinGW with GCC 7.3.0

**Comment by xfxyjwf** [comment]
Help us fix it with a pull request? :)

**Comment by chronoxor** [comment]
Fixed!
