### ISSUE TITLE
`make install` doesn't install Python modules

### ISSUE THREAD

**Issue by stefanseefeld** [google/protobuf#4592]
I'm trying to install `protobuf` from sources. I notice that `make install` doesn't install any Python modules. Is there a special `make` target I need to invoke to install them or is this functionality simply missing ?

**Comment by phil-el** [comment]
I don't think there is such target, see https://github.com/google/protobuf/tree/master/python

**Comment by TeBoring** [comment]
You should use pypi to download python runtime.
