### ISSUE TITLE
gtest download link in protobuf-2.5.0 autogen.sh is inacessible and needs update

### ISSUE THREAD

**Issue by vserrao** [google/protobuf#4595]
When I tried to build protobuf-2.5.0, I noticed that the gtest-1.5.0 tar download link in the autogen.sh is inaccessible. I compared with latest version and constructed the link for the required gtest version in protobuf-2.5.0 and got the gtest downloaded. 
Current gtest download link in v2.5.0 autogen.sh
----> http://googletest.googlecode.com/files/gtest-1.5.0.tar.bz2
New required gtest download link for protobuf-2.5.0
----> https://github.com/google/googletest/archive/release-1.5.0.tar.gz

I have prepared a patch for the same. PFA. 
[protobuf-2.5.0-gtestLinkUpdate.txt](https://github.com/google/protobuf/files/1978630/protobuf-2.5.0-gtestLinkUpdate.txt)

Please let me know if any queries

**Comment by xfxyjwf** [comment]
Thanks for the tips. Though we can no longer update already released 2.5.0.
