### ISSUE TITLE
Multi Dimensional arrays, Nested Maps and their combination

### ISSUE THREAD

**Issue by dilipvamsi** [google/protobuf#4596]
Hi,
Is there a possibility of implementation of the following without creating a message.

1. **Repeated Field** with **Repeated Field** as **_Element_** (nested list)
2. **Repeated Field** with **Map Field** as **_Element_** (list of maps)
3. **Map Field** with **Repeated Field** as **_Value_** (map from a key to list)
4. **Map Field** with **Map Field** as **_Value_** (map from key to map)

Thanks,
Dilip Vamsi.

**Comment by xfxyjwf** [comment]
No.  You will need to create a message type to hold the inner repeated/map field.

**Comment by 4F2E4A2E** [comment]
It seems that there no way support for nested arrays with protobuf. 
This `[[[48.21705505712975]]]` is simply not possible to be achieved without having to write your encoder and decoder. 

Unfortunately, there is no statement, about nested arrays in the docs and possible workarounds.

**Comment by perezd** [comment]
Are nested messages not a realistic solution?

**Comment by 4F2E4A2E** [comment]
Hey @perezd, thank you for asking, but no. _I would love to be wrong here_, but as far as I can tell,  proto3 does not support nested arrays in any way.

I have migrated a few APIs to gRPC over time, but this one I am playing around with has entities with geoJson data, like this one: 
```
{ "type": "MultiPolygon",
  "coordinates": [
    [
      [[102.0, 2.0], [103.0, 2.0], [103.0, 3.0], [102.0, 3.0], [102.0, 2.0]]
    ],
    [
      [[100.0, 0.0], [101.0, 0.0], [101.0, 1.0], [100.0, 1.0], [100.0, 0.0]],
      [[100.2, 0.2], [100.8, 0.2], [100.8, 0.8], [100.2, 0.8], [100.2, 0.2]]
    ]
  ]
}
```

Though, there are solutions for geoJson as protobuf (geobuf), but they require its own encode and decode method. Which I would have to write for each language in the environment, in my case, dart, ts, python and maybe go. This takes the point of using protobuf and grpc completely.

I love gRPC and protobuf, but at the moment I cannot express how disappointed I am in being forced to give it up.

geobuf: https://github.com/mapbox/geobuf

**Comment by sinorockie** [comment]
> Hey @perezd, thank you for asking, but no. _I would love to be wrong here_, but as far as I can tell, proto3 does not support nested arrays in any way.
> 
> I have migrated a few APIs to gRPC over time, but this one I am playing around with has entities with geoJson data, like this one:
> 
> ```
> { "type": "MultiPolygon",
>   "coordinates": [
>     [
>       [[102.0, 2.0], [103.0, 2.0], [103.0, 3.0], [102.0, 3.0], [102.0, 2.0]]
>     ],
>     [
>       [[100.0, 0.0], [101.0, 0.0], [101.0, 1.0], [100.0, 1.0], [100.0, 0.0]],
>       [[100.2, 0.2], [100.8, 0.2], [100.8, 0.8], [100.2, 0.8], [100.2, 0.2]]
>     ]
>   ]
> }
> ```
> 
> Though, there are solutions for geoJson as protobuf (geobuf), but they require its own encode and decode method. Which I would have to write for each language in the environment, in my case, dart, ts, python and maybe go. This takes the point of using protobuf and grpc completely.
> 
> I love gRPC and protobuf, but at the moment I cannot express how disappointed I am in being forced to give it up.
> 
> geobuf: https://github.com/mapbox/geobuf

Although protobuf v3 support nested arrays through repeated google.protobuf.ListValue which can be used after importing google.protobuf.struct.proto
