### ISSUE TITLE
Use GeneratedMessage instead of GeneratedMessageV3

### ISSUE THREAD

**Issue by nkrode** [google/protobuf#4606]
Hi - Is there a way to force protoc 3.5.1 to treat a proto file with syntax = "proto2" to generate messages extending GeneratedMessage class instead of GeneratedMessageV3?

We have third party libraries which expect GeneratedMessage in message signature.

Thanks,
Nitin

**Comment by xfxyjwf** [comment]
This is not possible. GeneratedMessage/GeneratedMessageV3 is not supposed to be referenced directly by users code. Do you know why it's used by the library and whether they can remove the reference? If these libraries have included generated code by protoc 2.x, they will have to be updated for you to use protoc 3.5.1 with them.

**Comment by xfxyjwf** [comment]
The library should be updated to use MessageLite or Message interface instead. GeneratedMessage is to be used by generated code only and should not be used by users.
