### ISSUE TITLE
"extend" is now allowed in proto3 spec, but is used in tests

### ISSUE THREAD

**Issue by stepancheg** [google/protobuf#4610]
[Spec 3](https://developers.google.com/protocol-buffers/docs/reference/proto3-spec) doesn't mention `extend` unlike [Spec 2](https://developers.google.com/protocol-buffers/docs/reference/proto2-spec).

However `extend` with `syntax = "proto3"` is [used in protobuf tests](https://github.com/google/protobuf/blob/7377d81ca44baf2e505c927a2e25b2f0e3596fed/php/tests/proto/test_import_descriptor_proto.proto).

**Comment by stepancheg** [comment]
@TeBoring unfortunately protobuf compiler `protoc` accepts this option. And I'm writing Rust implementation of protobuf, and my implementation should be compatible with `protoc`.

If this option is not meant to be used outside of Google, then public version of `protoc` compiler should probably reject it.

**Comment by stepancheg** [comment]
```
%%% cat ./aaa.proto
syntax = "proto3";

import "google/protobuf/descriptor.proto";

message TestImportDescriptorProto {
  extend google.protobuf.MethodOptions {
    int32 a = 72295727;
  }
}

extend google.protobuf.MethodOptions {
  int32 a = 72295728;
}
%%% cat ./aaa.proto
syntax = "proto3";

import "google/protobuf/descriptor.proto";

message TestImportDescriptorProto {
  extend google.protobuf.MethodOptions {
    int32 a = 72295727;
  }
}

extend google.protobuf.MethodOptions {
  int32 a = 72295728;
}
```

**Comment by TeBoring** [comment]
@anandolee, we can still define custom option in proto3, right?

**Comment by xfxyjwf** [comment]
In proto3, custom options are allowed, i.e., users can use "extend" keyword to define their own extensions to proto descriptor options. The spec is missing stuff because it was created after protoc, i.e., it's introduced to describe what protoc does, rather than defining what protoc does. If you are implementing protobuf support in a new language it's better to follow what protoc accepts instead of what the spec doc says.

**Comment by subfuzion** [comment]
I know the issues is closed, but can the misleading title (which shows up in searches) be fixed? I believe *now* is supposed to be *not*.

**Comment by fowles** [comment]
Fixed!  (I hate that typo and am amazed how often I make it)
