### ISSUE TITLE
Compatibility in Proto3 for retaining unknown fields

### ISSUE THREAD

**Issue by jaineshp** [google/protobuf#4612]
Hello, 

Let's say we have a JSON String and want to convert it to Proto3 object. Looks like there is no feature to retain the unknown fields in proto3. So when I will convert the proto3 object back to JSON I will lose the fields that are not present in the proto object. Do we have anything around it? 

A simple workaround is to use only keys of JSON which are there in proto. But that doesn't look scalable. 

Thank you.

**Comment by xfxyjwf** [comment]
There is no way to preserve unknown fields through the JSON-to-proto boundary. If you are doing JSON to proto conversion, make sure you either reject the conversion when unknown fields are present, or make sure your application can tolerate missing unknown fields during the conversion.
