### ISSUE TITLE
Unable to add hiphen "-" in proto 3 field name

### ISSUE THREAD

**Issue by Nayan-Das** [google/protobuf#4613]
message Obsmsg { 
message P-GLOBAL {
         string latitude = 1;
         string longitude = 2;
         string altitude = 3;
      }
   
   P-GLOBAL p-global = 1;
}

I am unable to generate java class file if "-" contain in the field name.

**Comment by acozzette** [comment]
@Nayan-Das I believe this is working as intended--we don't support hyphens in field names or other identifiers. You can use underscores, though.

**Comment by Nayan-Das** [comment]
I understand,we can not add "-" but is there any way we can annotate the field name for "-".
Like any other library (Jackson,Ebean,GSON) support annotation.
Example of GSON annotation-
 @SerializedName("person-name")
    String personName;

I can not change the field name .Please suggest is there any way around?

**Comment by acozzette** [comment]
@Nayan-Das Are you just trying to set the JSON field name? If so, you could try annotating the field like this:
`PGlobal p_global = 1 [json_name = "p-global"];`
I haven't tried using hypens in JSON field names but I assume it should work.

**Comment by vladimirshramov** [comment]
oasisprotocol grpc uses  dash in service name;
example fullMethodName: oasis-core.Beacon/GetBaseEpoch
but I can not write `package: oasis-core;`
Generated class BeaconGrpc has line:
`public static final String SERVICE_NAME = "oasis_core.Beacon";`
Please support setting SERVICE_NAME in builder;
