### ISSUE TITLE
configure.ac fails to find sched_yield for android

### ISSUE THREAD

**Issue by banshee** [google/protobuf#4615]
The configure.ac file wants to find sched_yield for android:

```
case "$target_os" in
  mingw* | cygwin* | win* )
    ;;
  *)
    # Need to link against rt on Solaris
    AC_SEARCH_LIBS([sched_yield], [rt], [], [AC_MSG_FAILURE([sched_yield was not found on your system])])
    ;;
esac

```

The problem is that it tries to find it by compiling a binary that runs on the host (using the toolchain meant for cross-compiling binaries that run on Android).  I don't think it's possible; sched_yield isn't defined in any of the libraries in the toolchain that I could find.  (I assume it's present on the target).

I think all you need to do to solve this is to add ``` | *android*```  to the mingw* | cygwin ... line.

**Comment by acozzette** [comment]
@banshee Could you send us a pull request with your suggested fix?

**Comment by banshee** [comment]
Done - https://github.com/google/protobuf/pull/4631.  I wasn't sure which branch to target though.

**Comment by acozzette** [comment]
@banshee Thanks! I think it would be best to target the master branch, though.

**Comment by banshee** [comment]
Retargeting came up with some unrelated issues with php files; I'll probably just kill that one and create a new one from master

**Comment by banshee** [comment]
https://github.com/google/protobuf/pull/4631 now points to master

**Comment by acozzette** [comment]
Thanks for the pull request!

**Comment by banshee** [comment]
Happy to help

**Comment by JoanPereyra** [comment]
I have the same issue for target_os linux-gnu
