### ISSUE TITLE
Why returning "str" for INT types in MessageToDict

### ISSUE THREAD

**Issue by zipperHead** [google/protobuf#4636]
https://github.com/google/protobuf/blob/e232038e061ad99225a1c568fca24181416461ef/python/google/protobuf/json_format.py#L284

I am wondering what is the reason behind returning a string for integer type fields in this method "MessageToDict"

**Comment by xfxyjwf** [comment]
See:
https://developers.google.com/protocol-buffers/docs/proto3#json

Specifically:
```
int64, fixed64, uint64, JSON value will be a decimal string. Either numbers or strings are accepted.
```
