### ISSUE TITLE
Why c++ zerocopystream can reduce memory copy?

### ISSUE THREAD

**Issue by little-bird-in-china** [google/protobuf#4641]
How zerocopystream like IstreamInputStream and OstreamOutputStream reduce memory copy?

**Comment by daoleno** [comment]
>  So, the stream can return a buffer which actually points directly into the final data structure where the bytes are to be stored, and the caller can interact directly with that buffer, eliminating an intermediate copy operation.

[zero_copy_stream.h](https://developers.google.com/protocol-buffers/docs/reference/cpp/google.protobuf.io.zero_copy_stream)

**Comment by little-bird-in-china** [comment]
Is there any use case for the zerocopystream out of protobuf library,
It's seems nonsense to me.
