### ISSUE TITLE
PHP: Support a more convenient way to set/get wrapper types.

### ISSUE THREAD

**Issue by xfxyjwf** [google/protobuf#4645]
Right now to create a wrapper type, users need to do:
```
$mybool = new BoolValue();
$mybool.setValue(true);
```

See b/79144925

**Comment by AnashOommen** [comment]
I illustrated this with BoolValue, but similar problem exists for other other wrapper types also. It would be helpful if we had an easier way of constructing these objects, using the native types.

**Comment by TeBoring** [comment]
We have already implemented array constructor in php-generated-dev. I will merge it in this coming week.
You can just do: ```$mybool = new BoolValue()```

**Comment by TeBoring** [comment]
merged into master and 3.6.x
