### ISSUE TITLE
Is this a bug ?

### ISSUE THREAD

**Issue by weike20** [google/protobuf#4647]
test.proto
syntax = "proto2";
package ProtoBuf;
message EXAMPLE_MESSAGE
{
    optional uint32 id = 1;
}
main.cpp:
#include <iostream>
#include <memory>
#include <cstring>
#include "test.pb.h"
using namespace std;
std::vector<char*> buff;
void serialize1(const ProtoBuf::EXAMPLE_MESSAGE& message)
{
    char body[message.ByteSize()];
    message.SerializeToArray(body,message.ByteSize());
    buff.push_back(body);
}

int main()
{
    ProtoBuf::EXAMPLE_MESSAGE msg1;
    for(int i = 0;i<2;++i)
    {
        msg1.set_id(i);
        serialize1(msg1);
    }
 for(size_t i = 0;i<buff.size();++i)
    {
        ProtoBuf::EXAMPLE_MESSAGE msg2;
        msg2.ParseFromArray(buff[i],msg1.ByteSize());
        std::cout<<"index: "<<i<<" id: "<<msg2.id()<<std::endl;
    }

    return 0;
}
console : 
index:0 id 0
index:1 id 0

**Comment by weike20** [comment]
Or I was wrong？

**Comment by arthur-tacca** [comment]
The problem is not in C++, but in your understanding of variable lifetimes in C++, specifically here:

    void serialize1(const ProtoBuf::EXAMPLE_MESSAGE& message)
    {
        char body[message.ByteSize()];
        message.SerializeToArray(body,message.ByteSize());
        buff.push_back(body);  // <-- taking address of local variable to dereference later
    }

**Comment by weike20** [comment]
I got it,thanks.
