### ISSUE TITLE
Error with version of protocol buf

### ISSUE THREAD

**Issue by timoonboru** [google/protobuf#4649]
Helo, The error is shown as
[libprotobuf FATAL google/protobuf/stubs/common.cc:61] This program requires version 3.5.0 of the Protocol Buffer runtime library, but the installed version is 2.6.1. Please update your library. If you compiled the program yourself, make sure that your headers are from the same version of Protocol Buffers as your link-time library. (Version verification failed in "bazel-out/arm-opt/genfiles/tensorflow/contrib/tpu/proto/tpu_embedding_config.pb.cc".)
terminate called after throwing an instance of 'google::protobuf::FatalException'
what(): This program requires version 3.5.0 of the Protocol Buffer runtime library, but the installed version is 2.6.1. Please update your library. If you compiled the program yourself, make sure that your headers are from the same version of Protocol Buffers as your link-time library. (Version verification failed in "bazel-out/arm-opt/genfiles/tensorflow/contrib/tpu/proto/tpu_embedding_config.pb.cc".)
Aborted (core dumped)

This error seems that I have different versions of protoc. 
What is the relation between protoc and protobuf?
And WHY "the installed version is 2.6.1."

nvidia@tegra-ubuntu:~$ protoc --version
libprotoc 3.5.1

nvidia@tegra-ubuntu:~$ pip list
protobuf (3.5.2.post1)

Which one is the real protoc version? 2.6.1, 3.5.1 or  3.5.2.post1 ?

 Thank u!

**Comment by acozzette** [comment]
The `protoc` that is used to generate code from `.proto` files has to exactly match the version the protobuf runtime (e.g. `libprotobuf`) that you link against. I think you probably have an old 2.6.1 library installed through the system package manager, so it might simplify things to remove that, if possible.

**Comment by krkim728** [comment]
In my case, I remove the environment variable about libprotobuf at etc/bash.bshrc
from
export LD_PRELOAD=$LD_PRELOAD:/usr/lib/x86_64-linux-gnu/libstdc++.so.6:/usr/lib/x86_64-linux-gnu/libprotobuf.so.9
to
export LD_PRELOAD=$LD_PRELOAD:/usr/lib/x86_64-linux-gnu/libstdc++.so.6

And, I solved.

**Comment by zhilaAI** [comment]
sorry I have the same problem how did you solve it?
