### ISSUE TITLE
when to support lite runtime in proto3?

### ISSUE THREAD

**Issue by raymondhjm** [google/protobuf#465]
supporting for resource limited devices such as android/ios would prefer a lite runtime of protobuf 3, as the size of packaged android/ios application become a critical consideration in common cases.

**Comment by noisypants** [comment]
I'm interested in this as well.  Specifically, i'm interested in the lite runtime for C#.
thanks

**Comment by joshburnett** [comment]
Interested in the lite runtime for C++ here.
Thanks!

**Comment by DrJohnAZoidberg** [comment]
Also interested in the lite runtime for C++.
thanks

**Comment by suvirbhargav** [comment]
Any update on lite support? 
Thanks

**Comment by xfxyjwf** [comment]
Different languages have different schedules. The first to support proto3 lite is probably Java and then C++. They will likely happen after protobuf 3.0.0 release though.
