### ISSUE TITLE
Make in msys2 with MinGW32 fails

### ISSUE THREAD

**Issue by Panakotta00** [google/protobuf#4653]
when I try to compile protobuf for c++ in my msys2 with mingw32 to implement the lib in my Qt project I get this error:

```
./.libs/lt-protoc.c:315:19: error: '_P_WAIT' undeclared (first use in this function)
   rval = _spawnv (_P_WAIT, lt_argv_zero, (const char * const *) newargz);
                   ^
./.libs/lt-protoc.c:315:19: note: each undeclared identifier is reported only once for each function it appears in
strip: './protoc.exe': No such file
```
I have downloaded leatest -zip for c++... runned ./configure and then make

Has anybody an idea why this won't work?

**Comment by acozzette** [comment]
We don't officially support MinGW and don't really have any experience with it, so unfortunately I don't think we can help much with this error. One thing you could try would be to use the CMake build instead and see if that works. If you figure out a fix, feel free to send us a pull request.

**Comment by lamborqq** [comment]
I ran into the same problem, window Qt+mingw uses protobuf
  Is there any other plan?

**Comment by Kreijstal** [comment]
> I ran into the same problem, window Qt+mingw uses protobuf Is there any other plan?

just install from https://packages.msys2.org/package/mingw-w64-x86_64-protobuf
