### ISSUE TITLE
[C++/VS2017] unresolved external in text_format.cc and wire_format.cc

### ISSUE THREAD

**Issue by Johnnyloong** [google/protobuf#4662]
I build protobuf with vcpkg, and I use the static lib,include three files: libprotobuf-lited.lib, libprotobufd.lib , libprotocd.lib, in my project. but there are two link errors in my project:

2>------ Build started: Project: logic_songyuan_alpha, Configuration: Debug Win32 ------
2>libprotobufd.lib(text_format.cc.obj) : error LNK2019: unresolved external symbol ___std_reverse_trivially_swappable_4 referenced in function "void __cdecl std::_Reverse_unchecked1<class google::protobuf::Message const * *>(class google::protobuf::Message const * * const,class google::protobuf::Message const * * const,struct std::integral_constant<unsigned int,4>)" (??$_Reverse_unchecked1@PAPBVMessage@protobuf@google@@@std@@YAXQAPBVMessage@protobuf@google@@0U?$integral_constant@I$03@0@@Z)
2>libprotobufd.lib(wire_format.cc.obj) : error LNK2001: unresolved external symbol ___std_reverse_trivially_swappable_4
2>E:\git\symj\vs_project\Debug\logic_songyuan_alpha.exe : fatal error LNK1120: 1 unresolved externals

I don't know what to do with it

**Comment by Johnnyloong** [comment]
I solve this problem just by upgrade the vs project version to v14.1

**Comment by Pitority** [comment]
@Johnnyloong I still get this exact error 

`unresolved external symbol ___std_reverse_trivially_swappable_4	libprotobuf.lib(wire_format.cc.obj)	`

My Platform Toolset is set to "VS17 V141". What is your SDK-Version? Maybe reopen this bug?

**Comment by aarotech** [comment]
Any solution to this?
I have no version mismatch anywhere in any project but this error still prevents building in VS 2017
