### ISSUE TITLE
Any Type Url returns 404 error

### ISSUE THREAD

**Issue by sbsends** [google/protobuf#4664]
When I perform a get request on a Any type url (for instance: type.googleapis.com/google.profile.Person) I receive a 404 error.

**Comment by sbsends** [comment]
@haberman @bakineggs @tenderlove @nico

**Comment by sbsends** [comment]
How are binary representations of type proto's generated? Does any tooling for this exist?

**Comment by sbsends** [comment]
@xfxyjwf

**Comment by xfxyjwf** [comment]
At the moment no such service exists as far as I can tell. What's your use case for this?

**Comment by sbsends** [comment]
[Use Case](https://github.com/tensortask/ttp)

**Comment by xfxyjwf** [comment]
@sbsends Can you explain a bit more? I saw a Any field there, but why do you need a type service? How will you or your user use a type service?

**Comment by sbsends** [comment]
@xfxyjwf The goal is to write a minimalist protobuf for transmitting tensors between applications and translating between various formats (e.g. converting from a tensorflow serving protobuf to a request formatted for Google ML-Engine). The Any field is to allow specific formats to use the same baseline format while retaining the ability to extend that application's specific needs (e.g. adding a model version number or other forms of application specific metadata).

**Comment by sbsends** [comment]
@xfxyjwf I will have the users push code to the metadata directory within the GitHub repo that I linked. I will autogenerate and host the binaries from that directory.

**Comment by xfxyjwf** [comment]
So you need to implement your own type service? For that you can use the C++ TypeResolver API here:
https://github.com/google/protobuf/blob/master/src/google/protobuf/util/type_resolver.h#L62
https://github.com/google/protobuf/blob/master/src/google/protobuf/util/type_resolver_util.h#L47

I.e., your service will read all .proto files in the metadata directory, create a DescriptorPool for it and use the above TypeResolver to convert it to the google.protobuf.Type message.

**Comment by sbsends** [comment]
Thank you @xfxyjwf!
