### ISSUE TITLE
3.4.x branch has been deleted

### ISSUE THREAD

**Issue by whbruce** [google/protobuf#4670]
The "rocko" release (fall 2017) of the Openembedded build system relies on this branch.

**Comment by iyernaveenr** [comment]
I second whbruce's comment above.
@whbruce How about using 3.5.1.1 instead of 3.4.x? I tried 3.5.1.1, and it worked.

**Comment by schiffermtq** [comment]
Restoring the 3.4.x branch (e.g. to the v3.4.1 tag) would be desirable, so projects referencing it (like the mentioned OpenEmbedded Rocko release) can be built without changes.

**Comment by opello** [comment]
A workaround is to add a `protobuf_3.4.1.bbappend` that changes the `SRC_URI` to `git://github.com/google/protobuf.git;tag=v3.4.1`.

**Comment by balister** [comment]
FYI there is a patch for this problem on the list. We use the mailing list for problem like this, not github issues.

**Comment by xfxyjwf** [comment]
Please use tag instead of branch. We do not guarantee branches to be stable.
