### ISSUE TITLE
The debug version of an error

### ISSUE THREAD

**Issue by zhaobu** [google/protobuf#4679]
When I use the c++ debug version to generate the source code,an error occurred:
[libprotobuf FATAL C:\code\protobuf\src\google\protobuf\generated_message_reflection.cc:2372] CHECK failed: file != NULL:
I read the protobuf source code,the error line of code:
  const ::google::protobuf::FileDescriptor* file =
      ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(filename);
  GOOGLE_CHECK(file != NULL);
beacuse the pointer "file " is a null pointer;

**Comment by zhaobu** [comment]
this is my test proto file:

syntax = "proto3";
message Person {
   string name = 1;  
   int32 age = 2;  
   string email = 3;  
   int32 int_set = 4;
}

**Comment by xfxyjwf** [comment]
I think this is a duplicate of https://github.com/google/protobuf/issues/4773
