### ISSUE TITLE
add java_classname option

### ISSUE THREAD

**Issue by nodirt** [google/protobuf#4680]
Add message-level option `java_classname` that specifies an alternative name for the generated Java class for the message.

Motivation: we already started to use a message name `Builder` and later tried to compile it to Java. It compiles to invalid Java code: conflict between the constructor and the method that creates a message builder.

WDYT/how hard is to implement overall? We might want to contribute.

**Comment by xfxyjwf** [comment]
The problem of such options is that it adds complexity to both the implementation and the API surface, and it will become a lot worse when multiple options get added and can affect with each other (which is very likely if we are too liberal in adding options). So in general we do not accept new options unless it's necessary to address a severe problem.

In this case I would suggest you rename the message instead.

**Comment by nodirt** [comment]
thanks

FWIW the context was crbug.com/846509
