### ISSUE TITLE
What is serialized in python3 cannot be deserialized in Js

### ISSUE THREAD

**Issue by taoxinyi** [google/protobuf#4688]
The .proto file
```
syntax = "proto3";
message ChatMessageItem {
    int32 clientId = 1;
    string clientName = 2;
    string message = 3;
    string imageUrl = 4;
    int32 timeStamp = 5;
    string fileUrl = 6;
    int32 fileSize = 7;
    string fileName = 8;
}

message ChatMessage {
    enum Type {
        CHAT_MESSAGE = 0;
        CLIENT_ENTER = 1;
        CLIENT_LEAVE = 2;
    }
    Type type = 1;
    repeated ChatMessageItem chat_message_item = 2;
    repeated ChatMessageItem current_client = 3;
}
```
Serialize this ChatMessage instance in python3
```
>>> chat_message
chat_message_item {
  clientId: 3
  clientName: "TaoB"
  imageUrl: "/media/user/photo/2016/11/24/QQ\345\233\276\347\211\20720161123202858.png"
  timeStamp: 1527310142
  fileUrl: "media/user/3/\345\265\214\345\205\245\345\274\217_20180526124902.pptx"
  fileSize: 5808168
  fileName: "\345\265\214\345\205\245\345\274\217.pptx"
}
```
```
b = chat_message.SerializeToString()
s = ""
for i in range(len(b)):
    s += str(b[i]) + ","
>>> s
```
`18,141,1,8,3,18,4,84,97,111,66,34,55,47,109,101,100,105,97,47,117,115,101,114,47,112,104,111,116,111,47,50,48,49,54,47,49,49,47,50,52,47,81,81,229,155,190,231,137,135,50,48,49,54,49,49,50,51,50,48,50,56,53,56,46,112,110,103,40,190,206,163,216,5,50,42,109,101,100,105,97,47,117,115,101,114,47,51,47,229,181,140,229,133,165,229,188,143,95,50,48,49,56,48,53,50,54,49,50,52,57,48,50,46,112,112,116,120,56,168,192,226,2,66,14,229,181,140,229,133,165,229,188,143,46,112,112,116,120,37,122,156,43,217,`

Then put this array into Js
`var uint8Array = new Uint8Array([18,141,1,8,3,18,4,84,97,111,66,34,55,47,109,101,100,105,97,47,117,115,101,114,47,112,104,111,116,111,47,50,48,49,54,47,49,49,47,50,52,47,81,81,229,155,190,231,137,135,50,48,49,54,49,49,50,51,50,48,50,56,53,56,46,112,110,103,40,171,201,163,216,5,50,42,109,101,100,105,97,47,117,115,101,114,47,51,47,229,181,140,229,133,165,229,188,143,95,50,48,49,56,48,53,50,54,49,50,51,56,48,51,46,112,112,116,120,56,168,192,226,2,66,14,229,181,140,229,133,165,229,188,143,46,112,112,116,120,37,122,156,43,217]);`

It throws `uncaught exception: AssertionError: Assertion failed   protobuf.js:100:845` when tying to decode.
`console.log(proto.ChatMessage.deserializeBinary(uint8Array));`

This happens randomly and I don't how to solve this. It seems in python the bytes can be parsed back to ChatMessage Instance. But using the same byte data in Js sometime it throws an error.

**Comment by acozzette** [comment]
Could you post the line of code in `protobuf.js` that contains the assertion that's failing?

**Comment by taoxinyi** [comment]
@acozzette  

```
goog.string.splitLimit=function(a,b,c){a=a.split(b);for(var d=[];0<c&&a.length;)d.push(a.shift()),c--;a.length&&d.push(a.join(b));return d};goog.string.editDistance=function(a,b){var c=[],d=[];if(a==b)return 0;if(!a.length||!b.length)return Math.max(a.length,b.length);for(var e=0;e<b.length+1;e++)c[e]=e;for(e=0;e<a.length;e++){d[0]=e+1;for(var f=0;f<b.length;f++)d[f+1]=Math.min(d[f]+1,c[f+1]+1,c[f]+Number(a[e]!=b[f]));for(f=0;f<c.length;f++)c[f]=d[f]}return d[b.length]};goog.asserts={};goog.asserts.ENABLE_ASSERTS=goog.DEBUG;goog.asserts.AssertionError=function(a,b){b.unshift(a);goog.debug.Error.call(this,goog.string.subs.apply(null,b));b.shift();this.messagePattern=a};goog.inherits(goog.asserts.AssertionError,goog.debug.Error);goog.asserts.AssertionError.prototype.name="AssertionError";goog.asserts.DEFAULT_ERROR_HANDLER=function(a){throw a;};goog.asserts.errorHandler_=goog.asserts.DEFAULT_ERROR_HANDLER;
```

**Comment by acozzette** [comment]
When you say this happens randomly, do you mean that it happens for certain serialized messages but not others? Does the parsing fail reliably with the particular serialized message you posted?

**Comment by taoxinyi** [comment]
@acozzette  Yes. For most serialized messages, it can be parsed correctly in js. However,in my case, the parsing of this particular serialized message always fails in js. Maybe this is the problem of serialization in python because this particular serialized message cannot be parsed when I use protobuf.js either.

**Comment by acozzette** [comment]
@taoxinyi Ok, I see. If you wouldn't mind, could you try narrowing it down to a smaller message that results  in the same error? I am guessing that there is just one particular field causing the problem.

**Comment by taoxinyi** [comment]
@acozzette  Maybe fileSize or fileUrl. Because this problem only occurred after I added file-related field. I'll test it thoroughly when I have time.

**Comment by acozzette** [comment]
@taoxinyi Let me close this issue for now but feel free to post here if you're able to figure out more about which field is causing the problem.

This might also be related to #4721. I think that bug is similar because it only affects Python 3 and involves handling of non-ASCII UTF-8 characters.

**Comment by gpshead** [comment]
fyi - regardless of bugs, using the text format as a data interchange between implementations is fraught with peril.  That is not what text format is for.  Use binary when you need to do that.
