### ISSUE TITLE
[BUG][C++] a double value SerializeToString,and then ParseFromString will failed.

### ISSUE THREAD

**Issue by zhailei2014** [google/protobuf#4689]
A double var that the right of the decimal places is zero (for example 5.0)  SerializeToString,
Then ParseFromString you will get the wrong result.

**Comment by xfxyjwf** [comment]
The following two lines are incorrect because protobuf data is not null-terminated strings.
```cpp
strcpy_s(szBuf, str.c_str());
person1.ParseFromString(szBuf);
```
