### ISSUE TITLE
[Java] Merging bool fields

### ISSUE THREAD

**Issue by vexdev** [google/protobuf#4690]
When using the `mergeFrom` method there seem to be an inconsistency between the documentation and the actual behaviour when merging `bool` primitives.

The documentation for `mergeFrom` states:

> * For singular primitive fields, if the field is set in other, then other's value overwrites the value in this message.

While the actual generated code looks like:

```
        if (other.getValue() != false) {
          setValue(other.getValue());
        }
```

Therefore the merge happens only if the other message has a true value.

Probably the documentation should be extended or the generated code should be modified to always merge a boolean.

**Comment by xfxyjwf** [comment]
It seems you are using proto3. In proto3, a bool field is considered set only if its value is true.
