### ISSUE TITLE
csharp tests are constantly failing on travis-ci.

### ISSUE THREAD

**Issue by xfxyjwf** [google/protobuf#470]
See: https://travis-ci.org/google/protobuf/jobs/65670469

**Comment by jtattermusch** [comment]
The failure posted is for OS X run.
see the logs: "x86_64-apple-darwin13.4.0"

I haven't setup C# tests to run on OS X. Just preventing the tests from running on OS X should work fine.

**Comment by xfxyjwf** [comment]
the failing csharp test is excluded in https://github.com/google/protobuf/pull/483
