### ISSUE TITLE
add python caffe layer error

### ISSUE THREAD

**Issue by jasminezz** [google/protobuf#4700]
When i Add a new python caffe layer, if protobuf version=3.1.0 everything is ok. But When I change to version=3.5.0, I get the error:
*** Aborted at 1527676860 (unix time) try "date -d @1527676860" if you are using GNU date ***
PC: @     0x7fd3fb5ffd53 std::_Hashtable<>::clear()
*** SIGSEGV (@0x9) received by PID 19443 (TID 0x7fd469f2bb00) from PID 9; stack trace: ***
    @     0x7fd4670234b0 (unknown)
    @     0x7fd3fb5ffd53 std::_Hashtable<>::clear()
    @     0x7fd3fb5f84d6 google::protobuf::DescriptorPool::FindFileByName()
    @     0x7fd3fb5b0058 google::protobuf::python::cdescriptor_pool::AddSerializedFile()
    @     0x7fd4676809f0 PyEval_EvalFrameEx
    @     0x7fd4677b605c PyEval_EvalCodeEx
    @     0x7fd46770c46d (unknown)
    @     0x7fd4676df273 PyObject_Call
    @     0x7fd4676ffb75 (unknown)
    @     0x7fd467696173 (unknown)
    @     0x7fd4676df273 PyObject_Call
    @     0x7fd46767d35c PyEval_EvalFrameEx
    @     0x7fd4677b605c PyEval_EvalCodeEx
    @     0x7fd467677da9 PyEval_EvalCode
    @     0x7fd467719244 PyImport_ExecCodeModuleEx
    @     0x7fd467719c1f (unknown)
    @     0x7fd46771b390 (unknown)
    @     0x7fd46771b658 (unknown)
    @     0x7fd46771c76b PyImport_ImportModuleLevel
    @     0x7fd4676868b8 (unknown)
    @     0x7fd4676df273 PyObject_Call
    @     0x7fd4677b5487 PyEval_CallObjectWithKeywords
    @     0x7fd46767b7e6 PyEval_EvalFrameEx
    @     0x7fd4677b605c PyEval_EvalCodeEx
    @     0x7fd467677da9 PyEval_EvalCode
    @     0x7fd467719244 PyImport_ExecCodeModuleEx
    @     0x7fd467719c1f (unknown)
    @     0x7fd46771b390 (unknown)
    @     0x7fd46771b658 (unknown)
    @     0x7fd46771c76b PyImport_ImportModuleLevel
    @     0x7fd4676868b8 (unknown)
    @     0x7fd4676df273 PyObject_Call

**Comment by acozzette** [comment]
@jasminezz Could you provide some more details on how to reproduce the crash?

**Comment by jasminezz** [comment]
I have fix the problem. Because there are 3 protobufs:Ubuntu has a Protobuf, system python has a Protobuf, Virtuenv has a protobuf, all these must have the same version.
