### ISSUE TITLE
How to validate a new version of a schema against a previous one?

### ISSUE THREAD

**Issue by javierholguera** [google/protobuf#4701]
If I have schema like this

```proto
syntax = "proto3";

message SearchRequest {
  string query = 1;
  int32 page_number = 2;
  int32 result_per_page = 3;
}
```

Let's say that I'm evolving this schema and I accidentally do these changes:

```proto
syntax = "proto3";

message SearchRequest {
  **int32** query = 1;
  int32 page_number = 2;
  int32 result_per_page = 3;
  string another_field = 4;
}
```
How can I know that the changes that I've done are not compatible with the previous version of the schema? Assuming I had the previous stored somewhere to compare against a newer version.

**Comment by xfxyjwf** [comment]
There isn't such a tool available as far as I can tell. It sounds useful though.

**Comment by paulolai** [comment]
For anyone else who comes across this question, https://github.com/nilslice/protolock looks like tool you were after.
