### ISSUE TITLE
[C#] Custom factory for nested type

### ISSUE THREAD

**Issue by kkc0923** [google/protobuf#4742]
Hi. I investigated that can Protobuf C# generate all type from user-specific factory funtion.

It seems that Protobuf has already MessageParser<T>(Func<T> factory). But it handles only single type T. If my type T has nested types, I can't specify factory function of nested type:

MyTypeA
{
    MyTypeB fieldB;
    MyTypeC fieldC;
}

How to specify factory function of MyTypeB when using MessageParser<MyTypeA> for fieldB?

Is is need to reuse object for zero-allocation in fast-paced networking game. Thanks.

**Comment by kkc0923** [comment]
Oh, It seems that Protobuf allocate internal stream class at each deserialization call (maybe CodedInputStream?)

Is there any method for zero-allocating serialization/deserialization?

**Comment by anandolee** [comment]
"It seems that Protobuf has already MessageParser(Func factory). But it handles only single type T."  I believe our internal code also use MessageParser and can handle nested types.

" It seems that Protobuf allocate internal stream class at each deserialization call" 
ParseFrom(CodedInputStream input) in MessageParse does not allocate new CodedInputStream:
https://github.com/google/protobuf/blob/47b7d2c7cadf74ceec90fc5042232819cd0dd557/csharp/src/Google.Protobuf/MessageParser.cs#L134
Other Parse methods do allocate new CodedInputStream
