### ISSUE TITLE
Alternative to -I in protoc ?

### ISSUE THREAD

**Issue by simplesteph** [google/protobuf#4743]
Just an idea I have. Wondering the feasibility. Unfortunately I can't really implement this as my cpp knowledge is close to 0. 

I'm wondering if it could be worth using an empty file `__protoroot__` as a self discoverable `-I` flag. 

`__protoroot__` under `src/` would implicitly add `-I src/` as a compiler option and would save a lot of headache to figure out the correct `protoc` command to generate the desired output. 

I believe this would also be nice for IDE in order to verify the correctness of proto files that could be placed anywhere in a project

Thoughts ? Would this create conflicts ?

**Comment by akonradi** [comment]
Just a drive-by comment since I don't have any say in `protoc`, but I don't know how you'd be able to implement this without scanning every directory in the system for the magic `__protoroot__` file unless you restricted the search to ancestor directories only. Otherwise how would `protoc` know where to look for the `__protoroot__` file?

**Comment by simplesteph** [comment]
Any directory while walking from the command to the proto files ?

**Comment by acozzette** [comment]
Unfortunately I think it would be hard to get this to mesh well with the way imports currently work. There has been some related discussion around this on #4737. `protoc` uses the `-I` option to decide where to look for `.proto` files that are passed to it on the command line, so it doesn't even know how to find its first file unless it's already in a `-I` path (the default is `.`). The other thing is that every `.proto` file needs to have a unique path identifying it, so things get confusing pretty quickly if you have one `-I` path that's a descendant of another.

**Comment by simplesteph** [comment]
Sounds good I'll close this then
