### ISSUE TITLE
Issue when there isn't any message but only service

### ISSUE THREAD

**Issue by mwei0210** [google/protobuf#4747]
if there is only service in proto files but not message, js_out would still generate goog.object.extend() which would cause error when compiled.

https://github.com/google/protobuf/blob/ed4321d1cb33199984118d801956822842771e7e/src/google/protobuf/compiler/js/js_generator.cc#L3481

**Comment by acozzette** [comment]
@mwei0210 Thanks for reporting the bug. Would you be interested in sending a pull request with a fix?
