### ISSUE TITLE
Not able to insert code into generated JAVA files.

### ISSUE THREAD

**Issue by albertRCell** [google/protobuf#4752]
Hello,

I'm not sure if this is the right channel to ask this but I've been trying to insert code using the insertion points on my JAVA generated classes and haven't been able to even get the generated classes on my plugin.

Here is what I have so far.

1. My proto file example.proto

```
syntax = "proto3";
enum Greeting {
    NONE = 0;
    MR = 1;
    MRS = 2;
    MISS = 3;
}

message Hello {
    Greeting greeting = 1;
    string name = 2;
}

message Bye {
    string name = 1;
}

option java_multiple_files = true;
```

2. I created a java class for my custom pulgin
```
public class Test {
   /* Code to get generated files from java_out and use the insertion points */
   PluginProtos.CodeGeneratorResponse codeGeneratorResponse = PluginProtos.CodeGeneratorResponse.parseFrom(System.in)
   /* This is creating an empty code GeneratorResponse.... I guess I need the one generated by java_out to then use the insertion points, the problem is that I don't know how to do that...
}
```

3. I then created my bash file to pass in as my plugin to `protoc`
`protoc --java_out=./classes --plugin=protoc-gen-demo=my-plugin --demo_out=. example.proto
`
My `Test.java` class is being executed (I printed some random message to make sure). However, I don't know how to get the `CodeGeneratorResponse` from `java_out` so that I can then use the insert points to add some code. Do you have an example or can you tell me if I'm doing something wrong so far?.

Thanks.

Alberto.

**Comment by acozzette** [comment]
I have never tried using the insertion points myself but I believe the way to do it is to have your plugin read in a CodeGeneratorRequest and output a CodeGeneratorResponse. I don't think your plugin gets to see the original generated code--it just has to produce a response that indicates what text you want to output at a given insertion point: https://github.com/google/protobuf/blob/e264d6bc581481094829478e5d4547dcef35e70e/src/google/protobuf/compiler/plugin.proto#L161

**Comment by albertRCell** [comment]
Hi @acozzette, thanks for the response, I'll try that. 

However, I don't really understand how that's going to work, when I read from CodeGeneratorRequest I don't get the insertion points either, so does that mean I need to know how the insertion points look like beforehand?

Also, my understanding is that to create an insertion point, a File needs to exist to attach that insertion point to it. How can I go about it and write it in the CodeGeneratorResponse if I don't know the name of the class nor the insertion point? Do you have any example that can help me?

**Comment by acozzette** [comment]
Unfortunately I don't have any examples offhand, but I think you do have to know in advance what insertion points will be generated. It would probably be easiest to generate the plain Java code and look at that to get an idea of the insertion points. The class names should be fairly easy to determine based on the package name and message names, which you can get from the CodeGeneratorRequest.

**Comment by albertRCell** [comment]
Okay, I'll try that.
