### ISSUE TITLE
Passing a parameter to my custom protoc plugin

### ISSUE THREAD

**Issue by JonasVautherin** [google/protobuf#4759]
I am creating a custom protoc plugin that I call with:

```
protoc --plugin=protoc-gen-custom=my_plugin.py [...]
```

I have seen that the swift plugin accepts an argument with `--swift_opt`. How can I do that with my custom plugin?

Also, do I have to call it with `protoc-gen-custom`, or is there a way to call it with something like `--myplugin_out=.`, like the other plugins?

**Comment by xfxyjwf** [comment]
Try:
```
protoc --plugin=protoc-gen-custom=my_plugin.py --custom_out=. --custom_opt=your_options
```

You can of course replace "custom" with any other name you want.

**Comment by JonasVautherin** [comment]
Thanks a lot!

I did not realize I could replace "custom" actually, and I did not manage to find the protoc implementation yet, so I have no clue how the command line is parsed :sweat_smile:.

Working perfectly now :-).
