### ISSUE TITLE
C++ compiling error  C2143

### ISSUE THREAD

**Issue by thisisme2017** [google/protobuf#4762]
C++: Microsoft (R) Program Maintenance Utility Version 12.00.21005.1

While nmaking the error below occurs
error log:
json_stream_parser_test.cc
...\protobuf\protobuf-3.5.1\src\google\protobuf\util\internal\json_stream_parser_test.cc : warning C4819: The file contains a character that cannot be represented in the current code page (932). Save the file in Unicode format to prevent data loss
C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\INCLUDE\xlocale(337) : warning C4530: C++ exception handler used, but unwind semantics are not enabled. Specify /EHsc
C:\aworkspace\other\protobuf\protobuf-3.5.1\src\google\protobuf\util\internal\json_stream_parser_test.cc(394) : error C2143: syntax error : missing ';' before '}'

**Comment by xfxyjwf** [comment]
Protobuf source files use utf-8 encoding. You need to change your IDE's encoding accordingly.

**Comment by thisisme2017** [comment]
"nmake unicode=1" does not work. How to change IDE's encoding?

**Comment by acozzette** [comment]
I'm not too familiar with Visual Studio so I'm not sure how to change the encoding. Another workaround you could try would be to just find the non-ASCII character in that file and just delete it.
