### ISSUE TITLE
JS:using Map type happen error on react-native

### ISSUE THREAD

**Issue by linjson** [google/protobuf#4763]
code in react-native:
```js
/**
if I don't use 'google-protobuf' library ,this is work,
but I want to use 'google-protobuf' library on react-naitve,tell me how to do,
I know that change 'for-of' to 'for-in',but 'for-of' is in  react-naitve,
how can i support to for-of in 'google-protobuf' library

**/
var jspb = require('google-protobuf');
var s = new Map();

s.set("a",1);
s.set("b",2);
//happen error in this :for-of
for(let [key,value] of s){
    console.log("==>key:",key)
}
```

**Comment by linjson** [comment]
how remove the global.Symbol when build js

**Comment by acozzette** [comment]
The way to do it would be something like this:
`for (let [key, value] of s.entries()) { ... }`

You could also use the `forEach` method.

What problem are you having with `Symbol`?

**Comment by linjson** [comment]
because `Symbol.iterator="@@iterator"` in react-native and `Symbol.iterator="jscomp_symbol_iterator1" `
in google-protobuf,Symbol.iterator has conflict in this two library,so when using `for-of` happen error
