### ISSUE TITLE
Cannot find configure file in release source code

### ISSUE THREAD

**Issue by deidaraho** [google/protobuf#4767]
Hello,
Due to some problems my Centos system does not have internet access. I am trying to build a release version from source code according to your [c++ installation](https://github.com/google/protobuf/blob/2.7.0/src/README.md) and [protobuf realse](https://github.com/google/protobuf/releases). However, I cannot skip ./autogen.sh since there is no configure file in the package.
Could I ask for some helps? THX in advance.
Bests,
Runxin

**Comment by acozzette** [comment]
2.7 is a somewhat old release at this point so it might be best to upgrade to a newer version. But if you want to build with 2.7, you can just comment out the part of `autogen.sh` that uses the network. It just tries to fetch the gmock library, but you don't need that unless you want to run the tests. Running autogen.sh will then generate the configure script.

**Comment by deidaraho** [comment]
Thanks acozzette, I switched to release version 3.5.1. However, after I comment gmock and run autogen.sh, I faced another issue as,
> configure.ac:93: error: possibly undefined macro: AC_PROG_LIBTOOL
>       If this token and others are legitimate, please use m4_pattern_allow.
>       See the Autoconf documentation.

While I am sure I have libtool installed, since when I run yum install libtool, I got

> Loaded plugins: aliases, downloadonly, fastestmirror, priorities, security
> Loading mirror speeds from cached hostfile
> Setting up Install Process
> Package libtool-2.2.6-15.5.el6.x86_64 already installed and latest version
> Nothing to do
Could I ask for further helps? Thanks so much!

Bests,
Runxin

**Comment by xfxyjwf** [comment]
Do not download "Source code (zip)" or "Source code (tar.gz)". Download protobuf-all-3.6.0.tar.gz:
https://github.com/google/protobuf/releases/download/v3.6.0/protobuf-all-3.6.0.tar.gz

**Comment by elftech** [comment]
> Do not download "Source code (zip)" or "Source code (tar.gz)". Download protobuf-all-3.6.0.tar.gz:
> https://github.com/google/protobuf/releases/download/v3.6.0/protobuf-all-3.6.0.tar.gz

life-saving answer
