### ISSUE TITLE
How to convert value type to an Any property in node.js

### ISSUE THREAD

**Issue by AlonikiX** [google/protobuf#4768]
I have a message which uses an Any property:
message NetworkCommand {
  string command = 1;
  Any paras = 2;
}
`paras` can be a raw value type like integer and string, or a message.

How can I assign an integer or string value directly to the `paras`? And also, how to get the value from the `paras`?

I couldn't find any reference about this, please help.

**Comment by acozzette** [comment]
@AlonikiX You can use the `pack` and `unpack` methods on `Any` to access the stored value. See the test code here for example: https://github.com/google/protobuf/blob/7402555f34bbe04ca20268eff54a026c158087fb/js/binary/proto_test.js#L647

`Any` only stores messages, not primitive types like integers or strings, but to store a primitive type you can just wrap it in one of the wrapper types here: https://github.com/google/protobuf/blob/7402555f34bbe04ca20268eff54a026c158087fb/src/google/protobuf/wrappers.proto#L107

**Comment by RebornTong** [comment]
> message Response {
     string message = 2;
     google.protobuf.Any data = 3;
   }


node.js client receive a response, which is `var rsp`, and try to `rsp.data.unpack("balabala", "balabala")` , and throw exception, that: unpack method is not found
