### ISSUE TITLE
global std::once_flag variables don't work with Visual Studio

### ISSUE THREAD

**Issue by xfxyjwf** [google/protobuf#4773]
Symptom: statically built protoc binary check-fails.
https://github.com/google/protobuf/issues/4409
```
[libprotobuf FATAL D:\Google-Protobuf\src\src\google\protobuf\generated_message_reflection.cc:2372] CHECK failed: file != NULL: 
```
Cause:
Visual studio compiler bug:
https://developercommunity.visualstudio.com/content/problem/262083/compiler-emits-dynamic-initializer-for-variable-wi.html

Similar bug: https://developercommunity.visualstudio.com/content/problem/1044/compiler-emits-dynamic-initializer-for-constexpr-v.html

The compiler generates dynamic-initialization code for global std::once_flag variables even though the constructor of once_flag is constexpr. As a result, the following code is broken:
https://github.com/google/protobuf/blob/master/src/google/protobuf/descriptor.cc#L1343-L1362 
```
GOOGLE_PROTOBUF_DECLARE_ONCE(generated_pool_init_);
static void InitGeneratedPool() {
  generated_database_ = new EncodedDescriptorDatabase;
  generated_pool_ = new DescriptorPool(generated_database_);
  generated_pool_->InternalSetLazilyBuildDependencies();
}
void InitGeneratedPoolOnce() {
  ::google::protobuf::GoogleOnceInit(&generated_pool_init_, &InitGeneratedPool);
}
```

1. InitGeneratedPoolOnce() is called before generated_pool_init_ is dynamically initialized. It will call InitGeneratedPool() and create EncodeDescriptorDatabase/DescriptorPool for the first time.
2. dynamical initialization of generated_pool_init_ happens and it simply zeros the variable's content.
3. InitGeneratedPoolOnce() is called again and it calls InitGeneratedPool() again which creates new EncodedDescriptorDatabase/DescriptorPool for the second time.

Anything registered with the descriptordatabase/pool created in (1) will get lost after (3), and as a result descriptors that should already be in the global pool appear missing and this triggers the following check failure:
https://github.com/google/protobuf/blob/master/src/google/protobuf/generated_message_reflection.cc#L2370-L2372
```
  const ::google::protobuf::FileDescriptor* file =
      ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(filename);
  GOOGLE_CHECK(file != NULL);
```
We can workaround the problem by moving the global once_flag into a static variable inside the init function:
```
void InitGeneratedPoolOnce() {
  static ::google::protobuf::ProtobufOnceType generated_pool_init_;
  ::google::protobuf::GoogleOnceInit(&generated_pool_init_, &InitGeneratedPool);
}
```
This way, the variable is guaranteed to be initialized before GoogleOnceInit() and it appears to work with Visual Studio 2017.

**Comment by nikhilpothuru** [comment]
Hi, This is my first time trying to contribute to an open source project. I am looking to help out with any C++ or Python issues. It would be great to get some help starting off. I've gone through the Developer Guide and Protocol Buffer Basics: C++ to prepare. Thanks!

**Comment by xfxyjwf** [comment]
@nikhilpothuru Thanks for offering help! This issue here is probably not a great place to start though. I think it's probably better to start with some simple cleanups to get yourself more familiar with the protobuf build/development environment.

**Comment by nikhilpothuru** [comment]
Hi! Thank you for the quick reply. Is there a specific cleanup issue you can point me to? I'm looking through the issues, but it is a bit overwhelming since I don't know where to start. Thanks!

**Comment by remoe** [comment]
I've tested with VS 2017 (15.7.4) DEBUG and **protobuf 3.6.0**:

-GVisual Studio 15 Win64 -DCMAKE_SYSTEM_VERSION=8.1 -DBUILD_SHARED_LIBS=ON". 
The protoc executable crashes on tests:

```log
   8>Done Building Project "D:\sdk\_build\win_x86_64\protobuf-3.6.0-debug\protobuf.git\_build\test_plugin.vcxproj" (default targets).
    14>d:\apps\vs2017\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(171,5): error MSB6006: "cmd.exe" exited with code 3. [D:\sdk\_build\win_x86_64\protobuf-3.6.0-debug\protobuf.git\
       _build\lite-arena-test.vcxproj]
    14>Done Building Project "D:\sdk\_build\win_x86_64\protobuf-3.6.0-debug\protobuf.git\_build\lite-arena-test.vcxproj" (default targets) -- FAILED.
     9>d:\apps\vs2017\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(171,5): error MSB6006: "cmd.exe" exited with code 3. [D:\sdk\_build\win_x86_64\protobuf-3.6.0-debug\protobuf.git\
       _build\tests.vcxproj]
     9>Done Building Project "D:\sdk\_build\win_x86_64\protobuf-3.6.0-debug\protobuf.git\_build\tests.vcxproj" (default targets) -- FAILED.
     3>Project "D:\sdk\_build\win_x86_64\protobuf-3.6.0-debug\protobuf.git\_build\ALL_BUILD.vcxproj" (3) is building "D:\sdk\_build\win_x86_64\protobuf-3.6.0-debug\protobuf.git\_build\lite
       -test.vcxproj" (6) on node 1 (default targets).
     6>InitializeBuildStatus:
         Touching "lite-test.dir\Debug\lite-test.tlog\unsuccessfulbuild".
       CustomBuild:
         Generating D:/sdk/_build/win_x86_64/protobuf-3.6.0-debug/protobuf.git/src/google/protobuf/map_lite_unittest.pb.cc
         [libprotobuf FATAL d:\sdk\_build\win_x86_64\protobuf-3.6.0-debug\protobuf.git\src\google\protobuf\message.cc:346] File appears to be in generated pool but wasn't registered: googl
         e/protobuf/descriptor.proto
     6>d:\apps\vs2017\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(171,5): error MSB6006: "cmd.exe" exited with code 3. [D:\sdk\_build\win_x86_64\protobuf-3.6.0-debug\protobuf.git\
       _build\lite-test.vcxproj]

   8>Done Building Project "D:\sdk\_build\win_x86_64\protobuf-3.6.0-debug\protobuf.git\_build\test_plugin.vcxproj" (default targets).
    14>d:\apps\vs2017\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(171,5): error MSB6006: "cmd.exe" exited with code 3. [D:\sdk\_build\win_x86_64\protobuf-3.6.0-debug\protobuf.git\
       _build\lite-arena-test.vcxproj]
    14>Done Building Project "D:\sdk\_build\win_x86_64\protobuf-3.6.0-debug\protobuf.git\_build\lite-arena-test.vcxproj" (default targets) -- FAILED.
     9>d:\apps\vs2017\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(171,5): error MSB6006: "cmd.exe" exited with code 3. [D:\sdk\_build\win_x86_64\protobuf-3.6.0-debug\protobuf.git\
       _build\tests.vcxproj]
     9>Done Building Project "D:\sdk\_build\win_x86_64\protobuf-3.6.0-debug\protobuf.git\_build\tests.vcxproj" (default targets) -- FAILED.
     3>Project "D:\sdk\_build\win_x86_64\protobuf-3.6.0-debug\protobuf.git\_build\ALL_BUILD.vcxproj" (3) is building "D:\sdk\_build\win_x86_64\protobuf-3.6.0-debug\protobuf.git\_build\lite
       -test.vcxproj" (6) on node 1 (default targets).
     6>InitializeBuildStatus:
         Touching "lite-test.dir\Debug\lite-test.tlog\unsuccessfulbuild".
       CustomBuild:
         Generating D:/sdk/_build/win_x86_64/protobuf-3.6.0-debug/protobuf.git/src/google/protobuf/map_lite_unittest.pb.cc
         [libprotobuf FATAL d:\sdk\_build\win_x86_64\protobuf-3.6.0-debug\protobuf.git\src\google\protobuf\message.cc:346] File appears to be in generated pool but wasn't registered: googl
         e/protobuf/descriptor.proto
     6>d:\apps\vs2017\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(171,5): error MSB6006: "cmd.exe" exited with code 3. [D:\sdk\_build\win_x86_64\protobuf-3.6.0-debug\protobuf.git\
       _build\lite-test.vcxproj]

```

**Comment by Renshk** [comment]
This way, the initialization of generated_pool_init_ is not thread-safe in the InitGeneratedPoolOnce function.

**Comment by Renshk** [comment]
GeneratedMessageFactory::singleton function have the same issue.

**Comment by xfxyjwf** [comment]
@Renshk Why is it not thread-safe? I'm pretty sure C++11 guarantees static local variable to be initialized thread-safely.

**Comment by wheezil** [comment]
Greetings... I ran into this error (well, actually #4679) trying to build protobuf libraries for Windows using VS2017.  I found that copying the win32 distribution of protoc.exe over the built one allowed the build to complete successfully.  However, nmake check tests fail with similar errors.

Given that I have VS2017 and would like to proceed with a project, what is the best advice for working around the problem, until either VS2017 or protobuf arrives at a solution?
Thanks
john

**Comment by xfxyjwf** [comment]
@wheezil The bug only happens in debug build so you can workaround it by using the release build version of protobuf. The pre-built binaries published by us also do not have this problem because they are release builds.

**Comment by wheezil** [comment]
Thanks! I will just go with the pre-built binaries.

**Comment by snnn** [comment]
Support for constexpr Static Initializers only started from VS 2015 update 1, it's a relatively new.  You may use the Windows API: INIT_ONCE, which works for all VS versions.
