### ISSUE TITLE
3.6.0 and 3.6.0.1 status?

### ISSUE THREAD

**Issue by ilovezfs** [google/protobuf#4781]
https://github.com/google/protobuf/releases/latest points to 3.5.1
https://pypi.org/project/protobuf/ points to 3.6.0
https://github.com/google/protobuf/releases shows 3.6.0 and 3.6.0.1

What is the current stable release here? What should we be distributing in [Homebrew](https://github.com/Homebrew/homebrew-core/blob/master/Formula/protobuf.rb#L4)?

**Comment by sigiesec** [comment]
Are there any release notes for 3.6.0(.1)?

**Comment by xfxyjwf** [comment]
3.6.0 is the latest release:
https://github.com/google/protobuf/releases/tag/v3.6.0
