### ISSUE TITLE
[PHP] Segfaults with a wrong autoloader for GPBMetadata

### ISSUE THREAD

**Issue by tmatsuo** [google/protobuf#4793]
**What version of protobuf and what language are you using?**
Version: v3.6.0
Language: PHP
on glinux workstation

You can reproduce this by fetching a branch:

```sh
$ git clone -b tts https://github.com/tmatsuo/google-cloud-php.git
$ cd google-cloud-php/TextToSpeech
$ composer update
$ cd ..
$ phpunit --bootstrap TextToSpeech/vendor/autoload.php \
  TextToSpeech/tests/Unit/V1/TextToSpeechClientTest.php
Segmentation fault (core dumped)
```
```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007fb82e4f0c08 in message_free (object=0x7fb82cc73650) at /usr/local/google/home/tmatsuo/.phpbrew/build/php-7.1.18/ext/protobuf/message.c:84
84        if (*(void**)intern->data != NULL) {
```

Other simple repro code you can put into TextToSpeech directory: 
```php
<?php

require __DIR__ . '/vendor/autoload.php';

use Google\Cloud\TextToSpeech\V1\AudioConfig;
use Google\Cloud\TextToSpeech\V1\AudioEncoding;
use Google\Cloud\TextToSpeech\V1\SynthesisInput;
use Google\Cloud\TextToSpeech\V1\TextToSpeechClient;
use Google\Cloud\TextToSpeech\V1\VoiceSelectionParams;


$textToSpeechClient = new TextToSpeechClient();

$input = new SynthesisInput();
$input->setText('Japan national team won against Columbia!');
$voice = new VoiceSelectionParams();
$voice->setLanguageCode('en-US');
$audioConfig = new AudioConfig();
$audioConfig->setAudioEncoding(AudioEncoding::MP3);

$resp = $textToSpeechClient->synthesizeSpeech($input, $voice, $audioConfig);

```

**Comment by TeBoring** [comment]
In TextToSpeech/src/V1/ListVoicesResponse.php, line 26, it's referencing class in \GPBMetadata. However, metadata files are put in metadata. My guess is ```php_metadata_namespace``` was added to proto file after the code was initially generated. After  ```php_metadata_namespace``` was added, other generated code were not updated.

**Comment by tmatsuo** [comment]
Thanks! Here is what I found out so far.

The proto file:
https://github.com/googleapis/googleapis/blob/master/google/cloud/texttospeech/v1/cloud_tts.proto

It doesn't have `php_metadata_namespace`.

The name resolution in PHP land is done by the autoloader, and the composer.json has the configuration for it:
https://github.com/tmatsuo/google-cloud-php/blob/tts/TextToSpeech/composer.json#L9

```composer.json
            "GPBMetadata\\Google\\Cloud\\TextToSpeech\\": "metadata"
```

and the code is using lower case namespace:

```php
        \GPBMetadata\Google\Cloud\Texttospeech\V1\CloudTts::initOnce();
```

So very likely the right namespace configuration will fix the issue. I'll try that tomorrow.

**Comment by tmatsuo** [comment]
Yes, the correct path for the autoloader fixed the issue.

I still think the current behavior is not ideal though.

**Comment by TeBoring** [comment]
I think the user is supposed to use ```php_metadata_namespace```
