### ISSUE TITLE
protobuf 3.6.0 build with error: undefined reference

### ISSUE THREAD

**Issue by lxl910915** [google/protobuf#4831]
protobuf-3.6.0
g++-5.4

When we run `c++ -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wl,-Bsymbolic-functions -Wl,-z,relro -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/horovod/common/common.o build/temp.linux-x86_64-2.7/horovod/common/mpi_message.o build/temp.linux-x86_64-2.7/horovod/common/operations.o build/temp.linux-x86_64-2.7/horovod/common/timeline.o build/temp.linux-x86_64-2.7/horovod/common/comm.pb.o build/temp.linux-x86_64-2.7/horovod/common/ps_utils.o build/temp.linux-x86_64-2.7/horovod/common/zmq_common_test.o build/temp.linux-x86_64-2.7/horovod/common/ps_client.o -o build/lib.linux-x86_64-2.7/horovod/common/mpi_lib.so -I/usr/local/include -pthread -Wl,-rpath -Wl,/usr/local/lib -Wl,--enable-new-dtags -L/usr/local/lib -lmpi -lpthread horovod/common/libzmq.a **-lprotobuf -lstdc++ /usr/local/lib/libprotobuf.a**` command, it print the following errors:

`build/temp.linux-x86_64-2.7/horovod/common/comm.pb.o: In function `Comm::CtrlHeader::SerializeWithCachedSizes(google::protobuf::io::CodedOutputStream*) const':
/psserver/horovod/horovod/common/comm.pb.cc:553: undefined reference to `google::protobuf::internal::WireFormatLite::WriteString(int, std::string const&, google::protobuf::io::CodedOutputStream*)'
/psserver/horovod/horovod/common/comm.pb.cc:573: undefined reference to `google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(int, std::string const&, google::protobuf::io::CodedOutputStream*)'
/psserver/horovod/horovod/common/comm.pb.cc:563: undefined reference to `google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(int, std::string const&, google::protobuf::io::CodedOutputStream*)'
build/temp.linux-x86_64-2.7/horovod/common/comm.pb.o: In function `google::protobuf::internal::WireFormatLite::WriteStringToArray(int, std::string const&, unsigned char*)':
/usr/local/include/google/protobuf/wire_format_lite_inl.h:876: undefined reference to `google::protobuf::io::CodedOutputStream::WriteStringWithSizeToArray(std::string const&, unsigned char*)'
/usr/local/include/google/protobuf/wire_format_lite_inl.h:876: undefined reference to `google::protobuf::io::CodedOutputStream::WriteStringWithSizeToArray(std::string const&, unsigned char*)'
/usr/local/include/google/protobuf/wire_format_lite_inl.h:876: undefined reference to `google::protobuf::io::CodedOutputStream::WriteStringWithSizeToArray(std::string const&, unsigned char*)'
/usr/local/include/google/protobuf/wire_format_lite_inl.h:876: undefined reference to `google::protobuf::io::CodedOutputStream::WriteStringWithSizeToArray(std::string const&, unsigned char*)'
build/temp.linux-x86_64-2.7/horovod/common/comm.pb.o: In function `Comm::DataHeader::SerializeWithCachedSizes(google::protobuf::io::CodedOutputStream*) const':
/psserver/horovod/horovod/common/comm.pb.cc:1076: undefined reference to `google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(int, std::string const&, google::protobuf::io::CodedOutputStream*)'
build/temp.linux-x86_64-2.7/horovod/common/comm.pb.o: In function `google::protobuf::internal::ArenaStringPtr::UnsafeSetDefault(std::string const*)':
/usr/local/include/google/protobuf/arenastring.h:251: undefined reference to `google::protobuf::internal::fixed_address_empty_string'
build/temp.linux-x86_64-2.7/horovod/common/comm.pb.o: In function `google::protobuf::internal::ArenaStringPtr::DestroyNoArena(std::string const*)':
/usr/local/include/google/protobuf/arenastring.h:321: undefined reference to `google::protobuf::internal::fixed_address_empty_string'
build/temp.linux-x86_64-2.7/horovod/common/comm.pb.o: In function `google::protobuf::internal::ArenaStringPtr::UnsafeSetDefault(std::string const*)':
/usr/local/include/google/protobuf/arenastring.h:251: undefined reference to `google::protobuf::internal::fixed_address_empty_string'
build/temp.linux-x86_64-2.7/horovod/common/comm.pb.o: In function `google::protobuf::internal::ArenaStringPtr::DestroyNoArena(std::string const*)':
/usr/local/include/google/protobuf/arenastring.h:322: undefined reference to `google::protobuf::internal::fixed_address_empty_string'
build/temp.linux-x86_64-2.7/horovod/common/comm.pb.o: In function `google::protobuf::internal::ArenaStringPtr::SetNoArena(std::string const*, std::string const&)':
/usr/local/include/google/protobuf/arenastring.h:263: undefined reference to `google::protobuf::internal::fixed_address_empty_string'
build/temp.linux-x86_64-2.7/horovod/common/comm.pb.o:/usr/local/include/google/protobuf/arenastring.h:263: more undefined references to `google::protobuf::internal::fixed_address_empty_string' follow
build/temp.linux-x86_64-2.7/horovod/common/comm.pb.o: In function `google::protobuf::internal::WireFormatLite::ReadString(google::protobuf::io::CodedInputStream*, std::string*)':
/usr/local/include/google/protobuf/wire_format_lite.h:881: undefined reference to `google::protobuf::internal::WireFormatLite::ReadBytes(google::protobuf::io::CodedInputStream*, std::string*)'
build/temp.linux-x86_64-2.7/horovod/common/comm.pb.o: In function `google::protobuf::internal::ArenaStringPtr::UnsafeSetDefault(std::string const*)':
/usr/local/include/google/protobuf/arenastring.h:251: undefined reference to `google::protobuf::internal::fixed_address_empty_string'
/usr/local/include/google/protobuf/arenastring.h:251: undefined reference to `google::protobuf::internal::fixed_address_empty_string'
build/temp.linux-x86_64-2.7/horovod/common/comm.pb.o: In function `google::protobuf::internal::ArenaStringPtr::SetNoArena(std::string const*, std::string const&)':
/usr/local/include/google/protobuf/arenastring.h:263: undefined reference to `google::protobuf::internal::fixed_address_empty_string'
build/temp.linux-x86_64-2.7/horovod/common/comm.pb.o: In function `google::protobuf::internal::ArenaStringPtr::MutableNoArena(std::string const*)':
/usr/local/include/google/protobuf/arenastring.h:285: undefined reference to `google::protobuf::internal::fixed_address_empty_string'
build/temp.linux-x86_64-2.7/horovod/common/comm.pb.o: In function `google::protobuf::internal::WireFormatLite::ReadString(google::protobuf::io::CodedInputStream*, std::string*)':
/usr/local/include/google/protobuf/wire_format_lite.h:881: undefined reference to `google::protobuf::internal::WireFormatLite::ReadBytes(google::protobuf::io::CodedInputStream*, std::string*)'
build/temp.linux-x86_64-2.7/horovod/common/comm.pb.o: In function `protobuf_comm_2eproto::protobuf_AssignDescriptors()':
/psserver/horovod/horovod/common/comm.pb.cc:162: undefined reference to `google::protobuf::internal::AssignDescriptors(std::string const&, google::protobuf::internal::MigrationSchema const*, google::protobuf::Message const* const*, unsigned int const*, google::protobuf::Metadata*, google::protobuf::EnumDescriptor const**, google::protobuf::ServiceDescriptor const**)'
build/temp.linux-x86_64-2.7/horovod/common/comm.pb.o: In function `protobuf_comm_2eproto::AddDescriptorsImpl()':
/psserver/horovod/horovod/common/comm.pb.cc:200: undefined reference to `google::protobuf::MessageFactory::InternalRegisterGeneratedFile(char const*, void (*)(std::string const&))'
build/temp.linux-x86_64-2.7/horovod/common/comm.pb.o:(.data.rel.ro._ZTVN4Comm10CtrlHeaderE[_ZTVN4Comm10CtrlHeaderE]+0x20): undefined reference to `google::protobuf::Message::GetTypeName() const'
build/temp.linux-x86_64-2.7/horovod/common/comm.pb.o:(.data.rel.ro._ZTVN4Comm10CtrlHeaderE[_ZTVN4Comm10CtrlHeaderE]+0x58): undefined reference to `google::protobuf::Message::InitializationErrorString() const'
build/temp.linux-x86_64-2.7/horovod/common/comm.pb.o:(.data.rel.ro._ZTVN4Comm10DataHeaderE[_ZTVN4Comm10DataHeaderE]+0x20): undefined reference to `google::protobuf::Message::GetTypeName() const'
build/temp.linux-x86_64-2.7/horovod/common/comm.pb.o:(.data.rel.ro._ZTVN4Comm10DataHeaderE[_ZTVN4Comm10DataHeaderE]+0x58): undefined reference to `google::protobuf::Message::InitializationErrorString() const'
build/temp.linux-x86_64-2.7/horovod/common/comm.pb.o:(.data.rel.ro._ZTVN4Comm6HeaderE[_ZTVN4Comm6HeaderE]+0x20): undefined reference to `google::protobuf::Message::GetTypeName() const'
build/temp.linux-x86_64-2.7/horovod/common/comm.pb.o:(.data.rel.ro._ZTVN4Comm6HeaderE[_ZTVN4Comm6HeaderE]+0x58): undefined reference to `google::protobuf::Message::InitializationErrorString() const'
build/temp.linux-x86_64-2.7/horovod/common/zmq_common_test.o: In function `ps::ZMQClient::Send(Comm::Header const&, void const*)':
/psserver/horovod/horovod/common/zmq_common.hpp:110: undefined reference to `google::protobuf::MessageLite::SerializeToString(std::string*) const'
build/temp.linux-x86_64-2.7/horovod/common/zmq_common_test.o: In function `ps::ZMQServer::Send(std::string const&, Comm::Header const&, void const*)':
/psserver/horovod/horovod/common/zmq_common.hpp:335: undefined reference to `google::protobuf::MessageLite::SerializeToString(std::string*) const'
build/temp.linux-x86_64-2.7/horovod/common/ps_client.o: In function `ps::ZMQClient::Send(Comm::Header const&, void const*)':
/psserver/horovod/horovod/common/zmq_common.hpp:110: undefined reference to `google::protobuf::MessageLite::SerializeToString(std::string*) const'
/psserver/horovod/horovod/common/zmq_common.hpp:110: undefined reference to `google::protobuf::MessageLite::SerializeToString(std::string*) const'
build/temp.linux-x86_64-2.7/horovod/common/ps_client.o: In function `google::protobuf::internal::ArenaStringPtr::SetNoArena(std::string const*, std::string const&)':
/usr/local/include/google/protobuf/arenastring.h:263: undefined reference to `google::protobuf::internal::fixed_address_empty_string'
build/temp.linux-x86_64-2.7/horovod/common/ps_client.o: In function `ps::ZMQClient::Send(Comm::Header const&, void const*)':
/psserver/horovod/horovod/common/zmq_common.hpp:110: undefined reference to `google::protobuf::MessageLite::SerializeToString(std::string*) const'
build/temp.linux-x86_64-2.7/horovod/common/ps_client.o: In function `google::protobuf::internal::ArenaStringPtr::SetNoArena(std::string const*, std::string const&)':
/usr/local/include/google/protobuf/arenastring.h:263: undefined reference to `google::protobuf::internal::fixed_address_empty_string'
build/temp.linux-x86_64-2.7/horovod/common/ps_client.o: In function `ps::ZMQClient::Send(Comm::Header const&, void const*)':
/psserver/horovod/horovod/common/zmq_common.hpp:110: undefined reference to `google::protobuf::MessageLite::SerializeToString(std::string*) const'
build/temp.linux-x86_64-2.7/horovod/common/ps_client.o: In function `google::protobuf::internal::ArenaStringPtr::SetNoArena(std::string const*, std::string const&)':
/usr/local/include/google/protobuf/arenastring.h:263: undefined reference to `google::protobuf::internal::fixed_address_empty_string'
build/temp.linux-x86_64-2.7/horovod/common/ps_client.o: In function `ps::ZMQClient::Send(Comm::Header const&, void const*)':
/psserver/horovod/horovod/common/zmq_common.hpp:110: undefined reference to `google::protobuf::MessageLite::SerializeToString(std::string*) const'
build/temp.linux-x86_64-2.7/horovod/common/ps_client.o: In function `google::protobuf::internal::ArenaStringPtr::SetNoArena(std::string const*, std::string const&)':
/usr/local/include/google/protobuf/arenastring.h:263: undefined reference to `google::protobuf::internal::fixed_address_empty_string'
build/temp.linux-x86_64-2.7/horovod/common/ps_client.o: In function `ps::ZMQClient::Send(Comm::Header const&, void const*)':
/psserver/horovod/horovod/common/zmq_common.hpp:110: undefined reference to `google::protobuf::MessageLite::SerializeToString(std::string*) const'
/psserver/horovod/horovod/common/zmq_common.hpp:110: undefined reference to `google::protobuf::MessageLite::SerializeToString(std::string*) const'
collect2: error: ld returned 1 exit status`

If we remove '-lprotobuf -lstdc++ /usr/local/lib/libprotobuf.a', it works well. Can somebody provide any idea?

**Comment by lxl910915** [comment]
We change protobuf-3.4.0 and g++-4.7, it works well. But we don't know why

**Comment by acozzette** [comment]
@lxl910915 I'm glad it's working now! I'm not sure what the problem was either, but one thing that could be problematic is passing both `-lprotobuf` and `/usr/local/lib/libprotobuf.a` to `g++`. It seems to me that you would want to pass one or the other but not both--perhaps the linker was getting confused because it was processing `libprotobuf.a` twice.

**Comment by PlutusCN** [comment]
I met these errors, but I also don't know the reason and fix them.  @acozzette Can you give me the detailed solution ? Thanks a lot !

**Comment by acozzette** [comment]
@PlutusCN Could you provide some more details about your build setup? In general these kinds of errors would suggest that the linker is unable to find libprotobuf, but without more information it's hard to figure out the exact reason for that.

**Comment by PlutusCN** [comment]
#5098  @acozzette

**Comment by std-vector** [comment]
I got the same errors after I upgraded to the newest GCC 9.2.0 and CMake 3.16.2. But everything went well with GCC 4.8.5 and CMake 3.1.3. 
Any suggestions ?

**Comment by R030t1** [comment]
Issue is likely still relevant, something happened to my build and now it doesn't work with basically every protobuf symbol undefined.
