### ISSUE TITLE
I am facing problem  in communication between C++ and javascript.

### ISSUE THREAD

**Issue by goel-sunny** [google/protobuf#4834]
Hi ,

I am creating the message in c++ and then serialseToOstream and convert that oStream into char* and pass it to the javascript (i.e. front end side ) Now at front end side I am doing ref.reinterpret( char * , size)

and convert it into BUffer then trying to pass that buffer to deserialiseBinary(Buffer) function and getting an error :- 

C:\angular\buffer\jsInterface\node_modules\google-protobuf\google-protobuf.js:98
goog.string.splitLimit=function(a,b,c){a=a.split(b);for(var d=[];0<c&&a.length;)d.push(a.shift()),c--;a.length&&d.push(a.join(b));return d};goog.string.editDistance=function(a,b){var c=[],d=[];if(a==b)return 0;if(!a.length||!b.length)return Math.max(a.length,
e]=e;for(e=0;e<a.length;e++){d[0]=e+1;for(var f=0;f<b.length;f++)d[f+1]=Math.min(d[f]+1,c[f+1]+1,c[f]+Number(a[e]!=b[f]));for(f=0;f<c.length;f++)c[f]=d[f]}return d[b.length]};goog.asserts={};goog.asserts.ENABLE_ASSERTS=goog.DEBUG;goog.asserts.AssertionError=f
r.call(this,goog.string.subs.apply(null,b));b.shift();this.messagePattern=a};goog.inherits(goog.asserts.AssertionError,goog.debug.Error);goog.asserts.AssertionError.prototype.name="AssertionError";goog.asserts.DEFAULT_ERROR_HANDLER=function(a){throw a;};goog.
T_ERROR_HANDLER;

AssertionError: Assertion failed
    at new goog.asserts.AssertionError (C:\angular\buffer\jsInterface\node_modules\google-protobuf\google-protobuf.js:98:603)
    at Object.goog.asserts.doAssertFailure_ (C:\angular\buffer\jsInterface\node_modules\google-protobuf\google-protobuf.js:99:126)
    at Object.goog.asserts.assert (C:\angular\buffer\jsInterface\node_modules\google-protobuf\google-protobuf.js:99:385)
    at jspb.BinaryReader.readInt32 (C:\angular\buffer\jsInterface\node_modules\google-protobuf\google-protobuf.js:349:371)
    at Function.proto.example.Sample.deserializeBinaryFromReader (C:\angular\buffer\jsInterface\sample_pb.js:105:49)
    at Function.proto.example.Sample.deserializeBinary (C:\angular\buffer\jsInterface\sample_pb.js:82:31)
    at Object.<anonymous> (C:\angular\buffer\jsInterface\jsinterface.js:23:25)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)

Can any body help me in getting out of this issue or suggest me some other way to do this .

**Comment by TeBoring** [comment]
Can you provide the text/json format of encoded data.

**Comment by goel-sunny** [comment]
you mean .proto file or callled schema  .

**Comment by TeBoring** [comment]
Proto definition and what’s set in data.

**Comment by goel-sunny** [comment]
Proto defination is 

syntax="proto3" ;
message  Sample {
    string name;
    int32  age ;
};

I used SerialiseToArray( void * , size )  when i pass char * in this it runs fine but in case of int * pointer it  fails i  get null message at javascript side .

But its defination says you can pass any type pointer that doesn't matter but i get exceptionally behaviour.

**Comment by TeBoring** [comment]
I don't get you. Why do you need to put int*?

**Comment by TeBoring** [comment]
what's the serialized result?

**Comment by TeBoring** [comment]
closed for now. If there is still problem, feel free to reopen.

**Comment by shenaniganfiasco** [comment]
I have the same issue, i.e.

at jspb.BinaryReader.readInt32
at proto.com.org.myproto.Time.deserializeBinaryFromReader


proto (condensed):
`message MyMsg
{
	enum MessageType 
	{
		Request  = 1; 
		Response = 2;
		Ping     = 3; 
		...
		SubMsg   = 38;
	}

	optional MessageType msgType = 1 [default = Request];
	optional Time        t1      = 2;
	optional Time        t2      = 3;
	...
	repeated Cmd         cmd     = 41;
	optional com.org.myproto.extension.SubMsg sub = 42;
}`

serialized message (JS binary):
`[8,1,26,18,8,1,18,8,97,99,99,101,112,116,101,100,26,4,49,51,51,55]`
