### ISSUE TITLE
Ruby: Convert Protocol::MyType to byte[]

### ISSUE THREAD

**Issue by aniketdivekar** [google/protobuf#4837]
Hi,
How can I convert the protobuf object of custom type to byte array?
I have this autogenerated module called protocol
```
module ProtoCol
    MyType = Google::Protobuf::DescriptorPool.generated_pool.lookup("protocol.MyType").msgclass
end
```
how can I get byte array of Protocol::MyType object?

**Comment by TeBoring** [comment]
I don't understand your question. What do you mean by converting to byte[]. Encode?

**Comment by aniketdivekar** [comment]
@TeBoring Closing it. I had to do `object.to_proto.to_s`.
