### ISSUE TITLE
Generate js file from proto file with protoc v2.6.1

### ISSUE THREAD

**Issue by ithillel-aminev** [google/protobuf#4840]
**What version of protobuf and what language are you using?**
Version: v2.6.1
Language: JavaScript

**What operating system (Linux, Windows, ...) and version?**
Ubuntu Linux

**What runtime / compiler are you using (e.g., python version or gcc version)**
-

**What did you do?**
1. open my bash console
2. enter protoc --proto_path=src --js_out=library=whizz/ponycopter,binary:build/gen src/foo.proto src/bar/baz.proto from https://developers.google.com/protocol-buffers/docs/reference/javascript-generated 
3. See error: protoc-gen-js: program not found or is not executable
--js_out: protoc-gen-js: Plugin failed with status code 1.

**What did you expect to see**
a .js file generated from .proto 

**What did you see instead?**
an error 
error: protoc-gen-js: program not found or is not executable
--js_out: protoc-gen-js: Plugin failed with status code 1.

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Anything else we should know about your project / environment**
Usage of v2.6.1 is the requirement

**Comment by acozzette** [comment]
We added support for JS in the 3.0 release, so unfortunately it's not possible to use JavaScript with 2.6.1.

**Comment by ithillel-aminev** [comment]
It would be great to mention that version restriction on the official page https://developers.google.com/protocol-buffers/docs/reference/javascript-generated
