### ISSUE TITLE
为什么iOS序列化之后的数据跟Android的结果不一致？

### ISSUE THREAD

**Issue by SYJshang** [google/protobuf#4842]

**Comment by acgtun** [comment]
it is better to give an example.

**Comment by SYJshang** [comment]
我在iOS端序列化出来之后的数据为 4808e20f 12114b4d 4c384630 30393143 43323446 4441311a 304f2e1c e9996fe5 09429c92 3f67ebc4 af163709 9aef1bec a5ce694c d6e2bc47 0ce23a17 5d6e6116 e7f14551 1960e244 d4
而安卓那边序列化之后的是08e20f12114b4d4c38463030393143433234464441311a304f2e1ce9996fe509429c923f67ebc4af1637099aef1beca5ce694cd6e2bc470ce23a175d6e6116e7f145511960e244d4这个
前边会多出一个48。在嵌入式那边认证的是安卓的是正确的。我怀疑会不会是protobuf结构中可选值在不传的情况下不同平台会有不同的处理方式。
但是我不知道怎么去解决?

**Comment by taoyq1988** [comment]
give the origin data will better
