### ISSUE TITLE
Getting `libprotobuf.la` is not a valid libtool archive

### ISSUE THREAD

**Issue by uds5501** [google/protobuf#4851]
I was building from source according to the C++ installation instructions as describe [here](https://github.com/google/protobuf/blob/master/src/README.md) when I encountered this error.

**Cloned**: `master` branch
**OS**: Ubuntu 16.04.4 LTS
**Command**: `make`

**Error Log**
```
/bin/sed: can't read clones/Google/protobuf/src/libprotobuf.la: No such file or directory
libtool:   error: 'clones/Google/protobuf/src/libprotobuf.la' is not a valid libtool archive
Makefile:2638: recipe for target 'libprotoc.la' failed
make[2]: *** [libprotoc.la] Error 1
make[2]: Leaving directory '/home/uddeshya/Desktop/git clones/Google/protobuf/src'
Makefile:1541: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/uddeshya/Desktop/git clones/Google/protobuf'
Makefile:1448: recipe for target 'all' failed
make: *** [all] Error 2
```

How do I resolve this error?

**Comment by acozzette** [comment]
@uds5501 It looks to me like we must have some logic somewhere that can't handle spaces in file names, because I see you're building within a directory called `git clones` but the error message just refers to `clones/Google/...`. Ideally our build would be able to handle this but probably the easier fix would be to just rename your `git clones` directory as `git_clones`.

**Comment by Stokestack** [comment]
Still a problem in 3.7.1

**Comment by isaac-philip** [comment]
> This doesn't appear to be fixed... just got exactly the same problem, apparently for the same reason.
> 
> It also continues to fail when the source tree is moved to the drive root, with no spaces in the path. My old path included "open source" but now I'm building from
> /Volumes/software/protobuf-3.6.1/objectivec/DevTools
> 
> And the error I'm getting is
> cannot find the library 'source/Mac/protobuf-3.6.1/src/libprotobuf.la' or unhandled argument 'source/Mac/protobuf-3.6.1/src/libprotobuf.la'
> 
> So it's still (and incorrectly) referring to a fragment of the old "open source" path. Perhaps it should be doing a clean. Should I re-file this as a new bug? I don't see an indication of why this was closed. Thanks.

I also faced similar issue, but,

Rather than building on MacOSx we can attempt to use the binary also such as at -> https://github.com/protocolbuffers/protobuf/releases/download/v3.9.0/protoc-3.9.0-osx-x86_64.zip

**Comment by acozzette** [comment]
This seems to be a known issue with libtool: https://lists.gnu.org/archive/html/bug-libtool/2008-04/msg00033.html I think the best solution is just to avoid having spaces in the directory path.

**Comment by Stokestack** [comment]
Wow, over a decade later and libtool is still broken. Sad.

**Comment by mh4nx7net** [comment]
> This seems to be a known issue with libtool: https://lists.gnu.org/archive/html/bug-libtool/2008-04/msg00033.html I think the best solution is just to avoid having spaces in the directory path.

exactly having same issues
first of all they're seems can't read some directoryname within namespace, on me like an 
`~/D\ I\ R/to/build/thirdparty/protobuf`
there's don't know why, @Stokestack says over decade then no attention over here, and now is 2020 seriously? not just over a decade bruhh.

just change my dir name
`mv ~/D\ I\ R/ ~/DIR/`
remove my old protobuf, then get a new one by
`git submodule update --init`
or whatever ways you have to get the new one

done
![grimshoot-slurp-2020-03-08-14-59-53](https://user-images.githubusercontent.com/33443311/76158913-7f0a9f00-614d-11ea-8b6d-9fbd95839009.png)
