### ISSUE TITLE
protoc-artifacts/Dockerfile no longer works with protobuf 3.6.0

### ISSUE THREAD

**Issue by jtattermusch** [google/protobuf#4868]
The docker image used for building protoc artifacts does no longer work as protobuf 3.6.0 now requires C++11 and the docker image has gcc4.7 only.

I'm facing problems upgrading grpc's third_party/protobuf to 3.6.0 because of that (we use a similar dockerfile for building the protoc artifacts, the WIP PR is https://github.com/grpc/grpc/pull/15597).

```
[AUTOGEN] Preparing protobuf
...
checking whether c++ supports C++11 features by default... no
checking whether c++ supports C++11 features with -std=c++11... no
checking whether c++ supports C++11 features with +std=c++11... no
checking whether c++ supports C++11 features with -h std=c++11... no
checking whether c++ supports C++11 features with -std=c++0x... no
checking whether c++ supports C++11 features with +std=c++0x... no
checking whether c++ supports C++11 features with -h std=c++0x... no
configure: error: *** A compiler with support for C++11 language features is required.
make: *** [/var/local/git/grpc/libs/opt/protobuf/libprotobuf.a] Error 1
+ FAILED=true
```

It looks like the 3.6.0 binaries are available on the prorobuf release page - how were they build?

**Comment by jtattermusch** [comment]
@zhangkun83  you seem to be the original author of the Dockerfile - it there are particular reason why we chose to build the artifacts under CentOS 6.6?   I know we wanted to get binaries that are binary compatible with a wide range of distributions, but it seems to me that some of the older debian distributions (wheezy or jessie) would work as well and we wouldn't be needing workarounds for some docker bugs we are hitting with the current centos Dockerfile - also, I spent quite a lot of time trying to update the Dockerimage to devtoolset-2 (to get gcc 4.8 which should have enough C++11 support to build protobuf) but wasn't able to figure it out (devtoolset-2 seems broken).

**Comment by jtattermusch** [comment]
update: I was able to get the centos6.6 dockerfile working with devtools-2  in https://github.com/grpc/grpc/pull/15597 and the I've verified that it can successfully build protoc for protobuf 3.6.0. If the PR gets merged, we should sync the protobuf's version of that dockerfile with our version.

**Comment by xfxyjwf** [comment]
@acozzette Adam, I remember you used a new docker image or something to build 3.6.0 protoc release binary?

**Comment by acozzette** [comment]
Yes, sorry for the trouble, I tweaked the configuration to use devtools-2 but forgot to send out that change after I finished the release. I just sent out my change in #4877.
