### ISSUE TITLE
How to set map field on protoBuff java side

### ISSUE THREAD

**Issue by amitvyawahare** [google/protobuf#4875]
The example message:

message example {
          string a = 1;
          string b = 2;
          map<int32, String> c = 3; 
}

ProtoBuff 3.0 compiler for java will create setA, setB methods on builder but not setC. What is the correct way to set map c ?

**Comment by xfxyjwf** [comment]
See: https://developers.google.com/protocol-buffers/docs/reference/java-generated#map-fields
