### ISSUE TITLE
not clear how to install prebuilt binaries 

### ISSUE THREAD

**Issue by jeremy-rutman** [google/protobuf#4883]
I downloaded the prebuilt binaries for my platform, unzipped ... now what? 
No instructions in the readme, no install.txt, running install.sh gives a 'no input file specified' error. 
A line or two of usable instruction would come in handy

**Comment by xfxyjwf** [comment]
You probably downloaded the wrong zip. Try (if you are using windows):
https://github.com/google/protobuf/releases/download/v3.6.0/protoc-3.6.0-win32.zip

**Comment by jeremy-rutman** [comment]
I downloaded https://github.com/google/protobuf/releases/download/v3.6.0/protobuf-all-3.6.0.tar.gz 
expecting it to be suitable for ubuntu 18.04.  BTW how would downloading the wrong zip lead to a lack of instructions?

**Comment by xfxyjwf** [comment]
@jeremy-rutman Have you read the README.md file carefully in the package you downloaded?
https://github.com/google/protobuf/blob/master/README.md#protocol-compiler-installation

I think it's very clear on how to install pre-built protoc binaries. You were either looking at the wrong file, or overlooked it.

**Comment by jeremy-rutman** [comment]
sorry but its really not at all clear what to do after downloading and unzipping the protobuf tar.gz.   The README basically tells me nothing past downloading , and that installing the pre-built binary is the easiest for non C++ users.  I am guessing that I should take the protoc binary and put it in my path?   Consider that what may be obvious to you , who may have previous experience with protobuf  and its compilation/installation, may not be obvious to me, who has no experience .

**Comment by xfxyjwf** [comment]
> I downloaded the prebuilt binaries for my platform, unzipped ... now what?

I think your confusion comes from downloading the wrong package. You thought you downloaded the prebuilt binary package, but you really didn't. If you have followed the instruction to download the prebuilt binary package, there is a README in that package to tell you to put the binary in your path.

**Comment by jeremy-rutman** [comment]
yes, thanks
