### ISSUE TITLE
why is default for MessageToJson preserving_proto_field_name False?

### ISSUE THREAD

**Issue by tommyjcarpenter** [google/protobuf#4886]
In this file: https://github.com/google/protobuf/blob/master/python/google/protobuf/json_format.py

I am kind of puzzled as to why the default of `preserving_proto_field_name` is `False`, as in, "manipulate the data structure by default". This was the source of an obscure bug in our codebase. I would like to know the rationale behind manipulation as a default. I think the field should be something like `convert_to_camel` with a default as False.

**Comment by xfxyjwf** [comment]
The default is "lowerCamelCase" per proto3 JSON spec:
https://developers.google.com/protocol-buffers/docs/proto3#json
