### ISSUE TITLE
OnShutdownDelete shadowing issue

### ISSUE THREAD

**Issue by chronoxor** [google/protobuf#4887]
GCC 8.1.0 with -Wall -Werror -Wshadow -pedantic options

/home/travis/build/chronoxor/CppSerialization/modules/protobuf/src/google/protobuf/stubs/common.h:209:33: error: declaration of ‘const void* p’ shadows a parameter [-Werror=shadow]
   OnShutdownRun([](const void* p) { delete static_cast<const T*>(p); }, p);
                                 ^
/home/travis/build/chronoxor/CppSerialization/modules/protobuf/src/google/protobuf/stubs/common.h:208:24: note: shadowed declaration is here
 T* OnShutdownDelete(T* p) {
                     ~~~^

**Comment by xfxyjwf** [comment]
Thanks for the patch!
