### ISSUE TITLE
php protobuf.so  same message name with diff namespace error

### ISSUE THREAD

**Issue by xcwen** [google/protobuf#4892]
**What version of protobuf and what language are you using?**
Version: master/v3.6.0/
Language: C++/Java/Python/C#/Ruby/PHP/Objective-C/Javascript
php 
**What operating system (Linux, Windows, ...) and version?**
linux 
**What runtime / compiler are you using (e.g., python version or gcc version)**
php-7.2 ,   C extension: prootbuf.so
**What did you do?**
create two protobuf  test.proto, test1.proto
test.proto:
```protobuf
syntax = "proto3";
option php_namespace = "test"; 
message in {
  int32  value = 1; //
}
```
test1.proto:
```protobuf
syntax = "proto3";
option php_namespace = "test1"; 
message in {
  int32  value = 1; //
}
```
gen php code
```bash
protoc ./test.proto --php_out=./php
protoc ./test1.proto --php_out=./php
```
test code 
```php
<?php

require("./php/GPBMetadata/Test.php");
require("./php/GPBMetadata/Test1.php");
require("./php/test/in.php");
require("./php/test1/in.php");
$in=new \test\in();
$in1=new \test1\in();

```
test it , find error:

```bash
localhost:~/proto_test$ php a.php 
PHP Fatal error:  Unable to add file to DescriptorPool: Symtab already has a def named 'in'
 in /home/jim/proto_test/php/GPBMetadata/Test1.php on line 19
```

test  code :
[proto_test.tar.gz](https://github.com/google/protobuf/files/2183121/proto_test.tar.gz)

**Anything else we should know about your project / environment**

**Comment by TeBoring** [comment]
The descriptor for each message (implementation detail) is distinguished by its proto fully qualified name, which is package + message name.
In your example, although you provided different php_namespace, you don't give different package. So in the perspective of protobuf, two ```in``` have the same fully qualified name.
You should define different pacakage in these two proto files.

**Comment by xcwen** [comment]
thanks :>
