### ISSUE TITLE
error C3857: 'Map': multiple template parameter lists are not allowed

### ISSUE THREAD

**Issue by deulgaonkaranup** [google/protobuf#4901]
Hi,
 
I am trying to using protobuf-all-3.5.0.zip and creating a static library by using the VS solution generated.

I have followed the steps in CMake Configuration section of the readme file.

Steps:

1. C:\Path\to\protobuf\cmake\build\debug>cmake -G "NMake Makefiles" ^
 -DCMAKE_BUILD_TYPE=Debug ^
 -DCMAKE_INSTALL_PREFIX=../../../../install ^
 ../..

2. C:\Path\to\protobuf\cmake\build\solution>cmake -G "Visual Studio 14 2015 Win64" ^
 -DCMAKE_INSTALL_PREFIX=../../../../install ^
 ../..

3. Ran the batch file extract_includes.bat to extract header files 

When i link the library and include the header files in my solution, it gives me a compiler error : 
arena.h(923): error C3857: 'Map': multiple template parameter lists are not allowed

The line that throws the error is:
**template <typename Key, typename T>
  friend class Map;**

Could you please let me know how i could resolve this ? I have tried looking around but haven't had any luck.

**Comment by deulgaonkaranup** [comment]
I am working on windows operating system and generating a 64 bit .lib .

**Comment by deulgaonkaranup** [comment]
Closing the ticket as this was because of using 2.6 and 3.0 at the same time.

**Comment by pqshao** [comment]
> Closing the ticket as this was because of using 2.6 and 3.0 at the same time. Worked after removing 2.6 related files

hello, I run into the same problem , which files did you remove?

**Comment by puse45** [comment]
> 
> 
> Closing the ticket as this was because of using 2.6 and 3.0 at the same time. Worked after removing 2.6 related files

Hi, also having the same error, how do I go on about it?
