### ISSUE TITLE
[python] in interactive mode, `add()` modifies repeated message field even when there's an error

### ISSUE THREAD

**Issue by JohnHBrock** [google/protobuf#4914]
Not sure if this is a bug in protobuf or in my expectations, but this behavior unpleasantly surprised me.

**What version of protobuf and what language are you using?**
Version: v3.6.0
Language: Python

**What operating system (Linux, Windows, ...) and version?**
macOS 10.13.5

**What runtime / compiler are you using (e.g., python version or gcc version)**
Python 3.6.5

**What did you do?**
1. Compile this .proto definition:
  ```proto
syntax = "proto3";

message SomeMessage {
	repeated ListElement some_list = 1;
}

message ListElement {
	string value = 1;
}
```
2. Run python3 in interactive mode and run the following:
```python
import some_proto_pb2

some_message = some_proto_pb2.SomeMessage()
some_message.some_list.add("foo")  # whoops, forgot to add value=
some_message.some_list.add(valu="foo") # whoops, spelled value wrong
some_message.some_list.add(value="foo")
print(some_message.some_list)
```

**What did you expect to see**
After running this code, I expected `some_message.some_list` to contain a single element because the first two calls to `add()` produced errors, and I therefore expected them not to modify the collection. I.e., I expected `print(some_message.some_list)` to output:
```python
[value: "foo"
]
```

**What did you see instead?**
Instead, `some_message.some_list` contained two empty elements, followed by the element I expected:
```python
[, , value: "foo"
]
```

Here's a copy & paste from my interpreter:
```python
>>> import some_proto_pb2
>>> 
>>> some_message = some_proto_pb2.SomeMessage()
>>> some_message.some_list.add("foo")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: No positional arguments allowed
>>> some_message.some_list.add(valu="foo")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: Protocol message ListElement has no "valu" field.
>>> some_message.some_list.add(value="foo")
value: "foo"

>>> print(some_message.some_list)
[, , value: "foo"
]
```

**Comment by anandolee** [comment]
Do you know what interactive mode will do after an error is raised: continue with the rest code or stop at the error?  The behavior on your example seems like interactive mode continues with the rest code after error is raised, if it is the feature of interactive mode, then result it correct.

**Comment by JohnHBrock** [comment]
I don't think this is a feature of interactive mode, but I'm not 100% sure. It's hard for me to imagine the interpreter being able to continue execution after an unhandled exception.

**Comment by anandolee** [comment]
What's the behavior if you do in a .py file by try:

try:
  some_message.some_list.add("foo") 
except TypeError:
  pass

**Comment by JohnHBrock** [comment]
In python 3 I don't get an exception (interestingly, with python 2 I get `TypeError: __new__() got an unexpected keyword argument 'serialized_options'`).

I also ran this slightly modified version with python 3:
```py
import some_proto_pb2

some_message = some_proto_pb2.SomeMessage()

print(some_message.some_list)
print(len(some_message.some_list))

try:
  some_message.some_list.add("foo") 
except:
  pass

print(some_message.some_list)
print(len(some_message.some_list))
```
and got this output:
```sh
$ python3 bar.py 
[]
0
[]
1
```

**Comment by anandolee** [comment]
I've tried the following test:
```
  def testAddWrongRepeatedNestedField(self, message_module):
    msg = message_module.TestAllTypes()
    try:
      msg.repeated_nested_message.add("wrong")
    except TypeError:
      pass
    try:
      msg.repeated_nested_message.add(value="wrong")
    except ValueError:
      pass
    self.assertEqual(len(msg.repeated_nested_message), 0)
```

It can pass with pure python in both python2 and python3. Can not pass with python c extension for both python2 and python3 (len is 2 with protobuf python c extension). 


Corresponding code is in AddToAttached, we called AddMessage() first:
https://github.com/google/protobuf/blob/master/python/google/protobuf/pyext/repeated_composite_container.cc#L142

And Do the init check later:
https://github.com/google/protobuf/blob/master/python/google/protobuf/pyext/repeated_composite_container.cc#L154

Reverse the order could fix the issue. I've created a change for review in our internal code.
Thanks to raise this issue up

**Comment by anandolee** [comment]
The fix has been submitted in internal code, expect to see in next release.
