### ISSUE TITLE
"Buffer is not defined" when i use deserializeBinary() function ,who can help me? Thanks

### ISSUE THREAD

**Issue by bestbelief** [google/protobuf#4921]

**Comment by bestbelief** [comment]
ERROR:
core.js:1624 ERROR ReferenceError: Buffer is not defined
    at Object.push../node_modules/google-protobuf/google-protobuf.js.jspb.utils.byteSourceToUint8Array (google-protobuf.js:250)
 ..........
MY CODE:
subscribe() {
         const payload = new IotPayload();
         const metrics: Array<IotPayload.IotMetric> = new Array<IotPayload.IotMetric> ();
         const position = new IotPayload.IotPosition();
         payload.setTimestamp(5);
         payload.setMetricList(metrics);
         payload.setPosition(position);
         this.subMessage = null;
           this.mqttservice.observe(this.subTopic)
           .pipe(
            map(v => { console.log(v); return v ; }),
            map(v => v.payload), )
            .subscribe(msg => {
  //   when i user this code catch error 
            this.subMessage = IotPayload.deserializeBinary(msg);
            });
      }

**Comment by TeBoring** [comment]
```deserializeBinary``` expect a binary string instead of a protobuf message as argument.

**Comment by bestbelief** [comment]
thank you very much! I have found my mistake because the parameter type is not correct. you are right
