### ISSUE TITLE
Iterator invalidation for Map

### ISSUE THREAD

**Issue by dio** [google/protobuf#4938]
Hi, is it safe to say that the protobuf C++ Map implementation has the same behavior with `std::unordered_map` in terms of iterator invalidation?

Ref: 
1. https://stackoverflow.com/questions/16781886/can-we-store-unordered-maptiterator
2. https://stackoverflow.com/questions/6438086/iterator-invalidation-rules

Thanks!

**Comment by dio** [comment]
It seems it is untouched during mutation.

https://github.com/google/protobuf/blob/88795f64e4c5dc870c63b3d4d39924cc91590b2f/src/google/protobuf/map.h#L326-L327

```
// 8. Mutations to a map do not invalidate the map's iterators, pointers to
//    elements, or references to elements.
```

**Comment by xfxyjwf** [comment]
We can consider this issue resolved?

**Comment by dio** [comment]
Yeah. Sorry for the noise!
