### ISSUE TITLE
[Java] com.google.protobuf.Value support to wrapper Any as a field

### ISSUE THREAD

**Issue by yanxinyuan** [google/protobuf#4939]
**What language does this apply to?** java
**If it's a proto syntax change, is it for proto2 or proto3?** proto3
**If it's about generated code change, what programming language?** no, java

**Describe the problem you are trying to solve.**
We have a framework which communicate with protobuf. And now we want to move our old application to our framework, but it's interface was written by java pojo, so we provide a converter mechanism to solve this problem. 

For example: 
Integer/int ->(auto converter) Int32Value
Float/float ->(auto converter)  FloatValue
Map<String, String> ->(auto converter)  Struct
List<String> -> (auto converter) ListValue
Bean ->(user provide converter) Protobuf Object

But many of our application's parameters are List<Bean> or Map<String, Bean>, the way to solve this problem in my opinion is we transfer the Bean to protobuf object, and then transfer it to Any, and wrapper this any object to Value object. But till now the Value type only support 'null, a number, a string, a boolean, a recursive struct value, or a list of values'. Which means i have no way to handle this scenario.

**Describe the solution you'd like**
com.google.protobuf.Value support to set com.google.protobuf.Any as String or Boolean type does.

**Describe alternatives you've considered**
I have write a sample and test it, it works pretty well. But i don't think the code quality or guide line is ok,
so just for reference. 
https://gist.github.com/yanxinyuan/dbf88478d5c8e77879cae34ff19cb1a1

**Additional context**

**Comment by xfxyjwf** [comment]
google.protobuf.Value is designed to model a JSON value and that's why it has those types. google.protobuf.Any certainly doesn't fit there.

**Comment by yanxinyuan** [comment]
Thanks @xfxyjwf , But how we handle the scenario as i described by using protobuf?

**Comment by xfxyjwf** [comment]
When you convert List and Map, can you check whether they are a list of Beans (or the map value is Bean) and convert them as such:
List<Bean> => repeated Bean field
Map<String, Bean> => map<string, Bean> field
?

**Comment by yanxinyuan** [comment]
Sorry for late response, can you give some sample or more detail information like List => repeated Bean field ? How to transfer?

**Comment by yanxinyuan** [comment]
Thanks @xfxyjwf .
Actually the reason i asked "Value support to wrapper Any as a field" is i don't know how to handle the below scenario. In my application when i received a List type object, the type can be String, Boolean, **Bean** and so on. I will check if it is a list, i will transfer it to ListValue and pack it to any, then i can use the any object to communicate with other service. But if the type in the List is a Bean, and the Value type do not support to wrapper the Bean, so my solution is extending the Value implement as i described previous.
But as you said "google.protobuf.Value is designed to model a JSON value and that's why it has those types. ", when i received a List<?>, how am i parsing the list to Any?

```
public Any parseListObj(List<?> list) throws Exception {
	    com.google.protobuf.ListValue.Builder listBuilder = ListValue.newBuilder();
        for (Object subObj : list) {
	      Value value = parsePrimitiveType2Value(subObj);
              listBuilder.addValues(value);
        }
	Any any = Any.pack(listBuilder.build());
        return any;
}

private static Value parsePrimitiveType2Value(Object subObj) {
        if (subObj instanceof Double) {
            Value value = Value.newBuilder()
                    .setNumberValue(Double.valueOf(String.valueOf(subObj)))
                    .build();
            return value;
        } 
        if (subObj instanceof String) {
            Value value = Value.newBuilder()
                    .setStringValue(String.valueOf(subObj))
                    .build();
            return value;
        }
	// if subObj is user defined object, can not handle this scenario
        return null;
}
```

**Comment by yanxinyuan** [comment]
After i go through the source code of potobuf, i found maybe the "com.google.protobuf.RepeatedFieldBuilderV3" or "com.google.protobuf.ProtobufArrayList" can be used. But sadly the "RepeatedFieldBuilderV3" cannot be constructed and the "ProtobufArrayList" is not visible. .

**Comment by xfxyjwf** [comment]
If subObj is user defined object, can you use the user provided converter? You mentioned there is a user provided converter, right?
```
Bean ->(user provide converter) Protobuf Object
```

**Comment by yanxinyuan** [comment]
yes, I can use user provide converter to transfer user defined object to protobuf object. Means:

`List<Bean> ->(user provide converter) -> List<Protobuf Object>`

but how to parse the `List<Protobuf Object>` to Any?

**Comment by xfxyjwf** [comment]
Why do you need to convert it to Any? Isn't a List<Protobuf Object> easier to work with?

**Comment by yanxinyuan** [comment]
Oh, That's another question. My application is event driven based which means we can only handle event in our system. The data structure of event is some thing like 
``` 
---Event
------source
------destination
------Payload
---------Any
```
The field in Payload is a dynamic  object, so we can only use any here. 
For exmaple: 
a) if the field in payload is `List<Bean>`, i must do something to transfer to any.
b) If the field is Bean, i will invoke converter to transfer the Bean to protobuf object, then use any pack it.
c) If the field is String..., i will use StringValue to wrapper it ,and then use any pack it.

**Comment by yanxinyuan** [comment]
So the ways i think can solve my problem is something like: 
`List<Bean> ->(user provide converter) -> List<Protobuf Object> ->Any -> Set to Value -> Any`
Or
`List<Bean> ->(user provide converter) -> List<Protobuf Object> ->Any`
Or 
`List<Bean> ->(user provide converter) -> List<Protobuf Object> -> (like ProtobufArrayList) ->Any`

**Comment by xfxyjwf** [comment]
I think I need a concrete example to understand what you are trying to do. Say your old application has such a method:
```java
void DoSomething(int a, Foo b, List<Foo> c);
class Foo {...}
```
are you trying to convert that method to take proto types as parameters instead? Like:
```java
void DoSomething(google.protobuf.Int32Value a, FooProto b, List<FooProto> c);
void DoSomething(int a, Foo b, List<Foo> c) {
  DoSometing(convert(a), convert(b), convert(c));
}
```
?

**Comment by yanxinyuan** [comment]
@xfxyjwf  Thanks very much, I will try to make it clear by way of example, but there are some intellectual property issues, so please understand.

Our product is a event based distributed framework by java language. A key technology in our product is we have our own Container(Similar to but different from OSGI). The Container can load and execute user service(Similar to but different from Bundle, each service is isolated), obviously we used protobuf as a serialization technique here. Here are user code examples:

Shared class
`class Foo {...}`

Service One (Load by a Container):
`Foo DoFirst(int a){}`
Service Two (Load by another Container):
`void DoSecond(Foo foo){}`

If an specified event occurs, our Container will proceed as follows:
```
1. Invoke the `DoFirst` method by java reflect and get the return value(Foo object here)
2. Convert the Foo object to FooProto(by invoke user provide converter)
3. Pack FooProto to Any 
4. Set the any object to Event field
5. Send out
```
The received Container will proceed as follows:
```
1. Parsing event and get the "any" field
2. Unpack any object to FooProto 
3. Convert the FooProto to Foo object(by invoke user provide converter)
4. Invoke the 'DoSecond' method
5. ...
```
So here is the problem, if the return value of the `DoFirst` method is `List<Foo>` and the parameter of the `DoSecond` method is `List<Foo>` too, we got stuck in this scenario.

Shared class
`class Foo {...}`

Service One (Load by a Container):
`List<Foo> DoFirst(int a){}`
Service Two (Load by another Container):
`void DoSecond(List<Foo> foo){}`

If an specified event occurs, our Container will proceed as follows:
```
1. Invoke the `DoFirst` method by java reflect and get the return value(List<Foo> object here)
2. Convert the List<Foo> object to List<FooProto>(by invoke user provide converter)
3. Pack List<FooProto> to Any -> **Got stuck here**
4. Set the any object to Event field
5. Send out
```
**We got stuck at step 3, we can not parse the `List<FooProto>` object to Any.**

**Comment by yanxinyuan** [comment]
@xfxyjwf 
Great! That solves my issue. Thank you for your patience, thanks. And i will close the issue.
