### ISSUE TITLE
Mismatch in protoc and runtime library versions

### ISSUE THREAD

**Issue by akhuteta** [google/protobuf#4944]
I wanted to use protocol buffers in my project, so I installed the latest the latest release v3.6.0 from the tarball available on github.

When i try to link the cc file, generated after compiling using protoc, with libprotoc, I get an error that 
"This file was generated by an older version of protoc which is incompatible with your Protocol Buffer headers.  Please regenerate this file with a newer version of protoc.

Also the protoc --version reflects 3.0.0

My question is, both protoc and the runtime env got installed using the same tarball, then why do I get a version mismatch?

Here's my system details : 
Ubuntu 14.0.1
g++ version 6.4.0

**Comment by xfxyjwf** [comment]
Ubuntu comes with a pre-installed protoc. You need to uninstall that one.
