### ISSUE TITLE
Backward compatibility of the Python files generated from Protobuf files

### ISSUE THREAD

**Issue by pfreixes** [google/protobuf#4945]
Hi,

I would like to know if the Python files that are generated from Protobuf files are backward compatibility within the same major version, for examples:

I have a Python file that belongs to a specific service that was generated by the 3.0.0 version of the `protoc` compiler, then this file is used in another environment by a client of the service that uses the 3.6.0 version, my two questions here are:

1) The python file will be importable by the client that uses the newer version?
2) If yes, the data produced by the client will be consumable by the service that uses the older version?

Cheers,

**Comment by anandolee** [comment]
We have compatibility tests to  make sure old generated code can work with new runtime:
https://github.com/google/protobuf/blob/master/python/compatibility_tests/v2.5.0/test.sh

New generated code may not work with old runtime.

**Comment by pfreixes** [comment]
@anandolee thanks for your answer and sorry to be so late.

I'm wondering why the latest older version that is tested against the current one is the 3.0.0-beta4 [1]. Why not the none beta version? Why not with all of the 3.X versions already published?


[1] https://github.com/protocolbuffers/protobuf/blob/master/python/compatibility_tests/v2.5.0/test.sh#L38
