### ISSUE TITLE
Wnarrowing in io_win32_unittest.cc

### ISSUE THREAD

**Issue by ripopov** [google/protobuf#4955]
Version: v3.6.0
I'm using CMake from protobuf-3.6.0 on Windows with Mingw-w64 (g++ 6.4). With default options build fails with error:
protobuf-3.6.0\src\google\protobuf\stubs\io_win32_unittest.cc:77:1: error: narrowing conversion of '159' from 'int' to 'char' inside { } [-Wnarrowing]

**Comment by xfxyjwf** [comment]
Could you help send a pull request?

**Comment by ripopov** [comment]
Already fixed in master. cmake/tests.cmake line 207
