### ISSUE TITLE
C++ aggregate initialization 

### ISSUE THREAD

**Issue by whit2333** [google/protobuf#4957]
It would be great to use  aggregate initialization on the generated c++ classes. 
https://en.cppreference.com/w/cpp/language/aggregate_initialization

This can probably be implemented many ways but I am sure someone has thought about this before.

```
message Foo {
    int bar = 1;
    double blah = 2;
}
```
Using aggregate initialization:
```
Foo butt = { 5, 10.0 } ;
```

In modern C++ this would be easy (string data types might require some attention).

**Comment by gerben-s** [comment]
I don't have a strong opinion here. But I think we need t o be careful. For one we want the proto compiler to have the ability to reorder fields, while aggregate initialization needs to have to order as specified in the code.

Also removing a field and make it reserved seems a dangerous operation.

Josh any thoughts?

**Comment by haberman** [comment]
Any kind of order-based initialization seems dangerous, since fields can be added and removed. Also it's unclear whether the order would be based on field number or declaration order in the .proto file.

**Comment by gerben-s** [comment]
It seems that aggregate init is not compatible with the primary goals of protobuf. Namely provide a stable back and forwards compatible extensible protocol, both on the wire and as a programming library.

**Comment by darkdragon-001** [comment]
C++20 introduces [designated initializers](https://en.cppreference.com/w/cpp/language/aggregate_initialization#Designated_initializers). Maybe we can revisit the request?
