### ISSUE TITLE
The decoding performance is extremely slow for some pb file with python 3.7

### ISSUE THREAD

**Issue by JerryShih** [google/protobuf#4967]
**What version of protobuf and what language are you using?**
Version: v3.6.0
Language: Python

**What operating system (Linux, Windows, ...) and version?**
mac 10.13.6

**What runtime / compiler are you using (e.g., python version or gcc version)**
python 3.7

**What did you do?**
load a big pb2 base file from
https://s3.amazonaws.com/onnx-model-zoo/resnet/resnet34v1/resnet34v1.onnx

1. pip install onnx
2. run a script like:
```
import onnx
model=onnx.load("resnet34v1.onnx")
```

It's extremely slow when I load this file.
And here is the cProfiler data.

```
   Ordered by: internal time
   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
 21814770   18.504    0.000   24.525    0.000 decoder.py:297(InnerDecode)
 21815801   14.909    0.000   59.430    0.000 containers.py:249(append)
      182   12.078    0.066   96.030    0.528 decoder.py:202(DecodePackedField)
 21832522   10.832    0.000   36.232    0.000 {built-in method builtins.isinstance}
 21815489    9.559    0.000   20.988    0.000 {built-in method _abc._abc_instancecheck}
21815396/21815369    7.111    0.000    7.111    0.000 {built-in method _abc._abc_subclasscheck}
 21814696    6.415    0.000   42.643    0.000 type_checkers.py:101(CheckValue)
 21814770    6.021    0.000    6.021    0.000 {built-in method _struct.unpack}
 21815489    4.412    0.000   25.400    0.000 abc.py:137(__instancecheck__)
21815396/21815369    4.318    0.000   11.429    0.000 abc.py:141(__subclasscheck__)
 21832415    1.877    0.000    1.877    0.000 {method 'append' of 'list' objects}
     1645    0.133    0.000    0.331    0.000 python_message.py:469(init)
     1842    0.123    0.000    0.123    0.000 {method 'items' of 'dict' objects}

```

**What did you expect to see**
It should be less than 1 second.
My friend could load the file in 1 second with python 2.7+protobuf 3.6 on linux.

**Comment by xfxyjwf** [comment]
How large is the file? We have published python performance numbers here:
https://github.com/google/protobuf/blob/master/docs/performance.md

Depending on whether you are using pure python or python C extension, the performance varies quite a bit.

**Comment by JerryShih** [comment]
Which version will I have if I install protobuf from "pip install protobuf"?
The installed version is 3.6.0.
And I use mac.

**Comment by JerryShih** [comment]
The resnet34v1.onnx is about 83M.

**Comment by xfxyjwf** [comment]
"pip install protobuf" will install the version with C extension if it's available on your platform. If the C extension is not available, it will fallback to the pure python version which will be much slower. That seems to explain the difference you are seeing.

**Comment by JerryShih** [comment]
I just build the protobuf with c++-impl.
`
python setup.py build --cpp_implementation
`
It's faster now.
Thank you.
