### ISSUE TITLE
contains invalid UTF-8 data when parsing a protocol buffer. Use the 'bytes' type if you intend to send raw bytes.

### ISSUE THREAD

**Issue by wenhuiwu** [google/protobuf#4970]
we are tying use a python grpc clinet to send request to the go server. 
the proto param we used has been defined as:
message PbRider {
      string  speed_param  = 28;
};
but we get an error:
contains invalid UTF-8 data when parsing a protocol buffer. Use the 'bytes' type if you intend to send raw bytes.

**Comment by acozzette** [comment]
String fields are only intended for storing UTF-8 data, so if you need to send non-UTF-8 data then it is best to use a `bytes` field instead.

**Comment by wenhuiwu** [comment]
But the data has been changed to type-string on go server, why does the python client cannot parse this data? Maybe the python protobuf should do something to deal with those who contains non-UTF-8 data but defined as string in proto?
