### ISSUE TITLE
C# - Some types are missing

### ISSUE THREAD

**Issue by trydis** [google/protobuf#4998]
**What version of protobuf and what language are you using?**
Version: v3.5.1
Language: C#

**What operating system (Linux, Windows, ...) and version?**
MacOS 10.13.6

**Problem**
I'm trying to generate C# gRPC bindings for the Google Assistant. The command succeeds with no errors/warnings, but types in the `Google.Api` and `Google.Type` namespaces are missing.  Am I doing something wrong or is it a possible bug?

**Script**
```
#!/bin/bash

GRPC_TOOLS_PATH=~/.nuget/packages/grpc.tools/1.14.0/tools/macosx_x64
OUT_PATH=Assistant.Lib

$GRPC_TOOLS_PATH/protoc \
-I ~/dev/github/google/googleapis \
-I ~/dev/github/google/protobuf/src \
--csharp_out $OUT_PATH \
--grpc_out $OUT_PATH ~/dev/github/google/googleapis/google/assistant/embedded/v1alpha2/embedded_assistant.proto \
--plugin=protoc-gen-grpc=$GRPC_TOOLS_PATH/grpc_csharp_plugin
```

![image](https://user-images.githubusercontent.com/446036/43635624-f2ea258a-970f-11e8-88c0-7eaf35cf625f.png)

![image](https://user-images.githubusercontent.com/446036/43635648-01cdbd14-9710-11e8-9080-ce1616245cc6.png)

**Comment by trydis** [comment]
Ok, so i got it working by explicitly specifying the extra proto files. Not sure if that is expected behavior? 

```
#!/bin/bash

GRPC_TOOLS_PATH=~/.nuget/packages/grpc.tools/1.14.0/tools/macosx_x64
PROTO_PATH=~/dev/github/google/googleapis/google
OUT_PATH=Assistant.Lib

$GRPC_TOOLS_PATH/protoc \
-I ~/dev/github/google/googleapis \
-I ~/dev/github/google/protobuf/src \
--csharp_out $OUT_PATH \
--grpc_out $OUT_PATH $PROTO_PATH/assistant/embedded/v1alpha2/embedded_assistant.proto $PROTO_PATH/type/latlng.proto $PROTO_PATH/api/annotations.proto $PROTO_PATH/api/http.proto \
--plugin=protoc-gen-grpc=$GRPC_TOOLS_PATH/grpc_csharp_plugin
```

**Comment by anandolee** [comment]
+Jan, from grpc team

**Comment by jtattermusch** [comment]
@trydis   I think your fix is correct.  The generated classes for `annotations.proto`, `http.proto` and others need to come from somewhere - so unless you generate them and include the generated code in your project, you'll get an error.

There are some "common" .proto files pregenerated that are bundled in the Google.Protobuf nuget, but those are the only the "well known types" that are defined in the google/protobuf repository (e.g. https://github.com/google/protobuf/blob/master/src/google/protobuf/timestamp.proto).
Google.Api and Google.Type aren't logically part of protobuf - from protobuf's (and grpc's) perspective, they are just another .proto files (for which you need to generate the .cs files).

As a side note, isn't there an official C# client library for Assistant API? Using it would save you the trouble.

**Comment by trydis** [comment]
Thanks for the explanation.

AFAIK the only official option is the Python library (https://developers.google.com/assistant/sdk/overview#sdk_components).
