### ISSUE TITLE
Git status is not clean after building python version

### ISSUE THREAD

**Issue by finaldie** [google/protobuf#5004]
**What version of protobuf and what language are you using?**
Version: v3.6.0
Language: Python

**What operating system (Linux, Windows, ...) and version?**
**Linux:** Ubuntu 18.04

**What runtime / compiler are you using (e.g., python version or gcc version)**
gcc 7.3.0
python 3.6.5

**What did you do?**
1. Build c++ version: `./autogen.sh && ./configure --enable-static=no && make -j8`
2. Build python: `cd python && export LD_LIBRARY_PATH=../src/.libs; python3 setup.py build --cpp_implementation && cd ..`
3. Install c++ version: `sudo make install && sudo ldconfig`
4. Install python version: `cd python && export LD_LIBRARY_PATH=../src/.libs; python3 setup.py install --cpp_implementation`

**What did you expect to see**
```console
bash $>git st
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```

**What did you see instead?**
```console
root@0025efdb0c90: /workspace/deps/protobuf>git st
HEAD detached at v3.6.0
Untracked files:
  (use "git add <file>..." to include in what will be committed)

	python/dist/

nothing added to commit but untracked files present (use "git add" to track)
root@0025efdb0c90: /workspace/deps/protobuf>ls -hl python/dist/
total 2.1M
-rw-r--r-- 1 root root 1.8M Jul 23 20:52 protobuf-3.6.0-py3.6-linux-x86_64.egg
```
```console
root@0025efdb0c90: /workspace>git st
On branch 1.2
Your branch is up to date with 'origin/1.2'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)
  (commit or discard the untracked or modified content in submodules)

	modified:   deps/protobuf (untracked content)
```

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Anything else we should know about your project / environment**
In my project, the `protobuf` is imported as a submodule. I also checked latest `protobuf/master`, not fixed yet. If needed, please check this [Makefile][1] :)

[1]: https://github.com/finaldie/skull/blob/master/.Makefile.dep#L64

**Comment by xfxyjwf** [comment]
Thanks for making the fix!
