### ISSUE TITLE
How can I use vars(object) in python2.7 or 3.*? 

### ISSUE THREAD

**Issue by xzhacker123** [google/protobuf#5009]
> say_hi.proto

syntax = "proto2";

package proto;

message SayHi {
    required int32 id = 1;
    required string something = 2;
    optional string extra_info = 3;
}

> test.py

import say_hi_pb2

po = say_hi_pb2.SayHi()
po.id = 123
po.something = 'do_something'
po.extra_info = 'test'

bilibili = po.SerializeToString()

oo = say_hi_pb2.SayHi()
oo.ParseFromString(bilibili)

print type(oo)
print vars(oo)
print oo.id
print oo.something
print oo.extra_info

`<class 'say_hi_pb2.SayHi'>
Traceback (most recent call last):
  File "E:/PycharmProject/pb_test/proto/test.py", line 20, in <module>
    print vars(oo)
TypeError: vars() argument must have __dict__ attribute`

**Comment by anandolee** [comment]
Why do you need to use vars()? 
If your use case want to know what fields a message are defined in the .proto file, you can use Descriptor:
https://github.com/google/protobuf/blob/master/python/google/protobuf/descriptor.py#L222

**Comment by xzhacker123** [comment]
Thank you for your answer. I'm looking at the fields definition.
I want to implement RPC request with hprose + protobuf
[https://github.com/hprose/hprose-python](url)

	import hprose
	from pp import token_pb2
	client = hprose.HproseClient(r'http://*****/token')
	req = token_pb2.GetTokenRequest(MemberId=1)
	client.GetToken(req)

![image](https://user-images.githubusercontent.com/19922866/43751391-484b61fc-9a2f-11e8-92c9-9b90b8fbd7ee.png)

**Comment by anandolee** [comment]
I can't see what data is used for from your picture after data = vars(obj)

**Comment by anandolee** [comment]
Closing for clean up. Feel free to reopen if it is still an issue
