### ISSUE TITLE
CodedInputStream newInstance is package-private

### ISSUE THREAD

**Issue by deripas** [google/protobuf#5023]
I often have to work with 7bit coding  and found a useful class `CodedInputStream` in 

```xml
        <dependency>
            <groupId>com.google.protobuf</groupId>
            <artifactId>protobuf-java</artifactId>
        </dependency>
```
But method with custom buffer size **NOT public**! 
```java
  /** Create a new CodedInputStream wrapping the given InputStream. */
  static CodedInputStream newInstance(final InputStream input, int bufferSize) {
    if (input == null) {
      // TODO(nathanmittler): Ideally we should throw here. This is done for backward compatibility.
      return newInstance(EMPTY_BYTE_ARRAY);
    }
    return new StreamDecoder(input, bufferSize);
  }
```
Public only method with default buffer size:
```java
  /** Create a new CodedInputStream wrapping the given InputStream. */
  public static CodedInputStream newInstance(final InputStream input) {
    return newInstance(input, DEFAULT_BUFFER_SIZE);
  }
```

### Can you make the method public?

Now I have to use hack:
```java
package com.google.protobuf;

import java.io.InputStream;

public class CodedStreamUtil {

    public static CodedInputStream createInput(final InputStream input, int bufferSize) {
        return CodedInputStream.newInstance(input, bufferSize);
    }
}
```

Thank you.

**Comment by xfxyjwf** [comment]
Specifying a custom buffer size isn't common. Is the InputStream you are working with typically smaller than the default buffer size?

**Comment by deripas** [comment]
For example, I have reader binary message:
```java
stream = CodedInputStream.newInstance(...);
int flags = stream.readUInt32();
// some other header using 7bit
int size = stream.readUInt32();
int type = stream.readUInt32();
byte[] body = stream.readRawBytes(size);
```

I'm try reading message from TCP using Netty and [ReplayingDecoder](https://netty.io/4.0/api/io/netty/handler/codec/ReplayingDecoder.html).

> ReplayingDecoder passes a specialized ByteBuf implementation which throws an Error of certain type when there's not enough data in the buffer. 

`CodedInputStream` try reading 4096 byes (default buffer size), but my data is less.
`ReplayingDecoder`  can read the first message only when it accumulates 4096 bytes.

Current solution: read with single byte buffer:
```java
stream = CodedInputStream.newInstance(input, 1);
```

**Comment by xfxyjwf** [comment]
That would be very inefficient...

It sounds to me you have an incorrect implementation of InputStream. If CodedInputStream tries to read 4096 bytes, shouldn't InputStream give it just the amount it has? If your InputStream throws exception on that, that seems a broken implementation.

**Comment by deripas** [comment]
As an option, I can try reading the current buffer and catching a `InvalidProtocolBufferException` when buffer not yet fully received.
```java
try {
CodedInputStream stream = CodedInputStream.newInstance(bytes);
int flags = stream.readUInt32();
// some other header using 7bit
int size = stream.readUInt32();
int type = stream.readUInt32();
byte[] body = stream.readRawBytes(size);
// read complete    
} catch (InvalidProtocolBufferException e) {
// buffer not ready yet, wait next chunk           
}
```

**Comment by deripas** [comment]
replace using `ReplayingDecoder` to `ByteToMessageDecoder`
```java
 protected void decode(ChannelHandlerContext ctx, ByteBuf in, List<Object> out) throws Exception {
        in.markReaderIndex();
        try {
            CodedInputStream stream = CodedInputStream.newInstance(in.nioBuffer(in.readerIndex(), in.readableBytes()));
            // read data

            in.skipBytes(stream.getTotalBytesRead());
            out.add(binaryPackage);
        } catch (Exception e) {
            in.resetReaderIndex();
        }
    }
```
