### ISSUE TITLE
cannot use `oneof` in proto3-java

### ISSUE THREAD

**Issue by qbj10** [google/protobuf#5057]
```
message myResponse {
    oneof oneof_response {
        ListResponse list_response = 1;
        MetaResponse meta_response = 2;
    }
}

message ListResponse
{
    int32 status = 1;

    repeated List_data data = 7;
}

message MetaResponse
{
     int32 status = 1;
     repeated Meta_data data = 7;
}


```

I got error ' "oneof" is not defined.' with 'protoc-java-3.3.0.exe' and grpc-protobuf-1.14.0.
how to use the `oneof` in java? 
Thanks.

**Comment by xfxyjwf** [comment]
Try your proto here:
https://unpkg.com/google-protocol-compiler/index.html

Here is what I'm getting:
```
foo.proto:test.ListResponse.data: "List_data" is not defined.
foo.proto:test.MetaResponse.data: "Meta_data" is not defined.
```

**Comment by qbj10** [comment]
Thank you for your test page.
The "repeated oneof images = 4;" lead to the mistake, not "oneof oneof_response".

`// .proto file content
syntax = "proto3";
package test;

message List_data {
     int32 type = 1;
     int32 mpid = 2;
}

message Meta_data {
     string resourceid = 1;
     repeated oneof images = 4;
}

message KpListResponse
{
    int32 status = 1;
    repeated List_data data = 7;
}

message KpMetaResponse
{
     int32 status = 1;
     repeated Meta_data data = 7;
}

message KpResponse {
    oneof oneof_response {
        KpListResponse list_response = 1;
        KpMetaResponse meta_response = 2;
    }
}`
