### ISSUE TITLE
JavaNano: Reason for ByteBuffer in CodedOutputByteBufferNano ?

### ISSUE THREAD

**Issue by ennerf** [google/protobuf#511]
Is there a reason why CodedOutputByteBufferNano was switched to use ByteBuffer, but CodedInputByteBufferNano is still working on byte arrays? For our particular use case (many varint types and forced to consume byte[]) the performance dropped quite a bit.

I've uploaded a simple benchmark here (https://gist.github.com/ennerf/45809ef405a4a56a285b). The test value results in a 2 byte varint. It gets worse for larger values.

ByteBuffer vs byte[]:
writeRawLittleEndian32 dropped 19%
writeRawVarint32 dropped 41%

DirectByteBuffer vs byte[]:
writeRawLittleEndian32 gained 38%
writeRawVarint32 dropped 22%

Thanks

**Comment by pherl** [comment]
Closing it now. We are in general in favor of using lite rather than nano since 3.0 release, and don't have plans to further improve javanano.
