### ISSUE TITLE
c# review: Inlining tag sizes

### ISSUE THREAD

**Issue by jtattermusch** [google/protobuf#518]
This has already been merged by #515 to csharp-experimental, but would need a second pass review:
https://github.com/jskeet/protobuf/commit/828b7e61d0443832d99002fbda12a359e5f9f221

**Comment by jtattermusch** [comment]
(I think "size += 1 + pb::CodedOutputStream.ComputeRawVarint32Size((uint) dataSize);" is not very understandable because it's not obvious where the "1" comes from, perhaps we could define constants for tag sizes, but let's address that in a follow-up review).

**Comment by jskeet** [comment]
I think defining constants for the tag sizes would make it even more cluttered. Fundamentally, I'm not expecting people to look at the generated code. It shouldn't be ghastly to read, but I'm not bothered by it being *slightly* obscure. We could certainly document it in a generated code guide though.
