### ISSUE TITLE
Request: implement/add ExtensionRegistry.isEmpty() in Java 

### ISSUE THREAD

**Issue by protobufel** [google/protobuf#52]
It is crucial  to know whether an ExtensionRegistry is empty - for a number of reasons; but impossible at the moment. It could have been  produced as ExtensionRegistry.getEmptyRegistry(), or as the result of  ExtensionRegistry.newInstance(), or ExtensionRegistry.newInstance().getUnmodifiable(), and so forth.
However, there is no access to the underlying map, or its length, and also there is no equals.

**Comment by haberman** [comment]
This feature request is very old. I don't think in general we attempt to give every type an empty/null value that is recognizable. If you want a value to be possibly absent, it seems to make more sense to just make it nullable, instead of making it nonnull but having an "empty" value.
