### ISSUE TITLE
JSON support for C#

### ISSUE THREAD

**Issue by jtattermusch** [google/protobuf#520]

**Comment by jtattermusch** [comment]
Formatting partially implemented by #582

**Comment by jtattermusch** [comment]
Pending: 
-- JSON parsing
-- FieldMask proto has a custom JSON encoding.
-- Formatting of Wrapper types once they become represented by nullable C# types.

**Comment by jskeet** [comment]
Just parsing left, really...

**Comment by jskeet** [comment]
This is now done, other than support for Any which I'll track separately.
