### ISSUE TITLE
Protobuf, GG_ULONGLONG & android ndk

### ISSUE THREAD

**Issue by srenault** [google/protobuf#526]
Trying to compile protobuf using ndk compiler: 

https://github.com/google/protobuf/blob/master/src/google/protobuf/stubs/common.h#L1462

I have got an error saying that 'GG_ULONGLONG' isn't declared.

Alter 'GG_ULONGLONG' to 'GOOGLE_ULONGLONG' actually fix the compile error.

What do you think ?

**Comment by iphydf** [comment]
I think fix it. https://github.com/google/protobuf/blob/master/src/google/protobuf/stubs/common.h#L229 was probably GG_ULONGLONG before.

**Comment by xfxyjwf** [comment]
You guys are right. GG_ULONGLONG should be GOOGLE_ULONGLONG.

**Comment by jmcauley** [comment]
I can confirm that this prevented me from compiling on Windows and that changing it to GOOGLE-ULONGLONG seems to have fixed the issue.

**Comment by iphydf** [comment]
This is now fixed: https://github.com/google/protobuf/commit/ee35402244fc463cedc470baa0f5f1a6080d905d.
