### ISSUE TITLE
Support well known types

### ISSUE THREAD

**Issue by jskeet** [google/protobuf#528]
- (Runtime) Conversions between Timestamp and DateTime
- (Runtime) Conversions between Duration and TimeSpan
- (Runtime) Conversions between wrapper types and nullable types
- (Codegen) Direct of nullable types in generated code
- No enhanced support for Any (yet)
- No enhanced support for Struct (yet)
- No enhanced support for FieldMask (yet)

(We may want to make it easy to create a Struct from a Json.NET JObject, for example. That would probably be in a separate NuGet package.)

**Comment by jskeet** [comment]
Everything listed here is done now. We still need JSON formatting for FieldMask, and support in general for Any, when that's been decided. I don't think this issue is useful any more in itself.

**Comment by rushfrisby** [comment]
Where can I add a conversion between Timestamp and DateTimeOffset? I don't know the code base very well and not sure where to look. Thanks!
