### ISSUE TITLE
error: uninitialized member ‘google::protobuf::util::converter::DataPiece::<anonymous union>::i64_’ with ‘const’ type ‘const google::protobuf::int64’

### ISSUE THREAD

**Issue by xxw345** [google/protobuf#533]
I am compiling on cluster environment I don't have the root permission. So I configure --prefix=~/.usr/local/.
Everything is ok until I make, the errors come out:

libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I.. -pthread -DHAVE_PTHREAD=1 -DHAVE_ZLIB=1 -Wall -Wwrite-strings -Woverloaded-virtual -Wno-sign-compare -O2 -g -DNDEBUG -MT google/protobuf/util/internal/datapiece.lo -MD -MP -MF google/protobuf/util/internal/.deps/datapiece.Tpo -c google/protobuf/util/internal/datapiece.cc  -fPIC -DPIC -o google/protobuf/util/internal/.libs/datapiece.o
In file included from google/protobuf/util/internal/datapiece.cc:31:
./google/protobuf/util/internal/datapiece.h: In constructor ‘google::protobuf::util::converter::DataPiece::DataPiece(google::protobuf::int32)’:
./google/protobuf/util/internal/datapiece.h:79: error: uninitialized member ‘google::protobuf::util::converter::DataPiece::<anonymous union>::i64_’ with ‘const’ type ‘const google::protobuf::int64’
./google/protobuf/util/internal/datapiece.h:79: error: uninitialized member ‘google::protobuf::util::converter::DataPiece::<anonymous union>::u32_’ with ‘const’ type ‘const google::protobuf::uint32’
./google/protobuf/util/internal/datapiece.h:79: error: uninitialized member ‘google::protobuf::util::converter::DataPiece::<anonymous union>::u64_’ with ‘const’ type ‘const google::protobuf::uint64’
./google/protobuf/util/internal/datapiece.h:79: error: uninitialized member ‘google::protobuf::util::converter::DataPiece::<anonymous union>::double_’ with ‘const’ type ‘const double’
./google/protobuf/util/internal/datapiece.h:79: error: uninitialized member ‘google::protobuf::util::converter::DataPiece::<anonymous union>::float_’ with ‘const’ type ‘const float’
./google/protobuf/util/internal/datapiece.h:79: error: uninitialized member ‘google::protobuf::util::converter::DataPiece::<anonymous union>::bool_’ with ‘const’ type ‘const bool’
./google/protobuf/util/internal/datapiece.h: In constructor ‘google::protobuf::util::converter::DataPiece::DataPiece(google::protobuf::int64)’:
./google/protobuf/util/internal/datapiece.h:80: error: uninitialized member ‘google::protobuf::util::converter::DataPiece::<anonymous union>::i32_’ with ‘const’ type ‘const google::protobuf::int32’
./google/protobuf/util/internal/datapiece.h:80: error: uninitialized member ‘google::protobuf::util::converter::DataPiece::<anonymous union>::u32_’ with ‘const’ type ‘const google::protobuf::uint32’
./google/protobuf/util/internal/datapiece.h:80: error: uninitialized member ‘google::protobuf::util::converter::DataPiece::<anonymous union>::u64_’ with ‘const’ type ‘const google::protobuf::uint64’
./google/protobuf/util/internal/datapiece.h:80: error: uninitialized member ‘google::protobuf::util::converter::DataPiece::<anonymous union>::double_’ with ‘const’ type ‘const double’
./google/protobuf/util/internal/datapiece.h:80: error: uninitialized member ‘google::protobuf::util::converter::DataPiece::<anonymous union>::float_’ with ‘const’ type ‘const float’
./google/protobuf/util/internal/datapiece.h:80: error: uninitialized member ‘google::protobuf::util::converter::DataPiece::<anonymous union>::bool_’ with ‘const’ type ‘const bool’
./google/protobuf/util/internal/datapiece.h: In constructor ‘google::protobuf::util::converter::DataPiece::DataPiece(google::protobuf::uint32)’:
./google/protobuf/util/internal/datapiece.h:81: error: uninitialized member ‘google::protobuf::util::converter::DataPiece::<anonymous union>::i32_’ with ‘const’ type ‘const google::protobuf::int32’
./google/protobuf/util/internal/datapiece.h:81: error: uninitialized member ‘google::protobuf::util::converter::DataPiece::<anonymous union>::i64_’ with ‘const’ type ‘const google::protobuf::int64’
./google/protobuf/util/internal/datapiece.h:81: error: uninitialized member ‘google::protobuf::util::converter::DataPiece::<anonymous union>::u64_’ with ‘const’ type ‘const google::protobuf::uint64’
./google/protobuf/util/internal/datapiece.h:81: error: uninitialized member ‘google::protobuf::util::converter::DataPiece::<anonymous union>::double_’ with ‘const’ type ‘const double’
./google/protobuf/util/internal/datapiece.h:81: error: uninitialized member ‘google::protobuf::util::converter::DataPiece::<anonymous union>::float_’ with ‘const’ type ‘const float’
./google/protobuf/util/internal/datapiece.h:81: error: uninitialized member ‘google::protobuf::util::converter::DataPiece::<anonymous union>::bool_’ with ‘const’ type ‘const bool’
./google/protobuf/util/internal/datapiece.h: In constructor ‘google::protobuf::util::converter::DataPiece::DataPiece(google::protobuf::uint64)’:
./google/protobuf/util/internal/datapiece.h:82: error: uninitialized member ‘google::protobuf::util::converter::DataPiece::<anonymous union>::i32_’ with ‘const’ type ‘const google::protobuf::int32’
./google/protobuf/util/internal/datapiece.h:82: error: uninitialized member ‘google::protobuf::util::converter::DataPiece::<anonymous union>::i64_’ with ‘const’ type ‘const google::protobuf::int64’
./google/protobuf/util/internal/datapiece.h:82: error: uninitialized member ‘google::protobuf::util::converter::DataPiece::<anonymous union>::u32_’ with ‘const’ type ‘const google::protobuf::uint32’
./google/protobuf/util/internal/datapiece.h:82: error: uninitialized member ‘google::protobuf::util::converter::DataPiece::<anonymous union>::double_’ with ‘const’ type ‘const double’
./google/protobuf/util/internal/datapiece.h:82: error: uninitialized member ‘google::protobuf::util::converter::DataPiece::<anonymous union>::float_’ with ‘const’ type ‘const float’
./google/protobuf/util/internal/datapiece.h:82: error: uninitialized member ‘google::protobuf::util::converter::DataPiece::<anonymous union>::bool_’ with ‘const’ type ‘const bool’
./google/protobuf/util/internal/datapiece.h: In constructor ‘google::protobuf::util::converter::DataPiece::DataPiece(double)’:
./google/protobuf/util/internal/datapiece.h:83: error: uninitialized member ‘google::protobuf::util::converter::DataPiece::<anonymous union>::i32_’ with ‘const’ type ‘const google::protobuf::int32’
./google/protobuf/util/internal/datapiece.h:83: error: uninitialized member ‘google::protobuf::util::converter::DataPiece::<anonymous union>::i64_’ with ‘const’ type ‘const google::protobuf::int64’
./google/protobuf/util/internal/datapiece.h:83: error: uninitialized member ‘google::protobuf::util::converter::DataPiece::<anonymous union>::u32_’ with ‘const’ type ‘const google::protobuf::uint32’
./google/protobuf/util/internal/datapiece.h:83: error: uninitialized member ‘google::protobuf::util::converter::DataPiece::<anonymous union>::u64_’ with ‘const’ type ‘const google::protobuf::uint64’
./google/protobuf/util/internal/datapiece.h:83: error: uninitialized member ‘google::protobuf::util::converter::DataPiece::<anonymous union>::float_’ with ‘const’ type ‘const float’
./google/protobuf/util/internal/datapiece.h:83: error: uninitialized member ‘google::protobuf::util::converter::DataPiece::<anonymous union>::bool_’ with ‘const’ type ‘const bool’
./google/protobuf/util/internal/datapiece.h: In constructor ‘google::protobuf::util::converter::DataPiece::DataPiece(float)’:
./google/protobuf/util/internal/datapiece.h:84: error: uninitialized member ‘google::protobuf::util::converter::DataPiece::<anonymous union>::i32_’ with ‘const’ type ‘const google::protobuf::int32’
./google/protobuf/util/internal/datapiece.h:84: error: uninitialized member ‘google::protobuf::util::converter::DataPiece::<anonymous union>::i64_’ with ‘const’ type ‘const google::protobuf::int64’
./google/protobuf/util/internal/datapiece.h:84: error: uninitialized member ‘google::protobuf::util::converter::DataPiece::<anonymous union>::u32_’ with ‘const’ type ‘const google::protobuf::uint32’
./google/protobuf/util/internal/datapiece.h:84: error: uninitialized member ‘google::protobuf::util::converter::DataPiece::<anonymous union>::u64_’ with ‘const’ type ‘const google::protobuf::uint64’
./google/protobuf/util/internal/datapiece.h:84: error: uninitialized member ‘google::protobuf::util::converter::DataPiece::<anonymous union>::double_’ with ‘const’ type ‘const double’
./google/protobuf/util/internal/datapiece.h:84: error: uninitialized member ‘google::protobuf::util::converter::DataPiece::<anonymous union>::bool_’ with ‘const’ type ‘const bool’
./google/protobuf/util/internal/datapiece.h: In constructor ‘google::protobuf::util::converter::DataPiece::DataPiece(bool)’:
./google/protobuf/util/internal/datapiece.h:85: error: uninitialized member ‘google::protobuf::util::converter::DataPiece::<anonymous union>::i32_’ with ‘const’ type ‘const google::protobuf::int32’
./google/protobuf/util/internal/datapiece.h:85: error: uninitialized member ‘google::protobuf::util::converter::DataPiece::<anonymous union>::i64_’ with ‘const’ type ‘const google::protobuf::int64’
./google/protobuf/util/internal/datapiece.h:85: error: uninitialized member ‘google::protobuf::util::converter::DataPiece::<anonymous union>::u32_’ with ‘const’ type ‘const google::protobuf::uint32’
./google/protobuf/util/internal/datapiece.h:85: error: uninitialized member ‘google::protobuf::util::converter::DataPiece::<anonymous union>::u64_’ with ‘const’ type ‘const google::protobuf::uint64’
./google/protobuf/util/internal/datapiece.h:85: error: uninitialized member ‘google::protobuf::util::converter::DataPiece::<anonymous union>::double_’ with ‘const’ type ‘const double’
./google/protobuf/util/internal/datapiece.h:85: error: uninitialized member ‘google::protobuf::util::converter::DataPiece::<anonymous union>::float_’ with ‘const’ type ‘const float’
./google/protobuf/util/internal/datapiece.h: In constructor ‘google::protobuf::util::converter::DataPiece::DataPiece(google::protobuf::StringPiece)’:
./google/protobuf/util/internal/datapiece.h:86: error: uninitialized member ‘google::protobuf::util::converter::DataPiece::<anonymous union>::i32_’ with ‘const’ type ‘const google::protobuf::int32’
./google/protobuf/util/internal/datapiece.h:86: error: uninitialized member ‘google::protobuf::util::converter::DataPiece::<anonymous union>::i64_’ with ‘const’ type ‘const google::protobuf::int64’
./google/protobuf/util/internal/datapiece.h:86: error: uninitialized member ‘google::protobuf::util::converter::DataPiece::<anonymous union>::u32_’ with ‘const’ type ‘const google::protobuf::uint32’
./google/protobuf/util/internal/datapiece.h:86: error: uninitialized member ‘google::protobuf::util::converter::DataPiece::<anonymous union>::u64_’ with ‘const’ type ‘const google::protobuf::uint64’
./google/protobuf/util/internal/datapiece.h:86: error: uninitialized member ‘google::protobuf::util::converter::DataPiece::<anonymous union>::double_’ with ‘const’ type ‘const double’
./google/protobuf/util/internal/datapiece.h:86: error: uninitialized member ‘google::protobuf::util::converter::DataPiece::<anonymous union>::float_’ with ‘const’ type ‘const float’
./google/protobuf/util/internal/datapiece.h:86: error: uninitialized member ‘google::protobuf::util::converter::DataPiece::<anonymous union>::bool_’ with ‘const’ type ‘const bool’
./google/protobuf/util/internal/datapiece.h: In constructor ‘google::protobuf::util::converter::DataPiece::DataPiece(google::protobuf::StringPiece, bool)’:
./google/protobuf/util/internal/datapiece.h:90: error: uninitialized member ‘google::protobuf::util::converter::DataPiece::<anonymous union>::i32_’ with ‘const’ type ‘const google::protobuf::int32’
./google/protobuf/util/internal/datapiece.h:90: error: uninitialized member ‘google::protobuf::util::converter::DataPiece::<anonymous union>::i64_’ with ‘const’ type ‘const google::protobuf::int64’
./google/protobuf/util/internal/datapiece.h:90: error: uninitialized member ‘google::protobuf::util::converter::DataPiece::<anonymous union>::u32_’ with ‘const’ type ‘const google::protobuf::uint32’
./google/protobuf/util/internal/datapiece.h:90: error: uninitialized member ‘google::protobuf::util::converter::DataPiece::<anonymous union>::u64_’ with ‘const’ type ‘const google::protobuf::uint64’
./google/protobuf/util/internal/datapiece.h:90: error: uninitialized member ‘google::protobuf::util::converter::DataPiece::<anonymous union>::double_’ with ‘const’ type ‘const double’
./google/protobuf/util/internal/datapiece.h:90: error: uninitialized member ‘google::protobuf::util::converter::DataPiece::<anonymous union>::float_’ with ‘const’ type ‘const float’
./google/protobuf/util/internal/datapiece.h:90: error: uninitialized member ‘google::protobuf::util::converter::DataPiece::<anonymous union>::bool_’ with ‘const’ type ‘const bool’
./google/protobuf/util/internal/datapiece.h: In copy constructor ‘google::protobuf::util::converter::DataPiece::DataPiece(const google::protobuf::util::converter::DataPiece&)’:
./google/protobuf/util/internal/datapiece.h:92: error: uninitialized member ‘google::protobuf::util::converter::DataPiece::<anonymous union>::i32_’ with ‘const’ type ‘const google::protobuf::int32’
./google/protobuf/util/internal/datapiece.h:92: error: uninitialized member ‘google::protobuf::util::converter::DataPiece::<anonymous union>::i64_’ with ‘const’ type ‘const google::protobuf::int64’
./google/protobuf/util/internal/datapiece.h:92: error: uninitialized member ‘google::protobuf::util::converter::DataPiece::<anonymous union>::u32_’ with ‘const’ type ‘const google::protobuf::uint32’
./google/protobuf/util/internal/datapiece.h:92: error: uninitialized member ‘google::protobuf::util::converter::DataPiece::<anonymous union>::u64_’ with ‘const’ type ‘const google::protobuf::uint64’
./google/protobuf/util/internal/datapiece.h:92: error: uninitialized member ‘google::protobuf::util::converter::DataPiece::<anonymous union>::double_’ with ‘const’ type ‘const double’
./google/protobuf/util/internal/datapiece.h:92: error: uninitialized member ‘google::protobuf::util::converter::DataPiece::<anonymous union>::float_’ with ‘const’ type ‘const float’
./google/protobuf/util/internal/datapiece.h:92: error: uninitialized member ‘google::protobuf::util::converter::DataPiece::<anonymous union>::bool_’ with ‘const’ type ‘const bool’
./google/protobuf/util/internal/datapiece.h: In constructor ‘google::protobuf::util::converter::DataPiece::DataPiece(google::protobuf::util::converter::DataPiece::Type, google::protobuf::int32)’:
./google/protobuf/util/internal/datapiece.h:155: error: uninitialized member ‘google::protobuf::util::converter::DataPiece::<anonymous union>::i64_’ with ‘const’ type ‘const google::protobuf::int64’
./google/protobuf/util/internal/datapiece.h:155: error: uninitialized member ‘google::protobuf::util::converter::DataPiece::<anonymous union>::u32_’ with ‘const’ type ‘const google::protobuf::uint32’
./google/protobuf/util/internal/datapiece.h:155: error: uninitialized member ‘google::protobuf::util::converter::DataPiece::<anonymous union>::u64_’ with ‘const’ type ‘const google::protobuf::uint64’
./google/protobuf/util/internal/datapiece.h:155: error: uninitialized member ‘google::protobuf::util::converter::DataPiece::<anonymous union>::double_’ with ‘const’ type ‘const double’
./google/protobuf/util/internal/datapiece.h:155: error: uninitialized member ‘google::protobuf::util::converter::DataPiece::<anonymous union>::float_’ with ‘const’ type ‘const float’
./google/protobuf/util/internal/datapiece.h:155: error: uninitialized member ‘google::protobuf::util::converter::DataPiece::<anonymous union>::bool_’ with ‘const’ type ‘const bool’
make[2]: *** [google/protobuf/util/internal/datapiece.lo] Error 1

**Comment by xfxyjwf** [comment]
What's the version of the compiler you are using? I guess we can just remove "const" for these union fields.

**Comment by cjdrake** [comment]
I have seen the exact same error while using a Centos-6 machine.

```
$ gcc --version
gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-11)
Copyright (C) 2010 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by akshaypinto** [comment]
Also see these errors on sl 6.5 running gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-11)

**Comment by nslay** [comment]
Check in datapiece.h. Look for a union with above the named variables.

Remove the 'const' keyword from all members. While making those members const seems nice and readable, I don't think it matters in practice.

This happens in VS 2010 too.

**Comment by blueelwang** [comment]
I also see  these errors while using a Centos-6.6 machine
And gcc version:
gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-11)

**Comment by xxw345** [comment]
$ cat /etc/*-release
CentOS release 6.6 (Final)
LSB_VERSION=base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch:graphics-4.0-amd64:graphics-4.0-noarch:printing-4.0-amd64:printing-4.0-noarch
CentOS release 6.6 (Final)
CentOS release 6.6 (Final)

gcc --version
gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-11)
Copyright (C) 2010 Free Software Foundation, Inc.

Add I git clone a previous version of protobuf to avoid such error

**Comment by LouisLang** [comment]
Works after upgrading to GCC 4.9.1

**Comment by pbor** [comment]
well, upgrading the compiler is not really an option on stable systems...

**Comment by ShanJunjie** [comment]
I had the same problem.

cat /etc/*-release
LSB_VERSION=base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch
Red Hat Enterprise Linux Server release 6.5 (Santiago)
Red Hat Enterprise Linux Server release 6.5 (Santiago)

cat /etc/*-release
LSB_VERSION=base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch
Red Hat Enterprise Linux Server release 6.5 (Santiago)
Red Hat Enterprise Linux Server release 6.5 (Santiago)

I tried gcc 4.9.0. It worked, but the generated dynamic library couldn't be linked with other libraries. 
Still search how to resolve this problem.

**Comment by hhflying** [comment]
Had the same error in centos-6.6 with gcc 4.4.7.

After removing the const keywords in datapiece.h, the problem was gone.

**Comment by neilzhuo** [comment]
resolve the problem after do below.
Change:
195   union {
196     const int32 i32_;
197     const int64 i64_;
198     const uint32 u32_;
199     const uint64 u64_;
200     const double double_;
201     const float float_;
202     const bool bool_;
203     StringPiecePod str_;
204   };

To:
195   union {
196     int32 i32_;
197     int64 i64_;
198     uint32 u32_;
199     uint64 u64_;
200     double double_;
201     float float_;
202     bool bool_;
203     StringPiecePod str_;
204   };
