### ISSUE TITLE
Fix make distcheck for C#

### ISSUE THREAD

**Issue by jskeet** [google/protobuf#541]
The C# experimental branch fails the Travis "distcheck" build, because `Makefile.am` contains a bunch of references to files that don't exist.

Rather than hand-editing `Makefile.am` every time we add or remove a file from the protobuf runtime, we should automate it... but I don't want that to gate other feature work.

**Comment by jtattermusch** [comment]
I used the following script to generate the file list for csharp_EXTRA_DIST.
Not adding this as a script under csharp/ as the result needs to be pasted to Makefile.am manually (after removing the final backslash)

````
git ls-files csharp | grep -v .gitignore | awk '{ printf "  %-75s\\\n", $0 }'
```
