### ISSUE TITLE
The master branch and the v3.0.0-alpha-3 release cannot be compiled with the GOOGLE_PROTOBUF_NO_THREAD_SAFETY flag

### ISSUE THREAD

**Issue by waliwali** [google/protobuf#548]

**Comment by abigailbunyan** [comment]
This is also the case with v2.6.1, and has been spotted previously here: https://groups.google.com/forum/#!topic/protobuf/poWwsDDUWYk

I'm about to make a pull request to fix this.

**Comment by davebranton** [comment]
This is still an issue with the latest 3.1.2 release. It appears that GOOGLE_PROTOBUF_NO_THREAD_SAFETY is simply no longer supported - in particular the arena allocator uses the atomic operations extensively.

I've modified my local copy to build, should I submit a patch, or is this being worked on?

**Comment by acozzette** [comment]
@davebranton I'm not aware of anyone else actively working on this, so feel free to send a pull request if you have a fix for it.
