### ISSUE TITLE
Error in utility.cc, invalid identifier ::isnan(value)

### ISSUE THREAD

**Issue by jmcauley** [google/protobuf#553]
line 304 of utility.cc

if(::isnan(value))  return "NaN";

should be

if(std::isnan(value)) return "NaN";

**Comment by xfxyjwf** [comment]
std::isnan is from C++11. We probably should change that to MathLimits<double>::IsNan(value).

**Comment by nslay** [comment]
Also, please use MathLimits::IsFinite() instead of isfinite(). isfinite() does not exist in VS 2008 or 2010.
