### ISSUE TITLE
makeImmutable() and isMutable() symbol not found for protobuf 3 maps

### ISSUE THREAD

**Issue by ohad7** [google/protobuf#558]
I'm getting a "symbol not found" compilation in the java compiler of protobuf-alpha-3. It is complaining that it can't find makeImmutable and isMutable. Here's the proto that I'm using : 

```
message Query {
    enum Sort {
        ASC = 0;
        DESC = 1;
    }
    map<string, StringList> criteria = 1;
    string sort_by = 2;
    uint32 limit = 3;
    uint32 start = 4;
    Sort sort = 5;
}
```

And getting this error while compiling it for Java : 

```
Query.java:544: error: cannot find symbol
      result.criteria_.makeImmutable();
                      ^
  symbol:   method makeImmutable()
  location: variable criteria_ of type MapField<String,StringList>

Query.java:624: error: cannot find symbol
      if (!criteria_.isMutable()) {
                    ^
  symbol:   method isMutable()
  location: variable criteria_ of type MapField<String,StringList>
```

This is the gradle build settings that I'm using : 

```
apply plugin: 'com.google.protobuf'

buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath 'com.google.protobuf:protobuf-gradle-plugin:0.4.1'
    }
}

protocDep = "com.google.protobuf:protoc:3.0.0-alpha-3"
```
Not getting this error with 3.0.0-alpha-2.

**Comment by xfxyjwf** [comment]
I guess it's that the protobuf runtime you are using is version "3.0.0-alpah-2". Could you check?

**Comment by ohad7** [comment]
I use the same version for compilation and for runtime. In this case I haven't got to runtime since compilation is failing on the maps. When I use 3.0.0-alpha-2 everything works, but once I switch to alpha-3 I get this compilation error

Perhaps I'm misunderstanding you though.

**Comment by xfxyjwf** [comment]
What I meant is the protobuf library version you are compiling the generated code against with. Something like: com.google.protobuf:protobuf-java:3.0.0-alpha-3 in your gradle file. The makeImmutable() methods are added in alpha-3, so I suspect you are compiling the code against protobuf-java:3.0.0-alpha-2.

**Comment by xfxyjwf** [comment]
Note that com.google.protobuf:protoc and com.google.protobuf:protobuf-java are separate artifacts. You need to use the same version for these two.

**Comment by andremann** [comment]
I get the same error when compiling with alpha-3.1. I get the compiler work only with alpha-2.
Tested with Maven with configuration:
```
<configuration>
	<protocArtifact>com.google.protobuf:protoc:3.0.0-alpha-3.1:exe:${os.detected.classifier}</protocArtifact>
	<pluginId>grpc-java</pluginId>
	<pluginArtifact>io.grpc:protoc-gen-grpc-java:0.7.1:exe:${os.detected.classifier}</pluginArtifact>
</configuration>
```

**Comment by xfxyjwf** [comment]
If you get such errors, it's likely that the protoc plugin version doesn't match the protobuf java runtime version. Please ensure they are the same.
