### ISSUE TITLE
google.protobuf.Duration definition

### ISSUE THREAD

**Issue by dcarp** [google/protobuf#559]
Considering that negative durations are very common, defining members as signed should be more space-efficient.

```protobuf
message Duration {
  sint64 seconds = 1;
  sint32 nanos = 2;
}
```

**Comment by xfxyjwf** [comment]
Hi @dcarp, although I think this is a good suggestion, the definition of these proto types are pretty much set in stone now. They are already used in production servers inside Google and we cannot afford changing it in an wire-incompatible way.
