### ISSUE TITLE
C++: setter functions should return self reference

### ISSUE THREAD

**Issue by feiyunw** [google/protobuf#562]
For example:
message Person {
string name = 1;
int32 id = 2;
...
}
C++ setter functions should have the self-class referece as their return values:
inline Person& Person::set_name(...) { ...; return *this; };
inline Person& Person::set_id(...) { ...; return *this; };

Thus, we can set all fields in one line:
Person person;
person.set_name("Alice").set_id(1);

It will be more useful with more fields.

**Comment by arhad** [comment]
What is a real reason for this proposal? As I know, the only kind of functions in C++ that should return a reference to invoked instance are assignment operators, e. g. copy-assignment and move-assignment ones. So any other function must return either a result or nothing.

I agree that some languages greet invocation chains, but C++ is not this case.

**Comment by ChrisJefferson** [comment]
@arhad : There is nothing wrong with invocation chains, and certainly no rule that they are "forbidden" in C++. They are indeed less common than in other languages, but you can find them in popular C++ libraries such as 'boost'.

I'm not saying if they should be added here, but I don't think it is a terrible idea.

**Comment by xfxyjwf** [comment]
For C++ setters, the more conventional way is for them to return void. It's not worthwhile to change the API to support chaining.
