### ISSUE TITLE
Can't find old binary releases

### ISSUE THREAD

**Issue by darrint** [google/protobuf#572]
According to this page:

https://developers.google.com/protocol-buffers/docs/downloads

I should be able access the old googlecode site to download old binary releases. The links on that page no longer work. I'd like to download protoc for windows 2.4.1.

**Comment by xfxyjwf** [comment]
You can find it here: https://github.com/google/protobuf/releases/tag/v2.4.1

I guess we should remove the link to googlecode because it now just redirects back to github.

**Comment by darrint** [comment]
Thanks!

It wouldn't hurt to update the developers page at google to show how to get there.
