### ISSUE TITLE
Protoc 2.6.1 - Unrecognized syntax identifier "proto3".  This parser only recognizes "proto2".

### ISSUE THREAD

**Issue by AppVineyard** [google/protobuf#579]
I've been trying to setup an 'EC2 - g2.2xlarge' environment to do some "deep dream" testing and utilize the nvidia CUDA GPU benefits. Problem is I can't get past the setup for protobuf in python. I've followed the instruction all the way the point of :

4) Build and run the tests:

`$ python setup.py build`

The problem is I get the following output when I run the command above:

Terminal Log:
>(venv)ubuntu@ip-XXXX:~/protobuf/protobuf-3.0.0-alpha-3/python$ protoc --version
>libprotoc 2.6.1
>(venv)ubuntu@ip-XXXX:~/protobuf/protobuf-3.0.0-alpha-3/python$ python setup.py build
>running build
>running build_py
>Generating google/protobuf/map_unittest_pb2.py...
>google/protobuf/map_unittest.proto:31:10: Unrecognized syntax identifier "proto3".  This parser only >recognizes "proto2".
>(venv)ubuntu@ip-XXXX:~/protobuf/protobuf-3.0.0-alpha-3/python$

I can't figure out for the life of me what is causing the problem. I read on other websites similar problems but no solutions except for "Your protoc is out of date. You need to update it."  From what I know version 2.6.1 is the latest version.....therefore I am stumped. Apprecaite any help or insight anyone has.

**Comment by skybrian** [comment]
protoc 2.6.1 is the latest *stable* version, but it won't work. It doesn't support the "proto3" language yet. You need to use an alpha release of protoc 3.0. (I don't think Ubuntu has it yet so maybe you need to compile it from source?)

**Comment by AppVineyard** [comment]
Oh thay makes more sense. @skybrian

Is there a tutuorial on how to compile from the source?

**Comment by AppVineyard** [comment]
Actually nevermind I figured it out. Thanks for the insight @skybrian

**Comment by nitinkash** [comment]
@AppVineyard I am having the same issue, could you please help me out as to what you did to solve the issue.

**Comment by collectvic** [comment]
I have the same issue , have you got the solution?

**Comment by collectvic** [comment]
Hello, we can this page to find the solution:  https://github.com/google/protobuf/issues/368#issue-75644957

**Comment by shahbhoomi** [comment]
Hi i am having the same error "Unrecognized syntax identifier "proto3".  This parser only recognizes "proto2"." while doing this:
To generate the client and server side interfaces:

$ ./run_codegen.sh
Which internally invokes the protocol buffer compiler as:

$ protoc -I ../../protos --python_out=. --grpc_out=. --plugin=protoc-gen-grpc=`which grpc_python_plugin` ../../protos/helloworld.proto

Did anyone find the solution and can help me please?

**Comment by skybrian** [comment]
If you want to use proto3, you will need to upgrade your protobuf software to version 3. For a Mac you can get it from here:

https://github.com/google/protobuf/releases

It may also be available through Homebrew or Linux distros.

**Comment by SravyaKeerthana** [comment]
Hi,

On the Compilation of openairinterface develop-nb-iot branch,the following errors are occurring:

The commands used after downloading the develop branch:

cd openairinterface-develop-nb-iot
source oaienv
cd  cmake_targets
./build_oai -I

Error:

t/issue330/issue330.proto:1:10: Unrecognized syntax identifier "proto3".  This parser only recognizes "proto2".
Makefile:2417: recipe for target 't/issue330/issue330.pb-c.h' failed
make: *** [t/issue330/issue330.pb-c.h] Error 1
make: *** Waiting for unfinished jobs....
t/issue330/issue330.proto:1:10: Unrecognized syntax identifier "proto3".  This parser only recognizes "proto2".
Makefile:2417: recipe for target 't/issue330/issue330.pb-c.c' failed
make: *** [t/issue330/issue330.pb-c.c] Error 1

The errors are occuring while it is trying to compile the protobuf-c of version 2.6.1
What can be the solution?

regards,
Sravya Keerthana R

**Comment by acozzette** [comment]
@SravyaKeerthana You will need to use protoc 3.0 or higher if you're working with .proto files that have `syntax = "proto3"`.

**Comment by SravyaKeerthana** [comment]
Can I know how to update the protoc version from 2.6.1 to protoc 3.0 ?
