### ISSUE TITLE
"undefined reference to `google::protobuf::internal::Release_Store" PowerPC cross compiling

### ISSUE THREAD

**Issue by zzzlodey** [google/protobuf#581]
Hi All!

I'm using protobuf-2.6.1 and I would like to make cross compiling for PowerPC e300c3.

==
export CC=powerpc-e300c3-linux-gnu-c++
export CXX=powerpc-e300c3-linux-gnu-g++

./configure --host=powerpc-e300c3-linux --with-protoc=/home/user/protobuf-2.6.1/prev_x86_dir/protoc --prefix=/home/user/protobuf-2.6.1/new_ppc_dir/
&&
make

==

But I get these errors:

==
...
/bin/bash ../libtool  --tag=CXX   --mode=link powerpc-e300c3-linux-gnu-g++ -pthread -Wall -Wwrite-strings -Woverloaded-virtual -Wno-sign-compare -O2 -g -DNDEBUG -pthread  -o protoc google/protobuf/compiler/main.o -lpthread libprotobuf.la libprotoc.la -lz 
libtool: link: powerpc-e300c3-linux-gnu-g++ -pthread -Wall -Wwrite-strings -Woverloaded-virtual -Wno-sign-compare -O2 -g -DNDEBUG -pthread -o .libs/protoc google/protobuf/compiler/main.o  -lpthread ./.libs/libprotobuf.so ./.libs/libprotoc.so -lz -pthread -Wl,-rpath -Wl,/home/zzzlodey/Dropbox/Микран/TRUNK/SnmpAgent++/protobuf-2.6.1/install_dir_ppc/lib
./.libs/libprotobuf.so: undefined reference to `google::protobuf::internal::Release_Store(int volatile*, int)'
./.libs/libprotobuf.so: undefined reference to `google::protobuf::internal::Acquire_CompareAndSwap(int volatile*, int, int)'
./.libs/libprotobuf.so: undefined reference to `google::protobuf::internal::Acquire_Load(int const volatile*)'
collect2: ld returned 1 exit status
make[3]: *** [protoc] Error 1
make[3]: Leaving directory `/home/user/protobuf-2.6.1/src'
make[2]: *** [all] Error 2
make[2]: Leaving directory `/home/user/protobuf-2.6.1/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/user/protobuf-2.6.1/protobuf-2.6.1'
make: *** [all] Error 2
==

What I'm doing wrong???

Thanks!

Oleg

**Comment by xfxyjwf** [comment]
It seems our atomicops implementation does not support the platform you are targeting. You probably need to update [atomicopts.h](https://github.com/google/protobuf/blob/master/src/google/protobuf/stubs/atomicops.h) to add support for your platform.

**Comment by bsilver8192** [comment]
I have a powerpc atomicops implementation which seems to work, but it's hard to test that kind of thing. Does it make sense for me to submit a pull request with it?

**Comment by xfxyjwf** [comment]
Yes, please help submit a pull request for this.
