### ISSUE TITLE
Fails to build in 64bit mode on Solaris

### ISSUE THREAD

**Issue by meltahan** [google/protobuf#585]
In the platform_macros.h file, SOLARIS_64BIT_ENABLED is always undefined regardless of the --enable-64bit-solaris config flag

**Comment by xfxyjwf** [comment]
Could you help fix the issue in platform_macros.h? We don't work on Solaris machines and have to rely on our users to help fixing problems there.

**Comment by meltahan** [comment]
I was thinking of how to fix this.. The problem is SOLARIS_64BIT_ENABLED is defined in config.h, and including config.h in platform_macros.h is not a good idea as it'll create macro names collisions with any other project including platform_macros.h or any other protobuf files that include it.

**Comment by xfxyjwf** [comment]
We had removed the use of config.h as it doesn't fit into the bazel build system. Is there any other predefined macros we can use here to distinguish between 64bit and 32bit on Solaris?

**Comment by meltahan** [comment]
You can check for 64-bit on Solaris:
#if defined(__sparc_v9__) || defined(__sparcv9) || defined(__arch64__)

But you gotta get rid of the --enable-64bit-solaris flag as it won't make sense anymore

**Comment by xfxyjwf** [comment]
Thanks. That seems to be the way to go. Could you send a PR for this?

**Comment by meltahan** [comment]
Sure. So to avoid breaking any existing auto build scripts that provide this --enable-64bit-solaris configure flag, should i just add a note saying it's deprecated and ignored?

**Comment by xfxyjwf** [comment]
It seems --enable-64bit-solaris does more than just adding the SOLARIS_64BIT_ENABLED macro (it adds -m64 to the C++ compiler arguments)? If so we probably don't want to remove it from the configure files.

**Comment by meltahan** [comment]
Yes i noticed that. There are a few issues with it though. It appends the -m64 flag to CXXFLAGS and CFLAGS only if they were not provided by the user (users can provide these flags for purposes other than building a 64/32 bit build). It also doesn't add the -m64 flag to the LDFLAGS. I'll fix these issues and submit a PR that will make the --enable-64bit-solaris flag work properly.

**Comment by meltahan** [comment]
Do you require a CLA from contributors?

**Comment by xfxyjwf** [comment]
@meltahan yes. When you send the pull request, a @googlebot will check your CLA and give instructions if you haven't signed it yet.

**Comment by motahan** [comment]
Finally the CLA issues are resolved. I'll submit a PR soon.
