### ISSUE TITLE
How to use release protobuf 3.0.0-alpha-3?

### ISSUE THREAD

**Issue by Michael-Hamburger** [google/protobuf#589]
Hello!

I am writing a Blender-Add-On in **Python** which needs to communicate with a **C++**-Application. The Blender-Add-On is creating a 3D Gemoetry and the C++-Application is creating some textures for it. For IPC I found protobuf and would like to use it (http://stackoverflow.com/questions/6915191/simple-ipc-between-c-and-python-cross-platform).

I searched for protobuf and found the github-repo and the google dev-page. The examples look straight forward and are easy to understand. Now I thought I will try a simple example for Python and C++.
So far, so good...

I am using **Visual Studio 2013 Community, Windows 8.1 x64 and python 3**. I found out that protobuf v3 (alpha) supports python 3. So I think I need to compile it for python myself? (afaik on the google dev-page I can only download protobuf 2.6). 
I also found https://github.com/google/protobuf/releases/tag/v3.0.0-alpha-3

There is a release for python and for cpp. Can I use them instead of compiling it myself?
How do I use the protobuf-python-3.0.0-alpha-3.zip release correctly? The README says that I should build and run the tests. If I do *python setup.py test* then I get the error that Visual C++ 10.0 is required (which is Visual Studio 2010). After googling I found that the same error comes when building something for python 2.7. Do I really need to install VS 2010 for that? Can I skip build and run tests?

Sorry if that are really basic questions but I am stuck and would love to use a simple interchange format instead of creating my own.

Thanks!

**Comment by TeBoring** [comment]
For protoc compiler, you don't need to compile it by your self. Just
download it from
https://github.com/google/protobuf/releases/download/v3.0.0-alpha-3/protoc-3.0.0-alpha-3-win32.zip
For python runtime, you can download the egg from
https://pypi.python.org/pypi/protobuf/3.0.0a3

2015-07-11 5:26 GMT-07:00 Michael <notifications@github.com>:

**Comment by Michael-Hamburger** [comment]
The py version of the python runtime egg is for 2.7. Is it compatible to 3.x?

Am I right that I need to build the libprotobuf.lib and to link it to use protobuf in a c++-applic

Am I right that I need to build the libprotobuf.lib and to link it to use protobuf in a c++-application?

**Comment by TeBoring** [comment]
To my understanding, protobuf is not fully compatible to 3.x yet. @haberman
to confirm.
To use c++ implementation, you need to build libprotobuf. However, the
python c++ implementation is not supported in windows. I am not sure it can
work.

2015-07-11 6:11 GMT-07:00 Michael <notifications@github.com>:

**Comment by Michael-Hamburger** [comment]
Looks like it's working!

I was able to create a Visual Studio 2013 project, which uses libprotobuf and creates a person (from the addressbook-example on the google-dev-page). I serialize the person to a file on the harddisk, load the file in python via open and call the ParseFromString().

Why do you say that the python c++ implementation is not supported in windows?
There is a vsprojects-folder which aims directly to visual studio and windows? Maybe I just don't understand what you mean.

Thanks again!

**Comment by TeBoring** [comment]
2015-07-11 7:37 GMT-07:00 Michael <notifications@github.com>:

> Looks like it's working!
>
> I was able to create a Visual Studio 2013 project, which uses libprotobuf
> and creates a person (from the addressbook-example on the google-dev-page).
> I serialize the person to a file on the harddisk, load the file in python
> via open and call the ParseFromString().
>
> Why do you say that the python c++ implementation is not supported in
> windows?
>
We didn't test c++ implementation on windows. So I am not sure whether it
can work. We will make sure we test it in future release.
