### ISSUE TITLE
protoc doesn't support files starting with Byte order marks.

### ISSUE THREAD

**Issue by jtattermusch** [google/protobuf#592]
Trying to compile .proto file starting with unicode byte order mark ( U+FEFF character) results in an error.

This is extremely painful in Visual Studio, which saves all files with a byteorder mark, so basically every .proto file that you write in Visual Studio editor will be considered broken by protoc.

The error message is also not very helpful:
health.proto:1:1: Interpreting non ascii codepoint 239.
[libprotobuf WARNING google/protobuf/compiler/parser.cc:491] No syntax specified
 for the proto file. Please use 'syntax = "proto2";' or 'syntax = "proto3";' to
specify a syntax version. (Defaulted to proto2 syntax.)
health.proto:1:1: Expected top-level statement (e.g. "message").
health.proto:1:2: Interpreting non ascii codepoint 187.
health.proto:1:3: Interpreting non ascii codepoint 191.

**Comment by jtattermusch** [comment]
@anandolee, I was hoping you could take a look at this. If you are too busy, feel free to assign me and I will try to find some time to address this.

@jskeet  FYI (I think we've mentioned this problem once somewhere).

**Comment by anandolee** [comment]
It is not only related to C#, parser.cc will be changed to support BOM?
@pherl do you think we should support .proto files starting with BOA?

**Comment by chai2010** [comment]
I think the .proto file is a UTF8 encoding file, withnot BOM.
The `protoc` is not a editor, don't need support invalid .proto file format.

**Comment by jtattermusch** [comment]
as @anandolee suggested, this is basically a question which encodings should be considered valid for .proto file. If we don't support 0xfeff mark at the beginning of the proto file, we are making life harder for Visual Studio users.

**Comment by xfxyjwf** [comment]
Protobuf only support utf-8 encoded files, but I can see it's a pain to deal with BOM added automatically by visual studio. I would vote for updating our parser to ignore BOM.

**Comment by anandolee** [comment]
Will update our parser to ignore BOM

**Comment by jtattermusch** [comment]
Thanks!
