### ISSUE TITLE
Google Protobuf 2.6.1 fails to build on Mac

### ISSUE THREAD

**Issue by poonamchawla** [google/protobuf#597]
Compiler Information:
Apple LLVM version 5.1 (clang-503.0.40) (based on LLVM 3.4svn)
Target: x86_64-apple-darwin13.4.0
Thread model: posix
Compiling Protobuf 2.6.1 on Mac gives the following error message

In file included from ./include/gtest/internal/gtest-param-util.h:47:
./include/gtest/gtest-printers.h:777:31: error: no template named 'tuple_element' in namespace 'std::tr1'; did you mean 'std::tuple_element'?
    UniversalPrinter<typename ::std::tr1::tuple_element<N - 1, Tuple>::type>
                              ^~~~~~~~~~~~~~~~~~~~~~~~~
                              std::tuple_element
/Applications/Xcode5.1.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/c++/v1/__tuple_03:23:62: note: 'std::tuple_element' declared here
template <size_t _Ip, class _Tp> class _LIBCPP_TYPE_VIS_ONLY tuple_element;
                                                             ^
In file included from src/gtest-all.cc:39:
In file included from ./include/gtest/gtest.h:62:
In file included from ./include/gtest/gtest-param-test.h:192:
In file included from ./include/gtest/internal/gtest-param-util.h:47:
./include/gtest/gtest-printers.h:810:31: error: no template named 'tuple_element' in namespace 'std::tr1'; did you mean 'std::tuple_element'?
    UniversalPrinter<typename ::std::tr1::tuple_element<0, Tuple>::type>::
                              ^~~~~~~~~~~~~~~~~~~~~~~~~
                              std::tuple_element
/Applications/Xcode5.1.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/c++/v1/__tuple_03:23:62: note: 'std::tuple_element' declared here
template <size_t _Ip, class _Tp> class _LIBCPP_TYPE_VIS_ONLY tuple_element;

**Comment by jakirkham** [comment]
Seeing similar issues with TR1. In particular, seeing this in the `v3.0.0-beta-2` release.

**Comment by xfxyjwf** [comment]
FYI. The latest version (3.2.0) starts to enable C++11 by default.

**Comment by jakirkham** [comment]
That's going to cause problems if anyone wants to build protobuf for Python 2.7 on Windows as one is restricted to using VS 2008, which does not have C++11 support.

**Comment by xfxyjwf** [comment]
@jakirkham python requires vs 2008? Can you give more details here?

**Comment by xfxyjwf** [comment]
@jakirkham If for any reason your project still require protobuf to stay pre-C++11, please reply to https://github.com/google/protobuf/issues/2780 where we are collecting feedback about moving to C++11.

**Comment by jakirkham** [comment]
Alright, I have tried to clarify this in [comment]( https://github.com/google/protobuf/issues/2780#issuecomment-286227582 ). That said, I do not spend much time personally with Windows compared to others. I'll see if I can get some other Windows users to take a look.
