### ISSUE TITLE
Rename Google.ProtocolBuffers directories and projects to Google.Protobuf

### ISSUE THREAD

**Issue by jtattermusch** [google/protobuf#600]
We have a bit of a debt here. This has no impact to fuctionality (because the resulting assembly is already named Google.Protobuf and so are the namespaces, but later this will be really hard to change, so why don't keep things clean.

@jskeet  opinions?

**Comment by jskeet** [comment]
Which directories do you mean? `src/ProtocolBuffers` and `src/ProtocolBuffers.Test`? If so, I'd been thinking the same thing.

I'd be happy enough to rename the directories to `Google.Protobuf` and `Google.Protobuf.Tests`.

**Comment by jtattermusch** [comment]
Currently we don't have any pull requests against C# code, so if you don't have any pending work in your fork, it's probably a good time to do this now. Let me know if you want me to create the PR, I am happy to do so.

**Comment by jskeet** [comment]
I have quite a chunk of pending work on wrapper types, which is nowhere near ready to create a PR for yet :(

That's *all* I currently have up in the air though - how about we get that done, and then I address that before anything new? Or we could just do it now and I'll clear up as best I can...

**Comment by jtattermusch** [comment]
I will leave it up to you, as you're the one affected by this the most.

**Comment by jtattermusch** [comment]
@jskeet, do you have any other in-progress code besides #611?

It looks like after some of my PR get merged (hopefully today), this would be the last thing blocking merging csharp-experimental to master.

**Comment by jskeet** [comment]
No, #611 is it for now. If we can get that in - even if more work is required - that would be a great time to do the rename.

We should also look at addressbook.proto before merging though - I suspect I've broken the Java and C++ code there. See #565

**Comment by jskeet** [comment]
Right, now I have no more pending code, I'm on this.

**Comment by jtattermusch** [comment]
Looks like this was done
