### ISSUE TITLE
google::protobuf::internal::empty_string_ error

### ISSUE THREAD

**Issue by wangchao92** [google/protobuf#609]
When I build my project, it shows:
/usr/local/include/google/protobuf/generated_message_util.h:80: undefined reference to `google::protobuf::internal::empty_string_'
Anyone has any ideas? Thanks!

**Comment by ameyag** [comment]
Which language is been used for your project?

**Comment by xfxyjwf** [comment]
If you can build protobuf's unit tests, you can follow its configuration to configure your own projects. Also make sure you are using the latest releases and following instructions in the README.md file correctly.
