### ISSUE TITLE
C# Custom JSON formatting and parsing for FieldMask well known type

### ISSUE THREAD

**Issue by jtattermusch** [google/protobuf#617]
FieldMask uses a custom JSON format.

https://github.com/google/protobuf/blob/master/src/google/protobuf/field_mask.proto#L131

**Comment by jtattermusch** [comment]
we probably don't need this for the initial release.

**Comment by jskeet** [comment]
I think it's probably worth covering as many of the WKT as possible for JSON formatting, at least where it's simple - and this one sounds pretty trivial :)

**Comment by jskeet** [comment]
The formatting is now implemented. Parsing of FieldMask will be done as part of a bigger parsing effort.
