### ISSUE TITLE
Mention C# in protobuf docs at developers.google.com

### ISSUE THREAD

**Issue by jtattermusch** [google/protobuf#618]
Once C# is released, it should be mentioned here:
https://developers.google.com/protocol-buffers/docs/proto3

**Comment by jskeet** [comment]
And appropriately documented, of course. Before the final release we'll want to include generated documentation too, like https://developers.google.com/protocol-buffers/docs/reference/java/index. We should probably start investigating which tool we want to use for that.

**Comment by jtattermusch** [comment]
I don't have experience with Sandcastle which you originally mentioned as one of our possible choices. For gRPC, I might just use Doxygen, because gRPC is a multi-language project and we will definitely use Doxygen for (at least some) other languages, it might outweigh the fact that doxygen is perhaps less .NET oriented than some other solutions.

The google-api-dotnet-client (Apiary client library) uses Doxygen.

**Comment by jskeet** [comment]
Okay - will certainly give that a try as one option.

**Comment by anandolee** [comment]
We have tech writer who can help with the document. Have send both of you the email

**Comment by jskeet** [comment]
This is now done, in terms of the "generated code guide" and the tutorial. We still need to publish the runtime API (javadoc equivalent) but that is in progress. Closing this issue.
