### ISSUE TITLE
C# Custom JSON formatting and parsing for struct well known type

### ISSUE THREAD

**Issue by jtattermusch** [google/protobuf#619]
even though struct.proto fails to mention that, I think https://github.com/google/protobuf/blob/master/src/google/protobuf/struct.proto should use a custom JSON format.

**Comment by jskeet** [comment]
Other than Any support (which is a separate feature on its own, really) I think all the WKTs now format appropriately. We don't have any JSON parsing support at all yet. Closing this issue for now.
