### ISSUE TITLE
Invalid Unicode characters possible with \U escape

### ISSUE THREAD

**Issue by knah** [google/protobuf#637]
When parsing \U escape, the fifth symbol is not properly checked, allowing for sequences like \U001FFFFF to be parsed and then converted into UTF-8. According to wiki, these values are not considered valid in UTF-8 even though they can be encoded.

**Comment by xfxyjwf** [comment]
Which language are you using?

**Comment by knah** [comment]
I'm using protoc built from master branch. Looking at source code, it seems to me that this is also the case in csharp-experimental and protoc-alpha-3.1 branches.
The resulting invalid strings can be passed into package/namespace names in target language, they are stored for custom option values and could in theory resurface somewhere deep in the user code that reads these options.

**Comment by jskeet** [comment]
Can you give an example of what you mean by "when parsing \U escape"? Do you mean when converting from JSON to protobuf? The context isn't clear at the moment.

**Comment by knah** [comment]
I'm sorry I wasn't very specific.
I mean when protoc parses .proto file and generates language-specific files. One of such examples would be file with a single line, like this:
```
option csharp_namespace = "\U001FFFFF";
```
This will cause protoc to generate .cs file containing invalid character. While it's not much of a problem as it won't compile anyway, it could cause some harm in user-defined options or default values.
As another example, the following .proto:
```
syntax = "proto2";
option csharp_namespace = "δ";
import "google/protobuf/descriptor.proto";
extend google.protobuf.FieldOptions {
	optional string singleCharOnlyOption = 1354235 [default = "\U001FFFFF"];
}
```
will happily generate a field with given default value. When decoded in C#, it turns (in my tests) into four "replacement character" with code \uFFFD. 
At the same time, protoc will not compile values like \U00200000 with error "Expected eight hex digits up to 10ffff for \U escape sequence".
It also seems to allow surrogate pair values in \u and \U escapes, which it probably shouldn't.

**Comment by haberman** [comment]
Can you elaborate on why you think `\U001FFFFF` should be rejected?

`U+1FFFFF` appears to be a currently unallocated code point. But I don't see anything about it saying it is invalid or should be rejected by tools.

Checking for surrogate pair values probably makes sense though.
