### ISSUE TITLE
Memoryleak since change const ::std::string kEmptyString to const ::std::string& GetEmptyString()

### ISSUE THREAD

**Issue by berthold08** [google/protobuf#648]
There was a fix anounced in the google chrome sources. But I miss the fix in the latest download of chromium.
-- start
google FIX vom 02.10.2014
----
\third_party\protobuf\src\google\protobuf\generated_message_util.cc

src/google/protobuf/generated_message_util.cc View
 @@ -36,7 +36,6 @@
 
 #include <limits>
 
-
 namespace google {
 namespace protobuf {
 namespace internal {
 @@ -51,8 +50,13 @@ double NaN() {
 const ::std::string* empty_string_;
 GOOGLE_PROTOBUF_DECLARE_ONCE(empty_string_once_init_);
 
+void DeleteEmptyString() {
+  delete empty_string_;
+}
+
 void InitEmptyString() {
   empty_string_ = new string;
+  OnShutdown(&DeleteEmptyString);
 }

---
webrtc Issue 3086:	Memoryleak since change const ::std::string kEmptyString to const ::std::string& GetEmptyString()
--ende

**Comment by xfxyjwf** [comment]
Isn't this already fixed in protobuf code? See: https://github.com/google/protobuf/blob/master/src/google/protobuf/generated_message_util.cc#L60

**Comment by berthold08** [comment]
It looks like it is not included in chromium download from 18.07.2015 and not in the webrtc download.
See attached screenshots.

![protobuf-chromium](https://cloud.githubusercontent.com/assets/7162068/8952701/c790a20a-35d9-11e5-9215-7c3e8730e8fd.jpg)
![protobuf-g-m-util](https://cloud.githubusercontent.com/assets/7162068/8952702/c790d4b4-35d9-11e5-93fa-97de160eeb66.jpg)

**Comment by xfxyjwf** [comment]
This issue was fixed in protobuf version 2.6.1. It seems chromium has not been synced to the latest release of protobuf. Could you submit an bug report to the chromium project instead?
