### ISSUE TITLE
Enum conflict in Python

### ISSUE THREAD

**Issue by arunvx** [google/protobuf#65]
Consider the following enum defined within a .proto file:

enum CoreDataScope {
	local = 1;
	file = 2;
	global = 3;
	invalid = 4;
}

Protoc.exe then generates the following Python code (showing just a snippet):

///////
_COREDATASCOPE = descriptor.EnumDescriptor(
  name='CoreDataScope',
  full_name='SIES.Meta.CoreDataScope',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='local', index=0, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='file', index=1, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='global', index=2, number=3,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='invalid', index=3, number=4,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=12851,
  serialized_end=12918,
)

local = 1
file = 2
global = 3
invalid = 4
///////

The above fails in Python due to the use of the reserved keyword "global". I think this is a defect in the auto code generator for Python (protoc.exe)

**Comment by xfxyjwf** [comment]
Protocol compiler cannot avoid such conflicts completely. For such cases we usually prefer renaming to adding special cases in the compiler.
