### ISSUE TITLE
RepeatedPtrField::erase

### ISSUE THREAD

**Issue by ubique** [google/protobuf#661]
Documentation says that there is "erase" method both in RepeatedField and RepeatedPtrField.
But no such method exists.

**Comment by songtzu** [comment]
maybe your protobuf source is old.
in old version 2.4.1, there is no erase in RepeatedPtrField
in current version there is . hope it helps !

**Comment by xfxyjwf** [comment]
Thanks @songtzu ! The erase method is only available starting from the v3.0.0-alpha+ versions.
