### ISSUE TITLE
Offer optional C++11 mode when compiling protobufs

### ISSUE THREAD

**Issue by sleevi** [google/protobuf#67]
C++11 offers new features that may be of interest to applications using protoc, and it would be nice to include an optional flag to protoc indicating C++11 can be used, possibly on a language-feature by language-feature basis.

For example, C++11 offers both enum classes (`enum class E` - C++11 7.2 p2 ) and explicit enum types (`enum Foo : int` C++11 7.2 p5), both of which allow for forward declaration of enums. By allowing forward declaration, C++ applications can reduce the places that include the .pb.h with the enum definition.

Protobufs currently presume/guarantee that an enum can be expressed as an int (vis-a-vis https://github.com/google/protobuf/blob/e428862450679aaccd3675d1092f9f5253b7bd43/src/google/protobuf/compiler/cpp/cpp_enum.cc#L231 ), so having something like https://github.com/google/protobuf/blob/e428862450679aaccd3675d1092f9f5253b7bd43/src/google/protobuf/compiler/cpp/cpp_enum.cc#L78 instead use `enum $classname$ : int {` would allow for forward declarations.

**Comment by orian** [comment]
Probably enum classes would also reduce Google's internal dev pains ;-)

**Comment by alexandruirimiea** [comment]
I strongly vote for the enum class feature. 

Currently, I have a case where I want to print a description of the proto enum, like:

---
Utils.h

#include "ProtocGenerated.h"

void toString(ProtocGenerated::ProtoEnum protoEnum);
---

In order to achieve this, the protoc generated header must be included in this header - "Utils.h" - (that happens to be included in many other places), but this is not an option, so I have to change the enums from the generated headers to enum classes.

My suspicion regarding the lack of this feature is that forcing to describe the enum type size reduces the ability of protobuf to optimize the space.

**Comment by kaimast** [comment]
Has there been any process on this?

**Comment by goldenbull** [comment]
Btw, is it possible to allow enum entries in different enums to have the same name? just  like java and C# and any modern language. I hate the error:
```
Note that enum values use C++ scoping rules, meaning that enum values are siblings of their type, not children of it.
```

**Comment by xfxyjwf** [comment]
I don't think we will add a C++11 compile mode. We can consider adding support for some of the individual C++11 features, though. For the enum feature, there is already a separate issue for it:
https://github.com/google/protobuf/issues/1079

**Comment by nico** [comment]
I think the feature most interesting for Chromium (which sleevi and I work on) are enums with underlying types, not enum classes. We want to be able to forward declare enums defined in proto.h files.

**Comment by timotheecour** [comment]
I'm using the following workaround, isn't that enough?
```
message Foo {
  enum Type {
    unknown = 0;
    val1 = 1;
    val2 = 2;
  }
}

message Test{
  optional Foo.Type foo = 1;
}

```

In C++: `Foo::val1`

**Comment by sleevi** [comment]
No, because that doesn't allow forward declaring the type.

**Comment by nico** [comment]
@xfxyjwf Want me to file a new issue for a mode that adds enums with explicit underlying types, or do you want to reopen this one and retitle it, since that's what this issue was originally about?

**Comment by xfxyjwf** [comment]
@nico Could you create a separate issue specifically for enum?

**Comment by AustinSchuh** [comment]
@xfxyjwf For our build, I wanted to enable -Wsuggest-override for modern GCC.  This required me to modify protobuf to add override declarations to methods, including the generated code.

I'd like to upstream those changes.  Are you interested?  I can either add override unconditionally or add it with a macro (which is either defined to be nothing, or to be override).

**Comment by xfxyjwf** [comment]
@AustinSchuh Adding a PROTOBUF_OVERRIDE macro seems fine to me.

**Comment by khuzemap** [comment]
@xfxyjwf  , I am ready to put up a change that adds PROTOBUF_OVERRIDE but I see "final" has been replaced by PROTOBUF_FINAL in recent change (https://github.com/google/protobuf/commit/0400cca3236de1ca303af38bf81eab332d042b7c). Is this how "override" also needs to be added now?

**Comment by khuzemap** [comment]
@xfxyjwf , have updated the change. using "override" keyword now.

**Comment by khuzemap** [comment]
@xfxyjwf, wonder if you got chance to take a look at the change.
