### ISSUE TITLE
Documentation for timestamp unclear on "whole seconds" JSON formatting

### ISSUE THREAD

**Issue by jskeet** [google/protobuf#670]
The JSON documentation for Timestamp states:

> Uses RFC 3339, where generated output will always be Z-normalized and uses 3, 6 or 9 fractional digits.

It's unclear whether the Unix epoch (for example) should be formatted as `1970-01-01T00:00:00Z` or `1970-01-01T00:00:00.000Z`. Looking at the C++ code, it seems like it's the former - but that should be clarified in the documentation.

**Comment by xfxyjwf** [comment]
Now it has been updated to:
```
Uses RFC 3339, where generated output will always be Z-normalized and uses 0, 3, 6 or 9 fractional digits.
```

For whole seconds, the fractional parts should be omitted.
