### ISSUE TITLE
Java conformance code will fail when reading more than 256 bytes

### ISSUE THREAD

**Issue by jskeet** [google/protobuf#685]
Drive-by issue rather than fix as I'm in the middle of implementing it for C#, but in `ConformanceJava.java`:

```java
 return buf[0] | (buf[1] << 1) | (buf[2] << 2) | (buf[3] << 3);
```

should be:

```java
 return buf[0] | (buf[1] << 8) | (buf[2] << 16) | (buf[3] << 24);
```

... quite possibly with some bit masking given the signed-byte nature of Java.

**Comment by xfxyjwf** [comment]
Fixed now.
