### ISSUE TITLE
How can I use protobuf upload large file to server on Android?

### ISSUE THREAD

**Issue by wangkunlin** [google/protobuf#697]
How can I use protobuf upload large file to server on Android?My company use this protocol,and I study it tow days,but no effect.

**Comment by xfxyjwf** [comment]
Protobuf is used to convert in-memory data objects to a serialized format suitable for storage or wire-transfer. It does not handle file transfer itself though. I guess you are looking for something else.

**Comment by wangkunlin** [comment]
ok，thanks

**Comment by flockonus** [comment]
As reference for ppl coming next, one possible answer using protobuf is https://grpc.io as its main msg exchange medium is protobuf
