### ISSUE TITLE
new version for python3 fix

### ISSUE THREAD

**Issue by btabibian** [google/protobuf#704]
Hi,

Will there be a new version for this fix SHA: 42809ef8fef9e4d76267eb21bcb8a856f10ba418.

Currently installing using pip produces the error even though it is fixed in master.

Installing from the master also throws a lot of syntax error in the same style as SHA: 42809ef8fef9e4d76267eb21bcb8a856f10ba418. Is it possible that these non-Python3 compatible codes were reintroduced?

Thanks,
B.

**Comment by mitchellrj** [comment]
:+1:

**Comment by xfxyjwf** [comment]
I believe the latest version (3.0.0b2) supports python 3. Let me know if it doesn't.
