### ISSUE TITLE
I can't install protobuf

### ISSUE THREAD

**Issue by xu6148152** [google/protobuf#730]
I used mvn install, and then it will be error. My environment is osx10.10.2
this is error log.

Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:1.3:run (generate-sources) on project protobuf-java: An Ant BuildException has occured: Execute failed: java.io.IOException: Cannot run program "../src/protoc": error=2, No such file or directory -> [Help 1]  

Can anyone help me? Thank you very much.

**Comment by xfxyjwf** [comment]
Before building the Java version, you need to follow the C++ instructions to build the protoc binary first.

**Comment by xu6148152** [comment]
@xfxyjwf  Thank you very much, I have built it successfully
