### ISSUE TITLE
Proto binary to JSON modifies keys

### ISSUE THREAD

**Issue by tn0502** [google/protobuf#731]
The JSON output serialized from proto binaries (using `google::protobuf::util::BinaryToJsonString`) has different casing for its keys, making it unusable for us. E.g. I deserialize
```json
{"People": [{"FirstName": "Tommy"}]}
```
and the objects look fine until I serialize them again
```json
{"people": [{"firstName": "Tommy"}]}
```

**Comment by xfxyjwf** [comment]
In JSON, field names are turned into camelCase (starting with a lower case letter). The serialization result seems correct to me and I think the parsing part should report an error.

**Comment by tn0502** [comment]
Even with a schema like this
```proto
message Person {
  optional string FirstName;
}
```
Does it not both parse and encode the first JSON? Why does it change the key? ProtoBuf is unable to recreate the binary because the keys no longer match.

**Comment by xfxyjwf** [comment]
According the proto3 JSON spec, JSON names should be the camelCase version of the proto field name. For "FirstName", its JSON name should be "firstName". We haven't decided whether to allow or reject "FirstName" in this case though (or whether to reject first_name if the proto field is named as such). We will publish a more detailed JSON spec. For the time being, it's better to avoid "FirstName" or "first_name" in JSON.

**Comment by tn0502** [comment]
Unfortunately, our JSON schema has been in production for quite some time. Changing it now will break a lot of things for us.

**Comment by xfxyjwf** [comment]
Some update on the json name: we discussed it this week and think it's reasonable to add an option to support that.

Another feature request for this: https://github.com/google/protobuf/issues/795

**Comment by xfxyjwf** [comment]
We have added a JsonFormat.Printer option to preserve the field name declared in the .proto file:
https://github.com/google/protobuf/blob/master/java/util/src/main/java/com/google/protobuf/util/JsonFormat.java#L152

We also added a field option which can be used to customize the JSON name per field:
```proto
message Foo {
  int32 value = 1 [json_name = "some_other_name"];
}
```

The two cannot be used at the same time though.

**Comment by reece** [comment]
@xfxyjwf  How do you activate this feature in protoc (on the command line, I mean)?

**Comment by xfxyjwf** [comment]
@reece You don't need to do anything with protoc to activate it. It's on by default. Just compile the proto file normally and our JsonFormat libraries should respect the json_name option specified in the .proto file.

**Comment by reece** [comment]
I misunderstood. I thought https://github.com/google/protobuf/issues/731#issuecomment-173423707 was that there were two features: 1) an "option" to preserve field names and 2) "also" the ability to specify json_name in a field.

FWIW, I would much prefer that protoc not modify symbols, ever. Implicit and assumed behaviors create more problems than they solve. (The same functionality with a feature switch would be great!)

**Comment by xfxyjwf** [comment]
I think you were correct. There are indeed two features. Neither of them require anything to turn on.

**Comment by reece** [comment]
Thanks. I was way off base... my python models were generating json with camelCase, which incorrectly thought was because protoc had generated that. Instead, I just needed to pass preserving_proto_field_name=True to MessageToJson. Thanks for your replies.

**Comment by MartinThoma** [comment]
In Python:

```
from google.protobuf.json_format import MessageToJson
json_obj = MessageToJson(msg, preserving_proto_field_name=True)
```

**Comment by bobbytables** [comment]
For anyone else that finds this issue the way I did, there's a way you can decode the JSON back into the object representation with the different key format:

```ruby
MyMessage.decode_json(json_string)
```

So even if you have `startedAt` in the JSON but your proto declares it as `started_at`, the `decode_json` method will convert it correctly for you.

Inversely, there is a `encode_json` method on the message class, but I find using `to_json` on the object does the same thing.

**Comment by tonyneel923** [comment]
> We have added a JsonFormat.Printer option to preserve the field name declared in the .proto file:
> https://github.com/google/protobuf/blob/master/java/util/src/main/java/com/google/protobuf/util/JsonFormat.java#L152
> 
> We also added a field option which can be used to customize the JSON name per field:
> 
> ```protobuf
> message Foo {
>   int32 value = 1 [json_name = "some_other_name"];
> }
> ```
> 
> The two cannot be used at the same time though.

Is this only for Java? Is there support for javscript?
