### ISSUE TITLE
Error setting certificate verify locations

### ISSUE THREAD

**Issue by cynodelic** [google/protobuf#733]
During the execution of `./autogen.sh`, I had this error:

    Google Mock not present.  Fetching gmock-1.7.0 from the web...
      % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                     Dload  Upload   Total   Spent    Left  Speed
      0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0curl: (77) error setting certificate verify locations:
      CAfile: /etc/pki/tls/certs/ca-bundle.crt
      CApath: none

__How can I fix it?__

**Comment by xfxyjwf** [comment]
The error message is reported by "curl" when downloading gmock. It may be just a temporary error. If it persists, you can download one of the packages on the release page:
https://github.com/google/protobuf/releases

The files in the downloads sections should already have the configure script and you can skip autogen.sh.
