### ISSUE TITLE
Integer overflows in new arena code

### ISSUE THREAD

**Issue by fweimer** [google/protobuf#761]
There are a couple of cases where the new arena code can produce blocks which are smaller than expected.

There is a relevant TODO in `Arena::NewBlock`:

```
if (n > size - kHeaderSize) {
  // TODO(sanjay): Check if n + kHeaderSize would overflow
  size = kHeaderSize + n;
}
```

In `Arena::AllocateAligned`, the alignment/padding computation can silently wrap around to zero:

```
// Align n to next multiple of 8 (from Hacker's Delight, Chapter 3.)
n = (n + 7) & -8;
```

**Comment by xfxyjwf** [comment]
I guess we can add such a check at the beginning of AllocateAligned:
```cpp
GOOGLE_CHECK(n <= std::numeric_limits<size_t>::max() - 7 &&
             n <= std::numeric_limits<size_t>::max() - kHeaderSize);
```

**Comment by acozzette** [comment]
I am going to go ahead and close this because we are cleaning up issues and I see that this one has not been updated in a long time. Feel free to reopen it if this is still a problem, though. From a quick glance at arena.cc it looks like this issue was fixed at some point in the last year or so.
