### ISSUE TITLE
There are other operating systems running on sparc machines

### ISSUE THREAD

**Issue by MartinHusemann** [google/protobuf#763]
In stubs/platform_macros.h a sparc cpu is always associated with the Solaris operating system (and especially its default non-64bit userland). This causes GOOGLE_PROTOBUF_ARCH_64_BIT to not be set despite **LP64** being defined (and building for 64bit). The usage of GOOGLE_PROTOBUF_ARCH_64_BIT vs. **LP64** is not always consistent, so this leads to compilation errors.

Easiest fix is to just align the defines, or only special case Solaris.

Like this:

```
--- stubs/platform_macros.h.orig        2015-08-24 23:53:18.000000000 +0200
+++ stubs/platform_macros.h     2015-08-26 21:41:27.000000000 +0200
@@ -67,7 +67,7 @@
 #define GOOGLE_PROTOBUF_ARCH_32_BIT 1
 #elif defined(sparc)
 #define GOOGLE_PROTOBUF_ARCH_SPARC 1
-#ifdef SOLARIS_64BIT_ENABLED
+#if (defined(sun) && defined(SOLARIS_64BIT_ENABLED)) || __LP64__
 #define GOOGLE_PROTOBUF_ARCH_64_BIT 1
 #else
 #define GOOGLE_PROTOBUF_ARCH_32_BIT 1
```

Or, if someone can test on Solaris: just get rid of SOLARIS_64BIT_ENABLED and only test for **LP64**?

**Comment by xfxyjwf** [comment]
Feel free to send a PR. We don't have Solaris to test the change though. Better to take the approach that's less likely to break Solaris users.

**Comment by haberman** [comment]
PR https://github.com/google/protobuf/pull/780 seems to indicate that this problem has already been solved. Please re-open if there is still a problem.
