### ISSUE TITLE
MessageNano.toByteArray heap usage

### ISSUE THREAD

**Issue by drmichi** [google/protobuf#764]
Dear ProtoBuf Team

I am currently using MessageNano to exchange messages between two android.os.HandlerThread (Looper with a Handler and a MessageQueue).
So far I was able to keep the heap trashing to zero, except that now I have to use the toByteArray function in order to serialize the binary data.

In the background I already have a com.android.volley.toolbox.ByteArrayPool for the raw byte array, however the current implementation of MessageNano creates a new instance of CodedOutputByteBufferNano for each toByteArray call.

```
/**
 * Serialize to a byte array starting at offset through length. The
 * method getSerializedSize must have been called prior to calling
 * this method so the proper length is know.  If an attempt to
 * write more than length bytes OutOfSpaceException will be thrown
 * and if length bytes are not written then IllegalStateException
 * is thrown.
 */
public static final void toByteArray(MessageNano msg, byte[] data, int offset, int length) {
    try {
        final CodedOutputByteBufferNano output =
            CodedOutputByteBufferNano.newInstance(data, offset, length);
        msg.writeTo(output);
        output.checkNoSpaceLeft();
    } catch (IOException e) {
        throw new RuntimeException("Serializing to a byte array threw an IOException "
                + "(should never happen).", e);
    }
}
```

Wouldn't it be nice to have a heapless MessageNano.toByteArray?

![heap_usage](https://cloud.githubusercontent.com/assets/5869289/9524616/12c94ff2-4ce0-11e5-836e-66fc57b52af8.PNG)
![heap_allocations](https://cloud.githubusercontent.com/assets/5869289/9524621/1629ca0a-4ce0-11e5-8d74-054832927b15.PNG)

**Comment by xfxyjwf** [comment]
@drmichi , what's the proto message definition you used this test? and what data does the message contain?

It's not easy to avoid allocating this CodedOutputByteBufferNano in toByteArray. Before committing to it, I would like to understand why allocating a single object carries so much weight in your test. Is your test just calling toByteArray repeatedly on an empty message? How does it look like in the real-world application?

**Comment by drmichi** [comment]
@xfxyjwf Thank you for your response.

The .proto looks like this:
```
message ExampleData {
    enum DataMode {
        ModeA = 0;
        ModeB = 1;
        ModeC = 2;
    }    
    required int32 sequence_number = 1;
    optional float data_a = 2;
    optional float data_b = 3;
    optional float data_c = 4;
    optional float data_d = 5;
    optional float data_e = 6;
    optional float data_f = 7;
    optional DataMode current_data_mode = 8;
    optional bool data_g = 9;
}
```

I am using the android.os.Looper Framework to exchange messages between threads.
http://developer.android.com/reference/android/os/package-summary.html

Each message is a MessageNano, which is recycled in the "DataProducer" and "DataReceiver".
So far I was able to get a throughput of 8000 msg/s on the actual hardware.
![androidhandlerthread](https://cloud.githubusercontent.com/assets/5869289/9573558/0dcfbf50-4fbe-11e5-9d14-5c2cdf6d0c6a.png)
