### ISSUE TITLE
Consider populating a directory hierarchy for C# based on namespace

### ISSUE THREAD

**Issue by jskeet** [google/protobuf#773]
Currently we don't do this because in .NET projects there tends to be a "base" namespace, but I think we'll want to address this with another flag, based on a bit of experience of trying to use the current approach.

Proposal:

- Add a new flag of `csharp_base_package`
- When working out where to generate code, generate a directory name based on the namespace from the base package onwards. For example, if the base package is `a.b` and the declared package for the .proto file is `a.b.c.d`, create a directory of `C.D` and put the code in there, in a namespace of A.B.C.D
- If `csharp_base_package` isn't specified, treat it as empty (e.g. create a directory of `A.B.C.D` in the above example)
- If `csharp_base_package` is specified but the .proto package doesn't start with that, fail

Alternatives to consider:

- Specify the base namespace instead of base package (e.g. `A.B` instead of `a.b`)
- Have yet another flag to allow the existing behaviour of not creating directories

The GRPC plugin should do the same thing.

Thoughts?

@anandolee @jtattermusch

**Comment by anandolee** [comment]
All other languages do not have language_base_package flag, some have language_package flag.

No more flags will be great. If we  have to add, I prefer csharp_package instead of csharp_base_package.

**Comment by jskeet** [comment]
Which other languages have anything like this? I can't see any using protoc --help. I don't think csharp_package would make sense, as it's not specifying a package/namespace that anything should be in - it's specifying the package/namespace that should be used as a relative base for creating directories.

Having thought about it more, I think it should actually be csharp_base_namespace rather than csharp_base_package, as the namespace can be specified in the .proto file... the directory should be generated based on namespace rather than package, so it makes sense for this flag to be in terms of namespaces.

I'll start writing the code to implement it, and we can then work out what to call the flag. I think we *do* need a new flag, unless we use csharp_out to include both pieces of information, e.g. `--csharp_out=src=Foo.Bar`, which would be equivalent to `--csharp_out=src --csharp_base_namespace=Foo.Bar`... but I'd rather keep them separate.

**Comment by anandolee** [comment]
@pherl Is it OK to add one more flag to FileOptions in descriptor.proto?

**Comment by jskeet** [comment]
This isn't a file option, and shouldn't be - it's a command line flag, which is appropriate given what it controls.

**Comment by pherl** [comment]
Hmm, this flag seems to make the generated files indeterministic. When will
the base flag be used? What's the default value for google owned protos,
e.g. one platform protos?

**Comment by jskeet** [comment]
It entirely depends on where you want them to go. It's no more indeterministic than --csharp_out being a command line option. It doesn't change the *content* of the files - it only changes where they're written out to.

Basically it's up to the user to put them into their project however they wish. Different users may want to lay their projects out slightly differently (e.g. one using Google as a base namespace if they have multiple APIs in the same project, and one using Google.Pubsub.V1 as a base namespace if they're only using that API). It doesn't change the compiled code (the IL) at all.

**Comment by pherl** [comment]
hmm, if I understand this correctly, it's the same as appending the base
directory to the --csharp_out flag? Why the csharp_out cannot be used in
this case then?

**Comment by jskeet** [comment]
No, it's not - it's the *opposite* of appending the base directory to the csharp_out flag, effectively... it's *removing* directories from the generated hierarchy... but those directories may not exist.

This is very normal in a C# project layout - you have a root source directory which is effectively some default namespace... like the Google.Protobuf directory represents the Google.Protobuf namespace. There's no "Google" directory and no "Protobuf" directory... just "Google.Protobuf" (which could just be "MainLibrary" or something similar) but code in the Google.Protobuf namespace goes into that directory, and code in the Google.Protobuf.Reflection goes in a Reflection subdirectory, etc.

**Comment by pherl** [comment]
Ah, I see. It makes sense to introduce a generator flag for this.
