### ISSUE TITLE
build only c++ (protoc)

### ISSUE THREAD

**Issue by ekg** [google/protobuf#779]
Is there a way to only build protoc, not the java or python systems?

**Comment by xfxyjwf** [comment]
Follow instructions here to build protoc (and also proto C++ runtime):
https://github.com/google/protobuf/blob/master/README.md

**Comment by lucifercr07** [comment]
The above Readme specified in the link builds protoc with all the java and other language compilers, along with c++. 
Is there any way to just build protoc cpp compiler?

**Comment by DavidRobb** [comment]
Actually, build instructions say:

For example: if you only need C++, download protobuf-cpp-[VERSION].tar.gz; if you need C++ and Java, download protobuf-java-[VERSION].tar.gz (every package contains C++ source already); if you need C++ and multiple other languages, download protobuf-all-[VERSION].tar.gz.

**Comment by sciencemanx** [comment]
Is there any insight into how the protobuf-cpp-[VERSION].tar.gz is constructed?

**Comment by acozzette** [comment]
@sciencemanx If I remember right that comes from running `make dist` and then the `post_process_dist.sh` script.

**Comment by Clement-Jean** [comment]
I answered to my own question on stackoverflow about how to do this. Even though it is quite a rudimentary solution (grep + remove), it does work and compile quite faster. Check [it](https://stackoverflow.com/questions/60182810/build-protoc-for-c-with-cmake)

**Comment by bsolomon1124** [comment]
@xfxyjwf why is this issue closed?

Following the exact instructions from your link will still build for all languages, not just C++

```
set -ex \
    && yum update -y \
    && yum install -y \
        autoconf \
        automake \
        g++ \
        git \
        glibc-headers \
        gzip \
        libtool \
        make \
        zlib-devel \
    && curl -Lo /opt/protobuf.tar.gz \
        "https://github.com/protocolbuffers/protobuf/releases/download/v${PROTOBUF_VERSION}/protobuf-cpp-${PROTOBUF_VERSION}.tar.gz" \
    && tar -xzvf protobuf.tar.gz \
    && rm -f protobuf.tar.gz \
    && pushd "protobuf-${PROTOBUF_VERSION}" \
    && ./configure --with-zlib --disable-debug \
    && make \
    && make install \
    && ldconfig --verbose \
    && popd \
    && rm -rf "protobuf-${PROTOBUF_VERSION}" \
    && protoc --version \
    && pkg-config --cflags protobuf \
    && pkg-config --libs protobuf
```

**Comment by sionhughes** [comment]
Same issue as  @bsolomon1124 here too.

**Comment by jwmelto** [comment]
This issue should be broadened to allow building an arbitrary subset of language compilers/bindings. Particularly as the list of supported lanaguages grows, having to build all of them is an unnecessary burden on users.
