### ISSUE TITLE
protoc 2.6.1 in Maven Central fails on RHEL 6: GLIBC_2.14 not found

### ISSUE THREAD

**Issue by joakimortbrant** [google/protobuf#781]
Is it possible to get a new binary build for 2.6.1 same way as after #354 for protoc 3.x.x ? (i.e building it in an older linux env)
Would be great to be able to use this with our current version of protobuf / linux.

**Comment by ejona86** [comment]
@zhangkun83, FYI

**Comment by zhangkun83** [comment]
Sorry for the long wait. I am pushing a new build for 2.6.1, which is versioned `2.6.1-build2`. Now it resides in a staging repository `https://oss.sonatype.org/content/repositories/comgoogle-1077/`. Please (temporarily) add it to your repositories and see if it works for you. I will then release it on Maven Central.

**Comment by zhangkun83** [comment]
I have pushed `2.6.1-build2` to Maven Central, which should have fixed the issue.

**Comment by yktoo** [comment]
I can confirm it works on RHEL 6.7 (GLIBC 2.12).

**Comment by smallufo** [comment]
Is there any version 3.1.0 that works with RHEL 6 ?

```
$ ./protoc-3.1.0-linux-x86_64.exe 
./protoc-3.1.0-linux-x86_64.exe: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by ./protoc-3.1.0-linux-x86_64.exe)
```

```
$ cat /etc/redhat-release 
CentOS release 6.8 (Final)
```

**Comment by low205** [comment]
Same problem with RHEL 6. Can we get a 3.1.0 version for GLIBC 2.12?
protoc: stdout: . stderr: /u01/jenkins/.gradle/caches/modules-2/files-2.1/com.google.protobuf/protoc/3.1.0/655f228fd199960f37dad67daf73ab8e9fbfe2e/protoc-3.1.0-linux-x86_64.exe: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /u01/jenkins/.gradle/caches/modules-2/files-2.1/com.google.protobuf/protoc/3.1.0/655f228fd199960f37dad67daf73ab8e9fbfe2e/protoc-3.1.0-linux-x86_64.exe)

**Comment by zhangkun83** [comment]
@xfxyjwf it seems the 3.1.0 protoc linux artifacts were not built from Centos 6.6 as suggested in [this doc](https://github.com/google/protobuf/tree/master/protoc-artifacts#tips-for-deploying-on-linux). Can you make a new build?

**Comment by xfxyjwf** [comment]
@TeBoring built the 3.1.0 protoc binary.

**Comment by TeBoring** [comment]
I have uploaded 3.1.0-buid2 to maven.
