### ISSUE TITLE
compile warning about UTF-16

### ISSUE THREAD

**Issue by emmenlau** [google/protobuf#784]
I get the following compiler warning on Ubuntu 15.04:

```
Running com.google.protobuf.CodedOutputStreamTest
Aug 31, 2015 4:40:58 PM com.google.protobuf.CodedOutputStream writeStringNoTag
WARNING: Converting ill-formed UTF-16. Your Protocol Buffer will not round trip correctly!
com.google.protobuf.Utf8$UnpairedSurrogateException: Unpaired surrogate at index -1
    at com.google.protobuf.Utf8.encode(Utf8.java:460)
    at com.google.protobuf.CodedOutputStream.efficientWriteStringNoTag(CodedOutputStream.java:483)
[...]
```

Is this a problem? Can I do something to fix it? Thanks for your great work!

**Comment by xfxyjwf** [comment]
This error suggests your string fields contain invalid UTF-16 value and after converted to UTF-8 it will not contain the same value.

**Comment by emmenlau** [comment]
I'm sorry I should have been more explicit: I meant that I get this error from building your latest release. The compile does not fail, but when checking the logs I found this message. Its printed during the compile (or subsequent tests, I don't know). Do I do something wrong when compiling your release? Does it mean I configured wrongly?

**Comment by xfxyjwf** [comment]
No, it's fine. We have tests to verify the behavior when invalid UTF-16 string is encountered and that's why you see these warning when building protobuf. You can safely ignore them.

**Comment by emmenlau** [comment]
Thanks! Ignoring the issue, and closing as "won't fix"!

**Comment by emmenlau** [comment]
Actually the behavior is still a bit unfortunate... I have just spent another hour to figure out why I get this warning during the protobuf-java compile, just to find my own issue here, from one year ago! Do you think it would be possible that the tests run without throwing this exception? I think many users must be scared to run the tests and see exceptions being thrown...
Thanks a lot for your consideration!
