### ISSUE TITLE
hash_set and hash_map are deprecated in vc14 compiler

### ISSUE THREAD

**Issue by aarotech** [google/protobuf#792]
Taken from:
http://blogs.msdn.com/b/vcblog/archive/2014/06/06/c-14-stl-features-fixes-and-breaking-changes-in-visual-studio-14-ctp1.aspx?PageIndex=3

"* In VS14, we're going to deprecate <hash_map> and <hash_set>.  Including them will emit a static_assert of the form "<hash_map> is deprecated and will be REMOVED. Please use <unordered_map>. You can define _SILENCE_STDEXT_HASH_DEPRECATION_WARNINGS to acknowledge that you have received this warning."  (I reserve the right to change that macro name before RTM, although I like what I've got.)  Defining the escape hatch macro (one macro works for both headers) will allow your code to compile, and the containers will be fully supported in VS14 aside from this frowny face.  Then in VS15, these headers will be REMOVED FOREVER.  They're a maintenance burden - the underlying machinery that powers hash_meow and unordered_meow has to be more complicated in order to support two flavors.  The pre-Standardization hash_meow interface is also more difficult to use than the Standard unordered_meow interface."

Will this be addressed in the release version?

Edit: I mean the next release.

**Comment by xfxyjwf** [comment]
Do you mean in the next release? Maybe... It depends on how much time we get to fix pending issues. It would be appreciated if you could help send a PR to fix this though :)

**Comment by aarotech** [comment]
Yes, I mean the next release.  

I'm not quite sure what you mean by sending a PR but I have a couple suggestions for making things vc14 ready.  

The definitions for min and max which are referenced in zero_copy_stream_impl_lite.cc have been removed from xutility.  As a replacement I've been using minmax.h.  The only change required is to include minmax.h at the top of zero_copy_stream_impl_lite.cc.  

The other issues are related to hash_set and hash_map being deprecated and can be resolved by using unordered_set and unordered_map instead.

**Comment by xfxyjwf** [comment]
I meant a Pull Request: https://github.com/google/protobuf/pulls . It should be very easy if you already have all the changes in your local git.

**Comment by xfxyjwf** [comment]
We are using C++11 unordered_map and unordered_set for Visual Studio 2010+ (VS10+) now.
