### ISSUE TITLE
Considering support snake_case for JsonFormat

### ISSUE THREAD

**Issue by zhihuawensc** [google/protobuf#795]
Currently even if the proto file is written in snake_case, JsonFormat will still generate json string in camelCase. Please considering adding the option to generate json in snake_case.

**Comment by xfxyjwf** [comment]
Hi @zhihuawensc 
Just want to let you know we have discussed this feature request this week and think it's reasonable to support. It's a pretty strait-forward feature to implement. You can expect it to hit the master branch soon (likely 1 or 2 weeks).

**Comment by zhihuawensc** [comment]
Thanks a lot.



On Thu, Sep 10, 2015 at 6:29 PM, Feng Xiao <notifications@github.com> wrote:

> Hi @zhihuawensc <https://github.com/zhihuawensc>
> Just want to let you know we have discussed this feature request this week
> and think it's reasonable to support. It's a pretty strait-forward feature
> to implement. You can expect it to hit the master branch soon (likely 1 or
> 2 weeks).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/google/protobuf/issues/795#issuecomment-139425948>.
>



-- 
Zhihua Wen

**Comment by chrsmith** [comment]
Any update on this? This is currently blocking my ability to work with another proto3-based project (https://github.com/google/kythe).

To restate the problem: the proto defines a field in snake_case and `JsonFormatter` outputs in camelCase. So it is impossible round-trip protos to JSON and back as a result. Specifically, I'm writing JSON-encoded protos from the C# implementation, and trying to parse them in Go.

Is this supposed to be a supported scenario? Or am I doing it the wrong way?

**Comment by xfxyjwf** [comment]
In Java, JsonFormat.Printer now has a preservingProtoFieldNames() option, with which the JSON output will use whatever name you specified in the .proto file.

Also there is a field option added to customize the JSON field name:
```proto
message Foo {
  int32 value = 1 [json_name = "some_other_name"];
}
```

Note that the two cannot be used together.

**Comment by mxmark** [comment]
Is there any any option to generate snake_case names in C++ as well (apart from specifying individual 'json_name' options for each field) ? This would be quite useful..

**Comment by xfxyjwf** [comment]
There isn't such an option in C++ yet, but feel free to send me a PR to add it.

**Comment by hookover** [comment]
Is there any any option to generate snake_case names in PHP as well ?
