### ISSUE TITLE
Generate minimum code for nano java

### ISSUE THREAD

**Issue by wora** [google/protobuf#798]
Just some ideas to share:
- The generated parse code checks for whether to preserve unknown fields. The proto3 semantics does not require preserved unknown fields, so we shouldn't need to check it.
- Can we use a "/dev/null" style output stream for writeTo() and use it calculate estimate size. This avoid generate extra method for each message.
- The generated code contains comment like "// optional foo xx = 1". We should remove optional here.

**Comment by haberman** [comment]
We don't have any further plans to develop nano. We recommend lite over nano.
