### ISSUE TITLE
in C++ int64 == long long int

### ISSUE THREAD

**Issue by ekg** [google/protobuf#801]
I've noticed that int64 types are now represented as long long ints in C++. Why the change? Is this because we're only guaranteed that long's are "at least" 32 bits wide? In practice, this seems to mean that long ints are 64 bits wide, but maybe this isn't true for all implementations?

**Comment by xfxyjwf** [comment]
On Visual Studio, long is always 4 bytes (i.e., 32 bits) no matter whether it's x86 or x64 that your binary is built for.

Any issues for int64 being "long long"?

**Comment by ekg** [comment]
It's not a fundamental problem, although it adds a bit of a roadbump to development in. Although `sizeof(int64_t) == sizeof(long) == sizeof(long long)` on 64-bit linux systems, we've tended to use `long`/`int64_t` for storing ids. These aren't recognized by compilers as compatible types despite the fact that they are the same size, so upgrading to match this change will require a nice bit of finding and replacing. It sounds like it's preferable to have it as you've changed it though.

**Comment by xyzzyz** [comment]
I'd like to ask to reconsider making int64 to be int64_t, as opposed to being long long. int64_t is specifically designed to just what int64 is meant to be, and is future-proof -- we might live to see long long to be 128 bit on future platforms. Even though long long is freely convertible to int64_t right now, these are not the same types usually, and it really shows when e.g. one wants to declare a variable with type RepeatedPtrField<int64_t> (must use RepeatedPtrField<::google::protobuf::int64>), or implement their own ZeroCopyOutputStream (int64_t ByteCount() doesn't work, must be ::google::protobuf::int64 ByteCount()).

**Comment by ekg** [comment]
I agree! We should make it future proof and set it to be int64_t.

**Comment by xfxyjwf** [comment]
Compatibility with int64_t seems a compelling reason. I guess it's better to define int64 as int64_t if int64_t is available.

**Comment by mridulnagpal** [comment]
i have sent a PR replacing all the int64 with int64_t

**Comment by phylake** [comment]
I'm running into this too. @mridulnagpal please link the PR.

**Comment by phylake** [comment]
Then why is it an open issue? I'm running v3.3.0

```bash
root@hp:/host/build# protoc --version
libprotoc 3.3.0
root@hp:/host/build# gcc --version
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by xfxyjwf** [comment]
This is fixed in https://github.com/google/protobuf/commit/a17367f44a3b592993d2ac5c074ed58fb0ce784c

**Comment by phylake** [comment]
Thanks @xfxyjwf
