### ISSUE TITLE
Consider returning null instead of throwing an exception in MessageDescriptor.FieldCollection indexers

### ISSUE THREAD

**Issue by jskeet** [google/protobuf#803]
Currently it's a bit of a pain to conditionally request a field from a FieldCollection, because the indexers will throw a KeyNotFoundException. This is what `IDictionary<,>` does, but that may be partly because the dictionaries values could be of a value type - whereas here we know it will be a FieldDescriptor.

This is a trivial change to implement - it's a matter of whether or not we *want* to implement it....

/cc: @jtattermusch

**Comment by jtattermusch** [comment]
I've always thought of indexer [] throwing KeyNotFoundException as a rule of thumb. An alternative would be to just add TryGet method.
https://msdn.microsoft.com/en-us/library/bb347013(v=vs.110).aspx

**Comment by jskeet** [comment]
I'm not sure it's a rule of thumb so much as what makes sense for `Dictionary<,>` - a lookup returns an empty sequence, for example. We *could* add `TryGet`, but it feels somewhat unnecessary when `null` is available. Hmm. Will keep pondering.

**Comment by jtattermusch** [comment]
I'd be probably fine with returning null. Are you convinced getting a field conditionally will have its use?
I imagine two common scenarios:
1. I know what message type I am dealing with, so I only touch fields that actually exist. KeyNotFound Exception probably makes sense here.
2. I don't know what messages type I am dealing with, so I iterate over the fields in fieldcollection. At later point, whenever I decide to use indexer, I know the field should be there. KeyNotFound Exception makes sense again.

**Comment by jskeet** [comment]
I thought about this mostly when I was spiking JSON parsing (which won't actually use the indexers, but...) In that case, I want to detect a field being absent, but throw a *different* exception. I could catch KeyNotFoundException and rethrow a wrapped one, but it's a bit ugly. Definitely a good idea to think about use cases for this though...

**Comment by jskeet** [comment]
In JSON parsing we're exposing a dictionary anyway. Callers could always create their own dictionary if necessary. Closing this.
