### ISSUE TITLE
in protobuf2.6.1 java and python serialize different bytes

### ISSUE THREAD

**Issue by ming15** [google/protobuf#805]
I meet a error, 
I trid to serialize a same object use python and java, and write these bytes to file.

then i watched these files with hex, 
java generate:
```
0A 04 08 01 10 1E 0A 04 08 02 10 1E
```
python generate 
```
0D 0A 04 08 01 10 1E 0D 0A 04 08 02 10 1E
```

see, in python file, it appends a `0D`, this is why?

i use 2.6.1 protobuf

**Comment by lutzhorn** [comment]
What is the definition?

**Comment by wanggnim** [comment]
config.proto
```
import "BiyunLevel.proto";

option java_package = "wang.gnim.excel";

message ExcelConfig { 
    repeated Sheet1 Sheet1s = 1;
}
```

BiyunLevel.proto
```
option java_package = "wang.gnim.excel";

message Sheet1 { 
    optional uint32 level = 1;
    optional uint32 star1 = 2;
}
```

the test file is : https://github.com/wanggnim/excel2protobuf/tree/master/src/test

**Comment by xfxyjwf** [comment]
0A is '\n' and 0D 0A is '\r\n'. It sounds like you are writing the data into a text file and '\n' is automatically converted to '\r\n'. To fix the problem you should write your data into a binary file.

**Comment by wanggnim** [comment]
ok, thanks, i will hava a try
