### ISSUE TITLE
Proto does not compile with -Wsign-conversion

### ISSUE THREAD

**Issue by ctiller** [google/protobuf#807]
We'd like to enable `-Wsign-conversion -Werror` this for gRPC, however we get build failures with gRPC code that pulls in protobuf headers (all over the place - I can link a build trace if needed).

Would it be possible to at least clean up public headers so that the code compiles with this flag combination?

**Comment by xfxyjwf** [comment]
Cleanup this in public headers seems reasonable to me.

I do need some tests to cover this though.
