### ISSUE TITLE
can use gmock as git submodule?

### ISSUE THREAD

**Issue by i5ting** [google/protobuf#808]
https://github.com/google/googletest/tree/master/googlemock

**Comment by edmonds** [comment]
Submodules are very problematic. Consider the "subtree" merge strategy instead:

https://www.kernel.org/pub/software/scm/git/docs/howto/using-merge-subtree.html

**Comment by xfxyjwf** [comment]
"subtree" is something new to me. We should align with grpc (https://github.com/grpc/grpc) though. They are using submodules so we probably should do the same in protobuf for third_party dependencies.

**Comment by xfxyjwf** [comment]
Same issue as: https://github.com/google/protobuf/issues/236
