### ISSUE TITLE
Successful serializing, exception while deserializing

### ISSUE THREAD

**Issue by fabiannagel** [google/protobuf#809]
How can the serialization of a message can be successful while the deserialization causes an exception? In detail:

"com.google.protobuf.InvalidProtocolBufferException: While parsing a protocol message, the input ended unexpectedly in the middle of a field.  This could mean either than the input has been truncated or that an embedded message misreported its own length."

I get this error in Python as well as in Java code, so this doesn't seem to be an implementation issue. Serializing and deserializing happens in the same module, so I really don't see where any truncation should happen as it's the exact same variable.

Is there any way to debug this error? My proto file is right here: https://gist.github.com/fabiannagel/9658d947b6b43ddacdcc

**Comment by xfxyjwf** [comment]
How does your Java code look like?

**Comment by fabiannagel** [comment]
See here: https://gist.github.com/fabiannagel/ddd3add898ef260cea9e

testSerialization() is just a method I created to further investigate the error. Normally, the deserialization would be done in a Python module.

**Comment by xfxyjwf** [comment]
You store binary data in strings, which will corrupt the original data.

**Comment by fabiannagel** [comment]
This crossed my mind for a second, but the deserialization worked for a couple of formatted messages. The described error just happend every couple tries or so. So I'll just change this to a regular byte array and it should work. Thanks!
