### ISSUE TITLE
Publish 3.0.0.alpha.4 to RubyGems

### ISSUE THREAD

**Issue by kmontag** [google/protobuf#810]
Would be great to be able to depend on the latest version of the gem without having to use bundler git trickery :)

Thanks!

**Comment by benmccann** [comment]
FYI, 3.0.0-beta-1 is the latest version.

Any word on when 3.0.0 final will be released?

**Comment by xfxyjwf** [comment]
We expect all languages to reach beta before the end of this year. After that the 3.0.0 final release will probably happen in Q1 2016.

**Comment by haberman** [comment]
@benmccann That's not entirely true. For Ruby, since it hasn't reached what we consider "beta" readiness, was released as alpha 4 instead of beta 1.

**Comment by haberman** [comment]
I just published alpha-4 to RubyGems. Sorry for the delay.
