### ISSUE TITLE
ProtocolBuffer C++ LNK2001 Problem

### ISSUE THREAD

**Issue by mrev1l1** [google/protobuf#812]
I'm trying to use protocol buffers, but i keep getting the same errors no matter what i do
Error	3	error LNK2001: unresolved external symbol "int google::protobuf::internal::empty_string_once_init_" (?empty_string_once_init_@internal@protobuf@google@@3HA)	D:\Projects\protobufSerealizer\protobufSerealizer\test.pb.obj	protobufSerealizer
Error	2	error LNK2001: unresolved external symbol "class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const * const google::protobuf::internal::empty_string_" (?empty_string_@internal@protobuf@google@@3PBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@B)	D:\Projects\protobufSerealizer\protobufSerealizer\test.pb.obj	protobufSerealizer

any ideas of how to solve it?

**Comment by dinoframe** [comment]
Similar linking error in VS 2015/Release config has been resolved by changing:
libprotobuf project-> Properties-> C/C++ -> Optimization -> Inline Function Expansion -> from Any Suitable to Disabled

**Comment by martin34** [comment]
I have the same problem, even if I disable Inline Function Expansion. 
Is there an other solution?

**Comment by Wufflez** [comment]
I'm having exactly the same problem

**Comment by mgalayko** [comment]
This fixed the same problem for me: http://stackoverflow.com/a/16065204.

**Comment by adam-zhang** [comment]
"This fixed the same problem for me: http://stackoverflow.com/a/16065204."
It doesn't work neither.
