### ISSUE TITLE
template method may cause malloc/free mismatch

### ISSUE THREAD

**Issue by feiyunw** [google/protobuf#816]
# Problem description:
My Windows app (VC++ 2008 SP1) uses libprotobuf-lite. When I used the release version libprotobuf-lite for debug mode app development, it reported heap corruption when calling RepeatedPtrFieldBase::Destroy(). But everything was OK when I linked to the debug version libprotobuf-lite.

# Root cause analysis:
1. When building the release version libprotobuf-lite, it uses release version VC library:
```javascript
void** RepeatedPtrFieldBase::InternalExtend(int extend_amount) {
...
    rep_ = reinterpret_cast<Rep*>(
        new char[kRepHeaderSize + sizeof(old_rep->elements[0]) * new_size]);
```
The above code in repeated_field.cc is a usual member function. The "new" and its underneath "malloc" use the release version VC library.
2. When building the debug version application, its uses debug version VC library:
```javascript
template <typename TypeHandler>
void RepeatedPtrFieldBase::Destroy() {
...
      delete [] reinterpret_cast<char*>(rep_);
```
This template method needs a template parameter to generate the object target (as an .obj file), thus the code generation has to be postponed until building the application.
Hence the "delete" and its underneath "free" use the debug version VC library.
The mismatch of malloc and free version caused the heap corruption.

# Conclusion:
I suggest to modify such template methods which handle new/delete, so that both new and delete should be in template methods, or neither of them.

**Comment by xfxyjwf** [comment]
I don't think we can guarantee that (put all new/delete in template methods or none of them). I suggest you use debug lib with a debug app and the release lib with a release app.

Or this should be filed as a bug to VC if mixing release lib with debug apps is a supported use case. Their malloc/free functions must behave consistently in both builds.
