### ISSUE TITLE
Objective-C: Conflicting nullability specifier caused by setValue:forKey:

### ISSUE THREAD

**Issue by MaxGabriel** [google/protobuf#818]
Hi, I'm getting the following error when compiling on Xcode 7.0:

```
Conflicting nullability specifier on parameter types, 'nonnull' conflicts with existing specifier 'nullable'
```

This error occurs for each instance of `setValue:forKey:`:

```
- (void)setValue:(id)value forKey:(BOOL)key;
```

since the superclass (`NSObject`) implementation defines it as:

```
- (void)setValue:(nullable id)value forKey:(NSString *)key;
```

A potential easy fix is to just change the nullability annotations on the `setValue:forKey:` methods to use the `nullable` attribute for the value. Alternatively, I believe these declarations could be deleted because the `setValue:forKey:` method is already present on their superclass.

**Comment by MaxGabriel** [comment]
If possible it would be nice to have an `objective-c` label for this issue.

**Comment by thomasvl** [comment]
https://github.com/google/protobuf/pull/841 should handle this.
