### ISSUE TITLE
Objective-C: Conflicting parameter types in implementation of 'setValue:forKey:'

### ISSUE THREAD

**Issue by MaxGabriel** [google/protobuf#820]
Hi, I'm getting warnings because the type of the `key` parameter is being overridden in methods like this:

```
- (void)setValue:(id)value forKey:(BOOL)key
```

which causes the following warning:

```
Conflicting parameter types in implementation of 'setValue:forKey:': 'NSString * _Nonnull' vs 'BOOL _Nonnull' (aka 'bool')
```

I'm using Xcode 7. I can't reproduce these warnings in the Protobuf project itself, only when importing the files into my project.

<hr>

These warnings could be ignored like so:

```
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wmismatched-parameter-types"
- (void)setValue:(id)value forKey:(BOOL)key {
#pragma clang diagnostic pop
```

Alternatively, the method name could be changed to not override the `NSObject` `setValue:forKey:` method (I don't know if the override is intentional).

Would you be interested in me implementing either of these solutions?

**Comment by thomasvl** [comment]
https://github.com/google/protobuf/pull/841 should handle this.
