### ISSUE TITLE
Unresolved external symbols in MSVC 14 (VS 2015)

### ISSUE THREAD

**Issue by PeterBocan** [google/protobuf#821]
Hello guys, I do have one little problem building "protoc" application on Windows - unresolved external symbols:

    1>------ Build started: Project: protoc, Configuration: Release x64 ------
    1>libprotobuf.lib(generated_message_reflection.obj) : error LNK2019: unresolved external symbol "public: static class google::protobuf::Arena * __cdecl google::protobuf::internal::GenericTypeHandler<class google::protobuf::Message>::GetArena(class google::protobuf::Message *)" (?GetArena@?$GenericTypeHandler@VMessage@protobuf@google@@@internal@protobuf@google@@SAPEAVArena@34@PEAVMessage@34@@Z) referenced in function "protected: void __cdecl google::protobuf::internal::RepeatedPtrFieldBase::AddAllocatedInternal<class google::protobuf::internal::GenericTypeHandler<class google::protobuf::Message> >(class google::protobuf::Message *,struct google::protobuf::internal::integral_constant<bool,1>)" (??$AddAllocatedInternal@V?$GenericTypeHandler@VMessage@protobuf@google@@@internal@protobuf@google@@@RepeatedPtrFieldBase@internal@protobuf@google@@IEAAXPEAVMessage@23@U?$integral_constant@_N$00@123@@Z)
    1>libprotobuf.lib(map_field.obj) : error LNK2001: unresolved external symbol "public: static class google::protobuf::Arena * __cdecl google::protobuf::internal::GenericTypeHandler<class google::protobuf::Message>::GetArena(class google::protobuf::Message *)" (?GetArena@?$GenericTypeHandler@VMessage@protobuf@google@@@internal@protobuf@google@@SAPEAVArena@34@PEAVMessage@34@@Z)
    1>libprotobuf.lib(generated_message_reflection.obj) : error LNK2019: unresolved external symbol "public: static void * __cdecl google::protobuf::internal::GenericTypeHandler<class google::protobuf::Message>::GetMaybeArenaPointer(class google::protobuf::Message *)" (?GetMaybeArenaPointer@?$GenericTypeHandler@VMessage@protobuf@google@@@internal@protobuf@google@@SAPEAXPEAVMessage@34@@Z) referenced in function "protected: void __cdecl google::protobuf::internal::RepeatedPtrFieldBase::AddAllocatedInternal<class google::protobuf::internal::GenericTypeHandler<class google::protobuf::Message> >(class google::protobuf::Message *,struct google::protobuf::internal::integral_constant<bool,1>)" (??$AddAllocatedInternal@V?$GenericTypeHandler@VMessage@protobuf@google@@@internal@protobuf@google@@@RepeatedPtrFieldBase@internal@protobuf@google@@IEAAXPEAVMessage@23@U?$integral_constant@_N$00@123@@Z)
    1>libprotobuf.lib(map_field.obj) : error LNK2001: unresolved external symbol "public: static void * __cdecl google::protobuf::internal::GenericTypeHandler<class google::protobuf::Message>::GetMaybeArenaPointer(class google::protobuf::Message *)" (?GetMaybeArenaPointer@?$GenericTypeHandler@VMessage@protobuf@google@@@internal@protobuf@google@@SAPEAXPEAVMessage@34@@Z)
    1>C:\Dev\protobuf-3.0.0-beta-1\cmake\builds\Release\protoc.exe : fatal error LNK1120: 2 unresolved externals
    ========== Build: 0 succeeded, 1 failed, 3 up-to-date, 0 skipped ==========

I've tried to link against debug and release libraries, but I haven't been successful. Any idea how to fix it?

**Comment by xfxyjwf** [comment]
This is a known issue. It's fixed in master branch but not included in beta-1 release. You can try to sync to master and see if the problem persist.
See: https://github.com/google/protobuf/issues/240

**Comment by PeterBocan** [comment]
Okay, I'll try master branch.

**Comment by PeterBocan** [comment]
And, I must say, it works. :+1:
