### ISSUE TITLE
typedef int64 to "long long" causes compatibility issues

### ISSUE THREAD

**Issue by chinmayatm** [google/protobuf#823]
One of the changes in the latest proto3 library is that the following typedefs are changed from

typedef int64_t int64;
typedef uint64_t int64;
to
typedef long long int64;
typedef unsigned long long uint64;

In our codebase we have int64_t & uint64_t based typedefs and some of the things becomes incompatible with the newest definitions. Google logging library also as it as int64_t based typedef.

Feng Xiao is aware of this issue.

**Comment by chinmayatm** [comment]
Hello Feng, any updates on this. we are presently using the alpha2 version of protbuf3 and we would ideally like to upgrade to beta1 soon. Thanks!

**Comment by xfxyjwf** [comment]
@chinmayatm Could you patch it locally as a temporary solution? This cannot be fixed in beta1 because beta-1's already out. I'll only get time to work on this when we start the next beta-2 release.

**Comment by chinmayatm** [comment]
@xfxyjwf applied the following patch on beta1 and started using it.

index 9f4fb82..6f65323 100644
--- a/src/google/protobuf/stubs/int128.cc
+++ b/src/google/protobuf/stubs/int128.cc
@@ -145,15 +145,18 @@ std::ostream& operator<<(std::ostream& o, const uint128& b) {
   std::streamsize div_base_log;
   switch (flags & std::ios::basefield) {
     case std::ios::hex:
-      div = GOOGLE_ULONGLONG(0x1000000000000000);  // 16^15
+      div = static_cast<uint64>(
+          GOOGLE_ULONGLONG(0x1000000000000000));  // 16^15
       div_base_log = 15;
       break;
     case std::ios::oct:
-      div = GOOGLE_ULONGLONG(01000000000000000000000);  // 8^21
+      div = static_cast<uint64>(
+          GOOGLE_ULONGLONG(01000000000000000000000));  // 8^21
       div_base_log = 21;
       break;
     default:  // std::ios::dec
-      div = GOOGLE_ULONGLONG(10000000000000000000);  // static_cast<uint64>(
+          GOOGLE_ULONGLONG(10000000000000000000));  // 10^19
       div_base_log = 19;
       break;
   }
diff --git a/src/google/protobuf/stubs/port.h b/src/google/protobuf/stubs/port.h
index 9ea34cd..5620178 100644
--- a/src/google/protobuf/stubs/port.h
+++ b/src/google/protobuf/stubs/port.h
@@ -100,15 +100,15 @@ typedef unsigned __int16 uint16;
 typedef unsigned __int32 uint32;
 typedef unsigned __int64 uint64;
 #else
-typedef signed char  int8;
-typedef short int16;
-typedef int int32;
-typedef long long int64;
-
-typedef unsigned char  uint8;
-typedef unsigned short uint16;
-typedef unsigned int uint32;
-typedef unsigned long long uint64;
+typedef int8_t  int8;
+typedef int16_t int16;
+typedef int32_t int32;
+typedef int64_t int64;
+
+typedef uint8_t  uint8;
+typedef uint16_t uint16;
+typedef uint32_t uint32;
+typedef uint64_t uint64;
 #endif
 
 // long long macros to be used because gcc and vc++ use different suffixes,
