### ISSUE TITLE
Compile error in generated Java code if tag # on a field is greater than half the documented max

### ISSUE THREAD

**Issue by imacleish** [google/protobuf#826]
If you use a tag number greater than 268,435,455 (half the maximum - 1) generated Java code will fail to compile because it generates an int literal that's too large for a signed integer.

**Comment by lrdcasimir** [comment]
It seems like the SimpleAtoI code assumes a full 32 bits of precision in the resulting literal here:
https://github.com/google/protobuf/blob/8eebad1082816e3fa189af07b74162c13e730a21/src/google/protobuf/compiler/java/java_message.cc#L1180

**Comment by acozzette** [comment]
I forgot to update this issue but this has been fixed for a while now.
