### ISSUE TITLE
Serializing null values in nullable collection throws nullreference

### ISSUE THREAD

**Issue by vipinlalvs** [google/protobuf#827]
class Program
    {
        [ProtoContract]
        public class ProtoTest
        {
            [ProtoMember(1)]
            public List<string> Collecton { get; set; }
        }
        static void Main(string[] args)
        {
            ProtoTest test = new ProtoTest();
            test.Collecton = new List<string>();
            test.Collecton.Add("A");
            test.Collecton.Add(null);
            test.Collecton.Add("B");
            test.Collecton.Add(null);

            //This code works fine on Protobuf 1.0.0.282
            //But throws exception on Protobuf 2.0.0.668
            byte[] buffer = Serialize<ProtoTest>(test);
            ProtoTest converted = Deserialize<ProtoTest>(buffer);

            //In 1.0.0.282 converted.Collection is having 2 items excluded null values.
            //In 2.0.0.668 Serialization fails with NullReference exception.
            Console.Read();
           
        }

        static byte[] Serialize<T>(T objectToSerialize)
        {
            using (MemoryStream ms = new MemoryStream())
            {
                Serializer.Serialize<T>(ms, objectToSerialize);
                ms.Position = 0;
                return ms.ToArray();
            }
        }

        static T Deserialize<T>(byte[] uncompressedBytes)
        {
            using (MemoryStream ms = new MemoryStream(uncompressedBytes))
            {
                return Serializer.Deserialize<T>(ms);
            }
        }
    }

While executing this code we are getting NullReferenceException on Serialize with latest Protobuf V2. But it works fine with V1.
Worst part of the NullReferneceException behavior is, for a large DTO we wont be able to figure out which type/collection is having null value. We have tried this solution https://code.google.com/p/protobuf-net/issues/detail?id=217. 
But can we have the earlier version behavior than throwing NullReferenceException. Could you please tell us why you people removed the old behavior? 

For null values on reference types, Protobuf V2 is creating default instance with default values. But in earlier version it was just neglecting null values.
Please find the scenario below.
  

     
    class Program
    {
        [ProtoContract]        
        public abstract class NullableBase
        {
            public NullableBase()
            {
            }

            [ProtoMember(1)]
            public int? Value { get; set; }            
        }

        [ProtoContract]
        public class NullableChild:NullableBase
        {
            [ProtoMember(2)]
            public string StrValue { get; set; }
        }

        [ProtoContract]
        public class ProtoTest
        {
            [ProtoMember(1)]
            public List<NullableBase> RefCollecton { get; set; }

        }

        static void Main(string[] args)
        {
            var nullableBaseType=ProtoBuf.Meta.RuntimeTypeModel.Default.Add(typeof(NullableBase), true);
            nullableBaseType.AddSubType(100, typeof(NullableChild));
            ProtoTest test = new ProtoTest();

            test.RefCollecton = new List<NullableBase>();
            test.RefCollecton.Add(new NullableChild() { StrValue = "A" });
            test.RefCollecton.Add(new NullableChild() { StrValue = "B" });
            test.RefCollecton.Add(null);

            byte[] buffer = Serialize<ProtoTest>(test);
            //For null values on reference type Protobuf is trying to create default instance.
            //Here the type is NullBase and its an abstract class. Protobuf wont be able to create it and throwing exception.
            //Why Protobuf creates default instance for null values.
            ProtoTest converted = Deserialize<ProtoTest>(buffer);
            Console.Read();
           
        }

        static byte[] Serialize<T>(T objectToSerialize)
        {
            using (MemoryStream ms = new MemoryStream())
            {
                Serializer.Serialize<T>(ms, objectToSerialize);
                ms.Position = 0;
                return ms.ToArray();
            }
        }

        static T Deserialize<T>(byte[] uncompressedBytes)
        {
            using (MemoryStream ms = new MemoryStream(uncompressedBytes))
            {
                return Serializer.Deserialize<T>(ms);
            }
        }
    }

**Comment by jskeet** [comment]
Sorry for not noticing this before - but this is not the right project to report this issue on. Please report the issue separately on https://github.com/mgravell/protobuf-net
