### ISSUE TITLE
Language guide: 'Any' → 'google.protobuf.Any'

### ISSUE THREAD

**Issue by wking** [google/protobuf#828]
I couldn't find the repository behind [the Any docs](https://developers.google.com/protocol-buffers/docs/proto3#any), so I'm filing this here.

The current example:

```
$ cat test.proto
syntax = "proto3";

import "google/protobuf/any.proto";

message ErrorStatus {
  string message = 1;
  repeated Any details = 2;
}
```

Fails to compile:

```
$ protoc --go_out=./go test.proto 
test.proto:7:12: "Any" is not defined.
[libprotobuf WARNING google/protobuf/descriptor.cc:6135] Warning: Unused import: "test.proto" imports "google/protobuf/any.proto" which is not used.
```

But with a namepaced `google.protobuf.Any` it works:

```
$ sed -i 's/Any/google.protobuf.Any/' test.proto
$ protoc --go_out=./go test.proto
$ echo $?
0
```

**Comment by yangyuan6** [comment]
fixed:
cd ~ && mkdir pb && cd pb && git clo https://github.com/protocolbuffers/protobuf.git
protoc proto/example.proto     --go_out=. --go-grpc_out=. --zrpc_out=.  -I=~/pb/protobuf/src -I={ proto/example.proto directory } 

<img width="874" height="56" alt="Image" src="https://github.com/user-attachments/assets/07c001a6-eb1e-4558-83eb-d45843814dce" />
