### ISSUE TITLE
Can not use 'Any' type in python

### ISSUE THREAD

**Issue by hhzzk** [google/protobuf#830]
Hi,
My .proto file like this:
```python
syntax = "proto3";
import "google/protobuf/any.proto";

 message HidargsReply {
     map<string, Any> hidargs = 1;
 }
```
to compile and get:
```shell
db_op.proto: "Any" is not defined.
[libprotobuf WARNING google/protobuf/descriptor.cc:6135] Warning: Unused import: "db_op.proto" imports "google/protobuf/any.proto" which is not used.
```
and the platform I used:
```shell
$ python --version
Python 2.7.6
$ protoc --version
libprotoc 3.0.0
```
Thanks for any feedback.

**Comment by xfxyjwf** [comment]
This is a duplicate of https://github.com/google/protobuf/issues/828. To reference Any, you need to use "google.protobuf.Any". The language guide needs update.

**Comment by hhzzk** [comment]
With "google.protobuf.Any" I still get error:
```shell
db_op.proto: Import "google.protobuf.Any" was not found or had errors.
db_op.proto: "Any" is not defined.
```
and I use python plugin, is it still under development ?

**Comment by xfxyjwf** [comment]
Try:
```proto
syntax = "proto3";
import "google/protobuf/any.proto";

 message HidargsReply {
     map<string, google.protobuf.Any> hidargs = 1;
 }
```

**Comment by hhzzk** [comment]
yes, it works.
Thanks a lot..

**Comment by hhzzk** [comment]
Still has problem use Any type in python:
After compile by following command:
```shell
protoc -I ./ --python_out=. --grpc_out=. --plugin=protoc-gen-grpc=`which grpc_python_plugin` ./db_op.proto
```
I got db_op_pb2.py,  the following sentence :
```shell
from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2
```
 calls import error:
```shell
from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2
ImportError: cannot import name any_pb2
```
and the protobuf version I used:
```python
>>> import google.protobuf
>>> google.protobuf.__version__
'3.0.0a4'
>>> 
```
and also I can't find any package named any_pb2 in google.protobuf.

Thanks

**Comment by xfxyjwf** [comment]
It seems Any is not included in Python runtime. We should fix the setup.py script to include Any (and other well-known types).

**Comment by hhzzk** [comment]
@xfxyjwf  This issue was resolved by commit [7464f40](https://github.com/google/protobuf/commit/7464f40a7e1fa6d5d0c3d4131720e7863d864eb8)

**Comment by EricBuist** [comment]
And what do we do until this is fixed? Why is this so clunky? I spent three days trying and trying again to automate the generation of code from .proto files and this any.proto always comes back as an issue, for different languages. I cannot modify the source .proto files to replace this with something else for the time being.

**Comment by yangyuan6** [comment]
fixed:
`cd ~ && mkdir pb && cd pb && git clo https://github.com/protocolbuffers/protobuf.git`
`protoc proto/example.proto     --go_out=. --go-grpc_out=. --zrpc_out=.  -I=~/pb/protobuf/src -I={ proto/example.proto directory }`
