### ISSUE TITLE
Pull comments out of .proto files for XML comments in generated C#

### ISSUE THREAD

**Issue by jskeet** [google/protobuf#832]
Ideally, we should parse the comments as Markdown and then reformat them as best we can into C# XML comments. That's a _lot_ of work.

As a temporary measure, we could generate mono-spaced comments as Java does here:
https://github.com/google/protobuf/blob/master/src/google/protobuf/compiler/java/java_doc_comment.cc

**Comment by jskeet** [comment]
First pass at this was merged in PR #845.

**Comment by xfxyjwf** [comment]
Is this done?
