### ISSUE TITLE
Crash on map fields if protobuf library is built without C++11 but used in an app built with C++11.

### ISSUE THREAD

**Issue by xfxyjwf** [google/protobuf#839]
To reproduce:
1. Build and install protobuf following instructions in README.md.
2. Add the following code snippet to examples/add_person.cc (in main):
   
   ``` cpp
   google::protobuf::Struct st;
   google::protobuf::Value value;
   (*st.mutable_fields())["LogMessage"] = value;
   ```
3. Build add_person_cpp with -std=c++11:
4. Run ./add_person_cpp

It will crash with Floating point exception. Stack trace: [stack_trace.txt](https://github.com/google/protobuf/files/4825/stack_trace.txt)

Compiling without -std=c++11 works fine.

**Comment by haberman** [comment]
I'm not sure this is a bug. C++98 and C++11 have incompatible ABIs when it comes to libstdc++. I think that people who are using C++11 need to compile protobuf as C++11 also, if I'm understanding correctly.

For more info see: https://gcc.gnu.org/wiki/Cxx11AbiCompatibility

**Comment by xfxyjwf** [comment]
It seems pretty easy to make this mistake if protobuf and the user's application are built separately (e.g., users install protobuf via "apt-get install protobuf" and then use the installed lib to build their code). If there is a way to work-around it, we probably should do. If it's hard to work-around, I guess we should at least try to produce some more meaningful error message.

**Comment by haberman** [comment]
I don't think there's anything we can do about this case. People who are using C++11 will need to make sure protobuf is built as C++11, and we can't really work around this or usefully warn about this case.
