### ISSUE TITLE
Python runtime for Protobuf 3.0.0 alpha 4 on Pypi

### ISSUE THREAD

**Issue by rguldener** [google/protobuf#840]
Any chance we get to see alpha 4 (as bundled in the beta 1 release of the language) of protobuf 3.0.0 for Python runtime on Pypi anytime soon?

I am referring to this release: https://github.com/google/protobuf/releases/tag/v3.0.0-beta-1

**Comment by xfxyjwf** [comment]
FYI. We have uploaded 3.0.0b2 to the pypi site.
