### ISSUE TITLE
Expand benchmarks for Java

### ISSUE THREAD

**Issue by nmittler** [google/protobuf#842]
From https://github.com/grpc/grpc-java/issues/1054:

```
Implement some basic protobuf benchmarks independent of GRPC
(scrape the web or extract Googles) as a framework for experimenting
with optimizations
```
The gRPC team has a few ideas for optimizing protobuf marshalling but we need to expand the benchmark suite before that work can begin.

cc/ @louiscryan @ejona86 @xfxyjwf

**Comment by nmittler** [comment]
FYI, I'd be happy to do the work here.

**Comment by xfxyjwf** [comment]
The benchmarks for proto Java are not opensourced. I suggest we track this bug internally, add new benchmarks to our internal code base and then get part of these benchmarks opensourced if needed.

**Comment by xfxyjwf** [comment]
Also, for significant protobuf changes like this we should do it internally first to make sure it does not impact google3 users negatively.

**Comment by nmittler** [comment]
@xfxyjwf sgtm ... I'll close this for now and continue internally.  Thanks.
