### ISSUE TITLE
./configure error

### ISSUE THREAD

**Issue by kimeuichan** [google/protobuf#844]
$ ./configure
.
.
.
checking for working strtod... yes
checking for ftruncate... yes
checking for memset... yes
checking for mkdir... yes
checking for strchr... yes
checking for strerror... yes
checking for strtol... yes
checking zlib version... headers missing or too old (require
./configure: line 15810: ACX_PTHREAD: command not found
./configure: line 15821: AC_CXX_STL_HASH: command not found
configure: creating ./config.status
config.status: error: cannot find input file: `Makefile.in'

also i use aclocal,autoconf,autoheader,automake --add-missing

what can i do?

**Comment by xfxyjwf** [comment]
What's the autoconf version you are using?

**Comment by kimeuichan** [comment]
i use 2.68 version

**Comment by xfxyjwf** [comment]
Mine is 2.69 so it doesn't seem to be the problem. What version of protobuf are you using? And what exact commands you ran before ./configure? Could you try to download one of the release tarballs listed in the release page (https://github.com/google/protobuf/releases/tag/v3.0.0-beta-1) and see if these work?

**Comment by kimeuichan** [comment]
i use latest version of protobuf and i commands aclocal ,autoconf, autoheader ,automake --add-missing
. i want to build CuraEngine.. .I don't know how using url you give me

**Comment by xfxyjwf** [comment]
Can you follow this [README.md](https://github.com/google/protobuf/blob/master/README.md) file and do:
```bash
$ ./autogen.sh
$ ./configure
```
?

If it still doesn't work, try download this [protobuf-cpp-v3.0.0-beta-1.tar.gz](https://github.com/google/protobuf/releases/download/v3.0.0-beta-1/protobuf-cpp-3.0.0-beta-1.tar.gz), untar it, and run ./configure directly.

**Comment by kimeuichan** [comment]
OMG... Thanks It's working!
