### ISSUE TITLE
Build documentation should mention the need to install autoconf

### ISSUE THREAD

**Issue by wrwg** [google/protobuf#847]
Many linux distributions don't have autoconf installed by default. For developers not familiar with C++ projects, which need to compile protoc from source, it is surprising that

    ./autogen.sh

... creates an error in this case. The documentation should mention the possible need to do

   sudo apt-get install autoconf

... as well as

   sudo apt-get install libtool

... which is needed by autoconf itself.

**Comment by xfxyjwf** [comment]
Added now.
