### ISSUE TITLE
setup.py sdist doesn't include enough files to build with --cpp_implementation

### ISSUE THREAD

**Issue by exomoxo** [google/protobuf#850]
A Python source package built with `setup.py sdist` (i.e. what's uploaded to PyPI) doesn't contain the C++ header files necessary to build the accelerated extension using `--cpp_implementation`.

It would really gel better with the Python ecosystem if `pip install protobuf  --install-option="--cpp_implementation"` just works. This would let projects include protobuf in their `requirements.txt`, and still seamlessly benefit from the C++ acceleration. We build and deploy server-side applications, and part of our pipeline includes quickly constructing the virtualenv from scratch using binary wheels, without Internet access and without invoking compilers.

Are there existing ideas on how to reach such a goal?
1. Including all the header files in `python/../src` and `python/google/protobuf` into the final sdist tarball is a good start. And `pip install` can rely on `libprotobuf.so` being already pre-installed somewhere.
2. Of course the most standalone way would involve including all the files to build `libprotobuf.so`. This would bloat the sdist tarball significantly, but many projects already involve such complex build steps, e.g. numpy and friends.

**Comment by pherl** [comment]
I think we are now releasing python c++ binary dist now.
