### ISSUE TITLE
How to define a structs tag in golang with protobuf? 

### ISSUE THREAD

**Issue by ZhiqinYang** [google/protobuf#853]
excuse me! 
i have some problem , How can i define a structs tag in golang with protobuf, i wana modify the default name . 
 i need a struct tag  is  "json:receipt-data", but i can't name field 'receipt-data' .

**Comment by xfxyjwf** [comment]
Only underscores ("_") are allowed in identifier names (message names, field names, etc). There isn't a way to workaround that. Though I have no idea what you mean by "struct tag" though. You probably want to file an issue to the golang/protobuf repo: https://github.com/golang/protobuf
