### ISSUE TITLE
NewCallback shouldn't be put into global namespace

### ISSUE THREAD

**Issue by mzhaom** [google/protobuf#857]
The callback.h provided by protobuf is incomplete and we have our own implementation of Closure and NewCallback function. But unfortunately protobuf's NewCallback function is pulled into global namespace and then successfully confused the compiler:

```
test.cc:108:9: error: cannot initialize a parameter of type 'Closure *' with an rvalue of type 'google::protobuf::Closure *'
```

**Comment by xfxyjwf** [comment]
Hi, could you check if the problem still persists?
