### ISSUE TITLE
Use pkgutil to allow successfully work with python packages that contain google or google/protobuf

### ISSUE THREAD

**Issue by tbetbetbe** [google/protobuf#859]
google/protobuf is a key dependency of python grpc.

Shortly, gRPC-based  will be published that contain either a top-level 'google' package, and in some cases other modules in the google/protobuf package.

At the moment using, any of these other packages will generally fail  because the protobuf package is installed
- the other google package will contain modules with the google package (sometimes in google/protobuf)
- when the protobuf package is installed, both google and google/protobuf end up being resolved to the protobuf package
- other paths on the sys.path are not searched

The result is importing modules from the other packages ends with 'No module named logging.v1'  for snippets like:

```python

from google.logging.v1 import ....

```

There is well-known way to resolve this using [pkgutil](https://docs.python.org/2/library/pkgutil.html)
- Use pkgutil.extend_path inside the __init__.py of the google and google/protobuf packages
E.g,

```python
import pkgutil
__path__ = pkgutil.extend_path(__path__, __name__)
```

A good online resource explaining this use of pkgutil is available at [pymotw:pkgutil](https://pymotw.com/2/pkgutil/)

**Comment by haberman** [comment]
Is this the same problem as described in https://github.com/google/protobuf/issues/713 ?

This is one of those issues that I'd be happy to accept a PR for. The only reason I haven't fixed it already is because the Python packaging ecosystem is (to me) really complicated and subtle, and so it often takes a lot of background research for me to determine exactly what the right fix is.

**Comment by xfxyjwf** [comment]
Same issue here: https://github.com/google/protobuf/issues/1153

**Comment by haberman** [comment]
Closing in favor of https://github.com/google/protobuf/issues/1296
