### ISSUE TITLE
Check whitespace around JSON formatting

### ISSUE THREAD

**Issue by jskeet** [google/protobuf#862]
Should a list of 1, 2, 3 be `[1, 2, 3]` or `[ 1, 2, 3 ]`?
Should an object with a field foo of value bar be `{"foo": "bar"}`, `{ "foo" : "bar" }` or something else?

Investigate current behaviour, and make C# consistent with others (e.g. Java).

**Comment by jskeet** [comment]
Java now allows the option of formatting with indentation. That would be nice to have too... both of these are non-urgent though.

**Comment by jskeet** [comment]
Due to multi-line formatting, the field values are hard to tell - but in Java a list is indeed formatted as `[1, 2, 3]` with no space before the first element or after the last element.

**Comment by jskeet** [comment]
And the current C# behaviour is shown in a test:

```csharp
AssertJson("{ 'repeatedInt32': [ 1, 2, 3, 4, 5 ] }",
    JsonFormatter.Default.Format(new TestAllTypes { RepeatedInt32 = { 1, 2, 3, 4, 5 } }));
```

**Comment by gvaish** [comment]
So, what's the verdict?

1. Don't have leading / training whitespace by default, and
2. Allow _formatting with indentation_ option?

**Comment by gvaish** [comment]
And I assume, it impacts `JsonFormatter::ToDiagnosticString()`. Am I right?

**Comment by jskeet** [comment]
To be honest, I'm not particularly tempted to make any changes at this point. I don't want to add a "formatting with indentation" option at this point, although it could be added in a minor version. The result is readable enough as it is, IMO.

**Comment by jskeet** [comment]
Closing this for now - I don't expect to want to change this before GA.
