### ISSUE TITLE
MSVS 2015 - stubs/common.h trivial warning at default warning level

### ISSUE THREAD

**Issue by mintyc** [google/protobuf#865]
So close to no warnings at default level in user code using the lib in C++. Not talking about building the lib. (beta-1 / head)

src/google/protobuf/stubs/common.h

line 149: Add static_cast to avoid warning
```
inline bool IsStructurallyValidUTF8(const std::string& str) {
  return IsStructurallyValidUTF8(str.data(), static_cast<int>(str.length()));
}
```

**Comment by xfxyjwf** [comment]
Fixed now.
