### ISSUE TITLE
cpp-3.0.0-beta-1 Visual Studio 11 2012 error C2977: 'std::tuple' : too many template arguments

### ISSUE THREAD

**Issue by james-cxx** [google/protobuf#870]
First, kudos on the move the CMake for generating Visual Studio solutions.  Very nice!

When generating for "Visual Studio 11 2012 Win64", the following five projects fail to build (C2977) because there are "too many template arguments":
- gmock
- gmock_main
- lite-arena-test
- test_plugin
- tests

This can be addressed by adding `_VARIADIC_MAX=10` to the Preprocessor Definitions of these projects.  Maybe this could be done with some special-casing in the CMakeLists.txt files. A mention of this in the README.md would be a good stop-gap.

**Comment by TeBoring** [comment]
Close this for clean up. Feel free to reopen the issue if there is still problem.

**Comment by haberman** [comment]
I think @TeBoring meant to close this issue.
