### ISSUE TITLE
竟然不原生支持Golang，可笑

### ISSUE THREAD

**Issue by CaiCQ** [google/protobuf#873]
按道理都是Google团体成员的项目，却加入了这么多其他语言美对Golang的支持，是内部混乱还是说明什么问题呢！

**Comment by xfxyjwf** [comment]
Golang is officially supported and it's in the golang repo: https://github.com/golang/protobuf

(For those of you who don't speak Chinese: @CaiCQ is complaining why there isn't official golang support for protobuf.)

**Comment by CaiCQ** [comment]
I think I write English more and more people don't understand.
