### ISSUE TITLE
Python - controlling indent for json.dumps

### ISSUE THREAD

**Issue by mhahn** [google/protobuf#897]
an `indent` of 2 is hardcoded:

https://github.com/google/protobuf/blob/master/python/google/protobuf/json_format.py#L83

this should be a kwarg to MessageToJson so it can be disabled if the user doesn't need indenting.

**Comment by jeromekelleher** [comment]
+1 --- I was just about to open an issue for this very problem!

**Comment by anandolee** [comment]
Have added the support in internal code
