### ISSUE TITLE
Python code generator option to generate relative imports

### ISSUE THREAD

**Issue by virtuald** [google/protobuf#90]
Using protoc 2.6.0 installed on OSX via brew, other _pb2.py files are imported like so:

```
import file_pb2
```

The project I'm working on sticks the protobuf generated files as a subpackage of its main python package, which seems like a pretty reasonable thing to do. Because those packages use relative imports, I'd like a protobuf option that generates this instead:

```
from . import file_pb2
```

This may be related to #7 (or solved there), as I'm using python 3 and I believe that is when python starts being picky about absolute/relative imports.

**Comment by jleclanche** [comment]
Confirming the issue. Using relative imports solves it and should work fine on 2.7.

**Comment by acozzette** [comment]
Let me close this issue since it appears that it duplicates #1491 and most of the discussion is happening on that issue.
