### ISSUE TITLE
c# support for .Net 3.0

### ISSUE THREAD

**Issue by Extrawurst** [google/protobuf#902]
Is it (will it be) possible to use with C# .Net 3.0 ? This is the version of C# that is supported by Unity and using protobuf there is a pretty big usecase.

**Comment by jtattermusch** [comment]
https://github.com/google/protobuf/issues/644

**Comment by jskeet** [comment]
Yup, this is a dupe of #644. Will close this one to leave all discussion there.

**Comment by ChenFengPa** [comment]
in this github have a batch surport ,net3.5 in unity https://github.com/bitcraftCoLtd/protobuf3-for-unity
