### ISSUE TITLE
protobuf 3 beta fails to compile using clang and libc++ on Ubuntu

### ISSUE THREAD

**Issue by whatsinthemicrowave** [google/protobuf#910]
$ export CXX='clang++'
$ export CXXFLAGS='-std=c++1y -stdlib=libc++'
$ export LDFLAGS='-stdlib=libc++ -lc++ -lc++abi'
$ ./configure
$ make 
...
libtool: compile:  clang++ -DHAVE_CONFIG_H -I. -I.. -pthread -DHAVE_PTHREAD=1 -Wall -Wwrite-strings -Woverloaded-virtual -Wno-sign-compare -std=c++1y -stdlib=libc++ -MT google/protobuf/map_field.lo -MD -MP -MF google/protobuf/.deps/map_field.Tpo -c google/protobuf/map_field.cc  -fPIC -DPIC -o google/protobuf/.libs/map_field.o
In file included from google/protobuf/map_field.cc:31:
In file included from ./google/protobuf/map_field.h:40:
In file included from ./google/protobuf/map_field_lite.h:34:
./google/protobuf/map.h:550:12: error: static_cast from 'const google::protobuf::MapKey *' to 'void *' is not allowed
...

**Comment by iphydf** [comment]
```cpp
google/protobuf/map.h:554:12: error: static_cast from 'const
      std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > *' to 'void *'
      is not allowed
      new (static_cast<void*>(p)) NodeType(std::forward<Args>(args)...);
           ^~~~~~~~~~~~~~~~~~~~~
[...]
test.cc:635:19: note: in instantiation of member function
      'google::protobuf::internal::MapField<std::__1::basic_string<char, std::__1::char_traits<char>,
      std::__1::allocator<char> >, im::tox::tox4j::impl::jni::proto::Value,
      google::protobuf::internal::WireFormatLite::FieldType::TYPE_STRING,
      google::protobuf::internal::WireFormatLite::FieldType::TYPE_MESSAGE, 0>::size' requested here
  return members_.size();
```

The root of the instantiation is:
```cpp
inline int Struct::members_size() const {                                                                 
  return members_.size();                                                                                 
}
```

`members_` is:
```cpp
::google::protobuf::internal::MapField<
      ::std::string, ::im::tox::tox4j::impl::jni::proto::Value,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE,
      0 > members_
```

And `Value` is another message class.

**Comment by TeBoring** [comment]
Feel free to reopen if there is still problem.
