### ISSUE TITLE
System.Security.VerificationException when instantiating MessageParser with code coverage on.

### ISSUE THREAD

**Issue by jtattermusch** [google/protobuf#911]
I was trying to generate code coverage using dotCover, and it looks like that MessageParser constructor throws VerificationException when code coverage is on (dotCover seems to use some additional security settings). Without dotCover, all the code runs without any problem.

I see this problem when instantiating all message classes, and the line throwing the exception is 
```
public sealed partial class Empty : pb::IMessage<Empty> {
    private static readonly pb::MessageParser<Empty> _parser = new pb::MessageParser<Empty>(() => new Empty());
```

Full stack trace:
```
System.TypeInitializationException: The type initializer for 'Math.DivArgs' threw an exception. ---> System.Security.VerificationException: Operation could destabilize the runtime.
   at Google.Protobuf.MessageParser`1..ctor(Func`1 factory)
   at Math.DivArgs..cctor() in c:\Users\jtattermusch\github\grpc\src\csharp\Grpc.Examples\Math.cs:line 52
   --- End of inner exception stack trace ---
   at Math.DivArgs..ctor()
   at Math.Tests.MathClientServerTest.Div1() in c:\Users\jtattermusch\github\grp
c\src\csharp\Grpc.Examples.Tests\MathClientServerTests.cs:line 55
```

**Comment by jtattermusch** [comment]
@jskeet FYI

**Comment by jskeet** [comment]
My guess is that actually, dotCover is adding extra IL (for the sake of coverage) which is invalid in this particular case. There's a similar report here: https://gitter.im/structuremap/structuremap/archives/2015/09/09

Possibly worth talking to JetBrains?

**Comment by jtattermusch** [comment]
https://youtrack.jetbrains.com/issue/DCVR-7708

**Comment by ww898** [comment]
@jtattermusch Sorry for the bug. Could you please to try last dotCover EAP version? Probably I had fixed it as https://youtrack.jetbrains.com/issue/PROF-395.

**Comment by jskeet** [comment]
@jtattermusch Can this be closed now? Does the latest dotCover fix the issue?

**Comment by ww898** [comment]
The issue was fixed
