### ISSUE TITLE
ReadOnly naming convention

### ISSUE THREAD

**Issue by yeison** [google/protobuf#918]
Instead of using the ReadOnly naming convention for the read only interfaces.

i.e. 
Interface ReadOnlyMessage
    -class Message implements ReadOnlyMessage

Doesn't it make more sense to name the implementing class Mutable?

i.e.

Interface Message
    -class MutableMessage implements Message

The reason I think this makes more sense is the following.  It's easier to replace existing (non-nano) protobuf types.  The non-nano protobuf types will already be immutable in one's code, it makes more sense for the name to be preserved for the immutable type.  That is to say, the behavior should be preserved with the name.  The new type will have the differing Mutable* prefix, and also the corresponding different behavior.

Secondly, it's more important to explicitly recognize the mutable types.

Third, the "is a" relationship is violated by the existing naming convention/inheritance.  Using the example above, the 'Message' type is not Read-Only in its behavior.

For example a method with the following signature might assume that the message it's receiving is read-only.  However it can still accept a Message type that is in fact mutable.  The data on that message type might have changed without the knowledge of the method's author who might have assumed, due to its name, that the message was immutable.

```
public static void doStuff(ReadOnlyMessage m)
```

**Comment by xfxyjwf** [comment]
Not sure what language are you talking about, but regarding the naming convention of generated code, we won't change it any more (until we make another major release, like 4.0.0+).
