### ISSUE TITLE
Python - `clear_when_set_to_default` behavior

### ISSUE THREAD

**Issue by mhahn** [google/protobuf#919]
I'm curious about the behavior of `clear_when_set_to_default` when setting the value of a non-repeated, scalar field.

I understand that in proto3, default values have been dropped from being specified in the message, but I don't see why the value would be cleared if it was explicitly set to something in the code.

My interpretation of `ListFields` is that it's a list of all the fields that have been set. Now that seems to no longer be the case.

say I have something like the following proto:

```
syntax = "proto3";

enum ContactMethodType {
    CELL_PHONE = 0;
    EMAIL = 1;
}

message ContactMethod {
    ContactMethodType contact_method_type = 1;
    string value = 2;
}
```

which results in the following behavior:
```
contact_method = ContactMethod(value=2, contact_method_type=0)
# ListFields() will only return 1 field since we're using the default
assert len(contact_method.ListFields(), 1)
contact_method.contact_method_type = 1
# ListFields() will now return 2 fields since we're no longer using the default
assert len(contact_method.ListFields(), 2)
# setting back to 0 will clear the field
contact_method.contact_method_type = 0
assert len(conact_method.ListFields(), 1)
```

that seems overly aggressive to me. what is the new definition of `ListFields`? 

I came across this because I use: https://github.com/benhodgson/protobuf-to-dict/blob/master/src/protobuf_to_dict.py#L42, which no longer generates a dictionary with enum values if they're set to the default.

If this is the desired behavior, is there another way to list all of the message field types so I could construct the dictionary (with default enum values included)?

The only way I can see from the message is iterating over all attributes that are lowercase and don't start with a "_".

**Comment by mhahn** [comment]
re: listing field types, I now see that I could just use `DESCRIPTOR`

**Comment by xfxyjwf** [comment]
@mhahn yes, instead of ListFields() you will need to iterate through all fields in the descriptor. It might be possible to change the protobuf_to_dict.py to do this for proto3 be default and use ListFields() for proto2 only.

**Comment by mhahn** [comment]
Just out of curiosity, what is the reasoning behind clearing the field when
it's set to the default?

**Comment by xfxyjwf** [comment]
@mhahn because in proto3 has_bits has been dropped so there is no way to distinguish between a field not set and a field set to default. Therefore assigning a field to default has the same effect as making it not set.

**Comment by mhahn** [comment]
Interesting, thanks!

**Comment by mhahn** [comment]
@xfxyjwf would you be open to accepting a PR to add `to_dict` within the protobuf library? maybe something similar to `json_format`?

**Comment by xfxyjwf** [comment]
@mhahn please check with Python proto owners @haberman @anandolee
