### ISSUE TITLE
JavaNano JsonFormat Compatibility

### ISSUE THREAD

**Issue by yeison** [google/protobuf#921]
How do I print a JavaNano object as json?  I noticed that the JsonFormat static methods do not support the MessageNano type.

**Comment by xfxyjwf** [comment]
Currently there is no plan to support JSON in JavaNano (or JavaLite, Objective-C). This general impression we have about mobile platforms is that code size matters a lot and JSON support adds too much to it while not being very useful compared to binary format we already support.

**Comment by yeison** [comment]
Okay, thanks.
