### ISSUE TITLE
Add a recursion limit for JSON parsing

### ISSUE THREAD

**Issue by jskeet** [google/protobuf#932]

**Comment by jtattermusch** [comment]
@xfxyjwf  can you please rate importance of this one? Do other languages have support?

**Comment by xfxyjwf** [comment]
I think this is an important security fix needed to protect sever from malicious inputs. We have such recursion limits when parsing proto binary data, and for JSON we'd better have the same protection as well.

**Comment by jskeet** [comment]
Sure - shouldn't be hard to do, so long as we don't mind a few off-by-one inconsistencies around wrapper types etc. (Basically there may be cases where our counting isn't precise, for the sake of convenience - but that's very unlikely to be an issue.)

Will do this when the initial PR has landed.
