### ISSUE TITLE
Consider allowing ToString to be "overridden" in partial classes

### ISSUE THREAD

**Issue by jskeet** [google/protobuf#933]
If we view ToString() as effectively diagnostic (so no protobuf library code depends on it - something we'd need to validate) then it might make sense in some cases to allow the generated code to have a specialized ToString implementation via a partial class.

This could be achieved as documented here:
http://codeblog.jonskeet.uk/2015/07/27/sideways-overriding-with-partial-methods/

Not sure whether it's a good idea or not, but it's been requested.

**Comment by lostindark** [comment]
An alternative solution is introduce a base class and put the default ToString implementation there.
Maybe this is a overkill for just implementation ToString, but it is a simpler and clear solution.

**Comment by jskeet** [comment]
I'd rather not have a base class if at all possible. Aside from anything else, without a Protobuf-specific base class, users can provide their own base class. But yes, it's at least an option.

**Comment by jskeet** [comment]
Thinking about it further, this is trickier than I thought - because I suspect we want this to be recursive, i.e. if I have a `Person` containing an `Address`, and `Address` has funky formatting, then I probably want to get that when I call `ToString()` on `Person`.

**Comment by jskeet** [comment]
Here's another suggestion:

- Introduce a new interface, call it `IFoo` for now, with a method `ToDiagnosticString`
- `ToString` always calls `JsonFormatter.ToDiagnosticString` (as per #afbc89a)
- That code notices when a message implements `IFoo`, and calls its `ToDiagnosticString` code instead of using normal JSON formatting
- We make `Any` implement `IFoo`, and make its `ToDiagnosticString` return the JSON "@type/@value" representation it does now - so it's just an example of the special case

It's a little convoluted, but works nicely with recursion.

Thoughts? // cc @jtattermusch

**Comment by lostindark** [comment]
The interface solution looks like a good candidate. Given this is only used for diagnostics, the additional interface check shouldn't cause any performance concern.

**Comment by jskeet** [comment]
Implemented now via ICustomDiagnosticMessage.
