### ISSUE TITLE
[python] upload alpha4 to pypi

### ISSUE THREAD

**Issue by mhahn** [google/protobuf#938]
https://pypi.python.org/pypi/protobuf

alpha 3.0.0a3 is the last version on pypi.

**Comment by kellrott** [comment]
Is there a pip one liner that I can use until a newer version is pushed? I tried:
```
pip install https://github.com/google/protobuf/releases/download/v3.0.0-beta-1/protobuf-python-3.0.0-alpha-4.tar.gz
```
But I got a 'setup.py doesn't exist', because its in the python subdirectory and not the base directory of the tarball.

**Comment by xfxyjwf** [comment]
The latest version on PyPi is now 3.0.0b2.
