### ISSUE TITLE
  Can not make install grpc in Centos 7 

### ISSUE THREAD

**Issue by bangph** [google/protobuf#946]
Hi,

I could not get over with this error when make install grpc in Centos 7, please help. I also make install protobuf before make and make install grpc but it not success. (make verify-install could not help also).

We couldn't find protoc 3.0.0+ installed on your system. While this
won't prevent grpc from working, you won't be able to compile
and run any meaningful code with it.

Please download and install protobuf 3.0.0+ from:

https://github.com/google/protobuf/releases

Once you've done so, or if you think this message is in error,
you can re-run this check by doing:

Here is protobuf in my system

[root@gonzo rasdaman]# ls -l /usr/local/lib | grep 'proto*'
-rw-r--r--. 1 root root 51965098 Nov 5 13:39 libprotobuf.a
-rwxr-xr-x. 1 root root 901 Nov 5 13:39 libprotobuf.la
-rw-r--r--. 1 root root 4306170 Nov 5 13:39 libprotobuf-lite.a
-rwxr-xr-x. 1 root root 916 Nov 5 13:39 libprotobuf-lite.la
lrwxrwxrwx. 1 root root 26 Nov 5 09:58 libprotobuf-lite.so -> libprotobuf-lite.so.10.0.0
lrwxrwxrwx. 1 root root 26 Nov 5 09:58 libprotobuf-lite.so.10 -> libprotobuf-lite.so.10.0.0
-rwxr-xr-x. 1 root root 1908482 Nov 5 09:58 libprotobuf-lite.so.10.0.0
lrwxrwxrwx. 1 root root 21 Nov 5 09:58 libprotobuf.so -> libprotobuf.so.10.0.0
lrwxrwxrwx. 1 root root 21 Nov 5 09:58 libprotobuf.so.10 -> libprotobuf.so.10.0.0
-rwxr-xr-x. 1 root root 20500151 Nov 5 09:58 libprotobuf.so.10.0.0
-rw-r--r--. 1 root root 86971888 Nov 5 13:39 libprotoc.a
-rwxr-xr-x. 1 root root 925 Nov 5 13:39 libprotoc.la
lrwxrwxrwx. 1 root root 19 Nov 5 09:58 libprotoc.so -> libprotoc.so.10.0.0
lrwxrwxrwx. 1 root root 19 Nov 5 09:58 libprotoc.so.10 -> libprotoc.so.10.0.0
-rwxr-xr-x. 1 root root 29639716 Nov 5 09:58 libprotoc.so.10.0.0

**Comment by xfxyjwf** [comment]
Hi @bangph, could you file the issue to grpc?
https://github.com/grpc/grpc

It's more likely to be a grpc problem than a protobuf one.

**Comment by bangph** [comment]
Hi, @xfxyjwf  

yes, I've done it but....I think both is from one Company and you are the provider so you should know why it is not work with another implemented platforms like grpc.

**Comment by xfxyjwf** [comment]
Could you link the grpc issue here? I can help ping the grpc guys if you do not receive a response from them.

**Comment by bangph** [comment]
@xfxyjwf Hi 

https://github.com/grpc/grpc/issues/4055 here you are, please go and tell them what is problem with my system (I followed your guide and their guide to install but it is always unsuccessful). Thanks.

**Comment by xfxyjwf** [comment]
Have you tried the solution posted by @js1990  in the grpc thread?

I'm closing this issue. Please follow up in the grpc thread.
