### ISSUE TITLE
Relativ to absolut import in python3 in new ptotobuf version 3.0.0 

### ISSUE THREAD

**Issue by aurelw** [google/protobuf#957]
This issue only concerns python3 generated code.

I have several message .pb files which i compile into python3 code. They all follow a package structure, "package myprotos.suba". There are several .pb files and corresponding modules, subBase, suba, subb. suba and subb import subBase. I now want to put all those generated python modules into one python package "myprotos". so i create "myprotos" directory, and add an empty **init**.py file.

Then in python code i should be able to do the following:

``` python
import myprotos
from myprotos import suba   # fails because suba is not in the path
```

However, this fails in the auto-generated module suba at the following statement:

``` python
import subBase
```

This is because python3 drops the support for these relative imports. A correctly generated code would look something like this:

``` python
import myprotos
from myprotos import subBase
```

Because the proto files already specifies package and subpackages it would be possible to generate an entire output directory with as a python package with working, cross-referencing imports.

**Comment by xdmiodz** [comment]
Hi,

Looks similar to #881 

In your `subb.proto` you can import `subBase.proto` like:

```
#subb.proto
import 'myprotos/subBase.proto'
```

In this case the generated file will import `subBase` properly.

**Comment by anandolee** [comment]
See  #1491 for discussion of relative imports
