### ISSUE TITLE
Google Protocol buffers in Qt5 Android Project

### ISSUE THREAD

**Issue by williamkibira** [google/protobuf#96]
Hello My name is William , and i am trying to build a C++ application with Protocol buffers but, i can't seem to get the application to package and x86 libprotobuf *so , i was wondering if someone can help me with a way to actually compile Google protobuf into A QtMobile C++ application for Arms , IOS and BlackBerry on building and packaging .

Thank you. Hope to here form you all soon.

**Comment by rohansurya** [comment]
@williamkibira 
Hi, I too am facing the same issues as you did. It would be really helpful if you have some tutorial on the same.

**Comment by williamkibira** [comment]
Ow, hello. Hope ur doing ok. I assume ur using a linux environment and
Androids Native Development Kit. Inside the source code for protobuf 2.5
there is a build file that can be used to build for the architectures mips
, x86, arms and arms7. I will try to make a pdf guide for you to do this.
Then show you how to let QT5 package and link to the right apk for each
architecture.

**Comment by rohansurya** [comment]
Hi...I am using windows environment.

**Comment by williamkibira** [comment]
Never used windows before. Can i give you prebuilt libraries instead ?

**Comment by rohansurya** [comment]
Hmmm...a pdf guide (Linux environment) would be helpful. I can try to relate it.

**Comment by williamkibira** [comment]
Ok then.

**Comment by williamkibira** [comment]
Tomorrow about the time you contacted me, i will  send you a pdf. This time
, showing what i did but, for windows. There is no.  Big difference in the
ndk use in Linux and other OSes. Sorry for the delay.

**Comment by rohansurya** [comment]
Sure I will. That would be really helpful. Thank you :)

**Comment by williamkibira** [comment]
Here is a link to a set of pre-built libraries in case you feel a bit too
lazy to build them up yourself.

https://drive.google.com/file/d/0B4YBVeioVfpPRlR2QWNaVW5FWGs/view?usp=sharing

**Comment by rohansurya** [comment]
Thank you for the link. But a pdf guide will be really helpful as I want to build them.

**Comment by williamkibira** [comment]
There is a pdf attached to that email. Check properly

**Comment by rohansurya** [comment]
Sorry my mistake! But I am unable to access that link

**Comment by williamkibira** [comment]
Ow , i see, let me try to easy it a bit

**Comment by williamkibira** [comment]
You should have access now.

**Comment by rohansurya** [comment]
Sorry for the delayed response. I am able to access the link now but I do not see any pdf attached. Could you please check.

**Comment by williamkibira** [comment]
Can you access the libraries now ?

**Comment by rohansurya** [comment]
Hi,

I am unable to access the libraries.

**Comment by williamkibira** [comment]
You have to use , your gmail, but if that is the case , you can give me
your gmail account and i pass them to you or i can use drop box instead.

**Comment by williamkibira** [comment]
https://www.dropbox.com/s/3b7oegcnn7mxw48/libs.tar.7z?dl=0

**Comment by rohansurya** [comment]
Hi William,
I am still not able to access the libraries. A guide to compile protobuf for android would be really helpful.

**Comment by williamkibira** [comment]
That is what was contained in the pdf, it shows how you can compile the
libraries with android native development kit in windows.

**Comment by mohabouje** [comment]
@williamkibira 
Can you share an explication about how to integrate protocol buffer with Qt for Android?
If you have an repository with an example or a pdf, please send it to me.
mohabouje@gmail.com
Thank you.

**Comment by williamkibira** [comment]
Hello Mohabouje , sorry its been a while since i have had to do anything with Protobuf but, i think its a lot easier now than it was back then .

First of all protobuf has build integration with cmake now , on the other hand the actual static or dynamic libraries can be built with the information in these scripts.

https://gist.github.com/helayzhang/9034454 and https://github.com/julienr/protobuf-android , the resulting libraries can simply be linked into your Qt Android project .

This is old information , i would probably do it some other way at this point but, like i said its been a while .
