### ISSUE TITLE
gcc-5.2 {PROJECT}.pb.cc.o undefined reference to symbol '_ZN6google8protobuf2io16CodedInputStream20ReadVarint64FallbackEv' CPP

### ISSUE THREAD

**Issue by KilicY** [google/protobuf#967]
With gcc 5.2 i get this error

`/usr/bin/ld: PROJECT.pb.cc.o undefined reference to symbol _ZN6google8protobuf2io16CodedInputStream20ReadVarint64FallbackEv'>
/usr/lib/libprotobuf.so.10: error adding symbols: DSO missing from command line
`

I use cmake with the pkg-config module to build my application. When I build the Project on another machine with gcc-4.9 there is no Problem.

I install protobuf and grpc with gcc-5.2. I am running the project on Ubuntu 14.10

I reinstalled protobuf and grpc after cleaning up the old installation but the issue remains

**Comment by TeBoring** [comment]
Close this for clean up. Feel free to reopen it if there is still problem.

**Comment by jamierpond** [comment]
Also hitting a similar issue right now..
