### ISSUE TITLE
protoc binary distributed in maven central requires external dynamic libs

### ISSUE THREAD

**Issue by pranasblk** [google/protobuf#969]
Would it be possible to have self contained binaries with static linking?
Currently I am running protoc linux binary on very restrictive environment and getting error message about missing ```/lib64/libc.so.6``` (```GLIBC_2.14```) for the com.google.protobuf:protoc:2.6.1 ...

**Comment by xfxyjwf** [comment]
@zhangkun83 to help take a look.

**Comment by zhangkun83** [comment]
What's the linux version you are running?

**Comment by pranasblk** [comment]
Red Hat Enterprise 6.6

**Comment by zhangkun83** [comment]
I am pushing a new build for 2.6.1 that depends on lower version of GLIBC and will work on RHEL 6.6.
The version is `2.6.1-build2`. It's in staging repo now.
@pranasblk can you (temporarily) add `https://oss.sonatype.org/content/repositories/comgoogle-1077/` to your repos and see if the new version works on your system?

**Comment by pranasblk** [comment]
Thanks a bunch!

**Comment by zhangkun83** [comment]
I have pushed `2.6.1-build2` to Maven Central.
