### ISSUE TITLE
.NET Nuget package does not include protoc.exe

### ISSUE THREAD

**Issue by ashern** [google/protobuf#972]
The readme says that protoc will be included in the package directory, but the only file present is Google.Protobuf.dll in the lib/net40 directory.

**Comment by jtattermusch** [comment]
Are you sure you are using the right package? 
https://www.nuget.org/packages/Google.Protobuf/

**Comment by MeirionHughes** [comment]
../packages\Google.Protobuf.3.0.0-alpha4\tools\protoc.exe
