### ISSUE TITLE
No has_email() in the tutorial

### ISSUE THREAD

**Issue by antran89** [google/protobuf#992]
Hi all,
Recently, I read the tutorial on how to use [Protobuf in C++](https://developers.google.com/protocol-buffers/docs/cpptutorial). However, the tutorial writing is not the same as the [example](https://github.com/google/protobuf/tree/master/examples) provided in the repo that cloned from Github.
In particular, there is no `has_` method for the `email` field. I also checked the generated code from Google Protobuf, there is no `has_email()` method.

```
if (person.has_email()) {
      cout << "  E-mail address: " << person.email() << endl;
}

```

Thanks,

**Comment by xfxyjwf** [comment]
The tutorial was written for proto2 but the example has been updated to proto3 some time ago. There is no has method in proto3. We should update the tutorial to proto3 as well.

**Comment by xfxyjwf** [comment]
Removed from the fixit backlog. Created https://github.com/google/protobuf/issues/4035 for this cleanup instead.
