### ISSUE TITLE
Question: Would a plugin refactor/PR to allow for custom CLI options be considered?

### ISSUE THREAD

**Issue by steckel** [google/protobuf#996]
After some investigation I've found that the plugin pattern does not allow for custom cli options be passed (e.g. `protoc --plugin=protoc-gen-foo --foo_out=tmp --foo_opt=baz ...` `--foo_opt` is disallowed).

```cpp
// main.cc
FooGenerator foogenerator;
return google::protobuf::compiler::PluginMain(argc, argv, &foogenerator);
```

Compared to when registering on the `google::protobuf::compiler::CommandLineInterface` instance.

```cpp
// main.cc
FooGenerator foogenerator;
google::protobuf::compiler::CommandLineInterface cli;
cli.RegisterGenerator("--foo_out", "--foo_opt", &foogenerator, "Generate Foo.");
```

Unless I am mistaken and the `cli` instance is available to the plugins in some way (I would prefer hearing that this is true), it seems that this would discourage the plugin pattern from being adopted compared to third parties redistributing protoc with their own cli instance.

Would a small refactor that allows the `PluginMain` function or `Generator` declare it's cli command lines be a welcomed change? Would a pull request be welcomed?

**Comment by xfxyjwf** [comment]
You don't actually need --foo_opt to pass CLI options to the plugin. You might get the idea of --foo_opt from --cpp_opt, but that thing was added for a different reason (we probably shouldn't have it opensourced...). The following two are equivalent:
```bash
$ protoc --cpp_out=tmp --cpp_opt=a=b,c=d
```
```bash
$ protoc --cpp_out=a=b,c=d:tmp
```

So for plugins, just pass the options in --foo_out:
```bash
$ protoc --foo_out=baz,quz:tmp
```

**Comment by steckel** [comment]
:clap: Thank you!
