### ISSUE TITLE
Objective-c: Please consider keeping the original bytes buffer and delaying malloc for string field

### ISSUE THREAD

**Issue by zhihuawensc** [google/protobuf#999]
Recently we found if most of our fields are String, deserializing using protocol buffer is sometimes slower than JSON.

Further investigation shows it is because there are many small memory allocations for String fields at https://github.com/google/protobuf/blob/24fe6ba750bf8a247d41fc589460dce1bdd697a1/objectivec/GPBCodedInputStream.m#L626.

Please consider adding an option while parsing the Proto buffer bytes array so that the malloc for String fields can be delayed until they are being accessed, it probably will be more performant if most the fields are String.

We know FlatBuffer is doing sth similar to this idea where the original buffer is always kept and all the unpacking is done in accessing time.

**Comment by thomasvl** [comment]
I'm going to close this out as the implementation has now changes and there is no longer a malloc and we are instead directly creating native NSStrings, so we don't have control over what it does internally for allocations.
